CasADi: casadi::SerializingStream Class Reference
casadi::SerializingStream Class Reference
Helper class for Serialization.
#include <serializing_stream.hpp>
Detailed Description
Author
Joris Gillis
Date
2018
Extra doc: https://github.com/casadi/casadi/wiki/L_ao
Definition at line 205 of file serializing_stream.hpp.
Public Member Functions
SerializingStream (std::ostream &out)
Constructor.
SerializingStream (std::ostream &out, const Dict &opts)
void pack (const Sparsity &e)
Serializes an object to the output stream.
void pack (const MX &e)
void pack (const SXElem &e)
void pack (const Linsol &e)
template<class T >
void pack (const Matrix< T > &e)
void pack (const Function &e)
void pack (const Importer &e)
void pack (const Slice &e)
void pack (const GenericType &e)
void pack (std::istream &s)
void pack (int e)
void pack (bool e)
void pack (casadi_int e)
void pack (size_t e)
void pack (double e)
void pack (const std::string &e)
void pack (char e)
template<class T >
void pack (const std::vector< T > &e)
template<class K , class V >
void pack (const std::map< K, V > &e)
template<class A , class B >
void pack (const std::pair< A, B > &e)
template<class T >
void pack (const std::string &descr, const T &e)
template<class T >
void pack (const std::string &descr, T &e)
void version (const std::string &name, int v)
void connect (DeserializingStream &s)
void reset ()
Friends
class DeserializingStream
Constructor & Destructor Documentation
SerializingStream() [1/2]
casadi::SerializingStream::SerializingStream (std::ostream & out)
Definition at line 70 of file serializing_stream.cpp.
                                                           :
       SerializingStream(out_s, Dict()) {
     }
SerializingStream() [2/2]
casadi::SerializingStream::SerializingStream (std::ostream & out, const Dict & opts)
Definition at line 74 of file serializing_stream.cpp.
                                                                             :
         out(out_s), debug_(false) {
       // Sanity check
       pack(serialization_check);
       // API version check
       pack(casadi_int(serialization_protocol_version));
       bool debug = false;
       // Read options
       for (auto&& op : opts) {
         if (op.first=="debug") {
           debug = op.second;
         } else {
           casadi_error("Unknown option: '" + op.first + "'.");
         }
       }
       pack(debug);
       debug_ = debug;
     }
References pack(), casadi::serialization_check, and casadi::serialization_protocol_version.
Member Function Documentation
connect()
void casadi::SerializingStream::connect (DeserializingStream & s)
Definition at line 395 of file serializing_stream.cpp.
{
     nodes_ = &s.nodes_;
   }
pack() [1/22]
void casadi::SerializingStream::pack (bool e)
Definition at line 163 of file serializing_stream.cpp.
{
       decorate('b');
       pack(static_cast<char>(e));
     }
References pack().
pack() [2/22]
void casadi::SerializingStream::pack (casadi_int e)
Definition at line 117 of file serializing_stream.cpp.
{
       decorate('J');
       int64_t n = e;
       const char* c = reinterpret_cast<const char*>(&n);
       for (int j=0;j<8;++j) pack(c[j]);
     }
References pack().
pack() [3/22]
void casadi::SerializingStream::pack (char e)
Definition at line 177 of file serializing_stream.cpp.
{
       unsigned char ref = 'a';
       // Note: outputstreams work neatly with std::hex,
       // but inputstreams don't
       out.put(ref + (reinterpret_cast<unsigned char&>(e) % 16));
       out.put(ref + (reinterpret_cast<unsigned char&>(e) >> 4));
     }
pack() [4/22]
void casadi::SerializingStream::pack (const Function & e)
Definition at line 233 of file serializing_stream.cpp.
{
       decorate('F');
       shared_pack(e);
     }
pack() [5/22]
void casadi::SerializingStream::pack (const GenericType & e)
Definition at line 263 of file serializing_stream.cpp.
{
       decorate('G');
       shared_pack(e);
     }
pack() [6/22]
void casadi::SerializingStream::pack (const Importer & e)
Definition at line 243 of file serializing_stream.cpp.
{
       decorate('M');
       shared_pack(e);
     }
pack() [7/22]
void casadi::SerializingStream::pack (const Linsol & e)
Definition at line 253 of file serializing_stream.cpp.
{
       decorate('L');
       shared_pack(e);
     }
pack() [8/22]
template<class T > void casadi::SerializingStream::pack (const Matrix< T > & e) inline
Definition at line 221 of file serializing_stream.hpp.
{
       e.serialize(*this);
     }
References casadi::Matrix< Scalar >::serialize().
pack() [9/22]
void casadi::SerializingStream::pack (const MX & e)
Definition at line 223 of file serializing_stream.cpp.
{
       decorate('X');
       shared_pack(e);
     }
pack() [10/22]
void casadi::SerializingStream::pack (const Slice & e)
Definition at line 301 of file serializing_stream.cpp.
{
       decorate('S');
       e.serialize(*this);
     }
References casadi::Slice::serialize().
pack() [11/22]
void casadi::SerializingStream::pack (const Sparsity & e)
Extra doc: https://github.com/casadi/casadi/wiki/L_ap
Definition at line 213 of file serializing_stream.cpp.
{
       decorate('S');
       shared_pack(e);
     }
Referenced by casadi::XFunction< DerivedType, MatType, NodeType >::delayed_serialize_members(), pack(), casadi::Function::serialize(), casadi::GenericType::serialize(), casadi::Slice::serialize(), casadi::Sparsity::serialize(), casadi::SXNode::serialize(), casadi::GenericTypeInternal< ID, T >::serialize(), casadi::Conic::serialize(), casadi::Convexify::serialize(), casadi::ProtoFunction::serialize_body(), casadi::ImporterInternal::serialize_body(), casadi::MXNode::serialize_body(), casadi::Assertion::serialize_body(), casadi::BinaryMX< ScX, ScY >::serialize_body(), casadi::BSplineCommon::serialize_body(), casadi::BSpline::serialize_body(), casadi::Call::serialize_body(), casadi::Low::serialize_body(), casadi::Conic::serialize_body(), casadi::ConstantDM::serialize_body(), casadi::ConstantFile::serialize_body(), casadi::External::serialize_body(), casadi::FunctionInternal::serialize_body(), casadi::GetNonzerosVector::serialize_body(), casadi::GetNonzerosSlice::serialize_body(), casadi::GetNonzerosSlice2::serialize_body(), casadi::GetNonzerosSliceParam::serialize_body(), casadi::GetNonzerosParamSlice::serialize_body(), casadi::Integrator::serialize_body(), casadi::FixedStepIntegrator::serialize_body(), casadi::Interpolant::serialize_body(), casadi::IOInstruction::serialize_body(), casadi::LinsolInternal::serialize_body(), casadi::Map::serialize_body(), casadi::MapSum::serialize_body(), casadi::Monitor::serialize_body(), casadi::OutputNode::serialize_body(), casadi::MXFunction::serialize_body(), casadi::Nlpsol::serialize_body(), casadi::OracleFunction::serialize_body(), casadi::HorzRepmat::serialize_body(), casadi::HorzRepsum::serialize_body(), casadi::Rootfinder::serialize_body(), casadi::SetNonzerosVector< Add >::serialize_body(), casadi::SetNonzerosSlice< Add >::serialize_body(), casadi::SetNonzerosSlice2< Add >::serialize_body(), casadi::SetNonzerosParamSlice< Add >::serialize_body(), casadi::SetNonzerosSliceParam< Add >::serialize_body(), casadi::LinsolCall< Tr >::serialize_body(), casadi::Split::serialize_body(), casadi::Switch::serialize_body(), casadi::SXFunction::serialize_body(), casadi::SymbolicMX::serialize_body(), casadi::UnaryMX::serialize_body(), casadi::XFunction< DerivedType, MatType, NodeType >::serialize_body(), casadi::Blocksqp::serialize_body(), casadi::BonminInterface::serialize_body(), casadi::CbcInterface::serialize_body(), casadi::ClpInterface::serialize_body(), casadi::CplexInterface::serialize_body(), casadi::GurobiInterface::serialize_body(), casadi::HighsInterface::serialize_body(), casadi::IpoptInterface::serialize_body(), casadi::KnitroInterface::serialize_body(), casadi::LapackLu::serialize_body(), casadi::LapackQr::serialize_body(), casadi::MumpsInterface::serialize_body(), casadi::OoqpInterface::serialize_body(), casadi::OsqpInterface::serialize_body(), casadi::ProxqpInterface::serialize_body(), casadi::QpoasesInterface::serialize_body(), casadi::SnoptInterface::serialize_body(), casadi::CvodesInterface::serialize_body(), casadi::IdasInterface::serialize_body(), casadi::SundialsInterface::serialize_body(), casadi::SuperscsInterface::serialize_body(), casadi::WorhpInterface::serialize_body(), casadi::BSplineInterpolant::serialize_body(), casadi::Collocation::serialize_body(), casadi::FastNewton::serialize_body(), casadi::Feasiblesqpmethod::serialize_body(), casadi::Ipqp::serialize_body(), casadi::LinearInterpolant::serialize_body(), casadi::LinsolLdl::serialize_body(), casadi::LinsolQr::serialize_body(), casadi::Newton::serialize_body(), casadi::QpToNlp::serialize_body(), casadi::Qrqp::serialize_body(), casadi::Sqpmethod::serialize_body(), casadi::SymbolicQr::serialize_body(), casadi::BinarySX::serialize_node(), casadi::RealtypeSX::serialize_node(), casadi::IntegerSX::serialize_node(), casadi::ZeroSX::serialize_node(), casadi::OneSX::serialize_node(), casadi::MinusOneSX::serialize_node(), casadi::InfSX::serialize_node(), casadi::MinusInfSX::serialize_node(), casadi::NanSX::serialize_node(), casadi::SymbolicSX::serialize_node(), casadi::UnarySX::serialize_node(), casadi::RuntimeConst< T >::serialize_type(), casadi::ImporterInternal::serialize_type(), casadi::MXNode::serialize_type(), casadi::PluginInterface< Derived >::serialize_type(), casadi::BinaryMX< ScX, ScY >::serialize_type(), casadi::BSpline::serialize_type(), casadi::BSplineParametric::serialize_type(), casadi::ConstantDM::serialize_type(), casadi::ConstantFile::serialize_type(), casadi::ZeroByZero::serialize_type(), casadi::Constant< Value >::serialize_type(), casadi::GenericExternal::serialize_type(), casadi::FunctionInternal::serialize_type(), casadi::GetNonzerosVector::serialize_type(), casadi::GetNonzerosSlice::serialize_type(), casadi::GetNonzerosSlice2::serialize_type(), casadi::GetNonzerosParamVector::serialize_type(), casadi::GetNonzerosSliceParam::serialize_type(), casadi::GetNonzerosParamSlice::serialize_type(), casadi::GetNonzerosParamParam::serialize_type(), casadi::Map::serialize_type(), casadi::MapSum::serialize_type(), casadi::Multiplication::serialize_type(), casadi::DenseMultiplication::serialize_type(), casadi::Project::serialize_type(), casadi::Densify::serialize_type(), casadi::Sparsify::serialize_type(), casadi::SetNonzerosVector< Add >::serialize_type(), casadi::SetNonzerosSlice< Add >::serialize_type(), casadi::SetNonzerosSlice2< Add >::serialize_type(), casadi::SetNonzerosParamVector< Add >::serialize_type(), casadi::SetNonzerosParamSlice< Add >::serialize_type(), casadi::SetNonzerosSliceParam< Add >::serialize_type(), casadi::SetNonzerosParamParam< Add >::serialize_type(), casadi::Solve< Tr >::serialize_type(), casadi::Transpose::serialize_type(), casadi::DenseTranspose::serialize_type(), casadi::LinearInterpolant::serialize_type(), casadi::LinearInterpolantJac::serialize_type(), SerializingStream(), and version().
pack() [12/22]
template<class K , class V > void casadi::SerializingStream::pack (const std::map< K, V > & e) inline
Definition at line 243 of file serializing_stream.hpp.
{
       decorate('D');
       pack(static_cast<casadi_int>(e.size()));
       for (const auto & i : e) {
         pack(i.first);
         pack(i.second);
       }
     }
pack() [13/22]
template<class A , class B > void casadi::SerializingStream::pack (const std::pair< A, B > & e) inline
Definition at line 252 of file serializing_stream.hpp.
{
       decorate('p');
       pack(e.first);
       pack(e.second);
     }
pack() [14/22]
template<class T > void casadi::SerializingStream::pack (const std::string & descr, const T & e) inline
Definition at line 258 of file serializing_stream.hpp.
{
       if (debug_) pack(descr);
       pack(e);
     }
pack() [15/22]
template<class T > void casadi::SerializingStream::pack (const std::string & descr, T & e) inline
Definition at line 263 of file serializing_stream.hpp.
{
       if (debug_) pack(descr);
       pack(e);
     }
pack() [16/22]
void casadi::SerializingStream::pack (const std::string & e)
Definition at line 185 of file serializing_stream.cpp.
{
       decorate('s');
       int s = e.size();
       pack(s);
       const char* c = e.c_str();
       for (int j=0;j<s;++j) pack(c[j]);
     }
References pack().
pack() [17/22]
template<class T > void casadi::SerializingStream::pack (const std::vector< T > & e) inline
Definition at line 237 of file serializing_stream.hpp.
{
       decorate('V');
       pack(static_cast<casadi_int>(e.size()));
       for (auto&& i : e) pack(i);
     }
pack() [18/22]
void casadi::SerializingStream::pack (const SXElem & e)
Definition at line 311 of file serializing_stream.cpp.
{
       decorate('E');
       shared_pack(e);
     }
pack() [19/22]
void casadi::SerializingStream::pack (double e)
Definition at line 207 of file serializing_stream.cpp.
{
       decorate('d');
       const char* c = reinterpret_cast<const char*>(&e);
       for (int j=0;j<8;++j) pack(c[j]);
     }
References pack().
pack() [20/22]
void casadi::SerializingStream::pack (int e)
Definition at line 149 of file serializing_stream.cpp.
{
       decorate('i');
       int32_t n = e;
       const char* c = reinterpret_cast<const char*>(&n);
       for (int j=0;j<4;++j) pack(c[j]);
     }
References pack().
pack() [21/22]
void casadi::SerializingStream::pack (size_t e)
Definition at line 124 of file serializing_stream.cpp.
{
       decorate('K');
       uint64_t n = e;
       const char* c = reinterpret_cast<const char*>(&n);
       for (int j=0;j<8;++j) pack(c[j]);
     }
References pack().
pack() [22/22]
void casadi::SerializingStream::pack (std::istream & s)
Definition at line 273 of file serializing_stream.cpp.
{
       decorate('B');
       s.seekg(0, std::ios::end);
       size_t len = s.tellg();
       s.seekg(0, std::ios::beg);
       pack(len);
       char buffer[1024];
       for (size_t i=0;i<len;++i) {
         s.read(buffer, 1024);
         size_t c = s.gcount();
         for (size_t j=0;j<c;++j) {
           pack(buffer[j]);
         }
         if (s.rdstate() & std::ifstream::eofbit) break;
       }
     }
References pack().
reset()
void casadi::SerializingStream::reset ()
Definition at line 403 of file serializing_stream.cpp.
{
     shared_map_.clear();
   }
version()
void casadi::SerializingStream::version (const std::string & name, int v)
Definition at line 357 of file serializing_stream.cpp.
{
     pack(name+"::serialization::version", v);
   }
References pack().
Referenced by casadi::Convexify::serialize(), casadi::ProtoFunction::serialize_body(), casadi::ImporterInternal::serialize_body(), casadi::Conic::serialize_body(), casadi::External::serialize_body(), casadi::FunctionInternal::serialize_body(), casadi::Integrator::serialize_body(), casadi::FixedStepIntegrator::serialize_body(), casadi::ImplicitFixedStepIntegrator::serialize_body(), casadi::Interpolant::serialize_body(), casadi::MXFunction::serialize_body(), casadi::Nlpsol::serialize_body(), casadi::OracleFunction::serialize_body(), casadi::Rootfinder::serialize_body(), casadi::Switch::serialize_body(), casadi::SXFunction::serialize_body(), casadi::XFunction< DerivedType, MatType, NodeType >::serialize_body(), casadi::Blocksqp::serialize_body(), casadi::BonminInterface::serialize_body(), casadi::CbcInterface::serialize_body(), casadi::ClpInterface::serialize_body(), casadi::CplexInterface::serialize_body(), casadi::GurobiInterface::serialize_body(), casadi::HighsInterface::serialize_body(), casadi::HpipmInterface::serialize_body(), casadi::IpoptInterface::serialize_body(), casadi::KnitroInterface::serialize_body(), casadi::LapackLu::serialize_body(), casadi::MumpsInterface::serialize_body(), casadi::OoqpInterface::serialize_body(), casadi::OsqpInterface::serialize_body(), casadi::ProxqpInterface::serialize_body(), casadi::QpoasesInterface::serialize_body(), casadi::SnoptInterface::serialize_body(), casadi::CvodesInterface::serialize_body(), casadi::IdasInterface::serialize_body(), casadi::SundialsInterface::serialize_body(), casadi::SuperscsInterface::serialize_body(), casadi::WorhpInterface::serialize_body(), casadi::BSplineInterpolant::serialize_body(), casadi::Collocation::serialize_body(), casadi::FastNewton::serialize_body(), casadi::Feasiblesqpmethod::serialize_body(), casadi::Ipqp::serialize_body(), casadi::LinsolLdl::serialize_body(), casadi::LinsolQr::serialize_body(), casadi::Newton::serialize_body(), casadi::QpToNlp::serialize_body(), casadi::Qrqp::serialize_body(), casadi::RungeKutta::serialize_body(), casadi::Sqpmethod::serialize_body(), casadi::SymbolicQr::serialize_body(), casadi::GenericExternal::serialize_type(), casadi::LinearInterpolant::serialize_type(), and casadi::LinearInterpolantJac::serialize_type().
Friends And Related Function Documentation
DeserializingStream
friend class DeserializingStream friend
Definition at line 206 of file serializing_stream.hpp.
The documentation for this class was generated from the following files:
serializing_stream.hpp
serializing_stream.cpp