CasADi: Title
Title
Enumerations
enum casadi::RfpIn { casadi::RFP_X , casadi::RFP_P , casadi::RFP_NUM_IN }
Inputs of the symbolic representation of the rootfinding problem.
enum casadi::RfpOut { casadi::RFP_G , casadi::RFP_NUM_OUT }
Inputs of the symbolic representation of the rootfinding problem.
enum casadi::RootfinderInput { casadi::ROOTFINDER_X0 , casadi::ROOTFINDER_P , casadi::ROOTFINDER_NUM_IN }
Input arguments of a rootfinder.
enum casadi::RootfinderOutput { casadi::ROOTFINDER_X , casadi::ROOTFINDER_NUM_OUT }
Output arguments of a rootfinder.
Functions
Function casadi::rootfinder (const std::string &name, const std::string &solver, const SXDict &rfp, const Dict &opts)
Function casadi::rootfinder (const std::string &name, const std::string &solver, const MXDict &rfp, const Dict &opts)
Function casadi::rootfinder (const std::string &name, const std::string &solver, const Function &f, const Dict &opts)
std::vector< std::string > casadi::rootfinder_in ()
Get rootfinder input scheme.
std::vector< std::string > casadi::rootfinder_out ()
Get rootfinder output scheme.
std::string casadi::rootfinder_in (casadi_int ind)
Get rootfinder input scheme name by index.
std::string casadi::rootfinder_out (casadi_int ind)
Get rootfinder output scheme name by index.
casadi_int casadi::rootfinder_n_in ()
Number of rootfinder inputs.
casadi_int casadi::rootfinder_n_out ()
Number of rootfinder outputs.
std::vector< std::string > casadi::rootfinder_options (const std::string &name)
Get all options for a plugin.
std::string casadi::rootfinder_option_type (const std::string &name, const std::string &op)
Get type info for a particular option.
std::string casadi::rootfinder_option_info (const std::string &name, const std::string &op)
Get documentation for a particular option.
bool casadi::has_rootfinder (const std::string &name)
Check if a particular plugin is available.
void casadi::load_rootfinder (const std::string &name)
Explicitly load a plugin dynamically.
std::string casadi::doc_rootfinder (const std::string &name)
Get the documentation string for a plugin.
Variables
const std::vector< std::string > casadi::RFP_INPUTS = {"x", "p"}
Shortnames for DAE symbolic representation inputs.
const std::vector< std::string > casadi::RFP_OUTPUTS = {"g"}
Shortnames for DAE symbolic representation outputs.
Detailed Description
Create a solver for rootfinding problems Takes a function where one of the inputs is unknown and one of the outputs is a residual function that is always zero, defines a new function where the the unknown input has been replaced by a guess for the unknown and the residual output has been replaced by the calculated value for the input.
For a function [y0, y1, ...,yi, .., yn] = F(x0, x1, ..., xj, ..., xm), where xj is unknown and yi=0, defines a new function [y0, y1, ...,xj, .., yn] = G(x0, x1, ..., xj_guess, ..., xm),
xj and yi must have the same dimension and d(yi)/d(xj) must be invertable.
By default, the first input is unknown and the first output is the residual.
General information
List of available options
Id Type Description Used in
ad_weight OT_DOUBLE Weighting factor for derivative calculation.When there is an option of either using forward or reverse mode directional derivatives, the condition ad_weight*nf<=(1-ad_weight)*na is used where nf and na are estimates of the number of forward/reverse mode directional derivatives needed. By default, ad_weight is calculated automatically, but this can be overridden by setting this option. In particular, 0 means forcing forward mode and 1 forcing reverse mode. Leave unset for (class specific) heuristics. casadi::FunctionInternal
ad_weight_sp OT_DOUBLE Weighting factor for sparsity pattern calculation calculation.Overrides default behavior. Set to 0 and 1 to force forward and reverse mode respectively. Cf. option "ad_weight". When set to -1, sparsity is completely ignored and dense matrices are used. casadi::FunctionInternal
always_inline OT_BOOL Force inlining. casadi::FunctionInternal
cache OT_DICT Prepopulate the function cache. Default: empty casadi::FunctionInternal
common_options OT_DICT Options for auto-generated functions casadi::OracleFunction
compiler OT_STRING Just-in-time compiler plugin to be used. casadi::FunctionInternal
constraints OT_INTVECTOR Constrain the unknowns. 0 (default): no constraint on ui, 1: ui >= 0.0, -1: ui <= 0.0, 2: ui > 0.0, -2: ui < 0.0. casadi::Rootfinder
custom_jacobian OT_FUNCTION Override CasADi's AD. Use together with 'jac_penalty': 0. Note: Highly experimental. Syntax may break often. casadi::FunctionInternal
der_options OT_DICT Default options to be used to populate forward_options, reverse_options, and jacobian_options before those options are merged in. casadi::FunctionInternal
derivative_of OT_FUNCTION The function is a derivative of another function. The type of derivative (directional derivative, Jacobian) is inferred from the function name. casadi::FunctionInternal
dump OT_BOOL Dump function to file upon first evaluation. [false] casadi::FunctionInternal
dump_dir OT_STRING Directory to dump inputs/outputs to. Make sure the directory exists [.] casadi::FunctionInternal
dump_format OT_STRING Choose file format to dump matrices. See DM.from_file [mtx] casadi::FunctionInternal
dump_in OT_BOOL Dump numerical values of inputs to file (readable with DM.from_file) [default: false] A counter is used to generate unique names. The counter may be reset using reset_dump_count. casadi::FunctionInternal
dump_out OT_BOOL Dump numerical values of outputs to file (readable with DM.from_file) [default: false] A counter is used to generate unique names. The counter may be reset using reset_dump_count. casadi::FunctionInternal
enable_fd OT_BOOL Enable derivative calculation by finite differencing. [default: false]] casadi::FunctionInternal
enable_forward OT_BOOL Enable derivative calculation using generated functions for Jacobian-times-vector products - typically using forward mode AD - if available. [default: true] casadi::FunctionInternal
enable_jacobian OT_BOOL Enable derivative calculation using generated functions for Jacobians of all differentiable outputs with respect to all differentiable inputs - if available. [default: true] casadi::FunctionInternal
enable_reverse OT_BOOL Enable derivative calculation using generated functions for transposed Jacobian-times-vector products - typically using reverse mode AD - if available. [default: true] casadi::FunctionInternal
error_on_fail OT_BOOL Throw exceptions when function evaluation fails (default true). casadi::ProtoFunction
expand OT_BOOL Replace MX with SX expressions in problem formulation [false] This happens before creating derivatives unless indicated by postpone_expand casadi::OracleFunction
external_transform OT_VECTORVECTOR List of external_transform instruction arguments. Default: empty casadi::FunctionInternal
fd_method OT_STRING Method for finite differencing [default 'central'] casadi::FunctionInternal
fd_options OT_DICT Options to be passed to the finite difference instance casadi::FunctionInternal
forward_options OT_DICT Options to be passed to a forward mode constructor casadi::FunctionInternal
gather_stats OT_BOOL Deprecated option (ignored): Statistics are now always collected. casadi::FunctionInternal
implicit_input OT_INT Index of the input that corresponds to the actual root-finding casadi::Rootfinder
implicit_output OT_INT Index of the output that corresponds to the actual root-finding casadi::Rootfinder
input_scheme OT_STRINGVECTOR Deprecated option (ignored) casadi::FunctionInternal
inputs_check OT_BOOL Throw exceptions when the numerical values of the inputs don't make sense casadi::FunctionInternal
is_diff_in OT_BOOLVECTOR Indicate for each input if it should be differentiable. casadi::FunctionInternal
is_diff_out OT_BOOLVECTOR Indicate for each output if it should be differentiable. casadi::FunctionInternal
jac_penalty OT_DOUBLE When requested for a number of forward/reverse directions, it may be cheaper to compute first the full jacobian and then multiply with seeds, rather than obtain the requested directions in a straightforward manner. Casadi uses a heuristic to decide which is cheaper. A high value of 'jac_penalty' makes it less likely for the heurstic to chose the full Jacobian strategy. The special value -1 indicates never to use the full Jacobian strategy casadi::FunctionInternal
jacobian_function OT_FUNCTION Function object for calculating the Jacobian (autogenerated by default) casadi::Rootfinder
jacobian_options OT_DICT Options to be passed to a Jacobian constructor casadi::FunctionInternal
jit OT_BOOL Use just-in-time compiler to speed up the evaluation casadi::FunctionInternal
jit_cleanup OT_BOOL Cleanup up the temporary source file that jit creates. Default: true casadi::FunctionInternal
jit_name OT_STRING The file name used to write out code. The actual file names used depend on 'jit_temp_suffix' and include extensions. Default: 'jit_tmp' casadi::FunctionInternal
jit_options OT_DICT Options to be passed to the jit compiler. casadi::FunctionInternal
jit_serialize OT_STRING Specify behaviour when serializing a jitted function: SOURCE|link|embed. casadi::FunctionInternal
jit_temp_suffix OT_BOOL Use a temporary (seemingly random) filename suffix for generated code and libraries. This is desired for thread-safety. This behaviour may defeat caching compiler wrappers. Default: true casadi::FunctionInternal
linear_solver OT_STRING User-defined linear solver class. Needed for sensitivities. casadi::Rootfinder
linear_solver_options OT_DICT Options to be passed to the linear solver. casadi::Rootfinder
max_io OT_INT Acceptable number of inputs and outputs. Warn if exceeded. casadi::FunctionInternal
max_num_dir OT_INT Specify the maximum number of directions for derivative functions. Overrules the builtin optimized_num_dir. casadi::FunctionInternal
monitor OT_STRINGVECTOR Set of user problem functions to be monitored casadi::OracleFunction
never_inline OT_BOOL Forbid inlining. casadi::FunctionInternal
output_scheme OT_STRINGVECTOR Deprecated option (ignored) casadi::FunctionInternal
post_expand OT_BOOL After construction, expand this Function. Default: False casadi::FunctionInternal
post_expand_options OT_DICT Options to be passed to post-construction expansion. Default: empty casadi::FunctionInternal
postpone_expand OT_BOOL When expand is active, postpone it until after creation of derivatives. Default: False casadi::OracleFunction
print_canonical OT_BOOL When printing numerical matrices, use a format that is exact and reproducible in generated C code. casadi::FunctionInternal
print_in OT_BOOL Print numerical values of inputs [default: false] casadi::FunctionInternal
print_out OT_BOOL Print numerical values of outputs [default: false] casadi::FunctionInternal
print_time OT_BOOL print information about execution time. Implies record_time. casadi::ProtoFunction
record_time OT_BOOL record information about execution time, for retrieval with stats(). casadi::ProtoFunction
regularity_check OT_BOOL Throw exceptions when NaN or Inf appears during evaluation casadi::ProtoFunction
reverse_options OT_DICT Options to be passed to a reverse mode constructor casadi::FunctionInternal
show_eval_warnings OT_BOOL Show warnings generated from function evaluations [true] casadi::OracleFunction
specific_options OT_DICT Options for specific auto-generated functions, overwriting the defaults from common_options. Nested dictionary. casadi::OracleFunction
user_data OT_VOIDPTR A user-defined field that can be used to identify the function or pass additional information casadi::FunctionInternal
verbose OT_BOOL Verbose evaluation – for debugging casadi::ProtoFunction
Input scheme: casadi::RootfinderInput (ROOTFINDER_NUM_IN = 2)
Full name Short Description
ROOTFINDER_X0 x0 Initial guess for the solution.
ROOTFINDER_P p Parameters.
Output scheme: casadi::RootfinderOutput (ROOTFINDER_NUM_OUT = 1)
Full name Short Description
ROOTFINDER_X x Solution to the system of equations.
List of plugins
- kinsol
- fast_newton
- nlpsol
- newton
Note: some of the plugins in this list might not be available on your system. Also, there might be extra plugins available to you that are not listed here. You can obtain their documentation with Rootfinder.doc("myextraplugin")
kinsol
KINSOL interface from the Sundials suite
Extra doc: https://github.com/casadi/casadi/wiki/L_226
List of available options
Id Type Description
abstol OT_DOUBLE Stopping criterion tolerance
disable_internal_warnings OT_BOOL Disable KINSOL internal warning messages
exact_jacobian OT_BOOL Use exact Jacobian information
f_scale OT_DOUBLEVECTOR Equation scaling factors
iterative_solver OT_STRING gmres|bcgstab|tfqmr
linear_solver_type OT_STRING dense|banded|iterative|user_defined
lower_bandwidth OT_INT Lower bandwidth for banded linear solvers
max_iter OT_INT Maximum number of Newton iterations. Putting 0 sets the default value of KinSol.
max_krylov OT_INT Maximum Krylov space dimension
pretype OT_STRING Type of preconditioner
print_level OT_INT Verbosity level
strategy OT_STRING Globalization strategy
u_scale OT_DOUBLEVECTOR Variable scaling factors
upper_bandwidth OT_INT Upper bandwidth for banded linear solvers
use_preconditioner OT_BOOL Precondition an iterative solver
fast_newton
Implements simple newton iterations to solve an implicit function.
Extra doc: https://github.com/casadi/casadi/wiki/L_237
List of available options
Id Type Description
abstol OT_DOUBLE Stopping criterion tolerance on ||g||__inf)
abstolStep OT_DOUBLE Stopping criterion tolerance on step size
max_iter OT_INT Maximum number of Newton iterations to perform before returning.
nlpsol
newton
Implements simple newton iterations to solve an implicit function.
Extra doc: https://github.com/casadi/casadi/wiki/L_236
List of available options
Id Type Description
abstol OT_DOUBLE Stopping criterion tolerance on max(|F|)
abstolStep OT_DOUBLE Stopping criterion tolerance on step size
line_search OT_BOOL Enable line-search (default: true)
max_iter OT_INT Maximum number of Newton iterations to perform before returning.
print_iteration OT_BOOL Print information about each iteration
Author
Joel Andersson
Date
2011-2015
Extra doc: https://github.com/casadi/casadi/wiki/L_21r
Enumeration Type Documentation
RfpIn
enum casadi::RfpIn
Enumerator
RFP_X
RFP_P
RFP_NUM_IN
Definition at line 139 of file rootfinder.hpp.
              {
     RFP_X,
     RFP_P,
     RFP_NUM_IN};
RfpOut
enum casadi::RfpOut
Enumerator
RFP_G
RFP_NUM_OUT
Definition at line 148 of file rootfinder.hpp.
               {
     RFP_G,
     RFP_NUM_OUT};
RootfinderInput
enum casadi::RootfinderInput
Enumerator
ROOTFINDER_X0
Initial guess for the solution.
ROOTFINDER_P
Parameters.
ROOTFINDER_NUM_IN
Number of input arguments of a rootfinder.
Definition at line 156 of file rootfinder.hpp.
{
     ROOTFINDER_X0,
     ROOTFINDER_P,
     ROOTFINDER_NUM_IN
   };
RootfinderOutput
enum casadi::RootfinderOutput
Enumerator
ROOTFINDER_X
Solution to the system of equations.
ROOTFINDER_NUM_OUT
Number of output arguments of a rootfinder.
Definition at line 166 of file rootfinder.hpp.
{
     ROOTFINDER_X,
     ROOTFINDER_NUM_OUT
   };
Function Documentation
doc_rootfinder()
CASADI_EXPORT std::string casadi::doc_rootfinder (const std::string & name)
Definition at line 107 of file rootfinder.cpp.
{
     return Rootfinder::getPlugin(name).doc;
   }
References casadi::PluginInterface< Rootfinder >::getPlugin().
has_rootfinder()
CASADI_EXPORT bool casadi::has_rootfinder (const std::string & name)
Definition at line 99 of file rootfinder.cpp.
{
     return Rootfinder::has_plugin(name);
   }
References casadi::PluginInterface< Rootfinder >::has_plugin().
load_rootfinder()
CASADI_EXPORT void casadi::load_rootfinder (const std::string & name)
Definition at line 103 of file rootfinder.cpp.
{
     Rootfinder::load_plugin(name);
   }
References casadi::PluginInterface< Rootfinder >::load_plugin().
rootfinder() [1/3]
CASADI_EXPORT Function casadi::rootfinder (const std::string & name, const std::string & solver, const Function & f, const Dict & opts)
Definition at line 152 of file rootfinder.cpp.
{
     // Make sure that residual function is sound
     if (f.has_free()) {
       casadi_error("Cannot create '" + name + "' since " + str(f.get_free()) + " are free.");
     }
     return Function::create(Rootfinder::instantiate(name, solver, f), opts);
   }
References casadi::Function::create(), casadi::Function::get_free(), casadi::Function::has_free(), casadi::PluginInterface< Rootfinder >::instantiate(), and casadi::str().
rootfinder() [2/3]
CASADI_EXPORT Function casadi::rootfinder (const std::string & name, const std::string & solver, const MXDict & rfp, const Dict & opts)
Definition at line 116 of file rootfinder.cpp.
{
     return rootfinder(name, solver, Rootfinder::create_oracle(rfp, opts), opts);
   }
References casadi::Rootfinder::create_oracle(), and casadi::rootfinder().
rootfinder() [3/3]
CASADI_EXPORT Function casadi::rootfinder (const std::string & name, const std::string & solver, const SXDict & rfp, const Dict & opts = Dict())
Examples
solvers/KinsolSolver.py, solvers/NLPImplicitSolver.py, and solvers/NewtonImplicitSolver.py.
Definition at line 111 of file rootfinder.cpp.
{
     return rootfinder(name, solver, Rootfinder::create_oracle(rfp, opts), opts);
   }
References casadi::Rootfinder::create_oracle().
Referenced by casadi::ImplicitFixedStepIntegrator::init(), casadi::rootfinder(), and casadi::simpleIRK().
rootfinder_in() [1/2]
CASADI_EXPORT std::vector< std::string > casadi::rootfinder_in ()
Extra doc: https://github.com/casadi/casadi/wiki/L_1ty
Definition at line 35 of file rootfinder.cpp.
{
     std::vector<std::string> ret(rootfinder_n_in());
     for (size_t i=0; i<ret.size(); ++i) ret[i]=rootfinder_in(i);
     return ret;
   }
References casadi::rootfinder_n_in().
rootfinder_in() [2/2]
CASADI_EXPORT std::string casadi::rootfinder_in (casadi_int ind)
Extra doc: https://github.com/casadi/casadi/wiki/L_1u0
Definition at line 47 of file rootfinder.cpp.
{
     switch (static_cast<RootfinderInput>(ind)) {
     case ROOTFINDER_X0:  return "x0";
     case ROOTFINDER_P:   return "p";
     case ROOTFINDER_NUM_IN: break;
     }
     return std::string();
   }
References casadi::ROOTFINDER_NUM_IN, casadi::ROOTFINDER_P, and casadi::ROOTFINDER_X0.
rootfinder_n_in()
CASADI_EXPORT casadi_int casadi::rootfinder_n_in ()
Extra doc: https://github.com/casadi/casadi/wiki/L_1u2
Definition at line 64 of file rootfinder.cpp.
{
     return ROOTFINDER_NUM_IN;
   }
References casadi::ROOTFINDER_NUM_IN.
Referenced by casadi::rootfinder_in().
rootfinder_n_out()
CASADI_EXPORT casadi_int casadi::rootfinder_n_out ()
Extra doc: https://github.com/casadi/casadi/wiki/L_1u3
Definition at line 68 of file rootfinder.cpp.
{
     return ROOTFINDER_NUM_OUT;
   }
References casadi::ROOTFINDER_NUM_OUT.
Referenced by casadi::rootfinder_out().
rootfinder_option_info()
CASADI_EXPORT std::string casadi::rootfinder_option_info (const std::string & name, const std::string & op)
Extra doc: https://github.com/casadi/casadi/wiki/L_1u6
Definition at line 95 of file rootfinder.cpp.
{
     return Rootfinder::plugin_options(name).info(op);
   }
References casadi::Options::info(), and casadi::PluginInterface< Rootfinder >::plugin_options().
rootfinder_option_type()
CASADI_EXPORT std::string casadi::rootfinder_option_type (const std::string & name, const std::string & op)
Extra doc: https://github.com/casadi/casadi/wiki/L_1u5
Definition at line 91 of file rootfinder.cpp.
{
     return Rootfinder::plugin_options(name).type(op);
   }
References casadi::PluginInterface< Rootfinder >::plugin_options(), and casadi::Options::type().
rootfinder_options()
CASADI_EXPORT std::vector< std::string > casadi::rootfinder_options (const std::string & name)
Extra doc: https://github.com/casadi/casadi/wiki/L_1u4
Definition at line 87 of file rootfinder.cpp.
{
     return Rootfinder::plugin_options(name).all();
   }
References casadi::Options::all(), and casadi::PluginInterface< Rootfinder >::plugin_options().
Referenced by casadi::ImplicitFixedStepIntegrator::init().
rootfinder_out() [1/2]
CASADI_EXPORT std::vector< std::string > casadi::rootfinder_out ()
Extra doc: https://github.com/casadi/casadi/wiki/L_1tz
Definition at line 41 of file rootfinder.cpp.
{
     std::vector<std::string> ret(rootfinder_n_out());
     for (size_t i=0; i<ret.size(); ++i) ret[i]=rootfinder_out(i);
     return ret;
   }
References casadi::rootfinder_n_out().
rootfinder_out() [2/2]
CASADI_EXPORT std::string casadi::rootfinder_out (casadi_int ind)
Extra doc: https://github.com/casadi/casadi/wiki/L_1u1
Definition at line 56 of file rootfinder.cpp.
{
     switch (static_cast<RootfinderOutput>(ind)) {
     case ROOTFINDER_X:  return "x";
     case ROOTFINDER_NUM_OUT: break;
     }
     return std::string();
   }
References casadi::ROOTFINDER_NUM_OUT, and casadi::ROOTFINDER_X.
Variable Documentation
RFP_INPUTS
const std::vector<std::string> casadi::RFP_INPUTS = {"x", "p"}
Definition at line 145 of file rootfinder.hpp.
RFP_OUTPUTS
const std::vector<std::string> casadi::RFP_OUTPUTS = {"g"}
Definition at line 153 of file rootfinder.hpp.