CasADi: casadi::XmlFileInternal Class Reference
casadi::XmlFileInternal Class Reference abstract
#include <xml_file_internal.hpp>
Detailed Description
Definition at line 35 of file xml_file_internal.hpp.
Classes
struct Exposed
Public Types
typedef XmlFileInternal *(* Creator) ()
using weak_ref_type = WeakRefInternal
typedef int(* RegFcn) (Plugin *plugin)
Public Member Functions
XmlFileInternal ()
~XmlFileInternal () override
void disp (std::ostream &stream, bool more=false) const override
Print a description.
virtual XmlNode parse (const std::string &filename)
virtual void dump (const std::string &filename, const XmlNode &node)
virtual std::string class_name () const =0
Readable name of the internal class.
casadi_int getCount () const
Get the reference count.
std::string debug_repr (const SharedObjectInternal *) const
GenericWeakRef< SharedObject, SharedObjectInternal > * weak ()
Get a weak reference to the object.
virtual const char * plugin_name () const=0
void serialize_type (SerializingStream &s) const
Serialize type information.
Static Public Member Functions
static bool has_plugin (const std::string &pname, bool verbose=false)
Check if a plugin is available or can be loaded.
static const Options & plugin_options (const std::string &pname)
Get the plugin options.
static Deserialize plugin_deserialize (const std::string &pname)
Get the plugin deserialize_map.
static Plugin pluginFromRegFcn (RegFcn regfcn)
Instantiate a Plugin struct from a factory function.
static Plugin load_plugin (const std::string &pname, bool register_plugin=true, bool needs_lock=true)
Load a plugin dynamically.
static handle_t load_library (const std::string &libname, std::string &resultpath, bool global)
Load a library dynamically.
static void registerPlugin (const Plugin &plugin, bool needs_lock=true)
Register an integrator in the factory.
static void registerPlugin (RegFcn regfcn, bool needs_lock=true)
Register an integrator in the factory.
static Plugin & getPlugin (const std::string &pname)
Load and get the creator function.
static XmlFileInternal * instantiate (const std::string &fname, const std::string &pname, Problem problem)
static ProtoFunction * deserialize (DeserializingStream &s)
Deserialize with type disambiguation.
Static Public Attributes
static std::map< std::string, Plugin > solvers_
Collection of solvers.
static const std::string infix_ = "xmlfile"
Infix.
Protected Member Functions
void initSingleton ()
void destroySingleton ()
B shared_from_this ()
Get a shared object from the current internal object.
const B shared_from_this () const
Get a shared object from the current internal object.
Member Typedef Documentation
Creator
typedef XmlFileInternal*(* casadi::XmlFileInternal::Creator) ()
Definition at line 57 of file xml_file_internal.hpp.
RegFcn
typedef int(* casadi::PluginInterface< XmlFileInternal >::RegFcn) (Plugin *plugin) inherited
Definition at line 73 of file plugin_interface.hpp.
weak_ref_type
using casadi::SharedObjectInternal::weak_ref_type = WeakRefInternal inherited
Definition at line 152 of file shared_object.hpp.
Constructor & Destructor Documentation
XmlFileInternal()
casadi::XmlFileInternal::XmlFileInternal ()
Definition at line 30 of file xml_file_internal.cpp.
{
 }
~XmlFileInternal()
casadi::XmlFileInternal::~XmlFileInternal () override
Definition at line 33 of file xml_file_internal.cpp.
{
 }
Member Function Documentation
class_name()
virtual std::string casadi::SharedObjectInternal::class_name () const pure virtual inherited
Implemented in casadi::SymbolicQr, casadi::Sqpmethod, casadi::ShellCompiler, casadi::Scpgen, casadi::RungeKutta, casadi::Qrsqp, casadi::Qrqp, casadi::QpToNlp, casadi::Newton, casadi::Lsqr, casadi::LinsolTridiag, casadi::LinsolQr, casadi::LinsolLdl, casadi::LinearInterpolantJac, casadi::LinearInterpolant, casadi::Ipqp, casadi::ImplicitToNlp, casadi::Feasiblesqpmethod, casadi::FastNewton, casadi::Collocation, casadi::BSplineInterpolant, casadi::WorhpInterface, casadi::TinyXmlInterface, casadi::SuperscsInterface, casadi::KinsolInterface, casadi::IdasInterface, casadi::CvodesInterface, casadi::SqicInterface, casadi::SnoptInterface, casadi::SlicotExpm, casadi::SlicotDple, casadi::SLEQPInterface, casadi::QpoasesInterface, casadi::ProxqpInterface, casadi::OsqpInterface, casadi::OoqpInterface, casadi::MumpsInterface, casadi::MadnlpInterface, casadi::LapackQr, casadi::LapackLu, casadi::KnitroInterface, casadi::IpoptInterface, casadi::Ma27Interface, casadi::HpmpcInterface, casadi::HpipmInterface, casadi::HighsInterface, casadi::GurobiInterface, casadi::FatropInterface, casadi::FatropConicInterface, casadi::DaqpInterface, casadi::CsparseInterface, casadi::CSparseCholeskyInterface, casadi::CplexInterface, casadi::ClpInterface, casadi::ClarabelInterface, casadi::ClangCompiler, casadi::CbcInterface, casadi::BonminInterface, casadi::Blocksqp, casadi::AmplInterface, casadi::AlpaqaInterface, casadi::SXFunction, casadi::Switch, casadi::SparsityInternal, casadi::WeakRefInternal, casadi::ZipMemResource, casadi::ZipResource, casadi::DirResource, casadi::OptiNode, casadi::Nlpsol, casadi::MXNode, casadi::MXFunction, casadi::MapSum, casadi::ThreadMap, casadi::OmpMap, casadi::Map, casadi::JitFunction, casadi::Interpolant, casadi::DllLibrary, casadi::ImporterInternal, casadi::GenericTypeInternal< ID, T >, casadi::FmuFunction, casadi::Fmu3, casadi::Fmu2, casadi::Smoothing, casadi::CentralDiff, casadi::BackwardDiff, casadi::ForwardDiff, casadi::External, casadi::DaeBuilderInternal, casadi::CallbackInternal, and casadi::BlazingSplineFunction.
Referenced by casadi::FunctionInternal::call_forward(), casadi::FunctionInternal::call_reverse(), casadi::FunctionInternal::codegen_body(), casadi::ProtoFunction::construct(), casadi::FmuInternal::deserialize(), casadi::ResourceInternal::deserialize(), casadi::FmuInternal::disp(), casadi::FunctionInternal::disp(), casadi::LinsolInternal::disp(), dump(), casadi::FunctionInternal::eval(), casadi::FunctionInternal::eval_dm(), casadi::FunctionInternal::eval_sx(), casadi::FunctionInternal::export_code(), casadi::LinsolInternal::generate(), casadi::FunctionInternal::generate_dependencies(), casadi::Conic::generateNativeCode(), casadi::FmuInternal::get_adjoint_derivative(), casadi::FunctionInternal::get_forward(), casadi::FunctionInternal::get_function(), casadi::FunctionInternal::get_jacobian(), casadi::FunctionInternal::get_reverse(), casadi::FiniteDiff::init(), casadi::FunctionInternal::instruction_constant(), casadi::FunctionInternal::instruction_id(), casadi::FunctionInternal::instruction_input(), casadi::FunctionInternal::instruction_MX(), casadi::FunctionInternal::instruction_output(), casadi::FunctionInternal::instructions_sx(), casadi::LinsolInternal::linsol_eval_sx(), casadi::FunctionInternal::n_instructions(), casadi::FunctionInternal::n_nodes(), casadi::LinsolInternal::neig(), casadi::LinsolInternal::nfact(), casadi::FunctionInternal::oracle(), parse(), casadi::LinsolInternal::rank(), casadi::FmuInternal::serialize_type(), casadi::ResourceInternal::serialize_type(), and casadi::LinsolInternal::solve().
debug_repr()
std::string casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::debug_repr (const Internal * i) const inherited
Definition at line 62 of file generic_shared_internal.hpp.
{
     // Note: i != this because of something something multiple inheritance
     return str( (casadi_int)(i)) + "/" + static_cast<const Internal*>(this)->class_name();
   }
deserialize()
static ProtoFunction* casadi::PluginInterface< XmlFileInternal >::deserialize (DeserializingStream & s) inline static inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_rr
Definition at line 121 of file plugin_interface.hpp.
{
       std::string class_name, plugin_name;
       s.unpack("PluginInterface::plugin_name", plugin_name);
       Deserialize deserialize = plugin_deserialize(plugin_name);
       return deserialize(s);
     }
destroySingleton()
void casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::destroySingleton () inline protected inherited
Called in the destructor of singletons
Definition at line 77 of file generic_shared_internal.hpp.
{
       static_cast<Internal*>(this)->count--;
     }
disp()
void casadi::XmlFileInternal::disp (std::ostream & stream, bool more = false) const override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_ed
Implements casadi::SharedObjectInternal.
Definition at line 44 of file xml_file_internal.cpp.
{
 }
dump()
void casadi::XmlFileInternal::dump (const std::string & filename, const XmlNode & node) virtual
Reimplemented in casadi::TinyXmlInterface.
Definition at line 52 of file xml_file_internal.cpp.
{
   casadi_error("dump not defined for " + class_name());
 }
References casadi::SharedObjectInternal::class_name().
getCount()
casadi_int casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::getCount inherited
Definition at line 60 of file generic_shared_internal.hpp.
{
     return static_cast<const Internal*>(this)->count;
   }
getPlugin()
PluginInterface< XmlFileInternal >::Plugin & casadi::PluginInterface< XmlFileInternal >::getPlugin (const std::string & pname) static inherited
Definition at line 102 of file plugin_interface.hpp.
{
 #ifdef CASADI_WITH_THREADSAFE_SYMBOLICS
     std::lock_guard<std::mutex> lock(Derived::mutex_solvers_);
 #endif // CASADI_WITH_THREADSAFE_SYMBOLICS
     // Check if the solver has been loaded
     auto it=Derived::solvers_.find(pname);
     // Load the solver if needed
     if (it==Derived::solvers_.end()) {
       load_plugin(pname, true, false);
       it=Derived::solvers_.find(pname);
     }
     casadi_assert_dev(it!=Derived::solvers_.end());
     return it->second;
   }
has_plugin()
bool casadi::PluginInterface< XmlFileInternal >::has_plugin (const std::string & pname, bool verbose = false) static inherited
Definition at line 76 of file plugin_interface.hpp.
{
 #ifdef CASADI_WITH_THREADSAFE_SYMBOLICS
     std::lock_guard<std::mutex> lock(Derived::mutex_solvers_);
 #endif // CASADI_WITH_THREADSAFE_SYMBOLICS
     // Quick return if available
     if (Derived::solvers_.find(pname) != Derived::solvers_.end()) {
       return true;
     }
     // Try loading the plugin
     try {
       (void)load_plugin(pname, false, false);
       return true;
     } catch (CasadiException& ex) {
       if (verbose) {
         casadi_warning(ex.what());
       }
       return false;
     }
   }
initSingleton()
void casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::initSingleton () inline protected inherited
Called in the constructor of singletons to avoid that the counter reaches zero
Definition at line 71 of file generic_shared_internal.hpp.
{
       casadi_assert_dev(static_cast<Internal*>(this)->count==0);
       static_cast<Internal*>(this)->count++;
     }
instantiate()
XmlFileInternal * casadi::PluginInterface< XmlFileInternal >::instantiate (const std::string & fname, const std::string & pname, Problem problem) static inherited
Definition at line 106 of file plugin_interface.hpp.
{
     // Assert the plugin exists (needed for adaptors)
     if (!has_plugin(pname, true)) {
       casadi_error("Plugin '" + pname + "' is not found.");
     }
     return getPlugin(pname).creator(fname, problem);
   }
load_library()
handle_t casadi::PluginInterface< XmlFileInternal >::load_library (const std::string & libname, std::string & resultpath, bool global) static inherited
Definition at line 92 of file plugin_interface.hpp.
{
 #ifndef WITH_DL
     casadi_error("WITH_DL option needed for dynamic loading");
 #else // WITH_DL
     // Get the name of the shared library
     std::string lib = SHARED_LIBRARY_PREFIX + libname + SHARED_LIBRARY_SUFFIX;
     // Build up search paths;
     std::vector<std::string> search_paths = get_search_paths();
     return open_shared_library(lib, search_paths, resultpath,
       "PluginInterface::load_plugin", global);
 #endif // WITH_DL
   }
load_plugin()
PluginInterface< XmlFileInternal >::Plugin casadi::PluginInterface< XmlFileInternal >::load_plugin (const std::string & pname, bool register_plugin = true, bool needs_lock = true) static inherited
Definition at line 88 of file plugin_interface.hpp.
{
 #ifdef CASADI_WITH_THREADSAFE_SYMBOLICS
     casadi::conditional_lock_guard<std::mutex> lock(Derived::mutex_solvers_, needs_lock);
 #endif // CASADI_WITH_THREADSAFE_SYMBOLICS
     // Issue warning and quick return if already loaded
     if (Derived::solvers_.find(pname) != Derived::solvers_.end()) {
       casadi_warning("PluginInterface: Solver " + pname + " is already in use. Ignored.");
       return Plugin();
     }
     // Logger singletons are lazily instantiated on first uout()/uerr() calls
     // This instantation may lead to a data race with potential instatiations in plugin
     // To be safe, trigger instantatin before any plugin loading
     uout();
     uerr();
 #ifndef WITH_DL
     casadi_error("WITH_DL option needed for dynamic loading");
 #else // WITH_DL
     // Retrieve the registration function
     RegFcn reg;
     // Load the dll
     std::string regName = "casadi_register_" + Derived::infix_ + "_" + pname;
     std::string searchpath;
     handle_t handle = load_library("casadi_" + Derived::infix_ + "_" + pname, searchpath,
       false);
 #ifdef _WIN32
 #if __GNUC__
 #pragma GCC diagnostic push
 #pragma GCC diagnostic ignored "-Wcast-function-type"
 #endif
     reg = reinterpret_cast<RegFcn>(GetProcAddress(handle, TEXT(regName.c_str())));
 #if __GNUC__
 #pragma GCC diagnostic pop
 #endif
 #else // _WIN32
     // Reset error
     dlerror();
     // Load creator
     reg = reinterpret_cast<RegFcn>(dlsym(handle, regName.c_str()));
 #endif // _WIN32
     casadi_assert(reg!=nullptr,
       "PluginInterface::load_plugin: no \"" + regName + "\" found in " + searchpath + ".");
     // Create a temporary struct
     Plugin plugin = pluginFromRegFcn(reg);
     // Register the plugin
     if (register_plugin) {
       registerPlugin(plugin, false);
     }
     return plugin;
 #endif // WITH_DL
   }
parse()
XmlNode casadi::XmlFileInternal::parse (const std::string & filename) virtual
Reimplemented in casadi::TinyXmlInterface.
Definition at line 47 of file xml_file_internal.cpp.
{
   casadi_error("parse not defined for " + class_name());
   return XmlNode();
 }
References casadi::SharedObjectInternal::class_name().
plugin_deserialize()
Deserialize casadi::PluginInterface< XmlFileInternal >::plugin_deserialize (const std::string & pname) static inherited
Definition at line 82 of file plugin_interface.hpp.
{
     Deserialize m = getPlugin(pname).deserialize;
     casadi_assert(m, "Plugin \"" + pname + "\" does not support deserialize");
     return m;
   }
plugin_name()
virtual const char* casadi::PluginInterface< XmlFileInternal >::plugin_name () const pure virtual inherited
Implemented in casadi::TinyXmlInterface.
plugin_options()
const Options & casadi::PluginInterface< XmlFileInternal >::plugin_options (const std::string & pname) static inherited
Definition at line 79 of file plugin_interface.hpp.
{
     const Options *op = getPlugin(pname).options;
     casadi_assert(op!=nullptr, "Plugin \"" + pname + "\" does not support options");
     return *op;
   }
pluginFromRegFcn()
PluginInterface< XmlFileInternal >::Plugin casadi::PluginInterface< XmlFileInternal >::pluginFromRegFcn (RegFcn regfcn) static inherited
Definition at line 85 of file plugin_interface.hpp.
{
     // Create a temporary struct
     Plugin plugin;
     // Set the fields
     int flag = regfcn(&plugin);
     casadi_assert(flag==0, "Registration of plugin failed.");
     return plugin;
   }
registerPlugin() [1/2]
void casadi::PluginInterface< XmlFileInternal >::registerPlugin (const Plugin & plugin, bool needs_lock = true) static inherited
Definition at line 96 of file plugin_interface.hpp.
{
 #ifdef CASADI_WITH_THREADSAFE_SYMBOLICS
     casadi::conditional_lock_guard<std::mutex> lock(Derived::mutex_solvers_, needs_lock);
 #endif // CASADI_WITH_THREADSAFE_SYMBOLICS
     // Check if the solver name is in use
     typename std::map<std::string, Plugin>::iterator it=Derived::solvers_.find(plugin.name);
     casadi_assert(it==Derived::solvers_.end(),
       "Solver " + str(plugin.name) + " is already in use");
     // Add to list of solvers
     Derived::solvers_[plugin.name] = plugin;
   }
registerPlugin() [2/2]
void casadi::PluginInterface< XmlFileInternal >::registerPlugin (RegFcn regfcn, bool needs_lock = true) static inherited
Definition at line 99 of file plugin_interface.hpp.
{
     registerPlugin(pluginFromRegFcn(regfcn), needs_lock);
   }
serialize_type()
void casadi::PluginInterface< XmlFileInternal >::serialize_type (SerializingStream & s) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_rq
Definition at line 114 of file plugin_interface.hpp.
{
       s.pack("PluginInterface::plugin_name", std::string(plugin_name()));
     }
shared_from_this() [1/2]
B casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::shared_from_this () inline protected inherited
Definition at line 83 of file generic_shared_internal.hpp.
{
       casadi_assert_dev(B::test_cast(static_cast<Internal*>(this)));
       B ret;
       ret.own(static_cast<Internal*>(this));
       return ret;
     }
shared_from_this() [2/2]
const B casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::shared_from_this () const inline protected inherited
Definition at line 92 of file generic_shared_internal.hpp.
{
       casadi_assert_dev(B::test_cast(static_cast<const Internal*>(this)));
       B ret;
       ret.own(const_cast<Internal*>(static_cast<const Internal*>(this)));
       return ret;
     }
weak()
GenericWeakRef< SharedObject , SharedObjectInternal > * casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::weak inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1ai
Definition at line 67 of file generic_shared_internal.hpp.
{
     if (weak_ref_==nullptr) {
       weak_ref_ = new GenericWeakRef<Shared, Internal>(static_cast<Internal*>(this));
     }
     return weak_ref_;
   }
Member Data Documentation
infix_
const std::string casadi::XmlFileInternal::infix_ = "xmlfile" static
Definition at line 70 of file xml_file_internal.hpp.
solvers_
std::map< std::string, XmlFileInternal::Plugin > casadi::XmlFileInternal::solvers_ static
Definition at line 63 of file xml_file_internal.hpp.
The documentation for this class was generated from the following files:
xml_file_internal.hpp
xml_file_internal.cpp