CasADi: casadi::CasadiException Class Reference
casadi::CasadiException Class Reference
Casadi exception class.
#include <exception.hpp>
Detailed Description
\author Joel Andersson
\date 2010
Example for simple exception throwing:
\code
        throw CasadiException("This is a nasty error");
\endcode
Example for exception chaining:
\code
        try {
                throw CasadiException("This is a nasty error");
        catch(CasadiException &e) {
                throw CasadiException("Serious error.") << e;
        }
\endcode
Extra doc: https://github.com/casadi/casadi/wiki/L_7u
Definition at line 77 of file exception.hpp.
Public Member Functions
CasadiException ()
Default constructor.
CasadiException (const std::string &msg)
Form message string.
~CasadiException () throw ()
Destructor.
const char * what () const override throw ()
Display error.
Protected Attributes
std::string msg_
Constructor & Destructor Documentation
CasadiException() [1/2]
casadi::CasadiException::CasadiException () inline
Definition at line 80 of file exception.hpp.
                     {
   }
CasadiException() [2/2]
casadi::CasadiException::CasadiException (const std::string & msg) inline explicit
Definition at line 84 of file exception.hpp.
 : msg_(msg) {}
~CasadiException()
casadi::CasadiException::~CasadiException () throw () inline
Definition at line 87 of file exception.hpp.
 {}
Member Function Documentation
what()
const char* casadi::CasadiException::what () const throw () inline override
Definition at line 90 of file exception.hpp.
{
     return msg_.c_str();
   }
Referenced by casadi::accepted_iterate(), casadi::KnitroInterface::callback(), casadi::Nlpsol::callback(), casadi::AlpaqaProblem::eval_f(), casadi::BonminUserClass::eval_f(), casadi::IpoptUserClass::eval_f(), casadi::AlpaqaProblem::eval_f_grad_f(), casadi::AlpaqaProblem::eval_g(), casadi::BonminUserClass::eval_g(), casadi::IpoptUserClass::eval_g(), casadi::BonminUserClass::eval_grad_f(), casadi::IpoptUserClass::eval_grad_f(), casadi::AlpaqaProblem::eval_grad_L(), casadi::BonminUserClass::eval_h(), casadi::IpoptUserClass::eval_h(), casadi::AlpaqaProblem::eval_hess_L(), casadi::AlpaqaProblem::eval_hess_L_prod(), casadi::AlpaqaProblem::eval_hess_ψ(), casadi::AlpaqaProblem::eval_hess_ψ_prod(), casadi::AlpaqaProblem::eval_jac_g(), casadi::BonminUserClass::eval_jac_g(), casadi::IpoptUserClass::eval_jac_g(), casadi::AlpaqaProblem::eval_ψ(), casadi::AlpaqaProblem::eval_ψ_grad_ψ(), casadi::XFunction< DerivedType, MatType, NodeType >::factory(), casadi::PluginInterface< Derived >::has_plugin(), casadi::BonminInterface::intermediate_callback(), casadi::IpoptInterface::intermediate_callback(), casadi::Function::operator()(), and casadi::SnoptInterface::userfun().
Member Data Documentation
msg_
std::string casadi::CasadiException::msg_ protected
Definition at line 95 of file exception.hpp.
The documentation for this class was generated from the following file:
exception.hpp