CasADi: casadi::HpipmMemory Struct Reference
casadi::HpipmMemory Struct Reference
#include <hpipm_interface.hpp>
Detailed Description
Definition at line 78 of file hpipm_interface.hpp.
Public Member Functions
HpipmMemory ()
Constructor.
~HpipmMemory ()
Destructor.
void add_stat (const std::string &s)
Public Attributes
casadi_hpipm_data< double > d
casadi_qp_data< double > d_qp
std::map< std::string, FStats > fstats
FStats * t_total
Constructor & Destructor Documentation
HpipmMemory()
casadi::HpipmMemory::HpipmMemory ()
Definition at line 740 of file hpipm_interface.cpp.
{
   }
~HpipmMemory()
casadi::HpipmMemory::~HpipmMemory ()
Definition at line 743 of file hpipm_interface.cpp.
{
   }
Member Function Documentation
add_stat()
void casadi::ProtoFunctionMemory::add_stat (const std::string & s) inline inherited
Definition at line 74 of file function_internal.hpp.
{
       bool added = fstats.insert(std::make_pair(s, FStats())).second;
       casadi_assert(added, "Duplicate stat: '" + s + "'");
     }
Referenced by casadi::ProtoFunction::init_mem(), casadi::LinsolInternal::init_mem(), casadi::Nlpsol::init_mem(), casadi::OracleFunction::init_mem(), casadi::CbcInterface::init_mem(), casadi::ClpInterface::init_mem(), casadi::HpipmInterface::init_mem(), casadi::Feasiblesqpmethod::init_mem(), casadi::Sqpmethod::init_mem(), and casadi::OracleFunction::local_init_mem().
Member Data Documentation
d
casadi_hpipm_data<double> casadi::HpipmMemory::d
Definition at line 80 of file hpipm_interface.hpp.
Referenced by casadi::HpipmInterface::get_stats().
d_qp
casadi_qp_data<double> casadi::ConicMemory::d_qp inherited
Definition at line 39 of file conic_impl.hpp.
Referenced by casadi::Conic::get_stats().
fstats
std::map<std::string, FStats> casadi::ProtoFunctionMemory::fstats inherited
Definition at line 68 of file function_internal.hpp.
Referenced by casadi::Nlpsol::callback(), casadi::IpoptUserClass::eval_h(), casadi::BonminInterface::intermediate_callback(), casadi::IpoptInterface::intermediate_callback(), casadi::OracleFunction::join_results(), casadi::HighsInterface::solve(), casadi::HpipmInterface::solve(), casadi::HpmpcInterface::solve(), casadi::ProxqpInterface::solve(), casadi::QpoasesInterface::solve(), casadi::Sqpmethod::solve_ela_QP(), casadi::Feasiblesqpmethod::solve_LP(), casadi::Feasiblesqpmethod::solve_QP(), and casadi::Sqpmethod::solve_QP().
t_total
FStats* casadi::ProtoFunctionMemory::t_total inherited
Definition at line 71 of file function_internal.hpp.
Referenced by casadi::LinsolCall< Tr >::eval(), casadi::FunctionInternal::eval_gen(), and casadi::Linsol::solve().
The documentation for this struct was generated from the following files:
hpipm_interface.hpp
hpipm_interface.cpp