CasADi: casadi::Fmu Class Reference
casadi::Fmu Class Reference
Interface to binary FMU.
#include <fmu.hpp>
Detailed Description
Can be shared between multiple CasADi functions.
Author
Joel Andersson
Date
2023
Extra doc: https://github.com/casadi/casadi/wiki/L_26s
Definition at line 60 of file fmu.hpp.
Public Types
using internal_base_type = SharedObjectInternal
using base_type = SharedObject
Public Member Functions
Fmu ()
Default constructor.
Fmu (const std::string &name, FmuApi api, const DaeBuilderInternal *dae, const std::vector< std::string > &scheme_in, const std::vector< std::string > &scheme_out, const std::map< std::string, std::vector< size_t >> &scheme, const std::vector< std::string > &aux)
Importer factory.
const std::string & name () const
Name of the instance.
const std::string & instance_name () const
Name of the FMU.
size_t n_in () const
Get the number of scheme inputs.
size_t n_out () const
Get the number of scheme outputs.
size_t index_in (const std::string &n) const
size_t index_out (const std::string &n) const
const std::vector< size_t > & ired (size_t ind) const
const std::vector< size_t > & ored (size_t ind) const
double nominal_in (size_t ind) const
double nominal_out (size_t ind) const
double min_in (size_t ind) const
double max_in (size_t ind) const
std::vector< double > all_nominal_in (size_t ind) const
std::vector< double > all_nominal_out (size_t ind) const
std::string desc_in (FmuMemory *m, size_t id, bool more=true) const
bool provides_directional_derivatives () const
Does the FMU provide support for forward directional derivatives.
bool provides_adjoint_derivatives () const
Does the FMU provide support for adjoint directional derivatives.
bool can_be_instantiated_only_once_per_process () const
Does the FMU declare restrictions on instantiation?
Sparsity jac_sparsity (const std::vector< size_t > &osub, const std::vector< size_t > &isub) const
Sparsity jac_sparsity (size_t oind, size_t iind) const
Sparsity hess_sparsity (const std::vector< size_t > &r, const std::vector< size_t > &c) const
Sparsity hess_sparsity (size_t r, size_t c) const
FmuMemory * alloc_mem (const FmuFunction &f) const
Create memory block.
int init_mem (FmuMemory *m) const
Initalize memory block.
void free_mem (void *mem) const
Free memory block.
void free_instance (void *instance) const
void set (FmuMemory *m, size_t ind, const double *value) const
void request (FmuMemory *m, size_t ind) const
int eval (FmuMemory *m) const
void get (FmuMemory *m, size_t ind, double *value) const
void set_fwd (FmuMemory *m, casadi_int nseed, const casadi_int *id, const double *v) const
void set_fwd (FmuMemory *m, size_t ind, const double *v) const
void request_fwd (FmuMemory *m, casadi_int nsens, const casadi_int *id, const casadi_int *wrt_id) const
void request_fwd (FmuMemory *m, casadi_int ind) const
int eval_fwd (FmuMemory *m, bool independent_seeds) const
void get_fwd (FmuMemory *m, casadi_int nsens, const casadi_int *id, double *v) const
void get_fwd (FmuMemory *m, size_t ind, double *v) const
void set_adj (FmuMemory *m, casadi_int nseed, const casadi_int *id, const double *v) const
void set_adj (FmuMemory *m, size_t ind, const double *v) const
void request_adj (FmuMemory *m, casadi_int nsens, const casadi_int *id, const casadi_int *wrt_id) const
void request_adj (FmuMemory *m, casadi_int ind) const
int eval_adj (FmuMemory *m) const
void get_adj (FmuMemory *m, casadi_int nsens, const casadi_int *id, double *v) const
void get_adj (FmuMemory *m, size_t ind, double *v) const
void get_stats (FmuMemory *m, Dict *stats, const std::vector< std::string > &name_in, const InputStruct *in) const
Get stats.
void serialize (SerializingStream &s) const
Serialize an object.
std::string class_name () const
Get class name.
void disp (std::ostream &stream, bool more=false) const
Print a description of the object.
std::string get_str (bool more=false) const
Get string representation.
void print_ptr (std::ostream &stream=casadi::uout()) const
void own (SharedObjectInternal *node)
void assign (SharedObjectInternal *node)
Assign the node to a node class pointer without reference counting.
casadi_int getCount () const
Get the reference count.
void swap (GenericShared &other)
Swap content with another instance.
std::string debug_repr () const
bool is_null () const
Is a null pointer?
casadi_int __hash__ () const
Returns a number that is unique for a given Node.
GenericWeakRef< SharedObject, SharedObjectInternal > * weak ()
Get a weak reference to the object.
FmuInternal * operator-> ()
const FmuInternal * operator-> () const
FmuInternal * get () const
Static Public Member Functions
static std::string type_name ()
Get type name.
static Fmu create (FmuInternal *node)
Create from node.
static Fmu deserialize (DeserializingStream &s)
Deserialize with type disambiguation.
Protected Member Functions
void count_up ()
void count_down ()
Member Typedef Documentation
base_type
using casadi::SharedObject::base_type = SharedObject inherited
Definition at line 103 of file shared_object.hpp.
internal_base_type
using casadi::SharedObject::internal_base_type = SharedObjectInternal inherited
Definition at line 102 of file shared_object.hpp.
Constructor & Destructor Documentation
Fmu() [1/2]
casadi::Fmu::Fmu ()
Definition at line 48 of file fmu.cpp.
          {
 }
Fmu() [2/2]
casadi::Fmu::Fmu (const std::string & name, FmuApi api, const DaeBuilderInternal * dae, const std::vector< std::string > & scheme_in, const std::vector< std::string > & scheme_out, const std::map< std::string, std::vector< size_t >> & scheme, const std::vector< std::string > & aux)
Definition at line 51 of file fmu.cpp.
{
   if (api == FmuApi::FMI2) {
 #ifdef WITH_FMI2
   // Create
   own(new Fmu2(name, scheme_in, scheme_out, scheme, aux));
 #else  // WITH_FMI2
   // No compilation support
   casadi_error("CasADi was not compiled with WITH_FMI2=ON.");
 #endif  // WITH_FMI2
   } else if (api == FmuApi::FMI3) {
 #ifdef WITH_FMI3
   // Create
   own(new Fmu3(name, scheme_in, scheme_out, scheme, aux));
 #else  // WITH_FMI3
   // No compilation support
   casadi_error("CasADi was not compiled with WITH_FMI3=ON.");
 #endif  // WITH_FMI3
   } else {
     // Not supported
     casadi_error("Unsupported FMU API: " + to_string(api));
   }
   // Initialize
   try {
     (*this)->init(dae);
     (*this)->finalize();
   } catch(std::exception& e) {
     THROW_ERROR("init", e.what());
   }
 }
References casadi::FMI2, casadi::FMI3, name(), casadi::GenericShared< SharedObject, SharedObjectInternal >::own(), and casadi::to_string().
Member Function Documentation
__hash__()
casadi_int casadi::GenericShared< SharedObject , SharedObjectInternal >::__hash__ inherited
If the Object does not point to any node, "0" is returned.
Extra doc: https://github.com/casadi/casadi/wiki/L_av
Definition at line 123 of file generic_shared_impl.hpp.
{
     return reinterpret_cast<casadi_int>(get());
   }
all_nominal_in()
std::vector< double > casadi::Fmu::all_nominal_in (size_t ind) const
Definition at line 203 of file fmu.cpp.
{
   try {
     return (*this)->all_nominal_in(ind);
   } catch(std::exception& e) {
     THROW_ERROR("all_nominal_in", e.what());
   }
 }
Referenced by casadi::FmuFunction::get_nominal_in().
all_nominal_out()
std::vector< double > casadi::Fmu::all_nominal_out (size_t ind) const
Definition at line 211 of file fmu.cpp.
{
   try {
     return (*this)->all_nominal_out(ind);
   } catch(std::exception& e) {
     THROW_ERROR("all_nominal_out", e.what());
   }
 }
Referenced by casadi::FmuFunction::get_nominal_in(), and casadi::FmuFunction::get_nominal_out().
alloc_mem()
FmuMemory * casadi::Fmu::alloc_mem (const FmuFunction & f) const
Extra doc: https://github.com/casadi/casadi/wiki/L_2dn
Definition at line 93 of file fmu.cpp.
{
   return (*this)->alloc_mem(f);
 }
Referenced by casadi::FmuFunction::alloc_mem().
assign()
void casadi::GenericShared< SharedObject , SharedObjectInternal >::assign (Internal * node) inherited
improper use will cause memory leaks!
Extra doc: https://github.com/casadi/casadi/wiki/L_at
Definition at line 96 of file generic_shared_impl.hpp.
{
     node = node_;
   }
can_be_instantiated_only_once_per_process()
bool casadi::Fmu::can_be_instantiated_only_once_per_process () const
Definition at line 243 of file fmu.cpp.
{
   try {
     return (*this)->can_be_instantiated_only_once_per_process_;
   } catch(std::exception& e) {
     THROW_ERROR("can_be_instantiated_only_once_per_process", e.what());
   }
 }
Referenced by casadi::FmuFunction::check_mem_count().
class_name()
std::string casadi::SharedObject::class_name () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_au
Definition at line 31 of file shared_object.cpp.
{
     return (*this)->class_name();
   }
Referenced by casadi::FmuFunction::check_mem_count(), casadi::MXFunction::export_code_body(), and casadi::BlazingSplineFunction::merge().
count_down()
void casadi::GenericShared< SharedObject , SharedObjectInternal >::count_down protected inherited
Definition at line 133 of file generic_shared_impl.hpp.
{
 #ifdef WITH_EXTRA_CHECKS
     casadi_assert_dev(Function::call_depth_==0);
 #endif // WITH_EXTRA_CHECKS
     if (!node) return;
     if (node->weak_ref_) {
 #ifdef CASADI_WITH_THREADSAFE_SYMBOLICS
       auto mutex = node->weak_ref_->get_mutex();
       // Avoid triggering a delete while a weak_ref.shared_if_alive is being called
       std::lock_guard<std::mutex> lock(*mutex);
       // Could it be that this mutex is destroyed when the lock goes out of scope?
 #endif // CASADI_WITH_THREADSAFE_SYMBOLICS
       if (--static_cast<Internal*>(node)->count == 0) {
         delete node;
         node = nullptr;
       }
     } else {
       if (--static_cast<Internal*>(node)->count == 0) {
         delete node;
         node = nullptr;
       }
     }
   }
count_up()
void casadi::GenericShared< SharedObject , SharedObjectInternal >::count_up protected inherited
Definition at line 132 of file generic_shared_impl.hpp.
{
 #ifdef WITH_EXTRA_CHECKS
     casadi_assert_dev(Function::call_depth_==0);
 #endif // WITH_EXTRA_CHECKS
     if (node) static_cast<Internal*>(node)->count++;
   }
create()
Fmu casadi::Fmu::create (FmuInternal * node) static
Extra doc: https://github.com/casadi/casadi/wiki/L_27c
Definition at line 1365 of file fmu.cpp.
{
   Fmu ret;
   ret.own(node);
   return ret;
 }
References casadi::GenericShared< Shared, Internal >::own().
Referenced by deserialize().
debug_repr()
std::string casadi::GenericShared< SharedObject , SharedObjectInternal >::debug_repr inherited
Definition at line 112 of file generic_shared_impl.hpp.
{
     if (node) {
         return node->debug_repr(node);
     } else {
         return "NULL";
     }
   }
desc_in()
std::string casadi::Fmu::desc_in (FmuMemory * m, size_t id, bool more = true) const
Definition at line 219 of file fmu.cpp.
{
   try {
     return (*this)->desc_in(m, id, more);
   } catch(std::exception& e) {
     THROW_ERROR("desc_in", e.what());
   }
 }
Referenced by casadi::FmuFunction::check_hessian(), and casadi::FmuFunction::eval_task().
deserialize()
Fmu casadi::Fmu::deserialize (DeserializingStream & s) static
Extra doc: https://github.com/casadi/casadi/wiki/L_27e
Definition at line 1361 of file fmu.cpp.
{
   return Fmu::create(FmuInternal::deserialize(s));
 }
References create(), and casadi::FmuInternal::deserialize().
disp()
void casadi::SharedObject::disp (std::ostream & stream, bool more = false) const inherited
Definition at line 35 of file shared_object.cpp.
{
     if (is_null()) {
       stream << "NULL";
     } else {
       (*this)->disp(stream, more);
     }
   }
References casadi::GenericShared< SharedObject, SharedObjectInternal >::is_null().
Referenced by casadi::Nlpsol::disp_more(), and casadi::CsparseInterface::nfact().
eval()
int casadi::Fmu::eval (FmuMemory * m) const
Definition at line 301 of file fmu.cpp.
{
   try {
     return (*this)->eval(m);
   } catch(std::exception& e) {
     THROW_ERROR("eval", e.what());
   }
 }
Referenced by casadi::FmuFunction::eval_task().
eval_adj()
int casadi::Fmu::eval_adj (FmuMemory * m) const
Definition at line 407 of file fmu.cpp.
{
   try {
     return (*this)->eval_adj(m);
   } catch(std::exception& e) {
     THROW_ERROR("eval_adj", e.what());
   }
 }
Referenced by casadi::FmuFunction::eval_task().
eval_fwd()
int casadi::Fmu::eval_fwd (FmuMemory * m, bool independent_seeds) const
Definition at line 350 of file fmu.cpp.
{
   try {
     return (*this)->eval_fwd(m, independent_seeds);
   } catch(std::exception& e) {
     THROW_ERROR("eval_fwd", e.what());
   }
 }
Referenced by casadi::FmuFunction::eval_task().
free_instance()
void casadi::Fmu::free_instance (void * instance) const
Definition at line 277 of file fmu.cpp.
{
   try {
     return (*this)->free_instance(instance);
   } catch(std::exception& e) {
     THROW_ERROR("free_instance", e.what());
   }
 }
Referenced by casadi::FmuFunction::free_mem().
free_mem()
void casadi::Fmu::free_mem (void * mem) const
Extra doc: https://github.com/casadi/casadi/wiki/L_2dt
Definition at line 97 of file fmu.cpp.
{
   return (*this)->free_mem(mem);
 }
Referenced by casadi::FmuFunction::free_mem().
get() [1/2]
FmuInternal * casadi::Fmu::get () const
Access functions of the node
Definition at line 101 of file fmu.cpp.
{
   return static_cast<FmuInternal*>(SharedObject::get());
 }
References casadi::GenericShared< SharedObject, SharedObjectInternal >::get().
Referenced by casadi::FmuFunction::eval_task().
get() [2/2]
void casadi::Fmu::get (FmuMemory * m, size_t ind, double * value) const
Definition at line 309 of file fmu.cpp.
{
   try {
     return (*this)->get(m, id, value);
   } catch(std::exception& e) {
     THROW_ERROR("get", e.what());
   }
 }
References casadi::FmuInternal::get().
get_adj() [1/2]
void casadi::Fmu::get_adj (FmuMemory * m, casadi_int nsens, const casadi_int * id, double * v) const
Definition at line 415 of file fmu.cpp.
{
   try {
     return (*this)->get_adj(m, nsens, id, v);
   } catch(std::exception& e) {
     THROW_ERROR("get_adj", e.what());
   }
 }
Referenced by casadi::FmuFunction::eval_task().
get_adj() [2/2]
void casadi::Fmu::get_adj (FmuMemory * m, size_t ind, double * v) const
Definition at line 423 of file fmu.cpp.
{
   try {
     return (*this)->get_adj(m, ind, v);
   } catch(std::exception& e) {
     THROW_ERROR("get_adj", e.what());
   }
 }
get_fwd() [1/2]
void casadi::Fmu::get_fwd (FmuMemory * m, casadi_int nsens, const casadi_int * id, double * v) const
Definition at line 358 of file fmu.cpp.
{
   try {
     return (*this)->get_fwd(m, nsens, id, v);
   } catch(std::exception& e) {
     THROW_ERROR("get_fwd", e.what());
   }
 }
Referenced by casadi::FmuFunction::eval_task().
get_fwd() [2/2]
void casadi::Fmu::get_fwd (FmuMemory * m, size_t ind, double * v) const
Definition at line 366 of file fmu.cpp.
{
   try {
     return (*this)->get_fwd(m, ind, v);
   } catch(std::exception& e) {
     THROW_ERROR("get_fwd", e.what());
   }
 }
get_stats()
void casadi::Fmu::get_stats (FmuMemory * m, Dict * stats, const std::vector< std::string > & name_in, const InputStruct * in) const
Extra doc: https://github.com/casadi/casadi/wiki/L_26y
Definition at line 431 of file fmu.cpp.
{
   try {
     return (*this)->get_stats(m, stats, name_in, in);
   } catch(std::exception& e) {
     THROW_ERROR("get_stats", e.what());
   }
 }
Referenced by casadi::FmuFunction::get_stats().
get_str()
std::string casadi::SharedObject::get_str (bool more = false) const inline inherited
Definition at line 91 of file shared_object.hpp.
{
         std::stringstream ss;
         disp(ss, more);
         return ss.str();
       }
getCount()
casadi_int casadi::GenericShared< SharedObject , SharedObjectInternal >::getCount inherited
Definition at line 102 of file generic_shared_impl.hpp.
{
     return (*this)->getCount();
   }
hess_sparsity() [1/2]
Sparsity casadi::Fmu::hess_sparsity (const std::vector< size_t > & r, const std::vector< size_t > & c) const
Definition at line 260 of file fmu.cpp.
{
   try {
     return (*this)->hess_sparsity(r, c);
   } catch(std::exception& e) {
     THROW_ERROR("hess_sparsity", e.what());
   }
 }
Referenced by casadi::FmuFunction::get_jac_sparsity(), casadi::FmuFunction::get_sparsity_out(), and casadi::FmuFunction::init().
hess_sparsity() [2/2]
Sparsity casadi::Fmu::hess_sparsity (size_t r, size_t c) const inline
Definition at line 160 of file fmu.hpp.
{
     return hess_sparsity(ired(r), ired(c));
   }
index_in()
size_t casadi::Fmu::index_in (const std::string & n) const
Definition at line 139 of file fmu.cpp.
{
   try {
     return (*this)->index_in(n);
   } catch(std::exception& e) {
     THROW_ERROR("index_in", e.what());
   }
 }
index_out()
size_t casadi::Fmu::index_out (const std::string & n) const
Definition at line 147 of file fmu.cpp.
{
   try {
     return (*this)->index_out(n);
   } catch(std::exception& e) {
     THROW_ERROR("index_out", e.what());
   }
 }
init_mem()
int casadi::Fmu::init_mem (FmuMemory * m) const
Extra doc: https://github.com/casadi/casadi/wiki/L_26x
Definition at line 268 of file fmu.cpp.
{
   try {
     return (*this)->init_mem(m);
   } catch(std::exception& e) {
     THROW_ERROR("init_mem", e.what());
     return 1;
   }
 }
Referenced by casadi::FmuFunction::init_mem().
instance_name()
const std::string & casadi::Fmu::instance_name () const
Extra doc: https://github.com/casadi/casadi/wiki/L_2ab
Definition at line 114 of file fmu.cpp.
{
   if (is_null()) {
     static std::string null = "null";
     return null;
   } else {
     return (*this)->instance_name_;
   }
 }
References casadi::GenericShared< SharedObject, SharedObjectInternal >::is_null().
Referenced by casadi::FmuFunction::check_mem_count().
ired()
const std::vector< size_t > & casadi::Fmu::ired (size_t ind) const
Definition at line 155 of file fmu.cpp.
{
   try {
     return (*this)->ired_.at(ind);
   } catch(std::exception& e) {
     THROW_ERROR("ired", e.what());
   }
 }
Referenced by casadi::FmuFunction::eval(), casadi::FmuFunction::get_sparsity_in(), casadi::FmuFunction::get_sparsity_out(), and casadi::FmuFunction::init().
is_null()
bool casadi::GenericShared< SharedObject , SharedObjectInternal >::is_null inherited
Definition at line 116 of file generic_shared_impl.hpp.
{
     return node==nullptr;
   }
jac_sparsity() [1/2]
Sparsity casadi::Fmu::jac_sparsity (const std::vector< size_t > & osub, const std::vector< size_t > & isub) const
Definition at line 251 of file fmu.cpp.
{
   try {
     return (*this)->jac_sparsity(osub, isub);
   } catch(std::exception& e) {
     THROW_ERROR("jac_sparsity", e.what());
   }
 }
Referenced by casadi::FmuFunction::get_jac_sparsity(), casadi::FmuFunction::get_sparsity_out(), and casadi::FmuFunction::init().
jac_sparsity() [2/2]
Sparsity casadi::Fmu::jac_sparsity (size_t oind, size_t iind) const inline
Definition at line 152 of file fmu.hpp.
{
     return jac_sparsity(ored(oind), ired(iind));
   }
max_in()
double casadi::Fmu::max_in (size_t ind) const
Definition at line 195 of file fmu.cpp.
{
   try {
     return (*this)->max_in_.at(ind);
   } catch(std::exception& e) {
     THROW_ERROR("max_in", e.what());
   }
 }
Referenced by casadi::FmuFunction::eval_task().
min_in()
double casadi::Fmu::min_in (size_t ind) const
Definition at line 187 of file fmu.cpp.
{
   try {
     return (*this)->min_in_.at(ind);
   } catch(std::exception& e) {
     THROW_ERROR("min_in", e.what());
   }
 }
Referenced by casadi::FmuFunction::eval_task().
n_in()
size_t casadi::Fmu::n_in () const
Extra doc: https://github.com/casadi/casadi/wiki/L_26v
Definition at line 123 of file fmu.cpp.
{
   try {
     return (*this)->n_in();
   } catch(std::exception& e) {
     THROW_ERROR("n_in", e.what());
   }
 }
Referenced by casadi::FmuFunction::eval(), casadi::FmuFunction::eval_task(), and casadi::FmuFunction::init().
n_out()
size_t casadi::Fmu::n_out () const
Extra doc: https://github.com/casadi/casadi/wiki/L_26w
Definition at line 131 of file fmu.cpp.
{
   try {
     return (*this)->n_out();
   } catch(std::exception& e) {
     THROW_ERROR("n_out", e.what());
   }
 }
Referenced by casadi::FmuFunction::eval(), casadi::FmuFunction::eval_task(), and casadi::FmuFunction::init().
name()
const std::string & casadi::Fmu::name () const
Extra doc: https://github.com/casadi/casadi/wiki/L_26u
Definition at line 105 of file fmu.cpp.
{
   if (is_null()) {
     static std::string null = "null";
     return null;
   } else {
     return (*this)->name_;
   }
 }
References casadi::GenericShared< SharedObject, SharedObjectInternal >::is_null().
Referenced by Fmu().
nominal_in()
double casadi::Fmu::nominal_in (size_t ind) const
Definition at line 171 of file fmu.cpp.
{
   try {
     return (*this)->nominal_in_.at(ind);
   } catch(std::exception& e) {
     THROW_ERROR("nominal_in", e.what());
   }
 }
Referenced by casadi::FmuFunction::eval_task(), and casadi::FmuFunction::init().
nominal_out()
double casadi::Fmu::nominal_out (size_t ind) const
Definition at line 179 of file fmu.cpp.
{
   try {
     return (*this)->nominal_out_.at(ind);
   } catch(std::exception& e) {
     THROW_ERROR("nominal_out", e.what());
   }
 }
operator->() [1/2]
FmuInternal * casadi::Fmu::operator-> ()
Access functions of the node
Definition at line 85 of file fmu.cpp.
{
   return static_cast<FmuInternal*>(SharedObject::operator->());
 }
References casadi::GenericShared< SharedObject, SharedObjectInternal >::operator->().
operator->() [2/2]
const FmuInternal * casadi::Fmu::operator-> () const
Access functions of the node
Definition at line 89 of file fmu.cpp.
{
   return static_cast<const FmuInternal*>(SharedObject::operator->());
 }
References casadi::GenericShared< SharedObject, SharedObjectInternal >::operator->().
ored()
const std::vector< size_t > & casadi::Fmu::ored (size_t ind) const
Definition at line 163 of file fmu.cpp.
{
   try {
     return (*this)->ored_.at(ind);
   } catch(std::exception& e) {
     THROW_ERROR("ored", e.what());
   }
 }
Referenced by casadi::FmuFunction::eval(), casadi::FmuFunction::get_sparsity_in(), casadi::FmuFunction::get_sparsity_out(), and casadi::FmuFunction::init().
own()
void casadi::GenericShared< SharedObject , SharedObjectInternal >::own (Internal * node) inherited
Assign the node to a node class pointer (or null)
Definition at line 89 of file generic_shared_impl.hpp.
{
     count_down();
     node = node_;
     count_up();
   }
print_ptr()
void casadi::SharedObject::print_ptr (std::ostream & stream = casadi::uout()) const inherited
Print the pointer to the internal class
Definition at line 43 of file shared_object.cpp.
{
     stream << get();
   }
References casadi::GenericShared< SharedObject, SharedObjectInternal >::get().
provides_adjoint_derivatives()
bool casadi::Fmu::provides_adjoint_derivatives () const
Definition at line 235 of file fmu.cpp.
{
   try {
     return (*this)->provides_adjoint_derivatives_;
   } catch(std::exception& e) {
     THROW_ERROR("provides_adjoint_derivatives", e.what());
   }
 }
Referenced by casadi::FmuFunction::FmuFunction(), and casadi::FmuFunction::init().
provides_directional_derivatives()
bool casadi::Fmu::provides_directional_derivatives () const
Definition at line 227 of file fmu.cpp.
{
   try {
     return (*this)->provides_directional_derivatives_;
   } catch(std::exception& e) {
     THROW_ERROR("provides_directional_derivatives", e.what());
   }
 }
Referenced by casadi::FmuFunction::FmuFunction(), and casadi::FmuFunction::init().
request()
void casadi::Fmu::request (FmuMemory * m, size_t ind) const
Definition at line 293 of file fmu.cpp.
{
   try {
     return (*this)->request(m, ind);
   } catch(std::exception& e) {
     THROW_ERROR("request", e.what());
   }
 }
Referenced by casadi::FmuFunction::eval_task().
request_adj() [1/2]
void casadi::Fmu::request_adj (FmuMemory * m, casadi_int ind) const
Definition at line 399 of file fmu.cpp.
{
   try {
     return (*this)->request_adj(m, ind);
   } catch(std::exception& e) {
     THROW_ERROR("request_adj", e.what());
   }
 }
request_adj() [2/2]
void casadi::Fmu::request_adj (FmuMemory * m, casadi_int nsens, const casadi_int * id, const casadi_int * wrt_id) const
Definition at line 390 of file fmu.cpp.
{
   try {
     return (*this)->request_adj(m, nsens, id, wrt_id);
   } catch(std::exception& e) {
     THROW_ERROR("request_adj", e.what());
   }
 }
Referenced by casadi::FmuFunction::eval_task().
request_fwd() [1/2]
void casadi::Fmu::request_fwd (FmuMemory * m, casadi_int ind) const
Definition at line 342 of file fmu.cpp.
{
   try {
     return (*this)->request_fwd(m, ind);
   } catch(std::exception& e) {
     THROW_ERROR("request_fwd", e.what());
   }
 }
request_fwd() [2/2]
void casadi::Fmu::request_fwd (FmuMemory * m, casadi_int nsens, const casadi_int * id, const casadi_int * wrt_id) const
Definition at line 333 of file fmu.cpp.
{
   try {
     return (*this)->request_fwd(m, nsens, id, wrt_id);
   } catch(std::exception& e) {
     THROW_ERROR("request_fwd", e.what());
   }
 }
Referenced by casadi::FmuFunction::eval_task().
serialize()
void casadi::Fmu::serialize (SerializingStream & s) const
Extra doc: https://github.com/casadi/casadi/wiki/L_27d
Definition at line 1357 of file fmu.cpp.
{
   return (*this)->serialize(s);
 }
set()
void casadi::Fmu::set (FmuMemory * m, size_t ind, const double * value) const
Definition at line 285 of file fmu.cpp.
{
   try {
     return (*this)->set(m, ind, value);
   } catch(std::exception& e) {
     THROW_ERROR("set", e.what());
   }
 }
Referenced by casadi::FmuFunction::eval_task().
set_adj() [1/2]
void casadi::Fmu::set_adj (FmuMemory * m, casadi_int nseed, const casadi_int * id, const double * v) const
Definition at line 374 of file fmu.cpp.
{
   try {
     return (*this)->set_adj(m, nseed, id, v);
   } catch(std::exception& e) {
     THROW_ERROR("set_adj", e.what());
   }
 }
Referenced by casadi::FmuFunction::eval_task().
set_adj() [2/2]
void casadi::Fmu::set_adj (FmuMemory * m, size_t ind, const double * v) const
Definition at line 382 of file fmu.cpp.
{
   try {
     return (*this)->set_adj(m, ind, v);
   } catch(std::exception& e) {
     THROW_ERROR("set_adj", e.what());
   }
 }
set_fwd() [1/2]
void casadi::Fmu::set_fwd (FmuMemory * m, casadi_int nseed, const casadi_int * id, const double * v) const
Definition at line 317 of file fmu.cpp.
{
   try {
     return (*this)->set_fwd(m, nseed, id, v);
   } catch(std::exception& e) {
     THROW_ERROR("set_fwd", e.what());
   }
 }
Referenced by casadi::FmuFunction::eval_task().
set_fwd() [2/2]
void casadi::Fmu::set_fwd (FmuMemory * m, size_t ind, const double * v) const
Definition at line 325 of file fmu.cpp.
{
   try {
     return (*this)->set_fwd(m, ind, v);
   } catch(std::exception& e) {
     THROW_ERROR("set_fwd", e.what());
   }
 }
swap()
void casadi::GenericShared< SharedObject , SharedObjectInternal >::swap (GenericShared< SharedObject, SharedObjectInternal > & other) inherited
Definition at line 105 of file generic_shared_impl.hpp.
{
     GenericShared<Shared, Internal> temp = *this;
     *this = other;
     other = temp;
   }
type_name()
static std::string casadi::Fmu::type_name () inline static
Extra doc: https://github.com/casadi/casadi/wiki/L_26t
Definition at line 67 of file fmu.hpp.
 {return "Fmu";}
weak()
GenericWeakRef< SharedObject , SharedObjectInternal > * casadi::GenericShared< SharedObject , SharedObjectInternal >::weak inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_aw
Definition at line 130 of file generic_shared_impl.hpp.
{
     return (*this)->weak();
   }
The documentation for this class was generated from the following files:
fmu.hpp
fmu.cpp