CasADi: std Namespace Reference
std Namespace Reference
Classes
class numeric_limits< casadi::SXElem >
Functions
template<typename T >
ostream & operator<< (ostream &stream, const vector< T > &v)
Enables flushing an std::vector to a stream (prints representation)
template<typename T , size_t N>
ostream & operator<< (ostream &stream, const array< T, N > &v)
Enables flushing an std::vector to a stream (prints representation)
template<typename T >
ostream & operator<< (ostream &stream, const set< T > &v)
Enables flushing an std::set to a stream (prints representation)
template<typename T1 , typename T2 >
ostream & operator<< (ostream &stream, const pair< T1, T2 > &p)
template<typename T1 , typename T2 >
ostream & operator<< (ostream &stream, const std::map< T1, T2 > &p)
template<typename T2 >
ostream & operator<< (ostream &stream, const std::map< std::string, T2 > &p)
template<typename T >
bool mul_overflows (const T &a, const T &b)
Function Documentation
mul_overflows()
template<typename T > bool std::mul_overflows (const T & a, const T & b)
Definition at line 537 of file casadi_misc.hpp.
{
     if (a==0 || b==0) return false;
     return abs(std::numeric_limits<T>::max()/a) < abs(b);
   }
Referenced by casadi::SparsityInternal::find().
operator<<() [1/6]
template<typename T , size_t N> ostream& std::operator<< (ostream & stream, const array< T, N > & v)
Definition at line 506 of file casadi_misc.hpp.
{
     stream << casadi::str(v);
     return stream;
   }
References casadi::str().
operator<<() [2/6]
template<typename T1 , typename T2 > ostream& std::operator<< (ostream & stream, const pair< T1, T2 > & p)
Definition at line 519 of file casadi_misc.hpp.
{
     stream << casadi::str(p);
     return stream;
   }
References casadi::str().
operator<<() [3/6]
template<typename T > ostream& std::operator<< (ostream & stream, const set< T > & v)
Definition at line 513 of file casadi_misc.hpp.
{
     stream << casadi::str(v);
     return stream;
   }
References casadi::str().
operator<<() [4/6]
template<typename T2 > ostream& std::operator<< (ostream & stream, const std::map< std::string, T2 > & p)
Definition at line 531 of file casadi_misc.hpp.
{
     stream << casadi::str(p);
     return stream;
   }
References casadi::str().
operator<<() [5/6]
template<typename T1 , typename T2 > ostream& std::operator<< (ostream & stream, const std::map< T1, T2 > & p)
Definition at line 525 of file casadi_misc.hpp.
{
     stream << casadi::str(p);
     return stream;
   }
References casadi::str().
operator<<() [6/6]
template<typename T > ostream& std::operator<< (ostream & stream, const vector< T > & v)
Definition at line 499 of file casadi_misc.hpp.
{
     stream << casadi::str(v);
     return stream;
   }
References casadi::str().