CasADi: casadi::FStats Class Reference
casadi::FStats Class Reference
#include <timing.hpp>
Detailed Description
Timer class
FStats hack; hack.tic(); .... hack.toc();
Definition at line 47 of file timing.hpp.
Public Member Functions
FStats ()
Constructor.
void reset ()
Reset the statistics.
void tic ()
Start timing.
void toc ()
Stop timing.
void join (FStats &rhs)
Public Attributes
casadi_int n_call = 0
Accumulated number of calls since last reset.
double t_wall = 0
Accumulated wall time [s] since last reset.
double t_proc = 0
Accumulated proc time [s] since last reset.
Constructor & Destructor Documentation
FStats()
casadi::FStats::FStats ()
Definition at line 31 of file timing.cpp.
                  {
   }
Member Function Documentation
join()
void casadi::FStats::join (FStats & rhs)
Definition at line 59 of file timing.cpp.
{
     t_proc += rhs.t_proc;
     t_wall += rhs.t_wall;
     n_call += rhs.n_call;
   }
References n_call, t_proc, and t_wall.
reset()
void casadi::FStats::reset ()
Definition at line 34 of file timing.cpp.
                      {
     n_call = 0;
     t_wall = 0;
     t_proc = 0;
   }
tic()
void casadi::FStats::tic ()
Definition at line 40 of file timing.cpp.
                    {
     start_proc = std::clock();
     start_wall= high_resolution_clock::now();
   }
Referenced by casadi::LinsolCall< Tr >::eval(), casadi::FunctionInternal::eval_gen(), casadi::ScopedTiming::ScopedTiming(), and casadi::Linsol::solve().
toc()
void casadi::FStats::toc ()
Definition at line 45 of file timing.cpp.
                    {
     // First get the time points
     stop_proc = std::clock();
     stop_wall = high_resolution_clock::now();
     // Process them
     double proc = static_cast<double>(stop_proc - start_proc) / static_cast<double>(CLOCKS_PER_SEC);
     t_proc += proc;
     double wall = duration<double>(stop_wall - start_wall).count();
     t_wall += wall;
     n_call +=1;
   }
Referenced by casadi::ScopedTiming::~ScopedTiming().
Member Data Documentation
n_call
casadi_int casadi::FStats::n_call = 0
Definition at line 75 of file timing.hpp.
Referenced by join().
t_proc
double casadi::FStats::t_proc = 0
Definition at line 81 of file timing.hpp.
Referenced by join().
t_wall
double casadi::FStats::t_wall = 0
Definition at line 78 of file timing.hpp.
Referenced by join().
The documentation for this class was generated from the following files:
timing.hpp
timing.cpp