CasADi: Title
Title
Functions
Function casadi::conic (const std::string &name, const std::string &solver, const SpDict &qp, const Dict &opts)
Function casadi::qpsol (const std::string &name, const std::string &solver, const SXDict &qp, const Dict &opts)
Function casadi::qpsol (const std::string &name, const std::string &solver, const MXDict &qp, const Dict &opts)
std::vector< std::string > casadi::conic_in ()
Get input scheme of QP solvers.
std::vector< std::string > casadi::conic_out ()
Get QP solver output scheme of QP solvers.
std::string casadi::conic_in (casadi_int ind)
Get QP solver input scheme name by index.
std::string casadi::conic_out (casadi_int ind)
Get output scheme name by index.
casadi_int casadi::conic_n_in ()
Get the number of QP solver inputs.
casadi_int casadi::conic_n_out ()
Get the number of QP solver outputs.
std::vector< std::string > casadi::conic_options (const std::string &name)
Get all options for a plugin.
std::string casadi::conic_option_type (const std::string &name, const std::string &op)
Get type info for a particular option.
std::string casadi::conic_option_info (const std::string &name, const std::string &op)
Get documentation for a particular option.
bool casadi::has_conic (const std::string &name)
Check if a particular plugin is available.
void casadi::load_conic (const std::string &name)
Explicitly load a plugin dynamically.
std::string casadi::doc_conic (const std::string &name)
Get the documentation string for a plugin.
void casadi::conic_debug (const Function &f, const std::string &filename)
void casadi::conic_debug (const Function &f, std::ostream &file)
Detailed Description
Create a QP solver Solves the following strictly convex problem:
min          1/2 x' H x + g' x
x
subject to
LBA <= A x <= UBA
LBX <= x   <= UBX
resize(Q x, np, np) + P >= 0 (psd)
with :
H sparse (n x n) positive definite
g dense  (n x 1)
A sparse (nc x n)
Q sparse symmetric (np^2 x n)
P sparse symmetric (np x nq)
n: number of decision variables (x)
nc: number of constraints (A)
nq: shape of psd constraint matrix
If H is not positive-definite, the solver should throw an error.
Second-order cone constraints can be added as psd constraints through a helper function 'soc':
x in R^n y in R
|| x ||_2 <= y
<=>
soc(x, y) psd
This can be proven with soc(x, y)=[y*I x; x' y] using the Shur complement.
General information
List of available options
Id Type Description Used in
ad_weight OT_DOUBLE Weighting factor for derivative calculation.When there is an option of either using forward or reverse mode directional derivatives, the condition ad_weight*nf<=(1-ad_weight)*na is used where nf and na are estimates of the number of forward/reverse mode directional derivatives needed. By default, ad_weight is calculated automatically, but this can be overridden by setting this option. In particular, 0 means forcing forward mode and 1 forcing reverse mode. Leave unset for (class specific) heuristics. casadi::FunctionInternal
ad_weight_sp OT_DOUBLE Weighting factor for sparsity pattern calculation calculation.Overrides default behavior. Set to 0 and 1 to force forward and reverse mode respectively. Cf. option "ad_weight". When set to -1, sparsity is completely ignored and dense matrices are used. casadi::FunctionInternal
always_inline OT_BOOL Force inlining. casadi::FunctionInternal
cache OT_DICT Prepopulate the function cache. Default: empty casadi::FunctionInternal
compiler OT_STRING Just-in-time compiler plugin to be used. casadi::FunctionInternal
custom_jacobian OT_FUNCTION Override CasADi's AD. Use together with 'jac_penalty': 0. Note: Highly experimental. Syntax may break often. casadi::FunctionInternal
der_options OT_DICT Default options to be used to populate forward_options, reverse_options, and jacobian_options before those options are merged in. casadi::FunctionInternal
derivative_of OT_FUNCTION The function is a derivative of another function. The type of derivative (directional derivative, Jacobian) is inferred from the function name. casadi::FunctionInternal
discrete OT_BOOLVECTOR Indicates which of the variables are discrete, i.e. integer-valued casadi::Conic
dump OT_BOOL Dump function to file upon first evaluation. [false] casadi::FunctionInternal
dump_dir OT_STRING Directory to dump inputs/outputs to. Make sure the directory exists [.] casadi::FunctionInternal
dump_format OT_STRING Choose file format to dump matrices. See DM.from_file [mtx] casadi::FunctionInternal
dump_in OT_BOOL Dump numerical values of inputs to file (readable with DM.from_file) [default: false] casadi::FunctionInternal
dump_out OT_BOOL Dump numerical values of outputs to file (readable with DM.from_file) [default: false] casadi::FunctionInternal
enable_fd OT_BOOL Enable derivative calculation by finite differencing. [default: false]] casadi::FunctionInternal
enable_forward OT_BOOL Enable derivative calculation using generated functions for Jacobian-times-vector products - typically using forward mode AD - if available. [default: true] casadi::FunctionInternal
enable_jacobian OT_BOOL Enable derivative calculation using generated functions for Jacobians of all differentiable outputs with respect to all differentiable inputs - if available. [default: true] casadi::FunctionInternal
enable_reverse OT_BOOL Enable derivative calculation using generated functions for transposed Jacobian-times-vector products - typically using reverse mode AD - if available. [default: true] casadi::FunctionInternal
error_on_fail OT_BOOL Throw exceptions when function evaluation fails (default true). casadi::ProtoFunction
fd_method OT_STRING Method for finite differencing [default 'central'] casadi::FunctionInternal
fd_options OT_DICT Options to be passed to the finite difference instance casadi::FunctionInternal
forward_options OT_DICT Options to be passed to a forward mode constructor casadi::FunctionInternal
gather_stats OT_BOOL Deprecated option (ignored): Statistics are now always collected. casadi::FunctionInternal
input_scheme OT_STRINGVECTOR Deprecated option (ignored) casadi::FunctionInternal
inputs_check OT_BOOL Throw exceptions when the numerical values of the inputs don't make sense casadi::FunctionInternal
is_diff_in OT_BOOLVECTOR Indicate for each input if it should be differentiable. casadi::FunctionInternal
is_diff_out OT_BOOLVECTOR Indicate for each output if it should be differentiable. casadi::FunctionInternal
jac_penalty OT_DOUBLE When requested for a number of forward/reverse directions, it may be cheaper to compute first the full jacobian and then multiply with seeds, rather than obtain the requested directions in a straightforward manner. Casadi uses a heuristic to decide which is cheaper. A high value of 'jac_penalty' makes it less likely for the heurstic to chose the full Jacobian strategy. The special value -1 indicates never to use the full Jacobian strategy casadi::FunctionInternal
jacobian_options OT_DICT Options to be passed to a Jacobian constructor casadi::FunctionInternal
jit OT_BOOL Use just-in-time compiler to speed up the evaluation casadi::FunctionInternal
jit_cleanup OT_BOOL Cleanup up the temporary source file that jit creates. Default: true casadi::FunctionInternal
jit_name OT_STRING The file name used to write out code. The actual file names used depend on 'jit_temp_suffix' and include extensions. Default: 'jit_tmp' casadi::FunctionInternal
jit_options OT_DICT Options to be passed to the jit compiler. casadi::FunctionInternal
jit_serialize OT_STRING Specify behaviour when serializing a jitted function: SOURCE|link|embed. casadi::FunctionInternal
jit_temp_suffix OT_BOOL Use a temporary (seemingly random) filename suffix for generated code and libraries. This is desired for thread-safety. This behaviour may defeat caching compiler wrappers. Default: true casadi::FunctionInternal
max_io OT_INT Acceptable number of inputs and outputs. Warn if exceeded. casadi::FunctionInternal
max_num_dir OT_INT Specify the maximum number of directions for derivative functions. Overrules the builtin optimized_num_dir. casadi::FunctionInternal
never_inline OT_BOOL Forbid inlining. casadi::FunctionInternal
output_scheme OT_STRINGVECTOR Deprecated option (ignored) casadi::FunctionInternal
post_expand OT_BOOL After construction, expand this Function. Default: False casadi::FunctionInternal
post_expand_options OT_DICT Options to be passed to post-construction expansion. Default: empty casadi::FunctionInternal
print_in OT_BOOL Print numerical values of inputs [default: false] casadi::FunctionInternal
print_out OT_BOOL Print numerical values of outputs [default: false] casadi::FunctionInternal
print_problem OT_BOOL Print a numeric description of the problem casadi::Conic
print_time OT_BOOL print information about execution time. Implies record_time. casadi::ProtoFunction
record_time OT_BOOL record information about execution time, for retrieval with stats(). casadi::ProtoFunction
regularity_check OT_BOOL Throw exceptions when NaN or Inf appears during evaluation casadi::ProtoFunction
reverse_options OT_DICT Options to be passed to a reverse mode constructor casadi::FunctionInternal
user_data OT_VOIDPTR A user-defined field that can be used to identify the function or pass additional information casadi::FunctionInternal
verbose OT_BOOL Verbose evaluation – for debugging casadi::ProtoFunction
Input scheme: casadi::ConicInput (CONIC_NUM_IN = 12)
Full name Short Description
CONIC_H h The square matrix H: sparse, (n x n). Only the lower triangular part is actually used. The matrix is assumed to be symmetrical.
CONIC_G g The vector g: dense, (n x 1)
CONIC_A a The matrix A: sparse, (nc x n) - product with x must be dense.
CONIC_LBA lba dense, (nc x 1)
CONIC_UBA uba dense, (nc x 1)
CONIC_LBX lbx dense, (n x 1)
CONIC_UBX ubx dense, (n x 1)
CONIC_X0 x0 dense, (n x 1)
CONIC_LAM_X0 lam_x0 dense
CONIC_LAM_A0 lam_a0 dense
CONIC_Q q The matrix Q: sparse symmetric, (np^2 x n)
CONIC_P p The matrix P: sparse symmetric, (np x np)
Output scheme: casadi::ConicOutput (CONIC_NUM_OUT = 4)
Full name Short Description
CONIC_X x The primal solution.
CONIC_COST cost The optimal cost.
CONIC_LAM_A lam_a The dual solution corresponding to linear bounds.
CONIC_LAM_X lam_x The dual solution corresponding to simple bounds.
List of plugins
- cbc
- clp
- cplex
- gurobi
- highs
- hpipm
- hpmpc
- ooqp
- osqp
- proxqp
- qpoases
- sqic
- superscs
- ipqp
- nlpsol
- qrqp
Note: some of the plugins in this list might not be available on your system. Also, there might be extra plugins available to you that are not listed here. You can obtain their documentation with Conic.doc("myextraplugin")
cbc
Interface to Cbc solver for sparse Quadratic Programs
Extra doc: https://github.com/casadi/casadi/wiki/L_221
List of available options
Id Type Description
cbc OT_DICT Options to be passed to CBC.Three sets of options are supported. The first can be found in OsiSolverParameters.hpp. The second can be found in CbcModel.hpp. The third are options that can be passed to CbcMain1.
hot_start OT_BOOL Hot start with x0 [Default false].
sos_groups OT_INTVECTORVECTOR Definition of SOS groups by indices.
sos_types OT_INTVECTOR Specify 1 or 2 for each SOS group.
sos_weights OT_DOUBLEVECTORVECTOR Weights corresponding to SOS entries.
clp
Interface to Clp solver for sparse Quadratic Programs
Extra doc: https://github.com/casadi/casadi/wiki/L_22d
List of available options
Id Type Description
clp OT_DICT Options to be passed to CLP. A first set of options can be found in ClpParameters.hpp. eg. 'PrimalTolerance'. There are other options in additions. 'AutomaticScaling' (bool) is recognised. 'initial_solve' (default off) activates the use of Clp's initialSolve. 'initial_solve_options' takes a dictionary with following keys (see ClpSolve.hpp): SolveType (string), PresolveType (string), NumberPasses, SpecialOptions (intvectorvector), IndependentOptions (intvectorvector).
cplex
Interface to Cplex solver for sparse Quadratic Programs
Extra doc: https://github.com/casadi/casadi/wiki/L_22a
List of available options
Id Type Description
cplex OT_DICT Options to be passed to CPLEX
dep_check OT_INT Detect redundant constraints.
dump_filename OT_STRING The filename to dump to.
dump_to_file OT_BOOL Dumps QP to file in CPLEX format.
mip_start OT_BOOL Hot start integers with x0 [Default false].
qp_method OT_INT Determines which CPLEX algorithm to use.
sos_groups OT_INTVECTORVECTOR Definition of SOS groups by indices.
sos_types OT_INTVECTOR Specify 1 or 2 for each SOS group.
sos_weights OT_DOUBLEVECTORVECTOR Weights corresponding to SOS entries.
tol OT_DOUBLE Tolerance of solver
version_suffix OT_STRING Specify version of cplex to load. We will attempt to load libcplex<version_suffix>.[so|dll|dylib]. Default value is taken from CPLEX_VERSION env variable.
warm_start OT_BOOL Use warm start with simplex methods (affects only the simplex methods).
gurobi
Interface to the GUROBI Solver for quadratic programming
Extra doc: https://github.com/casadi/casadi/wiki/L_22q
List of available options
Id Type Description
gurobi OT_DICT Options to be passed to gurobi.
sos_groups OT_INTVECTORVECTOR Definition of SOS groups by indices.
sos_types OT_INTVECTOR Specify 1 or 2 for each SOS group.
sos_weights OT_DOUBLEVECTORVECTOR Weights corresponding to SOS entries.
vtype OT_STRINGVECTOR Type of variables: [CONTINUOUS|binary|integer|semicont|semiint]
highs
Interface to HiGHS solver for sparse Quadratic Programs, see highs.dev for more information and https://www.maths.ed.ac.uk/hall/HiGHS/HighsOptions.html for a list of options.
Extra doc: https://github.com/casadi/casadi/wiki/L_22f
List of available options
Id Type Description
highs OT_DICT Options to be passed to HiGHS.
hpipm
Interface to HMPC Solver
In order to use this interface, you must:
Decision variables must only by state and control, and the variable ordering must be [x0 u0 x1 u1 ...]
The constraints must be in order: [ gap0 lincon0 gap1 lincon1 ]
gap: Ak+1 = Ak xk + Bk uk lincon: yk= Ck xk + Dk uk
       A0 B0 -I
       C0 D0
              A1 B1 -I
              C1 D1
where I must be a diagonal sparse matrix
Either supply all of N, nx, ng, nu options or rely on automatic detection
Extra doc: https://github.com/casadi/casadi/wiki/L_242
List of available options
Id Type Description
N OT_INT OCP horizon
hpipm OT_DICT Options to be passed to hpipm
inf OT_DOUBLE Replace infinities by this amount [default: 1e8]
ng OT_INTVECTOR Number of non-dynamic constraints, length N+1
nu OT_INTVECTOR Number of controls, length N
nx OT_INTVECTOR Number of states, length N+1
hpmpc
Interface to HMPC Solver
In order to use this interface, you must:
Decision variables must only by state and control, and the variable ordering must be [x0 u0 x1 u1 ...]
The constraints must be in order: [ gap0 lincon0 gap1 lincon1 ]
gap: Ak+1 = Ak xk + Bk uk lincon: yk= Ck xk + Dk uk
       A0 B0 -I
       C0 D0
              A1 B1 -I
              C1 D1
where I must be a diagonal sparse matrix
Either supply all of N, nx, ng, nu options or rely on automatic detection
Extra doc: https://github.com/casadi/casadi/wiki/L_22p
List of available options
Id Type Description
N OT_INT OCP horizon
blasfeo_target OT_STRING hpmpc target
inf OT_DOUBLE HPMPC cannot handle infinities. Infinities will be replaced by this option's value.
max_iter OT_INT Max number of iterations
mu0 OT_DOUBLE Max element in cost function as estimate of max multiplier
ng OT_INTVECTOR Number of non-dynamic constraints, length N+1
nu OT_INTVECTOR Number of controls, length N
nx OT_INTVECTOR Number of states, length N+1
print_level OT_INT Amount of diagnostic printing [Default: 1].
target OT_STRING hpmpc target
tol OT_DOUBLE Tolerance in the duality measure
warm_start OT_BOOL Use warm-starting
ooqp
Interface to the OOQP Solver for quadratic programming The current implementation assumes that OOQP is configured with the MA27 sparse linear solver.
NOTE: when doing multiple calls to evaluate(), check if you need to reInit();
Extra doc: https://github.com/casadi/casadi/wiki/L_222
List of available options
Id Type Description
artol OT_DOUBLE tolerance as provided with setArTol to OOQP
mutol OT_DOUBLE tolerance as provided with setMuTol to OOQP
print_level OT_INT Print level. OOQP listens to print_level 0, 10 and 100
osqp
Interface to the OSQP Solver for quadratic programming
Extra doc: https://github.com/casadi/casadi/wiki/L_220
Interface to the PROXQP Solver for quadratic programming
Extra doc: https://github.com/casadi/casadi/wiki/L_243
List of available options
Id Type Description
osqp OT_DICT const Options to be passed to osqp.
warm_start_dual OT_BOOL Use lam_a0 and lam_x0 input to warmstart [Default: truw].
warm_start_primal OT_BOOL Use x0 input to warmstart [Default: true].
proxqp
List of available options
Id Type Description
proxqp OT_DICT const proxqp options.
warm_start_dual OT_BOOL Use y and z input to warmstart [Default: true].
warm_start_primal OT_BOOL Use x input to warmstart [Default: true].
qpoases
Interface to QPOases Solver for quadratic programming
Extra doc: https://github.com/casadi/casadi/wiki/L_22o
List of available options
Id Type Description
CPUtime OT_DOUBLE The maximum allowed CPU time in seconds for the whole initialisation (and the actually required one on output). Disabled if unset.
boundRelaxation OT_DOUBLE Initial relaxation of bounds to start homotopy and initial value for far bounds.
boundTolerance OT_DOUBLE If upper and lower bounds differ less than this tolerance, they are regarded equal, i.e. as equality constraint.
enableCholeskyRefactorisation OT_INT Specifies the frequency of a full re-factorisation of projected Hessian matrix: 0: turns them off, 1: uses them at each iteration etc.
enableDriftCorrection OT_INT Specifies the frequency of drift corrections: 0: turns them off.
enableEqualities OT_BOOL Specifies whether equalities should be treated as always active (True) or not (False)
enableFarBounds OT_BOOL Enables the use of far bounds.
enableFlippingBounds OT_BOOL Enables the use of flipping bounds.
enableFullLITests OT_BOOL Enables condition-hardened (but more expensive) LI test.
enableInertiaCorrection OT_BOOL Should working set be repaired when negative curvature is discovered during hotstart.
enableNZCTests OT_BOOL Enables nonzero curvature tests.
enableRamping OT_BOOL Enables ramping.
enableRegularisation OT_BOOL Enables automatic Hessian regularisation.
epsDen OT_DOUBLE Denominator tolerance for ratio tests.
epsFlipping OT_DOUBLE Tolerance of squared Cholesky diagonal factor which triggers flipping bound.
epsIterRef OT_DOUBLE Early termination tolerance for iterative refinement.
epsLITests OT_DOUBLE Tolerance for linear independence tests.
epsNZCTests OT_DOUBLE Tolerance for nonzero curvature tests.
epsNum OT_DOUBLE Numerator tolerance for ratio tests.
epsRegularisation OT_DOUBLE Scaling factor of identity matrix used for Hessian regularisation.
finalRamping OT_DOUBLE Final value for ramping strategy.
growFarBounds OT_DOUBLE Factor to grow far bounds.
hessian_type OT_STRING Type of Hessian - see qpOASES documentation [UNKNOWN|posdef|semidef|indef|zero|identity]]
initialFarBounds OT_DOUBLE Initial size for far bounds.
initialRamping OT_DOUBLE Start value for ramping strategy.
initialStatusBounds OT_STRING Initial status of bounds at first iteration.
linsol_plugin OT_STRING Linear solver plugin
maxDualJump OT_DOUBLE Maximum allowed jump in dual variables in linear independence tests.
maxPrimalJump OT_DOUBLE Maximum allowed jump in primal variables in nonzero curvature tests.
max_schur OT_INT Maximal number of Schur updates [75]
nWSR OT_INT The maximum number of working set recalculations to be performed during the initial homotopy. Default is 5(nx + nc)
numRefinementSteps OT_INT Maximum number of iterative refinement steps.
numRegularisationSteps OT_INT Maximum number of successive regularisation steps.
printLevel OT_STRING Defines the amount of text output during QP solution, see Section 5.7
schur OT_BOOL Use Schur Complement Approach [false]
sparse OT_BOOL Formulate the QP using sparse matrices. [false]
terminationTolerance OT_DOUBLE Relative termination tolerance to stop homotopy.
sqic
Interface to the SQIC solver for quadratic programming
Extra doc: https://github.com/casadi/casadi/wiki/L_21s
superscs
Interface to the SuperSCS solver for conic programming
Joris Gillis, 2019
Extra doc: https://github.com/casadi/casadi/wiki/L_21z
List of available options
Id Type Description
superscs OT_DICT Options to be passed to superscs.
ipqp
Solves QPs using a Mehrotra predictor-corrector interior point method
Extra doc: https://github.com/casadi/casadi/wiki/L_23c
List of available options
Id Type Description
constr_viol_tol OT_DOUBLE Constraint violation tolerance [1e-8].
dual_inf_tol OT_DOUBLE Dual feasibility violation tolerance [1e-8]
linear_solver OT_STRING A custom linear solver creator function [default: ldl]
linear_solver_options OT_DICT Options to be passed to the linear solver
max_iter OT_INT Maximum number of iterations [1000].
min_lam OT_DOUBLE Smallest multiplier treated as inactive for the initial active set [0].
print_header OT_BOOL Print header [true].
print_info OT_BOOL Print info [true].
print_iter OT_BOOL Print iterations [true].
nlpsol
Solve QPs using an Nlpsol Use the 'nlpsol' option to specify the NLP solver to use.
Extra doc: https://github.com/casadi/casadi/wiki/L_235
List of available options
Id Type Description
nlpsol OT_STRING Name of solver.
nlpsol_options OT_DICT Options to be passed to solver.
qrqp
Solve QPs using an active-set method
Extra doc: https://github.com/casadi/casadi/wiki/L_22y
List of available options
Id Type Description
constr_viol_tol OT_DOUBLE Constraint violation tolerance [1e-8].
dual_inf_tol OT_DOUBLE Dual feasibility violation tolerance [1e-8]
max_iter OT_INT Maximum number of iterations [1000].
min_lam OT_DOUBLE Smallest multiplier treated as inactive for the initial active set [0].
print_header OT_BOOL Print header [true].
print_info OT_BOOL Print info [true].
print_iter OT_BOOL Print iterations [true].
print_lincomb OT_BOOL Print dependant linear combinations of constraints [false]. Printed numbers are 0-based indices into the vector of [simple bounds;linear bounds]
Author
Joel Andersson
Date
2011-2015
Extra doc: https://github.com/casadi/casadi/wiki/L_21n
Function Documentation
conic()
CASADI_EXPORT Function casadi::conic (const std::string & name, const std::string & solver, const SpDict & qp, const Dict & opts = Dict())
Definition at line 43 of file conic.cpp.
{
     return Function::create(Conic::instantiate(name, solver, qp), opts);
   }
References casadi::Function::create(), and casadi::PluginInterface< Conic >::instantiate().
Referenced by casadi::Feasiblesqpmethod::init(), casadi::Qrsqp::init(), casadi::Scpgen::init(), casadi::Sqpmethod::init(), and casadi::qpsol_nlp().
conic_debug() [1/2]
CASADI_EXPORT void casadi::conic_debug (const Function & f, const std::string & filename)
Generate native code in the interfaced language for debugging
Definition at line 48 of file conic.cpp.
{
     std::ofstream file;
     file.open(filename.c_str());
     conic_debug(f, file);
   }
conic_debug() [2/2]
CASADI_EXPORT void casadi::conic_debug (const Function & f, std::ostream & file)
Generate native code in the interfaced language for debugging
Definition at line 54 of file conic.cpp.
{
     casadi_assert_dev(!f.is_null());
     const Conic* n = f.get<Conic>();
     return n->generateNativeCode(file);
   }
References casadi::Conic::generateNativeCode(), casadi::Function::get(), and casadi::SharedObject::is_null().
conic_in() [1/2]
CASADI_EXPORT std::vector< std::string > casadi::conic_in ()
Extra doc: https://github.com/casadi/casadi/wiki/L_1ee
Definition at line 60 of file conic.cpp.
{
     std::vector<std::string> ret(conic_n_in());
     for (size_t i=0; i<ret.size(); ++i) ret[i]=conic_in(i);
     return ret;
   }
References casadi::conic_n_in().
Referenced by casadi::Conic::get_name_in().
conic_in() [2/2]
CASADI_EXPORT std::string casadi::conic_in (casadi_int ind)
Extra doc: https://github.com/casadi/casadi/wiki/L_1eg
Definition at line 72 of file conic.cpp.
{
     switch (static_cast<ConicInput>(ind)) {
     case CONIC_H:      return "h";
     case CONIC_G:      return "g";
     case CONIC_A:      return "a";
     case CONIC_Q:      return "q";
     case CONIC_P:      return "p";
     case CONIC_LBA:    return "lba";
     case CONIC_UBA:    return "uba";
     case CONIC_LBX:    return "lbx";
     case CONIC_UBX:    return "ubx";
     case CONIC_X0:     return "x0";
     case CONIC_LAM_X0: return "lam_x0";
     case CONIC_LAM_A0: return "lam_a0";
     case CONIC_NUM_IN: break;
     }
     return std::string();
   }
References casadi::CONIC_A, casadi::CONIC_G, casadi::CONIC_H, casadi::CONIC_LAM_A0, casadi::CONIC_LAM_X0, casadi::CONIC_LBA, casadi::CONIC_LBX, casadi::CONIC_NUM_IN, casadi::CONIC_P, casadi::CONIC_Q, casadi::CONIC_UBA, casadi::CONIC_UBX, and casadi::CONIC_X0.
conic_n_in()
CASADI_EXPORT casadi_int casadi::conic_n_in ()
Extra doc: https://github.com/casadi/casadi/wiki/L_1ei
Definition at line 102 of file conic.cpp.
{
     return CONIC_NUM_IN;
   }
References casadi::CONIC_NUM_IN.
Referenced by casadi::conic_in().
conic_n_out()
CASADI_EXPORT casadi_int casadi::conic_n_out ()
Extra doc: https://github.com/casadi/casadi/wiki/L_1ej
Definition at line 106 of file conic.cpp.
{
     return CONIC_NUM_OUT;
   }
References casadi::CONIC_NUM_OUT.
Referenced by casadi::conic_out().
conic_option_info()
CASADI_EXPORT std::string casadi::conic_option_info (const std::string & name, const std::string & op)
Extra doc: https://github.com/casadi/casadi/wiki/L_1em
Definition at line 550 of file conic.cpp.
{
     return Conic::plugin_options(name).info(op);
   }
References casadi::Options::info(), and casadi::PluginInterface< Conic >::plugin_options().
conic_option_type()
CASADI_EXPORT std::string casadi::conic_option_type (const std::string & name, const std::string & op)
Extra doc: https://github.com/casadi/casadi/wiki/L_1el
Definition at line 546 of file conic.cpp.
{
     return Conic::plugin_options(name).type(op);
   }
References casadi::PluginInterface< Conic >::plugin_options(), and casadi::Options::type().
conic_options()
CASADI_EXPORT std::vector< std::string > casadi::conic_options (const std::string & name)
Extra doc: https://github.com/casadi/casadi/wiki/L_1ek
Definition at line 542 of file conic.cpp.
{
     return Conic::plugin_options(name).all();
   }
References casadi::Options::all(), and casadi::PluginInterface< Conic >::plugin_options().
conic_out() [1/2]
CASADI_EXPORT std::vector< std::string > casadi::conic_out ()
Extra doc: https://github.com/casadi/casadi/wiki/L_1ef
Definition at line 66 of file conic.cpp.
{
     std::vector<std::string> ret(conic_n_out());
     for (size_t i=0; i<ret.size(); ++i) ret[i]=conic_out(i);
     return ret;
   }
References casadi::conic_n_out().
Referenced by casadi::Conic::get_name_out().
conic_out() [2/2]
CASADI_EXPORT std::string casadi::conic_out (casadi_int ind)
Extra doc: https://github.com/casadi/casadi/wiki/L_1eh
Definition at line 91 of file conic.cpp.
{
     switch (static_cast<ConicOutput>(ind)) {
     case CONIC_X:     return "x";
     case CONIC_COST:  return "cost";
     case CONIC_LAM_A: return "lam_a";
     case CONIC_LAM_X: return "lam_x";
     case CONIC_NUM_OUT: break;
     }
     return std::string();
   }
References casadi::CONIC_COST, casadi::CONIC_LAM_A, casadi::CONIC_LAM_X, casadi::CONIC_NUM_OUT, and casadi::CONIC_X.
doc_conic()
CASADI_EXPORT std::string casadi::doc_conic (const std::string & name)
Definition at line 39 of file conic.cpp.
{
     return Conic::getPlugin(name).doc;
   }
References casadi::PluginInterface< Conic >::getPlugin().
has_conic()
CASADI_EXPORT bool casadi::has_conic (const std::string & name)
Definition at line 31 of file conic.cpp.
{
     return Conic::has_plugin(name);
   }
References casadi::PluginInterface< Conic >::has_plugin().
load_conic()
CASADI_EXPORT void casadi::load_conic (const std::string & name)
Definition at line 35 of file conic.cpp.
{
     Conic::load_plugin(name);
   }
References casadi::PluginInterface< Conic >::load_plugin().
qpsol() [1/2]
CASADI_EXPORT Function casadi::qpsol (const std::string & name, const std::string & solver, const MXDict & qp, const Dict & opts)
Definition at line 265 of file conic.cpp.
{
     return qpsol_nlp(name, solver, qp, opts);
   }
References casadi::qpsol_nlp().
qpsol() [2/2]
CASADI_EXPORT Function casadi::qpsol (const std::string & name, const std::string & solver, const SXDict & qp, const Dict & opts)
Definition at line 260 of file conic.cpp.
{
     return qpsol_nlp(name, solver, qp, opts);
   }
References casadi::qpsol_nlp().
Referenced by casadi::OptiNode::solve(), and casadi::OptiNode::to_function().