CasADi: casadi::InputStruct Struct Reference
casadi::InputStruct Struct Reference
#include <fmu_function.hpp>
Detailed Description
Definition at line 98 of file fmu_function.hpp.
Static Public Member Functions
static InputStruct parse (const std::string &n, const Fmu *fmu, std::vector< std::string > *name_in=0, std::vector< std::string > *name_out=0)
Public Attributes
InputType type
size_t ind
Member Function Documentation
parse()
InputStruct casadi::InputStruct::parse (const std::string & n, const Fmu * fmu, std::vector< std::string > * name_in = 0, std::vector< std::string > * name_out = 0) static
Definition at line 557 of file fmu_function.cpp.
{
   // Return value
   InputStruct s;
   // Look for a prefix
   if (has_prefix(n)) {
     // Get the prefix
     std::string pref, rem;
     pref = pop_prefix(n, &rem);
     if (pref == "out") {
       if (has_prefix(rem)) {
         // Second order function output (unused): Get the prefix
         pref = pop_prefix(rem, &rem);
         if (pref == "adj") {
           s.type = InputType::ADJ_OUT;
           s.ind = fmu ? fmu->index_in(rem) : -1;
           if (name_in) name_in->push_back(rem);
         } else {
           casadi_error("Cannot process: " + n);
         }
       } else {
         // Nondifferentiated function output (unused)
         s.type = InputType::OUT;
         s.ind = fmu ? fmu->index_out(rem) : -1;
         if (name_out) name_out->push_back(rem);
       }
     } else if (pref == "fwd") {
       // Forward seed
       s.type = InputType::FWD;
       s.ind = fmu ? fmu->index_in(rem) : 0;
       if (name_in) name_in->push_back(rem);
     } else if (pref == "adj") {
       // Adjoint seed
       s.type = InputType::ADJ;
       s.ind = fmu ? fmu->index_out(rem) : 0;
       if (name_out) name_out->push_back(rem);
     } else {
       // No such prefix
       casadi_error("No such prefix: " + pref);
     }
   } else {
     // No prefix - regular input
     s.type = InputType::REG;
     s.ind = fmu ? fmu->index_in(n) : 0;
     if (name_in) name_in->push_back(n);
   }
   // Return input struct
   return s;
 }
References casadi::ADJ, casadi::ADJ_OUT, casadi::FWD, casadi::has_prefix(), ind, casadi::FmuInternal::index_in(), casadi::FmuInternal::index_out(), casadi::OUT, casadi::pop_prefix(), casadi::REG, and type.
Referenced by casadi::FmuFunction::FmuFunction(), and casadi::FmuFunction::identify_io().
Member Data Documentation
ind
size_t casadi::InputStruct::ind
Definition at line 102 of file fmu_function.hpp.
Referenced by parse().
type
InputType casadi::InputStruct::type
Definition at line 100 of file fmu_function.hpp.
Referenced by parse().
The documentation for this struct was generated from the following files:
fmu_function.hpp
fmu_function.cpp