CasADi: casadi::Slice Class Reference
casadi::Slice Class Reference
Class representing a Slice.
#include <slice.hpp>
Detailed Description
Note that Python or Octave do not need to use this class. They can just use slicing utility from the host language (M[0:6] in Python, M(1:7))
Extra doc: https://github.com/casadi/casadi/wiki/L_13
Definition at line 47 of file slice.hpp.
Public Member Functions
Slice ()
Default constructor - all elements.
Slice (casadi_int i, bool ind1=false)
A single element (explicit to avoid ambiguity with IM overload.
Slice (casadi_int start, casadi_int stop, casadi_int step=1)
A slice.
Slice (int start, int stop, int step=1)
Slice (int start, casadi_int stop, int step=1)
Slice (casadi_int start, int stop, int step=1)
std::vector< casadi_int > all () const
Get a vector of indices.
std::vector< casadi_int > all (casadi_int len, bool ind1=false) const
Get a vector of indices.
std::vector< casadi_int > all (const Slice &outer, casadi_int len) const
Get a vector of indices (nested slice)
size_t size () const
Get number of elements.
bool is_empty () const
Check if slice is empty.
bool is_scalar (casadi_int len) const
Is the slice a scalar.
casadi_int scalar (casadi_int len) const
Get scalar (if is_scalar)
bool operator== (const Slice &other) const
Check equality.
bool operator!= (const Slice &other) const
Check inequality.
Slice apply (casadi_int len, bool ind1=false) const
Apply concrete length.
Slice operator- (casadi_int i) const
Substract.
Slice operator* (casadi_int i) const
std::string type_name () const
Get name of the class.
void disp (std::ostream &stream, bool more=false) const
Print a description of the object.
std::string get_str (bool more=false) const
Get string representation.
Dict info () const
void serialize (SerializingStream &s) const
Serialize an object.
Static Public Member Functions
static Slice deserialize (DeserializingStream &s)
Deserialize without type information.
Public Attributes
casadi_int start
start value: negative values will get added to length
casadi_int stop
stop value: use std::numeric_limits<casadi_int>::max() to indicate unboundedness
casadi_int step
Constructor & Destructor Documentation
Slice() [1/6]
casadi::Slice::Slice ()
Definition at line 32 of file slice.cpp.
                : start(0), stop(std::numeric_limits<casadi_int>::max()), step(1) {
   }
Referenced by apply(), deserialize(), operator*(), and operator-().
Slice() [2/6]
casadi::Slice::Slice (casadi_int i, bool ind1 = false) explicit
Definition at line 35 of file slice.cpp.
                                       : start(i-ind1), stop(i-ind1+1), step(1) {
     casadi_assert(!(ind1 && i<=0),
                           "Matlab is 1-based, but requested index " +
                           str(i) +  ". Note that negative slices are"
                           " disabled in the Matlab interface. "
                           "Possibly you may want to use 'end'.");
     if (i==-1) stop = std::numeric_limits<casadi_int>::max();
   }
References stop, and casadi::str().
Slice() [3/6]
casadi::Slice::Slice (casadi_int start, casadi_int stop, casadi_int step = 1)
Definition at line 44 of file slice.cpp.
                                                                  :
     start(start), stop(stop), step(step) { }
Slice() [4/6]
casadi::Slice::Slice (int start, int stop, int step = 1)
Definition at line 47 of file slice.cpp.
                                             : start(start), stop(stop), step(step) {
   }
Slice() [5/6]
casadi::Slice::Slice (int start, casadi_int stop, int step = 1)
Definition at line 49 of file slice.cpp.
                                                    : start(start), stop(stop), step(step) {
   }
Slice() [6/6]
casadi::Slice::Slice (casadi_int start, int stop, int step = 1)
Definition at line 51 of file slice.cpp.
                                                    : start(start), stop(stop), step(step) {
   }
Member Function Documentation
all() [1/3]
std::vector< casadi_int > casadi::Slice::all () const
Definition at line 90 of file slice.cpp.
{
     casadi_assert(start!=std::numeric_limits<casadi_int>::min(), "Need a length");
     casadi_assert(stop!=std::numeric_limits<casadi_int>::max(), "Need a length");
     if ((stop>=start && step<0) ||
         (stop<=start && step>0)) return std::vector<casadi_int>();
     return range(start, stop, step);
   }
References casadi::range(), start, step, and stop.
Referenced by all(), casadi::Matrix< Scalar >::get(), casadi::MX::get(), casadi::MX::get_nz(), casadi::MXNode::get_nz_ref(), casadi::Matrix< Scalar >::set(), casadi::MX::set(), casadi::Matrix< Scalar >::set_nz(), casadi::MX::set_nz(), and size().
all() [2/3]
std::vector< casadi_int > casadi::Slice::all (casadi_int len, bool ind1 = false) const
Definition at line 100 of file slice.cpp.
{
     return apply(len, ind1).all();
   }
References all(), and apply().
all() [3/3]
std::vector< casadi_int > casadi::Slice::all (const Slice & outer, casadi_int len) const
Definition at line 129 of file slice.cpp.
{
     std::vector<casadi_int> ret;
     for (casadi_int i=outer.start; i!=outer.stop; i+=outer.step) {
       for (casadi_int j=i+start; j!=i+stop; j+=step) {
         ret.push_back(j);
       }
     }
     return ret;
   }
References start, step, and stop.
apply()
Slice casadi::Slice::apply (casadi_int len, bool ind1 = false) const
Definition at line 66 of file slice.cpp.
{
     casadi_int start = this->start;
     if (start==std::numeric_limits<casadi_int>::min()) {
       start = (step < 0) ? len - 1 : 0;
     } else if (start<0) {
       start+=len;
     }
     casadi_int stop = this->stop;
     if (stop==std::numeric_limits<casadi_int>::max()) {
       stop = (step < 0) ? -1 : len;
     } else if (stop<0) {
       stop+=len;
     }
     casadi_assert(stop<=len,
       "Slice (start=" + str(start) + ", stop=" + str(stop) + ", step=" + str(step)
       + ") out of bounds with supplied length of " + str(len));
     casadi_assert(start>=0,
       "Slice (start=" + str(start) + ", stop=" + str(stop) + ", step=" + str(step)
       + ") out of bounds with start<0.");
     return Slice(start+ind1, stop+ind1, step);
   }
References Slice(), start, step, stop, and casadi::str().
Referenced by all(), and casadi::MX::get().
deserialize()
Slice casadi::Slice::deserialize (DeserializingStream & s) static
Extra doc: https://github.com/casadi/casadi/wiki/L_15
Definition at line 298 of file slice.cpp.
{
     casadi_int start, stop, step;
     s.unpack("Slice::start", start);
     s.unpack("Slice::stop", stop);
     s.unpack("Slice::step", step);
     return Slice(start, stop, step);
   }
References Slice(), start, step, stop, and casadi::DeserializingStream::unpack().
Referenced by casadi::DeserializingStream::unpack().
disp()
void casadi::Slice::disp (std::ostream & stream, bool more = false) const
Definition at line 115 of file slice.cpp.
{
     bool from_beginning = start == 0;
     bool till_end = stop == std::numeric_limits<casadi_int>::max();
     bool skip_none = step==1;
     if (stop==start+1) {
       stream << start;
     } else {
       if (!from_beginning) stream << start;
       stream << ":";
       if (!till_end) stream << stop;
       if (!skip_none) stream << ":" << step;
     }
   }
References start, step, and stop.
get_str()
std::string casadi::Slice::get_str (bool more = false) const inline
Definition at line 113 of file slice.hpp.
{
       std::stringstream ss;
       disp(ss, more);
       return ss.str();
     }
info()
Dict casadi::Slice::info () const inline
Obtain information
Definition at line 120 of file slice.hpp.
                       {
       return {{"start", start}, {"stop", stop}, {"step", step}};
     }
Referenced by casadi::SubAssign::info(), and casadi::SubRef::info().
is_empty()
bool casadi::Slice::is_empty () const
Definition at line 111 of file slice.cpp.
{
     return size()==0;
   }
References size().
Referenced by casadi::MXNode::get_nzadd().
is_scalar()
bool casadi::Slice::is_scalar (casadi_int len) const
Definition at line 139 of file slice.cpp.
{
     casadi_int start = std::min(this->start, len);
     casadi_int stop = std::min(this->stop, len);
     casadi_int nret = (stop-start)/step + ((stop-start)%step!=0);
     return nret==1;
   }
References start, step, and stop.
Referenced by casadi::Matrix< Scalar >::get(), scalar(), casadi::Matrix< Scalar >::set(), and casadi::Matrix< Scalar >::set_nz().
operator!=()
bool casadi::Slice::operator!= (const Slice & other) const inline
Definition at line 95 of file slice.hpp.
 { return !(*this == other);}
operator*()
Slice casadi::Slice::operator* (casadi_int i) const
Definition at line 60 of file slice.cpp.
{
     return Slice(start==std::numeric_limits<casadi_int>::min() ? start : start*i,
                  stop==std::numeric_limits<casadi_int>::max() ? stop : stop*i,
                  step*i);
   }
References Slice(), start, step, and stop.
operator-()
Slice casadi::Slice::operator- (casadi_int i) const
Definition at line 54 of file slice.cpp.
{
     return Slice(start==std::numeric_limits<casadi_int>::min() ? start : start-i,
                  stop==std::numeric_limits<casadi_int>::max() ? stop : stop-i,
                  step);
   }
References Slice(), start, step, and stop.
operator==()
bool casadi::Slice::operator== (const Slice & other) const inline
Definition at line 90 of file slice.hpp.
{
       return start==other.start && stop==other.stop && step==other.step;
     }
References start, step, and stop.
scalar()
casadi_int casadi::Slice::scalar (casadi_int len) const
Definition at line 146 of file slice.cpp.
{
     casadi_assert_dev(is_scalar(len));
     casadi_assert(start >= -len && start < len, "Slice::getScalar: out of bounds");
     return start >= 0 ? start : start+len;
   }
References is_scalar(), and start.
Referenced by casadi::Matrix< double >::einstein(), casadi::Matrix< Scalar >::get(), casadi::Matrix< double >::operator->(), casadi::Matrix< Scalar >::set(), and casadi::Matrix< Scalar >::set_nz().
serialize()
void casadi::Slice::serialize (SerializingStream & s) const
Extra doc: https://github.com/casadi/casadi/wiki/L_14
Definition at line 292 of file slice.cpp.
{
     s.pack("Slice::start", start);
     s.pack("Slice::stop", stop);
     s.pack("Slice::step", step);
   }
References casadi::SerializingStream::pack(), start, step, and stop.
Referenced by casadi::SerializingStream::pack().
size()
size_t casadi::Slice::size () const
Definition at line 104 of file slice.cpp.
{
     casadi_assert(start!=std::numeric_limits<casadi_int>::min() &&
                   stop!=std::numeric_limits<casadi_int>::max(),
                   "Cannot determine numel of slice.");
     return all(std::numeric_limits<casadi_int>::max()).size();
   }
References all(), start, and stop.
Referenced by casadi::GetNonzerosParam::create(), and is_empty().
type_name()
std::string casadi::Slice::type_name () const inline
Definition at line 107 of file slice.hpp.
 {return "Slice";}
Member Data Documentation
start
casadi_int casadi::Slice::start
Definition at line 51 of file slice.hpp.
Referenced by all(), apply(), casadi::SetNonzeros< Add >::create(), casadi::GetNonzeros::create(), deserialize(), disp(), casadi::GetNonzerosSliceParam::eval(), casadi::GetNonzerosParamSlice::eval(), casadi::GetNonzerosSlice::eval_gen(), casadi::GetNonzerosSlice2::eval_gen(), casadi::GetNonzerosSlice::generate(), casadi::GetNonzerosSlice2::generate(), casadi::GetNonzerosSliceParam::generate(), casadi::GetNonzerosParamSlice::generate(), is_scalar(), operator*(), operator-(), operator==(), scalar(), serialize(), size(), casadi::GetNonzerosSlice::sp_forward(), casadi::GetNonzerosSlice2::sp_forward(), casadi::GetNonzerosSlice::sp_reverse(), casadi::GetNonzerosSlice2::sp_reverse(), casadi::to_slice(), and casadi::to_slice2().
step
casadi_int casadi::Slice::step
Definition at line 54 of file slice.hpp.
Referenced by all(), apply(), casadi::SetNonzeros< Add >::create(), casadi::GetNonzeros::create(), deserialize(), disp(), casadi::GetNonzerosSliceParam::eval(), casadi::GetNonzerosParamSlice::eval(), casadi::GetNonzerosSlice::eval_gen(), casadi::GetNonzerosSlice2::eval_gen(), casadi::GetNonzerosSlice::generate(), casadi::GetNonzerosSlice2::generate(), casadi::GetNonzerosSliceParam::generate(), casadi::GetNonzerosParamSlice::generate(), is_scalar(), operator*(), operator-(), operator==(), serialize(), casadi::GetNonzerosSlice::sp_forward(), casadi::GetNonzerosSlice2::sp_forward(), casadi::GetNonzerosSlice::sp_reverse(), casadi::GetNonzerosSlice2::sp_reverse(), casadi::to_slice(), and casadi::to_slice2().
stop
casadi_int casadi::Slice::stop
Definition at line 53 of file slice.hpp.
Referenced by all(), apply(), casadi::SetNonzeros< Add >::create(), casadi::GetNonzeros::create(), deserialize(), disp(), casadi::GetNonzerosSliceParam::eval(), casadi::GetNonzerosParamSlice::eval(), casadi::GetNonzerosSlice::eval_gen(), casadi::GetNonzerosSlice2::eval_gen(), casadi::GetNonzerosSlice::generate(), casadi::GetNonzerosSlice2::generate(), casadi::GetNonzerosSliceParam::generate(), casadi::GetNonzerosParamSlice::generate(), is_scalar(), operator*(), operator-(), operator==(), serialize(), size(), Slice(), casadi::GetNonzerosSlice::sp_forward(), casadi::GetNonzerosSlice2::sp_forward(), casadi::GetNonzerosSlice::sp_reverse(), casadi::GetNonzerosSlice2::sp_reverse(), casadi::to_slice(), and casadi::to_slice2().
The documentation for this class was generated from the following files:
slice.hpp
slice.cpp