CasADi: casadi::Constant< Value > Class Template Reference
casadi::Constant< Value > Class Template Reference
A constant with all entries identical.
#include <constant_mx.hpp>
Detailed Description
template<typename Value>
class casadi::Constant< Value >
Definition at line 502 of file constant_mx.hpp.
Public Member Functions
Constant (const Sparsity &sp, Value v=Value())
Constructor.
Constant (DeserializingStream &s, const Value &v)
Deserializing constructor.
~Constant () override
Destructor.
std::string disp (const std::vector< std::string > &arg) const override
Print expression.
int eval (const double **arg, double **res, casadi_int *iw, double *w) const override
Evaluate the function numerically.
int eval_sx (const SXElem **arg, SXElem **res, casadi_int *iw, SXElem *w) const override
Evaluate the function symbolically (SX)
void generate (CodeGenerator &g, const std::vector< casadi_int > &arg, const std::vector< casadi_int > &res) const override
Generate code for the operation.
bool is_zero () const override
Check if a particular integer value.
bool is_one () const override
Check if identically one.
bool is_eye () const override
Check if identity matrix.
bool is_value (double val) const override
Check if a certain value.
double to_double () const override
Get the value (only for scalar constant nodes)
Matrix< double > get_DM () const override
Get the value (only for constant nodes)
MX get_project (const Sparsity &sp) const override
Get densification.
MX get_nzref (const Sparsity &sp, const std::vector< casadi_int > &nz) const override
Get the nonzeros of matrix.
MX get_nzassign (const MX &y, const std::vector< casadi_int > &nz) const override
Assign the nonzeros of a matrix to another matrix.
MX get_transpose () const override
Transpose.
MX get_unary (casadi_int op) const override
Get a unary operation.
MX _get_binary (casadi_int op, const MX &y, bool ScX, bool ScY) const override
Get a binary operation operation.
MX get_reshape (const Sparsity &sp) const override
Reshape.
MX get_horzcat (const std::vector< MX > &x) const override
Create a horizontal concatenation node.
MX get_vertcat (const std::vector< MX > &x) const override
Create a vertical concatenation node (vectors only)
bool is_equal (const MXNode *node, casadi_int depth) const override
Check if two nodes are equivalent up to a given depth.
void serialize_body (SerializingStream &s) const override
Serialize an object without type information.
void serialize_type (SerializingStream &s) const override
Serialize type information.
void eval_mx (const std::vector< MX > &arg, std::vector< MX > &res) const override
Evaluate symbolically (MX)
void ad_forward (const std::vector< std::vector< MX > > &fseed, std::vector< std::vector< MX > > &fsens) const override
Calculate forward mode directional derivatives.
void ad_reverse (const std::vector< std::vector< MX > > &aseed, std::vector< std::vector< MX > > &asens) const override
Calculate reverse mode directional derivatives.
int sp_forward (const bvec_t **arg, bvec_t **res, casadi_int *iw, bvec_t *w) const override
Propagate sparsity forward.
int sp_reverse (bvec_t **arg, bvec_t **res, casadi_int *iw, bvec_t *w) const override
Propagate sparsity backwards.
casadi_int op () const override
Get the operation.
MX get_dot (const MX &y) const override
Matrix multiplication.
bool __nonzero__ () const override
Return truth value of an MX.
bool is_valid_input () const override
Check if valid function input.
casadi_int n_primitives () const override
Get the number of symbolic primitives.
void primitives (std::vector< MX >::iterator &it) const override
Get symbolic primitives.
template<typename T >
void split_primitives_gen (const T &x, typename std::vector< T >::iterator &it) const
Split up an expression along primitives (template)
template<typename T >
T join_primitives_gen (typename std::vector< T >::const_iterator &it) const
Join an expression along symbolic primitives (template)
bool has_duplicates () const override
Detect duplicate symbolic expressions.
void reset_input () const override
Reset the marker for an input expression.
virtual bool is_minus_one () const
Check if identically minus one.
virtual bool is_unary () const
Check if unary operation.
virtual bool is_binary () const
Check if binary operation.
void can_inline (std::map< const MXNode *, casadi_int > &nodeind) const
Find out which nodes can be inlined.
std::string print_compact (std::map< const MXNode *, casadi_int > &nodeind, std::vector< std::string > &intermed) const
Print compact.
void disp (std::ostream &stream, bool more) const override
Print a description.
virtual void add_dependency (CodeGenerator &g) const
Add a dependent function.
virtual bool has_refcount () const
Is reference counting needed in codegen?
virtual void codegen_incref (CodeGenerator &g, std::set< void * > &added) const
Codegen incref.
virtual void codegen_decref (CodeGenerator &g, std::set< void * > &added) const
Codegen decref.
virtual const std::string & name () const
Get the name.
std::string class_name () const override
Get name of public class.
virtual bool is_output () const
Check if evaluation output.
virtual bool has_output () const
Check if a multiple output node.
virtual casadi_int which_output () const
Get function output.
virtual const Function & which_function () const
Get called function.
virtual Dict info () const
void serialize (SerializingStream &s) const
Serialize an object.
bool sameOpAndDeps (const MXNode *node, casadi_int depth) const
Checks if two nodes have the same operation and have.
const MX & dep (casadi_int ind=0) const
dependencies - functions that have to be evaluated before this one
casadi_int n_dep () const
Number of dependencies.
virtual casadi_int nout () const
Number of outputs.
virtual MX get_output (casadi_int oind) const
Get an output.
const Sparsity & sparsity () const
Get the sparsity.
virtual const Sparsity & sparsity (casadi_int oind) const
Get the sparsity of output oind.
template<class T >
bool matches_sparsity (const std::vector< T > &arg) const
casadi_int numel () const
Get shape.
casadi_int nnz (casadi_int i=0) const
casadi_int size1 () const
casadi_int size2 () const
std::pair< casadi_int, casadi_int > size () const
virtual casadi_int ind () const
virtual casadi_int segment () const
virtual casadi_int offset () const
void set_sparsity (const Sparsity &sparsity)
Set the sparsity.
virtual size_t sz_arg () const
Get required length of arg field.
virtual size_t sz_res () const
Get required length of res field.
virtual size_t sz_iw () const
Get required length of iw field.
virtual size_t sz_w () const
Get required length of w field.
void set_dep (const MX &dep)
Set unary dependency.
void set_dep (const MX &dep1, const MX &dep2)
Set binary dependencies.
void set_dep (const MX &dep1, const MX &dep2, const MX &dep3)
Set ternary dependencies.
void set_dep (const std::vector< MX > &dep)
Set multiple dependencies.
virtual casadi_int n_inplace () const
Can the operation be performed inplace (i.e. overwrite the result)
virtual Matrix< casadi_int > mapping () const
Get an IM representation of a GetNonzeros or SetNonzeros node.
virtual std::vector< MX > get_horzsplit (const std::vector< casadi_int > &output_offset) const
Create a horizontal split node.
virtual MX get_repmat (casadi_int m, casadi_int n) const
Create a repeated matrix node.
virtual MX get_repsum (casadi_int m, casadi_int n) const
Create a repeated sum node.
virtual std::vector< MX > get_vertsplit (const std::vector< casadi_int > &output_offset) const
Create a vertical split node (vectors only)
virtual MX get_diagcat (const std::vector< MX > &x) const
Create a diagonal concatenation node.
virtual std::vector< MX > get_diagsplit (const std::vector< casadi_int > &offset1, const std::vector< casadi_int > &offset2) const
Create a diagonal split node.
virtual MX get_sparsity_cast (const Sparsity &sp) const
Sparsity cast.
virtual MX get_mac (const MX &y, const MX &z) const
Matrix multiplication and addition.
virtual MX get_einstein (const MX &A, const MX &B, const std::vector< casadi_int > &dim_c, const std::vector< casadi_int > &dim_a, const std::vector< casadi_int > &dim_b, const std::vector< casadi_int > &c, const std::vector< casadi_int > &a, const std::vector< casadi_int > &b) const
Einstein product and addition.
virtual MX get_bilin (const MX &x, const MX &y) const
Bilinear form.
virtual MX get_rank1 (const MX &alpha, const MX &x, const MX &y) const
Bilinear form.
virtual MX get_logsumexp () const
Logsumexp.
virtual MX get_solve (const MX &r, bool tr, const Linsol &linear_solver) const
Solve a system of linear equations.
virtual MX get_solve_triu (const MX &r, bool tr) const
Solve a system of linear equations, upper triangular A.
virtual MX get_solve_tril (const MX &r, bool tr) const
Solve a system of linear equations, lower triangular A.
virtual MX get_solve_triu_unity (const MX &r, bool tr) const
Solve a system of linear equations, upper triangular A, unity diagonal.
virtual MX get_solve_tril_unity (const MX &r, bool tr) const
Solve a system of linear equations, lower triangular A, unity diagnal.
virtual MX get_nz_ref (const MX &nz) const
Get the nonzeros of matrix, parametrically.
virtual MX get_nz_ref (const MX &inner, const Slice &outer) const
Get the nonzeros of matrix, parametrically.
virtual MX get_nz_ref (const Slice &inner, const MX &outer) const
Get the nonzeros of matrix, parametrically.
virtual MX get_nz_ref (const MX &inner, const MX &outer) const
Get the nonzeros of matrix, parametrically.
virtual MX get_nzassign (const MX &y, const MX &nz) const
Assign the nonzeros of a matrix to another matrix, parametrically.
virtual MX get_nzassign (const MX &y, const MX &inner, const Slice &outer) const
Assign the nonzeros of a matrix to another matrix, parametrically.
virtual MX get_nzassign (const MX &y, const Slice &inner, const MX &outer) const
Assign the nonzeros of a matrix to another matrix, parametrically.
virtual MX get_nzassign (const MX &y, const MX &inner, const MX &outer) const
Assign the nonzeros of a matrix to another matrix, parametrically.
virtual MX get_nzadd (const MX &y, const std::vector< casadi_int > &nz) const
Add the nonzeros of a matrix to another matrix.
virtual MX get_nzadd (const MX &y, const MX &nz) const
Add the nonzeros of a matrix to another matrix, parametrically.
virtual MX get_nzadd (const MX &y, const MX &inner, const Slice &outer) const
Add the nonzeros of a matrix to another matrix, parametrically.
virtual MX get_nzadd (const MX &y, const Slice &inner, const MX &outer) const
Add the nonzeros of a matrix to another matrix, parametrically.
virtual MX get_nzadd (const MX &y, const MX &inner, const MX &outer) const
Add the nonzeros of a matrix to another matrix, parametrically.
virtual MX get_subref (const Slice &i, const Slice &j) const
Get submatrix reference.
virtual MX get_subassign (const MX &y, const Slice &i, const Slice &j) const
Get submatrix assignment.
MX get_binary (casadi_int op, const MX &y) const
Get a binary operation operation.
virtual MX get_det () const
Determinant.
virtual MX get_inv () const
Inverse.
virtual MX get_norm_fro () const
Frobenius norm.
virtual MX get_norm_2 () const
Spectral norm.
virtual MX get_norm_inf () const
Infinity norm.
virtual MX get_norm_1 () const
1-norm
virtual MX get_mmin () const
Min.
virtual MX get_mmax () const
Max.
MX get_assert (const MX &y, const std::string &fail_message) const
Assertion.
MX get_monitor (const std::string &comment) const
Monitor.
MX get_find () const
Find.
MX get_low (const MX &v, const Dict &options) const
Find.
MX get_bspline (const std::vector< double > &knots, const std::vector< casadi_int > &offset, const std::vector< double > &coeffs, const std::vector< casadi_int > &degree, casadi_int m, const std::vector< casadi_int > &lookup_mode) const
BSpline.
MX get_bspline (const MX &coeffs, const std::vector< double > &knots, const std::vector< casadi_int > &offset, const std::vector< casadi_int > &degree, casadi_int m, const std::vector< casadi_int > &lookup_mode) const
BSpline.
MX get_convexify (const Dict &opts) const
Convexify.
casadi_int getCount () const
Get the reference count.
WeakRef * weak ()
Get a weak reference to the object.
void split_primitives (const MX &x, std::vector< MX >::iterator &it) const override
Split up an expression along symbolic primitives.
void split_primitives (const SX &x, std::vector< SX >::iterator &it) const override
Split up an expression along symbolic primitives.
void split_primitives (const DM &x, std::vector< DM >::iterator &it) const override
Split up an expression along symbolic primitives.
MX join_primitives (std::vector< MX >::const_iterator &it) const override
Join an expression along symbolic primitives.
SX join_primitives (std::vector< SX >::const_iterator &it) const override
Join an expression along symbolic primitives.
DM join_primitives (std::vector< DM >::const_iterator &it) const override
Join an expression along symbolic primitives.
Static Public Member Functions
static ConstantMX * create (const Sparsity &sp, casadi_int val)
static ConstantMX * create (const Sparsity &sp, int val)
static ConstantMX * create (const Sparsity &sp, double val)
static ConstantMX * create (const Matrix< double > &val)
static ConstantMX * create (const Sparsity &sp, const std::string &fname)
static MXNode * deserialize (DeserializingStream &s)
Deserialize with type disambiguation.
static bool is_equal (const MXNode *x, const MXNode *y, casadi_int depth)
Check if two nodes are equivalent up to a given depth.
static bool maxDepth ()
Get equality checking depth.
static MX to_matrix (const MX &x, const Sparsity &sp)
Convert scalar to matrix.
static void copy_fwd (const bvec_t *arg, bvec_t *res, casadi_int len)
Propagate sparsities forward through a copy operation.
static void copy_rev (bvec_t *arg, bvec_t *res, casadi_int len)
Propagate sparsities backwards through a copy operation.
Public Attributes
Value v_
casadi_int temp
std::vector< MX > dep_
dependencies - functions that have to be evaluated before this one
Sparsity sparsity_
The sparsity pattern.
Static Public Attributes
static std::map< casadi_int, MXNode *(*)(DeserializingStream &)> deserialize_map
Protected Member Functions
void initSingleton ()
void destroySingleton ()
template<class B >
B shared_from_this ()
Get a shared object from the current internal object.
template<class B >
const B shared_from_this () const
Get a shared object from the current internal object.
Constructor & Destructor Documentation
Constant() [1/2]
template<typename Value > casadi::Constant< Value >::Constant (const Sparsity & sp, Value v = Value()) inline explicit
Extra doc: https://github.com/casadi/casadi/wiki/L_107
Definition at line 508 of file constant_mx.hpp.
 : ConstantMX(sp), v_(v) {}
Constant() [2/2]
template<typename Value > casadi::Constant< Value >::Constant (DeserializingStream & s, const Value & v) explicit
Extra doc: https://github.com/casadi/casadi/wiki/L_108
Definition at line 614 of file constant_mx.hpp.
                                                                   : ConstantMX(s), v_(v) {
   }
~Constant()
template<typename Value > casadi::Constant< Value >::~Constant () inline override
Definition at line 516 of file constant_mx.hpp.
 {}
Member Function Documentation
__nonzero__()
bool casadi::ConstantMX::__nonzero__ () const override virtual inherited
Reimplemented from casadi::MXNode.
Definition at line 139 of file constant_mx.cpp.
{
     if (numel()!=1) casadi_error("Can only determine truth value of scalar MX.");
     if (nnz()!=1) casadi_error("Can only determine truth value of dense scalar MX.");
     return !is_zero();
   }
References casadi::MXNode::is_zero(), casadi::MXNode::nnz(), and casadi::MXNode::numel().
_get_binary()
template<typename Value > MX casadi::Constant< Value >::_get_binary (casadi_int op, const MX & y, bool ScX, bool ScY) const override virtual
Reimplemented from casadi::MXNode.
Definition at line 682 of file constant_mx.hpp.
{
     casadi_assert_dev(sparsity()==y.sparsity() || ScX || ScY);
     if (ScX && !operation_checker<FX0Checker>(op)) {
       double ret;
       casadi_math<double>::fun(op, nnz()> 0 ? to_double(): 0.0, 0, ret);
       if (ret!=0) {
         Sparsity f = Sparsity::dense(y.size1(), y.size2());
         MX yy = project(y, f);
         return MX(f, shared_from_this<MX>())->_get_binary(op, yy, false, false);
       }
     } else if (ScY && !operation_checker<F0XChecker>(op)) {
       bool grow = true;
       if (y->op()==OP_CONST && dynamic_cast<const ConstantDM*>(y.get())==nullptr) {
         double ret;
         casadi_math<double>::fun(op, 0, y.nnz()>0 ? y->to_double() : 0, ret);
         grow = ret!=0;
       }
       if (grow) {
         Sparsity f = Sparsity::dense(size1(), size2());
         MX xx = project(shared_from_this<MX>(), f);
         return xx->_get_binary(op, MX(f, y), false, false);
       }
     }
     switch (op) {
     case OP_ADD:
       if (v_.value==0) return ScY && !y->is_zero() ? repmat(y, size1(), size2()) : y;
       break;
     case OP_SUB:
       if (v_.value==0) return ScY && !y->is_zero() ? repmat(-y, size1(), size2()) : -y;
       break;
     case OP_MUL:
       if (v_.value==1) return y;
       if (v_.value==-1) return -y;
       if (v_.value==2) return y->get_unary(OP_TWICE);
       break;
     case OP_DIV:
       if (v_.value==1) return y->get_unary(OP_INV);
       if (v_.value==-1) return -y->get_unary(OP_INV);
       break;
     case OP_POW:
       if (v_.value==0) return MX::zeros(y.sparsity());
       if (v_.value==1) return MX::ones(y.sparsity());
       if (v_.value==std::exp(1.0)) return y->get_unary(OP_EXP);
       break;
     default: break; //no rule
     }
     // Constant folding
     // NOTE: ugly, should use a function instead of a cast
     if (y->op()==OP_CONST && dynamic_cast<const ConstantDM*>(y.get())==nullptr) {
       double y_value = y.nnz()>0 ? y->to_double() : 0;
       double ret;
       casadi_math<double>::fun(op, nnz()> 0.0 ? to_double(): 0, y_value, ret);
       return MX(y.sparsity(), ret, false);
     }
     // Fallback
     return MXNode::_get_binary(op, y, ScX, ScY);
   }
References casadi::MXNode::_get_binary(), casadi::Sparsity::dense(), casadi::casadi_math< T >::fun(), casadi::MX::get(), casadi::MXNode::get_unary(), casadi::MXNode::is_zero(), casadi::GenericMatrix< MatType >::nnz(), casadi::GenericMatrix< MX >::ones(), casadi::MXNode::op(), casadi::OP_ADD, casadi::OP_CONST, casadi::OP_DIV, casadi::OP_EXP, casadi::OP_INV, casadi::OP_MUL, casadi::OP_POW, casadi::OP_SUB, casadi::OP_TWICE, casadi::GenericMatrix< MatType >::size1(), casadi::GenericMatrix< MatType >::size2(), casadi::MX::sparsity(), casadi::MXNode::to_double(), and casadi::GenericMatrix< MX >::zeros().
ad_forward()
void casadi::ConstantMX::ad_forward (const std::vector< std::vector< MX > > & fseed, std::vector< std::vector< MX > > & fsens) const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_yw
Reimplemented from casadi::MXNode.
Definition at line 107 of file constant_mx.cpp.
{
    MX zero_sens(size1(), size2());
    for (casadi_int d=0; d<fsens.size(); ++d) {
      fsens[d][0] = zero_sens;
    }
  }
References casadi::MXNode::size1(), and casadi::MXNode::size2().
ad_reverse()
void casadi::ConstantMX::ad_reverse (const std::vector< std::vector< MX > > & aseed, std::vector< std::vector< MX > > & asens) const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_yx
Reimplemented from casadi::MXNode.
Definition at line 115 of file constant_mx.cpp.
{
   }
add_dependency()
virtual void casadi::MXNode::add_dependency (CodeGenerator & g) const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1qo
Reimplemented in casadi::ConstantFile, and casadi::Call.
Definition at line 121 of file mx_node.hpp.
 {}
can_inline()
void casadi::MXNode::can_inline (std::map< const MXNode *, casadi_int > & nodeind) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1ql
Definition at line 270 of file mx_node.cpp.
{
     // Add or mark node in map
     std::map<const MXNode*, casadi_int>::iterator it=nodeind.find(this);
     if (it==nodeind.end()) {
       // First time encountered, mark inlined
       nodeind.insert(it, std::make_pair(this, 0));
       // Handle dependencies with recursion
       for (casadi_int i=0; i<n_dep(); ++i) {
         dep(i)->can_inline(nodeind);
       }
     } else if (it->second==0 && op()!=OP_PARAMETER) {
       // Node encountered before, do not inline (except if symbolic primitive)
       it->second = -1;
     }
   }
References casadi::MXNode::can_inline(), casadi::MXNode::dep(), casadi::MXNode::n_dep(), casadi::MXNode::op(), and casadi::OP_PARAMETER.
Referenced by casadi::MXNode::can_inline(), and casadi::MXNode::disp().
class_name()
std::string casadi::MXNode::class_name () const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1r1
Implements casadi::SharedObjectInternal.
Definition at line 197 of file mx_node.cpp.
{
     // Lazy solution
     return typeid(*this).name();
   }
Referenced by casadi::MXNode::ad_forward(), casadi::MXNode::ad_reverse(), casadi::MXNode::eval(), casadi::MXNode::eval_mx(), casadi::MXNode::eval_sx(), casadi::MXNode::generate(), casadi::MXNode::get_DM(), casadi::MXNode::has_duplicates(), casadi::MXNode::ind(), casadi::MXNode::mapping(), casadi::MXNode::name(), casadi::MXNode::offset(), casadi::MXNode::reset_input(), casadi::MXNode::segment(), casadi::MXNode::to_double(), casadi::MXNode::which_function(), and casadi::MXNode::which_output().
codegen_decref()
virtual void casadi::MXNode::codegen_decref (CodeGenerator & g, std::set< void * > & added) const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1qr
Reimplemented in casadi::Call.
Definition at line 136 of file mx_node.hpp.
 {}
codegen_incref()
virtual void casadi::MXNode::codegen_incref (CodeGenerator & g, std::set< void * > & added) const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1qq
Reimplemented in casadi::ConstantFile, and casadi::Call.
Definition at line 131 of file mx_node.hpp.
 {}
copy_fwd()
void casadi::MXNode::copy_fwd (const bvec_t * arg, bvec_t * res, casadi_int len) static inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1sl
Definition at line 1169 of file mx_node.cpp.
{
     if (arg!=res) {
       std::copy(arg, arg+len, res);
     }
   }
Referenced by casadi::Multiplication::sp_forward(), casadi::Reshape::sp_forward(), casadi::SparsityCast::sp_forward(), and casadi::UnaryMX::sp_forward().
copy_rev()
void casadi::MXNode::copy_rev (bvec_t * arg, bvec_t * res, casadi_int len) static inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1sm
Definition at line 1175 of file mx_node.cpp.
{
     if (arg!=res) {
       for (casadi_int k=0; k<len; ++k) {
         *arg++ |= *res;
         *res++ = 0;
       }
     }
   }
Referenced by casadi::Einstein::sp_reverse(), casadi::Multiplication::sp_reverse(), casadi::Rank1::sp_reverse(), casadi::Reshape::sp_reverse(), casadi::SetNonzerosVector< Add >::sp_reverse(), casadi::SetNonzerosSlice< Add >::sp_reverse(), casadi::SetNonzerosSlice2< Add >::sp_reverse(), casadi::SparsityCast::sp_reverse(), and casadi::UnaryMX::sp_reverse().
create() [1/5]
ConstantMX * casadi::ConstantMX::create (const Matrix< double > & val) static inherited
Definition at line 171 of file constant_mx.cpp.
{
     if (val.nnz()==0) {
       return create(val.sparsity(), 0);
     } else if (val.is_scalar()) {
       return create(val.sparsity(), val.scalar());
     } else {
       // Check if all values are the same
       const std::vector<double> vdata = val.nonzeros();
       double v = vdata[0];
       for (auto&& i : vdata) {
         if (i!=v) {
           // Values not all the same
           return new ConstantDM(val);
         }
       }
       // All values identical if reached this point
       return create(val.sparsity(), v);
     }
   }
References casadi::ConstantMX::create(), casadi::GenericMatrix< MatType >::is_scalar(), casadi::GenericMatrix< MatType >::nnz(), casadi::Matrix< Scalar >::nonzeros(), casadi::Matrix< Scalar >::scalar(), and casadi::Matrix< Scalar >::sparsity().
create() [2/5]
ConstantMX * casadi::ConstantMX::create (const Sparsity & sp, casadi_int val) static inherited
Definition at line 145 of file constant_mx.cpp.
{
     if (sp.is_empty(true)) {
       return ZeroByZero::getInstance();
     } else {
       switch (val) {
       case 0: return new Constant<CompiletimeConst<0> >(sp);
       case 1: return new Constant<CompiletimeConst<1> >(sp);
       case -1: return new Constant<CompiletimeConst<(-1)> >(sp);
       default: return new Constant<RuntimeConst<casadi_int> >(sp, val);
       }
     }
   }
References casadi::ZeroByZero::getInstance(), and casadi::Sparsity::is_empty().
Referenced by casadi::ConstantMX::create(), casadi::MX::inf(), casadi::MX::MX(), and casadi::MX::nan().
create() [3/5]
ConstantMX * casadi::ConstantMX::create (const Sparsity & sp, const std::string & fname) static inherited
Definition at line 192 of file constant_mx.cpp.
{
     if (sp.nnz()==0) {
       return create(sp, 0);
     } else {
       return new ConstantFile(sp, fname);
     }
   }
References casadi::ConstantMX::create(), and casadi::Sparsity::nnz().
create() [4/5]
ConstantMX * casadi::ConstantMX::create (const Sparsity & sp, double val) static inherited
Definition at line 158 of file constant_mx.cpp.
{
     if (sp.is_empty(true)) {
       return ZeroByZero::getInstance();
     } else {
       casadi_int intval = static_cast<casadi_int>(val);
       if (static_cast<double>(intval)-val==0) {
         return create(sp, intval);
       } else {
         return new Constant<RuntimeConst<double> >(sp, val);
       }
     }
   }
References casadi::ConstantMX::create(), casadi::ZeroByZero::getInstance(), and casadi::Sparsity::is_empty().
create() [5/5]
static ConstantMX* casadi::ConstantMX::create (const Sparsity & sp, int val) inline static inherited
Definition at line 58 of file constant_mx.hpp.
{
       return create(sp, static_cast<casadi_int>(val));
     }
dep()
const MX& casadi::MXNode::dep (casadi_int ind = 0) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1rm
Definition at line 319 of file mx_node.hpp.
 { return dep_.at(ind);}
Referenced by casadi::MXNode::_get_binary(), casadi::UnaryMX::_get_binary(), casadi::Bilin::ad_forward(), casadi::Call::ad_forward(), casadi::Determinant::ad_forward(), casadi::Dot::ad_forward(), casadi::Einstein::ad_forward(), casadi::GetNonzeros::ad_forward(), casadi::GetNonzerosParamVector::ad_forward(), casadi::GetNonzerosSliceParam::ad_forward(), casadi::GetNonzerosParamSlice::ad_forward(), casadi::GetNonzerosParamParam::ad_forward(), casadi::LogSumExp::ad_forward(), casadi::MMin::ad_forward(), casadi::MMax::ad_forward(), casadi::Multiplication::ad_forward(), casadi::NormF::ad_forward(), casadi::Project::ad_forward(), casadi::Rank1::ad_forward(), casadi::SparsityCast::ad_forward(), casadi::UnaryMX::ad_forward(), casadi::Bilin::ad_reverse(), casadi::Call::ad_reverse(), casadi::Determinant::ad_reverse(), casadi::Dot::ad_reverse(), casadi::Einstein::ad_reverse(), casadi::GetNonzeros::ad_reverse(), casadi::GetNonzerosParamVector::ad_reverse(), casadi::GetNonzerosSliceParam::ad_reverse(), casadi::GetNonzerosParamSlice::ad_reverse(), casadi::GetNonzerosParamParam::ad_reverse(), casadi::LogSumExp::ad_reverse(), casadi::MMin::ad_reverse(), casadi::MMax::ad_reverse(), casadi::Multiplication::ad_reverse(), casadi::NormF::ad_reverse(), casadi::Project::ad_reverse(), casadi::Rank1::ad_reverse(), casadi::Reshape::ad_reverse(), casadi::SparsityCast::ad_reverse(), casadi::UnaryMX::ad_reverse(), casadi::MXNode::can_inline(), casadi::MX::dep(), casadi::Reshape::disp(), casadi::Find::eval(), casadi::Low::eval(), casadi::GetNonzerosParamVector::eval(), casadi::GetNonzerosSliceParam::eval(), casadi::GetNonzerosParamSlice::eval(), casadi::GetNonzerosParamParam::eval(), casadi::MMin::eval(), casadi::MMax::eval(), casadi::Bilin::eval_gen(), casadi::Dot::eval_gen(), casadi::Einstein::eval_gen(), casadi::LogSumExp::eval_gen(), casadi::Multiplication::eval_gen(), casadi::NormF::eval_gen(), casadi::Project::eval_gen(), casadi::Densify::eval_gen(), casadi::Rank1::eval_gen(), casadi::HorzRepmat::eval_gen(), casadi::Concat::eval_gen(), casadi::Transpose::eval_gen(), casadi::DenseTranspose::eval_gen(), casadi::GetNonzeros::eval_mx(), casadi::GetNonzerosParamVector::eval_mx(), casadi::GetNonzerosSliceParam::eval_mx(), casadi::GetNonzerosParamSlice::eval_mx(), casadi::GetNonzerosParamParam::eval_mx(), casadi::MMin::eval_sx(), casadi::MMax::eval_sx(), casadi::BSplineParametric::generate(), casadi::Bilin::generate(), casadi::Find::generate(), casadi::Low::generate(), casadi::Concat::generate(), casadi::Convexify::generate(), casadi::Dot::generate(), casadi::Einstein::generate(), casadi::GetNonzerosVector::generate(), casadi::GetNonzerosSlice::generate(), casadi::GetNonzerosSlice2::generate(), casadi::GetNonzerosParamVector::generate(), casadi::GetNonzerosSliceParam::generate(), casadi::GetNonzerosParamSlice::generate(), casadi::GetNonzerosParamParam::generate(), casadi::Output::generate(), casadi::LogSumExp::generate(), casadi::MMin::generate(), casadi::MMax::generate(), casadi::Monitor::generate(), casadi::Multiplication::generate(), casadi::DenseMultiplication::generate(), casadi::NormF::generate(), casadi::Project::generate(), casadi::Densify::generate(), casadi::Sparsify::generate(), casadi::Rank1::generate(), casadi::HorzRepmat::generate(), casadi::HorzRepsum::generate(), casadi::Split::generate(), casadi::Transpose::generate(), casadi::DenseTranspose::generate(), casadi::MXNode::get_binary(), casadi::Diagsplit::get_diagcat(), casadi::Horzsplit::get_horzcat(), casadi::MXNode::get_horzsplit(), casadi::Concat::get_nzref(), casadi::GetNonzeros::get_nzref(), casadi::SparsityCast::get_nzref(), casadi::Reshape::get_reshape(), casadi::SparsityCast::get_reshape(), casadi::SparsityCast::get_sparsity_cast(), casadi::Reshape::get_transpose(), casadi::SparsityCast::get_transpose(), casadi::UnaryMX::get_unary(), casadi::Vertsplit::get_vertcat(), casadi::MXNode::get_vertsplit(), casadi::Concat::has_duplicates(), casadi::Reshape::has_duplicates(), casadi::SparsityCast::has_duplicates(), casadi::BinaryMX< ScX, ScY >::is_equal(), casadi::Concat::is_valid_input(), casadi::Reshape::is_valid_input(), casadi::SparsityCast::is_valid_input(), casadi::BSpline::jac_cached(), casadi::BSplineParametric::jac_cached(), casadi::Horzcat::join_primitives_gen(), casadi::Vertcat::join_primitives_gen(), casadi::Diagcat::join_primitives_gen(), casadi::Reshape::join_primitives_gen(), casadi::SparsityCast::join_primitives_gen(), casadi::Concat::n_primitives(), casadi::Reshape::n_primitives(), casadi::SparsityCast::n_primitives(), casadi::Horzcat::off(), casadi::Vertcat::off(), casadi::Diagcat::off(), casadi::MX::operator-(), casadi::OutputNode::OutputNode(), casadi::Concat::primitives(), casadi::Reshape::primitives(), casadi::SparsityCast::primitives(), casadi::MXFunction::print_arg(), casadi::MXNode::print_compact(), casadi::Concat::reset_input(), casadi::Reshape::reset_input(), casadi::SparsityCast::reset_input(), casadi::MXNode::sameOpAndDeps(), casadi::MXNode::set_dep(), casadi::MXNode::sp_forward(), casadi::Bilin::sp_forward(), casadi::Concat::sp_forward(), casadi::Dot::sp_forward(), casadi::GetNonzerosParam::sp_forward(), casadi::Multiplication::sp_forward(), casadi::Project::sp_forward(), casadi::Rank1::sp_forward(), casadi::Transpose::sp_forward(), casadi::DenseTranspose::sp_forward(), casadi::MXNode::sp_reverse(), casadi::Bilin::sp_reverse(), casadi::Concat::sp_reverse(), casadi::Dot::sp_reverse(), casadi::GetNonzerosParam::sp_reverse(), casadi::Multiplication::sp_reverse(), casadi::Project::sp_reverse(), casadi::HorzRepmat::sp_reverse(), casadi::Transpose::sp_reverse(), casadi::DenseTranspose::sp_reverse(), casadi::Horzcat::split_primitives_gen(), casadi::Vertcat::split_primitives_gen(), casadi::Diagcat::split_primitives_gen(), casadi::Reshape::split_primitives_gen(), casadi::SparsityCast::split_primitives_gen(), casadi::GetNonzerosParamSlice::sz_iw(), and casadi::GetNonzerosParamParam::sz_iw().
deserialize()
MXNode * casadi::ConstantMX::deserialize (DeserializingStream & s) static inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_z8
Definition at line 312 of file constant_mx.cpp.
{
     char t;
     s.unpack("ConstantMX::type", t);
     switch (t) {
       case 'a':    return new ConstantDM(s);
       case 'f':    return new ConstantFile(s);
       case 'z':    return ZeroByZero::getInstance();
       case 'D':
         return new Constant<RuntimeConst<double> >(s, RuntimeConst<double>::deserialize(s));
       case 'I':
         return new Constant<RuntimeConst<casadi_int> >(s,
                       RuntimeConst<casadi_int>::deserialize(s));
       case '0':
         return new Constant<CompiletimeConst<0> >(s, CompiletimeConst<0>::deserialize(s));
       case '1':
         return new Constant<CompiletimeConst<1> >(s, CompiletimeConst<1>::deserialize(s));
       case 'm':
         return new Constant<CompiletimeConst<(-1)> >(s, CompiletimeConst<(-1)>::deserialize(s));
       default:
         casadi_error("Error deserializing");
     }
   }
References casadi::RuntimeConst< T >::deserialize(), casadi::CompiletimeConst< v >::deserialize(), casadi::ZeroByZero::getInstance(), and casadi::DeserializingStream::unpack().
destroySingleton()
void casadi::SharedObjectInternal::destroySingleton () inline protected inherited
Called in the destructor of singletons
Definition at line 79 of file shared_object_internal.hpp.
{
       count--;
     }
disp() [1/2]
template<typename Value > std::string casadi::Constant< Value >::disp (const std::vector< std::string > & arg) const override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_109
Implements casadi::MXNode.
Definition at line 813 of file constant_mx.hpp.
{
     std::stringstream ss;
     if (sparsity().is_scalar()) {
       // Print scalar
       if (sparsity().nnz()==0) {
         ss << "00";
       } else {
         ss << v_.value;
       }
     } else if (sparsity().is_empty()) {
       // Print empty
       sparsity().disp(ss);
     } else {
       // Print value
       if (v_.value==0) {
         ss << "zeros(";
       } else if (v_.value==1) {
         ss << "ones(";
       } else if (v_.value!=v_.value) {
         ss << "nan(";
       } else if (v_.value==std::numeric_limits<double>::infinity()) {
         ss << "inf(";
       } else if (v_.value==-std::numeric_limits<double>::infinity()) {
         ss << "-inf(";
       } else {
         ss << "all_" << v_.value << "(";
       }
       // Print sparsity
       sparsity().disp(ss);
       ss << ")";
     }
     return ss.str();
   }
disp() [2/2]
void casadi::MXNode::disp (std::ostream & stream, bool more) const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1r2
Implements casadi::SharedObjectInternal.
Definition at line 253 of file mx_node.cpp.
{
     // Find out which noded can be inlined
     std::map<const MXNode*, casadi_int> nodeind;
     can_inline(nodeind);
     // Print expression
     std::vector<std::string> intermed;
     std::string s = print_compact(nodeind, intermed);
     // Print intermediate expressions
     for (casadi_int i=0; i<intermed.size(); ++i)
       stream << "@" << (i+1) << "=" << intermed[i] << ", ";
     // Print this
     stream << s;
   }
References casadi::MXNode::can_inline(), and casadi::MXNode::print_compact().
eval()
template<typename Value > int casadi::Constant< Value >::eval (const double ** arg, double ** res, casadi_int * iw, double * w) const override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_10a Evaluate the function numerically
Implements casadi::ConstantMX.
Definition at line 747 of file constant_mx.hpp.
{
     std::fill(res[0], res[0]+nnz(), to_double());
     return 0;
   }
eval_mx()
void casadi::ConstantMX::eval_mx (const std::vector< MX > & arg, std::vector< MX > & res) const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_yv
Reimplemented from casadi::MXNode.
Definition at line 103 of file constant_mx.cpp.
{
     res[0] = shared_from_this<MX>();
   }
eval_sx()
template<typename Value > int casadi::Constant< Value >::eval_sx (const SXElem ** arg, SXElem ** res, casadi_int * iw, SXElem * w) const override virtual
Implements casadi::ConstantMX.
Definition at line 753 of file constant_mx.hpp.
{
     std::fill(res[0], res[0]+nnz(), SXElem(v_.value));
     return 0;
   }
generate()
template<typename Value > void casadi::Constant< Value >::generate (CodeGenerator & g, const std::vector< casadi_int > & arg, const std::vector< casadi_int > & res) const override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_10b
Reimplemented from casadi::MXNode.
Definition at line 760 of file constant_mx.hpp.
{
     if (nnz()==0) {
       // Quick return
     } else if (nnz()==1) {
       g << g.workel(res[0]) << " = " << g.constant(to_double()) << ";\n";
     } else {
       if (to_double()==0) {
         g << g.clear(g.work(res[0], nnz()), nnz()) << '\n';
       } else {
         g << g.fill(g.work(res[0], nnz()), nnz(), g.constant(to_double())) << '\n';
       }
     }
   }
References casadi::CodeGenerator::clear(), casadi::CodeGenerator::constant(), casadi::CodeGenerator::fill(), casadi::CodeGenerator::work(), and casadi::CodeGenerator::workel().
get_assert()
MX casadi::MXNode::get_assert (const MX & y, const std::string & fail_message) const inherited
Definition at line 916 of file mx_node.cpp.
{
     return MX::create(new Assertion(shared_from_this<MX>(), y, fail_message));
   }
References casadi::MX::create().
get_bilin()
MX casadi::MXNode::get_bilin (const MX & x, const MX & y) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1rw
Definition at line 535 of file mx_node.cpp.
{
     return MX::create(new Bilin(shared_from_this<MX>(), x, y));
   }
References casadi::MX::create().
Referenced by casadi::MX::_bilin().
get_binary()
MX casadi::MXNode::get_binary (casadi_int op, const MX & y) const inherited
Definition at line 718 of file mx_node.cpp.
{
     // If-else-zero nodes are always simplified at top level to avoid NaN propagation
     if (y.op() == OP_IF_ELSE_ZERO) {
       if (op == OP_MUL) {
         // (Rule 1.) x * if_else_zero(c, y), simplified to if_else_zero(c, x * y)
         // Background: x is often a partial derivative and may evaluate to INF or NAN.
         // The simplification ensures that the zero seed corresponding to an inactive branch does
         // not give rise to any NaN contribution to the derivative due to NaN * 0 == NaN.
         return if_else_zero(y.dep(0), shared_from_this<MX>() * y.dep(1));
       } else if (op == OP_ADD && this->op() == OP_IF_ELSE_ZERO && MX::is_equal(dep(0), y.dep(0))) {
         // (Rule 2.) if_else_zero(c, x) + if_else_zero(c, y) is simplified to if_else_zero(c, x + y)
         // Background: During the backward propagation, seeds are added together. Without this rule,
         // the addition node can prevent rule (1.) from working in subsequent steps.
         return if_else_zero(y.dep(0), dep(1) + y.dep(1));
       }
     } else if (this->op() == OP_IF_ELSE_ZERO && op == OP_MUL) {
       // Same as Rule 1. above, but with factors swapped. For symmetry.
       return if_else_zero(dep(0), dep(1) * y);
     }
     // Create binary node
     if (sparsity().is_scalar(false)) {
       if (nnz()==0) {
         if (operation_checker<F0XChecker>(op)) return MX::zeros(Sparsity(y.size()));
         return to_matrix(MX(0)->_get_binary(op, y, true, false), y.sparsity());
       } else {
         return to_matrix(_get_binary(op, y, true, false), y.sparsity());
       }
     } else if (y.is_scalar()) {
       if (y.nnz()==0) {
         if (operation_checker<FX0Checker>(op)) return MX::zeros(Sparsity(size()));
         return to_matrix(_get_binary(op, MX(0), false, true), sparsity());
       } else {
         return to_matrix(_get_binary(op, y, false, true), sparsity());
       }
     } else {
       casadi_assert(sparsity().size() == y.sparsity().size(), "Dimension mismatch.");
       if (sparsity()==y.sparsity()) {
         // Matching sparsities
         return _get_binary(op, y, false, false);
       } else {
         // Get the sparsity pattern of the result
         // (ignoring structural zeros giving rise to nonzero result)
         const Sparsity& x_sp = sparsity();
         const Sparsity& y_sp = y.sparsity();
         Sparsity r_sp = x_sp.combine(y_sp, operation_checker<F0XChecker>(op),
                                             operation_checker<FX0Checker>(op));
         // Project the arguments to this sparsity
         MX xx = project(shared_from_this<MX>(), r_sp);
         MX yy = project(y, r_sp);
         return xx->_get_binary(op, yy, false, false);
       }
     }
   }
References casadi::MXNode::_get_binary(), casadi::Sparsity::combine(), casadi::MX::dep(), casadi::MXNode::dep(), casadi::if_else_zero(), casadi::MX::is_equal(), casadi::GenericMatrix< MatType >::is_scalar(), casadi::MXNode::MX, casadi::GenericMatrix< MatType >::nnz(), casadi::MXNode::nnz(), casadi::MX::op(), casadi::MXNode::op(), casadi::OP_ADD, casadi::OP_IF_ELSE_ZERO, casadi::OP_MUL, casadi::GenericMatrix< MatType >::size(), casadi::MXNode::size(), casadi::Sparsity::size(), casadi::MX::sparsity(), casadi::MXNode::sparsity(), casadi::MXNode::to_matrix(), and casadi::GenericMatrix< MX >::zeros().
Referenced by casadi::MX::binary(), and casadi::MXNode::get_dot().
get_bspline() [1/2]
MX casadi::MXNode::get_bspline (const MX & coeffs, const std::vector< double > & knots, const std::vector< casadi_int > & offset, const std::vector< casadi_int > & degree, casadi_int m, const std::vector< casadi_int > & lookup_mode) const inherited
Definition at line 952 of file mx_node.cpp.
{
     MX x = shared_from_this<MX>();
     return MX::create(new BSplineParametric(x, coeffs, knots, offset, degree, m, lookup_mode));
   }
References casadi::MX::create(), and casadi::MXNode::offset().
get_bspline() [2/2]
MX casadi::MXNode::get_bspline (const std::vector< double > & knots, const std::vector< casadi_int > & offset, const std::vector< double > & coeffs, const std::vector< casadi_int > & degree, casadi_int m, const std::vector< casadi_int > & lookup_mode) const inherited
Definition at line 942 of file mx_node.cpp.
{
     MX x = shared_from_this<MX>();
     return MX::create(new BSpline(x, knots, offset, coeffs, degree, m, lookup_mode));
   }
References casadi::MX::create(), and casadi::MXNode::offset().
Referenced by casadi::BSplineParametric::create(), and casadi::BSpline::create().
get_convexify()
MX casadi::MXNode::get_convexify (const Dict & opts) const inherited
Definition at line 962 of file mx_node.cpp.
{
     return MX::create(new Convexify(shared_from_this<MX>(), opts));
   }
References casadi::MX::create().
Referenced by casadi::MX::convexify().
get_det()
MX casadi::MXNode::get_det () const virtual inherited
Definition at line 966 of file mx_node.cpp.
{
     return MX::create(new Determinant(shared_from_this<MX>()));
   }
References casadi::MX::create().
Referenced by casadi::MX::det().
get_diagcat()
MX casadi::MXNode::get_diagcat (const std::vector< MX > & x) const virtual inherited
Reimplemented in casadi::Diagsplit.
Definition at line 1046 of file mx_node.cpp.
{
     // Create a Horzcat node
     return MX::create(new Diagcat(x));
   }
References casadi::MX::create().
Referenced by casadi::Diagsplit::get_diagcat().
get_diagsplit()
std::vector< MX > casadi::MXNode::get_diagsplit (const std::vector< casadi_int > & offset1, const std::vector< casadi_int > & offset2) const virtual inherited
Definition at line 1121 of file mx_node.cpp.
{
     if (is_zero()) {
       std::vector<MX> ret =
           MX::createMultipleOutput(new Diagsplit(shared_from_this<MX>(), offset1, offset2));
       for (casadi_int i=0;i<ret.size();++i) {
         ret[i]=MX::zeros(ret[i].sparsity());
       }
       return ret;
     }
     std::vector<MX> ret =
         MX::createMultipleOutput(new Diagsplit(shared_from_this<MX>(), offset1, offset2));
     return ret;
   }
References casadi::MX::createMultipleOutput(), casadi::MXNode::is_zero(), casadi::MXNode::sparsity(), and casadi::GenericMatrix< MX >::zeros().
Referenced by casadi::MX::diagsplit().
get_DM()
template<typename Value > Matrix<double> casadi::Constant< Value >::get_DM () const inline override virtual
Implements casadi::ConstantMX.
Definition at line 553 of file constant_mx.hpp.
{
       return Matrix<double>(sparsity(), to_double(), false);
     }
References casadi::Matrix< double >.
get_dot()
MX casadi::ConstantMX::get_dot (const MX & y) const override virtual inherited
Inner product
Reimplemented from casadi::MXNode.
Definition at line 227 of file constant_mx.cpp.
{
     if (y.is_constant()) {
       // Constant folding
       DM xv = get_DM();
       DM yv = y->get_DM();
       return dot(xv, yv);
     } else {
       return MXNode::get_dot(y);
     }
   }
References casadi::dot(), casadi::MXNode::get_DM(), casadi::ConstantMX::get_DM(), casadi::MXNode::get_dot(), and casadi::MX::is_constant().
get_einstein()
MX casadi::MXNode::get_einstein (const MX & A, const MX & B, const std::vector< casadi_int > & dim_c, const std::vector< casadi_int > & dim_a, const std::vector< casadi_int > & dim_b, const std::vector< casadi_int > & c, const std::vector< casadi_int > & a, const std::vector< casadi_int > & b) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1rv
Definition at line 512 of file mx_node.cpp.
{
     if (A.is_zero() || B.is_zero())
       return shared_from_this<MX>();
     MX C = densify(shared_from_this<MX>());
     if (A.is_constant() && B.is_constant() && C.is_constant()) {
       // Constant folding
       DM Ac = A->get_DM();
       DM Bc = B->get_DM();
       DM Cc = C->get_DM();
       return einstein(vec(densify(Ac)), vec(densify(Bc)), vec(densify(Cc)),
         dim_a, dim_b, dim_c, a, b, c);
     }
     return MX::create(new Einstein(C, densify(A), densify(B), dim_c, dim_a, dim_b, c, a, b));
   }
References casadi::MX::create(), casadi::MXNode::get_DM(), casadi::MX::is_constant(), and casadi::MX::is_zero().
Referenced by casadi::MX::einstein().
get_find()
MX casadi::MXNode::get_find () const inherited
Definition at line 928 of file mx_node.cpp.
{
     MX x = shared_from_this<MX>();
     casadi_assert(x.is_vector(), "Argument must be vector, got " + x.dim() + ".");
     if (x.is_column()) {
       return MX::create(new Find(shared_from_this<MX>()));
     } else {
       return find(x.T());
     }
   }
References casadi::MX::create(), casadi::GenericMatrix< MatType >::dim(), casadi::find(), casadi::GenericMatrix< MatType >::is_column(), casadi::GenericMatrix< MatType >::is_vector(), and casadi::MX::T().
Referenced by casadi::MX::find().
get_horzcat()
template<typename Value > MX casadi::Constant< Value >::get_horzcat (const std::vector< MX > & x) const override virtual
Reimplemented from casadi::MXNode.
Definition at line 618 of file constant_mx.hpp.
{
     // Check if all arguments have the same constant value
     for (auto&& i : x) {
       if (!i->is_value(to_double())) {
         // Not all the same value, fall back to base class
         return ConstantMX::get_horzcat(x);
       }
     }
     // Assemble the sparsity pattern
     std::vector<Sparsity> sp;
     for (auto&& i : x) sp.push_back(i.sparsity());
     return MX(horzcat(sp), v_.value, false);
   }
References casadi::MXNode::get_horzcat().
get_horzsplit()
std::vector< MX > casadi::MXNode::get_horzsplit (const std::vector< casadi_int > & output_offset) const virtual inherited
Definition at line 1071 of file mx_node.cpp.
{
     if (is_zero()) {
       std::vector<MX> ret =
           MX::createMultipleOutput(new Horzsplit(shared_from_this<MX>(), output_offset));
       for (casadi_int i=0;i<ret.size();++i) {
         ret[i]=MX::zeros(ret[i].sparsity());
       }
       return ret;
     }
     std::vector<MX> ret =
         MX::createMultipleOutput(new Horzsplit(shared_from_this<MX>(), output_offset));
     if (GlobalOptions::simplification_on_the_fly) {
       // Simplify horzsplit(horzcat)
       if (op()==OP_HORZCAT) {
         casadi_int offset_deps = 0;
         casadi_int j = 0;
         for (casadi_int i=0;i<output_offset.size();++i) {
           while (offset_deps<output_offset[i]) { offset_deps+=dep(j).size2();++j; }
           if (j>=n_dep()) j = n_dep()-1;
           if (output_offset[i]==offset_deps &&
               (i+1<output_offset.size()?output_offset[i+1]:size2()) ==
                offset_deps +dep(j).size2()) {
             // Aligned with vertcat dependency
             ret[i] = dep(j);
           }
         }
       }
     }
     return ret;
   }
References casadi::MX::createMultipleOutput(), casadi::MXNode::dep(), casadi::MXNode::is_zero(), casadi::MXNode::n_dep(), casadi::MXNode::op(), casadi::OP_HORZCAT, casadi::GlobalOptions::simplification_on_the_fly, casadi::GenericMatrix< MatType >::size2(), casadi::MXNode::size2(), casadi::MXNode::sparsity(), and casadi::GenericMatrix< MX >::zeros().
Referenced by casadi::MX::horzsplit().
get_inv()
MX casadi::MXNode::get_inv () const virtual inherited
Definition at line 970 of file mx_node.cpp.
{
     return MX::create(new Inverse(shared_from_this<MX>()));
   }
References casadi::MX::create().
Referenced by casadi::MX::inv_node().
get_logsumexp()
MX casadi::MXNode::get_logsumexp () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1ry
Definition at line 543 of file mx_node.cpp.
{
     return MX::create(new LogSumExp(shared_from_this<MX>()));
   }
References casadi::MX::create().
Referenced by casadi::MX::_logsumexp().
get_low()
MX casadi::MXNode::get_low (const MX & v, const Dict & options) const inherited
Definition at line 938 of file mx_node.cpp.
{
     return MX::create(new Low(v, shared_from_this<MX>(), options));
   }
References casadi::MX::create().
Referenced by casadi::MX::low().
get_mac()
MX casadi::MXNode::get_mac (const MX & y, const MX & z) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1ru
Definition at line 489 of file mx_node.cpp.
{
     if (sparsity().is_orthonormal() && y.is_column() && y.is_dense()
         && y.sparsity()==z.sparsity() && z.is_zero()) {
       std::vector<casadi_int> perm = sparsity().permutation_vector();
       MX nz = sparsity_cast(shared_from_this<MX>(), Sparsity::dense(nnz()));
       return (nz*y)(perm);
     }
     // Get reference to transposed first argument
     MX x = shared_from_this<MX>();
     casadi_assert(y.size2()==z.size2(),
       "Dimension error x.mac(z). Got y=" + str(y.size2()) + " and z=" + z.dim() + ".");
     casadi_assert(x.size1()==z.size1(),
       "Dimension error x.mac(z). Got x=" + x.dim() + " and z=" + z.dim() + ".");
     casadi_assert(y.size1()==x.size2(),
       "Dimension error x.mac(z). Got y=" + str(y.size1()) + " and x" + x.dim() + ".");
     if (x.is_dense() && y.is_dense() && z.is_dense()) {
       return MX::create(new DenseMultiplication(z, x, y));
     } else {
       return MX::create(new Multiplication(z, x, y));
     }
   }
References casadi::MX::create(), casadi::Sparsity::dense(), casadi::GenericMatrix< MatType >::dim(), casadi::GenericMatrix< MatType >::is_column(), casadi::GenericMatrix< MatType >::is_dense(), casadi::MX::is_zero(), casadi::MXNode::nnz(), casadi::Sparsity::permutation_vector(), casadi::GenericMatrix< MatType >::size1(), casadi::GenericMatrix< MatType >::size2(), casadi::MX::sparsity(), casadi::MXNode::sparsity(), and casadi::str().
Referenced by casadi::MX::mac().
get_mmax()
MX casadi::MXNode::get_mmax () const virtual inherited
Definition at line 1020 of file mx_node.cpp.
{
     if (sparsity_.is_empty()) return MX();
     return MX::create(new MMax(shared_from_this<MX>()));
   }
References casadi::MX::create(), casadi::Sparsity::is_empty(), casadi::MXNode::MX, and casadi::MXNode::sparsity_.
Referenced by casadi::MX::mmax().
get_mmin()
MX casadi::MXNode::get_mmin () const virtual inherited
Definition at line 1015 of file mx_node.cpp.
{
     if (sparsity_.is_empty()) return MX();
     return MX::create(new MMin(shared_from_this<MX>()));
   }
References casadi::MX::create(), casadi::Sparsity::is_empty(), casadi::MXNode::MX, and casadi::MXNode::sparsity_.
Referenced by casadi::MX::mmin().
get_monitor()
MX casadi::MXNode::get_monitor (const std::string & comment) const inherited
Definition at line 920 of file mx_node.cpp.
{
     if (nnz()==0) {
       return shared_from_this<MX>();
     } else {
       return MX::create(new Monitor(shared_from_this<MX>(), comment));
     }
   }
References casadi::MX::create(), and casadi::MXNode::nnz().
Referenced by casadi::MX::monitor().
get_norm_1()
MX casadi::MXNode::get_norm_1 () const virtual inherited
Definition at line 1011 of file mx_node.cpp.
{
     return MX::create(new Norm1(shared_from_this<MX>()));
   }
References casadi::MX::create().
Referenced by casadi::MX::norm_1().
get_norm_2()
MX casadi::MXNode::get_norm_2 () const virtual inherited
Definition at line 1003 of file mx_node.cpp.
{
     return MX::create(new Norm2(shared_from_this<MX>()));
   }
References casadi::MX::create().
Referenced by casadi::MX::norm_2().
get_norm_fro()
MX casadi::MXNode::get_norm_fro () const virtual inherited
Definition at line 999 of file mx_node.cpp.
{
     return MX::create(new NormF(shared_from_this<MX>()));
   }
References casadi::MX::create().
Referenced by casadi::MX::norm_fro().
get_norm_inf()
MX casadi::MXNode::get_norm_inf () const virtual inherited
Definition at line 1007 of file mx_node.cpp.
{
     return MX::create(new NormInf(shared_from_this<MX>()));
   }
References casadi::MX::create().
Referenced by casadi::MX::norm_inf().
get_nz_ref() [1/4]
MX casadi::MXNode::get_nz_ref (const MX & inner, const MX & outer) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1s8
Definition at line 614 of file mx_node.cpp.
{
     return GetNonzerosParam::create(shared_from_this<MX>(), inner, outer);
   }
References casadi::GetNonzerosParam::create().
get_nz_ref() [2/4]
MX casadi::MXNode::get_nz_ref (const MX & inner, const Slice & outer) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1s6
Definition at line 598 of file mx_node.cpp.
{
     if (outer.all()==std::vector<casadi_int>{0}) {
       return get_nz_ref(inner);
     } else {
       return GetNonzerosParam::create(shared_from_this<MX>(), inner, outer);
     }
   }
References casadi::Slice::all(), casadi::GetNonzerosParam::create(), and casadi::MXNode::get_nz_ref().
get_nz_ref() [3/4]
MX casadi::MXNode::get_nz_ref (const MX & nz) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1s5
Definition at line 594 of file mx_node.cpp.
{
     return GetNonzerosParam::create(shared_from_this<MX>(), nz);
   }
References casadi::GetNonzerosParam::create().
Referenced by casadi::GetNonzerosParamVector::ad_forward(), casadi::GetNonzerosSliceParam::ad_forward(), casadi::GetNonzerosParamSlice::ad_forward(), casadi::GetNonzerosParamParam::ad_forward(), casadi::SetNonzerosParamVector< Add >::ad_reverse(), casadi::SetNonzerosParamSlice< Add >::ad_reverse(), casadi::SetNonzerosSliceParam< Add >::ad_reverse(), casadi::SetNonzerosParamParam< Add >::ad_reverse(), casadi::MX::get(), casadi::MX::get_nz(), and casadi::MXNode::get_nz_ref().
get_nz_ref() [4/4]
MX casadi::MXNode::get_nz_ref (const Slice & inner, const MX & outer) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1s7
Definition at line 606 of file mx_node.cpp.
{
     if (inner.all()==std::vector<casadi_int>{0}) {
       return get_nz_ref(outer);
     } else {
       return GetNonzerosParam::create(shared_from_this<MX>(), inner, outer);
     }
   }
References casadi::Slice::all(), casadi::GetNonzerosParam::create(), and casadi::MXNode::get_nz_ref().
get_nzadd() [1/5]
MX casadi::MXNode::get_nzadd (const MX & y, const MX & inner, const MX & outer) const virtual inherited
a->get_nzadd(b,nz) returns b with b[nz]+=a
Extra doc: https://github.com/casadi/casadi/wiki/L_1si
Definition at line 678 of file mx_node.cpp.
{
     if (inner.is_empty() || outer.is_empty() || is_zero()) {
       return y;
     } else {
       return SetNonzerosParam<true>::create(y, shared_from_this<MX>(), inner, outer);
     }
   }
References casadi::SetNonzerosParam< Add >::create(), casadi::GenericMatrix< MatType >::is_empty(), and casadi::MXNode::is_zero().
get_nzadd() [2/5]
MX casadi::MXNode::get_nzadd (const MX & y, const MX & inner, const Slice & outer) const virtual inherited
a->get_nzadd(b,nz) returns b with b[nz]+=a
Extra doc: https://github.com/casadi/casadi/wiki/L_1sg
Definition at line 662 of file mx_node.cpp.
{
     if (inner.is_empty() || outer.is_empty() || is_zero()) {
       return y;
     } else {
       return SetNonzerosParam<true>::create(y, shared_from_this<MX>(), inner, outer);
     }
   }
References casadi::SetNonzerosParam< Add >::create(), casadi::Slice::is_empty(), casadi::GenericMatrix< MatType >::is_empty(), and casadi::MXNode::is_zero().
get_nzadd() [3/5]
MX casadi::MXNode::get_nzadd (const MX & y, const MX & nz) const virtual inherited
a->get_nzadd(b,nz) returns b with b[nz]+=a
Extra doc: https://github.com/casadi/casadi/wiki/L_1sf
Definition at line 654 of file mx_node.cpp.
{
     if (nz.is_empty() || is_zero()) {
       return y;
     } else {
       return SetNonzerosParam<true>::create(y, shared_from_this<MX>(), nz);
     }
   }
References casadi::SetNonzerosParam< Add >::create(), casadi::GenericMatrix< MatType >::is_empty(), and casadi::MXNode::is_zero().
get_nzadd() [4/5]
MX casadi::MXNode::get_nzadd (const MX & y, const Slice & inner, const MX & outer) const virtual inherited
a->get_nzadd(b,nz) returns b with b[nz]+=a
Extra doc: https://github.com/casadi/casadi/wiki/L_1sh
Definition at line 670 of file mx_node.cpp.
{
     if (outer.is_empty() || outer.is_empty() || is_zero()) {
       return y;
     } else {
       return SetNonzerosParam<true>::create(y, shared_from_this<MX>(), inner, outer);
     }
   }
References casadi::SetNonzerosParam< Add >::create(), casadi::GenericMatrix< MatType >::is_empty(), and casadi::MXNode::is_zero().
get_nzadd() [5/5]
MX casadi::MXNode::get_nzadd (const MX & y, const std::vector< casadi_int > & nz) const virtual inherited
a->get_nzadd(b,nz) returns b with b[nz]+=a
Extra doc: https://github.com/casadi/casadi/wiki/L_1sa
Definition at line 630 of file mx_node.cpp.
{
     if (nz.empty() || is_zero()) {
       return y;
     } else {
       return SetNonzeros<true>::create(y, shared_from_this<MX>(), nz);
     }
   }
References casadi::SetNonzeros< Add >::create(), and casadi::MXNode::is_zero().
Referenced by casadi::SetNonzeros< Add >::ad_forward(), casadi::SetNonzerosParamVector< Add >::ad_forward(), casadi::SetNonzerosParamSlice< Add >::ad_forward(), casadi::SetNonzerosSliceParam< Add >::ad_forward(), casadi::SetNonzerosParamParam< Add >::ad_forward(), casadi::GetNonzeros::ad_reverse(), casadi::GetNonzerosParamVector::ad_reverse(), casadi::GetNonzerosSliceParam::ad_reverse(), casadi::GetNonzerosParamSlice::ad_reverse(), casadi::GetNonzerosParamParam::ad_reverse(), casadi::SetNonzerosParamVector< Add >::eval_mx(), casadi::SetNonzerosParamSlice< Add >::eval_mx(), casadi::SetNonzerosSliceParam< Add >::eval_mx(), and casadi::SetNonzerosParamParam< Add >::eval_mx().
get_nzassign() [1/5]
MX casadi::MXNode::get_nzassign (const MX & y, const MX & inner, const MX & outer) const virtual inherited
a->get_nzassign(b,nz) returns b with b[nz]=a
Extra doc: https://github.com/casadi/casadi/wiki/L_1se
Definition at line 650 of file mx_node.cpp.
{
     return SetNonzerosParam<false>::create(y, shared_from_this<MX>(), inner, outer);
   }
References casadi::SetNonzerosParam< Add >::create().
get_nzassign() [2/5]
MX casadi::MXNode::get_nzassign (const MX & y, const MX & inner, const Slice & outer) const virtual inherited
a->get_nzassign(b,nz) returns b with b[nz]=a
Extra doc: https://github.com/casadi/casadi/wiki/L_1sc
Definition at line 642 of file mx_node.cpp.
{
     return SetNonzerosParam<false>::create(y, shared_from_this<MX>(), inner, outer);
   }
References casadi::SetNonzerosParam< Add >::create().
get_nzassign() [3/5]
MX casadi::MXNode::get_nzassign (const MX & y, const MX & nz) const virtual inherited
a->get_nzassign(b,nz) returns b with b[nz]=a
Extra doc: https://github.com/casadi/casadi/wiki/L_1sb
Definition at line 638 of file mx_node.cpp.
{
     return SetNonzerosParam<false>::create(y, shared_from_this<MX>(), nz);
   }
References casadi::SetNonzerosParam< Add >::create().
get_nzassign() [4/5]
MX casadi::MXNode::get_nzassign (const MX & y, const Slice & inner, const MX & outer) const virtual inherited
a->get_nzassign(b,nz) returns b with b[nz]=a
Extra doc: https://github.com/casadi/casadi/wiki/L_1sd
Definition at line 646 of file mx_node.cpp.
{
     return SetNonzerosParam<false>::create(y, shared_from_this<MX>(), inner, outer);
   }
References casadi::SetNonzerosParam< Add >::create().
get_nzassign() [5/5]
template<typename Value > MX casadi::Constant< Value >::get_nzassign (const MX & y, const std::vector< casadi_int > & nz) const override virtual
Reimplemented from casadi::MXNode.
Definition at line 791 of file constant_mx.hpp.
{
     if (y.is_constant() && y->is_zero() && v_.value==0) {
       return y;
     }
     // Fall-back
     return MXNode::get_nzassign(y, nz);
   }
References casadi::MXNode::get_nzassign(), casadi::MX::is_constant(), and casadi::MXNode::is_zero().
get_nzref()
template<typename Value > MX casadi::Constant< Value >::get_nzref (const Sparsity & sp, const std::vector< casadi_int > & nz) const override virtual
Reimplemented from casadi::MXNode.
Definition at line 777 of file constant_mx.hpp.
{
     if (v_.value!=0) {
       // Check if any "holes"
       for (std::vector<casadi_int>::const_iterator k=nz.begin(); k!=nz.end(); ++k) {
         if (*k<0) {
           // Do not simplify
           return MXNode::get_nzref(sp, nz);
         }
       }
     }
     return MX::create(new Constant<Value>(sp, v_));
   }
References casadi::MX::create(), and casadi::MXNode::get_nzref().
get_output()
MX casadi::MXNode::get_output (casadi_int oind) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1rp
Reimplemented in casadi::MultipleOutput.
Definition at line 393 of file mx_node.cpp.
{
     casadi_assert(oind==0, "Output index out of bounds");
     return shared_from_this<MX>();
   }
Referenced by casadi::MX::get_output().
get_project()
template<typename Value > MX casadi::Constant< Value >::get_project (const Sparsity & sp) const override virtual
Reimplemented from casadi::MXNode.
Definition at line 801 of file constant_mx.hpp.
{
     if (is_zero()) {
       return MX::create(new Constant<Value>(sp, v_));
     } else if (sp.is_dense()) {
       return densify(get_DM());
     } else {
       return MXNode::get_project(sp);
     }
   }
References casadi::MX::create(), casadi::MXNode::get_project(), casadi::Sparsity::is_dense(), and casadi::is_zero().
get_rank1()
MX casadi::MXNode::get_rank1 (const MX & alpha, const MX & x, const MX & y) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1rx
Definition at line 539 of file mx_node.cpp.
{
     return MX::create(new Rank1(shared_from_this<MX>(), alpha, x, y));
   }
References casadi::MX::create().
Referenced by casadi::MX::_rank1().
get_repmat()
MX casadi::MXNode::get_repmat (casadi_int m, casadi_int n) const virtual inherited
Definition at line 1103 of file mx_node.cpp.
{
     if (n==1) {
       return MX::create(new HorzRepmat(shared_from_this<MX>(), m));
     } else {
       // Fallback to generic_matrix impl
       return GenericMatrix<MX>::repmat(shared_from_this<MX>(), n, m);
     }
   }
References casadi::MX::create(), and casadi::SparsityInterface< MatType >::repmat().
Referenced by casadi::MX::repmat().
get_repsum()
MX casadi::MXNode::get_repsum (casadi_int m, casadi_int n) const virtual inherited
Definition at line 1112 of file mx_node.cpp.
{
     if (n==1) {
       return MX::create(new HorzRepsum(shared_from_this<MX>(), m));
     } else {
       // Fallback to generic_matrix impl
       return GenericMatrix<MX>::repsum(shared_from_this<MX>(), n, m);
     }
   }
References casadi::MX::create(), and casadi::GenericMatrix< MatType >::repsum().
Referenced by casadi::MX::repsum().
get_reshape()
template<typename Value > MX casadi::Constant< Value >::get_reshape (const Sparsity & sp) const override virtual
Reimplemented from casadi::MXNode.
Definition at line 650 of file constant_mx.hpp.
{
     return MX::create(new Constant<Value>(sp, v_));
   }
References casadi::MX::create().
get_solve()
MX casadi::MXNode::get_solve (const MX & r, bool tr, const Linsol & linear_solver) const virtual inherited
For system Ax = b:
A->get_solve(b)
Extra doc: https://github.com/casadi/casadi/wiki/L_1rz
Definition at line 579 of file mx_node.cpp.
{
     if (tr) {
       return MX::create(new LinsolCall<true>(densify(r), shared_from_this<MX>(), linear_solver));
     } else {
       return MX::create(new LinsolCall<false>(densify(r), shared_from_this<MX>(), linear_solver));
     }
   }
References casadi::MX::create().
Referenced by casadi::Rootfinder::ad_forward(), casadi::Rootfinder::ad_reverse(), and casadi::Linsol::solve().
get_solve_tril()
MX casadi::MXNode::get_solve_tril (const MX & r, bool tr) const virtual inherited
For system Ax = b:
A->get_solve_tril(b)
Extra doc: https://github.com/casadi/casadi/wiki/L_1s1
Reimplemented in casadi::Transpose, and casadi::BinaryMX< ScX, ScY >.
Definition at line 555 of file mx_node.cpp.
{
     if (tr) {
       return MX::create(new TrilSolve<true>(densify(r), shared_from_this<MX>()));
     } else {
       return MX::create(new TrilSolve<false>(densify(r), shared_from_this<MX>()));
     }
   }
References casadi::MX::create().
Referenced by casadi::BinaryMX< ScX, ScY >::get_solve_tril(), casadi::Transpose::get_solve_triu(), casadi::MX::solve(), and casadi::TrilSolve< Tr >::solve().
get_solve_tril_unity()
MX casadi::MXNode::get_solve_tril_unity (const MX & r, bool tr) const virtual inherited
For system Ax = b:
A->get_solve_tril(b)
Extra doc: https://github.com/casadi/casadi/wiki/L_1s3
Reimplemented in casadi::Transpose.
Definition at line 571 of file mx_node.cpp.
{
     if (tr) {
       return MX::create(new TrilSolveUnity<true>(densify(r), shared_from_this<MX>()));
     } else {
       return MX::create(new TrilSolveUnity<false>(densify(r), shared_from_this<MX>()));
     }
   }
References casadi::MX::create().
Referenced by casadi::BinaryMX< ScX, ScY >::get_solve_tril(), casadi::Transpose::get_solve_triu_unity(), and casadi::TrilSolveUnity< Tr >::solve().
get_solve_triu()
MX casadi::MXNode::get_solve_triu (const MX & r, bool tr) const virtual inherited
For system Ax = b:
A->get_solve_triu(b)
Extra doc: https://github.com/casadi/casadi/wiki/L_1s0
Reimplemented in casadi::Transpose, and casadi::BinaryMX< ScX, ScY >.
Definition at line 547 of file mx_node.cpp.
{
     if (tr) {
       return MX::create(new TriuSolve<true>(densify(r), shared_from_this<MX>()));
     } else {
       return MX::create(new TriuSolve<false>(densify(r), shared_from_this<MX>()));
     }
   }
References casadi::MX::create().
Referenced by casadi::Transpose::get_solve_tril(), casadi::BinaryMX< ScX, ScY >::get_solve_triu(), casadi::MX::solve(), and casadi::TriuSolve< Tr >::solve().
get_solve_triu_unity()
MX casadi::MXNode::get_solve_triu_unity (const MX & r, bool tr) const virtual inherited
For system Ax = b:
A->get_solve_triu(b)
Extra doc: https://github.com/casadi/casadi/wiki/L_1s2
Reimplemented in casadi::Transpose.
Definition at line 563 of file mx_node.cpp.
{
     if (tr) {
       return MX::create(new TriuSolveUnity<true>(densify(r), shared_from_this<MX>()));
     } else {
       return MX::create(new TriuSolveUnity<false>(densify(r), shared_from_this<MX>()));
     }
   }
References casadi::MX::create().
Referenced by casadi::Transpose::get_solve_tril_unity(), casadi::BinaryMX< ScX, ScY >::get_solve_triu(), and casadi::TriuSolveUnity< Tr >::solve().
get_sparsity_cast()
MX casadi::MXNode::get_sparsity_cast (const Sparsity & sp) const virtual inherited
Reimplemented in casadi::SparsityCast.
Definition at line 435 of file mx_node.cpp.
{
     casadi_assert_dev(sp.nnz()==nnz());
     if (sp==sparsity()) {
       return shared_from_this<MX>();
     } else {
       return MX::create(new SparsityCast(shared_from_this<MX>(), sp));
     }
   }
References casadi::MX::create(), casadi::Sparsity::nnz(), casadi::MXNode::nnz(), and casadi::MXNode::sparsity().
Referenced by casadi::SparsityCast::get_transpose(), and casadi::MX::sparsity_cast().
get_subassign()
MX casadi::MXNode::get_subassign (const MX & y, const Slice & i, const Slice & j) const virtual inherited
Definition at line 704 of file mx_node.cpp.
{
     return MX::create(new SubAssign(shared_from_this<MX>(), y, i, j));
   }
References casadi::MX::create().
get_subref()
MX casadi::MXNode::get_subref (const Slice & i, const Slice & j) const virtual inherited
Definition at line 700 of file mx_node.cpp.
{
     return MX::create(new SubRef(shared_from_this<MX>(), i, j));
   }
References casadi::MX::create().
get_transpose()
template<typename Value > MX casadi::Constant< Value >::get_transpose override virtual
Reimplemented from casadi::MXNode.
Definition at line 655 of file constant_mx.hpp.
{
     return MX::create(new Constant<Value>(sparsity().T(), v_));
   }
References casadi::MX::create().
get_unary()
template<typename Value > MX casadi::Constant< Value >::get_unary (casadi_int op) const override virtual
Reimplemented from casadi::MXNode.
Definition at line 660 of file constant_mx.hpp.
{
     // Constant folding
     double ret(0);
     casadi_math<double>::fun(op, to_double(), 0.0, ret);
     if (operation_checker<F0XChecker>(op) || sparsity().is_dense()) {
       return MX(sparsity(), ret);
     } else {
       if (v_.value==0) {
         if (is_zero() && operation_checker<F0XChecker>(op)) {
           return MX(sparsity(), ret, false);
         } else {
           return repmat(MX(ret), size1(), size2());
         }
       }
       double ret2;
       casadi_math<double>::fun(op, 0, 0.0, ret2);
       return DM(sparsity(), ret, false)
         + DM(sparsity().pattern_inverse(), ret2, false);
     }
   }
References casadi::casadi_math< T >::fun(), and casadi::is_zero().
get_vertcat()
template<typename Value > MX casadi::Constant< Value >::get_vertcat (const std::vector< MX > & x) const override virtual
Reimplemented from casadi::MXNode.
Definition at line 634 of file constant_mx.hpp.
{
     // Check if all arguments have the same constant value
     for (auto&& i : x) {
       if (!i->is_value(to_double())) {
         // Not all the same value, fall back to base class
         return ConstantMX::get_vertcat(x);
       }
     }
     // Assemble the sparsity pattern
     std::vector<Sparsity> sp;
     for (auto&& i : x) sp.push_back(i.sparsity());
     return MX(vertcat(sp), v_.value, false);
   }
References casadi::MXNode::get_vertcat().
get_vertsplit()
std::vector< MX > casadi::MXNode::get_vertsplit (const std::vector< casadi_int > & output_offset) const virtual inherited
Definition at line 1137 of file mx_node.cpp.
{
     if (is_zero()) {
       std::vector<MX> ret =
           MX::createMultipleOutput(new Vertsplit(shared_from_this<MX>(), output_offset));
       for (casadi_int i=0;i<ret.size();++i) {
         ret[i]=MX::zeros(ret[i].sparsity());
       }
       return ret;
     }
     std::vector<MX> ret =
         MX::createMultipleOutput(new Vertsplit(shared_from_this<MX>(), output_offset));
     if (GlobalOptions::simplification_on_the_fly) {
       // Simplify vertsplit(vertcat)
       if (op()==OP_VERTCAT) {
         casadi_int offset_deps = 0;
         casadi_int j = 0;
         for (casadi_int i=0;i<output_offset.size();++i) {
           while (offset_deps<output_offset[i]) { offset_deps+=dep(j).size1();++j; }
           if (j>=n_dep()) j = n_dep()-1;
           if (output_offset[i]==offset_deps &&
               (i+1<output_offset.size()?output_offset[i+1]:size1()) ==
                offset_deps +dep(j).size1()) {
             // Aligned with vertcat dependency
             ret[i] = dep(j);
           }
         }
       }
     }
     return ret;
   }
References casadi::MX::createMultipleOutput(), casadi::MXNode::dep(), casadi::MXNode::is_zero(), casadi::MXNode::n_dep(), casadi::MXNode::op(), casadi::OP_VERTCAT, casadi::GlobalOptions::simplification_on_the_fly, casadi::GenericMatrix< MatType >::size1(), casadi::MXNode::size1(), casadi::MXNode::sparsity(), and casadi::GenericMatrix< MX >::zeros().
Referenced by casadi::MX::vertsplit().
getCount()
casadi_int casadi::SharedObjectInternal::getCount () const inherited
Definition at line 58 of file shared_object_internal.cpp.
{
     return count;
   }
has_duplicates()
bool casadi::ConstantMX::has_duplicates () const inline override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_z6
Reimplemented from casadi::MXNode.
Definition at line 169 of file constant_mx.hpp.
 { return false;}
has_output()
virtual bool casadi::MXNode::has_output () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1rb
Reimplemented in casadi::MultipleOutput.
Definition at line 252 of file mx_node.hpp.
 {return false;}
has_refcount()
virtual bool casadi::MXNode::has_refcount () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1qp
Reimplemented in casadi::Call.
Definition at line 126 of file mx_node.hpp.
 { return false;}
ind()
casadi_int casadi::MXNode::ind () const virtual inherited
Reimplemented in casadi::IOInstruction.
Definition at line 210 of file mx_node.cpp.
{
     casadi_error("'ind' not defined for class " + class_name());
   }
References casadi::MXNode::class_name().
Referenced by casadi::GetNonzerosSliceParam::eval(), casadi::GetNonzerosParamParam::eval(), casadi::ConstantDM::generate(), casadi::GetNonzerosVector::generate(), casadi::MXFunction::print(), casadi::MXNode::print_compact(), and casadi::Einstein::sp_reverse().
info()
Dict casadi::MXNode::info () const virtual inherited
Obtain information about node
Reimplemented in casadi::SubRef, casadi::SubAssign, casadi::Split, casadi::Solve< Tr >, casadi::SetNonzerosSlice2< Add >, casadi::SetNonzerosSlice< Add >, casadi::SetNonzerosVector< Add >, casadi::OutputNode, casadi::IOInstruction, casadi::GetNonzerosParamParam, casadi::GetNonzerosParamSlice, casadi::GetNonzerosSliceParam, casadi::GetNonzerosSlice2, casadi::GetNonzerosSlice, casadi::GetNonzerosVector, and casadi::Einstein.
Definition at line 444 of file mx_node.cpp.
{
     return Dict();
   }
initSingleton()
void casadi::SharedObjectInternal::initSingleton () inline protected inherited
Called in the constructor of singletons to avoid that the counter reaches zero
Definition at line 73 of file shared_object_internal.hpp.
{
       casadi_assert_dev(count==0);
       count++;
     }
is_binary()
virtual bool casadi::MXNode::is_binary () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1qk
Reimplemented in casadi::BinaryMX< ScX, ScY >.
Definition at line 100 of file mx_node.hpp.
 { return false;}
is_equal() [1/2]
template<typename Value > bool casadi::Constant< Value >::is_equal (const MXNode * node, casadi_int depth) const override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_10d
Reimplemented from casadi::MXNode.
Definition at line 849 of file constant_mx.hpp.
{
     return node->is_value(to_double()) && sparsity()==node->sparsity();
   }
References casadi::MXNode::is_value(), and casadi::MXNode::sparsity().
is_equal() [2/2]
bool casadi::MXNode::is_equal (const MXNode * x, const MXNode * y, casadi_int depth) static inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1rj
Definition at line 1184 of file mx_node.cpp.
{
     if (x==y) {
       return true;
     } else if (depth>0) {
       return x->is_equal(y, depth);
     } else {
       return false;
     }
   }
References casadi::MXNode::is_equal().
Referenced by casadi::MXNode::_get_binary(), casadi::MX::is_equal(), and casadi::MXNode::is_equal().
is_eye()
template<typename Value > bool casadi::Constant< Value >::is_eye () const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_1qi
Reimplemented from casadi::MXNode.
Definition at line 544 of file constant_mx.hpp.
 { return v_.value==1 && sparsity().is_diag();}
is_minus_one()
virtual bool casadi::MXNode::is_minus_one () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1qg
Reimplemented in casadi::ConstantDM.
Definition at line 80 of file mx_node.hpp.
 { return false;}
is_one()
template<typename Value > bool casadi::Constant< Value >::is_one () const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_1qf
Reimplemented from casadi::MXNode.
Definition at line 543 of file constant_mx.hpp.
 { return v_.value==1;}
is_output()
virtual bool casadi::MXNode::is_output () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1ra
Reimplemented in casadi::OutputNode.
Definition at line 247 of file mx_node.hpp.
 {return false;}
Referenced by casadi::Diagsplit::get_diagcat(), casadi::Horzsplit::get_horzcat(), and casadi::Vertsplit::get_vertcat().
is_unary()
virtual bool casadi::MXNode::is_unary () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1qj
Reimplemented in casadi::UnaryMX.
Definition at line 95 of file mx_node.hpp.
 { return false;}
is_valid_input()
bool casadi::ConstantMX::is_valid_input () const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_z1
Reimplemented from casadi::MXNode.
Reimplemented in casadi::ZeroByZero.
Definition at line 41 of file constant_mx.cpp.
{
     return nnz()==0;
   }
References casadi::MXNode::nnz().
is_value()
template<typename Value > bool casadi::Constant< Value >::is_value (double val) const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_1qh
Reimplemented from casadi::MXNode.
Definition at line 545 of file constant_mx.hpp.
 { return v_.value==val;}
is_zero()
template<typename Value > bool casadi::Constant< Value >::is_zero () const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_10c
Reimplemented from casadi::MXNode.
Definition at line 542 of file constant_mx.hpp.
 { return v_.value==0;}
join_primitives() [1/3]
DM casadi::ConstantMX::join_primitives (std::vector< DM >::const_iterator & it) const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_z5
Reimplemented from casadi::MXNode.
Definition at line 99 of file constant_mx.cpp.
{
     return join_primitives_gen<DM>(it);
   }
join_primitives() [2/3]
MX casadi::ConstantMX::join_primitives (std::vector< MX >::const_iterator & it) const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_z5
Reimplemented from casadi::MXNode.
Definition at line 87 of file constant_mx.cpp.
{
     if (nnz()==0) {
       return shared_from_this<MX>();
     } else {
       return MXNode::join_primitives(it);
     }
   }
References casadi::MXNode::join_primitives(), and casadi::MXNode::nnz().
join_primitives() [3/3]
SX casadi::ConstantMX::join_primitives (std::vector< SX >::const_iterator & it) const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_z5
Reimplemented from casadi::MXNode.
Definition at line 95 of file constant_mx.cpp.
{
     return join_primitives_gen<SX>(it);
   }
join_primitives_gen()
template<typename T > T casadi::ConstantMX::join_primitives_gen (typename std::vector< T >::const_iterator & it) const inherited
Definition at line 79 of file constant_mx.cpp.
{
     if (nnz()==0) {
       return T(sparsity());
     } else {
       return MXNode::join_primitives(it);
     }
   }
References casadi::MXNode::join_primitives(), casadi::MXNode::nnz(), and casadi::MXNode::sparsity().
mapping()
Matrix< casadi_int > casadi::MXNode::mapping () const virtual inherited
Reimplemented in casadi::SetNonzeros< Add >, and casadi::GetNonzeros.
Definition at line 902 of file mx_node.cpp.
{
     casadi_error("'mapping' not defined for class " + class_name());
   }
References casadi::MXNode::class_name().
Referenced by casadi::BSplineCommon::derivative_coeff().
matches_sparsity()
template<class T > bool casadi::MXNode::matches_sparsity (const std::vector< T > & arg) const inline inherited
Definition at line 343 of file mx_node.hpp.
{
         for (casadi_int i=0;i<dep_.size();++i) {
             if (dep_[i].sparsity()!=arg[i].sparsity()) {
                 return false;
             }
         }
         return true;
     }
Referenced by casadi::GetNonzerosVector::eval_mx(), casadi::SetNonzerosVector< Add >::eval_mx(), casadi::SetNonzerosSlice< Add >::eval_mx(), and casadi::SetNonzerosSlice2< Add >::eval_mx().
maxDepth()
static bool casadi::MXNode::maxDepth () inline static inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1rk
Definition at line 307 of file mx_node.hpp.
 { return MX::get_max_depth();}
References casadi::MX::get_max_depth().
Referenced by casadi::MXNode::_get_binary(), and casadi::UnaryMX::_get_binary().
n_dep()
casadi_int casadi::MXNode::n_dep () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1rn
Definition at line 206 of file mx_node.cpp.
{
     return dep_.size();
   }
References casadi::MXNode::dep_.
Referenced by casadi::Call::ad_forward(), casadi::Call::ad_reverse(), casadi::Horzcat::ad_reverse(), casadi::Vertcat::ad_reverse(), casadi::Diagcat::ad_reverse(), casadi::MXNode::can_inline(), casadi::Call::disp(), casadi::Horzcat::disp(), casadi::Vertcat::disp(), casadi::Diagcat::disp(), casadi::Concat::eval_gen(), casadi::MXNode::get_horzsplit(), casadi::Concat::get_nzref(), casadi::MXNode::get_vertsplit(), casadi::Concat::has_duplicates(), casadi::Concat::is_valid_input(), casadi::Horzcat::join_primitives_gen(), casadi::Vertcat::join_primitives_gen(), casadi::Diagcat::join_primitives_gen(), casadi::Concat::n_primitives(), casadi::Horzcat::off(), casadi::Vertcat::off(), casadi::Diagcat::off(), casadi::Concat::primitives(), casadi::MXNode::print_compact(), casadi::Concat::reset_input(), casadi::MXNode::sameOpAndDeps(), casadi::MXNode::sp_forward(), casadi::Concat::sp_forward(), casadi::MXNode::sp_reverse(), and casadi::Concat::sp_reverse().
n_inplace()
virtual casadi_int casadi::MXNode::n_inplace () const inline virtual inherited
Reimplemented in casadi::UnaryMX, casadi::SparsityCast, casadi::Solve< Tr >, casadi::SetNonzerosParam< Add >, casadi::SetNonzeros< Add >, casadi::Reshape, casadi::Rank1, casadi::Multiplication, casadi::Monitor, casadi::LogSumExp, casadi::Einstein, casadi::BinaryMX< ScX, ScY >, and casadi::Assertion.
Definition at line 419 of file mx_node.hpp.
 { return 0;}
n_primitives()
casadi_int casadi::ConstantMX::n_primitives () const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_z2
Reimplemented from casadi::MXNode.
Definition at line 45 of file constant_mx.cpp.
{
     if (nnz()==0) {
       return 0;
     } else {
       return MXNode::n_primitives();
     }
   }
References casadi::MXNode::n_primitives(), and casadi::MXNode::nnz().
name()
const std::string & casadi::MXNode::name () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1r0
Reimplemented in casadi::SymbolicMX, and casadi::ZeroByZero.
Definition at line 193 of file mx_node.cpp.
{
     casadi_error("'name' not defined for class " + class_name());
   }
References casadi::MXNode::class_name().
Referenced by casadi::DaeBuilderInternal::all_variables(), and casadi::DaeBuilderInternal::tearing_variables().
nnz()
casadi_int casadi::MXNode::nnz (casadi_int i = 0) const inline inherited
Definition at line 354 of file mx_node.hpp.
 { return sparsity(i).nnz(); }
Referenced by casadi::ConstantMX::__nonzero__(), casadi::MXNode::_get_binary(), casadi::ConstantFile::add_dependency(), casadi::ConstantFile::codegen_incref(), casadi::ConstantFile::ConstantFile(), casadi::BSpline::dual(), casadi::Assertion::eval(), casadi::Find::eval(), casadi::Low::eval(), casadi::GetNonzerosParamVector::eval(), casadi::GetNonzerosSliceParam::eval(), casadi::GetNonzerosParamSlice::eval(), casadi::GetNonzerosParamParam::eval(), casadi::MMin::eval(), casadi::MMax::eval(), casadi::Monitor::eval(), casadi::UnaryMX::eval(), casadi::Dot::eval_gen(), casadi::Einstein::eval_gen(), casadi::LogSumExp::eval_gen(), casadi::Multiplication::eval_gen(), casadi::NormF::eval_gen(), casadi::Rank1::eval_gen(), casadi::HorzRepmat::eval_gen(), casadi::Reshape::eval_gen(), casadi::SparsityCast::eval_gen(), casadi::HorzRepsum::eval_gen(), casadi::Assertion::eval_sx(), casadi::MMin::eval_sx(), casadi::MMax::eval_sx(), casadi::Monitor::eval_sx(), casadi::UnaryMX::eval_sx(), casadi::BSplineParametric::generate(), casadi::Assertion::generate(), casadi::Bilin::generate(), casadi::Find::generate(), casadi::Concat::generate(), casadi::ConstantDM::generate(), casadi::ConstantFile::generate(), casadi::Convexify::generate(), casadi::Dot::generate(), casadi::Einstein::generate(), casadi::GetNonzerosVector::generate(), casadi::GetNonzerosSlice::generate(), casadi::GetNonzerosSlice2::generate(), casadi::GetNonzerosParamVector::generate(), casadi::GetNonzerosSliceParam::generate(), casadi::GetNonzerosParamSlice::generate(), casadi::GetNonzerosParamParam::generate(), casadi::Input::generate(), casadi::Output::generate(), casadi::LogSumExp::generate(), casadi::MMin::generate(), casadi::MMax::generate(), casadi::Monitor::generate(), casadi::Multiplication::generate(), casadi::DenseMultiplication::generate(), casadi::NormF::generate(), casadi::Project::generate(), casadi::Densify::generate(), casadi::Sparsify::generate(), casadi::Rank1::generate(), casadi::HorzRepmat::generate(), casadi::HorzRepsum::generate(), casadi::Reshape::generate(), casadi::SparsityCast::generate(), casadi::Split::generate(), casadi::Transpose::generate(), casadi::DenseTranspose::generate(), casadi::UnaryMX::generate(), casadi::MXNode::get_binary(), casadi::MXNode::get_dot(), casadi::MXNode::get_mac(), casadi::MXNode::get_monitor(), casadi::MXNode::get_nzref(), casadi::MXNode::get_sparsity_cast(), casadi::ConstantMX::is_valid_input(), casadi::ConstantMX::join_primitives(), casadi::ConstantMX::join_primitives_gen(), casadi::ConstantMX::n_primitives(), casadi::ConstantMX::primitives(), casadi::SetNonzerosVector< Add >::SetNonzerosVector(), casadi::Assertion::sp_forward(), casadi::Low::sp_forward(), casadi::ConstantMX::sp_forward(), casadi::GetNonzerosParam::sp_forward(), casadi::Monitor::sp_forward(), casadi::Multiplication::sp_forward(), casadi::Rank1::sp_forward(), casadi::HorzRepsum::sp_forward(), casadi::Reshape::sp_forward(), casadi::SparsityCast::sp_forward(), casadi::SymbolicMX::sp_forward(), casadi::Transpose::sp_forward(), casadi::UnaryMX::sp_forward(), casadi::Assertion::sp_reverse(), casadi::Low::sp_reverse(), casadi::ConstantMX::sp_reverse(), casadi::Einstein::sp_reverse(), casadi::GetNonzerosParam::sp_reverse(), casadi::Monitor::sp_reverse(), casadi::Multiplication::sp_reverse(), casadi::Project::sp_reverse(), casadi::Rank1::sp_reverse(), casadi::HorzRepmat::sp_reverse(), casadi::HorzRepsum::sp_reverse(), casadi::Reshape::sp_reverse(), casadi::SparsityCast::sp_reverse(), casadi::SymbolicMX::sp_reverse(), casadi::Transpose::sp_reverse(), casadi::UnaryMX::sp_reverse(), and casadi::ConstantMX::split_primitives_gen().
nout()
virtual casadi_int casadi::MXNode::nout () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1ro
Reimplemented in casadi::MultipleOutput, casadi::Split, casadi::Output, and casadi::Call.
Definition at line 329 of file mx_node.hpp.
 { return 1;}
Referenced by casadi::MX::createMultipleOutput(), casadi::MXNode::sp_forward(), and casadi::MXNode::sp_reverse().
numel()
casadi_int casadi::MXNode::numel () const inline inherited
Definition at line 353 of file mx_node.hpp.
 { return sparsity().numel(); }
Referenced by casadi::ConstantMX::__nonzero__(), casadi::DaeBuilderInternal::generate_wrapper(), and casadi::DaeBuilderInternal::n_mem().
offset()
casadi_int casadi::MXNode::offset () const virtual inherited
Reimplemented in casadi::IOInstruction.
Definition at line 218 of file mx_node.cpp.
{
     casadi_error("'offset' not defined for class " + class_name());
   }
References casadi::MXNode::class_name().
Referenced by casadi::BSplineParametric::create(), casadi::BSpline::create(), casadi::BSpline::dual(), casadi::MXNode::get_bspline(), casadi::BSplineCommon::get_coeff_size(), and casadi::BSplineCommon::prepare().
op()
casadi_int casadi::ConstantMX::op () const inline override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_z0
Implements casadi::MXNode.
Definition at line 108 of file constant_mx.hpp.
 { return OP_CONST;}
References casadi::OP_CONST.
primitives()
void casadi::ConstantMX::primitives (std::vector< MX >::iterator & it) const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_z3
Reimplemented from casadi::MXNode.
Definition at line 53 of file constant_mx.cpp.
{
     if (nnz()!=0) {
       MXNode::primitives(it);
     }
   }
References casadi::MXNode::nnz(), and casadi::MXNode::primitives().
print_compact()
std::string casadi::MXNode::print_compact (std::map< const MXNode *, casadi_int > & nodeind, std::vector< std::string > & intermed) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1qm
Definition at line 287 of file mx_node.cpp.
{
     // Get reference to node index
     casadi_int& ind = nodeind[this];
     // If positive, already in intermediate expressions
     if (ind>0) return "@" + str(ind);
     // Get expressions for dependencies
     std::vector<std::string> arg(n_dep());
     for (casadi_int i=0; i<arg.size(); ++i) {
       arg[i] = dep(i)->print_compact(nodeind, intermed);
     }
     // Get expression for this
     std::string s = disp(arg);
     // Decide what to do with the expression
     if (ind==0) {
       // Inline expression
       return s;
     } else {
       // Add to list of intermediate expressions and return reference
       intermed.push_back(s);
       ind = intermed.size(); // For subsequent references
       return "@" + str(ind);
     }
   }
References casadi::MXNode::dep(), casadi::MXNode::disp(), casadi::MXNode::ind(), casadi::MXNode::n_dep(), casadi::MXNode::print_compact(), and casadi::str().
Referenced by casadi::MXNode::disp(), and casadi::MXNode::print_compact().
reset_input()
void casadi::ConstantMX::reset_input () const inline override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_z7
Reimplemented from casadi::MXNode.
Definition at line 174 of file constant_mx.hpp.
 {}
sameOpAndDeps()
bool casadi::MXNode::sameOpAndDeps (const MXNode * node, casadi_int depth) const inherited
equivalent dependencies up to a given depth
Extra doc: https://github.com/casadi/casadi/wiki/L_1rl
Definition at line 906 of file mx_node.cpp.
{
     if (op()!=node->op() || n_dep()!=node->n_dep())
       return false;
     for (casadi_int i=0; i<n_dep(); ++i) {
       if (!MX::is_equal(dep(i), node->dep(i), depth-1))
         return false;
     }
     return true;
   }
References casadi::MXNode::dep(), casadi::MX::is_equal(), casadi::MXNode::n_dep(), and casadi::MXNode::op().
Referenced by casadi::GetNonzerosVector::is_equal(), casadi::GetNonzerosSlice::is_equal(), and casadi::GetNonzerosSlice2::is_equal().
segment()
casadi_int casadi::MXNode::segment () const virtual inherited
Reimplemented in casadi::IOInstruction.
Definition at line 214 of file mx_node.cpp.
{
     casadi_error("'segment' not defined for class " + class_name());
   }
References casadi::MXNode::class_name().
Referenced by casadi::MXFunction::print().
serialize()
void casadi::MXNode::serialize (SerializingStream & s) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1rf
Definition at line 448 of file mx_node.cpp.
{
     serialize_type(s);
     serialize_body(s);
   }
References casadi::MXNode::serialize_body(), and casadi::MXNode::serialize_type().
serialize_body()
template<typename Value > void casadi::Constant< Value >::serialize_body (SerializingStream & s) const override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_10e
Reimplemented from casadi::MXNode.
Definition at line 609 of file constant_mx.hpp.
{
     MXNode::serialize_body(s);
   }
References casadi::MXNode::serialize_body().
serialize_type()
template<typename Value > void casadi::Constant< Value >::serialize_type (SerializingStream & s) const override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_10f
Reimplemented from casadi::MXNode.
Definition at line 602 of file constant_mx.hpp.
{
     MXNode::serialize_type(s);
     s.pack("ConstantMX::type", Value::type_char());
     v_.serialize_type(s);
   }
References casadi::SerializingStream::pack(), and casadi::MXNode::serialize_type().
set_dep() [1/4]
void casadi::MXNode::set_dep (const MX & dep) inherited
Definition at line 226 of file mx_node.cpp.
{
     dep_.resize(1);
     dep_[0] = dep;
   }
References casadi::MXNode::dep(), and casadi::MXNode::dep_.
Referenced by casadi::Assertion::Assertion(), casadi::Bilin::Bilin(), casadi::BinaryMX< ScX, ScY >::BinaryMX(), casadi::BSpline::BSpline(), casadi::BSplineParametric::BSplineParametric(), casadi::Call::Call(), casadi::Concat::Concat(), casadi::Convexify::Convexify(), casadi::Determinant::Determinant(), casadi::Dot::Dot(), casadi::Einstein::Einstein(), casadi::Find::Find(), casadi::GetNonzeros::GetNonzeros(), casadi::GetNonzerosParam::GetNonzerosParam(), casadi::HorzRepmat::HorzRepmat(), casadi::HorzRepsum::HorzRepsum(), casadi::Inverse::Inverse(), casadi::LogSumExp::LogSumExp(), casadi::Low::Low(), casadi::MMax::MMax(), casadi::MMin::MMin(), casadi::Monitor::Monitor(), casadi::Multiplication::Multiplication(), casadi::Norm::Norm(), casadi::Output::Output(), casadi::OutputNode::OutputNode(), casadi::Project::Project(), casadi::Rank1::Rank1(), casadi::Reshape::Reshape(), casadi::SparsityCast::SparsityCast(), casadi::Split::Split(), casadi::SubAssign::SubAssign(), casadi::SubRef::SubRef(), casadi::Transpose::Transpose(), and casadi::UnaryMX::UnaryMX().
set_dep() [2/4]
void casadi::MXNode::set_dep (const MX & dep1, const MX & dep2) inherited
Definition at line 231 of file mx_node.cpp.
{
     dep_.resize(2);
     dep_[0] = dep1;
     dep_[1] = dep2;
   }
References casadi::MXNode::dep_.
set_dep() [3/4]
void casadi::MXNode::set_dep (const MX & dep1, const MX & dep2, const MX & dep3) inherited
Definition at line 237 of file mx_node.cpp.
{
     dep_.resize(3);
     dep_[0] = dep1;
     dep_[1] = dep2;
     dep_[2] = dep3;
   }
References casadi::MXNode::dep_.
set_dep() [4/4]
void casadi::MXNode::set_dep (const std::vector< MX > & dep) inherited
Definition at line 244 of file mx_node.cpp.
{
     dep_ = dep;
   }
References casadi::MXNode::dep(), and casadi::MXNode::dep_.
set_sparsity()
void casadi::MXNode::set_sparsity (const Sparsity & sparsity) inherited
Definition at line 222 of file mx_node.cpp.
{
     sparsity_ = sparsity;
   }
References casadi::MXNode::sparsity(), and casadi::MXNode::sparsity_.
Referenced by casadi::Assertion::Assertion(), casadi::Bilin::Bilin(), casadi::BinaryMX< ScX, ScY >::BinaryMX(), casadi::BSpline::BSpline(), casadi::BSplineParametric::BSplineParametric(), casadi::Call::Call(), casadi::ConstantMX::ConstantMX(), casadi::Convexify::Convexify(), casadi::Determinant::Determinant(), casadi::Diagcat::Diagcat(), casadi::Dot::Dot(), casadi::Einstein::Einstein(), casadi::Find::Find(), casadi::GetNonzeros::GetNonzeros(), casadi::GetNonzerosParam::GetNonzerosParam(), casadi::Horzcat::Horzcat(), casadi::HorzRepmat::HorzRepmat(), casadi::HorzRepsum::HorzRepsum(), casadi::Input::Input(), casadi::Inverse::Inverse(), casadi::LogSumExp::LogSumExp(), casadi::Low::Low(), casadi::MMax::MMax(), casadi::MMin::MMin(), casadi::Monitor::Monitor(), casadi::Multiplication::Multiplication(), casadi::Norm::Norm(), casadi::OutputNode::OutputNode(), casadi::Project::Project(), casadi::Rank1::Rank1(), casadi::Reshape::Reshape(), casadi::SparsityCast::SparsityCast(), casadi::Split::Split(), casadi::SymbolicMX::SymbolicMX(), casadi::Transpose::Transpose(), casadi::UnaryMX::UnaryMX(), and casadi::Vertcat::Vertcat().
shared_from_this() [1/2]
template<class B > B casadi::SharedObjectInternal::shared_from_this protected inherited
Template function implementations.
Definition at line 136 of file shared_object_internal.hpp.
{
     casadi_assert_dev(B::test_cast(this));
     B ret;
     ret.own(this);
     return ret;
   }
shared_from_this() [2/2]
template<class B > const B casadi::SharedObjectInternal::shared_from_this protected inherited
Definition at line 144 of file shared_object_internal.hpp.
{
     casadi_assert_dev(B::test_cast(this));
     B ret;
     ret.own(const_cast<SharedObjectInternal*>(this));
     return ret;
   }
size()
std::pair<casadi_int, casadi_int> casadi::MXNode::size () const inline inherited
Definition at line 357 of file mx_node.hpp.
 { return sparsity().size();}
Referenced by casadi::MXNode::_get_binary(), casadi::Reshape::ad_forward(), casadi::Reshape::ad_reverse(), casadi::Reshape::eval_mx(), casadi::MXNode::get_binary(), casadi::MXNode::join_primitives_gen(), casadi::Reshape::join_primitives_gen(), and casadi::Reshape::split_primitives_gen().
size1()
casadi_int casadi::MXNode::size1 () const inline inherited
Definition at line 355 of file mx_node.hpp.
 { return sparsity().size1(); }
Referenced by casadi::ConstantMX::ad_forward(), casadi::MXNode::get_dot(), and casadi::MXNode::get_vertsplit().
size2()
casadi_int casadi::MXNode::size2 () const inline inherited
Definition at line 356 of file mx_node.hpp.
 { return sparsity().size2(); }
Referenced by casadi::ConstantMX::ad_forward(), casadi::MXNode::get_dot(), and casadi::MXNode::get_horzsplit().
sp_forward()
int casadi::ConstantMX::sp_forward (const bvec_t ** arg, bvec_t ** res, casadi_int * iw, bvec_t * w) const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_yy
Reimplemented from casadi::MXNode.
Definition at line 119 of file constant_mx.cpp.
{
     std::fill_n(res[0], nnz(), 0);
     return 0;
   }
References casadi::MXNode::nnz().
sp_reverse()
int casadi::ConstantMX::sp_reverse (bvec_t ** arg, bvec_t ** res, casadi_int * iw, bvec_t * w) const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_yz
Reimplemented from casadi::MXNode.
Definition at line 124 of file constant_mx.cpp.
{
     std::fill_n(res[0], nnz(), 0);
     return 0;
   }
References casadi::MXNode::nnz().
sparsity() [1/2]
const Sparsity& casadi::MXNode::sparsity () const inline inherited
Definition at line 337 of file mx_node.hpp.
 { return sparsity_;}
Referenced by casadi::MXNode::_get_binary(), casadi::GetNonzeros::ad_forward(), casadi::GetNonzerosParamVector::ad_forward(), casadi::GetNonzerosSliceParam::ad_forward(), casadi::GetNonzerosParamSlice::ad_forward(), casadi::GetNonzerosParamParam::ad_forward(), casadi::LogSumExp::ad_forward(), casadi::Multiplication::ad_forward(), casadi::Project::ad_forward(), casadi::Rank1::ad_forward(), casadi::SparsityCast::ad_forward(), casadi::Bilin::ad_reverse(), casadi::GetNonzeros::ad_reverse(), casadi::GetNonzerosParamVector::ad_reverse(), casadi::GetNonzerosSliceParam::ad_reverse(), casadi::GetNonzerosParamSlice::ad_reverse(), casadi::GetNonzerosParamParam::ad_reverse(), casadi::Multiplication::ad_reverse(), casadi::Project::ad_reverse(), casadi::SparsityCast::ad_reverse(), casadi::Diagcat::Diagcat(), casadi::ConstantFile::disp(), casadi::Project::disp(), casadi::Reshape::disp(), casadi::SparsityCast::disp(), casadi::Bilin::eval_gen(), casadi::Multiplication::eval_gen(), casadi::Project::eval_gen(), casadi::Densify::eval_gen(), casadi::Sparsify::eval_gen(), casadi::Rank1::eval_gen(), casadi::HorzRepsum::eval_gen(), casadi::Transpose::eval_gen(), casadi::GetNonzeros::eval_mx(), casadi::GetNonzerosVector::eval_mx(), casadi::GetNonzerosParamVector::eval_mx(), casadi::GetNonzerosSliceParam::eval_mx(), casadi::GetNonzerosParamSlice::eval_mx(), casadi::GetNonzerosParamParam::eval_mx(), casadi::Project::eval_mx(), casadi::SparsityCast::eval_mx(), casadi::Bilin::generate(), casadi::Find::generate(), casadi::Multiplication::generate(), casadi::Project::generate(), casadi::Densify::generate(), casadi::Sparsify::generate(), casadi::Rank1::generate(), casadi::HorzRepmat::generate(), casadi::HorzRepsum::generate(), casadi::Transpose::generate(), casadi::UnaryMX::generate(), casadi::MXNode::get_binary(), casadi::MXNode::get_diagsplit(), casadi::MXNode::get_dot(), casadi::Horzsplit::get_horzcat(), casadi::MXNode::get_horzsplit(), casadi::MXNode::get_mac(), casadi::MXNode::get_nzref(), casadi::MultipleOutput::get_output(), casadi::MXNode::get_project(), casadi::MXNode::get_reshape(), casadi::SparsityCast::get_reshape(), casadi::MXNode::get_sparsity_cast(), casadi::MXNode::get_transpose(), casadi::Reshape::get_transpose(), casadi::SparsityCast::get_transpose(), casadi::MXNode::get_unary(), casadi::MXNode::get_vertsplit(), casadi::Horzcat::Horzcat(), casadi::ConstantDM::is_equal(), casadi::Constant< Value >::is_equal(), casadi::GetNonzerosVector::is_equal(), casadi::GetNonzerosSlice::is_equal(), casadi::GetNonzerosSlice2::is_equal(), casadi::Reshape::is_equal(), casadi::SetNonzerosVector< Add >::is_equal(), casadi::SetNonzerosSlice< Add >::is_equal(), casadi::SetNonzerosSlice2< Add >::is_equal(), casadi::SparsityCast::is_equal(), casadi::ConstantMX::join_primitives_gen(), casadi::SparsityCast::join_primitives_gen(), casadi::GetNonzeros::mapping(), casadi::OutputNode::OutputNode(), casadi::MXFunction::print_res(), casadi::MXNode::set_sparsity(), casadi::MXNode::sp_forward(), casadi::Multiplication::sp_forward(), casadi::Project::sp_forward(), casadi::Rank1::sp_forward(), casadi::HorzRepsum::sp_forward(), casadi::Split::sp_forward(), casadi::Transpose::sp_forward(), casadi::MXNode::sp_reverse(), casadi::Multiplication::sp_reverse(), casadi::Project::sp_reverse(), casadi::Rank1::sp_reverse(), casadi::HorzRepmat::sp_reverse(), casadi::HorzRepsum::sp_reverse(), casadi::Split::sp_reverse(), casadi::Transpose::sp_reverse(), casadi::SparsityCast::split_primitives_gen(), casadi::UnaryMX::UnaryMX(), and casadi::Vertcat::Vertcat().
sparsity() [2/2]
const Sparsity & casadi::MXNode::sparsity (casadi_int oind) const virtual inherited
Reimplemented in casadi::MultipleOutput, casadi::Split, and casadi::Call.
Definition at line 248 of file mx_node.cpp.
{
     casadi_assert(oind==0, "Index out of bounds");
     return sparsity_;
   }
References casadi::MXNode::sparsity_.
split_primitives() [1/3]
void casadi::ConstantMX::split_primitives (const DM & x, std::vector< DM >::iterator & it) const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_z4
Reimplemented from casadi::MXNode.
Definition at line 74 of file constant_mx.cpp.
{
     split_primitives_gen<DM>(x, it);
   }
split_primitives() [2/3]
void casadi::ConstantMX::split_primitives (const MX & x, std::vector< MX >::iterator & it) const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_z4
Reimplemented from casadi::MXNode.
Definition at line 66 of file constant_mx.cpp.
{
     split_primitives_gen<MX>(x, it);
   }
split_primitives() [3/3]
void casadi::ConstantMX::split_primitives (const SX & x, std::vector< SX >::iterator & it) const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_z4
Reimplemented from casadi::MXNode.
Definition at line 70 of file constant_mx.cpp.
{
     split_primitives_gen<SX>(x, it);
   }
split_primitives_gen()
template<typename T > void casadi::ConstantMX::split_primitives_gen (const T & x, typename std::vector< T >::iterator & it) const inherited
Definition at line 60 of file constant_mx.cpp.
{
     if (nnz()!=0) {
       MXNode::split_primitives(x, it);
     }
   }
References casadi::MXNode::nnz(), and casadi::MXNode::split_primitives().
sz_arg()
virtual size_t casadi::MXNode::sz_arg () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1rq
Reimplemented in casadi::Call.
Definition at line 374 of file mx_node.hpp.
 { return n_dep();}
sz_iw()
virtual size_t casadi::MXNode::sz_iw () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1rs
Reimplemented in casadi::DenseTranspose, casadi::Transpose, casadi::SetNonzerosParamParam< Add >, casadi::SetNonzerosParamSlice< Add >, casadi::GetNonzerosParamParam, casadi::GetNonzerosParamSlice, casadi::Convexify, casadi::Call, and casadi::BSplineCommon.
Definition at line 384 of file mx_node.hpp.
 { return 0;}
sz_res()
virtual size_t casadi::MXNode::sz_res () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1rr
Reimplemented in casadi::Call.
Definition at line 379 of file mx_node.hpp.
 { return nout();}
sz_w()
virtual size_t casadi::MXNode::sz_w () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1rt
Reimplemented in casadi::LinsolCall< Tr >, casadi::Sparsify, casadi::Densify, casadi::Project, casadi::Multiplication, casadi::Einstein, casadi::Convexify, casadi::Call, and casadi::BSplineCommon.
Definition at line 389 of file mx_node.hpp.
 { return 0;}
to_double()
template<typename Value > double casadi::Constant< Value >::to_double () const inline override virtual
Implements casadi::ConstantMX.
Definition at line 548 of file constant_mx.hpp.
{
       return static_cast<double>(v_.value);
     }
to_matrix()
static MX casadi::MXNode::to_matrix (const MX & x, const Sparsity & sp) inline static inherited
Definition at line 404 of file mx_node.hpp.
{
       if (x.size()==sp.size()) {
         return x;
       } else {
         return MX(sp, x);
       }
     }
References casadi::GenericMatrix< MatType >::size(), and casadi::Sparsity::size().
Referenced by casadi::MXNode::get_binary().
weak()
WeakRef * casadi::SharedObjectInternal::weak () inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1ai
Definition at line 62 of file shared_object_internal.cpp.
{
     if (weak_ref_==nullptr) {
       weak_ref_ = new WeakRef(this);
     }
     return weak_ref_;
   }
Referenced by casadi::SharedObject::weak().
which_function()
const Function & casadi::MXNode::which_function () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1rd
Reimplemented in casadi::Call.
Definition at line 316 of file mx_node.cpp.
{
     casadi_error("'which_function' not defined for class " + class_name());
   }
References casadi::MXNode::class_name().
which_output()
casadi_int casadi::MXNode::which_output () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1rc
Reimplemented in casadi::OutputNode, and casadi::Call.
Definition at line 320 of file mx_node.cpp.
{
     casadi_error("'which_output' not defined for class " + class_name());
   }
References casadi::MXNode::class_name().
Referenced by casadi::Diagsplit::get_diagcat(), casadi::Horzsplit::get_horzcat(), and casadi::Vertsplit::get_vertcat().
Member Data Documentation
dep_
std::vector<MX> casadi::MXNode::dep_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1sj
Definition at line 724 of file mx_node.hpp.
Referenced by casadi::MXNode::MXNode(), casadi::MXNode::n_dep(), casadi::MXNode::serialize_body(), casadi::MXNode::set_dep(), and casadi::MXNode::~MXNode().
deserialize_map
std::map< casadi_int, MXNode *(*)(DeserializingStream &)> casadi::MXNode::deserialize_map static inherited
Definition at line 741 of file mx_node.hpp.
Referenced by casadi::MXNode::deserialize().
sparsity_
Sparsity casadi::MXNode::sparsity_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1sk
Definition at line 729 of file mx_node.hpp.
Referenced by casadi::ConstantDM::ConstantDM(), casadi::MXNode::get_mmax(), casadi::MXNode::get_mmin(), casadi::MXNode::MXNode(), casadi::MXNode::serialize_body(), casadi::MXNode::set_sparsity(), and casadi::MXNode::sparsity().
temp
casadi_int casadi::MXNode::temp mutable inherited
Temporary variables to be used in user algorithms like sorting, the user is responsible of making sure that use is thread-safe The variable is initialized to zero
Definition at line 719 of file mx_node.hpp.
Referenced by casadi::SymbolicMX::has_duplicates(), casadi::MXNode::MXNode(), and casadi::SymbolicMX::reset_input().
v_
template<typename Value > Value casadi::Constant< Value >::v_
Definition at line 598 of file constant_mx.hpp.
The documentation for this class was generated from the following file:
constant_mx.hpp