CasADi: casadi::Importer Class Reference
casadi::Importer Class Reference
Importer.
#include <importer.hpp>
Detailed Description
Just-in-time compilation of code
General information
List of plugins
- clang
- shell
Note: some of the plugins in this list might not be available on your system. Also, there might be extra plugins available to you that are not listed here. You can obtain their documentation with Importer.doc("myextraplugin")
clang
Interface to the JIT compiler CLANG
Extra doc: https://github.com/casadi/casadi/wiki/L_21v
List of available options
Id Type Description
flags OT_STRINGVECTOR Compile flags for the JIT compiler. Default: None
include_path OT_STRING Include paths for the JIT compiler. The include directory shipped with CasADi will be automatically appended.
shell
Interface to the JIT compiler SHELL
Extra doc: https://github.com/casadi/casadi/wiki/L_22w
List of available options
Id Type Description
cleanup OT_BOOL Cleanup temporary files when unloading. Default: true
compiler OT_STRING Compiler command
compiler_flags OT_STRINGVECTOR Alias for 'compiler_flags'
compiler_output_flag OT_STRING Compiler flag to denote object output. Default: '-o '
compiler_setup OT_STRING Compiler setup command. Intended to be fixed. The 'flag' option is the prefered way to set custom flags.
directory OT_STRING Directory to put temporary objects in. Must end with a file separator.
extra_suffixes OT_STRINGVECTOR List of suffixes for extra files that the compiler may generate. Default: None
flags OT_STRINGVECTOR Compile flags for the JIT compiler. Default: None
linker OT_STRING Linker command
linker_flags OT_STRINGVECTOR Linker flags for the JIT compiler. Default: None
linker_output_flag OT_STRING Linker flag to denote shared library output. Default: '-o '
linker_setup OT_STRING Linker setup command. Intended to be fixed. The 'flag' option is the prefered way to set custom flags.
name OT_STRING The file name used to write out compiled objects/libraries. The actual file names used depend on 'temp_suffix' and include extensions. Default: 'tmp_casadi_compiler_shell'
temp_suffix OT_BOOL Use a temporary (seemingly random) filename suffix for file names. This is desired for thread-safety. This behaviour may defeat caching compiler wrappers. Default: true
Author
Joris Gillis
Date
2015
Extra doc: https://github.com/casadi/casadi/wiki/L_161
Definition at line 84 of file importer.hpp.
Public Member Functions
Importer ()
Default constructor.
Importer (const std::string &name, const std::string &compiler, const Dict &opts=Dict())
Importer factory.
ImporterInternal * operator-> ()
Access functions of the node.
const ImporterInternal * operator-> () const
std::string plugin_name () const
Query plugin name.
bool has_function (const std::string &symname) const
signal_t get_function (const std::string &symname)
Get a function pointer for numerical evaluation.
bool has_meta (const std::string &cmd, casadi_int ind=-1) const
Does a meta entry exist?
std::string get_meta (const std::string &cmd, casadi_int ind=-1) const
Get entry as a text.
bool inlined (const std::string &symname) const
Check if a function is inlined.
std::string body (const std::string &symname) const
Get the function body, if inlined.
std::string library () const
Get library name.
template<typename T >
T to (const std::string &cmd, casadi_int ind=-1) const
Convert to a type.
std::string meta_string (const std::string &cmd, casadi_int ind=-1) const
Get entry as a string.
template<typename T >
std::vector< T > meta_vector (const std::string &cmd, casadi_int ind=-1) const
Get entry as a vector.
template<typename T >
std::set< T > meta_set (const std::string &cmd, casadi_int ind=-1) const
Get entry as a set.
casadi_int meta_int (const std::string &cmd, casadi_int ind=-1) const
Get entry as an integer.
void serialize (SerializingStream &s) const
Serialize an object.
void own (SharedObjectInternal *node)
void assign (SharedObjectInternal *node)
Assign the node to a node class pointer without reference counting.
SharedObjectInternal * get () const
Get a const pointer to the node.
casadi_int getCount () const
Get the reference count.
void swap (SharedObject &other)
Swap content with another instance.
std::string class_name () const
Get class name.
void disp (std::ostream &stream, bool more=false) const
Print a description of the object.
std::string get_str (bool more=false) const
Get string representation.
void print_ptr (std::ostream &stream=casadi::uout()) const
bool is_null () const
Is a null pointer?
casadi_int __hash__ () const
Returns a number that is unique for a given Node.
WeakRef * weak ()
Get a weak reference to the object.
Static Public Member Functions
static std::string type_name ()
Get type name.
static bool test_cast (const SharedObjectInternal *ptr)
Check if a particular cast is allowed.
static bool has_plugin (const std::string &name)
Check if a plugin is available.
static void load_plugin (const std::string &name)
Explicitly load a plugin dynamically.
static std::string doc (const std::string &name)
Get solver specific documentation.
static Importer create (ImporterInternal *node)
Create from node.
static Importer create (ImporterInternal *node, const Dict &opts)
Create from node and initialize.
static std::string indexed (const std::string &cmd, casadi_int ind)
static Importer deserialize (DeserializingStream &s)
Deserialize with type disambiguation.
Protected Member Functions
void count_up ()
void count_down ()
Constructor & Destructor Documentation
Importer() [1/2]
casadi::Importer::Importer ()
Definition at line 31 of file importer.cpp.
                      {
   }
Importer() [2/2]
casadi::Importer::Importer (const std::string & name, const std::string & compiler, const Dict & opts = Dict()) explicit
Definition at line 34 of file importer.cpp.
{
     if (compiler=="none") {
       own(new ImporterInternal(name));
     } else if (compiler=="dll") {
       own(new DllLibrary(name));
     } else {
       own(ImporterInternal::getPlugin(compiler).creator(name));
     }
     (*this)->construct(opts);
   }
References casadi::PluginInterface< ImporterInternal >::getPlugin(), and casadi::SharedObject::own().
Member Function Documentation
__hash__()
casadi_int casadi::SharedObject::__hash__ () const inherited
If the Object does not point to any node, "0" is returned.
Extra doc: https://github.com/casadi/casadi/wiki/L_av
Definition at line 129 of file shared_object.cpp.
{
     return reinterpret_cast<casadi_int>(get());
   }
References casadi::SharedObject::get().
assign()
void casadi::SharedObject::assign (SharedObjectInternal * node) inherited
improper use will cause memory leaks!
Extra doc: https://github.com/casadi/casadi/wiki/L_at
Definition at line 52 of file shared_object.cpp.
{
     node = node_;
   }
Referenced by casadi::GenericType::to_double_vector_vector().
body()
std::string casadi::Importer::body (const std::string & symname) const
Definition at line 95 of file importer.cpp.
{
     return (*this)->body(symname);
   }
Referenced by casadi::External::codegen_body().
class_name()
std::string casadi::SharedObject::class_name () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_au
Definition at line 99 of file shared_object.cpp.
{
     return (*this)->class_name();
   }
Referenced by casadi::MXFunction::export_code_body().
count_down()
void casadi::SharedObject::count_down () protected inherited
Definition at line 84 of file shared_object.cpp.
{
 #ifdef WITH_EXTRA_CHECKS
     casadi_assert_dev(Function::call_depth_==0);
 #endif // WITH_EXTRA_CHECKS
     if (node && --node->count == 0) {
       delete node;
       node = nullptr;
     }
   }
Referenced by casadi::SharedObject::operator=(), casadi::SharedObject::own(), and casadi::SharedObject::~SharedObject().
count_up()
void casadi::SharedObject::count_up () protected inherited
Definition at line 77 of file shared_object.cpp.
{
 #ifdef WITH_EXTRA_CHECKS
     casadi_assert_dev(Function::call_depth_==0);
 #endif // WITH_EXTRA_CHECKS
     if (node) node->count++;
   }
Referenced by casadi::SharedObject::operator=(), casadi::SharedObject::own(), and casadi::SharedObject::SharedObject().
create() [1/2]
Importer casadi::Importer::create (ImporterInternal * node) static
Extra doc: https://github.com/casadi/casadi/wiki/L_163
Definition at line 111 of file importer.cpp.
{
     Importer ret;
     ret.own(node);
     return ret;
   }
References casadi::SharedObject::own().
Referenced by create(), and deserialize().
create() [2/2]
Importer casadi::Importer::create (ImporterInternal * node, const Dict & opts) static
Extra doc: https://github.com/casadi/casadi/wiki/L_164
Definition at line 117 of file importer.cpp.
{
     Importer ret = create(node);
     ret->construct(opts);
     return ret;
   }
References casadi::ImporterInternal::construct(), and create().
deserialize()
Importer casadi::Importer::deserialize (DeserializingStream & s) static
Extra doc: https://github.com/casadi/casadi/wiki/L_16d
Definition at line 107 of file importer.cpp.
{
     return Importer::create(ImporterInternal::deserialize(s));
   }
References create(), and casadi::ImporterInternal::deserialize().
disp()
void casadi::SharedObject::disp (std::ostream & stream, bool more = false) const inherited
Definition at line 103 of file shared_object.cpp.
{
     if (is_null()) {
       stream << "NULL";
     } else {
       (*this)->disp(stream, more);
     }
   }
References casadi::SharedObject::is_null().
Referenced by casadi::Nlpsol::disp_more(), and casadi::CsparseInterface::nfact().
doc()
std::string casadi::Importer::doc (const std::string & name) static
Definition at line 67 of file importer.cpp.
{
     return ImporterInternal::getPlugin(name).doc;
   }
References casadi::PluginInterface< ImporterInternal >::getPlugin().
get()
SharedObjectInternal * casadi::SharedObject::get () const inherited
Definition at line 69 of file shared_object.cpp.
{
     return node;
   }
Referenced by casadi::SharedObject::__hash__(), casadi::GenericType::as_bool(), casadi::GenericType::as_bool_vector(), casadi::GenericType::as_dict(), casadi::GenericType::as_double(), casadi::GenericType::as_double_vector(), casadi::GenericType::as_double_vector_vector(), casadi::GenericType::as_function(), casadi::GenericType::as_function_vector(), casadi::GenericType::as_int(), casadi::GenericType::as_int_vector(), casadi::GenericType::as_int_vector_vector(), casadi::GenericType::as_string(), casadi::GenericType::as_string_vector(), casadi::GenericType::as_void_pointer(), casadi::Function::get(), casadi::MX::get(), casadi::Sparsity::get(), casadi::DaeBuilder::get(), casadi::GenericType::getType(), and casadi::GenericType::serialize().
get_function()
signal_t casadi::Importer::get_function (const std::string & symname)
Definition at line 79 of file importer.cpp.
{
     return (*this)->get_function(symname);
   }
Referenced by casadi::FunctionInternal::finalize(), casadi::External::init_external(), and casadi::GenericExternal::init_external().
get_meta()
std::string casadi::Importer::get_meta (const std::string & cmd, casadi_int ind = -1) const
Extra doc: https://github.com/casadi/casadi/wiki/L_166
Definition at line 87 of file importer.cpp.
{
     return (*this)->get_meta(cmd, ind);
   }
get_str()
std::string casadi::SharedObject::get_str (bool more = false) const inline inherited
Definition at line 138 of file shared_object.hpp.
{
       std::stringstream ss;
       disp(ss, more);
       return ss.str();
     }
getCount()
casadi_int casadi::SharedObject::getCount () const inherited
Definition at line 121 of file shared_object.cpp.
{
     return (*this)->getCount();
   }
Referenced by casadi::MXNode::~MXNode().
has_function()
bool casadi::Importer::has_function (const std::string & symname) const
Definition at line 75 of file importer.cpp.
{
     return (*this)->has_function(symname);
   }
Referenced by casadi::External::factory(), casadi::External::has_forward(), casadi::External::has_jacobian(), casadi::External::has_reverse(), and casadi::External::init().
has_meta()
bool casadi::Importer::has_meta (const std::string & cmd, casadi_int ind = -1) const
Extra doc: https://github.com/casadi/casadi/wiki/L_165
Definition at line 83 of file importer.cpp.
{
     return (*this)->has_meta(cmd, ind);
   }
Referenced by casadi::GenericExternal::get_jac_sparsity(), casadi::External::get_n_in(), casadi::External::get_n_out(), casadi::External::get_name_in(), casadi::External::get_name_out(), casadi::GenericExternal::get_sparsity_in(), casadi::GenericExternal::get_sparsity_out(), casadi::GenericExternal::has_jac_sparsity(), and casadi::External::init().
has_plugin()
bool casadi::Importer::has_plugin (const std::string & name) static
Definition at line 59 of file importer.cpp.
{
     return ImporterInternal::has_plugin(name);
   }
References casadi::PluginInterface< ImporterInternal >::has_plugin().
indexed()
static std::string casadi::Importer::indexed (const std::string & cmd, casadi_int ind) inline static
Convert indexed command
Definition at line 163 of file importer.hpp.
{
       std::stringstream ss;
       ss << cmd << "[" << ind << "]";
       return ss.str();
     }
inlined()
bool casadi::Importer::inlined (const std::string & symname) const
Definition at line 91 of file importer.cpp.
{
     return (*this)->inlined(symname);
   }
Referenced by casadi::External::codegen_body(), and casadi::External::codegen_declarations().
is_null()
bool casadi::SharedObject::is_null () const inherited
Definition at line 73 of file shared_object.cpp.
{
     return node==nullptr;
   }
Referenced by casadi::FunctionInternal::add_embedded(), casadi::WeakRef::alive(), casadi::FunctionInternal::alloc(), casadi::Nlpsol::callback(), casadi::DaeBuilderInternal::clear_cache(), casadi::Switch::codegen_body(), casadi::Conic::Conic(), casadi::conic_debug(), casadi::Callback::construct(), casadi::Function::deserialize(), casadi::SharedObject::disp(), casadi::FunctionInternal::finalize(), casadi::Switch::find(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::get_n_in(), casadi::Switch::get_n_in(), casadi::FunctionInternal::get_n_out(), casadi::Switch::get_n_out(), casadi::FunctionInternal::get_name_in(), casadi::FunctionInternal::get_name_out(), casadi::FunctionInternal::get_partition(), casadi::FunctionInternal::get_sparsity_in(), casadi::Switch::get_sparsity_in(), casadi::FunctionInternal::get_sparsity_out(), casadi::Switch::get_sparsity_out(), casadi::MXFunction::get_stats(), casadi::GenericType::getType(), casadi::Sparsity::info(), casadi::Nlpsol::init(), casadi::Rootfinder::init(), casadi::Switch::init(), casadi::SnoptInterface::init(), casadi::SundialsInterface::init(), casadi::FastNewton::init(), casadi::Newton::init(), casadi::Scpgen::init(), casadi::BonminInterface::intermediate_callback(), casadi::IpoptInterface::intermediate_callback(), casadi::XFunction< DerivedType, MatType, NodeType >::jac(), casadi::FunctionInternal::jac_is_symm(), casadi::FunctionInternal::jac_sparsity(), casadi::OracleFunction::jit_dependencies(), casadi::SparsityInternal::maxtrans(), casadi::Function::name(), casadi::Function::operator->(), casadi::SharedObject::operator->(), casadi::Function::operator==(), casadi::DaeBuilderInternal::oracle(), casadi::Function::serialize(), casadi::Sparsity::serialize(), casadi::SnoptInterface::set_work(), casadi::OptiNode::solve(), casadi::KnitroInterface::solve(), casadi::WorhpInterface::solve(), casadi::FunctionInternal::sp_forward_block(), casadi::FunctionInternal::sp_reverse(), casadi::Sparsity::uni_coloring(), and casadi::Callback::~Callback().
library()
std::string casadi::Importer::library () const
Definition at line 99 of file importer.cpp.
{
     return (*this)->library();
   }
Referenced by casadi::FunctionInternal::serialize_body().
load_plugin()
void casadi::Importer::load_plugin (const std::string & name) static
Definition at line 63 of file importer.cpp.
{
     ImporterInternal::load_plugin(name);
   }
References casadi::PluginInterface< ImporterInternal >::load_plugin().
meta_int()
casadi_int casadi::Importer::meta_int (const std::string & cmd, casadi_int ind = -1) const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_16b
Definition at line 203 of file importer.hpp.
{
       return to<casadi_int>(cmd, ind);
     }
Referenced by casadi::External::get_n_in(), and casadi::External::get_n_out().
meta_set()
template<typename T > std::set<T> casadi::Importer::meta_set (const std::string & cmd, casadi_int ind = -1) const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_16a
Definition at line 196 of file importer.hpp.
{
       return text2set<T>(get_meta(cmd, ind));
     }
meta_string()
std::string casadi::Importer::meta_string (const std::string & cmd, casadi_int ind = -1) const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_168
Definition at line 180 of file importer.hpp.
{
       return to<std::string>(cmd, ind);
     }
Referenced by casadi::External::get_name_in(), and casadi::External::get_name_out().
meta_vector()
template<typename T > std::vector<T> casadi::Importer::meta_vector (const std::string & cmd, casadi_int ind = -1) const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_169
Definition at line 188 of file importer.hpp.
{
       return text2vector<T>(get_meta(cmd, ind));
     }
Referenced by casadi::GenericExternal::get_jac_sparsity(), casadi::GenericExternal::get_sparsity_in(), casadi::GenericExternal::get_sparsity_out(), and casadi::External::init().
operator->() [1/2]
ImporterInternal * casadi::Importer::operator-> ()
Definition at line 47 of file importer.cpp.
{
     return static_cast<ImporterInternal*>(SharedObject::operator->());
   }
References casadi::SharedObject::operator->().
operator->() [2/2]
const ImporterInternal * casadi::Importer::operator-> () const
Definition at line 51 of file importer.cpp.
{
     return static_cast<const ImporterInternal*>(SharedObject::operator->());
   }
References casadi::SharedObject::operator->().
own()
void casadi::SharedObject::own (SharedObjectInternal * node) inherited
Assign the node to a node class pointer (or null)
Definition at line 46 of file shared_object.cpp.
{
     count_down();
     node = node_;
     count_up();
   }
References casadi::SharedObject::count_down(), and casadi::SharedObject::count_up().
Referenced by casadi::Callback::construct(), casadi::Function::construct(), casadi::Function::create(), create(), casadi::Linsol::create(), casadi::GenericType::create(), casadi::Sparsity::create(), casadi::DaeBuilder::DaeBuilder(), casadi::FunctionInternal::deserialize(), casadi::Linsol::deserialize(), casadi::GenericType::GenericType(), casadi::LinearInterpolant::get_jacobian(), Importer(), casadi::MXFunction::init(), casadi::Linsol::Linsol(), casadi::MX::MX(), casadi::Opti::Opti(), casadi::WeakRef::shared(), casadi::WeakRef::WeakRef(), and casadi::XmlFile::XmlFile().
plugin_name()
std::string casadi::Importer::plugin_name () const
Definition at line 71 of file importer.cpp.
{
     return (*this)->plugin_name();
   }
print_ptr()
void casadi::SharedObject::print_ptr (std::ostream & stream = casadi::uout()) const inherited
Print the pointer to the internal class
Definition at line 111 of file shared_object.cpp.
{
     stream << node;
   }
serialize()
void casadi::Importer::serialize (SerializingStream & s) const
Extra doc: https://github.com/casadi/casadi/wiki/L_16c
Definition at line 103 of file importer.cpp.
{
     return (*this)->serialize(s);
   }
swap()
void casadi::SharedObject::swap (SharedObject & other) inherited
Definition at line 115 of file shared_object.cpp.
{
     SharedObject temp = *this;
     *this = other;
     other = temp;
   }
test_cast()
bool casadi::Importer::test_cast (const SharedObjectInternal * ptr) static
Definition at line 55 of file importer.cpp.
{
     return dynamic_cast<const ImporterInternal*>(ptr)!=nullptr;
   }
to()
template<typename T > T casadi::Importer::to (const std::string & cmd, casadi_int ind = -1) const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_167
Definition at line 173 of file importer.hpp.
{
       return text2type<T>(get_meta(cmd, ind));
     }
type_name()
static std::string casadi::Importer::type_name () inline static
Extra doc: https://github.com/casadi/casadi/wiki/L_162
Definition at line 91 of file importer.hpp.
 {return "Importer";}
weak()
WeakRef * casadi::SharedObject::weak () inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_aw
Definition at line 125 of file shared_object.cpp.
{
     return (*this)->weak();
   }
References casadi::SharedObjectInternal::weak().
Referenced by casadi::WeakRef::WeakRef().
The documentation for this class was generated from the following files:
importer.hpp
importer.cpp