CasADi: casadi::casadi_math< casadi_int > Struct Reference
casadi::casadi_math< casadi_int > Struct Reference
Specialize the class so that it can be used with integer type.
#include <calculus.hpp>
Detailed Description
Definition at line 1188 of file calculus.hpp.
Static Public Member Functions
static void fun (unsigned char op, const casadi_int &x, const casadi_int &y, casadi_int &f)
Evaluate a built in function.
static void fun (unsigned char op, const casadi_int *x, const casadi_int *y, casadi_int *f, casadi_int n)
static void fun (unsigned char op, const casadi_int *x, const casadi_int &y, casadi_int *f, casadi_int n)
static void fun (unsigned char op, const casadi_int &x, const casadi_int *y, casadi_int *f, casadi_int n)
static void der (unsigned char op, const casadi_int &x, const casadi_int &y, const casadi_int &f, casadi_int *d)
Evaluate a built in derivative function.
static void derF (unsigned char op, const casadi_int &x, const casadi_int &y, casadi_int &f, casadi_int *d)
Evaluate the function and the derivative function.
static casadi_int ndeps (unsigned char op)
Number of dependencies.
static std::string print (unsigned char op, const std::string &x, const std::string &y)
Print.
static std::string print (unsigned char op, const std::string &x)
static std::string pre (unsigned char op)
static std::string name (unsigned char op)
static std::string sep (unsigned char op)
static std::string post (unsigned char op)
Member Function Documentation
der()
static void casadi::casadi_math< casadi_int >::der (unsigned char op, const casadi_int & x, const casadi_int & y, const casadi_int & f, casadi_int * d) inline static
Extra doc: https://github.com/casadi/casadi/wiki/L_1gh
Definition at line 1230 of file calculus.hpp.
{
       double d_real[2] = {static_cast<double>(d[0]), static_cast<double>(d[1])};
       casadi_math<double>::der(op, static_cast<double>(x), static_cast<double>(y),
                                static_cast<double>(f), d_real);
       d[0] = static_cast<casadi_int>(d_real[0]);
       d[1] = static_cast<casadi_int>(d_real[1]);
     }
References casadi::casadi_math< T >::der().
derF()
static void casadi::casadi_math< casadi_int >::derF (unsigned char op, const casadi_int & x, const casadi_int & y, casadi_int & f, casadi_int * d) inline static
Extra doc: https://github.com/casadi/casadi/wiki/L_1gi
Definition at line 1242 of file calculus.hpp.
{
       double d_real[2] = {static_cast<double>(d[0]), static_cast<double>(d[1])};
       double f_real = static_cast<double>(f);
       casadi_math<double>::derF(op, static_cast<double>(x), static_cast<double>(y), f_real, d_real);
       f = static_cast<casadi_int>(f_real);
       d[0] = static_cast<casadi_int>(d_real[0]);
       d[1] = static_cast<casadi_int>(d_real[1]);
     }
References casadi::casadi_math< T >::derF().
fun() [1/4]
static void casadi::casadi_math< casadi_int >::fun (unsigned char op, const casadi_int & x, const casadi_int & y, casadi_int & f) inline static
Extra doc: https://github.com/casadi/casadi/wiki/L_1gg
Definition at line 1193 of file calculus.hpp.
{
       double ff(0);
       casadi_math<double>::fun(op, static_cast<double>(x), static_cast<double>(y), ff);
       f = static_cast<casadi_int>(ff);
     }
References casadi::casadi_math< T >::fun().
fun() [2/4]
static void casadi::casadi_math< casadi_int >::fun (unsigned char op, const casadi_int & x, const casadi_int * y, casadi_int * f, casadi_int n) inline static
Definition at line 1218 of file calculus.hpp.
{
       for (casadi_int i=0; i<n; ++i) {
         double ff;
         casadi_math<double>::fun(op, static_cast<double>(x), static_cast<double>(*y++), ff);
         *f++ = static_cast<casadi_int>(ff);
       }
     }
References casadi::casadi_math< T >::fun().
fun() [3/4]
static void casadi::casadi_math< casadi_int >::fun (unsigned char op, const casadi_int * x, const casadi_int & y, casadi_int * f, casadi_int n) inline static
Definition at line 1209 of file calculus.hpp.
{
       for (casadi_int i=0; i<n; ++i) {
         double ff;
         casadi_math<double>::fun(op, static_cast<double>(*x++), static_cast<double>(y), ff);
         *f++ = static_cast<casadi_int>(ff);
       }
     }
References casadi::casadi_math< T >::fun().
fun() [4/4]
static void casadi::casadi_math< casadi_int >::fun (unsigned char op, const casadi_int * x, const casadi_int * y, casadi_int * f, casadi_int n) inline static
Definition at line 1200 of file calculus.hpp.
{
       for (casadi_int i=0; i<n; ++i) {
         double ff(0);
         casadi_math<double>::fun(op, static_cast<double>(*x++), static_cast<double>(*y++), ff);
         *f++ = static_cast<casadi_int>(ff);
       }
     }
References casadi::casadi_math< T >::fun().
name()
static std::string casadi::casadi_math< casadi_int >::name (unsigned char op) inline static
Definition at line 1272 of file calculus.hpp.
{
       return casadi_math<double>::name(op);
     }
References casadi::casadi_math< T >::name().
ndeps()
static casadi_int casadi::casadi_math< casadi_int >::ndeps (unsigned char op) inline static
Extra doc: https://github.com/casadi/casadi/wiki/L_1gj
Definition at line 1255 of file calculus.hpp.
{
       return casadi_math<double>::ndeps(op);
     }
References casadi::casadi_math< T >::ndeps().
post()
static std::string casadi::casadi_math< casadi_int >::post (unsigned char op) inline static
Definition at line 1278 of file calculus.hpp.
{
       return casadi_math<double>::post(op);
     }
References casadi::casadi_math< T >::post().
pre()
static std::string casadi::casadi_math< casadi_int >::pre (unsigned char op) inline static
Definition at line 1269 of file calculus.hpp.
{
       return casadi_math<double>::pre(op);
     }
References casadi::casadi_math< T >::pre().
print() [1/2]
static std::string casadi::casadi_math< casadi_int >::print (unsigned char op, const std::string & x) inline static
Definition at line 1266 of file calculus.hpp.
{
       return casadi_math<double>::print(op, x);
     }
References casadi::casadi_math< T >::print().
print() [2/2]
static std::string casadi::casadi_math< casadi_int >::print (unsigned char op, const std::string & x, const std::string & y) inline static
Extra doc: https://github.com/casadi/casadi/wiki/L_1gk
Definition at line 1262 of file calculus.hpp.
{
       return casadi_math<double>::print(op, x, y);
     }
References casadi::casadi_math< T >::print().
sep()
static std::string casadi::casadi_math< casadi_int >::sep (unsigned char op) inline static
Definition at line 1275 of file calculus.hpp.
{
       return casadi_math<double>::sep(op);
     }
References casadi::casadi_math< T >::sep().
The documentation for this struct was generated from the following file:
calculus.hpp