CasADi: casadi::OptiSol Class Reference
casadi::OptiSol Class Reference
A simplified interface for NLP modeling/solving.
#include <optistack.hpp>
Detailed Description
This class offers a view with solution retrieval facilities The API is guaranteed to be stable.
Date
2017
Author
Joris Gillis, Erik Lambrechts
Extra doc: https://github.com/casadi/casadi/wiki/L_1v
Definition at line 605 of file optistack.hpp.
Public Member Functions
std::string type_name () const
void disp (std::ostream &stream, bool more=false) const
std::string get_str (bool more=false) const
std::vector< MX > value_variables () const
get assignment expressions for the optimal solution
std::vector< MX > value_parameters () const
Dict stats () const
Get statistics.
Opti opti () const
native_DM value (const MX &x, const std::vector< MX > &values=std::vector< MX >()) const
native_DM value (const DM &x, const std::vector< MX > &values=std::vector< MX >()) const
native_DM value (const SX &x, const std::vector< MX > &values=std::vector< MX >()) const
Protected Member Functions
OptiSol (const Opti &opti)
Protected Attributes
OptiAdvanced optistack_
Friends
class OptiNode
Constructor & Destructor Documentation
OptiSol()
casadi::OptiSol::OptiSol (const Opti & opti) protected
Definition at line 743 of file optistack.cpp.
                                  : optistack_(opti) {
 }
Member Function Documentation
disp()
void casadi::OptiSol::disp (std::ostream & stream, bool more = false) const
Definition at line 746 of file optistack.cpp.
{
   optistack_.disp(stream, more);
 }
References casadi::Opti::disp(), and optistack_.
get_str()
std::string casadi::OptiSol::get_str (bool more = false) const
Definition at line 750 of file optistack.cpp.
{
   return optistack_.get_str(more);
 }
References casadi::Opti::get_str(), and optistack_.
opti()
Opti casadi::OptiSol::opti () const inline
Definition at line 637 of file optistack.hpp.
 { return optistack_; } // NOLINT(cppcoreguidelines-slicing)
stats()
Dict casadi::OptiSol::stats () const
nlpsol stats are passed as-is. No stability can be guaranteed about this part of the API
Extra doc: https://github.com/casadi/casadi/wiki/L_1w
Definition at line 772 of file optistack.cpp.
{
   return optistack_.stats();
 }
References optistack_, and casadi::Opti::stats().
type_name()
std::string casadi::OptiSol::type_name () const inline
Definition at line 608 of file optistack.hpp.
 {return "OptiSol";}
value() [1/3]
DM casadi::OptiSol::value (const DM & x, const std::vector< MX > & values = std::vector<MX>()) const
Obtain value of expression at the current value
In regular mode, teh current value is the converged solution In debug mode, the value can be non-converged
Parameters
[in] values Optional assignment expressions (e.g. x==3) to overrule the current value
Definition at line 757 of file optistack.cpp.
{
   return optistack_.value(x, values);
 }
References optistack_, and casadi::Opti::value().
value() [2/3]
DM casadi::OptiSol::value (const MX & x, const std::vector< MX > & values = std::vector<MX>()) const
Obtain value of expression at the current value
In regular mode, teh current value is the converged solution In debug mode, the value can be non-converged
Parameters
[in] values Optional assignment expressions (e.g. x==3) to overrule the current value
Definition at line 754 of file optistack.cpp.
{
   return optistack_.value(x, values);
 }
References optistack_, and casadi::Opti::value().
value() [3/3]
DM casadi::OptiSol::value (const SX & x, const std::vector< MX > & values = std::vector<MX>()) const
Obtain value of expression at the current value
In regular mode, teh current value is the converged solution In debug mode, the value can be non-converged
Parameters
[in] values Optional assignment expressions (e.g. x==3) to overrule the current value
Definition at line 760 of file optistack.cpp.
{
   return optistack_.value(x, values);
 }
References optistack_, and casadi::Opti::value().
value_parameters()
std::vector< MX > casadi::OptiSol::value_parameters () const
Definition at line 768 of file optistack.cpp.
{
   return optistack_.value_parameters();
 }
References optistack_, and casadi::Opti::value_parameters().
value_variables()
std::vector< MX > casadi::OptiSol::value_variables () const
Definition at line 764 of file optistack.cpp.
{
   return optistack_.value_variables();
 }
References optistack_, and casadi::Opti::value_variables().
Friends And Related Function Documentation
OptiNode
friend class OptiNode friend
Definition at line 606 of file optistack.hpp.
Member Data Documentation
optistack_
OptiAdvanced casadi::OptiSol::optistack_ protected
Definition at line 641 of file optistack.hpp.
Referenced by disp(), get_str(), stats(), value(), value_parameters(), and value_variables().
The documentation for this class was generated from the following files:
optistack.hpp
optistack.cpp