CasADi: casadi::FatropConicMemory Struct Reference
casadi::FatropConicMemory Struct Reference
#include <fatrop_conic_interface.hpp>
Detailed Description
Definition at line 75 of file fatrop_conic_interface.hpp.
Public Member Functions
FatropConicMemory ()
Constructor.
~FatropConicMemory ()
Destructor.
void add_stat (const std::string &s)
Public Attributes
casadi_fatrop_conic_data< double > d
casadi_qp_data< double > d_qp
bool stats_available
std::map< std::string, FStats > fstats
FStats * t_total
Constructor & Destructor Documentation
FatropConicMemory()
casadi::FatropConicMemory::FatropConicMemory ()
Definition at line 377 of file fatrop_conic_interface.cpp.
{
   }
~FatropConicMemory()
casadi::FatropConicMemory::~FatropConicMemory ()
Definition at line 380 of file fatrop_conic_interface.cpp.
{
   }
Member Function Documentation
add_stat()
void casadi::ProtoFunctionMemory::add_stat (const std::string & s) inline inherited
Definition at line 74 of file function_internal.hpp.
{
       bool added = fstats.insert(std::make_pair(s, FStats())).second;
       casadi_assert(added, "Duplicate stat: '" + s + "'");
     }
Referenced by casadi::ProtoFunction::init_mem(), casadi::LinsolInternal::init_mem(), casadi::Nlpsol::init_mem(), casadi::OracleFunction::init_mem(), casadi::CbcInterface::init_mem(), casadi::ClpInterface::init_mem(), casadi::FatropConicInterface::init_mem(), casadi::HpipmInterface::init_mem(), casadi::Feasiblesqpmethod::init_mem(), casadi::Sqpmethod::init_mem(), and casadi::OracleFunction::local_init_mem().
Member Data Documentation
d
casadi_fatrop_conic_data<double> casadi::FatropConicMemory::d
Definition at line 77 of file fatrop_conic_interface.hpp.
Referenced by casadi::FatropConicInterface::get_stats().
d_qp
casadi_qp_data<double> casadi::ConicMemory::d_qp inherited
Definition at line 39 of file conic_impl.hpp.
Referenced by casadi::Conic::get_stats().
fstats
std::map<std::string, FStats> casadi::ProtoFunctionMemory::fstats inherited
Definition at line 68 of file function_internal.hpp.
Referenced by casadi::Nlpsol::callback(), casadi::IpoptUserClass::eval_h(), casadi::BonminInterface::intermediate_callback(), casadi::IpoptInterface::intermediate_callback(), casadi::OracleFunction::join_results(), casadi::ClarabelInterface::solve(), casadi::DaqpInterface::solve(), casadi::HighsInterface::solve(), casadi::HpipmInterface::solve(), casadi::HpmpcInterface::solve(), casadi::ProxqpInterface::solve(), casadi::QpoasesInterface::solve(), casadi::Sqpmethod::solve_ela_QP(), casadi::Feasiblesqpmethod::solve_LP(), casadi::Feasiblesqpmethod::solve_QP(), and casadi::Sqpmethod::solve_QP().
stats_available
bool casadi::FunctionMemory::stats_available inherited
Definition at line 84 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::eval_gen(), and casadi::FunctionInternal::setup().
t_total
FStats* casadi::ProtoFunctionMemory::t_total inherited
Definition at line 71 of file function_internal.hpp.
Referenced by casadi::LinsolCall< Tr >::eval(), and casadi::Linsol::solve().
The documentation for this struct was generated from the following files:
fatrop_conic_interface.hpp
fatrop_conic_interface.cpp