CasADi: casadi::ZipResource Class Reference
casadi::ZipResource Class Reference
RAII class for reading from a zip file.
#include <resource_internal.hpp>
Detailed Description
Extra doc: https://github.com/casadi/casadi/wiki/L_2c5
Definition at line 97 of file resource_internal.hpp.
Public Types
using weak_ref_type = WeakRefInternal
Public Member Functions
ZipResource (const std::string &path)
Initialize with a path.
~ZipResource () override
const std::string & path () const override
Get path for a consumer.
void unpack ()
std::string class_name () const override
Get type name.
void disp (std::ostream &stream, bool more) const override
Print description.
void serialize_type (SerializingStream &s) const override
Potentially decay into ZipMemResource.
void serialize_body (SerializingStream &s) const override
void serialize (SerializingStream &s) const
void change_option (const std::string &option_name, const GenericType &option_value)
casadi_int getCount () const
Get the reference count.
std::string debug_repr (const SharedObjectInternal *) const
GenericWeakRef< SharedObject, SharedObjectInternal > * weak ()
Get a weak reference to the object.
Static Public Member Functions
static ResourceInternal * deserialize (DeserializingStream &s)
Protected Member Functions
ZipResource (DeserializingStream &s)
void initSingleton ()
void destroySingleton ()
B shared_from_this ()
Get a shared object from the current internal object.
const B shared_from_this () const
Get a shared object from the current internal object.
Protected Attributes
std::string serialize_mode_
Member Typedef Documentation
weak_ref_type
using casadi::SharedObjectInternal::weak_ref_type = WeakRefInternal inherited
Definition at line 152 of file shared_object.hpp.
Constructor & Destructor Documentation
ZipResource() [1/2]
casadi::ZipResource::ZipResource (const std::string & path)
If the path is a directory or empty, the path is passed through to the consumer. Otherwise, the zip file is extracted to a temporary directory.
Upon destruction, the temporary directory is removed.
Extra doc: https://github.com/casadi/casadi/wiki/L_2c6
Definition at line 99 of file resource_internal.cpp.
     : ResourceInternal() {
   path_ = path;
   unpack();
 }
References path(), and unpack().
Referenced by deserialize().
~ZipResource()
casadi::ZipResource::~ZipResource () override
Definition at line 119 of file resource_internal.cpp.
{
   try {
       Filesystem::remove_all(dir_);
   } catch (...) {
       casadi_warning("Error: Cannot remove temporary directory: " + dir_);
   }
   try {
       Filesystem::remove(lock_file_);
   } catch (...) {
       casadi_warning("Error: Cannot remove lock file: " + lock_file_);
   }
 }
References casadi::Filesystem::remove(), and casadi::Filesystem::remove_all().
ZipResource() [2/2]
casadi::ZipResource::ZipResource (DeserializingStream & s) explicit protected
Definition at line 194 of file resource_internal.cpp.
                                                : ResourceInternal(s) {
   s.version("ZipResource", 1);
   s.unpack("ZipResource::path", path_);
   unpack();
 }
References unpack(), casadi::DeserializingStream::unpack(), and casadi::DeserializingStream::version().
Member Function Documentation
change_option()
void casadi::ResourceInternal::change_option (const std::string & option_name, const GenericType & option_value) inherited
Definition at line 53 of file resource_internal.cpp.
{
   if (option_name=="serialize_mode") {
     serialize_mode_ = option_value.to_string();
     casadi_assert(serialize_mode_=="embed" || serialize_mode_=="link",
       "Invalid serialization mode: " + serialize_mode_ + ". Pick 'link' or 'embed'.");
   } else {
     casadi_error("Option '" + option_name + "' does not exist");
   }
 }
References casadi::ResourceInternal::serialize_mode_, and casadi::GenericType::to_string().
class_name()
std::string casadi::ZipResource::class_name () const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_2cw
Implements casadi::SharedObjectInternal.
Definition at line 117 of file resource_internal.hpp.
 {return "ZipResource";}
Referenced by serialize_type().
debug_repr()
std::string casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::debug_repr (const Internal * i) const inherited
Definition at line 62 of file generic_shared_internal.hpp.
{
     // Note: i != this because of something something multiple inheritance
     return str( (casadi_int)(i)) + "/" + static_cast<const Internal*>(this)->class_name();
   }
deserialize()
ResourceInternal * casadi::ZipResource::deserialize (DeserializingStream & s) static
Definition at line 179 of file resource_internal.cpp.
{
   ZipResource* ret = new ZipResource(s);
   return ret;
 }
References ZipResource().
Referenced by casadi::ResourceInternal::deserialize().
destroySingleton()
void casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::destroySingleton () inline protected inherited
Called in the destructor of singletons
Definition at line 77 of file generic_shared_internal.hpp.
{
       static_cast<Internal*>(this)->count--;
     }
disp()
void casadi::ZipResource::disp (std::ostream & stream, bool more) const override virtual
Implements casadi::SharedObjectInternal.
Definition at line 111 of file resource_internal.cpp.
{
   stream << "ZipResource(\"" << path_ << "\") -> \"" << dir_ << "\"";
 }
getCount()
casadi_int casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::getCount inherited
Definition at line 60 of file generic_shared_internal.hpp.
{
     return static_cast<const Internal*>(this)->count;
   }
initSingleton()
void casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::initSingleton () inline protected inherited
Called in the constructor of singletons to avoid that the counter reaches zero
Definition at line 71 of file generic_shared_internal.hpp.
{
       casadi_assert_dev(static_cast<Internal*>(this)->count==0);
       static_cast<Internal*>(this)->count++;
     }
path()
const std::string& casadi::ZipResource::path () const inline override virtual
Implements casadi::ResourceInternal.
Definition at line 110 of file resource_internal.hpp.
 {return dir_;}
Referenced by ZipResource().
serialize()
void casadi::ResourceInternal::serialize (SerializingStream & s) const inherited
Definition at line 145 of file resource_internal.cpp.
{
   s.version("ResourceInternal", 1);
   serialize_type(s);
   serialize_body(s);
 }
References casadi::ResourceInternal::serialize_body(), casadi::ResourceInternal::serialize_type(), and casadi::SerializingStream::version().
serialize_body()
void casadi::ZipResource::serialize_body (SerializingStream & s) const override virtual
Reimplemented from casadi::ResourceInternal.
Definition at line 241 of file resource_internal.cpp.
{
   ResourceInternal::serialize_body(s);
   s.version("ZipResource", 1);
   if (serialize_mode_=="embed") {
     // Decay into ZipMemResource
     std::ifstream binary(path_, std::ios_base::binary);
     casadi_assert(binary.good(),
       "Could not open zip file '" + path_ + "'.");
     s.pack("ZipMemResource::blob", binary);
   } else {
     s.pack("ZipResource::path", path_);
   }
 }
References casadi::SerializingStream::pack(), casadi::ResourceInternal::serialize_body(), casadi::ResourceInternal::serialize_mode_, and casadi::SerializingStream::version().
serialize_type()
void casadi::ZipResource::serialize_type (SerializingStream & s) const override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_2cx
Reimplemented from casadi::ResourceInternal.
Definition at line 214 of file resource_internal.cpp.
{
   if (serialize_mode_=="embed") {
     // Decay into ZipMemResource
     std::string class_name = "ZipMemResource";
     s.pack("ResourceInternal::type", class_name);
   } else if (serialize_mode_=="link") {
     std::string class_name = "ZipResource";
     s.pack("ResourceInternal::type", class_name);
   } else {
     casadi_error("Unknown serialization mode: '" + serialize_mode_+ "'.");
   }
 }
References class_name(), casadi::SerializingStream::pack(), and casadi::ResourceInternal::serialize_mode_.
shared_from_this() [1/2]
B casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::shared_from_this () inline protected inherited
Definition at line 83 of file generic_shared_internal.hpp.
{
       casadi_assert_dev(B::test_cast(static_cast<Internal*>(this)));
       B ret;
       ret.own(static_cast<Internal*>(this));
       return ret;
     }
shared_from_this() [2/2]
const B casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::shared_from_this () const inline protected inherited
Definition at line 92 of file generic_shared_internal.hpp.
{
       casadi_assert_dev(B::test_cast(static_cast<const Internal*>(this)));
       B ret;
       ret.own(const_cast<Internal*>(static_cast<const Internal*>(this)));
       return ret;
     }
unpack()
void casadi::ZipResource::unpack ()
Definition at line 64 of file resource_internal.cpp.
{
   casadi_assert(Filesystem::is_enabled(),
   "Unzipping '" + path_ + "' requires advanced filesystem access. Compile CasADi with WITH_GC=ON.\n"
   "Alternatively, manually unzip it into a direcory, "
   "and pass this directory name instead of the zip file name.");
   // Extract filename part of path
   std::string zip_file = Filesystem::filename(path_);
   lock_file_ = temporary_file(zip_file + ".", ".lock");
   dir_ = lock_file_.substr(0, lock_file_.size()-5) + ".unzipped";
   casadi_assert(Archiver::has_plugin("libzip"),
   "Unzipping '" + path_ + "' requires libzip. Compile CasADi with WITH_LIBZIP=ON.\n"
   "Alternatively, manually unzip it into a direcory, "
   "and pass this directory name instead of the zip file name.");
   Archiver::getPlugin("libzip").exposed.unpack(path_, dir_);
 }
References casadi::Filesystem::filename(), casadi::PluginInterface< Archiver >::getPlugin(), casadi::PluginInterface< Archiver >::has_plugin(), casadi::Filesystem::is_enabled(), and casadi::temporary_file().
Referenced by ZipResource().
weak()
GenericWeakRef< SharedObject , SharedObjectInternal > * casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::weak inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1ai
Definition at line 67 of file generic_shared_internal.hpp.
{
     if (weak_ref_==nullptr) {
       weak_ref_ = new GenericWeakRef<Shared, Internal>(static_cast<Internal*>(this));
     }
     return weak_ref_;
   }
Member Data Documentation
serialize_mode_
std::string casadi::ResourceInternal::serialize_mode_ protected inherited
Definition at line 63 of file resource_internal.hpp.
Referenced by casadi::ResourceInternal::change_option(), casadi::ResourceInternal::ResourceInternal(), casadi::ResourceInternal::serialize_body(), casadi::DirResource::serialize_body(), serialize_body(), casadi::DirResource::serialize_type(), and serialize_type().
The documentation for this class was generated from the following files:
resource_internal.hpp
resource_internal.cpp