CasADi: Title
Title
Enumerations
enum casadi::SimulatorInput {
casadi::SIMULATOR_X0 , casadi::SIMULATOR_U , casadi::SIMULATOR_Z0 , casadi::SIMULATOR_P ,
casadi::SIMULATOR_NUM_IN
}
Input arguments of an simulator.
enum casadi::SimulatorOutput { casadi::SIMULATOR_X , casadi::SIMULATOR_Z , casadi::SIMULATOR_NUM_OUT }
Output arguments of an simulator.
Functions
Function casadi::simulator (const std::string &name, const std::string &solver, const SXDict &dae, const std::vector< double > &grid, const Dict &opts)
Function casadi::simulator (const std::string &name, const std::string &solver, const MXDict &dae, const std::vector< double > &grid, const Dict &opts)
Function casadi::simulator (const std::string &name, const std::string &solver, const Function &dae, const std::vector< double > &grid, const Dict &opts)
bool casadi::has_simulator (const std::string &name)
Check if a particular plugin is available.
void casadi::load_simulator (const std::string &name)
Explicitly load a plugin dynamically.
std::string casadi::doc_simulator (const std::string &name)
Get the documentation string for a plugin.
std::vector< std::string > casadi::simulator_in ()
Get input scheme of simulators.
std::vector< std::string > casadi::simulator_out ()
Get simulator output scheme of simulators.
std::string casadi::simulator_in (casadi_int ind)
Get simulator input scheme name by index.
std::string casadi::simulator_out (casadi_int ind)
Get output scheme name by index.
casadi_int casadi::simulator_n_in ()
Get the number of simulator inputs.
casadi_int casadi::simulator_n_out ()
Get the number of simulator outputs.
Detailed Description
Create an ODE/DAE simulator Solves an initial value problem (IVP) with the differential equation given as an implicit ODE coupled to an algebraic equation and a set of output equations:
Time grid: [t0, t1, ..., tN]
Initial conditions for forward integration
x(t0)  = x0
Sequential forward integration from t=tk to t=t{k+1}
der(x) = fx(t, x, z, p, uk)         ODE
0 = fz(t, x, z, p, uk)              Algebraic equations
yk = fy(t, x, z, p, uk)             Output equations
where we assume that the problem is index-1 (i.e. dfz/dz, is invertible) and furthermore that
General information
List of available options
Id Type Description Used in
ad_weight OT_DOUBLE Weighting factor for derivative calculation.When there is an option of either using forward or reverse mode directional derivatives, the condition ad_weight*nf<=(1-ad_weight)*na is used where nf and na are estimates of the number of forward/reverse mode directional derivatives needed. By default, ad_weight is calculated automatically, but this can be overridden by setting this option. In particular, 0 means forcing forward mode and 1 forcing reverse mode. Leave unset for (class specific) heuristics. casadi::FunctionInternal
ad_weight_sp OT_DOUBLE Weighting factor for sparsity pattern calculation calculation.Overrides default behavior. Set to 0 and 1 to force forward and reverse mode respectively. Cf. option "ad_weight". When set to -1, sparsity is completely ignored and dense matrices are used. casadi::FunctionInternal
always_inline OT_BOOL Force inlining. casadi::FunctionInternal
common_options OT_DICT Options for auto-generated functions casadi::OracleFunction
compiler OT_STRING Just-in-time compiler plugin to be used. casadi::FunctionInternal
custom_jacobian OT_FUNCTION Override CasADi's AD. Use together with 'jac_penalty': 0. Note: Highly experimental. Syntax may break often. casadi::FunctionInternal
der_options OT_DICT Default options to be used to populate forward_options, reverse_options, and jacobian_options before those options are merged in. casadi::FunctionInternal
derivative_of OT_FUNCTION The function is a derivative of another function. The type of derivative (directional derivative, Jacobian) is inferred from the function name. casadi::FunctionInternal
dump OT_BOOL Dump function to file upon first evaluation. [false] casadi::FunctionInternal
dump_dir OT_STRING Directory to dump inputs/outputs to. Make sure the directory exists [.] casadi::FunctionInternal
dump_format OT_STRING Choose file format to dump matrices. See DM.from_file [mtx] casadi::FunctionInternal
dump_in OT_BOOL Dump numerical values of inputs to file (readable with DM.from_file) [default: false] casadi::FunctionInternal
dump_out OT_BOOL Dump numerical values of outputs to file (readable with DM.from_file) [default: false] casadi::FunctionInternal
enable_fd OT_BOOL Enable derivative calculation by finite differencing. [default: false]] casadi::FunctionInternal
enable_forward OT_BOOL Enable derivative calculation using generated functions for Jacobian-times-vector products - typically using forward mode AD - if available. [default: true] casadi::FunctionInternal
enable_jacobian OT_BOOL Enable derivative calculation using generated functions for Jacobians of all differentiable outputs with respect to all differentiable inputs - if available. [default: true] casadi::FunctionInternal
enable_reverse OT_BOOL Enable derivative calculation using generated functions for transposed Jacobian-times-vector products - typically using reverse mode AD - if available. [default: true] casadi::FunctionInternal
error_on_fail OT_BOOL Throw exceptions when function evaluation fails (default true). casadi::ProtoFunction
expand OT_BOOL Replace MX with SX expressions in problem formulation [false] casadi::OracleFunction
fd_method OT_STRING Method for finite differencing [default 'central'] casadi::FunctionInternal
fd_options OT_DICT Options to be passed to the finite difference instance casadi::FunctionInternal
forward_options OT_DICT Options to be passed to a forward mode constructor casadi::FunctionInternal
gather_stats OT_BOOL Deprecated option (ignored): Statistics are now always collected. casadi::FunctionInternal
input_scheme OT_STRINGVECTOR Deprecated option (ignored) casadi::FunctionInternal
inputs_check OT_BOOL Throw exceptions when the numerical values of the inputs don't make sense casadi::FunctionInternal
is_diff_in OT_BOOLVECTOR Indicate for each input if it should be differentiable. casadi::FunctionInternal
is_diff_out OT_BOOLVECTOR Indicate for each output if it should be differentiable. casadi::FunctionInternal
jac_penalty OT_DOUBLE When requested for a number of forward/reverse directions, it may be cheaper to compute first the full jacobian and then multiply with seeds, rather than obtain the requested directions in a straightforward manner. Casadi uses a heuristic to decide which is cheaper. A high value of 'jac_penalty' makes it less likely for the heurstic to chose the full Jacobian strategy. The special value -1 indicates never to use the full Jacobian strategy casadi::FunctionInternal
jacobian_options OT_DICT Options to be passed to a Jacobian constructor casadi::FunctionInternal
jit OT_BOOL Use just-in-time compiler to speed up the evaluation casadi::FunctionInternal
jit_cleanup OT_BOOL Cleanup up the temporary source file that jit creates. Default: true casadi::FunctionInternal
jit_name OT_STRING The file name used to write out code. The actual file names used depend on 'jit_temp_suffix' and include extensions. Default: 'jit_tmp' casadi::FunctionInternal
jit_options OT_DICT Options to be passed to the jit compiler. casadi::FunctionInternal
jit_serialize OT_STRING Specify behaviour when serializing a jitted function: SOURCE|link|embed. casadi::FunctionInternal
jit_temp_suffix OT_BOOL Use a temporary (seemingly random) filename suffix for generated code and libraries. This is desired for thread-safety. This behaviour may defeat caching compiler wrappers. Default: true casadi::FunctionInternal
max_io OT_INT Acceptable number of inputs and outputs. Warn if exceeded. casadi::FunctionInternal
max_num_dir OT_INT Specify the maximum number of directions for derivative functions. Overrules the builtin optimized_num_dir. casadi::FunctionInternal
monitor OT_STRINGVECTOR Set of user problem functions to be monitored casadi::OracleFunction
never_inline OT_BOOL Forbid inlining. casadi::FunctionInternal
nfwd OT_INT Number of forward sensitivities casadi::Simulator
nondiff OT_BOOL Output nondifferentiated casadi::Simulator
output_scheme OT_STRINGVECTOR Deprecated option (ignored) casadi::FunctionInternal
post_expand OT_BOOL After construction, expand this Function. Default: False casadi::FunctionInternal
post_expand_options OT_DICT Options to be passed to post-construction expansion. Default: empty casadi::FunctionInternal
print_in OT_BOOL Print numerical values of inputs [default: false] casadi::FunctionInternal
print_out OT_BOOL Print numerical values of outputs [default: false] casadi::FunctionInternal
print_stats OT_BOOL Print out statistics after integration casadi::Simulator
print_time OT_BOOL print information about execution time. Implies record_time. casadi::ProtoFunction
record_time OT_BOOL record information about execution time, for retrieval with stats(). casadi::ProtoFunction
regularity_check OT_BOOL Throw exceptions when NaN or Inf appears during evaluation casadi::ProtoFunction
reverse_options OT_DICT Options to be passed to a reverse mode constructor casadi::FunctionInternal
show_eval_warnings OT_BOOL Show warnings generated from function evaluations [true] casadi::OracleFunction
specific_options OT_DICT Options for specific auto-generated functions, overwriting the defaults from common_options. Nested dictionary. casadi::OracleFunction
user_data OT_VOIDPTR A user-defined field that can be used to identify the function or pass additional information casadi::FunctionInternal
verbose OT_BOOL Verbose evaluation – for debugging casadi::ProtoFunction
Input scheme: casadi::SimulatorInput (SIMULATOR_NUM_IN = 4)
Full name Short Description
SIMULATOR_X0 x0 Differential state at the initial time.
SIMULATOR_U u Controls.
SIMULATOR_Z0 z0 Initial guess for the algebraic variable at the initial time.
SIMULATOR_P p Parameters.
Output scheme: casadi::SimulatorOutput (SIMULATOR_NUM_OUT = 2)
Full name Short Description
SIMULATOR_X x Differential state.
SIMULATOR_Z z Algebraic variable.
List of plugins
- cvodes
Note: some of the plugins in this list might not be available on your system. Also, there might be extra plugins available to you that are not listed here. You can obtain their documentation with Simulator.doc("myextraplugin")
cvodes
Interface to CVodes from the Sundials suite.
Extra doc: https://github.com/casadi/casadi/wiki/L_227
List of available options
Id Type Description
abstol OT_DOUBLE Absolute tolerence for the IVP solution
disable_internal_warnings OT_BOOL Disable SUNDIALS internal warning messages
fsens_err_con OT_BOOL include the forward sensitivities in all error controls
interpolation_type OT_STRING Type of interpolation for the adjoint sensitivities
linear_multistep_method OT_STRING Simulator scheme: BDF|adams
linear_solver OT_STRING A custom linear solver creator function [default: qr]
linear_solver_options OT_DICT Options to be passed to the linear solver
max_krylov OT_INT Maximum Krylov subspace size
max_multistep_order OT_INT Maximum order for the (variable-order) multistep method
max_num_steps OT_INT Maximum number of simulator steps
max_order OT_DOUBLE Maximum order
max_step_size OT_DOUBLE Max step size [default: 0/inf]
min_step_size OT_DOUBLE Min step size [default: 0/0.0]
newton_scheme OT_STRING Linear solver scheme in the Newton method: DIRECT|gmres|bcgstab|tfqmr
nonlin_conv_coeff OT_DOUBLE Coefficient in the nonlinear convergence test
nonlinear_solver_iteration OT_STRING Nonlinear solver type: NEWTON|functional
quad_err_con OT_BOOL Should the quadratures affect the step size control
reltol OT_DOUBLE Relative tolerence for the IVP solution
scale_abstol OT_BOOL Scale absolute tolerance by nominal value
sensitivity_method OT_STRING Sensitivity method: SIMULTANEOUS|staggered
step0 OT_DOUBLE initial step size [default: 0/estimated]
steps_per_checkpoint OT_INT Number of steps between two consecutive checkpoints
stop_at_end OT_BOOL Stop the simulator at the end of the interval
use_preconditioner OT_BOOL Precondition the iterative solver [default: true]
Author
Joel Andersson
Date
2011-2021
Extra doc: https://github.com/casadi/casadi/wiki/L_21m
Enumeration Type Documentation
SimulatorInput
enum casadi::SimulatorInput
Enumerator
SIMULATOR_X0
Differential state at the initial time.
SIMULATOR_U
Controls.
SIMULATOR_Z0
Initial guess for the algebraic variable at the initial time.
SIMULATOR_P
Parameters.
SIMULATOR_NUM_IN
Number of input arguments of an simulator.
Definition at line 93 of file casadi/core/simulator.hpp.
                       {
     SIMULATOR_X0,
     SIMULATOR_U,
     SIMULATOR_Z0,
     SIMULATOR_P,
     SIMULATOR_NUM_IN
   };
SimulatorOutput
enum casadi::SimulatorOutput
Enumerator
SIMULATOR_X
Differential state.
SIMULATOR_Z
Algebraic variable.
SIMULATOR_NUM_OUT
Number of output arguments of an simulator.
Definition at line 107 of file casadi/core/simulator.hpp.
{
     SIMULATOR_X,
     SIMULATOR_Z,
     SIMULATOR_NUM_OUT
   };
Function Documentation
doc_simulator()
CASADI_EXPORT std::string casadi::doc_simulator (const std::string & name)
Definition at line 39 of file simulator.cpp.
{
   return Simulator::getPlugin(name).doc;
 }
References casadi::PluginInterface< Simulator >::getPlugin().
has_simulator()
CASADI_EXPORT bool casadi::has_simulator (const std::string & name)
Definition at line 31 of file simulator.cpp.
{
   return Simulator::has_plugin(name);
 }
References casadi::PluginInterface< Simulator >::has_plugin().
load_simulator()
CASADI_EXPORT void casadi::load_simulator (const std::string & name)
Definition at line 35 of file simulator.cpp.
{
   Simulator::load_plugin(name);
 }
References casadi::PluginInterface< Simulator >::load_plugin().
simulator() [1/3]
CASADI_EXPORT Function casadi::simulator (const std::string & name, const std::string & solver, const Function & dae, const std::vector< double > & grid, const Dict & opts)
Definition at line 43 of file simulator.cpp.
{
   // Make sure that dae is sound
   if (dae.has_free()) {
     casadi_error("Cannot create '" + name + "' since " + str(dae.get_free()) + " are free.");
   }
   Simulator* intg = Simulator::getPlugin(solver).creator(name, dae, grid);
   return intg->create_advanced(opts);
 }
References casadi::Simulator::create_advanced(), casadi::Function::get_free(), casadi::PluginInterface< Simulator >::getPlugin(), casadi::Function::has_free(), and casadi::str().
Referenced by casadi::simulator().
simulator() [2/3]
CASADI_EXPORT Function casadi::simulator (const std::string & name, const std::string & solver, const MXDict & dae, const std::vector< double > & grid, const Dict & opts)
Definition at line 58 of file simulator.cpp.
{
   return simulator(name, solver, Simulator::map2oracle("dae", dae), grid, opts);
 }
References casadi::Simulator::map2oracle(), and casadi::simulator().
simulator() [3/3]
CASADI_EXPORT Function casadi::simulator (const std::string & name, const std::string & solver, const SXDict & dae, const std::vector< double > & grid, const Dict & opts = Dict())
Definition at line 53 of file simulator.cpp.
{
   return simulator(name, solver, Simulator::map2oracle("dae", dae), grid, opts);
 }
References casadi::Simulator::map2oracle(), and casadi::simulator().
simulator_in() [1/2]
CASADI_EXPORT std::vector< std::string > casadi::simulator_in ()
Extra doc: https://github.com/casadi/casadi/wiki/L_wx
Definition at line 63 of file simulator.cpp.
{
   std::vector<std::string> ret(simulator_n_in());
   for (size_t i=0; i<ret.size(); ++i) ret[i]=simulator_in(i);
   return ret;
 }
References casadi::simulator_n_in().
Referenced by casadi::Simulator::get_name_in().
simulator_in() [2/2]
CASADI_EXPORT std::string casadi::simulator_in (casadi_int ind)
Extra doc: https://github.com/casadi/casadi/wiki/L_x5
Definition at line 75 of file simulator.cpp.
{
   switch (static_cast<SimulatorInput>(ind)) {
   case SIMULATOR_X0:  return "x0";
   case SIMULATOR_U:   return "u";
   case SIMULATOR_Z0:  return "z0";
   case SIMULATOR_P:   return "p";
   case SIMULATOR_NUM_IN: break;
   }
   return std::string();
 }
References casadi::SIMULATOR_NUM_IN, casadi::SIMULATOR_P, casadi::SIMULATOR_U, casadi::SIMULATOR_X0, and casadi::SIMULATOR_Z0.
simulator_n_in()
casadi_int casadi::simulator_n_in () inline
Extra doc: https://github.com/casadi/casadi/wiki/L_x7
Definition at line 140 of file casadi/core/simulator.hpp.
 { return SIMULATOR_NUM_IN;}
References casadi::SIMULATOR_NUM_IN.
Referenced by casadi::simulator_in().
simulator_n_out()
casadi_int casadi::simulator_n_out () inline
Extra doc: https://github.com/casadi/casadi/wiki/L_x8
Definition at line 145 of file casadi/core/simulator.hpp.
 { return SIMULATOR_NUM_OUT;}
References casadi::SIMULATOR_NUM_OUT.
Referenced by casadi::simulator_out().
simulator_out() [1/2]
CASADI_EXPORT std::vector< std::string > casadi::simulator_out ()
Extra doc: https://github.com/casadi/casadi/wiki/L_wy
Definition at line 69 of file simulator.cpp.
{
   std::vector<std::string> ret(simulator_n_out());
   for (size_t i=0; i<ret.size(); ++i) ret[i]=simulator_out(i);
   return ret;
 }
References casadi::simulator_n_out().
Referenced by casadi::Simulator::get_name_in(), and casadi::Simulator::get_name_out().
simulator_out() [2/2]
CASADI_EXPORT std::string casadi::simulator_out (casadi_int ind)
Extra doc: https://github.com/casadi/casadi/wiki/L_x6
Definition at line 86 of file simulator.cpp.
{
   switch (static_cast<SimulatorOutput>(ind)) {
   case SIMULATOR_X:  return "x";
   case SIMULATOR_Z:  return "z";
   case SIMULATOR_NUM_OUT: break;
   }
   return std::string();
 }
References casadi::SIMULATOR_NUM_OUT, casadi::SIMULATOR_X, and casadi::SIMULATOR_Z.