CasADi: casadi::ProtoFunction Class Reference
casadi::ProtoFunction Class Reference abstract
Base class for FunctionInternal and LinsolInternal.
#include <function_internal.hpp>
Detailed Description
Author
Joel Andersson
Date
2017
Extra doc: https://github.com/casadi/casadi/wiki/L_jc
List of available options
Id Type Description Used in
error_on_fail OT_BOOL Throw exceptions when function evaluation fails (default true). casadi::ProtoFunction
print_time OT_BOOL print information about execution time. Implies record_time. casadi::ProtoFunction
record_time OT_BOOL record information about execution time, for retrieval with stats(). casadi::ProtoFunction
regularity_check OT_BOOL Throw exceptions when NaN or Inf appears during evaluation casadi::ProtoFunction
verbose OT_BOOL Verbose evaluation – for debugging casadi::ProtoFunction
Definition at line 92 of file function_internal.hpp.
Public Member Functions
ProtoFunction (const std::string &name)
Constructor.
~ProtoFunction () override=0
Destructor.
void construct (const Dict &opts)
Construct.
virtual Dict generate_options (const std::string &target) const
Reconstruct options dict.
void print_options (std::ostream &stream) const
Print list of options.
void print_option (const std::string &name, std::ostream &stream) const
Print all information there is to know about a certain option.
bool has_option (const std::string &option_name) const
Does a particular option exist.
virtual void change_option (const std::string &option_name, const GenericType &option_value)
Change option after object creation for debugging.
virtual void init (const Dict &opts)
Initialize.
virtual void finalize ()
Finalize the object creation.
int checkout () const
Checkout a memory object.
void release (int mem) const
Release a memory object.
void * memory (int ind) const
Memory objects.
virtual void * alloc_mem () const
Create memory block.
virtual int init_mem (void *mem) const
Initalize memory block.
virtual void free_mem (void *mem) const
Free memory block.
virtual Dict get_stats (void *mem) const
Get all statistics.
void clear_mem ()
Clear all memory (called from destructor)
void print (const char *fmt,...) const
C-style formatted printing during evaluation.
void sprint (char *buf, size_t buf_sz, const char *fmt,...) const
C-style formatted printing to string.
void format_time (char *buffer, double time) const
Format time in a fixed width 8 format.
void print_time (const std::map< std::string, FStats > &fstats) const
Print timing statistics.
void serialize (SerializingStream &s) const
Serialize an object.
virtual void serialize_body (SerializingStream &s) const
Serialize an object without type information.
virtual void serialize_type (SerializingStream &s) const
Serialize type information.
virtual std::string serialize_base_function () const
String used to identify the immediate FunctionInternal subclass.
casadi_int getCount () const
Get the reference count.
virtual std::string class_name () const =0
Readable name of the internal class.
virtual void disp (std::ostream &stream, bool more) const =0
Print a description of the object.
WeakRef * weak ()
Get a weak reference to the object.
Public Attributes
std::string name_
Name.
bool verbose_
Verbose printout.
bool print_time_
bool record_time_
bool regularity_check_
Errors are thrown when NaN is produced.
bool error_on_fail_
Throw an exception on failure?
Protected Member Functions
ProtoFunction (DeserializingStream &s)
Deserializing constructor.
void initSingleton ()
void destroySingleton ()
template<class B >
B shared_from_this ()
Get a shared object from the current internal object.
template<class B >
const B shared_from_this () const
Get a shared object from the current internal object.
static const Options options_
Options.
virtual const Options & get_options () const
Options.
Constructor & Destructor Documentation
ProtoFunction() [1/2]
casadi::ProtoFunction::ProtoFunction (const std::string & name)
Extra doc: https://github.com/casadi/casadi/wiki/L_jd
Definition at line 55 of file function_internal.cpp.
                                                     : name_(name) {
     // Default options (can be overridden in derived classes)
     verbose_ = false;
     print_time_ = false;
     record_time_ = false;
     regularity_check_ = false;
     error_on_fail_ = true;
   }
References error_on_fail_, print_time_, record_time_, regularity_check_, and verbose_.
~ProtoFunction()
casadi::ProtoFunction::~ProtoFunction () override pure virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_je
Definition at line 116 of file function_internal.cpp.
{
     for (void* m : mem_) {
       if (m!=nullptr) casadi_warning("Memory object has not been properly freed");
     }
     mem_.clear();
   }
ProtoFunction() [2/2]
casadi::ProtoFunction::ProtoFunction (DeserializingStream & s) explicit protected
Extra doc: https://github.com/casadi/casadi/wiki/L_jz
Definition at line 3794 of file function_internal.cpp.
{
     int version = s.version("ProtoFunction", 1, 2);
     s.unpack("ProtoFunction::name", name_);
     s.unpack("ProtoFunction::verbose", verbose_);
     s.unpack("ProtoFunction::print_time", print_time_);
     s.unpack("ProtoFunction::record_time", record_time_);
     if (version >= 2) s.unpack("ProtoFunction::regularity_check", regularity_check_);
     if (version >= 2) s.unpack("ProtoFunction::error_on_fail", error_on_fail_);
   }
References error_on_fail_, name_, print_time_, record_time_, regularity_check_, casadi::DeserializingStream::unpack(), verbose_, and casadi::DeserializingStream::version().
Member Function Documentation
alloc_mem()
virtual void* casadi::ProtoFunction::alloc_mem () const inline virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_jn
Reimplemented in casadi::SymbolicQr, casadi::Sqpmethod, casadi::Scpgen, casadi::Qrsqp, casadi::Qrqp, casadi::QpToNlp, casadi::Newton, casadi::Lsqr, casadi::LinsolTridiag, casadi::LinsolQr, casadi::LinsolLdl, casadi::Ipqp, casadi::ImplicitToNlp, casadi::Feasiblesqpmethod, casadi::FastNewton, casadi::WorhpInterface, casadi::SuperscsInterface, casadi::KinsolInterface, casadi::IdasInterface, casadi::CvodesInterface, casadi::SnoptInterface, casadi::SlicotExpm, casadi::SlicotDple, casadi::QpoasesInterface, casadi::ProxqpInterface, casadi::OsqpInterface, casadi::OoqpInterface, casadi::MumpsInterface, casadi::LapackQr, casadi::LapackLu, casadi::KnitroInterface, casadi::IpoptInterface, casadi::Ma27Interface, casadi::HpmpcInterface, casadi::HpipmInterface, casadi::HighsInterface, casadi::GurobiInterface, casadi::CsparseInterface, casadi::CSparseCholeskyInterface, casadi::CplexInterface, casadi::ClpInterface, casadi::CbcInterface, casadi::BonminInterface, casadi::Blocksqp, casadi::AmplInterface, casadi::OracleFunction, casadi::Nlpsol, casadi::LinsolInternal, and casadi::FixedStepIntegrator.
Definition at line 172 of file function_internal.hpp.
 { return new ProtoFunctionMemory(); }
Referenced by checkout(), and casadi::FunctionInternal::codegen_checkout().
change_option()
void casadi::ProtoFunction::change_option (const std::string & option_name, const GenericType & option_value) virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_jk
Reimplemented in casadi::MXFunction, and casadi::FunctionInternal.
Definition at line 904 of file function_internal.cpp.
{
     if (option_name == "verbose") {
       verbose_ = option_value;
     } else if (option_name == "regularity_check") {
       regularity_check_ = option_value;
     } else {
       // Failure
       casadi_error("Option '" + option_name + "' cannot be changed");
     }
   }
References regularity_check_, and verbose_.
Referenced by casadi::FunctionInternal::change_option().
checkout()
int casadi::ProtoFunction::checkout () const
Definition at line 3497 of file function_internal.cpp.
{
 #ifdef CASADI_WITH_THREAD
     std::lock_guard<std::mutex> lock(mtx_);
 #endif //CASADI_WITH_THREAD
     if (unused_.empty()) {
       // Allocate a new memory object
       void* m = alloc_mem();
       mem_.push_back(m);
       if (init_mem(m)) {
         casadi_error("Failed to create or initialize memory object");
       }
       return mem_.size()-1;
     } else {
       // Use an unused memory object
       int m = unused_.top();
       unused_.pop();
       return m;
     }
   }
References alloc_mem(), and init_mem().
Referenced by finalize(), and casadi::FunctionBuffer::FunctionBuffer().
class_name()
virtual std::string casadi::SharedObjectInternal::class_name () const pure virtual inherited
Implemented in casadi::SymbolicQr, casadi::Sqpmethod, casadi::ShellCompiler, casadi::Scpgen, casadi::RungeKutta, casadi::Qrsqp, casadi::Qrqp, casadi::QpToNlp, casadi::Newton, casadi::Lsqr, casadi::LinsolTridiag, casadi::LinsolQr, casadi::LinsolLdl, casadi::LinearInterpolantJac, casadi::LinearInterpolant, casadi::Ipqp, casadi::ImplicitToNlp, casadi::Feasiblesqpmethod, casadi::FastNewton, casadi::Collocation, casadi::BSplineInterpolant, casadi::WorhpInterface, casadi::TinyXmlInterface, casadi::SuperscsInterface, casadi::KinsolInterface, casadi::IdasInterface, casadi::CvodesInterface, casadi::SqicInterface, casadi::SnoptInterface, casadi::SlicotExpm, casadi::SlicotDple, casadi::QpoasesInterface, casadi::ProxqpInterface, casadi::OsqpInterface, casadi::OoqpInterface, casadi::MumpsInterface, casadi::LapackQr, casadi::LapackLu, casadi::KnitroInterface, casadi::IpoptInterface, casadi::Ma27Interface, casadi::HpmpcInterface, casadi::HpipmInterface, casadi::HighsInterface, casadi::GurobiInterface, casadi::CsparseInterface, casadi::CSparseCholeskyInterface, casadi::CplexInterface, casadi::ClpInterface, casadi::ClangCompiler, casadi::CbcInterface, casadi::BonminInterface, casadi::Blocksqp, casadi::AmplInterface, casadi::SXFunction, casadi::Switch, casadi::SparsityInternal, casadi::WeakRefInternal, casadi::OptiNode, casadi::Nlpsol, casadi::MXNode, casadi::MXFunction, casadi::MapSum, casadi::ThreadMap, casadi::OmpMap, casadi::Map, casadi::JitFunction, casadi::Interpolant, casadi::DllLibrary, casadi::ImporterInternal, casadi::GenericTypeInternal< ID, T >, casadi::Smoothing, casadi::CentralDiff, casadi::BackwardDiff, casadi::ForwardDiff, casadi::External, casadi::DaeBuilderInternal, and casadi::CallbackInternal.
Referenced by casadi::FunctionInternal::call_forward(), casadi::FunctionInternal::call_reverse(), casadi::FunctionInternal::codegen_body(), construct(), casadi::FunctionInternal::disp(), casadi::LinsolInternal::disp(), casadi::XmlFileInternal::dump(), casadi::FunctionInternal::eval(), casadi::FunctionInternal::eval_dm(), casadi::FunctionInternal::eval_sx(), casadi::FunctionInternal::export_code(), casadi::LinsolInternal::generate(), casadi::FunctionInternal::generate_dependencies(), casadi::Conic::generateNativeCode(), casadi::FunctionInternal::get_forward(), casadi::FunctionInternal::get_function(), casadi::FunctionInternal::get_jacobian(), casadi::FunctionInternal::get_reverse(), casadi::FiniteDiff::init(), casadi::FunctionInternal::instruction_constant(), casadi::FunctionInternal::instruction_id(), casadi::FunctionInternal::instruction_input(), casadi::FunctionInternal::instruction_MX(), casadi::FunctionInternal::instruction_output(), casadi::FunctionInternal::instructions_sx(), casadi::LinsolInternal::linsol_eval_sx(), casadi::FunctionInternal::n_instructions(), casadi::FunctionInternal::n_nodes(), casadi::LinsolInternal::neig(), casadi::LinsolInternal::nfact(), casadi::FunctionInternal::oracle(), casadi::XmlFileInternal::parse(), casadi::LinsolInternal::rank(), casadi::LinsolInternal::solve(), and casadi::FunctionInternal::which_depends().
clear_mem()
void casadi::ProtoFunction::clear_mem ()
Extra doc: https://github.com/casadi/casadi/wiki/L_jq
Definition at line 3389 of file function_internal.cpp.
{
     for (auto&& i : mem_) {
       if (i!=nullptr) free_mem(i);
     }
     mem_.clear();
   }
References free_mem().
Referenced by casadi::AmplInterface::~AmplInterface(), casadi::Blocksqp::~Blocksqp(), casadi::BonminInterface::~BonminInterface(), casadi::BSplineInterpolant::~BSplineInterpolant(), casadi::CallbackInternal::~CallbackInternal(), casadi::CbcInterface::~CbcInterface(), casadi::ClpInterface::~ClpInterface(), casadi::CplexInterface::~CplexInterface(), casadi::CsparseInterface::~CsparseInterface(), casadi::CvodesInterface::~CvodesInterface(), casadi::External::~External(), casadi::FastNewton::~FastNewton(), casadi::Feasiblesqpmethod::~Feasiblesqpmethod(), casadi::FiniteDiff::~FiniteDiff(), casadi::FixedStepIntegrator::~FixedStepIntegrator(), casadi::GurobiInterface::~GurobiInterface(), casadi::HighsInterface::~HighsInterface(), casadi::HpipmInterface::~HpipmInterface(), casadi::HpmpcInterface::~HpmpcInterface(), casadi::IdasInterface::~IdasInterface(), casadi::ImplicitToNlp::~ImplicitToNlp(), casadi::IpoptInterface::~IpoptInterface(), casadi::Ipqp::~Ipqp(), casadi::JitFunction::~JitFunction(), casadi::KinsolInterface::~KinsolInterface(), casadi::KnitroInterface::~KnitroInterface(), casadi::LapackLu::~LapackLu(), casadi::LapackQr::~LapackQr(), casadi::LinearInterpolant::~LinearInterpolant(), casadi::LinearInterpolantJac::~LinearInterpolantJac(), casadi::LinsolLdl::~LinsolLdl(), casadi::LinsolQr::~LinsolQr(), casadi::LinsolTridiag::~LinsolTridiag(), casadi::Lsqr::~Lsqr(), casadi::Ma27Interface::~Ma27Interface(), casadi::Map::~Map(), casadi::MapSum::~MapSum(), casadi::MumpsInterface::~MumpsInterface(), casadi::MXFunction::~MXFunction(), casadi::Newton::~Newton(), casadi::Nlpsol::~Nlpsol(), casadi::OmpMap::~OmpMap(), casadi::OoqpInterface::~OoqpInterface(), casadi::OsqpInterface::~OsqpInterface(), casadi::ProxqpInterface::~ProxqpInterface(), casadi::QpoasesInterface::~QpoasesInterface(), casadi::QpToNlp::~QpToNlp(), casadi::Qrqp::~Qrqp(), casadi::Qrsqp::~Qrsqp(), casadi::Scpgen::~Scpgen(), casadi::SlicotDple::~SlicotDple(), casadi::SlicotExpm::~SlicotExpm(), casadi::SnoptInterface::~SnoptInterface(), casadi::Sqpmethod::~Sqpmethod(), casadi::SuperscsInterface::~SuperscsInterface(), casadi::Switch::~Switch(), casadi::SymbolicQr::~SymbolicQr(), casadi::ThreadMap::~ThreadMap(), and casadi::WorhpInterface::~WorhpInterface().
construct()
void casadi::ProtoFunction::construct (const Dict & opts)
Prepares the function for evaluation
Extra doc: https://github.com/casadi/casadi/wiki/L_jf
Definition at line 131 of file function_internal.cpp.
{
     // Sanitize dictionary is needed
     if (!Options::is_sane(opts)) {
       // Call recursively
       return construct(Options::sanitize(opts));
     }
     // Make sure all options exist
     get_options().check(opts);
     // Initialize the class hierarchy
     try {
       init(opts);
     } catch(std::exception& e) {
       casadi_error("Error calling " + class_name() + "::init for '" + name_ + "':\n"
         + std::string(e.what()));
     }
     // Revisit class hierarchy in reverse order
     try {
       finalize();
     } catch(std::exception& e) {
       casadi_error("Error calling " + class_name() + "::finalize for '" + name_ + "':\n"
         + std::string(e.what()));
     }
   }
References casadi::Options::check(), casadi::SharedObjectInternal::class_name(), finalize(), get_options(), init(), casadi::Options::is_sane(), name_, and casadi::Options::sanitize().
Referenced by casadi::Function::create(), and casadi::LinearInterpolant::get_jacobian().
destroySingleton()
void casadi::SharedObjectInternal::destroySingleton () inline protected inherited
Called in the destructor of singletons
Definition at line 79 of file shared_object_internal.hpp.
{
       count--;
     }
disp()
virtual void casadi::SharedObjectInternal::disp (std::ostream & stream, bool more) const pure virtual inherited
Implemented in casadi::XmlFileInternal, casadi::OptiNode, casadi::SparsityInternal, casadi::WeakRefInternal, casadi::MXNode, casadi::LinsolInternal, casadi::ImporterInternal, casadi::GenericTypeInternal< ID, T >, casadi::FunctionInternal, and casadi::DaeBuilderInternal.
Referenced by casadi::WeakRefInternal::disp().
finalize()
void casadi::ProtoFunction::finalize () virtual
This function, which visits the class hierarchy in reverse order is run after init() has been completed.
Extra doc: https://github.com/casadi/casadi/wiki/L_jm
Reimplemented in casadi::LinsolQr, casadi::OracleFunction, casadi::FunctionInternal, and casadi::CallbackInternal.
Definition at line 716 of file function_internal.cpp.
{
     // Create memory object
     int mem = checkout();
     casadi_assert_dev(mem==0);
   }
References checkout().
Referenced by construct(), casadi::Linsol::deserialize(), casadi::FunctionInternal::finalize(), and casadi::LinsolQr::finalize().
format_time()
void casadi::ProtoFunction::format_time (char * buffer, double time) const
Extra doc: https://github.com/casadi/casadi/wiki/L_jt
Definition at line 3678 of file function_internal.cpp.
{
     // Always of width 8
     casadi_assert_dev(time>=0);
     double log_time = log10(time);
     int magn = static_cast<int>(floor(log_time));
     int iprefix = static_cast<int>(floor(log_time/3));
     if (iprefix<-4) {
       sprint(buffer, 10, "       0");
       return;
     }
     if (iprefix>=5) {
       sprint(buffer, 10, "     inf");
       return;
     }
     char prefixes[] = "TGMk munp";
     char prefix = prefixes[4-iprefix];
     int rem = magn-3*iprefix;
     double time_normalized = time/pow(10, 3*iprefix);
     if (rem==0) {
       sprint(buffer, 10, "  %1.2f%cs", time_normalized, prefix);
     } else if (rem==1) {
       sprint(buffer, 10, " %2.2f%cs", time_normalized, prefix);
     } else {
       sprint(buffer, 10, "%3.2f%cs", time_normalized, prefix);
     }
   }
References sprint().
Referenced by print_time().
free_mem()
virtual void casadi::ProtoFunction::free_mem (void * mem) const inline virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_jp
Reimplemented in casadi::SymbolicQr, casadi::Sqpmethod, casadi::Scpgen, casadi::Qrsqp, casadi::Qrqp, casadi::QpToNlp, casadi::Newton, casadi::Lsqr, casadi::LinsolTridiag, casadi::LinsolQr, casadi::LinsolLdl, casadi::Ipqp, casadi::ImplicitToNlp, casadi::Feasiblesqpmethod, casadi::FastNewton, casadi::WorhpInterface, casadi::SuperscsInterface, casadi::KinsolInterface, casadi::IdasInterface, casadi::CvodesInterface, casadi::SnoptInterface, casadi::SlicotExpm, casadi::SlicotDple, casadi::QpoasesInterface, casadi::ProxqpInterface, casadi::OsqpInterface, casadi::OoqpInterface, casadi::MumpsInterface, casadi::LapackQr, casadi::LapackLu, casadi::KnitroInterface, casadi::IpoptInterface, casadi::Ma27Interface, casadi::HpmpcInterface, casadi::HpipmInterface, casadi::HighsInterface, casadi::GurobiInterface, casadi::CsparseInterface, casadi::CSparseCholeskyInterface, casadi::CplexInterface, casadi::ClpInterface, casadi::CbcInterface, casadi::BonminInterface, casadi::Blocksqp, casadi::AmplInterface, casadi::OracleFunction, casadi::Nlpsol, casadi::LinsolInternal, and casadi::FixedStepIntegrator.
Definition at line 182 of file function_internal.hpp.
 { delete static_cast<ProtoFunctionMemory*>(mem); }
Referenced by clear_mem().
generate_options()
Dict casadi::ProtoFunction::generate_options (const std::string & target) const virtual
Reimplemented in casadi::SXFunction, casadi::MXFunction, and casadi::FunctionInternal.
Definition at line 363 of file function_internal.cpp.
{
     Dict opts;
     opts["verbose"] = verbose_;
     opts["print_time"] = print_time_;
     opts["record_time"] = record_time_;
     opts["regularity_check"] = regularity_check_;
     opts["error_on_fail"] = error_on_fail_;
     return opts;
   }
References error_on_fail_, print_time_, record_time_, regularity_check_, and verbose_.
Referenced by casadi::FunctionInternal::generate_options().
get_options()
virtual const Options& casadi::ProtoFunction::get_options () const inline virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_jg
Reimplemented in casadi::SymbolicQr, casadi::Sqpmethod, casadi::Scpgen, casadi::Qrsqp, casadi::Qrqp, casadi::QpToNlp, casadi::Newton, casadi::LinsolQr, casadi::LinsolLdl, casadi::LinearInterpolant, casadi::Ipqp, casadi::ImplicitToNlp, casadi::Feasiblesqpmethod, casadi::FastNewton, casadi::Collocation, casadi::BSplineInterpolant, casadi::WorhpInterface, casadi::SuperscsInterface, casadi::SundialsInterface, casadi::KinsolInterface, casadi::IdasInterface, casadi::CvodesInterface, casadi::SnoptInterface, casadi::SlicotDple, casadi::QpoasesInterface, casadi::ProxqpInterface, casadi::OsqpInterface, casadi::OoqpInterface, casadi::MumpsInterface, casadi::LapackQr, casadi::LapackLu, casadi::KnitroInterface, casadi::IpoptInterface, casadi::HpmpcInterface, casadi::HpipmInterface, casadi::HighsInterface, casadi::GurobiInterface, casadi::CplexInterface, casadi::ClpInterface, casadi::CbcInterface, casadi::BonminInterface, casadi::Blocksqp, casadi::AmplInterface, casadi::SXFunction, casadi::Rootfinder, casadi::OracleFunction, casadi::Nlpsol, casadi::MXFunction, casadi::JitFunction, casadi::Interpolant, casadi::ImplicitFixedStepIntegrator, casadi::FixedStepIntegrator, casadi::Integrator, casadi::FunctionInternal, casadi::FiniteDiff, casadi::Expm, casadi::Dple, and casadi::Conic.
Definition at line 116 of file function_internal.hpp.
 { return options_;}
Referenced by construct(), has_option(), print_option(), and print_options().
get_stats()
Dict casadi::ProtoFunction::get_stats (void * mem) const virtual
Reimplemented in casadi::Sqpmethod, casadi::Scpgen, casadi::Qrsqp, casadi::Qrqp, casadi::QpToNlp, casadi::Newton, casadi::Ipqp, casadi::ImplicitToNlp, casadi::Feasiblesqpmethod, casadi::FastNewton, casadi::WorhpInterface, casadi::SuperscsInterface, casadi::SundialsInterface, casadi::SnoptInterface, casadi::QpoasesInterface, casadi::ProxqpInterface, casadi::OsqpInterface, casadi::OoqpInterface, casadi::KnitroInterface, casadi::IpoptInterface, casadi::HpmpcInterface, casadi::HpipmInterface, casadi::HighsInterface, casadi::GurobiInterface, casadi::CplexInterface, casadi::ClpInterface, casadi::CbcInterface, casadi::BonminInterface, casadi::Rootfinder, casadi::OracleFunction, casadi::Nlpsol, casadi::MXFunction, and casadi::Conic.
Definition at line 2816 of file function_internal.cpp.
{
     auto m = static_cast<ProtoFunctionMemory*>(mem);
     // Add timing statistics
     Dict stats;
     for (const auto& s : m->fstats) {
       stats["n_call_" +s.first] = s.second.n_call;
       stats["t_wall_" +s.first] = s.second.t_wall;
       stats["t_proc_" +s.first] = s.second.t_proc;
     }
     return stats;
   }
Referenced by casadi::Conic::get_stats(), casadi::MXFunction::get_stats(), casadi::OracleFunction::get_stats(), and casadi::QpToNlp::get_stats().
getCount()
casadi_int casadi::SharedObjectInternal::getCount () const inherited
Definition at line 58 of file shared_object_internal.cpp.
{
     return count;
   }
has_option()
bool casadi::ProtoFunction::has_option (const std::string & option_name) const
Extra doc: https://github.com/casadi/casadi/wiki/L_jj
Definition at line 900 of file function_internal.cpp.
{
     return get_options().find(option_name) != 0;
   }
References casadi::Options::find(), and get_options().
init()
void casadi::ProtoFunction::init (const Dict & opts) virtual
Initialize and make the object ready for setting arguments and evaluation. This method is typically called after setting options but before evaluating. If passed to another class (in the constructor), this class should invoke this function when initialized.
Extra doc: https://github.com/casadi/casadi/wiki/L_jl
Reimplemented in casadi::SymbolicQr, casadi::Sqpmethod, casadi::Scpgen, casadi::RungeKutta, casadi::Qrsqp, casadi::Qrqp, casadi::QpToNlp, casadi::Newton, casadi::LinsolTridiag, casadi::LinsolQr, casadi::LinsolLdl, casadi::LinearInterpolantJac, casadi::LinearInterpolant, casadi::Ipqp, casadi::ImplicitToNlp, casadi::Feasiblesqpmethod, casadi::FastNewton, casadi::Collocation, casadi::BSplineInterpolant, casadi::WorhpInterface, casadi::SuperscsInterface, casadi::SundialsInterface, casadi::KinsolInterface, casadi::IdasInterface, casadi::CvodesInterface, casadi::SnoptInterface, casadi::SlicotExpm, casadi::SlicotDple, casadi::QpoasesInterface, casadi::ProxqpInterface, casadi::OsqpInterface, casadi::OoqpInterface, casadi::MumpsInterface, casadi::LapackQr, casadi::LapackLu, casadi::KnitroInterface, casadi::IpoptInterface, casadi::Ma27Interface, casadi::HpmpcInterface, casadi::HpipmInterface, casadi::HighsInterface, casadi::GurobiInterface, casadi::CsparseInterface, casadi::CSparseCholeskyInterface, casadi::CplexInterface, casadi::ClpInterface, casadi::CbcInterface, casadi::BonminInterface, casadi::Blocksqp, casadi::AmplInterface, casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >, casadi::SXFunction, casadi::Switch, casadi::Rootfinder, casadi::OracleFunction, casadi::Nlpsol, casadi::MXFunction, casadi::MapSum, casadi::ThreadMap, casadi::OmpMap, casadi::Map, casadi::LinsolInternal, casadi::JitFunction, casadi::Interpolant, casadi::ImplicitFixedStepIntegrator, casadi::FixedStepIntegrator, casadi::Integrator, casadi::FunctionInternal, casadi::FiniteDiff, casadi::GenericExternal, casadi::External, casadi::Expm, casadi::Dple, casadi::Conic, and casadi::CallbackInternal.
Definition at line 346 of file function_internal.cpp.
{
     // Read options
     for (auto&& op : opts) {
       if (op.first=="verbose") {
         verbose_ = op.second;
       } else if (op.first=="print_time") {
         print_time_ = op.second;
       } else if (op.first=="record_time") {
         record_time_ = op.second;
       } else if (op.first=="regularity_check") {
         regularity_check_ = op.second;
       } else if (op.first=="error_on_fail") {
         error_on_fail_ = op.second;
       }
     }
   }
References error_on_fail_, print_time_, record_time_, regularity_check_, and verbose_.
Referenced by construct(), casadi::FunctionInternal::init(), and casadi::LinsolInternal::init().
init_mem()
int casadi::ProtoFunction::init_mem (void * mem) const virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_jo
Reimplemented in casadi::SymbolicQr, casadi::Sqpmethod, casadi::Scpgen, casadi::Qrqp, casadi::Newton, casadi::Lsqr, casadi::LinsolTridiag, casadi::LinsolQr, casadi::LinsolLdl, casadi::Ipqp, casadi::Feasiblesqpmethod, casadi::FastNewton, casadi::WorhpInterface, casadi::SuperscsInterface, casadi::SundialsInterface, casadi::KinsolInterface, casadi::IdasInterface, casadi::CvodesInterface, casadi::SnoptInterface, casadi::SlicotExpm, casadi::SlicotDple, casadi::QpoasesInterface, casadi::ProxqpInterface, casadi::OsqpInterface, casadi::MumpsInterface, casadi::LapackQr, casadi::LapackLu, casadi::KnitroInterface, casadi::IpoptInterface, casadi::Ma27Interface, casadi::HpmpcInterface, casadi::HpipmInterface, casadi::HighsInterface, casadi::GurobiInterface, casadi::CsparseInterface, casadi::CSparseCholeskyInterface, casadi::CplexInterface, casadi::ClpInterface, casadi::CbcInterface, casadi::BonminInterface, casadi::Blocksqp, casadi::AmplInterface, casadi::Rootfinder, casadi::OracleFunction, casadi::Nlpsol, casadi::LinsolInternal, casadi::FixedStepIntegrator, casadi::Integrator, and casadi::Conic.
Definition at line 787 of file function_internal.cpp.
{
     auto m = static_cast<ProtoFunctionMemory*>(mem);
     if (record_time_) {
       m->add_stat("total");
       m->t_total = &m->fstats.at("total");
     } else {
       m->t_total = nullptr;
     }
     return 0;
   }
References casadi::ProtoFunctionMemory::add_stat(), and record_time_.
Referenced by checkout(), casadi::FunctionInternal::codegen_checkout(), casadi::Conic::init_mem(), casadi::LinsolInternal::init_mem(), casadi::OracleFunction::init_mem(), casadi::SlicotDple::init_mem(), casadi::SlicotExpm::init_mem(), and casadi::OracleFunction::local_init_mem().
initSingleton()
void casadi::SharedObjectInternal::initSingleton () inline protected inherited
Called in the constructor of singletons to avoid that the counter reaches zero
Definition at line 73 of file shared_object_internal.hpp.
{
       casadi_assert_dev(count==0);
       count++;
     }
memory()
void * casadi::ProtoFunction::memory (int ind) const
Definition at line 3490 of file function_internal.cpp.
{
 #ifdef CASADI_WITH_THREAD
     std::lock_guard<std::mutex> lock(mtx_);
 #endif //CASADI_WITH_THREAD
     return mem_.at(ind);
   }
Referenced by casadi::FunctionInternal::call_gen(), casadi::FunctionInternal::get_jac_sparsity_gen(), casadi::FunctionInternal::get_jac_sparsity_hierarchical(), casadi::Sqpmethod::solve_ela_QP(), and casadi::Sqpmethod::solve_QP().
print()
void casadi::ProtoFunction::print (const char * fmt, ...) const
Extra doc: https://github.com/casadi/casadi/wiki/L_jr
Definition at line 3719 of file function_internal.cpp.
{
     // Variable number of arguments
     va_list args;
     va_start(args, fmt);
     // Static & dynamic buffers
     char buf[256];
     size_t buf_sz = sizeof(buf);
     char* buf_dyn = nullptr;
     // Try to print with a small buffer
     casadi_int n = vsnprintf(buf, buf_sz, fmt, args);
     // Need a larger buffer?
     if (n>static_cast<casadi_int>(buf_sz)) {
       buf_sz = static_cast<size_t>(n+1);
       buf_dyn = new char[buf_sz];
       n = vsnprintf(buf_dyn, buf_sz, fmt, args);
     }
     // Print buffer content
     if (n>=0) uout() << (buf_dyn ? buf_dyn : buf) << std::flush;
     // Cleanup
     delete[] buf_dyn;
     va_end(args);
     // Throw error if failure
     casadi_assert(n>=0, "Print failure while processing '" + std::string(fmt) + "'");
   }
References casadi::uout().
Referenced by casadi::Feasiblesqpmethod::anderson_acc_step_update(), casadi::Nlpsol::callback(), casadi::Blocksqp::convertHessian(), casadi::Feasiblesqpmethod::feasibility_iterations(), casadi::Blocksqp::feasibilityRestorationPhase(), casadi::Blocksqp::fullstep(), casadi::Blocksqp::init(), casadi::Feasiblesqpmethod::init(), casadi::Ipqp::init(), casadi::Qrqp::init(), casadi::Qrsqp::init(), casadi::Sqpmethod::init(), casadi::LinsolQr::nfact(), casadi::Feasiblesqpmethod::print_iteration(), casadi::Qrsqp::print_iteration(), casadi::Sqpmethod::print_iteration(), casadi::SundialsInterface::print_stats(), print_time(), casadi::Blocksqp::printInfo(), casadi::Blocksqp::printProgress(), casadi::Blocksqp::run(), casadi::Blocksqp::solve(), casadi::Feasiblesqpmethod::solve(), casadi::Qrsqp::solve(), casadi::Sqpmethod::solve(), casadi::Sqpmethod::solve_ela_QP(), casadi::Feasiblesqpmethod::solve_LP(), casadi::Feasiblesqpmethod::solve_QP(), casadi::Qrsqp::solve_QP(), casadi::Sqpmethod::solve_QP(), and casadi::Blocksqp::solveQP().
print_option()
void casadi::ProtoFunction::print_option (const std::string & name, std::ostream & stream) const
Extra doc: https://github.com/casadi/casadi/wiki/L_ji
Definition at line 896 of file function_internal.cpp.
{
     get_options().print_one(name, stream);
   }
References get_options(), and casadi::Options::print_one().
print_options()
void casadi::ProtoFunction::print_options (std::ostream & stream) const
Extra doc: https://github.com/casadi/casadi/wiki/L_jh
Definition at line 892 of file function_internal.cpp.
{
     get_options().print_all(stream);
   }
References get_options(), and casadi::Options::print_all().
print_time()
void casadi::ProtoFunction::print_time (const std::map< std::string, FStats > & fstats) const
Extra doc: https://github.com/casadi/casadi/wiki/L_ju
Definition at line 3639 of file function_internal.cpp.
{
     if (!print_time_) return;
     // Length of the name being printed
     size_t name_len=0;
     for (auto &&s : fstats) {
       name_len = std::max(s.first.size(), name_len);
     }
     name_len = std::max(name_.size(), name_len);
     // Print name with a given length. Format: "%NNs "
     char namefmt[10];
     sprint(namefmt, sizeof(namefmt), "%%%ds ", static_cast<casadi_int>(name_len));
     // Print header
     print(namefmt, name_.c_str());
     print(" : %8s %10s %8s %10s %9s\n", "t_proc", "(avg)", "t_wall", "(avg)", "n_eval");
     char buffer_proc[10];
     char buffer_wall[10];
     char buffer_proc_avg[10];
     char buffer_wall_avg[10];
     // Print keys
     for (const auto &s : fstats) {
       if (s.second.n_call!=0) {
         print(namefmt, s.first.c_str());
         format_time(buffer_proc, s.second.t_proc);
         format_time(buffer_wall, s.second.t_wall);
         format_time(buffer_proc_avg, s.second.t_proc/s.second.n_call);
         format_time(buffer_wall_avg, s.second.t_wall/s.second.n_call);
         print(" | %s (%s) %s (%s) %9d\n",
           buffer_proc, buffer_proc_avg,
           buffer_wall, buffer_wall_avg, s.second.n_call);
       }
     }
   }
References format_time(), name_, print(), print_time_, and sprint().
Referenced by casadi::FunctionInternal::eval_gen().
release()
void casadi::ProtoFunction::release (int mem) const
Definition at line 3517 of file function_internal.cpp.
{
 #ifdef CASADI_WITH_THREAD
     std::lock_guard<std::mutex> lock(mtx_);
 #endif //CASADI_WITH_THREAD
     unused_.push(mem);
   }
serialize()
void casadi::ProtoFunction::serialize (SerializingStream & s) const
Extra doc: https://github.com/casadi/casadi/wiki/L_jv
Definition at line 3995 of file function_internal.cpp.
{
     serialize_type(s);
     serialize_body(s);
   }
References serialize_body(), and serialize_type().
serialize_base_function()
virtual std::string casadi::ProtoFunction::serialize_base_function () const inline virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_jy
Reimplemented in casadi::LinearInterpolantJac, casadi::Rootfinder, casadi::Nlpsol, casadi::MapSum, casadi::Map, casadi::Interpolant, casadi::Integrator, casadi::External, and casadi::Conic.
Definition at line 229 of file function_internal.hpp.
{
       return class_name();
     }
Referenced by casadi::FunctionInternal::serialize_type().
serialize_body()
void casadi::ProtoFunction::serialize_body (SerializingStream & s) const virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_jw
Reimplemented in casadi::SymbolicQr, casadi::Sqpmethod, casadi::RungeKutta, casadi::Qrqp, casadi::QpToNlp, casadi::Newton, casadi::LinsolQr, casadi::LinsolLdl, casadi::LinearInterpolant, casadi::Ipqp, casadi::Feasiblesqpmethod, casadi::FastNewton, casadi::Collocation, casadi::BSplineInterpolant, casadi::WorhpInterface, casadi::SuperscsInterface, casadi::SundialsInterface, casadi::IdasInterface, casadi::CvodesInterface, casadi::SnoptInterface, casadi::QpoasesInterface, casadi::ProxqpInterface, casadi::OsqpInterface, casadi::OoqpInterface, casadi::MumpsInterface, casadi::LapackQr, casadi::LapackLu, casadi::KnitroInterface, casadi::IpoptInterface, casadi::HpipmInterface, casadi::HighsInterface, casadi::GurobiInterface, casadi::CplexInterface, casadi::ClpInterface, casadi::CbcInterface, casadi::BonminInterface, casadi::Blocksqp, casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >, casadi::SXFunction, casadi::Switch, casadi::Rootfinder, casadi::OracleFunction, casadi::Nlpsol, casadi::MXFunction, casadi::MapSum, casadi::Map, casadi::LinsolInternal, casadi::Interpolant, casadi::ImplicitFixedStepIntegrator, casadi::FixedStepIntegrator, casadi::Integrator, casadi::FunctionInternal, casadi::External, and casadi::Conic.
Definition at line 3784 of file function_internal.cpp.
{
     s.version("ProtoFunction", 2);
     s.pack("ProtoFunction::name", name_);
     s.pack("ProtoFunction::verbose", verbose_);
     s.pack("ProtoFunction::print_time", print_time_);
     s.pack("ProtoFunction::record_time", record_time_);
     s.pack("ProtoFunction::regularity_check", regularity_check_);
     s.pack("ProtoFunction::error_on_fail", error_on_fail_);
   }
References error_on_fail_, name_, casadi::SerializingStream::pack(), print_time_, record_time_, regularity_check_, verbose_, and casadi::SerializingStream::version().
Referenced by serialize(), casadi::FunctionInternal::serialize_body(), and casadi::LinsolInternal::serialize_body().
serialize_type()
virtual void casadi::ProtoFunction::serialize_type (SerializingStream & s) const inline virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_jx
Reimplemented in casadi::LinearInterpolantJac, casadi::LinearInterpolant, casadi::Rootfinder, casadi::Nlpsol, casadi::MapSum, casadi::Map, casadi::LinsolInternal, casadi::Interpolant, casadi::Integrator, casadi::FunctionInternal, casadi::GenericExternal, and casadi::Conic.
Definition at line 224 of file function_internal.hpp.
 {}
Referenced by serialize(), and casadi::LinsolInternal::serialize_type().
shared_from_this() [1/2]
template<class B > B casadi::SharedObjectInternal::shared_from_this protected inherited
Template function implementations.
Definition at line 136 of file shared_object_internal.hpp.
{
     casadi_assert_dev(B::test_cast(this));
     B ret;
     ret.own(this);
     return ret;
   }
shared_from_this() [2/2]
template<class B > const B casadi::SharedObjectInternal::shared_from_this protected inherited
Definition at line 144 of file shared_object_internal.hpp.
{
     casadi_assert_dev(B::test_cast(this));
     B ret;
     ret.own(const_cast<SharedObjectInternal*>(this));
     return ret;
   }
sprint()
void casadi::ProtoFunction::sprint (char * buf, size_t buf_sz, const char * fmt, ...) const
Extra doc: https://github.com/casadi/casadi/wiki/L_js
Definition at line 3707 of file function_internal.cpp.
{
     // Variable number of arguments
     va_list args;
     va_start(args, fmt);
     // Print to buffer
     casadi_int n = vsnprintf(buf, buf_sz, fmt, args);
     // Cleanup
     va_end(args);
     // Throw error if failure
     casadi_assert(n>=0 && n<buf_sz, "Print failure while processing '" + std::string(fmt) + "'");
   }
Referenced by format_time(), and print_time().
weak()
WeakRef * casadi::SharedObjectInternal::weak () inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1ai
Definition at line 62 of file shared_object_internal.cpp.
{
     if (weak_ref_==nullptr) {
       weak_ref_ = new WeakRef(this);
     }
     return weak_ref_;
   }
Referenced by casadi::SharedObject::weak().
Member Data Documentation
error_on_fail_
bool casadi::ProtoFunction::error_on_fail_
Definition at line 249 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::call_gen(), casadi::HighsInterface::codegen_body(), casadi::HpipmInterface::codegen_body(), casadi::OsqpInterface::codegen_body(), casadi::Qrqp::codegen_body(), casadi::Conic::Conic(), casadi::Conic::eval(), casadi::Nlpsol::eval(), casadi::Rootfinder::eval(), generate_options(), init(), casadi::Nlpsol::Nlpsol(), ProtoFunction(), casadi::Rootfinder::Rootfinder(), serialize_body(), casadi::CplexInterface::solve(), and casadi::KinsolInterface::solve().
name_
std::string casadi::ProtoFunction::name_
Definition at line 234 of file function_internal.hpp.
Referenced by casadi::MXFunction::ad_forward(), casadi::MXFunction::ad_reverse(), casadi::Integrator::augmented_dae(), casadi::OracleFunction::calc_function(), casadi::FunctionInternal::call_forward(), casadi::FunctionInternal::call_reverse(), casadi::FunctionInternal::codegen_body(), casadi::External::codegen_body(), casadi::External::codegen_checkout(), casadi::External::codegen_declarations(), casadi::MXFunction::codegen_declarations(), casadi::External::codegen_decref(), casadi::External::codegen_incref(), casadi::FunctionInternal::codegen_meta(), casadi::FunctionInternal::codegen_name(), casadi::External::codegen_release(), casadi::FunctionInternal::codegen_sparsities(), construct(), casadi::OracleFunction::create_function(), casadi::FunctionInternal::definition(), casadi::FunctionInternal::eval(), casadi::MXFunction::eval(), casadi::FunctionInternal::eval_mx(), casadi::MXFunction::eval_mx(), casadi::FunctionInternal::finalize(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::FunctionInternal(), casadi::Integrator::get_forward(), casadi::Integrator::get_forward_dae(), casadi::Map::get_function(), casadi::MapSum::get_function(), casadi::OracleFunction::get_function(), casadi::GenericExternal::get_jac_sparsity(), casadi::FunctionInternal::get_n_in(), casadi::External::get_n_in(), casadi::FunctionInternal::get_n_out(), casadi::External::get_n_out(), casadi::FunctionInternal::get_name_in(), casadi::External::get_name_in(), casadi::FunctionInternal::get_name_out(), casadi::External::get_name_out(), casadi::FunctionInternal::get_partition(), casadi::Integrator::get_reverse(), casadi::FunctionInternal::get_sparsity_in(), casadi::GenericExternal::get_sparsity_in(), casadi::FunctionInternal::get_sparsity_out(), casadi::GenericExternal::get_sparsity_out(), casadi::External::has_forward(), casadi::GenericExternal::has_jac_sparsity(), casadi::External::has_jacobian(), casadi::External::has_reverse(), casadi::External::init(), casadi::FunctionInternal::init(), casadi::MXFunction::init(), casadi::CvodesInterface::init(), casadi::IdasInterface::init(), casadi::External::init_external(), casadi::GenericExternal::init_external(), casadi::FunctionInternal::jac_is_symm(), casadi::FunctionInternal::jacobian(), casadi::FunctionInternal::map(), casadi::OracleFunction::monitored(), casadi::MXFunction::print_arg(), casadi::FunctionInternal::print_in(), casadi::FunctionInternal::print_out(), casadi::MXFunction::print_res(), print_time(), ProtoFunction(), casadi::CvodesInterface::reset(), casadi::IdasInterface::reset(), casadi::IdasInterface::resetB(), casadi::FunctionInternal::reverse(), serialize_body(), casadi::GurobiInterface::solve(), casadi::SnoptInterface::solve(), casadi::Integrator::sp_forward(), casadi::Integrator::sp_reverse(), casadi::FunctionInternal::wrap(), and casadi::FunctionInternal::wrap_as_needed().
options_
const Options casadi::ProtoFunction::options_ static
Initial value:
= {{},
     {{"verbose",
       {OT_BOOL,
        "Verbose evaluation -- for debugging"}},
      {"print_time",
       {OT_BOOL,
        "print information about execution time. Implies record_time."}},
      {"record_time",
       {OT_BOOL,
        "record information about execution time, for retrieval with stats()."}},
      {"regularity_check",
       {OT_BOOL,
        "Throw exceptions when NaN or Inf appears during evaluation"}},
      {"error_on_fail",
       {OT_BOOL,
        "Throw exceptions when function evaluation fails (default true)."}}
      }
  }
Extra doc: https://github.com/casadi/casadi/wiki/L_jg
Definition at line 115 of file function_internal.hpp.
Referenced by casadi::casadi_register_linsol_csparse(), casadi::casadi_register_linsol_lsqr(), casadi::casadi_register_linsol_ma27(), and casadi::casadi_register_linsol_tridiag().
print_time_
bool casadi::ProtoFunction::print_time_
Definition at line 240 of file function_internal.hpp.
Referenced by casadi::FixedStepIntegrator::create_advanced(), generate_options(), init(), casadi::FunctionInternal::init(), casadi::Nlpsol::Nlpsol(), print_time(), ProtoFunction(), and serialize_body().
record_time_
bool casadi::ProtoFunction::record_time_
Definition at line 243 of file function_internal.hpp.
Referenced by generate_options(), init(), casadi::FunctionInternal::init(), init_mem(), casadi::LinsolInternal::init_mem(), ProtoFunction(), and serialize_body().
regularity_check_
bool casadi::ProtoFunction::regularity_check_
Definition at line 246 of file function_internal.hpp.
Referenced by casadi::OracleFunction::calc_function(), change_option(), casadi::FunctionInternal::eval_gen(), casadi::FunctionInternal::FunctionInternal(), generate_options(), init(), ProtoFunction(), and serialize_body().
verbose_
bool casadi::ProtoFunction::verbose_
Definition at line 237 of file function_internal.hpp.
Referenced by casadi::MXFunction::ad_forward(), casadi::MXFunction::ad_reverse(), change_option(), casadi::BSplineInterpolant::construct_graph(), casadi::OracleFunction::create_function(), casadi::Integrator::eval(), casadi::MXFunction::eval(), casadi::MXFunction::eval_mx(), casadi::FunctionInternal::finalize(), casadi::KinsolInterface::func(), generate_options(), casadi::Integrator::get_forward(), casadi::Integrator::get_forward_dae(), casadi::FunctionInternal::get_jac_sparsity_gen(), casadi::FunctionInternal::get_jac_sparsity_hierarchical(), casadi::FunctionInternal::get_jac_sparsity_hierarchical_symm(), casadi::FunctionInternal::get_partition(), casadi::Integrator::get_reverse(), init(), casadi::FiniteDiff::init(), casadi::FunctionInternal::init(), casadi::MXFunction::init(), casadi::Blocksqp::init(), casadi::HpipmInterface::init(), casadi::HpmpcInterface::init(), casadi::IpoptInterface::init(), casadi::CvodesInterface::init(), casadi::IdasInterface::init(), casadi::Feasiblesqpmethod::init(), casadi::Scpgen::init(), casadi::Sqpmethod::init(), casadi::IpoptInterface::init_mem(), casadi::IdasInterface::init_mem(), casadi::BonminInterface::intermediate_callback(), casadi::OracleFunction::jit_dependencies(), casadi::CsparseInterface::nfact(), casadi::LapackLu::nfact(), casadi::LapackQr::nfact(), casadi::LinsolQr::nfact(), ProtoFunction(), casadi::CvodesInterface::reset(), casadi::IdasInterface::reset(), casadi::IdasInterface::resetB(), serialize_body(), casadi::CbcInterface::solve(), casadi::ClpInterface::solve(), casadi::CplexInterface::solve(), casadi::GurobiInterface::solve(), casadi::QpoasesInterface::solve(), casadi::Ipqp::solve(), casadi::Qrqp::solve(), casadi::AmplInterface::solve(), casadi::SnoptInterface::solve(), casadi::KinsolInterface::solve(), casadi::WorhpInterface::solve(), casadi::Newton::solve(), casadi::Qrsqp::solve(), casadi::Scpgen::solve(), casadi::Sqpmethod::solve(), casadi::Sqpmethod::solve_ela_QP(), casadi::Feasiblesqpmethod::solve_LP(), casadi::Feasiblesqpmethod::solve_QP(), casadi::Qrsqp::solve_QP(), casadi::Sqpmethod::solve_QP(), casadi::Integrator::sp_forward(), and casadi::Integrator::sp_reverse().
The documentation for this class was generated from the following files:
function_internal.hpp
function_internal.cpp