CasADi: casadi::StringSerializer Class Reference
casadi::StringSerializer Class Reference
#include <serializer.hpp>
Detailed Description
Definition at line 181 of file serializer.hpp.
Public Types
enum SerializationType {
SERIALIZED_SPARSITY , SERIALIZED_MX_v1 , SERIALIZED_DM , SERIALIZED_SX_v1 ,
SERIALIZED_LINSOL , SERIALIZED_FUNCTION , SERIALIZED_GENERICTYPE , SERIALIZED_INT ,
SERIALIZED_DOUBLE , SERIALIZED_STRING , SERIALIZED_SPARSITY_VECTOR , SERIALIZED_MX_VECTOR_v1 ,
SERIALIZED_DM_VECTOR , SERIALIZED_SX_VECTOR_v1 , SERIALIZED_LINSOL_VECTOR , SERIALIZED_FUNCTION_VECTOR ,
SERIALIZED_GENERICTYPE_VECTOR , SERIALIZED_INT_VECTOR , SERIALIZED_DOUBLE_VECTOR , SERIALIZED_STRING_VECTOR ,
SERIALIZED_MX , SERIALIZED_SX , SERIALIZED_MX_VECTOR , SERIALIZED_SX_VECTOR
}
Public Member Functions
StringSerializer (const Dict &opts=Dict())
Advanced serialization of CasADi objects.
~StringSerializer ()
std::string encode ()
Returns a string that holds the serialized objects.
void pack (const Sparsity &e)
void pack (const MX &e)
void pack (const Matrix< double > &e)
void pack (const Matrix< SXElem > &e)
void pack (const Linsol &e)
void pack (const Function &e)
void pack (const GenericType &e)
void pack (const casadi_int &e)
void pack (const double &e)
void pack (const std::string &e)
void pack (const std::vector< Sparsity > &e)
void pack (const std::vector< MX > &e)
void pack (const std::vector< Matrix< double > > &e)
void pack (const std::vector< Matrix< SXElem > > &e)
void pack (const std::vector< Linsol > &e)
void pack (const std::vector< Function > &e)
void pack (const std::vector< GenericType > &e)
void pack (const std::vector< casadi_int > &e)
void pack (const std::vector< double > &e)
void pack (const std::vector< std::string > &e)
void connect (DeserializerBase &s)
void reset ()
Static Public Member Functions
static std::string type_to_string (SerializationType type)
Protected Member Functions
SerializingStream & serializer ()
Protected Attributes
std::unique_ptr< std::ostream > sstream_
std::unique_ptr< SerializingStream > serializer_
Member Enumeration Documentation
SerializationType
enum casadi::SerializerBase::SerializationType inherited
Enumerator
SERIALIZED_SPARSITY
SERIALIZED_MX_v1
SERIALIZED_DM
SERIALIZED_SX_v1
SERIALIZED_LINSOL
SERIALIZED_FUNCTION
SERIALIZED_GENERICTYPE
SERIALIZED_INT
SERIALIZED_DOUBLE
SERIALIZED_STRING
SERIALIZED_SPARSITY_VECTOR
SERIALIZED_MX_VECTOR_v1
SERIALIZED_DM_VECTOR
SERIALIZED_SX_VECTOR_v1
SERIALIZED_LINSOL_VECTOR
SERIALIZED_FUNCTION_VECTOR
SERIALIZED_GENERICTYPE_VECTOR
SERIALIZED_INT_VECTOR
SERIALIZED_DOUBLE_VECTOR
SERIALIZED_STRING_VECTOR
SERIALIZED_MX
SERIALIZED_SX
SERIALIZED_MX_VECTOR
SERIALIZED_SX_VECTOR
Definition at line 78 of file serializer.hpp.
{
       SERIALIZED_SPARSITY,
       SERIALIZED_MX_v1,
       SERIALIZED_DM,
       SERIALIZED_SX_v1,
       SERIALIZED_LINSOL,
       SERIALIZED_FUNCTION,
       SERIALIZED_GENERICTYPE,
       SERIALIZED_INT,
       SERIALIZED_DOUBLE,
       SERIALIZED_STRING,
       SERIALIZED_SPARSITY_VECTOR,
       SERIALIZED_MX_VECTOR_v1,
       SERIALIZED_DM_VECTOR,
       SERIALIZED_SX_VECTOR_v1,
       SERIALIZED_LINSOL_VECTOR,
       SERIALIZED_FUNCTION_VECTOR,
       SERIALIZED_GENERICTYPE_VECTOR,
       SERIALIZED_INT_VECTOR,
       SERIALIZED_DOUBLE_VECTOR,
       SERIALIZED_STRING_VECTOR,
       SERIALIZED_MX,
       SERIALIZED_SX,
       SERIALIZED_MX_VECTOR,
       SERIALIZED_SX_VECTOR
     };
Constructor & Destructor Documentation
StringSerializer()
casadi::StringSerializer::StringSerializer (const Dict & opts = Dict())
This class is intended for advanced users that want to circumvent the restrictions of standard pickling/matlab save load, ie no raw SX/MX symbols allowed.
x = SX.sym('x');
s = StringSerializer();
s.pack(x);
s.pack(sin(x));
data = s.encode();
s = StringDeserializer(data);
a = s.unpack();
b = s.unpack();
Note: Saving SX/MX objects individually has a substantial overhead (both time and length of encoded string). You are encouraged to use the vector/list variants of 'save' for SX/MX to reduce the overhead.
See also
Function::save, Function::serialize, StringDeserializer, FileSerializer
Extra doc: https://github.com/casadi/casadi/wiki/L_7o
Definition at line 38 of file serializer.cpp.
                                                        :
         SerializerBase(std::unique_ptr<std::ostream>(new std::stringstream()), opts) {
     }
~StringSerializer()
casadi::StringSerializer::~StringSerializer ()
Definition at line 101 of file serializer.cpp.
 { }
Member Function Documentation
connect()
void casadi::SerializerBase::connect (DeserializerBase & s) inherited
Definition at line 295 of file serializer.cpp.
{
     serializer_->connect(*s.deserializer_);
   }
References casadi::SerializerBase::connect().
Referenced by casadi::SerializerBase::connect().
encode()
std::string casadi::StringSerializer::encode ()
As a side effect, this method clears the internal buffer
Extra doc: https://github.com/casadi/casadi/wiki/L_7p
Definition at line 87 of file serializer.cpp.
{
       std::string ret = static_cast<std::stringstream*>(sstream_.get())->str();
       static_cast<std::stringstream*>(sstream_.get())->str("");
       sstream_->clear();
       return ret;
     }
References casadi::SerializerBase::sstream_, and casadi::str().
Referenced by casadi::external_transform().
pack() [1/20]
void casadi::SerializerBase::pack (const casadi_int & e) inherited
pack() [2/20]
void casadi::SerializerBase::pack (const double & e) inherited
pack() [3/20]
void casadi::SerializerBase::pack (const Function & e) inherited
pack() [4/20]
void casadi::SerializerBase::pack (const GenericType & e) inherited
pack() [5/20]
void casadi::SerializerBase::pack (const Linsol & e) inherited
pack() [6/20]
void casadi::SerializerBase::pack (const Matrix< double > & e) inherited
pack() [7/20]
void casadi::SerializerBase::pack (const Matrix< SXElem > & e) inherited
pack() [8/20]
void casadi::SerializerBase::pack (const MX & e) inherited
Definition at line 141 of file serializer.cpp.
{
       serializer().pack(static_cast<char>(SERIALIZED_MX));
       serializer().pack(Function::order({e}));
       serializer().pack(e);
     }
References casadi::Function::order(), casadi::SerializingStream::pack(), casadi::SerializerBase::SERIALIZED_MX, and casadi::SerializerBase::serializer().
pack() [9/20]
void casadi::SerializerBase::pack (const Sparsity & e) inherited
Referenced by casadi::external_transform(), and casadi::Function::save().
pack() [10/20]
void casadi::SerializerBase::pack (const std::string & e) inherited
pack() [11/20]
void casadi::SerializerBase::pack (const std::vector< casadi_int > & e) inherited
pack() [12/20]
void casadi::SerializerBase::pack (const std::vector< double > & e) inherited
pack() [13/20]
void casadi::SerializerBase::pack (const std::vector< Function > & e) inherited
pack() [14/20]
void casadi::SerializerBase::pack (const std::vector< GenericType > & e) inherited
pack() [15/20]
void casadi::SerializerBase::pack (const std::vector< Linsol > & e) inherited
pack() [16/20]
void casadi::SerializerBase::pack (const std::vector< Matrix< double > > & e) inherited
pack() [17/20]
void casadi::SerializerBase::pack (const std::vector< Matrix< SXElem > > & e) inherited
pack() [18/20]
void casadi::SerializerBase::pack (const std::vector< MX > & e) inherited
Definition at line 146 of file serializer.cpp.
{
       serializer().pack(static_cast<char>(SERIALIZED_MX_VECTOR));
       serializer().pack(Function::order(e));
       serializer().pack(e);
     }
References casadi::Function::order(), casadi::SerializingStream::pack(), casadi::SerializerBase::SERIALIZED_MX_VECTOR, and casadi::SerializerBase::serializer().
pack() [19/20]
void casadi::SerializerBase::pack (const std::vector< Sparsity > & e) inherited
pack() [20/20]
void casadi::SerializerBase::pack (const std::vector< std::string > & e) inherited
reset()
void casadi::SerializerBase::reset () inherited
Definition at line 298 of file serializer.cpp.
{
     serializer_->reset();
   }
References casadi::SerializerBase::serializer_.
serializer()
SerializingStream & casadi::SerializerBase::serializer () protected inherited
Definition at line 125 of file serializer.cpp.
{
       return *serializer_;
     }
References casadi::SerializerBase::serializer_.
Referenced by casadi::SerializerBase::pack().
type_to_string()
std::string casadi::SerializerBase::type_to_string (SerializationType type) static inherited
Definition at line 54 of file serializer.cpp.
{
       switch (type) {
         case SERIALIZED_SPARSITY: return "sparsity";
         case SERIALIZED_MX: return "mx";
         case SERIALIZED_MX_v1: return "mx_v1";
         case SERIALIZED_DM: return "dm";
         case SERIALIZED_SX: return "sx";
         case SERIALIZED_SX_v1: return "sx_v1";
         case SERIALIZED_LINSOL: return "linsol";
         case SERIALIZED_FUNCTION: return "function";
         case SERIALIZED_GENERICTYPE: return "generictype";
         case SERIALIZED_INT: return "int";
         case SERIALIZED_DOUBLE: return "double";
         case SERIALIZED_STRING: return "string";
         case SERIALIZED_SPARSITY_VECTOR: return "sparsity_vector";
         case SERIALIZED_MX_VECTOR: return "mx_vector";
         case SERIALIZED_MX_VECTOR_v1: return "mx_vector_v1";
         case SERIALIZED_DM_VECTOR: return "dm_vector";
         case SERIALIZED_SX_VECTOR: return "sx_vector";
         case SERIALIZED_SX_VECTOR_v1: return "sx_vector_v1";
         case SERIALIZED_LINSOL_VECTOR: return "linsol_vector";
         case SERIALIZED_FUNCTION_VECTOR: return "function_vector";
         case SERIALIZED_GENERICTYPE_VECTOR: return "generictype_vector";
         case SERIALIZED_INT_VECTOR: return "int_vector";
         case SERIALIZED_DOUBLE_VECTOR: return "double_vector";
         case SERIALIZED_STRING_VECTOR: return "string_vector";
         default: casadi_error("Unknown type" + str(type));
       }
     }
References casadi::SerializerBase::SERIALIZED_DM, casadi::SerializerBase::SERIALIZED_DM_VECTOR, casadi::SerializerBase::SERIALIZED_DOUBLE, casadi::SerializerBase::SERIALIZED_DOUBLE_VECTOR, casadi::SerializerBase::SERIALIZED_FUNCTION, casadi::SerializerBase::SERIALIZED_FUNCTION_VECTOR, casadi::SerializerBase::SERIALIZED_GENERICTYPE, casadi::SerializerBase::SERIALIZED_GENERICTYPE_VECTOR, casadi::SerializerBase::SERIALIZED_INT, casadi::SerializerBase::SERIALIZED_INT_VECTOR, casadi::SerializerBase::SERIALIZED_LINSOL, casadi::SerializerBase::SERIALIZED_LINSOL_VECTOR, casadi::SerializerBase::SERIALIZED_MX, casadi::SerializerBase::SERIALIZED_MX_v1, casadi::SerializerBase::SERIALIZED_MX_VECTOR, casadi::SerializerBase::SERIALIZED_MX_VECTOR_v1, casadi::SerializerBase::SERIALIZED_SPARSITY, casadi::SerializerBase::SERIALIZED_SPARSITY_VECTOR, casadi::SerializerBase::SERIALIZED_STRING, casadi::SerializerBase::SERIALIZED_STRING_VECTOR, casadi::SerializerBase::SERIALIZED_SX, casadi::SerializerBase::SERIALIZED_SX_v1, casadi::SerializerBase::SERIALIZED_SX_VECTOR, casadi::SerializerBase::SERIALIZED_SX_VECTOR_v1, and casadi::str().
Referenced by casadi::DeserializerBase::unpack_mx(), casadi::DeserializerBase::unpack_mx_vector(), casadi::DeserializerBase::unpack_sx(), and casadi::DeserializerBase::unpack_sx_vector().
Member Data Documentation
serializer_
std::unique_ptr<SerializingStream> casadi::SerializerBase::serializer_ protected inherited
Definition at line 113 of file serializer.hpp.
Referenced by casadi::DeserializerBase::connect(), casadi::SerializerBase::reset(), and casadi::SerializerBase::serializer().
sstream_
std::unique_ptr<std::ostream> casadi::SerializerBase::sstream_ protected inherited
Definition at line 112 of file serializer.hpp.
Referenced by encode().
The documentation for this class was generated from the following files:
serializer.hpp
serializer.cpp