CasADi: casadi::Resource Class Reference
casadi::Resource Class Reference
RAII class for reading from a zip file.
#include <resource.hpp>
Detailed Description
Extra doc: https://github.com/casadi/casadi/wiki/L_2cn
Definition at line 42 of file resource.hpp.
Public Types
using internal_base_type = SharedObjectInternal
using base_type = SharedObject
Public Member Functions
Resource (const std::string &path)
Initialize with a path.
Resource ()
Default constructor.
ResourceInternal * get () const
const ResourceInternal * operator-> () const
Access a member function or object.
ResourceInternal * operator-> ()
Access a member function or object.
const ResourceInternal & operator* () const
Reference to internal structure.
const std::string & path () const
Get path for a consumer.
void serialize (SerializingStream &s) const
Serialize an object.
void change_option (const std::string &option_name, const GenericType &option_value)
Change option after object creation for debugging.
std::string class_name () const
Get class name.
void disp (std::ostream &stream, bool more=false) const
Print a description of the object.
std::string get_str (bool more=false) const
Get string representation.
void print_ptr (std::ostream &stream=casadi::uout()) const
void own (SharedObjectInternal *node)
void assign (SharedObjectInternal *node)
Assign the node to a node class pointer without reference counting.
casadi_int getCount () const
Get the reference count.
void swap (GenericShared &other)
Swap content with another instance.
std::string debug_repr () const
bool is_null () const
Is a null pointer?
casadi_int __hash__ () const
Returns a number that is unique for a given Node.
GenericWeakRef< SharedObject, SharedObjectInternal > * weak ()
Get a weak reference to the object.
Static Public Member Functions
static std::string type_name ()
Readable name of the public class.
static bool test_cast (const SharedObjectInternal *ptr)
Check if a particular cast is allowed.
static Resource create (ResourceInternal *node)
Create from node.
static Resource deserialize (DeserializingStream &s)
Deserialize with type disambiguation.
Protected Member Functions
void count_up ()
void count_down ()
Member Typedef Documentation
base_type
using casadi::SharedObject::base_type = SharedObject inherited
Definition at line 103 of file shared_object.hpp.
internal_base_type
using casadi::SharedObject::internal_base_type = SharedObjectInternal inherited
Definition at line 102 of file shared_object.hpp.
Constructor & Destructor Documentation
Resource() [1/2]
casadi::Resource::Resource (const std::string & path)
If the path is a directory or empty, the path is passed through to the consumer. Otherwise, the zip file is extracted to a temporary directory.
Upon destruction, the temporary directory is removed.
Extra doc: https://github.com/casadi/casadi/wiki/L_2co
Definition at line 35 of file resource.cpp.
{
     // Pass through empty strings
     if (path.empty() || !Filesystem::is_enabled() || Filesystem::is_directory(path)) {
       own(new DirResource(path));
       return;
     }
     own(new ZipResource(path));
   }
References casadi::Filesystem::is_directory(), casadi::Filesystem::is_enabled(), casadi::GenericShared< SharedObject, SharedObjectInternal >::own(), and path().
Resource() [2/2]
casadi::Resource::Resource () explicit
Definition at line 32 of file resource.cpp.
                      {
   }
Member Function Documentation
__hash__()
casadi_int casadi::GenericShared< SharedObject , SharedObjectInternal >::__hash__ inherited
If the Object does not point to any node, "0" is returned.
Extra doc: https://github.com/casadi/casadi/wiki/L_av
Definition at line 123 of file generic_shared_impl.hpp.
{
     return reinterpret_cast<casadi_int>(get());
   }
assign()
void casadi::GenericShared< SharedObject , SharedObjectInternal >::assign (Internal * node) inherited
improper use will cause memory leaks!
Extra doc: https://github.com/casadi/casadi/wiki/L_at
Definition at line 96 of file generic_shared_impl.hpp.
{
     node = node_;
   }
change_option()
void casadi::Resource::change_option (const std::string & option_name, const GenericType & option_value)
This is only possible for a selected number of options that do not change the numerical results of the comput
Extra doc: https://github.com/casadi/casadi/wiki/L_2d4
Definition at line 74 of file resource.cpp.
{
     return (*this)->change_option(option_name, option_value);
   }
Referenced by casadi::DaeBuilderInternal::DaeBuilderInternal().
class_name()
std::string casadi::SharedObject::class_name () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_au
Definition at line 31 of file shared_object.cpp.
{
     return (*this)->class_name();
   }
Referenced by casadi::FmuFunction::check_mem_count(), casadi::MXFunction::export_code_body(), and casadi::BlazingSplineFunction::merge().
count_down()
void casadi::GenericShared< SharedObject , SharedObjectInternal >::count_down protected inherited
Definition at line 133 of file generic_shared_impl.hpp.
{
 #ifdef WITH_EXTRA_CHECKS
     casadi_assert_dev(Function::call_depth_==0);
 #endif // WITH_EXTRA_CHECKS
     if (!node) return;
     if (node->weak_ref_) {
 #ifdef CASADI_WITH_THREADSAFE_SYMBOLICS
       auto mutex = node->weak_ref_->get_mutex();
       // Avoid triggering a delete while a weak_ref.shared_if_alive is being called
       std::lock_guard<std::mutex> lock(*mutex);
       // Could it be that this mutex is destroyed when the lock goes out of scope?
 #endif // CASADI_WITH_THREADSAFE_SYMBOLICS
       if (--static_cast<Internal*>(node)->count == 0) {
         delete node;
         node = nullptr;
       }
     } else {
       if (--static_cast<Internal*>(node)->count == 0) {
         delete node;
         node = nullptr;
       }
     }
   }
count_up()
void casadi::GenericShared< SharedObject , SharedObjectInternal >::count_up protected inherited
Definition at line 132 of file generic_shared_impl.hpp.
{
 #ifdef WITH_EXTRA_CHECKS
     casadi_assert_dev(Function::call_depth_==0);
 #endif // WITH_EXTRA_CHECKS
     if (node) static_cast<Internal*>(node)->count++;
   }
create()
Resource casadi::Resource::create (ResourceInternal * node) static
Extra doc: https://github.com/casadi/casadi/wiki/L_2cp
Definition at line 44 of file resource.cpp.
{
     Resource ret;
     ret.own(node);
     return ret;
   }
References casadi::GenericShared< Shared, Internal >::own().
Referenced by deserialize().
debug_repr()
std::string casadi::GenericShared< SharedObject , SharedObjectInternal >::debug_repr inherited
Definition at line 112 of file generic_shared_impl.hpp.
{
     if (node) {
         return node->debug_repr(node);
     } else {
         return "NULL";
     }
   }
deserialize()
Resource casadi::Resource::deserialize (DeserializingStream & s) static
Extra doc: https://github.com/casadi/casadi/wiki/L_2cr
Definition at line 82 of file resource.cpp.
{
     return Resource::create(ResourceInternal::deserialize(s));
   }
References create(), and casadi::ResourceInternal::deserialize().
disp()
void casadi::SharedObject::disp (std::ostream & stream, bool more = false) const inherited
Definition at line 35 of file shared_object.cpp.
{
     if (is_null()) {
       stream << "NULL";
     } else {
       (*this)->disp(stream, more);
     }
   }
References casadi::GenericShared< SharedObject, SharedObjectInternal >::is_null().
Referenced by casadi::Nlpsol::disp_more(), and casadi::CsparseInterface::nfact().
get()
ResourceInternal * casadi::Resource::get () const
Definition at line 66 of file resource.cpp.
{
     return static_cast<ResourceInternal*>(SharedObject::get());
   }
References casadi::GenericShared< SharedObject, SharedObjectInternal >::get().
Referenced by operator*().
get_str()
std::string casadi::SharedObject::get_str (bool more = false) const inline inherited
Definition at line 91 of file shared_object.hpp.
{
         std::stringstream ss;
         disp(ss, more);
         return ss.str();
       }
getCount()
casadi_int casadi::GenericShared< SharedObject , SharedObjectInternal >::getCount inherited
Definition at line 102 of file generic_shared_impl.hpp.
{
     return (*this)->getCount();
   }
is_null()
bool casadi::GenericShared< SharedObject , SharedObjectInternal >::is_null inherited
Definition at line 116 of file generic_shared_impl.hpp.
{
     return node==nullptr;
   }
operator*()
const ResourceInternal & casadi::Resource::operator* () const
Definition at line 58 of file resource.cpp.
{
     return *static_cast<const ResourceInternal*>(get());
   }
References get().
operator->() [1/2]
ResourceInternal * casadi::Resource::operator-> ()
Definition at line 54 of file resource.cpp.
{
     return static_cast<ResourceInternal*>(SharedObject::operator->());
   }
References casadi::GenericShared< SharedObject, SharedObjectInternal >::operator->().
operator->() [2/2]
const ResourceInternal * casadi::Resource::operator-> () const
Definition at line 50 of file resource.cpp.
{
     return static_cast<const ResourceInternal*>(SharedObject::operator->());
   }
References casadi::GenericShared< SharedObject, SharedObjectInternal >::operator->().
own()
void casadi::GenericShared< SharedObject , SharedObjectInternal >::own (Internal * node) inherited
Assign the node to a node class pointer (or null)
Definition at line 89 of file generic_shared_impl.hpp.
{
     count_down();
     node = node_;
     count_up();
   }
path()
const std::string & casadi::Resource::path () const
Definition at line 70 of file resource.cpp.
{
     return (*this)->path();
   }
Referenced by casadi::FmuInternal::finalize(), and Resource().
print_ptr()
void casadi::SharedObject::print_ptr (std::ostream & stream = casadi::uout()) const inherited
Print the pointer to the internal class
Definition at line 43 of file shared_object.cpp.
{
     stream << get();
   }
References casadi::GenericShared< SharedObject, SharedObjectInternal >::get().
serialize()
void casadi::Resource::serialize (SerializingStream & s) const
Extra doc: https://github.com/casadi/casadi/wiki/L_2cq
Definition at line 78 of file resource.cpp.
{
     return (*this)->serialize(s);
   }
swap()
void casadi::GenericShared< SharedObject , SharedObjectInternal >::swap (GenericShared< SharedObject, SharedObjectInternal > & other) inherited
Definition at line 105 of file generic_shared_impl.hpp.
{
     GenericShared<Shared, Internal> temp = *this;
     *this = other;
     other = temp;
   }
test_cast()
bool casadi::Resource::test_cast (const SharedObjectInternal * ptr) static
Definition at line 62 of file resource.cpp.
{
     return dynamic_cast<const ResourceInternal*>(ptr)!=nullptr;
   }
type_name()
static std::string casadi::Resource::type_name () inline static
Definition at line 59 of file resource.hpp.
 {return "Resource";}
weak()
GenericWeakRef< SharedObject , SharedObjectInternal > * casadi::GenericShared< SharedObject , SharedObjectInternal >::weak inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_aw
Definition at line 130 of file generic_shared_impl.hpp.
{
     return (*this)->weak();
   }
The documentation for this class was generated from the following files:
resource.hpp
resource.cpp