CasADi: casadi::HpmpcMemory Struct Reference
casadi::HpmpcMemory Struct Reference
#include <hpmpc_interface.hpp>
Detailed Description
Definition at line 75 of file hpmpc_interface.hpp.
Public Member Functions
HpmpcMemory ()
Constructor.
~HpmpcMemory ()
Destructor.
void add_stat (const std::string &s)
Public Attributes
std::vector< double > A
std::vector< double > B
std::vector< double > b
std::vector< double > b2
std::vector< double > Q
std::vector< double > S
std::vector< double > R
std::vector< double > q
std::vector< double > r
std::vector< double > lb
std::vector< double > ub
std::vector< double > C
std::vector< double > D
std::vector< double > lg
std::vector< double > ug
std::vector< double * > As
std::vector< double * > Bs
std::vector< double * > bs
std::vector< double * > Qs
std::vector< double * > Ss
std::vector< double * > Rs
std::vector< double * > qs
std::vector< double * > rs
std::vector< double * > lbs
std::vector< double * > ubs
std::vector< double * > Cs
std::vector< double * > Ds
std::vector< double * > lgs
std::vector< double * > ugs
std::vector< double > I
std::vector< double * > Is
std::vector< double > x
std::vector< double > u
std::vector< double > pi
std::vector< double > lam
std::vector< double * > xs
std::vector< double * > us
std::vector< double * > pis
std::vector< double * > lams
std::vector< int > hidxb
std::vector< int * > hidxbs
std::vector< int > nx
std::vector< int > nu
std::vector< int > ng
std::vector< int > nb
std::vector< double > stats
std::vector< char > workspace
std::vector< double > pv
int iter_count
int return_status
std::vector< double > res
casadi_qp_data< double > d_qp
std::map< std::string, FStats > fstats
FStats * t_total
Constructor & Destructor Documentation
HpmpcMemory()
casadi::HpmpcMemory::HpmpcMemory ()
Definition at line 738 of file hpmpc_interface.cpp.
{
   }
~HpmpcMemory()
casadi::HpmpcMemory::~HpmpcMemory ()
Definition at line 741 of file hpmpc_interface.cpp.
{
   }
Member Function Documentation
add_stat()
void casadi::ProtoFunctionMemory::add_stat (const std::string & s) inline inherited
Definition at line 74 of file function_internal.hpp.
{
       bool added = fstats.insert(std::make_pair(s, FStats())).second;
       casadi_assert(added, "Duplicate stat: '" + s + "'");
     }
Referenced by casadi::ProtoFunction::init_mem(), casadi::LinsolInternal::init_mem(), casadi::Nlpsol::init_mem(), casadi::OracleFunction::init_mem(), casadi::CbcInterface::init_mem(), casadi::ClpInterface::init_mem(), casadi::FatropConicInterface::init_mem(), casadi::HpipmInterface::init_mem(), casadi::Feasiblesqpmethod::init_mem(), casadi::Sqpmethod::init_mem(), and casadi::OracleFunction::local_init_mem().
Member Data Documentation
A
std::vector<double> casadi::HpmpcMemory::A
Definition at line 77 of file hpmpc_interface.hpp.
As
std::vector<double*> casadi::HpmpcMemory::As
Definition at line 78 of file hpmpc_interface.hpp.
B
std::vector<double> casadi::HpmpcMemory::B
Definition at line 77 of file hpmpc_interface.hpp.
b
std::vector<double> casadi::HpmpcMemory::b
Definition at line 77 of file hpmpc_interface.hpp.
b2
std::vector<double> casadi::HpmpcMemory::b2
Definition at line 77 of file hpmpc_interface.hpp.
Bs
std::vector<double*> casadi::HpmpcMemory::Bs
Definition at line 78 of file hpmpc_interface.hpp.
bs
std::vector<double*> casadi::HpmpcMemory::bs
Definition at line 78 of file hpmpc_interface.hpp.
C
std::vector<double> casadi::HpmpcMemory::C
Definition at line 77 of file hpmpc_interface.hpp.
Cs
std::vector<double*> casadi::HpmpcMemory::Cs
Definition at line 78 of file hpmpc_interface.hpp.
D
std::vector<double> casadi::HpmpcMemory::D
Definition at line 77 of file hpmpc_interface.hpp.
d_qp
casadi_qp_data<double> casadi::ConicMemory::d_qp inherited
Definition at line 39 of file conic_impl.hpp.
Referenced by casadi::Conic::get_stats().
Ds
std::vector<double*> casadi::HpmpcMemory::Ds
Definition at line 78 of file hpmpc_interface.hpp.
fstats
std::map<std::string, FStats> casadi::ProtoFunctionMemory::fstats inherited
Definition at line 68 of file function_internal.hpp.
Referenced by casadi::Nlpsol::callback(), casadi::IpoptUserClass::eval_h(), casadi::BonminInterface::intermediate_callback(), casadi::IpoptInterface::intermediate_callback(), casadi::OracleFunction::join_results(), casadi::DaqpInterface::solve(), casadi::HighsInterface::solve(), casadi::HpipmInterface::solve(), casadi::HpmpcInterface::solve(), casadi::ProxqpInterface::solve(), casadi::QpoasesInterface::solve(), casadi::Sqpmethod::solve_ela_QP(), casadi::Feasiblesqpmethod::solve_LP(), casadi::Feasiblesqpmethod::solve_QP(), and casadi::Sqpmethod::solve_QP().
hidxb
std::vector<int> casadi::HpmpcMemory::hidxb
Definition at line 85 of file hpmpc_interface.hpp.
hidxbs
std::vector<int*> casadi::HpmpcMemory::hidxbs
Definition at line 86 of file hpmpc_interface.hpp.
I
std::vector<double> casadi::HpmpcMemory::I
Definition at line 80 of file hpmpc_interface.hpp.
Is
std::vector<double*> casadi::HpmpcMemory::Is
Definition at line 81 of file hpmpc_interface.hpp.
iter_count
int casadi::HpmpcMemory::iter_count
Definition at line 98 of file hpmpc_interface.hpp.
lam
std::vector<double> casadi::HpmpcMemory::lam
Definition at line 82 of file hpmpc_interface.hpp.
lams
std::vector<double*> casadi::HpmpcMemory::lams
Definition at line 83 of file hpmpc_interface.hpp.
lb
std::vector<double> casadi::HpmpcMemory::lb
Definition at line 77 of file hpmpc_interface.hpp.
lbs
std::vector<double*> casadi::HpmpcMemory::lbs
Definition at line 78 of file hpmpc_interface.hpp.
lg
std::vector<double> casadi::HpmpcMemory::lg
Definition at line 77 of file hpmpc_interface.hpp.
lgs
std::vector<double*> casadi::HpmpcMemory::lgs
Definition at line 78 of file hpmpc_interface.hpp.
nb
std::vector<int> casadi::HpmpcMemory::nb
Definition at line 91 of file hpmpc_interface.hpp.
ng
std::vector<int> casadi::HpmpcMemory::ng
Definition at line 90 of file hpmpc_interface.hpp.
nu
std::vector<int> casadi::HpmpcMemory::nu
Definition at line 89 of file hpmpc_interface.hpp.
nx
std::vector<int> casadi::HpmpcMemory::nx
Definition at line 88 of file hpmpc_interface.hpp.
pi
std::vector<double> casadi::HpmpcMemory::pi
Definition at line 82 of file hpmpc_interface.hpp.
pis
std::vector<double*> casadi::HpmpcMemory::pis
Definition at line 83 of file hpmpc_interface.hpp.
pv
std::vector<double> casadi::HpmpcMemory::pv
Definition at line 96 of file hpmpc_interface.hpp.
q
std::vector<double> casadi::HpmpcMemory::q
Definition at line 77 of file hpmpc_interface.hpp.
Q
std::vector<double> casadi::HpmpcMemory::Q
Definition at line 77 of file hpmpc_interface.hpp.
Qs
std::vector<double*> casadi::HpmpcMemory::Qs
Definition at line 78 of file hpmpc_interface.hpp.
qs
std::vector<double*> casadi::HpmpcMemory::qs
Definition at line 78 of file hpmpc_interface.hpp.
r
std::vector<double> casadi::HpmpcMemory::r
Definition at line 77 of file hpmpc_interface.hpp.
R
std::vector<double> casadi::HpmpcMemory::R
Definition at line 77 of file hpmpc_interface.hpp.
res
std::vector<double> casadi::HpmpcMemory::res
Definition at line 100 of file hpmpc_interface.hpp.
return_status
int casadi::HpmpcMemory::return_status
Definition at line 99 of file hpmpc_interface.hpp.
Referenced by casadi::HpmpcInterface::get_stats().
Rs
std::vector<double*> casadi::HpmpcMemory::Rs
Definition at line 78 of file hpmpc_interface.hpp.
rs
std::vector<double*> casadi::HpmpcMemory::rs
Definition at line 78 of file hpmpc_interface.hpp.
S
std::vector<double> casadi::HpmpcMemory::S
Definition at line 77 of file hpmpc_interface.hpp.
Ss
std::vector<double*> casadi::HpmpcMemory::Ss
Definition at line 78 of file hpmpc_interface.hpp.
stats
std::vector<double> casadi::HpmpcMemory::stats
Definition at line 92 of file hpmpc_interface.hpp.
t_total
FStats* casadi::ProtoFunctionMemory::t_total inherited
Definition at line 71 of file function_internal.hpp.
Referenced by casadi::LinsolCall< Tr >::eval(), and casadi::Linsol::solve().
u
std::vector<double> casadi::HpmpcMemory::u
Definition at line 82 of file hpmpc_interface.hpp.
ub
std::vector<double> casadi::HpmpcMemory::ub
Definition at line 77 of file hpmpc_interface.hpp.
ubs
std::vector<double*> casadi::HpmpcMemory::ubs
Definition at line 78 of file hpmpc_interface.hpp.
ug
std::vector<double> casadi::HpmpcMemory::ug
Definition at line 77 of file hpmpc_interface.hpp.
ugs
std::vector<double*> casadi::HpmpcMemory::ugs
Definition at line 78 of file hpmpc_interface.hpp.
us
std::vector<double*> casadi::HpmpcMemory::us
Definition at line 83 of file hpmpc_interface.hpp.
workspace
std::vector<char> casadi::HpmpcMemory::workspace
Definition at line 94 of file hpmpc_interface.hpp.
x
std::vector<double> casadi::HpmpcMemory::x
Definition at line 82 of file hpmpc_interface.hpp.
xs
std::vector<double*> casadi::HpmpcMemory::xs
Definition at line 83 of file hpmpc_interface.hpp.
The documentation for this struct was generated from the following files:
hpmpc_interface.hpp
hpmpc_interface.cpp