CasADi: casadi::GenericType Class Reference
casadi::GenericType Class Reference
Generic data type, can hold different types such as bool, casadi_int, std::string etc.
#include <generic_type.hpp>
Detailed Description
Author
Joel Andersson
Date
2010
Extra doc: https://github.com/casadi/casadi/wiki/L_17n
Definition at line 72 of file generic_type.hpp.
Public Types
typedef std::map< std::string, GenericType > Dict
C++ equivalent of Python's dict or MATLAB's struct.
Public Member Functions
GenericType ()
Default constructor.
GenericType (bool b)
Constructors (implicit type conversion)
GenericType (casadi_int i)
GenericType (int i)
GenericType (double d)
GenericType (const std::string &s)
GenericType (const std::vector< bool > &iv)
GenericType (const std::vector< casadi_int > &iv)
GenericType (const std::vector< int > &iv)
GenericType (const std::vector< std::vector< casadi_int > > &ivv)
GenericType (const std::vector< double > &dv)
GenericType (const std::vector< std::vector< double > > &dv)
GenericType (const std::vector< std::string > &sv)
GenericType (const std::vector< std::vector< std::string > > &sv)
GenericType (const char s[])
GenericType (const Function &f)
GenericType (const std::vector< Function > &f)
GenericType (const Dict &dict)
GenericType (const std::vector< Dict > &dictv)
GenericType (const std::vector< std::vector< GenericType > > &gvv)
GenericType (const std::vector< GenericType > &gv)
GenericType (void *ptr)
std::string get_description () const
Get a description of the object's type.
bool can_cast_to (TypeID other) const
bool can_cast_to (const GenericType &other) const
TypeID getType () const
bool operator== (const GenericType &op2) const
Equality.
bool operator!= (const GenericType &op2) const
void serialize (SerializingStream &s) const
Serialize an object.
void own (SharedObjectInternal *node)
void assign (SharedObjectInternal *node)
Assign the node to a node class pointer without reference counting.
SharedObjectInternal * get () const
Get a const pointer to the node.
casadi_int getCount () const
Get the reference count.
void swap (SharedObject &other)
Swap content with another instance.
SharedObjectInternal * operator-> () const
Access a member function or object.
std::string class_name () const
Get class name.
void disp (std::ostream &stream, bool more=false) const
Print a description of the object.
std::string get_str (bool more=false) const
Get string representation.
void print_ptr (std::ostream &stream=casadi::uout()) const
bool is_null () const
Is a null pointer?
casadi_int __hash__ () const
Returns a number that is unique for a given Node.
WeakRef * weak ()
Get a weak reference to the object.
operator bool () const
operator casadi_int () const
operator int () const
operator double () const
operator std::string () const
operator std::vector< bool > () const
operator std::vector< casadi_int > () const
operator std::vector< int > () const
operator std::vector< std::vector< casadi_int > > () const
operator std::vector< std::vector< int > > () const
operator std::vector< double > () const
operator std::vector< std::vector< double > > () const
operator std::vector< std::string > () const
operator std::vector< std::vector< std::string > > () const
operator const Function & () const
operator const std::vector< Function > & () const
operator const Dict & () const
operator const std::vector< Dict > & () const
operator const std::vector< std::vector< GenericType > > & () const
operator const std::vector< GenericType > & () const
bool is_bool () const
Check if a particular type.
bool is_int () const
Check if a particular type.
bool is_double () const
Check if a particular type.
bool is_string () const
Check if a particular type.
bool is_empty_vector () const
Check if a particular type.
bool is_int_vector () const
Check if a particular type.
bool is_int_vector_vector () const
Check if a particular type.
bool is_double_vector () const
Check if a particular type.
bool is_double_vector_vector () const
Check if a particular type.
bool is_bool_vector () const
Check if a particular type.
bool is_string_vector () const
Check if a particular type.
bool is_string_vector_vector () const
Check if a particular type.
bool is_dict () const
Check if a particular type.
bool is_dict_vector () const
Check if a particular type.
bool is_vector_vector () const
Check if a particular type.
bool is_vector () const
Check if a particular type.
bool is_function () const
Check if a particular type.
bool is_function_vector () const
Check if a particular type.
bool is_void_pointer () const
Check if a particular type.
const bool & as_bool () const
Cast to the internal type.
const casadi_int & as_int () const
Cast to the internal type.
const double & as_double () const
Cast to the internal type.
const std::string & as_string () const
Cast to the internal type.
const std::vector< casadi_int > & as_int_vector () const
Cast to the internal type.
const std::vector< casadi_int > & as_bool_vector () const
Cast to the internal type.
const std::vector< std::vector< casadi_int > > & as_int_vector_vector () const
Cast to the internal type.
const std::vector< double > & as_double_vector () const
Cast to the internal type.
const std::vector< std::vector< double > > & as_double_vector_vector () const
Cast to the internal type.
const std::vector< std::string > & as_string_vector () const
Cast to the internal type.
const std::vector< std::vector< std::string > > & as_string_vector_vector () const
Cast to the internal type.
const Dict & as_dict () const
Cast to the internal type.
const std::vector< Dict > & as_dict_vector () const
Cast to the internal type.
const std::vector< std::vector< GenericType > > & as_vector_vector () const
Cast to the internal type.
const std::vector< GenericType > & as_vector () const
Cast to the internal type.
const Function & as_function () const
Cast to the internal type.
const std::vector< Function > & as_function_vector () const
Cast to the internal type.
void *const & as_void_pointer () const
Cast to the internal type.
bool to_bool () const
Convert to a type.
casadi_int to_int () const
Convert to a type.
double to_double () const
Convert to a type.
std::string to_string () const
Convert to a type.
std::vector< casadi_int > to_int_vector () const
Convert to a type.
std::vector< bool > to_bool_vector () const
Convert to a type.
std::vector< std::vector< casadi_int > > to_int_vector_vector () const
Convert to a type.
std::vector< double > to_double_vector () const
Convert to a type.
std::vector< std::vector< double > > to_double_vector_vector () const
Convert to a type.
std::vector< std::string > to_string_vector () const
Convert to a type.
std::vector< std::vector< std::string > > to_string_vector_vector () const
Convert to a type.
Dict to_dict () const
Convert to a type.
std::vector< Dict > to_dict_vector () const
Convert to a type.
std::vector< GenericType > to_vector () const
Convert to a type.
std::vector< std::vector< GenericType > > to_vector_vector () const
Convert to a type.
Function to_function () const
Convert to a type.
std::vector< Function > to_function_vector () const
Convert to a type.
void * to_void_pointer () const
Convert to a type.
std::vector< int > to_int_type_vector () const
Convert to a type.
Static Public Member Functions
static std::string type_name ()
Public class name.
static std::string get_type_description (TypeID type)
Get a description of a type.
static GenericType create (SharedObjectInternal *node)
Create from node.
static GenericType from_type (TypeID type)
Construct a GenericType given an TypeID.
static GenericType deserialize (DeserializingStream &s)
Deserialize with type disambiguation.
Protected Member Functions
void count_up ()
void count_down ()
Member Typedef Documentation
Dict
typedef std::map<std::string, GenericType> casadi::GenericType::Dict
Definition at line 80 of file generic_type.hpp.
Constructor & Destructor Documentation
GenericType() [1/22]
casadi::GenericType::GenericType ()
Definition at line 249 of file generic_type.cpp.
{
   }
GenericType() [2/22]
casadi::GenericType::GenericType (bool b)
Definition at line 252 of file generic_type.cpp.
{
     own(new BoolType(b));
   }
References casadi::SharedObject::own().
GenericType() [3/22]
casadi::GenericType::GenericType (casadi_int i)
Definition at line 256 of file generic_type.cpp.
{
     own(new IntType(i));
   }
References casadi::SharedObject::own().
GenericType() [4/22]
casadi::GenericType::GenericType (int i) inline
Definition at line 90 of file generic_type.hpp.
 : GenericType(static_cast<casadi_int>(i)) {}
GenericType() [5/22]
casadi::GenericType::GenericType (double d)
Definition at line 260 of file generic_type.cpp.
{
     own(new DoubleType(d));
   }
References casadi::SharedObject::own().
GenericType() [6/22]
casadi::GenericType::GenericType (const std::string & s)
Definition at line 300 of file generic_type.cpp.
{
     own(new StringType(s));
   }
References casadi::SharedObject::own().
GenericType() [7/22]
casadi::GenericType::GenericType (const std::vector< bool > & iv)
Definition at line 278 of file generic_type.cpp.
{
     std::vector<casadi_int> i_vec(b_vec.size());
     std::copy(b_vec.begin(), b_vec.end(), i_vec.begin());
     own(new IntVectorType(i_vec));
   }
References casadi::SharedObject::own().
GenericType() [8/22]
casadi::GenericType::GenericType (const std::vector< casadi_int > & iv)
Definition at line 264 of file generic_type.cpp.
{
     own(new IntVectorType(iv));
   }
References casadi::SharedObject::own().
GenericType() [9/22]
casadi::GenericType::GenericType (const std::vector< int > & iv)
Definition at line 268 of file generic_type.cpp.
{
     std::vector<casadi_int> temp(iv.size());
     std::copy(iv.begin(), iv.end(), temp.begin());
     own(new IntVectorType(temp));
   }
References casadi::SharedObject::own().
GenericType() [10/22]
casadi::GenericType::GenericType (const std::vector< std::vector< casadi_int > > & ivv)
Definition at line 274 of file generic_type.cpp.
{
     own(new IntVectorVectorType(ivv));
   }
References casadi::SharedObject::own().
GenericType() [11/22]
casadi::GenericType::GenericType (const std::vector< double > & dv)
Definition at line 284 of file generic_type.cpp.
{
     own(new DoubleVectorType(dv));
   }
References casadi::SharedObject::own().
GenericType() [12/22]
casadi::GenericType::GenericType (const std::vector< std::vector< double > > & dv)
Definition at line 288 of file generic_type.cpp.
{
     own(new DoubleVectorVectorType(dv));
   }
References casadi::SharedObject::own().
GenericType() [13/22]
casadi::GenericType::GenericType (const std::vector< std::string > & sv)
Definition at line 292 of file generic_type.cpp.
{
     own(new StringVectorType(sv));
   }
References casadi::SharedObject::own().
GenericType() [14/22]
casadi::GenericType::GenericType (const std::vector< std::vector< std::string > > & sv)
Definition at line 296 of file generic_type.cpp.
{
     own(new StringVectorVectorType(sv));
   }
References casadi::SharedObject::own().
GenericType() [15/22]
casadi::GenericType::GenericType (const char s[])
Definition at line 304 of file generic_type.cpp.
{
     own(new StringType(s));
   }
References casadi::SharedObject::own().
GenericType() [16/22]
casadi::GenericType::GenericType (const Function & f)
Definition at line 308 of file generic_type.cpp.
{
     own(new FunctionType(f));
   }
References casadi::SharedObject::own().
GenericType() [17/22]
casadi::GenericType::GenericType (const std::vector< Function > & f)
Definition at line 312 of file generic_type.cpp.
{
     own(new FunctionVectorType(f));
   }
References casadi::SharedObject::own().
GenericType() [18/22]
casadi::GenericType::GenericType (const Dict & dict)
Definition at line 709 of file generic_type.cpp.
{
     own(new DictType(dict));
   }
References casadi::SharedObject::own().
GenericType() [19/22]
casadi::GenericType::GenericType (const std::vector< Dict > & dictv)
Definition at line 713 of file generic_type.cpp.
{
     own(new DictVectorType(dictv));
   }
References casadi::SharedObject::own().
GenericType() [20/22]
casadi::GenericType::GenericType (const std::vector< std::vector< GenericType > > & gvv)
Definition at line 721 of file generic_type.cpp.
{
     own(new VectorVectorType(gvv));
   }
References casadi::SharedObject::own().
GenericType() [21/22]
casadi::GenericType::GenericType (const std::vector< GenericType > & gv)
Definition at line 717 of file generic_type.cpp.
{
     own(new VectorType(gv));
   }
References casadi::SharedObject::own().
GenericType() [22/22]
casadi::GenericType::GenericType (void * ptr)
Definition at line 725 of file generic_type.cpp.
{
     own(new VoidPointerType(ptr));
   }
References casadi::SharedObject::own().
Member Function Documentation
__hash__()
casadi_int casadi::SharedObject::__hash__ () const inherited
If the Object does not point to any node, "0" is returned.
Extra doc: https://github.com/casadi/casadi/wiki/L_av
Definition at line 129 of file shared_object.cpp.
{
     return reinterpret_cast<casadi_int>(get());
   }
References casadi::SharedObject::get().
as_bool()
const bool & casadi::GenericType::as_bool () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17q
Definition at line 316 of file generic_type.cpp.
{
     casadi_assert_dev(is_bool());
     return static_cast<const BoolType*>(get())->d_;
   }
References casadi::SharedObject::get(), and is_bool().
Referenced by to_bool().
as_bool_vector()
const std::vector< casadi_int > & casadi::GenericType::as_bool_vector () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17q
Definition at line 341 of file generic_type.cpp.
{
     casadi_assert_dev(is_bool_vector());
     return static_cast<const IntVectorType*>(get())->d_;
   }
References casadi::SharedObject::get(), and is_bool_vector().
Referenced by to_vector().
as_dict()
const GenericType::Dict & casadi::GenericType::as_dict () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17q
Definition at line 371 of file generic_type.cpp.
{
     casadi_assert_dev(is_dict());
     return static_cast<const DictType*>(get())->d_;
   }
References casadi::SharedObject::get(), and is_dict().
Referenced by to_dict().
as_dict_vector()
const std::vector< GenericType::Dict > & casadi::GenericType::as_dict_vector () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17q
Definition at line 376 of file generic_type.cpp.
{
     casadi_assert_dev(is_dict_vector());
     return static_cast<const DictVectorType*>(get())->d_;
   }
References casadi::SharedObject::get(), and is_dict_vector().
Referenced by to_dict_vector(), and to_vector().
as_double()
const double & casadi::GenericType::as_double () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17q
Definition at line 326 of file generic_type.cpp.
{
     casadi_assert_dev(is_double());
     return static_cast<const DoubleType*>(get())->d_;
   }
References casadi::SharedObject::get(), and is_double().
Referenced by to_double().
as_double_vector()
const std::vector< double > & casadi::GenericType::as_double_vector () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17q
Definition at line 351 of file generic_type.cpp.
{
     casadi_assert_dev(is_double_vector());
     return static_cast<const DoubleVectorType*>(get())->d_;
   }
References casadi::SharedObject::get(), and is_double_vector().
Referenced by to_double_vector(), to_string_vector(), and to_vector().
as_double_vector_vector()
const std::vector< std::vector< double > > & casadi::GenericType::as_double_vector_vector () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17q
Definition at line 356 of file generic_type.cpp.
{
     casadi_assert_dev(is_double_vector_vector());
     return static_cast<const DoubleVectorVectorType*>(get())->d_;
   }
References casadi::SharedObject::get(), and is_double_vector_vector().
Referenced by to_double_vector_vector(), to_vector(), and to_vector_vector().
as_function()
const Function & casadi::GenericType::as_function () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17q
Definition at line 391 of file generic_type.cpp.
{
     casadi_assert_dev(is_function());
     return static_cast<const FunctionType*>(get())->d_;
   }
References casadi::SharedObject::get(), and is_function().
Referenced by to_function().
as_function_vector()
const std::vector< Function > & casadi::GenericType::as_function_vector () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17q
Definition at line 396 of file generic_type.cpp.
{
     casadi_assert_dev(is_function_vector());
     return static_cast<const FunctionVectorType*>(get())->d_;
   }
References casadi::SharedObject::get(), and is_function_vector().
Referenced by to_function_vector(), and to_vector().
as_int()
const casadi_int & casadi::GenericType::as_int () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17q
Definition at line 321 of file generic_type.cpp.
{
     casadi_assert_dev(is_int());
     return static_cast<const IntType*>(get())->d_;
   }
References casadi::SharedObject::get(), and is_int().
Referenced by to_int(), and to_void_pointer().
as_int_vector()
const std::vector< casadi_int > & casadi::GenericType::as_int_vector () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17q
Definition at line 336 of file generic_type.cpp.
{
     casadi_assert_dev(is_int_vector());
     return static_cast<const IntVectorType*>(get())->d_;
   }
References casadi::SharedObject::get(), and is_int_vector().
Referenced by to_double_vector(), to_int_type_vector(), to_int_vector(), to_string_vector(), and to_vector().
as_int_vector_vector()
const std::vector< std::vector< casadi_int > > & casadi::GenericType::as_int_vector_vector () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17q
Definition at line 346 of file generic_type.cpp.
{
     casadi_assert_dev(is_int_vector_vector());
     return static_cast<const IntVectorVectorType*>(get())->d_;
   }
References casadi::SharedObject::get(), and is_int_vector_vector().
Referenced by to_double_vector_vector(), to_int_vector_vector(), to_vector(), and to_vector_vector().
as_string()
const std::string & casadi::GenericType::as_string () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17q
Definition at line 331 of file generic_type.cpp.
{
     casadi_assert_dev(is_string());
     return static_cast<const StringType*>(get())->d_;
   }
References casadi::SharedObject::get(), and is_string().
Referenced by to_string(), and to_string_vector().
as_string_vector()
const std::vector< std::string > & casadi::GenericType::as_string_vector () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17q
Definition at line 361 of file generic_type.cpp.
{
     casadi_assert_dev(is_string_vector());
     return static_cast<const StringVectorType*>(get())->d_;
   }
References casadi::SharedObject::get(), and is_string_vector().
Referenced by to_string_vector(), and to_vector().
as_string_vector_vector()
const std::vector< std::vector< std::string > > & casadi::GenericType::as_string_vector_vector () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17q
Definition at line 366 of file generic_type.cpp.
{
     casadi_assert_dev(is_string_vector_vector());
     return static_cast<const StringVectorVectorType*>(get())->d_;
   }
References casadi::SharedObject::get(), and is_string_vector_vector().
Referenced by to_string_vector_vector(), to_vector(), and to_vector_vector().
as_vector()
const std::vector< GenericType > & casadi::GenericType::as_vector () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17q
Definition at line 386 of file generic_type.cpp.
{
     casadi_assert_dev(is_vector());
     return static_cast<const VectorType*>(get())->d_;
   }
References casadi::SharedObject::get(), and is_vector().
Referenced by to_vector().
as_vector_vector()
const std::vector< std::vector< GenericType > > & casadi::GenericType::as_vector_vector () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17q
Definition at line 381 of file generic_type.cpp.
{
     casadi_assert_dev(is_vector_vector());
     return static_cast<const VectorVectorType*>(get())->d_;
   }
References casadi::SharedObject::get(), and is_vector_vector().
Referenced by to_vector(), and to_vector_vector().
as_void_pointer()
void *const & casadi::GenericType::as_void_pointer () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17q
Definition at line 401 of file generic_type.cpp.
{
     casadi_assert_dev(is_void_pointer());
     return static_cast<const VoidPointerType*>(get())->d_;
   }
References casadi::SharedObject::get(), and is_void_pointer().
Referenced by to_void_pointer().
assign()
void casadi::SharedObject::assign (SharedObjectInternal * node) inherited
improper use will cause memory leaks!
Extra doc: https://github.com/casadi/casadi/wiki/L_at
Definition at line 52 of file shared_object.cpp.
{
     node = node_;
   }
Referenced by to_double_vector_vector().
can_cast_to() [1/2]
bool casadi::GenericType::can_cast_to (const GenericType & other) const inline
Definition at line 161 of file generic_type.hpp.
 { return can_cast_to(other.getType()) ;}
References can_cast_to(), and getType().
Referenced by can_cast_to().
can_cast_to() [2/2]
bool casadi::GenericType::can_cast_to (TypeID other) const
Definition at line 60 of file generic_type.cpp.
{
     switch (other) {
     case OT_BOOL:
       return is_bool() || is_int() || is_double();
     case OT_BOOLVECTOR:
       return is_int_vector() || is_double_vector();
     case OT_INT:
     case OT_DOUBLE:
       return is_int() || is_double();
     case OT_INTVECTOR:
     case OT_DOUBLEVECTOR:
       return is_double_vector() || is_int_vector();
     case OT_INTVECTORVECTOR:
     case OT_DOUBLEVECTORVECTOR:
       return is_double_vector_vector() || is_int_vector_vector();
     case OT_STRINGVECTOR:
       return is_string_vector() || is_string() || is_double_vector() || is_int_vector();
     case OT_VECTOR:
       return is_vector() || is_double_vector() || is_int_vector() || is_string_vector() ||
              is_function_vector() ||
              is_int_vector_vector() || is_double_vector_vector() || is_string_vector_vector() ||
              is_bool_vector() || is_dict_vector();
     case OT_VECTORVECTOR:
       return is_vector_vector() ||
              is_int_vector_vector() || is_double_vector_vector() || is_string_vector_vector();
     case OT_VOIDPTR:
       return is_void_pointer() || is_int();
     default:
       return getType() == other;
     }
   }
References getType(), is_bool(), is_bool_vector(), is_dict_vector(), is_double(), is_double_vector(), is_double_vector_vector(), is_function_vector(), is_int(), is_int_vector(), is_int_vector_vector(), is_string(), is_string_vector(), is_string_vector_vector(), is_vector(), is_vector_vector(), is_void_pointer(), casadi::OT_BOOL, casadi::OT_BOOLVECTOR, casadi::OT_DOUBLE, casadi::OT_DOUBLEVECTOR, casadi::OT_DOUBLEVECTORVECTOR, casadi::OT_INT, casadi::OT_INTVECTOR, casadi::OT_INTVECTORVECTOR, casadi::OT_STRINGVECTOR, casadi::OT_VECTOR, casadi::OT_VECTORVECTOR, and casadi::OT_VOIDPTR.
class_name()
std::string casadi::SharedObject::class_name () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_au
Definition at line 99 of file shared_object.cpp.
{
     return (*this)->class_name();
   }
Referenced by casadi::MXFunction::export_code_body().
count_down()
void casadi::SharedObject::count_down () protected inherited
Definition at line 84 of file shared_object.cpp.
{
 #ifdef WITH_EXTRA_CHECKS
     casadi_assert_dev(Function::call_depth_==0);
 #endif // WITH_EXTRA_CHECKS
     if (node && --node->count == 0) {
       delete node;
       node = nullptr;
     }
   }
Referenced by casadi::SharedObject::operator=(), casadi::SharedObject::own(), and casadi::SharedObject::~SharedObject().
count_up()
void casadi::SharedObject::count_up () protected inherited
Definition at line 77 of file shared_object.cpp.
{
 #ifdef WITH_EXTRA_CHECKS
     casadi_assert_dev(Function::call_depth_==0);
 #endif // WITH_EXTRA_CHECKS
     if (node) node->count++;
   }
Referenced by casadi::SharedObject::operator=(), casadi::SharedObject::own(), and casadi::SharedObject::SharedObject().
create()
GenericType casadi::GenericType::create (SharedObjectInternal * node) static
Extra doc: https://github.com/casadi/casadi/wiki/L_17o
Definition at line 784 of file generic_type.cpp.
{
     GenericType ret;
     ret.own(node);
     return ret;
   }
References casadi::SharedObject::own().
deserialize()
GenericType casadi::GenericType::deserialize (DeserializingStream & s) static
Extra doc: https://github.com/casadi/casadi/wiki/L_17s
Definition at line 742 of file generic_type.cpp.
{
     int itype;
     s.unpack("GenericType::type", itype);
     TypeID type = static_cast<TypeID>(itype);
     switch (type) {
       case OT_STRING:
         return StringType::deserialize(s);
       case OT_DOUBLE:
         return DoubleType::deserialize(s);
       case OT_INT:
         return IntType::deserialize(s);
       case OT_BOOL:
         return BoolType::deserialize(s);
       case OT_DOUBLEVECTOR:
         return DoubleVectorType::deserialize(s);
       case OT_DOUBLEVECTORVECTOR:
         return DoubleVectorVectorType::deserialize(s);
       case OT_INTVECTOR:
         return IntVectorType::deserialize(s);
       case OT_INTVECTORVECTOR:
         return IntVectorVectorType::deserialize(s);
       case OT_STRINGVECTOR:
         return StringVectorType::deserialize(s);
       case OT_STRINGVECTORVECTOR:
         return StringVectorVectorType::deserialize(s);
       case OT_FUNCTION:
         return FunctionType::deserialize(s);
       case OT_FUNCTIONVECTOR:
         return FunctionVectorType::deserialize(s);
       case OT_DICT:
         return DictType::deserialize(s);
       case OT_DICTVECTOR:
         return VectorType::deserialize(s);
       case OT_VECTOR:
         return VectorType::deserialize(s);
       case OT_VECTORVECTOR:
         return VectorVectorType::deserialize(s);
       default:
         casadi_error("Not implemented: " + get_type_description(type));
     }
   }
References casadi::GenericTypeInternal< ID, T >::deserialize(), get_type_description(), casadi::OT_BOOL, casadi::OT_DICT, casadi::OT_DICTVECTOR, casadi::OT_DOUBLE, casadi::OT_DOUBLEVECTOR, casadi::OT_DOUBLEVECTORVECTOR, casadi::OT_FUNCTION, casadi::OT_FUNCTIONVECTOR, casadi::OT_INT, casadi::OT_INTVECTOR, casadi::OT_INTVECTORVECTOR, casadi::OT_STRING, casadi::OT_STRINGVECTOR, casadi::OT_STRINGVECTORVECTOR, casadi::OT_VECTOR, casadi::OT_VECTORVECTOR, and casadi::DeserializingStream::unpack().
disp()
void casadi::SharedObject::disp (std::ostream & stream, bool more = false) const inherited
Definition at line 103 of file shared_object.cpp.
{
     if (is_null()) {
       stream << "NULL";
     } else {
       (*this)->disp(stream, more);
     }
   }
References casadi::SharedObject::is_null().
Referenced by casadi::Nlpsol::disp_more(), and casadi::CsparseInterface::nfact().
from_type()
GenericType casadi::GenericType::from_type (TypeID type) static
Definition at line 92 of file generic_type.cpp.
{
     switch (type) {
     case OT_INTVECTOR:
       return std::vector<casadi_int>();
     case OT_INTVECTORVECTOR:
       return std::vector< std::vector<casadi_int> >();
     case OT_BOOLVECTOR:
       return std::vector<bool>();
     case OT_DOUBLEVECTOR:
       return std::vector<double>();
     case OT_DOUBLEVECTORVECTOR:
       return std::vector< std::vector<double> >();
     case OT_STRINGVECTOR:
       return std::vector<std::string>();
     case OT_STRINGVECTORVECTOR:
       return std::vector<std::vector<std::string> >();
     case OT_DICTVECTOR:
       return std::vector<GenericType::Dict>();
     case OT_VECTORVECTOR:
       return std::vector<std::vector< GenericType> >();
     case OT_VECTOR:
       return std::vector<GenericType>();
     default:
       casadi_error("empty_from_type. Unsupported type " + str(type));
     }
   }
References casadi::OT_BOOLVECTOR, casadi::OT_DICTVECTOR, casadi::OT_DOUBLEVECTOR, casadi::OT_DOUBLEVECTORVECTOR, casadi::OT_INTVECTOR, casadi::OT_INTVECTORVECTOR, casadi::OT_STRINGVECTOR, casadi::OT_STRINGVECTORVECTOR, casadi::OT_VECTOR, casadi::OT_VECTORVECTOR, and casadi::str().
get()
SharedObjectInternal * casadi::SharedObject::get () const inherited
Definition at line 69 of file shared_object.cpp.
{
     return node;
   }
Referenced by casadi::SharedObject::__hash__(), as_bool(), as_bool_vector(), as_dict(), as_dict_vector(), as_double(), as_double_vector(), as_double_vector_vector(), as_function(), as_function_vector(), as_int(), as_int_vector(), as_int_vector_vector(), as_string(), as_string_vector(), as_string_vector_vector(), as_vector(), as_vector_vector(), as_void_pointer(), casadi::Fmu::get(), casadi::Function::get(), casadi::MX::get(), casadi::Sparsity::get(), casadi::DaeBuilder::get(), getType(), and serialize().
get_description()
std::string casadi::GenericType::get_description () const inline
Definition at line 128 of file generic_type.hpp.
 { return get_type_description(getType()); }
get_str()
std::string casadi::SharedObject::get_str (bool more = false) const inline inherited
Definition at line 138 of file shared_object.hpp.
{
       std::stringstream ss;
       disp(ss, more);
       return ss.str();
     }
get_type_description()
std::string casadi::GenericType::get_type_description (TypeID type) static
Definition at line 119 of file generic_type.cpp.
{
     switch (type) {
     case OT_BOOL:
       return "OT_BOOL";
     case OT_INT:
       return "OT_INT";
     case OT_DOUBLE:
       return "OT_DOUBLE";
     case OT_STRING:
       return "OT_STRING";
     case OT_INTVECTOR:
       return "OT_INTVECTOR";
     case OT_INTVECTORVECTOR:
       return "OT_INTVECTORVECTOR";
     case OT_BOOLVECTOR:
       return "OT_BOOLVECTOR";
     case OT_DOUBLEVECTOR:
       return "OT_DOUBLEVECTOR";
     case OT_DOUBLEVECTORVECTOR:
       return "OT_DOUBLEVECTORVECTOR";
     case OT_STRINGVECTOR:
       return "OT_STRINGVECTOR";
     case OT_STRINGVECTORVECTOR:
       return "OT_STRINGVECTORVECTOR";
     case OT_DICT:
       return "OT_DICT";
     case OT_DICTVECTOR:
       return "OT_DICTVECTOR";
     case OT_VECTORVECTOR:
       return "OT_VECTORVECTOR";
     case OT_VECTOR:
       return "OT_VECTOR";
     case OT_FUNCTION:
       return "OT_FUNCTION";
     case OT_FUNCTIONVECTOR:
       return "OT_FUNCTIONVECTOR";
     case OT_VOIDPTR:
       return "OT_VOIDPTR";
     default:
       return "OT_UNKNOWN";
     }
   }
References casadi::OT_BOOL, casadi::OT_BOOLVECTOR, casadi::OT_DICT, casadi::OT_DICTVECTOR, casadi::OT_DOUBLE, casadi::OT_DOUBLEVECTOR, casadi::OT_DOUBLEVECTORVECTOR, casadi::OT_FUNCTION, casadi::OT_FUNCTIONVECTOR, casadi::OT_INT, casadi::OT_INTVECTOR, casadi::OT_INTVECTORVECTOR, casadi::OT_STRING, casadi::OT_STRINGVECTOR, casadi::OT_STRINGVECTORVECTOR, casadi::OT_VECTOR, casadi::OT_VECTORVECTOR, and casadi::OT_VOIDPTR.
Referenced by casadi::Options::check(), deserialize(), casadi::Options::Entry::disp(), and casadi::Options::type().
getCount()
casadi_int casadi::SharedObject::getCount () const inherited
Definition at line 121 of file shared_object.cpp.
{
     return (*this)->getCount();
   }
Referenced by casadi::MXNode::~MXNode().
getType()
TypeID casadi::GenericType::getType () const
Definition at line 729 of file generic_type.cpp.
{
     if (is_null()) {
       return OT_NULL;
     } else {
       return static_cast<const GenericTypeBase*>(get())->getType();
     }
   }
References casadi::SharedObject::get(), casadi::SharedObject::is_null(), and casadi::OT_NULL.
Referenced by can_cast_to(), is_bool(), is_bool_vector(), is_dict(), is_dict_vector(), is_double(), is_double_vector(), is_double_vector_vector(), is_function(), is_function_vector(), is_int(), is_int_vector(), is_int_vector_vector(), is_string(), is_string_vector(), is_string_vector_vector(), is_vector(), is_vector_vector(), is_void_pointer(), and serialize().
is_bool()
bool casadi::GenericType::is_bool () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17p
Definition at line 164 of file generic_type.cpp.
{
     return getType()==OT_BOOL;
   }
References getType(), and casadi::OT_BOOL.
Referenced by as_bool(), can_cast_to(), to_bool(), and to_int().
is_bool_vector()
bool casadi::GenericType::is_bool_vector () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17p
Definition at line 197 of file generic_type.cpp.
{
     return getType()==OT_BOOLVECTOR;
   }
References getType(), and casadi::OT_BOOLVECTOR.
Referenced by as_bool_vector(), can_cast_to(), is_empty_vector(), and to_vector().
is_dict()
bool casadi::GenericType::is_dict () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17p
Definition at line 233 of file generic_type.cpp.
{
     return getType()==OT_DICT;
   }
References getType(), and casadi::OT_DICT.
Referenced by as_dict(), and to_dict().
is_dict_vector()
bool casadi::GenericType::is_dict_vector () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17p
Definition at line 237 of file generic_type.cpp.
{
     return getType()==OT_DICTVECTOR;
   }
References getType(), and casadi::OT_DICTVECTOR.
Referenced by as_dict_vector(), can_cast_to(), is_empty_vector(), to_dict_vector(), and to_vector().
is_double()
bool casadi::GenericType::is_double () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17p
Definition at line 172 of file generic_type.cpp.
{
     return getType()==OT_DOUBLE;
   }
References getType(), and casadi::OT_DOUBLE.
Referenced by as_double(), can_cast_to(), operator!=(), to_double(), and to_int().
is_double_vector()
bool casadi::GenericType::is_double_vector () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17p
Definition at line 205 of file generic_type.cpp.
{
     return getType()==OT_DOUBLEVECTOR;
   }
References getType(), and casadi::OT_DOUBLEVECTOR.
Referenced by as_double_vector(), can_cast_to(), is_empty_vector(), operator!=(), to_double_vector(), to_string_vector(), and to_vector().
is_double_vector_vector()
bool casadi::GenericType::is_double_vector_vector () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17p
Definition at line 209 of file generic_type.cpp.
{
     return getType()==OT_DOUBLEVECTORVECTOR;
   }
References getType(), and casadi::OT_DOUBLEVECTORVECTOR.
Referenced by as_double_vector_vector(), can_cast_to(), is_empty_vector(), operator!=(), to_double_vector_vector(), to_vector(), and to_vector_vector().
is_empty_vector()
bool casadi::GenericType::is_empty_vector () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17p
Definition at line 180 of file generic_type.cpp.
{
     return (is_int_vector() && to_int_vector().empty()) ||
       (is_int_vector_vector() && to_int_vector_vector().empty()) ||
       (is_double_vector_vector() && to_double_vector_vector().empty()) ||
       (is_double_vector() && to_double_vector().empty()) ||
       (is_string_vector() && to_string_vector().empty()) ||
       (is_string_vector_vector() && to_string_vector_vector().empty()) ||
       (is_bool_vector() && to_bool_vector().empty()) ||
       (is_dict_vector() && to_dict_vector().empty()) ||
       (is_vector_vector() && to_vector_vector().empty()) ||
       (is_vector() && to_vector().empty());
   }
References is_bool_vector(), is_dict_vector(), is_double_vector(), is_double_vector_vector(), is_int_vector(), is_int_vector_vector(), is_string_vector(), is_string_vector_vector(), is_vector(), is_vector_vector(), to_bool_vector(), to_dict_vector(), to_double_vector(), to_double_vector_vector(), to_int_vector(), to_int_vector_vector(), to_string_vector(), to_string_vector_vector(), to_vector(), and to_vector_vector().
is_function()
bool casadi::GenericType::is_function () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17p
Definition at line 221 of file generic_type.cpp.
{
     return getType()==OT_FUNCTION;
   }
References getType(), and casadi::OT_FUNCTION.
Referenced by as_function(), and to_function().
is_function_vector()
bool casadi::GenericType::is_function_vector () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17p
Definition at line 225 of file generic_type.cpp.
{
     return getType()==OT_FUNCTIONVECTOR;
   }
References getType(), and casadi::OT_FUNCTIONVECTOR.
Referenced by as_function_vector(), can_cast_to(), to_function_vector(), and to_vector().
is_int()
bool casadi::GenericType::is_int () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17p
Definition at line 168 of file generic_type.cpp.
{
     return getType()==OT_INT;
   }
References getType(), and casadi::OT_INT.
Referenced by as_int(), can_cast_to(), operator!=(), to_bool(), to_double(), and to_int().
is_int_vector()
bool casadi::GenericType::is_int_vector () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17p
Definition at line 193 of file generic_type.cpp.
{
     return getType()==OT_INTVECTOR;
   }
References getType(), and casadi::OT_INTVECTOR.
Referenced by as_int_vector(), can_cast_to(), is_empty_vector(), operator!=(), to_bool_vector(), to_double_vector(), to_int_type_vector(), to_int_vector(), to_string_vector(), and to_vector().
is_int_vector_vector()
bool casadi::GenericType::is_int_vector_vector () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17p
Definition at line 201 of file generic_type.cpp.
{
     return getType()==OT_INTVECTORVECTOR;
   }
References getType(), and casadi::OT_INTVECTORVECTOR.
Referenced by as_int_vector_vector(), can_cast_to(), is_empty_vector(), operator!=(), to_double_vector_vector(), to_int_vector_vector(), to_vector(), and to_vector_vector().
is_null()
bool casadi::SharedObject::is_null () const inherited
Definition at line 73 of file shared_object.cpp.
{
     return node==nullptr;
   }
Referenced by casadi::FunctionInternal::add_embedded(), casadi::WeakRef::alive(), casadi::FunctionInternal::alloc(), casadi::Nlpsol::callback(), casadi::DaeBuilderInternal::clear_cache(), casadi::Switch::codegen_body(), casadi::Conic::Conic(), casadi::conic_debug(), casadi::Callback::construct(), casadi::Function::deserialize(), casadi::SharedObject::disp(), casadi::FunctionInternal::finalize(), casadi::Switch::find(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::get_n_in(), casadi::Switch::get_n_in(), casadi::FunctionInternal::get_n_out(), casadi::Switch::get_n_out(), casadi::FunctionInternal::get_name_in(), casadi::FunctionInternal::get_name_out(), casadi::FunctionInternal::get_partition(), casadi::FunctionInternal::get_sparsity_in(), casadi::Switch::get_sparsity_in(), casadi::FunctionInternal::get_sparsity_out(), casadi::Switch::get_sparsity_out(), casadi::MXFunction::get_stats(), getType(), casadi::Sparsity::info(), casadi::Nlpsol::init(), casadi::Rootfinder::init(), casadi::Switch::init(), casadi::SLEQPInterface::init(), casadi::SnoptInterface::init(), casadi::SundialsInterface::init(), casadi::FastNewton::init(), casadi::Newton::init(), casadi::Scpgen::init(), casadi::BonminInterface::intermediate_callback(), casadi::IpoptInterface::intermediate_callback(), casadi::XFunction< DerivedType, MatType, NodeType >::jac(), casadi::FunctionInternal::jac_is_symm(), casadi::FunctionInternal::jac_sparsity(), casadi::OracleFunction::jit_dependencies(), casadi::SparsityInternal::maxtrans(), casadi::Fmu::name(), casadi::Function::name(), casadi::Function::operator->(), casadi::SharedObject::operator->(), casadi::Function::operator==(), casadi::DaeBuilderInternal::oracle(), casadi::Function::serialize(), casadi::Sparsity::serialize(), casadi::SLEQPInterface::set_work(), casadi::SnoptInterface::set_work(), casadi::OptiNode::solve(), casadi::KnitroInterface::solve(), casadi::SLEQPInterface::solve(), casadi::WorhpInterface::solve(), casadi::FunctionInternal::sp_forward_block(), casadi::FunctionInternal::sp_reverse(), casadi::Sparsity::uni_coloring(), and casadi::Callback::~Callback().
is_string()
bool casadi::GenericType::is_string () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17p
Definition at line 176 of file generic_type.cpp.
{
     return getType()==OT_STRING;
   }
References getType(), and casadi::OT_STRING.
Referenced by as_string(), can_cast_to(), operator!=(), to_string(), and to_string_vector().
is_string_vector()
bool casadi::GenericType::is_string_vector () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17p
Definition at line 213 of file generic_type.cpp.
{
     return getType()==OT_STRINGVECTOR;
   }
References getType(), and casadi::OT_STRINGVECTOR.
Referenced by as_string_vector(), can_cast_to(), is_empty_vector(), to_string_vector(), and to_vector().
is_string_vector_vector()
bool casadi::GenericType::is_string_vector_vector () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17p
Definition at line 217 of file generic_type.cpp.
{
     return getType()==OT_STRINGVECTORVECTOR;
   }
References getType(), and casadi::OT_STRINGVECTORVECTOR.
Referenced by as_string_vector_vector(), can_cast_to(), is_empty_vector(), to_string_vector_vector(), to_vector(), and to_vector_vector().
is_vector()
bool casadi::GenericType::is_vector () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17p
Definition at line 245 of file generic_type.cpp.
{
     return getType()==OT_VECTOR;
   }
References getType(), and casadi::OT_VECTOR.
Referenced by as_vector(), can_cast_to(), is_empty_vector(), and to_vector().
is_vector_vector()
bool casadi::GenericType::is_vector_vector () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17p
Definition at line 241 of file generic_type.cpp.
{
     return getType()==OT_VECTORVECTOR;
   }
References getType(), and casadi::OT_VECTORVECTOR.
Referenced by as_vector_vector(), can_cast_to(), is_empty_vector(), to_vector(), and to_vector_vector().
is_void_pointer()
bool casadi::GenericType::is_void_pointer () const
Extra doc: https://github.com/casadi/casadi/wiki/L_17p
Definition at line 229 of file generic_type.cpp.
{
     return getType()==OT_VOIDPTR;
   }
References getType(), and casadi::OT_VOIDPTR.
Referenced by as_void_pointer(), can_cast_to(), and to_void_pointer().
operator bool()
casadi::GenericType::operator bool () const inline
Implicit typecasting
Definition at line 136 of file generic_type.hpp.
 { return to_bool();}
operator casadi_int()
casadi::GenericType::operator casadi_int () const inline
Implicit typecasting
Definition at line 137 of file generic_type.hpp.
 { return to_int();}
References casadi::to_int().
operator const Dict &()
casadi::GenericType::operator const Dict & () const inline
Implicit typecasting
Definition at line 154 of file generic_type.hpp.
 { return as_dict();}
operator const Function &()
casadi::GenericType::operator const Function & () const inline
Implicit typecasting
Definition at line 152 of file generic_type.hpp.
 { return as_function();}
operator const std::vector< Dict > &()
casadi::GenericType::operator const std::vector< Dict > & () const inline
Implicit typecasting
Definition at line 155 of file generic_type.hpp.
 { return as_dict_vector();}
operator const std::vector< Function > &()
casadi::GenericType::operator const std::vector< Function > & () const inline
Implicit typecasting
Definition at line 153 of file generic_type.hpp.
 { return as_function_vector();}
operator const std::vector< GenericType > &()
casadi::GenericType::operator const std::vector< GenericType > & () const inline
Implicit typecasting
Definition at line 157 of file generic_type.hpp.
 { return as_vector();}
operator const std::vector< std::vector< GenericType > > &()
casadi::GenericType::operator const std::vector< std::vector< GenericType > > & () const inline
Implicit typecasting
Definition at line 156 of file generic_type.hpp.
 { return as_vector_vector();}
operator double()
casadi::GenericType::operator double () const inline
Implicit typecasting
Definition at line 139 of file generic_type.hpp.
 { return to_double();}
operator int()
casadi::GenericType::operator int () const inline
Implicit typecasting
Definition at line 138 of file generic_type.hpp.
 { return to_int();}
References casadi::to_int().
operator std::string()
casadi::GenericType::operator std::string () const inline
Implicit typecasting
Definition at line 140 of file generic_type.hpp.
 { return to_string();}
References casadi::to_string().
operator std::vector< bool >()
casadi::GenericType::operator std::vector< bool > () const inline
Implicit typecasting
Definition at line 141 of file generic_type.hpp.
 { return to_bool_vector();}
operator std::vector< casadi_int >()
casadi::GenericType::operator std::vector< casadi_int > () const inline
Implicit typecasting
Definition at line 142 of file generic_type.hpp.
 { return to_int_vector();}
operator std::vector< double >()
casadi::GenericType::operator std::vector< double > () const inline
Implicit typecasting
Definition at line 146 of file generic_type.hpp.
 { return to_double_vector();}
operator std::vector< int >()
casadi::GenericType::operator std::vector< int > () const
Implicit typecasting
Definition at line 452 of file generic_type.cpp.
{
     std::vector<int> ret;
     std::vector<casadi_int> source = to_int_vector();
     return casadi::to_int(source);
   }
References casadi::to_int().
operator std::vector< std::string >()
casadi::GenericType::operator std::vector< std::string > () const inline
Implicit typecasting
Definition at line 150 of file generic_type.hpp.
 { return to_string_vector();}
operator std::vector< std::vector< casadi_int > >()
casadi::GenericType::operator std::vector< std::vector< casadi_int > > () const inline
Implicit typecasting
Definition at line 144 of file generic_type.hpp.
 { return to_int_vector_vector();}
operator std::vector< std::vector< double > >()
casadi::GenericType::operator std::vector< std::vector< double > > () const inline
Implicit typecasting
Definition at line 147 of file generic_type.hpp.
{
       return to_double_vector_vector();
     }
operator std::vector< std::vector< int > >()
casadi::GenericType::operator std::vector< std::vector< int > > () const
Implicit typecasting
operator std::vector< std::vector< std::string > >()
casadi::GenericType::operator std::vector< std::vector< std::string > > () const inline
Implicit typecasting
Definition at line 151 of file generic_type.hpp.
 { return to_string_vector_vector();}
operator!=()
bool casadi::GenericType::operator!= (const GenericType & op2) const
Definition at line 648 of file generic_type.cpp.
{
     if (is_string() && op2.is_string()) {
       return to_string() != op2.to_string();
     }
     if (is_int() && op2.is_int()) {
       return to_int() != op2.to_int();
     }
     if (is_double() && op2.is_double()) {
       return to_double() != op2.to_double();
     }
     if (is_double_vector() && op2.is_double_vector()) {
       const std::vector<double> &v1 = to_double_vector();
       const std::vector<double> &v2 = op2.to_double_vector();
       if (v1.size() != v2.size()) return true;
       for (casadi_int i=0; i<v1.size(); ++i)
         if (v1[i] != v2[i]) return true;
       return false;
     }
     if (is_int_vector() && op2.is_int_vector()) {
       const std::vector<casadi_int> &v1 = to_int_vector();
       const std::vector<casadi_int> &v2 = op2.to_int_vector();
       if (v1.size() != v2.size()) return true;
       for (casadi_int i=0; i<v1.size(); ++i)
         if (v1[i] != v2[i]) return true;
       return false;
     }
     if (is_int_vector_vector() && op2.is_int_vector_vector()) {
       const std::vector< std::vector<casadi_int> > &v1 = to_int_vector_vector();
       const std::vector< std::vector<casadi_int> > &v2 = op2.to_int_vector_vector();
       if (v1.size() != v2.size()) return true;
       for (casadi_int i=0; i<v1.size(); ++i) {
         if (v1[i].size() != v2[i].size()) return true;
         for (casadi_int j=0; j<v1[i].size(); ++j) {
           if (v1[i][j] != v2[i][j]) return true;
         }
       }
       return false;
     }
     if (is_double_vector_vector() && op2.is_double_vector_vector()) {
       const std::vector< std::vector<double> > &v1 = to_double_vector_vector();
       const std::vector< std::vector<double> > &v2 = op2.to_double_vector_vector();
       if (v1.size() != v2.size()) return true;
       for (casadi_int i=0; i<v1.size(); ++i) {
         if (v1[i].size() != v2[i].size()) return true;
         for (casadi_int j=0; j<v1[i].size(); ++j) {
           if (v1[i][j] != v2[i][j]) return true;
         }
       }
       return false;
     }
     // Different types
     return true;
   }
References is_double(), is_double_vector(), is_double_vector_vector(), is_int(), is_int_vector(), is_int_vector_vector(), is_string(), to_double(), to_double_vector(), to_double_vector_vector(), to_int(), to_int_vector(), to_int_vector_vector(), and to_string().
operator->()
SharedObjectInternal * casadi::SharedObject::operator-> () const inherited
Definition at line 94 of file shared_object.cpp.
{
     casadi_assert_dev(!is_null());
     return node;
   }
References casadi::SharedObject::is_null().
Referenced by casadi::DaeBuilder::operator->(), casadi::Fmu::operator->(), casadi::Importer::operator->(), casadi::Linsol::operator->(), casadi::MX::operator->(), casadi::Opti::operator->(), casadi::WeakRef::operator->(), casadi::Sparsity::operator->(), and casadi::XmlFile::operator->().
operator==()
bool casadi::GenericType::operator== (const GenericType & op2) const
Definition at line 644 of file generic_type.cpp.
{
     return !(*this != op2);
   }
own()
void casadi::SharedObject::own (SharedObjectInternal * node) inherited
Assign the node to a node class pointer (or null)
Definition at line 46 of file shared_object.cpp.
{
     count_down();
     node = node_;
     count_up();
   }
References casadi::SharedObject::count_down(), and casadi::SharedObject::count_up().
Referenced by casadi::Callback::construct(), casadi::Function::construct(), casadi::Fmu::create(), casadi::Function::create(), casadi::Importer::create(), casadi::Linsol::create(), create(), casadi::Sparsity::create(), casadi::DaeBuilder::DaeBuilder(), casadi::FunctionInternal::deserialize(), casadi::Linsol::deserialize(), casadi::FmuFunction::factory(), casadi::Fmu::Fmu(), GenericType(), casadi::FmuFunction::get_forward(), casadi::FmuFunction::get_jacobian(), casadi::LinearInterpolant::get_jacobian(), casadi::FmuFunction::get_reverse(), casadi::Importer::Importer(), casadi::MXFunction::init(), casadi::Linsol::Linsol(), casadi::MX::MX(), casadi::Opti::Opti(), casadi::WeakRef::shared(), casadi::WeakRef::WeakRef(), and casadi::XmlFile::XmlFile().
print_ptr()
void casadi::SharedObject::print_ptr (std::ostream & stream = casadi::uout()) const inherited
Print the pointer to the internal class
Definition at line 111 of file shared_object.cpp.
{
     stream << node;
   }
serialize()
void casadi::GenericType::serialize (SerializingStream & s) const
Extra doc: https://github.com/casadi/casadi/wiki/L_17r
Definition at line 737 of file generic_type.cpp.
{
     s.pack("GenericType::type", static_cast<int>(getType()));
     static_cast<const GenericTypeBase*>(get())->serialize(s);
   }
References casadi::SharedObject::get(), getType(), and casadi::SerializingStream::pack().
swap()
void casadi::SharedObject::swap (SharedObject & other) inherited
Definition at line 115 of file shared_object.cpp.
{
     SharedObject temp = *this;
     *this = other;
     other = temp;
   }
to_bool()
bool casadi::GenericType::to_bool () const
Definition at line 406 of file generic_type.cpp.
{
     if (is_bool()) {
       return as_bool();
     } else if (is_int()) {
       return static_cast<bool>(to_int());
     } else {
       casadi_assert(is_bool(), "type mismatch");
       return false;
     }
   }
References as_bool(), is_bool(), is_int(), and to_int().
Referenced by to_int().
to_bool_vector()
std::vector< bool > casadi::GenericType::to_bool_vector () const
Definition at line 458 of file generic_type.cpp.
{
     casadi_assert(is_int_vector(), "type mismatch");
     std::vector<casadi_int> v = to_int_vector();
     std::vector<bool> ret(v.size());
     for (casadi_int i=0; i<v.size(); ++i) {
       casadi_assert(v[i]==0 || v[i]==1, "Entries must be zero or one");
       ret[i] = v[i]==1;
     }
     return ret;
   }
References is_int_vector(), and to_int_vector().
Referenced by is_empty_vector().
to_dict()
Dict casadi::GenericType::to_dict () const
Definition at line 520 of file generic_type.cpp.
{
     casadi_assert(is_dict(), "type mismatch");
     return as_dict();
   }
References as_dict(), and is_dict().
to_dict_vector()
std::vector< Dict > casadi::GenericType::to_dict_vector () const
Definition at line 525 of file generic_type.cpp.
{
     casadi_assert(is_dict_vector(), "type mismatch");
     return as_dict_vector();
   }
References as_dict_vector(), and is_dict_vector().
Referenced by is_empty_vector().
to_double()
double casadi::GenericType::to_double () const
Definition at line 428 of file generic_type.cpp.
{
     if (is_int()) {
       return static_cast<double>(to_int());
     } else {
       casadi_assert(is_double(), "type mismatch");
       return as_double();
     }
   }
References as_double(), is_double(), is_int(), and to_int().
Referenced by operator!=(), and to_int().
to_double_vector()
std::vector< double > casadi::GenericType::to_double_vector () const
Definition at line 474 of file generic_type.cpp.
{
     if (is_int_vector()) {
       auto v = as_int_vector();
       return std::vector<double>(v.begin(), v.end());
     } else {
       casadi_assert(is_double_vector(), "type mismatch");
       return as_double_vector();
     }
   }
References as_double_vector(), as_int_vector(), is_double_vector(), and is_int_vector().
Referenced by is_empty_vector(), and operator!=().
to_double_vector_vector()
std::vector< std::vector< double > > casadi::GenericType::to_double_vector_vector () const
Definition at line 484 of file generic_type.cpp.
{
     if (is_int_vector_vector()) {
       auto v = as_int_vector_vector();
       std::vector< std::vector<double> > ret(v.size());
       for (casadi_int i=0;i<v.size();++i)
         ret[i].assign(v[i].begin(), v[i].end());
       return ret;
     } else {
       casadi_assert(is_double_vector_vector(), "type mismatch");
       return as_double_vector_vector();
     }
   }
References as_double_vector_vector(), as_int_vector_vector(), casadi::SharedObject::assign(), is_double_vector_vector(), and is_int_vector_vector().
Referenced by is_empty_vector(), and operator!=().
to_function()
Function casadi::GenericType::to_function () const
Definition at line 624 of file generic_type.cpp.
{
     casadi_assert(is_function(), "type mismatch");
     return as_function();
   }
References as_function(), and is_function().
to_function_vector()
std::vector< Function > casadi::GenericType::to_function_vector () const
Definition at line 629 of file generic_type.cpp.
{
     casadi_assert(is_function_vector(), "type mismatch");
     return as_function_vector();
   }
References as_function_vector(), and is_function_vector().
to_int()
casadi_int casadi::GenericType::to_int () const
Definition at line 417 of file generic_type.cpp.
{
     if (is_double()) {
       return static_cast<casadi_int>(to_double());
     } else if (is_bool()) {
       return static_cast<casadi_int>(to_bool());
     } else {
       casadi_assert(is_int(), "type mismatch");
       return as_int();
     }
   }
References as_int(), is_bool(), is_double(), is_int(), to_bool(), and to_double().
Referenced by operator!=(), to_bool(), and to_double().
to_int_type_vector()
std::vector< int > casadi::GenericType::to_int_type_vector () const
Definition at line 442 of file generic_type.cpp.
{
     casadi_assert(is_int_vector(), "type mismatch");
     return casadi::to_int(as_int_vector());
   }
References as_int_vector(), is_int_vector(), and casadi::to_int().
to_int_vector()
std::vector< casadi_int > casadi::GenericType::to_int_vector () const
Definition at line 447 of file generic_type.cpp.
{
     casadi_assert(is_int_vector(), "type mismatch");
     return as_int_vector();
   }
References as_int_vector(), and is_int_vector().
Referenced by is_empty_vector(), operator!=(), and to_bool_vector().
to_int_vector_vector()
std::vector< std::vector< casadi_int > > casadi::GenericType::to_int_vector_vector () const
Definition at line 469 of file generic_type.cpp.
{
     casadi_assert(is_int_vector_vector(), "type mismatch");
     return as_int_vector_vector();
   }
References as_int_vector_vector(), and is_int_vector_vector().
Referenced by is_empty_vector(), and operator!=().
to_string()
std::string casadi::GenericType::to_string () const
Definition at line 437 of file generic_type.cpp.
{
     casadi_assert(is_string(), "type mismatch");
     return as_string();
   }
References as_string(), and is_string().
Referenced by casadi::FunctionInternal::change_option(), and operator!=().
to_string_vector()
std::vector< std::string > casadi::GenericType::to_string_vector () const
Definition at line 497 of file generic_type.cpp.
{
     if (is_string()) {
       std::string s = as_string();
       return std::vector<std::string>(1, s);
     } else if (is_double_vector()) {
       auto v = as_double_vector();
       casadi_assert(v.empty(), "Cast only permitted for zero-length vectors");
       return {};
     } else if (is_int_vector()) {
       auto v = as_int_vector();
       casadi_assert(v.empty(), "Cast only permitted for zero-length vectors");
       return {};
     } else {
       casadi_assert(is_string_vector(), "type mismatch");
       return as_string_vector();
     }
   }
References as_double_vector(), as_int_vector(), as_string(), as_string_vector(), is_double_vector(), is_int_vector(), is_string(), and is_string_vector().
Referenced by is_empty_vector().
to_string_vector_vector()
std::vector< std::vector< std::string > > casadi::GenericType::to_string_vector_vector () const
Definition at line 515 of file generic_type.cpp.
{
     casadi_assert(is_string_vector_vector(), "type mismatch");
     return as_string_vector_vector();
   }
References as_string_vector_vector(), and is_string_vector_vector().
Referenced by is_empty_vector().
to_vector()
std::vector< GenericType > casadi::GenericType::to_vector () const
Definition at line 530 of file generic_type.cpp.
{
     if (is_double_vector()) {
       auto v = as_double_vector();
       std::vector<GenericType> ret(v.size());
       for (casadi_int i=0;i<v.size();++i) ret[i] = v[i];
       return ret;
     } else if (is_int_vector()) {
       auto v = as_int_vector();
       std::vector<GenericType> ret(v.size());
       for (casadi_int i=0;i<v.size();++i) ret[i] = v[i];
       return ret;
     } else if (is_string_vector()) {
       auto v = as_string_vector();
       std::vector<GenericType> ret(v.size());
       for (casadi_int i=0;i<v.size();++i) ret[i] = v[i];
       return ret;
     } else if (is_function_vector()) {
       auto v = as_function_vector();
       std::vector<GenericType> ret(v.size());
       for (casadi_int i=0;i<v.size();++i) ret[i] = v[i];
       return ret;
     } else if (is_double_vector_vector()) {
       auto v = as_double_vector_vector();
       std::vector<GenericType> ret(v.size());
       for (casadi_int i=0;i<v.size();++i) ret[i] = v[i];
       return ret;
     } else if (is_int_vector_vector()) {
       auto v = as_int_vector_vector();
       std::vector<GenericType> ret(v.size());
       for (casadi_int i=0;i<v.size();++i) ret[i] = v[i];
       return ret;
     } else if (is_string_vector_vector()) {
       auto v = as_string_vector_vector();
       std::vector<GenericType> ret(v.size());
       for (casadi_int i=0;i<v.size();++i) ret[i] = v[i];
       return ret;
     } else if (is_bool_vector()) {
       auto v = as_bool_vector();
       std::vector<GenericType> ret(v.size());
       for (casadi_int i=0;i<v.size();++i) ret[i] = v[i];
       return ret;
     } else if (is_dict_vector()) {
       auto v = as_dict_vector();
       std::vector<GenericType> ret(v.size());
       for (casadi_int i=0;i<v.size();++i) ret[i] = v[i];
       return ret;
     } else if (is_vector_vector()) {
       auto v = as_vector_vector();
       std::vector<GenericType> ret(v.size());
       for (casadi_int i=0;i<v.size();++i) ret[i] = v[i];
       return ret;
     } else {
       casadi_assert(is_vector(), "type mismatch");
       return as_vector();
     }
   }
References as_bool_vector(), as_dict_vector(), as_double_vector(), as_double_vector_vector(), as_function_vector(), as_int_vector(), as_int_vector_vector(), as_string_vector(), as_string_vector_vector(), as_vector(), as_vector_vector(), is_bool_vector(), is_dict_vector(), is_double_vector(), is_double_vector_vector(), is_function_vector(), is_int_vector(), is_int_vector_vector(), is_string_vector(), is_string_vector_vector(), is_vector(), and is_vector_vector().
Referenced by is_empty_vector().
to_vector_vector()
std::vector< std::vector< GenericType > > casadi::GenericType::to_vector_vector () const
Definition at line 587 of file generic_type.cpp.
{
     if (is_double_vector_vector()) {
       auto v = as_double_vector_vector();
       std::vector<std::vector<GenericType> > ret(v.size());
       for (casadi_int i=0;i<v.size();++i) {
         ret[i].resize(v[i].size());
         for (casadi_int j=0;j<v[i].size();++j) {
           ret[i][j] = v[i][j];
         }
       }
       return ret;
     } else if (is_int_vector_vector()) {
       auto v = as_int_vector_vector();
       std::vector<std::vector<GenericType> > ret(v.size());
       for (casadi_int i=0;i<v.size();++i) {
         ret[i].resize(v[i].size());
         for (casadi_int j=0;j<v[i].size();++j) {
           ret[i][j] = v[i][j];
         }
       }
       return ret;
     } else if (is_string_vector_vector()) {
       auto v = as_string_vector_vector();
       std::vector<std::vector<GenericType> > ret(v.size());
       for (casadi_int i=0;i<v.size();++i) {
         ret[i].resize(v[i].size());
         for (casadi_int j=0;j<v[i].size();++j) {
           ret[i][j] = v[i][j];
         }
       }
       return ret;
     } else {
       casadi_assert(is_vector_vector(), "type mismatch");
       return as_vector_vector();
     }
   }
References as_double_vector_vector(), as_int_vector_vector(), as_string_vector_vector(), as_vector_vector(), is_double_vector_vector(), is_int_vector_vector(), is_string_vector_vector(), and is_vector_vector().
Referenced by is_empty_vector().
to_void_pointer()
void * casadi::GenericType::to_void_pointer () const
Definition at line 634 of file generic_type.cpp.
{
     if (is_void_pointer()) {
       return as_void_pointer();
     } else {
       casadi_int i = as_int();
       casadi_assert(i==0, "Only zero pointers accepted");
       return nullptr;
     }
   }
References as_int(), as_void_pointer(), and is_void_pointer().
type_name()
static std::string casadi::GenericType::type_name () inline static
Definition at line 111 of file generic_type.hpp.
 {return "GenericType";}
weak()
WeakRef * casadi::SharedObject::weak () inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_aw
Definition at line 125 of file shared_object.cpp.
{
     return (*this)->weak();
   }
References casadi::SharedObjectInternal::weak().
Referenced by casadi::WeakRef::WeakRef().
The documentation for this class was generated from the following files:
generic_type.hpp
generic_type.cpp