CasADi: casadi::StringDeserializer Class Reference
casadi::StringDeserializer Class Reference
#include <serializer.hpp>
Detailed Description
Definition at line 225 of file serializer.hpp.
Public Member Functions
StringDeserializer (const std::string &string)
Advanced deserialization of CasADi objects.
~StringDeserializer ()
void decode (const std::string &string)
Sets the string to deserialize objects from.
SerializerBase::SerializationType pop_type ()
Sparsity blind_unpack_sparsity ()
MX blind_unpack_mx ()
Matrix< double > blind_unpack_dm ()
Matrix< SXElem > blind_unpack_sx ()
Linsol blind_unpack_linsol ()
Function blind_unpack_function ()
GenericType blind_unpack_generictype ()
casadi_int blind_unpack_int ()
double blind_unpack_double ()
std::string blind_unpack_string ()
std::vector< Sparsity > blind_unpack_sparsity_vector ()
std::vector< MX > blind_unpack_mx_vector ()
std::vector< Matrix< double > > blind_unpack_dm_vector ()
std::vector< Matrix< SXElem > > blind_unpack_sx_vector ()
std::vector< Linsol > blind_unpack_linsol_vector ()
std::vector< Function > blind_unpack_function_vector ()
std::vector< GenericType > blind_unpack_generictype_vector ()
std::vector< casadi_int > blind_unpack_int_vector ()
std::vector< double > blind_unpack_double_vector ()
std::vector< std::string > blind_unpack_string_vector ()
Sparsity unpack_sparsity ()
MX unpack_mx ()
Matrix< double > unpack_dm ()
Matrix< SXElem > unpack_sx ()
Linsol unpack_linsol ()
Function unpack_function ()
GenericType unpack_generictype ()
casadi_int unpack_int ()
double unpack_double ()
std::string unpack_string ()
std::vector< Sparsity > unpack_sparsity_vector ()
std::vector< MX > unpack_mx_vector ()
std::vector< Matrix< double > > unpack_dm_vector ()
std::vector< Matrix< SXElem > > unpack_sx_vector ()
std::vector< Linsol > unpack_linsol_vector ()
std::vector< Function > unpack_function_vector ()
std::vector< GenericType > unpack_generictype_vector ()
std::vector< casadi_int > unpack_int_vector ()
std::vector< double > unpack_double_vector ()
std::vector< std::string > unpack_string_vector ()
void connect (SerializerBase &s)
void reset ()
Protected Member Functions
DeserializingStream & deserializer ()
Protected Attributes
std::unique_ptr< std::istream > dstream_
std::unique_ptr< DeserializingStream > deserializer_
Constructor & Destructor Documentation
StringDeserializer()
casadi::StringDeserializer::StringDeserializer (const std::string & string)
See also
StringDeserializer
Extra doc: https://github.com/casadi/casadi/wiki/L_7r
Definition at line 114 of file serializer.cpp.
                                                                   :
         DeserializerBase(std::unique_ptr<std::istream>(
           new std::stringstream(string))) {
     }
~StringDeserializer()
casadi::StringDeserializer::~StringDeserializer ()
Definition at line 120 of file serializer.cpp.
 { }
Member Function Documentation
blind_unpack_dm()
Matrix<double> casadi::DeserializerBase::blind_unpack_dm () inherited
blind_unpack_dm_vector()
std::vector< Matrix<double> > casadi::DeserializerBase::blind_unpack_dm_vector () inherited
blind_unpack_double()
double casadi::DeserializerBase::blind_unpack_double () inherited
blind_unpack_double_vector()
std::vector<double> casadi::DeserializerBase::blind_unpack_double_vector () inherited
blind_unpack_function()
Function casadi::DeserializerBase::blind_unpack_function () inherited
Referenced by casadi::Function::load().
blind_unpack_function_vector()
std::vector<Function> casadi::DeserializerBase::blind_unpack_function_vector () inherited
blind_unpack_generictype()
GenericType casadi::DeserializerBase::blind_unpack_generictype () inherited
blind_unpack_generictype_vector()
std::vector<GenericType> casadi::DeserializerBase::blind_unpack_generictype_vector () inherited
blind_unpack_int()
casadi_int casadi::DeserializerBase::blind_unpack_int () inherited
blind_unpack_int_vector()
std::vector<casadi_int> casadi::DeserializerBase::blind_unpack_int_vector () inherited
blind_unpack_linsol()
Linsol casadi::DeserializerBase::blind_unpack_linsol () inherited
blind_unpack_linsol_vector()
std::vector<Linsol> casadi::DeserializerBase::blind_unpack_linsol_vector () inherited
blind_unpack_mx()
MX casadi::DeserializerBase::blind_unpack_mx () inherited
blind_unpack_mx_vector()
std::vector<MX> casadi::DeserializerBase::blind_unpack_mx_vector () inherited
blind_unpack_sparsity()
Sparsity casadi::DeserializerBase::blind_unpack_sparsity () inherited
blind_unpack_sparsity_vector()
std::vector<Sparsity> casadi::DeserializerBase::blind_unpack_sparsity_vector () inherited
blind_unpack_string()
std::string casadi::DeserializerBase::blind_unpack_string () inherited
blind_unpack_string_vector()
std::vector<std::string> casadi::DeserializerBase::blind_unpack_string_vector () inherited
blind_unpack_sx()
Matrix<SXElem> casadi::DeserializerBase::blind_unpack_sx () inherited
blind_unpack_sx_vector()
std::vector< Matrix<SXElem> > casadi::DeserializerBase::blind_unpack_sx_vector () inherited
connect()
void casadi::DeserializerBase::connect (SerializerBase & s) inherited
Definition at line 209 of file serializer.cpp.
{
     deserializer_->connect(*s.serializer_);
   }
References casadi::DeserializerBase::deserializer_, and casadi::SerializerBase::serializer_.
decode()
void casadi::StringDeserializer::decode (const std::string & string)
Extra doc: https://github.com/casadi/casadi/wiki/L_7s
Definition at line 91 of file serializer.cpp.
{
       casadi_assert(dstream_->peek() == std::char_traits<char>::eof(),
         "StringDeserializer::decode does not apply: current string not fully consumed yet.");
       static_cast<std::stringstream*>(dstream_.get())->str(string);
       dstream_->clear(); // reset error flags
     }
References casadi::DeserializerBase::dstream_, and casadi::str().
deserializer()
DeserializingStream & casadi::DeserializerBase::deserializer () protected inherited
Definition at line 127 of file serializer.cpp.
{
       casadi_assert(dstream_->peek() != std::char_traits<char>::eof(),
         "Deserializer reached end of stream. Nothing left to unpack.");
       return *deserializer_;
     }
References casadi::DeserializerBase::deserializer_, and casadi::DeserializerBase::dstream_.
Referenced by casadi::DeserializerBase::pop_type().
pop_type()
SerializerBase::SerializationType casadi::DeserializerBase::pop_type () inherited
Definition at line 133 of file serializer.cpp.
{
       char type;
       deserializer().unpack(type);
       return static_cast<SerializerBase::SerializationType>(type);
     }
References casadi::DeserializerBase::deserializer(), and casadi::DeserializingStream::unpack().
Referenced by casadi::Function::load().
reset()
void casadi::DeserializerBase::reset () inherited
Definition at line 212 of file serializer.cpp.
{
     deserializer_->reset();
   }
References casadi::DeserializerBase::deserializer_.
unpack_dm()
Matrix<double> casadi::DeserializerBase::unpack_dm () inherited
unpack_dm_vector()
std::vector< Matrix<double> > casadi::DeserializerBase::unpack_dm_vector () inherited
unpack_double()
double casadi::DeserializerBase::unpack_double () inherited
unpack_double_vector()
std::vector<double> casadi::DeserializerBase::unpack_double_vector () inherited
unpack_function()
Function casadi::DeserializerBase::unpack_function () inherited
Referenced by casadi::external_transform().
unpack_function_vector()
std::vector<Function> casadi::DeserializerBase::unpack_function_vector () inherited
unpack_generictype()
GenericType casadi::DeserializerBase::unpack_generictype () inherited
unpack_generictype_vector()
std::vector<GenericType> casadi::DeserializerBase::unpack_generictype_vector () inherited
unpack_int()
casadi_int casadi::DeserializerBase::unpack_int () inherited
unpack_int_vector()
std::vector<casadi_int> casadi::DeserializerBase::unpack_int_vector () inherited
unpack_linsol()
Linsol casadi::DeserializerBase::unpack_linsol () inherited
unpack_linsol_vector()
std::vector<Linsol> casadi::DeserializerBase::unpack_linsol_vector () inherited
unpack_mx()
MX casadi::DeserializerBase::unpack_mx () inherited
unpack_mx_vector()
std::vector<MX> casadi::DeserializerBase::unpack_mx_vector () inherited
unpack_sparsity()
Sparsity casadi::DeserializerBase::unpack_sparsity () inherited
unpack_sparsity_vector()
std::vector<Sparsity> casadi::DeserializerBase::unpack_sparsity_vector () inherited
unpack_string()
std::string casadi::DeserializerBase::unpack_string () inherited
unpack_string_vector()
std::vector<std::string> casadi::DeserializerBase::unpack_string_vector () inherited
unpack_sx()
Matrix<SXElem> casadi::DeserializerBase::unpack_sx () inherited
unpack_sx_vector()
std::vector< Matrix<SXElem> > casadi::DeserializerBase::unpack_sx_vector () inherited
Member Data Documentation
deserializer_
std::unique_ptr<DeserializingStream> casadi::DeserializerBase::deserializer_ protected inherited
Definition at line 170 of file serializer.hpp.
Referenced by casadi::DeserializerBase::connect(), casadi::DeserializerBase::deserializer(), and casadi::DeserializerBase::reset().
dstream_
std::unique_ptr<std::istream> casadi::DeserializerBase::dstream_ protected inherited
Definition at line 169 of file serializer.hpp.
Referenced by decode(), casadi::DeserializerBase::deserializer(), and casadi::FileDeserializer::FileDeserializer().
The documentation for this class was generated from the following files:
serializer.hpp
serializer.cpp