CasADi: casadi::AmplInterface Class Reference
casadi::AmplInterface Class Reference
'AmplInterface' plugin for Nlpsol
#include <ampl_interface.hpp>
Detailed Description
List of available options
Id Type Description
solver OT_STRING AMPL solver binary
List of available options
Id Type Description Used in
ad_weight OT_DOUBLE Weighting factor for derivative calculation.When there is an option of either using forward or reverse mode directional derivatives, the condition ad_weight*nf<=(1-ad_weight)*na is used where nf and na are estimates of the number of forward/reverse mode directional derivatives needed. By default, ad_weight is calculated automatically, but this can be overridden by setting this option. In particular, 0 means forcing forward mode and 1 forcing reverse mode. Leave unset for (class specific) heuristics. casadi::FunctionInternal
ad_weight_sp OT_DOUBLE Weighting factor for sparsity pattern calculation calculation.Overrides default behavior. Set to 0 and 1 to force forward and reverse mode respectively. Cf. option "ad_weight". When set to -1, sparsity is completely ignored and dense matrices are used. casadi::FunctionInternal
always_inline OT_BOOL Force inlining. casadi::FunctionInternal
bound_consistency OT_BOOL Ensure that primal-dual solution is consistent with the bounds casadi::Nlpsol
cache OT_DICT Prepopulate the function cache. Default: empty casadi::FunctionInternal
calc_f OT_BOOL Calculate 'f' in the Nlpsol base class casadi::Nlpsol
calc_g OT_BOOL Calculate 'g' in the Nlpsol base class casadi::Nlpsol
calc_lam_p OT_BOOL Calculate 'lam_p' in the Nlpsol base class casadi::Nlpsol
calc_lam_x OT_BOOL Calculate 'lam_x' in the Nlpsol base class casadi::Nlpsol
calc_multipliers OT_BOOL Calculate Lagrange multipliers in the Nlpsol base class casadi::Nlpsol
common_options OT_DICT Options for auto-generated functions casadi::OracleFunction
compiler OT_STRING Just-in-time compiler plugin to be used. casadi::FunctionInternal
custom_jacobian OT_FUNCTION Override CasADi's AD. Use together with 'jac_penalty': 0. Note: Highly experimental. Syntax may break often. casadi::FunctionInternal
der_options OT_DICT Default options to be used to populate forward_options, reverse_options, and jacobian_options before those options are merged in. casadi::FunctionInternal
derivative_of OT_FUNCTION The function is a derivative of another function. The type of derivative (directional derivative, Jacobian) is inferred from the function name. casadi::FunctionInternal
detect_simple_bounds OT_BOOL Automatically detect simple bounds (lbx/ubx) (default false). This is hopefully beneficial to speed and robustness but may also have adverse affects: 1) Subtleties in heuristics and stopping criteria may change the solution, 2) IPOPT may lie about multipliers of simple equality bounds unless 'fixed_variable_treatment' is set to 'relax_bounds'. casadi::Nlpsol
detect_simple_bounds_is_simple OT_BOOLVECTOR For internal use only. casadi::Nlpsol
detect_simple_bounds_parts OT_FUNCTION For internal use only. casadi::Nlpsol
detect_simple_bounds_target_x OT_INTVECTOR For internal use only. casadi::Nlpsol
discrete OT_BOOLVECTOR Indicates which of the variables are discrete, i.e. integer-valued casadi::Nlpsol
dump OT_BOOL Dump function to file upon first evaluation. [false] casadi::FunctionInternal
dump_dir OT_STRING Directory to dump inputs/outputs to. Make sure the directory exists [.] casadi::FunctionInternal
dump_format OT_STRING Choose file format to dump matrices. See DM.from_file [mtx] casadi::FunctionInternal
dump_in OT_BOOL Dump numerical values of inputs to file (readable with DM.from_file) [default: false] casadi::FunctionInternal
dump_out OT_BOOL Dump numerical values of outputs to file (readable with DM.from_file) [default: false] casadi::FunctionInternal
enable_fd OT_BOOL Enable derivative calculation by finite differencing. [default: false]] casadi::FunctionInternal
enable_forward OT_BOOL Enable derivative calculation using generated functions for Jacobian-times-vector products - typically using forward mode AD - if available. [default: true] casadi::FunctionInternal
enable_jacobian OT_BOOL Enable derivative calculation using generated functions for Jacobians of all differentiable outputs with respect to all differentiable inputs - if available. [default: true] casadi::FunctionInternal
enable_reverse OT_BOOL Enable derivative calculation using generated functions for transposed Jacobian-times-vector products - typically using reverse mode AD - if available. [default: true] casadi::FunctionInternal
error_on_fail OT_BOOL Throw exceptions when function evaluation fails (default true). casadi::ProtoFunction
eval_errors_fatal OT_BOOL When errors occur during evaluation of f,g,...,stop the iterations casadi::Nlpsol
expand OT_BOOL Replace MX with SX expressions in problem formulation [false] casadi::OracleFunction
fd_method OT_STRING Method for finite differencing [default 'central'] casadi::FunctionInternal
fd_options OT_DICT Options to be passed to the finite difference instance casadi::FunctionInternal
forward_options OT_DICT Options to be passed to a forward mode constructor casadi::FunctionInternal
gather_stats OT_BOOL Deprecated option (ignored): Statistics are now always collected. casadi::FunctionInternal
ignore_check_vec OT_BOOL If set to true, the input shape of F will not be checked. casadi::Nlpsol
input_scheme OT_STRINGVECTOR Deprecated option (ignored) casadi::FunctionInternal
inputs_check OT_BOOL Throw exceptions when the numerical values of the inputs don't make sense casadi::FunctionInternal
is_diff_in OT_BOOLVECTOR Indicate for each input if it should be differentiable. casadi::FunctionInternal
is_diff_out OT_BOOLVECTOR Indicate for each output if it should be differentiable. casadi::FunctionInternal
iteration_callback OT_FUNCTION A function that will be called at each iteration with the solver as input. Check documentation of Callback. casadi::Nlpsol
iteration_callback_ignore_errors OT_BOOL If set to true, errors thrown by iteration_callback will be ignored. casadi::Nlpsol
iteration_callback_step OT_INT Only call the callback function every few iterations. casadi::Nlpsol
jac_penalty OT_DOUBLE When requested for a number of forward/reverse directions, it may be cheaper to compute first the full jacobian and then multiply with seeds, rather than obtain the requested directions in a straightforward manner. Casadi uses a heuristic to decide which is cheaper. A high value of 'jac_penalty' makes it less likely for the heurstic to chose the full Jacobian strategy. The special value -1 indicates never to use the full Jacobian strategy casadi::FunctionInternal
jacobian_options OT_DICT Options to be passed to a Jacobian constructor casadi::FunctionInternal
jit OT_BOOL Use just-in-time compiler to speed up the evaluation casadi::FunctionInternal
jit_cleanup OT_BOOL Cleanup up the temporary source file that jit creates. Default: true casadi::FunctionInternal
jit_name OT_STRING The file name used to write out code. The actual file names used depend on 'jit_temp_suffix' and include extensions. Default: 'jit_tmp' casadi::FunctionInternal
jit_options OT_DICT Options to be passed to the jit compiler. casadi::FunctionInternal
jit_serialize OT_STRING Specify behaviour when serializing a jitted function: SOURCE|link|embed. casadi::FunctionInternal
jit_temp_suffix OT_BOOL Use a temporary (seemingly random) filename suffix for generated code and libraries. This is desired for thread-safety. This behaviour may defeat caching compiler wrappers. Default: true casadi::FunctionInternal
max_io OT_INT Acceptable number of inputs and outputs. Warn if exceeded. casadi::FunctionInternal
max_num_dir OT_INT Specify the maximum number of directions for derivative functions. Overrules the builtin optimized_num_dir. casadi::FunctionInternal
min_lam OT_DOUBLE Minimum allowed multiplier value casadi::Nlpsol
monitor OT_STRINGVECTOR Set of user problem functions to be monitored casadi::OracleFunction
never_inline OT_BOOL Forbid inlining. casadi::FunctionInternal
no_nlp_grad OT_BOOL Prevent the creation of the 'nlp_grad' function casadi::Nlpsol
oracle_options OT_DICT Options to be passed to the oracle function casadi::Nlpsol
output_scheme OT_STRINGVECTOR Deprecated option (ignored) casadi::FunctionInternal
post_expand OT_BOOL After construction, expand this Function. Default: False casadi::FunctionInternal
post_expand_options OT_DICT Options to be passed to post-construction expansion. Default: empty casadi::FunctionInternal
print_in OT_BOOL Print numerical values of inputs [default: false] casadi::FunctionInternal
print_out OT_BOOL Print numerical values of outputs [default: false] casadi::FunctionInternal
print_time OT_BOOL print information about execution time. Implies record_time. casadi::ProtoFunction
record_time OT_BOOL record information about execution time, for retrieval with stats(). casadi::ProtoFunction
regularity_check OT_BOOL Throw exceptions when NaN or Inf appears during evaluation casadi::ProtoFunction
reverse_options OT_DICT Options to be passed to a reverse mode constructor casadi::FunctionInternal
sens_linsol OT_STRING Linear solver used for parametric sensitivities (default 'qr'). casadi::Nlpsol
sens_linsol_options OT_DICT Linear solver options used for parametric sensitivities. casadi::Nlpsol
show_eval_warnings OT_BOOL Show warnings generated from function evaluations [true] casadi::OracleFunction
solver OT_STRING AMPL solver binary casadi::AmplInterface
specific_options OT_DICT Options for specific auto-generated functions, overwriting the defaults from common_options. Nested dictionary. casadi::OracleFunction
user_data OT_VOIDPTR A user-defined field that can be used to identify the function or pass additional information casadi::FunctionInternal
verbose OT_BOOL Verbose evaluation – for debugging casadi::ProtoFunction
verbose_init OT_BOOL Print out timing information about the different stages of initialization casadi::Nlpsol
warn_initial_bounds OT_BOOL Warn if the initial guess does not satisfy LBX and UBX casadi::Nlpsol
Definition at line 56 of file ampl_interface.hpp.
Public Types
typedef Nlpsol *(* Creator) (const std::string &name, const Function &oracle)
typedef int(* RegFcn) (Plugin *plugin)
Public Member Functions
AmplInterface (const std::string &name, const Function &nlp)
~AmplInterface () override
const char * plugin_name () const override
std::string class_name () const override
Get type name.
void init (const Dict &opts) override
Initialize.
void * alloc_mem () const override
Create memory block.
int init_mem (void *mem) const override
Initalize memory block.
void free_mem (void *mem) const override
Free memory block.
void set_work (void *mem, const double **&arg, double **&res, casadi_int *&iw, double *&w) const override
Set the (persistent) work vectors.
int solve (void *mem) const override
void serialize_body (SerializingStream &s) const override
Serialize an object without type information.
void serialize_type (SerializingStream &s) const override
Serialize type information.
std::string serialize_base_function () const override
String used to identify the immediate FunctionInternal subclass.
void disp_more (std::ostream &stream) const override
Print description.
virtual void check_inputs (void *mem) const
Check if the inputs correspond to a well-posed problem.
double get_default_in (casadi_int ind) const override
Get default input value.
virtual bool integer_support () const
Can discrete variables be treated.
int eval (const double **arg, double **res, casadi_int *iw, double *w, void *mem) const final
Evaluate numerically.
void nlpsol_codegen_body (CodeGenerator &g) const
Generate code for the function body.
bool uses_output () const override
Do the derivative functions need nondifferentiated outputs?
Dict get_stats (void *mem) const override
Get all statistics.
int callback (NlpsolMemory *m) const
Function kkt () const
bool is_a (const std::string &type, bool recursive) const override
Check if the function is of a particular type.
virtual DM getReducedHessian ()
virtual void setOptionsFromFile (const std::string &file)
Read options from parameter xml.
void finalize () override
Finalize initialization.
void join_results (OracleMemory *m) const
Combine results from different threads.
const Function & oracle () const override
Get oracle.
void expand ()
Function create_function (const Function &oracle, const std::string &fname, const std::vector< std::string > &s_in, const std::vector< std::string > &s_out, const Function::AuxOut &aux=Function::AuxOut())
Function create_function (const std::string &fname, const std::vector< std::string > &s_in, const std::vector< std::string > &s_out, const Function::AuxOut &aux=Function::AuxOut())
Function create_forward (const std::string &fname, casadi_int nfwd)
void set_function (const Function &fcn, const std::string &fname, bool jit=false)
void set_function (const Function &fcn)
int calc_function (OracleMemory *m, const std::string &fcn, const double *const *arg=nullptr, int thread_id=0) const
int calc_sp_forward (const std::string &fcn, const bvec_t **arg, bvec_t **res, casadi_int *iw, bvec_t *w) const
int calc_sp_reverse (const std::string &fcn, bvec_t **arg, bvec_t **res, casadi_int *iw, bvec_t *w) const
std::vector< std::string > get_function () const override
Get list of dependency functions.
const Function & get_function (const std::string &name) const override
virtual bool monitored (const std::string &name) const
bool has_function (const std::string &fname) const override
std::string generate_dependencies (const std::string &fname, const Dict &opts) const override
Export / Generate C code for the generated functions.
void jit_dependencies (const std::string &fname) override
JIT for dependencies.
int local_init_mem (void *mem) const
Initalize memory block.
void local_free_mem (void *mem) const
Free memory block.
void set_temp (void *mem, const double **arg, double **res, casadi_int *iw, double *w) const override
Set the work vectors.
virtual std::string getAdaptorSolverName () const
Obtain solver name from Adaptor.
Dict generate_options (const std::string &target) const override
Reconstruct options dict.
void change_option (const std::string &option_name, const GenericType &option_value) override
Change option after object creation for debugging.
Function self () const
Get a public class instance.
virtual Function factory (const std::string &name, const std::vector< std::string > &s_in, const std::vector< std::string > &s_out, const Function::AuxOut &aux, const Dict &opts) const
void add_embedded (std::map< FunctionInternal *, Function > &all_fun, const Function &dep, casadi_int max_depth) const
virtual void find (std::map< FunctionInternal *, Function > &all_fun, casadi_int max_depth) const
virtual std::vector< bool > which_depends (const std::string &s_in, const std::vector< std::string > &s_out, casadi_int order, bool tr=false) const
Which variables enter with some order.
virtual int eval_sx (const SXElem **arg, SXElem **res, casadi_int *iw, SXElem *w, void *mem) const
Evaluate with symbolic scalars.
virtual void eval_mx (const MXVector &arg, MXVector &res, bool always_inline, bool never_inline) const
Evaluate with symbolic matrices.
template<typename M >
void call (const std::vector< M > &arg, std::vector< M > &res, bool always_inline, bool never_inline) const
Call a function, templated.
template<typename M >
bool matching_arg (const std::vector< M > &arg, casadi_int &npar) const
Check if input arguments that needs to be replaced.
template<typename M >
bool matching_res (const std::vector< M > &arg, casadi_int &npar) const
Check if output arguments that needs to be replaced.
template<typename M >
std::vector< M > replace_arg (const std::vector< M > &arg, casadi_int npar) const
Replace 0-by-0 inputs.
template<typename M >
std::vector< M > project_arg (const std::vector< M > &arg, casadi_int npar) const
Project sparsities.
template<typename M >
std::vector< M > project_res (const std::vector< M > &arg, casadi_int npar) const
Project sparsities.
template<typename M >
std::vector< M > replace_res (const std::vector< M > &res, casadi_int npar) const
Replace 0-by-0 outputs.
template<typename M >
std::vector< std::vector< M > > replace_fseed (const std::vector< std::vector< M >> &fseed, casadi_int npar) const
Replace 0-by-0 forward seeds.
template<typename M >
std::vector< std::vector< M > > replace_fseed (const std::vector< std::vector< M > > &fseed, casadi_int npar) const
template<typename M >
std::vector< std::vector< M > > replace_aseed (const std::vector< std::vector< M >> &aseed, casadi_int npar) const
Replace 0-by-0 reverse seeds.
template<typename M >
std::vector< std::vector< M > > replace_aseed (const std::vector< std::vector< M > > &aseed, casadi_int npar) const
std::vector< MX > mapsum_mx (const std::vector< MX > &arg, const std::string &parallelization)
Parallel evaluation.
virtual Function slice (const std::string &name, const std::vector< casadi_int > &order_in, const std::vector< casadi_int > &order_out, const Dict &opts) const
returns a new function with a selection of inputs/outputs of the original
bool has_derivative () const
Can derivatives be calculated in any way?
virtual double ad_weight () const
Weighting factor for chosing forward/reverse mode.
virtual double sp_weight () const
Weighting factor for chosing forward/reverse mode,.
virtual std::vector< MX > free_mx () const
Get free variables (MX)
virtual std::vector< SX > free_sx () const
Get free variables (SX)
virtual bool has_free () const
Does the function have free variables.
virtual void generate_lifted (Function &vdef_fcn, Function &vinit_fcn) const
Extract the functions needed for the Lifted Newton method.
virtual casadi_int n_instructions () const
Get the number of atomic operations.
virtual casadi_int instruction_id (casadi_int k) const
Get an atomic operation operator index.
virtual std::vector< casadi_int > instruction_input (casadi_int k) const
Get the (integer) input arguments of an atomic operation.
virtual double instruction_constant (casadi_int k) const
Get the floating point output argument of an atomic operation.
virtual std::vector< casadi_int > instruction_output (casadi_int k) const
Get the (integer) output argument of an atomic operation.
virtual casadi_int n_nodes () const
Number of nodes in the algorithm.
virtual MX instruction_MX (casadi_int k) const
get MX expression associated with instruction
virtual SX instructions_sx () const
get SX expression associated with instructions
Function wrap () const
Wrap in an Function instance consisting of only one MX call.
Function wrap_as_needed (const Dict &opts) const
Wrap in an Function instance consisting of only one MX call.
Dict cache () const
Get all functions in the cache.
bool incache (const std::string &fname, Function &f, const std::string &suffix="") const
Get function in cache.
void tocache (const Function &f, const std::string &suffix="") const
Save function to cache.
void codegen (CodeGenerator &g, const std::string &fname) const
Generate code the function.
void codegen_meta (CodeGenerator &g) const
Generate meta-information allowing a user to evaluate a generated function.
void codegen_sparsities (CodeGenerator &g) const
Codegen sparsities.
virtual std::string codegen_name (const CodeGenerator &g, bool ns=true) const
Get name in codegen.
std::string codegen_mem (CodeGenerator &g, const std::string &index="mem") const
Get thread-local memory object.
virtual void codegen_incref (CodeGenerator &g) const
Codegen incref for dependencies.
virtual void codegen_decref (CodeGenerator &g) const
Codegen decref for dependencies.
virtual void codegen_alloc_mem (CodeGenerator &g) const
Codegen decref for alloc_mem.
virtual void codegen_init_mem (CodeGenerator &g) const
Codegen decref for init_mem.
virtual void codegen_free_mem (CodeGenerator &g) const
Codegen for free_mem.
virtual void codegen_checkout (CodeGenerator &g) const
Codegen for checkout.
virtual void codegen_release (CodeGenerator &g) const
Codegen for release.
std::string signature (const std::string &fname) const
Code generate the function.
virtual void codegen_declarations (CodeGenerator &g) const
Generate code for the declarations of the C function.
virtual void codegen_body (CodeGenerator &g) const
Generate code for the function body.
virtual std::string codegen_mem_type () const
Thread-local memory object type.
virtual bool has_codegen () const
Is codegen supported?
virtual void export_code (const std::string &lang, std::ostream &stream, const Dict &options) const
Export function in a specific language.
void disp (std::ostream &stream, bool more) const override
Display object.
std::string definition () const
Get function signature: name:(inputs)->(outputs)
void print_dimensions (std::ostream &stream) const
Print dimensions of inputs and outputs.
virtual std::vector< std::string > get_free () const
Print free variables.
void get_partition (casadi_int iind, casadi_int oind, Sparsity &D1, Sparsity &D2, bool compact, bool symmetric, bool allow_forward, bool allow_reverse) const
Get the unidirectional or bidirectional partition.
virtual double get_max_in (casadi_int ind) const
Get largest input value.
virtual double get_min_in (casadi_int ind) const
Get smallest input value.
virtual std::vector< double > get_nominal_in (casadi_int ind) const
virtual std::vector< double > get_nominal_out (casadi_int ind) const
virtual double get_reltol () const
Get relative tolerance.
virtual double get_abstol () const
Get absolute tolerance.
virtual bool get_diff_in (casadi_int i)
Which inputs are differentiable.
virtual bool get_diff_out (casadi_int i)
Which outputs are differentiable.
casadi_int index_in (const std::string &name) const
Get input scheme index by name.
casadi_int index_out (const std::string &name) const
Get output scheme index by name.
virtual int sp_forward (const bvec_t **arg, bvec_t **res, casadi_int *iw, bvec_t *w, void *mem) const
Propagate sparsity forward.
virtual int sp_forward_block (const bvec_t **arg, bvec_t **res, casadi_int *iw, bvec_t *w, void *mem, casadi_int oind, casadi_int iind) const
Propagate sparsity forward, specific block.
virtual int sp_reverse (bvec_t **arg, bvec_t **res, casadi_int *iw, bvec_t *w, void *mem) const
Propagate sparsity backwards.
void sz_work (size_t &sz_arg, size_t &sz_res, size_t &sz_iw, size_t &sz_w) const
Get number of temporary variables needed.
size_t sz_arg () const
Get required length of arg field.
size_t sz_res () const
Get required length of res field.
size_t sz_iw () const
Get required length of iw field.
size_t sz_w () const
Get required length of w field.
void alloc_arg (size_t sz_arg, bool persistent=false)
Ensure required length of arg field.
void alloc_res (size_t sz_res, bool persistent=false)
Ensure required length of res field.
void alloc_iw (size_t sz_iw, bool persistent=false)
Ensure required length of iw field.
void alloc_w (size_t sz_w, bool persistent=false)
Ensure required length of w field.
void alloc (const Function &f, bool persistent=false, int num_threads=1)
Ensure work vectors long enough to evaluate function.
void setup (void *mem, const double **arg, double **res, casadi_int *iw, double *w) const
Set the (persistent and temporary) work vectors.
virtual Dict info () const
Function map (casadi_int n, const std::string &parallelization) const
Generate/retrieve cached serial map.
void generate_in (const std::string &fname, const double **arg) const
Export an input file that can be passed to generate C code with a main.
void generate_out (const std::string &fname, double **res) const
template<typename MatType >
std::vector< std::vector< MatType > > fwd_seed (casadi_int nfwd) const
Symbolic expressions for the forward seeds.
template<typename MatType >
std::vector< std::vector< MatType > > symbolicAdjSeed (casadi_int nadj, const std::vector< MatType > &v) const
Symbolic expressions for the adjoint seeds.
void print_in (std::ostream &stream, const double **arg, bool truncate) const
Print inputs.
void print_out (std::ostream &stream, double **res, bool truncate) const
Print outputs.
void construct (const Dict &opts)
Construct.
void print_options (std::ostream &stream) const
Print list of options.
void print_option (const std::string &name, std::ostream &stream) const
Print all information there is to know about a certain option.
bool has_option (const std::string &option_name) const
Does a particular option exist.
int checkout () const
Checkout a memory object.
void release (int mem) const
Release a memory object.
void * memory (int ind) const
Memory objects.
void clear_mem ()
Clear all memory (called from destructor)
void print (const char *fmt,...) const
C-style formatted printing during evaluation.
void sprint (char *buf, size_t buf_sz, const char *fmt,...) const
C-style formatted printing to string.
void format_time (char *buffer, double time) const
Format time in a fixed width 8 format.
void print_time (const std::map< std::string, FStats > &fstats) const
Print timing statistics.
void serialize (SerializingStream &s) const
Serialize an object.
casadi_int getCount () const
Get the reference count.
WeakRef * weak ()
Get a weak reference to the object.
size_t get_n_in () override
Number of function inputs and outputs.
size_t get_n_out () override
Number of function inputs and outputs.
Sparsity get_sparsity_in (casadi_int i) override
Sparsities of function inputs and outputs.
Sparsity get_sparsity_out (casadi_int i) override
Sparsities of function inputs and outputs.
std::string get_name_in (casadi_int i) override
Names of function input and outputs.
std::string get_name_out (casadi_int i) override
Names of function input and outputs.
bool has_forward (casadi_int nfwd) const override
Generate a function that calculates forward mode derivatives.
Function get_forward (casadi_int nfwd, const std::string &name, const std::vector< std::string > &inames, const std::vector< std::string > &onames, const Dict &opts) const override
Generate a function that calculates forward mode derivatives.
bool has_reverse (casadi_int nadj) const override
Generate a function that calculates reverse mode derivatives.
Function get_reverse (casadi_int nadj, const std::string &name, const std::vector< std::string > &inames, const std::vector< std::string > &onames, const Dict &opts) const override
Generate a function that calculates reverse mode derivatives.
virtual bool has_spfwd () const
Is the class able to propagate seeds through the algorithm?
virtual bool has_sprev () const
Is the class able to propagate seeds through the algorithm?
int eval_gen (const double **arg, double **res, casadi_int *iw, double *w, void *mem) const
Evaluate numerically.
int eval_gen (const SXElem **arg, SXElem **res, casadi_int *iw, SXElem *w, void *mem) const
Evaluate a function, overloaded.
int eval_gen (const bvec_t **arg, bvec_t **res, casadi_int *iw, bvec_t *w, void *mem) const
Evaluate a function, overloaded.
virtual std::vector< DM > eval_dm (const std::vector< DM > &arg) const
Evaluate with DM matrices.
virtual bool has_eval_dm () const
Evaluate with DM matrices.
void call_gen (const MXVector &arg, MXVector &res, casadi_int npar, bool always_inline, bool never_inline) const
Call a function, overloaded.
template<typename D >
void call_gen (const std::vector< Matrix< D > > &arg, std::vector< Matrix< D > > &res, casadi_int npar, bool always_inline, bool never_inline) const
Call a function, overloaded.
template<typename M >
void check_arg (const std::vector< M > &arg, casadi_int &npar) const
Check if input arguments have correct length and dimensions.
template<typename M >
void check_res (const std::vector< M > &res, casadi_int &npar) const
Check if output arguments have correct length and dimensions.
template<typename M >
std::map< std::string, M > convert_arg (const std::vector< M > &arg) const
Convert from/to input/output lists/map.
template<typename M >
std::vector< M > convert_arg (const std::map< std::string, M > &arg) const
Convert from/to input/output lists/map.
template<typename M >
std::map< std::string, M > convert_res (const std::vector< M > &res) const
Convert from/to input/output lists/map.
template<typename M >
std::vector< M > convert_res (const std::map< std::string, M > &res) const
Convert from/to input/output lists/map.
std::vector< double > nz_in (const std::vector< DM > &arg) const
Convert from/to flat vector of input/output nonzeros.
std::vector< DM > nz_in (const std::vector< double > &arg) const
Convert from/to flat vector of input/output nonzeros.
std::vector< double > nz_out (const std::vector< DM > &res) const
Convert from/to flat vector of input/output nonzeros.
std::vector< DM > nz_out (const std::vector< double > &res) const
Convert from/to flat vector of input/output nonzeros.
virtual void call_forward (const std::vector< MX > &arg, const std::vector< MX > &res, const std::vector< std::vector< MX > > &fseed, std::vector< std::vector< MX > > &fsens, bool always_inline, bool never_inline) const
Forward mode AD, virtual functions overloaded in derived classes.
virtual void call_forward (const std::vector< SX > &arg, const std::vector< SX > &res, const std::vector< std::vector< SX > > &fseed, std::vector< std::vector< SX > > &fsens, bool always_inline, bool never_inline) const
Forward mode AD, virtual functions overloaded in derived classes.
virtual void call_reverse (const std::vector< MX > &arg, const std::vector< MX > &res, const std::vector< std::vector< MX > > &aseed, std::vector< std::vector< MX > > &asens, bool always_inline, bool never_inline) const
Reverse mode, virtual functions overloaded in derived classes.
virtual void call_reverse (const std::vector< SX > &arg, const std::vector< SX > &res, const std::vector< std::vector< SX > > &aseed, std::vector< std::vector< SX > > &asens, bool always_inline, bool never_inline) const
Reverse mode, virtual functions overloaded in derived classes.
Function jacobian () const
Return Jacobian of all input elements with respect to all output elements.
virtual bool has_jacobian () const
Return Jacobian of all input elements with respect to all output elements.
virtual Function get_jacobian (const std::string &name, const std::vector< std::string > &inames, const std::vector< std::string > &onames, const Dict &opts) const
Return Jacobian of all input elements with respect to all output elements.
Sparsity & jac_sparsity (casadi_int oind, casadi_int iind, bool compact, bool symmetric) const
Get Jacobian sparsity.
virtual bool has_jac_sparsity (casadi_int oind, casadi_int iind) const
Get Jacobian sparsity.
virtual Sparsity get_jac_sparsity (casadi_int oind, casadi_int iind, bool symmetric) const
Get Jacobian sparsity.
Function forward (casadi_int nfwd) const
Return function that calculates forward derivatives.
Function reverse (casadi_int nadj) const
Return function that calculates adjoint derivatives.
virtual const SX sx_in (casadi_int ind) const
Get function input(s) and output(s)
virtual const std::vector< SX > sx_in () const
Get function input(s) and output(s)
virtual const SX sx_out (casadi_int ind) const
Get function input(s) and output(s)
virtual const std::vector< SX > sx_out () const
Get function input(s) and output(s)
virtual const MX mx_in (casadi_int ind) const
Get function input(s) and output(s)
virtual const std::vector< MX > mx_in () const
Get function input(s) and output(s)
virtual const MX mx_out (casadi_int ind) const
Get function input(s) and output(s)
virtual const std::vector< MX > mx_out () const
Get function input(s) and output(s)
const DM dm_in (casadi_int ind) const
Get function input(s) and output(s)
const std::vector< DM > dm_in () const
Get function input(s) and output(s)
const DM dm_out (casadi_int ind) const
Get function input(s) and output(s)
const std::vector< DM > dm_out () const
Get function input(s) and output(s)
casadi_int nnz_in () const
Number of input/output nonzeros.
casadi_int nnz_in (casadi_int ind) const
Number of input/output nonzeros.
casadi_int nnz_out () const
Number of input/output nonzeros.
casadi_int nnz_out (casadi_int ind) const
Number of input/output nonzeros.
casadi_int numel_in () const
Number of input/output elements.
casadi_int numel_in (casadi_int ind) const
Number of input/output elements.
casadi_int numel_out (casadi_int ind) const
Number of input/output elements.
casadi_int numel_out () const
Number of input/output elements.
casadi_int size1_in (casadi_int ind) const
Input/output dimensions.
casadi_int size2_in (casadi_int ind) const
Input/output dimensions.
casadi_int size1_out (casadi_int ind) const
Input/output dimensions.
casadi_int size2_out (casadi_int ind) const
Input/output dimensions.
std::pair< casadi_int, casadi_int > size_in (casadi_int ind) const
Input/output dimensions.
std::pair< casadi_int, casadi_int > size_out (casadi_int ind) const
Input/output dimensions.
const Sparsity & sparsity_in (casadi_int ind) const
Input/output sparsity.
const Sparsity & sparsity_out (casadi_int ind) const
Input/output sparsity.
bool all_scalar () const
Are all inputs and outputs scalar.
virtual bool jac_is_symm (casadi_int oind, casadi_int iind) const
Is a Jacobian block known to be symmetric a priori?
Sparsity to_compact (casadi_int oind, casadi_int iind, const Sparsity &sp) const
Convert to compact Jacobian sparsity pattern.
Sparsity from_compact (casadi_int oind, casadi_int iind, const Sparsity &sp) const
Convert from compact Jacobian sparsity pattern.
template<bool fwd>
Sparsity get_jac_sparsity_gen (casadi_int oind, casadi_int iind) const
Get the sparsity pattern via sparsity seed propagation.
Sparsity get_jac_sparsity_hierarchical (casadi_int oind, casadi_int iind) const
A flavor of get_jac_sparsity_gen that does hierarchical block structure recognition.
Sparsity get_jac_sparsity_hierarchical_symm (casadi_int oind, casadi_int iind) const
virtual std::vector< MX > symbolic_output (const std::vector< MX > &arg) const
Get a vector of symbolic variables corresponding to the outputs.
virtual bool fwdViaJac (casadi_int nfwd) const
Calculate derivatives by multiplying the full Jacobian and multiplying.
virtual bool adjViaJac (casadi_int nadj) const
Calculate derivatives by multiplying the full Jacobian and multiplying.
Static Public Member Functions
static Nlpsol * creator (const std::string &name, const Function &nlp)
Create a new NLP Solver.
static ProtoFunction * deserialize (DeserializingStream &s)
Deserialize into MX.
static void bound_consistency (casadi_int n, double *z, double *lam, const double *lbz, const double *ubz)
static std::string shortname ()
Short name.
template<typename Type >
static void append_to_vec (GenericType &t, Type el)
WORKAROUND: Add an element to an std::vector stored in a GenericType:
template<typename XType >
static Function create_oracle (const std::map< std::string, XType > &d, const Dict &opts)
Convert dictionary to Problem.
static std::string forward_name (const std::string &fcn, casadi_int nfwd)
Helper function: Get name of forward derivative function.
static std::string reverse_name (const std::string &fcn, casadi_int nadj)
Helper function: Get name of adjoint derivative function.
template<typename MatType >
static bool purgable (const std::vector< MatType > &seed)
Can a derivative direction be skipped.
static std::string string_from_UnifiedReturnStatus (UnifiedReturnStatus status)
static bool has_plugin (const std::string &pname, bool verbose=false)
Check if a plugin is available or can be loaded.
static const Options & plugin_options (const std::string &pname)
Get the plugin options.
static Deserialize plugin_deserialize (const std::string &pname)
Get the plugin deserialize_map.
static Plugin pluginFromRegFcn (RegFcn regfcn)
Instantiate a Plugin struct from a factory function.
static Plugin load_plugin (const std::string &pname, bool register_plugin=true)
Load a plugin dynamically.
static handle_t load_library (const std::string &libname, std::string &resultpath, bool global)
Load a library dynamically.
static void registerPlugin (const Plugin &plugin)
Register an integrator in the factory.
static void registerPlugin (RegFcn regfcn)
Register an integrator in the factory.
static Plugin & getPlugin (const std::string &pname)
Load and get the creator function.
static Nlpsol * instantiate (const std::string &fname, const std::string &pname, Problem problem)
static bool check_mat (const Sparsity &arg, const Sparsity &inp, casadi_int &npar)
Public Attributes
std::string solver_
std::stringstream nl_init_
casadi_nlpsol_prob< double > p_nlp_
casadi_int nx_
Number of variables.
casadi_int ng_
Number of constraints.
casadi_int np_
Number of parameters.
Function fcallback_
callback function, executed at each iteration
casadi_int callback_step_
Execute the callback function only after this amount of iterations.
std::string sens_linsol_
Linear solver and options.
Dict sens_linsol_options_
std::vector< char > detect_simple_bounds_is_simple_
Function detect_simple_bounds_parts_
std::vector< casadi_int > detect_simple_bounds_target_x_
std::vector< casadi_int > detect_simple_bounds_target_g_
bool mi_
WeakRef kkt_
Cache for KKT function.
bool always_inline_
bool never_inline_
size_t n_in_
Number of inputs and outputs.
size_t n_out_
std::vector< bool > is_diff_in_
Are inputs and outputs differentiable?
std::vector< bool > is_diff_out_
std::vector< Sparsity > sparsity_in_
Input and output sparsity.
std::vector< Sparsity > sparsity_out_
std::vector< std::string > name_in_
Input and output scheme.
std::vector< std::string > name_out_
bool jit_
Use just-in-time compiler.
bool jit_cleanup_
Cleanup jit source file.
std::string jit_serialize_
Serialize behaviour.
std::string jit_name_
Name if jit source file.
std::string jit_base_name_
bool jit_temp_suffix_
Use a temporary name.
eval_t eval_
Numerical evaluation redirected to a C function.
casadi_checkout_t checkout_
Checkout redirected to a C function.
casadi_release_t release_
Release redirected to a C function.
Dict stats_
Dict of statistics (resulting from evaluate)
bool has_refcount_
Reference counting in codegen?
Dict cache_init_
Values to prepopulate the function cache with.
std::map< std::string, WeakRef > cache_
Function cache.
std::vector< Sparsity > jac_sparsity_ [2]
Cache for sparsities of the Jacobian blocks.
Function derivative_of_
If the function is the derivative of another function.
void * user_data_
User-set field.
std::string compiler_plugin_
Just-in-time compiler.
Importer compiler_
Dict jit_options_
double jac_penalty_
Penalty factor for using a complete Jacobian to calculate directional derivatives.
bool enable_forward_
bool enable_reverse_
bool enable_jacobian_
bool enable_fd_
bool enable_forward_op_
bool enable_reverse_op_
bool enable_jacobian_op_
bool enable_fd_op_
double ad_weight_
Weighting factor for derivative calculation and sparsity pattern calculation.
double ad_weight_sp_
casadi_int max_num_dir_
Maximum number of sensitivity directions.
bool inputs_check_
Errors are thrown if numerical values of inputs look bad.
Dict fd_options_
double fd_step_
std::string fd_method_
bool print_in_
bool print_out_
casadi_int max_io_
bool dump_in_
bool dump_out_
bool dump_
std::string dump_dir_
std::string dump_format_
Dict forward_options_
Dict reverse_options_
Dict jacobian_options_
Dict der_options_
Function custom_jacobian_
casadi_int dump_count_ = 0
std::string name_
Name.
bool verbose_
Verbose printout.
bool print_time_
bool record_time_
bool regularity_check_
Errors are thrown when NaN is produced.
bool error_on_fail_
Throw an exception on failure?
bool eval_errors_fatal_
Options.
bool warn_initial_bounds_
Options.
bool iteration_callback_ignore_errors_
Options.
bool calc_multipliers_
Options.
bool calc_lam_x_
Options.
bool calc_lam_p_
Options.
bool calc_f_
Options.
bool calc_g_
Options.
bool bound_consistency_
Options.
double min_lam_
Options.
bool no_nlp_grad_
Options.
std::vector< bool > discrete_
Options.
Static Public Attributes
static const std::string meta_doc
A documentation string.
static std::map< std::string, Plugin > solvers_
Collection of solvers.
static const std::string infix_ = "nlpsol"
Infix.
static std::map< std::string, ProtoFunction *(*)(DeserializingStream &)> deserialize_map
Protected Member Functions
void set_jac_sparsity (casadi_int oind, casadi_int iind, const Sparsity &sp)
Populate jac_sparsity_ and jac_sparsity_compact_ during initialization.
void initSingleton ()
void destroySingleton ()
template<class B >
B shared_from_this ()
Get a shared object from the current internal object.
template<class B >
const B shared_from_this () const
Get a shared object from the current internal object.
Protected Attributes
Function oracle_
Oracle: Used to generate other functions.
Dict common_options_
Options for creating functions.
Dict specific_options_
bool show_eval_warnings_
Show evaluation warnings.
int max_num_threads_
std::map< std::string, RegFun > all_functions_
std::vector< std::string > monitor_
size_t stride_arg_
size_t stride_res_
size_t stride_iw_
size_t stride_w_
static const Options options_
Options.
const Options & get_options () const override
Options.
Member Typedef Documentation
Creator
typedef Nlpsol*(* casadi::Nlpsol::Creator) (const std::string &name, const Function &oracle) inherited
Definition at line 261 of file nlpsol_impl.hpp.
RegFcn
typedef int(* casadi::PluginInterface< Nlpsol >::RegFcn) (Plugin *plugin) inherited
Definition at line 72 of file plugin_interface.hpp.
Constructor & Destructor Documentation
AmplInterface()
casadi::AmplInterface::AmplInterface (const std::string & name, const Function & nlp) explicit
Definition at line 49 of file ampl_interface.cpp.
     : Nlpsol(name, nlp) {
   }
~AmplInterface()
casadi::AmplInterface::~AmplInterface () override
Definition at line 54 of file ampl_interface.cpp.
{
     clear_mem();
   }
References casadi::ProtoFunction::clear_mem().
Member Function Documentation
ad_weight()
double casadi::FunctionInternal::ad_weight () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_l5
Definition at line 3056 of file function_internal.cpp.
{
     // If reverse mode derivatives unavailable, use forward
     if (!enable_reverse_) return 0;
     // If forward mode derivatives unavailable, use reverse
     if (!enable_forward_ && !enable_fd_) return 1;
     // Use the (potentially user set) option
     return ad_weight_;
   }
References casadi::FunctionInternal::ad_weight_, casadi::FunctionInternal::enable_fd_, casadi::FunctionInternal::enable_forward_, and casadi::FunctionInternal::enable_reverse_.
Referenced by casadi::FunctionInternal::adjViaJac(), casadi::Function::expand(), casadi::FunctionInternal::fwdViaJac(), casadi::FunctionInternal::get_partition(), casadi::FunctionInternal::wrap(), and casadi::FunctionInternal::wrap_as_needed().
add_embedded()
void casadi::FunctionInternal::add_embedded (std::map< FunctionInternal *, Function > & all_fun, const Function & dep, casadi_int max_depth) const inherited
Definition at line 3487 of file function_internal.cpp.
{
     // Add, if not already in graph and not null
     if (!dep.is_null() && all_fun.find(dep.get()) == all_fun.end()) {
       // Add to map
       all_fun[dep.get()] = dep;
       // Also add its dependencies
       if (max_depth > 0) dep->find(all_fun, max_depth - 1);
     }
   }
References casadi::FunctionInternal::find(), casadi::Function::get(), and casadi::SharedObject::is_null().
Referenced by casadi::MXFunction::find(), and casadi::Switch::find().
adjViaJac()
bool casadi::FunctionInternal::adjViaJac (casadi_int nadj) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_nc
Definition at line 2791 of file function_internal.cpp.
{
     if (!enable_reverse_) return true;
     if (jac_penalty_==-1) return false;
     // Heuristic 1: Jac calculated via reverse mode likely cheaper
     if (jac_penalty_*static_cast<double>(nnz_out())<nadj) return true;
     // Heuristic 2: Jac calculated via forward mode likely cheaper
     double w = ad_weight();
     if ((enable_forward_ || enable_fd_) &&
         jac_penalty_*w*static_cast<double>(nnz_in())<(1-w)*static_cast<double>(nadj))
       return true; // NOLINT
     return false;
   }
References casadi::FunctionInternal::ad_weight(), casadi::FunctionInternal::enable_fd_, casadi::FunctionInternal::enable_forward_, casadi::FunctionInternal::enable_reverse_, casadi::FunctionInternal::jac_penalty_, casadi::FunctionInternal::nnz_in(), and casadi::FunctionInternal::nnz_out().
Referenced by casadi::FunctionInternal::call_reverse().
all_scalar()
bool casadi::FunctionInternal::all_scalar () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mi
Definition at line 3517 of file function_internal.cpp.
{
     // Check inputs
     for (casadi_int i=0; i<n_in_; ++i) {
       if (!sparsity_in_[i].is_scalar()) return false;
     }
     // Check outputs
     for (casadi_int i=0; i<n_out_; ++i) {
       if (!sparsity_out_[i].is_scalar()) return false;
     }
     // All are scalar
     return true;
   }
References casadi::FunctionInternal::n_in_, casadi::FunctionInternal::n_out_, casadi::FunctionInternal::sparsity_in_, and casadi::FunctionInternal::sparsity_out_.
Referenced by casadi::FunctionInternal::call().
alloc()
void casadi::FunctionInternal::alloc (const Function & f, bool persistent = false, int num_threads = 1) inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_n8
Definition at line 2749 of file function_internal.cpp.
{
     if (f.is_null()) return;
     size_t sz_arg, sz_res, sz_iw, sz_w;
     f.sz_work(sz_arg, sz_res, sz_iw, sz_w);
     alloc_arg(sz_arg*num_threads, persistent);
     alloc_res(sz_res*num_threads, persistent);
     alloc_iw(sz_iw*num_threads, persistent);
     alloc_w(sz_w*num_threads, persistent);
   }
References casadi::FunctionInternal::alloc_arg(), casadi::FunctionInternal::alloc_iw(), casadi::FunctionInternal::alloc_res(), casadi::FunctionInternal::alloc_w(), casadi::SharedObject::is_null(), casadi::FunctionInternal::sz_arg(), casadi::FunctionInternal::sz_iw(), casadi::FunctionInternal::sz_res(), casadi::FunctionInternal::sz_w(), and casadi::Function::sz_work().
Referenced by casadi::OracleFunction::finalize(), casadi::KinsolInterface::get_jtimes(), casadi::FiniteDiff::init(), casadi::Nlpsol::init(), casadi::Rootfinder::init(), casadi::Switch::init(), casadi::Feasiblesqpmethod::init(), casadi::ImplicitToNlp::init(), casadi::QpToNlp::init(), casadi::Qrsqp::init(), casadi::Scpgen::init(), and casadi::Sqpmethod::init().
alloc_arg()
void casadi::FunctionInternal::alloc_arg (size_t sz_arg, bool persistent = false) inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_n4
Definition at line 2717 of file function_internal.cpp.
{
     if (persistent) {
       sz_arg_per_ += sz_arg;
     } else {
       sz_arg_tmp_ = std::max(sz_arg_tmp_, sz_arg);
     }
   }
References casadi::FunctionInternal::sz_arg().
Referenced by casadi::FunctionInternal::alloc(), casadi::External::init(), casadi::FunctionInternal::init(), casadi::Map::init(), casadi::OmpMap::init(), casadi::ThreadMap::init(), casadi::MapSum::init(), casadi::MXFunction::init(), casadi::Nlpsol::init(), casadi::HighsInterface::init(), casadi::HpipmInterface::init(), casadi::BSplineInterpolant::init(), and casadi::Qrqp::init().
alloc_iw()
void casadi::FunctionInternal::alloc_iw (size_t sz_iw, bool persistent = false) inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_n6
Definition at line 2733 of file function_internal.cpp.
{
     if (persistent) {
       sz_iw_per_ += sz_iw;
     } else {
       sz_iw_tmp_ = std::max(sz_iw_tmp_, sz_iw);
     }
   }
References casadi::FunctionInternal::sz_iw().
Referenced by casadi::FunctionInternal::alloc(), casadi::External::init(), casadi::Interpolant::init(), casadi::Map::init(), casadi::OmpMap::init(), casadi::ThreadMap::init(), casadi::MapSum::init(), casadi::MXFunction::init(), casadi::Nlpsol::init(), casadi::Blocksqp::init(), casadi::GurobiInterface::init(), casadi::HighsInterface::init(), casadi::HpipmInterface::init(), casadi::IpoptInterface::init(), casadi::OoqpInterface::init(), casadi::SlicotDple::init(), casadi::SlicotExpm::init(), casadi::SundialsInterface::init(), casadi::BSplineInterpolant::init(), casadi::Feasiblesqpmethod::init(), casadi::Ipqp::init(), casadi::LinearInterpolant::init(), casadi::LinearInterpolantJac::init(), casadi::Qrqp::init(), and casadi::Sqpmethod::init().
alloc_mem()
void* casadi::AmplInterface::alloc_mem () const inline override virtual
Reimplemented from casadi::Nlpsol.
Definition at line 82 of file ampl_interface.hpp.
 { return new AmplInterfaceMemory();}
alloc_res()
void casadi::FunctionInternal::alloc_res (size_t sz_res, bool persistent = false) inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_n5
Definition at line 2725 of file function_internal.cpp.
{
     if (persistent) {
       sz_res_per_ += sz_res;
     } else {
       sz_res_tmp_ = std::max(sz_res_tmp_, sz_res);
     }
   }
References casadi::FunctionInternal::sz_res().
Referenced by casadi::FunctionInternal::alloc(), casadi::External::init(), casadi::FiniteDiff::init(), casadi::FunctionInternal::init(), casadi::Map::init(), casadi::OmpMap::init(), casadi::ThreadMap::init(), casadi::MapSum::init(), casadi::MXFunction::init(), casadi::Nlpsol::init(), casadi::Blocksqp::init(), casadi::HighsInterface::init(), casadi::HpipmInterface::init(), casadi::BSplineInterpolant::init(), and casadi::Qrqp::init().
alloc_w()
void casadi::FunctionInternal::alloc_w (size_t sz_w, bool persistent = false) inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_n7
Definition at line 2741 of file function_internal.cpp.
{
     if (persistent) {
       sz_w_per_ += sz_w;
     } else {
       sz_w_tmp_ = std::max(sz_w_tmp_, sz_w);
     }
   }
References casadi::FunctionInternal::sz_w().
Referenced by casadi::FunctionInternal::alloc(), casadi::External::init(), casadi::FiniteDiff::init(), casadi::Integrator::init(), casadi::FixedStepIntegrator::init(), casadi::Interpolant::init(), casadi::JitFunction::init(), casadi::Map::init(), casadi::OmpMap::init(), casadi::ThreadMap::init(), casadi::MapSum::init(), casadi::MXFunction::init(), casadi::Nlpsol::init(), casadi::Rootfinder::init(), casadi::Switch::init(), casadi::Blocksqp::init(), casadi::BonminInterface::init(), casadi::CbcInterface::init(), casadi::ClpInterface::init(), casadi::CplexInterface::init(), casadi::GurobiInterface::init(), casadi::HighsInterface::init(), casadi::HpipmInterface::init(), casadi::IpoptInterface::init(), casadi::KnitroInterface::init(), casadi::OoqpInterface::init(), casadi::OsqpInterface::init(), casadi::ProxqpInterface::init(), casadi::QpoasesInterface::init(), casadi::SlicotDple::init(), casadi::SlicotExpm::init(), casadi::SnoptInterface::init(), casadi::CvodesInterface::init(), casadi::IdasInterface::init(), casadi::KinsolInterface::init(), casadi::SundialsInterface::init(), casadi::SuperscsInterface::init(), casadi::WorhpInterface::init(), casadi::BSplineInterpolant::init(), casadi::FastNewton::init(), casadi::Feasiblesqpmethod::init(), casadi::ImplicitToNlp::init(), casadi::Ipqp::init(), casadi::LinearInterpolant::init(), casadi::LinearInterpolantJac::init(), casadi::Newton::init(), casadi::QpToNlp::init(), casadi::Qrqp::init(), casadi::Qrsqp::init(), casadi::Scpgen::init(), and casadi::Sqpmethod::init().
append_to_vec()
template<typename Type > static void casadi::Nlpsol::append_to_vec (GenericType & t, Type el) inline static inherited
Definition at line 292 of file nlpsol_impl.hpp.
{
       std::vector<Type> v = t;
       v.push_back(el);
       t = v;
     }
bound_consistency()
void casadi::Nlpsol::bound_consistency (casadi_int n, double * z, double * lam, const double * lbz, const double * ubz) static inherited
Definition at line 648 of file nlpsol.cpp.
{
     casadi_assert_dev(z!=nullptr);
     casadi_assert_dev(lam!=nullptr);
     casadi_assert_dev(lbz!=nullptr);
     casadi_assert_dev(ubz!=nullptr);
     // Local variables
     casadi_int i;
     // Loop over variables
     for (i=0; i<n; ++i) {
       // Make sure bounds are respected
       z[i] = std::fmin(std::fmax(z[i], lbz[i]), ubz[i]);
       // Adjust multipliers
       if (std::isinf(lbz[i]) && std::isinf(ubz[i])) {
         // Both multipliers are infinite
         lam[i] = 0.;
       } else if (std::isinf(lbz[i]) || z[i] - lbz[i] > ubz[i] - z[i]) {
         // Infinite lower bound or closer to upper bound than lower bound
         lam[i] = std::fmax(0., lam[i]);
       } else if (std::isinf(ubz[i]) || z[i] - lbz[i] < ubz[i] - z[i]) {
         // Infinite upper bound or closer to lower bound than upper bound
         lam[i] = std::fmin(0., lam[i]);
       }
     }
   }
Referenced by casadi::Nlpsol::eval().
cache()
Dict casadi::FunctionInternal::cache () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_26g
Definition at line 950 of file function_internal.cpp.
{
     // Return value
     Dict ret;
     // Add all Function instances that haven't been deleted
     for (auto&& cf : cache_) {
       if (cf.second.alive()) {
         ret[cf.first] = shared_cast<Function>(cf.second.shared());
       }
     }
     return ret;
   }
References casadi::FunctionInternal::cache_.
calc_function()
int casadi::OracleFunction::calc_function (OracleMemory * m, const std::string & fcn, const double *const * arg = nullptr, int thread_id = 0) const inherited
Definition at line 219 of file oracle_function.cpp.
{
   auto ml = m->thread_local_mem.at(thread_id);
   // Is the function monitored?
   bool monitored = this->monitored(fcn);
   // Print progress
   if (monitored) casadi_message("Calling \"" + fcn + "\"");
   // Respond to a possible Crl+C signals
   // Python interrupt checker needs the GIL.
   // We may not have access to it in a multi-threaded context
   // See issue #2955
   if (max_num_threads_==1) InterruptHandler::check();
   // Get function
   const Function& f = get_function(fcn);
   // Get statistics structure
   FStats& fstats = ml->fstats.at(fcn);
   // Number of inputs and outputs
   casadi_int n_in = f.n_in(), n_out = f.n_out();
   // Prepare stats, start timer
   ScopedTiming tic(fstats);
   // Input buffers
   if (arg) {
     std::fill_n(ml->arg, n_in, nullptr);
     for (casadi_int i=0; i<n_in; ++i) ml->arg[i] = *arg++;
   }
   // Print inputs nonzeros
   if (monitored) {
     std::stringstream s;
     s << fcn << " input nonzeros:\n";
     for (casadi_int i=0; i<n_in; ++i) {
       s << " " << i << " (" << f.name_in(i) << "): ";
       if (ml->arg[i]) {
         // Print nonzeros
         s << "[";
         for (casadi_int k=0; k<f.nnz_in(i); ++k) {
           if (k!=0) s << ", ";
           DM::print_scalar(s, ml->arg[i][k]);
         }
         s << "]\n";
       } else {
         // All zero input
         s << "0\n";
       }
     }
     casadi_message(s.str());
   }
   // Evaluate memory-less
   try {
     if (f(ml->arg, ml->res, ml->iw, ml->w)) {
       // Recoverable error
       if (monitored) casadi_message(name_ + ":" + fcn + " failed");
       return 1;
     }
   } catch(std::exception& ex) {
     // Fatal error: Generate stack trace
     casadi_error("Error in " + name_ + ":" + fcn + ":" + std::string(ex.what()));
   }
   // Print output nonzeros
   if (monitored) {
     std::stringstream s;
     s << fcn << " output nonzeros:\n";
     for (casadi_int i=0; i<n_out; ++i) {
       s << " " << i << " (" << f.name_out(i) << "): ";
       if (ml->res[i]) {
         // Print nonzeros
         s << "[";
         for (casadi_int k=0; k<f.nnz_out(i); ++k) {
           if (k!=0) s << ", ";
           DM::print_scalar(s, ml->res[i][k]);
         }
         s << "]\n";
       } else {
         // Ignored output
         s << " N/A\n";
       }
     }
     casadi_message(s.str());
   }
   // Make sure not NaN or Inf
   for (casadi_int i=0; i<n_out; ++i) {
     if (!ml->res[i]) continue;
     if (!std::all_of(ml->res[i], ml->res[i]+f.nnz_out(i), [](double v) { return isfinite(v);})) {
       std::stringstream ss;
       auto it = std::find_if(ml->res[i], ml->res[i] + f.nnz_out(i),
         [](double v) { return !isfinite(v);});
       casadi_int k = std::distance(ml->res[i], it);
       bool is_nan = isnan(ml->res[i][k]);
       ss << name_ << ":" << fcn << " failed: " << (is_nan? "NaN" : "Inf") <<
       " detected for output " << f.name_out(i) << ", at " << f.sparsity_out(i).repr_el(k) << ".";
       if (regularity_check_) {
         casadi_error(ss.str());
       } else {
         if (show_eval_warnings_) casadi_warning(ss.str());
       }
       return -1;
     }
   }
   // Success
   return 0;
 }
References casadi::InterruptHandler::check(), casadi::OracleFunction::get_function(), casadi::OracleFunction::max_num_threads_, casadi::OracleFunction::monitored(), casadi::Function::n_in(), casadi::Function::n_out(), casadi::ProtoFunction::name_, casadi::Function::name_in(), casadi::Function::name_out(), casadi::Function::nnz_in(), casadi::Function::nnz_out(), casadi::Matrix< double >::print_scalar(), casadi::ProtoFunction::regularity_check_, casadi::Sparsity::repr_el(), casadi::OracleFunction::show_eval_warnings_, casadi::Function::sparsity_out(), and casadi::OracleMemory::thread_local_mem.
Referenced by casadi::KinsolInterface::bjac(), casadi::SundialsInterface::calc_daeB(), casadi::SundialsInterface::calc_daeF(), casadi::SundialsInterface::calc_jacF(), casadi::SundialsInterface::calc_jtimesB(), casadi::SundialsInterface::calc_jtimesF(), casadi::SundialsInterface::calc_quadB(), casadi::SundialsInterface::calc_quadF(), casadi::KinsolInterface::djac(), casadi::Nlpsol::eval(), casadi::BonminUserClass::eval_f(), casadi::IpoptUserClass::eval_f(), casadi::BonminUserClass::eval_g(), casadi::IpoptUserClass::eval_g(), casadi::BonminUserClass::eval_grad_f(), casadi::IpoptUserClass::eval_grad_f(), casadi::BonminUserClass::eval_h(), casadi::IpoptUserClass::eval_h(), casadi::BonminUserClass::eval_jac_g(), casadi::IpoptUserClass::eval_jac_g(), casadi::Blocksqp::evaluate(), casadi::Feasiblesqpmethod::feasibility_iterations(), casadi::KinsolInterface::psetup(), casadi::KnitroInterface::solve(), casadi::SnoptInterface::solve(), casadi::WorhpInterface::solve(), casadi::Feasiblesqpmethod::solve(), casadi::Newton::solve(), casadi::Qrsqp::solve(), casadi::Sqpmethod::solve(), casadi::FixedStepIntegrator::stepB(), casadi::FixedStepIntegrator::stepF(), and casadi::SnoptInterface::userfun().
calc_sp_forward()
int casadi::OracleFunction::calc_sp_forward (const std::string & fcn, const bvec_t ** arg, bvec_t ** res, casadi_int * iw, bvec_t * w) const inherited
Definition at line 335 of file oracle_function.cpp.
{
   return get_function(fcn)(arg, res, iw, w);
 }
References casadi::OracleFunction::get_function().
Referenced by casadi::Integrator::bdae_sp_forward(), casadi::Integrator::bquad_sp_forward(), casadi::Integrator::fdae_sp_forward(), and casadi::Integrator::fquad_sp_forward().
calc_sp_reverse()
int casadi::OracleFunction::calc_sp_reverse (const std::string & fcn, bvec_t ** arg, bvec_t ** res, casadi_int * iw, bvec_t * w) const inherited
Definition at line 340 of file oracle_function.cpp.
{
   return get_function(fcn).rev(arg, res, iw, w);
 }
References casadi::OracleFunction::get_function().
Referenced by casadi::Integrator::bdae_sp_reverse(), casadi::Integrator::bquad_sp_reverse(), casadi::Integrator::fdae_sp_reverse(), and casadi::Integrator::fquad_sp_reverse().
call()
template<typename M > void casadi::FunctionInternal::call (const std::vector< M > & arg, std::vector< M > & res, bool always_inline, bool never_inline) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kh
Definition at line 1466 of file function_internal.hpp.
{
     // If all inputs are scalar ...
     if (all_scalar()) {
       // ... and some arguments are matrix-valued with matching dimensions ...
       bool matrix_call = false;
       std::pair<casadi_int, casadi_int> sz;
       for (auto&& a : arg) {
         if (!a.is_scalar() && !a.is_empty()) {
           if (!matrix_call) {
             // Matrix call
             matrix_call = true;
             sz = a.size();
           } else if (a.size()!=sz) {
             // Not same dimensions
             matrix_call = false;
             break;
           }
         }
       }
       // ... then, call multiple times
       if (matrix_call) {
         // Start with zeros
         res.resize(n_out_);
         M z = M::zeros(sz);
         for (auto&& a : res) a = z;
         // Call multiple times
         std::vector<M> arg1 = arg, res1;
         for (casadi_int c=0; c<sz.second; ++c) {
           for (casadi_int r=0; r<sz.first; ++r) {
             // Get scalar arguments
             for (casadi_int i=0; i<arg.size(); ++i) {
               if (arg[i].size()==sz) arg1[i] = arg[i](r, c);
             }
             // Call recursively with scalar arguments
             call(arg1, res1, always_inline, never_inline);
             // Get results
             casadi_assert_dev(res.size() == res1.size());
             for (casadi_int i=0; i<res.size(); ++i) res[i](r, c) = res1[i];
           }
         }
         // All elements assigned
         return;
       }
     }
     // Check if inputs need to be replaced
     casadi_int npar = 1;
     if (!matching_arg(arg, npar)) {
       return call(replace_arg(arg, npar), res, always_inline, never_inline);
     }
     // Call the type-specific method
     call_gen(arg, res, npar, always_inline, never_inline);
   }
References casadi::FunctionInternal::all_scalar(), casadi::FunctionInternal::call_gen(), casadi::FunctionInternal::matching_arg(), casadi::FunctionInternal::n_out_, and casadi::FunctionInternal::replace_arg().
call_forward() [1/2]
void casadi::FunctionInternal::call_forward (const std::vector< MX > & arg, const std::vector< MX > & res, const std::vector< std::vector< MX > > & fseed, std::vector< std::vector< MX > > & fsens, bool always_inline, bool never_inline) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ku
Definition at line 2811 of file function_internal.cpp.
{
     casadi_assert(!(always_inline && never_inline), "Inconsistent options");
     casadi_assert(!always_inline, "Class " + class_name() +
                           " cannot be inlined in an MX expression");
     // Derivative information must be available
     casadi_assert(has_derivative(),
                           "Derivatives cannot be calculated for " + name_);
     // Number of directional derivatives
     casadi_int nfwd = fseed.size();
     fsens.resize(nfwd);
     // Quick return if no seeds
     if (nfwd==0) return;
     // Check if seeds need to have dimensions corrected
     casadi_int npar = 1;
     for (auto&& r : fseed) {
       if (!matching_arg(r, npar)) {
         return FunctionInternal::call_forward(arg, res, replace_fseed(fseed, npar),
                                             fsens, always_inline, never_inline);
       }
     }
     // Calculating full Jacobian and then multiplying
     if (fwdViaJac(nfwd)) {
       // Multiply the Jacobian from the right
       std::vector<MX> darg = arg;
       darg.insert(darg.end(), res.begin(), res.end());
       std::vector<MX> J = jacobian()(darg);
       // Join forward seeds
       std::vector<MX> v(nfwd), all_fseed(n_in_);
       for (size_t i = 0; i < n_in_; ++i) {
         for (size_t d = 0; d < nfwd; ++d) v[d] = vec(fseed.at(d).at(i));
         all_fseed[i] = horzcat(v);
       }
       // Calculate forward sensitivities
       std::vector<MX> all_fsens(n_out_);
       std::vector<MX>::const_iterator J_it = J.begin();
       for (size_t oind = 0; oind < n_out_; ++oind) {
         for (size_t iind = 0; iind < n_in_; ++iind) {
           // Add contribution
           MX a = mtimes(*J_it++, all_fseed[iind]);
           all_fsens[oind] = all_fsens[oind].is_empty(true) ? a : all_fsens[oind] + a;
         }
       }
       // Split forward sensitivities
       for (size_t d = 0; d < nfwd; ++d) fsens[d].resize(n_out_);
       for (size_t i = 0; i < n_out_; ++i) {
         v = horzsplit(all_fsens[i]);
         casadi_assert_dev(v.size() == nfwd);
         for (size_t d = 0; d < nfwd; ++d) fsens[d][i] = reshape(v[d], size_out(i));
       }
     } else {
       // Evaluate in batches
       casadi_assert_dev(enable_forward_ || enable_fd_);
       casadi_int max_nfwd = max_num_dir_;
       if (!enable_fd_) {
         while (!has_forward(max_nfwd)) max_nfwd/=2;
       }
       casadi_int offset = 0;
       while (offset<nfwd) {
         // Number of derivatives, in this batch
         casadi_int nfwd_batch = std::min(nfwd-offset, max_nfwd);
         // All inputs and seeds
         std::vector<MX> darg;
         darg.reserve(n_in_ + n_out_ + n_in_);
         darg.insert(darg.end(), arg.begin(), arg.end());
         darg.insert(darg.end(), res.begin(), res.end());
         std::vector<MX> v(nfwd_batch);
         for (casadi_int i=0; i<n_in_; ++i) {
           for (casadi_int d=0; d<nfwd_batch; ++d) v[d] = fseed[offset+d][i];
           darg.push_back(horzcat(v));
         }
         // Create the evaluation node
         Function dfcn = self().forward(nfwd_batch);
         std::vector<MX> x = dfcn(darg);
         casadi_assert_dev(x.size()==n_out_);
         // Retrieve sensitivities
         for (casadi_int d=0; d<nfwd_batch; ++d) fsens[offset+d].resize(n_out_);
         for (casadi_int i=0; i<n_out_; ++i) {
           if (size2_out(i)>0) {
             v = horzsplit(x[i], size2_out(i));
             casadi_assert_dev(v.size()==nfwd_batch);
           } else {
             v = std::vector<MX>(nfwd_batch, MX(size_out(i)));
           }
           for (casadi_int d=0; d<nfwd_batch; ++d) fsens[offset+d][i] = v[d];
         }
         // Update offset
         offset += nfwd_batch;
       }
     }
   }
References casadi::SharedObjectInternal::class_name(), casadi::FunctionInternal::enable_fd_, casadi::FunctionInternal::enable_forward_, casadi::FunctionInternal::forward(), casadi::FunctionInternal::fwdViaJac(), casadi::FunctionInternal::has_derivative(), casadi::FunctionInternal::has_forward(), casadi::FunctionInternal::jacobian(), casadi::FunctionInternal::matching_arg(), casadi::FunctionInternal::max_num_dir_, casadi::FunctionInternal::n_in_, casadi::FunctionInternal::n_out_, casadi::ProtoFunction::name_, casadi::FunctionInternal::replace_fseed(), casadi::FunctionInternal::size2_out(), and casadi::FunctionInternal::size_out().
Referenced by casadi::Rootfinder::ad_forward(), casadi::Call::ad_forward(), casadi::MXFunction::ad_forward(), casadi::XFunction< DerivedType, MatType, NodeType >::call_forward(), casadi::MX::forward(), casadi::Integrator::get_forward_dae(), and casadi::Scpgen::init().
call_forward() [2/2]
void casadi::FunctionInternal::call_forward (const std::vector< SX > & arg, const std::vector< SX > & res, const std::vector< std::vector< SX > > & fseed, std::vector< std::vector< SX > > & fsens, bool always_inline, bool never_inline) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ku
Definition at line 3030 of file function_internal.cpp.
{
     casadi_assert(!(always_inline && never_inline), "Inconsistent options");
     if (fseed.empty()) { // Quick return if no seeds
       fsens.clear();
       return;
     }
     casadi_error("'forward' (SX) not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
call_gen() [1/2]
void casadi::FunctionInternal::call_gen (const MXVector & arg, MXVector & res, casadi_int npar, bool always_inline, bool never_inline) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kg
Definition at line 3687 of file function_internal.cpp.
{
     if (npar==1) {
       eval_mx(arg, res, always_inline, never_inline);
     } else {
       // Split it up arguments
       std::vector<std::vector<MX>> v(npar, arg);
       std::vector<MX> t;
       for (int i=0; i<n_in_; ++i) {
         if (arg[i].size2()!=size2_in(i)) {
           t = horzsplit(arg[i], size2_in(i));
           casadi_assert_dev(t.size()==npar);
           for (int p=0; p<npar; ++p) v[p][i] = t[p];
         }
       }
       // Unroll the loop
       for (int p=0; p<npar; ++p) {
         eval_mx(v[p], t, always_inline, never_inline);
         v[p] = t;
       }
       // Concatenate results
       t.resize(npar);
       res.resize(n_out_);
       for (int i=0; i<n_out_; ++i) {
         for (int p=0; p<npar; ++p) t[p] = v[p][i];
         res[i] = horzcat(t);
       }
     }
   }
References casadi::FunctionInternal::eval_mx(), casadi::FunctionInternal::n_in_, casadi::FunctionInternal::n_out_, and casadi::FunctionInternal::size2_in().
Referenced by casadi::FunctionInternal::call().
call_gen() [2/2]
template<typename D > void casadi::FunctionInternal::call_gen (const std::vector< Matrix< D > > & arg, std::vector< Matrix< D > > & res, casadi_int npar, bool always_inline, bool never_inline) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kg
Definition at line 1570 of file function_internal.hpp.
{
     casadi_assert(!never_inline, "Call-nodes only possible in MX expressions");
     std::vector< Matrix<D> > arg2 = project_arg(arg, npar);
     // Which arguments require mapped evaluation
     std::vector<bool> mapped(n_in_);
     for (casadi_int i=0; i<n_in_; ++i) {
       mapped[i] = arg[i].size2()!=size2_in(i);
     }
     // Allocate results
     res.resize(n_out_);
     for (casadi_int i=0; i<n_out_; ++i) {
       if (!res[i].sparsity().is_stacked(sparsity_out(i), npar)) {
         res[i] = Matrix<D>::zeros(repmat(sparsity_out(i), 1, npar));
       }
     }
     // Allocate temporary memory if needed
     std::vector<casadi_int> iw_tmp(sz_iw());
     std::vector<D> w_tmp(sz_w());
     // Get pointers to input arguments
     std::vector<const D*> argp(sz_arg());
     for (casadi_int i=0; i<n_in_; ++i) argp[i]=get_ptr(arg2[i]);
     // Get pointers to output arguments
     std::vector<D*> resp(sz_res());
     for (casadi_int i=0; i<n_out_; ++i) resp[i]=get_ptr(res[i]);
     // For all parallel calls
     for (casadi_int p=0; p<npar; ++p) {
       // Call memory-less
       if (eval_gen(get_ptr(argp), get_ptr(resp),
                    get_ptr(iw_tmp), get_ptr(w_tmp), memory(0))) {
         if (error_on_fail_) casadi_error("Evaluation failed");
       }
       // Update offsets
       if (p==npar-1) break;
       for (casadi_int i=0; i<n_in_; ++i) if (mapped[i]) argp[i] += nnz_in(i);
       for (casadi_int i=0; i<n_out_; ++i) resp[i] += nnz_out(i);
     }
   }
References casadi::ProtoFunction::error_on_fail_, casadi::FunctionInternal::eval_gen(), casadi::get_ptr(), casadi::ProtoFunction::memory(), casadi::FunctionInternal::n_in_, casadi::FunctionInternal::n_out_, casadi::FunctionInternal::nnz_in(), casadi::FunctionInternal::nnz_out(), casadi::FunctionInternal::project_arg(), casadi::FunctionInternal::size2_in(), casadi::FunctionInternal::sparsity_out(), casadi::FunctionInternal::sz_arg(), casadi::FunctionInternal::sz_iw(), casadi::FunctionInternal::sz_res(), casadi::FunctionInternal::sz_w(), and casadi::GenericMatrix< Matrix< Scalar > >::zeros().
call_reverse() [1/2]
void casadi::FunctionInternal::call_reverse (const std::vector< MX > & arg, const std::vector< MX > & res, const std::vector< std::vector< MX > > & aseed, std::vector< std::vector< MX > > & asens, bool always_inline, bool never_inline) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kv
Definition at line 2916 of file function_internal.cpp.
{
     casadi_assert(!(always_inline && never_inline), "Inconsistent options");
     casadi_assert(!always_inline, "Class " + class_name() +
                           " cannot be inlined in an MX expression");
     // Derivative information must be available
     casadi_assert(has_derivative(),
                           "Derivatives cannot be calculated for " + name_);
     // Number of directional derivatives
     casadi_int nadj = aseed.size();
     asens.resize(nadj);
     // Quick return if no seeds
     if (nadj==0) return;
     // Check if seeds need to have dimensions corrected
     casadi_int npar = 1;
     for (auto&& r : aseed) {
       if (!matching_res(r, npar)) {
         return FunctionInternal::call_reverse(arg, res, replace_aseed(aseed, npar),
                                             asens, always_inline, never_inline);
       }
     }
     // Calculating full Jacobian and then multiplying likely cheaper
     if (adjViaJac(nadj)) {
       // Multiply the transposed Jacobian from the right
       std::vector<MX> darg = arg;
       darg.insert(darg.end(), res.begin(), res.end());
       std::vector<MX> J = jacobian()(darg);
       // Join adjoint seeds
       std::vector<MX> v(nadj), all_aseed(n_out_);
       for (size_t i = 0; i < n_out_; ++i) {
         for (size_t d = 0; d < nadj; ++d) v[d] = vec(aseed.at(d).at(i));
         all_aseed[i] = horzcat(v);
       }
       // Calculate adjoint sensitivities
       std::vector<MX> all_asens(n_in_);
       std::vector<MX>::const_iterator J_it = J.begin();
       for (size_t oind = 0; oind < n_out_; ++oind) {
         for (size_t iind = 0; iind < n_in_; ++iind) {
           // Add contribution
           MX a = mtimes((*J_it++).T(), all_aseed[oind]);
           all_asens[iind] = all_asens[iind].is_empty(true) ? a : all_asens[iind] + a;
         }
       }
       // Split adjoint sensitivities
       for (size_t d = 0; d < nadj; ++d) asens[d].resize(n_in_);
       for (size_t i = 0; i < n_in_; ++i) {
         v = horzsplit(all_asens[i]);
         casadi_assert_dev(v.size() == nadj);
         for (size_t d = 0; d < nadj; ++d) {
           if (asens[d][i].is_empty(true)) {
             asens[d][i] = reshape(v[d], size_in(i));
           } else {
             asens[d][i] += reshape(v[d], size_in(i));
           }
         }
       }
     } else {
       // Evaluate in batches
       casadi_assert_dev(enable_reverse_);
       casadi_int max_nadj = max_num_dir_;
       while (!has_reverse(max_nadj)) max_nadj/=2;
       casadi_int offset = 0;
       while (offset<nadj) {
         // Number of derivatives, in this batch
         casadi_int nadj_batch =  std::min(nadj-offset, max_nadj);
         // All inputs and seeds
         std::vector<MX> darg;
         darg.reserve(n_in_ + n_out_ + n_out_);
         darg.insert(darg.end(), arg.begin(), arg.end());
         darg.insert(darg.end(), res.begin(), res.end());
         std::vector<MX> v(nadj_batch);
         for (casadi_int i=0; i<n_out_; ++i) {
           for (casadi_int d=0; d<nadj_batch; ++d) v[d] = aseed[offset+d][i];
           darg.push_back(horzcat(v));
         }
         // Create the evaluation node
         Function dfcn = self().reverse(nadj_batch);
         std::vector<MX> x = dfcn(darg);
         casadi_assert_dev(x.size()==n_in_);
         // Retrieve sensitivities
         for (casadi_int d=0; d<nadj_batch; ++d) asens[offset+d].resize(n_in_);
         for (casadi_int i=0; i<n_in_; ++i) {
           if (size2_in(i)>0) {
             v = horzsplit(x[i], size2_in(i));
             casadi_assert_dev(v.size()==nadj_batch);
           } else {
             v = std::vector<MX>(nadj_batch, MX(size_in(i)));
           }
           for (casadi_int d=0; d<nadj_batch; ++d) {
             if (asens[offset+d][i].is_empty(true)) {
               asens[offset+d][i] = v[d];
             } else {
               asens[offset+d][i] += v[d];
             }
           }
         }
         // Update offset
         offset += nadj_batch;
       }
     }
   }
References casadi::FunctionInternal::adjViaJac(), casadi::SharedObjectInternal::class_name(), casadi::FunctionInternal::enable_reverse_, casadi::FunctionInternal::has_derivative(), casadi::FunctionInternal::has_reverse(), casadi::FunctionInternal::jacobian(), casadi::FunctionInternal::matching_res(), casadi::FunctionInternal::max_num_dir_, casadi::FunctionInternal::n_in_, casadi::FunctionInternal::n_out_, casadi::ProtoFunction::name_, casadi::FunctionInternal::replace_aseed(), casadi::FunctionInternal::reverse(), casadi::FunctionInternal::size2_in(), and casadi::FunctionInternal::size_in().
Referenced by casadi::Rootfinder::ad_reverse(), casadi::MXFunction::ad_reverse(), casadi::Call::ad_reverse(), casadi::XFunction< DerivedType, MatType, NodeType >::call_reverse(), casadi::Scpgen::init(), and casadi::MX::reverse().
call_reverse() [2/2]
void casadi::FunctionInternal::call_reverse (const std::vector< SX > & arg, const std::vector< SX > & res, const std::vector< std::vector< SX > > & aseed, std::vector< std::vector< SX > > & asens, bool always_inline, bool never_inline) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kv
Definition at line 3043 of file function_internal.cpp.
{
     casadi_assert(!(always_inline && never_inline), "Inconsistent options");
     if (aseed.empty()) { // Quick return if no seeds
       asens.clear();
       return;
     }
     casadi_error("'reverse' (SX) not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
callback()
int casadi::Nlpsol::callback (NlpsolMemory * m) const inherited
Definition at line 1186 of file nlpsol.cpp.
{
     // Quick return if no callback function
     if (fcallback_.is_null()) return 0;
     // Callback inputs
     std::fill_n(m->arg, fcallback_.n_in(), nullptr);
     auto d_nlp = &m->d_nlp;
     m->arg[NLPSOL_X] = d_nlp->z;
     m->arg[NLPSOL_F] = &d_nlp->objective;
     m->arg[NLPSOL_G] = d_nlp->z + nx_;
     m->arg[NLPSOL_LAM_G] = d_nlp->lam + nx_;
     m->arg[NLPSOL_LAM_X] = d_nlp->lam;
     // Callback outputs
     std::fill_n(m->res, fcallback_.n_out(), nullptr);
     double ret = 0;
     m->res[0] = &ret;
     // Start timer
     m->fstats.at("callback_fun").tic();
     try {
       // Evaluate
       fcallback_(m->arg, m->res, m->iw, m->w, 0);
     } catch(KeyboardInterruptException& ex) {
       (void)ex;  // unused
       throw;
     } catch(std::exception& ex) {
       print("WARNING: intermediate_callback error: %s\n", ex.what());
       if (!iteration_callback_ignore_errors_) ret=1;
     }
     // User user interruption?
     if (static_cast<casadi_int>(ret)) return 1;
     // Stop timer
     m->fstats.at("callback_fun").toc();
     return 0;
   }
References casadi::OracleMemory::arg, casadi::NlpsolMemory::d_nlp, casadi::Nlpsol::fcallback_, casadi::ProtoFunctionMemory::fstats, casadi::SharedObject::is_null(), casadi::Nlpsol::iteration_callback_ignore_errors_, casadi::OracleMemory::iw, casadi::Function::n_in(), casadi::Function::n_out(), casadi::NLPSOL_F, casadi::NLPSOL_G, casadi::NLPSOL_LAM_G, casadi::NLPSOL_LAM_X, casadi::NLPSOL_X, casadi::Nlpsol::nx_, casadi::ProtoFunction::print(), casadi::OracleMemory::res, casadi::OracleMemory::w, and casadi::CasadiException::what().
Referenced by casadi::Feasiblesqpmethod::solve(), casadi::Qrsqp::solve(), and casadi::Sqpmethod::solve().
change_option()
void casadi::FunctionInternal::change_option (const std::string & option_name, const GenericType & option_value) override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_k5
Reimplemented from casadi::ProtoFunction.
Reimplemented in casadi::MXFunction.
Definition at line 414 of file function_internal.cpp.
{
     if (option_name == "print_in") {
       print_in_ = option_value;
     } else if (option_name == "print_out") {
       print_out_ = option_value;
     } else if (option_name=="ad_weight") {
       ad_weight_ = option_value;
     } else if (option_name=="ad_weight_sp") {
       ad_weight_sp_ = option_value;
     } else if (option_name=="dump") {
       dump_ = option_value;
     } else if (option_name=="dump_in") {
       dump_in_ = option_value;
     } else if (option_name=="dump_out") {
       dump_out_ = option_value;
     } else if (option_name=="dump_dir") {
       dump_dir_ = option_value.to_string();
     } else if (option_name=="dump_format") {
       dump_format_ = option_value.to_string();
     } else {
       // Option not found - continue to base classes
       ProtoFunction::change_option(option_name, option_value);
     }
   }
References casadi::FunctionInternal::ad_weight_, casadi::FunctionInternal::ad_weight_sp_, casadi::ProtoFunction::change_option(), casadi::FunctionInternal::dump_, casadi::FunctionInternal::dump_dir_, casadi::FunctionInternal::dump_format_, casadi::FunctionInternal::dump_in_, casadi::FunctionInternal::dump_out_, casadi::FunctionInternal::print_in_, casadi::FunctionInternal::print_out_, and casadi::GenericType::to_string().
Referenced by casadi::MXFunction::change_option().
check_arg()
template<typename M > void casadi::FunctionInternal::check_arg (const std::vector< M > & arg, casadi_int & npar) const inherited
Raises errors.
Parameters
npar[in] normal usage: 1, disallow pararallel calls: -1
[out] npar max number of horizontal repetitions across all arguments (or -1)
Extra doc: https://github.com/casadi/casadi/wiki/L_ki
Definition at line 1617 of file function_internal.hpp.
{
     casadi_assert(arg.size()==n_in_, "Incorrect number of inputs: Expected "
                           + str(n_in_) + ", got " + str(arg.size()));
     for (casadi_int i=0; i<n_in_; ++i) {
       if (!check_mat(arg[i].sparsity(), sparsity_in(i), npar)) {
         // Dimensions
         std::string d_arg = str(arg[i].size1()) + "-by-" + str(arg[i].size2());
         std::string d_in = str(size1_in(i)) + "-by-" + str(size2_in(i));
         std::string e = "Input " + str(i) + " (" + name_in_[i] + ") has mismatching shape. "
                      "Got " + d_arg + ". Allowed dimensions, in general, are:\n"
                      " - The input dimension N-by-M (here " + d_in + ")\n"
                      " - A scalar, i.e. 1-by-1\n"
                      " - M-by-N if N=1 or M=1 (i.e. a transposed vector)\n"
                      " - N-by-M1 if K*M1=M for some K (argument repeated horizontally)\n";
         if (npar!=-1) {
           e += " - N-by-P*M, indicating evaluation with multiple arguments (P must be a "
                      "multiple of " + str(npar) + " for consistency with previous inputs)";
         }
         casadi_error(e);
       }
     }
   }
References casadi::FunctionInternal::check_mat(), casadi::FunctionInternal::n_in_, casadi::FunctionInternal::name_in_, casadi::FunctionInternal::size1_in(), casadi::FunctionInternal::size2_in(), casadi::FunctionInternal::sparsity_in(), and casadi::str().
Referenced by casadi::FunctionInternal::mapsum_mx(), and casadi::FunctionInternal::matching_arg().
check_inputs()
void casadi::Nlpsol::check_inputs (void * mem) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1nx
Definition at line 587 of file nlpsol.cpp.
{
     auto m = static_cast<NlpsolMemory*>(mem);
     auto d_nlp = &m->d_nlp;
     // Skip check?
     if (!inputs_check_) return;
     const double inf = std::numeric_limits<double>::infinity();
     // Number of equality constraints
     casadi_int n_eq = 0;
     // Detect ill-posed problems (simple bounds)
     for (casadi_int i=0; i<nx_; ++i) {
       double lb = d_nlp->lbx ? d_nlp->lbx[i] : get_default_in(NLPSOL_LBX);
       double ub = d_nlp->ubx ? d_nlp->ubx[i] : get_default_in(NLPSOL_UBX);
       double x0 = d_nlp->x0 ? d_nlp->x0[i] : get_default_in(NLPSOL_X0);
       casadi_assert(lb <= ub && lb!=inf && ub!=-inf,
           "Ill-posed problem detected: "
           "LBX[" + str(i) + "] <= UBX[" + str(i) + "] was violated. "
           "Got LBX[" + str(i) + "]=" + str(lb) + " and UBX[" + str(i) + "] = " + str(ub) + ".");
       if (warn_initial_bounds_ && (x0>ub || x0<lb)) {
         casadi_warning("Nlpsol: The initial guess does not satisfy LBX and UBX. "
           "Option 'warn_initial_bounds' controls this warning.");
         break;
       }
       if (lb==ub) n_eq++;
     }
     // Detect ill-posed problems (nonlinear bounds)
     for (casadi_int i=0; i<nnz_out(NLPSOL_G); ++i) {
       double lb = d_nlp->lbg ? d_nlp->lbg[i] : get_default_in(NLPSOL_LBG);
       double ub = d_nlp->ubg ? d_nlp->ubg[i] : get_default_in(NLPSOL_UBG);
       casadi_assert(lb <= ub && lb!=inf && ub!=-inf,
         "Ill-posed problem detected: "
         "LBG[" + str(i) + "] <= UBG[" + str(i) + "] was violated. "
         "Got LBG[" + str(i) + "] = " + str(lb) + " and UBG[" + str(i) + "] = " + str(ub) + ".");
       if (lb==ub) n_eq++;
     }
     // Make sure enough degrees of freedom
     using casadi::str; // Workaround, MingGW bug, cf. CasADi issue #890
     if (n_eq> nx_) {
       casadi_warning("NLP is overconstrained: There are " + str(n_eq) +
       " equality constraints but only " + str(nx_) + " variables.");
     }
   }
References casadi::NlpsolMemory::d_nlp, casadi::Nlpsol::get_default_in(), casadi::inf, casadi::FunctionInternal::inputs_check_, casadi::NLPSOL_G, casadi::NLPSOL_LBG, casadi::NLPSOL_LBX, casadi::NLPSOL_UBG, casadi::NLPSOL_UBX, casadi::NLPSOL_X0, casadi::FunctionInternal::nnz_out(), casadi::Nlpsol::nx_, casadi::str(), and casadi::Nlpsol::warn_initial_bounds_.
Referenced by casadi::Nlpsol::eval().
check_mat()
bool casadi::FunctionInternal::check_mat (const Sparsity & arg, const Sparsity & inp, casadi_int & npar) static inherited
Helper function
Parameters
npar[in] normal usage: 1, disallow pararallel calls: -1
npar[out] required number of parallel calls (or -1)
Definition at line 3237 of file function_internal.cpp.
{
     // Matching dimensions
     if (arg.size()==inp.size()) return true;
     // Calling with empty matrix - set all to zero
     if (arg.is_empty()) return true;
     // Calling with a scalar - set all
     if (arg.is_scalar()) return true;
     // Vectors that are transposes of each other
     if (arg.is_vector() && inp.size()==std::make_pair(arg.size2(), arg.size1())) return true;
     // Horizontal repmat
     if (arg.size1()==inp.size1() && arg.size2()>0 && inp.size2()>0
         && inp.size2()%arg.size2()==0) return true;
     if (npar==-1) return false;
     // Evaluate with multiple arguments
     if (arg.size1()==inp.size1() && arg.size2()>0 && inp.size2()>0
         && arg.size2()%(npar*inp.size2())==0) {
       npar *= arg.size2()/(npar*inp.size2());
       return true;
     }
     // No match
     return false;
   }
References casadi::Sparsity::is_empty(), casadi::Sparsity::is_scalar(), casadi::Sparsity::is_vector(), casadi::Sparsity::size(), casadi::Sparsity::size1(), and casadi::Sparsity::size2().
Referenced by casadi::FunctionInternal::check_arg(), casadi::FunctionInternal::check_res(), and casadi::FunctionInternal::mapsum_mx().
check_res()
template<typename M > void casadi::FunctionInternal::check_res (const std::vector< M > & res, casadi_int & npar) const inherited
Raises errors.
Parameters
npar[in] normal usage: 1, disallow pararallel calls: -1
[out] npar max number of horizontal repetitions across all arguments (or -1)
Extra doc: https://github.com/casadi/casadi/wiki/L_kj
Definition at line 1641 of file function_internal.hpp.
{
     casadi_assert(res.size()==n_out_, "Incorrect number of outputs: Expected "
                           + str(n_out_) + ", got " + str(res.size()));
     for (casadi_int i=0; i<n_out_; ++i) {
       casadi_assert(check_mat(res[i].sparsity(), sparsity_out(i), npar),
                     "Output " + str(i) + " (" + name_out_[i] + ") has mismatching shape. "
                     "Expected " + str(size_out(i)) + ", got " + str(res[i].size()));
     }
   }
References casadi::FunctionInternal::check_mat(), casadi::FunctionInternal::n_out_, casadi::FunctionInternal::name_out_, casadi::FunctionInternal::size_out(), casadi::FunctionInternal::sparsity_out(), and casadi::str().
Referenced by casadi::FunctionInternal::matching_res().
checkout()
int casadi::ProtoFunction::checkout () const inherited
Definition at line 3440 of file function_internal.cpp.
{
 #ifdef CASADI_WITH_THREAD
     std::lock_guard<std::mutex> lock(mtx_);
 #endif //CASADI_WITH_THREAD
     if (unused_.empty()) {
       // Allocate a new memory object
       void* m = alloc_mem();
       mem_.push_back(m);
       if (init_mem(m)) {
         casadi_error("Failed to create or initialize memory object");
       }
       return mem_.size()-1;
     } else {
       // Use an unused memory object
       int m = unused_.top();
       unused_.pop();
       return m;
     }
   }
References casadi::ProtoFunction::alloc_mem(), and casadi::ProtoFunction::init_mem().
Referenced by casadi::ProtoFunction::finalize(), and casadi::FunctionBuffer::FunctionBuffer().
class_name()
std::string casadi::AmplInterface::class_name () const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_1o4
Reimplemented from casadi::Nlpsol.
Definition at line 65 of file ampl_interface.hpp.
 { return "AmplInterface";}
clear_mem()
void casadi::ProtoFunction::clear_mem () inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_jq
Definition at line 3332 of file function_internal.cpp.
{
     for (auto&& i : mem_) {
       if (i!=nullptr) free_mem(i);
     }
     mem_.clear();
   }
References casadi::ProtoFunction::free_mem().
Referenced by ~AmplInterface(), casadi::Blocksqp::~Blocksqp(), casadi::BonminInterface::~BonminInterface(), casadi::BSplineInterpolant::~BSplineInterpolant(), casadi::CallbackInternal::~CallbackInternal(), casadi::CbcInterface::~CbcInterface(), casadi::ClpInterface::~ClpInterface(), casadi::CplexInterface::~CplexInterface(), casadi::CsparseInterface::~CsparseInterface(), casadi::CvodesInterface::~CvodesInterface(), casadi::External::~External(), casadi::FastNewton::~FastNewton(), casadi::Feasiblesqpmethod::~Feasiblesqpmethod(), casadi::FiniteDiff::~FiniteDiff(), casadi::FixedStepIntegrator::~FixedStepIntegrator(), casadi::GurobiInterface::~GurobiInterface(), casadi::HighsInterface::~HighsInterface(), casadi::HpipmInterface::~HpipmInterface(), casadi::HpmpcInterface::~HpmpcInterface(), casadi::IdasInterface::~IdasInterface(), casadi::ImplicitToNlp::~ImplicitToNlp(), casadi::IpoptInterface::~IpoptInterface(), casadi::Ipqp::~Ipqp(), casadi::JitFunction::~JitFunction(), casadi::KinsolInterface::~KinsolInterface(), casadi::KnitroInterface::~KnitroInterface(), casadi::LapackLu::~LapackLu(), casadi::LapackQr::~LapackQr(), casadi::LinearInterpolant::~LinearInterpolant(), casadi::LinearInterpolantJac::~LinearInterpolantJac(), casadi::LinsolLdl::~LinsolLdl(), casadi::LinsolQr::~LinsolQr(), casadi::LinsolTridiag::~LinsolTridiag(), casadi::Lsqr::~Lsqr(), casadi::Ma27Interface::~Ma27Interface(), casadi::Map::~Map(), casadi::MapSum::~MapSum(), casadi::MumpsInterface::~MumpsInterface(), casadi::MXFunction::~MXFunction(), casadi::Newton::~Newton(), casadi::Nlpsol::~Nlpsol(), casadi::OmpMap::~OmpMap(), casadi::OoqpInterface::~OoqpInterface(), casadi::OsqpInterface::~OsqpInterface(), casadi::ProxqpInterface::~ProxqpInterface(), casadi::QpoasesInterface::~QpoasesInterface(), casadi::QpToNlp::~QpToNlp(), casadi::Qrqp::~Qrqp(), casadi::Qrsqp::~Qrsqp(), casadi::Scpgen::~Scpgen(), casadi::SlicotDple::~SlicotDple(), casadi::SlicotExpm::~SlicotExpm(), casadi::SnoptInterface::~SnoptInterface(), casadi::Sqpmethod::~Sqpmethod(), casadi::SuperscsInterface::~SuperscsInterface(), casadi::Switch::~Switch(), casadi::SymbolicQr::~SymbolicQr(), casadi::ThreadMap::~ThreadMap(), and casadi::WorhpInterface::~WorhpInterface().
codegen()
void casadi::FunctionInternal::codegen (CodeGenerator & g, const std::string & fname) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lm
Definition at line 2218 of file function_internal.cpp.
{
     // Define function
     g << "/* " << definition() << " */\n";
     g << "static " << signature(fname) << " {\n";
     // Reset local variables, flush buffer
     g.flush(g.body);
     g.scope_enter();
     // Generate function body (to buffer)
     codegen_body(g);
     g.scope_exit();
     // Finalize the function
     g << "return 0;\n";
     g << "}\n\n";
     // Flush to function body
     g.flush(g.body);
   }
References casadi::CodeGenerator::body, casadi::FunctionInternal::codegen_body(), casadi::FunctionInternal::definition(), casadi::CodeGenerator::flush(), casadi::CodeGenerator::scope_enter(), casadi::CodeGenerator::scope_exit(), and casadi::FunctionInternal::signature().
Referenced by casadi::CodeGenerator::add_dependency().
codegen_alloc_mem()
void casadi::FunctionInternal::codegen_alloc_mem (CodeGenerator & g) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lt
Reimplemented in casadi::External.
Definition at line 2250 of file function_internal.cpp.
{
     bool needs_mem = !codegen_mem_type().empty();
     if (needs_mem) {
     std::string name = codegen_name(g, false);
     std::string mem_counter = g.shorthand(name + "_mem_counter");
     g << "return " + mem_counter + "++;\n";
     }
   }
References casadi::FunctionInternal::codegen_mem_type(), casadi::FunctionInternal::codegen_name(), and casadi::CodeGenerator::shorthand().
Referenced by casadi::CodeGenerator::add_dependency().
codegen_body()
void casadi::FunctionInternal::codegen_body (CodeGenerator & g) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_m0
Reimplemented in casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >, casadi::Sqpmethod, casadi::Qrqp, casadi::LinearInterpolantJac, casadi::LinearInterpolant, casadi::Feasiblesqpmethod, casadi::FastNewton, casadi::BSplineInterpolant, casadi::OsqpInterface, casadi::HpipmInterface, casadi::HighsInterface, casadi::SXFunction, casadi::Switch, casadi::MXFunction, casadi::MapSum, casadi::ThreadMap, casadi::OmpMap, casadi::Map, casadi::JitFunction, casadi::FiniteDiff, and casadi::External.
Definition at line 2630 of file function_internal.cpp.
{
     casadi_warning("The function \"" + name_ + "\", which is of type \""
                    + class_name() + "\" cannot be code generated. The generation "
                    "will proceed, but compilation of the code will not be possible.");
     g << "#error Code generation not supported for " << class_name() << "\n";
   }
References casadi::SharedObjectInternal::class_name(), and casadi::ProtoFunction::name_.
Referenced by casadi::FunctionInternal::codegen(), and casadi::BSplineInterpolant::codegen_body().
codegen_checkout()
void casadi::FunctionInternal::codegen_checkout (CodeGenerator & g) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lw
Reimplemented in casadi::External.
Definition at line 2259 of file function_internal.cpp.
{
     std::string name = codegen_name(g, false);
     std::string stack_counter = g.shorthand(name + "_unused_stack_counter");
     std::string stack = g.shorthand(name + "_unused_stack");
     std::string mem_counter = g.shorthand(name + "_mem_counter");
     std::string mem_array = g.shorthand(name + "_mem");
     std::string alloc_mem = g.shorthand(name + "_alloc_mem");
     std::string init_mem = g.shorthand(name + "_init_mem");
     g.auxiliaries << "static int " << mem_counter  << " = 0;\n";
     g.auxiliaries << "static int " << stack_counter  << " = -1;\n";
     g.auxiliaries << "static int " << stack << "[CASADI_MAX_NUM_THREADS];\n";
     g.auxiliaries << "static " << codegen_mem_type() <<
                " " << mem_array << "[CASADI_MAX_NUM_THREADS];\n\n";
     g << "int mid;\n";
     g << "if (" << stack_counter << ">=0) {\n";
     g << "return " << stack << "[" << stack_counter << "--];\n";
     g << "} else {\n";
     g << "if (" << mem_counter << "==CASADI_MAX_NUM_THREADS) return -1;\n";
     g << "mid = " << alloc_mem << "();\n";
     g << "if (mid<0) return -1;\n";
     g << "if(" << init_mem << "(mid)) return -1;\n";
     g << "return mid;\n";
     g << "}\n";
   }
References casadi::ProtoFunction::alloc_mem(), casadi::CodeGenerator::auxiliaries, casadi::FunctionInternal::codegen_mem_type(), casadi::FunctionInternal::codegen_name(), casadi::ProtoFunction::init_mem(), and casadi::CodeGenerator::shorthand().
Referenced by casadi::CodeGenerator::add_dependency().
codegen_declarations()
void casadi::FunctionInternal::codegen_declarations (CodeGenerator & g) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lz
Reimplemented in casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >, casadi::Sqpmethod, casadi::Feasiblesqpmethod, casadi::FastNewton, casadi::BSplineInterpolant, casadi::SXFunction, casadi::Switch, casadi::MXFunction, casadi::MapSum, casadi::Map, casadi::FiniteDiff, and casadi::External.
Definition at line 2626 of file function_internal.cpp.
{
     // Nothing to declare
   }
Referenced by casadi::CodeGenerator::add_dependency(), and casadi::BSplineInterpolant::codegen_declarations().
codegen_decref()
virtual void casadi::FunctionInternal::codegen_decref (CodeGenerator & g) const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ls
Reimplemented in casadi::MXFunction, and casadi::External.
Definition at line 806 of file function_internal.hpp.
 {}
Referenced by casadi::CodeGenerator::add_dependency(), and casadi::FunctionInternal::codegen_meta().
codegen_free_mem()
virtual void casadi::FunctionInternal::codegen_free_mem (CodeGenerator & g) const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lv
Reimplemented in casadi::OsqpInterface, casadi::HighsInterface, and casadi::External.
Definition at line 821 of file function_internal.hpp.
 {}
Referenced by casadi::CodeGenerator::add_dependency().
codegen_incref()
virtual void casadi::FunctionInternal::codegen_incref (CodeGenerator & g) const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lr
Reimplemented in casadi::MXFunction, and casadi::External.
Definition at line 801 of file function_internal.hpp.
 {}
Referenced by casadi::CodeGenerator::add_dependency(), and casadi::FunctionInternal::codegen_meta().
codegen_init_mem()
void casadi::FunctionInternal::codegen_init_mem (CodeGenerator & g) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lu
Reimplemented in casadi::OsqpInterface, casadi::HighsInterface, and casadi::External.
Definition at line 2246 of file function_internal.cpp.
{
     g << "return 0;\n";
   }
Referenced by casadi::CodeGenerator::add_dependency().
codegen_mem()
std::string casadi::FunctionInternal::codegen_mem (CodeGenerator & g, const std::string & index = "mem") const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lq
Definition at line 2620 of file function_internal.cpp.
{
     std::string name = codegen_name(g, false);
     std::string mem_array = g.shorthand(name + "_mem");
     return mem_array+"[" + index + "]";
   }
References casadi::FunctionInternal::codegen_name(), and casadi::CodeGenerator::shorthand().
Referenced by casadi::HighsInterface::codegen_body(), casadi::OsqpInterface::codegen_body(), casadi::HighsInterface::codegen_free_mem(), casadi::OsqpInterface::codegen_free_mem(), casadi::HighsInterface::codegen_init_mem(), and casadi::OsqpInterface::codegen_init_mem().
codegen_mem_type()
virtual std::string casadi::FunctionInternal::codegen_mem_type () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_m1
Reimplemented in casadi::OsqpInterface, casadi::HighsInterface, and casadi::External.
Definition at line 851 of file function_internal.hpp.
 { return ""; }
Referenced by casadi::CodeGenerator::add_dependency(), casadi::FunctionInternal::codegen_alloc_mem(), casadi::FunctionInternal::codegen_checkout(), casadi::FunctionInternal::codegen_meta(), and casadi::CodeGenerator::operator()().
codegen_meta()
void casadi::FunctionInternal::codegen_meta (CodeGenerator & g) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ln
Definition at line 2296 of file function_internal.cpp.
{
     bool needs_mem = !codegen_mem_type().empty();
     g << g.declare("int " + name_ + "_alloc_mem(void)") << " {\n";
     if (needs_mem) {
       g << "return " << codegen_name(g) << "_alloc_mem();\n";
     } else {
       g << "return 0;\n";
     }
     g << "}\n\n";
     g << g.declare("int " + name_ + "_init_mem(int mem)") << " {\n";
     if (needs_mem) {
       g << "return " << codegen_name(g) << "_init_mem(mem);\n";
     } else {
       g << "return 0;\n";
     }
     g << "}\n\n";
     g << g.declare("void " + name_ + "_free_mem(int mem)") << " {\n";
     if (needs_mem) {
       g << codegen_name(g) << "_free_mem(mem);\n";
     }
     g << "}\n\n";
     // Checkout/release routines
     g << g.declare("int " + name_ + "_checkout(void)") << " {\n";
     if (needs_mem) {
       g << "return " << codegen_name(g) << "_checkout();\n";
     } else {
       g << "return 0;\n";
     }
     g << "}\n\n";
     if (needs_mem) {
       g << g.declare("void " + name_ + "_release(int mem)") << " {\n";
       g << codegen_name(g) << "_release(mem);\n";
     } else {
       g << g.declare("void " + name_ + "_release(int mem)") << " {\n";
     }
     g << "}\n\n";
     // Reference counter routines
     g << g.declare("void " + name_ + "_incref(void)") << " {\n";
     codegen_incref(g);
     g << "}\n\n"
       << g.declare("void " + name_ + "_decref(void)") << " {\n";
     codegen_decref(g);
     g << "}\n\n";
     // Number of inputs and outptus
     g << g.declare("casadi_int " + name_ + "_n_in(void)")
       << " { return " << n_in_ << ";}\n\n"
       << g.declare("casadi_int " + name_ + "_n_out(void)")
       << " { return " << n_out_ << ";}\n\n";
     // Default inputs
     g << g.declare("casadi_real " + name_ + "_default_in(casadi_int i)") << " {\n"
       << "switch (i) {\n";
     for (casadi_int i=0; i<n_in_; ++i) {
       double def = get_default_in(i);
       if (def!=0) g << "case " << i << ": return " << g.constant(def) << ";\n";
     }
     g << "default: return 0;\n}\n"
       << "}\n\n";
     // Input names
     g << g.declare("const char* " + name_ + "_name_in(casadi_int i)") << " {\n"
       << "switch (i) {\n";
     for (casadi_int i=0; i<n_in_; ++i) {
       g << "case " << i << ": return \"" << name_in_[i] << "\";\n";
     }
     g << "default: return 0;\n}\n"
       << "}\n\n";
     // Output names
     g << g.declare("const char* " + name_ + "_name_out(casadi_int i)") << " {\n"
       << "switch (i) {\n";
     for (casadi_int i=0; i<n_out_; ++i) {
       g << "case " << i << ": return \"" << name_out_[i] << "\";\n";
     }
     g << "default: return 0;\n}\n"
       << "}\n\n";
     // Codegen sparsities
     codegen_sparsities(g);
     // Determine work vector size
     casadi_int sz_w_codegen = sz_w();
     if (is_a("SXFunction", true) && !g.avoid_stack()) sz_w_codegen = 0;
     // Function that returns work vector lengths
     g << g.declare(
         "int " + name_ + "_work(casadi_int *sz_arg, casadi_int* sz_res, "
         "casadi_int *sz_iw, casadi_int *sz_w)")
       << " {\n"
       << "if (sz_arg) *sz_arg = " << sz_arg() << ";\n"
       << "if (sz_res) *sz_res = " << sz_res() << ";\n"
       << "if (sz_iw) *sz_iw = " << sz_iw() << ";\n"
       << "if (sz_w) *sz_w = " << sz_w_codegen << ";\n"
       << "return 0;\n"
       << "}\n\n";
     // Also add to header file to allow getting
      if (g.with_header) {
       g.header
         << "#define " << name_ << "_SZ_ARG " << sz_arg() << "\n"
         << "#define " << name_ << "_SZ_RES " << sz_res() << "\n"
         << "#define " << name_ << "_SZ_IW " << sz_iw() << "\n"
         << "#define " << name_ << "_SZ_W " << sz_w() << "\n";
      }
     // Which inputs are differentiable
     if (!all(is_diff_in_)) {
       g << g.declare("int " + name_ + "_diff_in(casadi_int i)") << " {\n"
         << "switch (i) {\n";
       for (casadi_int i=0; i<n_in_; ++i) {
         g << "case " << i << ": return " << is_diff_in_[i] << ";\n";
       }
       g << "default: return -1;\n}\n"
         << "}\n\n";
     }
     // Which outputs are differentiable
     if (!all(is_diff_out_)) {
       g << g.declare("int " + name_ + "_diff_out(casadi_int i)") << " {\n"
         << "switch (i) {\n";
       for (casadi_int i=0; i<n_out_; ++i) {
         g << "case " << i << ": return " << is_diff_out_[i] << ";\n";
       }
       g << "default: return -1;\n}\n"
         << "}\n\n";
     }
     // Generate mex gateway for the function
     if (g.mex) {
       // Begin conditional compilation
       g << "#ifdef MATLAB_MEX_FILE\n";
       // Declare wrapper
       g << "void mex_" << name_
         << "(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {\n"
         << "casadi_int i;\n";
       g << "int mem;\n";
       // Work vectors, including input and output buffers
       casadi_int i_nnz = nnz_in(), o_nnz = nnz_out();
       size_t sz_w = this->sz_w();
       for (casadi_int i=0; i<n_in_; ++i) {
         const Sparsity& s = sparsity_in_[i];
         sz_w = std::max(sz_w, static_cast<size_t>(s.size1())); // To be able to copy a column
         sz_w = std::max(sz_w, static_cast<size_t>(s.size2())); // To be able to copy a row
       }
       sz_w += i_nnz + o_nnz;
       g << CodeGenerator::array("casadi_real", "w", sz_w);
       g << CodeGenerator::array("casadi_int", "iw", sz_iw());
       std::string fw = "w+" + str(i_nnz + o_nnz);
       // Copy inputs to buffers
       casadi_int offset=0;
       g << CodeGenerator::array("const casadi_real*", "arg", sz_arg(), "{0}");
       // Allocate output buffers
       g << "casadi_real* res[" << sz_res() << "] = {0};\n";
       // Check arguments
       g << "if (argc>" << n_in_ << ") mexErrMsgIdAndTxt(\"Casadi:RuntimeError\","
         << "\"Evaluation of \\\"" << name_ << "\\\" failed. Too many input arguments "
         << "(%d, max " << n_in_ << ")\", argc);\n";
       g << "if (resc>" << n_out_ << ") mexErrMsgIdAndTxt(\"Casadi:RuntimeError\","
         << "\"Evaluation of \\\"" << name_ << "\\\" failed. "
         << "Too many output arguments (%d, max " << n_out_ << ")\", resc);\n";
       for (casadi_int i=0; i<n_in_; ++i) {
         std::string p = "argv[" + str(i) + "]";
         g << "if (--argc>=0) arg[" << i << "] = "
           << g.from_mex(p, "w", offset, sparsity_in_[i], fw) << "\n";
         offset += nnz_in(i);
       }
       for (casadi_int i=0; i<n_out_; ++i) {
         if (i==0) {
           // if i==0, always store output (possibly ans output)
           g << "--resc;\n";
         } else {
           // Store output, if it exists
           g << "if (--resc>=0) ";
         }
         // Create and get pointer
         g << g.res(i) << " = w+" << str(offset) << ";\n";
         offset += nnz_out(i);
       }
       g << name_ << "_incref();\n";
       g << "mem = " << name_ << "_checkout();\n";
       // Call the function
       g << "i = " << name_ << "(arg, res, iw, " << fw << ", mem);\n"
         << "if (i) mexErrMsgIdAndTxt(\"Casadi:RuntimeError\",\"Evaluation of \\\"" << name_
         << "\\\" failed.\");\n";
       g << name_ << "_release(mem);\n";
       g << name_ << "_decref();\n";
       // Save results
       for (casadi_int i=0; i<n_out_; ++i) {
         g << "if (" << g.res(i) << ") resv[" << i << "] = "
           << g.to_mex(sparsity_out_[i], g.res(i)) << "\n";
       }
       // End conditional compilation and function
       g << "}\n"
         << "#endif\n\n";
     }
     if (g.main) {
       // Declare wrapper
       g << "casadi_int main_" << name_ << "(casadi_int argc, char* argv[]) {\n";
       g << "casadi_int j;\n";
       g << "casadi_real* a;\n";
       g << "const casadi_real* r;\n";
       g << "casadi_int flag;\n";
       if (needs_mem) g << "int mem;\n";
       // Work vectors and input and output buffers
       size_t nr = sz_w() + nnz_in() + nnz_out();
       g << CodeGenerator::array("casadi_int", "iw", sz_iw())
         << CodeGenerator::array("casadi_real", "w", nr);
       // Input buffers
       g << "const casadi_real* arg[" << sz_arg() << "];\n";
       // Output buffers
       g << "casadi_real* res[" << sz_res() << "];\n";
       casadi_int off=0;
       for (casadi_int i=0; i<n_in_; ++i) {
         g << "arg[" << i << "] = w+" << off << ";\n";
         off += nnz_in(i);
       }
       for (casadi_int i=0; i<n_out_; ++i) {
         g << "res[" << i << "] = w+" << off << ";\n";
         off += nnz_out(i);
       }
       // TODO(@jaeandersson): Read inputs from file. For now; read from stdin
       g << "a = w;\n"
         << "for (j=0; j<" << nnz_in() << "; ++j) "
         << "if (scanf(\"%lg\", a++)<=0) return 2;\n";
       if (needs_mem) {
         g << "mem = " << name_ << "_checkout();\n";
       }
       // Call the function
       g << "flag = " << name_ << "(arg, res, iw, w+" << off << ", ";
       if (needs_mem) {
         g << "mem";
       } else {
         g << "0";
       }
       g << ");\n";
       if (needs_mem) {
         g << name_ << "_release(mem);\n";
       }
       g << "if (flag) return flag;\n";
       // TODO(@jaeandersson): Write outputs to file. For now: print to stdout
       g << "r = w+" << nnz_in() << ";\n"
         << "for (j=0; j<" << nnz_out() << "; ++j) "
         << g.printf("%g ", "*r++") << "\n";
       // End with newline
       g << g.printf("\\n") << "\n";
       // Finalize function
       g << "return 0;\n"
         << "}\n\n";
     }
     if (g.with_mem) {
       // Allocate memory
       g << g.declare("casadi_functions* " + name_ + "_functions(void)") << " {\n"
         << "static casadi_functions fun = {\n"
         << name_ << "_incref,\n"
         << name_ << "_decref,\n"
         << name_ << "_checkout,\n"
         << name_ << "_release,\n"
         << name_ << "_default_in,\n"
         //<< name_ << "_alloc_mem,\n"
         //<< name_ << "_init_mem,\n"
         //<< name_ << "_free_mem,\n"
         << name_ << "_n_in,\n"
         << name_ << "_n_out,\n"
         << name_ << "_name_in,\n"
         << name_ << "_name_out,\n"
         << name_ << "_sparsity_in,\n"
         << name_ << "_sparsity_out,\n"
         << name_ << "_work,\n"
         << name_ << "\n"
         << "};\n"
         << "return &fun;\n"
         << "}\n";
     }
     // Flush
     g.flush(g.body);
   }
References casadi::all(), casadi::CodeGenerator::array(), casadi::CodeGenerator::avoid_stack(), casadi::CodeGenerator::body, casadi::FunctionInternal::codegen_decref(), casadi::FunctionInternal::codegen_incref(), casadi::FunctionInternal::codegen_mem_type(), casadi::FunctionInternal::codegen_name(), casadi::FunctionInternal::codegen_sparsities(), casadi::CodeGenerator::constant(), casadi::CodeGenerator::declare(), casadi::CodeGenerator::flush(), casadi::CodeGenerator::from_mex(), casadi::FunctionInternal::get_default_in(), casadi::CodeGenerator::header, casadi::FunctionInternal::is_a(), casadi::FunctionInternal::is_diff_in_, casadi::FunctionInternal::is_diff_out_, casadi::CodeGenerator::main, casadi::CodeGenerator::mex, casadi::FunctionInternal::n_in_, casadi::FunctionInternal::n_out_, casadi::ProtoFunction::name_, casadi::FunctionInternal::name_in_, casadi::FunctionInternal::name_out_, casadi::FunctionInternal::nnz_in(), casadi::FunctionInternal::nnz_out(), casadi::CodeGenerator::printf(), casadi::CodeGenerator::res(), casadi::Sparsity::size1(), casadi::Sparsity::size2(), casadi::FunctionInternal::sparsity_in_, casadi::FunctionInternal::sparsity_out_, casadi::str(), casadi::FunctionInternal::sz_arg(), casadi::FunctionInternal::sz_iw(), casadi::FunctionInternal::sz_res(), casadi::FunctionInternal::sz_w(), casadi::CodeGenerator::to_mex(), casadi::CodeGenerator::with_header, and casadi::CodeGenerator::with_mem.
Referenced by casadi::CodeGenerator::add().
codegen_name()
std::string casadi::FunctionInternal::codegen_name (const CodeGenerator & g, bool ns = true) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lp
Definition at line 2605 of file function_internal.cpp.
{
     if (ns) {
       // Get the index of the function
       for (auto&& e : g.added_functions_) {
         if (e.f.get()==this) return e.codegen_name;
       }
     } else {
       for (casadi_int i=0;i<g.added_functions_.size();++i) {
         const auto & e = g.added_functions_[i];
         if (e.f.get()==this) return "f" + str(i);
       }
     }
     casadi_error("Function '" + name_ + "' not found");
   }
References casadi::CodeGenerator::added_functions_, casadi::ProtoFunction::name_, and casadi::str().
Referenced by casadi::FunctionInternal::codegen_alloc_mem(), casadi::FunctionInternal::codegen_checkout(), casadi::Call::codegen_decref(), casadi::Call::codegen_incref(), casadi::FunctionInternal::codegen_mem(), casadi::FunctionInternal::codegen_meta(), casadi::FunctionInternal::codegen_release(), and casadi::CodeGenerator::mem().
codegen_release()
void casadi::FunctionInternal::codegen_release (CodeGenerator & g) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lx
Reimplemented in casadi::External.
Definition at line 2285 of file function_internal.cpp.
{
     std::string name = codegen_name(g, false);
     std::string stack_counter = g.shorthand(name + "_unused_stack_counter");
     std::string stack = g.shorthand(name + "_unused_stack");
     g << stack << "[++" << stack_counter << "] = mem;\n";
   }
References casadi::FunctionInternal::codegen_name(), and casadi::CodeGenerator::shorthand().
Referenced by casadi::CodeGenerator::add_dependency().
codegen_sparsities()
void casadi::FunctionInternal::codegen_sparsities (CodeGenerator & g) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lo
Definition at line 2292 of file function_internal.cpp.
{
     g.add_io_sparsities(name_, sparsity_in_, sparsity_out_);
   }
References casadi::CodeGenerator::add_io_sparsities(), casadi::ProtoFunction::name_, casadi::FunctionInternal::sparsity_in_, and casadi::FunctionInternal::sparsity_out_.
Referenced by casadi::FunctionInternal::codegen_meta().
construct()
void casadi::ProtoFunction::construct (const Dict & opts) inherited
Prepares the function for evaluation
Extra doc: https://github.com/casadi/casadi/wiki/L_jf
Definition at line 131 of file function_internal.cpp.
{
     // Sanitize dictionary is needed
     if (!Options::is_sane(opts)) {
       // Call recursively
       return construct(Options::sanitize(opts));
     }
     // Make sure all options exist
     get_options().check(opts);
     // Initialize the class hierarchy
     try {
       init(opts);
     } catch(std::exception& e) {
       casadi_error("Error calling " + class_name() + "::init for '" + name_ + "':\n"
         + std::string(e.what()));
     }
     // Revisit class hierarchy in reverse order
     try {
       finalize();
     } catch(std::exception& e) {
       casadi_error("Error calling " + class_name() + "::finalize for '" + name_ + "':\n"
         + std::string(e.what()));
     }
   }
References casadi::Options::check(), casadi::SharedObjectInternal::class_name(), casadi::ProtoFunction::finalize(), casadi::ProtoFunction::get_options(), casadi::ProtoFunction::init(), casadi::Options::is_sane(), casadi::ProtoFunction::name_, and casadi::Options::sanitize().
Referenced by casadi::Function::create(), and casadi::LinearInterpolant::get_jacobian().
convert_arg() [1/2]
template<typename M > std::vector< M > casadi::FunctionInternal::convert_arg (const std::map< std::string, M > & arg) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ks
Definition at line 1741 of file function_internal.hpp.
{
     // Get default inputs
     std::vector<M> arg_v(n_in_);
     for (casadi_int i=0; i<arg_v.size(); ++i) {
       arg_v[i] = get_default_in(i);
     }
     // Assign provided inputs
     for (auto&& e : arg) {
       arg_v.at(index_in(e.first)) = e.second;
     }
     return arg_v;
   }
References casadi::FunctionInternal::get_default_in(), casadi::FunctionInternal::index_in(), and casadi::FunctionInternal::n_in_.
convert_arg() [2/2]
template<typename M > std::map< std::string, M > casadi::FunctionInternal::convert_arg (const std::vector< M > & arg) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ks
Definition at line 1729 of file function_internal.hpp.
{
     casadi_assert(arg.size()==n_in_, "Incorrect number of inputs: Expected "
                       + str(n_in_) + ", got " + str(arg.size()));
     std::map<std::string, M> ret;
     for (casadi_int i=0;i<n_in_;++i) {
       ret[name_in_[i]] = arg[i];
     }
     return ret;
   }
References casadi::FunctionInternal::n_in_, casadi::FunctionInternal::name_in_, and casadi::str().
convert_res() [1/2]
template<typename M > std::vector< M > casadi::FunctionInternal::convert_res (const std::map< std::string, M > & res) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ks
Definition at line 1770 of file function_internal.hpp.
{
     // Get default inputs
     std::vector<M> res_v(n_out_);
     for (casadi_int i=0; i<res_v.size(); ++i) {
       res_v[i] = std::numeric_limits<double>::quiet_NaN();
     }
     // Assign provided inputs
     for (auto&& e : res) {
       M a = e.second;
       res_v.at(index_out(e.first)) = a;
     }
     return res_v;
   }
References casadi::FunctionInternal::index_out(), and casadi::FunctionInternal::n_out_.
convert_res() [2/2]
template<typename M > std::map< std::string, M > casadi::FunctionInternal::convert_res (const std::vector< M > & res) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ks
Definition at line 1758 of file function_internal.hpp.
{
     casadi_assert(res.size()==n_out_, "Incorrect number of outputs: Expected "
                       + str(n_out_) + ", got " + str(res.size()));
     std::map<std::string, M> ret;
     for (casadi_int i=0;i<n_out_;++i) {
       ret[name_out_[i]] = res[i];
     }
     return ret;
   }
References casadi::FunctionInternal::n_out_, casadi::FunctionInternal::name_out_, and casadi::str().
create_forward()
Function casadi::OracleFunction::create_forward (const std::string & fname, casadi_int nfwd) inherited
Create an oracle function as a forward derivative of a different function
Definition at line 204 of file oracle_function.cpp.
{
   // Create derivative
   Function ret = get_function(fname).forward(nfwd);
   if (!has_function(ret.name())) set_function(ret, ret.name(), true);
   return ret;
 }
References casadi::OracleFunction::get_function(), casadi::OracleFunction::has_function(), casadi::Function::name(), and casadi::OracleFunction::set_function().
Referenced by casadi::Integrator::init(), casadi::SundialsInterface::init(), and casadi::RungeKutta::setup_step().
create_function() [1/2]
Function casadi::OracleFunction::create_function (const Function & oracle, const std::string & fname, const std::vector< std::string > & s_in, const std::vector< std::string > & s_out, const Function::AuxOut & aux = Function::AuxOut()) inherited
Create an oracle function, using a different oracle function Temporary addition to allow transition from one oracle formulation to another.
Definition at line 163 of file oracle_function.cpp.
{
   // Print progress
   if (verbose_) {
     casadi_message(name_ + "::create_function " + fname + ":" + str(s_in) + "->" + str(s_out));
   }
   // Check if function is already in cache
   Function ret;
   if (incache(fname, ret)) {
     // Consistency checks
     casadi_assert(ret.n_in() == s_in.size(), fname + " has wrong number of inputs");
     casadi_assert(ret.n_out() == s_out.size(), fname + " has wrong number of outputs");
   } else {
     // Retrieve specific set of options if available
     Dict specific_options;
     auto it = specific_options_.find(fname);
     if (it!=specific_options_.end()) specific_options = it->second;
     // Combine specific and common options
     Dict opt = combine(specific_options, common_options_);
     // Generate the function
     ret = oracle.factory(fname, s_in, s_out, aux, opt);
     // Make sure that it's sound
     if (ret.has_free()) {
       casadi_error("Cannot create '" + fname + "' since " + str(ret.get_free()) + " are free.");
     }
     // Add to cache
     tocache(ret);
   }
   // Save and return
   set_function(ret, fname, true);
   return ret;
 }
References casadi::combine(), casadi::OracleFunction::common_options_, casadi::Function::factory(), casadi::Function::get_free(), casadi::Function::has_free(), casadi::FunctionInternal::incache(), casadi::Function::n_in(), casadi::Function::n_out(), casadi::ProtoFunction::name_, casadi::OracleFunction::oracle(), casadi::OracleFunction::set_function(), casadi::OracleFunction::specific_options_, casadi::str(), casadi::FunctionInternal::tocache(), and casadi::ProtoFunction::verbose_.
Referenced by casadi::OracleFunction::create_function(), casadi::Integrator::init(), casadi::Nlpsol::init(), casadi::Blocksqp::init(), casadi::BonminInterface::init(), casadi::IpoptInterface::init(), casadi::KnitroInterface::init(), casadi::SnoptInterface::init(), casadi::SundialsInterface::init(), casadi::WorhpInterface::init(), casadi::Feasiblesqpmethod::init(), casadi::Qrsqp::init(), and casadi::Sqpmethod::init().
create_function() [2/2]
Function casadi::OracleFunction::create_function (const std::string & fname, const std::vector< std::string > & s_in, const std::vector< std::string > & s_out, const Function::AuxOut & aux = Function::AuxOut()) inherited
Create an oracle function
Definition at line 156 of file oracle_function.cpp.
{
   return create_function(oracle_, fname, s_in, s_out, aux);
 }
References casadi::OracleFunction::create_function(), and casadi::OracleFunction::oracle_.
create_oracle()
template<typename XType > Function casadi::Nlpsol::create_oracle (const std::map< std::string, XType > & d, const Dict & opts) static inherited
Definition at line 126 of file nlpsol.cpp.
{
     std::vector<XType> nl_in(NL_NUM_IN), nl_out(NL_NUM_OUT);
     for (auto&& i : d) {
       if (i.first=="x") {
         nl_in[NL_X]=i.second;
       } else if (i.first=="p") {
         nl_in[NL_P]=i.second;
       } else if (i.first=="f") {
         nl_out[NL_F]=i.second;
       } else if (i.first=="g") {
         nl_out[NL_G]=i.second;
       } else {
         casadi_error("No such field: " + i.first);
       }
     }
     if (nl_out[NL_F].is_empty()) nl_out[NL_F] = 0;
     if (nl_out[NL_G].is_empty()) nl_out[NL_G] = XType(0, 1);
     // Options for the oracle
     Dict oracle_options;
     Dict::const_iterator it = opts.find("oracle_options");
     if (it != opts.end()) {
       // "oracle_options" has been set
       oracle_options = it->second;
     } else {
       // Propagate selected options from Nlpsol to oracle by default
       for (const char* op : {"verbose", "regularity_check"})
       if ((it = opts.find(op)) != opts.end()) {
         oracle_options[op] = it->second;
       }
     }
     // Create oracle
     return Function("nlp", nl_in, nl_out, NL_INPUTS, NL_OUTPUTS, oracle_options);
   }
References casadi::FunctionInternal::Function, casadi::NL_F, casadi::NL_G, casadi::NL_INPUTS, casadi::NL_NUM_IN, casadi::NL_NUM_OUT, casadi::NL_OUTPUTS, casadi::NL_P, and casadi::NL_X.
Referenced by casadi::construct_nlpsol().
creator()
static Nlpsol* casadi::AmplInterface::creator (const std::string & name, const Function & nlp) inline static
Definition at line 68 of file ampl_interface.hpp.
{
       return new AmplInterface(name, nlp);
     }
Referenced by casadi::casadi_register_nlpsol_ampl().
definition()
std::string casadi::FunctionInternal::definition () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ma
Definition at line 921 of file function_internal.cpp.
{
     std::stringstream s;
     // Print name
     s << name_ << ":(";
     // Print input arguments
     for (casadi_int i=0; i<n_in_; ++i) {
       if (!is_diff_in_.empty() && !is_diff_in_[i]) s << "#";
       s << name_in_[i] << sparsity_in_[i].postfix_dim() << (i==n_in_-1 ? "" : ",");
     }
     s << ")->(";
     // Print output arguments
     for (casadi_int i=0; i<n_out_; ++i) {
       if (!is_diff_out_.empty() && !is_diff_out_[i]) s << "#";
       s << name_out_[i] << sparsity_out_[i].postfix_dim() << (i==n_out_-1 ? "" : ",");
     }
     s << ")";
     return s.str();
   }
References casadi::FunctionInternal::is_diff_in_, casadi::FunctionInternal::is_diff_out_, casadi::FunctionInternal::n_in_, casadi::FunctionInternal::n_out_, casadi::ProtoFunction::name_, casadi::FunctionInternal::name_in_, casadi::FunctionInternal::name_out_, casadi::FunctionInternal::sparsity_in_, and casadi::FunctionInternal::sparsity_out_.
Referenced by casadi::FunctionInternal::codegen(), casadi::FunctionInternal::disp(), and casadi::MXFunction::should_inline().
deserialize()
ProtoFunction * casadi::Nlpsol::deserialize (DeserializingStream & s) static inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1nn
Definition at line 1303 of file nlpsol.cpp.
{
     return PluginInterface<Nlpsol>::deserialize(s);
   }
References casadi::PluginInterface< Derived >::deserialize().
destroySingleton()
void casadi::SharedObjectInternal::destroySingleton () inline protected inherited
Called in the destructor of singletons
Definition at line 79 of file shared_object_internal.hpp.
{
       count--;
     }
disp()
void casadi::FunctionInternal::disp (std::ostream & stream, bool more) const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_m8
Implements casadi::SharedObjectInternal.
Definition at line 942 of file function_internal.cpp.
{
     stream << definition() << " " << class_name();
     if (more) {
       stream << std::endl;
       disp_more(stream);
     }
   }
References casadi::SharedObjectInternal::class_name(), casadi::FunctionInternal::definition(), and casadi::FunctionInternal::disp_more().
Referenced by casadi::MXFunction::eval().
disp_more()
void casadi::Nlpsol::disp_more (std::ostream & stream) const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1nt
Reimplemented from casadi::FunctionInternal.
Definition at line 912 of file nlpsol.cpp.
{
     stream << "minimize f(x;p) subject to lbx<=x<=ubx, lbg<=g(x;p)<=ubg defined by:\n";
     oracle_.disp(stream, true);
   }
References casadi::SharedObject::disp(), and casadi::OracleFunction::oracle_.
dm_in() [1/2]
const std::vector< DM > casadi::FunctionInternal::dm_in () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_l7
Definition at line 3110 of file function_internal.cpp.
{
     std::vector<DM> ret(n_in_);
     for (casadi_int i=0; i<ret.size(); ++i) {
       ret[i] = dm_in(i);
     }
     return ret;
   }
References casadi::FunctionInternal::n_in_.
Referenced by casadi::FunctionInternal::nz_in().
dm_in() [2/2]
const DM casadi::FunctionInternal::dm_in (casadi_int ind) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_l7
Definition at line 3086 of file function_internal.cpp.
{
     return DM::zeros(sparsity_in(ind));
   }
References casadi::FunctionInternal::sparsity_in(), and casadi::GenericMatrix< MatType >::zeros().
dm_out() [1/2]
const std::vector< DM > casadi::FunctionInternal::dm_out () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_l7
Definition at line 3118 of file function_internal.cpp.
{
     std::vector<DM> ret(n_out_);
     for (casadi_int i=0; i<ret.size(); ++i) {
       ret[i] = dm_out(i);
     }
     return ret;
   }
References casadi::FunctionInternal::n_out_.
Referenced by casadi::FunctionInternal::nz_out().
dm_out() [2/2]
const DM casadi::FunctionInternal::dm_out (casadi_int ind) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_l7
Definition at line 3090 of file function_internal.cpp.
{
     return DM::zeros(sparsity_out(ind));
   }
References casadi::FunctionInternal::sparsity_out(), and casadi::GenericMatrix< MatType >::zeros().
eval()
int casadi::Nlpsol::eval (const double ** arg, double ** res, casadi_int * iw, double * w, void * mem) const final virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kb
Reimplemented from casadi::FunctionInternal.
Definition at line 674 of file nlpsol.cpp.
{
     auto m = static_cast<NlpsolMemory*>(mem);
     auto d_nlp = &m->d_nlp;
     // Reset the solver, prepare for solution
     setup(m, arg, res, iw, w);
     auto p_nlp = d_nlp->prob;
     // Set initial guess
     casadi_copy(d_nlp->x0, nx_, d_nlp->z);
     // Read simple bounds and multiplier guesses
     casadi_copy(d_nlp->lbx, nx_, d_nlp->lbz);
     casadi_copy(d_nlp->ubx, nx_, d_nlp->ubz);
     casadi_copy(d_nlp->lam_x0, nx_, d_nlp->lam);
     if (p_nlp->detect_bounds.ng==0) {
       // Read constraint bounds and multiplier guesses
       casadi_copy(d_nlp->lbg, ng_, d_nlp->lbz+nx_);
       casadi_copy(d_nlp->ubg, ng_, d_nlp->ubz+nx_);
       casadi_copy(d_nlp->lam_g0, ng_, d_nlp->lam+nx_);
     } else {
       auto& d_bounds = d_nlp->detect_bounds;
       const auto& p_bounds = p_nlp->detect_bounds;
       d_bounds.arg[0] = d_nlp->p;
       d_bounds.res[0] = d_bounds.a;
       d_bounds.res[1] = d_bounds.b;
       detect_simple_bounds_parts_(d_bounds.arg, d_bounds.res, d_bounds.iw, d_bounds.w);
       for (casadi_int i=0;i<p_bounds.nb;++i) {
         if (d_bounds.a[i]==0) {
           casadi_int k = p_bounds.target_g[i];
           if (d_nlp->lbg[k]>d_bounds.b[i]) return 1;
           if (d_nlp->ubg[k]<d_bounds.b[i]) return 1;
         }
       }
       double* lbz = d_nlp->lbz+nx_;
       double* ubz = d_nlp->ubz+nx_;
       double* lam = d_nlp->lam+nx_;
       for (casadi_int i=0;i<nx_;++i) {
         d_bounds.lam_xl[i] = d_nlp->lam_x0 ? (d_nlp->lam_x0[i]<0)*d_nlp->lam_x0[i] : 0.;
         d_bounds.lam_xu[i] = d_nlp->lam_x0 ? (d_nlp->lam_x0[i]>0)*d_nlp->lam_x0[i] : 0.;
       }
       for (casadi_int i=0;i<nx_;++i) {
         d_bounds.target_l[i] = i;
         d_bounds.target_u[i] = i;
       }
       // Update lbz/ubz
       casadi_int k=0;
       for (casadi_int i=0;i<p_bounds.ng;++i) {
         if (p_bounds.is_simple[i]) {
           // Update lbz/ubz
           double lb = (d_nlp->lbg[i]-d_bounds.b[k])/fabs(d_bounds.a[k]);
           double ub = (d_nlp->ubg[i]-d_bounds.b[k])/fabs(d_bounds.a[k]);
           casadi_int j = p_bounds.target_x[k];
           if (lb==d_nlp->lbz[j]) {
             if (d_nlp->lam_g0) d_bounds.lam_xl[j] += (d_nlp->lam_g0[i]<0)*d_nlp->lam_g0[i];
           } else if (lb>d_nlp->lbz[j]) {
             d_nlp->lbz[j] = lb;
             d_bounds.target_l[j] = nx_+i;
             if (d_nlp->lam_g0) d_bounds.lam_xl[j] = (d_nlp->lam_g0[i]<0)*d_nlp->lam_g0[i];
           }
           if (ub==d_nlp->ubz[j]) {
             if (d_nlp->lam_g0) d_bounds.lam_xu[j] += (d_nlp->lam_g0[i]>0)*d_nlp->lam_g0[i];
           } else if (ub<d_nlp->ubz[j]) {
             d_nlp->ubz[j] = ub;
             d_bounds.target_u[j] = nx_+i;
             if (d_nlp->lam_g0) d_bounds.lam_xu[j] = (d_nlp->lam_g0[i]>0)*d_nlp->lam_g0[i];
           }
           k++;
         } else {
           // Update lbz/ubz
           *lbz++ = d_nlp->lbg[i];
           *ubz++ = d_nlp->ubg[i];
           if (d_nlp->lam_g0) *lam++ = d_nlp->lam_g0[i];
         }
       }
       for (casadi_int i=0;i<nx_;++i) {
         d_nlp->lam[i] = d_bounds.lam_xl[i]+d_bounds.lam_xu[i];
       }
     }
     // Set multipliers to nan
     casadi_fill(d_nlp->lam_p, np_, nan);
     // Reset f, g
     d_nlp->objective = nan;
     casadi_fill(d_nlp->z + nx_, ng_, nan);
     // Check the provided inputs
     check_inputs(m);
     // Solve the NLP
     int flag = solve(m);
     // Join statistics (introduced for parallel oracle facilities)
     join_results(m);
     // Calculate multiplers
     if ((calc_f_ || calc_g_ || calc_lam_x_ || calc_lam_p_) && !flag) {
       const double lam_f = 1.;
       m->arg[0] = d_nlp->z;
       m->arg[1] = d_nlp->p;
       m->arg[2] = &lam_f;
       m->arg[3] = d_nlp->lam + nx_;
       m->res[0] = calc_f_ ? &d_nlp->objective : nullptr;
       m->res[1] = calc_g_ ? d_nlp->z + nx_ : nullptr;
       m->res[2] = calc_lam_x_ ? d_nlp->lam : nullptr;
       m->res[3] = calc_lam_p_ ? d_nlp->lam_p : nullptr;
       if (calc_function(m, "nlp_grad")) {
         casadi_warning("Failed to calculate multipliers");
       }
       if (calc_lam_x_) casadi_scal(nx_, -1., d_nlp->lam);
       if (calc_lam_p_) casadi_scal(np_, -1., d_nlp->lam_p);
     }
     // Make sure that an optimal solution is consistant with bounds
     if (bound_consistency_ && !flag) {
       bound_consistency(nx_+ng_, d_nlp->z, d_nlp->lam, d_nlp->lbz, d_nlp->ubz);
     }
     // Get optimal solution
     casadi_copy(d_nlp->z, nx_, d_nlp->x);
     if (p_nlp->detect_bounds.ng==0) {
       casadi_copy(d_nlp->z + nx_, ng_, d_nlp->g);
       casadi_copy(d_nlp->lam, nx_, d_nlp->lam_x);
       casadi_copy(d_nlp->lam + nx_, ng_, d_nlp->lam_g);
     } else {
       auto& d_bounds = d_nlp->detect_bounds;
       const auto& p_bounds = p_nlp->detect_bounds;
       casadi_fill(d_nlp->lam_x, nx_, 0.);
       casadi_fill(d_nlp->lam_g, p_bounds.ng, 0.);
       casadi_int k = 0;
       casadi_int k_normal = 0;
       for (casadi_int i=0;i<p_bounds.ng;++i) {
         if (p_bounds.is_simple[i]) {
           casadi_int j = p_bounds.target_x[k];
           if (d_nlp->g) d_nlp->g[i] = d_bounds.a[k]*d_nlp->z[j]+d_bounds.b[k];
           k++;
         } else {
           if (d_nlp->g) d_nlp->g[i] = d_nlp->z[nx_+k_normal];
           if (d_nlp->lam_g) d_nlp->lam_g[i] = d_nlp->lam[nx_+k_normal];
           k_normal++;
         }
       }
       for (casadi_int i=0;i<nx_;++i) {
         if (d_bounds.target_l[i]<nx_) {
           if (d_nlp->lam_x) d_nlp->lam_x[i] += (d_nlp->lam[i]<0)*d_nlp->lam[i];
         } else {
           if (d_nlp->lam_g)
             d_nlp->lam_g[d_bounds.target_l[i]-nx_] += (d_nlp->lam[i]<0)*d_nlp->lam[i];
         }
         if (d_bounds.target_u[i]<nx_) {
           if (d_nlp->lam_x) d_nlp->lam_x[i] += (d_nlp->lam[i]>0)*d_nlp->lam[i];
         } else {
           if (d_nlp->lam_g)
             d_nlp->lam_g[d_bounds.target_u[i]-nx_] += (d_nlp->lam[i]>0)*d_nlp->lam[i];
         }
       }
     }
     casadi_copy(d_nlp->lam_p, np_, d_nlp->lam_p);
     casadi_copy(&d_nlp->objective, 1, d_nlp->f);
     if (error_on_fail_ && !m->success)
       casadi_error("nlpsol process failed. "
                    "Set 'error_on_fail' option to false to ignore this error.");
     return flag;
   }
References casadi::Nlpsol::bound_consistency(), casadi::Nlpsol::bound_consistency_, casadi::Nlpsol::calc_f_, casadi::OracleFunction::calc_function(), casadi::Nlpsol::calc_g_, casadi::Nlpsol::calc_lam_p_, casadi::Nlpsol::calc_lam_x_, casadi::casadi_copy(), casadi::casadi_fill(), casadi::casadi_scal(), casadi::Nlpsol::check_inputs(), casadi::NlpsolMemory::d_nlp, casadi::Nlpsol::detect_simple_bounds_parts_, casadi::ProtoFunction::error_on_fail_, casadi::OracleFunction::join_results(), casadi::nan, casadi::Nlpsol::ng_, casadi::Nlpsol::np_, casadi::Nlpsol::nx_, casadi::FunctionInternal::setup(), and casadi::Nlpsol::solve().
eval_dm()
std::vector< DM > casadi::FunctionInternal::eval_dm (const std::vector< DM > & arg) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ke
Reimplemented in casadi::CallbackInternal.
Definition at line 1986 of file function_internal.cpp.
{
     casadi_error("'eval_dm' not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
Referenced by casadi::FunctionInternal::eval().
eval_gen() [1/3]
int casadi::FunctionInternal::eval_gen (const bvec_t ** arg, bvec_t ** res, casadi_int * iw, bvec_t * w, void * mem) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kf
Definition at line 403 of file function_internal.hpp.
{
       return sp_forward(arg, res, iw, w, mem);
     }
eval_gen() [2/3]
int casadi::FunctionInternal::eval_gen (const double ** arg, double ** res, casadi_int * iw, double * w, void * mem) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kb
Definition at line 824 of file function_internal.cpp.
{
     casadi_int dump_id = (dump_in_ || dump_out_ || dump_) ? get_dump_id() : 0;
     if (dump_in_) dump_in(dump_id, arg);
     if (dump_ && dump_id==0) dump();
     if (print_in_) print_in(uout(), arg, false);
     auto m = static_cast<ProtoFunctionMemory*>(mem);
     // Reset statistics
     for (auto&& s : m->fstats) s.second.reset();
     if (m->t_total) m->t_total->tic();
     int ret;
     if (eval_) {
       int mem = 0;
       if (checkout_) {
 #ifdef CASADI_WITH_THREAD
     std::lock_guard<std::mutex> lock(mtx_);
 #endif //CASADI_WITH_THREAD
         mem = checkout_();
       }
       ret = eval_(arg, res, iw, w, mem);
       if (release_) {
 #ifdef CASADI_WITH_THREAD
     std::lock_guard<std::mutex> lock(mtx_);
 #endif //CASADI_WITH_THREAD
         release_(mem);
       }
     } else {
       ret = eval(arg, res, iw, w, mem);
     }
     if (m->t_total) m->t_total->toc();
     // Show statistics
     print_time(m->fstats);
     if (dump_out_) dump_out(dump_id, res);
     if (print_out_) print_out(uout(), res, false);
     // Check all outputs for NaNs
     if (regularity_check_) {
       for (casadi_int i = 0; i < n_out_; ++i) {
         // Skip of not calculated
         if (!res[i]) continue;
         // Loop over nonzeros
         casadi_int nnz = this->nnz_out(i);
         for (casadi_int nz = 0; nz < nnz; ++nz) {
           if (isnan(res[i][nz]) || isinf(res[i][nz])) {
             // Throw readable error message
             casadi_error(str(res[i][nz]) + " detected for output " + name_out_[i] + " at "
               + sparsity_out(i).repr_el(nz));
           }
         }
       }
     }
     return ret;
   }
References casadi::FunctionInternal::checkout_, casadi::FunctionInternal::dump_, casadi::FunctionInternal::dump_in_, casadi::FunctionInternal::dump_out_, casadi::FunctionInternal::eval(), casadi::FunctionInternal::eval_, casadi::FunctionInternal::n_out_, casadi::FunctionInternal::name_out_, casadi::FunctionInternal::nnz_out(), casadi::FunctionInternal::print_in(), casadi::FunctionInternal::print_in_, casadi::FunctionInternal::print_out(), casadi::FunctionInternal::print_out_, casadi::ProtoFunction::print_time(), casadi::ProtoFunction::regularity_check_, casadi::FunctionInternal::release_, casadi::FunctionInternal::sparsity_out(), casadi::str(), casadi::ProtoFunctionMemory::t_total, casadi::FStats::tic(), and casadi::uout().
Referenced by casadi::FunctionInternal::call_gen().
eval_gen() [3/3]
int casadi::FunctionInternal::eval_gen (const SXElem ** arg, SXElem ** res, casadi_int * iw, SXElem * w, void * mem) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kf
Definition at line 400 of file function_internal.hpp.
{
       return eval_sx(arg, res, iw, w, mem);
     }
eval_mx()
void casadi::FunctionInternal::eval_mx (const MXVector & arg, MXVector & res, bool always_inline, bool never_inline) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kd
Reimplemented in casadi::MXFunction.
Definition at line 2153 of file function_internal.cpp.
{
     always_inline = always_inline || always_inline_;
     never_inline = never_inline || never_inline_;
     // The code below creates a call node, to inline, wrap in an MXFunction
     if (always_inline) {
       casadi_assert(!never_inline, "Inconsistent options for " + str(name_));
       return wrap().call(arg, res, true);
     }
     // Create a call-node
     res = Call::create(self(), arg);
   }
References casadi::FunctionInternal::always_inline_, casadi::Function::call(), casadi::Call::create(), casadi::ProtoFunction::name_, casadi::FunctionInternal::never_inline_, casadi::str(), and casadi::FunctionInternal::wrap().
Referenced by casadi::FunctionInternal::call_gen(), and casadi::MXFunction::eval_mx().
eval_sx()
int casadi::FunctionInternal::eval_sx (const SXElem ** arg, SXElem ** res, casadi_int * iw, SXElem * w, void * mem) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kc
Reimplemented in casadi::SXFunction, casadi::Switch, casadi::MXFunction, casadi::MapSum, and casadi::Map.
Definition at line 1990 of file function_internal.cpp.
{
     casadi_error("'eval_sx' not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
expand()
void casadi::OracleFunction::expand () inherited
Definition at line 372 of file oracle_function.cpp.
{
   oracle_ = oracle_.expand();
 }
References casadi::Function::expand(), and casadi::OracleFunction::oracle_.
Referenced by casadi::Integrator::init(), and casadi::OracleFunction::init().
export_code()
void casadi::FunctionInternal::export_code (const std::string & lang, std::ostream & stream, const Dict & options) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_m5
Reimplemented in casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, and casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >.
Definition at line 2113 of file function_internal.cpp.
{
     casadi_error("'export_code' not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
factory()
Function casadi::FunctionInternal::factory (const std::string & name, const std::vector< std::string > & s_in, const std::vector< std::string > & s_out, const Function::AuxOut & aux, const Dict & opts) const virtual inherited
Reimplemented in casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >, and casadi::External.
Definition at line 3467 of file function_internal.cpp.
{
     return wrap().factory(name, s_in, s_out, aux, opts);
   }
References casadi::Function::factory(), and casadi::FunctionInternal::wrap().
Referenced by casadi::Function::factory(), and casadi::External::factory().
finalize()
void casadi::OracleFunction::finalize () override virtual inherited
Reimplemented from casadi::FunctionInternal.
Definition at line 105 of file oracle_function.cpp.
{
   // Allocate space for (parallel) evaluations
   // Lifted from set_function as max_num_threads_ is not known yet in that method
   for (auto&& e : all_functions_) {
     Function& fcn = e.second.f;
     // Compute strides for multi threading
     size_t sz_arg, sz_res, sz_iw, sz_w;
     fcn.sz_work(sz_arg, sz_res, sz_iw, sz_w);
     stride_arg_ = std::max(stride_arg_, sz_arg);
     stride_res_ = std::max(stride_res_, sz_res);
     stride_iw_ = std::max(stride_iw_, sz_iw);
     stride_w_ = std::max(stride_w_, sz_w);
     bool persistent = false;
     alloc(fcn, persistent, max_num_threads_);
   }
   // Set corresponding monitors
   for (const std::string& fname : monitor_) {
     auto it = all_functions_.find(fname);
     if (it==all_functions_.end()) {
       casadi_warning("Ignoring monitor '" + fname + "'."
                       " Available functions: " + join(get_function()) + ".");
     } else {
       if (it->second.monitored) casadi_warning("Duplicate monitor " + fname);
       it->second.monitored = true;
     }
   }
   // Check specific options
   for (auto&& i : specific_options_) {
     if (all_functions_.find(i.first)==all_functions_.end())
       casadi_warning("Ignoring specific_options entry '" + i.first+"'."
                       " Available functions: " + join(get_function()) + ".");
   }
   // Recursive call
   FunctionInternal::finalize();
 }
References casadi::OracleFunction::all_functions_, casadi::FunctionInternal::alloc(), casadi::FunctionInternal::finalize(), casadi::OracleFunction::get_function(), casadi::join(), casadi::OracleFunction::max_num_threads_, casadi::OracleFunction::monitor_, casadi::OracleFunction::specific_options_, casadi::OracleFunction::stride_arg_, casadi::OracleFunction::stride_iw_, casadi::OracleFunction::stride_res_, casadi::OracleFunction::stride_w_, casadi::FunctionInternal::sz_arg(), casadi::FunctionInternal::sz_iw(), casadi::FunctionInternal::sz_res(), casadi::FunctionInternal::sz_w(), and casadi::Function::sz_work().
find()
virtual void casadi::FunctionInternal::find (std::map< FunctionInternal *, Function > & all_fun, casadi_int max_depth) const inline virtual inherited
Reimplemented in casadi::Switch, and casadi::MXFunction.
Definition at line 346 of file function_internal.hpp.
 {}
Referenced by casadi::FunctionInternal::add_embedded(), casadi::FunctionInternal::from_compact(), and casadi::FunctionInternal::to_compact().
format_time()
void casadi::ProtoFunction::format_time (char * buffer, double time) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_jt
Definition at line 3621 of file function_internal.cpp.
{
     // Always of width 8
     casadi_assert_dev(time>=0);
     double log_time = log10(time);
     int magn = static_cast<int>(floor(log_time));
     int iprefix = static_cast<int>(floor(log_time/3));
     if (iprefix<-4) {
       sprint(buffer, 10, "       0");
       return;
     }
     if (iprefix>=5) {
       sprint(buffer, 10, "     inf");
       return;
     }
     char prefixes[] = "TGMk munp";
     char prefix = prefixes[4-iprefix];
     int rem = magn-3*iprefix;
     double time_normalized = time/pow(10, 3*iprefix);
     if (rem==0) {
       sprint(buffer, 10, "  %1.2f%cs", time_normalized, prefix);
     } else if (rem==1) {
       sprint(buffer, 10, " %2.2f%cs", time_normalized, prefix);
     } else {
       sprint(buffer, 10, "%3.2f%cs", time_normalized, prefix);
     }
   }
References casadi::ProtoFunction::sprint().
Referenced by casadi::ProtoFunction::print_time().
forward()
Function casadi::FunctionInternal::forward (casadi_int nfwd) const inherited
forward(nfwd) returns a cached instance if available, and calls Function get_forward(casadi_int nfwd) if no cached version is available.
Extra doc: https://github.com/casadi/casadi/wiki/L_l0
Definition at line 1995 of file function_internal.cpp.
{
     casadi_assert_dev(nfwd>=0);
     // Used wrapped function if forward not available
     if (!enable_forward_ && !enable_fd_) {
       // Derivative information must be available
       casadi_assert(has_derivative(), "Derivatives cannot be calculated for " + name_);
       return wrap().forward(nfwd);
     }
     // Retrieve/generate cached
     Function f;
     std::string fname = forward_name(name_, nfwd);
     if (!incache(fname, f)) {
       casadi_int i;
       // Names of inputs
       std::vector<std::string> inames;
       for (i=0; i<n_in_; ++i) inames.push_back("in_" + name_in_[i]);
       for (i=0; i<n_out_; ++i) inames.push_back("out_" + name_out_[i]);
       for (i=0; i<n_in_; ++i) inames.push_back("fwd_" + name_in_[i]);
       // Names of outputs
       std::vector<std::string> onames;
       for (i=0; i<n_out_; ++i) onames.push_back("fwd_" + name_out_[i]);
       // Options
       Dict opts = combine(forward_options_, der_options_);
       opts = combine(opts, generate_options("forward"));
       if (!enable_forward_) opts = fd_options_;
       opts["derivative_of"] = self();
       // Generate derivative function
       casadi_assert_dev(enable_forward_ || enable_fd_);
       if (enable_forward_) {
         f = get_forward(nfwd, fname, inames, onames, opts);
       } else {
         // Get FD method
         if (fd_method_.empty() || fd_method_=="central") {
           f = Function::create(new CentralDiff(fname, nfwd), opts);
         } else if (fd_method_=="forward") {
           f = Function::create(new ForwardDiff(fname, nfwd), opts);
         } else if (fd_method_=="backward") {
           f = Function::create(new BackwardDiff(fname, nfwd), opts);
         } else if (fd_method_=="smoothing") {
           f = Function::create(new Smoothing(fname, nfwd), opts);
         } else {
           casadi_error("Unknown 'fd_method': " + fd_method_);
         }
       }
       // Consistency check for inputs
       casadi_assert_dev(f.n_in()==n_in_ + n_out_ + n_in_);
       casadi_int ind=0;
       for (i=0; i<n_in_; ++i) f.assert_size_in(ind++, size1_in(i), size2_in(i));
       for (i=0; i<n_out_; ++i) f.assert_size_in(ind++, size1_out(i), size2_out(i));
       for (i=0; i<n_in_; ++i) f.assert_size_in(ind++, size1_in(i), nfwd*size2_in(i));
       // Consistency check for outputs
       casadi_assert_dev(f.n_out()==n_out_);
       for (i=0; i<n_out_; ++i) f.assert_size_out(i, size1_out(i), nfwd*size2_out(i));
       // Save to cache
       tocache(f);
     }
     return f;
   }
References casadi::Function::assert_size_in(), casadi::Function::assert_size_out(), casadi::combine(), casadi::Function::create(), casadi::FunctionInternal::der_options_, casadi::FunctionInternal::enable_fd_, casadi::FunctionInternal::enable_forward_, casadi::FunctionInternal::fd_method_, casadi::FunctionInternal::fd_options_, casadi::Function::forward(), casadi::FunctionInternal::forward_name(), casadi::FunctionInternal::forward_options_, casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::get_forward(), casadi::FunctionInternal::has_derivative(), casadi::FunctionInternal::incache(), casadi::Function::n_in(), casadi::FunctionInternal::n_in_, casadi::Function::n_out(), casadi::FunctionInternal::n_out_, casadi::ProtoFunction::name_, casadi::FunctionInternal::name_in_, casadi::FunctionInternal::name_out_, casadi::FunctionInternal::size1_in(), casadi::FunctionInternal::size1_out(), casadi::FunctionInternal::size2_in(), casadi::FunctionInternal::size2_out(), casadi::FunctionInternal::tocache(), and casadi::FunctionInternal::wrap().
Referenced by casadi::FunctionInternal::call_forward(), and casadi::Function::forward().
forward_name()
static std::string casadi::FunctionInternal::forward_name (const std::string & fcn, casadi_int nfwd) inline static inherited
Definition at line 605 of file function_internal.hpp.
{
       return "fwd" + str(nfwd) + "_" + fcn;
     }
References casadi::str().
Referenced by casadi::Integrator::bdae_sp_forward(), casadi::Integrator::bdae_sp_reverse(), casadi::Integrator::bquad_sp_forward(), casadi::Integrator::bquad_sp_reverse(), casadi::SundialsInterface::calc_daeB(), casadi::SundialsInterface::calc_daeF(), casadi::SundialsInterface::calc_jtimesF(), casadi::SundialsInterface::calc_quadB(), casadi::SundialsInterface::calc_quadF(), casadi::Integrator::fdae_sp_forward(), casadi::Integrator::fdae_sp_reverse(), casadi::FunctionInternal::forward(), casadi::Integrator::fquad_sp_forward(), casadi::Integrator::fquad_sp_reverse(), casadi::Integrator::sp_jac_dae(), casadi::Integrator::sp_jac_rdae(), casadi::FixedStepIntegrator::stepB(), and casadi::FixedStepIntegrator::stepF().
free_mem()
void casadi::AmplInterface::free_mem (void * mem) const inline override virtual
Reimplemented from casadi::Nlpsol.
Definition at line 88 of file ampl_interface.hpp.
 { delete static_cast<AmplInterfaceMemory*>(mem);}
free_mx()
std::vector< MX > casadi::FunctionInternal::free_mx () const virtual inherited
Reimplemented in casadi::MXFunction.
Definition at line 3154 of file function_internal.cpp.
{
     casadi_error("'free_mx' only defined for 'MXFunction'");
   }
free_sx()
std::vector< SX > casadi::FunctionInternal::free_sx () const virtual inherited
Reimplemented in casadi::SXFunction.
Definition at line 3158 of file function_internal.cpp.
{
     casadi_error("'free_sx' only defined for 'SXFunction'");
   }
from_compact()
Sparsity casadi::FunctionInternal::from_compact (casadi_int oind, casadi_int iind, const Sparsity & sp) const inherited
Definition at line 1822 of file function_internal.cpp.
{
     // Return value
     Sparsity r = sp;
     // Insert rows if sparse output
     if (numel_out(oind) != r.size1()) {
       casadi_assert_dev(r.size1() == nnz_out(oind));
       r.enlargeRows(numel_out(oind), sparsity_out(oind).find());
     }
     // Insert columns if sparse input
     if (numel_in(iind) != r.size2()) {
       casadi_assert_dev(r.size2() == nnz_in(iind));
       r.enlargeColumns(numel_in(iind), sparsity_in(iind).find());
     }
     // Return non-compact pattern
     return r;
   }
References casadi::Sparsity::enlargeColumns(), casadi::Sparsity::enlargeRows(), casadi::FunctionInternal::find(), casadi::FunctionInternal::nnz_in(), casadi::FunctionInternal::nnz_out(), casadi::FunctionInternal::numel_in(), casadi::FunctionInternal::numel_out(), casadi::Sparsity::size1(), casadi::Sparsity::size2(), casadi::FunctionInternal::sparsity_in(), and casadi::FunctionInternal::sparsity_out().
Referenced by casadi::FunctionInternal::jac_sparsity().
fwd_seed()
template<typename MatType > std::vector< std::vector< MatType > > casadi::FunctionInternal::fwd_seed (casadi_int nfwd) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_nr
Definition at line 1426 of file function_internal.hpp.
{
     std::vector<std::vector<MatType>> fseed(nfwd);
     for (casadi_int dir=0; dir<nfwd; ++dir) {
       fseed[dir].resize(n_in_);
       for (casadi_int iind=0; iind<n_in_; ++iind) {
         std::string n = "f" + str(dir) + "_" +  name_in_[iind];
         Sparsity sp = is_diff_in_[iind] ? sparsity_in(iind) : Sparsity(size_in(iind));
         fseed[dir][iind] = MatType::sym(n, sp);
       }
     }
     return fseed;
   }
References casadi::FunctionInternal::is_diff_in_, casadi::FunctionInternal::n_in_, casadi::FunctionInternal::name_in_, casadi::FunctionInternal::size_in(), casadi::FunctionInternal::sparsity_in(), and casadi::str().
fwdViaJac()
bool casadi::FunctionInternal::fwdViaJac (casadi_int nfwd) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_nc
Definition at line 2775 of file function_internal.cpp.
{
     if (!enable_forward_ && !enable_fd_) return true;
     if (jac_penalty_==-1) return false;
     // Heuristic 1: Jac calculated via forward mode likely cheaper
     if (jac_penalty_*static_cast<double>(nnz_in())<nfwd) return true;
     // Heuristic 2: Jac calculated via reverse mode likely cheaper
     double w = ad_weight();
     if (enable_reverse_ &&
         jac_penalty_*(1-w)*static_cast<double>(nnz_out())<w*static_cast<double>(nfwd))
       return true; // NOLINT
     return false;
   }
References casadi::FunctionInternal::ad_weight(), casadi::FunctionInternal::enable_fd_, casadi::FunctionInternal::enable_forward_, casadi::FunctionInternal::enable_reverse_, casadi::FunctionInternal::jac_penalty_, casadi::FunctionInternal::nnz_in(), and casadi::FunctionInternal::nnz_out().
Referenced by casadi::FunctionInternal::call_forward().
generate_dependencies()
std::string casadi::OracleFunction::generate_dependencies (const std::string & fname, const Dict & opts) const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_j
Reimplemented from casadi::FunctionInternal.
Definition at line 345 of file oracle_function.cpp.
{
   CodeGenerator gen(fname, opts);
   gen.add(oracle_);
   for (auto&& e : all_functions_) {
     if (e.second.jit) gen.add(e.second.f);
   }
   return gen.generate();
 }
References casadi::CodeGenerator::add(), casadi::OracleFunction::all_functions_, casadi::CodeGenerator::generate(), and casadi::OracleFunction::oracle_.
Referenced by casadi::OracleFunction::jit_dependencies().
generate_in()
void casadi::FunctionInternal::generate_in (const std::string & fname, const double ** arg) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ne
Definition at line 722 of file function_internal.cpp.
{
     // Set up output stream
     std::ofstream of(fname);
     casadi_assert(of.good(), "Error opening stream '" + fname + "'.");
     normalized_setup(of);
     // Encode each input
     for (casadi_int i=0; i<n_in_; ++i) {
       const double* v = arg[i];
       for (casadi_int k=0;k<nnz_in(i);++k) {
         normalized_out(of, v ? v[k] : 0);
         of << std::endl;
       }
     }
   }
References casadi::FunctionInternal::n_in_, casadi::FunctionInternal::nnz_in(), casadi::normalized_out(), and casadi::normalized_setup().
generate_lifted()
void casadi::FunctionInternal::generate_lifted (Function & vdef_fcn, Function & vinit_fcn) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_l9
Reimplemented in casadi::MXFunction.
Definition at line 3162 of file function_internal.cpp.
{
     casadi_error("'generate_lifted' only defined for 'MXFunction'");
   }
generate_options()
Dict casadi::FunctionInternal::generate_options (const std::string & target) const override virtual inherited
Reimplemented from casadi::ProtoFunction.
Reimplemented in casadi::SXFunction, and casadi::MXFunction.
Definition at line 373 of file function_internal.cpp.
{
     Dict opts = ProtoFunction::generate_options(target);
     opts["jac_penalty"] = jac_penalty_;
     opts["user_data"] = user_data_;
     opts["inputs_check"] = inputs_check_;
     if (target!="tmp") opts["jit"] = jit_;
     opts["jit_cleanup"] = jit_cleanup_;
     opts["jit_serialize"] = jit_serialize_;
     opts["compiler"] = compiler_plugin_;
     opts["jit_options"] = jit_options_;
     opts["jit_name"] = jit_base_name_;
     opts["jit_temp_suffix"] = jit_temp_suffix_;
     opts["ad_weight"] = ad_weight_;
     opts["ad_weight_sp"] = ad_weight_sp_;
     opts["always_inline"] = always_inline_;
     opts["never_inline"] = never_inline_;
     opts["max_num_dir"] = max_num_dir_;
     if (target=="clone" || target=="tmp") {
       opts["enable_forward"] = enable_forward_op_;
       opts["enable_reverse"] = enable_reverse_op_;
       opts["enable_jacobian"] = enable_jacobian_op_;
       opts["enable_fd"] = enable_fd_op_;
       opts["reverse_options"] = reverse_options_;
       opts["forward_options"] = forward_options_;
       opts["jacobian_options"] = jacobian_options_;
       opts["der_options"] = der_options_;
       opts["derivative_of"] = derivative_of_;
     }
     opts["fd_options"] = fd_options_;
     opts["fd_method"] = fd_method_;
     opts["print_in"] = print_in_;
     opts["print_out"] = print_out_;
     opts["max_io"] = max_io_;
     opts["dump_in"] = dump_in_;
     opts["dump_out"] = dump_out_;
     opts["dump_dir"] = dump_dir_;
     opts["dump_format"] = dump_format_;
     opts["dump"] = dump_;
     return opts;
   }
References casadi::FunctionInternal::ad_weight_, casadi::FunctionInternal::ad_weight_sp_, casadi::FunctionInternal::always_inline_, casadi::FunctionInternal::compiler_plugin_, casadi::FunctionInternal::der_options_, casadi::FunctionInternal::derivative_of_, casadi::FunctionInternal::dump_, casadi::FunctionInternal::dump_dir_, casadi::FunctionInternal::dump_format_, casadi::FunctionInternal::dump_in_, casadi::FunctionInternal::dump_out_, casadi::FunctionInternal::enable_fd_op_, casadi::FunctionInternal::enable_forward_op_, casadi::FunctionInternal::enable_jacobian_op_, casadi::FunctionInternal::enable_reverse_op_, casadi::FunctionInternal::fd_method_, casadi::FunctionInternal::fd_options_, casadi::FunctionInternal::forward_options_, casadi::ProtoFunction::generate_options(), casadi::FunctionInternal::inputs_check_, casadi::FunctionInternal::jac_penalty_, casadi::FunctionInternal::jacobian_options_, casadi::FunctionInternal::jit_, casadi::FunctionInternal::jit_base_name_, casadi::FunctionInternal::jit_cleanup_, casadi::FunctionInternal::jit_options_, casadi::FunctionInternal::jit_serialize_, casadi::FunctionInternal::jit_temp_suffix_, casadi::FunctionInternal::max_io_, casadi::FunctionInternal::max_num_dir_, casadi::FunctionInternal::never_inline_, casadi::FunctionInternal::print_in_, casadi::FunctionInternal::print_out_, casadi::FunctionInternal::reverse_options_, and casadi::FunctionInternal::user_data_.
Referenced by casadi::FunctionInternal::forward(), casadi::MXFunction::generate_options(), and casadi::FunctionInternal::reverse().
generate_out()
void casadi::FunctionInternal::generate_out (const std::string & fname, double ** res) const inherited
Definition at line 738 of file function_internal.cpp.
{
     // Set up output stream
     std::ofstream of(fname);
     casadi_assert(of.good(), "Error opening stream '" + fname + "'.");
     normalized_setup(of);
     // Encode each input
     for (casadi_int i=0; i<n_out_; ++i) {
       const double* v = res[i];
       for (casadi_int k=0;k<nnz_out(i);++k) {
         normalized_out(of, v ? v[k] : std::numeric_limits<double>::quiet_NaN());
         of << std::endl;
       }
     }
   }
References casadi::FunctionInternal::n_out_, casadi::FunctionInternal::nnz_out(), casadi::normalized_out(), and casadi::normalized_setup().
get_abstol()
virtual double casadi::FunctionInternal::get_abstol () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mp
Reimplemented in casadi::SundialsInterface, casadi::Smoothing, casadi::CentralDiff, and casadi::ForwardDiff.
Definition at line 1046 of file function_internal.hpp.
{
       return eps;
     }
References casadi::eps.
Referenced by casadi::FiniteDiff::init().
get_default_in()
double casadi::Nlpsol::get_default_in (casadi_int ind) const inline override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1ny
Reimplemented from casadi::FunctionInternal.
Definition at line 198 of file nlpsol_impl.hpp.
 { return nlpsol_default_in(ind);}
References casadi::nlpsol_default_in().
Referenced by casadi::Nlpsol::check_inputs().
get_diff_in()
virtual bool casadi::FunctionInternal::get_diff_in (casadi_int i) inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ms
Reimplemented in casadi::BSplineInterpolant, casadi::Interpolant, casadi::GenericExternal, and casadi::Expm.
Definition at line 1063 of file function_internal.hpp.
 { return true; }
Referenced by casadi::GenericExternal::get_diff_in(), and casadi::FunctionInternal::init().
get_diff_out()
virtual bool casadi::FunctionInternal::get_diff_out (casadi_int i) inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mt
Reimplemented in casadi::GenericExternal.
Definition at line 1068 of file function_internal.hpp.
 { return true; }
Referenced by casadi::GenericExternal::get_diff_out(), and casadi::FunctionInternal::init().
get_forward()
Function casadi::Nlpsol::get_forward (casadi_int nfwd, const std::string & name, const std::vector< std::string > & inames, const std::vector< std::string > & onames, const Dict & opts) const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1o2
Reimplemented from casadi::FunctionInternal.
Definition at line 933 of file nlpsol.cpp.
{
     casadi_assert(detect_simple_bounds_is_simple_.empty(),
       "Simple bound detection not compatible with get_forward");
     // Symbolic expression for the input
     std::vector<MX> arg = mx_in(), res = mx_out();
     // Initial guesses not used for derivative calculations
     for (NlpsolInput i : {NLPSOL_X0, NLPSOL_LAM_X0, NLPSOL_LAM_G0}) {
       std::string name = arg[i].is_symbolic() ? arg[i].name() : "tmp_get_forward";
       arg[i] = MX::sym(name, Sparsity(arg[i].size()));
     }
     // Optimal solution
     MX x = res[NLPSOL_X];
     MX lam_g = res[NLPSOL_LAM_G];
     MX lam_x = res[NLPSOL_LAM_X];
     MX lam_p = res[NLPSOL_LAM_P];
     MX f = res[NLPSOL_F];
     MX g = res[NLPSOL_G];
     // Inputs used
     MX lbx = arg[NLPSOL_LBX];
     MX ubx = arg[NLPSOL_UBX];
     MX lbg = arg[NLPSOL_LBG];
     MX ubg = arg[NLPSOL_UBG];
     MX p = arg[NLPSOL_P];
     // Get KKT function
     Function kkt = this->kkt();
     // Hessian of the Lagrangian, Jacobian of the constraints
     std::vector<MX> HJ_res = kkt({x, p, 1, lam_g});
     MX JG = HJ_res.at(0);
     MX HL = HJ_res.at(1);
     // Active set (assumed known and given by the multiplier signs)
     MX ubIx = lam_x > min_lam_;
     MX lbIx = lam_x < -min_lam_;
     MX bIx = ubIx + lbIx;
     MX iIx = 1-bIx;
     MX ubIg = lam_g > min_lam_;
     MX lbIg = lam_g < -min_lam_;
     MX bIg = ubIg + lbIg;
     MX iIg = 1-bIg;
     // KKT matrix
     MX H_11 = mtimes(diag(iIx), HL) + diag(bIx);
     MX H_12 = mtimes(diag(iIx), JG.T());
     MX H_21 = mtimes(diag(bIg), JG);
     MX H_22 = diag(-iIg);
     MX H = MX::blockcat({{H_11, H_12}, {H_21, H_22}});
     // Sensitivity inputs
     std::vector<MX> fseed(NLPSOL_NUM_IN);
     MX fwd_lbx = fseed[NLPSOL_LBX] = MX::sym("fwd_lbx", repmat(x.sparsity(), 1, nfwd));
     MX fwd_ubx = fseed[NLPSOL_UBX] = MX::sym("fwd_ubx", repmat(x.sparsity(), 1, nfwd));
     MX fwd_lbg = fseed[NLPSOL_LBG] = MX::sym("fwd_lbg", repmat(g.sparsity(), 1, nfwd));
     MX fwd_ubg = fseed[NLPSOL_UBG] = MX::sym("fwd_ubg", repmat(g.sparsity(), 1, nfwd));
     MX fwd_p = fseed[NLPSOL_P] = MX::sym("fwd_p", repmat(p.sparsity(), 1, nfwd));
     // Guesses are unused
     for (NlpsolInput i : {NLPSOL_X0, NLPSOL_LAM_X0, NLPSOL_LAM_G0}) {
       fseed[i] = MX(repmat(Sparsity(arg[i].size()), 1, nfwd));
     }
     // nlp_grad has the signature
     // (x, p, lam_f, lam_g) -> (f, g, grad_x, grad_p)
     // with lam_f=1 and lam_g=lam_g, grad_x = -lam_x, grad_p=-lam_p
     Function nlp_grad = get_function("nlp_grad");
     // fwd_nlp_grad has the signature
     // (x, p, lam_f, lam_g, f, g, grad_x, grad_p,
     //  fwd_x, fwd_p, fwd_lam_f, fwd_lam_g)
     // -> (fwd_f, fwd_g, fwd_grad_x, fwd_grad_p)
     Function fwd_nlp_grad = nlp_grad.forward(nfwd);
     // Calculate sensitivities from fwd_p
     std::vector<MX> vv = {x, p, 1, lam_g, f, g, -lam_x, -lam_p, 0., fwd_p, 0., 0.};
     vv = fwd_nlp_grad(vv);
     MX fwd_g_p = vv.at(1);
     MX fwd_gL_p = vv.at(2);
     // Propagate forward seeds
     MX fwd_alpha_x = (if_else(lbIx, fwd_lbx, 0) + if_else(ubIx, fwd_ubx, 0))
                    - if_else(iIx, fwd_gL_p, 0);
     MX fwd_alpha_g = (if_else(ubIg, fwd_ubg, 0) + if_else(lbIg, fwd_lbg, 0))
                    - if_else(bIg, fwd_g_p, 0);
     MX v = MX::vertcat({fwd_alpha_x, fwd_alpha_g});
     // Solve
     v = MX::solve(H, v, sens_linsol_, sens_linsol_options_);
     // Extract sensitivities in x, lam_x and lam_g
     std::vector<MX> v_split = vertsplit(v, {0, nx_, nx_+ng_});
     MX fwd_x = v_split.at(0);
     MX fwd_lam_g = v_split.at(1);
     // Calculate sensitivities in lam_x, lam_g
     vv = {x, p, 1, lam_g, f, g, -lam_x, -lam_p,
           fwd_x, fwd_p, 0, fwd_lam_g};
     vv = fwd_nlp_grad(vv);
     MX fwd_f = vv.at(0);
     MX fwd_g = vv.at(1);
     MX fwd_lam_x = -vv.at(2);
     MX fwd_lam_p = -vv.at(3);
     // Forward sensitivities
     std::vector<MX> fsens(NLPSOL_NUM_OUT);
     fsens[NLPSOL_X] = fwd_x;
     fsens[NLPSOL_F] = fwd_f;
     fsens[NLPSOL_G] = fwd_g;
     fsens[NLPSOL_LAM_X] = fwd_lam_x;
     fsens[NLPSOL_LAM_G] = fwd_lam_g;
     fsens[NLPSOL_LAM_P] = fwd_lam_p;
     // Gather return values
     arg.insert(arg.end(), res.begin(), res.end());
     arg.insert(arg.end(), fseed.begin(), fseed.end());
     res = fsens;
     Dict options = opts;
     options["allow_duplicate_io_names"] = true;
     return Function(name, arg, res, inames, onames, options);
   }
References casadi::MX::blockcat(), casadi::Nlpsol::detect_simple_bounds_is_simple_, casadi::Function::forward(), casadi::FunctionInternal::Function, casadi::OracleFunction::get_function(), casadi::if_else(), casadi::Nlpsol::kkt(), casadi::Nlpsol::min_lam_, casadi::FunctionInternal::mx_in(), casadi::FunctionInternal::mx_out(), casadi::Nlpsol::ng_, casadi::NLPSOL_F, casadi::NLPSOL_G, casadi::NLPSOL_LAM_G, casadi::NLPSOL_LAM_G0, casadi::NLPSOL_LAM_P, casadi::NLPSOL_LAM_X, casadi::NLPSOL_LAM_X0, casadi::NLPSOL_LBG, casadi::NLPSOL_LBX, casadi::NLPSOL_NUM_IN, casadi::NLPSOL_NUM_OUT, casadi::NLPSOL_P, casadi::NLPSOL_UBG, casadi::NLPSOL_UBX, casadi::NLPSOL_X, casadi::NLPSOL_X0, casadi::Nlpsol::nx_, casadi::Nlpsol::sens_linsol_, casadi::Nlpsol::sens_linsol_options_, casadi::MX::solve(), casadi::MX::sparsity(), casadi::GenericMatrix< MX >::sym(), and casadi::MX::vertcat().
get_free()
std::vector< std::string > casadi::FunctionInternal::get_free () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mc
Reimplemented in casadi::SXFunction, and casadi::MXFunction.
Definition at line 916 of file function_internal.cpp.
{
     casadi_assert_dev(!has_free());
     return std::vector<std::string>();
   }
References casadi::FunctionInternal::has_free().
get_function() [1/2]
std::vector< std::string > casadi::OracleFunction::get_function () const override virtual inherited
-1 Indicates irregularity
Extra doc: https://github.com/casadi/casadi/wiki/L_i
Reimplemented from casadi::FunctionInternal.
Definition at line 447 of file oracle_function.cpp.
{
   std::vector<std::string> ret;
   ret.reserve(all_functions_.size());
   for (auto&& e : all_functions_) {
     ret.push_back(e.first);
   }
   return ret;
 }
References casadi::OracleFunction::all_functions_.
Referenced by casadi::Rootfinder::ad_forward(), casadi::Rootfinder::ad_reverse(), casadi::OracleFunction::calc_function(), casadi::OracleFunction::calc_sp_forward(), casadi::OracleFunction::calc_sp_reverse(), casadi::FastNewton::codegen_body(), casadi::Feasiblesqpmethod::codegen_body(), casadi::Sqpmethod::codegen_body(), casadi::FastNewton::codegen_declarations(), casadi::Feasiblesqpmethod::codegen_declarations(), casadi::Sqpmethod::codegen_declarations(), casadi::Feasiblesqpmethod::codegen_feasibility_iterations(), casadi::FixedStepIntegrator::create_advanced(), casadi::OracleFunction::create_forward(), casadi::OracleFunction::finalize(), casadi::Nlpsol::get_forward(), casadi::OracleFunction::get_function(), casadi::Nlpsol::get_reverse(), casadi::FixedStepIntegrator::init(), casadi::ImplicitFixedStepIntegrator::init(), casadi::Blocksqp::init(), casadi::BonminInterface::init(), casadi::IpoptInterface::init(), casadi::SundialsInterface::init(), casadi::FastNewton::init(), casadi::Feasiblesqpmethod::init(), casadi::Sqpmethod::init(), casadi::OracleFunction::monitored(), casadi::SundialsInterface::set_work(), casadi::Collocation::setup_step(), casadi::RungeKutta::setup_step(), casadi::Integrator::sp_jac_dae(), and casadi::Integrator::sp_jac_rdae().
get_function() [2/2]
const Function & casadi::OracleFunction::get_function (const std::string & name) const override virtual inherited
Reimplemented from casadi::FunctionInternal.
Definition at line 456 of file oracle_function.cpp.
{
   auto it = all_functions_.find(name);
   casadi_assert(it!=all_functions_.end(),
     "No function \"" + name + "\" in " + name_ + ". " +
     "Available functions: " + join(get_function()) + ".");
   return it->second.f;
 }
References casadi::OracleFunction::all_functions_, casadi::OracleFunction::get_function(), casadi::join(), and casadi::ProtoFunction::name_.
get_jac_sparsity()
Sparsity casadi::FunctionInternal::get_jac_sparsity (casadi_int oind, casadi_int iind, bool symmetric) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kz Get, if necessary generate, the sparsity of a Jacobian block
Reimplemented in casadi::GenericExternal, casadi::Expm, and casadi::CallbackInternal.
Definition at line 1765 of file function_internal.cpp.
{
     // Check if we are able to propagate dependencies through the function
     if (has_spfwd() || has_sprev()) {
       // Get weighting factor
       double w = sp_weight();
       // Skip generation, assume dense
       if (w == -1) return Sparsity();
       Sparsity sp;
       if (nnz_in(iind) > 3*bvec_size && nnz_out(oind) > 3*bvec_size &&
             GlobalOptions::hierarchical_sparsity) {
         if (symmetric) {
           sp = get_jac_sparsity_hierarchical_symm(oind, iind);
         } else {
           sp = get_jac_sparsity_hierarchical(oind, iind);
         }
       } else {
         // Number of nonzero inputs and outputs
         casadi_int nz_in = nnz_in(iind);
         casadi_int nz_out = nnz_out(oind);
         // Number of forward sweeps we must make
         casadi_int nsweep_fwd = nz_in/bvec_size;
         if (nz_in%bvec_size) nsweep_fwd++;
         // Number of adjoint sweeps we must make
         casadi_int nsweep_adj = nz_out/bvec_size;
         if (nz_out%bvec_size) nsweep_adj++;
         // Use forward mode?
         if (w*static_cast<double>(nsweep_fwd) <= (1-w)*static_cast<double>(nsweep_adj)) {
           sp = get_jac_sparsity_gen<true>(oind, iind);
         } else {
           sp = get_jac_sparsity_gen<false>(oind, iind);
         }
       }
       // There may be false positives here that are not present
       // in the reverse mode that precedes it.
       // This can lead to an assymetrical result
       //  cf. #1522
       if (symmetric) sp=sp*sp.T();
       return sp;
     } else {
       // Not calculated
       return Sparsity();
     }
   }
References casadi::bvec_size, casadi::FunctionInternal::get_jac_sparsity_hierarchical(), casadi::FunctionInternal::get_jac_sparsity_hierarchical_symm(), casadi::FunctionInternal::has_spfwd(), casadi::FunctionInternal::has_sprev(), casadi::GlobalOptions::hierarchical_sparsity, casadi::FunctionInternal::nnz_in(), casadi::FunctionInternal::nnz_out(), casadi::FunctionInternal::nz_in(), casadi::FunctionInternal::nz_out(), casadi::FunctionInternal::sp_weight(), and casadi::Sparsity::T().
Referenced by casadi::Expm::get_jac_sparsity(), casadi::GenericExternal::get_jac_sparsity(), and casadi::FunctionInternal::jac_sparsity().
get_jac_sparsity_gen()
template<bool fwd> Sparsity casadi::FunctionInternal::get_jac_sparsity_gen (casadi_int oind, casadi_int iind) const inherited
Definition at line 1110 of file function_internal.cpp.
{
     // Number of nonzero inputs and outputs
     casadi_int nz_in = nnz_in(iind);
     casadi_int nz_out = nnz_out(oind);
     // Evaluation buffers
     std::vector<typename JacSparsityTraits<fwd>::arg_t> arg(sz_arg(), nullptr);
     std::vector<bvec_t*> res(sz_res(), nullptr);
     std::vector<casadi_int> iw(sz_iw());
     std::vector<bvec_t> w(sz_w(), 0);
     // Seeds and sensitivities
     std::vector<bvec_t> seed(nz_in, 0);
     arg[iind] = get_ptr(seed);
     std::vector<bvec_t> sens(nz_out, 0);
     res[oind] = get_ptr(sens);
     if (!fwd) std::swap(seed, sens);
     // Number of forward sweeps we must make
     casadi_int nsweep = seed.size() / bvec_size;
     if (seed.size() % bvec_size) nsweep++;
     // Print
     if (verbose_) {
       casadi_message(str(nsweep) + std::string(fwd ? " forward" : " reverse") + " sweeps "
                      "needed for " + str(seed.size()) + " directions");
     }
     // Progress
     casadi_int progress = -10;
     // Temporary vectors
     std::vector<casadi_int> jcol, jrow;
     // Loop over the variables, bvec_size variables at a time
     for (casadi_int s=0; s<nsweep; ++s) {
       // Print progress
       if (verbose_) {
         casadi_int progress_new = (s*100)/nsweep;
         // Print when entering a new decade
         if (progress_new / 10 > progress / 10) {
           progress = progress_new;
           casadi_message(str(progress) + " %");
         }
       }
       // Nonzero offset
       casadi_int offset = s*bvec_size;
       // Number of local seed directions
       casadi_int ndir_local = seed.size()-offset;
       ndir_local = std::min(static_cast<casadi_int>(bvec_size), ndir_local);
       for (casadi_int i=0; i<ndir_local; ++i) {
         seed[offset+i] |= bvec_t(1)<<i;
       }
       // Propagate the dependencies
       JacSparsityTraits<fwd>::sp(this, get_ptr(arg), get_ptr(res),
                                   get_ptr(iw), get_ptr(w), memory(0));
       // Loop over the nonzeros of the output
       for (casadi_int el=0; el<sens.size(); ++el) {
         // Get the sparsity sensitivity
         bvec_t spsens = sens[el];
         if (!fwd) {
           // Clear the sensitivities for the next sweep
           sens[el] = 0;
         }
         // If there is a dependency in any of the directions
         if (spsens!=0) {
           // Loop over seed directions
           for (casadi_int i=0; i<ndir_local; ++i) {
             // If dependents on the variable
             if ((bvec_t(1) << i) & spsens) {
               // Add to pattern
               jcol.push_back(el);
               jrow.push_back(i+offset);
             }
           }
         }
       }
       // Remove the seeds
       for (casadi_int i=0; i<ndir_local; ++i) {
         seed[offset+i] = 0;
       }
     }
     // Construct sparsity pattern and return
     if (!fwd) swap(jrow, jcol);
     Sparsity ret = Sparsity::triplet(nz_out, nz_in, jcol, jrow);
     if (verbose_) {
       casadi_message("Formed Jacobian sparsity pattern (dimension " + str(ret.size()) + ", "
           + str(ret.nnz()) + " (" + str(ret.density()) + " %) nonzeros.");
     }
     return ret;
   }
References casadi::bvec_size, casadi::Sparsity::density(), casadi::get_ptr(), casadi::ProtoFunction::memory(), casadi::Sparsity::nnz(), casadi::FunctionInternal::nnz_in(), casadi::FunctionInternal::nnz_out(), casadi::FunctionInternal::nz_in(), casadi::FunctionInternal::nz_out(), casadi::Sparsity::size(), casadi::str(), casadi::FunctionInternal::sz_arg(), casadi::FunctionInternal::sz_iw(), casadi::FunctionInternal::sz_res(), casadi::FunctionInternal::sz_w(), casadi::Sparsity::triplet(), and casadi::ProtoFunction::verbose_.
get_jac_sparsity_hierarchical()
Sparsity casadi::FunctionInternal::get_jac_sparsity_hierarchical (casadi_int oind, casadi_int iind) const inherited
Decide which ad_mode to take
Definition at line 1450 of file function_internal.cpp.
{
     // Number of nonzero inputs
     casadi_int nz_in = nnz_in(iind);
     // Number of nonzero outputs
     casadi_int nz_out = nnz_out(oind);
     // Seeds and sensitivities
     std::vector<bvec_t> s_in(nz_in, 0);
     std::vector<bvec_t> s_out(nz_out, 0);
     // Evaluation buffers
     std::vector<const bvec_t*> arg_fwd(sz_arg(), nullptr);
     std::vector<bvec_t*> arg_adj(sz_arg(), nullptr);
     arg_fwd[iind] = arg_adj[iind] = get_ptr(s_in);
     std::vector<bvec_t*> res(sz_res(), nullptr);
     res[oind] = get_ptr(s_out);
     std::vector<casadi_int> iw(sz_iw());
     std::vector<bvec_t> w(sz_w());
     // Sparsity triplet accumulator
     std::vector<casadi_int> jcol, jrow;
     // Cols of the coarse blocks
     std::vector<casadi_int> coarse_col(2, 0); coarse_col[1] = nz_out;
     // Rows of the coarse blocks
     std::vector<casadi_int> coarse_row(2, 0); coarse_row[1] = nz_in;
     // Cols of the fine blocks
     std::vector<casadi_int> fine_col;
     // Rows of the fine blocks
     std::vector<casadi_int> fine_row;
     // In each iteration, subdivide each coarse block in this many fine blocks
     casadi_int subdivision = bvec_size;
     Sparsity r = Sparsity::dense(1, 1);
     // The size of a block
     casadi_int granularity_row = nz_in;
     casadi_int granularity_col = nz_out;
     bool use_fwd = true;
     casadi_int nsweeps = 0;
     bool hasrun = false;
     // Get weighting factor
     double sp_w = sp_weight();
     // Lookup table for bvec_t
     std::vector<bvec_t> bvec_lookup;
     bvec_lookup.reserve(bvec_size);
     for (casadi_int i=0;i<bvec_size;++i) {
       bvec_lookup.push_back(bvec_t(1) << i);
     }
     while (!hasrun || coarse_col.size()!=nz_out+1 || coarse_row.size()!=nz_in+1) {
       if (verbose_) {
         casadi_message("Block size: " + str(granularity_col) + " x " + str(granularity_row));
       }
       // Clear the sparsity triplet acccumulator
       jcol.clear();
       jrow.clear();
       // Clear the fine block structure
       fine_row.clear();
       fine_col.clear();
       // r transpose will be needed in the algorithm
       Sparsity rT = r.T();
       // Forward mode
       Sparsity D1 = rT.uni_coloring(r);
       // Adjoint mode
       Sparsity D2 = r.uni_coloring(rT);
       if (verbose_) {
         casadi_message("Coloring on " + str(r.dim()) + " (fwd seeps: " + str(D1.size2()) +
                  " , adj sweeps: " + str(D2.size1()) + ")");
       }
       // Use whatever required less colors if we tried both (with preference to forward mode)
       double fwd_cost = static_cast<double>(use_fwd ? granularity_row : granularity_col) *
         sp_w*static_cast<double>(D1.size2());
       double adj_cost = static_cast<double>(use_fwd ? granularity_col : granularity_row) *
         (1-sp_w)*static_cast<double>(D2.size2());
       use_fwd = fwd_cost <= adj_cost;
       if (verbose_) {
         casadi_message(std::string(use_fwd ? "Forward" : "Reverse") + " mode chosen "
             "(fwd cost: " + str(fwd_cost) + ", adj cost: " + str(adj_cost) + ")");
       }
       // Get seeds and sensitivities
       bvec_t* seed_v = use_fwd ? get_ptr(s_in) : get_ptr(s_out);
       bvec_t* sens_v = use_fwd ? get_ptr(s_out) : get_ptr(s_in);
       // The number of zeros in the seed and sensitivity directions
       casadi_int nz_seed = use_fwd ? nz_in  : nz_out;
       casadi_int nz_sens = use_fwd ? nz_out : nz_in;
       // Clear the seeds
       for (casadi_int i=0; i<nz_seed; ++i) seed_v[i]=0;
       // Choose the active jacobian coloring scheme
       Sparsity D = use_fwd ? D1 : D2;
       // Adjoint mode amounts to swapping
       if (!use_fwd) {
         std::swap(coarse_col, coarse_row);
         std::swap(granularity_col, granularity_row);
         std::swap(r, rT);
       }
       // Subdivide the coarse block cols
       for (casadi_int k=0;k<coarse_col.size()-1;++k) {
         casadi_int diff = coarse_col[k+1]-coarse_col[k];
         casadi_int new_diff = diff/subdivision;
         if (diff%subdivision>0) new_diff++;
         std::vector<casadi_int> temp = range(coarse_col[k], coarse_col[k+1], new_diff);
         fine_col.insert(fine_col.end(), temp.begin(), temp.end());
       }
       // Subdivide the coarse block rows
       for (casadi_int k=0;k<coarse_row.size()-1;++k) {
         casadi_int diff = coarse_row[k+1]-coarse_row[k];
         casadi_int new_diff = diff/subdivision;
         if (diff%subdivision>0) new_diff++;
         std::vector<casadi_int> temp = range(coarse_row[k], coarse_row[k+1], new_diff);
         fine_row.insert(fine_row.end(), temp.begin(), temp.end());
       }
       if (fine_row.back()!=coarse_row.back()) fine_row.push_back(coarse_row.back());
       if (fine_col.back()!=coarse_col.back()) fine_col.push_back(coarse_col.back());
       granularity_col = fine_col[1] - fine_col[0];
       granularity_row = fine_row[1] - fine_row[0];
       // The index into the bvec bit vector
       casadi_int bvec_i = 0;
       // Create lookup tables for the fine blocks
       std::vector<casadi_int> fine_col_lookup = lookupvector(fine_col, nz_sens+1);
       std::vector<casadi_int> fine_row_lookup = lookupvector(fine_row, nz_seed+1);
       // Triplet data used as a lookup table
       std::vector<casadi_int> lookup_col;
       std::vector<casadi_int> lookup_row;
       std::vector<casadi_int> lookup_value;
       // The maximum number of fine blocks contained in one coarse block
       casadi_int n_fine_blocks_max = 0;
       for (casadi_int i=0;i<coarse_row.size()-1;++i) {
         casadi_int del = fine_row_lookup[coarse_row[i+1]]-fine_row_lookup[coarse_row[i]];
         n_fine_blocks_max = std::max(n_fine_blocks_max, del);
       }
       // Loop over all coarse seed directions from the coloring
       for (casadi_int csd=0; csd<D.size2(); ++csd) {
         casadi_int fci_offset = 0;
         casadi_int fci_cap = bvec_size-bvec_i;
         // Flag to indicate if all fine blocks have been handled
         bool f_finished = false;
         // Loop while not finished
         while (!f_finished) {
           // Loop over all coarse rows that are found in the coloring for this coarse seed direction
           for (casadi_int k=D.colind(csd); k<D.colind(csd+1); ++k) {
             casadi_int cci = D.row(k);
             // The first and last rows of the fine block
             casadi_int fci_start = fine_row_lookup[coarse_row[cci]];
             casadi_int fci_end   = fine_row_lookup[coarse_row[cci+1]];
             // Local counter that modifies index into bvec
             casadi_int bvec_i_mod = 0;
             casadi_int value = -bvec_i + fci_offset + fci_start;
             // Loop over the rows of the fine block
             for (casadi_int fci = fci_offset; fci < std::min(fci_end-fci_start, fci_cap); ++fci) {
               // Loop over the coarse block cols that appear in the coloring
               // for the current coarse seed direction
               for (casadi_int cri=rT.colind(cci);cri<rT.colind(cci+1);++cri) {
                 lookup_col.push_back(rT.row(cri));
                 lookup_row.push_back(bvec_i+bvec_i_mod);
                 lookup_value.push_back(value);
               }
               // Toggle on seeds
               bvec_toggle(seed_v, fine_row[fci+fci_start], fine_row[fci+fci_start+1],
                           bvec_i+bvec_i_mod);
               bvec_i_mod++;
             }
           }
           // Bump bvec_i for next major coarse direction
           bvec_i+= std::min(n_fine_blocks_max, fci_cap);
           // Check if bvec buffer is full
           if (bvec_i==bvec_size || csd==D.size2()-1) {
             // Calculate sparsity for bvec_size directions at once
             // Statistics
             nsweeps+=1;
             // Construct lookup table
             IM lookup = IM::triplet(lookup_row, lookup_col, lookup_value, bvec_size,
                                     coarse_col.size());
             // Propagate the dependencies
             if (use_fwd) {
               JacSparsityTraits<true>::sp(this, get_ptr(arg_fwd), get_ptr(res),
                 get_ptr(iw), get_ptr(w), memory(0));
             } else {
               std::fill(w.begin(), w.end(), 0);
               JacSparsityTraits<false>::sp(this, get_ptr(arg_adj), get_ptr(res),
                 get_ptr(iw), get_ptr(w), memory(0));
             }
             // Temporary bit work vector
             bvec_t spsens;
             // Loop over the cols of coarse blocks
             for (casadi_int cri=0;cri<coarse_col.size()-1;++cri) {
               // Loop over the cols of fine blocks within the current coarse block
               for (casadi_int fri=fine_col_lookup[coarse_col[cri]];
                    fri<fine_col_lookup[coarse_col[cri+1]];++fri) {
                 // Lump individual sensitivities together into fine block
                 bvec_or(sens_v, spsens, fine_col[fri], fine_col[fri+1]);
                 // Next iteration if no sparsity
                 if (!spsens) continue;
                 // Loop over all bvec_bits
                 for (casadi_int bvec_i=0;bvec_i<bvec_size;++bvec_i) {
                   if (spsens & bvec_lookup[bvec_i]) {
                     // if dependency is found, add it to the new sparsity pattern
                     casadi_int ind = lookup.sparsity().get_nz(bvec_i, cri);
                     if (ind==-1) continue;
                     jrow.push_back(bvec_i+lookup->at(ind));
                     jcol.push_back(fri);
                   }
                 }
               }
             }
             // Clear the forward seeds/adjoint sensitivities, ready for next bvec sweep
             std::fill(s_in.begin(), s_in.end(), 0);
             // Clear the adjoint seeds/forward sensitivities, ready for next bvec sweep
             std::fill(s_out.begin(), s_out.end(), 0);
             // Clean lookup table
             lookup_col.clear();
             lookup_row.clear();
             lookup_value.clear();
           }
           if (n_fine_blocks_max>fci_cap) {
             fci_offset += std::min(n_fine_blocks_max, fci_cap);
             bvec_i = 0;
             fci_cap = bvec_size;
           } else {
             f_finished = true;
           }
         }
       }
       // Swap results if adjoint mode was used
       if (use_fwd) {
         // Construct fine sparsity pattern
         r = Sparsity::triplet(fine_row.size()-1, fine_col.size()-1, jrow, jcol);
         coarse_col = fine_col;
         coarse_row = fine_row;
       } else {
         // Construct fine sparsity pattern
         r = Sparsity::triplet(fine_col.size()-1, fine_row.size()-1, jcol, jrow);
         coarse_col = fine_row;
         coarse_row = fine_col;
       }
       hasrun = true;
     }
     if (verbose_) {
       casadi_message("Number of sweeps: " + str(nsweeps));
       casadi_message("Formed Jacobian sparsity pattern (dimension " + str(r.size()) + ", " +
           str(r.nnz()) + " (" + str(r.density()) + " %) nonzeros.");
     }
     return r.T();
   }
References casadi::bvec_or(), casadi::bvec_size, casadi::bvec_toggle(), casadi::Sparsity::colind(), casadi::Sparsity::dense(), casadi::Sparsity::density(), casadi::diff(), casadi::Sparsity::dim(), casadi::Sparsity::get_nz(), casadi::get_ptr(), casadi::lookupvector(), casadi::ProtoFunction::memory(), casadi::Sparsity::nnz(), casadi::FunctionInternal::nnz_in(), casadi::FunctionInternal::nnz_out(), casadi::FunctionInternal::nz_in(), casadi::FunctionInternal::nz_out(), casadi::range(), casadi::Sparsity::row(), casadi::Sparsity::size(), casadi::Sparsity::size1(), casadi::Sparsity::size2(), casadi::FunctionInternal::sp_weight(), casadi::Matrix< Scalar >::sparsity(), casadi::str(), casadi::FunctionInternal::sz_arg(), casadi::FunctionInternal::sz_iw(), casadi::FunctionInternal::sz_res(), casadi::FunctionInternal::sz_w(), casadi::Sparsity::T(), casadi::Sparsity::triplet(), casadi::Matrix< casadi_int >::triplet(), casadi::Sparsity::uni_coloring(), and casadi::ProtoFunction::verbose_.
Referenced by casadi::FunctionInternal::get_jac_sparsity().
get_jac_sparsity_hierarchical_symm()
Sparsity casadi::FunctionInternal::get_jac_sparsity_hierarchical_symm (casadi_int oind, casadi_int iind) const inherited
A flavor of get_jac_sparsity_gen that does hierarchical block structure recognition for symmetric Jacobians
Definition at line 1215 of file function_internal.cpp.
{
     casadi_assert_dev(has_spfwd());
     // Number of nonzero inputs
     casadi_int nz = nnz_in(iind);
     casadi_assert_dev(nz==nnz_out(oind));
     // Evaluation buffers
     std::vector<const bvec_t*> arg(sz_arg(), nullptr);
     std::vector<bvec_t*> res(sz_res(), nullptr);
     std::vector<casadi_int> iw(sz_iw());
     std::vector<bvec_t> w(sz_w());
     // Seeds
     std::vector<bvec_t> seed(nz, 0);
     arg[iind] = get_ptr(seed);
     // Sensitivities
     std::vector<bvec_t> sens(nz, 0);
     res[oind] = get_ptr(sens);
     // Sparsity triplet accumulator
     std::vector<casadi_int> jcol, jrow;
     // Cols/rows of the coarse blocks
     std::vector<casadi_int> coarse(2, 0); coarse[1] = nz;
     // Cols/rows of the fine blocks
     std::vector<casadi_int> fine;
     // In each iteration, subdivide each coarse block in this many fine blocks
     casadi_int subdivision = bvec_size;
     Sparsity r = Sparsity::dense(1, 1);
     // The size of a block
     casadi_int granularity = nz;
     casadi_int nsweeps = 0;
     bool hasrun = false;
     while (!hasrun || coarse.size()!=nz+1) {
       if (verbose_) casadi_message("Block size: " + str(granularity));
       // Clear the sparsity triplet acccumulator
       jcol.clear();
       jrow.clear();
       // Clear the fine block structure
       fine.clear();
       Sparsity D = r.star_coloring();
       if (verbose_) {
         casadi_message("Star coloring on " + str(r.dim()) + ": "
           + str(D.size2()) + " <-> " + str(D.size1()));
       }
       // Clear the seeds
       std::fill(seed.begin(), seed.end(), 0);
       // Subdivide the coarse block
       for (casadi_int k=0; k<coarse.size()-1; ++k) {
         casadi_int diff = coarse[k+1]-coarse[k];
         casadi_int new_diff = diff/subdivision;
         if (diff%subdivision>0) new_diff++;
         std::vector<casadi_int> temp = range(coarse[k], coarse[k+1], new_diff);
         fine.insert(fine.end(), temp.begin(), temp.end());
       }
       if (fine.back()!=coarse.back()) fine.push_back(coarse.back());
       granularity = fine[1] - fine[0];
       // The index into the bvec bit vector
       casadi_int bvec_i = 0;
       // Create lookup tables for the fine blocks
       std::vector<casadi_int> fine_lookup = lookupvector(fine, nz+1);
       // Triplet data used as a lookup table
       std::vector<casadi_int> lookup_col;
       std::vector<casadi_int> lookup_row;
       std::vector<casadi_int> lookup_value;
       // The maximum number of fine blocks contained in one coarse block
       casadi_int n_fine_blocks_max = 0;
       for (casadi_int i=0;i<coarse.size()-1;++i) {
         casadi_int del = fine_lookup[coarse[i+1]]-fine_lookup[coarse[i]];
         n_fine_blocks_max = std::max(n_fine_blocks_max, del);
       }
       // Loop over all coarse seed directions from the coloring
       for (casadi_int csd=0; csd<D.size2(); ++csd) {
         casadi_int fci_offset = 0;
         casadi_int fci_cap = bvec_size-bvec_i;
         // Flag to indicate if all fine blocks have been handled
         bool f_finished = false;
         // Loop while not finished
         while (!f_finished) {
           // Loop over all coarse rows that are found in the coloring for this coarse seed direction
           for (casadi_int k=D.colind(csd); k<D.colind(csd+1); ++k) {
             casadi_int cci = D.row(k);
             // The first and last rows of the fine block
             casadi_int fci_start = fine_lookup[coarse[cci]];
             casadi_int fci_end   = fine_lookup[coarse[cci+1]];
             // Local counter that modifies index into bvec
             casadi_int bvec_i_mod = 0;
             casadi_int value = -bvec_i + fci_offset + fci_start;
             //casadi_assert_dev(value>=0);
             // Loop over the rows of the fine block
             for (casadi_int fci = fci_offset; fci<std::min(fci_end-fci_start, fci_cap); ++fci) {
               // Loop over the coarse block cols that appear in the
               // coloring for the current coarse seed direction
               for (casadi_int cri=r.colind(cci);cri<r.colind(cci+1);++cri) {
                 lookup_col.push_back(r.row(cri));
                 lookup_row.push_back(bvec_i+bvec_i_mod);
                 lookup_value.push_back(value);
               }
               // Toggle on seeds
               bvec_toggle(get_ptr(seed), fine[fci+fci_start], fine[fci+fci_start+1],
                           bvec_i+bvec_i_mod);
               bvec_i_mod++;
             }
           }
           // Bump bvec_i for next major coarse direction
           bvec_i += std::min(n_fine_blocks_max, fci_cap);
           // Check if bvec buffer is full
           if (bvec_i==bvec_size || csd==D.size2()-1) {
             // Calculate sparsity for bvec_size directions at once
             // Statistics
             nsweeps+=1;
             // Construct lookup table
             IM lookup = IM::triplet(lookup_row, lookup_col, lookup_value,
                                     bvec_size, coarse.size());
             std::reverse(lookup_col.begin(), lookup_col.end());
             std::reverse(lookup_row.begin(), lookup_row.end());
             std::reverse(lookup_value.begin(), lookup_value.end());
             IM duplicates =
               IM::triplet(lookup_row, lookup_col, lookup_value, bvec_size, coarse.size())
               - lookup;
             duplicates = sparsify(duplicates);
             lookup(duplicates.sparsity()) = -bvec_size;
             // Propagate the dependencies
             JacSparsityTraits<true>::sp(this, get_ptr(arg), get_ptr(res),
               get_ptr(iw), get_ptr(w), nullptr);
             // Temporary bit work vector
             bvec_t spsens;
             // Loop over the cols of coarse blocks
             for (casadi_int cri=0; cri<coarse.size()-1; ++cri) {
               // Loop over the cols of fine blocks within the current coarse block
               for (casadi_int fri=fine_lookup[coarse[cri]];fri<fine_lookup[coarse[cri+1]];++fri) {
                 // Lump individual sensitivities together into fine block
                 bvec_or(get_ptr(sens), spsens, fine[fri], fine[fri+1]);
                 // Loop over all bvec_bits
                 for (casadi_int bvec_i=0;bvec_i<bvec_size;++bvec_i) {
                   if (spsens & (bvec_t(1) << bvec_i)) {
                     // if dependency is found, add it to the new sparsity pattern
                     casadi_int ind = lookup.sparsity().get_nz(bvec_i, cri);
                     if (ind==-1) continue;
                     casadi_int lk = lookup->at(ind);
                     if (lk>-bvec_size) {
                       jrow.push_back(bvec_i+lk);
                       jcol.push_back(fri);
                       jrow.push_back(fri);
                       jcol.push_back(bvec_i+lk);
                     }
                   }
                 }
               }
             }
             // Clear the forward seeds/adjoint sensitivities, ready for next bvec sweep
             std::fill(seed.begin(), seed.end(), 0);
             // Clean lookup table
             lookup_col.clear();
             lookup_row.clear();
             lookup_value.clear();
           }
           if (n_fine_blocks_max>fci_cap) {
             fci_offset += std::min(n_fine_blocks_max, fci_cap);
             bvec_i = 0;
             fci_cap = bvec_size;
           } else {
             f_finished = true;
           }
         }
       }
       // Construct fine sparsity pattern
       r = Sparsity::triplet(fine.size()-1, fine.size()-1, jrow, jcol);
       // There may be false positives here that are not present
       // in the reverse mode that precedes it.
       // This can lead to an assymetrical result
       //  cf. #1522
       r=r*r.T();
       coarse = fine;
       hasrun = true;
     }
     if (verbose_) {
       casadi_message("Number of sweeps: " + str(nsweeps));
       casadi_message("Formed Jacobian sparsity pattern (dimension " + str(r.size()) +
           ", " + str(r.nnz()) + " (" + str(r.density()) + " %) nonzeros.");
     }
     return r.T();
   }
References casadi::bvec_or(), casadi::bvec_size, casadi::bvec_toggle(), casadi::Sparsity::colind(), casadi::Sparsity::dense(), casadi::Sparsity::density(), casadi::diff(), casadi::Sparsity::dim(), casadi::Sparsity::get_nz(), casadi::get_ptr(), casadi::FunctionInternal::has_spfwd(), casadi::lookupvector(), casadi::Sparsity::nnz(), casadi::FunctionInternal::nnz_in(), casadi::FunctionInternal::nnz_out(), casadi::range(), casadi::Sparsity::row(), casadi::Sparsity::size(), casadi::Sparsity::size1(), casadi::Sparsity::size2(), casadi::Matrix< Scalar >::sparsity(), casadi::Sparsity::star_coloring(), casadi::str(), casadi::FunctionInternal::sz_arg(), casadi::FunctionInternal::sz_iw(), casadi::FunctionInternal::sz_res(), casadi::FunctionInternal::sz_w(), casadi::Sparsity::T(), casadi::Sparsity::triplet(), casadi::Matrix< casadi_int >::triplet(), and casadi::ProtoFunction::verbose_.
Referenced by casadi::FunctionInternal::get_jac_sparsity().
get_jacobian()
Function casadi::FunctionInternal::get_jacobian (const std::string & name, const std::vector< std::string > & inames, const std::vector< std::string > & onames, const Dict & opts) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ky
Reimplemented in casadi::LinearInterpolantJac, casadi::LinearInterpolant, casadi::BSplineInterpolant, casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >, casadi::JitFunction, casadi::External, and casadi::CallbackInternal.
Definition at line 2210 of file function_internal.cpp.
{
     casadi_error("'get_jacobian' not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
Referenced by casadi::External::get_jacobian(), casadi::BSplineInterpolant::get_jacobian(), casadi::LinearInterpolantJac::get_jacobian(), and casadi::FunctionInternal::jacobian().
get_max_in()
virtual double casadi::FunctionInternal::get_max_in (casadi_int ind) const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mm
Definition at line 1017 of file function_internal.hpp.
{
       return inf;
     }
References casadi::inf.
get_min_in()
virtual double casadi::FunctionInternal::get_min_in (casadi_int ind) const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mn
Definition at line 1024 of file function_internal.hpp.
{
       return -inf;
     }
References casadi::inf.
get_n_in()
size_t casadi::Nlpsol::get_n_in () inline override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1np
Reimplemented from casadi::FunctionInternal.
Definition at line 139 of file nlpsol_impl.hpp.
 { return NLPSOL_NUM_IN;}
References casadi::NLPSOL_NUM_IN.
get_n_out()
size_t casadi::Nlpsol::get_n_out () inline override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1np
Reimplemented from casadi::FunctionInternal.
Definition at line 140 of file nlpsol_impl.hpp.
 { return NLPSOL_NUM_OUT;}
References casadi::NLPSOL_NUM_OUT.
get_name_in()
std::string casadi::Nlpsol::get_name_in (casadi_int i) inline override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1nr
Reimplemented from casadi::FunctionInternal.
Definition at line 155 of file nlpsol_impl.hpp.
 { return nlpsol_in(i);}
References casadi::nlpsol_in().
get_name_out()
std::string casadi::Nlpsol::get_name_out (casadi_int i) inline override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1nr
Reimplemented from casadi::FunctionInternal.
Definition at line 156 of file nlpsol_impl.hpp.
 { return nlpsol_out(i);}
References casadi::nlpsol_out().
get_nominal_in()
virtual std::vector<double> casadi::FunctionInternal::get_nominal_in (casadi_int ind) const inline virtual inherited
Definition at line 1028 of file function_internal.hpp.
{
       return std::vector<double>(nnz_in(ind), 1.);
     }
get_nominal_out()
virtual std::vector<double> casadi::FunctionInternal::get_nominal_out (casadi_int ind) const inline virtual inherited
Definition at line 1032 of file function_internal.hpp.
{
       return std::vector<double>(nnz_out(ind), 1.);
     }
get_options()
const Options& casadi::AmplInterface::get_options () const inline override virtual
Reimplemented from casadi::Nlpsol.
Definition at line 75 of file ampl_interface.hpp.
 { return options_;}
get_partition()
void casadi::FunctionInternal::get_partition (casadi_int iind, casadi_int oind, Sparsity & D1, Sparsity & D2, bool compact, bool symmetric, bool allow_forward, bool allow_reverse) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_md
Definition at line 1887 of file function_internal.cpp.
{
     if (verbose_) casadi_message(name_ + "::get_partition");
     casadi_assert(allow_forward || allow_reverse, "Inconsistent options");
     // Sparsity pattern with transpose
     Sparsity &AT = jac_sparsity(oind, iind, compact, symmetric);
     Sparsity A = symmetric ? AT : AT.T();
     // Get seed matrices by graph coloring
     if (symmetric) {
       casadi_assert_dev(enable_forward_ || enable_fd_);
       casadi_assert_dev(allow_forward);
       // Star coloring if symmetric
       if (verbose_) casadi_message("FunctionInternal::getPartition star_coloring");
       D1 = A.star_coloring();
       if (verbose_) {
         casadi_message("Star coloring completed: " + str(D1.size2())
           + " directional derivatives needed ("
                  + str(A.size1()) + " without coloring).");
       }
     } else {
       casadi_assert_dev(enable_forward_ || enable_fd_ || enable_reverse_);
       // Get weighting factor
       double w = ad_weight();
       // Which AD mode?
       if (w==1) allow_forward = false;
       if (w==0) allow_reverse = false;
       casadi_assert(allow_forward || allow_reverse, "Conflicting ad weights");
       // Best coloring encountered so far (relatively tight upper bound)
       double best_coloring = std::numeric_limits<double>::infinity();
       // Test forward mode first?
       bool test_fwd_first = allow_forward && w*static_cast<double>(A.size1()) <=
         (1-w)*static_cast<double>(A.size2());
       casadi_int mode_fwd = test_fwd_first ? 0 : 1;
       // Test both coloring modes
       for (casadi_int mode=0; mode<2; ++mode) {
         // Is this the forward mode?
         bool fwd = mode==mode_fwd;
         // Skip?
         if (!allow_forward && fwd) continue;
         if (!allow_reverse && !fwd) continue;
         // Perform the coloring
         if (fwd) {
           if (verbose_) casadi_message("Unidirectional coloring (forward mode)");
           bool d = best_coloring>=w*static_cast<double>(A.size1());
           casadi_int max_colorings_to_test =
             d ? A.size1() : static_cast<casadi_int>(floor(best_coloring/w));
           D1 = AT.uni_coloring(A, max_colorings_to_test);
           if (D1.is_null()) {
             if (verbose_) {
               casadi_message("Forward mode coloring interrupted (more than "
                              + str(max_colorings_to_test) + " needed).");
             }
           } else {
             if (verbose_) {
               casadi_message("Forward mode coloring completed: "
                              + str(D1.size2()) + " directional derivatives needed ("
                              + str(A.size1()) + " without coloring).");
             }
             D2 = Sparsity();
             best_coloring = w*static_cast<double>(D1.size2());
           }
         } else {
           if (verbose_) casadi_message("Unidirectional coloring (adjoint mode)");
           bool d = best_coloring>=(1-w)*static_cast<double>(A.size2());
           casadi_int max_colorings_to_test =
             d ? A.size2() : static_cast<casadi_int>(floor(best_coloring/(1-w)));
           D2 = A.uni_coloring(AT, max_colorings_to_test);
           if (D2.is_null()) {
             if (verbose_) {
               casadi_message("Adjoint mode coloring interrupted (more than "
                             + str(max_colorings_to_test) + " needed).");
             }
           } else {
             if (verbose_) {
               casadi_message("Adjoint mode coloring completed: "
                              + str(D2.size2()) + " directional derivatives needed ("
                              + str(A.size2()) + " without coloring).");
             }
             D1 = Sparsity();
             best_coloring = (1-w)*static_cast<double>(D2.size2());
           }
         }
       }
     }
   }
References casadi::FunctionInternal::ad_weight(), casadi::FunctionInternal::enable_fd_, casadi::FunctionInternal::enable_forward_, casadi::FunctionInternal::enable_reverse_, casadi::SharedObject::is_null(), casadi::FunctionInternal::jac_sparsity(), casadi::ProtoFunction::name_, casadi::Sparsity::size1(), casadi::Sparsity::size2(), casadi::Sparsity::star_coloring(), casadi::str(), casadi::Sparsity::T(), casadi::Sparsity::uni_coloring(), and casadi::ProtoFunction::verbose_.
get_reltol()
virtual double casadi::FunctionInternal::get_reltol () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mo
Reimplemented in casadi::SundialsInterface.
Definition at line 1039 of file function_internal.hpp.
{
       return eps;
     }
References casadi::eps.
Referenced by casadi::FiniteDiff::init().
get_reverse()
Function casadi::Nlpsol::get_reverse (casadi_int nadj, const std::string & name, const std::vector< std::string > & inames, const std::vector< std::string > & onames, const Dict & opts) const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1o3
Reimplemented from casadi::FunctionInternal.
Definition at line 1064 of file nlpsol.cpp.
{
     casadi_assert(detect_simple_bounds_is_simple_.empty(),
       "Simple bound detection not compatible with get_reverse");
     // Symbolic expression for the input
     std::vector<MX> arg = mx_in(), res = mx_out();
     // Initial guesses not used for derivative calculations
     for (NlpsolInput i : {NLPSOL_X0, NLPSOL_LAM_X0, NLPSOL_LAM_G0}) {
       std::string name = arg[i].is_symbolic() ? arg[i].name() : "tmp_get_reverse";
       arg[i] = MX::sym(name, Sparsity(arg[i].size()));
     }
     // Optimal solution
     MX x = res[NLPSOL_X];
     MX lam_g = res[NLPSOL_LAM_G];
     MX lam_x = res[NLPSOL_LAM_X];
     MX lam_p = res[NLPSOL_LAM_P];
     MX f = res[NLPSOL_F];
     MX g = res[NLPSOL_G];
     // Inputs used
     MX lbx = arg[NLPSOL_LBX];
     MX ubx = arg[NLPSOL_UBX];
     MX lbg = arg[NLPSOL_LBG];
     MX ubg = arg[NLPSOL_UBG];
     MX p = arg[NLPSOL_P];
     // Get KKT function
     Function kkt = this->kkt();
     // Hessian of the Lagrangian, Jacobian of the constraints
     std::vector<MX> HJ_res = kkt({x, p, 1, lam_g});
     MX JG = HJ_res.at(0);
     MX HL = HJ_res.at(1);
     // Active set (assumed known and given by the multiplier signs)
     MX ubIx = lam_x > min_lam_;
     MX lbIx = lam_x < -min_lam_;
     MX bIx = ubIx + lbIx;
     MX iIx = 1-bIx;
     MX ubIg = lam_g > min_lam_;
     MX lbIg = lam_g < -min_lam_;
     MX bIg = ubIg + lbIg;
     MX iIg = 1-bIg;
     // KKT matrix
     MX H_11 = mtimes(diag(iIx), HL) + diag(bIx);
     MX H_12 = mtimes(diag(iIx), JG.T());
     MX H_21 = mtimes(diag(bIg), JG);
     MX H_22 = diag(-iIg);
     MX H = MX::blockcat({{H_11, H_12}, {H_21, H_22}});
     // Sensitivity inputs
     std::vector<MX> aseed(NLPSOL_NUM_OUT);
     MX adj_x = aseed[NLPSOL_X] = MX::sym("adj_x", repmat(x.sparsity(), 1, nadj));
     MX adj_lam_g = aseed[NLPSOL_LAM_G] = MX::sym("adj_lam_g", repmat(g.sparsity(), 1, nadj));
     MX adj_lam_x = aseed[NLPSOL_LAM_X] = MX::sym("adj_lam_x", repmat(x.sparsity(), 1, nadj));
     MX adj_lam_p = aseed[NLPSOL_LAM_P] = MX::sym("adj_lam_p", repmat(p.sparsity(), 1, nadj));
     MX adj_f = aseed[NLPSOL_F] = MX::sym("adj_f", Sparsity::dense(1, nadj));
     MX adj_g = aseed[NLPSOL_G] = MX::sym("adj_g", repmat(g.sparsity(), 1, nadj));
     // nlp_grad has the signature
     // (x, p, lam_f, lam_g) -> (f, g, grad_x, grad_p)
     // with lam_f=1 and lam_g=lam_g, grad_x = -lam_x, grad_p=-lam_p
     Function nlp_grad = get_function("nlp_grad");
     // rev_nlp_grad has the signature
     // (x, p, lam_f, lam_g, f, g, grad_x, grad_p,
     //  adj_f, adj_g, adj_grad_x, adj_grad_p)
     // -> (adj_x, adj_p, adj_lam_f, adj_lam_g)
     Function rev_nlp_grad = nlp_grad.reverse(nadj);
     // Calculate sensitivities from f, g and lam_x
     std::vector<MX> vv = {x, p, 1, lam_g, f, g, -lam_x, -lam_p,
                      adj_f, adj_g, -adj_lam_x, -adj_lam_p};
     vv = rev_nlp_grad(vv);
     MX adj_x0 = vv.at(0);
     MX adj_p0 = vv.at(1);
     MX adj_lam_g0 = vv.at(3);
     // Solve to get beta_x_bar, beta_g_bar
     MX v = MX::vertcat({adj_x + adj_x0, adj_lam_g + adj_lam_g0});
     v = MX::solve(H.T(), v, sens_linsol_, sens_linsol_options_);
     std::vector<MX> v_split = vertsplit(v, {0, nx_, nx_+ng_});
     MX beta_x_bar = v_split.at(0);
     MX beta_g_bar = v_split.at(1);
     // Calculate sensitivities in p
     vv = {x, p, 1, lam_g, f, g, -lam_x, -lam_p,
           0, bIg*beta_g_bar, iIx*beta_x_bar, 0};
     vv = rev_nlp_grad(vv);
     MX adj_p = vv.at(1);
     // Reverse sensitivities
     std::vector<MX> asens(NLPSOL_NUM_IN);
     asens[NLPSOL_UBX] = if_else(ubIx, beta_x_bar, 0);
     asens[NLPSOL_LBX] = if_else(lbIx, beta_x_bar, 0);
     asens[NLPSOL_UBG] = if_else(ubIg, beta_g_bar, 0);
     asens[NLPSOL_LBG] = if_else(lbIg, beta_g_bar, 0);
     asens[NLPSOL_P] = adj_p0 - adj_p;
     // Guesses are unused
     for (NlpsolInput i : {NLPSOL_X0, NLPSOL_LAM_X0, NLPSOL_LAM_G0}) {
       asens[i] = MX(repmat(Sparsity(arg[i].size()), 1, nadj));
     }
     // Gather return values
     arg.insert(arg.end(), res.begin(), res.end());
     arg.insert(arg.end(), aseed.begin(), aseed.end());
     res = asens;
     Dict options = opts;
     options["allow_duplicate_io_names"] = true;
     return Function(name, arg, res, inames, onames, options);
   }
References casadi::MX::blockcat(), casadi::Sparsity::dense(), casadi::Nlpsol::detect_simple_bounds_is_simple_, casadi::FunctionInternal::Function, casadi::OracleFunction::get_function(), casadi::if_else(), casadi::Nlpsol::kkt(), casadi::Nlpsol::min_lam_, casadi::FunctionInternal::mx_in(), casadi::FunctionInternal::mx_out(), casadi::Nlpsol::ng_, casadi::NLPSOL_F, casadi::NLPSOL_G, casadi::NLPSOL_LAM_G, casadi::NLPSOL_LAM_G0, casadi::NLPSOL_LAM_P, casadi::NLPSOL_LAM_X, casadi::NLPSOL_LAM_X0, casadi::NLPSOL_LBG, casadi::NLPSOL_LBX, casadi::NLPSOL_NUM_IN, casadi::NLPSOL_NUM_OUT, casadi::NLPSOL_P, casadi::NLPSOL_UBG, casadi::NLPSOL_UBX, casadi::NLPSOL_X, casadi::NLPSOL_X0, casadi::Nlpsol::nx_, casadi::Function::reverse(), casadi::Nlpsol::sens_linsol_, casadi::Nlpsol::sens_linsol_options_, casadi::MX::solve(), casadi::MX::sparsity(), casadi::GenericMatrix< MX >::sym(), casadi::MX::T(), and casadi::MX::vertcat().
get_sparsity_in()
Sparsity casadi::Nlpsol::get_sparsity_in (casadi_int i) override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1nq
Reimplemented from casadi::FunctionInternal.
Definition at line 291 of file nlpsol.cpp.
{
     switch (static_cast<NlpsolInput>(i)) {
     case NLPSOL_X0:
     case NLPSOL_LBX:
     case NLPSOL_UBX:
     case NLPSOL_LAM_X0:
       return get_sparsity_out(NLPSOL_X);
     case NLPSOL_LBG:
     case NLPSOL_UBG:
     case NLPSOL_LAM_G0:
       return get_sparsity_out(NLPSOL_G);
     case NLPSOL_P:
       return oracle_.sparsity_in(NL_P);
     case NLPSOL_NUM_IN: break;
     }
     return Sparsity();
   }
References casadi::Nlpsol::get_sparsity_out(), casadi::NL_P, casadi::NLPSOL_G, casadi::NLPSOL_LAM_G0, casadi::NLPSOL_LAM_X0, casadi::NLPSOL_LBG, casadi::NLPSOL_LBX, casadi::NLPSOL_NUM_IN, casadi::NLPSOL_P, casadi::NLPSOL_UBG, casadi::NLPSOL_UBX, casadi::NLPSOL_X, casadi::NLPSOL_X0, casadi::OracleFunction::oracle_, and casadi::Function::sparsity_in().
Referenced by casadi::Nlpsol::get_sparsity_out().
get_sparsity_out()
Sparsity casadi::Nlpsol::get_sparsity_out (casadi_int i) override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1nq
Reimplemented from casadi::FunctionInternal.
Definition at line 309 of file nlpsol.cpp.
{
     switch (static_cast<NlpsolOutput>(i)) {
     case NLPSOL_F:
       return oracle_.sparsity_out(NL_F);
     case NLPSOL_X:
     case NLPSOL_LAM_X:
       return oracle_.sparsity_in(NL_X);
     case NLPSOL_LAM_G:
     case NLPSOL_G:
       if (detect_simple_bounds_is_simple_.empty()) {
         return oracle_.sparsity_out(NL_G);
       } else {
         return Sparsity::dense(detect_simple_bounds_is_simple_.size());
       }
     case NLPSOL_LAM_P:
       return get_sparsity_in(NLPSOL_P);
     case NLPSOL_NUM_OUT: break;
     }
     return Sparsity();
   }
References casadi::Sparsity::dense(), casadi::Nlpsol::detect_simple_bounds_is_simple_, casadi::Nlpsol::get_sparsity_in(), casadi::NL_F, casadi::NL_G, casadi::NL_X, casadi::NLPSOL_F, casadi::NLPSOL_G, casadi::NLPSOL_LAM_G, casadi::NLPSOL_LAM_P, casadi::NLPSOL_LAM_X, casadi::NLPSOL_NUM_OUT, casadi::NLPSOL_P, casadi::NLPSOL_X, casadi::OracleFunction::oracle_, casadi::Function::sparsity_in(), and casadi::Function::sparsity_out().
Referenced by casadi::Nlpsol::get_sparsity_in().
get_stats()
Dict casadi::Nlpsol::get_stats (void * mem) const override virtual inherited
Reimplemented from casadi::ProtoFunction.
Reimplemented in casadi::Sqpmethod, casadi::Scpgen, casadi::Qrsqp, casadi::Feasiblesqpmethod, casadi::WorhpInterface, casadi::SnoptInterface, casadi::KnitroInterface, casadi::IpoptInterface, and casadi::BonminInterface.
Definition at line 1227 of file nlpsol.cpp.
{
     Dict stats = OracleFunction::get_stats(mem);
     auto m = static_cast<NlpsolMemory*>(mem);
     stats["success"] = m->success;
     stats["unified_return_status"] = string_from_UnifiedReturnStatus(m->unified_return_status);
     return stats;
   }
References casadi::OracleFunction::get_stats(), casadi::FunctionInternal::string_from_UnifiedReturnStatus(), and casadi::NlpsolMemory::success.
Referenced by casadi::BonminInterface::get_stats(), casadi::IpoptInterface::get_stats(), casadi::KnitroInterface::get_stats(), casadi::SnoptInterface::get_stats(), casadi::WorhpInterface::get_stats(), casadi::Feasiblesqpmethod::get_stats(), casadi::Qrsqp::get_stats(), casadi::Scpgen::get_stats(), and casadi::Sqpmethod::get_stats().
getAdaptorSolverName()
virtual std::string casadi::FunctionInternal::getAdaptorSolverName () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_k3
Definition at line 292 of file function_internal.hpp.
 { return ""; }
getCount()
casadi_int casadi::SharedObjectInternal::getCount () const inherited
Definition at line 58 of file shared_object_internal.cpp.
{
     return count;
   }
getPlugin()
PluginInterface< Nlpsol >::Plugin & casadi::PluginInterface< Nlpsol >::getPlugin (const std::string & pname) static inherited
Definition at line 100 of file plugin_interface.hpp.
{
     // Check if the solver has been loaded
     auto it=Derived::solvers_.find(pname);
     // Load the solver if needed
     if (it==Derived::solvers_.end()) {
       load_plugin(pname);
       it=Derived::solvers_.find(pname);
     }
     casadi_assert_dev(it!=Derived::solvers_.end());
     return it->second;
   }
getReducedHessian()
DM casadi::Nlpsol::getReducedHessian () virtual inherited
Definition at line 639 of file nlpsol.cpp.
{
     casadi_error("getReducedHessian not defined for class " + class_name());
     return DM();
   }
References casadi::Nlpsol::class_name().
has_codegen()
virtual bool casadi::FunctionInternal::has_codegen () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_m3
Reimplemented in casadi::LinearInterpolantJac, casadi::LinearInterpolant, casadi::BSplineInterpolant, casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >, casadi::Switch, casadi::MapSum, casadi::Map, casadi::JitFunction, and casadi::FiniteDiff.
Definition at line 861 of file function_internal.hpp.
 { return false;}
Referenced by casadi::FunctionInternal::finalize().
has_derivative()
bool casadi::FunctionInternal::has_derivative () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_l4
Definition at line 2771 of file function_internal.cpp.
{
     return enable_forward_ || enable_reverse_ || enable_jacobian_ || enable_fd_;
   }
References casadi::FunctionInternal::enable_fd_, casadi::FunctionInternal::enable_forward_, casadi::FunctionInternal::enable_jacobian_, and casadi::FunctionInternal::enable_reverse_.
Referenced by casadi::FunctionInternal::call_forward(), casadi::FunctionInternal::call_reverse(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::jacobian(), and casadi::FunctionInternal::reverse().
has_eval_dm()
virtual bool casadi::FunctionInternal::has_eval_dm () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ke
Reimplemented in casadi::CallbackInternal.
Definition at line 393 of file function_internal.hpp.
 { return false;}
Referenced by casadi::FunctionInternal::eval().
has_forward()
bool casadi::Nlpsol::has_forward (casadi_int nfwd) const inline override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1o2
Reimplemented from casadi::FunctionInternal.
Definition at line 232 of file nlpsol_impl.hpp.
 { return true;}
has_free()
virtual bool casadi::FunctionInternal::has_free () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_l8
Reimplemented in casadi::SXFunction, and casadi::MXFunction.
Definition at line 701 of file function_internal.hpp.
 { return false;}
Referenced by casadi::FunctionInternal::get_free().
has_function()
bool casadi::OracleFunction::has_function (const std::string & fname) const override virtual inherited
Reimplemented from casadi::FunctionInternal.
Definition at line 472 of file oracle_function.cpp.
{
   return all_functions_.find(fname) != all_functions_.end();
 }
References casadi::OracleFunction::all_functions_.
Referenced by casadi::OracleFunction::create_forward(), casadi::FixedStepIntegrator::init(), casadi::BonminInterface::init(), casadi::IpoptInterface::init(), casadi::Feasiblesqpmethod::init(), casadi::Sqpmethod::init(), and casadi::OracleFunction::set_function().
has_jac_sparsity()
virtual bool casadi::FunctionInternal::has_jac_sparsity (casadi_int oind, casadi_int iind) const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kz Get, if necessary generate, the sparsity of a Jacobian block
Reimplemented in casadi::GenericExternal, casadi::Expm, and casadi::CallbackInternal.
Definition at line 600 of file function_internal.hpp.
 { return false;}
Referenced by casadi::FunctionInternal::get_sparsity_out(), casadi::GenericExternal::has_jac_sparsity(), and casadi::FunctionInternal::jac_sparsity().
has_jacobian()
virtual bool casadi::FunctionInternal::has_jacobian () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ky
Reimplemented in casadi::LinearInterpolantJac, casadi::LinearInterpolant, casadi::BSplineInterpolant, casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >, casadi::JitFunction, casadi::External, and casadi::CallbackInternal.
Definition at line 587 of file function_internal.hpp.
 { return false;}
Referenced by casadi::External::has_jacobian(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::jacobian().
has_option()
bool casadi::ProtoFunction::has_option (const std::string & option_name) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_jj
Definition at line 900 of file function_internal.cpp.
{
     return get_options().find(option_name) != 0;
   }
References casadi::Options::find(), and casadi::ProtoFunction::get_options().
has_plugin()
bool casadi::PluginInterface< Nlpsol >::has_plugin (const std::string & pname, bool verbose = false) static inherited
Definition at line 75 of file plugin_interface.hpp.
{
     // Quick return if available
     if (Derived::solvers_.find(pname) != Derived::solvers_.end()) {
       return true;
     }
     // Try loading the plugin
     try {
       (void)load_plugin(pname, false);
       return true;
     } catch (CasadiException& ex) {
       if (verbose) {
         casadi_warning(ex.what());
       }
       return false;
     }
   }
has_reverse()
bool casadi::Nlpsol::has_reverse (casadi_int nadj) const inline override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1o3
Reimplemented from casadi::FunctionInternal.
Definition at line 243 of file nlpsol_impl.hpp.
 { return true;}
has_spfwd()
virtual bool casadi::FunctionInternal::has_spfwd () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ka
Reimplemented in casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >, casadi::Rootfinder, casadi::MapSum, casadi::Map, and casadi::Integrator.
Definition at line 364 of file function_internal.hpp.
 { return false;}
Referenced by casadi::FunctionInternal::get_jac_sparsity(), casadi::FunctionInternal::get_jac_sparsity_hierarchical_symm(), casadi::FunctionInternal::jac_sparsity(), and casadi::FunctionInternal::sp_weight().
has_sprev()
virtual bool casadi::FunctionInternal::has_sprev () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ka
Reimplemented in casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >, casadi::Rootfinder, casadi::MapSum, casadi::Map, and casadi::Integrator.
Definition at line 365 of file function_internal.hpp.
 { return false;}
Referenced by casadi::FunctionInternal::get_jac_sparsity(), casadi::FunctionInternal::jac_sparsity(), and casadi::FunctionInternal::sp_weight().
incache()
bool casadi::FunctionInternal::incache (const std::string & fname, Function & f, const std::string & suffix = "") const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lk
Definition at line 962 of file function_internal.cpp.
{
     auto it = cache_.find(fname + ":" + suffix);
     if (it!=cache_.end() && it->second.alive()) {
       f = shared_cast<Function>(it->second.shared());
       return true;
     } else {
       return false;
     }
   }
References casadi::FunctionInternal::cache_.
Referenced by casadi::MapSum::create(), casadi::OracleFunction::create_function(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::jacobian(), casadi::FunctionInternal::map(), casadi::FunctionInternal::reverse(), and casadi::FunctionInternal::wrap().
index_in()
casadi_int casadi::FunctionInternal::index_in (const std::string & name) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mu
Definition at line 1073 of file function_internal.hpp.
{
       for (casadi_int i=0; i<name_in_.size(); ++i) {
         if (name_in_[i]==name) return i;
       }
       casadi_error("FunctionInternal::index_in: could not find entry \""
                    + name + "\". Available names are: " + str(name_in_) + ".");
       return -1;
     }
References casadi::str().
Referenced by casadi::FunctionInternal::convert_arg().
index_out()
casadi_int casadi::FunctionInternal::index_out (const std::string & name) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mv
Definition at line 1085 of file function_internal.hpp.
{
       for (casadi_int i=0; i<name_out_.size(); ++i) {
         if (name_out_[i]==name) return i;
       }
       casadi_error("FunctionInternal::index_out: could not find entry \""
                    + name + "\". Available names are: " + str(name_out_) + ".");
       return -1;
     }
References casadi::str().
Referenced by casadi::FunctionInternal::convert_res().
info()
Dict casadi::FunctionInternal::info () const virtual inherited
Obtain information about function
Reimplemented in casadi::Switch, and casadi::Map.
Definition at line 2807 of file function_internal.cpp.
{
     return Dict();
   }
Referenced by casadi::MXFunction::export_code_body(), casadi::Blocksqp::feasibilityRestorationPhase(), casadi::Blocksqp::filterLineSearch(), casadi::Blocksqp::fullstep(), casadi::BSplineInterpolant::init(), casadi::Blocksqp::kktErrorReduction(), casadi::Feasiblesqpmethod::print_iteration(), casadi::Sqpmethod::print_iteration(), casadi::Blocksqp::secondOrderCorrection(), casadi::SnoptInterface::solve(), casadi::Feasiblesqpmethod::solve(), casadi::Sqpmethod::solve(), and casadi::Sqpmethod::solve_elastic_mode().
init()
void casadi::AmplInterface::init (const Dict & opts) override virtual
Reimplemented from casadi::Nlpsol.
Definition at line 66 of file ampl_interface.cpp.
{
     // Call the init method of the base class
     Nlpsol::init(opts);
     // Set default options
     solver_ = "ipopt";
     // Read user options
     for (auto&& op : opts) {
       if (op.first=="solver") {
         solver_ = op.second.to_string();
       }
     }
     // Extract the expressions
     casadi_assert(oracle().is_a("SXFunction"),
                   "Only SX supported currently.");
     std::vector<SX> xp = oracle().sx_in();
     std::vector<SX> fg = oracle()(xp);
     // Get x, p, f and g
     SX x = xp.at(NL_X);
     SX p = xp.at(NL_P);
     SX f = fg.at(NL_F);
     SX g = fg.at(NL_G);
     casadi_assert(p.is_empty(), "'p' currently not supported");
     // Names of the variables, constraints
     std::vector<std::string> x_name, g_name;
     for (casadi_int i=0; i<nx_; ++i) x_name.push_back("x[" + str(i) + "]");
     for (casadi_int i=0; i<ng_; ++i) g_name.push_back("g[" + str(i) + "]");
     casadi_int max_x_name = x_name.back().size();
     casadi_int max_g_name = g_name.empty() ? 0 : g_name.back().size();
     // Calculate the Jacobian, gradient
     Sparsity jac_g = SX::jacobian(g, x).sparsity();
     Sparsity jac_f = SX::jacobian(f, x).sparsity();
     // Extract the shared subexpressions
     std::vector<SX> ex = {f, g}, v, vdef;
     shared(ex, v, vdef);
     f = ex[0];
     g = ex[1];
     // Header
     nl_init_ << "g3 1 1 0\n";
     // Type of constraints
     nl_init_ << nx_ << " " // number of variables
        << ng_ << " " // number of constraints
        << 1 << " " // number of objectives
        << 0 << " " // number of ranges
        << 0 << " " // ?
        << 0 << "\n"; // number of logical constraints
     // Nonlinearity - assume all nonlinear for now TODO: Detect
     nl_init_ << ng_ << " "  // nonlinear constraints
        << 1 << "\n"; // nonlinear objectives
     // Network constraints
     nl_init_ << 0 << " " // nonlinear
        << 0 << "\n"; // linear
     // Nonlinear variables
     nl_init_ << nx_ << " " // in constraints
        << nx_ << " " // in objectives
        << nx_ << "\n"; // in both
     // Linear network ..
     nl_init_ << 0 << " " // .. variables ..
        << 0 << " " // .. arith ..
        << 0 << " " // .. functions ..
        << 0 << "\n"; // .. flags
     // Discrete variables
     nl_init_ << 0 << " " // binary
        << 0 << " " // integer
        << 0 << " " // nonlinear in both
        << 0 << " " // nonlinear in constraints
        << 0 << "\n"; // nonlinear in objective
     // Nonzeros in the Jacobian, gradients
     nl_init_ << jac_g.nnz() << " " // nnz in Jacobian
        << jac_f.nnz() << "\n"; // nnz in gradients
     // Maximum name length
     nl_init_ << max_x_name << " " // constraints
        << max_g_name << "\n"; // variables
     // Shared subexpressions
     nl_init_ << v.size() << " " // both
        << 0 << " " // constraints
        << 0 << " " // objective
        << 0 << " " // c1 - constaint, but linear?
        << 0 << "\n"; // o1 - objective, but linear?
     // Create a function which evaluates f and g
     Function F("F", {vertcat(v), x}, {vertcat(vdef), f, g},
               {"v", "x"}, {"vdef", "f", "g"});
     // Iterate over the algoritm
     std::vector<std::string> work(F.sz_w());
     // Loop over the algorithm
     for (casadi_int k=0; k<F.n_instructions(); ++k) {
       // Get the atomic operation
       casadi_int op = F.instruction_id(k);
       // Get the operation indices
       std::vector<casadi_int> o = F.instruction_output(k);
       casadi_int o0=-1, o1=-1, i0=-1, i1=-1;
       if (!o.empty()) o0 = o[0];
       if (o.size()>1) o1 = o[1];
       std::vector<casadi_int> i = F.instruction_input(k);
       if (!i.empty()) i0 = i[0];
       if (i.size()>1) i1 = i[1];
       switch (op) {
         case OP_CONST:
         work[o0] = "n" + str(F.instruction_constant(k)) + "\n";
         break;
         case OP_INPUT:
         work[o0] = "v" + str(i0*v.size() + i1) + "\n";
         break;
         case OP_OUTPUT:
         if (o0==0) {
           // Common subexpression
           nl_init_ << "V" << (x.nnz()+o1) << " 0 0\n" << work[i0];
         } else if (o0==1) {
           // Nonlinear objective term
           nl_init_ << "O" << o1 << " 0\n" << work[i0];
         } else {
           // Nonlinear constraint term
           nl_init_ << "C" << o1 << "\n" << work[i0];
         }
         break;
         case OP_ADD: work[o0] = "o0\n" + work[i0] + work[i1]; break;
         case OP_SUB: work[o0] = "o1\n" + work[i0] + work[i1]; break;
         case OP_MUL: work[o0] = "o2\n" + work[i0] + work[i1]; break;
         case OP_DIV: work[o0] = "o3\n" + work[i0] + work[i1]; break;
         case OP_SQ: work[o0] = "o5\n" + work[i0] + "n2\n"; break;
         case OP_POW: work[o0] = "o5\n" + work[i0] + work[i1]; break;
         case OP_FLOOR: work[o0] = "o13\n" + work[i0]; break;
         case OP_CEIL: work[o0] = "o14\n" + work[i0]; break;
         case OP_FABS: work[o0] = "o15\n" + work[i0]; break;
         case OP_NEG: work[o0] = "o16\n" + work[i0]; break;
         case OP_TANH: work[o0] = "o37\n" + work[i0]; break;
         case OP_TAN: work[o0] = "o38\n" + work[i0]; break;
         case OP_SQRT: work[o0] = "o39\n" + work[i0]; break;
         case OP_SINH: work[o0] = "o40\n" + work[i0]; break;
         case OP_SIN: work[o0] = "o41\n" + work[i0]; break;
         case OP_LOG: work[o0] = "o43\n" + work[i0]; break;
         case OP_EXP: work[o0] = "o44\n" + work[i0]; break;
         case OP_COSH: work[o0] = "o45\n" + work[i0]; break;
         case OP_COS: work[o0] = "o46\n" + work[i0]; break;
         case OP_ATANH: work[o0] = "o47\n" + work[i0]; break;
         case OP_ATAN2: work[o0] = "o48\n" + work[i0] + work[i1]; break;
         case OP_ATAN: work[o0] = "o49\n" + work[i0]; break;
         case OP_ASINH: work[o0] = "o50\n" + work[i0]; break;
         case OP_ASIN: work[o0] = "o51\n" + work[i0]; break;
         case OP_ACOSH: work[o0] = "o52\n" + work[i0]; break;
         case OP_ACOS: work[o0] = "o53\n" + work[i0]; break;
         default:
         if (casadi_math<double>::ndeps(op)==1) {
           casadi_error(casadi_math<double>::print(op, "x") + " not supported");
         } else {
           casadi_error(casadi_math<double>::print(op, "x", "y") + " not supported");
         }
       }
     }
     // k segments, cumulative column count in jac_g
     const casadi_int *colind = jac_g.colind(), *row = jac_g.row();
     nl_init_ << "k" << (nx_-1) << "\n";
     for (casadi_int i=1; i<nx_; ++i) nl_init_ << colind[i] << "\n";
     // J segments, rows in jac_g
     Sparsity sp = jac_g.T();
     colind = sp.colind(), row = sp.row();
     for (casadi_int i=0; i<ng_; ++i) {
       nl_init_ << "J" << i << " " << (colind[i+1]-colind[i]) << "\n";
       for (casadi_int k=colind[i]; k<colind[i+1]; ++k) {
         casadi_int r=row[k];
         nl_init_ << r << " " << 0 << "\n"; // no linear term
       }
     }
     // G segments, rows in jac_f
     sp = jac_f.T();
     colind = sp.colind(), row = sp.row();
     nl_init_ << "G" << 0 << " " << (colind[0+1]-colind[0]) << "\n";
     for (casadi_int k=colind[0]; k<colind[0+1]; ++k) {
       casadi_int r=row[k];
       nl_init_ << r << " " << 0 << "\n"; // no linear term
     }
   }
References casadi::Sparsity::colind(), casadi::Nlpsol::init(), casadi::Nlpsol::is_a(), casadi::GenericMatrix< MatType >::is_empty(), casadi::Matrix< Scalar >::jacobian(), casadi::Nlpsol::ng_, casadi::NL_F, casadi::NL_G, nl_init_, casadi::NL_P, casadi::NL_X, casadi::GenericMatrix< MatType >::nnz(), casadi::Sparsity::nnz(), casadi::Nlpsol::nx_, casadi::OP_ACOS, casadi::OP_ACOSH, casadi::OP_ADD, casadi::OP_ASIN, casadi::OP_ASINH, casadi::OP_ATAN, casadi::OP_ATAN2, casadi::OP_ATANH, casadi::OP_CEIL, casadi::OP_CONST, casadi::OP_COS, casadi::OP_COSH, casadi::OP_DIV, casadi::OP_EXP, casadi::OP_FABS, casadi::OP_FLOOR, casadi::OP_INPUT, casadi::OP_LOG, casadi::OP_MUL, casadi::OP_NEG, casadi::OP_OUTPUT, casadi::OP_POW, casadi::OP_SIN, casadi::OP_SINH, casadi::OP_SQ, casadi::OP_SQRT, casadi::OP_SUB, casadi::OP_TAN, casadi::OP_TANH, casadi::OracleFunction::oracle(), casadi::Sparsity::row(), solver_, casadi::str(), casadi::Function::sx_in(), and casadi::Sparsity::T().
init_mem()
int casadi::AmplInterface::init_mem (void * mem) const override virtual
Reimplemented from casadi::Nlpsol.
Definition at line 260 of file ampl_interface.cpp.
{
     if (Nlpsol::init_mem(mem)) return 1;
     //auto m = static_cast<AmplInterfaceMemory*>(mem);
     return 0;
   }
References casadi::Nlpsol::init_mem().
initSingleton()
void casadi::SharedObjectInternal::initSingleton () inline protected inherited
Called in the constructor of singletons to avoid that the counter reaches zero
Definition at line 73 of file shared_object_internal.hpp.
{
       casadi_assert_dev(count==0);
       count++;
     }
instantiate()
Nlpsol * casadi::PluginInterface< Nlpsol >::instantiate (const std::string & fname, const std::string & pname, Problem problem) static inherited
Definition at line 104 of file plugin_interface.hpp.
{
     // Assert the plugin exists (needed for adaptors)
     if (!has_plugin(pname, true)) {
       casadi_error("Plugin '" + pname + "' is not found.");
     }
     return getPlugin(pname).creator(fname, problem);
   }
instruction_constant()
double casadi::FunctionInternal::instruction_constant (casadi_int k) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ld
Reimplemented in casadi::SXFunction.
Definition at line 3179 of file function_internal.cpp.
{
     casadi_error("'instruction_constant' not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
instruction_id()
casadi_int casadi::FunctionInternal::instruction_id (casadi_int k) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lb
Reimplemented in casadi::SXFunction, and casadi::MXFunction.
Definition at line 3171 of file function_internal.cpp.
{
     casadi_error("'instruction_id' not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
instruction_input()
std::vector< casadi_int > casadi::FunctionInternal::instruction_input (casadi_int k) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lc
Reimplemented in casadi::SXFunction, and casadi::MXFunction.
Definition at line 3175 of file function_internal.cpp.
{
     casadi_error("'instruction_input' not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
instruction_MX()
MX casadi::FunctionInternal::instruction_MX (casadi_int k) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lg
Reimplemented in casadi::MXFunction.
Definition at line 3187 of file function_internal.cpp.
{
     casadi_error("'instruction_MX' not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
instruction_output()
std::vector< casadi_int > casadi::FunctionInternal::instruction_output (casadi_int k) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_le
Reimplemented in casadi::SXFunction, and casadi::MXFunction.
Definition at line 3183 of file function_internal.cpp.
{
     casadi_error("'instruction_output' not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
instructions_sx()
SX casadi::FunctionInternal::instructions_sx () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lh
Reimplemented in casadi::SXFunction.
Definition at line 3191 of file function_internal.cpp.
{
     casadi_error("'instructions_sx' not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
integer_support()
virtual bool casadi::Nlpsol::integer_support () const inline virtual inherited
Reimplemented in casadi::KnitroInterface, and casadi::BonminInterface.
Definition at line 201 of file nlpsol_impl.hpp.
 { return false;}
Referenced by casadi::Nlpsol::init().
is_a()
bool casadi::Nlpsol::is_a (const std::string & type, bool recursive) const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1o5
Reimplemented from casadi::FunctionInternal.
Definition at line 287 of file nlpsol.cpp.
{
     return type=="Nlpsol" || (recursive && OracleFunction::is_a(type, recursive));
   }
References casadi::FunctionInternal::is_a().
Referenced by init().
jac_is_symm()
bool casadi::FunctionInternal::jac_is_symm (casadi_int oind, casadi_int iind) const virtual inherited
Definition at line 1752 of file function_internal.cpp.
{
     // If derivative expression
     if (!derivative_of_.is_null()) {
       std::string n = derivative_of_.name();
       // Reverse move
       if (name_ == "adj1_" + n) {
         if (iind == oind) return true;
       }
     }
     // Not symmetric by default
     return false;
   }
References casadi::FunctionInternal::derivative_of_, casadi::SharedObject::is_null(), casadi::Function::name(), and casadi::ProtoFunction::name_.
jac_sparsity()
Sparsity & casadi::FunctionInternal::jac_sparsity (casadi_int oind, casadi_int iind, bool compact, bool symmetric) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kz Get, if necessary generate, the sparsity of a Jacobian block
Definition at line 1840 of file function_internal.cpp.
{
     // If first call, allocate cache
     for (bool c : {false, true}) {
       if (jac_sparsity_[c].empty()) jac_sparsity_[c].resize(n_in_ * n_out_);
     }
     // Flat index
     casadi_int ind = iind + oind * n_in_;
     // Reference to the block
     Sparsity& jsp = jac_sparsity_[compact].at(ind);
     // If null, generate
     if (jsp.is_null()) {
       // Use (non)-compact pattern, if given
       Sparsity& jsp_other = jac_sparsity_[!compact].at(ind);
       if (!jsp_other.is_null()) {
         jsp = compact ? to_compact(oind, iind, jsp_other) : from_compact(oind, iind, jsp_other);
       } else {
         // Generate pattern
         Sparsity sp;
         bool sp_is_compact;
         if (!is_diff_out_.at(oind) || !is_diff_in_.at(iind)) {
           // All-zero sparse
           sp = Sparsity(nnz_out(oind), nnz_in(iind));
           sp_is_compact = true;
         } else {
           // Use internal routine to determine sparsity
           if (has_spfwd() || has_sprev() || has_jac_sparsity(oind, iind)) {
             sp = get_jac_sparsity(oind, iind, symmetric);
           }
           // If null, dense
           if (sp.is_null()) sp = Sparsity::dense(nnz_out(oind), nnz_in(iind));
           // Is the return the compact pattern?
           sp_is_compact = sp.size1() == nnz_out(oind) && sp.size2() == nnz_in(iind);
         }
         // Save to cache and convert if needed
         if (sp_is_compact == compact) {
           jsp = sp;
         } else {
           jsp_other = sp;
           jsp = compact ? to_compact(oind, iind, sp) : from_compact(oind, iind, sp);
         }
       }
     }
     // Return a reference to the block
     return jsp;
   }
References casadi::Sparsity::dense(), casadi::FunctionInternal::from_compact(), casadi::FunctionInternal::get_jac_sparsity(), casadi::FunctionInternal::has_jac_sparsity(), casadi::FunctionInternal::has_spfwd(), casadi::FunctionInternal::has_sprev(), casadi::FunctionInternal::is_diff_in_, casadi::FunctionInternal::is_diff_out_, casadi::SharedObject::is_null(), casadi::FunctionInternal::jac_sparsity_, casadi::FunctionInternal::n_in_, casadi::FunctionInternal::n_out_, casadi::FunctionInternal::nnz_in(), casadi::FunctionInternal::nnz_out(), casadi::Sparsity::size1(), casadi::Sparsity::size2(), and casadi::FunctionInternal::to_compact().
Referenced by casadi::FunctionInternal::get_partition(), casadi::FunctionInternal::sp_forward_block(), and casadi::FunctionInternal::sp_reverse().
jacobian()
Function casadi::FunctionInternal::jacobian () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ky
Definition at line 2169 of file function_internal.cpp.
{
     // Used wrapped function if jacobian not available
     if (!has_jacobian()) {
       // Derivative information must be available
       casadi_assert(has_derivative(),
                             "Derivatives cannot be calculated for " + name_);
       return wrap().jacobian();
     }
     // Retrieve/generate cached
     Function f;
     std::string fname = "jac_" + name_;
     if (!incache(fname, f)) {
       // Names of inputs
       std::vector<std::string> inames;
       for (casadi_int i=0; i<n_in_; ++i) inames.push_back(name_in_[i]);
       for (casadi_int i=0; i<n_out_; ++i) inames.push_back("out_" + name_out_[i]);
       // Names of outputs
       std::vector<std::string> onames;
       onames.reserve(n_in_ * n_out_);
       for (size_t oind = 0; oind < n_out_; ++oind) {
         for (size_t iind = 0; iind < n_in_; ++iind) {
           onames.push_back("jac_" + name_out_[oind] + "_" + name_in_[iind]);
         }
       }
       // Options
       Dict opts = combine(jacobian_options_, der_options_);
       opts["derivative_of"] = self();
       // Generate derivative function
       casadi_assert_dev(enable_jacobian_);
       f = get_jacobian(fname, inames, onames, opts);
       // Consistency checks
       casadi_assert(f.n_in() == inames.size(),
         "Mismatching input signature, expected " + str(inames));
       casadi_assert(f.n_out() == onames.size(),
         "Mismatching output signature, expected " + str(onames));
       // Save to cache
       tocache(f);
     }
     return f;
   }
References casadi::combine(), casadi::FunctionInternal::der_options_, casadi::FunctionInternal::enable_jacobian_, casadi::FunctionInternal::get_jacobian(), casadi::FunctionInternal::has_derivative(), casadi::FunctionInternal::has_jacobian(), casadi::FunctionInternal::incache(), casadi::Function::jacobian(), casadi::FunctionInternal::jacobian_options_, casadi::Function::n_in(), casadi::FunctionInternal::n_in_, casadi::Function::n_out(), casadi::FunctionInternal::n_out_, casadi::ProtoFunction::name_, casadi::FunctionInternal::name_in_, casadi::FunctionInternal::name_out_, casadi::str(), casadi::FunctionInternal::tocache(), and casadi::FunctionInternal::wrap().
Referenced by casadi::FunctionInternal::call_forward(), casadi::FunctionInternal::call_reverse(), and casadi::Function::jacobian().
jit_dependencies()
void casadi::OracleFunction::jit_dependencies (const std::string & fname) override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_k
Reimplemented from casadi::FunctionInternal.
Definition at line 355 of file oracle_function.cpp.
{
   if (compiler_.is_null()) {
     if (verbose_) casadi_message("compiling to "+ fname+"'.");
     // JIT dependent functions
     compiler_ = Importer(generate_dependencies(fname, Dict()),
                         compiler_plugin_, jit_options_);
   }
   // Replace the Oracle functions with generated functions
   for (auto&& e : all_functions_) {
     if (verbose_) casadi_message("loading '" + e.second.f.name() + "' from '" + fname + "'.");
     if (e.second.jit) {
       e.second.f_original = e.second.f;
       e.second.f = external(e.second.f.name(), compiler_);
     }
   }
 }
References casadi::OracleFunction::all_functions_, casadi::FunctionInternal::compiler_, casadi::FunctionInternal::compiler_plugin_, casadi::external(), casadi::OracleFunction::generate_dependencies(), casadi::SharedObject::is_null(), casadi::FunctionInternal::jit_options_, and casadi::ProtoFunction::verbose_.
join_results()
void casadi::OracleFunction::join_results (OracleMemory * m) const inherited
Definition at line 145 of file oracle_function.cpp.
{
   // Combine runtime statistics
   // Note: probably not correct to simply add wall times
   for (int i = 0; i < max_num_threads_; ++i) {
     auto* ml = m->thread_local_mem[i];
     for (auto&& s : ml->fstats) {
       m->fstats.at(s.first).join(s.second);
     }
   }
 }
References casadi::ProtoFunctionMemory::fstats, casadi::OracleFunction::max_num_threads_, and casadi::OracleMemory::thread_local_mem.
Referenced by casadi::Nlpsol::eval().
kkt()
Function casadi::Nlpsol::kkt () const inherited
Definition at line 917 of file nlpsol.cpp.
{
     // Quick return if cached
     if (kkt_.alive()) {
       return shared_cast<Function>(kkt_.shared());
     }
     // Generate KKT function
     Function ret = oracle_.factory("kkt", {"x", "p", "lam:f", "lam:g"},
       {"jac:g:x", "hess:gamma:x:x"}, {{"gamma", {"f", "g"}}});
     // Cache and return
     kkt_ = ret;
     return ret;
   }
References casadi::WeakRef::alive(), casadi::Function::factory(), casadi::Nlpsol::kkt_, casadi::OracleFunction::oracle_, and casadi::WeakRef::shared().
Referenced by casadi::Nlpsol::get_forward(), and casadi::Nlpsol::get_reverse().
load_library()
handle_t casadi::PluginInterface< Nlpsol >::load_library (const std::string & libname, std::string & resultpath, bool global) static inherited
Definition at line 90 of file plugin_interface.hpp.
{
 #ifndef WITH_DL
     casadi_error("WITH_DL option needed for dynamic loading");
 #else // WITH_DL
     // Get the name of the shared library
     std::string lib = SHARED_LIBRARY_PREFIX + libname + SHARED_LIBRARY_SUFFIX;
     // Build up search paths;
     std::vector<std::string> search_paths = get_search_paths();
     return open_shared_library(lib, search_paths, resultpath,
       "PluginInterface::load_plugin", global);
 #endif // WITH_DL
   }
load_plugin()
PluginInterface< Nlpsol >::Plugin casadi::PluginInterface< Nlpsol >::load_plugin (const std::string & pname, bool register_plugin = true) static inherited
Definition at line 87 of file plugin_interface.hpp.
{
     // Issue warning and quick return if already loaded
     if (Derived::solvers_.find(pname) != Derived::solvers_.end()) {
       casadi_warning("PluginInterface: Solver " + pname + " is already in use. Ignored.");
       return Plugin();
     }
 #ifndef WITH_DL
     casadi_error("WITH_DL option needed for dynamic loading");
 #else // WITH_DL
     // Retrieve the registration function
     RegFcn reg;
     // Load the dll
     std::string regName = "casadi_register_" + Derived::infix_ + "_" + pname;
     std::string searchpath;
     handle_t handle = load_library("casadi_" + Derived::infix_ + "_" + pname, searchpath,
       false);
 #ifdef _WIN32
 #if __GNUC__
 #pragma GCC diagnostic push
 #pragma GCC diagnostic ignored "-Wcast-function-type"
 #endif
     reg = reinterpret_cast<RegFcn>(GetProcAddress(handle, TEXT(regName.c_str())));
 #if __GNUC__
 #pragma GCC diagnostic pop
 #endif
 #else // _WIN32
     // Reset error
     dlerror();
     // Load creator
     reg = reinterpret_cast<RegFcn>(dlsym(handle, regName.c_str()));
 #endif // _WIN32
     casadi_assert(reg!=nullptr,
       "PluginInterface::load_plugin: no \"" + regName + "\" found in " + searchpath + ".");
     // Create a temporary struct
     Plugin plugin = pluginFromRegFcn(reg);
     // Register the plugin
     if (register_plugin) {
       registerPlugin(plugin);
     }
     return plugin;
 #endif // WITH_DL
   }
local_free_mem()
void casadi::OracleFunction::local_free_mem (void * mem) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_o
Definition at line 211 of file oracle_function.hpp.
 { delete static_cast<LocalOracleMemory*>(mem);}
Referenced by casadi::OracleFunction::free_mem().
local_init_mem()
int casadi::OracleFunction::local_init_mem (void * mem) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_m
Definition at line 382 of file oracle_function.cpp.
{
   if (ProtoFunction::init_mem(mem)) return 1;
   if (!mem) return 1;
   auto m = static_cast<LocalOracleMemory*>(mem);
   // Create statistics
   for (auto&& e : all_functions_) {
     m->add_stat(e.first);
   }
   return 0;
 }
References casadi::ProtoFunctionMemory::add_stat(), casadi::OracleFunction::all_functions_, and casadi::ProtoFunction::init_mem().
Referenced by casadi::OracleFunction::init_mem().
map()
Function casadi::FunctionInternal::map (casadi_int n, const std::string & parallelization) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_nd
Definition at line 985 of file function_internal.cpp.
{
     Function f;
     if (parallelization=="serial") {
       // Serial maps are cached
       std::string fname = "map" + str(n) + "_" + name_;
       if (!incache(fname, f)) {
         // Create new serial map
         f = Map::create(parallelization, self(), n);
         casadi_assert_dev(f.name()==fname);
         // Save in cache
         tocache(f);
       }
     } else {
       // Non-serial maps are not cached
       f = Map::create(parallelization, self(), n);
     }
     return f;
   }
References casadi::Map::create(), casadi::FunctionInternal::incache(), casadi::Function::name(), casadi::ProtoFunction::name_, casadi::str(), and casadi::FunctionInternal::tocache().
Referenced by casadi::Dple::get_forward(), casadi::Dple::get_reverse(), and casadi::FunctionInternal::mapsum_mx().
mapsum_mx()
std::vector< MX > casadi::FunctionInternal::mapsum_mx (const std::vector< MX > & arg, const std::string & parallelization) inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kw
Definition at line 3200 of file function_internal.cpp.
{
     if (x.empty()) return x;
     // Check number of arguments
     casadi_assert(x.size()==n_in_, "mapsum_mx: Wrong number_i of arguments");
     // Number of parallel calls
     casadi_int npar = 1;
     // Check/replace arguments
     std::vector<MX> x_mod(x.size());
     for (casadi_int i=0; i<n_in_; ++i) {
       if (check_mat(x[i].sparsity(), sparsity_in_[i], npar)) {
         x_mod[i] = replace_mat(x[i], sparsity_in_[i], npar);
       } else {
         // Mismatching sparsity: The following will throw an error message
         npar = 0;
         check_arg(x, npar);
       }
     }
     casadi_int n = 1;
     for (casadi_int i=0; i<x_mod.size(); ++i) {
       n = std::max(x_mod[i].size2() / size2_in(i), n);
     }
     std::vector<casadi_int> reduce_in;
     for (casadi_int i=0; i<x_mod.size(); ++i) {
       if (x_mod[i].size2()/size2_in(i)!=n) {
         reduce_in.push_back(i);
       }
     }
     Function ms = self().map("mapsum", parallelization, n, reduce_in, range(n_out_));
     // Call the internal function
     return ms(x_mod);
   }
References casadi::FunctionInternal::check_arg(), casadi::FunctionInternal::check_mat(), casadi::FunctionInternal::map(), casadi::FunctionInternal::n_in_, casadi::FunctionInternal::n_out_, casadi::range(), casadi::replace_mat(), casadi::FunctionInternal::size2_in(), and casadi::FunctionInternal::sparsity_in_.
matching_arg()
template<typename M > bool casadi::FunctionInternal::matching_arg (const std::vector< M > & arg, casadi_int & npar) const inherited
Raises errors
Parameters
npar[in] normal usage: 1, disallow pararallel calls: -1
[out] npar max number of horizontal repetitions across all arguments (or -1)
Extra doc: https://github.com/casadi/casadi/wiki/L_kk
Definition at line 1652 of file function_internal.hpp.
{
     check_arg(arg, npar);
     for (casadi_int i=0; i<n_in_; ++i) {
       if (arg.at(i).size1()!=size1_in(i)) return false;
       if (arg.at(i).size2()!=size2_in(i) && arg.at(i).size2()!=npar*size2_in(i)) return false;
     }
     return true;
   }
References casadi::FunctionInternal::check_arg(), casadi::FunctionInternal::n_in_, casadi::FunctionInternal::size1_in(), and casadi::FunctionInternal::size2_in().
Referenced by casadi::MXFunction::ad_forward(), casadi::FunctionInternal::call(), casadi::FunctionInternal::call_forward(), and casadi::FunctionInternal::nz_in().
matching_res()
template<typename M > bool casadi::FunctionInternal::matching_res (const std::vector< M > & arg, casadi_int & npar) const inherited
Raises errors
Parameters
npar[in] normal usage: 1, disallow pararallel calls: -1
[out] npar max number of horizontal repetitions across all arguments (or -1)
Extra doc: https://github.com/casadi/casadi/wiki/L_kl
Definition at line 1662 of file function_internal.hpp.
{
     check_res(res, npar);
     for (casadi_int i=0; i<n_out_; ++i) {
       if (res.at(i).size1()!=size1_out(i)) return false;
       if (res.at(i).size2()!=size2_out(i) && res.at(i).size2()!=npar*size2_out(i)) return false;
     }
     return true;
   }
References casadi::FunctionInternal::check_res(), casadi::FunctionInternal::n_out_, casadi::FunctionInternal::size1_out(), and casadi::FunctionInternal::size2_out().
Referenced by casadi::MXFunction::ad_reverse(), casadi::FunctionInternal::call_reverse(), and casadi::FunctionInternal::nz_out().
memory()
void * casadi::ProtoFunction::memory (int ind) const inherited
Definition at line 3433 of file function_internal.cpp.
{
 #ifdef CASADI_WITH_THREAD
     std::lock_guard<std::mutex> lock(mtx_);
 #endif //CASADI_WITH_THREAD
     return mem_.at(ind);
   }
Referenced by casadi::FunctionInternal::call_gen(), casadi::FunctionInternal::get_jac_sparsity_gen(), casadi::FunctionInternal::get_jac_sparsity_hierarchical(), casadi::Sqpmethod::solve_ela_QP(), and casadi::Sqpmethod::solve_QP().
monitored()
bool casadi::OracleFunction::monitored (const std::string & name) const virtual inherited
Definition at line 464 of file oracle_function.cpp.
{
   auto it = all_functions_.find(name);
   casadi_assert(it!=all_functions_.end(),
     "No function \"" + name + "\" in " + name_+ ". " +
     "Available functions: " + join(get_function()) + ".");
   return it->second.monitored;
 }
References casadi::OracleFunction::all_functions_, casadi::OracleFunction::get_function(), casadi::join(), and casadi::ProtoFunction::name_.
Referenced by casadi::OracleFunction::calc_function().
mx_in() [1/2]
const std::vector< MX > casadi::FunctionInternal::mx_in () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_l7
Reimplemented in casadi::MXFunction.
Definition at line 3134 of file function_internal.cpp.
{
     std::vector<MX> ret(n_in_);
     for (casadi_int i=0; i<ret.size(); ++i) {
       ret[i] = mx_in(i);
     }
     return ret;
   }
References casadi::FunctionInternal::n_in_.
Referenced by casadi::Nlpsol::get_forward(), casadi::LinearInterpolantJac::get_jacobian(), casadi::Nlpsol::get_reverse(), casadi::FunctionInternal::wrap(), and casadi::FunctionInternal::wrap_as_needed().
mx_in() [2/2]
const MX casadi::FunctionInternal::mx_in (casadi_int ind) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_l7
Reimplemented in casadi::MXFunction.
Definition at line 3126 of file function_internal.cpp.
{
     return MX::sym(name_in_.at(ind), sparsity_in(ind));
   }
References casadi::FunctionInternal::name_in_, casadi::FunctionInternal::sparsity_in(), and casadi::GenericMatrix< MX >::sym().
mx_out() [1/2]
const std::vector< MX > casadi::FunctionInternal::mx_out () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_l7
Definition at line 3142 of file function_internal.cpp.
{
     std::vector<MX> ret(n_out_);
     for (casadi_int i=0; i<ret.size(); ++i) {
       ret[i] = mx_out(i);
     }
     return ret;
   }
References casadi::FunctionInternal::n_out_.
Referenced by casadi::Nlpsol::get_forward(), and casadi::Nlpsol::get_reverse().
mx_out() [2/2]
const MX casadi::FunctionInternal::mx_out (casadi_int ind) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_l7
Definition at line 3130 of file function_internal.cpp.
{
     return MX::sym(name_out_.at(ind), sparsity_out(ind));
   }
References casadi::FunctionInternal::name_out_, casadi::FunctionInternal::sparsity_out(), and casadi::GenericMatrix< MX >::sym().
n_instructions()
casadi_int casadi::FunctionInternal::n_instructions () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_la
Reimplemented in casadi::SXFunction, and casadi::MXFunction.
Definition at line 3167 of file function_internal.cpp.
{
     casadi_error("'n_instructions' not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
n_nodes()
casadi_int casadi::FunctionInternal::n_nodes () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lf
Reimplemented in casadi::SXFunction, and casadi::MXFunction.
Definition at line 3195 of file function_internal.cpp.
{
     casadi_error("'n_nodes' not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
nlpsol_codegen_body()
void casadi::Nlpsol::nlpsol_codegen_body (CodeGenerator & g) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1o0
Definition at line 1235 of file nlpsol.cpp.
{
     g.local("d_nlp", "struct casadi_nlpsol_data");
     g.local("p_nlp", "struct casadi_nlpsol_prob");
     g << "d_nlp.prob = &p_nlp;\n";
     g << "p_nlp.nx = " << nx_ << ";\n";
     g << "p_nlp.ng = " << ng_ << ";\n";
     g << "p_nlp.np = " << np_ << ";\n";
     g << "p_nlp.detect_bounds.ng = " << detect_simple_bounds_is_simple_.size() << ";\n";
     if (detect_simple_bounds_is_simple_.size()) {
       g << "p_nlp.detect_bounds.nb = " << detect_simple_bounds_target_x_.size() << ";\n";
       g << "p_nlp.target_x.nb = " << g.constant(detect_simple_bounds_target_x_) << ";\n";
       g << "p_nlp.target_g.nb = " << g.constant(detect_simple_bounds_target_g_) << ";\n";
     }
     g << "casadi_nlpsol_init(&d_nlp, &arg, &res, &iw, &w);\n";
     g << "d_nlp.p = arg[" << NLPSOL_P << "];\n";
     g << "d_nlp.lbx = arg[" << NLPSOL_LBX << "];\n";
     g << "d_nlp.ubx = arg[" << NLPSOL_UBX << "];\n";
     g << "d_nlp.lbg = arg[" << NLPSOL_LBG << "];\n";
     g << "d_nlp.ubg = arg[" << NLPSOL_UBG << "];\n";
     g << "d_nlp.x0 = arg[" << NLPSOL_X0 << "];\n";
     g << "d_nlp.lam_x0 = arg[" << NLPSOL_LAM_X0 << "];\n";
     g << "d_nlp.lam_g0 = arg[" << NLPSOL_LAM_G0 << "];\n";
     g << "d_nlp.x = res[" << NLPSOL_X << "];\n";
     g << "d_nlp.f = res[" << NLPSOL_F << "];\n";
     g << "d_nlp.g = res[" << NLPSOL_G << "];\n";
     g << "d_nlp.lam_x = res[" << NLPSOL_LAM_X << "];\n";
     g << "d_nlp.lam_g = res[" << NLPSOL_LAM_G << "];\n";
     g << "d_nlp.lam_p = res[" << NLPSOL_LAM_P << "];\n";
   }
References casadi::CodeGenerator::constant(), casadi::Nlpsol::detect_simple_bounds_is_simple_, casadi::Nlpsol::detect_simple_bounds_target_g_, casadi::Nlpsol::detect_simple_bounds_target_x_, casadi::CodeGenerator::local(), casadi::Nlpsol::ng_, casadi::NLPSOL_F, casadi::NLPSOL_G, casadi::NLPSOL_LAM_G, casadi::NLPSOL_LAM_G0, casadi::NLPSOL_LAM_P, casadi::NLPSOL_LAM_X, casadi::NLPSOL_LAM_X0, casadi::NLPSOL_LBG, casadi::NLPSOL_LBX, casadi::NLPSOL_P, casadi::NLPSOL_UBG, casadi::NLPSOL_UBX, casadi::NLPSOL_X, casadi::NLPSOL_X0, casadi::Nlpsol::np_, and casadi::Nlpsol::nx_.
Referenced by casadi::Feasiblesqpmethod::codegen_body(), and casadi::Sqpmethod::codegen_body().
nnz_in() [1/2]
casadi_int casadi::FunctionInternal::nnz_in () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_me
Definition at line 2129 of file function_internal.cpp.
{
     casadi_int ret=0;
     for (casadi_int iind=0; iind<n_in_; ++iind) ret += nnz_in(iind);
     return ret;
   }
References casadi::FunctionInternal::n_in_.
Referenced by casadi::FunctionInternal::adjViaJac(), casadi::FunctionInternal::call_gen(), casadi::JitFunction::codegen_body(), casadi::FunctionInternal::codegen_meta(), casadi::CallbackInternal::finalize(), casadi::FunctionInternal::from_compact(), casadi::FunctionInternal::fwdViaJac(), casadi::FunctionInternal::generate_in(), casadi::FunctionInternal::get_jac_sparsity(), casadi::Expm::get_jac_sparsity(), casadi::FunctionInternal::get_jac_sparsity_gen(), casadi::FunctionInternal::get_jac_sparsity_hierarchical(), casadi::FunctionInternal::get_jac_sparsity_hierarchical_symm(), casadi::JitFunction::init(), casadi::Nlpsol::init(), casadi::CbcInterface::init(), casadi::ClpInterface::init(), casadi::CplexInterface::init(), casadi::OoqpInterface::init(), casadi::ProxqpInterface::init(), casadi::QpoasesInterface::init(), casadi::ImplicitToNlp::init(), casadi::FunctionInternal::jac_sparsity(), casadi::FunctionInternal::nz_in(), casadi::ImplicitToNlp::set_work(), casadi::CbcInterface::solve(), casadi::ClpInterface::solve(), casadi::CplexInterface::solve(), casadi::OoqpInterface::solve(), casadi::ProxqpInterface::solve(), casadi::QpToNlp::solve(), casadi::KinsolInterface::solve(), casadi::FunctionInternal::sp_forward(), and casadi::FunctionInternal::sp_reverse().
nnz_in() [2/2]
casadi_int casadi::FunctionInternal::nnz_in (casadi_int ind) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_me
Definition at line 921 of file function_internal.hpp.
 { return sparsity_in(ind).nnz(); }
nnz_out() [1/2]
casadi_int casadi::FunctionInternal::nnz_out () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_me
Definition at line 2135 of file function_internal.cpp.
{
     casadi_int ret=0;
     for (casadi_int oind=0; oind<n_out_; ++oind) ret += nnz_out(oind);
     return ret;
   }
References casadi::FunctionInternal::n_out_.
Referenced by casadi::FunctionInternal::adjViaJac(), casadi::FunctionInternal::call_gen(), casadi::Nlpsol::check_inputs(), casadi::JitFunction::codegen_body(), casadi::FunctionInternal::codegen_meta(), casadi::FunctionInternal::eval_gen(), casadi::Switch::eval_sx(), casadi::CallbackInternal::finalize(), casadi::FunctionInternal::from_compact(), casadi::FunctionInternal::fwdViaJac(), casadi::FunctionInternal::generate_out(), casadi::FunctionInternal::get_jac_sparsity(), casadi::Expm::get_jac_sparsity(), casadi::FunctionInternal::get_jac_sparsity_gen(), casadi::FunctionInternal::get_jac_sparsity_hierarchical(), casadi::FunctionInternal::get_jac_sparsity_hierarchical_symm(), casadi::JitFunction::init(), casadi::Nlpsol::init(), casadi::FunctionInternal::jac_sparsity(), casadi::FunctionInternal::nz_out(), casadi::KinsolInterface::solve(), casadi::FunctionInternal::sp_forward(), and casadi::FunctionInternal::sp_reverse().
nnz_out() [2/2]
casadi_int casadi::FunctionInternal::nnz_out (casadi_int ind) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_me
Definition at line 923 of file function_internal.hpp.
 { return sparsity_out(ind).nnz(); }
numel_in() [1/2]
casadi_int casadi::FunctionInternal::numel_in () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mf
Definition at line 2141 of file function_internal.cpp.
{
     casadi_int ret=0;
     for (casadi_int iind=0; iind<n_in_; ++iind) ret += numel_in(iind);
     return ret;
   }
References casadi::FunctionInternal::n_in_.
Referenced by casadi::FunctionInternal::from_compact(), and casadi::Integrator::get_reverse().
numel_in() [2/2]
casadi_int casadi::FunctionInternal::numel_in (casadi_int ind) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mf
Definition at line 931 of file function_internal.hpp.
 { return sparsity_in(ind).numel(); }
numel_out() [1/2]
casadi_int casadi::FunctionInternal::numel_out () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mf
Definition at line 2147 of file function_internal.cpp.
{
     casadi_int ret=0;
     for (casadi_int oind=0; oind<n_out_; ++oind) ret += numel_out(oind);
     return ret;
   }
References casadi::FunctionInternal::n_out_.
Referenced by casadi::FunctionInternal::from_compact(), and casadi::Integrator::get_reverse().
numel_out() [2/2]
casadi_int casadi::FunctionInternal::numel_out (casadi_int ind) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mf
Definition at line 932 of file function_internal.hpp.
 { return sparsity_out(ind).numel(); }
nz_in() [1/2]
std::vector< double > casadi::FunctionInternal::nz_in (const std::vector< DM > & arg) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kt
Definition at line 3290 of file function_internal.cpp.
{
     // Disallow parallel inputs
     casadi_int npar = -1;
     if (!matching_arg(arg, npar)) {
       return nz_in(replace_arg(arg, npar));
     }
     std::vector<DM> arg2 = project_arg(arg, 1);
     std::vector<double> ret(nnz_in());
     casadi_int offset = 0;
     for (casadi_int i=0;i<n_in_;++i) {
       const double* e = arg2.at(i).ptr();
       std::copy(e, e+nnz_in(i), ret.begin()+offset);
       offset+= nnz_in(i);
     }
     return ret;
   }
References casadi::FunctionInternal::matching_arg(), casadi::FunctionInternal::n_in_, casadi::FunctionInternal::nnz_in(), casadi::FunctionInternal::project_arg(), and casadi::FunctionInternal::replace_arg().
Referenced by casadi::FunctionInternal::get_jac_sparsity(), casadi::FunctionInternal::get_jac_sparsity_gen(), and casadi::FunctionInternal::get_jac_sparsity_hierarchical().
nz_in() [2/2]
std::vector< DM > casadi::FunctionInternal::nz_in (const std::vector< double > & arg) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kt
Definition at line 3260 of file function_internal.cpp.
{
     casadi_assert(nnz_in()==arg.size(),
       "Dimension mismatch. Expecting " + str(nnz_in()) +
       ", got " + str(arg.size()) + " instead.");
     std::vector<DM> ret = dm_in();
     casadi_int offset = 0;
     for (casadi_int i=0;i<n_in_;++i) {
       DM& r = ret.at(i);
       std::copy(arg.begin()+offset, arg.begin()+offset+nnz_in(i), r.ptr());
       offset+= nnz_in(i);
     }
     return ret;
   }
References casadi::FunctionInternal::dm_in(), casadi::FunctionInternal::n_in_, casadi::FunctionInternal::nnz_in(), casadi::Matrix< Scalar >::ptr(), and casadi::str().
nz_out() [1/2]
std::vector< double > casadi::FunctionInternal::nz_out (const std::vector< DM > & res) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kt
Definition at line 3308 of file function_internal.cpp.
{
     // Disallow parallel inputs
     casadi_int npar = -1;
     if (!matching_res(res, npar)) {
       return nz_out(replace_res(res, npar));
     }
     std::vector<DM> res2 = project_res(res, 1);
     std::vector<double> ret(nnz_out());
     casadi_int offset = 0;
     for (casadi_int i=0;i<n_out_;++i) {
       const double* e = res2.at(i).ptr();
       std::copy(e, e+nnz_out(i), ret.begin()+offset);
       offset+= nnz_out(i);
     }
     return ret;
   }
References casadi::FunctionInternal::matching_res(), casadi::FunctionInternal::n_out_, casadi::FunctionInternal::nnz_out(), casadi::FunctionInternal::project_res(), and casadi::FunctionInternal::replace_res().
Referenced by casadi::FunctionInternal::get_jac_sparsity(), casadi::FunctionInternal::get_jac_sparsity_gen(), and casadi::FunctionInternal::get_jac_sparsity_hierarchical().
nz_out() [2/2]
std::vector< DM > casadi::FunctionInternal::nz_out (const std::vector< double > & res) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kt
Definition at line 3275 of file function_internal.cpp.
{
     casadi_assert(nnz_out()==res.size(),
       "Dimension mismatch. Expecting " + str(nnz_out()) +
       ", got " + str(res.size()) + " instead.");
     std::vector<DM> ret = dm_out();
     casadi_int offset = 0;
     for (casadi_int i=0;i<n_out_;++i) {
       DM& r = ret.at(i);
       std::copy(res.begin()+offset, res.begin()+offset+nnz_out(i), r.ptr());
       offset+= nnz_out(i);
     }
     return ret;
   }
References casadi::FunctionInternal::dm_out(), casadi::FunctionInternal::n_out_, casadi::FunctionInternal::nnz_out(), casadi::Matrix< Scalar >::ptr(), and casadi::str().
oracle()
const Function& casadi::OracleFunction::oracle () const inline override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_h
Reimplemented from casadi::FunctionInternal.
Definition at line 127 of file oracle_function.hpp.
 { return oracle_;}
Referenced by casadi::OracleFunction::create_function(), init(), and casadi::Scpgen::init().
plugin_deserialize()
Deserialize casadi::PluginInterface< Nlpsol >::plugin_deserialize (const std::string & pname) static inherited
Definition at line 81 of file plugin_interface.hpp.
{
     Deserialize m = getPlugin(pname).deserialize;
     casadi_assert(m, "Plugin \"" + pname + "\" does not support deserialize");
     return m;
   }
plugin_name()
const char* casadi::AmplInterface::plugin_name () const inline override virtual
Implements casadi::PluginInterface< Nlpsol >.
Definition at line 62 of file ampl_interface.hpp.
 { return "ampl";}
plugin_options()
const Options & casadi::PluginInterface< Nlpsol >::plugin_options (const std::string & pname) static inherited
Definition at line 78 of file plugin_interface.hpp.
{
     const Options *op = getPlugin(pname).options;
     casadi_assert(op!=nullptr, "Plugin \"" + pname + "\" does not support options");
     return *op;
   }
pluginFromRegFcn()
PluginInterface< Nlpsol >::Plugin casadi::PluginInterface< Nlpsol >::pluginFromRegFcn (RegFcn regfcn) static inherited
Definition at line 84 of file plugin_interface.hpp.
{
     // Create a temporary struct
     Plugin plugin;
     // Set the fields
     int flag = regfcn(&plugin);
     casadi_assert(flag==0, "Registration of plugin failed.");
     return plugin;
   }
print()
void casadi::ProtoFunction::print (const char * fmt, ...) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_jr
Definition at line 3662 of file function_internal.cpp.
{
     // Variable number of arguments
     va_list args;
     va_start(args, fmt);
     // Static & dynamic buffers
     char buf[256];
     size_t buf_sz = sizeof(buf);
     char* buf_dyn = nullptr;
     // Try to print with a small buffer
     casadi_int n = vsnprintf(buf, buf_sz, fmt, args);
     // Need a larger buffer?
     if (n>static_cast<casadi_int>(buf_sz)) {
       buf_sz = static_cast<size_t>(n+1);
       buf_dyn = new char[buf_sz];
       n = vsnprintf(buf_dyn, buf_sz, fmt, args);
     }
     // Print buffer content
     if (n>=0) uout() << (buf_dyn ? buf_dyn : buf) << std::flush;
     // Cleanup
     delete[] buf_dyn;
     va_end(args);
     // Throw error if failure
     casadi_assert(n>=0, "Print failure while processing '" + std::string(fmt) + "'");
   }
References casadi::uout().
Referenced by casadi::Feasiblesqpmethod::anderson_acc_step_update(), casadi::Nlpsol::callback(), casadi::Blocksqp::convertHessian(), casadi::Feasiblesqpmethod::feasibility_iterations(), casadi::Blocksqp::feasibilityRestorationPhase(), casadi::Blocksqp::fullstep(), casadi::Blocksqp::init(), casadi::Feasiblesqpmethod::init(), casadi::Ipqp::init(), casadi::Qrqp::init(), casadi::Qrsqp::init(), casadi::Sqpmethod::init(), casadi::LinsolQr::nfact(), casadi::Feasiblesqpmethod::print_iteration(), casadi::Qrsqp::print_iteration(), casadi::Sqpmethod::print_iteration(), casadi::SundialsInterface::print_stats(), casadi::ProtoFunction::print_time(), casadi::Blocksqp::printInfo(), casadi::Blocksqp::printProgress(), casadi::Blocksqp::run(), casadi::Blocksqp::solve(), casadi::Feasiblesqpmethod::solve(), casadi::Qrsqp::solve(), casadi::Sqpmethod::solve(), casadi::Sqpmethod::solve_ela_QP(), casadi::Feasiblesqpmethod::solve_LP(), casadi::Feasiblesqpmethod::solve_QP(), casadi::Qrsqp::solve_QP(), casadi::Sqpmethod::solve_QP(), and casadi::Blocksqp::solveQP().
print_dimensions()
void casadi::FunctionInternal::print_dimensions (std::ostream & stream) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mb
Definition at line 879 of file function_internal.cpp.
{
     stream << " Number of inputs: " << n_in_ << std::endl;
     for (casadi_int i=0; i<n_in_; ++i) {
       stream << "  Input " << i  << " (\"" << name_in_[i] << "\"): "
              << sparsity_in_[i].dim() << std::endl;
     }
     stream << " Number of outputs: " << n_out_ << std::endl;
     for (casadi_int i=0; i<n_out_; ++i) {
       stream << "  Output " << i  << " (\"" << name_out_[i] << "\"): "
              << sparsity_out_[i].dim() << std::endl;
     }
   }
References casadi::FunctionInternal::n_in_, casadi::FunctionInternal::n_out_, casadi::FunctionInternal::name_in_, casadi::FunctionInternal::name_out_, casadi::FunctionInternal::sparsity_in_, and casadi::FunctionInternal::sparsity_out_.
print_in()
void casadi::FunctionInternal::print_in (std::ostream & stream, const double ** arg, bool truncate) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_nv
Definition at line 798 of file function_internal.cpp.
{
     stream << "Function " << name_ << " (" << this << ")" << std::endl;
     for (casadi_int i=0; i<n_in_; ++i) {
       stream << "Input " << i << " (" << name_in_[i] << "): ";
       if (arg[i]) {
         DM::print_default(stream, sparsity_in_[i], arg[i], truncate);
         stream << std::endl;
       } else {
         stream << "NULL" << std::endl;
       }
     }
   }
References casadi::FunctionInternal::n_in_, casadi::ProtoFunction::name_, casadi::FunctionInternal::name_in_, casadi::Matrix< double >::print_default(), and casadi::FunctionInternal::sparsity_in_.
Referenced by casadi::FunctionInternal::eval_gen().
print_option()
void casadi::ProtoFunction::print_option (const std::string & name, std::ostream & stream) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ji
Definition at line 896 of file function_internal.cpp.
{
     get_options().print_one(name, stream);
   }
References casadi::ProtoFunction::get_options(), and casadi::Options::print_one().
print_options()
void casadi::ProtoFunction::print_options (std::ostream & stream) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_jh
Definition at line 892 of file function_internal.cpp.
{
     get_options().print_all(stream);
   }
References casadi::ProtoFunction::get_options(), and casadi::Options::print_all().
print_out()
void casadi::FunctionInternal::print_out (std::ostream & stream, double ** res, bool truncate) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_nw
Definition at line 811 of file function_internal.cpp.
{
     stream << "Function " << name_ << " (" << this << ")" << std::endl;
     for (casadi_int i=0; i<n_out_; ++i) {
       stream << "Output " << i << " (" << name_out_[i] << "): ";
       if (res[i]) {
         DM::print_default(stream, sparsity_out_[i], res[i], truncate);
         stream << std::endl;
       } else {
         stream << "NULL" << std::endl;
       }
     }
   }
References casadi::FunctionInternal::n_out_, casadi::ProtoFunction::name_, casadi::FunctionInternal::name_out_, casadi::Matrix< double >::print_default(), and casadi::FunctionInternal::sparsity_out_.
Referenced by casadi::FunctionInternal::eval_gen().
print_time()
void casadi::ProtoFunction::print_time (const std::map< std::string, FStats > & fstats) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ju
Definition at line 3582 of file function_internal.cpp.
{
     if (!print_time_) return;
     // Length of the name being printed
     size_t name_len=0;
     for (auto &&s : fstats) {
       name_len = std::max(s.first.size(), name_len);
     }
     name_len = std::max(name_.size(), name_len);
     // Print name with a given length. Format: "%NNs "
     char namefmt[10];
     sprint(namefmt, sizeof(namefmt), "%%%ds ", static_cast<casadi_int>(name_len));
     // Print header
     print(namefmt, name_.c_str());
     print(" : %8s %10s %8s %10s %9s\n", "t_proc", "(avg)", "t_wall", "(avg)", "n_eval");
     char buffer_proc[10];
     char buffer_wall[10];
     char buffer_proc_avg[10];
     char buffer_wall_avg[10];
     // Print keys
     for (const auto &s : fstats) {
       if (s.second.n_call!=0) {
         print(namefmt, s.first.c_str());
         format_time(buffer_proc, s.second.t_proc);
         format_time(buffer_wall, s.second.t_wall);
         format_time(buffer_proc_avg, s.second.t_proc/s.second.n_call);
         format_time(buffer_wall_avg, s.second.t_wall/s.second.n_call);
         print(" | %s (%s) %s (%s) %9d\n",
           buffer_proc, buffer_proc_avg,
           buffer_wall, buffer_wall_avg, s.second.n_call);
       }
     }
   }
References casadi::ProtoFunction::format_time(), casadi::ProtoFunction::name_, casadi::ProtoFunction::print(), casadi::ProtoFunction::print_time_, and casadi::ProtoFunction::sprint().
Referenced by casadi::FunctionInternal::eval_gen().
project_arg()
template<typename M > std::vector< M > casadi::FunctionInternal::project_arg (const std::vector< M > & arg, casadi_int npar) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kn
Definition at line 1524 of file function_internal.hpp.
{
     casadi_assert_dev(arg.size()==n_in_);
     // Which arguments require mapped evaluation
     std::vector<bool> mapped(n_in_);
     for (casadi_int i=0; i<n_in_; ++i) {
       mapped[i] = arg[i].size2()!=size2_in(i);
     }
     // Check if matching input sparsity
     std::vector<bool> matching(n_in_);
     bool any_mismatch = false;
     for (casadi_int i=0; i<n_in_; ++i) {
       if (mapped[i]) {
         matching[i] = arg[i].sparsity().is_stacked(sparsity_in(i), npar);
       } else {
         matching[i] = arg[i].sparsity()==sparsity_in(i);
       }
       any_mismatch = any_mismatch || !matching[i];
     }
     // Correct input sparsity
     if (any_mismatch) {
       std::vector<M> arg2(arg);
       for (casadi_int i=0; i<n_in_; ++i) {
         if (!matching[i]) {
           if (mapped[i]) {
             arg2[i] = project(arg2[i], repmat(sparsity_in(i), 1, npar));
           } else {
             arg2[i] = project(arg2[i], sparsity_in(i));
           }
         }
       }
       return arg2;
     }
     return arg;
   }
References casadi::FunctionInternal::n_in_, casadi::FunctionInternal::size2_in(), and casadi::FunctionInternal::sparsity_in().
Referenced by casadi::FunctionInternal::call_gen(), and casadi::FunctionInternal::nz_in().
project_res()
template<typename M > std::vector< M > casadi::FunctionInternal::project_res (const std::vector< M > & arg, casadi_int npar) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ko
Definition at line 1564 of file function_internal.hpp.
{
       return arg;
   }
Referenced by casadi::FunctionInternal::nz_out().
purgable()
template<typename MatType > bool casadi::FunctionInternal::purgable (const std::vector< MatType > & seed) static inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_nq
Definition at line 1417 of file function_internal.hpp.
{
     for (auto i=v.begin(); i!=v.end(); ++i) {
       if (!i->is_zero()) return false;
     }
     return true;
   }
Referenced by casadi::MXFunction::ad_forward(), and casadi::MXFunction::ad_reverse().
registerPlugin() [1/2]
void casadi::PluginInterface< Nlpsol >::registerPlugin (const Plugin & plugin) static inherited
Definition at line 94 of file plugin_interface.hpp.
{
     // Check if the solver name is in use
     typename std::map<std::string, Plugin>::iterator it=Derived::solvers_.find(plugin.name);
     casadi_assert(it==Derived::solvers_.end(),
       "Solver " + str(plugin.name) + " is already in use");
     // Add to list of solvers
     Derived::solvers_[plugin.name] = plugin;
   }
registerPlugin() [2/2]
void casadi::PluginInterface< Nlpsol >::registerPlugin (RegFcn regfcn) static inherited
Definition at line 97 of file plugin_interface.hpp.
{
     registerPlugin(pluginFromRegFcn(regfcn));
   }
release()
void casadi::ProtoFunction::release (int mem) const inherited
Definition at line 3460 of file function_internal.cpp.
{
 #ifdef CASADI_WITH_THREAD
     std::lock_guard<std::mutex> lock(mtx_);
 #endif //CASADI_WITH_THREAD
     unused_.push(mem);
   }
replace_arg()
template<typename M > std::vector< M > casadi::FunctionInternal::replace_arg (const std::vector< M > & arg, casadi_int npar) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_km
Definition at line 1697 of file function_internal.hpp.
{
     std::vector<M> r(arg.size());
     for (casadi_int i=0; i<r.size(); ++i) r[i] = replace_mat(arg[i], sparsity_in(i), npar);
     return r;
   }
References casadi::replace_mat(), and casadi::FunctionInternal::sparsity_in().
Referenced by casadi::FunctionInternal::call(), casadi::FunctionInternal::nz_in(), and casadi::FunctionInternal::replace_fseed().
replace_aseed() [1/2]
template<typename M > std::vector<std::vector<M> > casadi::FunctionInternal::replace_aseed (const std::vector< std::vector< M > > & aseed, casadi_int npar) const inherited
Definition at line 1721 of file function_internal.hpp.
{
     std::vector<std::vector<M> > r(aseed.size());
     for (casadi_int d=0; d<r.size(); ++d) r[d] = replace_res(aseed[d], npar);
     return r;
   }
References casadi::FunctionInternal::replace_res().
replace_aseed() [2/2]
template<typename M > std::vector<std::vector<M> > casadi::FunctionInternal::replace_aseed (const std::vector< std::vector< M >> & aseed, casadi_int npar) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kr
Referenced by casadi::MXFunction::ad_reverse(), and casadi::FunctionInternal::call_reverse().
replace_fseed() [1/2]
template<typename M > std::vector<std::vector<M> > casadi::FunctionInternal::replace_fseed (const std::vector< std::vector< M > > & fseed, casadi_int npar) const inherited
Definition at line 1713 of file function_internal.hpp.
{
     std::vector<std::vector<M> > r(fseed.size());
     for (casadi_int d=0; d<r.size(); ++d) r[d] = replace_arg(fseed[d], npar);
     return r;
   }
References casadi::FunctionInternal::replace_arg().
replace_fseed() [2/2]
template<typename M > std::vector<std::vector<M> > casadi::FunctionInternal::replace_fseed (const std::vector< std::vector< M >> & fseed, casadi_int npar) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kq
Referenced by casadi::MXFunction::ad_forward(), and casadi::FunctionInternal::call_forward().
replace_res()
template<typename M > std::vector< M > casadi::FunctionInternal::replace_res (const std::vector< M > & res, casadi_int npar) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kp
Definition at line 1705 of file function_internal.hpp.
{
     std::vector<M> r(res.size());
     for (casadi_int i=0; i<r.size(); ++i) r[i] = replace_mat(res[i], sparsity_out(i), npar);
     return r;
   }
References casadi::replace_mat(), and casadi::FunctionInternal::sparsity_out().
Referenced by casadi::FunctionInternal::nz_out(), and casadi::FunctionInternal::replace_aseed().
reverse()
Function casadi::FunctionInternal::reverse (casadi_int nadj) const inherited
reverse(nadj) returns a cached instance if available, and calls Function get_reverse(casadi_int nadj) if no cached version is available.
Extra doc: https://github.com/casadi/casadi/wiki/L_l1
Definition at line 2054 of file function_internal.cpp.
{
     casadi_assert_dev(nadj>=0);
     // Used wrapped function if reverse not available
     if (!enable_reverse_) {
       // Derivative information must be available
       casadi_assert(has_derivative(), "Derivatives cannot be calculated for " + name_);
       return wrap().reverse(nadj);
     }
     // Retrieve/generate cached
     Function f;
     std::string fname = reverse_name(name_, nadj);
     if (!incache(fname, f)) {
       casadi_int i;
       // Names of inputs
       std::vector<std::string> inames;
       for (i=0; i<n_in_; ++i) inames.push_back("in_" + name_in_[i]);
       for (i=0; i<n_out_; ++i) inames.push_back("out_" + name_out_[i]);
       for (i=0; i<n_out_; ++i) inames.push_back("adj_" + name_out_[i]);
       // Names of outputs
       std::vector<std::string> onames;
       for (casadi_int i=0; i<n_in_; ++i) onames.push_back("adj_" + name_in_[i]);
       // Options
       Dict opts = combine(reverse_options_, der_options_);
       opts = combine(opts, generate_options("reverse"));
       opts["derivative_of"] = self();
       // Generate derivative function
       casadi_assert_dev(enable_reverse_);
       f = get_reverse(nadj, fname, inames, onames, opts);
       // Consistency check for inputs
       casadi_assert_dev(f.n_in()==n_in_ + n_out_ + n_out_);
       casadi_int ind=0;
       for (i=0; i<n_in_; ++i) f.assert_size_in(ind++, size1_in(i), size2_in(i));
       for (i=0; i<n_out_; ++i) f.assert_size_in(ind++, size1_out(i), size2_out(i));
       for (i=0; i<n_out_; ++i) f.assert_size_in(ind++, size1_out(i), nadj*size2_out(i));
       // Consistency check for outputs
       casadi_assert_dev(f.n_out()==n_in_);
       for (i=0; i<n_in_; ++i) f.assert_size_out(i, size1_in(i), nadj*size2_in(i));
       // Save to cache
       tocache(f);
     }
     return f;
   }
References casadi::Function::assert_size_in(), casadi::Function::assert_size_out(), casadi::combine(), casadi::FunctionInternal::der_options_, casadi::FunctionInternal::enable_reverse_, casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::get_reverse(), casadi::FunctionInternal::has_derivative(), casadi::FunctionInternal::incache(), casadi::Function::n_in(), casadi::FunctionInternal::n_in_, casadi::Function::n_out(), casadi::FunctionInternal::n_out_, casadi::ProtoFunction::name_, casadi::FunctionInternal::name_in_, casadi::FunctionInternal::name_out_, casadi::Function::reverse(), casadi::FunctionInternal::reverse_name(), casadi::FunctionInternal::reverse_options_, casadi::FunctionInternal::size1_in(), casadi::FunctionInternal::size1_out(), casadi::FunctionInternal::size2_in(), casadi::FunctionInternal::size2_out(), casadi::FunctionInternal::tocache(), and casadi::FunctionInternal::wrap().
Referenced by casadi::FunctionInternal::call_reverse(), and casadi::Function::reverse().
reverse_name()
static std::string casadi::FunctionInternal::reverse_name (const std::string & fcn, casadi_int nadj) inline static inherited
Definition at line 626 of file function_internal.hpp.
{
       return "adj" + str(nadj) + "_" + fcn;
     }
References casadi::str().
Referenced by casadi::FunctionInternal::reverse().
self()
Function casadi::FunctionInternal::self () const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_k8
Definition at line 323 of file function_internal.hpp.
 { return shared_from_this<Function>();}
serialize()
void casadi::ProtoFunction::serialize (SerializingStream & s) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_jv
Definition at line 3938 of file function_internal.cpp.
{
     serialize_type(s);
     serialize_body(s);
   }
References casadi::ProtoFunction::serialize_body(), and casadi::ProtoFunction::serialize_type().
serialize_base_function()
std::string casadi::Nlpsol::serialize_base_function () const inline override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1no
Reimplemented from casadi::ProtoFunction.
Definition at line 127 of file nlpsol_impl.hpp.
 { return "Nlpsol"; }
serialize_body()
void casadi::Nlpsol::serialize_body (SerializingStream & s) const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1nl
Reimplemented from casadi::FunctionInternal.
Reimplemented in casadi::Sqpmethod, casadi::Feasiblesqpmethod, casadi::WorhpInterface, casadi::SnoptInterface, casadi::KnitroInterface, casadi::IpoptInterface, casadi::BonminInterface, and casadi::Blocksqp.
Definition at line 1269 of file nlpsol.cpp.
{
     OracleFunction::serialize_body(s);
     s.version("Nlpsol", 3);
     s.pack("Nlpsol::nx", nx_);
     s.pack("Nlpsol::ng", ng_);
     s.pack("Nlpsol::np", np_);
     s.pack("Nlpsol::fcallback", fcallback_);
     s.pack("Nlpsol::callback_step", callback_step_);
     s.pack("Nlpsol::eval_errors_fatal", eval_errors_fatal_);
     s.pack("Nlpsol::warn_initial_bounds", warn_initial_bounds_);
     s.pack("Nlpsol::iteration_callback_ignore_errors", iteration_callback_ignore_errors_);
     s.pack("Nlpsol::calc_multipliers", calc_multipliers_);
     s.pack("Nlpsol::calc_lam_x", calc_lam_x_);
     s.pack("Nlpsol::calc_lam_p", calc_lam_p_);
     s.pack("Nlpsol::calc_f", calc_f_);
     s.pack("Nlpsol::calc_g", calc_g_);
     s.pack("Nlpsol::min_lam", min_lam_);
     s.pack("Nlpsol::bound_consistency", bound_consistency_);
     s.pack("Nlpsol::no_nlp_grad", no_nlp_grad_);
     s.pack("Nlpsol::discrete", discrete_);
     s.pack("Nlpsol::mi", mi_);
     s.pack("Nlpsol::sens_linsol", sens_linsol_);
     s.pack("Nlpsol::sens_linsol_options", sens_linsol_options_);
     s.pack("Nlpsol::detect_simple_bounds_is_simple", detect_simple_bounds_is_simple_);
     s.pack("Nlpsol::detect_simple_bounds_parts", detect_simple_bounds_parts_);
     s.pack("Nlpsol::detect_simple_bounds_target_x", detect_simple_bounds_target_x_);
   }
References casadi::Nlpsol::bound_consistency_, casadi::Nlpsol::calc_f_, casadi::Nlpsol::calc_g_, casadi::Nlpsol::calc_lam_p_, casadi::Nlpsol::calc_lam_x_, casadi::Nlpsol::calc_multipliers_, casadi::Nlpsol::callback_step_, casadi::Nlpsol::detect_simple_bounds_is_simple_, casadi::Nlpsol::detect_simple_bounds_parts_, casadi::Nlpsol::detect_simple_bounds_target_x_, casadi::Nlpsol::discrete_, casadi::Nlpsol::eval_errors_fatal_, casadi::Nlpsol::fcallback_, casadi::Nlpsol::iteration_callback_ignore_errors_, casadi::Nlpsol::mi_, casadi::Nlpsol::min_lam_, casadi::Nlpsol::ng_, casadi::Nlpsol::no_nlp_grad_, casadi::Nlpsol::np_, casadi::Nlpsol::nx_, casadi::SerializingStream::pack(), casadi::Nlpsol::sens_linsol_, casadi::Nlpsol::sens_linsol_options_, casadi::OracleFunction::serialize_body(), casadi::SerializingStream::version(), and casadi::Nlpsol::warn_initial_bounds_.
Referenced by casadi::Blocksqp::serialize_body(), casadi::BonminInterface::serialize_body(), casadi::IpoptInterface::serialize_body(), casadi::KnitroInterface::serialize_body(), casadi::SnoptInterface::serialize_body(), casadi::WorhpInterface::serialize_body(), casadi::Feasiblesqpmethod::serialize_body(), and casadi::Sqpmethod::serialize_body().
serialize_type()
void casadi::Nlpsol::serialize_type (SerializingStream & s) const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1nm
Reimplemented from casadi::FunctionInternal.
Definition at line 1298 of file nlpsol.cpp.
{
     OracleFunction::serialize_type(s);
     PluginInterface<Nlpsol>::serialize_type(s);
   }
References casadi::PluginInterface< Derived >::serialize_type(), and casadi::FunctionInternal::serialize_type().
set_function() [1/2]
void casadi::OracleFunction::set_function (const Function & fcn) inline inherited
Register the function for evaluation and statistics gathering
Definition at line 153 of file oracle_function.hpp.
 { set_function(fcn, fcn.name()); }
References casadi::Function::name(), and casadi::OracleFunction::set_function().
Referenced by casadi::OracleFunction::set_function().
set_function() [2/2]
void casadi::OracleFunction::set_function (const Function & fcn, const std::string & fname, bool jit = false) inherited
Register the function for evaluation and statistics gathering
Definition at line 211 of file oracle_function.cpp.
{
   casadi_assert(!has_function(fname), "Duplicate function " + fname);
   RegFun& r = all_functions_[fname];
   r.f = fcn;
   r.jit = jit;
 }
References casadi::OracleFunction::all_functions_, casadi::OracleFunction::RegFun::f, casadi::OracleFunction::has_function(), and casadi::OracleFunction::RegFun::jit.
Referenced by casadi::OracleFunction::create_forward(), casadi::OracleFunction::create_function(), casadi::FixedStepIntegrator::init(), casadi::ImplicitFixedStepIntegrator::init(), casadi::Rootfinder::init(), casadi::BonminInterface::init(), casadi::IpoptInterface::init(), casadi::SundialsInterface::init(), casadi::Feasiblesqpmethod::init(), casadi::Newton::init(), casadi::Sqpmethod::init(), casadi::Collocation::setup_step(), and casadi::RungeKutta::setup_step().
set_jac_sparsity()
void casadi::FunctionInternal::set_jac_sparsity (casadi_int oind, casadi_int iind, const Sparsity & sp) protected inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_nx
Definition at line 3530 of file function_internal.cpp.
{
     casadi_int ind = iind + oind * n_in_;
     jac_sparsity_[false].resize(n_in_ * n_out_);
     jac_sparsity_[false].at(ind) = sp;
     jac_sparsity_[true].resize(n_in_ * n_out_);
     jac_sparsity_[true].at(ind) = to_compact(oind, iind, sp);
   }
References casadi::FunctionInternal::jac_sparsity_, casadi::FunctionInternal::n_in_, casadi::FunctionInternal::n_out_, and casadi::FunctionInternal::to_compact().
set_temp()
void casadi::OracleFunction::set_temp (void * mem, const double ** arg, double ** res, casadi_int * iw, double * w) const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_q
Reimplemented from casadi::FunctionInternal.
Definition at line 426 of file oracle_function.cpp.
{
   auto m = static_cast<OracleMemory*>(mem);
   m->arg = arg;
   m->res = res;
   m->iw = iw;
   m->w = w;
   for (int i = 0; i < max_num_threads_; ++i) {
     auto* ml = m->thread_local_mem[i];
     ml->arg = arg;
     ml->res = res;
     ml->iw = iw;
     ml->w = w;
     arg += stride_arg_;
     res += stride_res_;
     iw += stride_iw_;
     w += stride_w_;
   }
 }
References casadi::OracleMemory::arg, casadi::OracleFunction::max_num_threads_, casadi::OracleFunction::stride_arg_, casadi::OracleFunction::stride_iw_, casadi::OracleFunction::stride_res_, and casadi::OracleFunction::stride_w_.
set_work()
void casadi::AmplInterface::set_work (void * mem, const double **& arg, double **& res, casadi_int *& iw, double *& w) const override virtual
Reimplemented from casadi::Nlpsol.
Definition at line 267 of file ampl_interface.cpp.
{
     //auto m = static_cast<AmplInterfaceMemory*>(mem);
     // Set work in base classes
     Nlpsol::set_work(mem, arg, res, iw, w);
   }
References casadi::Nlpsol::set_work().
setOptionsFromFile()
void casadi::Nlpsol::setOptionsFromFile (const std::string & file) virtual inherited
Definition at line 644 of file nlpsol.cpp.
{
     casadi_error("setOptionsFromFile not defined for class " + class_name());
   }
References casadi::Nlpsol::class_name().
setup()
void casadi::FunctionInternal::setup (void * mem, const double ** arg, double ** res, casadi_int * iw, double * w) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_nb
Definition at line 3326 of file function_internal.cpp.
{
     set_work(mem, arg, res, iw, w);
     set_temp(mem, arg, res, iw, w);
   }
References casadi::FunctionInternal::set_temp(), and casadi::FunctionInternal::set_work().
Referenced by casadi::Conic::eval(), casadi::Nlpsol::eval(), casadi::Integrator::eval(), casadi::Rootfinder::eval(), casadi::SlicotDple::eval(), and casadi::SlicotExpm::eval().
shared_from_this() [1/2]
template<class B > B casadi::SharedObjectInternal::shared_from_this protected inherited
Template function implementations.
Definition at line 136 of file shared_object_internal.hpp.
{
     casadi_assert_dev(B::test_cast(this));
     B ret;
     ret.own(this);
     return ret;
   }
shared_from_this() [2/2]
template<class B > const B casadi::SharedObjectInternal::shared_from_this protected inherited
Definition at line 144 of file shared_object_internal.hpp.
{
     casadi_assert_dev(B::test_cast(this));
     B ret;
     ret.own(const_cast<SharedObjectInternal*>(this));
     return ret;
   }
shortname()
static std::string casadi::Nlpsol::shortname () inline static inherited
Definition at line 273 of file nlpsol_impl.hpp.
 { return "nlpsol";}
signature()
std::string casadi::FunctionInternal::signature (const std::string & fname) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ly
Definition at line 2241 of file function_internal.cpp.
{
     return "int " + fname + "(const casadi_real** arg, casadi_real** res, "
                             "casadi_int* iw, casadi_real* w, int mem)";
   }
Referenced by casadi::CodeGenerator::add(), casadi::FunctionInternal::codegen(), and casadi::External::codegen_declarations().
size1_in()
casadi_int casadi::FunctionInternal::size1_in (casadi_int ind) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mg
Definition at line 940 of file function_internal.hpp.
 { return sparsity_in(ind).size1(); }
Referenced by casadi::FunctionInternal::check_arg(), casadi::FunctionInternal::forward(), casadi::Integrator::get_forward(), casadi::Integrator::get_reverse(), casadi::FunctionInternal::matching_arg(), and casadi::FunctionInternal::reverse().
size1_out()
casadi_int casadi::FunctionInternal::size1_out (casadi_int ind) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mg
Definition at line 942 of file function_internal.hpp.
 { return sparsity_out(ind).size1(); }
Referenced by casadi::FunctionInternal::forward(), casadi::Integrator::get_forward(), casadi::LinearInterpolantJac::get_jacobian(), casadi::FunctionInternal::matching_res(), and casadi::FunctionInternal::reverse().
size2_in()
casadi_int casadi::FunctionInternal::size2_in (casadi_int ind) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mg
Definition at line 941 of file function_internal.hpp.
 { return sparsity_in(ind).size2(); }
Referenced by casadi::FunctionInternal::call_gen(), casadi::FunctionInternal::call_reverse(), casadi::FunctionInternal::check_arg(), casadi::FunctionInternal::forward(), casadi::Integrator::get_reverse(), casadi::FunctionInternal::mapsum_mx(), casadi::FunctionInternal::matching_arg(), casadi::FunctionInternal::project_arg(), and casadi::FunctionInternal::reverse().
size2_out()
casadi_int casadi::FunctionInternal::size2_out (casadi_int ind) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mg
Definition at line 943 of file function_internal.hpp.
 { return sparsity_out(ind).size2(); }
Referenced by casadi::FunctionInternal::call_forward(), casadi::FunctionInternal::forward(), casadi::Integrator::get_forward(), casadi::LinearInterpolantJac::get_jacobian(), casadi::FunctionInternal::matching_res(), and casadi::FunctionInternal::reverse().
size_in()
std::pair<casadi_int, casadi_int> casadi::FunctionInternal::size_in (casadi_int ind) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mg
Definition at line 944 of file function_internal.hpp.
{
       return sparsity_in(ind).size();
     }
Referenced by casadi::Rootfinder::ad_forward(), casadi::Rootfinder::ad_reverse(), casadi::MXFunction::ad_reverse(), casadi::FunctionInternal::call_reverse(), casadi::FunctionInternal::fwd_seed(), casadi::Dple::get_forward(), and casadi::Dple::get_reverse().
size_out()
std::pair<casadi_int, casadi_int> casadi::FunctionInternal::size_out (casadi_int ind) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mg
Definition at line 947 of file function_internal.hpp.
{
       return sparsity_out(ind).size();
     }
Referenced by casadi::MXFunction::ad_forward(), casadi::Rootfinder::ad_reverse(), casadi::FunctionInternal::call_forward(), casadi::FunctionInternal::check_res(), casadi::FunctionInternal::eval(), casadi::Integrator::get_forward(), casadi::Integrator::get_reverse(), and casadi::Nlpsol::init().
slice()
Function casadi::FunctionInternal::slice (const std::string & name, const std::vector< casadi_int > & order_in, const std::vector< casadi_int > & order_out, const Dict & opts) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_l2
Reimplemented in casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, and casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >.
Definition at line 3511 of file function_internal.cpp.
{
     return wrap().slice(name, order_in, order_out, opts);
   }
References casadi::Function::slice(), and casadi::FunctionInternal::wrap().
Referenced by casadi::Function::slice().
solve()
int casadi::AmplInterface::solve (void * mem) const override virtual
Implements casadi::Nlpsol.
Definition at line 276 of file ampl_interface.cpp.
{
     auto m = static_cast<AmplInterfaceMemory*>(mem);
     auto d_nlp = &m->d_nlp;
     // Create .nl file and add preamble
     std::string nlname = temporary_file("casadi_ampl_tmp", ".nl");
     std::ofstream nl(nlname, std::ofstream::out);
     if (verbose_) casadi_message("Opened " + nlname);
     nl << nl_init_.str();
     // Primal intial guess
     nl << "x" << nx_ << "\n";
     for (casadi_int i=0; i<nx_; ++i) {
       nl << i << " " << d_nlp->z[i] << "\n";
     }
     // Add constraint bounds
     nl << "r\n";
     for (casadi_int i=0; i<ng_; ++i) {
       double lbg = d_nlp->lbz[i+nx_];
       double ubg = d_nlp->ubz[i+nx_];
       if (isinf(lbg)) {
         if (isinf(ubg)) { // no constraint
           nl << "3\n";
         } else { // only upper
           nl << "1 " << ubg <<  "\n";
         }
       } else {
         if (isinf(ubg)) { // only lower
           nl << "2 " << lbg << "\n";
         } else if (ubg==lbg) { // equality
           nl << "4 " << lbg << "\n";
         } else { // range
           nl << "0 " << lbg << " " << ubg << "\n";
         }
       }
     }
     // Add variable bounds
     nl << "b\n";
     for (casadi_int i=0; i<nx_; ++i) {
       double lbx = d_nlp->lbz[i];
       double ubx = d_nlp->ubz[i];
       if (isinf(lbx)) {
         if (isinf(ubx)) { // no constraint
           nl << "3\n";
         } else { // only upper
           nl << "1 " << ubx <<  "\n";
         }
       } else {
         if (isinf(ubx)) { // only lower
           nl << "2 " << lbx << "\n";
         } else if (ubx==lbx) { // equality
           nl << "4 " << lbx << "\n";
         } else { // range
           nl << "0 " << lbx << " " << ubx << "\n";
         }
       }
     }
     // Close file
     nl.close();
     // Temporary name for the .sol file
     std::string solname = temporary_file("casadi_ampl_tmp", ".sol");
     // Temporary name for the solver output
     std::string outname = temporary_file("casadi_ampl_tmp", ".out");
     // Call executable
     std::string system_cmd = solver_ + " -o" + solname + " " + nlname + " > " + outname;
     int ret = system(system_cmd.c_str());
     casadi_assert_dev(ret==0);
     // Delete the nl file
     if (remove(nlname.c_str())!=0) {
       casadi_warning("Failed to remove " + nlname);
     }
     if (verbose_) casadi_message("Removed " + nlname);
     // Open .out file and dump to screen
     std::ifstream out(outname, std::ifstream::in);
     casadi_assert(out.is_open(), "Failed to open " + outname);
     std::string line;
     while (!out.eof()) {
       getline(out, line);
       uout() << line << "\n";
     }
     // Close and delete .out file
     out.close();
     if (remove(outname.c_str())!=0) {
       casadi_warning("Failed to remove " + outname);
     }
     if (verbose_) casadi_message("Removed " + outname);
     // Open .sol file
     std::ifstream sol(solname, std::ifstream::in);
     casadi_assert(sol.is_open(), "Failed to open " + solname);
     if (verbose_) casadi_message("Opened " + solname);
     // Get all the lines
     std::vector<std::string> sol_lines;
     while (!sol.eof()) {
       getline(sol, line);
       sol_lines.push_back(line);
     }
     // Get the primal solution
     for (casadi_int i=0; i<nx_; ++i) {
       std::istringstream s(sol_lines.at(sol_lines.size() - nx_ + i - 1));
       s >> d_nlp->z[i];
     }
     // Get the dual solution (x)
     for (casadi_int i=0; i<nx_; ++i) {
       d_nlp->lam[i] = casadi::nan;  // not implemented
     }
     // Get the dual solution (g)
     for (casadi_int i=0; i<ng_; ++i) {
       std::istringstream s(sol_lines.at(sol_lines.size() - ng_ - nx_ + i - 1));
       s >> d_nlp->lam[i + nx_];
       d_nlp->lam[i + nx_] *= -1;
     }
     // Close and delete .sol file
     sol.close();
     if (remove(solname.c_str())!=0) {
       casadi_warning("Failed to remove " + solname);
     }
     if (verbose_) casadi_message("Removed " + solname);
     return 0;
   }
References casadi::NlpsolMemory::d_nlp, casadi::nan, casadi::Nlpsol::ng_, nl_init_, casadi::Nlpsol::nx_, solver_, casadi::temporary_file(), casadi::uout(), and casadi::ProtoFunction::verbose_.
sp_forward()
int casadi::FunctionInternal::sp_forward (const bvec_t ** arg, bvec_t ** res, casadi_int * iw, bvec_t * w, void * mem) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mw
Reimplemented in casadi::BSplineInterpolant, casadi::SXFunction, casadi::Rootfinder, casadi::MXFunction, casadi::MapSum, casadi::Map, and casadi::Integrator.
Definition at line 2642 of file function_internal.cpp.
{
     // Loop over outputs
     for (casadi_int oind=0; oind<n_out_; ++oind) {
       // Skip if nothing to assign
       if (res[oind]==nullptr || nnz_out(oind)==0) continue;
       // Clear result
       casadi_clear(res[oind], nnz_out(oind));
       // Loop over inputs
       for (casadi_int iind=0; iind<n_in_; ++iind) {
         // Skip if no seeds
         if (arg[iind]==nullptr || nnz_in(iind)==0) continue;
         // Propagate sparsity for the specific block
         if (sp_forward_block(arg, res, iw, w, mem, oind, iind)) return 1;
       }
     }
     return 0;
   }
References casadi::casadi_clear(), casadi::FunctionInternal::n_in_, casadi::FunctionInternal::n_out_, casadi::FunctionInternal::nnz_in(), casadi::FunctionInternal::nnz_out(), and casadi::FunctionInternal::sp_forward_block().
Referenced by casadi::MXFunction::sp_forward(), and casadi::BSplineInterpolant::sp_forward().
sp_forward_block()
int casadi::FunctionInternal::sp_forward_block (const bvec_t ** arg, bvec_t ** res, casadi_int * iw, bvec_t * w, void * mem, casadi_int oind, casadi_int iind) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mx
Definition at line 2661 of file function_internal.cpp.
{
     // Get the sparsity of the Jacobian block
     Sparsity sp = jac_sparsity(oind, iind, true, false);
     if (sp.is_null() || sp.nnz() == 0) return 0; // Skip if zero
     // Carry out the sparse matrix-vector multiplication
     casadi_int d1 = sp.size2();
     const casadi_int *colind = sp.colind(), *row = sp.row();
     for (casadi_int cc=0; cc<d1; ++cc) {
       for (casadi_int el = colind[cc]; el < colind[cc+1]; ++el) {
         res[oind][row[el]] |= arg[iind][cc];
       }
     }
     return 0;
   }
References casadi::Sparsity::colind(), casadi::SharedObject::is_null(), casadi::FunctionInternal::jac_sparsity(), casadi::Sparsity::nnz(), casadi::Sparsity::row(), and casadi::Sparsity::size2().
Referenced by casadi::FunctionInternal::sp_forward().
sp_reverse()
int casadi::FunctionInternal::sp_reverse (bvec_t ** arg, bvec_t ** res, casadi_int * iw, bvec_t * w, void * mem) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_my
Reimplemented in casadi::BSplineInterpolant, casadi::SXFunction, casadi::Rootfinder, casadi::MXFunction, casadi::MapSum, casadi::Map, and casadi::Integrator.
Definition at line 2677 of file function_internal.cpp.
{
     // Loop over outputs
     for (casadi_int oind=0; oind<n_out_; ++oind) {
       // Skip if nothing to assign
       if (res[oind]==nullptr || nnz_out(oind)==0) continue;
       // Loop over inputs
       for (casadi_int iind=0; iind<n_in_; ++iind) {
         // Skip if no seeds
         if (arg[iind]==nullptr || nnz_in(iind)==0) continue;
         // Get the sparsity of the Jacobian block
         Sparsity sp = jac_sparsity(oind, iind, true, false);
         if (sp.is_null() || sp.nnz() == 0) continue; // Skip if zero
         // Carry out the sparse matrix-vector multiplication
         casadi_int d1 = sp.size2();
         const casadi_int *colind = sp.colind(), *row = sp.row();
         for (casadi_int cc=0; cc<d1; ++cc) {
           for (casadi_int el = colind[cc]; el < colind[cc+1]; ++el) {
             arg[iind][cc] |= res[oind][row[el]];
           }
         }
       }
       // Clear seeds
       casadi_clear(res[oind], nnz_out(oind));
     }
     return 0;
   }
References casadi::casadi_clear(), casadi::Sparsity::colind(), casadi::SharedObject::is_null(), casadi::FunctionInternal::jac_sparsity(), casadi::FunctionInternal::n_in_, casadi::FunctionInternal::n_out_, casadi::Sparsity::nnz(), casadi::FunctionInternal::nnz_in(), casadi::FunctionInternal::nnz_out(), casadi::Sparsity::row(), and casadi::Sparsity::size2().
Referenced by casadi::MXFunction::sp_reverse(), and casadi::BSplineInterpolant::sp_reverse().
sp_weight()
double casadi::FunctionInternal::sp_weight () const virtual inherited
sparsity propagation
Extra doc: https://github.com/casadi/casadi/wiki/L_l6
Definition at line 3067 of file function_internal.cpp.
{
     // If reverse mode propagation unavailable, use forward
     if (!has_sprev()) return 0;
     // If forward mode propagation unavailable, use reverse
     if (!has_spfwd()) return 1;
     // Use the (potentially user set) option
     return ad_weight_sp_;
   }
References casadi::FunctionInternal::ad_weight_sp_, casadi::FunctionInternal::has_spfwd(), and casadi::FunctionInternal::has_sprev().
Referenced by casadi::FunctionInternal::get_jac_sparsity(), casadi::FunctionInternal::get_jac_sparsity_hierarchical(), casadi::MXFunction::sp_forward(), casadi::MXFunction::sp_reverse(), casadi::FunctionInternal::wrap(), and casadi::FunctionInternal::wrap_as_needed().
sparsity_in()
const Sparsity& casadi::FunctionInternal::sparsity_in (casadi_int ind) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mh
Definition at line 956 of file function_internal.hpp.
 { return sparsity_in_.at(ind); }
Referenced by casadi::FunctionInternal::check_arg(), casadi::FixedStepIntegrator::create_advanced(), casadi::FunctionInternal::dm_in(), casadi::FunctionInternal::from_compact(), casadi::FunctionInternal::fwd_seed(), casadi::Integrator::get_forward(), casadi::Integrator::get_reverse(), casadi::JitFunction::JitFunction(), casadi::FunctionInternal::mx_in(), casadi::FunctionInternal::project_arg(), casadi::FunctionInternal::replace_arg(), casadi::HpipmInterface::set_hpipm_prob(), casadi::FunctionInternal::sx_in(), and casadi::FunctionInternal::to_compact().
sparsity_out()
const Sparsity& casadi::FunctionInternal::sparsity_out (casadi_int ind) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mh
Definition at line 957 of file function_internal.hpp.
 { return sparsity_out_.at(ind); }
Referenced by casadi::FunctionInternal::call_gen(), casadi::FunctionInternal::check_res(), casadi::FunctionInternal::dm_out(), casadi::FunctionInternal::eval_gen(), casadi::FunctionInternal::from_compact(), casadi::Integrator::get_reverse(), casadi::JitFunction::JitFunction(), casadi::FunctionInternal::mx_out(), casadi::FunctionInternal::replace_res(), casadi::FunctionInternal::sx_out(), and casadi::FunctionInternal::to_compact().
sprint()
void casadi::ProtoFunction::sprint (char * buf, size_t buf_sz, const char * fmt, ...) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_js
Definition at line 3650 of file function_internal.cpp.
{
     // Variable number of arguments
     va_list args;
     va_start(args, fmt);
     // Print to buffer
     casadi_int n = vsnprintf(buf, buf_sz, fmt, args);
     // Cleanup
     va_end(args);
     // Throw error if failure
     casadi_assert(n>=0 && n<buf_sz, "Print failure while processing '" + std::string(fmt) + "'");
   }
Referenced by casadi::ProtoFunction::format_time(), and casadi::ProtoFunction::print_time().
string_from_UnifiedReturnStatus()
std::string casadi::FunctionInternal::string_from_UnifiedReturnStatus (UnifiedReturnStatus status) static inherited
Definition at line 3718 of file function_internal.cpp.
{
     switch (status) {
       case SOLVER_RET_LIMITED:  return "SOLVER_RET_LIMITED";
       case SOLVER_RET_NAN:  return "SOLVER_RET_NAN";
       case SOLVER_RET_SUCCESS:  return "SOLVER_RET_SUCCESS";
       default: return "SOLVER_RET_UNKNOWN";
     }
   }
References casadi::SOLVER_RET_LIMITED, casadi::SOLVER_RET_NAN, and casadi::SOLVER_RET_SUCCESS.
Referenced by casadi::Conic::get_stats(), casadi::Nlpsol::get_stats(), and casadi::Rootfinder::get_stats().
sx_in() [1/2]
const std::vector< SX > casadi::FunctionInternal::sx_in () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_l7
Reimplemented in casadi::SXFunction.
Definition at line 3094 of file function_internal.cpp.
{
     std::vector<SX> ret(n_in_);
     for (casadi_int i=0; i<ret.size(); ++i) {
       ret[i] = sx_in(i);
     }
     return ret;
   }
References casadi::FunctionInternal::n_in_.
sx_in() [2/2]
const SX casadi::FunctionInternal::sx_in (casadi_int ind) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_l7
Reimplemented in casadi::SXFunction.
Definition at line 3078 of file function_internal.cpp.
{
     return SX::sym(name_in_.at(ind), sparsity_in(ind));
   }
References casadi::FunctionInternal::name_in_, casadi::FunctionInternal::sparsity_in(), and casadi::GenericMatrix< Matrix< Scalar > >::sym().
sx_out() [1/2]
const std::vector< SX > casadi::FunctionInternal::sx_out () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_l7
Definition at line 3102 of file function_internal.cpp.
{
     std::vector<SX> ret(n_out_);
     for (casadi_int i=0; i<ret.size(); ++i) {
       ret[i] = sx_out(i);
     }
     return ret;
   }
References casadi::FunctionInternal::n_out_.
sx_out() [2/2]
const SX casadi::FunctionInternal::sx_out (casadi_int ind) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_l7
Definition at line 3082 of file function_internal.cpp.
{
     return SX::sym(name_out_.at(ind), sparsity_out(ind));
   }
References casadi::FunctionInternal::name_out_, casadi::FunctionInternal::sparsity_out(), and casadi::GenericMatrix< Matrix< Scalar > >::sym().
symbolic_output()
std::vector< MX > casadi::FunctionInternal::symbolic_output (const std::vector< MX > & arg) const virtual inherited
Reimplemented in casadi::MXFunction.
Definition at line 1044 of file function_internal.cpp.
{
     return self()(arg);
   }
Referenced by casadi::MXFunction::symbolic_output().
symbolicAdjSeed()
template<typename MatType > std::vector< std::vector< MatType > > casadi::FunctionInternal::symbolicAdjSeed (casadi_int nadj, const std::vector< MatType > & v) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ns
Definition at line 1442 of file function_internal.hpp.
{
     std::vector<std::vector<MatType> > aseed(nadj, v);
     for (casadi_int dir=0; dir<nadj; ++dir) {
       // Replace symbolic inputs
       casadi_int oind=0;
       for (typename std::vector<MatType>::iterator i=aseed[dir].begin();
           i!=aseed[dir].end();
           ++i, ++oind) {
         // Name of the adjoint seed
         std::stringstream ss;
         ss << "a";
         if (nadj>1) ss << dir << "_";
         ss << oind;
         // Save to matrix
         *i = MatType::sym(ss.str(), is_diff_out_[oind] ? i->sparsity() : Sparsity(i->size()));
       }
     }
     return aseed;
   }
References casadi::FunctionInternal::is_diff_out_.
sz_arg()
size_t casadi::FunctionInternal::sz_arg () const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_n0
Definition at line 1119 of file function_internal.hpp.
 { return sz_arg_per_ + sz_arg_tmp_;}
Referenced by casadi::FunctionInternal::alloc(), casadi::FunctionInternal::alloc_arg(), casadi::FunctionInternal::call_gen(), casadi::OmpMap::codegen_body(), casadi::FunctionInternal::codegen_meta(), casadi::OmpMap::eval(), casadi::MXFunction::eval_sx(), casadi::OracleFunction::finalize(), casadi::FunctionInternal::get_jac_sparsity_gen(), casadi::FunctionInternal::get_jac_sparsity_hierarchical(), casadi::FunctionInternal::get_jac_sparsity_hierarchical_symm(), casadi::External::init(), casadi::Nlpsol::init(), casadi::HighsInterface::init(), casadi::HpipmInterface::init(), casadi::Qrqp::init(), and casadi::FunctionInternal::sz_work().
sz_iw()
size_t casadi::FunctionInternal::sz_iw () const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_n2
Definition at line 1129 of file function_internal.hpp.
 { return sz_iw_per_ + sz_iw_tmp_;}
Referenced by casadi::FunctionInternal::alloc(), casadi::FunctionInternal::alloc_iw(), casadi::FunctionInternal::call_gen(), casadi::OmpMap::codegen_body(), casadi::FunctionInternal::codegen_meta(), casadi::OmpMap::eval(), casadi::OracleFunction::finalize(), casadi::FunctionInternal::get_jac_sparsity_gen(), casadi::FunctionInternal::get_jac_sparsity_hierarchical(), casadi::FunctionInternal::get_jac_sparsity_hierarchical_symm(), casadi::External::init(), casadi::Nlpsol::init(), casadi::HighsInterface::init(), casadi::HpipmInterface::init(), casadi::Feasiblesqpmethod::init(), casadi::Qrqp::init(), casadi::Sqpmethod::init(), and casadi::FunctionInternal::sz_work().
sz_res()
size_t casadi::FunctionInternal::sz_res () const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_n1
Definition at line 1124 of file function_internal.hpp.
 { return sz_res_per_ + sz_res_tmp_;}
Referenced by casadi::FunctionInternal::alloc(), casadi::FunctionInternal::alloc_res(), casadi::FunctionInternal::call_gen(), casadi::OmpMap::codegen_body(), casadi::FunctionInternal::codegen_meta(), casadi::OmpMap::eval(), casadi::MXFunction::eval_sx(), casadi::OracleFunction::finalize(), casadi::FunctionInternal::get_jac_sparsity_gen(), casadi::FunctionInternal::get_jac_sparsity_hierarchical(), casadi::FunctionInternal::get_jac_sparsity_hierarchical_symm(), casadi::External::init(), casadi::Nlpsol::init(), casadi::HighsInterface::init(), casadi::HpipmInterface::init(), casadi::Qrqp::init(), and casadi::FunctionInternal::sz_work().
sz_w()
size_t casadi::FunctionInternal::sz_w () const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_n3
Definition at line 1134 of file function_internal.hpp.
 { return sz_w_per_ + sz_w_tmp_;}
Referenced by casadi::FunctionInternal::alloc(), casadi::FunctionInternal::alloc_w(), casadi::FunctionInternal::call_gen(), casadi::OmpMap::codegen_body(), casadi::FunctionInternal::codegen_meta(), casadi::OmpMap::eval(), casadi::OracleFunction::finalize(), casadi::FunctionInternal::get_jac_sparsity_gen(), casadi::FunctionInternal::get_jac_sparsity_hierarchical(), casadi::FunctionInternal::get_jac_sparsity_hierarchical_symm(), casadi::External::init(), casadi::MXFunction::init(), casadi::Nlpsol::init(), casadi::Rootfinder::init(), casadi::HighsInterface::init(), casadi::HpipmInterface::init(), casadi::Feasiblesqpmethod::init(), casadi::Qrqp::init(), casadi::Sqpmethod::init(), casadi::MXFunction::sp_reverse(), and casadi::FunctionInternal::sz_work().
sz_work()
void casadi::FunctionInternal::sz_work (size_t & sz_arg, size_t & sz_res, size_t & sz_iw, size_t & sz_w) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mz
Definition at line 2709 of file function_internal.cpp.
{
     sz_arg = this->sz_arg();
     sz_res = this->sz_res();
     sz_iw = this->sz_iw();
     sz_w = this->sz_w();
   }
References casadi::FunctionInternal::sz_arg(), casadi::FunctionInternal::sz_iw(), casadi::FunctionInternal::sz_res(), and casadi::FunctionInternal::sz_w().
to_compact()
Sparsity casadi::FunctionInternal::to_compact (casadi_int oind, casadi_int iind, const Sparsity & sp) const inherited
Definition at line 1815 of file function_internal.cpp.
{
     // Strip rows and columns
     std::vector<casadi_int> mapping;
     return sp.sub(sparsity_out(oind).find(), sparsity_in(iind).find(), mapping);
   }
References casadi::FunctionInternal::find(), casadi::FunctionInternal::sparsity_in(), casadi::FunctionInternal::sparsity_out(), and casadi::Sparsity::sub().
Referenced by casadi::FunctionInternal::jac_sparsity(), and casadi::FunctionInternal::set_jac_sparsity().
tocache()
void casadi::FunctionInternal::tocache (const Function & f, const std::string & suffix = "") const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ll
Definition at line 973 of file function_internal.cpp.
{
     // Add to cache
     cache_.insert(std::make_pair(f.name() + ":" + suffix, f));
     // Remove a lost reference, if any, to prevent uncontrolled growth
     for (auto it = cache_.begin(); it!=cache_.end(); ++it) {
       if (!it->second.alive()) {
         cache_.erase(it);
         break; // just one dead reference is enough
       }
     }
   }
References casadi::FunctionInternal::cache_, and casadi::Function::name().
Referenced by casadi::MapSum::create(), casadi::OracleFunction::create_function(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::init(), casadi::FunctionInternal::jacobian(), casadi::FunctionInternal::map(), casadi::FunctionInternal::reverse(), and casadi::FunctionInternal::wrap().
uses_output()
bool casadi::Nlpsol::uses_output () const inline override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1o1
Reimplemented from casadi::FunctionInternal.
Definition at line 223 of file nlpsol_impl.hpp.
 {return true;}
weak()
WeakRef * casadi::SharedObjectInternal::weak () inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1ai
Definition at line 62 of file shared_object_internal.cpp.
{
     if (weak_ref_==nullptr) {
       weak_ref_ = new WeakRef(this);
     }
     return weak_ref_;
   }
Referenced by casadi::SharedObject::weak().
which_depends()
std::vector< bool > casadi::FunctionInternal::which_depends (const std::string & s_in, const std::vector< std::string > & s_out, casadi_int order, bool tr = false) const virtual inherited
Parameters
[in] s_in Input name
[in] s_out Output name(s)
[in] order Only 1 (linear) and 2 (nonlinear) allowed
[in] tr Flip the relationship. Return which expressions contain the variables
Extra doc: https://github.com/casadi/casadi/wiki/L_k9
Reimplemented in casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, and casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >.
Definition at line 3498 of file function_internal.cpp.
{
     casadi_error("'which_depends' not defined for " + class_name());
     return std::vector<bool>();
   }
References casadi::SharedObjectInternal::class_name().
wrap()
Function casadi::FunctionInternal::wrap () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_li
Definition at line 1022 of file function_internal.cpp.
{
     Function f;
     std::string fname = "wrap_" + name_;
     if (!incache(fname, f)) {
       // Options
       Dict opts;
       opts["derivative_of"] = derivative_of_;
       opts["ad_weight"] = ad_weight();
       opts["ad_weight_sp"] = sp_weight();
       opts["max_num_dir"] = max_num_dir_;
       opts["is_diff_in"] = is_diff_in_;
       opts["is_diff_out"] = is_diff_out_;
       // Wrap the function
       std::vector<MX> arg = mx_in();
       std::vector<MX> res = self()(arg);
       f = Function(fname, arg, res, name_in_, name_out_, opts);
       // Save in cache
       tocache(f);
     }
     return f;
   }
References casadi::FunctionInternal::ad_weight(), casadi::FunctionInternal::derivative_of_, casadi::FunctionInternal::Function, casadi::FunctionInternal::incache(), casadi::FunctionInternal::is_diff_in_, casadi::FunctionInternal::is_diff_out_, casadi::FunctionInternal::max_num_dir_, casadi::FunctionInternal::mx_in(), casadi::ProtoFunction::name_, casadi::FunctionInternal::name_in_, casadi::FunctionInternal::name_out_, casadi::FunctionInternal::sp_weight(), and casadi::FunctionInternal::tocache().
Referenced by casadi::FunctionInternal::eval_mx(), casadi::FunctionInternal::factory(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::jacobian(), casadi::FunctionInternal::reverse(), casadi::FunctionInternal::slice(), and casadi::Function::wrap().
wrap_as_needed()
Function casadi::FunctionInternal::wrap_as_needed (const Dict & opts) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lj
Definition at line 1004 of file function_internal.cpp.
{
     if (opts.empty()) return shared_from_this<Function>();
     std::string fname = "wrap_" + name_;
     // Options
     Dict my_opts = opts;
     my_opts["derivative_of"] = derivative_of_;
     if (my_opts.find("ad_weight")==my_opts.end())
       my_opts["ad_weight"] = ad_weight();
     if (my_opts.find("ad_weight_sp")==my_opts.end())
       my_opts["ad_weight_sp"] = sp_weight();
     if (my_opts.find("max_num_dir")==my_opts.end())
       my_opts["max_num_dir"] = max_num_dir_;
     // Wrap the function
     std::vector<MX> arg = mx_in();
     std::vector<MX> res = self()(arg);
     return Function(fname, arg, res, name_in_, name_out_, my_opts);
   }
References casadi::FunctionInternal::ad_weight(), casadi::FunctionInternal::derivative_of_, casadi::FunctionInternal::Function, casadi::FunctionInternal::max_num_dir_, casadi::FunctionInternal::mx_in(), casadi::ProtoFunction::name_, casadi::FunctionInternal::name_in_, casadi::FunctionInternal::name_out_, and casadi::FunctionInternal::sp_weight().
Referenced by casadi::Function::wrap_as_needed().
Member Data Documentation
ad_weight_
double casadi::FunctionInternal::ad_weight_ inherited
Definition at line 1296 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::ad_weight(), casadi::FunctionInternal::change_option(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
ad_weight_sp_
double casadi::FunctionInternal::ad_weight_sp_ inherited
Definition at line 1296 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::change_option(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), casadi::FunctionInternal::serialize_body(), and casadi::FunctionInternal::sp_weight().
all_functions_
std::map<std::string, RegFun> casadi::OracleFunction::all_functions_ protected inherited
Definition at line 88 of file oracle_function.hpp.
Referenced by casadi::OracleFunction::finalize(), casadi::OracleFunction::generate_dependencies(), casadi::OracleFunction::get_function(), casadi::OracleFunction::has_function(), casadi::OracleFunction::init_mem(), casadi::OracleFunction::jit_dependencies(), casadi::OracleFunction::local_init_mem(), casadi::OracleFunction::monitored(), casadi::OracleFunction::OracleFunction(), casadi::OracleFunction::serialize_body(), and casadi::OracleFunction::set_function().
always_inline_
bool casadi::FunctionInternal::always_inline_ inherited
Definition at line 1200 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::eval_mx(), casadi::MXFunction::eval_mx(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
bound_consistency_
bool casadi::Nlpsol::bound_consistency_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1nk
Definition at line 98 of file nlpsol_impl.hpp.
Referenced by casadi::Feasiblesqpmethod::codegen_body(), casadi::Sqpmethod::codegen_body(), casadi::Nlpsol::eval(), casadi::Nlpsol::init(), casadi::Nlpsol::Nlpsol(), and casadi::Nlpsol::serialize_body().
cache_
std::map<std::string, WeakRef> casadi::FunctionInternal::cache_ mutable inherited
Definition at line 1272 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::cache(), casadi::FunctionInternal::incache(), and casadi::FunctionInternal::tocache().
cache_init_
Dict casadi::FunctionInternal::cache_init_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_26h
Definition at line 1269 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
calc_f_
bool casadi::Nlpsol::calc_f_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1nk
Definition at line 97 of file nlpsol_impl.hpp.
Referenced by casadi::Sqpmethod::codegen_body(), casadi::Sqpmethod::codegen_declarations(), casadi::Nlpsol::eval(), casadi::Nlpsol::init(), casadi::Nlpsol::Nlpsol(), and casadi::Nlpsol::serialize_body().
calc_g_
bool casadi::Nlpsol::calc_g_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1nk
Definition at line 97 of file nlpsol_impl.hpp.
Referenced by casadi::Sqpmethod::codegen_body(), casadi::Sqpmethod::codegen_declarations(), casadi::Nlpsol::eval(), casadi::Nlpsol::init(), casadi::Nlpsol::Nlpsol(), and casadi::Nlpsol::serialize_body().
calc_lam_p_
bool casadi::Nlpsol::calc_lam_p_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1nk
Definition at line 97 of file nlpsol_impl.hpp.
Referenced by casadi::Sqpmethod::codegen_body(), casadi::Sqpmethod::codegen_declarations(), casadi::Nlpsol::eval(), casadi::Nlpsol::init(), casadi::Nlpsol::Nlpsol(), and casadi::Nlpsol::serialize_body().
calc_lam_x_
bool casadi::Nlpsol::calc_lam_x_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1nk
Definition at line 97 of file nlpsol_impl.hpp.
Referenced by casadi::Sqpmethod::codegen_body(), casadi::Sqpmethod::codegen_declarations(), casadi::Nlpsol::eval(), casadi::Nlpsol::init(), casadi::Nlpsol::Nlpsol(), and casadi::Nlpsol::serialize_body().
calc_multipliers_
bool casadi::Nlpsol::calc_multipliers_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1nk
Definition at line 96 of file nlpsol_impl.hpp.
Referenced by casadi::Nlpsol::init(), casadi::Nlpsol::Nlpsol(), and casadi::Nlpsol::serialize_body().
callback_step_
casadi_int casadi::Nlpsol::callback_step_ inherited
Definition at line 78 of file nlpsol_impl.hpp.
Referenced by casadi::Nlpsol::init(), casadi::BonminUserClass::intermediate_callback(), casadi::IpoptUserClass::intermediate_callback(), casadi::Nlpsol::Nlpsol(), and casadi::Nlpsol::serialize_body().
checkout_
casadi_checkout_t casadi::FunctionInternal::checkout_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_nl
Definition at line 1249 of file function_internal.hpp.
Referenced by casadi::GenericExternal::any_symbol_found(), casadi::External::codegen_checkout(), casadi::External::codegen_declarations(), casadi::External::codegen_mem_type(), casadi::FunctionInternal::eval_gen(), casadi::FunctionInternal::finalize(), casadi::FunctionInternal::FunctionInternal(), casadi::GenericExternal::init_external(), and casadi::FunctionBuffer::operator=().
common_options_
Dict casadi::OracleFunction::common_options_ protected inherited
Definition at line 70 of file oracle_function.hpp.
Referenced by casadi::OracleFunction::create_function(), casadi::OracleFunction::init(), casadi::OracleFunction::OracleFunction(), and casadi::OracleFunction::serialize_body().
compiler_
Importer casadi::FunctionInternal::compiler_ inherited
Definition at line 1285 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::finalize(), casadi::FunctionInternal::FunctionInternal(), casadi::Scpgen::init(), casadi::OracleFunction::jit_dependencies(), and casadi::FunctionInternal::serialize_body().
compiler_plugin_
std::string casadi::FunctionInternal::compiler_plugin_ inherited
Definition at line 1284 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::finalize(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), casadi::Scpgen::init(), casadi::OracleFunction::jit_dependencies(), and casadi::FunctionInternal::serialize_body().
custom_jacobian_
Function casadi::FunctionInternal::custom_jacobian_ inherited
Definition at line 1333 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
der_options_
Dict casadi::FunctionInternal::der_options_ inherited
Definition at line 1330 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::forward(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), casadi::FunctionInternal::jacobian(), casadi::FunctionInternal::reverse(), and casadi::FunctionInternal::serialize_body().
derivative_of_
Function casadi::FunctionInternal::derivative_of_ inherited
Definition at line 1278 of file function_internal.hpp.
Referenced by casadi::FiniteDiff::codegen_body(), casadi::LinearInterpolantJac::codegen_body(), casadi::FiniteDiff::codegen_declarations(), casadi::FiniteDiff::eval(), casadi::LinearInterpolantJac::eval(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FiniteDiff::get_default_in(), casadi::CentralDiff::get_forward(), casadi::FunctionInternal::get_n_in(), casadi::FiniteDiff::get_n_in(), casadi::FunctionInternal::get_n_out(), casadi::FiniteDiff::get_n_out(), casadi::FunctionInternal::get_name_in(), casadi::FiniteDiff::get_name_in(), casadi::FunctionInternal::get_name_out(), casadi::FiniteDiff::get_name_out(), casadi::FunctionInternal::get_sparsity_in(), casadi::FiniteDiff::get_sparsity_in(), casadi::FunctionInternal::get_sparsity_out(), casadi::FiniteDiff::get_sparsity_out(), casadi::LinearInterpolantJac::has_parametric_grid(), casadi::LinearInterpolantJac::has_parametric_values(), casadi::FiniteDiff::init(), casadi::FunctionInternal::init(), casadi::SundialsInterface::init(), casadi::LinearInterpolantJac::init(), casadi::FunctionInternal::jac_is_symm(), casadi::FunctionInternal::serialize_body(), casadi::LinearInterpolantJac::serialize_type(), casadi::FunctionInternal::wrap(), and casadi::FunctionInternal::wrap_as_needed().
deserialize_map
std::map< std::string, ProtoFunction *(*)(DeserializingStream &)> casadi::FunctionInternal::deserialize_map static inherited
Initial value:
= {
    {"MXFunction", MXFunction::deserialize},
    {"SXFunction", SXFunction::deserialize},
    {"Interpolant", Interpolant::deserialize},
    {"Switch", Switch::deserialize},
    {"Map", Map::deserialize},
    {"MapSum", MapSum::deserialize},
    {"Nlpsol", Nlpsol::deserialize},
    {"Rootfinder", Rootfinder::deserialize},
    {"Integrator", Integrator::deserialize},
    {"External", External::deserialize},
    {"Conic", Conic::deserialize},
  }
Definition at line 1377 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::deserialize().
detect_simple_bounds_is_simple_
std::vector<char> casadi::Nlpsol::detect_simple_bounds_is_simple_ inherited
Definition at line 84 of file nlpsol_impl.hpp.
Referenced by casadi::Nlpsol::get_forward(), casadi::Nlpsol::get_reverse(), casadi::Nlpsol::get_sparsity_out(), casadi::Nlpsol::init(), casadi::Nlpsol::Nlpsol(), casadi::Nlpsol::nlpsol_codegen_body(), and casadi::Nlpsol::serialize_body().
detect_simple_bounds_parts_
Function casadi::Nlpsol::detect_simple_bounds_parts_ inherited
Definition at line 85 of file nlpsol_impl.hpp.
Referenced by casadi::Nlpsol::eval(), casadi::Nlpsol::init(), casadi::Nlpsol::Nlpsol(), and casadi::Nlpsol::serialize_body().
detect_simple_bounds_target_g_
std::vector<casadi_int> casadi::Nlpsol::detect_simple_bounds_target_g_ inherited
Definition at line 87 of file nlpsol_impl.hpp.
Referenced by casadi::Nlpsol::init(), casadi::Nlpsol::Nlpsol(), and casadi::Nlpsol::nlpsol_codegen_body().
detect_simple_bounds_target_x_
std::vector<casadi_int> casadi::Nlpsol::detect_simple_bounds_target_x_ inherited
Definition at line 86 of file nlpsol_impl.hpp.
Referenced by casadi::Nlpsol::init(), casadi::Nlpsol::Nlpsol(), casadi::Nlpsol::nlpsol_codegen_body(), and casadi::Nlpsol::serialize_body().
discrete_
std::vector<bool> casadi::Nlpsol::discrete_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1nk
Definition at line 101 of file nlpsol_impl.hpp.
Referenced by casadi::BonminUserClass::get_variables_types(), casadi::Nlpsol::init(), casadi::Nlpsol::Nlpsol(), casadi::Nlpsol::serialize_body(), and casadi::KnitroInterface::solve().
dump_
bool casadi::FunctionInternal::dump_ inherited
Definition at line 1321 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::change_option(), casadi::FunctionInternal::eval_gen(), casadi::FunctionInternal::finalize(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), and casadi::FunctionInternal::init().
dump_count_
casadi_int casadi::FunctionInternal::dump_count_ = 0 mutable inherited
Definition at line 1336 of file function_internal.hpp.
dump_dir_
std::string casadi::FunctionInternal::dump_dir_ inherited
Definition at line 1324 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::change_option(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
dump_format_
std::string casadi::FunctionInternal::dump_format_ inherited
Definition at line 1327 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::change_option(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
dump_in_
bool casadi::FunctionInternal::dump_in_ inherited
Definition at line 1321 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::change_option(), casadi::FunctionInternal::eval_gen(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
dump_out_
bool casadi::FunctionInternal::dump_out_ inherited
Definition at line 1321 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::change_option(), casadi::FunctionInternal::eval_gen(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
enable_fd_
bool casadi::FunctionInternal::enable_fd_ inherited
Definition at line 1292 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::ad_weight(), casadi::FunctionInternal::adjViaJac(), casadi::FunctionInternal::call_forward(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::fwdViaJac(), casadi::FunctionInternal::get_partition(), casadi::FunctionInternal::has_derivative(), casadi::FunctionInternal::init(), casadi::JitFunction::JitFunction(), and casadi::FunctionInternal::serialize_body().
enable_fd_op_
bool casadi::FunctionInternal::enable_fd_op_ inherited
Definition at line 1293 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
enable_forward_
bool casadi::FunctionInternal::enable_forward_ inherited
Definition at line 1292 of file function_internal.hpp.
Referenced by casadi::MXFunction::ad_forward(), casadi::FunctionInternal::ad_weight(), casadi::FunctionInternal::adjViaJac(), casadi::FunctionInternal::call_forward(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::fwdViaJac(), casadi::FunctionInternal::get_partition(), casadi::FunctionInternal::has_derivative(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
enable_forward_op_
bool casadi::FunctionInternal::enable_forward_op_ inherited
Definition at line 1293 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
enable_jacobian_
bool casadi::FunctionInternal::enable_jacobian_ inherited
Definition at line 1292 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::has_derivative(), casadi::FunctionInternal::init(), casadi::FunctionInternal::jacobian(), and casadi::FunctionInternal::serialize_body().
enable_jacobian_op_
bool casadi::FunctionInternal::enable_jacobian_op_ inherited
Definition at line 1293 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
enable_reverse_
bool casadi::FunctionInternal::enable_reverse_ inherited
Definition at line 1292 of file function_internal.hpp.
Referenced by casadi::MXFunction::ad_reverse(), casadi::FunctionInternal::ad_weight(), casadi::FunctionInternal::adjViaJac(), casadi::FunctionInternal::call_reverse(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::fwdViaJac(), casadi::FunctionInternal::get_partition(), casadi::FunctionInternal::has_derivative(), casadi::FunctionInternal::init(), casadi::FunctionInternal::reverse(), and casadi::FunctionInternal::serialize_body().
enable_reverse_op_
bool casadi::FunctionInternal::enable_reverse_op_ inherited
Definition at line 1293 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
error_on_fail_
bool casadi::ProtoFunction::error_on_fail_ inherited
Definition at line 249 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::call_gen(), casadi::HighsInterface::codegen_body(), casadi::HpipmInterface::codegen_body(), casadi::OsqpInterface::codegen_body(), casadi::Qrqp::codegen_body(), casadi::Conic::Conic(), casadi::Conic::eval(), casadi::Nlpsol::eval(), casadi::Rootfinder::eval(), casadi::ProtoFunction::generate_options(), casadi::ProtoFunction::init(), casadi::Nlpsol::Nlpsol(), casadi::ProtoFunction::ProtoFunction(), casadi::Rootfinder::Rootfinder(), casadi::ProtoFunction::serialize_body(), casadi::CplexInterface::solve(), and casadi::KinsolInterface::solve().
eval_
eval_t casadi::FunctionInternal::eval_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_nk
Definition at line 1244 of file function_internal.hpp.
Referenced by casadi::FunctionBuffer::_eval(), casadi::GenericExternal::any_symbol_found(), casadi::FunctionInternal::eval_gen(), casadi::FunctionInternal::finalize(), casadi::FunctionInternal::FunctionInternal(), and casadi::GenericExternal::init_external().
eval_errors_fatal_
bool casadi::Nlpsol::eval_errors_fatal_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1nk
Definition at line 93 of file nlpsol_impl.hpp.
Referenced by casadi::Nlpsol::init(), casadi::Nlpsol::Nlpsol(), and casadi::Nlpsol::serialize_body().
fcallback_
Function casadi::Nlpsol::fcallback_ inherited
Definition at line 75 of file nlpsol_impl.hpp.
Referenced by casadi::Nlpsol::callback(), casadi::Nlpsol::init(), casadi::BonminInterface::intermediate_callback(), casadi::IpoptInterface::intermediate_callback(), casadi::Nlpsol::Nlpsol(), casadi::Nlpsol::serialize_body(), and casadi::WorhpInterface::solve().
fd_method_
std::string casadi::FunctionInternal::fd_method_ inherited
Definition at line 1311 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::forward(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
fd_options_
Dict casadi::FunctionInternal::fd_options_ inherited
Definition at line 1305 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::forward(), casadi::FunctionInternal::generate_options(), and casadi::FunctionInternal::init().
fd_step_
double casadi::FunctionInternal::fd_step_ inherited
Definition at line 1308 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
forward_options_
Dict casadi::FunctionInternal::forward_options_ inherited
Definition at line 1330 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::forward(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
has_refcount_
bool casadi::FunctionInternal::has_refcount_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_no
Definition at line 1264 of file function_internal.hpp.
Referenced by casadi::CodeGenerator::add_dependency(), casadi::FunctionInternal::FunctionInternal(), casadi::Call::has_refcount(), casadi::External::init(), casadi::MXFunction::init(), casadi::OsqpInterface::OsqpInterface(), and casadi::FunctionInternal::serialize_body().
infix_
const std::string casadi::Nlpsol::infix_ = "nlpsol" static inherited
Definition at line 270 of file nlpsol_impl.hpp.
inputs_check_
bool casadi::FunctionInternal::inputs_check_ inherited
Definition at line 1302 of file function_internal.hpp.
Referenced by casadi::Nlpsol::check_inputs(), casadi::Conic::eval(), casadi::SqicInterface::evaluate(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), casadi::FunctionInternal::serialize_body(), and casadi::GurobiInterface::solve().
is_diff_in_
std::vector<bool> casadi::FunctionInternal::is_diff_in_ inherited
Definition at line 1206 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::codegen_meta(), casadi::FunctionInternal::definition(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::fwd_seed(), casadi::FunctionInternal::init(), casadi::Map::init(), casadi::MapSum::init(), casadi::FunctionInternal::jac_sparsity(), casadi::FunctionInternal::serialize_body(), and casadi::FunctionInternal::wrap().
is_diff_out_
std::vector<bool> casadi::FunctionInternal::is_diff_out_ inherited
Definition at line 1206 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::codegen_meta(), casadi::FunctionInternal::definition(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::init(), casadi::Map::init(), casadi::MapSum::init(), casadi::FunctionInternal::jac_sparsity(), casadi::FunctionInternal::serialize_body(), casadi::FunctionInternal::symbolicAdjSeed(), and casadi::FunctionInternal::wrap().
iteration_callback_ignore_errors_
bool casadi::Nlpsol::iteration_callback_ignore_errors_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1nk
Definition at line 95 of file nlpsol_impl.hpp.
Referenced by casadi::Nlpsol::callback(), casadi::Nlpsol::init(), casadi::BonminInterface::intermediate_callback(), casadi::IpoptInterface::intermediate_callback(), casadi::Nlpsol::Nlpsol(), and casadi::Nlpsol::serialize_body().
jac_penalty_
double casadi::FunctionInternal::jac_penalty_ inherited
Definition at line 1289 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::adjViaJac(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::fwdViaJac(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
jac_sparsity_
std::vector<Sparsity> casadi::FunctionInternal::jac_sparsity_[2] mutable inherited
Definition at line 1275 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::jac_sparsity(), and casadi::FunctionInternal::set_jac_sparsity().
jacobian_options_
Dict casadi::FunctionInternal::jacobian_options_ inherited
Definition at line 1330 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), casadi::FunctionInternal::jacobian(), and casadi::FunctionInternal::serialize_body().
jit_
bool casadi::FunctionInternal::jit_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_nf
Definition at line 1217 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::finalize(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), casadi::JitFunction::JitFunction(), casadi::OracleFunction::OracleFunction(), casadi::FunctionInternal::serialize_body(), casadi::OracleFunction::serialize_body(), and casadi::FunctionInternal::~FunctionInternal().
jit_base_name_
std::string casadi::FunctionInternal::jit_base_name_ inherited
Definition at line 1234 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::finalize(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
jit_cleanup_
bool casadi::FunctionInternal::jit_cleanup_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ng
Definition at line 1222 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), casadi::FunctionInternal::serialize_body(), and casadi::FunctionInternal::~FunctionInternal().
jit_name_
std::string casadi::FunctionInternal::jit_name_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ni
Definition at line 1232 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::finalize(), and casadi::FunctionInternal::~FunctionInternal().
jit_options_
Dict casadi::FunctionInternal::jit_options_ inherited
Definition at line 1286 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::finalize(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), casadi::Scpgen::init(), casadi::OracleFunction::jit_dependencies(), casadi::FunctionInternal::serialize_body(), and casadi::FunctionInternal::~FunctionInternal().
jit_serialize_
std::string casadi::FunctionInternal::jit_serialize_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_nh
Definition at line 1227 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), casadi::OracleFunction::OracleFunction(), casadi::FunctionInternal::serialize_body(), and casadi::OracleFunction::serialize_body().
jit_temp_suffix_
bool casadi::FunctionInternal::jit_temp_suffix_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_nj
Definition at line 1239 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::finalize(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
kkt_
WeakRef casadi::Nlpsol::kkt_ mutable inherited
Definition at line 108 of file nlpsol_impl.hpp.
Referenced by casadi::Nlpsol::kkt().
max_io_
casadi_int casadi::FunctionInternal::max_io_ inherited
Definition at line 1318 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
max_num_dir_
casadi_int casadi::FunctionInternal::max_num_dir_ inherited
Definition at line 1299 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::call_forward(), casadi::FunctionInternal::call_reverse(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), casadi::FunctionInternal::serialize_body(), casadi::FunctionInternal::wrap(), and casadi::FunctionInternal::wrap_as_needed().
max_num_threads_
int casadi::OracleFunction::max_num_threads_ protected inherited
Definition at line 77 of file oracle_function.hpp.
Referenced by casadi::OracleFunction::calc_function(), casadi::OracleFunction::finalize(), casadi::OracleFunction::free_mem(), casadi::OracleFunction::init(), casadi::KnitroInterface::init(), casadi::OracleFunction::init_mem(), casadi::OracleFunction::join_results(), casadi::OracleFunction::OracleFunction(), casadi::OracleFunction::serialize_body(), and casadi::OracleFunction::set_temp().
meta_doc
const std::string casadi::AmplInterface::meta_doc static
Initial value:
=
      "\n"
"AMPL interface\n"
"\n"
"\n"
Definition at line 98 of file ampl_interface.hpp.
Referenced by casadi::casadi_register_nlpsol_ampl().
mi_
bool casadi::Nlpsol::mi_ inherited
Definition at line 105 of file nlpsol_impl.hpp.
Referenced by casadi::Nlpsol::init(), casadi::Nlpsol::Nlpsol(), casadi::Nlpsol::serialize_body(), and casadi::KnitroInterface::solve().
min_lam_
double casadi::Nlpsol::min_lam_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1nk
Definition at line 99 of file nlpsol_impl.hpp.
Referenced by casadi::Nlpsol::get_forward(), casadi::Nlpsol::get_reverse(), casadi::Nlpsol::init(), casadi::Nlpsol::Nlpsol(), and casadi::Nlpsol::serialize_body().
monitor_
std::vector<std::string> casadi::OracleFunction::monitor_ protected inherited
Definition at line 91 of file oracle_function.hpp.
Referenced by casadi::OracleFunction::finalize(), casadi::OracleFunction::init(), casadi::OracleFunction::OracleFunction(), and casadi::OracleFunction::serialize_body().
n_in_
size_t casadi::FunctionInternal::n_in_ inherited
Definition at line 1203 of file function_internal.hpp.
Referenced by casadi::Rootfinder::ad_reverse(), casadi::MXFunction::ad_reverse(), casadi::FunctionInternal::all_scalar(), casadi::KinsolInterface::bjac(), casadi::FunctionInternal::call_forward(), casadi::FunctionInternal::call_gen(), casadi::FunctionInternal::call_reverse(), casadi::FunctionInternal::check_arg(), casadi::JitFunction::codegen_body(), casadi::Map::codegen_body(), casadi::OmpMap::codegen_body(), casadi::MapSum::codegen_body(), casadi::MXFunction::codegen_body(), casadi::Switch::codegen_body(), casadi::FastNewton::codegen_body(), casadi::FunctionInternal::codegen_meta(), casadi::FunctionInternal::convert_arg(), casadi::FunctionInternal::definition(), casadi::KinsolInterface::djac(), casadi::FunctionInternal::dm_in(), casadi::FunctionInternal::eval(), casadi::OmpMap::eval(), casadi::MXFunction::eval(), casadi::Switch::eval(), casadi::Map::eval_gen(), casadi::MapSum::eval_gen(), casadi::MXFunction::eval_mx(), casadi::Switch::eval_sx(), casadi::CallbackInternal::finalize(), casadi::FunctionInternal::forward(), casadi::KinsolInterface::func(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::fwd_seed(), casadi::FunctionInternal::generate_in(), casadi::GenericExternal::get_jac_sparsity(), casadi::GenericExternal::has_jac_sparsity(), casadi::FunctionInternal::init(), casadi::MXFunction::init(), casadi::Switch::init(), casadi::ImplicitToNlp::init(), casadi::FunctionInternal::jac_sparsity(), casadi::FunctionInternal::jacobian(), casadi::KinsolInterface::jtimes(), casadi::FunctionInternal::mapsum_mx(), casadi::FunctionInternal::matching_arg(), casadi::FunctionInternal::mx_in(), casadi::FunctionInternal::nnz_in(), casadi::FunctionInternal::numel_in(), casadi::FunctionInternal::nz_in(), casadi::FunctionInternal::print_dimensions(), casadi::FunctionInternal::print_in(), casadi::FunctionInternal::project_arg(), casadi::KinsolInterface::psetup(), casadi::FunctionInternal::reverse(), casadi::FunctionInternal::set_jac_sparsity(), casadi::Rootfinder::set_work(), casadi::QpToNlp::solve(), casadi::KinsolInterface::solve(), casadi::FastNewton::solve(), casadi::ImplicitToNlp::solve(), casadi::Newton::solve(), casadi::FunctionInternal::sp_forward(), casadi::Integrator::sp_forward(), casadi::MXFunction::sp_forward(), casadi::Rootfinder::sp_forward(), casadi::FunctionInternal::sp_reverse(), casadi::Integrator::sp_reverse(), casadi::Map::sp_reverse(), casadi::MapSum::sp_reverse(), casadi::MXFunction::sp_reverse(), casadi::Rootfinder::sp_reverse(), and casadi::FunctionInternal::sx_in().
n_out_
size_t casadi::FunctionInternal::n_out_ inherited
Definition at line 1203 of file function_internal.hpp.
Referenced by casadi::Rootfinder::ad_forward(), casadi::MXFunction::ad_forward(), casadi::Rootfinder::ad_reverse(), casadi::FunctionInternal::all_scalar(), casadi::KinsolInterface::bjac(), casadi::FunctionInternal::call(), casadi::FunctionInternal::call_forward(), casadi::FunctionInternal::call_gen(), casadi::FunctionInternal::call_reverse(), casadi::FunctionInternal::check_res(), casadi::JitFunction::codegen_body(), casadi::Map::codegen_body(), casadi::OmpMap::codegen_body(), casadi::MapSum::codegen_body(), casadi::MXFunction::codegen_body(), casadi::Switch::codegen_body(), casadi::FastNewton::codegen_body(), casadi::FunctionInternal::codegen_meta(), casadi::FunctionInternal::convert_res(), casadi::FunctionInternal::definition(), casadi::KinsolInterface::djac(), casadi::FunctionInternal::dm_out(), casadi::FunctionInternal::eval(), casadi::OmpMap::eval(), casadi::MXFunction::eval(), casadi::Switch::eval(), casadi::FunctionInternal::eval_gen(), casadi::Map::eval_gen(), casadi::MapSum::eval_gen(), casadi::Switch::eval_sx(), casadi::CallbackInternal::finalize(), casadi::FunctionInternal::forward(), casadi::KinsolInterface::func(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_out(), casadi::LinearInterpolantJac::get_jacobian(), casadi::FunctionInternal::init(), casadi::MapSum::init(), casadi::Nlpsol::init(), casadi::Switch::init(), casadi::FunctionInternal::jac_sparsity(), casadi::FunctionInternal::jacobian(), casadi::FunctionInternal::mapsum_mx(), casadi::FunctionInternal::matching_res(), casadi::FunctionInternal::mx_out(), casadi::FunctionInternal::nnz_out(), casadi::FunctionInternal::numel_out(), casadi::FunctionInternal::nz_out(), casadi::FunctionInternal::print_dimensions(), casadi::FunctionInternal::print_out(), casadi::KinsolInterface::psetup(), casadi::FunctionInternal::reverse(), casadi::FunctionInternal::set_jac_sparsity(), casadi::Rootfinder::set_work(), casadi::QpToNlp::solve(), casadi::KinsolInterface::solve(), casadi::FastNewton::solve(), casadi::ImplicitToNlp::solve(), casadi::Newton::solve(), casadi::FunctionInternal::sp_forward(), casadi::Integrator::sp_forward(), casadi::MXFunction::sp_forward(), casadi::Rootfinder::sp_forward(), casadi::FunctionInternal::sp_reverse(), casadi::Integrator::sp_reverse(), casadi::Map::sp_reverse(), casadi::MapSum::sp_reverse(), casadi::MXFunction::sp_reverse(), casadi::Rootfinder::sp_reverse(), and casadi::FunctionInternal::sx_out().
name_
std::string casadi::ProtoFunction::name_ inherited
Definition at line 234 of file function_internal.hpp.
Referenced by casadi::MXFunction::ad_forward(), casadi::MXFunction::ad_reverse(), casadi::Integrator::augmented_dae(), casadi::OracleFunction::calc_function(), casadi::FunctionInternal::call_forward(), casadi::FunctionInternal::call_reverse(), casadi::FunctionInternal::codegen_body(), casadi::External::codegen_body(), casadi::External::codegen_checkout(), casadi::External::codegen_declarations(), casadi::MXFunction::codegen_declarations(), casadi::External::codegen_decref(), casadi::External::codegen_incref(), casadi::FunctionInternal::codegen_meta(), casadi::FunctionInternal::codegen_name(), casadi::External::codegen_release(), casadi::FunctionInternal::codegen_sparsities(), casadi::ProtoFunction::construct(), casadi::OracleFunction::create_function(), casadi::FunctionInternal::definition(), casadi::FunctionInternal::eval(), casadi::MXFunction::eval(), casadi::FunctionInternal::eval_mx(), casadi::MXFunction::eval_mx(), casadi::FunctionInternal::finalize(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::FunctionInternal(), casadi::Integrator::get_forward(), casadi::Integrator::get_forward_dae(), casadi::Map::get_function(), casadi::MapSum::get_function(), casadi::OracleFunction::get_function(), casadi::GenericExternal::get_jac_sparsity(), casadi::FunctionInternal::get_n_in(), casadi::External::get_n_in(), casadi::FunctionInternal::get_n_out(), casadi::External::get_n_out(), casadi::FunctionInternal::get_name_in(), casadi::External::get_name_in(), casadi::FunctionInternal::get_name_out(), casadi::External::get_name_out(), casadi::FunctionInternal::get_partition(), casadi::Integrator::get_reverse(), casadi::FunctionInternal::get_sparsity_in(), casadi::GenericExternal::get_sparsity_in(), casadi::FunctionInternal::get_sparsity_out(), casadi::GenericExternal::get_sparsity_out(), casadi::External::has_forward(), casadi::GenericExternal::has_jac_sparsity(), casadi::External::has_jacobian(), casadi::External::has_reverse(), casadi::External::init(), casadi::FunctionInternal::init(), casadi::MXFunction::init(), casadi::CvodesInterface::init(), casadi::IdasInterface::init(), casadi::External::init_external(), casadi::GenericExternal::init_external(), casadi::FunctionInternal::jac_is_symm(), casadi::FunctionInternal::jacobian(), casadi::FunctionInternal::map(), casadi::OracleFunction::monitored(), casadi::MXFunction::print_arg(), casadi::FunctionInternal::print_in(), casadi::FunctionInternal::print_out(), casadi::MXFunction::print_res(), casadi::ProtoFunction::print_time(), casadi::ProtoFunction::ProtoFunction(), casadi::CvodesInterface::reset(), casadi::IdasInterface::reset(), casadi::IdasInterface::resetB(), casadi::FunctionInternal::reverse(), casadi::ProtoFunction::serialize_body(), casadi::GurobiInterface::solve(), casadi::SnoptInterface::solve(), casadi::Integrator::sp_forward(), casadi::Integrator::sp_reverse(), casadi::FunctionInternal::wrap(), and casadi::FunctionInternal::wrap_as_needed().
name_in_
std::vector<std::string> casadi::FunctionInternal::name_in_ inherited
Definition at line 1212 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::check_arg(), casadi::JitFunction::codegen_body(), casadi::FunctionInternal::codegen_meta(), casadi::FunctionInternal::convert_arg(), casadi::FunctionInternal::definition(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::fwd_seed(), casadi::FunctionInternal::init(), casadi::FunctionInternal::jacobian(), casadi::JitFunction::JitFunction(), casadi::FunctionInternal::mx_in(), casadi::FunctionInternal::print_dimensions(), casadi::FunctionInternal::print_in(), casadi::FunctionInternal::reverse(), casadi::FunctionInternal::serialize_body(), casadi::FunctionInternal::sx_in(), casadi::FunctionInternal::wrap(), casadi::FunctionInternal::wrap_as_needed(), and casadi::XFunction< DerivedType, MatType, NodeType >::XFunction().
name_out_
std::vector<std::string> casadi::FunctionInternal::name_out_ inherited
Definition at line 1212 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::check_res(), casadi::JitFunction::codegen_body(), casadi::FunctionInternal::codegen_meta(), casadi::FunctionInternal::convert_res(), casadi::FunctionInternal::definition(), casadi::FunctionInternal::eval_gen(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::init(), casadi::FunctionInternal::jacobian(), casadi::JitFunction::JitFunction(), casadi::FunctionInternal::mx_out(), casadi::FunctionInternal::print_dimensions(), casadi::FunctionInternal::print_out(), casadi::FunctionInternal::reverse(), casadi::FunctionInternal::serialize_body(), casadi::FunctionInternal::sx_out(), casadi::FunctionInternal::wrap(), casadi::FunctionInternal::wrap_as_needed(), and casadi::XFunction< DerivedType, MatType, NodeType >::XFunction().
never_inline_
bool casadi::FunctionInternal::never_inline_ inherited
Definition at line 1200 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::eval_mx(), casadi::MXFunction::eval_mx(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
ng_
casadi_int casadi::Nlpsol::ng_ inherited
Definition at line 69 of file nlpsol_impl.hpp.
Referenced by casadi::Blocksqp::acceptStep(), casadi::BonminUserClass::BonminUserClass(), casadi::Blocksqp::calcOptTol(), casadi::Feasiblesqpmethod::codegen_body(), casadi::Sqpmethod::codegen_body(), casadi::Feasiblesqpmethod::codegen_feasibility_iterations(), casadi::Sqpmethod::codegen_qp_ela_solve(), casadi::Sqpmethod::codegen_solve_elastic_mode(), casadi::Feasiblesqpmethod::codegen_step_update(), casadi::Nlpsol::eval(), casadi::Scpgen::eval_vec(), casadi::Blocksqp::evaluate(), casadi::Feasiblesqpmethod::feasibility_iterations(), casadi::Blocksqp::feasibilityRestorationPhase(), casadi::IpoptUserClass::finalize_metadata(), casadi::BonminInterface::finalize_solution(), casadi::IpoptInterface::finalize_solution(), casadi::BonminInterface::get_bounds_info(), casadi::BonminUserClass::get_bounds_info(), casadi::IpoptUserClass::get_bounds_info(), casadi::IpoptInterface::get_bounds_info(), casadi::Nlpsol::get_forward(), casadi::BonminInterface::get_nlp_info(), casadi::IpoptInterface::get_nlp_info(), casadi::Nlpsol::get_reverse(), casadi::BonminInterface::get_starting_point(), casadi::BonminUserClass::get_starting_point(), casadi::IpoptUserClass::get_starting_point(), casadi::IpoptInterface::get_starting_point(), casadi::Nlpsol::init(), init(), casadi::Blocksqp::init(), casadi::BonminInterface::init(), casadi::IpoptInterface::init(), casadi::KnitroInterface::init(), casadi::SnoptInterface::init(), casadi::Feasiblesqpmethod::init(), casadi::Qrsqp::init(), casadi::Scpgen::init(), casadi::Sqpmethod::init(), casadi::IpoptInterface::init_mem(), casadi::SnoptInterface::init_mem(), casadi::BonminInterface::intermediate_callback(), casadi::IpoptInterface::intermediate_callback(), casadi::IpoptUserClass::IpoptUserClass(), casadi::Blocksqp::kktErrorReduction(), casadi::Scpgen::line_search(), casadi::Blocksqp::lInfConstraintNorm(), casadi::Nlpsol::Nlpsol(), casadi::Nlpsol::nlpsol_codegen_body(), casadi::Scpgen::primalInfeasibility(), casadi::Blocksqp::reduceSOCStepsize(), casadi::Blocksqp::reset_sqp(), casadi::Blocksqp::secondOrderCorrection(), casadi::Nlpsol::serialize_body(), casadi::Blocksqp::set_work(), casadi::BonminInterface::set_work(), casadi::IpoptInterface::set_work(), casadi::KnitroInterface::set_work(), casadi::SnoptInterface::set_work(), casadi::WorhpInterface::set_work(), casadi::Qrsqp::set_work(), casadi::Scpgen::set_work(), solve(), casadi::Blocksqp::solve(), casadi::BonminInterface::solve(), casadi::IpoptInterface::solve(), casadi::KnitroInterface::solve(), casadi::SnoptInterface::solve(), casadi::WorhpInterface::solve(), casadi::Feasiblesqpmethod::solve(), casadi::Qrsqp::solve(), casadi::Scpgen::solve(), casadi::Sqpmethod::solve(), casadi::Sqpmethod::solve_ela_QP(), casadi::Sqpmethod::solve_elastic_mode(), casadi::Scpgen::solve_qp(), casadi::Blocksqp::solveQP(), casadi::Feasiblesqpmethod::step_update(), and casadi::Blocksqp::updateStepBounds().
nl_init_
std::stringstream casadi::AmplInterface::nl_init_
Definition at line 104 of file ampl_interface.hpp.
Referenced by init(), and solve().
no_nlp_grad_
bool casadi::Nlpsol::no_nlp_grad_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1nk
Definition at line 100 of file nlpsol_impl.hpp.
Referenced by casadi::Nlpsol::init(), casadi::Nlpsol::Nlpsol(), and casadi::Nlpsol::serialize_body().
np_
casadi_int casadi::Nlpsol::np_ inherited
Definition at line 72 of file nlpsol_impl.hpp.
Referenced by casadi::Feasiblesqpmethod::codegen_body(), casadi::Sqpmethod::codegen_body(), casadi::Nlpsol::eval(), casadi::Blocksqp::feasibilityRestorationPhase(), casadi::Nlpsol::init(), casadi::Scpgen::init(), casadi::Nlpsol::Nlpsol(), casadi::Nlpsol::nlpsol_codegen_body(), and casadi::Nlpsol::serialize_body().
nx_
casadi_int casadi::Nlpsol::nx_ inherited
Definition at line 66 of file nlpsol_impl.hpp.
Referenced by casadi::Blocksqp::acceptStep(), casadi::Feasiblesqpmethod::anderson_acc_init_memory(), casadi::Feasiblesqpmethod::anderson_acc_step_update(), casadi::Feasiblesqpmethod::anderson_acc_update_memory(), casadi::BonminUserClass::BonminUserClass(), casadi::Sqpmethod::calc_gamma_1(), casadi::Blocksqp::calcHessianUpdateLimitedMemory(), casadi::Blocksqp::calcLagrangeGradient(), casadi::Blocksqp::calcOptTol(), casadi::Nlpsol::callback(), casadi::Nlpsol::check_inputs(), casadi::Feasiblesqpmethod::codegen_body(), casadi::Sqpmethod::codegen_body(), casadi::Sqpmethod::codegen_calc_gamma_1(), casadi::Feasiblesqpmethod::codegen_eval_m_k(), casadi::Feasiblesqpmethod::codegen_feasibility_iterations(), casadi::Sqpmethod::codegen_qp_ela_solve(), casadi::Feasiblesqpmethod::codegen_qp_solve(), casadi::Sqpmethod::codegen_qp_solve(), casadi::Sqpmethod::codegen_solve_elastic_mode(), casadi::Feasiblesqpmethod::codegen_step_update(), casadi::Feasiblesqpmethod::codegen_tr_update(), casadi::Blocksqp::convertHessian(), casadi::Scpgen::dualInfeasibility(), casadi::Nlpsol::eval(), casadi::Scpgen::eval_exp(), casadi::Feasiblesqpmethod::eval_m_k(), casadi::Scpgen::eval_mat(), casadi::Scpgen::eval_res(), casadi::Scpgen::eval_vec(), casadi::Blocksqp::evaluate(), casadi::Feasiblesqpmethod::feasibility_iterations(), casadi::Blocksqp::feasibilityRestorationHeuristic(), casadi::Blocksqp::feasibilityRestorationPhase(), casadi::Blocksqp::filterLineSearch(), casadi::IpoptUserClass::finalize_metadata(), casadi::BonminInterface::finalize_solution(), casadi::IpoptInterface::finalize_solution(), casadi::Blocksqp::fullstep(), casadi::BonminInterface::get_bounds_info(), casadi::BonminUserClass::get_bounds_info(), casadi::IpoptUserClass::get_bounds_info(), casadi::IpoptInterface::get_bounds_info(), casadi::Nlpsol::get_forward(), casadi::BonminInterface::get_nlp_info(), casadi::IpoptInterface::get_nlp_info(), casadi::Nlpsol::get_reverse(), casadi::BonminInterface::get_starting_point(), casadi::BonminUserClass::get_starting_point(), casadi::IpoptUserClass::get_starting_point(), casadi::IpoptInterface::get_starting_point(), casadi::Nlpsol::init(), init(), casadi::Blocksqp::init(), casadi::BonminInterface::init(), casadi::IpoptInterface::init(), casadi::KnitroInterface::init(), casadi::SnoptInterface::init(), casadi::WorhpInterface::init(), casadi::Feasiblesqpmethod::init(), casadi::Qrsqp::init(), casadi::Scpgen::init(), casadi::Sqpmethod::init(), casadi::IpoptInterface::init_mem(), casadi::SnoptInterface::init_mem(), casadi::BonminInterface::intermediate_callback(), casadi::IpoptInterface::intermediate_callback(), casadi::IpoptUserClass::IpoptUserClass(), casadi::Blocksqp::kktErrorReduction(), casadi::Scpgen::line_search(), casadi::Blocksqp::lInfConstraintNorm(), casadi::Nlpsol::Nlpsol(), casadi::Nlpsol::nlpsol_codegen_body(), casadi::Scpgen::primalInfeasibility(), casadi::Blocksqp::printProgress(), casadi::Blocksqp::reduceSOCStepsize(), casadi::Scpgen::regularize(), casadi::Blocksqp::reset_sqp(), casadi::Blocksqp::resetHessian(), casadi::Blocksqp::secondOrderCorrection(), casadi::Nlpsol::serialize_body(), casadi::Blocksqp::set_work(), casadi::BonminInterface::set_work(), casadi::IpoptInterface::set_work(), casadi::KnitroInterface::set_work(), casadi::SnoptInterface::set_work(), casadi::WorhpInterface::set_work(), casadi::Qrsqp::set_work(), casadi::Scpgen::set_work(), solve(), casadi::Blocksqp::solve(), casadi::BonminInterface::solve(), casadi::IpoptInterface::solve(), casadi::KnitroInterface::solve(), casadi::SnoptInterface::solve(), casadi::WorhpInterface::solve(), casadi::Feasiblesqpmethod::solve(), casadi::Qrsqp::solve(), casadi::Scpgen::solve(), casadi::Sqpmethod::solve(), casadi::Sqpmethod::solve_ela_QP(), casadi::Sqpmethod::solve_elastic_mode(), casadi::Feasiblesqpmethod::solve_LP(), casadi::Feasiblesqpmethod::solve_QP(), casadi::Qrsqp::solve_QP(), casadi::Scpgen::solve_qp(), casadi::Sqpmethod::solve_QP(), casadi::Blocksqp::solveQP(), casadi::Feasiblesqpmethod::step_update(), casadi::Feasiblesqpmethod::tr_update(), casadi::Blocksqp::updateDeltaGamma(), casadi::Blocksqp::updateStepBounds(), and casadi::SnoptInterface::userfun().
options_
const Options casadi::AmplInterface::options_ static
Initial value:
= {{&Nlpsol::options_},
     {{"solver",
       {OT_STRING,
        "AMPL solver binary"}}
     }
  }
Definition at line 74 of file ampl_interface.hpp.
Referenced by casadi::casadi_register_nlpsol_ampl().
oracle_
Function casadi::OracleFunction::oracle_ protected inherited
Definition at line 67 of file oracle_function.hpp.
Referenced by casadi::Rootfinder::ad_forward(), casadi::Rootfinder::ad_reverse(), casadi::Integrator::augmented_dae(), casadi::OracleFunction::create_function(), casadi::Nlpsol::disp_more(), casadi::OracleFunction::expand(), casadi::KinsolInterface::func(), casadi::OracleFunction::generate_dependencies(), casadi::Integrator::get_forward_dae(), casadi::KinsolInterface::get_jtimes(), casadi::Nlpsol::get_sparsity_in(), casadi::Nlpsol::get_sparsity_out(), casadi::Integrator::init(), casadi::FixedStepIntegrator::init(), casadi::Nlpsol::init(), casadi::OracleFunction::init(), casadi::Rootfinder::init(), casadi::Blocksqp::init(), casadi::BonminInterface::init(), casadi::IpoptInterface::init(), casadi::KnitroInterface::init(), casadi::FastNewton::init(), casadi::ImplicitToNlp::init(), casadi::Newton::init(), casadi::Nlpsol::kkt(), casadi::OracleFunction::OracleFunction(), casadi::OracleFunction::serialize_body(), casadi::ImplicitToNlp::set_work(), casadi::KinsolInterface::solve(), casadi::ImplicitToNlp::solve(), casadi::Rootfinder::sp_forward(), and casadi::Rootfinder::sp_reverse().
p_nlp_
casadi_nlpsol_prob<double> casadi::Nlpsol::p_nlp_ inherited
Definition at line 63 of file nlpsol_impl.hpp.
Referenced by casadi::Nlpsol::init(), and casadi::Nlpsol::set_work().
print_in_
bool casadi::FunctionInternal::print_in_ inherited
Definition at line 1314 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::change_option(), casadi::FunctionInternal::eval_gen(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
print_out_
bool casadi::FunctionInternal::print_out_ inherited
Definition at line 1315 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::change_option(), casadi::FunctionInternal::eval_gen(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
print_time_
bool casadi::ProtoFunction::print_time_ inherited
Definition at line 240 of file function_internal.hpp.
Referenced by casadi::FixedStepIntegrator::create_advanced(), casadi::ProtoFunction::generate_options(), casadi::ProtoFunction::init(), casadi::FunctionInternal::init(), casadi::Nlpsol::Nlpsol(), casadi::ProtoFunction::print_time(), casadi::ProtoFunction::ProtoFunction(), and casadi::ProtoFunction::serialize_body().
record_time_
bool casadi::ProtoFunction::record_time_ inherited
Definition at line 243 of file function_internal.hpp.
Referenced by casadi::ProtoFunction::generate_options(), casadi::ProtoFunction::init(), casadi::FunctionInternal::init(), casadi::ProtoFunction::init_mem(), casadi::LinsolInternal::init_mem(), casadi::ProtoFunction::ProtoFunction(), and casadi::ProtoFunction::serialize_body().
regularity_check_
bool casadi::ProtoFunction::regularity_check_ inherited
Definition at line 246 of file function_internal.hpp.
Referenced by casadi::OracleFunction::calc_function(), casadi::ProtoFunction::change_option(), casadi::FunctionInternal::eval_gen(), casadi::FunctionInternal::FunctionInternal(), casadi::ProtoFunction::generate_options(), casadi::ProtoFunction::init(), casadi::ProtoFunction::ProtoFunction(), and casadi::ProtoFunction::serialize_body().
release_
casadi_release_t casadi::FunctionInternal::release_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_nm
Definition at line 1254 of file function_internal.hpp.
Referenced by casadi::GenericExternal::any_symbol_found(), casadi::External::codegen_declarations(), casadi::External::codegen_release(), casadi::FunctionInternal::eval_gen(), casadi::FunctionInternal::finalize(), casadi::FunctionInternal::FunctionInternal(), casadi::GenericExternal::init_external(), and casadi::FunctionBuffer::~FunctionBuffer().
reverse_options_
Dict casadi::FunctionInternal::reverse_options_ inherited
Definition at line 1330 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), casadi::FunctionInternal::reverse(), and casadi::FunctionInternal::serialize_body().
sens_linsol_
std::string casadi::Nlpsol::sens_linsol_ inherited
Definition at line 81 of file nlpsol_impl.hpp.
Referenced by casadi::Nlpsol::get_forward(), casadi::Nlpsol::get_reverse(), casadi::Nlpsol::init(), casadi::Nlpsol::Nlpsol(), and casadi::Nlpsol::serialize_body().
sens_linsol_options_
Dict casadi::Nlpsol::sens_linsol_options_ inherited
Definition at line 82 of file nlpsol_impl.hpp.
Referenced by casadi::Nlpsol::get_forward(), casadi::Nlpsol::get_reverse(), casadi::Nlpsol::init(), casadi::Nlpsol::Nlpsol(), and casadi::Nlpsol::serialize_body().
show_eval_warnings_
bool casadi::OracleFunction::show_eval_warnings_ protected inherited
Definition at line 74 of file oracle_function.hpp.
Referenced by casadi::OracleFunction::calc_function(), casadi::OracleFunction::init(), casadi::OracleFunction::OracleFunction(), and casadi::OracleFunction::serialize_body().
solver_
std::string casadi::AmplInterface::solver_
Definition at line 101 of file ampl_interface.hpp.
Referenced by init(), and solve().
solvers_
std::map< std::string, Nlpsol::Plugin > casadi::Nlpsol::solvers_ static inherited
Definition at line 267 of file nlpsol_impl.hpp.
sparsity_in_
std::vector<Sparsity> casadi::FunctionInternal::sparsity_in_ inherited
Definition at line 1209 of file function_internal.hpp.
Referenced by casadi::CodeGenerator::add(), casadi::FunctionInternal::all_scalar(), casadi::Switch::codegen_body(), casadi::FunctionInternal::codegen_meta(), casadi::FunctionInternal::codegen_sparsities(), casadi::FunctionInternal::definition(), casadi::FunctionInternal::eval(), casadi::Switch::eval(), casadi::Switch::eval_sx(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::init(), casadi::Switch::init(), casadi::ImplicitToNlp::init(), casadi::JitFunction::JitFunction(), casadi::FunctionInternal::mapsum_mx(), casadi::FunctionInternal::print_dimensions(), casadi::FunctionInternal::print_in(), casadi::FunctionInternal::serialize_body(), and casadi::HpmpcInterface::solve().
sparsity_out_
std::vector<Sparsity> casadi::FunctionInternal::sparsity_out_ inherited
Definition at line 1209 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::all_scalar(), casadi::Switch::codegen_body(), casadi::FunctionInternal::codegen_meta(), casadi::FunctionInternal::codegen_sparsities(), casadi::FunctionInternal::definition(), casadi::FunctionInternal::eval(), casadi::Switch::eval(), casadi::Switch::eval_sx(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::init(), casadi::Nlpsol::init(), casadi::Switch::init(), casadi::JitFunction::JitFunction(), casadi::FunctionInternal::print_dimensions(), casadi::FunctionInternal::print_out(), and casadi::FunctionInternal::serialize_body().
specific_options_
Dict casadi::OracleFunction::specific_options_ protected inherited
Definition at line 71 of file oracle_function.hpp.
Referenced by casadi::OracleFunction::create_function(), casadi::OracleFunction::finalize(), casadi::OracleFunction::init(), casadi::OracleFunction::OracleFunction(), and casadi::OracleFunction::serialize_body().
stats_
Dict casadi::FunctionInternal::stats_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_nn
Definition at line 1259 of file function_internal.hpp.
stride_arg_
size_t casadi::OracleFunction::stride_arg_ protected inherited
Definition at line 94 of file oracle_function.hpp.
Referenced by casadi::OracleFunction::finalize(), casadi::OracleFunction::init(), casadi::OracleFunction::OracleFunction(), casadi::OracleFunction::serialize_body(), and casadi::OracleFunction::set_temp().
stride_iw_
size_t casadi::OracleFunction::stride_iw_ protected inherited
Definition at line 94 of file oracle_function.hpp.
Referenced by casadi::OracleFunction::finalize(), casadi::OracleFunction::init(), casadi::OracleFunction::OracleFunction(), casadi::OracleFunction::serialize_body(), and casadi::OracleFunction::set_temp().
stride_res_
size_t casadi::OracleFunction::stride_res_ protected inherited
Definition at line 94 of file oracle_function.hpp.
Referenced by casadi::OracleFunction::finalize(), casadi::OracleFunction::init(), casadi::OracleFunction::OracleFunction(), casadi::OracleFunction::serialize_body(), and casadi::OracleFunction::set_temp().
stride_w_
size_t casadi::OracleFunction::stride_w_ protected inherited
Definition at line 94 of file oracle_function.hpp.
Referenced by casadi::OracleFunction::finalize(), casadi::OracleFunction::init(), casadi::OracleFunction::OracleFunction(), casadi::OracleFunction::serialize_body(), and casadi::OracleFunction::set_temp().
user_data_
void* casadi::FunctionInternal::user_data_ inherited
Definition at line 1281 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), and casadi::FunctionInternal::init().
verbose_
bool casadi::ProtoFunction::verbose_ inherited
Definition at line 237 of file function_internal.hpp.
Referenced by casadi::MXFunction::ad_forward(), casadi::MXFunction::ad_reverse(), casadi::ProtoFunction::change_option(), casadi::BSplineInterpolant::construct_graph(), casadi::OracleFunction::create_function(), casadi::Integrator::eval(), casadi::MXFunction::eval(), casadi::MXFunction::eval_mx(), casadi::FunctionInternal::finalize(), casadi::KinsolInterface::func(), casadi::ProtoFunction::generate_options(), casadi::Integrator::get_forward(), casadi::Integrator::get_forward_dae(), casadi::FunctionInternal::get_jac_sparsity_gen(), casadi::FunctionInternal::get_jac_sparsity_hierarchical(), casadi::FunctionInternal::get_jac_sparsity_hierarchical_symm(), casadi::FunctionInternal::get_partition(), casadi::Integrator::get_reverse(), casadi::ProtoFunction::init(), casadi::FiniteDiff::init(), casadi::FunctionInternal::init(), casadi::MXFunction::init(), casadi::Blocksqp::init(), casadi::HpipmInterface::init(), casadi::HpmpcInterface::init(), casadi::IpoptInterface::init(), casadi::CvodesInterface::init(), casadi::IdasInterface::init(), casadi::Feasiblesqpmethod::init(), casadi::Scpgen::init(), casadi::Sqpmethod::init(), casadi::IpoptInterface::init_mem(), casadi::IdasInterface::init_mem(), casadi::BonminInterface::intermediate_callback(), casadi::OracleFunction::jit_dependencies(), casadi::CsparseInterface::nfact(), casadi::LapackLu::nfact(), casadi::LapackQr::nfact(), casadi::LinsolQr::nfact(), casadi::ProtoFunction::ProtoFunction(), casadi::CvodesInterface::reset(), casadi::IdasInterface::reset(), casadi::IdasInterface::resetB(), casadi::ProtoFunction::serialize_body(), casadi::CbcInterface::solve(), casadi::ClpInterface::solve(), casadi::CplexInterface::solve(), casadi::GurobiInterface::solve(), casadi::QpoasesInterface::solve(), casadi::Ipqp::solve(), casadi::Qrqp::solve(), solve(), casadi::SnoptInterface::solve(), casadi::KinsolInterface::solve(), casadi::WorhpInterface::solve(), casadi::Newton::solve(), casadi::Qrsqp::solve(), casadi::Scpgen::solve(), casadi::Sqpmethod::solve(), casadi::Sqpmethod::solve_ela_QP(), casadi::Feasiblesqpmethod::solve_LP(), casadi::Feasiblesqpmethod::solve_QP(), casadi::Qrsqp::solve_QP(), casadi::Sqpmethod::solve_QP(), casadi::Integrator::sp_forward(), and casadi::Integrator::sp_reverse().
warn_initial_bounds_
bool casadi::Nlpsol::warn_initial_bounds_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1nk
Definition at line 94 of file nlpsol_impl.hpp.
Referenced by casadi::Nlpsol::check_inputs(), casadi::Nlpsol::init(), casadi::Nlpsol::Nlpsol(), and casadi::Nlpsol::serialize_body().
The documentation for this class was generated from the following files:
ampl_interface.hpp
ampl_interface.cpp
ampl_interface_meta.cpp