CasADi: casadi::SharedObject Class Reference
casadi::SharedObject Class Reference
SharedObject implements a reference counting framework similar for efficient and.
#include <shared_object.hpp>
Detailed Description
easily-maintained memory management.
To use the class, both the SharedObject class (the public class), and the SharedObjectInternal class (the internal class) must be inherited from. It can be done in two different files and together with memory management, this approach provides a clear distinction of which methods of the class are to be considered "public", i.e. methods for public use that can be considered to remain over time with small changes, and the internal memory.
When interfacing a software, which typically includes including some header file, this is best done only in the file where the internal class is defined, to avoid polluting the global namespace and other side effects.
The default constructor always means creating a null pointer to an internal class only. To allocate an internal class (this works only when the internal class isn't abstract), use the constructor with arguments.
The copy constructor and the assignment operator perform shallow copies only, to make a deep copy you must use the clone method explicitly. This will give a shared pointer instance.
In an inheritance hierarchy, you can cast down automatically, e.g. (SXFunction is a child class of Function): SXFunction derived(...); Function base = derived;
To cast up, use the shared_cast template function, which works analogously to dynamic_cast, static_cast, const_cast etc, e.g.: SXFunction derived(...); Function base = derived; SXFunction derived_from_base = shared_cast<SXFunction>(base);
A failed shared_cast will result in a null pointer (cf. dynamic_cast)
Author
Joel Andersson
Date
2010
Extra doc: https://github.com/casadi/casadi/wiki/L_as
Definition at line 84 of file shared_object.hpp.
Public Member Functions
SharedObject ()
Default constructor.
SharedObject (const SharedObject &ref)
Copy constructor (shallow copy)
~SharedObject ()
Destructor.
SharedObject & operator= (const SharedObject &ref)
Assignment operator.
void own (SharedObjectInternal *node)
void assign (SharedObjectInternal *node)
Assign the node to a node class pointer without reference counting.
SharedObjectInternal * get () const
Get a const pointer to the node.
casadi_int getCount () const
Get the reference count.
void swap (SharedObject &other)
Swap content with another instance.
SharedObjectInternal * operator-> () const
Access a member function or object.
std::string class_name () const
Get class name.
void disp (std::ostream &stream, bool more=false) const
Print a description of the object.
std::string get_str (bool more=false) const
Get string representation.
void print_ptr (std::ostream &stream=casadi::uout()) const
bool is_null () const
Is a null pointer?
casadi_int __hash__ () const
Returns a number that is unique for a given Node.
WeakRef * weak ()
Get a weak reference to the object.
Protected Member Functions
void count_up ()
void count_down ()
Friends
template<class B >
B shared_cast (SharedObject &A)
Typecast a shared object to a base class to a shared object to a derived class,.
template<class B >
const B shared_cast (const SharedObject &A)
Typecast a shared object to a base class to a shared object to a derived class,.
Constructor & Destructor Documentation
SharedObject() [1/2]
casadi::SharedObject::SharedObject ()
Definition at line 33 of file shared_object.cpp.
{
     node = nullptr;
   }
SharedObject() [2/2]
casadi::SharedObject::SharedObject (const SharedObject & ref)
Definition at line 37 of file shared_object.cpp.
{
     node = ref.node;
     count_up();
   }
References count_up().
~SharedObject()
casadi::SharedObject::~SharedObject ()
Definition at line 42 of file shared_object.cpp.
{
     count_down();
   }
References count_down().
Member Function Documentation
__hash__()
casadi_int casadi::SharedObject::__hash__ () const
If the Object does not point to any node, "0" is returned.
Extra doc: https://github.com/casadi/casadi/wiki/L_av
Definition at line 129 of file shared_object.cpp.
{
     return reinterpret_cast<casadi_int>(get());
   }
References get().
assign()
void casadi::SharedObject::assign (SharedObjectInternal * node)
improper use will cause memory leaks!
Extra doc: https://github.com/casadi/casadi/wiki/L_at
Definition at line 52 of file shared_object.cpp.
{
     node = node_;
   }
Referenced by casadi::GenericType::to_double_vector_vector().
class_name()
std::string casadi::SharedObject::class_name () const
Extra doc: https://github.com/casadi/casadi/wiki/L_au
Definition at line 99 of file shared_object.cpp.
{
     return (*this)->class_name();
   }
Referenced by casadi::MXFunction::export_code_body().
count_down()
void casadi::SharedObject::count_down () protected
Definition at line 84 of file shared_object.cpp.
{
 #ifdef WITH_EXTRA_CHECKS
     casadi_assert_dev(Function::call_depth_==0);
 #endif // WITH_EXTRA_CHECKS
     if (node && --node->count == 0) {
       delete node;
       node = nullptr;
     }
   }
Referenced by operator=(), own(), and ~SharedObject().
count_up()
void casadi::SharedObject::count_up () protected
Definition at line 77 of file shared_object.cpp.
{
 #ifdef WITH_EXTRA_CHECKS
     casadi_assert_dev(Function::call_depth_==0);
 #endif // WITH_EXTRA_CHECKS
     if (node) node->count++;
   }
Referenced by operator=(), own(), and SharedObject().
disp()
void casadi::SharedObject::disp (std::ostream & stream, bool more = false) const
Definition at line 103 of file shared_object.cpp.
{
     if (is_null()) {
       stream << "NULL";
     } else {
       (*this)->disp(stream, more);
     }
   }
References is_null().
Referenced by casadi::Nlpsol::disp_more(), and casadi::CsparseInterface::nfact().
get()
SharedObjectInternal * casadi::SharedObject::get () const
Definition at line 69 of file shared_object.cpp.
{
     return node;
   }
Referenced by __hash__(), casadi::GenericType::as_bool(), casadi::GenericType::as_bool_vector(), casadi::GenericType::as_dict(), casadi::GenericType::as_double(), casadi::GenericType::as_double_vector(), casadi::GenericType::as_double_vector_vector(), casadi::GenericType::as_function(), casadi::GenericType::as_function_vector(), casadi::GenericType::as_int(), casadi::GenericType::as_int_vector(), casadi::GenericType::as_int_vector_vector(), casadi::GenericType::as_string(), casadi::GenericType::as_string_vector(), casadi::GenericType::as_void_pointer(), casadi::Fmu::get(), casadi::Function::get(), casadi::MX::get(), casadi::Sparsity::get(), casadi::DaeBuilder::get(), casadi::GenericType::getType(), and casadi::GenericType::serialize().
get_str()
std::string casadi::SharedObject::get_str (bool more = false) const inline
Definition at line 138 of file shared_object.hpp.
{
       std::stringstream ss;
       disp(ss, more);
       return ss.str();
     }
getCount()
casadi_int casadi::SharedObject::getCount () const
Definition at line 121 of file shared_object.cpp.
{
     return (*this)->getCount();
   }
Referenced by casadi::MXNode::~MXNode().
is_null()
bool casadi::SharedObject::is_null () const
Definition at line 73 of file shared_object.cpp.
{
     return node==nullptr;
   }
Referenced by casadi::FunctionInternal::add_embedded(), casadi::WeakRef::alive(), casadi::FunctionInternal::alloc(), casadi::Nlpsol::callback(), casadi::DaeBuilderInternal::clear_cache(), casadi::Switch::codegen_body(), casadi::Conic::Conic(), casadi::conic_debug(), casadi::Callback::construct(), casadi::Function::deserialize(), disp(), casadi::FunctionInternal::finalize(), casadi::Switch::find(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::get_n_in(), casadi::Switch::get_n_in(), casadi::FunctionInternal::get_n_out(), casadi::Switch::get_n_out(), casadi::FunctionInternal::get_name_in(), casadi::FunctionInternal::get_name_out(), casadi::FunctionInternal::get_partition(), casadi::FunctionInternal::get_sparsity_in(), casadi::Switch::get_sparsity_in(), casadi::FunctionInternal::get_sparsity_out(), casadi::Switch::get_sparsity_out(), casadi::MXFunction::get_stats(), casadi::GenericType::getType(), casadi::Sparsity::info(), casadi::Nlpsol::init(), casadi::Rootfinder::init(), casadi::Switch::init(), casadi::SnoptInterface::init(), casadi::SundialsInterface::init(), casadi::FastNewton::init(), casadi::Newton::init(), casadi::Scpgen::init(), casadi::BonminInterface::intermediate_callback(), casadi::IpoptInterface::intermediate_callback(), casadi::XFunction< DerivedType, MatType, NodeType >::jac(), casadi::FunctionInternal::jac_is_symm(), casadi::FunctionInternal::jac_sparsity(), casadi::OracleFunction::jit_dependencies(), casadi::SparsityInternal::maxtrans(), casadi::Fmu::name(), casadi::Function::name(), casadi::Function::operator->(), operator->(), casadi::Function::operator==(), casadi::DaeBuilderInternal::oracle(), casadi::Function::serialize(), casadi::Sparsity::serialize(), casadi::SnoptInterface::set_work(), casadi::OptiNode::solve(), casadi::KnitroInterface::solve(), casadi::WorhpInterface::solve(), casadi::FunctionInternal::sp_forward_block(), casadi::FunctionInternal::sp_reverse(), casadi::Sparsity::uni_coloring(), and casadi::Callback::~Callback().
operator->()
SharedObjectInternal * casadi::SharedObject::operator-> () const
Definition at line 94 of file shared_object.cpp.
{
     casadi_assert_dev(!is_null());
     return node;
   }
References is_null().
Referenced by casadi::DaeBuilder::operator->(), casadi::Fmu::operator->(), casadi::Importer::operator->(), casadi::Linsol::operator->(), casadi::MX::operator->(), casadi::Opti::operator->(), casadi::WeakRef::operator->(), casadi::Sparsity::operator->(), and casadi::XmlFile::operator->().
operator=()
SharedObject & casadi::SharedObject::operator= (const SharedObject & ref)
Definition at line 56 of file shared_object.cpp.
{
     // quick return if the old and new pointers point to the same object
     if (node == ref.node) return *this;
     // decrease the counter and delete if this was the last pointer
     count_down();
     // save the new pointer
     node = ref.node;
     count_up();
     return *this;
   }
References count_down(), and count_up().
Referenced by casadi::Function::construct().
own()
void casadi::SharedObject::own (SharedObjectInternal * node)
Assign the node to a node class pointer (or null)
Definition at line 46 of file shared_object.cpp.
{
     count_down();
     node = node_;
     count_up();
   }
References count_down(), and count_up().
Referenced by casadi::Callback::construct(), casadi::Function::construct(), casadi::Function::create(), casadi::Importer::create(), casadi::Linsol::create(), casadi::GenericType::create(), casadi::Sparsity::create(), casadi::DaeBuilder::DaeBuilder(), casadi::FunctionInternal::deserialize(), casadi::Linsol::deserialize(), casadi::FmuFunction::factory(), casadi::Fmu::Fmu(), casadi::GenericType::GenericType(), casadi::FmuFunction::get_jacobian(), casadi::LinearInterpolant::get_jacobian(), casadi::FmuFunction::get_reverse(), casadi::Importer::Importer(), casadi::MXFunction::init(), casadi::Linsol::Linsol(), casadi::MX::MX(), casadi::Opti::Opti(), casadi::WeakRef::shared(), casadi::WeakRef::WeakRef(), and casadi::XmlFile::XmlFile().
print_ptr()
void casadi::SharedObject::print_ptr (std::ostream & stream = casadi::uout()) const
Print the pointer to the internal class
Definition at line 111 of file shared_object.cpp.
{
     stream << node;
   }
swap()
void casadi::SharedObject::swap (SharedObject & other)
Definition at line 115 of file shared_object.cpp.
{
     SharedObject temp = *this;
     *this = other;
     other = temp;
   }
weak()
WeakRef * casadi::SharedObject::weak ()
Extra doc: https://github.com/casadi/casadi/wiki/L_aw
Definition at line 125 of file shared_object.cpp.
{
     return (*this)->weak();
   }
References casadi::SharedObjectInternal::weak().
Referenced by casadi::WeakRef::WeakRef().
Friends And Related Function Documentation
shared_cast [1/2]
template<class B > const B shared_cast (const SharedObject & A) friend
cf. dynamic_cast (const)
Extra doc: https://github.com/casadi/casadi/wiki/L_b7
Definition at line 259 of file shared_object.hpp.
{
     SharedObject A_copy = A;
     return shared_cast<B>(A_copy);
   }
shared_cast [2/2]
template<class B > B shared_cast (SharedObject & A) friend
cf. dynamic_cast
Extra doc: https://github.com/casadi/casadi/wiki/L_b6
Get a pointer to the node
Create a return object
Quick return if not allowed
Assign node of B and return
Definition at line 237 of file shared_object.hpp.
{
     SharedObjectInternal* ptr = A.get();
     B ret;
     if (!B::test_cast(ptr)) return ret;
     ret.own(ptr);
     return ret;
   }
The documentation for this class was generated from the following files:
shared_object.hpp
shared_object.cpp