CasADi: casadi::GenericMatrix< MatType > Class Template Reference
casadi::GenericMatrix< MatType > Class Template Reference
Matrix base class.
#include <generic_matrix.hpp>
Detailed Description
template<typename MatType>
class casadi::GenericMatrix< MatType >
This is a common base class for MX and Matrix<>, introducing a uniform syntax and implementing common functionality using the curiously recurring template pattern (CRTP) idiom.
The class is designed with the idea that "everything is a matrix", that is, also scalars and vectors.
This philosophy makes it easy to use and to interface in particularly with Python and Matlab/Octave.
The syntax tries to stay as close as possible to the ublas syntax when it comes to vector/matrix operations.
Index starts with 0.
Index vec happens as follows: (rr, cc) -> k = rr+cc*size1()
Vectors are column vectors.
The storage format is Compressed Column Storage (CCS), similar to that used for sparse matrices in Matlab,
but unlike this format, we do allow for elements to be structurally non-zero but numerically zero.
The sparsity pattern, which is reference counted and cached, can be accessed with Sparsity& sparsity()
Author
Joel Andersson
Date
2012
Extra doc: https://github.com/casadi/casadi/wiki/L_1am
Definition at line 75 of file generic_matrix.hpp.
Public Member Functions
casadi_int nnz () const
Get the number of (structural) non-zero elements.
casadi_int nnz_lower () const
Get the number of non-zeros in the lower triangular half.
casadi_int nnz_upper () const
Get the number of non-zeros in the upper triangular half.
casadi_int nnz_diag () const
Get get the number of non-zeros on the diagonal.
casadi_int numel () const
Get the number of elements.
casadi_int size1 () const
Get the first dimension (i.e. number of rows)
casadi_int rows () const
Get the number of rows, Octave-style syntax.
casadi_int size2 () const
Get the second dimension (i.e. number of columns)
casadi_int columns () const
Get the number of columns, Octave-style syntax.
std::string dim (bool with_nz=false) const
Get string representation of dimensions.
std::pair< casadi_int, casadi_int > size () const
Get the shape.
casadi_int size (casadi_int axis) const
Get the size along a particular dimensions.
bool is_empty (bool both=false) const
Check if the sparsity is empty, i.e. if one of the dimensions is zero.
bool is_dense () const
Check if the matrix expression is dense.
bool is_scalar (bool scalar_and_dense=false) const
Check if the matrix expression is scalar.
bool is_square () const
Check if the matrix expression is square.
bool is_vector () const
Check if the matrix is a row or column vector.
bool is_row () const
Check if the matrix is a row vector (i.e. size1()==1)
bool is_column () const
Check if the matrix is a column vector (i.e. size2()==1)
bool is_triu () const
Check if the matrix is upper triangular.
bool is_tril () const
Check if the matrix is lower triangular.
Sparsity sparsity () const
Get the sparsity pattern.
template<typename K >
const MatType nz (const K &k) const
Get vector nonzero or slice of nonzeros.
template<typename K >
NonZeros< MatType, K > nz (const K &k)
Access vector nonzero or slice of nonzeros.
template<typename RR >
const MatType operator() (const RR &rr) const
Get vector element or slice.
template<typename RR , typename CC >
const MatType operator() (const RR &rr, const CC &cc) const
Get Matrix element or slice.
template<typename RR >
SubIndex< MatType, RR > operator() (const RR &rr)
Access Matrix elements (one argument)
template<typename RR , typename CC >
SubMatrix< MatType, RR, CC > operator() (const RR &rr, const CC &cc)
Access Matrix elements (two arguments)
std::vector< casadi_int > get_row () const
Get the sparsity pattern. See the Sparsity class for details.
std::vector< casadi_int > get_colind () const
Get the sparsity pattern. See the Sparsity class for details.
const casadi_int * row () const
Get the sparsity pattern. See the Sparsity class for details.
const casadi_int * colind () const
Get the sparsity pattern. See the Sparsity class for details.
casadi_int row (casadi_int el) const
Get the sparsity pattern. See the Sparsity class for details.
casadi_int colind (casadi_int col) const
Get the sparsity pattern. See the Sparsity class for details.
Static Public Member Functions
static MatType logsumexp (const MatType &x)
static MatType interp1d (const std::vector< double > &x, const MatType &v, const std::vector< double > &xq, const std::string &mode, bool equidistant)
Functions called by friend functions defined here.
static casadi_int sprank (const MatType &x)
Functions called by friend functions defined here.
static casadi_int norm_0_mul (const MatType &x, const MatType &y)
Functions called by friend functions defined here.
static MatType tril (const MatType &x, bool includeDiagonal=true)
Functions called by friend functions defined here.
static MatType triu (const MatType &x, bool includeDiagonal=true)
Functions called by friend functions defined here.
static MatType sumsqr (const MatType &x)
Functions called by friend functions defined here.
static MatType linspace (const MatType &a, const MatType &b, casadi_int nsteps)
Functions called by friend functions defined here.
static MatType cross (const MatType &a, const MatType &b, casadi_int dim=-1)
Functions called by friend functions defined here.
static MatType skew (const MatType &a)
Functions called by friend functions defined here.
static MatType inv_skew (const MatType &a)
Functions called by friend functions defined here.
static MatType tril2symm (const MatType &x)
Functions called by friend functions defined here.
static MatType triu2symm (const MatType &x)
Functions called by friend functions defined here.
static MatType repsum (const MatType &x, casadi_int n, casadi_int m=1)
Functions called by friend functions defined here.
static MatType diff (const MatType &x, casadi_int n=1, casadi_int axis=-1)
Functions called by friend functions defined here.
static bool is_linear (const MatType &expr, const MatType &var)
Functions called by friend functions defined here.
static bool is_quadratic (const MatType &expr, const MatType &var)
Functions called by friend functions defined here.
static void quadratic_coeff (const MatType &expr, const MatType &var, MatType &A, MatType &b, MatType &c, bool check)
Functions called by friend functions defined here.
static void linear_coeff (const MatType &expr, const MatType &var, MatType &A, MatType &b, bool check)
Functions called by friend functions defined here.
static MatType jtimes (const MatType &ex, const MatType &arg, const MatType &v, bool tr=false, const Dict &opts=Dict())
static MatType gradient (const MatType &ex, const MatType &arg, const Dict &opts=Dict())
static MatType tangent (const MatType &ex, const MatType &arg, const Dict &opts=Dict())
static MatType linearize (const MatType &f, const MatType &x, const MatType &x0, const Dict &opts=Dict())
static MatType mpower (const MatType &x, const MatType &y)
static MatType soc (const MatType &x, const MatType &y)
Construct symbolic primitives
The "sym" function is intended to work in a similar way as "sym" used in the Symbolic Toolbox for Matlab but instead creating a CasADi symbolic primitive.
static MatType sym (const std::string &name, casadi_int nrow=1, casadi_int ncol=1)
Create an nrow-by-ncol symbolic primitive.
static MatType sym (const std::string &name, const std::pair< casadi_int, casadi_int > &rc)
Construct a symbolic primitive with given dimensions.
static MatType sym (const std::string &name, const Sparsity &sp)
Create symbolic primitive with a given sparsity pattern.
static std::vector< MatType > sym (const std::string &name, const Sparsity &sp, casadi_int p)
Create a vector of length p with with matrices.
static std::vector< MatType > sym (const std::string &name, casadi_int nrow, casadi_int ncol, casadi_int p)
Create a vector of length p with nrow-by-ncol symbolic primitives.
static std::vector< std::vector< MatType > > sym (const std::string &name, const Sparsity &sp, casadi_int p, casadi_int r)
Create a vector of length r of vectors of length p with.
static std::vector< std::vector< MatType > > sym (const std::string &name, casadi_int nrow, casadi_int ncol, casadi_int p, casadi_int r)
Create a vector of length r of vectors of length p.
static MatType zeros (casadi_int nrow=1, casadi_int ncol=1)
Create a dense matrix or a matrix with specified sparsity with all entries zero.
static MatType zeros (const Sparsity &sp)
Create a dense matrix or a matrix with specified sparsity with all entries zero.
static MatType zeros (const std::pair< casadi_int, casadi_int > &rc)
Create a dense matrix or a matrix with specified sparsity with all entries zero.
static MatType ones (casadi_int nrow=1, casadi_int ncol=1)
Create a dense matrix or a matrix with specified sparsity with all entries one.
static MatType ones (const Sparsity &sp)
Create a dense matrix or a matrix with specified sparsity with all entries one.
static MatType ones (const std::pair< casadi_int, casadi_int > &rc)
Create a dense matrix or a matrix with specified sparsity with all entries one.
Friends
MatType interp1d (const std::vector< double > &x, const MatType &v, const std::vector< double > &xq, const std::string &mode, bool equidistant=false)
Performs 1d linear interpolation.
MatType mpower (const MatType &x, const MatType &n)
Matrix power x^n.
MatType soc (const MatType &x, const MatType &y)
Construct second-order-convex.
MatType mrdivide (const MatType &x, const MatType &n)
Matrix divide (cf. slash '/' in MATLAB)
MatType mldivide (const MatType &x, const MatType &n)
Matrix divide (cf. backslash '\' in MATLAB)
std::vector< MatType > symvar (const MatType &x)
Get all symbols contained in the supplied expression.
MatType sumsqr (const MatType &x)
Calculate sum of squares: sum_ij X_ij^2.
MatType logsumexp (const MatType &x)
x -> log(sum_i exp(x_i))
MatType logsumexp (const MatType &x, const MatType &margin)
Scaled version of logsumexp.
MatType linspace (const MatType &a, const MatType &b, casadi_int nsteps)
Matlab's linspace command.
MatType cross (const MatType &a, const MatType &b, casadi_int dim=-1)
Matlab's cross command.
MatType skew (const MatType &a)
Generate a skew symmetric matrix from a 3-vector.
MatType inv_skew (const MatType &a)
Generate the 3-vector progenitor of a skew symmetric matrix.
MatType det (const MatType &A)
Matrix determinant (experimental)
MatType inv_minor (const MatType &A)
Matrix inverse (experimental)
MatType inv (const MatType &A)
Matrix inverse.
MatType inv (const MatType &A, const std::string &lsolver, const Dict &options=Dict())
Matrix inverse.
MatType trace (const MatType &x)
Matrix trace.
MatType tril2symm (const MatType &a)
Convert a lower triangular matrix to a symmetric one.
MatType triu2symm (const MatType &a)
Convert a upper triangular matrix to a symmetric one.
MatType norm_fro (const MatType &x)
Frobenius norm.
MatType norm_2 (const MatType &x)
2-norm
MatType norm_1 (const MatType &x)
1-norm
MatType norm_inf (const MatType &x)
Infinity-norm.
MatType diff (const MatType &x, casadi_int n=1, casadi_int axis=-1)
Returns difference (n-th order) along given axis (MATLAB convention)
MatType cumsum (const MatType &x, casadi_int axis=-1)
Returns cumulative sum along given axis (MATLAB convention)
MatType dot (const MatType &x, const MatType &y)
Inner product of two matrices.
MatType nullspace (const MatType &A)
Computes the nullspace of a matrix A.
MatType polyval (const MatType &p, const MatType &x)
Evaluate a polynomial with coefficients p in x.
MatType diag (const MatType &A)
Get the diagonal of a matrix or construct a diagonal.
MatType unite (const MatType &A, const MatType &B)
Unite two matrices no overlapping sparsity.
MatType densify (const MatType &x)
Make the matrix dense if not already.
MatType densify (const MatType &x, const MatType &val)
Make the matrix dense and assign nonzeros to a value.
MatType project (const MatType &A, const Sparsity &sp, bool intersect=false)
Create a new matrix with a given sparsity pattern but with the.
MatType if_else (const MatType &cond, const MatType &if_true, const MatType &if_false, bool short_circuit=false)
Branching on MX nodes.
MatType conditional (const MatType &ind, const std::vector< MatType > &x, const MatType &x_default, bool short_circuit=false)
Create a switch.
bool depends_on (const MatType &f, const MatType &arg)
Check if expression depends on the argument.
MatType substitute (const MatType &ex, const MatType &v, const MatType &vdef)
Substitute variable v with expression vdef in an expression ex.
std::vector< MatType > substitute (const std::vector< MatType > &ex, const std::vector< MatType > &v, const std::vector< MatType > &vdef)
Substitute variable var with expression expr in multiple expressions.
void substitute_inplace (const std::vector< MatType > &v, std::vector< MatType > &inout_vdef, std::vector< MatType > &inout_ex, bool reverse=false)
Inplace substitution with piggyback expressions.
MatType cse (const MatType &e)
Common subexpression elimination.
std::vector< MatType > cse (const std::vector< MatType > &e)
Common subexpression elimination.
MatType solve (const MatType &A, const MatType &b)
Solve a system of equations: A*x = b.
MatType solve (const MatType &A, const MatType &b, const std::string &lsolver, const Dict &dict=Dict())
Solve a system of equations: A*x = b.
MatType linearize (const MatType &f, const MatType &x, const MatType &x0, const Dict &opts=Dict())
Linearize an expression.
MatType pinv (const MatType &A)
Computes the Moore-Penrose pseudo-inverse.
MatType pinv (const MatType &A, const std::string &lsolver, const Dict &dict=Dict())
Computes the Moore-Penrose pseudo-inverse.
MatType expm_const (const MatType &A, const MatType &t)
Calculate Matrix exponential.
MatType expm (const MatType &A)
Calculate Matrix exponential.
MatType jacobian (const MatType &ex, const MatType &arg, const Dict &opts=Dict())
Calculate Jacobian.
MatType gradient (const MatType &ex, const MatType &arg, const Dict &opts=Dict())
Calculate the gradient of an expression.
MatType tangent (const MatType &ex, const MatType &arg, const Dict &opts=Dict())
Calculate the tangent of an expression.
MatType jtimes (const MatType &ex, const MatType &arg, const MatType &v, bool tr=false, const Dict &opts=Dict())
Calculate the Jacobian and multiply by a vector from the right.
std::vector< std::vector< MatType > > forward (const std::vector< MatType > &ex, const std::vector< MatType > &arg, const std::vector< std::vector< MatType > > &v, const Dict &opts=Dict())
Forward directional derivative.
std::vector< std::vector< MatType > > reverse (const std::vector< MatType > &ex, const std::vector< MatType > &arg, const std::vector< std::vector< MatType > > &v, const Dict &opts=Dict())
Reverse directional derivative.
std::vector< bool > which_depends (const MatType &expr, const MatType &var, casadi_int order, bool tr)
Find out which variables enter with some order.
Sparsity jacobian_sparsity (const MatType &f, const MatType &x)
Get the sparsity pattern of a jacobian.
bool is_linear (const MatType &expr, const MatType &var)
Is expr linear in var?
bool is_quadratic (const MatType &expr, const MatType &var)
Is expr quadratic in var?
void quadratic_coeff (const MatType &expr, const MatType &var, MatType &A, MatType &b, MatType &c, bool check=true)
Recognizes quadratic form in scalar expression.
void linear_coeff (const MatType &expr, const MatType &var, MatType &A, MatType &b, bool check=true)
Recognizes linear form in vector expression.
casadi_int n_nodes (const MatType &A)
MatType simplify (const MatType &x)
Simplify an expression.
std::string print_operator (const MatType &xb, const std::vector< std::string > &args)
Get a string representation for a binary MatType, using custom arguments.
void extract (std::vector< MatType > &ex, std::vector< MatType > &v, std::vector< MatType > &vdef, const Dict &opts=Dict())
Introduce intermediate variables for selected nodes in a graph.
void shared (std::vector< MatType > &ex, std::vector< MatType > &v, std::vector< MatType > &vdef, const std::string &v_prefix="v_", const std::string &v_suffix="")
Extract shared subexpressions from an set of expressions.
MatType repsum (const MatType &A, casadi_int n, casadi_int m=1)
Given a repeated matrix, computes the sum of repeated parts.
MatType einstein (const MatType &A, const MatType &B, const MatType &C, const std::vector< casadi_int > &dim_a, const std::vector< casadi_int > &dim_b, const std::vector< casadi_int > &dim_c, const std::vector< casadi_int > &a, const std::vector< casadi_int > &b, const std::vector< casadi_int > &c)
Compute any contraction of two dense tensors, using index/einstein notation.
MatType einstein (const MatType &A, const MatType &B, const std::vector< casadi_int > &dim_a, const std::vector< casadi_int > &dim_b, const std::vector< casadi_int > &dim_c, const std::vector< casadi_int > &a, const std::vector< casadi_int > &b, const std::vector< casadi_int > &c)
Compute any contraction of two dense tensors, using index/einstein notation.
MatType hessian (const MatType &ex, const MatType &arg, const Dict &opts=Dict())
Hessian and (optionally) gradient.
MatType hessian (const MatType &ex, const MatType &arg, MatType &output_g, const Dict &opts=Dict())
Hessian and (optionally) gradient.
MatType mmin (const MatType &x)
Smallest element in a matrix.
MatType mmax (const MatType &x)
Largest element in a matrix.
static MatType bilin (const MatType &A, const MatType &x, const MatType &y)
Calculate bilinear/quadratic form x^T A y.
MatType bilin (const MatType &A, const MatType &x, const MatType &y)
Calculate bilinear/quadratic form x^T A y.
MatType bilin (const MatType &A, const MatType &x)
Calculate bilinear/quadratic form x^T A y.
static MatType rank1 (const MatType &A, const MatType &alpha, const MatType &x, const MatType &y)
Make a rank-1 update to a matrix A.
MatType rank1 (const MatType &A, const MatType &alpha, const MatType &x, const MatType &y)
Make a rank-1 update to a matrix A.
Member Function Documentation
colind() [1/2]
template<typename MatType > const casadi_int* casadi::GenericMatrix< MatType >::colind () const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1b8
Definition at line 198 of file generic_matrix.hpp.
 { return sparsity().colind(); }
References casadi::Sparsity::colind(), and casadi::GenericMatrix< MatType >::sparsity().
Referenced by casadi::Matrix< Scalar >::densify(), casadi::SnoptInterface::init(), casadi::Conic::sdp_to_socp_init(), casadi::MX::set(), casadi::SnoptInterface::solve(), and casadi::SnoptInterface::userfun().
colind() [2/2]
template<typename MatType > casadi_int casadi::GenericMatrix< MatType >::colind (casadi_int col) const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1b8
Definition at line 201 of file generic_matrix.hpp.
 { return sparsity().colind(col); }
References casadi::Sparsity::colind(), and casadi::GenericMatrix< MatType >::sparsity().
columns()
template<typename MatType > casadi_int casadi::GenericMatrix< MatType >::columns () const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1av
Definition at line 124 of file generic_matrix.hpp.
 {return size2();}
References casadi::GenericMatrix< MatType >::size2().
cross()
template<typename MatType > MatType casadi::GenericMatrix< MatType >::cross (const MatType & a, const MatType & b, casadi_int dim = -1) static
Definition at line 1215 of file generic_matrix.hpp.
{
     casadi_assert(a.size1()==b.size1() && a.size2()==b.size2(),
       "cross(a, b): Inconsistent dimensions. Dimension of a ("
       + a.dim() + " ) must equal that of b (" + b.dim() + ").");
     casadi_assert(a.size1()==3 || a.size2()==3,
       "cross(a, b): One of the dimensions of a should have length 3, but got "
         + a.dim() + ".");
     casadi_assert(dim==-1 || dim==1 || dim==2,
       "cross(a, b, dim): Dim must be 1, 2 or -1 (automatic).");
     std::vector<MatType> ret(3);
     bool t = a.size1()==3;
     if (dim==1) t = true;
     if (dim==2) t = false;
     MatType a1 = t ? a(0, Slice()) : a(Slice(), 0);
     MatType a2 = t ? a(1, Slice()) : a(Slice(), 1);
     MatType a3 = t ? a(2, Slice()) : a(Slice(), 2);
     MatType b1 = t ? b(0, Slice()) : b(Slice(), 0);
     MatType b2 = t ? b(1, Slice()) : b(Slice(), 1);
     MatType b3 = t ? b(2, Slice()) : b(Slice(), 2);
     ret[0] = a2*b3-a3*b2;
     ret[1] = a3*b1-a1*b3;
     ret[2] = a1*b2-a2*b1;
     return t ? vertcat(ret) : horzcat(ret);
   }
diff()
template<typename MatType > MatType casadi::GenericMatrix< MatType >::diff (const MatType & x, casadi_int n = 1, casadi_int axis = -1) static
Definition at line 1567 of file generic_matrix.hpp.
{
     casadi_assert(axis==-1 || axis==0 || axis==1, "Axis argument invalid");
     casadi_assert(n>=1, "n argument invalid");
     MatType ret = x;
     for (casadi_int i=0;i<n;++i) {
       // Matlab's special case
       if (axis==-1 && ret.is_scalar()) return MatType();
       casadi_int local_axis = (axis==-1) ? ret.is_row() : axis;
       if (local_axis==0) {
         if (ret.size1()<=1) {
           ret = MatType::zeros(0, ret.size2());
         } else {
           ret = ret(Slice(1, ret.size1()), Slice())-ret(Slice(0, ret.size1()-1), Slice());
         }
       } else {
         if (ret.size2()<=1) {
           ret = MatType::zeros(ret.size1(), 0);
         } else {
           ret = ret(Slice(), Slice(1, ret.size2()))-ret(Slice(), Slice(0, ret.size2()-1));
         }
       }
     }
     return ret;
   }
dim()
template<typename MatType > std::string casadi::GenericMatrix< MatType >::dim (bool with_nz = false) const
The representation is e.g. "4x5" or "4x5,10nz"
Extra doc: https://github.com/casadi/casadi/wiki/L_1aw
Definition at line 1164 of file generic_matrix.hpp.
{
     return sparsity().dim(with_nz);
   }
Referenced by casadi::Assertion::Assertion(), casadi::MX::attachAssert(), casadi::MX::binary(), casadi::BSplineParametric::create(), casadi::BSpline::create(), casadi::OptiNode::describe(), casadi::Determinant::Determinant(), casadi::MXNode::get_find(), casadi::MXNode::get_mac(), casadi::Inverse::Inverse(), casadi::MX::mac(), casadi::OptiNode::minimize(), casadi::Multiplication::Multiplication(), casadi::MX::project(), casadi::Linsol::solve(), casadi::Solve< Tr >::Solve(), and casadi::OptiNode::subject_to().
get_colind()
template<typename MatType > std::vector<casadi_int> casadi::GenericMatrix< MatType >::get_colind () const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1b8
Definition at line 195 of file generic_matrix.hpp.
 { return sparsity().get_colind(); }
References casadi::Sparsity::get_colind(), and casadi::GenericMatrix< MatType >::sparsity().
get_row()
template<typename MatType > std::vector<casadi_int> casadi::GenericMatrix< MatType >::get_row () const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1b8
Definition at line 194 of file generic_matrix.hpp.
 { return sparsity().get_row(); }
References casadi::Sparsity::get_row(), and casadi::GenericMatrix< MatType >::sparsity().
interp1d()
template<typename MatType > MatType casadi::GenericMatrix< MatType >::interp1d (const std::vector< double > & x, const MatType & v, const std::vector< double > & xq, const std::string & mode, bool equidistant) static
Definition at line 1252 of file generic_matrix.hpp.
{
     bool mode_floor = mode == "floor";
     bool mode_ceil = mode == "ceil";
     casadi_assert_dev(is_increasing(x));
     casadi_assert(x.size()==v.size1(),
       "interp1d(x, v, xq): dimensions mismatch. v expected to have " + str(x.size()) + " rows,"
       " but got " + str(v.size1()) + " instead.");
     // Need at least two elements
     casadi_assert(x.size()>=2, "interp1d(x, v, xq): x must be at least length 2.");
     // Vectors to compose a sparse matrix
     std::vector<double> val;
     std::vector<casadi_int> colind(1, 0);
     std::vector<casadi_int> row;
     // Number of nonzeros in to-be composed matrix
     casadi_int nnz = 0;
     for (casadi_int i=0;i<xq.size();++i) {
       // Obtain index corresponding to xq[i]
       double ind = index_interp1d(x, xq[i], equidistant);
       if (mode_floor) ind = floor(ind);
       if (mode_ceil) ind = ceil(ind);
       // Split into integer and fractional part
       double int_partd;
       double frac_part = modf(ind, &int_partd);
       casadi_int int_part = static_cast<casadi_int>(int_partd);
       if (frac_part==0) {
          // Create a single entry
          val.push_back(1);
          row.push_back(int_part);
          nnz+=1;
          colind.push_back(nnz);
        } else {
          // Create a double entry
          val.push_back(1-frac_part);
          val.push_back(frac_part);
          row.push_back(int_part);
          row.push_back(int_part+1);
          nnz+=2;
          colind.push_back(nnz);
        }
      }
      // Construct sparsity for composed matrix
      Sparsity sp(x.size(), xq.size() , colind, row);
      return MatType::mtimes(MatType(sp, val).T(), v);
   }
References casadi::index_interp1d(), casadi::is_increasing(), and casadi::str().
inv_skew()
template<typename MatType > MatType casadi::GenericMatrix< MatType >::inv_skew (const MatType & a) static
Definition at line 1322 of file generic_matrix.hpp.
{
     casadi_assert(a.size1()==3 && a.size2()==3,
       "inv_skew(a): Expecting 3-by-3 matrix, got " + a.dim() + ".");
     return 0.5*vertcat(std::vector<MatType>({a(2, 1)-a(1, 2), a(0, 2)-a(2, 0), a(1, 0)-a(0, 1)}));
   }
is_column()
template<typename MatType > bool casadi::GenericMatrix< MatType >::is_column () const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1b5
Definition at line 178 of file generic_matrix.hpp.
 { return sparsity().is_column();}
References casadi::Sparsity::is_column(), and casadi::GenericMatrix< MatType >::sparsity().
Referenced by casadi::Bilin::Bilin(), casadi::DaeBuilderInternal::der(), casadi::Find::Find(), casadi::Matrix< Scalar >::get(), casadi::MX::get(), casadi::MXNode::get_find(), casadi::MXNode::get_mac(), casadi::Matrix< Scalar >::get_nz(), casadi::MX::get_nz(), casadi::is_slice(), casadi::MX::MX(), casadi::MX::polyval(), casadi::MX::set(), and casadi::MX::vertsplit().
is_dense()
template<typename MatType > bool casadi::GenericMatrix< MatType >::is_dense () const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1b0
Definition at line 153 of file generic_matrix.hpp.
 { return sparsity().is_dense();}
References casadi::Sparsity::is_dense(), and casadi::GenericMatrix< MatType >::sparsity().
Referenced by casadi::MXNode::_get_binary(), casadi::GetNonzerosParam::create(), casadi::SetNonzerosParam< Add >::create(), casadi::Matrix< Scalar >::densify(), casadi::MX::densify(), casadi::Function::generate_in(), casadi::Function::generate_out(), casadi::Matrix< Scalar >::get(), casadi::MX::get(), casadi::MXNode::get_mac(), casadi::Matrix< double >::has_nz(), casadi::is_slice(), casadi::Low::Low(), casadi::MX::MX(), casadi::MX::polyval(), casadi::Matrix< Scalar >::set(), casadi::MX::set(), casadi::Matrix< Scalar >::set_nz(), and casadi::MX::set_nz().
is_empty()
template<typename MatType > bool casadi::GenericMatrix< MatType >::is_empty (bool both = false) const inline
(or optionally both dimensions)
Extra doc: https://github.com/casadi/casadi/wiki/L_1az
Definition at line 148 of file generic_matrix.hpp.
 { return sparsity().is_empty(both);}
References casadi::Sparsity::is_empty(), and casadi::GenericMatrix< MatType >::sparsity().
Referenced by casadi::Call::ad_reverse(), casadi::OptiNode::assert_empty(), casadi::OptiNode::bake(), casadi::MX::binary(), casadi::Call::common_cond(), casadi::DaeBuilderInternal::create(), casadi::DaeBuilderInternal::disp(), casadi::Function::generate_in(), casadi::Function::generate_out(), casadi::MXNode::get_nzadd(), casadi::AmplInterface::init(), casadi::BSpline::jac_cached(), casadi::BSplineParametric::jac_cached(), casadi::MXNode::join_primitives(), casadi::DaeBuilderInternal::new_variable(), casadi::MX::project(), casadi::Call::projectArg(), and casadi::OptiNode::subject_to().
is_linear()
template<typename MatType > bool casadi::GenericMatrix< MatType >::is_linear (const MatType & expr, const MatType & var) static
Definition at line 1536 of file generic_matrix.hpp.
{
     return !any(MatType::which_depends(expr, var, 2, true));
   }
References casadi::any().
is_quadratic()
template<typename MatType > bool casadi::GenericMatrix< MatType >::is_quadratic (const MatType & expr, const MatType & var) static
Definition at line 1541 of file generic_matrix.hpp.
{
     return is_linear(gradient(expr, var), var);
   }
is_row()
template<typename MatType > bool casadi::GenericMatrix< MatType >::is_row () const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1b4
Definition at line 173 of file generic_matrix.hpp.
 { return sparsity().is_row();}
References casadi::Sparsity::is_row(), and casadi::GenericMatrix< MatType >::sparsity().
Referenced by casadi::Matrix< Scalar >::cumsum(), casadi::MX::cumsum(), casadi::Matrix< Scalar >::get(), casadi::MX::get(), casadi::Matrix< Scalar >::get_nz(), and casadi::MX::get_nz().
is_scalar()
template<typename MatType > bool casadi::GenericMatrix< MatType >::is_scalar (bool scalar_and_dense = false) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1b1
Definition at line 1169 of file generic_matrix.hpp.
{
     return sparsity().is_scalar(scalar_and_dense);
   }
Referenced by casadi::BinaryMX< ScX, ScY >::ad_reverse(), casadi::Assertion::Assertion(), casadi::MX::attachAssert(), casadi::MX::binary(), casadi::OptiNode::canon_expr(), casadi::ConstantMX::create(), casadi::Matrix< Scalar >::densify(), casadi::MX::densify(), casadi::Matrix< double >::einstein(), casadi::MXFunction::export_code_body(), casadi::Matrix< Scalar >::get(), casadi::MXNode::get_binary(), casadi::Matrix< Scalar >::get_nz(), casadi::Matrix< double >::has_nz(), casadi::is_slice(), casadi::MX::mac(), casadi::OptiNode::minimize(), casadi::MX::mldivide(), casadi::MX::mrdivide(), casadi::MX::mtimes(), casadi::MX::MX(), casadi::Call::projectArg(), casadi::Matrix< Scalar >::set(), casadi::MX::set(), casadi::Matrix< Scalar >::set_nz(), casadi::MX::set_nz(), and casadi::to_slice().
is_square()
template<typename MatType > bool casadi::GenericMatrix< MatType >::is_square () const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1b2
Definition at line 163 of file generic_matrix.hpp.
 { return sparsity().is_square();}
References casadi::Sparsity::is_square(), and casadi::GenericMatrix< MatType >::sparsity().
Referenced by casadi::Determinant::Determinant(), and casadi::MX::trace().
is_tril()
template<typename MatType > bool casadi::GenericMatrix< MatType >::is_tril () const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1b7
Definition at line 188 of file generic_matrix.hpp.
 { return sparsity().is_tril();}
References casadi::Sparsity::is_tril(), and casadi::GenericMatrix< MatType >::sparsity().
Referenced by casadi::MX::solve().
is_triu()
template<typename MatType > bool casadi::GenericMatrix< MatType >::is_triu () const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1b6
Definition at line 183 of file generic_matrix.hpp.
 { return sparsity().is_triu();}
References casadi::Sparsity::is_triu(), and casadi::GenericMatrix< MatType >::sparsity().
Referenced by casadi::MX::solve().
is_vector()
template<typename MatType > bool casadi::GenericMatrix< MatType >::is_vector () const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1b3
Definition at line 168 of file generic_matrix.hpp.
 { return sparsity().is_vector();}
References casadi::Sparsity::is_vector(), and casadi::GenericMatrix< MatType >::sparsity().
Referenced by casadi::OptiNode::canon_expr(), casadi::BSplineParametric::create(), casadi::GetNonzerosParam::create(), casadi::BSpline::create(), casadi::SetNonzerosParam< Add >::create(), casadi::Function::generate_in(), casadi::Function::generate_out(), casadi::Matrix< Scalar >::get(), casadi::MX::get(), casadi::MXNode::get_find(), casadi::MX::interpn_linear(), casadi::Low::Low(), and casadi::MX::norm_2().
linear_coeff()
template<typename MatType > void casadi::GenericMatrix< MatType >::linear_coeff (const MatType & expr, const MatType & var, MatType & A, MatType & b, bool check) static
Definition at line 1557 of file generic_matrix.hpp.
{
     casadi_assert(expr.is_vector(), "'linear_coeff' only defined for vector expressions.");
     if (check)
       casadi_assert(is_linear(expr, var), "'linear_coeff' called on non-linear expression.");
     A = substitute(jacobian(expr, var), var, 0);
     b = vec(substitute(expr, var, 0));
   }
linspace()
template<typename MatType > MatType casadi::GenericMatrix< MatType >::linspace (const MatType & a, const MatType & b, casadi_int nsteps) static
Definition at line 1202 of file generic_matrix.hpp.
{
     std::vector<MatType> ret(nsteps);
     ret[0] = a;
     MatType step = (b-a)/static_cast<MatType>(nsteps-1);
     for (casadi_int i=1; i<nsteps-1; ++i)
       ret[i] = a + i * step;
     ret[nsteps-1] = b;
     return vertcat(ret);
   }
nnz()
template<typename MatType > casadi_int casadi::GenericMatrix< MatType >::nnz
Extra doc: https://github.com/casadi/casadi/wiki/L_1an
Definition at line 1119 of file generic_matrix.hpp.
{
     return sparsity().nnz();
   }
Referenced by casadi::Constant< Value >::_get_binary(), casadi::OptiNode::bake(), casadi::ConstantMX::create(), casadi::GetNonzerosParam::create(), casadi::SetNonzeros< Add >::create(), casadi::GetNonzeros::create(), casadi::MX::depends_on(), casadi::Diagsplit::Diagsplit(), casadi::Find::eval(), casadi::Low::eval(), casadi::GetNonzerosParamVector::eval(), casadi::GetNonzerosSliceParam::eval(), casadi::GetNonzerosParamSlice::eval(), casadi::GetNonzerosParamParam::eval(), casadi::HorzRepmat::eval_gen(), casadi::Concat::eval_gen(), casadi::Transpose::eval_gen(), casadi::Find::generate(), casadi::Low::generate(), casadi::Concat::generate(), casadi::GetNonzerosParamVector::generate(), casadi::GetNonzerosSliceParam::generate(), casadi::GetNonzerosParamSlice::generate(), casadi::GetNonzerosParamParam::generate(), casadi::Output::generate(), casadi::HorzRepmat::generate(), casadi::MXNode::get_binary(), casadi::MX::get_nz(), casadi::Concat::get_nzref(), casadi::AmplInterface::init(), casadi::SnoptInterface::init(), casadi::SuperscsInterface::init(), casadi::Scpgen::init(), casadi::CplexInterface::init_mem(), casadi::SnoptInterface::init_mem(), casadi::SymbolicQr::linsol_eval_sx(), casadi::Monitor::Monitor(), casadi::mtaylor_recursive(), casadi::MX::polyval(), casadi::Reshape::Reshape(), casadi::Matrix< Scalar >::set(), casadi::MX::set(), casadi::MX::set_nz(), casadi::SuperscsInterface::solve(), casadi::MX::solve(), casadi::SnoptInterface::solve(), casadi::MXNode::sp_forward(), casadi::Concat::sp_forward(), casadi::Dot::sp_forward(), casadi::HorzRepmat::sp_forward(), casadi::MXNode::sp_reverse(), casadi::Concat::sp_reverse(), casadi::Dot::sp_reverse(), casadi::GetNonzerosParam::sp_reverse(), casadi::HorzRepmat::sp_reverse(), casadi::MX::sparsity_cast(), casadi::SparsityCast::SparsityCast(), casadi::OptiNode::subject_to(), casadi::GetNonzerosParamSlice::sz_iw(), and casadi::GetNonzerosParamParam::sz_iw().
nnz_diag()
template<typename MatType > casadi_int casadi::GenericMatrix< MatType >::nnz_diag
Extra doc: https://github.com/casadi/casadi/wiki/L_1aq
Definition at line 1134 of file generic_matrix.hpp.
{
     return sparsity().nnz_diag();
   }
nnz_lower()
template<typename MatType > casadi_int casadi::GenericMatrix< MatType >::nnz_lower
Extra doc: https://github.com/casadi/casadi/wiki/L_1ao
Definition at line 1124 of file generic_matrix.hpp.
{
     return sparsity().nnz_lower();
   }
nnz_upper()
template<typename MatType > casadi_int casadi::GenericMatrix< MatType >::nnz_upper
Extra doc: https://github.com/casadi/casadi/wiki/L_1ap
Definition at line 1129 of file generic_matrix.hpp.
{
     return sparsity().nnz_upper();
   }
norm_0_mul()
template<typename MatType > static casadi_int casadi::GenericMatrix< MatType >::norm_0_mul (const MatType & x, const MatType & y) inline static
Definition at line 216 of file generic_matrix.hpp.
{
       return Sparsity::norm_0_mul(x.sparsity(), y.sparsity());
     }
References casadi::Sparsity::norm_0_mul().
numel()
template<typename MatType > casadi_int casadi::GenericMatrix< MatType >::numel
Extra doc: https://github.com/casadi/casadi/wiki/L_1ar
Definition at line 1139 of file generic_matrix.hpp.
{
     return sparsity().numel();
   }
Referenced by casadi::BSpline::BSpline(), casadi::BSplineParametric::create(), casadi::GetNonzerosParam::create(), casadi::BSpline::create(), casadi::OptiNode::g_describe(), casadi::Function::generate_in(), casadi::Function::generate_out(), casadi::DaeBuilderInternal::hess_v_v_from_calls(), casadi::init_gen(), casadi::MX::interpn_linear(), casadi::DaeBuilderInternal::jac_vdef_v_from_calls(), casadi::Low::Low(), casadi::DaeBuilderInternal::new_variable(), and casadi::OptiNode::x_describe().
nz() [1/2]
template<typename MatType > template<typename K > NonZeros<MatType, K> casadi::GenericMatrix< MatType >::nz (const K & k) inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1bc
Definition at line 258 of file generic_matrix.hpp.
{
       return NonZeros<MatType, K>(self(), k);
     }
nz() [2/2]
template<typename MatType > template<typename K > const MatType casadi::GenericMatrix< MatType >::nz (const K & k) const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1bb
Definition at line 248 of file generic_matrix.hpp.
{
       MatType ret;
       self().get_nz(ret, false, k);
       return ret;
     }
Referenced by casadi::SnoptInterface::init(), casadi::MX::kron(), and casadi::MX::polyval().
ones() [1/3]
template<typename MatType > static MatType casadi::GenericMatrix< MatType >::ones (casadi_int nrow = 1, casadi_int ncol = 1) inline static
Extra doc: https://github.com/casadi/casadi/wiki/L_1di
Definition at line 1096 of file generic_matrix.hpp.
{
       return ones(Sparsity::dense(nrow, ncol));
     }
References casadi::Sparsity::dense().
Referenced by casadi::OptiNode::canon_expr(), and casadi::GenericMatrix< MatType >::ones().
ones() [2/3]
template<typename MatType > static MatType casadi::GenericMatrix< MatType >::ones (const Sparsity & sp) inline static
Extra doc: https://github.com/casadi/casadi/wiki/L_1di
Definition at line 1099 of file generic_matrix.hpp.
 { return MatType(sp, 1, false);}
ones() [3/3]
template<typename MatType > static MatType casadi::GenericMatrix< MatType >::ones (const std::pair< casadi_int, casadi_int > & rc) inline static
Extra doc: https://github.com/casadi/casadi/wiki/L_1di
Definition at line 1100 of file generic_matrix.hpp.
{
       return ones(rc.first, rc.second);
     }
References casadi::GenericMatrix< MatType >::ones().
operator()() [1/4]
template<typename MatType > template<typename RR > SubIndex<MatType, RR> casadi::GenericMatrix< MatType >::operator() (const RR & rr) inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1bf
Definition at line 286 of file generic_matrix.hpp.
{
       return SubIndex<MatType, RR>(self(), rr);
     }
operator()() [2/4]
template<typename MatType > template<typename RR > const MatType casadi::GenericMatrix< MatType >::operator() (const RR & rr) const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1bd
Definition at line 266 of file generic_matrix.hpp.
{
       MatType ret;
       self().get(ret, false, rr);
       return ret;
     }
operator()() [3/4]
template<typename MatType > template<typename RR , typename CC > SubMatrix<MatType, RR, CC> casadi::GenericMatrix< MatType >::operator() (const RR & rr, const CC & cc) inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1bg
Definition at line 294 of file generic_matrix.hpp.
{
       return SubMatrix<MatType, RR, CC>(self(), rr, cc);
     }
operator()() [4/4]
template<typename MatType > template<typename RR , typename CC > const MatType casadi::GenericMatrix< MatType >::operator() (const RR & rr, const CC & cc) const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1be
Definition at line 276 of file generic_matrix.hpp.
{
       MatType ret;
       self().get(ret, false, rr, cc);
       return ret;
     }
quadratic_coeff()
template<typename MatType > void casadi::GenericMatrix< MatType >::quadratic_coeff (const MatType & expr, const MatType & var, MatType & A, MatType & b, MatType & c, bool check) static
Definition at line 1546 of file generic_matrix.hpp.
{
     casadi_assert(expr.is_scalar(), "'quadratic_coeff' only defined for scalar expressions.");
     A = hessian(expr, var);
     b = substitute(jacobian(expr, var), var, 0).T();
     if (check)
       casadi_assert(!depends_on(A, var), "'quadratic_coeff' called on non-quadratic expression.");
     c = substitute(expr, var, 0);
   }
repsum()
template<typename MatType > MatType casadi::GenericMatrix< MatType >::repsum (const MatType & x, casadi_int n, casadi_int m = 1) static
Definition at line 1340 of file generic_matrix.hpp.
{
     casadi_assert_dev(x.size1() % n==0);
     casadi_assert_dev(x.size2() % m==0);
     std::vector< std::vector< MatType> > s =
       blocksplit(x, x.size1()/n, x.size2()/m);
     MatType sum = 0;
     for (casadi_int i=0;i<s.size();++i) {
       for (casadi_int j=0;j<s[i].size();++j) {
         sum = sum + s[i][j];
       }
     }
     return sum;
   }
References casadi::sum().
Referenced by casadi::MXNode::get_repsum().
row() [1/2]
template<typename MatType > const casadi_int* casadi::GenericMatrix< MatType >::row () const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1b8
Definition at line 197 of file generic_matrix.hpp.
 { return sparsity().row(); }
References casadi::Sparsity::row(), and casadi::GenericMatrix< MatType >::sparsity().
Referenced by casadi::Matrix< Scalar >::densify(), casadi::Transpose::eval_gen(), casadi::MX::set(), casadi::SnoptInterface::solve(), casadi::Transpose::sp_forward(), casadi::Transpose::sp_reverse(), and casadi::SnoptInterface::userfun().
row() [2/2]
template<typename MatType > casadi_int casadi::GenericMatrix< MatType >::row (casadi_int el) const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1b8
Definition at line 200 of file generic_matrix.hpp.
 { return sparsity().row(el); }
References casadi::Sparsity::row(), and casadi::GenericMatrix< MatType >::sparsity().
rows()
template<typename MatType > casadi_int casadi::GenericMatrix< MatType >::rows () const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1at
Definition at line 114 of file generic_matrix.hpp.
 {return size1();}
References casadi::GenericMatrix< MatType >::size1().
size() [1/2]
template<typename MatType > std::pair< casadi_int, casadi_int > casadi::GenericMatrix< MatType >::size
Extra doc: https://github.com/casadi/casadi/wiki/L_1ax
Definition at line 1154 of file generic_matrix.hpp.
{
     return sparsity().size();
   }
Referenced by casadi::MXNode::_get_binary(), casadi::BinaryMX< ScX, ScY >::ad_reverse(), casadi::OptiNode::bake(), casadi::MX::binary(), casadi::Matrix< Scalar >::densify(), casadi::MX::densify(), casadi::MX::erase(), casadi::MXFunction::generate_lifted(), casadi::MXNode::get_binary(), casadi::Matrix< Scalar >::get_nz(), casadi::DaeBuilderInternal::CallIO::hess(), casadi::MX::horzcat(), casadi::init_gen(), casadi::interpn_G(), casadi::MX::interpn_linear(), casadi::DaeBuilderInternal::CallIO::jac(), casadi::MXNode::join_primitives(), casadi::MX::kron(), casadi::MX::project(), casadi::Call::projectArg(), casadi::Matrix< Scalar >::set(), casadi::MX::set(), casadi::Matrix< Scalar >::set_nz(), casadi::MX::set_nz(), casadi::MXNode::to_matrix(), casadi::MX::unite(), and casadi::MX::vertcat().
size() [2/2]
template<typename MatType > casadi_int casadi::GenericMatrix< MatType >::size (casadi_int axis) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1ay
Definition at line 1159 of file generic_matrix.hpp.
{
     return sparsity().size(axis);
   }
size1()
template<typename MatType > casadi_int casadi::GenericMatrix< MatType >::size1
Extra doc: https://github.com/casadi/casadi/wiki/L_1as
Definition at line 1144 of file generic_matrix.hpp.
{
     return sparsity().size1();
   }
Referenced by casadi::Constant< Value >::_get_binary(), casadi::Collocation::algebraic_state_output(), casadi::MX::binary(), casadi::BSplineParametric::BSplineParametric(), casadi::OptiNode::canon_expr(), casadi::BSplineInterpolant::construct_graph(), casadi::Matrix< Scalar >::cumsum(), casadi::Matrix< Scalar >::densify(), casadi::BSplineCommon::derivative_coeff(), casadi::MX::diagsplit(), casadi::do_inline(), casadi::dplesol(), casadi::Find::eval(), casadi::DenseTranspose::eval_gen(), casadi::Find::generate(), casadi::DenseMultiplication::generate(), casadi::DenseTranspose::generate(), casadi::get_boor(), casadi::MXNode::get_dot(), casadi::MXNode::get_mac(), casadi::MXNode::get_vertsplit(), casadi::SuperscsInterface::init(), casadi::SuperscsInterface::init_mem(), casadi::MX::inv(), casadi::Inverse::Inverse(), casadi::MX::kron(), casadi::SymbolicQr::linsol_eval_sx(), casadi::MX::mac(), casadi::Multiplication::Multiplication(), casadi::MX::MX(), casadi::MX::pinv(), casadi::Call::projectArg(), casadi::MX::repmat(), casadi::MX::reshape(), casadi::GenericMatrix< MatType >::rows(), casadi::Matrix< Scalar >::set(), casadi::MX::set(), casadi::Matrix< Scalar >::set_nz(), casadi::MX::set_nz(), casadi::simpleIRK(), casadi::Linsol::solve(), casadi::SuperscsInterface::solve(), casadi::Solve< Tr >::Solve(), casadi::DenseTranspose::sp_forward(), casadi::DenseTranspose::sp_reverse(), casadi::MX::sum1(), and casadi::MX::vertsplit().
size2()
template<typename MatType > casadi_int casadi::GenericMatrix< MatType >::size2
Extra doc: https://github.com/casadi/casadi/wiki/L_1au
Definition at line 1149 of file generic_matrix.hpp.
{
     return sparsity().size2();
   }
Referenced by casadi::Constant< Value >::_get_binary(), casadi::MX::binary(), casadi::OptiNode::canon_expr(), casadi::GenericMatrix< MatType >::columns(), casadi::BSplineInterpolant::construct_graph(), casadi::Matrix< Scalar >::cumsum(), casadi::MX::cumsum(), casadi::Matrix< Scalar >::densify(), casadi::BSplineCommon::derivative_coeff(), casadi::MX::diagsplit(), casadi::do_inline(), casadi::DenseTranspose::eval_gen(), casadi::DenseMultiplication::generate(), casadi::DenseTranspose::generate(), casadi::get_boor(), casadi::MXNode::get_dot(), casadi::MXNode::get_horzsplit(), casadi::MXNode::get_mac(), casadi::HorzRepsum::HorzRepsum(), casadi::MX::horzsplit(), casadi::CplexInterface::init_mem(), casadi::SnoptInterface::init_mem(), casadi::SuperscsInterface::init_mem(), casadi::Inverse::Inverse(), casadi::MX::kron(), casadi::MX::mac(), casadi::Multiplication::Multiplication(), casadi::CsparseInterface::nfact(), casadi::MX::pinv(), casadi::Call::projectArg(), casadi::MX::repmat(), casadi::MX::reshape(), casadi::Conic::sdp_to_socp_init(), casadi::Matrix< Scalar >::set(), casadi::MX::set(), casadi::Matrix< Scalar >::set_nz(), casadi::MX::set_nz(), casadi::Linsol::solve(), casadi::SuperscsInterface::solve(), casadi::Solve< Tr >::Solve(), casadi::DenseTranspose::sp_forward(), casadi::DenseTranspose::sp_reverse(), casadi::MX::sum2(), and casadi::MX::trace().
skew()
template<typename MatType > MatType casadi::GenericMatrix< MatType >::skew (const MatType & a) static
Definition at line 1311 of file generic_matrix.hpp.
{
     casadi_assert(a.is_vector() && (a.size1()==3 || a.size2()==3),
       "skew(a): Expecting 3-vector, got " + a.dim() + ".");
     MatType x = a(0);
     MatType y = a(1);
     MatType z = a(2);
     return blockcat(std::vector< std::vector<MatType> >({{0, -z, y}, {z, 0, -x}, {-y, x, 0}}));
   }
sparsity()
template<typename MatType > const Sparsity & casadi::GenericMatrix< MatType >::sparsity
Extra doc: https://github.com/casadi/casadi/wiki/L_1b9
Definition at line 1114 of file generic_matrix.hpp.
{
     return self().sparsity();
   }
Referenced by casadi::GenericMatrix< MatType >::colind(), casadi::GenericMatrix< MatType >::get_colind(), casadi::GenericMatrix< MatType >::get_row(), casadi::GenericMatrix< MatType >::is_column(), casadi::GenericMatrix< MatType >::is_dense(), casadi::GenericMatrix< MatType >::is_empty(), casadi::GenericMatrix< MatType >::is_row(), casadi::GenericMatrix< MatType >::is_square(), casadi::GenericMatrix< MatType >::is_tril(), casadi::GenericMatrix< MatType >::is_triu(), casadi::GenericMatrix< MatType >::is_vector(), casadi::GenericMatrix< MatType >::row(), and casadi::MX::unite().
sprank()
template<typename MatType > static casadi_int casadi::GenericMatrix< MatType >::sprank (const MatType & x) inline static
Definition at line 215 of file generic_matrix.hpp.
 { return Sparsity::sprank(x.sparsity());}
References casadi::Sparsity::sprank().
sumsqr()
template<typename MatType > static MatType casadi::GenericMatrix< MatType >::sumsqr (const MatType & x) inline static
Definition at line 225 of file generic_matrix.hpp.
 { return dot(x, x);}
References casadi::GenericMatrix< MatType >::dot.
sym() [1/7]
template<typename MatType > static std::vector<MatType > casadi::GenericMatrix< MatType >::sym (const std::string & name, casadi_int nrow, casadi_int ncol, casadi_int p) inline static
Extra doc: https://github.com/casadi/casadi/wiki/L_1de
Definition at line 1055 of file generic_matrix.hpp.
{
       return sym(name, Sparsity::dense(nrow, ncol), p);
     }
References casadi::Sparsity::dense(), and casadi::GenericMatrix< MatType >::sym().
sym() [2/7]
template<typename MatType > static std::vector<std::vector<MatType> > casadi::GenericMatrix< MatType >::sym (const std::string & name, casadi_int nrow, casadi_int ncol, casadi_int p, casadi_int r) inline static
with nrow-by-ncol symbolic primitives
Extra doc: https://github.com/casadi/casadi/wiki/L_1dg
Definition at line 1074 of file generic_matrix.hpp.
{
       return sym(name, Sparsity::dense(nrow, ncol), p, r);
     }
References casadi::Sparsity::dense(), and casadi::GenericMatrix< MatType >::sym().
sym() [3/7]
template<typename MatType > static MatType casadi::GenericMatrix< MatType >::sym (const std::string & name, casadi_int nrow = 1, casadi_int ncol = 1) inline static
Extra doc: https://github.com/casadi/casadi/wiki/L_1da
Definition at line 1027 of file generic_matrix.hpp.
{
       return sym(name, Sparsity::dense(nrow, ncol));
     }
References casadi::Sparsity::dense().
Referenced by casadi::GenericMatrix< MatType >::sym().
sym() [4/7]
template<typename MatType > static MatType casadi::GenericMatrix< MatType >::sym (const std::string & name, const Sparsity & sp) inline static
Extra doc: https://github.com/casadi/casadi/wiki/L_1dc
Definition at line 1041 of file generic_matrix.hpp.
{
       return MatType::_sym(name, sp);
     }
sym() [5/7]
template<typename MatType > std::vector< MatType > casadi::GenericMatrix< MatType >::sym (const std::string & name, const Sparsity & sp, casadi_int p) static
with symbolic primitives of given sparsity
Extra doc: https://github.com/casadi/casadi/wiki/L_1dd
Definition at line 1176 of file generic_matrix.hpp.
{
     std::vector<MatType> ret(p);
     std::stringstream ss;
     for (casadi_int k=0; k<p; ++k) {
       ss.str("");
       ss << name << k;
       ret[k] = sym(ss.str(), sp);
     }
     return ret;
   }
sym() [6/7]
template<typename MatType > std::vector< std::vector< MatType > > casadi::GenericMatrix< MatType >::sym (const std::string & name, const Sparsity & sp, casadi_int p, casadi_int r) static
symbolic primitives with given sparsity
Extra doc: https://github.com/casadi/casadi/wiki/L_1df
Definition at line 1189 of file generic_matrix.hpp.
{
     std::vector<std::vector<MatType> > ret(r);
     for (casadi_int k=0; k<r; ++k) {
       std::stringstream ss;
       ss << name << "_" << k;
       ret[k] = sym(ss.str(), sp, p);
     }
     return ret;
   }
sym() [7/7]
template<typename MatType > static MatType casadi::GenericMatrix< MatType >::sym (const std::string & name, const std::pair< casadi_int, casadi_int > & rc) inline static
Extra doc: https://github.com/casadi/casadi/wiki/L_1db
Definition at line 1034 of file generic_matrix.hpp.
{
       return sym(name, rc.first, rc.second);
     }
References casadi::GenericMatrix< MatType >::sym().
tril()
template<typename MatType > static MatType casadi::GenericMatrix< MatType >::tril (const MatType & x, bool includeDiagonal = true) inline static
Definition at line 219 of file generic_matrix.hpp.
{
       return project(x, Sparsity::tril(x.sparsity(), includeDiagonal));
     }
References casadi::GenericMatrix< MatType >::project, and casadi::Sparsity::tril().
tril2symm()
template<typename MatType > MatType casadi::GenericMatrix< MatType >::tril2symm (const MatType & x) static
Definition at line 1331 of file generic_matrix.hpp.
{
     casadi_assert(x.is_square(),
       "Shape error in tril2symm. Expecting square shape but got " + x.dim());
     casadi_assert(x.nnz_upper()-x.nnz_diag()==0,
       "Sparsity error in tril2symm. Found above-diagonal entries in argument: " + x.dim());
     return x +  x.T() - diag(diag(x));
   }
triu()
template<typename MatType > static MatType casadi::GenericMatrix< MatType >::triu (const MatType & x, bool includeDiagonal = true) inline static
Definition at line 222 of file generic_matrix.hpp.
{
       return project(x, Sparsity::triu(x.sparsity(), includeDiagonal));
     }
References casadi::GenericMatrix< MatType >::project, and casadi::Sparsity::triu().
triu2symm()
template<typename MatType > MatType casadi::GenericMatrix< MatType >::triu2symm (const MatType & x) static
Definition at line 1355 of file generic_matrix.hpp.
{
     casadi_assert(x.is_square(),
       "Shape error in triu2symm. Expecting square shape but got " + x.dim());
     casadi_assert(x.nnz_lower()-x.nnz_diag()==0,
       "Sparsity error in triu2symm. Found below-diagonal entries in argument: " + x.dim());
     return x + x.T() - diag(diag(x));
   }
zeros() [1/3]
template<typename MatType > static MatType casadi::GenericMatrix< MatType >::zeros (casadi_int nrow = 1, casadi_int ncol = 1) inline static
Extra doc: https://github.com/casadi/casadi/wiki/L_1dh
Examples
misc/all.cc.
Definition at line 1083 of file generic_matrix.hpp.
{
       return zeros(Sparsity::dense(nrow, ncol));
     }
References casadi::Sparsity::dense().
Referenced by casadi::GetNonzeros::ad_reverse(), casadi::GetNonzerosParamVector::ad_reverse(), casadi::GetNonzerosSliceParam::ad_reverse(), casadi::GetNonzerosParamSlice::ad_reverse(), casadi::GetNonzerosParamParam::ad_reverse(), casadi::HpmpcInterface::blocksparsity(), casadi::HpipmInterface::blocksparsity(), casadi::OptiNode::canon_expr(), casadi::Sparsity::diagsplit(), casadi::FunctionInternal::dm_in(), casadi::FunctionInternal::dm_out(), casadi::Blocksqp::feasibilityRestorationPhase(), casadi::get_boor(), casadi::Expm::get_forward(), casadi::Expm::get_reverse(), casadi::init_gen(), casadi::MX::set(), casadi::OptiNode::variable(), and casadi::GenericMatrix< MatType >::zeros().
zeros() [2/3]
template<typename MatType > static MatType casadi::GenericMatrix< MatType >::zeros (const Sparsity & sp) inline static
Extra doc: https://github.com/casadi/casadi/wiki/L_1dh
Definition at line 1086 of file generic_matrix.hpp.
 { return MatType(sp, 0, false);}
zeros() [3/3]
template<typename MatType > static MatType casadi::GenericMatrix< MatType >::zeros (const std::pair< casadi_int, casadi_int > & rc) inline static
Extra doc: https://github.com/casadi/casadi/wiki/L_1dh
Definition at line 1087 of file generic_matrix.hpp.
{
       return zeros(rc.first, rc.second);
     }
References casadi::GenericMatrix< MatType >::zeros().
The documentation for this class was generated from the following file:
generic_matrix.hpp