CasADi: casadi::Polynomial Class Reference
casadi::Polynomial Class Reference
Helper class for differentiating and integrating polynomials.
#include <polynomial.hpp>
Detailed Description
Author
Joel Andersson
Date
2014
Extra doc: https://github.com/casadi/casadi/wiki/L_8y
Definition at line 39 of file polynomial.hpp.
Public Member Functions
Polynomial (double scalar=1)
Construct a constant polynomial.
Polynomial (double p0, double p1)
Construct a linear polynomial.
Polynomial (double p0, double p1, double p2)
Construct a quadratic polynomial.
Polynomial (double p0, double p1, double p2, double p3)
Construct a cubic polynomial.
template<typename T >
Polynomial (const std::vector< T > &coeff)
Construct from a vector of polynomial coefficients.
template<typename T >
T operator() (const T &x) const
Evaluate numerically.
const std::vector< double > & coeff () const
Coefficients of the polynomial.
casadi_int degree () const
Degree of the polynomial.
double scalar () const
Get scalar value (error if degree()!=0)
Polynomial derivative () const
Create a new polynomial for the derivative.
Polynomial anti_derivative () const
Create a new polynomial for the anti-derivative (primitive function)
void trim ()
Remove excess zeros.
std::string type_name () const
Readable name of the class.
void disp (std::ostream &stream, bool more=false) const
Print a description of the object.
Polynomial operator+ (const Polynomial &b) const
Polynomial & operator+= (const Polynomial &b)
Polynomial operator- (const Polynomial &b) const
Polynomial & operator-= (const Polynomial &b)
Polynomial operator* (const Polynomial &b) const
Polynomial & operator*= (const Polynomial &b)
Polynomial operator/ (double b) const
Polynomial & operator/= (double b)
Protected Attributes
std::vector< double > p_
Constructor & Destructor Documentation
Polynomial() [1/5]
casadi::Polynomial::Polynomial (double scalar = 1)
Definition at line 32 of file polynomial.cpp.
                                       : p_(1, scalar) {
   }
Referenced by anti_derivative(), derivative(), and operator*().
Polynomial() [2/5]
casadi::Polynomial::Polynomial (double p0, double p1)
Definition at line 35 of file polynomial.cpp.
{
     p_.resize(2);
     p_[0] = p0;
     p_[1] = p1;
   }
References p_.
Polynomial() [3/5]
casadi::Polynomial::Polynomial (double p0, double p1, double p2)
Definition at line 41 of file polynomial.cpp.
{
     p_.resize(3);
     p_[0] = p0;
     p_[1] = p1;
     p_[2] = p2;
   }
References p_.
Polynomial() [4/5]
casadi::Polynomial::Polynomial (double p0, double p1, double p2, double p3)
Definition at line 48 of file polynomial.cpp.
{
     p_.resize(4);
     p_[0] = p0;
     p_[1] = p1;
     p_[2] = p2;
     p_[3] = p3;
   }
References p_.
Polynomial() [5/5]
template<typename T > casadi::Polynomial::Polynomial (const std::vector< T > & coeff) inline
Definition at line 56 of file polynomial.hpp.
 : p_(coeff.begin(), coeff.end()) {}
Member Function Documentation
anti_derivative()
Polynomial casadi::Polynomial::anti_derivative () const
Definition at line 149 of file polynomial.cpp.
{
     std::vector<double> ret_p(p_.size()+1);
     ret_p[0] = 0;
     for (casadi_int k=0; k<p_.size(); ++k) {
       ret_p[k+1] = p_[k]/static_cast<double>(k+1);
     }
     return Polynomial(ret_p);
   }
References p_, and Polynomial().
Referenced by casadi::collocation_coeff(), and casadi::Collocation::setup_step().
coeff()
const std::vector<double>& casadi::Polynomial::coeff () const inline
Definition at line 71 of file polynomial.hpp.
 { return p_; }
Referenced by casadi::reduce_index_gen().
degree()
casadi_int casadi::Polynomial::degree () const
Definition at line 72 of file polynomial.cpp.
{
     return p_.size()-1;
   }
References p_.
Referenced by scalar().
derivative()
Polynomial casadi::Polynomial::derivative () const
Definition at line 141 of file polynomial.cpp.
{
     std::vector<double> ret_p(p_.size()-1);
     for (casadi_int k=1; k<p_.size(); ++k) {
       ret_p[k-1] = static_cast<double>(k)*p_[k];
     }
     return Polynomial(ret_p);
   }
References p_, and Polynomial().
Referenced by casadi::collocation_coeff(), and casadi::Collocation::setup_step().
disp()
void casadi::Polynomial::disp (std::ostream & stream, bool more = false) const
Definition at line 56 of file polynomial.cpp.
{
     if (more) {
       for (casadi_int d=0; d<p_.size(); ++d) {
         if (d==0) {
           stream << p_[d];
         } else if (d==1) {
           stream << " + " << p_[d] << "*x";
         } else {
           stream << " + " << p_[d] << "*x^" << d;
         }
       }
     } else {
       stream << p_;
     }
   }
References p_.
operator()()
template<typename T > T casadi::Polynomial::operator() (const T & x) const inline
Definition at line 60 of file polynomial.hpp.
{
       auto it = p_.rbegin();
       T ret = *it++;
       while (it!=p_.rend()) {
         ret *= x;
         ret += *it++;
       }
       return ret;
     }
References casadi::T.
operator*()
Polynomial casadi::Polynomial::operator* (const Polynomial & b) const
Definition at line 81 of file polynomial.cpp.
{
     std::vector<double> p_ret(p_.size() + a.p_.size() - 1, 0);
     for (casadi_int d=0; d<p_.size(); ++d) {
       for (casadi_int d_a=0; d_a<a.p_.size(); ++d_a) {
         p_ret[d+d_a] += p_[d] * a.p_[d_a];
       }
     }
     return Polynomial(p_ret);
   }
References p_, and Polynomial().
operator*=()
Polynomial & casadi::Polynomial::operator*= (const Polynomial & b)
Definition at line 91 of file polynomial.cpp.
{
     return *this = *this*d;
   }
operator+()
Polynomial casadi::Polynomial::operator+ (const Polynomial & b) const
Definition at line 108 of file polynomial.cpp.
{
     Polynomial ret = *this;
     return ret+=b;
   }
operator+=()
Polynomial & casadi::Polynomial::operator+= (const Polynomial & b)
Definition at line 113 of file polynomial.cpp.
{
     p_.resize(std::max(p_.size(), b.p_.size()), 0);
     transform(b.p_.begin(), b.p_.end(), p_.begin(), p_.begin(), std::plus<double>());
     trim();
     return *this;
   }
References p_, and trim().
operator-()
Polynomial casadi::Polynomial::operator- (const Polynomial & b) const
Definition at line 120 of file polynomial.cpp.
{
     Polynomial ret = *this;
     return ret-=b;
   }
operator-=()
Polynomial & casadi::Polynomial::operator-= (const Polynomial & b)
Definition at line 125 of file polynomial.cpp.
{
     p_.resize(std::max(p_.size(), b.p_.size()), 0);
     transform(p_.begin(), p_.begin()+b.p_.size(),
               b.p_.begin(), p_.begin(), std::minus<double>());
     trim();
     return *this;
   }
References p_, and trim().
operator/()
Polynomial casadi::Polynomial::operator/ (double b) const
Definition at line 95 of file polynomial.cpp.
{
     Polynomial ret = *this;
     ret/=d;
     return ret;
   }
operator/=()
Polynomial & casadi::Polynomial::operator/= (double b)
Definition at line 101 of file polynomial.cpp.
{
     for (std::vector<double>::iterator it=p_.begin(); it!=p_.end(); ++it) {
       *it /= d;
     }
     return *this;
   }
References p_.
scalar()
double casadi::Polynomial::scalar () const
Definition at line 76 of file polynomial.cpp.
{
     casadi_assert_dev(degree()==0);
     return p_.front();
   }
References degree(), and p_.
trim()
void casadi::Polynomial::trim ()
Definition at line 133 of file polynomial.cpp.
{
     // Remove trailing zeros
     size_t new_size = p_.size();
     std::vector<double>::const_reverse_iterator it=p_.rbegin();
     while (it!=p_.rend() && 0==*it++) new_size--;
     p_.resize(new_size);
   }
References p_.
Referenced by operator+=(), and operator-=().
type_name()
std::string casadi::Polynomial::type_name () const inline
Definition at line 89 of file polynomial.hpp.
 {return "Polynomial";}
Member Data Documentation
p_
std::vector<double> casadi::Polynomial::p_ protected
Definition at line 120 of file polynomial.hpp.
Referenced by anti_derivative(), degree(), derivative(), disp(), operator*(), operator+=(), operator-=(), operator/=(), Polynomial(), scalar(), and trim().
The documentation for this class was generated from the following files:
polynomial.hpp
polynomial.cpp