CasADi: casadi::Function Class Reference
casadi::Function Class Reference
Function object.
#include <function.hpp>
Detailed Description
A Function instance is a general multiple-input, multiple-output function where each input and output can be a sparse matrix.
For an introduction to this class, see the CasADi user guide.
Function is a reference counted and immutable class; copying a class instance is very cheap and its behavior (with some exceptions) is not affected by calling its member functions.
Author
Joel Andersson
Date
2010-2017
Extra doc: https://github.com/casadi/casadi/wiki/L_1uw
List of available options
Id Type Description Used in
ad_weight OT_DOUBLE Weighting factor for derivative calculation.When there is an option of either using forward or reverse mode directional derivatives, the condition ad_weight*nf<=(1-ad_weight)*na is used where nf and na are estimates of the number of forward/reverse mode directional derivatives needed. By default, ad_weight is calculated automatically, but this can be overridden by setting this option. In particular, 0 means forcing forward mode and 1 forcing reverse mode. Leave unset for (class specific) heuristics. casadi::FunctionInternal
ad_weight_sp OT_DOUBLE Weighting factor for sparsity pattern calculation calculation.Overrides default behavior. Set to 0 and 1 to force forward and reverse mode respectively. Cf. option "ad_weight". When set to -1, sparsity is completely ignored and dense matrices are used. casadi::FunctionInternal
always_inline OT_BOOL Force inlining. casadi::FunctionInternal
cache OT_DICT Prepopulate the function cache. Default: empty casadi::FunctionInternal
compiler OT_STRING Just-in-time compiler plugin to be used. casadi::FunctionInternal
custom_jacobian OT_FUNCTION Override CasADi's AD. Use together with 'jac_penalty': 0. Note: Highly experimental. Syntax may break often. casadi::FunctionInternal
der_options OT_DICT Default options to be used to populate forward_options, reverse_options, and jacobian_options before those options are merged in. casadi::FunctionInternal
derivative_of OT_FUNCTION The function is a derivative of another function. The type of derivative (directional derivative, Jacobian) is inferred from the function name. casadi::FunctionInternal
dump OT_BOOL Dump function to file upon first evaluation. [false] casadi::FunctionInternal
dump_dir OT_STRING Directory to dump inputs/outputs to. Make sure the directory exists [.] casadi::FunctionInternal
dump_format OT_STRING Choose file format to dump matrices. See DM.from_file [mtx] casadi::FunctionInternal
dump_in OT_BOOL Dump numerical values of inputs to file (readable with DM.from_file) [default: false] casadi::FunctionInternal
dump_out OT_BOOL Dump numerical values of outputs to file (readable with DM.from_file) [default: false] casadi::FunctionInternal
enable_fd OT_BOOL Enable derivative calculation by finite differencing. [default: false]] casadi::FunctionInternal
enable_forward OT_BOOL Enable derivative calculation using generated functions for Jacobian-times-vector products - typically using forward mode AD - if available. [default: true] casadi::FunctionInternal
enable_jacobian OT_BOOL Enable derivative calculation using generated functions for Jacobians of all differentiable outputs with respect to all differentiable inputs - if available. [default: true] casadi::FunctionInternal
enable_reverse OT_BOOL Enable derivative calculation using generated functions for transposed Jacobian-times-vector products - typically using reverse mode AD - if available. [default: true] casadi::FunctionInternal
error_on_fail OT_BOOL Throw exceptions when function evaluation fails (default true). casadi::ProtoFunction
fd_method OT_STRING Method for finite differencing [default 'central'] casadi::FunctionInternal
fd_options OT_DICT Options to be passed to the finite difference instance casadi::FunctionInternal
forward_options OT_DICT Options to be passed to a forward mode constructor casadi::FunctionInternal
gather_stats OT_BOOL Deprecated option (ignored): Statistics are now always collected. casadi::FunctionInternal
input_scheme OT_STRINGVECTOR Deprecated option (ignored) casadi::FunctionInternal
inputs_check OT_BOOL Throw exceptions when the numerical values of the inputs don't make sense casadi::FunctionInternal
is_diff_in OT_BOOLVECTOR Indicate for each input if it should be differentiable. casadi::FunctionInternal
is_diff_out OT_BOOLVECTOR Indicate for each output if it should be differentiable. casadi::FunctionInternal
jac_penalty OT_DOUBLE When requested for a number of forward/reverse directions, it may be cheaper to compute first the full jacobian and then multiply with seeds, rather than obtain the requested directions in a straightforward manner. Casadi uses a heuristic to decide which is cheaper. A high value of 'jac_penalty' makes it less likely for the heurstic to chose the full Jacobian strategy. The special value -1 indicates never to use the full Jacobian strategy casadi::FunctionInternal
jacobian_options OT_DICT Options to be passed to a Jacobian constructor casadi::FunctionInternal
jit OT_BOOL Use just-in-time compiler to speed up the evaluation casadi::FunctionInternal
jit_cleanup OT_BOOL Cleanup up the temporary source file that jit creates. Default: true casadi::FunctionInternal
jit_name OT_STRING The file name used to write out code. The actual file names used depend on 'jit_temp_suffix' and include extensions. Default: 'jit_tmp' casadi::FunctionInternal
jit_options OT_DICT Options to be passed to the jit compiler. casadi::FunctionInternal
jit_serialize OT_STRING Specify behaviour when serializing a jitted function: SOURCE|link|embed. casadi::FunctionInternal
jit_temp_suffix OT_BOOL Use a temporary (seemingly random) filename suffix for generated code and libraries. This is desired for thread-safety. This behaviour may defeat caching compiler wrappers. Default: true casadi::FunctionInternal
max_io OT_INT Acceptable number of inputs and outputs. Warn if exceeded. casadi::FunctionInternal
max_num_dir OT_INT Specify the maximum number of directions for derivative functions. Overrules the builtin optimized_num_dir. casadi::FunctionInternal
never_inline OT_BOOL Forbid inlining. casadi::FunctionInternal
output_scheme OT_STRINGVECTOR Deprecated option (ignored) casadi::FunctionInternal
post_expand OT_BOOL After construction, expand this Function. Default: False casadi::FunctionInternal
post_expand_options OT_DICT Options to be passed to post-construction expansion. Default: empty casadi::FunctionInternal
print_in OT_BOOL Print numerical values of inputs [default: false] casadi::FunctionInternal
print_out OT_BOOL Print numerical values of outputs [default: false] casadi::FunctionInternal
print_time OT_BOOL print information about execution time. Implies record_time. casadi::ProtoFunction
record_time OT_BOOL record information about execution time, for retrieval with stats(). casadi::ProtoFunction
regularity_check OT_BOOL Throw exceptions when NaN or Inf appears during evaluation casadi::ProtoFunction
reverse_options OT_DICT Options to be passed to a reverse mode constructor casadi::FunctionInternal
user_data OT_VOIDPTR A user-defined field that can be used to identify the function or pass additional information casadi::FunctionInternal
verbose OT_BOOL Verbose evaluation – for debugging casadi::ProtoFunction
Examples
SX/SXFunction_constr_oct.m, SX/SXFunction_constr_py.py, integrators/simulator.py, solvers/callback.py, solvers/exacthessian.py, and solvers/ipopt.py.
Definition at line 58 of file function.hpp.
Public Types
typedef std::map< std::string, std::vector< std::string > > AuxOut
Public Member Functions
Function ()
Default constructor, null pointer.
Function (const std::string &fname)
Construct from a file.
~Function ()
Destructor.
casadi_int n_in () const
Get the number of function inputs.
casadi_int n_out () const
Get the number of function outputs.
const std::vector< std::string > & name_in () const
Get input scheme.
const std::vector< std::string > & name_out () const
Get output scheme.
const std::string & name_in (casadi_int ind) const
Get input scheme name by index.
const std::string & name_out (casadi_int ind) const
Get output scheme name by index.
casadi_int index_in (const std::string &name) const
Find the index for a string describing a particular entry of an input scheme.
casadi_int index_out (const std::string &name) const
Find the index for a string describing a particular entry of an output scheme.
double default_in (casadi_int ind) const
Get default input value.
double max_in (casadi_int ind) const
Get largest input value.
double min_in (casadi_int ind) const
Get smallest input value.
std::vector< double > nominal_in (casadi_int ind) const
Get nominal input value.
std::vector< double > nominal_out (casadi_int ind) const
Get nominal output value.
Function factory (const std::string &name, const std::vector< std::string > &s_in, const std::vector< std::string > &s_out, const AuxOut &aux=AuxOut(), const Dict &opts=Dict()) const
Function oracle () const
Get oracle.
Function wrap () const
Wrap in an Function instance consisting of only one MX call.
Function wrap_as_needed (const Dict &opts) const
Wrap in a Function with options.
std::vector< bool > which_depends (const std::string &s_in, const std::vector< std::string > &s_out, casadi_int order=1, bool tr=false) const
Which variables enter with some order.
void print_dimensions (std::ostream &stream=casadi::uout()) const
Print dimensions of inputs and outputs.
void print_options (std::ostream &stream=casadi::uout()) const
Print options to a stream.
void print_option (const std::string &name, std::ostream &stream=casadi::uout()) const
Print all information there is to know about a certain option.
bool has_option (const std::string &option_name) const
Does a particular option exist.
void change_option (const std::string &option_name, const GenericType &option_value)
Change option after object creation for debugging.
bool uses_output () const
Do the derivative functions need nondifferentiated outputs?
Function jacobian_old (casadi_int iind, casadi_int oind) const
[DEPRECATED] Replaced by Function::factory.
Function hessian_old (casadi_int iind, casadi_int oind) const
[DEPRECATED] Replaced by Function::factory.
Function jacobian () const
Calculate all Jacobian blocks.
bool operator== (const Function &f) const
Check if same as another function.
int operator() (const double **arg, double **res, casadi_int *iw, double *w, int mem) const
Evaluate memory-less, numerically.
int operator() (const double **arg, double **res, casadi_int *iw, double *w) const
Evaluate numerically with checkout/release.
int operator() (const SXElem **arg, SXElem **res, casadi_int *iw, SXElem *w, int mem=0) const
Evaluate memory-less SXElem.
int operator() (const bvec_t **arg, bvec_t **res, casadi_int *iw, bvec_t *w, int mem=0) const
Propagate sparsity forward.
int rev (bvec_t **arg, bvec_t **res, casadi_int *iw, bvec_t *w, int mem=0) const
Propagate sparsity backward.
int rev (std::vector< bvec_t * > arg, std::vector< bvec_t * > res) const
Propagate sparsity backward with temporary memory allocation.
std::vector< MX > mapsum (const std::vector< MX > &x, const std::string &parallelization="serial") const
Evaluate symbolically in parallel and sum (matrix graph)
Function map (casadi_int n, const std::string &parallelization="serial") const
Create a mapped version of this function.
Function map (casadi_int n, const std::string &parallelization, casadi_int max_num_threads) const
Function slice (const std::string &name, const std::vector< casadi_int > &order_in, const std::vector< casadi_int > &order_out, const Dict &opts=Dict()) const
returns a new function with a selection of inputs/outputs of the original
Function forward (casadi_int nfwd) const
Get a function that calculates nfwd forward derivatives.
Function reverse (casadi_int nadj) const
Get a function that calculates nadj adjoint derivatives.
const std::vector< Sparsity > & jac_sparsity (bool compact=false) const
Get, if necessary generate, the sparsity of all Jacobian blocks.
Sparsity jac_sparsity (casadi_int oind, casadi_int iind, bool compact=false) const
Get, if necessary generate, the sparsity of a single Jacobian block.
std::string generate (const std::string &fname, const Dict &opts=Dict()) const
Export / Generate C code for the function.
std::string generate (const Dict &opts=Dict()) const
Export / Generate C code for the function.
std::string generate_dependencies (const std::string &fname, const Dict &opts=Dict()) const
Export / Generate C code for the dependency function.
FunctionInternal * get () const
template<typename T >
T * get () const
Get a pointer and typecast.
FunctionInternal * operator-> () const
Const access functions of the node.
Dict stats (int mem=0) const
Get all statistics obtained at the end of the last evaluate call.
bool has_free () const
Does the function have free variables.
std::vector< std::string > get_free () const
Get free variables as a string.
std::vector< SX > free_sx () const
Get all the free variables of the function.
std::vector< MX > free_mx () const
Get all the free variables of the function.
void generate_lifted (Function &vdef_fcn, Function &vinit_fcn) const
Extract the functions needed for the Lifted Newton method.
casadi_int n_nodes () const
Number of nodes in the algorithm.
casadi_int n_instructions () const
Number of instruction in the algorithm (SXFunction/MXFunction)
casadi_int instruction_id (casadi_int k) const
Identifier index of the instruction (SXFunction/MXFunction)
std::vector< casadi_int > instruction_input (casadi_int k) const
Locations in the work vector for the inputs of the instruction.
double instruction_constant (casadi_int k) const
Get the floating point output argument of an instruction (SXFunction)
std::vector< casadi_int > instruction_output (casadi_int k) const
Location in the work vector for the output of the instruction.
MX instruction_MX (casadi_int k) const
Get the MX node corresponding to an instruction (MXFunction)
SX instructions_sx () const
Get the SX node corresponding to all instructions (SXFunction)
size_t sz_arg () const
Get required length of arg field.
size_t sz_res () const
Get required length of res field.
size_t sz_iw () const
Get required length of iw field.
size_t sz_w () const
Get required length of w field.
void sz_work (size_t &sz_arg, size_t &sz_res, size_t &sz_iw, size_t &sz_w) const
Get number of temporary variables needed.
void set_work (const double **&arg, double **&res, casadi_int *&iw, double *&w, int mem=0) const
Set the (persistent) work vectors.
void set_temp (const double **arg, double **res, casadi_int *iw, double *w, int mem=0) const
Set the (temporary) work vectors.
void setup (const double **arg, double **res, casadi_int *iw, double *w, int mem=0) const
Set the (persistent and temporary) work vectors.
template<typename M >
void call_gen (const std::map< std::string, M > &arg, std::map< std::string, M > &res, bool always_inline, bool never_inline) const
Call using a map.
const std::string & name () const
Name of the function.
bool is_a (const std::string &type, bool recursive=true) const
Check if the function is of a particular type.
void assert_size_in (casadi_int i, casadi_int nrow, casadi_int ncol) const
Assert that an input dimension is equal so some given value.
void assert_size_out (casadi_int i, casadi_int nrow, casadi_int ncol) const
Assert that an output dimension is equal so some given value.
void assert_sparsity_out (casadi_int i, const Sparsity &sp, casadi_int n=1, bool allow_all_zero_sparse=true) const
Assert that an output sparsity is a multiple of some given sparsity.
casadi_int checkout () const
Checkout a memory object.
void release (int mem) const
Release a memory object.
void * memory (int ind) const
Get memory object.
Dict cache () const
Get all functions in the cache.
std::vector< std::string > get_function () const
Get a list of all functions.
Function get_function (const std::string &name) const
Get a dependency function.
bool has_function (const std::string &fname) const
Check if a particular dependency exists.
std::vector< Function > find_functions (casadi_int max_depth=-1) const
Get all functions embedded in the expression graphs.
Function find_function (const std::string &name, casadi_int max_depth=-1) const
Get a specific function embedded in the expression graphs.
Dict info () const
void own (SharedObjectInternal *node)
void assign (SharedObjectInternal *node)
Assign the node to a node class pointer without reference counting.
casadi_int getCount () const
Get the reference count.
void swap (SharedObject &other)
Swap content with another instance.
std::string class_name () const
Get class name.
void disp (std::ostream &stream, bool more=false) const
Print a description of the object.
std::string get_str (bool more=false) const
Get string representation.
void print_ptr (std::ostream &stream=casadi::uout()) const
bool is_null () const
Is a null pointer?
casadi_int __hash__ () const
Returns a number that is unique for a given Node.
WeakRef * weak ()
Get a weak reference to the object.
Function (const std::string &name, const std::vector< SX > &ex_in, const std::vector< SX > &ex_out, const Dict &opts=Dict())
Construct an SX function.
Function (const std::string &name, const std::vector< SX > &ex_in, const std::vector< SX > &ex_out, const std::vector< std::string > &name_in, const std::vector< std::string > &name_out, const Dict &opts=Dict())
Construct an SX function.
Function (const std::string &name, const std::map< std::string, SX > &dict, const std::vector< std::string > &name_in, const std::vector< std::string > &name_out, const Dict &opts=Dict())
Construct an SX function.
Function (const std::string &name, const std::vector< MX > &ex_in, const std::vector< MX > &ex_out, const Dict &opts=Dict())
Construct an MX function.
Function (const std::string &name, const std::vector< MX > &ex_in, const std::vector< MX > &ex_out, const std::vector< std::string > &name_in, const std::vector< std::string > &name_out, const Dict &opts=Dict())
Construct an MX function.
Function (const std::string &name, const std::map< std::string, MX > &dict, const std::vector< std::string > &name_in, const std::vector< std::string > &name_out, const Dict &opts=Dict())
Construct an MX function.
Function (const std::string &name, SXIList ex_in, const SXVector &ex_out, const Dict &opts=Dict())
To resolve ambiguity on some compilers.
Function (const std::string &name, const SXVector &ex_in, SXIList ex_out, const Dict &opts=Dict())
To resolve ambiguity on some compilers.
Function (const std::string &name, SXIList ex_in, SXIList ex_out, const Dict &opts=Dict())
To resolve ambiguity on some compilers.
Function (const std::string &name, SXIList ex_in, const SXVector &ex_out, const StringVector &name_in, const StringVector &name_out, const Dict &opts=Dict())
To resolve ambiguity on some compilers.
Function (const std::string &name, const SXVector &ex_in, SXIList ex_out, const StringVector &name_in, const StringVector &name_out, const Dict &opts=Dict())
To resolve ambiguity on some compilers.
Function (const std::string &name, SXIList ex_in, SXIList ex_out, const StringVector &name_in, const StringVector &name_out, const Dict &opts=Dict())
To resolve ambiguity on some compilers.
Function (const std::string &name, MXIList ex_in, const MXVector &ex_out, const Dict &opts=Dict())
To resolve ambiguity on some compilers.
Function (const std::string &name, const MXVector &ex_in, MXIList ex_out, const Dict &opts=Dict())
To resolve ambiguity on some compilers.
Function (const std::string &name, MXIList ex_in, MXIList ex_out, const Dict &opts=Dict())
To resolve ambiguity on some compilers.
Function (const std::string &name, MXIList ex_in, const MXVector &ex_out, const StringVector &name_in, const StringVector &name_out, const Dict &opts=Dict())
To resolve ambiguity on some compilers.
Function (const std::string &name, const MXVector &ex_in, MXIList ex_out, const StringVector &name_in, const StringVector &name_out, const Dict &opts=Dict())
To resolve ambiguity on some compilers.
Function (const std::string &name, MXIList ex_in, MXIList ex_out, const StringVector &name_in, const StringVector &name_out, const Dict &opts=Dict())
To resolve ambiguity on some compilers.
Function expand () const
Expand a function to SX.
Function expand (const std::string &name, const Dict &opts=Dict()) const
Expand a function to SX.
casadi_int size1_in (casadi_int ind) const
Get input dimension.
casadi_int size1_in (const std::string &iname) const
Get input dimension.
casadi_int size2_in (casadi_int ind) const
Get input dimension.
casadi_int size2_in (const std::string &iname) const
Get input dimension.
std::pair< casadi_int, casadi_int > size_in (casadi_int ind) const
Get input dimension.
std::pair< casadi_int, casadi_int > size_in (const std::string &iname) const
Get input dimension.
casadi_int size1_out (casadi_int ind) const
Get output dimension.
casadi_int size1_out (const std::string &oname) const
Get output dimension.
casadi_int size2_out (casadi_int ind) const
Get output dimension.
casadi_int size2_out (const std::string &oname) const
Get output dimension.
std::pair< casadi_int, casadi_int > size_out (casadi_int ind) const
Get output dimension.
std::pair< casadi_int, casadi_int > size_out (const std::string &oname) const
Get output dimension.
casadi_int nnz_in () const
Get number of input nonzeros.
casadi_int nnz_in (casadi_int ind) const
Get number of input nonzeros.
casadi_int nnz_in (const std::string &iname) const
Get number of input nonzeros.
casadi_int nnz_out () const
Get number of output nonzeros.
casadi_int nnz_out (casadi_int ind) const
Get number of output nonzeros.
casadi_int nnz_out (const std::string &oname) const
Get number of output nonzeros.
casadi_int numel_in () const
Get number of input elements.
casadi_int numel_in (casadi_int ind) const
Get number of input elements.
casadi_int numel_in (const std::string &iname) const
Get number of input elements.
casadi_int numel_out () const
Get number of output elements.
casadi_int numel_out (casadi_int ind) const
Get number of output elements.
casadi_int numel_out (const std::string &oname) const
Get number of output elements.
const Sparsity & sparsity_in (casadi_int ind) const
Get sparsity of a given input.
const Sparsity & sparsity_in (const std::string &iname) const
Get sparsity of a given input.
const Sparsity & sparsity_out (casadi_int ind) const
Get sparsity of a given output.
const Sparsity & sparsity_out (const std::string &iname) const
Get sparsity of a given output.
bool is_diff_in (casadi_int ind) const
Get differentiability of inputs/output.
bool is_diff_out (casadi_int ind) const
Get differentiability of inputs/output.
std::vector< bool > is_diff_in () const
Get differentiability of inputs/output.
std::vector< bool > is_diff_out () const
Get differentiability of inputs/output.
const Sparsity sparsity_jac (casadi_int iind, casadi_int oind, bool compact=false, bool symmetric=false) const
const Sparsity sparsity_jac (const std::string &iind, casadi_int oind=0, bool compact=false, bool symmetric=false) const
const Sparsity sparsity_jac (casadi_int iind, const std::string &oind, bool compact=false, bool symmetric=false) const
const Sparsity sparsity_jac (const std::string &iind, const std::string &oind, bool compact=false, bool symmetric=false) const
void call (const std::vector< DM > &arg, std::vector< DM > &res, bool always_inline=false, bool never_inline=false) const
Evaluate the function symbolically or numerically.
void call (const std::vector< SX > &arg, std::vector< SX > &res, bool always_inline=false, bool never_inline=false) const
Evaluate the function symbolically or numerically.
void call (const std::vector< MX > &arg, std::vector< MX > &res, bool always_inline=false, bool never_inline=false) const
Evaluate the function symbolically or numerically.
void call (const DMDict &arg, DMDict &res, bool always_inline=false, bool never_inline=false) const
Evaluate the function symbolically or numerically.
void call (const SXDict &arg, SXDict &res, bool always_inline=false, bool never_inline=false) const
Evaluate the function symbolically or numerically.
void call (const MXDict &arg, MXDict &res, bool always_inline=false, bool never_inline=false) const
Evaluate the function symbolically or numerically.
std::vector< DM > operator() (const std::vector< DM > &arg) const
std::vector< SX > operator() (const std::vector< SX > &arg) const
std::vector< MX > operator() (const std::vector< MX > &arg) const
const DMDict operator() (const DMDict &arg) const
const SXDict operator() (const SXDict &arg) const
const MXDict operator() (const MXDict &arg) const
void operator() (std::vector< const double * > arg, std::vector< double * > res) const
Evaluate with temporary memory allocation.
void operator() (std::vector< const bvec_t * > arg, std::vector< bvec_t * > res) const
Evaluate with temporary memory allocation.
void operator() (std::vector< const SXElem * > arg, std::vector< SXElem * > res) const
Evaluate with temporary memory allocation.
template<typename D >
void call_gen (std::vector< const D * > arg, std::vector< D * > res) const
Evaluate with temporary memory allocation.
void operator() (VecArg arg, VecRes res) const
Numerical evaluation.
void operator() (VecArg arg, MapRes res) const
Numerical evaluation.
void operator() (VecArg arg, VPrRes res) const
Numerical evaluation.
void operator() (VecArg arg, MPrRes res) const
Numerical evaluation.
void operator() (MapArg arg, VecRes res) const
Numerical evaluation.
void operator() (MapArg arg, MapRes res) const
Numerical evaluation.
void operator() (MapArg arg, VPrRes res) const
Numerical evaluation.
void operator() (MapArg arg, MPrRes res) const
Numerical evaluation.
std::vector< DM > operator() (const DM &arg0) const
std::vector< SX > operator() (const SX &arg0) const
std::vector< MX > operator() (const MX &arg0) const
Function mapaccum (const std::string &name, casadi_int N, const Dict &opts=Dict()) const
Create a mapaccumulated version of this function.
Function mapaccum (const std::string &name, casadi_int N, casadi_int n_accum, const Dict &opts=Dict()) const
Create a mapaccumulated version of this function.
Function mapaccum (const std::string &name, casadi_int n, const std::vector< casadi_int > &accum_in, const std::vector< casadi_int > &accum_out, const Dict &opts=Dict()) const
Create a mapaccumulated version of this function.
Function mapaccum (const std::string &name, casadi_int n, const std::vector< std::string > &accum_in, const std::vector< std::string > &accum_out, const Dict &opts=Dict()) const
Create a mapaccumulated version of this function.
Function mapaccum (casadi_int N, const Dict &opts=Dict()) const
Create a mapaccumulated version of this function.
Function fold (casadi_int N, const Dict &opts=Dict()) const
Create a mapaccumulated version of this function.
Function map (const std::string &name, const std::string &parallelization, casadi_int n, const std::vector< casadi_int > &reduce_in, const std::vector< casadi_int > &reduce_out, const Dict &opts=Dict()) const
Map with reduction.
Function map (const std::string &name, const std::string &parallelization, casadi_int n, const std::vector< std::string > &reduce_in, const std::vector< std::string > &reduce_out, const Dict &opts=Dict()) const
Map with reduction.
Function map (casadi_int n, const std::vector< bool > &reduce_in, const std::vector< bool > &reduce_out=std::vector< bool >(), const Dict &opts=Dict()) const
Map with reduction.
void generate_in (const std::string &fname, const std::vector< DM > &arg)
Export an input file that can be passed to generate C code with a main.
std::vector< DM > generate_in (const std::string &fname)
Export an input file that can be passed to generate C code with a main.
void generate_out (const std::string &fname, const std::vector< DM > &arg)
Export an output file that can be checked with generated C code output.
std::vector< DM > generate_out (const std::string &fname)
Export an output file that can be checked with generated C code output.
void export_code (const std::string &lang, const std::string &fname, const Dict &options=Dict()) const
Export function in specific language.
void serialize (std::ostream &stream, const Dict &opts=Dict()) const
Serialize.
void serialize (SerializingStream &s) const
Serialize an object.
std::string serialize (const Dict &opts=Dict()) const
Serialize.
void save (const std::string &fname, const Dict &opts=Dict()) const
Save Function to a file.
std::string export_code (const std::string &lang, const Dict &options=Dict()) const
Export function in specific language.
void export_code (const std::string &lang, std::ostream &stream, const Dict &options=Dict()) const
Export function in specific language.
const SX sx_in (casadi_int iind) const
Get symbolic primitives equivalent to the input expressions.
const SX sx_in (const std::string &iname) const
Get symbolic primitives equivalent to the input expressions.
const std::vector< SX > sx_in () const
Get symbolic primitives equivalent to the input expressions.
const MX mx_in (casadi_int ind) const
Get symbolic primitives equivalent to the input expressions.
const MX mx_in (const std::string &iname) const
Get symbolic primitives equivalent to the input expressions.
const std::vector< MX > mx_in () const
Get symbolic primitives equivalent to the input expressions.
const SX sx_out (casadi_int oind) const
Get symbolic primitives equivalent to the output expressions.
const SX sx_out (const std::string &oname) const
Get symbolic primitives equivalent to the output expressions.
const std::vector< SX > sx_out () const
Get symbolic primitives equivalent to the output expressions.
const MX mx_out (casadi_int ind) const
Get symbolic primitives equivalent to the output expressions.
const MX mx_out (const std::string &oname) const
Get symbolic primitives equivalent to the output expressions.
const std::vector< MX > mx_out () const
Get symbolic primitives equivalent to the output expressions.
std::vector< double > nz_from_in (const std::vector< DM > &arg) const
Convert from/to flat vector of input/output nonzeros.
std::vector< double > nz_from_out (const std::vector< DM > &arg) const
Convert from/to flat vector of input/output nonzeros.
std::vector< DM > nz_to_in (const std::vector< double > &arg) const
Convert from/to flat vector of input/output nonzeros.
std::vector< DM > nz_to_out (const std::vector< double > &arg) const
Convert from/to flat vector of input/output nonzeros.
DMDict convert_in (const std::vector< DM > &arg) const
Convert from/to input/output lists/map.
std::vector< DM > convert_in (const DMDict &arg) const
Convert from/to input/output lists/map.
DMDict convert_out (const std::vector< DM > &arg) const
Convert from/to input/output lists/map.
std::vector< DM > convert_out (const DMDict &arg) const
Convert from/to input/output lists/map.
SXDict convert_in (const std::vector< SX > &arg) const
Convert from/to input/output lists/map.
std::vector< SX > convert_in (const SXDict &arg) const
Convert from/to input/output lists/map.
SXDict convert_out (const std::vector< SX > &arg) const
Convert from/to input/output lists/map.
std::vector< SX > convert_out (const SXDict &arg) const
Convert from/to input/output lists/map.
MXDict convert_in (const std::vector< MX > &arg) const
Convert from/to input/output lists/map.
std::vector< MX > convert_in (const MXDict &arg) const
Convert from/to input/output lists/map.
MXDict convert_out (const std::vector< MX > &arg) const
Convert from/to input/output lists/map.
std::vector< MX > convert_out (const MXDict &arg) const
Convert from/to input/output lists/map.
bool has_spfwd () const
Is the class able to propagate seeds through the algorithm?
bool has_sprev () const
Is the class able to propagate seeds through the algorithm?
Static Public Member Functions
static std::string type_name ()
Get type name.
static Function create (FunctionInternal *node)
Create from node.
static Function create (FunctionInternal *node, const Dict &opts)
Create from node and initialize.
static Function conditional (const std::string &name, const std::vector< Function > &f, const Function &f_def, const Dict &opts=Dict())
Constuct a switch function.
static Function conditional (const std::string &name, const Function &f, const Dict &opts=Dict())
Conditional call to a function.
static Function bspline (const std::string &name, const std::vector< std::vector< double > > &knots, const std::vector< double > &coeffs, const std::vector< casadi_int > &degree, casadi_int m=1, const Dict &opts=Dict())
BSpline evaluator function.
static Function if_else (const std::string &name, const Function &f_true, const Function &f_false, const Dict &opts=Dict())
Constructor (if-else)
static bool test_cast (const SharedObjectInternal *ptr)
Check if a particular cast is allowed.
static bool check_name (const std::string &name)
Check if a string is a valid function name.
static std::string fix_name (const std::string &name)
Turn a string into a valid function name as defined by "check_name".
static Function deserialize (std::istream &stream)
Build function from serialization.
static Function deserialize (const std::string &s)
Build function from serialization.
static Function load (const std::string &filename)
Build function from serialization.
static Function deserialize (DeserializingStream &s)
Build function from serialization.
static Function jit (const std::string &name, const std::string &body, const std::vector< std::string > &name_in, const std::vector< std::string > &name_out, const Dict &opts=Dict())
Create a just-in-time compiled function from a C language string.
static Function jit (const std::string &name, const std::string &body, const std::vector< std::string > &name_in, const std::vector< std::string > &name_out, const std::vector< Sparsity > &sparsity_in, const std::vector< Sparsity > &sparsity_out, const Dict &opts=Dict())
Create a just-in-time compiled function from a C language string.
Protected Member Functions
Function mapaccum (const std::string &name, const std::vector< Function > &chain, casadi_int n_accum=1, const Dict &opts=Dict()) const
Helper function for mapaccum.
void count_up ()
void count_down ()
void construct (const std::string &name, const std::vector< SX > &ex_in, const std::vector< SX > &ex_out, const std::vector< std::string > &name_in, const std::vector< std::string > &name_out, const Dict &opts)
Called by constructors.
void construct (const std::string &name, const std::vector< MX > &ex_in, const std::vector< MX > &ex_out, const std::vector< std::string > &name_in, const std::vector< std::string > &name_out, const Dict &opts)
Called by constructors.
template<typename M >
void construct (const std::string &name, const std::map< std::string, M > &dict, const std::vector< std::string > &name_in, const std::vector< std::string > &name_out, const Dict &opts)
Called by constructors.
Static Protected Member Functions
static bool proceed_to (std::istream &file, const std::string &str)
Helper function for parsing .casadi files.
typedef const std::vector< std::vector< double > > & VecArg
Supported arguments for numerical evaluation and converters.
typedef std::vector< std::vector< double > > & VecRes
Supported arguments for numerical evaluation and converters.
typedef std::vector< std::vector< double > * > VPrRes
Supported arguments for numerical evaluation and converters.
typedef const std::map< std::string, std::vector< double > > & MapArg
Supported arguments for numerical evaluation and converters.
typedef std::map< std::string, std::vector< double > > & MapRes
Supported arguments for numerical evaluation and converters.
typedef std::map< std::string, std::vector< double > * > MPrRes
Supported arguments for numerical evaluation and converters.
std::vector< const double * > buf_in (VecArg arg) const
Supported arguments for numerical evaluation and converters.
std::vector< double * > buf_out (VecRes res) const
Supported arguments for numerical evaluation and converters.
std::vector< double * > buf_out (VPrRes res) const
Supported arguments for numerical evaluation and converters.
std::vector< const double * > buf_in (MapArg arg) const
Supported arguments for numerical evaluation and converters.
std::vector< double * > buf_out (MapRes res) const
Supported arguments for numerical evaluation and converters.
std::vector< double * > buf_out (MPrRes res) const
Supported arguments for numerical evaluation and converters.
Member Typedef Documentation
AuxOut
typedef std::map<std::string, std::vector<std::string> > casadi::Function::AuxOut
Definition at line 395 of file function.hpp.
MapArg
typedef const std::map<std::string, std::vector<double> >& casadi::Function::MapArg
Extra doc: https://github.com/casadi/casadi/wiki/L_1w9
Definition at line 563 of file function.hpp.
MapRes
typedef std::map<std::string, std::vector<double> >& casadi::Function::MapRes
Extra doc: https://github.com/casadi/casadi/wiki/L_1w9
Definition at line 565 of file function.hpp.
MPrRes
typedef std::map<std::string, std::vector<double>*> casadi::Function::MPrRes
Extra doc: https://github.com/casadi/casadi/wiki/L_1w9
Definition at line 567 of file function.hpp.
VecArg
typedef const std::vector<std::vector<double> >& casadi::Function::VecArg
Extra doc: https://github.com/casadi/casadi/wiki/L_1w9
Definition at line 556 of file function.hpp.
VecRes
typedef std::vector<std::vector<double> >& casadi::Function::VecRes
Extra doc: https://github.com/casadi/casadi/wiki/L_1w9
Definition at line 558 of file function.hpp.
VPrRes
typedef std::vector<std::vector<double>*> casadi::Function::VPrRes
Extra doc: https://github.com/casadi/casadi/wiki/L_1w9
Definition at line 560 of file function.hpp.
Constructor & Destructor Documentation
Function() [1/20]
casadi::Function::Function ()
Extra doc: https://github.com/casadi/casadi/wiki/L_1uy
Definition at line 56 of file function.cpp.
                      {
   }
Referenced by bspline(), deserialize(), expand(), find_function(), fold(), map(), and mapaccum().
Function() [2/20]
casadi::Function::Function (const std::string & fname)
Extra doc: https://github.com/casadi/casadi/wiki/L_1uz
Definition at line 90 of file function.cpp.
{
     casadi_error("Not implemented");
   }
Function() [3/20]
casadi::Function::Function (const std::string & name, const std::vector< SX > & ex_in, const std::vector< SX > & ex_out, const Dict & opts = Dict())
Extra doc: https://github.com/casadi/casadi/wiki/L_1v0
Definition at line 94 of file function.cpp.
{
     construct(name, ex_in, ex_out, {}, {}, opts);
   }
References construct(), and name().
Function() [4/20]
casadi::Function::Function (const std::string & name, const std::vector< SX > & ex_in, const std::vector< SX > & ex_out, const std::vector< std::string > & name_in, const std::vector< std::string > & name_out, const Dict & opts = Dict())
Extra doc: https://github.com/casadi/casadi/wiki/L_1v0
Definition at line 100 of file function.cpp.
{
     construct(name, ex_in, ex_out, name_in, name_out, opts);
   }
References construct(), name(), name_in(), and name_out().
Function() [5/20]
casadi::Function::Function (const std::string & name, const std::map< std::string, SX > & dict, const std::vector< std::string > & name_in, const std::vector< std::string > & name_out, const Dict & opts = Dict())
Extra doc: https://github.com/casadi/casadi/wiki/L_1v0
Definition at line 181 of file function.cpp.
{
     construct(name, dict, name_in, name_out, opts);
   }
References construct(), name(), name_in(), and name_out().
Function() [6/20]
casadi::Function::Function (const std::string & name, const std::vector< MX > & ex_in, const std::vector< MX > & ex_out, const Dict & opts = Dict())
Extra doc: https://github.com/casadi/casadi/wiki/L_1v1
Definition at line 108 of file function.cpp.
{
     construct(name, ex_in, ex_out, {}, {}, opts);
   }
References construct(), and name().
Function() [7/20]
casadi::Function::Function (const std::string & name, const std::vector< MX > & ex_in, const std::vector< MX > & ex_out, const std::vector< std::string > & name_in, const std::vector< std::string > & name_out, const Dict & opts = Dict())
Extra doc: https://github.com/casadi/casadi/wiki/L_1v1
Definition at line 114 of file function.cpp.
{
     construct(name, ex_in, ex_out, name_in, name_out, opts);
   }
References construct(), name(), name_in(), and name_out().
Function() [8/20]
casadi::Function::Function (const std::string & name, const std::map< std::string, MX > & dict, const std::vector< std::string > & name_in, const std::vector< std::string > & name_out, const Dict & opts = Dict())
Extra doc: https://github.com/casadi/casadi/wiki/L_1v1
Definition at line 187 of file function.cpp.
{
     construct(name, dict, name_in, name_out, opts);
   }
References construct(), name(), name_in(), and name_out().
Function() [9/20]
casadi::Function::Function (const std::string & name, SXIList ex_in, const SXVector & ex_out, const Dict & opts = Dict())
Extra doc: https://github.com/casadi/casadi/wiki/L_1v2
Definition at line 122 of file function.cpp.
{
     construct(name, SXVector(ex_in), ex_out, {}, {}, opts);
   }
References construct(), and name().
Function() [10/20]
casadi::Function::Function (const std::string & name, const SXVector & ex_in, SXIList ex_out, const Dict & opts = Dict())
Extra doc: https://github.com/casadi/casadi/wiki/L_1v2
Definition at line 127 of file function.cpp.
{
     construct(name, ex_in, SXVector(ex_out), {}, {}, opts);
   }
References construct(), and name().
Function() [11/20]
casadi::Function::Function (const std::string & name, SXIList ex_in, SXIList ex_out, const Dict & opts = Dict())
Extra doc: https://github.com/casadi/casadi/wiki/L_1v2
Definition at line 132 of file function.cpp.
{
     construct(name, SXVector(ex_in), SXVector(ex_out), {}, {}, opts);
   }
References construct(), and name().
Function() [12/20]
casadi::Function::Function (const std::string & name, SXIList ex_in, const SXVector & ex_out, const StringVector & name_in, const StringVector & name_out, const Dict & opts = Dict())
Extra doc: https://github.com/casadi/casadi/wiki/L_1v2
Definition at line 136 of file function.cpp.
{
     construct(name, SXVector(ex_in), ex_out, name_in, name_out, opts);
   }
References construct(), name(), name_in(), and name_out().
Function() [13/20]
casadi::Function::Function (const std::string & name, const SXVector & ex_in, SXIList ex_out, const StringVector & name_in, const StringVector & name_out, const Dict & opts = Dict())
Extra doc: https://github.com/casadi/casadi/wiki/L_1v2
Definition at line 142 of file function.cpp.
{
     construct(name, ex_in, SXVector(ex_out), name_in, name_out, opts);
   }
References construct(), name(), name_in(), and name_out().
Function() [14/20]
casadi::Function::Function (const std::string & name, SXIList ex_in, SXIList ex_out, const StringVector & name_in, const StringVector & name_out, const Dict & opts = Dict())
Extra doc: https://github.com/casadi/casadi/wiki/L_1v2
Definition at line 147 of file function.cpp.
{
     construct(name, SXVector(ex_in), SXVector(ex_out), name_in, name_out, opts);
   }
References construct(), name(), name_in(), and name_out().
Function() [15/20]
casadi::Function::Function (const std::string & name, MXIList ex_in, const MXVector & ex_out, const Dict & opts = Dict())
Extra doc: https://github.com/casadi/casadi/wiki/L_1v2
Definition at line 152 of file function.cpp.
{
     construct(name, MXVector(ex_in), ex_out, {}, {}, opts);
   }
References construct(), and name().
Function() [16/20]
casadi::Function::Function (const std::string & name, const MXVector & ex_in, MXIList ex_out, const Dict & opts = Dict())
Extra doc: https://github.com/casadi/casadi/wiki/L_1v2
Definition at line 157 of file function.cpp.
{
     construct(name, ex_in, MXVector(ex_out), {}, {}, opts);
   }
References construct(), and name().
Function() [17/20]
casadi::Function::Function (const std::string & name, MXIList ex_in, MXIList ex_out, const Dict & opts = Dict())
Extra doc: https://github.com/casadi/casadi/wiki/L_1v2
Definition at line 162 of file function.cpp.
{
     construct(name, MXVector(ex_in), MXVector(ex_out), {}, {}, opts);
   }
References construct(), and name().
Function() [18/20]
casadi::Function::Function (const std::string & name, MXIList ex_in, const MXVector & ex_out, const StringVector & name_in, const StringVector & name_out, const Dict & opts = Dict())
Extra doc: https://github.com/casadi/casadi/wiki/L_1v2
Definition at line 166 of file function.cpp.
{
     construct(name, MXVector(ex_in), ex_out, name_in, name_out, opts);
   }
References construct(), name(), name_in(), and name_out().
Function() [19/20]
casadi::Function::Function (const std::string & name, const MXVector & ex_in, MXIList ex_out, const StringVector & name_in, const StringVector & name_out, const Dict & opts = Dict())
Extra doc: https://github.com/casadi/casadi/wiki/L_1v2
Definition at line 171 of file function.cpp.
{
     construct(name, ex_in, MXVector(ex_out), name_in, name_out, opts);
   }
References construct(), name(), name_in(), and name_out().
Function() [20/20]
casadi::Function::Function (const std::string & name, MXIList ex_in, MXIList ex_out, const StringVector & name_in, const StringVector & name_out, const Dict & opts = Dict())
Extra doc: https://github.com/casadi/casadi/wiki/L_1v2
Definition at line 176 of file function.cpp.
{
     construct(name, MXVector(ex_in), MXVector(ex_out), name_in, name_out, opts);
   }
References construct(), name(), name_in(), and name_out().
~Function()
casadi::Function::~Function ()
Extra doc: https://github.com/casadi/casadi/wiki/L_1v4
Definition at line 59 of file function.cpp.
                       {
   }
Member Function Documentation
__hash__()
casadi_int casadi::SharedObject::__hash__ () const inherited
If the Object does not point to any node, "0" is returned.
Extra doc: https://github.com/casadi/casadi/wiki/L_av
Definition at line 129 of file shared_object.cpp.
{
     return reinterpret_cast<casadi_int>(get());
   }
References casadi::SharedObject::get().
assert_size_in()
void casadi::Function::assert_size_in (casadi_int i, casadi_int nrow, casadi_int ncol) const
Definition at line 1723 of file function.cpp.
{
     casadi_assert(size1_in(i)==nrow && size2_in(i)==ncol,
       "Incorrect shape for " + str(*this) + " input " + str(i) + " \""
       + name_in(i) + "\". Expected " + str(nrow) + "-by-" + str(ncol)
       + " but got " + str(size1_in(i)) +  "-by-" + str(size2_in(i)));
   }
References name_in(), size1_in(), size2_in(), and casadi::str().
Referenced by casadi::FunctionInternal::forward(), and casadi::FunctionInternal::reverse().
assert_size_out()
void casadi::Function::assert_size_out (casadi_int i, casadi_int nrow, casadi_int ncol) const
Definition at line 1731 of file function.cpp.
{
     casadi_assert(size1_out(i)==nrow && size2_out(i)==ncol,
       "Incorrect shape for " + str(*this) + " output " + str(i) + " \""
       + name_out(i) + "\". Expected " + str(nrow) + "-by-" + str(ncol)
       + " but got " + str(size1_out(i)) +  "-by-" + str(size2_out(i)));
   }
References name_out(), size1_out(), size2_out(), and casadi::str().
Referenced by assert_sparsity_out().
assert_sparsity_out()
void casadi::Function::assert_sparsity_out (casadi_int i, const Sparsity & sp, casadi_int n = 1, bool allow_all_zero_sparse = true) const
Definition at line 1738 of file function.cpp.
{
     // Assert shape
     assert_size_out(i, sp.size1(), sp.size2() * n);
     // Quick return if empty sparse
     if (allow_all_zero_sparse && sparsity_out(i).nnz() == 0) return;
     // Check sparsities
     casadi_assert(sparsity_out(i).is_stacked(sp, n), "Mismatching sparsity "
       "(but correct dimensions) for " + str(*this) + " output " + name_out(i));
   }
References assert_size_out(), name_out(), casadi::Sparsity::size1(), casadi::Sparsity::size2(), sparsity_out(), and casadi::str().
Referenced by casadi::FunctionInternal::forward(), and casadi::FunctionInternal::reverse().
assign()
void casadi::SharedObject::assign (SharedObjectInternal * node) inherited
improper use will cause memory leaks!
Extra doc: https://github.com/casadi/casadi/wiki/L_at
Definition at line 52 of file shared_object.cpp.
{
     node = node_;
   }
Referenced by casadi::GenericType::to_double_vector_vector().
bspline()
Function casadi::Function::bspline (const std::string & name, const std::vector< std::vector< double > > & knots, const std::vector< double > & coeffs, const std::vector< casadi_int > & degree, casadi_int m = 1, const Dict & opts = Dict()) static
Requires a known coefficient tensor
Extra doc: https://github.com/casadi/casadi/wiki/L_1wo
Definition at line 759 of file function.cpp.
{
     try {
       casadi_assert(degree.size()==knots.size(), "Degree list length (" + str(degree.size()) + ") "
                   "must match knot list length (" + str(knots.size()) + ").");
       MX x = MX::sym("x", degree.size());
       std::vector<std::string> lookup_mode;
       Dict opts_remainder = extract_from_dict(opts, "lookup_mode", lookup_mode);
       Dict opts_bspline;
       opts_bspline["lookup_mode"] = lookup_mode;
       MX y = MX::bspline(x, DM(coeffs), knots, degree, m, opts_bspline);
       return Function(name, {x}, {y}, opts_remainder);
     } catch(std::exception& e) {
       THROW_ERROR_NOOBJ("bspline", e.what(), "BSpline");
     }
   }
References casadi::MX::bspline(), casadi::extract_from_dict(), Function(), name(), casadi::str(), and casadi::GenericMatrix< MX >::sym().
buf_in() [1/2]
std::vector< const double * > casadi::Function::buf_in (Function::MapArg arg) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1w9
Definition at line 386 of file function.cpp.
{
     // Return value (RVO)
     std::vector<const double*> ret(sz_arg(), nullptr);
     // Read inputs
     for (auto i=arg.begin(); i!=arg.end(); ++i) {
       casadi_int ind = index_in(i->first);
       casadi_assert_dev(i->second.size()==nnz_in(ind));
       ret[ind] = get_ptr(i->second);
     }
     return ret;
   }
References casadi::get_ptr(), index_in(), nnz_in(), and sz_arg().
buf_in() [2/2]
std::vector< const double * > casadi::Function::buf_in (Function::VecArg arg) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1w9
Definition at line 352 of file function.cpp.
{
     casadi_assert_dev(arg.size()==n_in());
     auto arg_it=arg.begin();
     std::vector<const double*> buf_arg(sz_arg());
     for (casadi_uint i=0; i<arg.size(); ++i) {
       casadi_assert_dev(arg_it->size()==nnz_in(i));
       buf_arg[i] = get_ptr(*arg_it++);
     }
     return buf_arg;
   }
References casadi::get_ptr(), n_in(), nnz_in(), and sz_arg().
buf_out() [1/4]
std::vector< double * > casadi::Function::buf_out (Function::MapRes res) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1w9
Definition at line 400 of file function.cpp.
{
     // Return value (RVO)
     std::vector<double*> ret(sz_res(), nullptr);
     // Read outputs
     for (auto i=res.begin(); i!=res.end(); ++i) {
       casadi_int ind = index_out(i->first);
       i->second.resize(nnz_out(ind));
       ret[ind] = get_ptr(i->second);
     }
     return ret;
   }
References casadi::get_ptr(), index_out(), nnz_out(), and sz_res().
buf_out() [2/4]
std::vector< double * > casadi::Function::buf_out (Function::MPrRes res) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1w9
Definition at line 414 of file function.cpp.
{
     // Return value (RVO)
     std::vector<double*> ret(sz_res(), nullptr);
     // Read outputs
     for (auto i=res.begin(); i!=res.end(); ++i) {
       casadi_int ind = index_out(i->first);
       casadi_assert_dev(i->second!=0);
       i->second->resize(nnz_out(ind));
       ret[ind] = get_ptr(*i->second);
     }
     return ret;
   }
References casadi::get_ptr(), index_out(), nnz_out(), and sz_res().
buf_out() [3/4]
std::vector< double * > casadi::Function::buf_out (Function::VecRes res) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1w9
Definition at line 363 of file function.cpp.
{
     res.resize(n_out());
     auto res_it=res.begin();
     std::vector<double*> buf_res(sz_res());
     for (casadi_uint i=0; i<res.size(); ++i) {
       res_it->resize(nnz_out(i));
       buf_res[i] = get_ptr(*res_it++);
     }
     return buf_res;
   }
References casadi::get_ptr(), n_out(), nnz_out(), and sz_res().
buf_out() [4/4]
std::vector< double * > casadi::Function::buf_out (Function::VPrRes res) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1w9
Definition at line 374 of file function.cpp.
{
     casadi_assert_dev(res.size()==n_out());
     auto res_it=res.begin();
     std::vector<double*> buf_res(sz_res());
     for (casadi_uint i=0; i<res.size(); ++i) {
       casadi_assert_dev(*res_it!=0);
       (*res_it)->resize(nnz_out(i));
       buf_res[i] = get_ptr(**res_it++);
     }
     return buf_res;
   }
References casadi::get_ptr(), n_out(), nnz_out(), and sz_res().
cache()
Dict casadi::Function::cache () const
Extra doc: https://github.com/casadi/casadi/wiki/L_26i
Definition at line 1773 of file function.cpp.
{
     try {
       return (*this)->cache();
     } catch(std::exception& e) {
       THROW_ERROR("cache", e.what());
       return {};
     }
   }
call() [1/6]
void casadi::Function::call (const DMDict & arg, DMDict & res, bool always_inline = false, bool never_inline = false) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1w7
Definition at line 1396 of file function.cpp.
{
     try {
       call_gen(arg, res, always_inline, never_inline);
     } catch(std::exception& e) {
       THROW_ERROR("call", e.what());
     }
   }
References call_gen().
call() [2/6]
void casadi::Function::call (const MXDict & arg, MXDict & res, bool always_inline = false, bool never_inline = false) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1w7
Definition at line 1414 of file function.cpp.
{
     try {
       call_gen(arg, res, always_inline, never_inline);
     } catch(std::exception& e) {
       THROW_ERROR("call", e.what());
     }
   }
References call_gen().
call() [3/6]
void casadi::Function::call (const std::vector< DM > & arg, std::vector< DM > & res, bool always_inline = false, bool never_inline = false) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1w7
Definition at line 325 of file function.cpp.
{
     try {
       (*this)->call(arg, res, always_inline, never_inline);
     } catch(std::exception& e) {
       THROW_ERROR("call", e.what());
     }
   }
Referenced by call_gen(), casadi::detect_simple_bounds_gen(), casadi::FunctionInternal::eval_mx(), map(), casadi::MX::matrix_expand(), operator()(), and casadi::MX::substitute().
call() [4/6]
void casadi::Function::call (const std::vector< MX > & arg, std::vector< MX > & res, bool always_inline = false, bool never_inline = false) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1w7
Definition at line 343 of file function.cpp.
{
     try {
       (*this)->call(arg, res, always_inline, never_inline);
     } catch(std::exception& e) {
       THROW_ERROR("call", e.what());
     }
   }
call() [5/6]
void casadi::Function::call (const std::vector< SX > & arg, std::vector< SX > & res, bool always_inline = false, bool never_inline = false) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1w7
Definition at line 334 of file function.cpp.
{
     try {
       (*this)->call(arg, res, always_inline, never_inline);
     } catch(std::exception& e) {
       THROW_ERROR("call", e.what());
     }
   }
call() [6/6]
void casadi::Function::call (const SXDict & arg, SXDict & res, bool always_inline = false, bool never_inline = false) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1w7
Definition at line 1405 of file function.cpp.
{
     try {
       call_gen(arg, res, always_inline, never_inline);
     } catch(std::exception& e) {
       THROW_ERROR("call", e.what());
     }
   }
References call_gen().
call_gen() [1/2]
template<typename M > void casadi::Function::call_gen (const std::map< std::string, M > & arg, std::map< std::string, M > & res, bool always_inline, bool never_inline) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1xu
Definition at line 1362 of file function.cpp.
{
     // Convert to vector arguments
     std::vector<M> arg_v = (*this)->convert_arg(arg);
     // Make call
     std::vector<M> res_v;
     call(arg_v, res_v, always_inline, never_inline);
     // Save to map
     res.clear();
     for (casadi_int i=0; i<res_v.size(); ++i) {
       res[name_out(i)] = res_v[i];
     }
   }
References call(), and name_out().
call_gen() [2/2]
template<typename D > void casadi::Function::call_gen (std::vector< const D * > arg, std::vector< D * > res) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1w8
Definition at line 430 of file function.cpp.
{
     // Input buffer
     casadi_assert_dev(arg.size()>=n_in());
     arg.resize(sz_arg());
     // Output buffer
     casadi_assert_dev(res.size()>=n_out());
     res.resize(sz_res());
     // Work vectors
     std::vector<casadi_int> iw(sz_iw());
     std::vector<D> w(sz_w());
     // Evaluate memoryless
     (*this)(get_ptr(arg), get_ptr(res), get_ptr(iw), get_ptr(w), 0);
   }
References casadi::get_ptr(), n_in(), n_out(), sz_arg(), sz_iw(), sz_res(), and sz_w().
Referenced by call(), and operator()().
change_option()
void casadi::Function::change_option (const std::string & option_name, const GenericType & option_value)
This is only possible for a selected number of options that do not change the numerical results of the computation, e.g. to enable a more verbose output or saving to file.
Extra doc: https://github.com/casadi/casadi/wiki/L_1w2
Definition at line 1116 of file function.cpp.
{
     try {
       // Assert existance
       if (!has_option(option_name))
         casadi_error("Option '" + option_name + "' does not exist");
       // Call internal class
       (*this)->change_option(option_name, option_value);
     } catch(std::exception& e) {
       THROW_ERROR("change_option", e.what());
     }
   }
References has_option().
check_name()
bool casadi::Function::check_name (const std::string & name) static
Valid function names consist of
At least one character
Upper and lower case letters: a-zA-Z
Numbers 0-9, but never as first character
Underscore, but never as first character and never next to another underscore
May not be one of the following keywords: "null", "jac", "hess"
Extra doc: https://github.com/casadi/casadi/wiki/L_1xx
Definition at line 1259 of file function.cpp.
{
     // Check if empty
     if (name.empty()) return false;
     // Check if keyword
     for (const char* kw : {"null", "jac", "hess"}) {
       if (name==kw) return false;
     }
     // Make sure that the first character is a letter
     auto it=name.begin();
     if (!std::isalpha(*it++)) return false;
     // Check remain_ing characters
     for (; it!=name.end(); ++it) {
       if (*it=='_') {
         // Make sure that the next character isn't also an underscore
         if (it+1!=name.end() && *(it+1)=='_') return false;
       } else {
         // Make sure alphanumeric
         if (!std::isalnum(*it)) return false;
       }
     }
     // Valid function name if reached this point
     return true;
   }
References name().
Referenced by casadi::CodeGenerator::CodeGenerator(), fix_name(), and casadi::FunctionInternal::FunctionInternal().
checkout()
casadi_int casadi::Function::checkout () const
Definition at line 1711 of file function.cpp.
{
     return (*this)->checkout();
   }
Referenced by casadi::QpToNlp::alloc_mem(), and casadi::FunctionBuffer::operator=().
class_name()
std::string casadi::SharedObject::class_name () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_au
Definition at line 99 of file shared_object.cpp.
{
     return (*this)->class_name();
   }
Referenced by casadi::MXFunction::export_code_body().
conditional() [1/2]
Function casadi::Function::conditional (const std::string & name, const Function & f, const Dict & opts = Dict()) static
Extra doc: https://github.com/casadi/casadi/wiki/L_1wn
Definition at line 742 of file function.cpp.
{
     try {
       // Create a dummy function with the same signature as f
       std::vector<MX> dummy_in = f.mx_in();
       std::vector<MX> dummy_out(f.n_out());
       for (casadi_int i = 0; i < dummy_out.size(); ++i) {
         dummy_out.at(i) = MX::zeros(f.sparsity_out(i));
       }
       Function dummy("dummy_" + f.name(), dummy_in, dummy_out, f.name_in(), f.name_out());
       // Form a conditional call
       return if_else(name, f, dummy, opts);
     } catch(std::exception& e) {
       THROW_ERROR_NOOBJ("conditional", e.what(), "Switch");
     }
   }
References if_else(), mx_in(), n_out(), name(), name_in(), name_out(), sparsity_out(), and casadi::GenericMatrix< MX >::zeros().
conditional() [2/2]
Function casadi::Function::conditional (const std::string & name, const std::vector< Function > & f, const Function & f_def, const Dict & opts = Dict()) static
Extra doc: https://github.com/casadi/casadi/wiki/L_1wm
Definition at line 733 of file function.cpp.
{
     try {
       return create(new Switch(name, f, f_def), opts);
     } catch(std::exception& e) {
       THROW_ERROR_NOOBJ("conditional", e.what(), "Switch");
     }
   }
References create(), and name().
Referenced by casadi::MX::conditional(), casadi::Switch::get_forward(), and casadi::Switch::get_reverse().
construct() [1/3]
template<typename M > void casadi::Function::construct (const std::string & name, const std::map< std::string, M > & dict, const std::vector< std::string > & name_in, const std::vector< std::string > & name_out, const Dict & opts) protected
Extra doc: https://github.com/casadi/casadi/wiki/L_1y8
Definition at line 194 of file function.cpp.
{
     std::vector<M> ex_in(name_in.size()), ex_out(name_out.size());
     for (auto&& i : dict) {
       std::vector<std::string>::const_iterator it;
       if ((it = std::find(name_in.begin(), name_in.end(), i.first))!=name_in.end()) {
         // Input expression
         ex_in[it-name_in.begin()] = i.second;
       } else if ((it = std::find(name_out.begin(), name_out.end(), i.first))!=name_out.end()) {
         // Output expression
         ex_out[it-name_out.begin()] = i.second;
       } else {
         // Neither
         casadi_error("Unknown dictionary entry: '" + i.first + "'");
       }
     }
     construct(name, ex_in, ex_out, name_in, name_out, opts);
   }
References construct(), name(), name_in(), and name_out().
construct() [2/3]
void casadi::Function::construct (const std::string & name, const std::vector< MX > & ex_in, const std::vector< MX > & ex_out, const std::vector< std::string > & name_in, const std::vector< std::string > & name_out, const Dict & opts) protected
Extra doc: https://github.com/casadi/casadi/wiki/L_1y8
Definition at line 228 of file function.cpp.
{
     try {
       own(new MXFunction(name, ex_in, ex_out, name_in, name_out));
       (*this)->construct(opts);
       // Perform post-construction expand
       auto it = opts.find("post_expand");
       if (it!=opts.end()) {
         if (!it->second) return;
         auto it = opts.find("post_expand_options");
         if (it==opts.end()) {
           operator=((*this).expand());
         } else {
           operator=((*this).expand((*this).name(), it->second));
         }
       }
     } catch(std::exception& e) {
       THROW_ERROR_NOOBJ("Function", e.what(), "MXFunction");
     }
   }
References name(), name_in(), name_out(), casadi::SharedObject::operator=(), and casadi::SharedObject::own().
construct() [3/3]
void casadi::Function::construct (const std::string & name, const std::vector< SX > & ex_in, const std::vector< SX > & ex_out, const std::vector< std::string > & name_in, const std::vector< std::string > & name_out, const Dict & opts) protected
Extra doc: https://github.com/casadi/casadi/wiki/L_1y8
Definition at line 215 of file function.cpp.
{
     try {
       own(new SXFunction(name, ex_in, ex_out, name_in, name_out));
       (*this)->construct(opts);
     } catch(std::exception& e) {
       THROW_ERROR_NOOBJ("Function", e.what(), "SXFunction");
     }
   }
References name(), name_in(), name_out(), and casadi::SharedObject::own().
Referenced by construct(), and Function().
convert_in() [1/6]
std::vector< DM > casadi::Function::convert_in (const DMDict & arg) const
Will raise an error when an unknown key is used or a list has incorrect size. Does not perform sparsity checking.
Extra doc: https://github.com/casadi/casadi/wiki/L_1x7
Definition at line 1563 of file function.cpp.
{
     return (*this)->convert_arg(arg);
   }
convert_in() [2/6]
std::vector< MX > casadi::Function::convert_in (const MXDict & arg) const
Will raise an error when an unknown key is used or a list has incorrect size. Does not perform sparsity checking.
Extra doc: https://github.com/casadi/casadi/wiki/L_1x7
Definition at line 1595 of file function.cpp.
{
     return (*this)->convert_arg(arg);
   }
convert_in() [3/6]
DMDict casadi::Function::convert_in (const std::vector< DM > & arg) const
Will raise an error when an unknown key is used or a list has incorrect size. Does not perform sparsity checking.
Extra doc: https://github.com/casadi/casadi/wiki/L_1x7
Definition at line 1559 of file function.cpp.
{
     return (*this)->convert_arg(arg);
   }
convert_in() [4/6]
MXDict casadi::Function::convert_in (const std::vector< MX > & arg) const
Will raise an error when an unknown key is used or a list has incorrect size. Does not perform sparsity checking.
Extra doc: https://github.com/casadi/casadi/wiki/L_1x7
Definition at line 1591 of file function.cpp.
{
     return (*this)->convert_arg(arg);
   }
convert_in() [5/6]
SXDict casadi::Function::convert_in (const std::vector< SX > & arg) const
Will raise an error when an unknown key is used or a list has incorrect size. Does not perform sparsity checking.
Extra doc: https://github.com/casadi/casadi/wiki/L_1x7
Definition at line 1575 of file function.cpp.
{
     return (*this)->convert_arg(arg);
   }
convert_in() [6/6]
std::vector< SX > casadi::Function::convert_in (const SXDict & arg) const
Will raise an error when an unknown key is used or a list has incorrect size. Does not perform sparsity checking.
Extra doc: https://github.com/casadi/casadi/wiki/L_1x7
Definition at line 1579 of file function.cpp.
{
     return (*this)->convert_arg(arg);
   }
convert_out() [1/6]
std::vector< DM > casadi::Function::convert_out (const DMDict & arg) const
Will raise an error when an unknown key is used or a list has incorrect size. Does not perform sparsity checking.
Extra doc: https://github.com/casadi/casadi/wiki/L_1x7
Definition at line 1571 of file function.cpp.
{
     return (*this)->convert_res(arg);
   }
convert_out() [2/6]
std::vector< MX > casadi::Function::convert_out (const MXDict & arg) const
Will raise an error when an unknown key is used or a list has incorrect size. Does not perform sparsity checking.
Extra doc: https://github.com/casadi/casadi/wiki/L_1x7
Definition at line 1603 of file function.cpp.
{
     return (*this)->convert_res(arg);
   }
convert_out() [3/6]
DMDict casadi::Function::convert_out (const std::vector< DM > & arg) const
Will raise an error when an unknown key is used or a list has incorrect size. Does not perform sparsity checking.
Extra doc: https://github.com/casadi/casadi/wiki/L_1x7
Definition at line 1567 of file function.cpp.
{
     return (*this)->convert_res(arg);
   }
convert_out() [4/6]
MXDict casadi::Function::convert_out (const std::vector< MX > & arg) const
Will raise an error when an unknown key is used or a list has incorrect size. Does not perform sparsity checking.
Extra doc: https://github.com/casadi/casadi/wiki/L_1x7
Definition at line 1599 of file function.cpp.
{
     return (*this)->convert_res(arg);
   }
convert_out() [5/6]
SXDict casadi::Function::convert_out (const std::vector< SX > & arg) const
Will raise an error when an unknown key is used or a list has incorrect size. Does not perform sparsity checking.
Extra doc: https://github.com/casadi/casadi/wiki/L_1x7
Definition at line 1583 of file function.cpp.
{
     return (*this)->convert_res(arg);
   }
convert_out() [6/6]
std::vector< SX > casadi::Function::convert_out (const SXDict & arg) const
Will raise an error when an unknown key is used or a list has incorrect size. Does not perform sparsity checking.
Extra doc: https://github.com/casadi/casadi/wiki/L_1x7
Definition at line 1587 of file function.cpp.
{
     return (*this)->convert_res(arg);
   }
count_down()
void casadi::SharedObject::count_down () protected inherited
Definition at line 84 of file shared_object.cpp.
{
 #ifdef WITH_EXTRA_CHECKS
     casadi_assert_dev(Function::call_depth_==0);
 #endif // WITH_EXTRA_CHECKS
     if (node && --node->count == 0) {
       delete node;
       node = nullptr;
     }
   }
Referenced by casadi::SharedObject::operator=(), casadi::SharedObject::own(), and casadi::SharedObject::~SharedObject().
count_up()
void casadi::SharedObject::count_up () protected inherited
Definition at line 77 of file shared_object.cpp.
{
 #ifdef WITH_EXTRA_CHECKS
     casadi_assert_dev(Function::call_depth_==0);
 #endif // WITH_EXTRA_CHECKS
     if (node) node->count++;
   }
Referenced by casadi::SharedObject::operator=(), casadi::SharedObject::own(), and casadi::SharedObject::SharedObject().
create() [1/2]
Function casadi::Function::create (FunctionInternal * node) static
Extra doc: https://github.com/casadi/casadi/wiki/L_1v6
Definition at line 304 of file function.cpp.
{
     Function ret;
     ret.own(node);
     return ret;
   }
References casadi::SharedObject::own().
Referenced by conditional(), casadi::conic(), casadi::Interpolant::construct(), casadi::MapSum::create(), casadi::Map::create(), create(), casadi::Integrator::create_advanced(), casadi::FixedStepIntegrator::create_advanced(), casadi::dplesol(), casadi::expmsol(), casadi::DaeBuilderInternal::export_fmu(), casadi::external(), casadi::DaeBuilderInternal::fmu_fun(), casadi::FunctionInternal::forward(), casadi::ForwardDiff::get_forward(), casadi::CentralDiff::get_forward(), casadi::Smoothing::get_forward(), if_else(), jit(), casadi::nlpsol(), casadi::rootfinder(), and casadi::OptiNode::solve().
create() [2/2]
Function casadi::Function::create (FunctionInternal * node, const Dict & opts) static
Extra doc: https://github.com/casadi/casadi/wiki/L_1v7
Definition at line 310 of file function.cpp.
{
     Function ret = create(node);
     ret->construct(opts);
     return ret;
   }
References casadi::ProtoFunction::construct(), and create().
default_in()
double casadi::Function::default_in (casadi_int ind) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1vm
Definition at line 1423 of file function.cpp.
{
     return (*this)->get_default_in(ind);
   }
Referenced by casadi::Blocksqp::feasibilityRestorationPhase(), and casadi::FiniteDiff::get_default_in().
deserialize() [1/3]
Function casadi::Function::deserialize (const std::string & s) static
Extra doc: https://github.com/casadi/casadi/wiki/L_1y0
Definition at line 1302 of file function.cpp.
{
     std::stringstream ss;
     ss << s;
     return deserialize(ss);
   }
References deserialize().
deserialize() [2/3]
Function casadi::Function::deserialize (DeserializingStream & s) static
Extra doc: https://github.com/casadi/casadi/wiki/L_1y2
Definition at line 1237 of file function.cpp.
{
     bool is_null;
     s.unpack("Function::null", is_null);
     if (is_null) return Function();
     return FunctionInternal::deserialize(s);
   }
References casadi::FunctionInternal::deserialize(), Function(), casadi::SharedObject::is_null(), and casadi::DeserializingStream::unpack().
deserialize() [3/3]
Function casadi::Function::deserialize (std::istream & stream) static
Extra doc: https://github.com/casadi/casadi/wiki/L_1xz
Definition at line 1287 of file function.cpp.
{
     DeserializingStream s(stream);
     return deserialize(s);
   }
Referenced by deserialize().
disp()
void casadi::SharedObject::disp (std::ostream & stream, bool more = false) const inherited
Definition at line 103 of file shared_object.cpp.
{
     if (is_null()) {
       stream << "NULL";
     } else {
       (*this)->disp(stream, more);
     }
   }
References casadi::SharedObject::is_null().
Referenced by casadi::Nlpsol::disp_more(), and casadi::CsparseInterface::nfact().
expand() [1/2]
Function casadi::Function::expand () const
Extra doc: https://github.com/casadi/casadi/wiki/L_1v5
Examples
Function/expand.py, and MX/matrix_expand.py.
Definition at line 276 of file function.cpp.
{
     Dict opts;
     opts["ad_weight"] = (*this)->ad_weight();
     opts["ad_weight_sp"] = (*this)->sp_weight();
     opts["max_num_dir"] = (*this)->max_num_dir_;
     opts["is_diff_in"] = (*this)->is_diff_in_;
     opts["is_diff_out"] = (*this)->is_diff_out_;
     return expand(name(), opts);
   }
References casadi::FunctionInternal::ad_weight(), and name().
Referenced by casadi::OracleFunction::expand(), casadi::OracleFunction::init(), casadi::MX::matrix_expand(), and casadi::DaeBuilderInternal::oracle().
expand() [2/2]
Function casadi::Function::expand (const std::string & name, const Dict & opts = Dict()) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1v5
Definition at line 286 of file function.cpp.
{
     casadi_assert(!has_free(),
       "Function with free symbols cannot be expanded. "
       "List of free variables in your Function: " +
         join(get_free(), ","));
     Dict my_opts;
     my_opts["ad_weight"] = (*this)->ad_weight();
     my_opts["ad_weight_sp"] = (*this)->sp_weight();
     my_opts["max_num_dir"] = (*this)->max_num_dir_;
     my_opts["is_diff_in"] = (*this)->is_diff_in_;
     my_opts["is_diff_out"] = (*this)->is_diff_out_;
     update_dict(my_opts, opts);
     std::vector<SX> ex_in = sx_in();
     std::vector<SX> ex_out = Function(*this)(ex_in);
     return Function(name, ex_in, ex_out, name_in(), name_out(), my_opts);
   }
References Function(), get_free(), has_free(), casadi::join(), name(), name_in(), name_out(), sx_in(), and casadi::update_dict().
export_code() [1/3]
std::string casadi::Function::export_code (const std::string & lang, const Dict & options = Dict()) const
Only allowed for (a subset of) SX/MX Functions
Extra doc: https://github.com/casadi/casadi/wiki/L_1wz
Definition at line 1244 of file function.cpp.
{
     std::stringstream ss;
     (*this)->export_code(lang, ss, options);
     return ss.str();
   }
export_code() [2/3]
void casadi::Function::export_code (const std::string & lang, const std::string & fname, const Dict & options = Dict()) const
Only allowed for (a subset of) SX/MX Functions
Extra doc: https://github.com/casadi/casadi/wiki/L_1wz
Definition at line 1205 of file function.cpp.
{
     std::ofstream stream(fname);
     return (*this)->export_code(lang, stream, options);
   }
export_code() [3/3]
void casadi::Function::export_code (const std::string & lang, std::ostream & stream, const Dict & options = Dict()) const
Only allowed for (a subset of) SX/MX Functions
Extra doc: https://github.com/casadi/casadi/wiki/L_1wz
Definition at line 1200 of file function.cpp.
{
     return (*this)->export_code(lang, stream, options);
   }
factory()
Function casadi::Function::factory (const std::string & name, const std::vector< std::string > & s_in, const std::vector< std::string > & s_out, const AuxOut & aux = AuxOut(), const Dict & opts = Dict()) const
Definition at line 1749 of file function.cpp.
{
      try {
        return (*this)->factory(name, s_in, s_out, aux, opts);
      } catch(std::exception& e) {
        THROW_ERROR("factory", "Failed to create " + name + ":" + str(s_in) + "->" + str(s_out)
         + " with " + str(aux) + ":\n" + str(e.what()));
      }
   }
References casadi::FunctionInternal::factory(), name(), and casadi::str().
Referenced by casadi::DaeBuilderInternal::create(), casadi::OracleFunction::create_function(), casadi::FunctionInternal::factory(), casadi::KinsolInterface::get_jtimes(), hessian_old(), casadi::Rootfinder::init(), casadi::Blocksqp::init(), jacobian_old(), and casadi::Nlpsol::kkt().
find_function()
Function casadi::Function::find_function (const std::string & name, casadi_int max_depth = -1) const
Parameters
[in] name Name of function needed
[in] max_depth Maximum depth - a negative number indicates no maximum
Extra doc: https://github.com/casadi/casadi/wiki/L_1y7
Definition at line 1826 of file function.cpp.
{
     try {
       // If negative, make largest positive number
       if (max_depth < 0) max_depth = std::numeric_limits<casadi_int>::max();
       // The internal routine uses a map to avoid duplicate functions
       std::map<FunctionInternal*, Function> all_fun;
       (*this)->find(all_fun, max_depth);
       // Search this map
       for (auto&& e : all_fun) {
         if (e.second.name() == name) return e.second;
       }
       // Not found
       casadi_error("'" + name + "' not found");
     } catch(std::exception& e) {
       THROW_ERROR("find", e.what());
       return Function();
     }
   }
References Function(), and name().
find_functions()
std::vector< Function > casadi::Function::find_functions (casadi_int max_depth = -1) const
Parameters
[in] max_depth Maximum depth - a negative number indicates no maximum
Extra doc: https://github.com/casadi/casadi/wiki/L_1y6
Definition at line 1808 of file function.cpp.
{
     try {
       // If negative, make largest positive number
       if (max_depth < 0) max_depth = std::numeric_limits<casadi_int>::max();
       // The internal routine uses a map to avoid duplicate functions
       std::map<FunctionInternal*, Function> all_fun;
       (*this)->find(all_fun, max_depth);
       // Create return object
       std::vector<Function> ret;
       ret.reserve(all_fun.size());
       for (auto&& e : all_fun) ret.push_back(e.second);
       return ret;
     } catch(std::exception& e) {
       THROW_ERROR("find", e.what());
       return {};
     }
   }
Referenced by casadi::DaeBuilder::gather_fun().
fix_name()
std::string casadi::Function::fix_name (const std::string & name) static
Non-alphanumeric characters are converted into underscores and multiple consecutive undercores are dropped
Extra doc: https://github.com/casadi/casadi/wiki/L_1xy
Definition at line 1308 of file function.cpp.
{
     // Quick return if already valid name
     if (check_name(name)) return name;
     // If empty, name it "unnamed"
     if (name.empty()) return "unnamed";
     // Construct a sane name
     std::stringstream ss;
     // If the first character isn't a character, prepend an "a"
     if (!std::isalpha(name.front())) ss << "a";
     // Treat other characters
     bool previous_is_underscore = false;
     for (char c : name) {
       if (std::isalnum(c)) {
         // Alphanumeric characters
         ss << c;
         previous_is_underscore = false;
       } else if (!previous_is_underscore) {
         // Everything else becomes an underscore
         ss << '_';
         previous_is_underscore = true;
       }
     }
     // If name became a keyword, append 1
     for (const char* kw : {"null", "jac", "hess"}) {
       if (ss.str()==kw) ss << "1";
     }
     return ss.str();
   }
References check_name(), and name().
fold()
Function casadi::Function::fold (casadi_int N, const Dict & opts = Dict()) const
Suppose the function has a signature of:
   f: (x, u) -> (x_next , y )
The the mapaccumulated version has the signature:
   F: (x0, U) -> (X , Y )
    with
        U: horzcat([u0, u1, ..., u_(N-1)])
        X: horzcat([x1, x2, ..., x_N])
        Y: horzcat([y0, y1, ..., y_(N-1)])
    and
        x1, y0 <- f(x0, u0)
        x2, y1 <- f(x1, u1)
        ...
        x_N, y_(N-1) <- f(x_(N-1), u_(N-1))
Mapaccum has the following benefits over writing an equivalent for-loop:
much faster at construction time
potentially much faster compilation times (for codegen)
offers a trade-off between memory and evaluation time
The base (settable through the options dictionary, default 10), is used to create a tower of function calls, containing unrolled for-loops of length maximum base.
This technique is much more scalable in terms of memory-usage, but slightly slower at evaluation, than a plain for-loop. The effect is similar to that of a for-loop with a check-pointing instruction after each chunk of iterations with size base.
Set base to -1 to unroll all the way; no gains in memory efficiency here.
Extra doc: https://github.com/casadi/casadi/wiki/L_1wi
Definition at line 477 of file function.cpp.
{
     Function base = mapaccum(N, opts);
     std::vector<MX> base_in = base.mx_in();
     std::vector<MX> out = base(base_in);
     out[0] = out[0](Slice(), range((N-1)*size2_out(0), N*size2_out(0))); // NOLINT
     return Function("fold_"+name(), base_in, out, name_in(), name_out(), opts);
   }
References Function(), mapaccum(), mx_in(), name(), name_in(), name_out(), casadi::range(), and size2_out().
forward()
Function casadi::Function::forward (casadi_int nfwd) const
   Returns a function with <tt>n_in + n_out + n_in</tt> inputs
   and <tt>nfwd</tt> outputs.
   The first <tt>n_in</tt> inputs correspond to nondifferentiated inputs.
   The next <tt>n_out</tt> inputs correspond to nondifferentiated outputs.
   and the last <tt>n_in</tt> inputs correspond to forward seeds,
   stacked horizontally
   The  <tt>n_out</tt> outputs correspond to forward sensitivities,
   stacked horizontally.     *
   <tt>(n_in = n_in(), n_out = n_out())</tt>
  The functions returned are cached, meaning that if called multiple timed
  with the same value, then multiple references to the same function will be returned.
Extra doc: https://github.com/casadi/casadi/wiki/L_1wq
Definition at line 1079 of file function.cpp.
{
     try {
       return (*this)->forward(nfwd);
     } catch(std::exception& e) {
       THROW_ERROR("forward", e.what());
     }
   }
References casadi::FunctionInternal::forward().
Referenced by casadi::DaeBuilderInternal::export_fmu(), casadi::FunctionInternal::forward(), casadi::Map::get_forward(), casadi::MapSum::get_forward(), casadi::Nlpsol::get_forward(), casadi::Switch::get_forward(), and casadi::ImplicitFixedStepIntegrator::init().
free_mx()
std::vector< MX > casadi::Function::free_mx () const
Extra doc: https://github.com/casadi/casadi/wiki/L_1xb
Definition at line 1619 of file function.cpp.
{
     try {
       return (*this)->free_mx();
     } catch(std::exception& e) {
       THROW_ERROR("free_mx", e.what());
     }
   }
Referenced by casadi::MX::get_free(), and casadi::MX::symvar().
free_sx()
std::vector< SX > casadi::Function::free_sx () const
Extra doc: https://github.com/casadi/casadi/wiki/L_1xa
Definition at line 1611 of file function.cpp.
{
     try {
       return (*this)->free_sx();
     } catch(std::exception& e) {
       THROW_ERROR("free_sx", e.what());
     }
   }
Referenced by casadi::Matrix< Scalar >::get_free().
generate() [1/2]
std::string casadi::Function::generate (const Dict & opts = Dict()) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1wv
Definition at line 1132 of file function.cpp.
{
     return generate(name(), opts);
   }
References generate(), and name().
generate() [2/2]
std::string casadi::Function::generate (const std::string & fname, const Dict & opts = Dict()) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1wu
Examples
SX/generateCode.py.
Definition at line 1136 of file function.cpp.
{
     CodeGenerator gen(fname, opts);
     gen.add(*this);
     return gen.generate();
   }
References casadi::CodeGenerator::add(), and casadi::CodeGenerator::generate().
Referenced by generate().
generate_dependencies()
std::string casadi::Function::generate_dependencies (const std::string & fname, const Dict & opts = Dict()) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1ww
Definition at line 1142 of file function.cpp.
{
     return (*this)->generate_dependencies(fname, opts);
   }
generate_in() [1/2]
std::vector< DM > casadi::Function::generate_in (const std::string & fname)
See also
generate_out
convert_in to convert between dict/map and vector
Extra doc: https://github.com/casadi/casadi/wiki/L_1wx
Definition at line 1176 of file function.cpp.
{
     DM data = DM::from_file(fname, "txt");
     // Empty files are okay
     if (data.is_empty(true)) data = DM(0, 1);
     casadi_assert(data.is_vector() && data.is_dense(), "Expected dense vector");
     casadi_assert(data.numel()==nnz_in(),
       "Dimension mismatch: file contains a vector of size " + str(data.numel())
       + ", while size " + str(nnz_in()) + " was expected.");
     return nz_to_in(data.nonzeros());
   }
References casadi::Matrix< double >::from_file(), casadi::GenericMatrix< MatType >::is_dense(), casadi::GenericMatrix< MatType >::is_empty(), casadi::GenericMatrix< MatType >::is_vector(), nnz_in(), casadi::Matrix< Scalar >::nonzeros(), casadi::GenericMatrix< MatType >::numel(), nz_to_in(), and casadi::str().
generate_in() [2/2]
void casadi::Function::generate_in (const std::string & fname, const std::vector< DM > & arg)
See also
generate_out
convert_in to convert between dict/map and vector
Extra doc: https://github.com/casadi/casadi/wiki/L_1wx
Definition at line 1146 of file function.cpp.
{
     std::vector<double> d = nz_from_in(arg);
     // Set up output stream
     std::ofstream of(fname);
     casadi_assert(of.good(), "Error opening stream '" + fname + "'.");
     normalized_setup(of);
     // Encode each output
     for (casadi_int i=0; i<d.size(); ++i) {
       normalized_out(of, d[i]);
       of << std::endl;
     }
   }
References casadi::normalized_out(), casadi::normalized_setup(), and nz_from_in().
generate_lifted()
void casadi::Function::generate_lifted (Function & vdef_fcn, Function & vinit_fcn) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1xc
Definition at line 1639 of file function.cpp.
{
     try {
       (*this)->generate_lifted(vdef_fcn, vinit_fcn);
     } catch(std::exception& e) {
       THROW_ERROR("generate_lifted", e.what());
     }
   }
Referenced by casadi::Scpgen::init().
generate_out() [1/2]
std::vector< DM > casadi::Function::generate_out (const std::string & fname)
See also
generate_in
convert_out to convert between dict/map and vector
Extra doc: https://github.com/casadi/casadi/wiki/L_1wy
Definition at line 1188 of file function.cpp.
{
     DM data = DM::from_file(fname, "txt");
     // Empty files are okay
     if (data.is_empty(true)) data = DM(0, 1);
     casadi_assert(data.is_vector() && data.is_dense(), "Expected dense vector");
     casadi_assert(data.numel()==nnz_out(),
       "Dimension mismatch: file contains a vector of size " + str(data.numel())
       + ", while size " + str(nnz_out()) + " was expected.");
     return nz_to_out(data.nonzeros());
   }
References casadi::Matrix< double >::from_file(), casadi::GenericMatrix< MatType >::is_dense(), casadi::GenericMatrix< MatType >::is_empty(), casadi::GenericMatrix< MatType >::is_vector(), nnz_out(), casadi::Matrix< Scalar >::nonzeros(), casadi::GenericMatrix< MatType >::numel(), nz_to_out(), and casadi::str().
generate_out() [2/2]
void casadi::Function::generate_out (const std::string & fname, const std::vector< DM > & arg)
See also
generate_in
convert_out to convert between dict/map and vector
Extra doc: https://github.com/casadi/casadi/wiki/L_1wy
Definition at line 1161 of file function.cpp.
{
     std::vector<double> d = nz_from_out(res);
     // Set up output stream
     std::ofstream of(fname);
     casadi_assert(of.good(), "Error opening stream '" + fname + "'.");
     normalized_setup(of);
     // Encode each output
     for (casadi_int i=0; i<d.size(); ++i) {
       normalized_out(of, d[i]);
       of << std::endl;
     }
   }
References casadi::normalized_out(), casadi::normalized_setup(), and nz_from_out().
get() [1/2]
FunctionInternal * casadi::Function::get () const
Get a const pointer to the node
Definition at line 321 of file function.cpp.
{
     return static_cast<FunctionInternal*>(SharedObject::get());
   }
References casadi::SharedObject::get().
Referenced by casadi::FunctionInternal::add_embedded(), casadi::XFunction< DerivedType, MatType, NodeType >::call_forward(), casadi::XFunction< DerivedType, MatType, NodeType >::call_reverse(), casadi::LinearInterpolantJac::codegen_body(), casadi::Call::codegen_decref(), casadi::Call::codegen_incref(), casadi::conic_debug(), casadi::LinearInterpolantJac::eval(), casadi::MX::extract(), casadi::Blocksqp::feasibilityRestorationPhase(), casadi::XFunction< DerivedType, MatType, NodeType >::get_jacobian(), casadi::LinearInterpolantJac::has_parametric_grid(), casadi::LinearInterpolantJac::has_parametric_values(), casadi::SundialsInterface::init(), casadi::LinearInterpolantJac::init(), casadi::MX::jacobian(), operator->(), operator==(), casadi::LinearInterpolantJac::serialize_type(), casadi::OptiNode::solve_prepare(), and casadi::MX::substitute_inplace().
get() [2/2]
template<typename T > T* casadi::Function::get () const inline
Definition at line 915 of file function.hpp.
                    {
       T* ret = dynamic_cast<T*>(get());
       casadi_assert_dev(ret!=nullptr);
       return ret;
     }
get_free()
std::vector< std::string > casadi::Function::get_free () const
Extra doc: https://github.com/casadi/casadi/wiki/L_1x9
Definition at line 1128 of file function.cpp.
{
     return (*this)->get_free();
   }
Referenced by casadi::OracleFunction::create_function(), expand(), casadi::integrator(), casadi::nlpsol(), casadi::DaeBuilderInternal::prune(), casadi::rootfinder(), and casadi::DaeBuilderInternal::tearing_variables().
get_function() [1/2]
std::vector< std::string > casadi::Function::get_function () const
Extra doc: https://github.com/casadi/casadi/wiki/L_1y3
Definition at line 1782 of file function.cpp.
{
     try {
       return (*this)->get_function();
     } catch(std::exception& e) {
       THROW_ERROR("get_function", e.what());
       return {};
     }
   }
Referenced by casadi::IdasInterface::psetupF().
get_function() [2/2]
Function casadi::Function::get_function (const std::string & name) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1y4
Definition at line 1791 of file function.cpp.
{
     try {
       return (*this)->get_function(name);
     } catch(std::exception& e) {
       THROW_ERROR("get_function", e.what());
     }
   }
References name().
get_str()
std::string casadi::SharedObject::get_str (bool more = false) const inline inherited
Definition at line 138 of file shared_object.hpp.
{
       std::stringstream ss;
       disp(ss, more);
       return ss.str();
     }
getCount()
casadi_int casadi::SharedObject::getCount () const inherited
Definition at line 121 of file shared_object.cpp.
{
     return (*this)->getCount();
   }
Referenced by casadi::MXNode::~MXNode().
has_free()
bool casadi::Function::has_free () const
Extra doc: https://github.com/casadi/casadi/wiki/L_1x8
Definition at line 1635 of file function.cpp.
{
     return (*this)->has_free();
   }
Referenced by casadi::construct_nlpsol(), casadi::OracleFunction::create_function(), casadi::detect_simple_bounds_gen(), expand(), casadi::XFunction< DerivedType, MatType, NodeType >::factory(), casadi::integrator(), casadi::nlpsol(), casadi::rootfinder(), casadi::DaeBuilderInternal::tearing_variables(), and casadi::OptiNode::value().
has_function()
bool casadi::Function::has_function (const std::string & fname) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1y5
Definition at line 1799 of file function.cpp.
{
     try {
       return (*this)->has_function(fname);
     } catch(std::exception& e) {
       THROW_ERROR("has_function", e.what());
       return false;
     }
   }
has_option()
bool casadi::Function::has_option (const std::string & option_name) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1w1
Definition at line 1107 of file function.cpp.
{
     try {
       return (*this)->has_option(option_name);
     } catch(std::exception& e) {
       THROW_ERROR("has_option", e.what());
       return false;  // never reached
     }
   }
Referenced by change_option().
has_spfwd()
bool casadi::Function::has_spfwd () const
Extra doc: https://github.com/casadi/casadi/wiki/L_1xl
Definition at line 1627 of file function.cpp.
{
     return (*this)->has_spfwd();
   }
has_sprev()
bool casadi::Function::has_sprev () const
Extra doc: https://github.com/casadi/casadi/wiki/L_1xl
Definition at line 1631 of file function.cpp.
{
     return (*this)->has_sprev();
   }
hessian_old()
Function casadi::Function::hessian_old (casadi_int iind, casadi_int oind) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1w5
Definition at line 864 of file function.cpp.
{
     // Redirect to factory class
     std::vector<std::string> s_in = name_in();
     std::vector<std::string> s_out = name_out();
     s_out.insert(s_out.begin(), "grad:" + name_out(oind) + ":" + name_in(iind));
     s_out.insert(s_out.begin(),
                  "hess:" + name_out(oind) + ":" + name_in(iind) + ":" + name_in(iind));
     return factory(name() + "_hess", s_in, s_out);
   }
References factory(), name(), name_in(), and name_out().
if_else()
Function casadi::Function::if_else (const std::string & name, const Function & f_true, const Function & f_false, const Dict & opts = Dict()) static
Extra doc: https://github.com/casadi/casadi/wiki/L_1wp
Definition at line 778 of file function.cpp.
{
     try {
       return create(new Switch(name, std::vector<Function>(1, f_false), f_true), opts);
     } catch(std::exception& e) {
       THROW_ERROR_NOOBJ("if_else", e.what(), "Switch");
     }
   }
References create(), and name().
Referenced by conditional(), and casadi::MX::if_else().
index_in()
casadi_int casadi::Function::index_in (const std::string & name) const
example: schemeEntry("x_opt") -> returns NLPSOL_X if FunctionInternal adheres to SCHEME_NLPINput
Extra doc: https://github.com/casadi/casadi/wiki/L_1vk
Definition at line 927 of file function.cpp.
{
     try {
       return (*this)->index_in(name);
     } catch(std::exception& e) {
       THROW_ERROR("index_in", e.what());
     }
   }
References name().
Referenced by buf_in(), casadi::Blocksqp::feasibilityRestorationPhase(), map(), mapaccum(), sparsity_in(), and casadi::DaeBuilderInternal::update_dependencies().
index_out()
casadi_int casadi::Function::index_out (const std::string & name) const
example: schemeEntry("x_opt") -> returns NLPSOL_X if FunctionInternal adheres to SCHEME_NLPINput
Extra doc: https://github.com/casadi/casadi/wiki/L_1vl
Definition at line 935 of file function.cpp.
{
     try {
       return (*this)->index_out(name);
     } catch(std::exception& e) {
       THROW_ERROR("index_out", e.what());
     }
   }
References name().
Referenced by buf_out(), map(), mapaccum(), sparsity_out(), and casadi::DaeBuilderInternal::update_dependencies().
info()
Dict casadi::Function::info () const
Obtain information about function
Definition at line 1872 of file function.cpp.
{
     return (*this)->info();
   }
instruction_constant()
double casadi::Function::instruction_constant (casadi_int k) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1xh
Definition at line 1687 of file function.cpp.
{
     try {
       return (*this)->instruction_constant(k);
     } catch(std::exception& e) {
       THROW_ERROR("instruction_constant", e.what());
     }
   }
Referenced by casadi::SXFunction::export_code_body().
instruction_id()
casadi_int casadi::Function::instruction_id (casadi_int k) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1xf
Definition at line 1671 of file function.cpp.
{
     try {
       return (*this)->instruction_id(k);
     } catch(std::exception& e) {
       THROW_ERROR("instruction_id", e.what());
     }
   }
Referenced by casadi::MXFunction::export_code_body(), and casadi::SXFunction::export_code_body().
instruction_input()
std::vector< casadi_int > casadi::Function::instruction_input (casadi_int k) const
(SXFunction/MXFunction)
Extra doc: https://github.com/casadi/casadi/wiki/L_1xg
Definition at line 1679 of file function.cpp.
{
     try {
       return (*this)->instruction_input(k);
     } catch(std::exception& e) {
       THROW_ERROR("instruction_input", e.what());
     }
   }
Referenced by casadi::MXFunction::export_code_body(), and casadi::SXFunction::export_code_body().
instruction_MX()
MX casadi::Function::instruction_MX (casadi_int k) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1xj
Definition at line 1655 of file function.cpp.
{
     try {
       return (*this)->instruction_MX(k);
     } catch(std::exception& e) {
       THROW_ERROR("instruction_MX", e.what());
     }
   }
Referenced by casadi::MXFunction::export_code_body().
instruction_output()
std::vector< casadi_int > casadi::Function::instruction_output (casadi_int k) const
(SXFunction/MXFunction)
Extra doc: https://github.com/casadi/casadi/wiki/L_1xi
Definition at line 1695 of file function.cpp.
{
     try {
       return (*this)->instruction_output(k);
     } catch(std::exception& e) {
       THROW_ERROR("instruction_output", e.what());
     }
   }
Referenced by casadi::MXFunction::export_code_body(), and casadi::SXFunction::export_code_body().
instructions_sx()
SX casadi::Function::instructions_sx () const
Note: input and output instructions have no SX representation. This method returns nan for those instructions.
Extra doc: https://github.com/casadi/casadi/wiki/L_1xk
Definition at line 1663 of file function.cpp.
{
     try {
       return (*this)->instructions_sx();
     } catch(std::exception& e) {
       THROW_ERROR("instructions_sx", e.what());
     }
   }
is_a()
bool casadi::Function::is_a (const std::string & type, bool recursive = true) const
Optionally check if name matches one of the base classes (default true)
Extra doc: https://github.com/casadi/casadi/wiki/L_1xw
Definition at line 1607 of file function.cpp.
{
     return (*this)->is_a(type, recursive);
   }
Referenced by casadi::Integrator::augmented_dae(), casadi::Integrator::get_forward_dae(), and casadi::MXFunction::get_stats().
is_diff_in() [1/2]
std::vector< bool > casadi::Function::is_diff_in () const
Extra doc: https://github.com/casadi/casadi/wiki/L_1vt
Definition at line 1007 of file function.cpp.
{
     try {
       return (*this)->is_diff_in_;
     } catch(std::exception& e) {
       THROW_ERROR("is_diff_in", e.what());
     }
   }
is_diff_in() [2/2]
bool casadi::Function::is_diff_in (casadi_int ind) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1vt
Definition at line 991 of file function.cpp.
{
     try {
       return (*this)->is_diff_in_.at(ind);
     } catch(std::exception& e) {
       THROW_ERROR("is_diff_in", e.what());
     }
   }
Referenced by casadi::FunctionInternal::get_sparsity_out(), casadi::Map::init(), and casadi::MapSum::init().
is_diff_out() [1/2]
std::vector< bool > casadi::Function::is_diff_out () const
Extra doc: https://github.com/casadi/casadi/wiki/L_1vt
Definition at line 1015 of file function.cpp.
{
     try {
       return (*this)->is_diff_out_;
     } catch(std::exception& e) {
       THROW_ERROR("is_diff_out", e.what());
     }
   }
is_diff_out() [2/2]
bool casadi::Function::is_diff_out (casadi_int ind) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1vt
Definition at line 999 of file function.cpp.
{
     try {
       return (*this)->is_diff_out_.at(ind);
     } catch(std::exception& e) {
       THROW_ERROR("is_diff_out", e.what());
     }
   }
Referenced by casadi::FunctionInternal::get_sparsity_out(), casadi::Map::init(), and casadi::MapSum::init().
is_null()
bool casadi::SharedObject::is_null () const inherited
Definition at line 73 of file shared_object.cpp.
{
     return node==nullptr;
   }
Referenced by casadi::FunctionInternal::add_embedded(), casadi::WeakRef::alive(), casadi::FunctionInternal::alloc(), casadi::Nlpsol::callback(), casadi::DaeBuilderInternal::clear_cache(), casadi::Switch::codegen_body(), casadi::Conic::Conic(), casadi::conic_debug(), casadi::Callback::construct(), deserialize(), casadi::SharedObject::disp(), casadi::FunctionInternal::finalize(), casadi::Switch::find(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::get_n_in(), casadi::Switch::get_n_in(), casadi::FunctionInternal::get_n_out(), casadi::Switch::get_n_out(), casadi::FunctionInternal::get_name_in(), casadi::FunctionInternal::get_name_out(), casadi::FunctionInternal::get_partition(), casadi::FunctionInternal::get_sparsity_in(), casadi::Switch::get_sparsity_in(), casadi::FunctionInternal::get_sparsity_out(), casadi::Switch::get_sparsity_out(), casadi::MXFunction::get_stats(), casadi::GenericType::getType(), casadi::Sparsity::info(), casadi::Nlpsol::init(), casadi::Rootfinder::init(), casadi::Switch::init(), casadi::SnoptInterface::init(), casadi::SundialsInterface::init(), casadi::FastNewton::init(), casadi::Newton::init(), casadi::Scpgen::init(), casadi::BonminInterface::intermediate_callback(), casadi::IpoptInterface::intermediate_callback(), casadi::XFunction< DerivedType, MatType, NodeType >::jac(), casadi::FunctionInternal::jac_is_symm(), casadi::FunctionInternal::jac_sparsity(), casadi::OracleFunction::jit_dependencies(), casadi::SparsityInternal::maxtrans(), name(), operator->(), casadi::SharedObject::operator->(), operator==(), casadi::DaeBuilderInternal::oracle(), serialize(), casadi::Sparsity::serialize(), casadi::SnoptInterface::set_work(), casadi::OptiNode::solve(), casadi::KnitroInterface::solve(), casadi::WorhpInterface::solve(), casadi::FunctionInternal::sp_forward_block(), casadi::FunctionInternal::sp_reverse(), casadi::Sparsity::uni_coloring(), and casadi::Callback::~Callback().
jac_sparsity() [1/2]
const std::vector< Sparsity > & casadi::Function::jac_sparsity (bool compact = false) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1ws
Definition at line 900 of file function.cpp.
{
     // Make sure all are calculated
     for (casadi_int oind = 0; oind < n_out(); ++oind) {
       for (casadi_int iind = 0; iind < n_in(); ++iind) {
         (void)jac_sparsity(oind, iind, compact);
       }
     }
     // Return reference to internal cache
     return (*this)->jac_sparsity_[compact];
   }
References n_in(), and n_out().
Referenced by casadi::_jacobian_sparsity(), casadi::CodeGenerator::add(), casadi::FunctionInternal::get_sparsity_out(), casadi::Integrator::sp_jac_dae(), casadi::Integrator::sp_jac_rdae(), and casadi::DaeBuilderInternal::update_dependencies().
jac_sparsity() [2/2]
Sparsity casadi::Function::jac_sparsity (casadi_int oind, casadi_int iind, bool compact = false) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1wt
Definition at line 911 of file function.cpp.
{
     try {
       return (*this)->jac_sparsity(oind, iind, compact, (*this)->jac_is_symm(oind, iind));
     } catch(std::exception& e) {
       THROW_ERROR("jac_sparsity", e.what());
     }
   }
jacobian()
Function casadi::Function::jacobian () const
Generates a function that takes all non-differentiated inputs and outputs and calculates all Jacobian blocks. Inputs that are not needed by the routine are all-zero sparse matrices with the correct dimensions. Output blocks that are not calculated, e.g. if the corresponding input or output is marked non-differentiated are also all-zero sparse. The Jacobian blocks are sorted starting by all the blocks for the first output, then all the blocks for the second output and so on. E.g. f : (x, y) -> (r, s) results in the function jac_f : (x, y, out_r, out_s) -> (jac_r_x, jac_r_y, jac_s_x, jac_s_y)
This function is cached.
Extra doc: https://github.com/casadi/casadi/wiki/L_1w6
Definition at line 884 of file function.cpp.
{
     try {
       return (*this)->jacobian();
     } catch(std::exception& e) {
       THROW_ERROR("jacobian", e.what());
     }
   }
References casadi::FunctionInternal::jacobian().
Referenced by casadi::DaeBuilderInternal::CallIO::calc_jac(), and casadi::FunctionInternal::jacobian().
jacobian_old()
Function casadi::Function::jacobian_old (casadi_int iind, casadi_int oind) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1w4
Definition at line 856 of file function.cpp.
{
     // Redirect to factory class
     std::vector<std::string> s_in = name_in();
     std::vector<std::string> s_out = name_out();
     s_out.insert(s_out.begin(), "jac:" + name_out(oind) + ":" + name_in(iind));
     return factory(name() + "_jac", s_in, s_out);
   }
References factory(), name(), name_in(), and name_out().
jit() [1/2]
Function casadi::Function::jit (const std::string & name, const std::string & body, const std::vector< std::string > & name_in, const std::vector< std::string > & name_out, const Dict & opts = Dict()) static
The names and sparsity patterns of all the inputs and outputs must be provided. If sparsities are not provided, all inputs and outputs are assumed to be scalar. Only specify the function body, assuming that input and output nonzeros are stored in arrays with the specified naming convension. The data type used is 'casadi_real', which is typically equal to 'double‘ or another data type with the same API as 'double’.
Inputs may be null pointers. This means that the all entries are zero. Outputs may be null points. This means that the corresponding result can be ignored.
If an error occurs in the evaluation, issue "return 1;";
The final generated function will have a structure similar to:
casadi_int fname(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) { const casadi_real *x1, *x2; casadi_real *r1, *r2; x1 = *arg++; x2 = *arg++; r1 = *res++; r2 = *res++; <FUNCTION_BODY> return 0; }
Extra doc: https://github.com/casadi/casadi/wiki/L_1v3
Definition at line 253 of file function.cpp.
{
     // Pass empty vectors -> default values
     std::vector<Sparsity> sparsity_in, sparsity_out;
     return jit(name, body, name_in, name_out, sparsity_in, sparsity_out, opts);
   }
References name(), name_in(), name_out(), sparsity_in(), and sparsity_out().
Referenced by casadi::JitFunction::get_jacobian().
jit() [2/2]
Function casadi::Function::jit (const std::string & name, const std::string & body, const std::vector< std::string > & name_in, const std::vector< std::string > & name_out, const std::vector< Sparsity > & sparsity_in, const std::vector< Sparsity > & sparsity_out, const Dict & opts = Dict()) static
The names and sparsity patterns of all the inputs and outputs must be provided. If sparsities are not provided, all inputs and outputs are assumed to be scalar. Only specify the function body, assuming that input and output nonzeros are stored in arrays with the specified naming convension. The data type used is 'casadi_real', which is typically equal to 'double‘ or another data type with the same API as 'double’.
Inputs may be null pointers. This means that the all entries are zero. Outputs may be null points. This means that the corresponding result can be ignored.
If an error occurs in the evaluation, issue "return 1;";
The final generated function will have a structure similar to:
casadi_int fname(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) { const casadi_real *x1, *x2; casadi_real *r1, *r2; x1 = *arg++; x2 = *arg++; r1 = *res++; r2 = *res++; <FUNCTION_BODY> return 0; }
Extra doc: https://github.com/casadi/casadi/wiki/L_1v3
Definition at line 262 of file function.cpp.
{
     try {
       return create(new JitFunction(name, body, name_in, name_out,
                                     sparsity_in, sparsity_out), opts);
     } catch(std::exception& e) {
       THROW_ERROR_NOOBJ("jit", e.what(), "JitFunction");
     }
   }
References create(), name(), name_in(), name_out(), sparsity_in(), and sparsity_out().
load()
Function casadi::Function::load (const std::string & filename) static
Extra doc: https://github.com/casadi/casadi/wiki/L_1y1
Definition at line 1292 of file function.cpp.
{
     FileDeserializer fs(filename);
     auto t = fs.pop_type();
     if (t==SerializerBase::SerializationType::SERIALIZED_FUNCTION) {
       return fs.blind_unpack_function();
     } else {
       casadi_error("File is not loadable with 'load'. Use 'FileDeserializer' instead.");
     }
   }
References casadi::DeserializerBase::blind_unpack_function(), and casadi::DeserializerBase::pop_type().
map() [1/5]
Function casadi::Function::map (casadi_int n, const std::string & parallelization, casadi_int max_num_threads) const
Definition at line 646 of file function.cpp.
{
     casadi_assert(max_num_threads>=1, "max_num_threads invalid.");
     // No need for logic when we are not saturating the limit
     if (n<=max_num_threads) return map(n, parallelization);
     // Floored division
     casadi_int d = n/max_num_threads;
     if (d*max_num_threads==n) {
       // Easy when n is divisable by max_num_threads
       return map(d, "serial").map(max_num_threads, parallelization);
     } else {
       // Create a base map that computes a bit too much
       Function base = map(d+1, "serial").map(max_num_threads, parallelization);
       std::vector<MX> ret_in, base_in;
       casadi_int rem = (d+1)*max_num_threads-n;
       for (casadi_int i=0;i<n_in();++i) {
         MX arg = MX::sym("arg", repmat(sparsity_in(i), 1, n));
         ret_in.push_back(arg);
         MX last_arg = arg(Slice(), range((n-1)*size2_in(i), n*size2_in(i))); // NOLINT
         base_in.push_back(horzcat(arg, repmat(last_arg, 1, rem)));
       }
       std::vector<MX> ret_out = base(base_in);
       for (casadi_int i=0;i<n_out();++i) {
         ret_out[i] = horzsplit(ret_out[i], {0, n*size2_out(i), ret_out[i].size2()})[0];
       }
       return Function("helper", ret_in, ret_out, name_in(), name_out());
     }
   }
References Function(), map(), n_in(), n_out(), name_in(), name_out(), casadi::range(), size2_in(), size2_out(), sparsity_in(), and casadi::GenericMatrix< MX >::sym().
map() [2/5]
Function casadi::Function::map (casadi_int n, const std::string & parallelization = "serial") const
Suppose the function has a signature of:
   f: (a, p) -> ( s )
The the mapped version has the signature:
   F: (A, P) -> (S )
    with
        A: horzcat([a0, a1, ..., a_(N-1)])
        P: horzcat([p0, p1, ..., p_(N-1)])
        S: horzcat([s0, s1, ..., s_(N-1)])
    and
        s0 <- f(a0, p0)
        s1 <- f(a1, p1)
        ...
        s_(N-1) <- f(a_(N-1), p_(N-1))
Parameters
parallelization Type of parallelization used: unroll|serial|openmp
Extra doc: https://github.com/casadi/casadi/wiki/L_1wj
Definition at line 677 of file function.cpp.
{
     // Make sure not degenerate
     casadi_assert(n>0, "Degenerate map operation");
     // Quick return if possible
     if (n==1) return *this;
     // Unroll?
     if (parallelization=="unroll" || parallelization=="inline") {
       // Construct symbolic inputs
       std::vector<MX> arg(n_in());
       std::vector<std::vector<MX>> v(n, arg);
       std::vector<MX> tmp(n);
       for (casadi_int i=0; i<arg.size(); ++i) {
         for (casadi_int k=0; k<n; ++k) {
           tmp[k] = v[k][i] = MX::sym(name_in(i)+"_"+str(k), sparsity_in(i));
         }
         arg[i] = horzcat(tmp);
       }
       // Evaluate
       if (parallelization=="unroll") {
         for (auto&& w : v) w = (*this)(w);
       } else {
         for (auto&& w : v) call(std::vector<MX>(w), w, true, false);
       }
       // Gather outputs
       std::vector<MX> res(n_out());
       for (casadi_int i=0; i<res.size(); ++i) {
         for (casadi_int k=0; k<n; ++k) tmp[k] = v[k][i];
         res[i] = horzcat(tmp);
       }
       // Construct function
       return Function(name() + "_" + str(n), arg, res, name_in(), name_out());
     } else {
       // Generate/retrieve potentially cached map
       return (*this)->map(n, parallelization);
     }
   }
References call(), Function(), n_in(), n_out(), name(), name_in(), name_out(), sparsity_in(), casadi::str(), and casadi::GenericMatrix< MX >::sym().
Referenced by casadi::Dple::get_forward(), casadi::Expm::get_forward(), casadi::External::get_forward(), casadi::Map::get_forward(), casadi::Dple::get_reverse(), casadi::Expm::get_reverse(), casadi::External::get_reverse(), casadi::Map::get_reverse(), and map().
map() [3/5]
Function casadi::Function::map (casadi_int n, const std::vector< bool > & reduce_in, const std::vector< bool > & reduce_out = std::vector<bool>(), const Dict & opts = Dict()) const
A subset of the inputs are non-repeated and a subset of the outputs summed up.
Extra doc: https://github.com/casadi/casadi/wiki/L_1wk
Definition at line 605 of file function.cpp.
{
     return MapSum::create("mapsum_" + str(n) + "_" + name(), "serial",
       *this, n, reduce_in, reduce_out, opts);
   }
References casadi::MapSum::create(), name(), and casadi::str().
map() [4/5]
Function casadi::Function::map (const std::string & name, const std::string & parallelization, casadi_int n, const std::vector< casadi_int > & reduce_in, const std::vector< casadi_int > & reduce_out, const Dict & opts = Dict()) const
A subset of the inputs are non-repeated and a subset of the outputs summed up.
Extra doc: https://github.com/casadi/casadi/wiki/L_1wk
Definition at line 613 of file function.cpp.
{
     // Wrap in an MXFunction
     Function f = map(n, parallelization);
     // Start with the fully mapped inputs
     std::vector<MX> arg = f.mx_in();
     std::vector<MX> f_arg = arg;
     // Replace reduced inputs
     for (casadi_int i : reduce_in) {
       arg[i] = mx_in(i);
       f_arg[i] = repmat(arg[i], 1, n);
     }
     // Get fully mapped outputs
     std::vector<MX> res = f(f_arg);
     // Replace reduced outputs
     for (casadi_int i : reduce_out) {
       res[i] = repsum(res[i], 1, n);
     }
     // Construct return
     return Function(name, arg, res, name_in(), name_out());
   }
References Function(), map(), mx_in(), name(), name_in(), and name_out().
map() [5/5]
Function casadi::Function::map (const std::string & name, const std::string & parallelization, casadi_int n, const std::vector< std::string > & reduce_in, const std::vector< std::string > & reduce_out, const Dict & opts = Dict()) const
A subset of the inputs are non-repeated and a subset of the outputs summed up.
Extra doc: https://github.com/casadi/casadi/wiki/L_1wk
Definition at line 636 of file function.cpp.
{
     std::vector<casadi_int> reduce_in_num, reduce_out_num;
     for (const std::string& s : reduce_in) reduce_in_num.push_back(index_in(s));
     for (const std::string& s : reduce_out) reduce_out_num.push_back(index_out(s));
     return map(name, parallelization, n, reduce_in_num, reduce_out_num, opts);
   }
References index_in(), index_out(), map(), and name().
mapaccum() [1/6]
Function casadi::Function::mapaccum (casadi_int N, const Dict & opts = Dict()) const
Suppose the function has a signature of:
   f: (x, u) -> (x_next , y )
The the mapaccumulated version has the signature:
   F: (x0, U) -> (X , Y )
    with
        U: horzcat([u0, u1, ..., u_(N-1)])
        X: horzcat([x1, x2, ..., x_N])
        Y: horzcat([y0, y1, ..., y_(N-1)])
    and
        x1, y0 <- f(x0, u0)
        x2, y1 <- f(x1, u1)
        ...
        x_N, y_(N-1) <- f(x_(N-1), u_(N-1))
Mapaccum has the following benefits over writing an equivalent for-loop:
much faster at construction time
potentially much faster compilation times (for codegen)
offers a trade-off between memory and evaluation time
The base (settable through the options dictionary, default 10), is used to create a tower of function calls, containing unrolled for-loops of length maximum base.
This technique is much more scalable in terms of memory-usage, but slightly slower at evaluation, than a plain for-loop. The effect is similar to that of a for-loop with a check-pointing instruction after each chunk of iterations with size base.
Set base to -1 to unroll all the way; no gains in memory efficiency here.
Extra doc: https://github.com/casadi/casadi/wiki/L_1wi
Definition at line 484 of file function.cpp.
{
     return mapaccum("mapaccum_"+name(), N, opts);
   }
References mapaccum(), and name().
mapaccum() [2/6]
Function casadi::Function::mapaccum (const std::string & name, casadi_int N, casadi_int n_accum, const Dict & opts = Dict()) const
Suppose the function has a signature of:
   f: (x, u) -> (x_next , y )
The the mapaccumulated version has the signature:
   F: (x0, U) -> (X , Y )
    with
        U: horzcat([u0, u1, ..., u_(N-1)])
        X: horzcat([x1, x2, ..., x_N])
        Y: horzcat([y0, y1, ..., y_(N-1)])
    and
        x1, y0 <- f(x0, u0)
        x2, y1 <- f(x1, u1)
        ...
        x_N, y_(N-1) <- f(x_(N-1), u_(N-1))
Mapaccum has the following benefits over writing an equivalent for-loop:
much faster at construction time
potentially much faster compilation times (for codegen)
offers a trade-off between memory and evaluation time
The base (settable through the options dictionary, default 10), is used to create a tower of function calls, containing unrolled for-loops of length maximum base.
This technique is much more scalable in terms of memory-usage, but slightly slower at evaluation, than a plain for-loop. The effect is similar to that of a for-loop with a check-pointing instruction after each chunk of iterations with size base.
Set base to -1 to unroll all the way; no gains in memory efficiency here.
Extra doc: https://github.com/casadi/casadi/wiki/L_1wi
Definition at line 490 of file function.cpp.
{
     Dict options = opts;
     // Default base
     casadi_int base = 10;
     auto it = options.find("base");
     if (it!=options.end()) {
       base = it->second;
       options.erase(it);
     }
     casadi_assert(N>0, "mapaccum: N must be positive");
     if (base==-1)
       return mapaccum(name, std::vector<Function>(N, *this), n_accum, options);
     casadi_assert(base>=2, "mapaccum: base must be positive");
     // Decompose N into
     std::vector<Function> chain;
     Function c = *this;
     while (N!=0) {
       casadi_int r = N % base;
       chain.insert(chain.end(), r, c);
       N = (N-r)/base;
       c = c.mapaccum(c.name()+"_acc"+str(base), std::vector<Function>(base, c), n_accum, options);
     }
     return mapaccum(name, chain, n_accum, options);
   }
References mapaccum(), name(), and casadi::str().
mapaccum() [3/6]
Function casadi::Function::mapaccum (const std::string & name, casadi_int N, const Dict & opts = Dict()) const
Suppose the function has a signature of:
   f: (x, u) -> (x_next , y )
The the mapaccumulated version has the signature:
   F: (x0, U) -> (X , Y )
    with
        U: horzcat([u0, u1, ..., u_(N-1)])
        X: horzcat([x1, x2, ..., x_N])
        Y: horzcat([y0, y1, ..., y_(N-1)])
    and
        x1, y0 <- f(x0, u0)
        x2, y1 <- f(x1, u1)
        ...
        x_N, y_(N-1) <- f(x_(N-1), u_(N-1))
Mapaccum has the following benefits over writing an equivalent for-loop:
much faster at construction time
potentially much faster compilation times (for codegen)
offers a trade-off between memory and evaluation time
The base (settable through the options dictionary, default 10), is used to create a tower of function calls, containing unrolled for-loops of length maximum base.
This technique is much more scalable in terms of memory-usage, but slightly slower at evaluation, than a plain for-loop. The effect is similar to that of a for-loop with a check-pointing instruction after each chunk of iterations with size base.
Set base to -1 to unroll all the way; no gains in memory efficiency here.
Extra doc: https://github.com/casadi/casadi/wiki/L_1wi
Definition at line 487 of file function.cpp.
{
     return mapaccum(name, N, 1, opts);
   }
References name().
Referenced by casadi::MX::cumsum(), fold(), and mapaccum().
mapaccum() [4/6]
Function casadi::Function::mapaccum (const std::string & name, casadi_int n, const std::vector< casadi_int > & accum_in, const std::vector< casadi_int > & accum_out, const Dict & opts = Dict()) const
Suppose the function has a signature of:
   f: (x, u) -> (x_next , y )
The the mapaccumulated version has the signature:
   F: (x0, U) -> (X , Y )
    with
        U: horzcat([u0, u1, ..., u_(N-1)])
        X: horzcat([x1, x2, ..., x_N])
        Y: horzcat([y0, y1, ..., y_(N-1)])
    and
        x1, y0 <- f(x0, u0)
        x2, y1 <- f(x1, u1)
        ...
        x_N, y_(N-1) <- f(x_(N-1), u_(N-1))
Mapaccum has the following benefits over writing an equivalent for-loop:
much faster at construction time
potentially much faster compilation times (for codegen)
offers a trade-off between memory and evaluation time
The base (settable through the options dictionary, default 10), is used to create a tower of function calls, containing unrolled for-loops of length maximum base.
This technique is much more scalable in terms of memory-usage, but slightly slower at evaluation, than a plain for-loop. The effect is similar to that of a for-loop with a check-pointing instruction after each chunk of iterations with size base.
Set base to -1 to unroll all the way; no gains in memory efficiency here.
Extra doc: https://github.com/casadi/casadi/wiki/L_1wi
Definition at line 565 of file function.cpp.
{
     // Shorthands
     casadi_int n_in = this->n_in(), n_out = this->n_out();
     // Consistency checks
     casadi_assert_dev(in_range(accum_in, n_in) && isUnique(accum_in));
     casadi_assert_dev(in_range(accum_out, n_out) && isUnique(accum_out));
     casadi_assert_dev(accum_in.size()==accum_out.size());
     casadi_int n_accum=accum_in.size();
     // Quick return if no need to reorder
     if (accum_in==range(n_accum) && accum_out==range(n_accum)) {
       return mapaccum(name, n, n_accum, opts);
     }
     // Need to do some reordering
     std::vector<casadi_int> temp_in = complement(accum_in, n_in);
     std::vector<casadi_int> order_in = accum_in;
     order_in.insert(order_in.end(), temp_in.begin(), temp_in.end());
     std::vector<casadi_int> temp_out = complement(accum_out, n_out);
     std::vector<casadi_int> order_out = accum_out;
     order_out.insert(order_out.end(), temp_out.begin(), temp_out.end());
     Function ret = slice("slice_" + name, order_in, order_out);
     ret = ret.mapaccum("mapacc_" + name, n, n_accum, opts);
     return ret.slice(name, lookupvector(order_in, n_in),
                      lookupvector(order_out, n_out), opts);
   }
References casadi::complement(), casadi::in_range(), casadi::isUnique(), casadi::lookupvector(), mapaccum(), n_in(), n_out(), name(), casadi::range(), and slice().
mapaccum() [5/6]
Function casadi::Function::mapaccum (const std::string & name, casadi_int n, const std::vector< std::string > & accum_in, const std::vector< std::string > & accum_out, const Dict & opts = Dict()) const
Suppose the function has a signature of:
   f: (x, u) -> (x_next , y )
The the mapaccumulated version has the signature:
   F: (x0, U) -> (X , Y )
    with
        U: horzcat([u0, u1, ..., u_(N-1)])
        X: horzcat([x1, x2, ..., x_N])
        Y: horzcat([y0, y1, ..., y_(N-1)])
    and
        x1, y0 <- f(x0, u0)
        x2, y1 <- f(x1, u1)
        ...
        x_N, y_(N-1) <- f(x_(N-1), u_(N-1))
Mapaccum has the following benefits over writing an equivalent for-loop:
much faster at construction time
potentially much faster compilation times (for codegen)
offers a trade-off between memory and evaluation time
The base (settable through the options dictionary, default 10), is used to create a tower of function calls, containing unrolled for-loops of length maximum base.
This technique is much more scalable in terms of memory-usage, but slightly slower at evaluation, than a plain for-loop. The effect is similar to that of a for-loop with a check-pointing instruction after each chunk of iterations with size base.
Set base to -1 to unroll all the way; no gains in memory efficiency here.
Extra doc: https://github.com/casadi/casadi/wiki/L_1wi
Definition at line 595 of file function.cpp.
{
     std::vector<casadi_int> accum_in_num, accum_out_num;
     for (const std::string& s : accum_in) accum_in_num.push_back(index_in(s));
     for (const std::string& s : accum_out) accum_out_num.push_back(index_out(s));
     return mapaccum(name, n, accum_in_num, accum_out_num, opts);
   }
References index_in(), index_out(), mapaccum(), and name().
mapaccum() [6/6]
Function casadi::Function::mapaccum (const std::string & name, const std::vector< Function > & chain, casadi_int n_accum = 1, const Dict & opts = Dict()) const protected
Definition at line 520 of file function.cpp.
{
     // Shorthands
     casadi_int n_in = this->n_in(), n_out = this->n_out();
     // Consistency checks
     casadi_assert(!chain.empty(), "mapaccum: chain must be non-empty");
     casadi_assert(n_accum<=std::min(n_in, n_out), "mapaccum: too many accumulators");
     // Quick return?
     if (chain.size()==1) return chain[0];
     // Get symbolic expressions for inputs and outputs
     std::vector<MX> arg = mx_in();
     std::vector<MX> res;
     // Vectorized inputs and outputs
     std::vector<std::vector<MX>> varg(n_in), vres(n_out);
     for (casadi_int i=0; i<n_accum; ++i) varg[i].push_back(arg[i]);
     // For each function call
     for (const auto& f : chain) {
       // Stacked input expressions
       for (casadi_int i=n_accum; i<n_in; ++i) {
         arg[i] = MX::sym(name_in(i) + "_" + str(i), f.sparsity_in(i));
         varg[i].push_back(arg[i]);
       }
       // Call f
       res = f(arg);
       // Save output expressions
       for (casadi_int i=0; i<n_out; ++i) vres[i].push_back(res[i]);
       // Copy function output to input
       std::copy_n(res.begin(), n_accum, arg.begin());
       for (casadi_int i=0; i<n_accum; ++i) {
         // Ony get last component (allows nested calls)
         casadi_int ncol_out=f.size2_out(i), ncol_in=size2_in(i);
         if (ncol_out>ncol_in) {
           arg[i] = horzsplit(arg[i], {0, ncol_out-ncol_in, ncol_out}).back();
         }
       }
     }
     // Construct return
     for (casadi_int i=0; i<n_in; ++i) arg[i] = horzcat(varg[i]);
     for (casadi_int i=0; i<n_out; ++i) res[i] = horzcat(vres[i]);
     return Function(name, arg, res, name_in(), name_out(), opts);
   }
References Function(), mx_in(), n_in(), n_out(), name(), name_in(), name_out(), size2_in(), casadi::str(), and casadi::GenericMatrix< MX >::sym().
mapsum()
std::vector< MX > casadi::Function::mapsum (const std::vector< MX > & x, const std::string & parallelization = "serial") const
Parameters
parallelization Type of parallelization used: unroll|serial|openmp
Extra doc: https://github.com/casadi/casadi/wiki/L_1wh
Definition at line 724 of file function.cpp.
{
     try {
       return (*this)->mapsum_mx(x, parallelization);
     } catch(std::exception& e) {
       THROW_ERROR("mapsum", e.what());
     }
   }
max_in()
double casadi::Function::max_in (casadi_int ind) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1vn
Definition at line 1427 of file function.cpp.
{
     return (*this)->get_max_in(ind);
   }
memory()
void * casadi::Function::memory (int ind) const
Definition at line 1719 of file function.cpp.
{
     return (*this)->memory(ind);
   }
Referenced by casadi::Blocksqp::feasibilityRestorationPhase(), casadi::FunctionBuffer::FunctionBuffer(), casadi::QpToNlp::get_stats(), operator()(), casadi::FunctionBuffer::operator=(), rev(), set_temp(), set_work(), setup(), casadi::QpToNlp::solve(), casadi::ImplicitToNlp::solve(), and stats().
min_in()
double casadi::Function::min_in (casadi_int ind) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1vo
Definition at line 1431 of file function.cpp.
{
     return (*this)->get_min_in(ind);
   }
mx_in() [1/3]
const std::vector< MX > casadi::Function::mx_in () const
There is no guarantee that subsequent calls return unique answers
Extra doc: https://github.com/casadi/casadi/wiki/L_1x4
Definition at line 1535 of file function.cpp.
{
     return (*this)->mx_in();
   }
Referenced by map(), and mapaccum().
mx_in() [2/3]
const MX casadi::Function::mx_in (casadi_int ind) const
There is no guarantee that subsequent calls return unique answers
Extra doc: https://github.com/casadi/casadi/wiki/L_1x4
Definition at line 1527 of file function.cpp.
{
     return (*this)->mx_in(ind);
   }
Referenced by conditional(), casadi::DaeBuilderInternal::create(), casadi::FixedStepIntegrator::create_advanced(), fold(), casadi::Map::get_forward(), casadi::MapSum::get_forward(), casadi::Switch::get_forward(), casadi::MX::get_input(), casadi::Map::get_reverse(), casadi::MapSum::get_reverse(), casadi::Switch::get_reverse(), casadi::Blocksqp::init(), casadi::Scpgen::init(), and map().
mx_in() [3/3]
const MX casadi::Function::mx_in (const std::string & iname) const inline
There is no guarantee that subsequent calls return unique answers
Extra doc: https://github.com/casadi/casadi/wiki/L_1x4
Definition at line 946 of file function.hpp.
{
       return mx_in(index_in(iname));
     }
mx_out() [1/3]
const std::vector< MX > casadi::Function::mx_out () const
There is no guarantee that subsequent calls return unique answers
Extra doc: https://github.com/casadi/casadi/wiki/L_1x5
Definition at line 1539 of file function.cpp.
{
     return (*this)->mx_out();
   }
mx_out() [2/3]
const MX casadi::Function::mx_out (casadi_int ind) const
There is no guarantee that subsequent calls return unique answers
Extra doc: https://github.com/casadi/casadi/wiki/L_1x5
Definition at line 1531 of file function.cpp.
{
     return (*this)->mx_out(ind);
   }
mx_out() [3/3]
const MX casadi::Function::mx_out (const std::string & oname) const inline
There is no guarantee that subsequent calls return unique answers
Extra doc: https://github.com/casadi/casadi/wiki/L_1x5
Definition at line 964 of file function.hpp.
{
       return mx_out(index_out(oname));
     }
n_in()
casadi_int casadi::Function::n_in () const
Extra doc: https://github.com/casadi/casadi/wiki/L_1v8
Definition at line 787 of file function.cpp.
{
     return (*this)->n_in_;
   }
Referenced by buf_in(), casadi::OracleFunction::calc_function(), casadi::DaeBuilderInternal::CallIO::calc_jac(), casadi::Call::Call(), call_gen(), casadi::Nlpsol::callback(), casadi::FiniteDiff::codegen_body(), casadi::Sqpmethod::codegen_qp_ela_solve(), casadi::Feasiblesqpmethod::codegen_qp_solve(), casadi::Sqpmethod::codegen_qp_solve(), casadi::MapSum::create(), casadi::OracleFunction::create_function(), casadi::FiniteDiff::eval(), casadi::Scpgen::eval_exp(), casadi::Scpgen::eval_mat(), casadi::Scpgen::eval_res(), casadi::Scpgen::eval_vec(), casadi::External::factory(), casadi::Blocksqp::feasibilityRestorationPhase(), casadi::FunctionInternal::forward(), casadi::FiniteDiff::get_default_in(), casadi::FunctionInternal::get_n_in(), casadi::FiniteDiff::get_n_in(), casadi::Switch::get_n_in(), casadi::FunctionInternal::get_n_out(), casadi::FunctionInternal::get_name_in(), casadi::FiniteDiff::get_name_in(), casadi::FunctionInternal::get_name_out(), casadi::FunctionInternal::get_sparsity_in(), casadi::FiniteDiff::get_sparsity_in(), casadi::FunctionInternal::get_sparsity_out(), casadi::Integrator::init(), casadi::Nlpsol::init(), casadi::Rootfinder::init(), casadi::BonminInterface::init(), casadi::IpoptInterface::init(), casadi::FastNewton::init(), casadi::Feasiblesqpmethod::init(), casadi::Newton::init(), casadi::Sqpmethod::init(), casadi::BonminInterface::intermediate_callback(), casadi::IpoptInterface::intermediate_callback(), jac_sparsity(), casadi::FunctionInternal::jacobian(), map(), mapaccum(), casadi::MapSum::MapSum(), casadi::SymbolicQr::nfact(), casadi::qpsol_nlp(), rev(), casadi::FunctionInternal::reverse(), casadi::simpleIntegrator(), casadi::simpleIRK(), casadi::simpleRK(), casadi::WorhpInterface::solve(), casadi::Scpgen::solve(), casadi::SymbolicQr::solve(), casadi::Sqpmethod::solve_ela_QP(), casadi::Feasiblesqpmethod::solve_LP(), casadi::Feasiblesqpmethod::solve_QP(), casadi::Qrsqp::solve_QP(), casadi::Scpgen::solve_qp(), casadi::Sqpmethod::solve_QP(), and casadi::ThreadsWork().
n_instructions()
casadi_int casadi::Function::n_instructions () const
Extra doc: https://github.com/casadi/casadi/wiki/L_1xe
Definition at line 1647 of file function.cpp.
{
     try {
       return (*this)->n_instructions();
     } catch(std::exception& e) {
       THROW_ERROR("n_instructions", e.what());
     }
   }
Referenced by casadi::MXFunction::export_code_body(), and casadi::SXFunction::export_code_body().
n_nodes()
casadi_int casadi::Function::n_nodes () const
Extra doc: https://github.com/casadi/casadi/wiki/L_1xd
Definition at line 1703 of file function.cpp.
{
     try {
       return (*this)->n_nodes();
     } catch(std::exception& e) {
       THROW_ERROR("n_nodes", e.what());
     }
   }
Referenced by casadi::Scpgen::init(), and casadi::MX::n_nodes().
n_out()
casadi_int casadi::Function::n_out () const
Extra doc: https://github.com/casadi/casadi/wiki/L_1v9
Definition at line 791 of file function.cpp.
{
     return (*this)->n_out_;
   }
Referenced by buf_out(), casadi::OracleFunction::calc_function(), casadi::DaeBuilderInternal::CallIO::calc_jac(), call_gen(), casadi::Nlpsol::callback(), casadi::FiniteDiff::codegen_body(), casadi::Sqpmethod::codegen_qp_ela_solve(), casadi::Feasiblesqpmethod::codegen_qp_solve(), casadi::Sqpmethod::codegen_qp_solve(), conditional(), casadi::MapSum::create(), casadi::OracleFunction::create_function(), casadi::FiniteDiff::eval(), casadi::Scpgen::eval_exp(), casadi::Scpgen::eval_mat(), casadi::Scpgen::eval_res(), casadi::Scpgen::eval_vec(), casadi::MXFunction::export_code_body(), casadi::External::factory(), casadi::Blocksqp::feasibilityRestorationPhase(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::get_n_in(), casadi::FiniteDiff::get_n_in(), casadi::FunctionInternal::get_n_out(), casadi::FiniteDiff::get_n_out(), casadi::Switch::get_n_out(), casadi::FunctionInternal::get_name_in(), casadi::FiniteDiff::get_name_in(), casadi::FunctionInternal::get_sparsity_in(), casadi::FiniteDiff::get_sparsity_in(), casadi::Integrator::init(), casadi::Nlpsol::init(), casadi::Rootfinder::init(), casadi::BonminInterface::init(), casadi::IpoptInterface::init(), casadi::Feasiblesqpmethod::init(), casadi::Sqpmethod::init(), casadi::BonminInterface::intermediate_callback(), casadi::IpoptInterface::intermediate_callback(), jac_sparsity(), casadi::FunctionInternal::jacobian(), map(), mapaccum(), casadi::MapSum::MapSum(), casadi::SymbolicQr::nfact(), casadi::Call::nout(), casadi::qpsol_nlp(), rev(), casadi::FunctionInternal::reverse(), casadi::simpleIntegrator(), casadi::simpleIRK(), casadi::simpleRK(), casadi::WorhpInterface::solve(), casadi::Scpgen::solve(), casadi::SymbolicQr::solve(), casadi::Sqpmethod::solve_ela_QP(), casadi::Feasiblesqpmethod::solve_LP(), casadi::Feasiblesqpmethod::solve_QP(), casadi::Qrsqp::solve_QP(), casadi::Scpgen::solve_qp(), casadi::Sqpmethod::solve_QP(), and casadi::ThreadsWork().
name()
const std::string & casadi::Function::name () const
Extra doc: https://github.com/casadi/casadi/wiki/L_1xv
Definition at line 1250 of file function.cpp.
{
     if (is_null()) {
       static std::string null = "null";
       return null;
     } else {
       return (*this)->name_;
     }
   }
References casadi::SharedObject::is_null().
Referenced by casadi::CodeGenerator::add(), casadi::DaeBuilderInternal::add_fun(), casadi::Integrator::augmented_dae(), bspline(), casadi::Call::Call(), check_name(), conditional(), casadi::Callback::construct(), construct(), casadi::MapSum::create(), casadi::Map::create(), casadi::FixedStepIntegrator::create_advanced(), casadi::Call::disp(), casadi::Switch::disp_more(), expand(), factory(), find_function(), fix_name(), fold(), Function(), casadi::FunctionInternal::FunctionInternal(), generate(), casadi::Callback::get_forward(), casadi::MapSum::get_forward(), get_function(), casadi::Callback::get_jacobian(), casadi::FunctionInternal::get_n_in(), casadi::FunctionInternal::get_n_out(), casadi::FunctionInternal::get_name_in(), casadi::FunctionInternal::get_name_out(), casadi::Callback::get_reverse(), casadi::MapSum::get_reverse(), casadi::FunctionInternal::get_sparsity_in(), casadi::FunctionInternal::get_sparsity_out(), hessian_old(), if_else(), index_in(), index_out(), casadi::FunctionInternal::init(), casadi::ImplicitFixedStepIntegrator::init(), casadi::Rootfinder::init(), casadi::SundialsInterface::init(), casadi::FunctionInternal::jac_is_symm(), jacobian_old(), jit(), casadi::FunctionInternal::map(), map(), mapaccum(), print_option(), casadi::OracleFunction::set_function(), casadi::RungeKutta::setup_step(), slice(), and casadi::FunctionInternal::tocache().
name_in() [1/2]
const std::vector< std::string > & casadi::Function::name_in () const
Extra doc: https://github.com/casadi/casadi/wiki/L_1vg
Definition at line 919 of file function.cpp.
{
     return (*this)->name_in_;
   }
Referenced by assert_size_in(), casadi::OracleFunction::calc_function(), conditional(), construct(), casadi::DaeBuilderInternal::create(), expand(), casadi::External::factory(), fold(), Function(), casadi::KinsolInterface::get_jtimes(), casadi::FunctionInternal::get_name_in(), casadi::FiniteDiff::get_name_in(), casadi::FunctionInternal::get_name_out(), hessian_old(), casadi::Rootfinder::init(), jacobian_old(), jit(), map(), mapaccum(), and casadi::qpsol_nlp().
name_in() [2/2]
const std::string & casadi::Function::name_in (casadi_int ind) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1vi
Definition at line 943 of file function.cpp.
{
     try {
       return (*this)->name_in_.at(ind);
     } catch(std::exception& e) {
       THROW_ERROR("name_in", e.what());
     }
   }
name_out() [1/2]
const std::vector< std::string > & casadi::Function::name_out () const
Extra doc: https://github.com/casadi/casadi/wiki/L_1vh
Definition at line 923 of file function.cpp.
{
     return (*this)->name_out_;
   }
Referenced by assert_size_out(), assert_sparsity_out(), casadi::OracleFunction::calc_function(), call_gen(), conditional(), construct(), casadi::DaeBuilderInternal::create(), expand(), casadi::External::factory(), fold(), Function(), casadi::KinsolInterface::get_jtimes(), casadi::FunctionInternal::get_name_in(), casadi::FiniteDiff::get_name_in(), casadi::FunctionInternal::get_name_out(), casadi::FiniteDiff::get_name_out(), hessian_old(), casadi::Rootfinder::init(), jacobian_old(), jit(), map(), mapaccum(), and casadi::qpsol_nlp().
name_out() [2/2]
const std::string & casadi::Function::name_out (casadi_int ind) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1vj
Definition at line 951 of file function.cpp.
{
     try {
       return (*this)->name_out_.at(ind);
     } catch(std::exception& e) {
       THROW_ERROR("name_out", e.what());
     }
   }
nnz_in() [1/3]
casadi_int casadi::Function::nnz_in () const
For a particular input or for all of the inputs
Extra doc: https://github.com/casadi/casadi/wiki/L_1vc
Definition at line 819 of file function.cpp.
{
     return (*this)->nnz_in();
   }
Referenced by casadi::_which_depends(), buf_in(), casadi::OracleFunction::calc_function(), casadi::FiniteDiff::codegen_body(), casadi::Map::codegen_body(), casadi::OmpMap::codegen_body(), casadi::MapSum::codegen_body(), casadi::FiniteDiff::eval(), casadi::OmpMap::eval(), casadi::Map::eval_gen(), casadi::MapSum::eval_gen(), casadi::Call::generate(), generate_in(), casadi::MapSum::get_forward(), casadi::MapSum::get_reverse(), casadi::FiniteDiff::init(), casadi::Rootfinder::init(), casadi::ImplicitToNlp::init(), casadi::QpToNlp::init(), casadi::FunctionBuffer::set_arg(), casadi::ImplicitToNlp::set_work(), casadi::ImplicitToNlp::solve(), casadi::Map::sp_reverse(), casadi::MapSum::sp_reverse(), and casadi::ThreadsWork().
nnz_in() [2/3]
casadi_int casadi::Function::nnz_in (casadi_int ind) const
For a particular input or for all of the inputs
Extra doc: https://github.com/casadi/casadi/wiki/L_1vc
Definition at line 835 of file function.cpp.
{
     return (*this)->nnz_in(ind);
   }
nnz_in() [3/3]
casadi_int casadi::Function::nnz_in (const std::string & iname) const inline
For a particular input or for all of the inputs
Extra doc: https://github.com/casadi/casadi/wiki/L_1vc
Definition at line 271 of file function.hpp.
 {return nnz_in(index_in(iname));}
References nnz_in().
Referenced by nnz_in().
nnz_out() [1/3]
casadi_int casadi::Function::nnz_out () const
For a particular output or for all of the outputs
Extra doc: https://github.com/casadi/casadi/wiki/L_1vd
Definition at line 823 of file function.cpp.
{
     return (*this)->nnz_out();
   }
Referenced by casadi::_which_depends(), buf_out(), casadi::OracleFunction::calc_function(), casadi::FiniteDiff::codegen_body(), casadi::Map::codegen_body(), casadi::OmpMap::codegen_body(), casadi::MapSum::codegen_body(), casadi::FiniteDiff::eval(), casadi::OmpMap::eval(), casadi::Map::eval_gen(), casadi::MapSum::eval_gen(), casadi::Call::generate(), generate_out(), casadi::FiniteDiff::init(), casadi::FixedStepIntegrator::init(), casadi::MapSum::init(), casadi::Rootfinder::init(), casadi::SundialsInterface::init(), casadi::SuperscsInterface::init(), casadi::SymbolicQr::init_mem(), casadi::FunctionBuffer::set_res(), casadi::SundialsInterface::set_work(), casadi::SuperscsInterface::solve(), casadi::Map::sp_reverse(), casadi::MapSum::sp_reverse(), and casadi::ThreadsWork().
nnz_out() [2/3]
casadi_int casadi::Function::nnz_out (casadi_int ind) const
For a particular output or for all of the outputs
Extra doc: https://github.com/casadi/casadi/wiki/L_1vd
Definition at line 839 of file function.cpp.
{
     return (*this)->nnz_out(ind);
   }
nnz_out() [3/3]
casadi_int casadi::Function::nnz_out (const std::string & oname) const inline
For a particular output or for all of the outputs
Extra doc: https://github.com/casadi/casadi/wiki/L_1vd
Definition at line 282 of file function.hpp.
 {return nnz_out(index_out(oname));}
References nnz_out().
Referenced by nnz_out().
nominal_in()
std::vector< double > casadi::Function::nominal_in (casadi_int ind) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1vp
Definition at line 1435 of file function.cpp.
{
     return (*this)->get_nominal_in(ind);
   }
Referenced by casadi::Integrator::init().
nominal_out()
std::vector< double > casadi::Function::nominal_out (casadi_int ind) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1vq
Definition at line 1439 of file function.cpp.
{
     return (*this)->get_nominal_out(ind);
   }
numel_in() [1/3]
casadi_int casadi::Function::numel_in () const
For a particular input or for all of the inputs
Extra doc: https://github.com/casadi/casadi/wiki/L_1ve
Definition at line 827 of file function.cpp.
{
     return (*this)->numel_in();
   }
Referenced by casadi::Integrator::init().
numel_in() [2/3]
casadi_int casadi::Function::numel_in (casadi_int ind) const
For a particular input or for all of the inputs
Extra doc: https://github.com/casadi/casadi/wiki/L_1ve
Definition at line 843 of file function.cpp.
{
     return (*this)->numel_in(ind);
   }
numel_in() [3/3]
casadi_int casadi::Function::numel_in (const std::string & iname) const inline
For a particular input or for all of the inputs
Extra doc: https://github.com/casadi/casadi/wiki/L_1ve
Definition at line 293 of file function.hpp.
 {return numel_in(index_in(iname));}
References numel_in().
Referenced by numel_in().
numel_out() [1/3]
casadi_int casadi::Function::numel_out () const
For a particular output or for all of the outputs
Extra doc: https://github.com/casadi/casadi/wiki/L_1vf
Definition at line 831 of file function.cpp.
{
     return (*this)->numel_out();
   }
Referenced by casadi::Integrator::init(), and casadi::Nlpsol::init().
numel_out() [2/3]
casadi_int casadi::Function::numel_out (casadi_int ind) const
For a particular output or for all of the outputs
Extra doc: https://github.com/casadi/casadi/wiki/L_1vf
Definition at line 847 of file function.cpp.
{
     return (*this)->numel_out(ind);
   }
numel_out() [3/3]
casadi_int casadi::Function::numel_out (const std::string & oname) const inline
For a particular output or for all of the outputs
Extra doc: https://github.com/casadi/casadi/wiki/L_1vf
Definition at line 304 of file function.hpp.
 {return numel_out(index_out(oname));}
References numel_out().
Referenced by numel_out().
nz_from_in()
std::vector< double > casadi::Function::nz_from_in (const std::vector< DM > & arg) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1x6
Definition at line 1543 of file function.cpp.
{
     return (*this)->nz_in(arg);
   }
Referenced by generate_in().
nz_from_out()
std::vector< double > casadi::Function::nz_from_out (const std::vector< DM > & arg) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1x6
Definition at line 1547 of file function.cpp.
{
     return (*this)->nz_out(res);
   }
Referenced by generate_out().
nz_to_in()
std::vector< DM > casadi::Function::nz_to_in (const std::vector< double > & arg) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1x6
Definition at line 1551 of file function.cpp.
{
     return (*this)->nz_in(arg);
   }
Referenced by generate_in().
nz_to_out()
std::vector< DM > casadi::Function::nz_to_out (const std::vector< double > & arg) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1x6
Definition at line 1555 of file function.cpp.
{
     return (*this)->nz_out(res);
   }
Referenced by generate_out().
operator()() [1/24]
int casadi::Function::operator() (const bvec_t ** arg, bvec_t ** res, casadi_int * iw, bvec_t * w, int mem = 0) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1we
Definition at line 1035 of file function.cpp.
{
     try {
       return (*this)->sp_forward(arg, res, iw, w, memory(mem));
     } catch(std::exception& e) {
       THROW_ERROR("operator()", e.what());
     }
   }
References memory().
operator()() [2/24]
std::vector<DM> casadi::Function::operator() (const DM & arg0) const inline
Functor shorthand for evaluation, single argument (only C++)
Definition at line 588 of file function.hpp.
{
       return operator()(std::vector<DM>{arg0});
     }
operator()() [3/24]
const DMDict casadi::Function::operator() (const DMDict & arg) const
Functor shorthand for evaluation
Definition at line 1378 of file function.cpp.
{
     DMDict res;
     call(arg, res);
     return res;
   }
References call().
operator()() [4/24]
int casadi::Function::operator() (const double ** arg, double ** res, casadi_int * iw, double * w) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1wc
Definition at line 1448 of file function.cpp.
{
     scoped_checkout<Function> mem(*this);
     return operator()(arg, res, iw, w, mem);
   }
References operator()().
operator()() [5/24]
int casadi::Function::operator() (const double ** arg, double ** res, casadi_int * iw, double * w, int mem) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1wb
Definition at line 1454 of file function.cpp.
{
     try {
 #ifdef WITH_EXTRA_CHECKS
       // Should never happen
       casadi_assert_dev(call_depth_>=0);
       call_depth_++;
       // For consistency check
       casadi_int depth = call_depth_;
 #endif // WITH_EXTRA_CHECKS
       int ret = (*this)->eval_gen(arg, res, iw, w, memory(mem));
 #ifdef WITH_EXTRA_CHECKS
       // Consitency check
       casadi_assert_dev(call_depth_==depth);
       call_depth_--;
 #endif // WITH_EXTRA_CHECKS
       return ret;
     } catch (KeyboardInterruptException& e) {
       (void)e;  // unused
 #ifdef WITH_EXTRA_CHECKS
       call_depth_--;
 #endif // WITH_EXTRA_CHECKS
       throw;
     } catch(std::exception& e) {
 #ifdef WITH_EXTRA_CHECKS
       call_depth_--;
 #endif // WITH_EXTRA_CHECKS
       (*this)->print_in(uerr(), arg, true);
       THROW_ERROR("operator()", e.what());
     }
   }
References memory(), casadi::uerr(), and casadi::CasadiException::what().
operator()() [6/24]
std::vector<MX> casadi::Function::operator() (const MX & arg0) const inline
Functor shorthand for evaluation, single argument (only C++)
Definition at line 594 of file function.hpp.
{
       return operator()(std::vector<MX>{arg0});
     }
operator()() [7/24]
const MXDict casadi::Function::operator() (const MXDict & arg) const
Functor shorthand for evaluation
Definition at line 1390 of file function.cpp.
{
     MXDict res;
     call(arg, res);
     return res;
   }
References call().
operator()() [8/24]
std::vector< DM > casadi::Function::operator() (const std::vector< DM > & arg) const
Functor shorthand for evaluation
Definition at line 1343 of file function.cpp.
{
     std::vector<DM> res;
     call(arg, res);
     return res;
   }
References call().
Referenced by operator()().
operator()() [9/24]
std::vector< MX > casadi::Function::operator() (const std::vector< MX > & arg) const
Functor shorthand for evaluation
Definition at line 1355 of file function.cpp.
{
     std::vector<MX> res;
     call(arg, res);
     return res;
   }
References call().
operator()() [10/24]
std::vector< SX > casadi::Function::operator() (const std::vector< SX > & arg) const
Functor shorthand for evaluation
Definition at line 1349 of file function.cpp.
{
     std::vector<SX> res;
     call(arg, res);
     return res;
   }
References call().
operator()() [11/24]
std::vector<SX> casadi::Function::operator() (const SX & arg0) const inline
Functor shorthand for evaluation, single argument (only C++)
Definition at line 591 of file function.hpp.
{
       return operator()(std::vector<SX>{arg0});
     }
operator()() [12/24]
const SXDict casadi::Function::operator() (const SXDict & arg) const
Functor shorthand for evaluation
Definition at line 1384 of file function.cpp.
{
     SXDict res;
     call(arg, res);
     return res;
   }
References call().
operator()() [13/24]
int casadi::Function::operator() (const SXElem ** arg, SXElem ** res, casadi_int * iw, SXElem * w, int mem = 0) const
Same syntax as the double version, allowing use in templated code
Extra doc: https://github.com/casadi/casadi/wiki/L_1wd
Definition at line 1486 of file function.cpp.
{
     try {
       return (*this)->eval_sx(arg, res, iw, w, memory(mem));
     } catch(std::exception& e) {
       THROW_ERROR("operator()", e.what());
     }
   }
References memory().
operator()() [14/24]
void casadi::Function::operator() (MapArg arg, MapRes res) const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1wa
Definition at line 581 of file function.hpp.
 { (*this)(buf_in(arg), buf_out(res)); }
operator()() [15/24]
void casadi::Function::operator() (MapArg arg, MPrRes res) const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1wa
Definition at line 583 of file function.hpp.
 { (*this)(buf_in(arg), buf_out(res)); }
operator()() [16/24]
void casadi::Function::operator() (MapArg arg, VecRes res) const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1wa
Definition at line 580 of file function.hpp.
 { (*this)(buf_in(arg), buf_out(res)); }
operator()() [17/24]
void casadi::Function::operator() (MapArg arg, VPrRes res) const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1wa
Definition at line 582 of file function.hpp.
 { (*this)(buf_in(arg), buf_out(res)); }
operator()() [18/24]
void casadi::Function::operator() (std::vector< const bvec_t * > arg, std::vector< bvec_t * > res) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1w8
Definition at line 452 of file function.cpp.
{
     return call_gen(arg, res);
   }
References call_gen().
operator()() [19/24]
void casadi::Function::operator() (std::vector< const double * > arg, std::vector< double * > res) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1w8
Definition at line 448 of file function.cpp.
{
     return call_gen(arg, res);
   }
References call_gen().
operator()() [20/24]
void casadi::Function::operator() (std::vector< const SXElem * > arg, std::vector< SXElem * > res) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1w8
Definition at line 456 of file function.cpp.
{
     return call_gen(arg, res);
   }
References call_gen().
operator()() [21/24]
void casadi::Function::operator() (VecArg arg, MapRes res) const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1wa
Definition at line 576 of file function.hpp.
 { (*this)(buf_in(arg), buf_out(res)); }
operator()() [22/24]
void casadi::Function::operator() (VecArg arg, MPrRes res) const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1wa
Definition at line 578 of file function.hpp.
 { (*this)(buf_in(arg), buf_out(res)); }
operator()() [23/24]
void casadi::Function::operator() (VecArg arg, VecRes res) const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1wa
Definition at line 575 of file function.hpp.
 { (*this)(buf_in(arg), buf_out(res)); }
operator()() [24/24]
void casadi::Function::operator() (VecArg arg, VPrRes res) const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1wa
Definition at line 577 of file function.hpp.
 { (*this)(buf_in(arg), buf_out(res)); }
operator->()
FunctionInternal * casadi::Function::operator-> () const
Extra doc: https://github.com/casadi/casadi/wiki/L_1x3
Definition at line 316 of file function.cpp.
{
     casadi_assert_dev(!is_null());
     return get();
   }
References get(), and casadi::SharedObject::is_null().
operator==()
bool casadi::Function::operator== (const Function & f) const
Definition at line 1862 of file function.cpp.
{
     try {
       casadi_assert(!is_null(), "lhs is null");
       casadi_assert(!f.is_null(), "rhs is null");
       return get()==f.get();
     } catch(std::exception& e) {
       THROW_ERROR("operator==", e.what());
     }
   }
References get(), and casadi::SharedObject::is_null().
oracle()
Function casadi::Function::oracle () const
Extra doc: https://github.com/casadi/casadi/wiki/L_1vu
Definition at line 1846 of file function.cpp.
{
     try {
       return (*this)->oracle();
     } catch(std::exception& e) {
       THROW_ERROR("oracle", e.what());
     }
   }
References casadi::FunctionInternal::oracle().
own()
void casadi::SharedObject::own (SharedObjectInternal * node) inherited
Assign the node to a node class pointer (or null)
Definition at line 46 of file shared_object.cpp.
{
     count_down();
     node = node_;
     count_up();
   }
References casadi::SharedObject::count_down(), and casadi::SharedObject::count_up().
Referenced by casadi::Callback::construct(), construct(), create(), casadi::Importer::create(), casadi::Linsol::create(), casadi::GenericType::create(), casadi::Sparsity::create(), casadi::DaeBuilder::DaeBuilder(), casadi::FunctionInternal::deserialize(), casadi::Linsol::deserialize(), casadi::GenericType::GenericType(), casadi::LinearInterpolant::get_jacobian(), casadi::Importer::Importer(), casadi::MXFunction::init(), casadi::Linsol::Linsol(), casadi::MX::MX(), casadi::Opti::Opti(), casadi::WeakRef::shared(), casadi::WeakRef::WeakRef(), and casadi::XmlFile::XmlFile().
print_dimensions()
void casadi::Function::print_dimensions (std::ostream & stream = casadi::uout()) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1vy
Definition at line 1095 of file function.cpp.
{
     (*this)->print_dimensions(stream);
   }
print_option()
void casadi::Function::print_option (const std::string & name, std::ostream & stream = casadi::uout()) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1w0
Definition at line 1103 of file function.cpp.
{
     (*this)->print_option(name, stream);
   }
References name().
print_options()
void casadi::Function::print_options (std::ostream & stream = casadi::uout()) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1vz
Definition at line 1099 of file function.cpp.
{
     (*this)->print_options(stream);
   }
print_ptr()
void casadi::SharedObject::print_ptr (std::ostream & stream = casadi::uout()) const inherited
Print the pointer to the internal class
Definition at line 111 of file shared_object.cpp.
{
     stream << node;
   }
proceed_to()
bool casadi::Function::proceed_to (std::istream & file, const std::string & str) static protected
Definition at line 62 of file function.cpp.
{
     // Make sure that the file is ready for reading
     if (!file.good()) return false;
     // Have we already wrapped around once?
     //bool wrapped_around = false;
     // Read line-by-line
     std::string tmp;
     while (true) {
       // Read a word
       std::streampos cur_pos = file.tellg();
       file >> tmp;
       if (!file.good()) return false;
       // Check if match
       if (str==tmp) return true;
       // If comment, continue to the end of the line
       if (tmp.at(0)=='#') {
         file.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
         continue;
       }
       // If mismatching name, rewind and break
       file.seekg(cur_pos);
       return false;
     }
   }
References casadi::str().
release()
void casadi::Function::release (int mem) const
Definition at line 1715 of file function.cpp.
{
     (*this)->release(mem);
   }
Referenced by casadi::QpToNlp::free_mem(), and casadi::FunctionBuffer::~FunctionBuffer().
rev() [1/2]
int casadi::Function::rev (bvec_t ** arg, bvec_t ** res, casadi_int * iw, bvec_t * w, int mem = 0) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1wf
Definition at line 1044 of file function.cpp.
{
     try {
       return (*this)->sp_reverse(arg, res, iw, w, memory(mem));
     } catch(std::exception& e) {
       THROW_ERROR("rev", e.what());
     }
   }
References memory().
Referenced by casadi::_which_depends(), rev(), casadi::Call::sp_reverse(), casadi::Map::sp_reverse(), casadi::MapSum::sp_reverse(), and casadi::Rootfinder::sp_reverse().
rev() [2/2]
int casadi::Function::rev (std::vector< bvec_t * > arg, std::vector< bvec_t * > res) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1wg
Definition at line 460 of file function.cpp.
{
     // Input buffer
     casadi_assert_dev(arg.size()>=n_in());
     arg.resize(sz_arg());
     // Output buffer
     casadi_assert_dev(res.size()>=n_out());
     res.resize(sz_res());
     // Work vectors
     std::vector<casadi_int> iw(sz_iw());
     std::vector<bvec_t> w(sz_w());
     // Evaluate memoryless
     return rev(get_ptr(arg), get_ptr(res), get_ptr(iw), get_ptr(w), 0);
   }
References casadi::get_ptr(), n_in(), n_out(), rev(), sz_arg(), sz_iw(), sz_res(), and sz_w().
reverse()
Function casadi::Function::reverse (casadi_int nadj) const
   Returns a function with <tt>n_in + n_out + n_out</tt> inputs
   and <tt>n_in</tt> outputs.
   The first <tt>n_in</tt> inputs correspond to nondifferentiated inputs.
   The next <tt>n_out</tt> inputs correspond to nondifferentiated outputs.
   and the last <tt>n_out</tt> inputs correspond to adjoint seeds,
   stacked horizontally
   The  <tt>n_in</tt> outputs correspond to adjoint sensitivities,
   stacked horizontally.     *
   <tt>(n_in = n_in(), n_out = n_out())</tt>
   <tt>(n_in = n_in(), n_out = n_out())</tt>
  The functions returned are cached, meaning that if called multiple timed
  with the same value, then multiple references to the same function will be returned.
Extra doc: https://github.com/casadi/casadi/wiki/L_1wr
Definition at line 1087 of file function.cpp.
{
     try {
       return (*this)->reverse(nadj);
     } catch(std::exception& e) {
       THROW_ERROR("reverse", e.what());
     }
   }
References casadi::FunctionInternal::reverse().
Referenced by casadi::DaeBuilderInternal::export_fmu(), casadi::Map::get_reverse(), casadi::MapSum::get_reverse(), casadi::Nlpsol::get_reverse(), casadi::Switch::get_reverse(), casadi::Integrator::init(), casadi::ImplicitFixedStepIntegrator::init(), casadi::FunctionInternal::reverse(), and casadi::RungeKutta::setup_step().
save()
void casadi::Function::save (const std::string & fname, const Dict & opts = Dict()) const
See also
load
Extra doc: https://github.com/casadi/casadi/wiki/L_240
Definition at line 1212 of file function.cpp.
{
     FileSerializer fs(fname, opts);
     fs.pack(*this);
   }
References casadi::SerializerBase::pack().
serialize() [1/3]
std::string casadi::Function::serialize (const Dict & opts = Dict()) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1x2
Definition at line 1217 of file function.cpp.
{
     std::stringstream ss;
     serialize(ss, opts);
     return ss.str();
   }
References serialize().
serialize() [2/3]
void casadi::Function::serialize (SerializingStream & s) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1x1
Definition at line 1228 of file function.cpp.
{
     if (is_null()) {
       s.pack("Function::null", true);
     } else {
       s.pack("Function::null", false);
       (*this)->serialize(s);
     }
   }
References casadi::SharedObject::is_null(), and casadi::SerializingStream::pack().
serialize() [3/3]
void casadi::Function::serialize (std::ostream & stream, const Dict & opts = Dict()) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1x0
Definition at line 1223 of file function.cpp.
{
     SerializingStream s(stream, opts);
     return serialize(s);
   }
Referenced by serialize().
set_temp()
void casadi::Function::set_temp (const double ** arg, double ** res, casadi_int * iw, double * w, int mem = 0) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1xs
Definition at line 1061 of file function.cpp.
{
     try {
       (*this)->set_temp(memory(mem), arg, res, iw, w);
     } catch(std::exception& e) {
       THROW_ERROR("set_temp", e.what());
     }
   }
References memory().
set_work()
void casadi::Function::set_work (const double **& arg, double **& res, casadi_int *& iw, double *& w, int mem = 0) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1xr
Definition at line 1052 of file function.cpp.
{
     try {
       (*this)->set_work(memory(mem), arg, res, iw, w);
     } catch(std::exception& e) {
       THROW_ERROR("set_work", e.what());
     }
   }
References memory().
setup()
void casadi::Function::setup (const double ** arg, double ** res, casadi_int * iw, double * w, int mem = 0) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1xt
Definition at line 1070 of file function.cpp.
{
     try {
       (*this)->setup(memory(mem), arg, res, iw, w);
     } catch(std::exception& e) {
       THROW_ERROR("setup", e.what());
     }
   }
References memory().
size1_in() [1/2]
casadi_int casadi::Function::size1_in (casadi_int ind) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1va
Definition at line 795 of file function.cpp.
{
     return (*this)->size1_in(ind);
   }
Referenced by assert_size_in(), casadi::Blocksqp::feasibilityRestorationPhase(), and casadi::Blocksqp::init().
size1_in() [2/2]
casadi_int casadi::Function::size1_in (const std::string & iname) const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1va
Definition at line 240 of file function.hpp.
 {return size1_in(index_in(iname));}
References size1_in().
Referenced by size1_in().
size1_out() [1/2]
casadi_int casadi::Function::size1_out (casadi_int ind) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1vb
Definition at line 803 of file function.cpp.
{
     return (*this)->size1_out(ind);
   }
Referenced by assert_size_out(), and casadi::Blocksqp::init().
size1_out() [2/2]
casadi_int casadi::Function::size1_out (const std::string & oname) const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1vb
Definition at line 254 of file function.hpp.
 {return size1_out(index_out(oname));}
References size1_out().
Referenced by size1_out().
size2_in() [1/2]
casadi_int casadi::Function::size2_in (casadi_int ind) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1va
Definition at line 799 of file function.cpp.
{
     return (*this)->size2_in(ind);
   }
Referenced by assert_size_in(), map(), and mapaccum().
size2_in() [2/2]
casadi_int casadi::Function::size2_in (const std::string & iname) const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1va
Definition at line 242 of file function.hpp.
 {return size2_in(index_in(iname));}
References size2_in().
Referenced by size2_in().
size2_out() [1/2]
casadi_int casadi::Function::size2_out (casadi_int ind) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1vb
Definition at line 807 of file function.cpp.
{
     return (*this)->size2_out(ind);
   }
Referenced by assert_size_out(), fold(), and map().
size2_out() [2/2]
casadi_int casadi::Function::size2_out (const std::string & oname) const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1vb
Definition at line 256 of file function.hpp.
 {return size2_out(index_out(oname));}
References size2_out().
Referenced by size2_out().
size_in() [1/2]
std::pair< casadi_int, casadi_int > casadi::Function::size_in (casadi_int ind) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1va
Definition at line 811 of file function.cpp.
{
     return (*this)->size_in(ind);
   }
Referenced by casadi::DaeBuilderInternal::CallIO::calc_jac(), casadi::Integrator::get_reverse(), and casadi::Nlpsol::init().
size_in() [2/2]
std::pair<casadi_int, casadi_int> casadi::Function::size_in (const std::string & iname) const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1va
Definition at line 244 of file function.hpp.
{
       return size_in(index_in(iname));
     }
size_out() [1/2]
std::pair< casadi_int, casadi_int > casadi::Function::size_out (casadi_int ind) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1vb
Definition at line 815 of file function.cpp.
{
     return (*this)->size_out(ind);
   }
Referenced by casadi::DaeBuilderInternal::CallIO::calc_jac(), casadi::SqicInterface::generateNativeCode(), casadi::FunctionInternal::get_sparsity_in(), and casadi::SqicInterface::init().
size_out() [2/2]
std::pair<casadi_int, casadi_int> casadi::Function::size_out (const std::string & oname) const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1vb
Definition at line 258 of file function.hpp.
{
       return size_out(index_out(oname));
     }
slice()
Function casadi::Function::slice (const std::string & name, const std::vector< casadi_int > & order_in, const std::vector< casadi_int > & order_out, const Dict & opts = Dict()) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1wl
Definition at line 714 of file function.cpp.
{
     try {
       return (*this)->slice(name, order_in, order_out, opts);
     } catch(std::exception& e) {
       THROW_ERROR("slice", e.what());
     }
   }
References name(), and casadi::FunctionInternal::slice().
Referenced by mapaccum(), and casadi::FunctionInternal::slice().
sparsity_in() [1/2]
const Sparsity & casadi::Function::sparsity_in (casadi_int ind) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1vr
Definition at line 959 of file function.cpp.
{
     try {
       return (*this)->sparsity_in_.at(ind);
     } catch(std::exception& e) {
       THROW_ERROR("sparsity_in", e.what());
     }
   }
Referenced by casadi::Call::Call(), casadi::Switch::codegen_body(), casadi::Switch::eval_sx(), casadi::Blocksqp::feasibilityRestorationPhase(), casadi::Integrator::get_forward_dae(), casadi::FunctionInternal::get_sparsity_in(), casadi::FiniteDiff::get_sparsity_in(), casadi::Nlpsol::get_sparsity_in(), casadi::Switch::get_sparsity_in(), casadi::FunctionInternal::get_sparsity_out(), casadi::Nlpsol::get_sparsity_out(), casadi::Integrator::init(), casadi::Nlpsol::init(), casadi::Rootfinder::init(), casadi::Switch::init(), jit(), map(), casadi::Collocation::setup_step(), casadi::RungeKutta::setup_step(), casadi::simpleIntegrator(), casadi::simpleIRK(), casadi::simpleRK(), and sparsity_in().
sparsity_in() [2/2]
const Sparsity & casadi::Function::sparsity_in (const std::string & iname) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1vr
Definition at line 967 of file function.cpp.
{
     try {
       return sparsity_in(index_in(iname));
     } catch(std::exception& e) {
       THROW_ERROR("sparsity_in", e.what());
     }
   }
References index_in(), and sparsity_in().
sparsity_jac() [1/4]
const Sparsity casadi::Function::sparsity_jac (casadi_int iind, casadi_int oind, bool compact = false, bool symmetric = false) const
[DEPRECATED] Get, if necessary generate, the sparsity of a Jacobian block
Definition at line 874 of file function.cpp.
{
     try {
       return (*this)->jac_sparsity(oind, iind, compact, symmetric);
     } catch(std::exception& e) {
       THROW_ERROR("sparsity_jac", e.what());
     }
   }
Referenced by casadi::Blocksqp::init().
sparsity_jac() [2/4]
const Sparsity casadi::Function::sparsity_jac (casadi_int iind, const std::string & oind, bool compact = false, bool symmetric = false) const inline
[DEPRECATED] Get, if necessary generate, the sparsity of a Jacobian block
Definition at line 481 of file function.hpp.
{
       return sparsity_jac(iind, index_out(oind), compact, symmetric);
     }
sparsity_jac() [3/4]
const Sparsity casadi::Function::sparsity_jac (const std::string & iind, casadi_int oind = 0, bool compact = false, bool symmetric = false) const inline
[DEPRECATED] Get, if necessary generate, the sparsity of a Jacobian block
Definition at line 477 of file function.hpp.
{
       return sparsity_jac(index_in(iind), oind, compact, symmetric);
     }
sparsity_jac() [4/4]
const Sparsity casadi::Function::sparsity_jac (const std::string & iind, const std::string & oind, bool compact = false, bool symmetric = false) const inline
[DEPRECATED] Get, if necessary generate, the sparsity of a Jacobian block
Definition at line 485 of file function.hpp.
{
       return sparsity_jac(index_in(iind), index_out(oind), compact, symmetric);
     }
sparsity_out() [1/2]
const Sparsity & casadi::Function::sparsity_out (casadi_int ind) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1vs
Definition at line 975 of file function.cpp.
{
     try {
       return (*this)->sparsity_out_.at(ind);
     } catch(std::exception& e) {
       THROW_ERROR("sparsity_out", e.what());
     }
   }
Referenced by assert_sparsity_out(), casadi::OracleFunction::calc_function(), casadi::Switch::codegen_body(), conditional(), casadi::Switch::eval_sx(), casadi::MXFunction::export_code_body(), casadi::Blocksqp::feasibilityRestorationPhase(), casadi::Integrator::get_forward_dae(), casadi::FunctionInternal::get_sparsity_in(), casadi::FiniteDiff::get_sparsity_in(), casadi::FunctionInternal::get_sparsity_out(), casadi::FiniteDiff::get_sparsity_out(), casadi::Nlpsol::get_sparsity_out(), casadi::Switch::get_sparsity_out(), casadi::Integrator::init(), casadi::Nlpsol::init(), casadi::Rootfinder::init(), casadi::Switch::init(), casadi::KnitroInterface::init(), casadi::SnoptInterface::init(), casadi::SundialsInterface::init(), casadi::SuperscsInterface::init(), casadi::Qrsqp::init(), casadi::Scpgen::init(), casadi::SuperscsInterface::init_mem(), jit(), casadi::IdasInterface::psetupF(), casadi::Call::sparsity(), and sparsity_out().
sparsity_out() [2/2]
const Sparsity & casadi::Function::sparsity_out (const std::string & iname) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1vs
Definition at line 983 of file function.cpp.
{
     try {
       return sparsity_out(index_out(iname));
     } catch(std::exception& e) {
       THROW_ERROR("sparsity_out", e.what());
     }
   }
References index_out(), and sparsity_out().
stats()
Dict casadi::Function::stats (int mem = 0) const
Definition at line 896 of file function.cpp.
{
     return (*this)->get_stats(memory(mem));
   }
References memory().
Referenced by casadi::DaeBuilder::get(), casadi::MXFunction::get_stats(), casadi::ImplicitToNlp::get_stats(), and casadi::OptiNode::stats().
swap()
void casadi::SharedObject::swap (SharedObject & other) inherited
Definition at line 115 of file shared_object.cpp.
{
     SharedObject temp = *this;
     *this = other;
     other = temp;
   }
sx_in() [1/3]
const std::vector< SX > casadi::Function::sx_in () const
There is no guarantee that subsequent calls return unique answers
Extra doc: https://github.com/casadi/casadi/wiki/L_1x4
Definition at line 1511 of file function.cpp.
{
     try {
       return (*this)->sx_in();
     } catch(std::exception& e) {
       THROW_ERROR("sx_in", e.what());
     }
   }
Referenced by expand().
sx_in() [2/3]
const SX casadi::Function::sx_in (casadi_int iind) const
There is no guarantee that subsequent calls return unique answers
Extra doc: https://github.com/casadi/casadi/wiki/L_1x4
Definition at line 1495 of file function.cpp.
{
     try {
       return (*this)->sx_in(iind);
     } catch(std::exception& e) {
       THROW_ERROR("sx_in", e.what());
     }
   }
Referenced by casadi::Matrix< Scalar >::get_input(), casadi::AmplInterface::init(), and casadi::qpsol_nlp().
sx_in() [3/3]
const SX casadi::Function::sx_in (const std::string & iname) const inline
There is no guarantee that subsequent calls return unique answers
Extra doc: https://github.com/casadi/casadi/wiki/L_1x4
Definition at line 941 of file function.hpp.
{
       return sx_in(index_in(iname));
     }
sx_out() [1/3]
const std::vector< SX > casadi::Function::sx_out () const
There is no guarantee that subsequent calls return unique answers
Extra doc: https://github.com/casadi/casadi/wiki/L_1x5
Definition at line 1519 of file function.cpp.
{
     try {
       return (*this)->sx_out();
     } catch(std::exception& e) {
       THROW_ERROR("sx_out", e.what());
     }
   }
sx_out() [2/3]
const SX casadi::Function::sx_out (casadi_int oind) const
There is no guarantee that subsequent calls return unique answers
Extra doc: https://github.com/casadi/casadi/wiki/L_1x5
Definition at line 1503 of file function.cpp.
{
     try {
       return (*this)->sx_out(oind);
     } catch(std::exception& e) {
       THROW_ERROR("sx_out", e.what());
     }
   }
sx_out() [3/3]
const SX casadi::Function::sx_out (const std::string & oname) const inline
There is no guarantee that subsequent calls return unique answers
Extra doc: https://github.com/casadi/casadi/wiki/L_1x5
Definition at line 959 of file function.hpp.
{
       return sx_out(index_out(oname));
     }
sz_arg()
size_t casadi::Function::sz_arg () const
Extra doc: https://github.com/casadi/casadi/wiki/L_1xm
Definition at line 1027 of file function.cpp.
 { return (*this)->sz_arg();}
Referenced by casadi::SymbolicQrMemory::alloc(), buf_in(), call_gen(), casadi::Blocksqp::feasibilityRestorationPhase(), casadi::FunctionBuffer::FunctionBuffer(), casadi::Map::init(), casadi::OmpMap::init(), casadi::ThreadMap::init(), casadi::MapSum::init(), casadi::BSplineInterpolant::init(), rev(), casadi::Call::sz_arg(), and sz_work().
sz_iw()
size_t casadi::Function::sz_iw () const
Extra doc: https://github.com/casadi/casadi/wiki/L_1xo
Definition at line 1031 of file function.cpp.
 { return (*this)->sz_iw();}
Referenced by casadi::SymbolicQrMemory::alloc(), call_gen(), casadi::Blocksqp::feasibilityRestorationPhase(), casadi::FunctionBuffer::FunctionBuffer(), casadi::Map::init(), casadi::OmpMap::init(), casadi::ThreadMap::init(), casadi::MapSum::init(), casadi::BSplineInterpolant::init(), rev(), casadi::Call::sz_iw(), and sz_work().
sz_res()
size_t casadi::Function::sz_res () const
Extra doc: https://github.com/casadi/casadi/wiki/L_1xn
Definition at line 1029 of file function.cpp.
 { return (*this)->sz_res();}
Referenced by casadi::SymbolicQrMemory::alloc(), buf_out(), call_gen(), casadi::Blocksqp::feasibilityRestorationPhase(), casadi::FunctionBuffer::FunctionBuffer(), casadi::Map::init(), casadi::OmpMap::init(), casadi::ThreadMap::init(), casadi::MapSum::init(), casadi::BSplineInterpolant::init(), rev(), casadi::Call::sz_res(), and sz_work().
sz_w()
size_t casadi::Function::sz_w () const
Extra doc: https://github.com/casadi/casadi/wiki/L_1xp
Definition at line 1033 of file function.cpp.
 { return (*this)->sz_w();}
Referenced by casadi::SymbolicQrMemory::alloc(), call_gen(), casadi::MapSum::codegen_body(), casadi::MapSum::eval_gen(), casadi::Blocksqp::feasibilityRestorationPhase(), casadi::FunctionBuffer::FunctionBuffer(), casadi::Map::init(), casadi::OmpMap::init(), casadi::ThreadMap::init(), casadi::MapSum::init(), casadi::Rootfinder::init(), casadi::BSplineInterpolant::init(), rev(), casadi::MapSum::sp_reverse(), casadi::Call::sz_w(), and sz_work().
sz_work()
void casadi::Function::sz_work (size_t & sz_arg, size_t & sz_res, size_t & sz_iw, size_t & sz_w) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1xq
Definition at line 1023 of file function.cpp.
{
     (*this)->sz_work(sz_arg, sz_res, sz_iw, sz_w);
   }
References sz_arg(), sz_iw(), sz_res(), and sz_w().
Referenced by casadi::FunctionInternal::alloc(), casadi::OmpMap::codegen_body(), casadi::OmpMap::eval(), casadi::OracleFunction::finalize(), and casadi::ThreadsWork().
test_cast()
bool casadi::Function::test_cast (const SharedObjectInternal * ptr) static
Definition at line 892 of file function.cpp.
{
     return dynamic_cast<const FunctionInternal*>(ptr)!=nullptr;
   }
type_name()
static std::string casadi::Function::type_name () inline static
Extra doc: https://github.com/casadi/casadi/wiki/L_1ux
Definition at line 65 of file function.hpp.
 {return "Function";}
uses_output()
bool casadi::Function::uses_output () const
Extra doc: https://github.com/casadi/casadi/wiki/L_1w3
Definition at line 851 of file function.cpp.
{
     return (*this)->uses_output();
   }
weak()
WeakRef * casadi::SharedObject::weak () inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_aw
Definition at line 125 of file shared_object.cpp.
{
     return (*this)->weak();
   }
References casadi::SharedObjectInternal::weak().
Referenced by casadi::WeakRef::WeakRef().
which_depends()
std::vector< bool > casadi::Function::which_depends (const std::string & s_in, const std::vector< std::string > & s_out, casadi_int order = 1, bool tr = false) const
Parameters
[in] order Only 1 (linear) and 2 (nonlinear) allowed
[in] tr Flip the relationship. Return which expressions contain the variables
Extra doc: https://github.com/casadi/casadi/wiki/L_1vx
Definition at line 1763 of file function.cpp.
{
     try {
       return (*this)->which_depends(s_in, s_out, order, tr);
     } catch(std::exception& e) {
       THROW_ERROR("which_depends", e.what());
     }
   }
Referenced by casadi::BonminInterface::init(), casadi::IpoptInterface::init(), and casadi::KnitroInterface::init().
wrap()
Function casadi::Function::wrap () const
Extra doc: https://github.com/casadi/casadi/wiki/L_1vv
Definition at line 1854 of file function.cpp.
{
     return (*this)->wrap();
   }
References casadi::FunctionInternal::wrap().
wrap_as_needed()
Function casadi::Function::wrap_as_needed (const Dict & opts) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1vw
Definition at line 1858 of file function.cpp.
{
     return (*this)->wrap_as_needed(opts);
   }
References casadi::FunctionInternal::wrap_as_needed().
Referenced by casadi::MapSum::create().
The documentation for this class was generated from the following files:
function.hpp
function.cpp