CasADi: casadi::KeyboardInterruptException Class Reference
casadi::KeyboardInterruptException Class Reference
#include <exception.hpp>
Detailed Description
Definition at line 98 of file exception.hpp.
Public Member Functions
KeyboardInterruptException ()
Default constructor.
~KeyboardInterruptException () throw ()
Destructor.
const char * what () const override throw ()
Display error.
Protected Attributes
std::string msg_
Constructor & Destructor Documentation
KeyboardInterruptException()
casadi::KeyboardInterruptException::KeyboardInterruptException () inline
Definition at line 101 of file exception.hpp.
 : CasadiException("KeyboardInterrupt") {}
~KeyboardInterruptException()
casadi::KeyboardInterruptException::~KeyboardInterruptException () throw () inline
Definition at line 103 of file exception.hpp.
 {}
Member Function Documentation
what()
const char* casadi::CasadiException::what () const throw () inline override inherited
Definition at line 90 of file exception.hpp.
{
     return msg_.c_str();
   }
Referenced by casadi::accepted_iterate(), casadi::KnitroInterface::callback(), casadi::Nlpsol::callback(), casadi::AlpaqaProblem::eval_f(), casadi::BonminUserClass::eval_f(), casadi::IpoptUserClass::eval_f(), casadi::AlpaqaProblem::eval_f_grad_f(), casadi::AlpaqaProblem::eval_g(), casadi::BonminUserClass::eval_g(), casadi::IpoptUserClass::eval_g(), casadi::BonminUserClass::eval_grad_f(), casadi::IpoptUserClass::eval_grad_f(), casadi::AlpaqaProblem::eval_grad_L(), casadi::BonminUserClass::eval_h(), casadi::IpoptUserClass::eval_h(), casadi::AlpaqaProblem::eval_hess_L(), casadi::AlpaqaProblem::eval_hess_L_prod(), casadi::AlpaqaProblem::eval_hess_ψ(), casadi::AlpaqaProblem::eval_hess_ψ_prod(), casadi::AlpaqaProblem::eval_jac_g(), casadi::BonminUserClass::eval_jac_g(), casadi::IpoptUserClass::eval_jac_g(), casadi::AlpaqaProblem::eval_ψ(), casadi::AlpaqaProblem::eval_ψ_grad_ψ(), casadi::XFunction< DerivedType, MatType, NodeType >::factory(), casadi::PluginInterface< Derived >::has_plugin(), casadi::BonminInterface::intermediate_callback(), casadi::IpoptInterface::intermediate_callback(), casadi::Function::operator()(), and casadi::SnoptInterface::userfun().
Member Data Documentation
msg_
std::string casadi::CasadiException::msg_ protected inherited
Definition at line 95 of file exception.hpp.
The documentation for this class was generated from the following file:
exception.hpp