CasADi: casadi::SymbolicQrMemory Struct Reference
casadi::SymbolicQrMemory Struct Reference
Memory for SymbolicQR
#include <symbolic_qr.hpp>
Detailed Description
Definition at line 49 of file symbolic_qr.hpp.
Public Member Functions
void alloc (const Function &f)
void add_stat (const std::string &s)
Public Attributes
std::vector< const double * > arg
std::vector< double * > res
std::vector< casadi_int > iw
std::vector< double > w
std::vector< double > q
std::vector< double > r
bool is_sfact
bool is_nfact
std::map< std::string, FStats > fstats
FStats * t_total
Member Function Documentation
add_stat()
void casadi::ProtoFunctionMemory::add_stat (const std::string & s) inline inherited
Definition at line 74 of file function_internal.hpp.
{
       bool added = fstats.insert(std::make_pair(s, FStats())).second;
       casadi_assert(added, "Duplicate stat: '" + s + "'");
     }
Referenced by casadi::ProtoFunction::init_mem(), casadi::LinsolInternal::init_mem(), casadi::Nlpsol::init_mem(), casadi::OracleFunction::init_mem(), casadi::CbcInterface::init_mem(), casadi::ClpInterface::init_mem(), casadi::HpipmInterface::init_mem(), casadi::Feasiblesqpmethod::init_mem(), casadi::Sqpmethod::init_mem(), and casadi::OracleFunction::local_init_mem().
alloc()
void casadi::SymbolicQrMemory::alloc (const Function & f)
Definition at line 223 of file symbolic_qr.cpp.
{
     arg.resize(std::max(arg.size(), f.sz_arg()));
     res.resize(std::max(res.size(), f.sz_res()));
     iw.resize(std::max(iw.size(), f.sz_iw()));
     w.resize(std::max(w.size(), f.sz_w()));
   }
References arg, iw, res, casadi::Function::sz_arg(), casadi::Function::sz_iw(), casadi::Function::sz_res(), casadi::Function::sz_w(), and w.
Referenced by casadi::SymbolicQr::init_mem().
Member Data Documentation
arg
std::vector<const double*> casadi::SymbolicQrMemory::arg
Definition at line 51 of file symbolic_qr.hpp.
Referenced by alloc().
fstats
std::map<std::string, FStats> casadi::ProtoFunctionMemory::fstats inherited
Definition at line 68 of file function_internal.hpp.
Referenced by casadi::Nlpsol::callback(), casadi::IpoptUserClass::eval_h(), casadi::BonminInterface::intermediate_callback(), casadi::IpoptInterface::intermediate_callback(), casadi::OracleFunction::join_results(), casadi::HighsInterface::solve(), casadi::HpipmInterface::solve(), casadi::HpmpcInterface::solve(), casadi::ProxqpInterface::solve(), casadi::QpoasesInterface::solve(), casadi::Sqpmethod::solve_ela_QP(), casadi::Feasiblesqpmethod::solve_LP(), casadi::Feasiblesqpmethod::solve_QP(), and casadi::Sqpmethod::solve_QP().
is_nfact
bool casadi::LinsolMemory::is_nfact inherited
Definition at line 39 of file linsol_internal.hpp.
Referenced by casadi::Linsol::nfact().
is_sfact
bool casadi::LinsolMemory::is_sfact inherited
Definition at line 39 of file linsol_internal.hpp.
Referenced by casadi::Linsol::sfact().
iw
std::vector<casadi_int> casadi::SymbolicQrMemory::iw
Definition at line 53 of file symbolic_qr.hpp.
Referenced by alloc().
q
std::vector<double> casadi::SymbolicQrMemory::q
Definition at line 60 of file symbolic_qr.hpp.
r
std::vector<double> casadi::SymbolicQrMemory::r
Definition at line 60 of file symbolic_qr.hpp.
res
std::vector<double*> casadi::SymbolicQrMemory::res
Definition at line 52 of file symbolic_qr.hpp.
Referenced by alloc().
t_total
FStats* casadi::ProtoFunctionMemory::t_total inherited
Definition at line 71 of file function_internal.hpp.
Referenced by casadi::LinsolCall< Tr >::eval(), casadi::FunctionInternal::eval_gen(), and casadi::Linsol::solve().
w
std::vector<double> casadi::SymbolicQrMemory::w
Definition at line 54 of file symbolic_qr.hpp.
Referenced by alloc().
The documentation for this struct was generated from the following files:
symbolic_qr.hpp
symbolic_qr.cpp