CasADi: casadi::OutputStruct Struct Reference
casadi::OutputStruct Struct Reference
#include <fmu_function.hpp>
Detailed Description
Definition at line 113 of file fmu_function.hpp.
Public Member Functions
OutputStruct ()
Static Public Member Functions
static OutputStruct parse (const std::string &n, const Fmu *fmu, std::vector< std::string > *name_in=0, std::vector< std::string > *name_out=0)
Public Attributes
OutputType type
size_t ind
size_t wrt
size_t rbegin
size_t rend
size_t cbegin
size_t cend
Constructor & Destructor Documentation
OutputStruct()
casadi::OutputStruct::OutputStruct () inline
Definition at line 127 of file fmu_function.hpp.
 : ind(-1), wrt(-1), rbegin(-1), rend(-1), cbegin(-1), cend(-1) {}
Member Function Documentation
parse()
OutputStruct casadi::OutputStruct::parse (const std::string & n, const Fmu * fmu, std::vector< std::string > * name_in = 0, std::vector< std::string > * name_out = 0) static
Definition at line 607 of file fmu_function.cpp.
{
   // Return value
   OutputStruct s;
   // Look for prefix
   if (has_prefix(n)) {
     // Get the prefix
     std::string pref, rem;
     pref = pop_prefix(n, &rem);
     if (pref == "jac") {
       // Jacobian block
       casadi_assert(has_prefix(rem), "Two arguments expected for Jacobian block");
       pref = pop_prefix(rem, &rem);
       if (pref == "adj") {
         // Jacobian of adjoint sensitivity
         casadi_assert(has_prefix(rem), "Two arguments expected for Jacobian block");
         pref = pop_prefix(rem, &rem);
         if (has_prefix(rem)) {
           // Jacobian with respect to a sensitivity seed
           std::string sens = pref;
           pref = pop_prefix(rem, &rem);
           if (pref == "adj") {
             // Jacobian of adjoint sensitivity w.r.t. adjoint seed -> Transpose of Jacobian
             s.type = OutputType::JAC_TRANS;
             s.ind = fmu ? fmu->index_out(rem) : -1;
             if (name_out) name_out->push_back(rem);
             s.wrt = fmu ? fmu->index_in(sens) : -1;
             if (name_in) name_in->push_back(sens);
           } else if (pref == "out") {
             // Jacobian w.r.t. to dummy output
             s.type = OutputType::JAC_ADJ_OUT;
             s.ind = fmu ? fmu->index_in(sens) : -1;
             if (name_in) name_in->push_back(sens);
             s.wrt = fmu ? fmu->index_out(rem) : -1;
             if (name_in) name_out->push_back(rem);
           } else {
             casadi_error("No such prefix: " + pref);
           }
         } else {
           // Hessian output
           s.type = OutputType::HESS;
           s.ind = fmu ? fmu->index_in(pref) : -1;
           if (name_in) name_in->push_back(pref);
           s.wrt = fmu ? fmu->index_in(rem) : -1;
           if (name_in) name_in->push_back(rem);
         }
       } else {
         if (has_prefix(rem)) {
           std::string out = pref;
           pref = pop_prefix(rem, &rem);
           if (pref == "adj") {
             // Jacobian of regular output w.r.t. adjoint sensitivity seed
             s.type = OutputType::JAC_REG_ADJ;
             s.ind = fmu ? fmu->index_out(out) : -1;
             if (name_out) name_out->push_back(out);
             s.wrt = fmu ? fmu->index_out(rem) : -1;
             if (name_out) name_out->push_back(rem);
           } else {
             casadi_error("No such prefix: " + pref);
           }
         } else {
           // Regular Jacobian
           s.type = OutputType::JAC;
           s.ind = fmu ? fmu->index_out(pref) : -1;
           if (name_out) name_out->push_back(pref);
           s.wrt = fmu ? fmu->index_in(rem) : -1;
           if (name_in) name_in->push_back(rem);
         }
       }
     } else if (pref == "fwd") {
       // Forward sensitivity
       s.type = OutputType::FWD;
       s.ind = fmu ? fmu->index_out(rem) : -1;
       if (name_out) name_out->push_back(rem);
     } else if (pref == "adj") {
       // Adjoint sensitivity
       s.type = OutputType::ADJ;
       s.wrt = fmu ? fmu->index_in(rem) : -1;
       if (name_in) name_in->push_back(rem);
     } else {
       // No such prefix
       casadi_error("No such prefix: " + pref);
     }
   } else {
     // No prefix - regular output
     s.type = OutputType::REG;
     s.ind = fmu ? fmu->index_out(n) : -1;
     if (name_out) name_out->push_back(n);
   }
   // Return output struct
   return s;
 }
References casadi::ADJ, casadi::FWD, casadi::has_prefix(), casadi::HESS, ind, casadi::FmuInternal::index_in(), casadi::FmuInternal::index_out(), casadi::JAC, casadi::JAC_ADJ_OUT, casadi::JAC_REG_ADJ, casadi::JAC_TRANS, casadi::pop_prefix(), casadi::REG, type, and wrt.
Referenced by casadi::FmuFunction::FmuFunction(), and casadi::FmuFunction::identify_io().
Member Data Documentation
cbegin
size_t casadi::OutputStruct::cbegin
Definition at line 121 of file fmu_function.hpp.
cend
size_t casadi::OutputStruct::cend
Definition at line 121 of file fmu_function.hpp.
ind
size_t casadi::OutputStruct::ind
Definition at line 117 of file fmu_function.hpp.
Referenced by casadi::FmuFunction::get_sparsity_out(), casadi::FmuFunction::init(), and parse().
rbegin
size_t casadi::OutputStruct::rbegin
Definition at line 121 of file fmu_function.hpp.
Referenced by casadi::FmuFunction::init().
rend
size_t casadi::OutputStruct::rend
Definition at line 121 of file fmu_function.hpp.
Referenced by casadi::FmuFunction::init().
type
OutputType casadi::OutputStruct::type
Definition at line 115 of file fmu_function.hpp.
Referenced by casadi::FmuFunction::init(), and parse().
wrt
size_t casadi::OutputStruct::wrt
Definition at line 119 of file fmu_function.hpp.
Referenced by casadi::FmuFunction::get_sparsity_out(), and parse().
The documentation for this struct was generated from the following files:
fmu_function.hpp
fmu_function.cpp