CasADi: casadi::CsparseInterface Class Reference
casadi::CsparseInterface Class Reference
'csparse' plugin for LinsolInternal
#include <csparse_interface.hpp>
Detailed Description
Definition at line 67 of file csparse_interface.hpp.
Public Types
typedef LinsolInternal *(* Creator) (const std::string &name, const Sparsity &sp)
typedef int(* RegFcn) (Plugin *plugin)
Public Member Functions
CsparseInterface (const std::string &name, const Sparsity &sp)
~CsparseInterface () override
void init (const Dict &opts) override
Initialize.
void * alloc_mem () const override
Create memory block.
int init_mem (void *mem) const override
Initalize memory block.
void free_mem (void *mem) const override
Free memory block.
int sfact (void *mem, const double *A) const override
int nfact (void *mem, const double *A) const override
Numeric factorization.
int solve (void *mem, const double *A, double *x, casadi_int nrhs, bool tr) const override
const char * plugin_name () const override
std::string class_name () const override
Readable name of the internal class.
void disp (std::ostream &stream, bool more) const override
Display object.
virtual void disp_more (std::ostream &stream) const
Print more.
virtual void linsol_eval_sx (const SXElem **arg, SXElem **res, casadi_int *iw, SXElem *w, void *mem, bool tr, casadi_int nrhs) const
Evaluate SX, possibly transposed.
virtual casadi_int neig (void *mem, const double *A) const
Number of negative eigenvalues.
virtual casadi_int rank (void *mem, const double *A) const
Matrix rank.
virtual void generate (CodeGenerator &g, const std::string &A, const std::string &x, casadi_int nrhs, bool tr) const
Generate C code.
casadi_int nrow () const
Get sparsity pattern.
casadi_int ncol () const
const casadi_int * colind () const
const casadi_int * row () const
casadi_int nnz () const
void serialize_type (SerializingStream &s) const override
Serialize type information.
void serialize_body (SerializingStream &s) const override
Serialize an object without type information.
void construct (const Dict &opts)
Construct.
virtual Dict generate_options (const std::string &target) const
Reconstruct options dict.
void print_options (std::ostream &stream) const
Print list of options.
void print_option (const std::string &name, std::ostream &stream) const
Print all information there is to know about a certain option.
bool has_option (const std::string &option_name) const
Does a particular option exist.
virtual void change_option (const std::string &option_name, const GenericType &option_value)
Change option after object creation for debugging.
virtual void finalize ()
Finalize the object creation.
int checkout () const
Checkout a memory object.
void release (int mem) const
Release a memory object.
void * memory (int ind) const
Memory objects.
virtual Dict get_stats (void *mem) const
Get all statistics.
void clear_mem ()
Clear all memory (called from destructor)
void print (const char *fmt,...) const
C-style formatted printing during evaluation.
void sprint (char *buf, size_t buf_sz, const char *fmt,...) const
C-style formatted printing to string.
void format_time (char *buffer, double time) const
Format time in a fixed width 8 format.
void print_time (const std::map< std::string, FStats > &fstats) const
Print timing statistics.
void serialize (SerializingStream &s) const
Serialize an object.
virtual std::string serialize_base_function () const
String used to identify the immediate FunctionInternal subclass.
casadi_int getCount () const
Get the reference count.
WeakRef * weak ()
Get a weak reference to the object.
Static Public Member Functions
static LinsolInternal * creator (const std::string &name, const Sparsity &sp)
Create a new LinsolInternal.
static ProtoFunction * deserialize (DeserializingStream &s)
Deserialize with type disambiguation.
static bool has_plugin (const std::string &pname, bool verbose=false)
Check if a plugin is available or can be loaded.
static const Options & plugin_options (const std::string &pname)
Get the plugin options.
static Deserialize plugin_deserialize (const std::string &pname)
Get the plugin deserialize_map.
static Plugin pluginFromRegFcn (RegFcn regfcn)
Instantiate a Plugin struct from a factory function.
static Plugin load_plugin (const std::string &pname, bool register_plugin=true)
Load a plugin dynamically.
static handle_t load_library (const std::string &libname, std::string &resultpath, bool global)
Load a library dynamically.
static void registerPlugin (const Plugin &plugin)
Register an integrator in the factory.
static void registerPlugin (RegFcn regfcn)
Register an integrator in the factory.
static Plugin & getPlugin (const std::string &pname)
Load and get the creator function.
static LinsolInternal * instantiate (const std::string &fname, const std::string &pname, Problem problem)
Public Attributes
Sparsity sp_
std::string name_
Name.
bool verbose_
Verbose printout.
bool print_time_
bool record_time_
bool regularity_check_
Errors are thrown when NaN is produced.
bool error_on_fail_
Throw an exception on failure?
Static Public Attributes
static const std::string meta_doc
A documentation string.
static std::map< std::string, Plugin > solvers_
Collection of solvers.
static const std::string infix_ = "linsol"
Infix.
Protected Member Functions
CsparseInterface (DeserializingStream &s)
Deserializing constructor.
void initSingleton ()
void destroySingleton ()
template<class B >
B shared_from_this ()
Get a shared object from the current internal object.
template<class B >
const B shared_from_this () const
Get a shared object from the current internal object.
static const Options options_
Options.
virtual const Options & get_options () const
Options.
Member Typedef Documentation
Creator
typedef LinsolInternal*(* casadi::LinsolInternal::Creator) (const std::string &name, const Sparsity &sp) inherited
Definition at line 121 of file linsol_internal.hpp.
RegFcn
typedef int(* casadi::PluginInterface< LinsolInternal >::RegFcn) (Plugin *plugin) inherited
Definition at line 72 of file plugin_interface.hpp.
Constructor & Destructor Documentation
CsparseInterface() [1/2]
casadi::CsparseInterface::CsparseInterface (const std::string & name, const Sparsity & sp)
Definition at line 48 of file csparse_interface.cpp.
     : LinsolInternal(name, sp) {
   }
~CsparseInterface()
casadi::CsparseInterface::~CsparseInterface () override
Definition at line 52 of file csparse_interface.cpp.
{
     clear_mem();
   }
References casadi::ProtoFunction::clear_mem().
CsparseInterface() [2/2]
casadi::CsparseInterface::CsparseInterface (DeserializingStream & s) inline explicit protected
Definition at line 116 of file csparse_interface.hpp.
 : LinsolInternal(s) {}
Member Function Documentation
alloc_mem()
void* casadi::CsparseInterface::alloc_mem () const inline override virtual
Reimplemented from casadi::LinsolInternal.
Definition at line 85 of file csparse_interface.hpp.
 { return new CsparseMemory();}
change_option()
void casadi::ProtoFunction::change_option (const std::string & option_name, const GenericType & option_value) virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_jk
Reimplemented in casadi::MXFunction, casadi::FunctionInternal, and casadi::FmuFunction.
Definition at line 919 of file function_internal.cpp.
{
     if (option_name == "verbose") {
       verbose_ = option_value;
     } else if (option_name == "regularity_check") {
       regularity_check_ = option_value;
     } else {
       // Failure
       casadi_error("Option '" + option_name + "' cannot be changed");
     }
   }
References casadi::ProtoFunction::regularity_check_, and casadi::ProtoFunction::verbose_.
Referenced by casadi::FunctionInternal::change_option().
checkout()
int casadi::ProtoFunction::checkout () const inherited
Definition at line 3540 of file function_internal.cpp.
{
 #ifdef CASADI_WITH_THREAD
     std::lock_guard<std::mutex> lock(mtx_);
 #endif //CASADI_WITH_THREAD
     if (unused_.empty()) {
       // Allocate a new memory object
       void* m = alloc_mem();
       mem_.push_back(m);
       if (init_mem(m)) {
         casadi_error("Failed to create or initialize memory object");
       }
       return static_cast<int>(mem_.size()) - 1;
     } else {
       // Use an unused memory object
       int m = unused_.top();
       unused_.pop();
       return m;
     }
   }
References casadi::ProtoFunction::alloc_mem(), and casadi::ProtoFunction::init_mem().
Referenced by casadi::ProtoFunction::finalize(), casadi::FunctionBuffer::FunctionBuffer(), and casadi::Sqpmethod::init_mem().
class_name()
std::string casadi::CsparseInterface::class_name () const inline override virtual
Implements casadi::SharedObjectInternal.
Definition at line 109 of file csparse_interface.hpp.
 { return "CsparseInterface";}
clear_mem()
void casadi::ProtoFunction::clear_mem () inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_jq
Definition at line 3432 of file function_internal.cpp.
{
     for (auto&& i : mem_) {
       if (i!=nullptr) free_mem(i);
     }
     mem_.clear();
   }
References casadi::ProtoFunction::free_mem().
Referenced by casadi::AlpaqaInterface::~AlpaqaInterface(), casadi::AmplInterface::~AmplInterface(), casadi::Blocksqp::~Blocksqp(), casadi::BonminInterface::~BonminInterface(), casadi::BSplineInterpolant::~BSplineInterpolant(), casadi::CallbackInternal::~CallbackInternal(), casadi::CbcInterface::~CbcInterface(), casadi::ClpInterface::~ClpInterface(), casadi::CplexInterface::~CplexInterface(), ~CsparseInterface(), casadi::CvodesInterface::~CvodesInterface(), casadi::DaqpInterface::~DaqpInterface(), casadi::External::~External(), casadi::FastNewton::~FastNewton(), casadi::FatropConicInterface::~FatropConicInterface(), casadi::FatropInterface::~FatropInterface(), casadi::Feasiblesqpmethod::~Feasiblesqpmethod(), casadi::FiniteDiff::~FiniteDiff(), casadi::FixedStepIntegrator::~FixedStepIntegrator(), casadi::FmuFunction::~FmuFunction(), casadi::GurobiInterface::~GurobiInterface(), casadi::HighsInterface::~HighsInterface(), casadi::HpipmInterface::~HpipmInterface(), casadi::HpmpcInterface::~HpmpcInterface(), casadi::IdasInterface::~IdasInterface(), casadi::ImplicitToNlp::~ImplicitToNlp(), casadi::IpoptInterface::~IpoptInterface(), casadi::Ipqp::~Ipqp(), casadi::JitFunction::~JitFunction(), casadi::KinsolInterface::~KinsolInterface(), casadi::KnitroInterface::~KnitroInterface(), casadi::LapackLu::~LapackLu(), casadi::LapackQr::~LapackQr(), casadi::LinearInterpolant::~LinearInterpolant(), casadi::LinearInterpolantJac::~LinearInterpolantJac(), casadi::LinsolLdl::~LinsolLdl(), casadi::LinsolQr::~LinsolQr(), casadi::LinsolTridiag::~LinsolTridiag(), casadi::Lsqr::~Lsqr(), casadi::Ma27Interface::~Ma27Interface(), casadi::MadnlpInterface::~MadnlpInterface(), casadi::Map::~Map(), casadi::MapSum::~MapSum(), casadi::MumpsInterface::~MumpsInterface(), casadi::MXFunction::~MXFunction(), casadi::Newton::~Newton(), casadi::Nlpsol::~Nlpsol(), casadi::OmpMap::~OmpMap(), casadi::OoqpInterface::~OoqpInterface(), casadi::OsqpInterface::~OsqpInterface(), casadi::ProxqpInterface::~ProxqpInterface(), casadi::QpoasesInterface::~QpoasesInterface(), casadi::QpToNlp::~QpToNlp(), casadi::Qrqp::~Qrqp(), casadi::Qrsqp::~Qrsqp(), casadi::Scpgen::~Scpgen(), casadi::SLEQPInterface::~SLEQPInterface(), casadi::SlicotDple::~SlicotDple(), casadi::SlicotExpm::~SlicotExpm(), casadi::SnoptInterface::~SnoptInterface(), casadi::Sqpmethod::~Sqpmethod(), casadi::SuperscsInterface::~SuperscsInterface(), casadi::Switch::~Switch(), casadi::SymbolicQr::~SymbolicQr(), casadi::ThreadMap::~ThreadMap(), and casadi::WorhpInterface::~WorhpInterface().
colind()
const casadi_int* casadi::LinsolInternal::colind () const inline inherited
Definition at line 138 of file linsol_internal.hpp.
 { return sp_.colind();}
Referenced by init_mem(), casadi::MumpsInterface::init_mem(), casadi::Ma27Interface::nfact(), and casadi::MumpsInterface::nfact().
construct()
void casadi::ProtoFunction::construct (const Dict & opts) inherited
Prepares the function for evaluation
Extra doc: https://github.com/casadi/casadi/wiki/L_jf
Definition at line 132 of file function_internal.cpp.
{
     // Sanitize dictionary is needed
     if (!Options::is_sane(opts)) {
       // Call recursively
       return construct(Options::sanitize(opts));
     }
     // Make sure all options exist
     get_options().check(opts);
     // Initialize the class hierarchy
     try {
       init(opts);
     } catch(std::exception& e) {
       casadi_error("Error calling " + class_name() + "::init for '" + name_ + "':\n"
         + std::string(e.what()));
     }
     // Revisit class hierarchy in reverse order
     try {
       finalize();
     } catch(std::exception& e) {
       casadi_error("Error calling " + class_name() + "::finalize for '" + name_ + "':\n"
         + std::string(e.what()));
     }
   }
References casadi::Options::check(), casadi::SharedObjectInternal::class_name(), casadi::ProtoFunction::finalize(), casadi::ProtoFunction::get_options(), casadi::ProtoFunction::init(), casadi::Options::is_sane(), casadi::ProtoFunction::name_, and casadi::Options::sanitize().
Referenced by casadi::Function::create(), casadi::FmuFunction::factory(), casadi::FmuFunction::get_forward(), casadi::FmuFunction::get_jacobian(), casadi::LinearInterpolant::get_jacobian(), and casadi::FmuFunction::get_reverse().
creator()
static LinsolInternal* casadi::CsparseInterface::creator (const std::string & name, const Sparsity & sp) inline static
Definition at line 74 of file csparse_interface.hpp.
{
       return new CsparseInterface(name, sp);
     }
Referenced by casadi::casadi_register_linsol_csparse().
deserialize()
static ProtoFunction* casadi::CsparseInterface::deserialize (DeserializingStream & s) inline static
Definition at line 112 of file csparse_interface.hpp.
 { return new CsparseInterface(s); }
Referenced by casadi::casadi_register_linsol_csparse().
destroySingleton()
void casadi::SharedObjectInternal::destroySingleton () inline protected inherited
Called in the destructor of singletons
Definition at line 79 of file shared_object_internal.hpp.
{
       count--;
     }
disp()
void casadi::LinsolInternal::disp (std::ostream & stream, bool more) const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_e4
Implements casadi::SharedObjectInternal.
Definition at line 43 of file linsol_internal.cpp.
{
     stream << "Linear solver " << class_name();
     if (more) {
       stream << std::endl;
       disp_more(stream);
     }
   }
References casadi::SharedObjectInternal::class_name(), and casadi::LinsolInternal::disp_more().
disp_more()
virtual void casadi::LinsolInternal::disp_more (std::ostream & stream) const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_e5
Definition at line 65 of file linsol_internal.hpp.
 {}
Referenced by casadi::LinsolInternal::disp().
finalize()
void casadi::ProtoFunction::finalize () virtual inherited
This function, which visits the class hierarchy in reverse order is run after init() has been completed.
Extra doc: https://github.com/casadi/casadi/wiki/L_jm
Reimplemented in casadi::LinsolQr, casadi::OracleFunction, casadi::FunctionInternal, and casadi::CallbackInternal.
Definition at line 720 of file function_internal.cpp.
{
     // Create memory object
     int mem = checkout();
     casadi_assert_dev(mem==0);
   }
References casadi::ProtoFunction::checkout().
Referenced by casadi::ProtoFunction::construct(), casadi::Linsol::deserialize(), casadi::FunctionInternal::finalize(), and casadi::LinsolQr::finalize().
format_time()
void casadi::ProtoFunction::format_time (char * buffer, double time) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_jt
Definition at line 3722 of file function_internal.cpp.
{
     // Always of width 8
     casadi_assert_dev(time>=0);
     double log_time = log10(time);
     int magn = static_cast<int>(floor(log_time));
     int iprefix = static_cast<int>(floor(log_time/3));
     if (iprefix<-4) {
       sprint(buffer, 10, "       0");
       return;
     }
     if (iprefix>=5) {
       sprint(buffer, 10, "     inf");
       return;
     }
     char prefixes[] = "TGMk munp";
     char prefix = prefixes[4-iprefix];
     int rem = magn-3*iprefix;
     double time_normalized = time/pow(10, 3*iprefix);
     if (rem==0) {
       sprint(buffer, 10, "  %1.2f%cs", time_normalized, prefix);
     } else if (rem==1) {
       sprint(buffer, 10, " %2.2f%cs", time_normalized, prefix);
     } else {
       sprint(buffer, 10, "%3.2f%cs", time_normalized, prefix);
     }
   }
References casadi::ProtoFunction::sprint().
Referenced by casadi::ProtoFunction::print_time().
free_mem()
void casadi::CsparseInterface::free_mem (void * mem) const inline override virtual
Reimplemented from casadi::LinsolInternal.
Definition at line 91 of file csparse_interface.hpp.
 { delete static_cast<CsparseMemory*>(mem);}
generate()
void casadi::LinsolInternal::generate (CodeGenerator & g, const std::string & A, const std::string & x, casadi_int nrhs, bool tr) const virtual inherited
Reimplemented in casadi::Lsqr, casadi::LinsolTridiag, casadi::LinsolQr, and casadi::LinsolLdl.
Definition at line 110 of file linsol_internal.cpp.
{
     g << "#error " <<  class_name() << " does not support code generation\n";
   }
References casadi::SharedObjectInternal::class_name().
generate_options()
Dict casadi::ProtoFunction::generate_options (const std::string & target) const virtual inherited
Reimplemented in casadi::SXFunction, casadi::MXFunction, and casadi::FunctionInternal.
Definition at line 367 of file function_internal.cpp.
{
     Dict opts;
     opts["verbose"] = verbose_;
     opts["print_time"] = print_time_;
     opts["record_time"] = record_time_;
     opts["regularity_check"] = regularity_check_;
     opts["error_on_fail"] = error_on_fail_;
     return opts;
   }
References casadi::ProtoFunction::error_on_fail_, casadi::ProtoFunction::print_time_, casadi::ProtoFunction::record_time_, casadi::ProtoFunction::regularity_check_, and casadi::ProtoFunction::verbose_.
Referenced by casadi::FunctionInternal::generate_options().
get_options()
virtual const Options& casadi::ProtoFunction::get_options () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_jg
Reimplemented in casadi::SymbolicQr, casadi::Sqpmethod, casadi::Scpgen, casadi::Qrsqp, casadi::Qrqp, casadi::QpToNlp, casadi::Newton, casadi::LinsolQr, casadi::LinsolLdl, casadi::LinearInterpolant, casadi::Ipqp, casadi::ImplicitToNlp, casadi::Feasiblesqpmethod, casadi::FastNewton, casadi::Collocation, casadi::BSplineInterpolant, casadi::WorhpInterface, casadi::SuperscsInterface, casadi::SundialsInterface, casadi::KinsolInterface, casadi::IdasInterface, casadi::CvodesInterface, casadi::SnoptInterface, casadi::SlicotDple, casadi::SLEQPInterface, casadi::QpoasesInterface, casadi::ProxqpInterface, casadi::OsqpInterface, casadi::OoqpInterface, casadi::MumpsInterface, casadi::MadnlpInterface, casadi::LapackQr, casadi::LapackLu, casadi::KnitroInterface, casadi::IpoptInterface, casadi::HpmpcInterface, casadi::HpipmInterface, casadi::HighsInterface, casadi::GurobiInterface, casadi::FatropInterface, casadi::FatropConicInterface, casadi::DaqpInterface, casadi::CplexInterface, casadi::ClpInterface, casadi::CbcInterface, casadi::BonminInterface, casadi::Blocksqp, casadi::AmplInterface, casadi::AlpaqaInterface, casadi::SXFunction, casadi::Rootfinder, casadi::OracleFunction, casadi::Nlpsol, casadi::MXFunction, casadi::JitFunction, casadi::Interpolant, casadi::ImplicitFixedStepIntegrator, casadi::FixedStepIntegrator, casadi::Integrator, casadi::FunctionInternal, casadi::FmuFunction, casadi::FiniteDiff, casadi::Expm, casadi::Dple, and casadi::Conic.
Definition at line 116 of file function_internal.hpp.
 { return options_;}
Referenced by casadi::ProtoFunction::construct(), casadi::ProtoFunction::has_option(), casadi::ProtoFunction::print_option(), and casadi::ProtoFunction::print_options().
get_stats()
Dict casadi::ProtoFunction::get_stats (void * mem) const virtual inherited
Reimplemented in casadi::Sqpmethod, casadi::Scpgen, casadi::Qrsqp, casadi::Qrqp, casadi::QpToNlp, casadi::Newton, casadi::Ipqp, casadi::ImplicitToNlp, casadi::Feasiblesqpmethod, casadi::FastNewton, casadi::WorhpInterface, casadi::SuperscsInterface, casadi::SundialsInterface, casadi::SnoptInterface, casadi::SLEQPInterface, casadi::QpoasesInterface, casadi::ProxqpInterface, casadi::OsqpInterface, casadi::OoqpInterface, casadi::MadnlpInterface, casadi::KnitroInterface, casadi::IpoptInterface, casadi::HpmpcInterface, casadi::HpipmInterface, casadi::HighsInterface, casadi::GurobiInterface, casadi::FatropInterface, casadi::FatropConicInterface, casadi::DaqpInterface, casadi::CplexInterface, casadi::ClpInterface, casadi::CbcInterface, casadi::BonminInterface, casadi::AlpaqaInterface, casadi::Rootfinder, casadi::OracleFunction, casadi::Nlpsol, casadi::MXFunction, casadi::FmuFunction, and casadi::Conic.
Definition at line 2859 of file function_internal.cpp.
{
     auto m = static_cast<ProtoFunctionMemory*>(mem);
     // Add timing statistics
     Dict stats;
     for (const auto& s : m->fstats) {
       stats["n_call_" +s.first] = s.second.n_call;
       stats["t_wall_" +s.first] = s.second.t_wall;
       stats["t_proc_" +s.first] = s.second.t_proc;
     }
     return stats;
   }
Referenced by casadi::Conic::get_stats(), casadi::FmuFunction::get_stats(), casadi::MXFunction::get_stats(), casadi::OracleFunction::get_stats(), and casadi::QpToNlp::get_stats().
getCount()
casadi_int casadi::SharedObjectInternal::getCount () const inherited
Definition at line 58 of file shared_object_internal.cpp.
{
     return count;
   }
getPlugin()
PluginInterface< LinsolInternal >::Plugin & casadi::PluginInterface< LinsolInternal >::getPlugin (const std::string & pname) static inherited
Definition at line 100 of file plugin_interface.hpp.
{
     // Check if the solver has been loaded
     auto it=Derived::solvers_.find(pname);
     // Load the solver if needed
     if (it==Derived::solvers_.end()) {
       load_plugin(pname);
       it=Derived::solvers_.find(pname);
     }
     casadi_assert_dev(it!=Derived::solvers_.end());
     return it->second;
   }
has_option()
bool casadi::ProtoFunction::has_option (const std::string & option_name) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_jj
Definition at line 915 of file function_internal.cpp.
{
     return get_options().find(option_name) != 0;
   }
References casadi::Options::find(), and casadi::ProtoFunction::get_options().
has_plugin()
bool casadi::PluginInterface< LinsolInternal >::has_plugin (const std::string & pname, bool verbose = false) static inherited
Definition at line 75 of file plugin_interface.hpp.
{
     // Quick return if available
     if (Derived::solvers_.find(pname) != Derived::solvers_.end()) {
       return true;
     }
     // Try loading the plugin
     try {
       (void)load_plugin(pname, false);
       return true;
     } catch (CasadiException& ex) {
       if (verbose) {
         casadi_warning(ex.what());
       }
       return false;
     }
   }
init()
void casadi::CsparseInterface::init (const Dict & opts) override virtual
Reimplemented from casadi::LinsolInternal.
Definition at line 61 of file csparse_interface.cpp.
{
     // Call the init method of the base class
     LinsolInternal::init(opts);
   }
References casadi::LinsolInternal::init().
init_mem()
int casadi::CsparseInterface::init_mem (void * mem) const override virtual
Reimplemented from casadi::LinsolInternal.
Definition at line 66 of file csparse_interface.cpp.
{
     if (LinsolInternal::init_mem(mem)) return 1;
     auto m = static_cast<CsparseMemory*>(mem);
     m->N = nullptr;
     m->S = nullptr;
     m->A.nzmax = this->nnz();  // maximum number of entries
     m->A.m = this->nrow(); // number of rows
     m->A.n = this->ncol(); // number of columns
     m->colind.resize(this->ncol()+1);
     m->row.resize(this->nnz());
     copy_vector(this->colind(), m->colind);
     copy_vector(this->row(), m->row);
     m->A.p = get_ptr(m->colind); // row pointers (size n+1)
     m->A.i = get_ptr(m->row); // row pointers (size n+1)
     m->A.x = nullptr; // numerical values, size nzmax
     m->A.nz = -1; // of entries in triplet matrix, -1 for compressed-column
     // Temporary
     m->temp_.resize(m->A.n);
     return 0;
   }
References casadi::LinsolInternal::colind(), casadi::copy_vector(), casadi::get_ptr(), casadi::LinsolInternal::init_mem(), casadi::CsparseMemory::N, casadi::LinsolInternal::ncol(), casadi::LinsolInternal::nnz(), casadi::LinsolInternal::nrow(), and casadi::LinsolInternal::row().
initSingleton()
void casadi::SharedObjectInternal::initSingleton () inline protected inherited
Called in the constructor of singletons to avoid that the counter reaches zero
Definition at line 73 of file shared_object_internal.hpp.
{
       casadi_assert_dev(count==0);
       count++;
     }
instantiate()
LinsolInternal * casadi::PluginInterface< LinsolInternal >::instantiate (const std::string & fname, const std::string & pname, Problem problem) static inherited
Definition at line 104 of file plugin_interface.hpp.
{
     // Assert the plugin exists (needed for adaptors)
     if (!has_plugin(pname, true)) {
       casadi_error("Plugin '" + pname + "' is not found.");
     }
     return getPlugin(pname).creator(fname, problem);
   }
linsol_eval_sx()
void casadi::LinsolInternal::linsol_eval_sx (const SXElem ** arg, SXElem ** res, casadi_int * iw, SXElem * w, void * mem, bool tr, casadi_int nrhs) const virtual inherited
Reimplemented in casadi::SymbolicQr.
Definition at line 63 of file linsol_internal.cpp.
{
     casadi_error("eval_sx not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
load_library()
handle_t casadi::PluginInterface< LinsolInternal >::load_library (const std::string & libname, std::string & resultpath, bool global) static inherited
Definition at line 90 of file plugin_interface.hpp.
{
 #ifndef WITH_DL
     casadi_error("WITH_DL option needed for dynamic loading");
 #else // WITH_DL
     // Get the name of the shared library
     std::string lib = SHARED_LIBRARY_PREFIX + libname + SHARED_LIBRARY_SUFFIX;
     // Build up search paths;
     std::vector<std::string> search_paths = get_search_paths();
     return open_shared_library(lib, search_paths, resultpath,
       "PluginInterface::load_plugin", global);
 #endif // WITH_DL
   }
load_plugin()
PluginInterface< LinsolInternal >::Plugin casadi::PluginInterface< LinsolInternal >::load_plugin (const std::string & pname, bool register_plugin = true) static inherited
Definition at line 87 of file plugin_interface.hpp.
{
     // Issue warning and quick return if already loaded
     if (Derived::solvers_.find(pname) != Derived::solvers_.end()) {
       casadi_warning("PluginInterface: Solver " + pname + " is already in use. Ignored.");
       return Plugin();
     }
 #ifndef WITH_DL
     casadi_error("WITH_DL option needed for dynamic loading");
 #else // WITH_DL
     // Retrieve the registration function
     RegFcn reg;
     // Load the dll
     std::string regName = "casadi_register_" + Derived::infix_ + "_" + pname;
     std::string searchpath;
     handle_t handle = load_library("casadi_" + Derived::infix_ + "_" + pname, searchpath,
       false);
 #ifdef _WIN32
 #if __GNUC__
 #pragma GCC diagnostic push
 #pragma GCC diagnostic ignored "-Wcast-function-type"
 #endif
     reg = reinterpret_cast<RegFcn>(GetProcAddress(handle, TEXT(regName.c_str())));
 #if __GNUC__
 #pragma GCC diagnostic pop
 #endif
 #else // _WIN32
     // Reset error
     dlerror();
     // Load creator
     reg = reinterpret_cast<RegFcn>(dlsym(handle, regName.c_str()));
 #endif // _WIN32
     casadi_assert(reg!=nullptr,
       "PluginInterface::load_plugin: no \"" + regName + "\" found in " + searchpath + ".");
     // Create a temporary struct
     Plugin plugin = pluginFromRegFcn(reg);
     // Register the plugin
     if (register_plugin) {
       registerPlugin(plugin);
     }
     return plugin;
 #endif // WITH_DL
   }
memory()
void * casadi::ProtoFunction::memory (int ind) const inherited
Definition at line 3533 of file function_internal.cpp.
{
 #ifdef CASADI_WITH_THREAD
     std::lock_guard<std::mutex> lock(mtx_);
 #endif //CASADI_WITH_THREAD
     return mem_.at(ind);
   }
Referenced by casadi::FunctionInternal::call_gen(), casadi::FunctionInternal::get_jac_sparsity_gen(), casadi::FunctionInternal::get_jac_sparsity_hierarchical(), casadi::Sqpmethod::solve_ela_QP(), and casadi::Sqpmethod::solve_QP().
ncol()
casadi_int casadi::LinsolInternal::ncol () const inline inherited
Definition at line 137 of file linsol_internal.hpp.
 { return sp_.size2();}
Referenced by casadi::LinsolQr::finalize(), casadi::LinsolQr::generate(), casadi::Lsqr::generate(), init_mem(), casadi::Ma27Interface::init_mem(), casadi::LapackLu::init_mem(), casadi::LapackQr::init_mem(), casadi::LinsolQr::init_mem(), casadi::Lsqr::init_mem(), casadi::Ma27Interface::nfact(), casadi::LapackLu::nfact(), casadi::LapackQr::nfact(), casadi::LinsolQr::nfact(), solve(), casadi::Ma27Interface::solve(), casadi::LapackLu::solve(), casadi::LinsolTridiag::solve(), and casadi::LapackQr::solve_batch().
neig()
casadi_int casadi::LinsolInternal::neig (void * mem, const double * A) const virtual inherited
Reimplemented in casadi::LinsolLdl, and casadi::Ma27Interface.
Definition at line 102 of file linsol_internal.cpp.
{
     casadi_error("'neig' not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
nfact()
int casadi::CsparseInterface::nfact (void * mem, const double * A) const override virtual
Reimplemented from casadi::LinsolInternal.
Definition at line 102 of file csparse_interface.cpp.
{
     auto m = static_cast<CsparseMemory*>(mem);
     // Set the nonzeros of the matrix
     m->A.x = const_cast<double*>(A);
     // Make sure that all entries of the linear system are valid
     for (casadi_int k=0; k<this->nnz(); ++k) {
       casadi_assert(!isnan(A[k]),
         "Nonzero " + str(k) + " is not-a-number");
       casadi_assert(!isinf(A[k]),
         "Nonzero " + str(k) + " is infinite");
     }
     if (verbose_) {
       uout() << "CsparseInterface::prepare: numeric factorization" << std::endl;
       uout() << "linear system to be factorized = " << std::endl;
       DM(sp_, std::vector<double>(A, A+nnz())).print_sparse(uout());
     }
     double tol = 1e-8;
     if (m->N) cs_nfree(m->N);
     m->N = cs_lu(&m->A, m->S, tol) ;                 // numeric LU factorization
     if (m->N==nullptr) {
       DM temp(sp_, std::vector<double>(A, A+nnz()));
       temp = sparsify(temp);
       if (temp.sparsity().is_singular()) {
         std::stringstream ss;
         ss << "CsparseInterface::prepare: factorization failed due to matrix"
           " being singular. Matrix contains numerical zeros which are "
             "structurally non-zero. Promoting these zeros to be structural "
             "zeros, the matrix was found to be structurally rank deficient."
             " sprank: " << sprank(temp.sparsity()) << " <-> " << temp.size2() << std::endl;
         if (verbose_) {
           ss << "Sparsity of the linear system: " << std::endl;
           sp_.disp(ss, true); // print detailed
         }
         throw CasadiException(ss.str());
       } else {
         std::stringstream ss;
         ss << "CsparseInterface::prepare: factorization failed, check if Jacobian is singular"
            << std::endl;
         if (verbose_) {
           ss << "Sparsity of the linear system: " << std::endl;
           sp_.disp(ss, true); // print detailed
         }
         throw CasadiException(ss.str());
       }
     }
     casadi_assert_dev(m->N!=nullptr);
     return 0;
   }
References casadi::CsparseMemory::A, casadi::SharedObject::disp(), casadi::Sparsity::is_singular(), casadi::LinsolInternal::nnz(), casadi::Matrix< Scalar >::print_sparse(), casadi::GenericMatrix< MatType >::size2(), casadi::LinsolInternal::sp_, casadi::Matrix< Scalar >::sparsity(), casadi::str(), casadi::uout(), and casadi::ProtoFunction::verbose_.
nnz()
casadi_int casadi::LinsolInternal::nnz () const inline inherited
Definition at line 140 of file linsol_internal.hpp.
 { return sp_.nnz();}
Referenced by init_mem(), casadi::Ma27Interface::init_mem(), casadi::MumpsInterface::init_mem(), casadi::SymbolicQr::linsol_eval_sx(), nfact(), casadi::Ma27Interface::nfact(), and casadi::MumpsInterface::nfact().
nrow()
casadi_int casadi::LinsolInternal::nrow () const inline inherited
Definition at line 136 of file linsol_internal.hpp.
 { return sp_.size1();}
Referenced by casadi::LinsolLdl::generate(), casadi::LinsolQr::generate(), casadi::Lsqr::generate(), init_mem(), casadi::LapackLu::init_mem(), casadi::MumpsInterface::init_mem(), casadi::LinsolLdl::init_mem(), casadi::LinsolQr::init_mem(), casadi::LinsolTridiag::init_mem(), casadi::Lsqr::init_mem(), casadi::LinsolLdl::neig(), casadi::LapackLu::nfact(), casadi::MumpsInterface::nfact(), casadi::LinsolLdl::rank(), casadi::LapackLu::solve(), casadi::LapackQr::solve(), casadi::LinsolTridiag::solve(), and casadi::SymbolicQr::solve().
plugin_deserialize()
Deserialize casadi::PluginInterface< LinsolInternal >::plugin_deserialize (const std::string & pname) static inherited
Definition at line 81 of file plugin_interface.hpp.
{
     Deserialize m = getPlugin(pname).deserialize;
     casadi_assert(m, "Plugin \"" + pname + "\" does not support deserialize");
     return m;
   }
plugin_name()
const char* casadi::CsparseInterface::plugin_name () const inline override virtual
Implements casadi::LinsolInternal.
Definition at line 106 of file csparse_interface.hpp.
 { return "csparse";}
plugin_options()
const Options & casadi::PluginInterface< LinsolInternal >::plugin_options (const std::string & pname) static inherited
Definition at line 78 of file plugin_interface.hpp.
{
     const Options *op = getPlugin(pname).options;
     casadi_assert(op!=nullptr, "Plugin \"" + pname + "\" does not support options");
     return *op;
   }
pluginFromRegFcn()
PluginInterface< LinsolInternal >::Plugin casadi::PluginInterface< LinsolInternal >::pluginFromRegFcn (RegFcn regfcn) static inherited
Definition at line 84 of file plugin_interface.hpp.
{
     // Create a temporary struct
     Plugin plugin;
     // Set the fields
     int flag = regfcn(&plugin);
     casadi_assert(flag==0, "Registration of plugin failed.");
     return plugin;
   }
print()
void casadi::ProtoFunction::print (const char * fmt, ...) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_jr
Definition at line 3763 of file function_internal.cpp.
{
     // Variable number of arguments
     va_list args;
     va_start(args, fmt);
     // Static & dynamic buffers
     char buf[256];
     size_t buf_sz = sizeof(buf);
     char* buf_dyn = nullptr;
     // Try to print with a small buffer
     casadi_int n = vsnprintf(buf, buf_sz, fmt, args);
     // Need a larger buffer?
     if (n>static_cast<casadi_int>(buf_sz)) {
       buf_sz = static_cast<size_t>(n+1);
       buf_dyn = new char[buf_sz];
       n = vsnprintf(buf_dyn, buf_sz, fmt, args);
     }
     // Print buffer content
     if (n>=0) uout() << (buf_dyn ? buf_dyn : buf) << std::flush;
     // Cleanup
     delete[] buf_dyn;
     va_end(args);
     // Throw error if failure
     casadi_assert(n>=0, "Print failure while processing '" + std::string(fmt) + "'");
   }
References casadi::uout().
Referenced by casadi::Feasiblesqpmethod::anderson_acc_step_update(), casadi::Nlpsol::callback(), casadi::Blocksqp::convertHessian(), casadi::FmuFunction::eval_task(), casadi::Feasiblesqpmethod::feasibility_iterations(), casadi::Blocksqp::feasibilityRestorationPhase(), casadi::Blocksqp::fullstep(), casadi::Blocksqp::init(), casadi::Feasiblesqpmethod::init(), casadi::Ipqp::init(), casadi::Qrqp::init(), casadi::Qrsqp::init(), casadi::Sqpmethod::init(), casadi::LinsolQr::nfact(), casadi::Feasiblesqpmethod::print_iteration(), casadi::Qrsqp::print_iteration(), casadi::Sqpmethod::print_iteration(), casadi::SundialsInterface::print_stats(), casadi::ProtoFunction::print_time(), casadi::Blocksqp::printInfo(), casadi::Blocksqp::printProgress(), casadi::Blocksqp::run(), casadi::Blocksqp::solve(), casadi::Feasiblesqpmethod::solve(), casadi::Qrsqp::solve(), casadi::Sqpmethod::solve(), casadi::Sqpmethod::solve_ela_QP(), casadi::Feasiblesqpmethod::solve_LP(), casadi::Feasiblesqpmethod::solve_QP(), casadi::Qrsqp::solve_QP(), casadi::Sqpmethod::solve_QP(), and casadi::Blocksqp::solveQP().
print_option()
void casadi::ProtoFunction::print_option (const std::string & name, std::ostream & stream) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ji
Definition at line 911 of file function_internal.cpp.
{
     get_options().print_one(name, stream);
   }
References casadi::ProtoFunction::get_options(), and casadi::Options::print_one().
print_options()
void casadi::ProtoFunction::print_options (std::ostream & stream) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_jh
Definition at line 907 of file function_internal.cpp.
{
     get_options().print_all(stream);
   }
References casadi::ProtoFunction::get_options(), and casadi::Options::print_all().
print_time()
void casadi::ProtoFunction::print_time (const std::map< std::string, FStats > & fstats) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ju
Definition at line 3683 of file function_internal.cpp.
{
     if (!print_time_) return;
     // Length of the name being printed
     size_t name_len=0;
     for (auto &&s : fstats) {
       name_len = std::max(s.first.size(), name_len);
     }
     name_len = std::max(name_.size(), name_len);
     // Print name with a given length. Format: "%NNs "
     char namefmt[10];
     sprint(namefmt, sizeof(namefmt), "%%%ds ", static_cast<casadi_int>(name_len));
     // Print header
     print(namefmt, name_.c_str());
     print(" : %8s %10s %8s %10s %9s\n", "t_proc", "(avg)", "t_wall", "(avg)", "n_eval");
     char buffer_proc[10];
     char buffer_wall[10];
     char buffer_proc_avg[10];
     char buffer_wall_avg[10];
     // Print keys
     for (const auto &s : fstats) {
       if (s.second.n_call!=0) {
         print(namefmt, s.first.c_str());
         format_time(buffer_proc, s.second.t_proc);
         format_time(buffer_wall, s.second.t_wall);
         format_time(buffer_proc_avg, s.second.t_proc/s.second.n_call);
         format_time(buffer_wall_avg, s.second.t_wall/s.second.n_call);
         print(" | %s (%s) %s (%s) %9d\n",
           buffer_proc, buffer_proc_avg,
           buffer_wall, buffer_wall_avg, s.second.n_call);
       }
     }
   }
References casadi::ProtoFunction::format_time(), casadi::ProtoFunction::name_, casadi::ProtoFunction::print(), casadi::ProtoFunction::print_time_, and casadi::ProtoFunction::sprint().
Referenced by casadi::FunctionInternal::eval_gen().
rank()
casadi_int casadi::LinsolInternal::rank (void * mem, const double * A) const virtual inherited
Reimplemented in casadi::LinsolLdl, and casadi::Ma27Interface.
Definition at line 106 of file linsol_internal.cpp.
{
     casadi_error("'rank' not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
registerPlugin() [1/2]
void casadi::PluginInterface< LinsolInternal >::registerPlugin (const Plugin & plugin) static inherited
Definition at line 94 of file plugin_interface.hpp.
{
     // Check if the solver name is in use
     typename std::map<std::string, Plugin>::iterator it=Derived::solvers_.find(plugin.name);
     casadi_assert(it==Derived::solvers_.end(),
       "Solver " + str(plugin.name) + " is already in use");
     // Add to list of solvers
     Derived::solvers_[plugin.name] = plugin;
   }
registerPlugin() [2/2]
void casadi::PluginInterface< LinsolInternal >::registerPlugin (RegFcn regfcn) static inherited
Definition at line 97 of file plugin_interface.hpp.
{
     registerPlugin(pluginFromRegFcn(regfcn));
   }
release()
void casadi::ProtoFunction::release (int mem) const inherited
Definition at line 3560 of file function_internal.cpp.
{
 #ifdef CASADI_WITH_THREAD
     std::lock_guard<std::mutex> lock(mtx_);
 #endif //CASADI_WITH_THREAD
     unused_.push(mem);
   }
row()
const casadi_int* casadi::LinsolInternal::row () const inline inherited
Definition at line 139 of file linsol_internal.hpp.
 { return sp_.row();}
Referenced by init_mem(), casadi::MumpsInterface::init_mem(), casadi::Ma27Interface::nfact(), and casadi::MumpsInterface::nfact().
serialize()
void casadi::ProtoFunction::serialize (SerializingStream & s) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_jv
Definition at line 4039 of file function_internal.cpp.
{
     serialize_type(s);
     serialize_body(s);
   }
References casadi::ProtoFunction::serialize_body(), and casadi::ProtoFunction::serialize_type().
serialize_base_function()
virtual std::string casadi::ProtoFunction::serialize_base_function () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_jy
Reimplemented in casadi::LinearInterpolantJac, casadi::Rootfinder, casadi::Nlpsol, casadi::MapSum, casadi::Map, casadi::Interpolant, casadi::Integrator, casadi::External, and casadi::Conic.
Definition at line 229 of file function_internal.hpp.
{
       return class_name();
     }
Referenced by casadi::FunctionInternal::serialize_type().
serialize_body()
void casadi::LinsolInternal::serialize_body (SerializingStream & s) const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ea
Reimplemented from casadi::ProtoFunction.
Reimplemented in casadi::SymbolicQr, casadi::LinsolQr, casadi::LinsolLdl, casadi::MumpsInterface, casadi::LapackQr, and casadi::LapackLu.
Definition at line 125 of file linsol_internal.cpp.
{
     ProtoFunction::serialize_body(s);
     s.pack("LinsolInternal::sp", sp_);
   }
References casadi::SerializingStream::pack(), casadi::ProtoFunction::serialize_body(), and casadi::LinsolInternal::sp_.
Referenced by casadi::LapackLu::serialize_body(), casadi::LapackQr::serialize_body(), casadi::MumpsInterface::serialize_body(), casadi::LinsolLdl::serialize_body(), casadi::LinsolQr::serialize_body(), and casadi::SymbolicQr::serialize_body().
serialize_type()
void casadi::LinsolInternal::serialize_type (SerializingStream & s) const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_e9
Reimplemented from casadi::ProtoFunction.
Definition at line 120 of file linsol_internal.cpp.
{
     ProtoFunction::serialize_type(s);
     PluginInterface<LinsolInternal>::serialize_type(s);
   }
References casadi::ProtoFunction::serialize_type(), and casadi::PluginInterface< Derived >::serialize_type().
sfact()
int casadi::CsparseInterface::sfact (void * mem, const double * A) const override virtual
Reimplemented from casadi::LinsolInternal.
Definition at line 89 of file csparse_interface.cpp.
{
     auto m = static_cast<CsparseMemory*>(mem);
     // Set the nonzeros of the matrix
     m->A.x = const_cast<double*>(A);
     // ordering and symbolic analysis
     casadi_int order = 0; // ordering?
     if (m->S) cs_sfree(m->S);
     m->S = cs_sqr(order, &m->A, 0);
     return 0;
   }
References casadi::CsparseMemory::A.
shared_from_this() [1/2]
template<class B > B casadi::SharedObjectInternal::shared_from_this protected inherited
Template function implementations.
Definition at line 136 of file shared_object_internal.hpp.
{
     casadi_assert_dev(B::test_cast(this));
     B ret;
     ret.own(this);
     return ret;
   }
shared_from_this() [2/2]
template<class B > const B casadi::SharedObjectInternal::shared_from_this protected inherited
Definition at line 144 of file shared_object_internal.hpp.
{
     casadi_assert_dev(B::test_cast(this));
     B ret;
     ret.own(const_cast<SharedObjectInternal*>(this));
     return ret;
   }
solve()
int casadi::CsparseInterface::solve (void * mem, const double * A, double * x, casadi_int nrhs, bool tr) const override virtual
Reimplemented from casadi::LinsolInternal.
Definition at line 156 of file csparse_interface.cpp.
{
     auto m = static_cast<CsparseMemory*>(mem);
     casadi_assert_dev(m->N!=nullptr);
     double *t = &m->temp_.front();
     for (casadi_int k=0; k<nrhs; ++k) {
       if (tr) {
         cs_pvec(m->S->q, x, t, m->A.n) ;       // t = P2*b
         casadi_assert_dev(m->N->U!=nullptr);
         cs_utsolve(m->N->U, t) ;              // t = U'\t
         cs_ltsolve(m->N->L, t) ;              // t = L'\t
         cs_pvec(m->N->pinv, t, x, m->A.n) ;    // x = P1*t
       } else {
         cs_ipvec(m->N->pinv, x, t, m->A.n) ;   // t = P1\b
         cs_lsolve(m->N->L, t) ;               // t = L\t
         cs_usolve(m->N->U, t) ;               // t = U\t
         cs_ipvec(m->S->q, t, x, m->A.n) ;      // x = P2\t
       }
       x += ncol();
     }
     return 0;
   }
References casadi::LinsolInternal::ncol().
sprint()
void casadi::ProtoFunction::sprint (char * buf, size_t buf_sz, const char * fmt, ...) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_js
Definition at line 3751 of file function_internal.cpp.
{
     // Variable number of arguments
     va_list args;
     va_start(args, fmt);
     // Print to buffer
     casadi_int n = vsnprintf(buf, buf_sz, fmt, args);
     // Cleanup
     va_end(args);
     // Throw error if failure
     casadi_assert(n>=0 && n<buf_sz, "Print failure while processing '" + std::string(fmt) + "'");
   }
Referenced by casadi::ProtoFunction::format_time(), and casadi::ProtoFunction::print_time().
weak()
WeakRef * casadi::SharedObjectInternal::weak () inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1ai
Definition at line 62 of file shared_object_internal.cpp.
{
     if (weak_ref_==nullptr) {
       weak_ref_ = new WeakRef(this);
     }
     return weak_ref_;
   }
Referenced by casadi::SharedObject::weak().
Member Data Documentation
error_on_fail_
bool casadi::ProtoFunction::error_on_fail_ inherited
Definition at line 249 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::call_gen(), casadi::DaqpInterface::codegen_body(), casadi::FatropInterface::codegen_body(), casadi::HighsInterface::codegen_body(), casadi::HpipmInterface::codegen_body(), casadi::IpoptInterface::codegen_body(), casadi::MadnlpInterface::codegen_body(), casadi::OsqpInterface::codegen_body(), casadi::Qrqp::codegen_body(), casadi::Conic::Conic(), casadi::Conic::eval(), casadi::Nlpsol::eval(), casadi::Rootfinder::eval(), casadi::ProtoFunction::generate_options(), casadi::ProtoFunction::init(), casadi::Nlpsol::Nlpsol(), casadi::ProtoFunction::ProtoFunction(), casadi::Rootfinder::Rootfinder(), casadi::ProtoFunction::serialize_body(), and casadi::KinsolInterface::solve().
infix_
const std::string casadi::LinsolInternal::infix_ = "linsol" static inherited
Definition at line 130 of file linsol_internal.hpp.
meta_doc
const std::string casadi::CsparseInterface::meta_doc static
Initial value:
=
      "\n"
"Linsol with CSparse Interface\n"
"\n"
"\n"
">List of available options\n"
"\n"
"+----+------+---------+-------------+\n"
"| Id | Type | Default | Description |\n"
"+====+======+=========+=============+\n"
"+----+------+---------+-------------+\n"
"\n"
"\n"
"\n"
"\n"
Definition at line 103 of file csparse_interface.hpp.
Referenced by casadi::casadi_register_linsol_csparse().
name_
std::string casadi::ProtoFunction::name_ inherited
Definition at line 234 of file function_internal.hpp.
Referenced by casadi::MXFunction::ad_forward(), casadi::MXFunction::ad_reverse(), casadi::Integrator::augmented_dae(), casadi::OracleFunction::calc_function(), casadi::FunctionInternal::call_forward(), casadi::FunctionInternal::call_reverse(), casadi::FunctionInternal::codegen_body(), casadi::External::codegen_body(), casadi::External::codegen_checkout(), casadi::External::codegen_declarations(), casadi::MXFunction::codegen_declarations(), casadi::External::codegen_decref(), casadi::External::codegen_incref(), casadi::FunctionInternal::codegen_meta(), casadi::FunctionInternal::codegen_name(), casadi::External::codegen_release(), casadi::FunctionInternal::codegen_sparsities(), casadi::ProtoFunction::construct(), casadi::OracleFunction::create_function(), casadi::FunctionInternal::definition(), casadi::FunctionInternal::eval(), casadi::MXFunction::eval(), casadi::FunctionInternal::eval_mx(), casadi::MXFunction::eval_mx(), casadi::FmuFunction::factory(), casadi::FunctionInternal::finalize(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::FunctionInternal(), casadi::Integrator::get_forward(), casadi::Integrator::get_forward_dae(), casadi::Map::get_function(), casadi::MapSum::get_function(), casadi::OracleFunction::get_function(), casadi::GenericExternal::get_jac_sparsity(), casadi::FunctionInternal::get_n_in(), casadi::External::get_n_in(), casadi::FunctionInternal::get_n_out(), casadi::External::get_n_out(), casadi::FunctionInternal::get_name_in(), casadi::External::get_name_in(), casadi::FunctionInternal::get_name_out(), casadi::External::get_name_out(), casadi::FunctionInternal::get_partition(), casadi::Integrator::get_reverse(), casadi::FunctionInternal::get_sparsity_in(), casadi::GenericExternal::get_sparsity_in(), casadi::FunctionInternal::get_sparsity_out(), casadi::GenericExternal::get_sparsity_out(), casadi::External::has_forward(), casadi::GenericExternal::has_jac_sparsity(), casadi::External::has_jacobian(), casadi::External::has_reverse(), casadi::External::init(), casadi::FunctionInternal::init(), casadi::MXFunction::init(), casadi::CvodesInterface::init(), casadi::IdasInterface::init(), casadi::External::init_external(), casadi::GenericExternal::init_external(), casadi::FunctionInternal::jac_is_symm(), casadi::FunctionInternal::jacobian(), casadi::FunctionInternal::map(), casadi::OracleFunction::monitored(), casadi::MXFunction::print_arg(), casadi::FunctionInternal::print_in(), casadi::FunctionInternal::print_out(), casadi::MXFunction::print_res(), casadi::ProtoFunction::print_time(), casadi::ProtoFunction::ProtoFunction(), casadi::CvodesInterface::reset(), casadi::IdasInterface::reset(), casadi::IdasInterface::resetB(), casadi::FunctionInternal::reverse(), casadi::ProtoFunction::serialize_body(), casadi::GurobiInterface::solve(), casadi::SnoptInterface::solve(), casadi::Integrator::sp_forward(), casadi::Integrator::sp_reverse(), casadi::FunctionInternal::wrap(), and casadi::FunctionInternal::wrap_as_needed().
options_
const Options casadi::ProtoFunction::options_ static inherited
Initial value:
= {{},
     {{"verbose",
       {OT_BOOL,
        "Verbose evaluation -- for debugging"}},
      {"print_time",
       {OT_BOOL,
        "print information about execution time. Implies record_time."}},
      {"record_time",
       {OT_BOOL,
        "record information about execution time, for retrieval with stats()."}},
      {"regularity_check",
       {OT_BOOL,
        "Throw exceptions when NaN or Inf appears during evaluation"}},
      {"error_on_fail",
       {OT_BOOL,
        "Throw exceptions when function evaluation fails (default true)."}}
      }
  }
Extra doc: https://github.com/casadi/casadi/wiki/L_jg
Definition at line 115 of file function_internal.hpp.
Referenced by casadi::casadi_register_linsol_csparse(), casadi::casadi_register_linsol_lsqr(), casadi::casadi_register_linsol_ma27(), and casadi::casadi_register_linsol_tridiag().
print_time_
bool casadi::ProtoFunction::print_time_ inherited
Definition at line 240 of file function_internal.hpp.
Referenced by casadi::FixedStepIntegrator::create_advanced(), casadi::ProtoFunction::generate_options(), casadi::ProtoFunction::init(), casadi::FunctionInternal::init(), casadi::Nlpsol::Nlpsol(), casadi::ProtoFunction::print_time(), casadi::ProtoFunction::ProtoFunction(), and casadi::ProtoFunction::serialize_body().
record_time_
bool casadi::ProtoFunction::record_time_ inherited
Definition at line 243 of file function_internal.hpp.
Referenced by casadi::ProtoFunction::generate_options(), casadi::ProtoFunction::init(), casadi::FunctionInternal::init(), casadi::ProtoFunction::init_mem(), casadi::LinsolInternal::init_mem(), casadi::ProtoFunction::ProtoFunction(), and casadi::ProtoFunction::serialize_body().
regularity_check_
bool casadi::ProtoFunction::regularity_check_ inherited
Definition at line 246 of file function_internal.hpp.
Referenced by casadi::OracleFunction::calc_function(), casadi::ProtoFunction::change_option(), casadi::FunctionInternal::eval_gen(), casadi::FunctionInternal::FunctionInternal(), casadi::ProtoFunction::generate_options(), casadi::ProtoFunction::init(), casadi::ProtoFunction::ProtoFunction(), and casadi::ProtoFunction::serialize_body().
solvers_
std::map< std::string, LinsolInternal::Plugin > casadi::LinsolInternal::solvers_ static inherited
Definition at line 127 of file linsol_internal.hpp.
sp_
Sparsity casadi::LinsolInternal::sp_ inherited
Definition at line 157 of file linsol_internal.hpp.
Referenced by casadi::LinsolQr::finalize(), casadi::LinsolLdl::generate(), casadi::LinsolQr::generate(), casadi::Lsqr::generate(), casadi::LinsolLdl::init(), casadi::LinsolQr::init(), casadi::SymbolicQr::init(), casadi::MumpsInterface::init_mem(), casadi::Lsqr::init_mem(), casadi::SymbolicQr::init_mem(), casadi::SymbolicQr::linsol_eval_sx(), casadi::LinsolInternal::LinsolInternal(), nfact(), casadi::LapackLu::nfact(), casadi::LapackQr::nfact(), casadi::LinsolLdl::nfact(), casadi::LinsolQr::nfact(), casadi::LinsolInternal::serialize_body(), casadi::LinsolTridiag::solve(), and casadi::Lsqr::solve().
verbose_
bool casadi::ProtoFunction::verbose_ inherited
Definition at line 237 of file function_internal.hpp.
Referenced by casadi::MXFunction::ad_forward(), casadi::MXFunction::ad_reverse(), casadi::ProtoFunction::change_option(), casadi::BSplineInterpolant::construct_graph(), casadi::OracleFunction::create_function(), casadi::FmuFunction::eval(), casadi::Integrator::eval(), casadi::MXFunction::eval(), casadi::MXFunction::eval_mx(), casadi::FmuFunction::factory(), casadi::FunctionInternal::finalize(), casadi::KinsolInterface::func(), casadi::ProtoFunction::generate_options(), casadi::FmuFunction::get_forward(), casadi::Integrator::get_forward(), casadi::Integrator::get_forward_dae(), casadi::FunctionInternal::get_jac_sparsity_gen(), casadi::FunctionInternal::get_jac_sparsity_hierarchical(), casadi::FunctionInternal::get_jac_sparsity_hierarchical_symm(), casadi::FmuFunction::get_jacobian(), casadi::FunctionInternal::get_partition(), casadi::FmuFunction::get_reverse(), casadi::Integrator::get_reverse(), casadi::ProtoFunction::init(), casadi::FiniteDiff::init(), casadi::FmuFunction::init(), casadi::FunctionInternal::init(), casadi::MXFunction::init(), casadi::Blocksqp::init(), casadi::FatropConicInterface::init(), casadi::FatropInterface::init(), casadi::HpipmInterface::init(), casadi::HpmpcInterface::init(), casadi::IpoptInterface::init(), casadi::MadnlpInterface::init(), casadi::CvodesInterface::init(), casadi::IdasInterface::init(), casadi::Feasiblesqpmethod::init(), casadi::Scpgen::init(), casadi::Sqpmethod::init(), casadi::IpoptInterface::init_mem(), casadi::IdasInterface::init_mem(), casadi::BonminInterface::intermediate_callback(), casadi::OracleFunction::jit_dependencies(), nfact(), casadi::LapackLu::nfact(), casadi::LapackQr::nfact(), casadi::LinsolQr::nfact(), casadi::ProtoFunction::ProtoFunction(), casadi::CvodesInterface::reset(), casadi::IdasInterface::reset(), casadi::IdasInterface::resetB(), casadi::ProtoFunction::serialize_body(), casadi::CbcInterface::solve(), casadi::ClpInterface::solve(), casadi::CplexInterface::solve(), casadi::GurobiInterface::solve(), casadi::HpipmInterface::solve(), casadi::QpoasesInterface::solve(), casadi::Ipqp::solve(), casadi::Qrqp::solve(), casadi::AlpaqaInterface::solve(), casadi::AmplInterface::solve(), casadi::SnoptInterface::solve(), casadi::KinsolInterface::solve(), casadi::WorhpInterface::solve(), casadi::Newton::solve(), casadi::Qrsqp::solve(), casadi::Scpgen::solve(), casadi::Sqpmethod::solve(), casadi::Sqpmethod::solve_ela_QP(), casadi::Feasiblesqpmethod::solve_LP(), casadi::Feasiblesqpmethod::solve_QP(), casadi::Qrsqp::solve_QP(), casadi::Sqpmethod::solve_QP(), casadi::Integrator::sp_forward(), and casadi::Integrator::sp_reverse().
The documentation for this class was generated from the following files:
csparse_interface.hpp
csparse_interface.cpp
csparse_interface_meta.cpp