CasADi: casadi::XmlNode Struct Reference
casadi::XmlNode Struct Reference
#include <xml_node.hpp>
Detailed Description
Definition at line 39 of file xml_node.hpp.
Public Member Functions
bool has_attribute (const std::string &att_name) const
Check if an attribute is present.
void set_attribute (const std::string &att_name, const std::string &att)
Add an attribute.
void set_attribute (const std::string &att_name, casadi_int att)
Add an integer attribute.
void set_attribute (const std::string &att_name, double att)
Add an integer attribute.
void set_attribute (const std::string &att_name, const std::vector< casadi_int > &att)
Add a vector attribute.
std::vector< std::string > child_names () const
Names of children.
std::vector< std::string > attribute_names () const
Names of attributes.
template<typename T >
T attribute (const std::string &att_name) const
Get an attribute by its name.
template<typename T >
T attribute (const std::string &att_name, const T &def_att) const
Get an attribute by its name, default value if not found.
const XmlNode & operator[] (size_t i) const
Get a reference to a child by its index.
XmlNode & operator[] (size_t i)
Get a reference to a child by its index.
const XmlNode & operator[] (const std::string &childname) const
Get a reference to a child by its name.
XmlNode & operator[] (const std::string &childname)
Get a reference to a child by its name.
bool has_child (const std::string &childname) const
Check if a child is present.
size_t size () const
Get the number of children.
template<typename T >
void get (T *val) const
Get value of text field.
void dump (std::ostream &stream, casadi_int indent=0) const
Dump representation.
Static Public Member Functions
static void read (const std::string &str, std::string *val)
Read the string value of a string (i.e. copy)
static void read (const std::string &str, bool *val)
Read the boolean value of a string.
static void read (const std::string &str, casadi_int *val)
Read the integer value of a string.
static void read (const std::string &str, size_t *val)
Read the size_t value of a string.
static void read (const std::string &str, double *val)
Read the double value of a string.
static void read (const std::string &str, std::vector< casadi_int > *val)
Read a vector of integer values of a string.
static void read (const std::string &str, std::vector< std::string > *val)
Read a vector of string values of a string.
Public Attributes
std::map< std::string, std::string > attributes
std::vector< XmlNode > children
std::string name
std::string comment
casadi_int line
std::string text
Friends
CASADI_EXPORT friend std::ostream & operator<< (std::ostream &stream, const XmlNode &node)
Print to stream.
Member Function Documentation
attribute() [1/2]
template<typename T > T casadi::XmlNode::attribute (const std::string & att_name) const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_vg
Definition at line 99 of file xml_node.hpp.
{
     // Find the attribute, if any
     auto it = this->attributes.find(att_name);
     casadi_assert(it != this->attributes.end(), "Could not find attribute " + att_name);
     // Attribute found, read it
     T ret;
     read(it->second, &ret);
     return ret;
   }
References casadi::T.
Referenced by casadi::DaeBuilderInternal::import_default_experiment(), casadi::DaeBuilderInternal::import_dynamic_equations(), casadi::DaeBuilderInternal::import_initial_equations(), casadi::DaeBuilderInternal::import_model_exchange(), casadi::DaeBuilderInternal::import_model_structure(), casadi::DaeBuilderInternal::import_model_variables(), casadi::DaeBuilderInternal::load_fmi_description(), casadi::DaeBuilderInternal::qualified_name(), casadi::DaeBuilderInternal::read_dependencies(), casadi::DaeBuilderInternal::read_dependencies_kind(), and set_attribute().
attribute() [2/2]
template<typename T > T casadi::XmlNode::attribute (const std::string & att_name, const T & def_att) const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_vh
Definition at line 113 of file xml_node.hpp.
{
     // Find the attribute, if any
     auto it = this->attributes.find(att_name);
     if (it == this->attributes.end()) {
       // No such attribute, return default value
       return def_att;
     } else {
       // Attribute found, read it
       T ret;
       read(it->second, &ret);
       return ret;
     }
   }
References casadi::T.
attribute_names()
std::vector< std::string > casadi::XmlNode::attribute_names () const
Extra doc: https://github.com/casadi/casadi/wiki/L_vf
Definition at line 169 of file xml_node.cpp.
{
   std::vector<std::string> ret;
   ret.reserve(this->attributes.size());
   for (auto& a : this->attributes) ret.push_back(a.first);
   return ret;
 }
References attributes.
child_names()
std::vector< std::string > casadi::XmlNode::child_names () const
Extra doc: https://github.com/casadi/casadi/wiki/L_ve
Definition at line 162 of file xml_node.cpp.
{
   std::vector<std::string> ret;
   ret.reserve(this->children.size());
   for (auto& c : this->children) ret.push_back(c.name);
   return ret;
 }
References children.
dump()
void casadi::XmlNode::dump (std::ostream & stream, casadi_int indent = 0) const
Extra doc: https://github.com/casadi/casadi/wiki/L_vw
Definition at line 84 of file xml_node.cpp.
{
   // Print name
   stream << std::string(indent, ' ') << "Node: " << this->name << std::endl;
   // Print comment
   if (!this->comment.empty()) {
     stream << std::string(indent, ' ') << "----- comment starts ----- "  << std::endl;
     stream << this->comment << std::endl;
     stream << std::string(indent, ' ') << "----- comment ends ----- "  << std::endl;
   }
   // Print text
   if (!this->text.empty())
     stream << std::string(indent+2, ' ') << "Text: " << this->text << std::endl;
   // Print attributes
   for (auto it = this->attributes.begin(); it != this->attributes.end(); ++it)
     stream << std::string(indent+2, ' ') << "attribute " << it->first
       << " = " << it->second << std::endl;
   // Print Children
   for (casadi_int i=0; i < size(); ++i) {
     stream << std::string(indent, ' ') << "Child " << i << ":" << std::endl;
     (*this)[i].dump(stream, indent+2);
   }
 }
References attributes, comment, name, size(), and text.
get()
template<typename T > void casadi::XmlNode::get (T * val) const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_vo
Definition at line 161 of file xml_node.hpp.
 { read(this->text, val);}
Referenced by casadi::DaeBuilderInternal::qualified_name(), and casadi::DaeBuilderInternal::read_expr().
has_attribute()
bool casadi::XmlNode::has_attribute (const std::string & att_name) const
Extra doc: https://github.com/casadi/casadi/wiki/L_vc
Definition at line 31 of file xml_node.cpp.
{
   return this->attributes.find(att_name) != this->attributes.end();
 }
References attributes.
Referenced by casadi::DaeBuilderInternal::read_dependencies(), and casadi::DaeBuilderInternal::read_dependencies_kind().
has_child()
bool casadi::XmlNode::has_child (const std::string & childname) const
Extra doc: https://github.com/casadi/casadi/wiki/L_vm
Definition at line 35 of file xml_node.cpp.
{
   // Linear search over the elements
   for (auto& c : this->children) {
     if (c.name == childname) return true;
   }
   // Not found
   return false;
 }
References children.
Referenced by casadi::DaeBuilderInternal::import_model_exchange(), casadi::DaeBuilderInternal::import_model_structure(), casadi::DaeBuilderInternal::import_model_variables(), and casadi::DaeBuilderInternal::load_fmi_description().
operator[]() [1/4]
XmlNode & casadi::XmlNode::operator[] (const std::string & childname)
Extra doc: https://github.com/casadi/casadi/wiki/L_vl
Definition at line 44 of file xml_node.cpp.
{
   // Linear search over the elements
   auto it = this->children.begin();
   for (; it != this->children.end(); ++it) {
     if (it->name == childname) break;
   }
   // Check that the child was indeed found
   casadi_assert(it != this->children.end(), "Could not find " + childname);
   // Return a reference to the child
   return *it;
 }
References children.
operator[]() [2/4]
const XmlNode & casadi::XmlNode::operator[] (const std::string & childname) const
Extra doc: https://github.com/casadi/casadi/wiki/L_vk
Definition at line 56 of file xml_node.cpp.
{
   return const_cast<XmlNode*>(this)->operator[](childname); // NOLINT
 }
operator[]() [3/4]
XmlNode& casadi::XmlNode::operator[] (size_t i) inline
Extra doc: https://github.com/casadi/casadi/wiki/L_vj
Definition at line 135 of file xml_node.hpp.
 { return this->children.at(i);}
operator[]() [4/4]
const XmlNode& casadi::XmlNode::operator[] (size_t i) const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_vi
Definition at line 130 of file xml_node.hpp.
 { return this->children.at(i);}
read() [1/7]
void casadi::XmlNode::read (const std::string & str, bool * val) static
Extra doc: https://github.com/casadi/casadi/wiki/L_vq
Definition at line 115 of file xml_node.cpp.
{
   if (str == "true") {
     *val = true;
   } else if (str == "false") {
     *val = false;
   } else {
     casadi_error("XML argument not 'true' or 'false'");
   }
 }
References casadi::str().
read() [2/7]
void casadi::XmlNode::read (const std::string & str, casadi_int * val) static
Extra doc: https://github.com/casadi/casadi/wiki/L_vr
Definition at line 130 of file xml_node.cpp.
{
   std::istringstream buffer(str);
   buffer >> *val;
 }
References casadi::str().
read() [3/7]
void casadi::XmlNode::read (const std::string & str, double * val) static
Extra doc: https://github.com/casadi/casadi/wiki/L_vs
Definition at line 135 of file xml_node.cpp.
{
   std::istringstream buffer(str);
   buffer >> *val;
 }
References casadi::str().
read() [4/7]
void casadi::XmlNode::read (const std::string & str, size_t * val) static
Extra doc: https://github.com/casadi/casadi/wiki/L_29u
Definition at line 125 of file xml_node.cpp.
{
   std::istringstream buffer(str);
   buffer >> *val;
 }
References casadi::str().
read() [5/7]
void casadi::XmlNode::read (const std::string & str, std::string * val) static
Extra doc: https://github.com/casadi/casadi/wiki/L_vp
Definition at line 111 of file xml_node.cpp.
{
   *val = str;
 }
References casadi::str().
read() [6/7]
void casadi::XmlNode::read (const std::string & str, std::vector< casadi_int > * val) static
Extra doc: https://github.com/casadi/casadi/wiki/L_vt
Definition at line 140 of file xml_node.cpp.
{
   val->clear();
   std::istringstream buffer(str);
   while (true) {
     casadi_int v;
     buffer >> v;
     if (buffer.fail()) break;
     val->push_back(v);
   }
 }
References casadi::str().
read() [7/7]
void casadi::XmlNode::read (const std::string & str, std::vector< std::string > * val) static
Extra doc: https://github.com/casadi/casadi/wiki/L_vu
Definition at line 151 of file xml_node.cpp.
{
   val->clear();
   std::istringstream buffer(str);
   while (true) {
     std::string v;
     buffer >> v;
     if (buffer.fail()) break;
     val->push_back(v);
   }
 }
References casadi::str().
set_attribute() [1/4]
void casadi::XmlNode::set_attribute (const std::string & att_name, casadi_int att) inline
Extra doc: https://github.com/casadi/casadi/wiki/L_252
Definition at line 71 of file xml_node.hpp.
{
     set_attribute(att_name, std::to_string(att));
   }
set_attribute() [2/4]
void casadi::XmlNode::set_attribute (const std::string & att_name, const std::string & att)
Extra doc: https://github.com/casadi/casadi/wiki/L_vd
Definition at line 60 of file xml_node.cpp.
{
   this->attributes[attribute_name] = attribute;
 }
References attribute(), and attributes.
Referenced by casadi::Variable::export_xml(), casadi::DaeBuilderInternal::generate_build_description(), casadi::DaeBuilderInternal::generate_model_description(), casadi::DaeBuilderInternal::generate_model_structure(), casadi::TinyXmlInterface::import_node(), and set_attribute().
set_attribute() [3/4]
void casadi::XmlNode::set_attribute (const std::string & att_name, const std::vector< casadi_int > & att)
Extra doc: https://github.com/casadi/casadi/wiki/L_254
Definition at line 64 of file xml_node.cpp.
{
   std::stringstream ss;
   if (!att.empty()) {
     ss << att.at(0);
     for (size_t i = 1; i < att.size(); ++i) ss << " " << att.at(i);
   }
   return set_attribute(att_name, ss.str());
 }
References set_attribute().
set_attribute() [4/4]
void casadi::XmlNode::set_attribute (const std::string & att_name, double att)
Extra doc: https://github.com/casadi/casadi/wiki/L_253
Definition at line 73 of file xml_node.cpp.
{
   std::stringstream ss;
   ss << std::scientific << std::setprecision(std::numeric_limits<double>::digits10 + 1) << att;
   set_attribute(att_name, ss.str());
 }
References set_attribute().
size()
size_t casadi::XmlNode::size () const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_vn
Definition at line 155 of file xml_node.hpp.
 { return this->children.size();}
Referenced by dump(), casadi::DaeBuilderInternal::import_binding_equations(), casadi::DaeBuilderInternal::import_dynamic_equations(), casadi::DaeBuilderInternal::import_initial_equations(), casadi::DaeBuilderInternal::import_model_structure(), casadi::DaeBuilderInternal::import_model_variables(), casadi::DaeBuilderInternal::qualified_name(), casadi::DaeBuilderInternal::read_expr(), and casadi::read_list().
Friends And Related Function Documentation
operator<<
CASADI_EXPORT friend std::ostream& operator<< (std::ostream & stream, const XmlNode & node) friend
Extra doc: https://github.com/casadi/casadi/wiki/L_vv
Definition at line 79 of file xml_node.cpp.
{
   node.dump(stream);
   return stream;
 }
Member Data Documentation
attributes
std::map<std::string, std::string> casadi::XmlNode::attributes
Definition at line 41 of file xml_node.hpp.
Referenced by attribute_names(), dump(), casadi::TinyXmlInterface::export_node(), has_attribute(), and set_attribute().
children
std::vector<XmlNode> casadi::XmlNode::children
Definition at line 44 of file xml_node.hpp.
Referenced by child_names(), casadi::TinyXmlInterface::export_node(), casadi::DaeBuilderInternal::generate_build_description(), casadi::DaeBuilderInternal::generate_model_description(), casadi::DaeBuilderInternal::generate_model_structure(), casadi::DaeBuilderInternal::generate_model_variables(), has_child(), casadi::TinyXmlInterface::import_node(), and operator[]().
comment
std::string casadi::XmlNode::comment
Definition at line 50 of file xml_node.hpp.
Referenced by dump(), and casadi::TinyXmlInterface::import_node().
line
casadi_int casadi::XmlNode::line
Definition at line 53 of file xml_node.hpp.
Referenced by casadi::TinyXmlInterface::import_node().
name
std::string casadi::XmlNode::name
Definition at line 47 of file xml_node.hpp.
Referenced by dump(), casadi::TinyXmlInterface::export_node(), casadi::Variable::export_xml(), casadi::DaeBuilderInternal::generate_build_description(), casadi::DaeBuilderInternal::generate_model_description(), casadi::DaeBuilderInternal::generate_model_structure(), casadi::DaeBuilderInternal::generate_model_variables(), casadi::DaeBuilderInternal::import_dynamic_equations(), casadi::DaeBuilderInternal::import_model_structure(), casadi::DaeBuilderInternal::import_model_variables(), casadi::TinyXmlInterface::import_node(), and casadi::DaeBuilderInternal::read_expr().
text
std::string casadi::XmlNode::text
Definition at line 56 of file xml_node.hpp.
Referenced by dump(), casadi::DaeBuilderInternal::import_model_variables(), casadi::TinyXmlInterface::import_node(), and casadi::DaeBuilderInternal::read_expr().
The documentation for this struct was generated from the following files:
xml_node.hpp
xml_node.cpp