CasADi: casadi::GurobiMemory Struct Reference
casadi::GurobiMemory Struct Reference
#include <gurobi_interface.hpp>
Detailed Description
Definition at line 49 of file gurobi_interface.hpp.
Public Member Functions
GurobiMemory ()
Constructor.
~GurobiMemory ()
Destructor.
void add_stat (const std::string &s)
Public Attributes
GRBenv * env
int return_status
int pool_sol_nr
std::vector< double > pool_obj_vals
std::vector< std::vector< double > > pool_solutions
std::vector< double > sos_weights
std::vector< int > sos_beg
std::vector< int > sos_ind
std::vector< int > sos_types
casadi_qp_data< double > d_qp
std::map< std::string, FStats > fstats
FStats * t_total
Constructor & Destructor Documentation
GurobiMemory()
casadi::GurobiMemory::GurobiMemory ()
Definition at line 564 of file gurobi_interface.cpp.
{
     this->env = nullptr;
   }
References env.
~GurobiMemory()
casadi::GurobiMemory::~GurobiMemory ()
Definition at line 568 of file gurobi_interface.cpp.
{
     if (this->env) GRBfreeenv(this->env);
   }
References env.
Member Function Documentation
add_stat()
void casadi::ProtoFunctionMemory::add_stat (const std::string & s) inline inherited
Definition at line 74 of file function_internal.hpp.
{
       bool added = fstats.insert(std::make_pair(s, FStats())).second;
       casadi_assert(added, "Duplicate stat: '" + s + "'");
     }
Referenced by casadi::ProtoFunction::init_mem(), casadi::LinsolInternal::init_mem(), casadi::Nlpsol::init_mem(), casadi::OracleFunction::init_mem(), casadi::CbcInterface::init_mem(), casadi::ClpInterface::init_mem(), casadi::FatropConicInterface::init_mem(), casadi::HpipmInterface::init_mem(), casadi::Feasiblesqpmethod::init_mem(), casadi::Sqpmethod::init_mem(), and casadi::OracleFunction::local_init_mem().
Member Data Documentation
d_qp
casadi_qp_data<double> casadi::ConicMemory::d_qp inherited
Definition at line 39 of file conic_impl.hpp.
Referenced by casadi::Conic::get_stats(), and casadi::FatropConicInterface::solve().
env
GRBenv* casadi::GurobiMemory::env
Definition at line 51 of file gurobi_interface.hpp.
Referenced by GurobiMemory(), and ~GurobiMemory().
fstats
std::map<std::string, FStats> casadi::ProtoFunctionMemory::fstats inherited
Definition at line 68 of file function_internal.hpp.
Referenced by casadi::Nlpsol::callback(), casadi::IpoptUserClass::eval_h(), casadi::BonminInterface::intermediate_callback(), casadi::IpoptInterface::intermediate_callback(), casadi::OracleFunction::join_results(), casadi::FatropConicInterface::solve(), casadi::HighsInterface::solve(), casadi::HpipmInterface::solve(), casadi::HpmpcInterface::solve(), casadi::ProxqpInterface::solve(), casadi::QpoasesInterface::solve(), casadi::Sqpmethod::solve_ela_QP(), casadi::Feasiblesqpmethod::solve_LP(), casadi::Feasiblesqpmethod::solve_QP(), and casadi::Sqpmethod::solve_QP().
pool_obj_vals
std::vector<double> casadi::GurobiMemory::pool_obj_vals
Definition at line 56 of file gurobi_interface.hpp.
pool_sol_nr
int casadi::GurobiMemory::pool_sol_nr
Definition at line 55 of file gurobi_interface.hpp.
pool_solutions
std::vector<std::vector<double> > casadi::GurobiMemory::pool_solutions
Definition at line 57 of file gurobi_interface.hpp.
return_status
int casadi::GurobiMemory::return_status
Definition at line 53 of file gurobi_interface.hpp.
sos_beg
std::vector<int> casadi::GurobiMemory::sos_beg
Definition at line 61 of file gurobi_interface.hpp.
sos_ind
std::vector<int> casadi::GurobiMemory::sos_ind
Definition at line 62 of file gurobi_interface.hpp.
sos_types
std::vector<int> casadi::GurobiMemory::sos_types
Definition at line 63 of file gurobi_interface.hpp.
sos_weights
std::vector<double> casadi::GurobiMemory::sos_weights
Definition at line 60 of file gurobi_interface.hpp.
t_total
FStats* casadi::ProtoFunctionMemory::t_total inherited
Definition at line 71 of file function_internal.hpp.
Referenced by casadi::LinsolCall< Tr >::eval(), casadi::FunctionInternal::eval_gen(), and casadi::Linsol::solve().
The documentation for this struct was generated from the following files:
gurobi_interface.hpp
gurobi_interface.cpp