CasADi: casadi::OptiAdvanced Class Reference
casadi::OptiAdvanced Class Reference
#include <optistack.hpp>
Detailed Description
Definition at line 551 of file optistack.hpp.
Public Types
using internal_base_type = SharedObjectInternal
using base_type = SharedObject
Public Member Functions
OptiAdvanced (const Opti &x)
~OptiAdvanced ()
Destructor.
Function casadi_solver () const
Get the underlying CasADi solver of the Opti stack.
bool is_parametric (const MX &expr) const
return true if expression is only dependant on Opti parameters, not variables
MetaCon canon_expr (const MX &expr) const
Interpret an expression (for internal use only)
MetaVar get_meta (const MX &m) const
Get meta-data of symbol (for internal use only)
MetaCon get_meta_con (const MX &m) const
Get meta-data of symbol (for internal use only)
void set_meta (const MX &m, const MetaVar &meta)
Set meta-data of an expression.
void set_meta_con (const MX &m, const MetaCon &meta)
Set meta-data of an expression.
void assert_active_symbol (const MX &m) const
std::vector< MX > active_symvar (VariableType type) const
std::vector< DM > active_values (VariableType type) const
MX x_lookup (casadi_index i) const
MX g_lookup (casadi_index i) const
casadi_index g_index_reduce_g (casadi_index i) const
casadi_index g_index_reduce_x (casadi_index i) const
casadi_index g_index_unreduce_g (casadi_index i) const
std::string x_describe (casadi_index i, const Dict &opts=Dict()) const
std::string g_describe (casadi_index i, const Dict &opts=Dict()) const
std::string describe (const MX &x, casadi_index indent=0, const Dict &opts=Dict()) const
void show_infeasibilities (double tol=0, const Dict &opts=Dict()) const
void solve_prepare ()
DMDict solve_actual (const DMDict &args)
DMDict arg () const
void res (const DMDict &res)
DMDict res () const
std::vector< MX > constraints () const
MX objective () const
OptiAdvanced baked_copy () const
void assert_empty () const
void bake ()
Fix the structure of the optimization problem.
void mark_problem_dirty (bool flag=true)
bool problem_dirty () const
void mark_solver_dirty (bool flag=true)
bool solver_dirty () const
void mark_solved (bool flag=true)
bool solved () const
void assert_solved () const
void assert_baked () const
casadi_int instance_number () const
MX variable (casadi_int n=1, casadi_int m=1, const std::string &attribute="full")
Create a decision variable (symbol)
MX variable (const Sparsity &sp, const std::string &attribute="full")
MX variable (const MX &symbol, const std::string &attribute="full")
MX parameter (casadi_int n=1, casadi_int m=1, const std::string &attribute="full")
Create a parameter (symbol); fixed during optimization.
MX parameter (const Sparsity &sp, const std::string &attribute="full")
MX parameter (const MX &symbol, const std::string &attribute="full")
void minimize (const MX &f, double linear_scale=1)
Set objective.
void subject_to ()
Clear constraints.
void solver (const std::string &solver, const Dict &plugin_options=Dict(), const Dict &solver_options=Dict())
Set a solver.
Dict stats () const
Get statistics.
std::string return_status () const
Get return status of solver.
std::vector< MX > initial () const
get assignment expressions for initial values
std::vector< MX > value_variables () const
get assignment expressions for latest values
std::vector< MX > value_parameters () const
Function scale_helper (const Function &h) const
Scale a helper function constructed via opti.x, opti.g, ...
MX dual (const MX &m) const
get the dual variable
casadi_int nx () const
Number of (scalarised) decision variables.
casadi_int np () const
Number of (scalarised) parameters.
casadi_int ng () const
Number of (scalarised) constraints.
MX x () const
Get all (scalarised) decision variables as a symbolic column vector.
MX p () const
Get all (scalarised) parameters as a symbolic column vector.
MX g () const
Get all (scalarised) constraint expressions as a column vector.
MX f () const
Get objective expression.
MX lbg () const
Get all (scalarised) bounds on constraints as a column vector.
MX ubg () const
DM x_linear_scale () const
DM x_linear_scale_offset () const
DM g_linear_scale () const
double f_linear_scale () const
MX lam_g () const
Get all (scalarised) dual variables as a symbolic column vector.
OptiAdvanced debug () const
Get a copy with advanced functionality.
OptiAdvanced advanced () const
Get a copy with advanced functionality.
Opti copy () const
Get a copy of the.
void update_user_dict (const MX &m, const Dict &meta)
add user data
void update_user_dict (const std::vector< MX > &m, const Dict &meta)
Dict user_dict (const MX &m) const
Get user data.
std::string type_name () const
Readable name of the class.
void disp (std::ostream &stream, bool more=false) const
Print representation.
std::string get_str (bool more=false) const
Get string representation.
std::string class_name () const
Get class name.
void print_ptr (std::ostream &stream=casadi::uout()) const
void own (SharedObjectInternal *node)
void assign (SharedObjectInternal *node)
Assign the node to a node class pointer without reference counting.
SharedObjectInternal * get () const
Get a const pointer to the node.
casadi_int getCount () const
Get the reference count.
void swap (GenericShared &other)
Swap content with another instance.
std::string debug_repr () const
bool is_null () const
Is a null pointer?
casadi_int __hash__ () const
Returns a number that is unique for a given Node.
GenericWeakRef< SharedObject, SharedObjectInternal > * weak ()
Get a weak reference to the object.
std::vector< MX > symvar () const
Get symbols present in expression.
std::vector< MX > symvar (const MX &expr) const
Get symbols present in expression.
std::vector< MX > symvar (const MX &expr, VariableType type) const
Get symbols present in expression.
void subject_to (const MX &g, const Dict &options=Dict())
Add constraints.
void subject_to (const std::vector< MX > &g, const Dict &options=Dict())
Add constraints.
void subject_to (const MX &g, const DM &linear_scale, const Dict &options=Dict())
Add constraints.
void subject_to (const std::vector< MX > &g, const DM &linear_scale, const Dict &options=Dict())
Add constraints.
void set_initial (const MX &x, const DM &v)
void set_initial (const std::vector< MX > &assignments)
void set_value (const MX &x, const DM &v)
Set value of parameter.
void set_value (const std::vector< MX > &assignments)
Set value of parameter.
void set_domain (const MX &x, const std::string &domain)
Set domain of a decision variable.
void set_linear_scale (const MX &x, const DM &scale, const DM &offset=0)
Set scale of a decision variable.
OptiSol solve ()
Crunch the numbers; solve the problem.
OptiSol solve_limited ()
Crunch the numbers; solve the problem.
native_DM value (const MX &x, const std::vector< MX > &values=std::vector< MX >()) const
native_DM value (const DM &x, const std::vector< MX > &values=std::vector< MX >()) const
Set domain of a decision variable.
native_DM value (const SX &x, const std::vector< MX > &values=std::vector< MX >()) const
Set domain of a decision variable.
Function to_function (const std::string &name, const std::vector< MX > &args, const std::vector< MX > &res, const Dict &opts=Dict())
Create a CasADi Function from the Opti solver.
Function to_function (const std::string &name, const std::vector< MX > &args, const std::vector< MX > &res, const std::vector< std::string > &name_in, const std::vector< std::string > &name_out, const Dict &opts=Dict())
Create a CasADi Function from the Opti solver.
Function to_function (const std::string &name, const std::map< std::string, MX > &dict, const std::vector< std::string > &name_in, const std::vector< std::string > &name_out, const Dict &opts=Dict())
Create a CasADi Function from the Opti solver.
void callback_class (OptiCallback *callback)
Helper methods for callback()
void callback_class ()
Helper methods for callback()
OptiNode * operator-> ()
Access a member of the node.
const OptiNode * operator-> () const
Const access a member of the node.
Static Public Member Functions
static MX bounded (const MX &lb, const MX &expr, const MX &ub)
Construct a double inequality.
static Opti create (OptiNode *node)
Public Attributes
bool problem_dirty_
bool solver_dirty_
bool solved_
Protected Member Functions
OptiAdvanced ()
void count_up ()
void count_down ()
Friends
class InternalOptiCallback
Member Typedef Documentation
base_type
using casadi::SharedObject::base_type = SharedObject inherited
Definition at line 103 of file shared_object.hpp.
internal_base_type
using casadi::SharedObject::internal_base_type = SharedObjectInternal inherited
Definition at line 102 of file shared_object.hpp.
Constructor & Destructor Documentation
OptiAdvanced() [1/2]
casadi::OptiAdvanced::OptiAdvanced (const Opti & x)
Definition at line 83 of file optistack.cpp.
                                           : Opti(rhs) {
 }
~OptiAdvanced()
casadi::OptiAdvanced::~OptiAdvanced () inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1t
Definition at line 560 of file optistack.hpp.
 {}
OptiAdvanced() [2/2]
casadi::OptiAdvanced::OptiAdvanced () inline protected
Definition at line 649 of file optistack.hpp.
 {}
Member Function Documentation
__hash__()
casadi_int casadi::GenericShared< SharedObject , SharedObjectInternal >::__hash__ inherited
If the Object does not point to any node, "0" is returned.
Extra doc: https://github.com/casadi/casadi/wiki/L_av
Definition at line 123 of file generic_shared_impl.hpp.
{
     return reinterpret_cast<casadi_int>(get());
   }
active_symvar()
std::vector< MX > casadi::OptiAdvanced::active_symvar (VariableType type) const
Definition at line 589 of file optistack.cpp.
{
   try {
     return (*this)->active_symvar(type);
   } catch(std::exception& e) {
     THROW_ERROR("active_symvar", e.what());
   }
 }
Referenced by casadi::Opti::disp().
active_values()
std::vector< DM > casadi::OptiAdvanced::active_values (VariableType type) const
Definition at line 597 of file optistack.cpp.
{
   try {
     return (*this)->active_values(type);
   } catch(std::exception& e) {
     THROW_ERROR("active_values", e.what());
   }
 }
advanced()
OptiAdvanced casadi::Opti::advanced () const inherited
You get access to more methods, but you have no guarantees about API stability
The copy is effectively a deep copy: Updating the state of the copy does not update the original.
Extra doc: https://github.com/casadi/casadi/wiki/L_1m
Definition at line 850 of file optistack.cpp.
{
   return copy();
 }
References casadi::Opti::copy().
arg()
DMDict casadi::OptiAdvanced::arg () const
Definition at line 690 of file optistack.cpp.
{
   try {
     return (*this)->arg();
   } catch(std::exception& e) {
     THROW_ERROR("arg", e.what());
   }
 }
assert_active_symbol()
void casadi::OptiAdvanced::assert_active_symbol (const MX & m) const
Definition at line 581 of file optistack.cpp.
{
   try {
     (*this)->assert_active_symbol(m);
   } catch(std::exception& e) {
     THROW_ERROR("assert_active_symbol", e.what());
   }
 }
assert_baked()
void casadi::OptiAdvanced::assert_baked () const
Definition at line 839 of file optistack.cpp.
{
   try {
     (*this)->assert_baked();
   } catch(std::exception& e) {
     THROW_ERROR("assert_baked", e.what());
   }
 }
assert_empty()
void casadi::OptiAdvanced::assert_empty () const
Definition at line 734 of file optistack.cpp.
{
   try {
     return (*this)->assert_empty();
   } catch(std::exception& e) {
     THROW_ERROR("assert_empty", e.what());
   }
 }
assert_solved()
void casadi::OptiAdvanced::assert_solved () const
Definition at line 832 of file optistack.cpp.
{
   try {
     (*this)->assert_solved();
   } catch(std::exception& e) {
     THROW_ERROR("assert_solved", e.what());
   }
 }
assign()
void casadi::GenericShared< SharedObject , SharedObjectInternal >::assign (Internal * node) inherited
improper use will cause memory leaks!
Extra doc: https://github.com/casadi/casadi/wiki/L_at
Definition at line 96 of file generic_shared_impl.hpp.
{
     node = node_;
   }
bake()
void casadi::OptiAdvanced::bake ()
Definition at line 778 of file optistack.cpp.
{
   try {
     (*this)->bake();
   } catch(std::exception& e) {
     THROW_ERROR("bake", e.what());
   }
 }
Referenced by casadi::OptiNode::baked_copy(), and casadi::Opti::disp().
baked_copy()
OptiAdvanced casadi::OptiAdvanced::baked_copy () const
Definition at line 726 of file optistack.cpp.
{
   try {
     return (*this)->baked_copy();
   } catch(std::exception& e) {
     THROW_ERROR("baked_copy", e.what());
   }
 }
References casadi::OptiNode::baked_copy().
bounded()
static MX casadi::Opti::bounded (const MX & lb, const MX & expr, const MX & ub) inline static inherited
Constructs: lb(p) <= g(x,p) <= ub(p)
Python prohibits such syntax directly
Extra doc: https://github.com/casadi/casadi/wiki/L_1k
Definition at line 397 of file optistack.hpp.
 { return (lb<=expr)<= ub; }
callback_class() [1/2]
void casadi::Opti::callback_class () inherited
Do not use directly.
Extra doc: https://github.com/casadi/casadi/wiki/L_1p
Definition at line 471 of file optistack.cpp.
{
   try {
     (*this)->callback_class();
   } catch(std::exception& e) {
     THROW_ERROR("callback_class", e.what());
   }
 }
Referenced by casadi::Opti::Opti().
callback_class() [2/2]
void casadi::Opti::callback_class (OptiCallback * callback) inherited
Do not use directly.
Extra doc: https://github.com/casadi/casadi/wiki/L_1p
Definition at line 463 of file optistack.cpp.
{
   try {
     (*this)->callback_class(callback);
   } catch(std::exception& e) {
     THROW_ERROR("callback_class", e.what());
   }
 }
canon_expr()
MetaCon casadi::OptiAdvanced::canon_expr (const MX & expr) const
Definition at line 540 of file optistack.cpp.
{
   try {
     return (*this)->canon_expr(expr);
   } catch(std::exception& e) {
     THROW_ERROR("canon_expr", e.what());
   }
 }
casadi_solver()
Function casadi::OptiAdvanced::casadi_solver () const
Definition at line 500 of file optistack.cpp.
{
   try {
     return (*this)->casadi_solver();
   } catch(std::exception& e) {
     THROW_ERROR("casadi_solver", e.what());
   }
 }
class_name()
std::string casadi::SharedObject::class_name () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_au
Definition at line 31 of file shared_object.cpp.
{
     return (*this)->class_name();
   }
Referenced by casadi::FmuFunction::check_mem_count(), casadi::MXFunction::export_code_body(), and casadi::BlazingSplineFunction::merge().
constraints()
std::vector< MX > casadi::OptiAdvanced::constraints () const
Definition at line 715 of file optistack.cpp.
{
   try {
     return (*this)->constraints();
   } catch(std::exception& e) {
     THROW_ERROR("constraints", e.what());
   }
 }
copy()
Opti casadi::Opti::copy () const inherited
The copy is effectively a deep copy: Updating the state of the copy does not update the original.
Extra doc: https://github.com/casadi/casadi/wiki/L_1n
Definition at line 853 of file optistack.cpp.
                       {
   return (*this)->copy();
 }
References casadi::OptiNode::copy().
Referenced by casadi::Opti::advanced(), and casadi::Opti::debug().
count_down()
void casadi::GenericShared< SharedObject , SharedObjectInternal >::count_down protected inherited
Definition at line 133 of file generic_shared_impl.hpp.
{
 #ifdef WITH_EXTRA_CHECKS
     casadi_assert_dev(Function::call_depth_==0);
 #endif // WITH_EXTRA_CHECKS
     if (!node) return;
     if (node->weak_ref_) {
 #ifdef CASADI_WITH_THREADSAFE_SYMBOLICS
       auto mutex = node->weak_ref_->get_mutex();
       // Avoid triggering a delete while a weak_ref.shared_if_alive is being called
       std::lock_guard<std::mutex> lock(*mutex);
       // Could it be that this mutex is destroyed when the lock goes out of scope?
 #endif // CASADI_WITH_THREADSAFE_SYMBOLICS
       if (--static_cast<Internal*>(node)->count == 0) {
         delete node;
         node = nullptr;
       }
     } else {
       if (--static_cast<Internal*>(node)->count == 0) {
         delete node;
         node = nullptr;
       }
     }
   }
count_up()
void casadi::GenericShared< SharedObject , SharedObjectInternal >::count_up protected inherited
Definition at line 132 of file generic_shared_impl.hpp.
{
 #ifdef WITH_EXTRA_CHECKS
     casadi_assert_dev(Function::call_depth_==0);
 #endif // WITH_EXTRA_CHECKS
     if (node) static_cast<Internal*>(node)->count++;
   }
create()
Opti casadi::Opti::create (OptiNode * node) static inherited
Definition at line 86 of file optistack.cpp.
{
   return Opti(node);
 }
References casadi::Opti::Opti().
Referenced by casadi::OptiNode::copy().
debug()
OptiAdvanced casadi::Opti::debug () const inherited
You get access to more methods, but you have no guarantees about API stability
The copy is effectively a deep copy: Updating the state of the copy does not update the original.
Extra doc: https://github.com/casadi/casadi/wiki/L_1l
Definition at line 847 of file optistack.cpp.
{
   return copy();
 }
References casadi::Opti::copy().
Referenced by casadi::Opti::disp().
debug_repr()
std::string casadi::GenericShared< SharedObject , SharedObjectInternal >::debug_repr inherited
Definition at line 112 of file generic_shared_impl.hpp.
{
     if (node) {
         return node->debug_repr(node);
     } else {
         return "NULL";
     }
   }
describe()
std::string casadi::OptiAdvanced::describe (const MX & x, casadi_index indent = 0, const Dict & opts = Dict()) const
Definition at line 659 of file optistack.cpp.
{
   try {
     return (*this)->describe(x, indent, opts);
   } catch(std::exception& e) {
     THROW_ERROR("describe", e.what());
   }
 }
References casadi::Opti::x().
Referenced by casadi::OptiNode::describe().
disp()
void casadi::Opti::disp (std::ostream & stream, bool more = false) const inherited
Definition at line 750 of file optistack.cpp.
{
   stream << "Opti {" << std::endl;
   OptiAdvanced mycopy = debug();
   stream << "  instance #" << mycopy.instance_number() << std::endl;
   if (mycopy.problem_dirty()) mycopy.bake();
   stream << "  #variables: " << mycopy.active_symvar(OPTI_VAR).size()
     << " (nx = " << mycopy.nx() << ")" <<  std::endl;
   stream << "  #parameters: " << mycopy.active_symvar(OPTI_PAR).size()
     << " (np = " << mycopy.np() << ")" << std::endl;
   stream << "  #constraints: " << mycopy.active_symvar(OPTI_DUAL_G).size()
     << " (ng = " << mycopy.ng() << ")" << std::endl;
   if (mycopy.solver_dirty()) {
     stream << "  CasADi solver needs updating." << std::endl;
   } else {
     stream << "  CasADi solver allocated." << std::endl;
   }
   if (mycopy.solved()) {
     stream << "  CasADi solver was called: " << mycopy.return_status() << std::endl;
   }
   stream << "}";
 }
References active_symvar(), bake(), casadi::Opti::debug(), instance_number(), casadi::Opti::ng(), casadi::Opti::np(), casadi::Opti::nx(), casadi::OPTI_DUAL_G, casadi::OPTI_PAR, casadi::OPTI_VAR, problem_dirty(), casadi::Opti::return_status(), solved(), and solver_dirty().
Referenced by casadi::OptiSol::disp(), and casadi::Opti::get_str().
dual()
MX casadi::Opti::dual (const MX & m) const inherited
m must be a constraint expression. The returned value is still a symbolic expression. Use value on it to obtain the numerical value.
Extra doc: https://github.com/casadi/casadi/wiki/L_1h
Definition at line 302 of file optistack.cpp.
{
   try {
     return (*this)->dual(m);
   } catch(std::exception& e) {
     THROW_ERROR("dual", e.what());
   }
 }
f()
MX casadi::Opti::f () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_26e
Definition at line 358 of file optistack.cpp.
                  {
   try {
     return (*this)->f();
   } catch(std::exception& e) {
     THROW_ERROR("f", e.what());
   }
 }
Referenced by casadi::Opti::minimize(), and objective().
f_linear_scale()
double casadi::Opti::f_linear_scale () const inherited
Definition at line 415 of file optistack.cpp.
{
   try {
     return (*this)->f_linear_scale();
   } catch(std::exception& e) {
     THROW_ERROR("f_linear_scale", e.what());
   }
 }
g()
MX casadi::Opti::g () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_26d
Definition at line 350 of file optistack.cpp.
                  {
   try {
     return (*this)->g();
   } catch(std::exception& e) {
     THROW_ERROR("g", e.what());
   }
 }
Referenced by casadi::Opti::subject_to().
g_describe()
std::string casadi::OptiAdvanced::g_describe (casadi_index i, const Dict & opts = Dict()) const
Definition at line 652 of file optistack.cpp.
{
   try {
     return (*this)->g_describe(i, opts);
   } catch(std::exception& e) {
     THROW_ERROR("g_describe", e.what());
   }
 }
Referenced by casadi::OptiNode::g_describe().
g_index_reduce_g()
casadi_int casadi::OptiAdvanced::g_index_reduce_g (casadi_index i) const
Definition at line 613 of file optistack.cpp.
{
   try {
     return (*this)->g_index_reduce_g(i);
   } catch(std::exception& e) {
     THROW_ERROR("g_index_reduce_g", e.what());
   }
 }
g_index_reduce_x()
casadi_int casadi::OptiAdvanced::g_index_reduce_x (casadi_index i) const
Definition at line 621 of file optistack.cpp.
{
   try {
     return (*this)->g_index_reduce_x(i);
   } catch(std::exception& e) {
     THROW_ERROR("g_index_reduce_x", e.what());
   }
 }
g_index_unreduce_g()
casadi_int casadi::OptiAdvanced::g_index_unreduce_g (casadi_index i) const
Definition at line 629 of file optistack.cpp.
{
   try {
     return (*this)->g_index_unreduce_g(i);
   } catch(std::exception& e) {
     THROW_ERROR("g_index_unreduce_g", e.what());
   }
 }
g_linear_scale()
DM casadi::Opti::g_linear_scale () const inherited
Definition at line 407 of file optistack.cpp.
{
   try {
     return (*this)->g_linear_scale();
   } catch(std::exception& e) {
     THROW_ERROR("g_linear_scale", e.what());
   }
 }
g_lookup()
MX casadi::OptiAdvanced::g_lookup (casadi_index i) const
Definition at line 637 of file optistack.cpp.
{
   try {
     return (*this)->g_lookup(i);
   } catch(std::exception& e) {
     THROW_ERROR("g_lookup", e.what());
   }
 }
Referenced by casadi::OptiNode::g_lookup().
get()
SharedObjectInternal * casadi::GenericShared< SharedObject , SharedObjectInternal >::get inherited
Definition at line 99 of file generic_shared_impl.hpp.
{
     return node;
   }
get_meta()
MetaVar casadi::OptiAdvanced::get_meta (const MX & m) const
Definition at line 548 of file optistack.cpp.
{
   try {
     return (*this)->get_meta(m);
   } catch(std::exception& e) {
     THROW_ERROR("get_meta", e.what());
   }
 }
get_meta_con()
MetaCon casadi::OptiAdvanced::get_meta_con (const MX & m) const
Definition at line 556 of file optistack.cpp.
{
   try {
     return (*this)->get_meta_con(m);
   } catch(std::exception& e) {
     THROW_ERROR("get_meta_con", e.what());
   }
 }
get_str()
std::string casadi::Opti::get_str (bool more = false) const inherited
Definition at line 772 of file optistack.cpp.
{
     std::stringstream ss;
     disp(ss, more);
     return ss.str();
 }
References casadi::Opti::disp().
Referenced by casadi::OptiSol::get_str().
getCount()
casadi_int casadi::GenericShared< SharedObject , SharedObjectInternal >::getCount inherited
Definition at line 102 of file generic_shared_impl.hpp.
{
     return (*this)->getCount();
   }
initial()
std::vector< MX > casadi::Opti::initial () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_266
Definition at line 278 of file optistack.cpp.
{
   try {
     return (*this)->initial();
   } catch(std::exception& e) {
     THROW_ERROR("initial", e.what());
   }
 }
instance_number()
casadi_int casadi::OptiAdvanced::instance_number () const
Definition at line 742 of file optistack.cpp.
{
   try {
     return (*this)->instance_number();
   } catch(std::exception& e) {
     THROW_ERROR("instance_number", e.what());
   }
 }
Referenced by casadi::Opti::disp().
is_null()
bool casadi::GenericShared< SharedObject , SharedObjectInternal >::is_null inherited
Definition at line 116 of file generic_shared_impl.hpp.
{
     return node==nullptr;
   }
is_parametric()
bool casadi::OptiAdvanced::is_parametric (const MX & expr) const
Definition at line 508 of file optistack.cpp.
{
   try {
     return (*this)->is_parametric(expr);
   } catch(std::exception& e) {
     THROW_ERROR("is_parametric", e.what());
   }
 }
lam_g()
MX casadi::Opti::lam_g () const inherited
Useful for obtaining the Lagrange Hessian:
* sol.value(hessian(opti.f+opti.lam_g'*opti.g,opti.x)) % MATLAB
* sol.value(hessian(opti.f+dot(opti.lam_g,opti.g),opti.x)[0]) # Python
*
Extra doc: https://github.com/casadi/casadi/wiki/L_1i
Definition at line 383 of file optistack.cpp.
                      {
   try {
     return (*this)->lam_g();
   } catch(std::exception& e) {
     THROW_ERROR("lam_g", e.what());
   }
 }
lbg()
MX casadi::Opti::lbg () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_26f
Definition at line 366 of file optistack.cpp.
                    {
   try {
     return (*this)->lbg();
   } catch(std::exception& e) {
     THROW_ERROR("lbg", e.what());
   }
 }
mark_problem_dirty()
void casadi::OptiAdvanced::mark_problem_dirty (bool flag = true)
Definition at line 786 of file optistack.cpp.
{
   try {
     (*this)->mark_problem_dirty(flag);
   } catch(std::exception& e) {
     THROW_ERROR("mark_problem_dirty", e.what());
   }
 }
mark_solved()
void casadi::OptiAdvanced::mark_solved (bool flag = true)
Definition at line 816 of file optistack.cpp.
{
   try {
     (*this)->mark_solved(flag);
   } catch(std::exception& e) {
     THROW_ERROR("mark_solved", e.what());
   }
 }
mark_solver_dirty()
void casadi::OptiAdvanced::mark_solver_dirty (bool flag = true)
Definition at line 801 of file optistack.cpp.
{
   try {
     (*this)->mark_solver_dirty(flag);
   } catch(std::exception& e) {
     THROW_ERROR("mark_solver_dirty", e.what());
   }
 }
minimize()
void casadi::Opti::minimize (const MX & f, double linear_scale = 1) inherited
Objective must be a scalar. Default objective: 0 When method is called multiple times, the last call takes effect
Extra doc: https://github.com/casadi/casadi/wiki/L_1a
Definition at line 114 of file optistack.cpp.
{
   try {
     (*this)->minimize(f, linear_scale);
   } catch(std::exception& e) {
     THROW_ERROR("minimize", e.what());
   }
 }
References casadi::Opti::f().
ng()
casadi_int casadi::Opti::ng () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_26a
Definition at line 326 of file optistack.cpp.
{
   try {
     return (*this)->ng();
   } catch(std::exception& e) {
     THROW_ERROR("ng", e.what());
   }
 }
Referenced by casadi::Opti::disp().
np()
casadi_int casadi::Opti::np () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_269
Definition at line 318 of file optistack.cpp.
{
   try {
     return (*this)->np();
   } catch(std::exception& e) {
     THROW_ERROR("nx", e.what());
   }
 }
Referenced by casadi::Opti::disp().
nx()
casadi_int casadi::Opti::nx () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_268
Definition at line 310 of file optistack.cpp.
{
   try {
     return (*this)->nx();
   } catch(std::exception& e) {
     THROW_ERROR("nx", e.what());
   }
 }
Referenced by casadi::Opti::disp().
objective()
MX casadi::OptiAdvanced::objective () const
Definition at line 722 of file optistack.cpp.
{
   return f();
 }
References casadi::Opti::f().
operator->() [1/2]
OptiNode * casadi::Opti::operator-> () inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1r
Definition at line 38 of file optistack.cpp.
{
   return static_cast<OptiNode*>(SharedObject::operator->());
 }
References casadi::GenericShared< SharedObject, SharedObjectInternal >::operator->().
operator->() [2/2]
const OptiNode * casadi::Opti::operator-> () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1s
Definition at line 42 of file optistack.cpp.
{
   return static_cast<const OptiNode*>(SharedObject::operator->());
 }
References casadi::GenericShared< SharedObject, SharedObjectInternal >::operator->().
own()
void casadi::GenericShared< SharedObject , SharedObjectInternal >::own (Internal * node) inherited
Assign the node to a node class pointer (or null)
Definition at line 89 of file generic_shared_impl.hpp.
{
     count_down();
     node = node_;
     count_up();
   }
p()
MX casadi::Opti::p () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_26c
Definition at line 342 of file optistack.cpp.
                  {
   try {
     return (*this)->p();
   } catch(std::exception& e) {
     THROW_ERROR("p", e.what());
   }
 }
parameter() [1/3]
MX casadi::Opti::parameter (casadi_int n = 1, casadi_int m = 1, const std::string & attribute = "full") inherited
The order of creation does not matter. It is not required for parameter to actualy appear in the optimization problem. Parameters that do appear, must be given a value before the problem can be solved.
Parameters
[in] n number of rows (default 1)
[in] m number of columnss (default 1)
[in] attribute 'full' (default) or 'symmetric'
Extra doc: https://github.com/casadi/casadi/wiki/L_19
Definition at line 90 of file optistack.cpp.
{
   try {
     return (*this)->parameter(n, m, attribute);
   } catch(std::exception& e) {
     THROW_ERROR("parameter", e.what());
   }
 }
parameter() [2/3]
MX casadi::Opti::parameter (const MX & symbol, const std::string & attribute = "full") inherited
Definition at line 106 of file optistack.cpp.
{
   try {
     return (*this)->parameter(symbol, attribute);
   } catch(std::exception& e) {
     THROW_ERROR("parameter", e.what());
   }
 }
parameter() [3/3]
MX casadi::Opti::parameter (const Sparsity & sp, const std::string & attribute = "full") inherited
Definition at line 98 of file optistack.cpp.
{
   try {
     return (*this)->parameter(sp, attribute);
   } catch(std::exception& e) {
     THROW_ERROR("parameter", e.what());
   }
 }
print_ptr()
void casadi::SharedObject::print_ptr (std::ostream & stream = casadi::uout()) const inherited
Print the pointer to the internal class
Definition at line 43 of file shared_object.cpp.
{
     stream << get();
   }
References casadi::GenericShared< SharedObject, SharedObjectInternal >::get().
problem_dirty()
bool casadi::OptiAdvanced::problem_dirty () const
Definition at line 793 of file optistack.cpp.
{
   try {
     return (*this)->problem_dirty();
   } catch(std::exception& e) {
     THROW_ERROR("problem_dirty", e.what());
   }
 }
Referenced by casadi::OptiNode::baked_copy(), and casadi::Opti::disp().
res() [1/2]
DMDict casadi::OptiAdvanced::res () const
Definition at line 707 of file optistack.cpp.
{
   try {
     return (*this)->res();
   } catch(std::exception& e) {
     THROW_ERROR("res", e.what());
   }
 }
Referenced by res().
res() [2/2]
void casadi::OptiAdvanced::res (const DMDict & res)
Definition at line 699 of file optistack.cpp.
{
   try {
     return (*this)->res(res);
   } catch(std::exception& e) {
     THROW_ERROR("res", e.what());
   }
 }
References res().
return_status()
std::string casadi::Opti::return_status () const inherited
   passed as-is from nlpsol
No stability can be guaranteed about this part of the API
Extra doc: https://github.com/casadi/casadi/wiki/L_1g
Definition at line 270 of file optistack.cpp.
{
   try {
     return (*this)->return_status();
   } catch(std::exception& e) {
     THROW_ERROR("return_status", e.what());
   }
 }
Referenced by casadi::Opti::disp().
scale_helper()
Function casadi::Opti::scale_helper (const Function & h) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_2ci
Definition at line 254 of file optistack.cpp.
{
   try {
     return (*this)->scale_helper(h);
   } catch(std::exception& e) {
     THROW_ERROR("scale_helper", e.what());
   }
 }
Referenced by casadi::OptiNode::scale_helper().
set_domain()
void casadi::Opti::set_domain (const MX & x, const std::string & domain) inherited
Parameters
[in] x decision variable
[in] type 'real', 'integer' (default: real)
* opti.set_domain(x, "real")
* opti.set_domain(x, "integer")
*
Extra doc: https://github.com/casadi/casadi/wiki/L_27t
Definition at line 189 of file optistack.cpp.
{
   try {
     (*this)->set_domain(x, domain);
   } catch(std::exception& e) {
     THROW_ERROR("set_domain", e.what());
   }
 }
References casadi::Opti::x().
set_initial() [1/2]
void casadi::Opti::set_initial (const MX & x, const DM & v) inherited
Set initial guess for decision variables
* opti.set_initial(x, 2)
* opti.set_initial(10*x(1), 2)
*
Definition at line 165 of file optistack.cpp.
{
   try {
     (*this)->set_initial(x, v);
   } catch(std::exception& e) {
     THROW_ERROR("set_initial", e.what());
   }
 }
References casadi::Opti::x().
set_initial() [2/2]
void casadi::Opti::set_initial (const std::vector< MX > & assignments) inherited
Set initial guess for decision variables
* opti.set_initial(x, 2)
* opti.set_initial(10*x(1), 2)
*
Definition at line 172 of file optistack.cpp.
{
   try {
     (*this)->set_initial(assignments);
   } catch(std::exception& e) {
     THROW_ERROR("set_initial", e.what());
   }
 }
set_linear_scale()
void casadi::Opti::set_linear_scale (const MX & x, const DM & scale, const DM & offset = 0) inherited
(x-offset)/scale will be used in the optimization problem
Parameters
[in] x decision variable
[in] scale scaling value (default: 1)
[in] offset scaling value (default: 0)
* opti.set_linear_scale(x, 20)
* opti.set_linear_scale(x, 20, 273.15)
*
Extra doc: https://github.com/casadi/casadi/wiki/L_2bs
Definition at line 197 of file optistack.cpp.
{
   try {
     (*this)->set_linear_scale(x, scale, offset);
   } catch(std::exception& e) {
     THROW_ERROR("set_linear_scale", e.what());
   }
 }
References casadi::Opti::x().
set_meta()
void casadi::OptiAdvanced::set_meta (const MX & m, const MetaVar & meta)
Definition at line 564 of file optistack.cpp.
{
   try {
     (*this)->set_meta(m, meta);
   } catch(std::exception& e) {
     THROW_ERROR("set_meta", e.what());
   }
 }
set_meta_con()
void casadi::OptiAdvanced::set_meta_con (const MX & m, const MetaCon & meta)
Definition at line 572 of file optistack.cpp.
{
   try {
     return (*this)->set_meta_con(m, meta);
   } catch(std::exception& e) {
     THROW_ERROR("set_meta_con", e.what());
   }
 }
set_value() [1/2]
void casadi::Opti::set_value (const MX & x, const DM & v) inherited
Each parameter must be given a value before 'solve' can be called
Extra doc: https://github.com/casadi/casadi/wiki/L_1d
Definition at line 181 of file optistack.cpp.
{
   try {
     (*this)->set_value(x, v);
   } catch(std::exception& e) {
     THROW_ERROR("set_value", e.what());
   }
 }
References casadi::Opti::x().
set_value() [2/2]
void casadi::Opti::set_value (const std::vector< MX > & assignments) inherited
Each parameter must be given a value before 'solve' can be called
Extra doc: https://github.com/casadi/casadi/wiki/L_1d
Definition at line 205 of file optistack.cpp.
{
   try {
     (*this)->set_value(assignments);
   } catch(std::exception& e) {
     THROW_ERROR("set_value", e.what());
   }
 }
show_infeasibilities()
void casadi::OptiAdvanced::show_infeasibilities (double tol = 0, const Dict & opts = Dict()) const
Definition at line 667 of file optistack.cpp.
{
   try {
     (*this)->show_infeasibilities(tol, opts);
   } catch(std::exception& e) {
     THROW_ERROR("show_infeasibilities", e.what());
   }
 }
solve()
OptiSol casadi::Opti::solve () inherited
Definition at line 213 of file optistack.cpp.
                     {
   try {
     return (*this)->solve(false);
   } catch(std::exception& e) {
     THROW_ERROR("solve", e.what());
   }
 }
solve_actual()
DMDict casadi::OptiAdvanced::solve_actual (const DMDict & args)
Definition at line 682 of file optistack.cpp.
{
   try {
     return (*this)->solve_actual(args);
   } catch(std::exception& e) {
     THROW_ERROR("solve_actual", e.what());
   }
 }
solve_limited()
OptiSol casadi::Opti::solve_limited () inherited
Allows the solver to return without error when an iteration or time limit is reached
Extra doc: https://github.com/casadi/casadi/wiki/L_1e
Definition at line 221 of file optistack.cpp.
{
   try {
     return (*this)->solve(true);
   } catch(std::exception& e) {
     THROW_ERROR("solve", e.what());
   }
 }
solve_prepare()
void casadi::OptiAdvanced::solve_prepare ()
Definition at line 675 of file optistack.cpp.
{
   try {
     (*this)->solve_prepare();
   } catch(std::exception& e) {
     THROW_ERROR("solve_prepare", e.what());
   }
 }
solved()
bool casadi::OptiAdvanced::solved () const
Definition at line 824 of file optistack.cpp.
{
   try {
     return (*this)->solved();
   } catch(std::exception& e) {
     THROW_ERROR("solved", e.what());
   }
 }
Referenced by casadi::Opti::disp().
solver()
void casadi::Opti::solver (const std::string & solver, const Dict & plugin_options = Dict(), const Dict & solver_options = Dict()) inherited
Parameters
[in] solver any of the nlpsol plugins can be used here In practice, not all nlpsol plugins may be supported yet
[in] options passed on to nlpsol plugin No stability can be guaranteed about this part of the API
[in] options to be passed to nlpsol solver No stability can be guaranteed about this part of the API
Extra doc: https://github.com/casadi/casadi/wiki/L_1c
Definition at line 155 of file optistack.cpp.
{
   try {
     (*this)->solver(solver, plugin_options, solver_options);
   } catch(std::exception& e) {
     THROW_ERROR("solver", e.what());
   }
 }
solver_dirty()
bool casadi::OptiAdvanced::solver_dirty () const
Definition at line 808 of file optistack.cpp.
{
   try {
     return (*this)->solver_dirty();
   } catch(std::exception& e) {
     THROW_ERROR("solver_dirty", e.what());
   }
 }
Referenced by casadi::Opti::disp().
stats()
Dict casadi::Opti::stats () const inherited
nlpsol stats are passed as-is. No stability can be guaranteed about this part of the API
Extra doc: https://github.com/casadi/casadi/wiki/L_1f
Definition at line 262 of file optistack.cpp.
{
   try {
     return (*this)->stats();
   } catch(std::exception& e) {
     THROW_ERROR("stats", e.what());
   }
 }
Referenced by casadi::OptiSol::stats().
subject_to() [1/5]
void casadi::Opti::subject_to () inherited
Definition at line 146 of file optistack.cpp.
                       {
   try {
     (*this)->subject_to();
   } catch(std::exception& e) {
     THROW_ERROR("subject_to", e.what());
   }
 }
Referenced by casadi::Opti::subject_to().
subject_to() [2/5]
void casadi::Opti::subject_to (const MX & g, const Dict & options = Dict()) inherited
Examples:
* \begin{itemize}
* opti.subject_to(sqrt(x+y) >= 1);
* opti.subject_to(sqrt(x+y) > 1)}: same as above
* opti.subject_to(1<= sqrt(x+y))}: same as above
* opti.subject_to(5*x+y==1)}: equality
*
* Python
* opti.subject_to([x*y>=1,x==3])
* opti.subject_to(opti.bounded(0,x,1))
*
* MATLAB
* opti.subject_to({x*y>=1,x==3})
* opti.subject_to(0<=x<=1)
*
Related functionalities:
opti.lbg,opti.g,opti.ubg represent the vector of flattened constraints
opti.debug.show_infeasibilities() may be used to inspect which constraints are violated
Extra doc: https://github.com/casadi/casadi/wiki/L_1b
Definition at line 122 of file optistack.cpp.
{
   try {
     (*this)->subject_to(g, 1, options);
   } catch(std::exception& e) {
     THROW_ERROR("subject_to", e.what());
   }
 }
References casadi::Opti::g().
subject_to() [3/5]
void casadi::Opti::subject_to (const MX & g, const DM & linear_scale, const Dict & options = Dict()) inherited
Examples:
* \begin{itemize}
* opti.subject_to(sqrt(x+y) >= 1);
* opti.subject_to(sqrt(x+y) > 1)}: same as above
* opti.subject_to(1<= sqrt(x+y))}: same as above
* opti.subject_to(5*x+y==1)}: equality
*
* Python
* opti.subject_to([x*y>=1,x==3])
* opti.subject_to(opti.bounded(0,x,1))
*
* MATLAB
* opti.subject_to({x*y>=1,x==3})
* opti.subject_to(0<=x<=1)
*
Related functionalities:
opti.lbg,opti.g,opti.ubg represent the vector of flattened constraints
opti.debug.show_infeasibilities() may be used to inspect which constraints are violated
Extra doc: https://github.com/casadi/casadi/wiki/L_1b
Definition at line 134 of file optistack.cpp.
{
   try {
     (*this)->subject_to(g, linear_scale, options);
   } catch(std::exception& e) {
     THROW_ERROR("subject_to", e.what());
   }
 }
References casadi::Opti::g().
subject_to() [4/5]
void casadi::Opti::subject_to (const std::vector< MX > & g, const Dict & options = Dict()) inherited
Examples:
* \begin{itemize}
* opti.subject_to(sqrt(x+y) >= 1);
* opti.subject_to(sqrt(x+y) > 1)}: same as above
* opti.subject_to(1<= sqrt(x+y))}: same as above
* opti.subject_to(5*x+y==1)}: equality
*
* Python
* opti.subject_to([x*y>=1,x==3])
* opti.subject_to(opti.bounded(0,x,1))
*
* MATLAB
* opti.subject_to({x*y>=1,x==3})
* opti.subject_to(0<=x<=1)
*
Related functionalities:
opti.lbg,opti.g,opti.ubg represent the vector of flattened constraints
opti.debug.show_infeasibilities() may be used to inspect which constraints are violated
Extra doc: https://github.com/casadi/casadi/wiki/L_1b
Definition at line 130 of file optistack.cpp.
{
   for (const auto& gs : g) subject_to(gs, 1, options);
 }
References casadi::Opti::g(), and casadi::Opti::subject_to().
subject_to() [5/5]
void casadi::Opti::subject_to (const std::vector< MX > & g, const DM & linear_scale, const Dict & options = Dict()) inherited
Examples:
* \begin{itemize}
* opti.subject_to(sqrt(x+y) >= 1);
* opti.subject_to(sqrt(x+y) > 1)}: same as above
* opti.subject_to(1<= sqrt(x+y))}: same as above
* opti.subject_to(5*x+y==1)}: equality
*
* Python
* opti.subject_to([x*y>=1,x==3])
* opti.subject_to(opti.bounded(0,x,1))
*
* MATLAB
* opti.subject_to({x*y>=1,x==3})
* opti.subject_to(0<=x<=1)
*
Related functionalities:
opti.lbg,opti.g,opti.ubg represent the vector of flattened constraints
opti.debug.show_infeasibilities() may be used to inspect which constraints are violated
Extra doc: https://github.com/casadi/casadi/wiki/L_1b
Definition at line 142 of file optistack.cpp.
{
   for (const auto& gs : g) subject_to(gs, linear_scale, options);
 }
References casadi::Opti::g(), and casadi::Opti::subject_to().
swap()
void casadi::GenericShared< SharedObject , SharedObjectInternal >::swap (GenericShared< SharedObject, SharedObjectInternal > & other) inherited
Definition at line 105 of file generic_shared_impl.hpp.
{
     GenericShared<Shared, Internal> temp = *this;
     *this = other;
     other = temp;
   }
symvar() [1/3]
std::vector< MX > casadi::OptiAdvanced::symvar () const
Returned vector is ordered according to the order of variable()/parameter() calls used to create the variables
Extra doc: https://github.com/casadi/casadi/wiki/L_1u
Definition at line 516 of file optistack.cpp.
{
   try {
     return (*this)->symvar();
   } catch(std::exception& e) {
     THROW_ERROR("symvar", e.what());
   }
 }
symvar() [2/3]
std::vector< MX > casadi::OptiAdvanced::symvar (const MX & expr) const
Returned vector is ordered according to the order of variable()/parameter() calls used to create the variables
Extra doc: https://github.com/casadi/casadi/wiki/L_1u
Definition at line 524 of file optistack.cpp.
{
   try {
     return (*this)->symvar(expr);
   } catch(std::exception& e) {
     THROW_ERROR("symvar", e.what());
   }
 }
symvar() [3/3]
std::vector< MX > casadi::OptiAdvanced::symvar (const MX & expr, VariableType type) const
Returned vector is ordered according to the order of variable()/parameter() calls used to create the variables
Extra doc: https://github.com/casadi/casadi/wiki/L_1u
Definition at line 532 of file optistack.cpp.
{
   try {
     return (*this)->symvar(expr, type);
   } catch(std::exception& e) {
     THROW_ERROR("symvar", e.what());
   }
 }
to_function() [1/3]
Function casadi::Opti::to_function (const std::string & name, const std::map< std::string, MX > & dict, const std::vector< std::string > & name_in, const std::vector< std::string > & name_out, const Dict & opts = Dict()) inherited
Parameters
[in] name Name of the resulting CasADi Function
[in] args List of parameters and decision/dual variables (which can be given an initial guess) with the resulting Function
[in] res List of expressions that will get evaluated at the optimal solution
[in] opts Standard CasADi Funcion options
Extra doc: https://github.com/casadi/casadi/wiki/L_1j
Definition at line 441 of file optistack.cpp.
                       {
   std::vector<MX> ex_in(name_in.size()), ex_out(name_out.size());
   for (auto&& i : dict) {
     std::vector<std::string>::const_iterator it;
     if ((it=find(name_in.begin(), name_in.end(), i.first))!=name_in.end()) {
       // Input expression
       ex_in[it-name_in.begin()] = i.second;
     } else if ((it=find(name_out.begin(), name_out.end(), i.first))!=name_out.end()) {
       // Output expression
       ex_out[it-name_out.begin()] = i.second;
     } else {
       // Neither
       casadi_error("Unknown dictionary entry: '" + i.first + "'");
     }
   }
   return to_function(name, ex_in, ex_out, name_in, name_out, opts);
 }
References casadi::find(), and casadi::Opti::to_function().
to_function() [2/3]
Function casadi::Opti::to_function (const std::string & name, const std::vector< MX > & args, const std::vector< MX > & res, const Dict & opts = Dict()) inherited
Parameters
[in] name Name of the resulting CasADi Function
[in] args List of parameters and decision/dual variables (which can be given an initial guess) with the resulting Function
[in] res List of expressions that will get evaluated at the optimal solution
[in] opts Standard CasADi Funcion options
Extra doc: https://github.com/casadi/casadi/wiki/L_1j
Definition at line 435 of file optistack.cpp.
                       {
   return to_function(name, args, res, {}, {}, opts);
 }
Referenced by casadi::Opti::to_function(), and casadi::OptiNode::to_function().
to_function() [3/3]
Function casadi::Opti::to_function (const std::string & name, const std::vector< MX > & args, const std::vector< MX > & res, const std::vector< std::string > & name_in, const std::vector< std::string > & name_out, const Dict & opts = Dict()) inherited
Parameters
[in] name Name of the resulting CasADi Function
[in] args List of parameters and decision/dual variables (which can be given an initial guess) with the resulting Function
[in] res List of expressions that will get evaluated at the optimal solution
[in] opts Standard CasADi Funcion options
Extra doc: https://github.com/casadi/casadi/wiki/L_1j
Definition at line 423 of file optistack.cpp.
                       {
   try {
     return (*this)->to_function(name, args, res, name_in, name_out, opts);
   } catch(std::exception& e) {
     THROW_ERROR("to_function", e.what());
   }
 }
type_name()
std::string casadi::Opti::type_name () const inline inherited
Definition at line 440 of file optistack.hpp.
 { return "Opti"; }
ubg()
MX casadi::Opti::ubg () const inherited
Definition at line 374 of file optistack.cpp.
                    {
   try {
     return (*this)->ubg();
   } catch(std::exception& e) {
     THROW_ERROR("ubg", e.what());
   }
 }
update_user_dict() [1/2]
void casadi::Opti::update_user_dict (const MX & m, const Dict & meta) inherited
Add arbitrary data in the form of a dictionary to symbols or constraints
Extra doc: https://github.com/casadi/casadi/wiki/L_1o
Definition at line 479 of file optistack.cpp.
{
   try {
     (*this)->update_user_dict(m, meta);
   } catch(std::exception& e) {
     THROW_ERROR("update_user_dict", e.what());
   }
 }
Referenced by casadi::Opti::update_user_dict().
update_user_dict() [2/2]
void casadi::Opti::update_user_dict (const std::vector< MX > & m, const Dict & meta) inherited
Definition at line 487 of file optistack.cpp.
{
   for (const auto& m : ms)
      update_user_dict(m, meta);
 }
References casadi::Opti::update_user_dict().
user_dict()
Dict casadi::Opti::user_dict (const MX & m) const inherited
Definition at line 492 of file optistack.cpp.
{
   try {
     return (*this)->user_dict(m);
   } catch(std::exception& e) {
     THROW_ERROR("user_dict", e.what());
   }
 }
value() [1/3]
DM casadi::Opti::value (const DM & x, const std::vector< MX > & values = std::vector<MX>()) const inherited
Parameters
[in] x decision variable
[in] type 'real', 'integer' (default: real)
* opti.set_domain(x, "real")
* opti.set_domain(x, "integer")
*
Extra doc: https://github.com/casadi/casadi/wiki/L_27t
Definition at line 238 of file optistack.cpp.
{
   try {
     return (*this)->value(x, values);
   } catch(std::exception& e) {
     THROW_ERROR("value", e.what());
   }
 }
References casadi::Opti::x().
value() [2/3]
DM casadi::Opti::value (const MX & x, const std::vector< MX > & values = std::vector<MX>()) const inherited
Obtain value of expression at the current value
In regular mode, teh current value is the converged solution In debug mode, the value can be non-converged
Parameters
[in] values Optional assignment expressions (e.g. x==3) to overrule the current value
Definition at line 229 of file optistack.cpp.
{
   try {
     return (*this)->value(x, values);
   } catch(std::exception& e) {
     THROW_ERROR("value", e.what());
   }
 }
References casadi::Opti::x().
Referenced by casadi::OptiSol::value().
value() [3/3]
DM casadi::Opti::value (const SX & x, const std::vector< MX > & values = std::vector<MX>()) const inherited
Parameters
[in] x decision variable
[in] type 'real', 'integer' (default: real)
* opti.set_domain(x, "real")
* opti.set_domain(x, "integer")
*
Extra doc: https://github.com/casadi/casadi/wiki/L_27t
Definition at line 246 of file optistack.cpp.
{
   try {
     return (*this)->value(x, values);
   } catch(std::exception& e) {
     THROW_ERROR("value", e.what());
   }
 }
References casadi::Opti::x().
value_parameters()
std::vector< MX > casadi::Opti::value_parameters () const inherited
Definition at line 294 of file optistack.cpp.
{
   try {
     return (*this)->value_parameters();
   } catch(std::exception& e) {
     THROW_ERROR("value_parameters", e.what());
   }
 }
Referenced by casadi::OptiSol::value_parameters().
value_variables()
std::vector< MX > casadi::Opti::value_variables () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_267
Definition at line 286 of file optistack.cpp.
{
   try {
     return (*this)->value_variables();
   } catch(std::exception& e) {
     THROW_ERROR("value_variables", e.what());
   }
 }
Referenced by casadi::OptiSol::value_variables().
variable() [1/3]
MX casadi::Opti::variable (casadi_int n = 1, casadi_int m = 1, const std::string & attribute = "full") inherited
The order of creation matters. The order will be reflected in the optimization problem. It is not required for decision variables to actualy appear in the optimization problem.
Parameters
[in] n number of rows (default 1)
[in] m number of columnss (default 1)
[in] attribute 'full' (default) or 'symmetric'
Extra doc: https://github.com/casadi/casadi/wiki/L_18
Definition at line 51 of file optistack.cpp.
{
   try {
     return (*this)->variable(n, m, attribute);
   } catch(std::exception& e) {
     THROW_ERROR("variable", e.what());
   }
 }
variable() [2/3]
MX casadi::Opti::variable (const MX & symbol, const std::string & attribute = "full") inherited
Definition at line 67 of file optistack.cpp.
{
   try {
     return (*this)->variable(symbol, attribute);
   } catch(std::exception& e) {
     THROW_ERROR("variable", e.what());
   }
 }
variable() [3/3]
MX casadi::Opti::variable (const Sparsity & sp, const std::string & attribute = "full") inherited
Definition at line 59 of file optistack.cpp.
{
   try {
     return (*this)->variable(sp, attribute);
   } catch(std::exception& e) {
     THROW_ERROR("variable", e.what());
   }
 }
weak()
GenericWeakRef< SharedObject , SharedObjectInternal > * casadi::GenericShared< SharedObject , SharedObjectInternal >::weak inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_aw
Definition at line 130 of file generic_shared_impl.hpp.
{
     return (*this)->weak();
   }
x()
MX casadi::Opti::x () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_26b
Definition at line 334 of file optistack.cpp.
                  {
   try {
     return (*this)->x();
   } catch(std::exception& e) {
     THROW_ERROR("x", e.what());
   }
 }
Referenced by describe(), casadi::Opti::set_domain(), casadi::Opti::set_initial(), casadi::Opti::set_linear_scale(), casadi::Opti::set_value(), and casadi::Opti::value().
x_describe()
std::string casadi::OptiAdvanced::x_describe (casadi_index i, const Dict & opts = Dict()) const
Definition at line 645 of file optistack.cpp.
{
   try {
     return (*this)->x_describe(i, opts);
   } catch(std::exception& e) {
     THROW_ERROR("x_describe", e.what());
   }
 }
Referenced by casadi::OptiNode::x_describe().
x_linear_scale()
DM casadi::Opti::x_linear_scale () const inherited
Definition at line 391 of file optistack.cpp.
{
   try {
     return (*this)->x_linear_scale();
   } catch(std::exception& e) {
     THROW_ERROR("x_linear_scale", e.what());
   }
 }
x_linear_scale_offset()
DM casadi::Opti::x_linear_scale_offset () const inherited
Definition at line 399 of file optistack.cpp.
{
   try {
     return (*this)->x_linear_scale_offset();
   } catch(std::exception& e) {
     THROW_ERROR("x_linear_scale_offset", e.what());
   }
 }
x_lookup()
MX casadi::OptiAdvanced::x_lookup (casadi_index i) const
Definition at line 605 of file optistack.cpp.
{
   try {
     return (*this)->x_lookup(i);
   } catch(std::exception& e) {
     THROW_ERROR("x_lookup", e.what());
   }
 }
Referenced by casadi::OptiNode::x_lookup().
Friends And Related Function Documentation
InternalOptiCallback
friend class InternalOptiCallback friend
Definition at line 552 of file optistack.hpp.
Member Data Documentation
problem_dirty_
bool casadi::OptiAdvanced::problem_dirty_
Definition at line 631 of file optistack.hpp.
solved_
bool casadi::OptiAdvanced::solved_
Definition at line 639 of file optistack.hpp.
solver_dirty_
bool casadi::OptiAdvanced::solver_dirty_
Definition at line 635 of file optistack.hpp.
The documentation for this class was generated from the following files:
optistack.hpp
optistack.cpp