CasADi: casadi::Linsol Class Reference
casadi::Linsol Class Reference
Linear solver.
#include <linsol.hpp>
Detailed Description
Create a solver for linear systems of equations Solves the linear system A*X = B or A^T*X = B for X with A square and non-singular
If A is structurally singular, an error will be thrown during init. If A is numerically singular, the prepare step will fail.
General information
List of plugins
- csparsecholesky
- csparse
- ma27
- lapacklu
- lapackqr
- mumps
- ldl
- qr
- tridiag
- symbolicqr
Note: some of the plugins in this list might not be available on your system. Also, there might be extra plugins available to you that are not listed here. You can obtain their documentation with Linsol.doc("myextraplugin")
csparsecholesky
Linsol with CSparseCholesky Interface
Extra doc: https://github.com/casadi/casadi/wiki/L_21u
csparse
Linsol with CSparse Interface
Extra doc: https://github.com/casadi/casadi/wiki/L_21t
ma27
Interface to the sparse direct linear solver MA27 Works for symmetric indefinite systems Partly adopted from qpOASES 3.2
Author
Joel Andersson
Date
2016
Extra doc: https://github.com/casadi/casadi/wiki/L_229
lapacklu
This class solves the linear system A.x=b by making an LU factorization of A:
A = L.U, with L lower and U upper triangular
Extra doc: https://github.com/casadi/casadi/wiki/L_22h
List of available options
Id Type Description
allow_equilibration_failure OT_BOOL Non-fatal error when equilibration fails
equilibration OT_BOOL Equilibrate the matrix
lapackqr
This class solves the linear system A.x=b by making an QR factorization of A:
A = Q.R, with Q orthogonal and R upper triangular
Extra doc: https://github.com/casadi/casadi/wiki/L_22g
List of available options
Id Type Description
max_nrhs OT_INT Maximum number of right-hand-sides that get processed in a single pass [default:10].
mumps
Interface to the sparse direct linear solver MUMPS Works for symmetric indefinite systems
Author
Joel Andersson
Date
2019
Extra doc: https://github.com/casadi/casadi/wiki/L_22t
List of available options
Id Type Description
posdef OT_BOOL Positive definite
symmetric OT_BOOL Symmetric matrix
ldl
Linear solver using sparse direct LDL factorization
Extra doc: https://github.com/casadi/casadi/wiki/L_233
qr
Linear solver using sparse direct QR factorization
Extra doc: https://github.com/casadi/casadi/wiki/L_22z
tridiag
Linear solver for tridiagonal matrices
Extra doc: https://github.com/casadi/casadi/wiki/L_22v
symbolicqr
Linear solver for sparse least-squares problems Inspired from https://github.com/scipy/scipy/blob/v0.14.0/scipy/sparse/linalg/isolve/lsqr.py#L96
Extra doc: https://github.com/casadi/casadi/wiki/L_230
Linsol based on QR factorization with sparsity pattern based reordering without partial pivoting
Extra doc: https://github.com/casadi/casadi/wiki/L_231
List of available options
Id Type Description
fopts OT_DICT Options to be passed to generated function objects
Author
Joel Andersson
Date
2011-2016
Extra doc: https://github.com/casadi/casadi/wiki/L_1kh
Definition at line 53 of file linsol.hpp.
Public Member Functions
Linsol ()
Default constructor.
Linsol (const std::string &name, const std::string &solver, const Sparsity &sp, const Dict &opts=Dict())
Constructor.
LinsolInternal * operator-> ()
Access functions of the node.
const LinsolInternal * operator-> () const
std::string plugin_name () const
Query plugin name.
const Sparsity & sparsity () const
Get linear system sparsity.
void sfact (const DM &A) const
Symbolic factorization of the linear system, e.g. selecting pivots.
void nfact (const DM &A) const
Numeric factorization of the linear system.
casadi_int neig (const DM &A) const
Number of negative eigenvalues.
casadi_int rank (const DM &A) const
Matrix rank.
Dict stats (int mem=1) const
Get all statistics obtained at the end of the last evaluate call.
casadi_int checkout () const
Checkout a memory object.
void release (int mem) const
Release a memory object.
void serialize (SerializingStream &s) const
Serialize an object.
void own (SharedObjectInternal *node)
void assign (SharedObjectInternal *node)
Assign the node to a node class pointer without reference counting.
SharedObjectInternal * get () const
Get a const pointer to the node.
casadi_int getCount () const
Get the reference count.
void swap (SharedObject &other)
Swap content with another instance.
std::string class_name () const
Get class name.
void disp (std::ostream &stream, bool more=false) const
Print a description of the object.
std::string get_str (bool more=false) const
Get string representation.
void print_ptr (std::ostream &stream=casadi::uout()) const
bool is_null () const
Is a null pointer?
casadi_int __hash__ () const
Returns a number that is unique for a given Node.
WeakRef * weak ()
Get a weak reference to the object.
DM solve (const DM &A, const DM &B, bool tr=false) const
MX solve (const MX &A, const MX &B, bool tr=false) const
int sfact (const double *A, int mem=0) const
int nfact (const double *A, int mem=0) const
int solve (const double *A, double *x, casadi_int nrhs=1, bool tr=false, int mem=0) const
casadi_int neig (const double *A, int mem=0) const
casadi_int rank (const double *A, int mem=0) const
Static Public Member Functions
static std::string type_name ()
Get type name.
static bool test_cast (const SharedObjectInternal *ptr)
Check if a particular cast is allowed.
static Linsol create (LinsolInternal *node)
Create from node.
static bool has_plugin (const std::string &name)
Check if a plugin is available.
static void load_plugin (const std::string &name)
Explicitly load a plugin dynamically.
static std::string doc (const std::string &name)
Get solver specific documentation.
static Linsol deserialize (DeserializingStream &s)
Deserialize with type disambiguation.
Protected Member Functions
void count_up ()
void count_down ()
Constructor & Destructor Documentation
Linsol() [1/2]
casadi::Linsol::Linsol ()
Definition at line 31 of file linsol.cpp.
                  {
   }
Linsol() [2/2]
casadi::Linsol::Linsol (const std::string & name, const std::string & solver, const Sparsity & sp, const Dict & opts = Dict()) explicit
Definition at line 34 of file linsol.cpp.
{
     own(LinsolInternal::getPlugin(solver).creator(name, sp));
     (*this)->construct(opts);
   }
References casadi::PluginInterface< LinsolInternal >::getPlugin(), and casadi::SharedObject::own().
Member Function Documentation
__hash__()
casadi_int casadi::SharedObject::__hash__ () const inherited
If the Object does not point to any node, "0" is returned.
Extra doc: https://github.com/casadi/casadi/wiki/L_av
Definition at line 129 of file shared_object.cpp.
{
     return reinterpret_cast<casadi_int>(get());
   }
References casadi::SharedObject::get().
assign()
void casadi::SharedObject::assign (SharedObjectInternal * node) inherited
improper use will cause memory leaks!
Extra doc: https://github.com/casadi/casadi/wiki/L_at
Definition at line 52 of file shared_object.cpp.
{
     node = node_;
   }
Referenced by casadi::GenericType::to_double_vector_vector().
checkout()
casadi_int casadi::Linsol::checkout () const
Definition at line 196 of file linsol.cpp.
{
     return (*this)->checkout();
   }
Referenced by casadi::SundialsInterface::init_mem(), and casadi::Ipqp::solve().
class_name()
std::string casadi::SharedObject::class_name () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_au
Definition at line 99 of file shared_object.cpp.
{
     return (*this)->class_name();
   }
Referenced by casadi::MXFunction::export_code_body().
count_down()
void casadi::SharedObject::count_down () protected inherited
Definition at line 84 of file shared_object.cpp.
{
 #ifdef WITH_EXTRA_CHECKS
     casadi_assert_dev(Function::call_depth_==0);
 #endif // WITH_EXTRA_CHECKS
     if (node && --node->count == 0) {
       delete node;
       node = nullptr;
     }
   }
Referenced by casadi::SharedObject::operator=(), casadi::SharedObject::own(), and casadi::SharedObject::~SharedObject().
count_up()
void casadi::SharedObject::count_up () protected inherited
Definition at line 77 of file shared_object.cpp.
{
 #ifdef WITH_EXTRA_CHECKS
     casadi_assert_dev(Function::call_depth_==0);
 #endif // WITH_EXTRA_CHECKS
     if (node) node->count++;
   }
Referenced by casadi::SharedObject::operator=(), casadi::SharedObject::own(), and casadi::SharedObject::SharedObject().
create()
Linsol casadi::Linsol::create (LinsolInternal * node) static
Extra doc: https://github.com/casadi/casadi/wiki/L_1kj
Definition at line 233 of file linsol.cpp.
{
     Linsol ret;
     ret.own(node);
     return ret;
   }
References casadi::SharedObject::own().
deserialize()
Linsol casadi::Linsol::deserialize (DeserializingStream & s) static
Extra doc: https://github.com/casadi/casadi/wiki/L_1kn
Definition at line 226 of file linsol.cpp.
{
     Linsol linsol;
     linsol.own(LinsolInternal::deserialize(s));
     linsol->finalize();
     return linsol;
   }
References casadi::LinsolInternal::deserialize(), casadi::ProtoFunction::finalize(), and casadi::SharedObject::own().
disp()
void casadi::SharedObject::disp (std::ostream & stream, bool more = false) const inherited
Definition at line 103 of file shared_object.cpp.
{
     if (is_null()) {
       stream << "NULL";
     } else {
       (*this)->disp(stream, more);
     }
   }
References casadi::SharedObject::is_null().
Referenced by casadi::Nlpsol::disp_more(), and casadi::CsparseInterface::nfact().
doc()
std::string casadi::Linsol::doc (const std::string & name) static
Definition at line 60 of file linsol.cpp.
{
     return LinsolInternal::getPlugin(name).doc;
   }
References casadi::PluginInterface< LinsolInternal >::getPlugin().
Referenced by casadi::doc_linsol().
get()
SharedObjectInternal * casadi::SharedObject::get () const inherited
Definition at line 69 of file shared_object.cpp.
{
     return node;
   }
Referenced by casadi::SharedObject::__hash__(), casadi::GenericType::as_bool(), casadi::GenericType::as_bool_vector(), casadi::GenericType::as_dict(), casadi::GenericType::as_dict_vector(), casadi::GenericType::as_double(), casadi::GenericType::as_double_vector(), casadi::GenericType::as_double_vector_vector(), casadi::GenericType::as_function(), casadi::GenericType::as_function_vector(), casadi::GenericType::as_int(), casadi::GenericType::as_int_vector(), casadi::GenericType::as_int_vector_vector(), casadi::GenericType::as_string(), casadi::GenericType::as_string_vector(), casadi::GenericType::as_string_vector_vector(), casadi::GenericType::as_vector(), casadi::GenericType::as_vector_vector(), casadi::GenericType::as_void_pointer(), casadi::Fmu::get(), casadi::Function::get(), casadi::MX::get(), casadi::Sparsity::get(), casadi::DaeBuilder::get(), casadi::GenericType::getType(), and casadi::GenericType::serialize().
get_str()
std::string casadi::SharedObject::get_str (bool more = false) const inline inherited
Definition at line 138 of file shared_object.hpp.
{
       std::stringstream ss;
       disp(ss, more);
       return ss.str();
     }
getCount()
casadi_int casadi::SharedObject::getCount () const inherited
Definition at line 121 of file shared_object.cpp.
{
     return (*this)->getCount();
   }
Referenced by casadi::MXNode::~MXNode().
has_plugin()
bool casadi::Linsol::has_plugin (const std::string & name) static
Definition at line 52 of file linsol.cpp.
{
     return LinsolInternal::has_plugin(name);
   }
References casadi::PluginInterface< LinsolInternal >::has_plugin().
Referenced by casadi::has_linsol().
is_null()
bool casadi::SharedObject::is_null () const inherited
Definition at line 73 of file shared_object.cpp.
{
     return node==nullptr;
   }
Referenced by casadi::FunctionInternal::add_embedded(), casadi::WeakRef::alive(), casadi::FunctionInternal::alloc(), casadi::Nlpsol::callback(), casadi::DaeBuilderInternal::clear_cache(), casadi::Switch::codegen_body(), casadi::Conic::Conic(), casadi::conic_debug(), casadi::Callback::construct(), casadi::Function::deserialize(), casadi::SharedObject::disp(), casadi::FunctionInternal::finalize(), casadi::Switch::find(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::get_n_in(), casadi::Switch::get_n_in(), casadi::FunctionInternal::get_n_out(), casadi::Switch::get_n_out(), casadi::FunctionInternal::get_name_in(), casadi::FunctionInternal::get_name_out(), casadi::FunctionInternal::get_partition(), casadi::FunctionInternal::get_sparsity_in(), casadi::Switch::get_sparsity_in(), casadi::FunctionInternal::get_sparsity_out(), casadi::Switch::get_sparsity_out(), casadi::MXFunction::get_stats(), casadi::GenericType::getType(), casadi::Sparsity::info(), casadi::Nlpsol::init(), casadi::Rootfinder::init(), casadi::Switch::init(), casadi::SLEQPInterface::init(), casadi::SnoptInterface::init(), casadi::SundialsInterface::init(), casadi::FastNewton::init(), casadi::Newton::init(), casadi::Scpgen::init(), casadi::BonminInterface::intermediate_callback(), casadi::IpoptInterface::intermediate_callback(), casadi::XFunction< DerivedType, MatType, NodeType >::jac(), casadi::FunctionInternal::jac_is_symm(), casadi::FunctionInternal::jac_sparsity(), casadi::OracleFunction::jit_dependencies(), casadi::SparsityInternal::maxtrans(), casadi::Fmu::name(), casadi::Function::name(), casadi::Function::operator->(), casadi::SharedObject::operator->(), casadi::Function::operator==(), casadi::DaeBuilderInternal::oracle(), casadi::Function::serialize(), casadi::Sparsity::serialize(), casadi::SLEQPInterface::set_work(), casadi::SnoptInterface::set_work(), casadi::OptiNode::solve(), casadi::KnitroInterface::solve(), casadi::SLEQPInterface::solve(), casadi::WorhpInterface::solve(), casadi::FunctionInternal::sp_forward_block(), casadi::FunctionInternal::sp_reverse(), casadi::Sparsity::uni_coloring(), and casadi::Callback::~Callback().
load_plugin()
void casadi::Linsol::load_plugin (const std::string & name) static
Definition at line 56 of file linsol.cpp.
{
     LinsolInternal::load_plugin(name);
   }
References casadi::PluginInterface< LinsolInternal >::load_plugin().
Referenced by casadi::load_linsol().
neig() [1/2]
casadi_int casadi::Linsol::neig (const DM & A) const
Not available for all solvers
Extra doc: https://github.com/casadi/casadi/wiki/L_1kk
Definition at line 165 of file linsol.cpp.
{
     if (A.sparsity()!=sparsity()) return neig(project(A, sparsity()));
     casadi_int n = neig(A.ptr());
     casadi_assert(n>=0, "'neig' failed");
     return n;
   }
References casadi::Matrix< Scalar >::ptr(), sparsity(), and casadi::Matrix< Scalar >::sparsity().
Referenced by casadi::QpoasesInterface::qpoases_nfact().
neig() [2/2]
casadi_int casadi::Linsol::neig (const double * A, int mem = 0) const
Low-level API
Definition at line 172 of file linsol.cpp.
{
     return (*this)->neig((*this)->memory(mem), A);
   }
nfact() [1/2]
void casadi::Linsol::nfact (const DM & A) const
Definition at line 126 of file linsol.cpp.
{
     if (A.sparsity()!=sparsity()) return nfact(project(A, sparsity()));
     if (nfact(A.ptr())) casadi_error("'nfact' failed");
   }
References casadi::Matrix< Scalar >::ptr(), sparsity(), and casadi::Matrix< Scalar >::sparsity().
Referenced by casadi::SlicotDple::eval(), casadi::KinsolInterface::psetup(), casadi::QpoasesInterface::qpoases_nfact(), solve(), casadi::Ipqp::solve(), and casadi::Newton::solve().
nfact() [2/2]
int casadi::Linsol::nfact (const double * A, int mem = 0) const
Low-level API
Definition at line 131 of file linsol.cpp.
{
     if (A==nullptr) return 1;
     auto m = static_cast<LinsolMemory*>((*this)->memory(mem));
     // Perform pivoting, if required
     if (!m->is_sfact) {
       if (sfact(A, mem)) return 1;
     }
     m->is_nfact = false;
     if (m->t_total) m->fstats.at("nfact").tic();
     int flag = (*this)->nfact(m, A);
     if (m->t_total) m->fstats.at("nfact").toc();
     if (flag && (*this)->regularity_check_) {
       // Collect nonzeros
       std::vector<std::string> nonzeros(sparsity().nnz());
       for (size_t nz = 0; nz < nonzeros.size(); ++nz)
         nonzeros[nz] = std::to_string(A[nz]);
       // Create .m file
       std::ofstream mfile;
       std::string fname = (*this)->class_name() + "_" + (*this)->name_ + "_debug.m";
       mfile.open(fname.c_str());
       Dict opts;
       opts["name"] = "A";
       opts["nonzeros"] = nonzeros;
       sparsity().export_code("matlab", mfile, opts);
       mfile.close();
       casadi_error("Numerical factorization failed for " + (*this)->name_
         + "[" + (*this)->class_name() + "]. Linear system saved to '" + fname + "'");
     }
     m->is_nfact = true;
     return flag;
   }
References casadi::Sparsity::export_code(), casadi::LinsolMemory::is_nfact, sfact(), and sparsity().
operator->() [1/2]
LinsolInternal * casadi::Linsol::operator-> ()
Definition at line 40 of file linsol.cpp.
{
     return static_cast<LinsolInternal*>(SharedObject::operator->());
   }
References casadi::SharedObject::operator->().
operator->() [2/2]
const LinsolInternal * casadi::Linsol::operator-> () const
Definition at line 44 of file linsol.cpp.
{
     return static_cast<const LinsolInternal*>(SharedObject::operator->());
   }
References casadi::SharedObject::operator->().
own()
void casadi::SharedObject::own (SharedObjectInternal * node) inherited
Assign the node to a node class pointer (or null)
Definition at line 46 of file shared_object.cpp.
{
     count_down();
     node = node_;
     count_up();
   }
References casadi::SharedObject::count_down(), and casadi::SharedObject::count_up().
Referenced by casadi::Callback::construct(), casadi::Function::construct(), casadi::Fmu::create(), casadi::Function::create(), casadi::Importer::create(), create(), casadi::GenericType::create(), casadi::Sparsity::create(), casadi::DaeBuilder::DaeBuilder(), casadi::FunctionInternal::deserialize(), deserialize(), casadi::FmuFunction::factory(), casadi::Fmu::Fmu(), casadi::GenericType::GenericType(), casadi::FmuFunction::get_forward(), casadi::FmuFunction::get_jacobian(), casadi::LinearInterpolant::get_jacobian(), casadi::FmuFunction::get_reverse(), casadi::Importer::Importer(), casadi::MXFunction::init(), Linsol(), casadi::MX::MX(), casadi::Opti::Opti(), casadi::WeakRef::shared(), casadi::WeakRef::WeakRef(), and casadi::XmlFile::XmlFile().
plugin_name()
std::string casadi::Linsol::plugin_name () const
Definition at line 64 of file linsol.cpp.
{
     return (*this)->plugin_name();
   }
print_ptr()
void casadi::SharedObject::print_ptr (std::ostream & stream = casadi::uout()) const inherited
Print the pointer to the internal class
Definition at line 111 of file shared_object.cpp.
{
     stream << node;
   }
rank() [1/2]
casadi_int casadi::Linsol::rank (const DM & A) const
Not available for all solvers
Extra doc: https://github.com/casadi/casadi/wiki/L_1kl
Definition at line 176 of file linsol.cpp.
{
     if (A.sparsity()!=sparsity()) return rank(project(A, sparsity()));
     casadi_int n = rank(A.ptr());
     casadi_assert(n>=0, "'rank' failed");
     return n;
   }
References casadi::Matrix< Scalar >::ptr(), sparsity(), and casadi::Matrix< Scalar >::sparsity().
Referenced by casadi::QpoasesInterface::qpoases_nfact().
rank() [2/2]
casadi_int casadi::Linsol::rank (const double * A, int mem = 0) const
Low-level API
Definition at line 183 of file linsol.cpp.
{
     return (*this)->rank((*this)->memory(mem), A);
   }
release()
void casadi::Linsol::release (int mem) const
Definition at line 200 of file linsol.cpp.
{
     (*this)->release(mem);
   }
Referenced by casadi::Ipqp::solve().
serialize()
void casadi::Linsol::serialize (SerializingStream & s) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1km
Definition at line 221 of file linsol.cpp.
{
     // TODO(jgillis): I don't get why LinsolInternal:: this is necessary
     return (*this)->LinsolInternal::serialize(s);
   }
sfact() [1/2]
void casadi::Linsol::sfact (const DM & A) const
Definition at line 104 of file linsol.cpp.
{
     if (A.sparsity()!=sparsity()) return sfact(project(A, sparsity()));
     if (sfact(A.ptr())) casadi_error("'sfact' failed");
   }
References casadi::Matrix< Scalar >::ptr(), sparsity(), and casadi::Matrix< Scalar >::sparsity().
Referenced by casadi::SlicotDple::eval(), nfact(), casadi::QpoasesInterface::qpoases_sfact(), and solve().
sfact() [2/2]
int casadi::Linsol::sfact (const double * A, int mem = 0) const
Low-level API
Definition at line 109 of file linsol.cpp.
{
     if (A==nullptr) return 1;
     auto m = static_cast<LinsolMemory*>((*this)->memory(mem));
     // Factorization will be needed after this step
     m->is_sfact = m->is_nfact = false;
     if (m->t_total) m->fstats.at("sfact").tic();
     // Perform pivoting
     if ((*this)->sfact(m, A)) return 1;
     if (m->t_total) m->fstats.at("sfact").toc();
     // Mark as (successfully) pivoted
     m->is_sfact = true;
     return 0;
   }
References casadi::LinsolMemory::is_sfact.
solve() [1/3]
DM casadi::Linsol::solve (const DM & A, const DM & B, bool tr = false) const
Solve linear system of equations
Definition at line 72 of file linsol.cpp.
{
     casadi_assert(A.size1()==B.size1(),
       "Linsol::solve: Dimension mismatch. A and b must have matching row count. "
       "Got " + A.dim() + " and " + B.dim() + ".");
     scoped_checkout<Linsol> mem(*this);
     auto m = static_cast<LinsolMemory*>((*this)->memory(mem));
     // Reset statistics
     for (auto&& s : m->fstats) s.second.reset();
     if (m->t_total) m->t_total->tic();
     // Symbolic factorization
     if (sfact(A.ptr(), mem)) casadi_error("Linsol::solve: 'sfact' failed");
     // Numeric factorization
     if (nfact(A.ptr(), mem)) casadi_error("Linsol::solve: 'nfact' failed");
     // Solve
     DM x = densify(B);
     if (solve(A.ptr(), x.ptr(), x.size2(), false, mem))
       casadi_error("Linsol::solve: 'solve' failed");
     // Show statistics
     if (m->t_total) m->t_total->toc();
     (*this)->print_time(m->fstats);
     return x;
   }
References casadi::GenericMatrix< MatType >::dim(), nfact(), casadi::Matrix< Scalar >::ptr(), sfact(), casadi::GenericMatrix< MatType >::size1(), casadi::GenericMatrix< MatType >::size2(), casadi::ProtoFunctionMemory::t_total, and casadi::FStats::tic().
Referenced by casadi::SlicotDple::eval(), casadi::KinsolInterface::psolve(), casadi::QpoasesInterface::qpoases_solve(), casadi::Ipqp::solve(), casadi::LinsolCall< Tr >::solve(), casadi::MX::solve(), casadi::Newton::solve(), and casadi::IdasInterface::solve_transposed().
solve() [2/3]
int casadi::Linsol::solve (const double * A, double * x, casadi_int nrhs = 1, bool tr = false, int mem = 0) const
Low-level API
Definition at line 187 of file linsol.cpp.
{
     auto m = static_cast<LinsolMemory*>((*this)->memory(mem));
     casadi_assert(m->is_nfact, "Linear system has not been factorized");
     if (m->t_total) m->fstats.at("solve").tic();
     int ret = (*this)->solve(m, A, x, nrhs, tr);
     if (m->t_total) m->fstats.at("solve").toc();
     return ret;
   }
solve() [3/3]
MX casadi::Linsol::solve (const MX & A, const MX & B, bool tr = false) const
Solve linear system of equations
Definition at line 100 of file linsol.cpp.
{
     return A->get_solve(B, tr, *this);
   }
References casadi::MXNode::get_solve().
sparsity()
const Sparsity & casadi::Linsol::sparsity () const
Definition at line 68 of file linsol.cpp.
{
     return (*this)->sp_;
   }
Referenced by casadi::SundialsInterface::init(), neig(), nfact(), rank(), casadi::SundialsInterface::set_work(), and sfact().
stats()
Dict casadi::Linsol::stats (int mem = 1) const
Definition at line 217 of file linsol.cpp.
{
     return (*this)->get_stats((*this)->memory(mem));
   }
swap()
void casadi::SharedObject::swap (SharedObject & other) inherited
Definition at line 115 of file shared_object.cpp.
{
     SharedObject temp = *this;
     *this = other;
     other = temp;
   }
test_cast()
bool casadi::Linsol::test_cast (const SharedObjectInternal * ptr) static
Definition at line 48 of file linsol.cpp.
{
     return dynamic_cast<const LinsolInternal*>(ptr)!=nullptr;
   }
type_name()
static std::string casadi::Linsol::type_name () inline static
Extra doc: https://github.com/casadi/casadi/wiki/L_1ki
Definition at line 60 of file linsol.hpp.
 {return "Linsol";}
weak()
WeakRef * casadi::SharedObject::weak () inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_aw
Definition at line 125 of file shared_object.cpp.
{
     return (*this)->weak();
   }
References casadi::SharedObjectInternal::weak().
Referenced by casadi::WeakRef::WeakRef().
The documentation for this class was generated from the following files:
linsol.hpp
linsol.cpp