CasADi: casadi::LapackLuMemory Struct Reference
casadi::LapackLuMemory Struct Reference
#include <lapack_lu.hpp>
Detailed Description
Definition at line 62 of file lapack_lu.hpp.
Public Member Functions
void add_stat (const std::string &s)
Public Attributes
std::vector< double > mat
std::vector< int > ipiv
Pivoting elements.
std::vector< double > r
Col and row scaling.
std::vector< double > c
char equed
Type of scaling during the last equilibration.
bool is_sfact
bool is_nfact
std::map< std::string, FStats > fstats
FStats * t_total
Member Function Documentation
add_stat()
void casadi::ProtoFunctionMemory::add_stat (const std::string & s) inline inherited
Definition at line 74 of file function_internal.hpp.
{
       bool added = fstats.insert(std::make_pair(s, FStats())).second;
       casadi_assert(added, "Duplicate stat: '" + s + "'");
     }
Referenced by casadi::ProtoFunction::init_mem(), casadi::LinsolInternal::init_mem(), casadi::Nlpsol::init_mem(), casadi::OracleFunction::init_mem(), casadi::CbcInterface::init_mem(), casadi::ClpInterface::init_mem(), casadi::HpipmInterface::init_mem(), casadi::Feasiblesqpmethod::init_mem(), casadi::Sqpmethod::init_mem(), and casadi::OracleFunction::local_init_mem().
Member Data Documentation
c
std::vector<double> casadi::LapackLuMemory::c
Definition at line 70 of file lapack_lu.hpp.
equed
char casadi::LapackLuMemory::equed
Definition at line 73 of file lapack_lu.hpp.
fstats
std::map<std::string, FStats> casadi::ProtoFunctionMemory::fstats inherited
Definition at line 68 of file function_internal.hpp.
Referenced by casadi::Nlpsol::callback(), casadi::IpoptUserClass::eval_h(), casadi::BonminInterface::intermediate_callback(), casadi::IpoptInterface::intermediate_callback(), casadi::OracleFunction::join_results(), casadi::HighsInterface::solve(), casadi::HpipmInterface::solve(), casadi::HpmpcInterface::solve(), casadi::ProxqpInterface::solve(), casadi::QpoasesInterface::solve(), casadi::Sqpmethod::solve_ela_QP(), casadi::Feasiblesqpmethod::solve_LP(), casadi::Feasiblesqpmethod::solve_QP(), and casadi::Sqpmethod::solve_QP().
ipiv
std::vector<int> casadi::LapackLuMemory::ipiv
Definition at line 67 of file lapack_lu.hpp.
is_nfact
bool casadi::LinsolMemory::is_nfact inherited
Definition at line 39 of file linsol_internal.hpp.
Referenced by casadi::Linsol::nfact().
is_sfact
bool casadi::LinsolMemory::is_sfact inherited
Definition at line 39 of file linsol_internal.hpp.
Referenced by casadi::Linsol::sfact().
mat
std::vector<double> casadi::LapackLuMemory::mat
Definition at line 64 of file lapack_lu.hpp.
Referenced by casadi::LapackLu::init_mem().
r
std::vector<double> casadi::LapackLuMemory::r
Definition at line 70 of file lapack_lu.hpp.
t_total
FStats* casadi::ProtoFunctionMemory::t_total inherited
Definition at line 71 of file function_internal.hpp.
Referenced by casadi::LinsolCall< Tr >::eval(), casadi::FunctionInternal::eval_gen(), and casadi::Linsol::solve().
The documentation for this struct was generated from the following file:
lapack_lu.hpp