CasADi: casadi::SparsityInterface< MatType > Class Template Reference
casadi::SparsityInterface< MatType > Class Template Reference
Sparsity interface class.
#include <sparsity_interface.hpp>
Detailed Description
template<typename MatType>
class casadi::SparsityInterface< MatType >
This is a common base class for GenericMatrix (i.e. MX and Matrix<>) and Sparsity, introducing a uniform syntax and implementing common functionality using the curiously recurring template pattern (CRTP) idiom.
Author
Joel Andersson
Date
2014
Extra doc: https://github.com/casadi/casadi/wiki/L_3d
Definition at line 51 of file sparsity_interface.hpp.
Static Public Member Functions
static std::vector< std::vector< MatType > > blocksplit (const MatType &x, const std::vector< casadi_int > &vert_offset, const std::vector< casadi_int > &horz_offset)
static std::vector< std::vector< MatType > > blocksplit (const MatType &x, casadi_int vert_incr, casadi_int horz_incr)
static MatType veccat (const std::vector< MatType > &x)
static MatType vec (const MatType &x)
static MatType repmat (const MatType &x, casadi_int n, casadi_int m=1)
static std::vector< casadi_int > offset (const std::vector< MatType > &v, bool vert=true)
static std::vector< MatType > diagsplit (const MatType &x, const std::vector< casadi_int > &output_offset)
static std::vector< MatType > diagsplit (const MatType &x, casadi_int incr)
static std::vector< MatType > diagsplit (const MatType &x, casadi_int incr1, casadi_int incr2)
static MatType mtimes (const std::vector< MatType > &args)
static std::vector< MatType > horzsplit (const MatType &x, casadi_int incr)
static std::vector< MatType > vertsplit (const MatType &x, casadi_int incr)
static MatType repmat (const MatType &A, const std::pair< casadi_int, casadi_int > &rc)
Protected Member Functions
const MatType & self () const
MatType & self ()
Friends
MatType horzcat (const std::vector< MatType > &v)
Concatenate a list of matrices horizontally.
MatType vertcat (const std::vector< MatType > &v)
Concatenate a list of matrices vertically.
std::vector< MatType > horzsplit (const MatType &x, const std::vector< casadi_int > &offset)
split horizontally, retaining groups of columns
std::vector< MatType > horzsplit (const MatType &x, casadi_int incr=1)
split horizontally, retaining fixed-sized groups of columns
std::vector< MatType > vertsplit (const MatType &x, const std::vector< casadi_int > &offset)
split vertically, retaining groups of rows
std::vector< casadi_int > offset (const std::vector< MatType > &v, bool vert=true)
Helper function, get offsets corresponding to a vector of matrices.
std::vector< MatType > vertsplit (const MatType &x, casadi_int incr=1)
split vertically, retaining fixed-sized groups of rows
MatType blockcat (const std::vector< std::vector< MatType > > &v)
Construct a matrix from a list of list of blocks.
MatType blockcat (const MatType &A, const MatType &B, const MatType &C, const MatType &D)
Construct a matrix from 4 blocks.
std::vector< std::vector< MatType > > blocksplit (const MatType &x, const std::vector< casadi_int > &vert_offset, const std::vector< casadi_int > &horz_offset)
chop up into blocks
std::vector< std::vector< MatType > > blocksplit (const MatType &x, casadi_int vert_incr=1, casadi_int horz_incr=1)
chop up into blocks
MatType diagcat (const std::vector< MatType > &A)
Construct a matrix with given block on the diagonal.
std::vector< MatType > diagsplit (const MatType &x, const std::vector< casadi_int > &output_offset1, const std::vector< casadi_int > &output_offset2)
split diagonally, retaining square matrices
std::vector< MatType > diagsplit (const MatType &x, const std::vector< casadi_int > &output_offset)
split diagonally, retaining square matrices
std::vector< MatType > diagsplit (const MatType &x, casadi_int incr=1)
split diagonally, retaining groups of square matrices
std::vector< MatType > diagsplit (const MatType &x, casadi_int incr1, casadi_int incr2)
split diagonally, retaining fixed-sized matrices
MatType veccat (const std::vector< MatType > &x)
concatenate vertically while vectorizing all arguments with vec
MatType mtimes (const MatType &x, const MatType &y)
Matrix product of two matrices.
MatType mtimes (const std::vector< MatType > &args)
Matrix product of n matrices.
MatType mac (const MatType &x, const MatType &y, const MatType &z)
Multiply-accumulate operation.
MatType transpose (const MatType &X)
Transpose.
MatType vec (const MatType &x)
make a vector
MatType reshape (const MatType &x, casadi_int nrow, casadi_int ncol)
Returns a reshaped version of the matrix.
MatType reshape (const MatType &x, std::pair< casadi_int, casadi_int > rc)
Returns a reshaped version of the matrix, dimensions as a vector.
MatType reshape (const MatType &x, const Sparsity &sp)
Reshape the matrix.
MatType sparsity_cast (const MatType &x, const Sparsity &sp)
Cast matrix nonzeros to different Sparsity.
casadi_int sprank (const MatType &x)
Obtain the structural rank of a sparsity-pattern.
casadi_int norm_0_mul (const MatType &x, const MatType &y)
0-norm (nonzero count) of a Matrix-matrix product
MatType triu (const MatType &x, bool includeDiagonal=true)
Get the upper triangular part of a matrix.
MatType tril (const MatType &x, bool includeDiagonal=true)
Get the lower triangular part of a matrix.
MatType kron (const MatType &a, const MatType &b)
Kronecker tensor product.
MatType repmat (const MatType &A, casadi_int n, casadi_int m=1)
Repeat matrix A n times vertically and m times horizontally.
MatType repmat (const MatType &A, const std::pair< casadi_int, casadi_int > &rc)
Repeat matrix A n times vertically and m times horizontally.
MatType horzcat (const MatType &x, const MatType &y)
Concatenate horizontally, two matrices.
MatType horzcat (const MatType &x, const MatType &y, const MatType &z)
Concatenate horizontally, three matrices.
MatType horzcat (const MatType &x, const MatType &y, const MatType &z, const MatType &w)
Concatenate horizontally, four matrices.
MatType horzcat (const MatType &x, const MatType &y, const MatType &z, const MatType &w, const MatType &v)
Concatenate horizontally, five matrices.
MatType horzcat (const MatType &x, const MatType &y, const MatType &z, const MatType &w, const MatType &v, const MatType &u)
Concatenate horizontally, six matrices.
MatType vertcat (const MatType &x, const MatType &y)
Concatenate vertically, two matrices.
MatType vertcat (const MatType &x, const MatType &y, const MatType &z)
Concatenate vertically, three matrices.
MatType vertcat (const MatType &x, const MatType &y, const MatType &z, const MatType &w)
Concatenate vertically, four matrices.
MatType vertcat (const MatType &x, const MatType &y, const MatType &z, const MatType &w, const MatType &v)
Concatenate vertically, five matrices.
MatType vertcat (const MatType &x, const MatType &y, const MatType &z, const MatType &w, const MatType &v, const MatType &u)
Concatenate vertically, six matrices.
MatType diagcat (const MatType &x, const MatType &y)
Concatenate along diagonal, two matrices.
MatType diagcat (const MatType &x, const MatType &y, const MatType &z)
Concatenate along diagonal, three matrices.
MatType diagcat (const MatType &x, const MatType &y, const MatType &z, const MatType &w)
Concatenate along diagonal, four matrices.
MatType diagcat (const MatType &x, const MatType &y, const MatType &z, const MatType &w, const MatType &v)
Concatenate along diagonal, five matrices.
MatType diagcat (const MatType &x, const MatType &y, const MatType &z, const MatType &w, const MatType &v, const MatType &u)
Concatenate along diagonal, six matrices.
MatType sum1 (const MatType &x)
Return a row-wise summation of elements.
MatType sum2 (const MatType &x)
Return a column-wise summation of elements.
Member Function Documentation
blocksplit() [1/2]
template<typename MatType > std::vector< std::vector< MatType > > casadi::SparsityInterface< MatType >::blocksplit (const MatType & x, casadi_int vert_incr, casadi_int horz_incr) static
Definition at line 590 of file sparsity_interface.hpp.
{
     casadi_assert_dev(horz_incr>=1);
     casadi_assert_dev(vert_incr>=1);
     casadi_int sz1 = x.size1();
     std::vector<casadi_int> offset1 = range(0, sz1, vert_incr);
     offset1.push_back(sz1);
     casadi_int sz2 = x.size2();
     std::vector<casadi_int> offset2 = range(0, sz2, horz_incr);
     offset2.push_back(sz2);
     return blocksplit(x, offset1, offset2);
   }
References casadi::range().
blocksplit() [2/2]
template<typename MatType > std::vector< std::vector< MatType > > casadi::SparsityInterface< MatType >::blocksplit (const MatType & x, const std::vector< casadi_int > & vert_offset, const std::vector< casadi_int > & horz_offset) static
Definition at line 579 of file sparsity_interface.hpp.
{
     std::vector<MatType> rows = MatType::vertsplit(x, vert_offset);
     std::vector< std::vector< MatType > > ret;
     for (auto&& r : rows) ret.push_back(MatType::horzsplit(r, horz_offset));
     return ret;
   }
diagsplit() [1/3]
template<typename MatType > std::vector< MatType > casadi::SparsityInterface< MatType >::diagsplit (const MatType & x, casadi_int incr) static
Definition at line 639 of file sparsity_interface.hpp.
{
     casadi_assert_dev(incr>=1);
     casadi_assert(x.is_square(), "diagsplit(x,incr)::input must be square but got "
                           + x.dim()  + ".");
     std::vector<casadi_int> offset2 = range(0, x.size2(), incr);
     offset2.push_back(x.size2());
     return MatType::diagsplit(x, offset2);
   }
References casadi::range().
diagsplit() [2/3]
template<typename MatType > std::vector< MatType > casadi::SparsityInterface< MatType >::diagsplit (const MatType & x, casadi_int incr1, casadi_int incr2) static
Definition at line 650 of file sparsity_interface.hpp.
{
     casadi_assert_dev(incr1>=1);
     casadi_assert_dev(incr2>=1);
     std::vector<casadi_int> offset1 = range(0, x.size1(), incr1);
     offset1.push_back(x.size1());
     std::vector<casadi_int> offset2 = range(0, x.size2(), incr2);
     offset2.push_back(x.size2());
     return MatType::diagsplit(x, offset1, offset2);
   }
References casadi::range().
diagsplit() [3/3]
template<typename MatType > std::vector< MatType > casadi::SparsityInterface< MatType >::diagsplit (const MatType & x, const std::vector< casadi_int > & output_offset) static
Definition at line 630 of file sparsity_interface.hpp.
{
     casadi_assert(x.is_square(), "diagsplit(x,incr)::input must be square but got "
                           + x.dim()  + ".");
     return MatType::diagsplit(x, output_offset, output_offset);
   }
horzsplit()
template<typename MatType > std::vector< MatType > casadi::SparsityInterface< MatType >::horzsplit (const MatType & x, casadi_int incr) static
Definition at line 671 of file sparsity_interface.hpp.
{
     casadi_assert_dev(incr>=1);
     casadi_int sz2 = x.size2();
     std::vector<casadi_int> offset2 = range(0, sz2, incr);
     offset2.push_back(sz2);
     return MatType::horzsplit(x, offset2);
   }
References casadi::range().
mtimes()
template<typename MatType > MatType casadi::SparsityInterface< MatType >::mtimes (const std::vector< MatType > & args) static
Definition at line 661 of file sparsity_interface.hpp.
{
     casadi_assert(!args.empty(),
                           "mul(std::vector<MatType> &args): "
                           "supplied list must not be empty.");
     MatType ret = args[0];
     for (casadi_int i=1; i<args.size(); ++i) ret = MatType::mtimes(ret, args[i]);
     return ret;
   }
offset()
template<typename MatType > std::vector< casadi_int > casadi::SparsityInterface< MatType >::offset (const std::vector< MatType > & v, bool vert = true) static
Definition at line 605 of file sparsity_interface.hpp.
{
     std::vector<casadi_int> ret(v.size()+1);
     ret[0]=0;
     for (casadi_int i=0; i<v.size(); ++i) {
       ret[i+1] = ret[i] + (vert ? v[i].size1() : v[i].size2());
     }
     return ret;
   }
Referenced by casadi::MX::horzsplit(), and casadi::MX::vertsplit().
repmat() [1/2]
template<typename MatType > static MatType casadi::SparsityInterface< MatType >::repmat (const MatType & A, const std::pair< casadi_int, casadi_int > & rc) inline static
Definition at line 75 of file sparsity_interface.hpp.
{
       return MatType::repmat(A, rc.first, rc.second);
     }
repmat() [2/2]
template<typename MatType > MatType casadi::SparsityInterface< MatType >::repmat (const MatType & x, casadi_int n, casadi_int m = 1) static
Definition at line 568 of file sparsity_interface.hpp.
{
     if (n==1 && m==1) return x;
     MatType allrows = vertcat(std::vector<MatType>(n, x));
     if (n==0) allrows = MatType(0, x.size2());
     MatType ret = horzcat(std::vector<MatType>(m, allrows));
     if (m==0) ret = MatType(allrows.size1(), 0);
     return ret;
   }
Referenced by casadi::Blocksqp::feasibilityRestorationPhase(), and casadi::MXNode::get_repmat().
self() [1/2]
template<typename MatType > MatType& casadi::SparsityInterface< MatType >::self () inline protected
Definition at line 55 of file sparsity_interface.hpp.
 { return static_cast<MatType&>(*this); }
self() [2/2]
template<typename MatType > const MatType& casadi::SparsityInterface< MatType >::self () const inline protected
Definition at line 54 of file sparsity_interface.hpp.
 { return static_cast<const MatType&>(*this); }
vec()
template<typename MatType > MatType casadi::SparsityInterface< MatType >::vec (const MatType & x) static
Definition at line 562 of file sparsity_interface.hpp.
{
     if (x.size2()==1) return x;
     return reshape(x, x.numel(), 1);
   }
veccat()
template<typename MatType > MatType casadi::SparsityInterface< MatType >::veccat (const std::vector< MatType > & x) static
Definition at line 615 of file sparsity_interface.hpp.
{
     std::vector< MatType > x_vec = x;
     for (typename std::vector< MatType >::iterator it=x_vec.begin();
          it!=x_vec.end(); ++it) {
       *it = vec(*it);
     }
     if (x_vec.empty()) {
       return MatType(0, 1);
     } else {
       return vertcat(x_vec);
     }
   }
Referenced by casadi::MX::conditional(), casadi::MX::cse(), casadi::MX::if_else(), casadi::MX::matrix_expand(), and casadi::MX::stop_diff().
vertsplit()
template<typename MatType > std::vector< MatType > casadi::SparsityInterface< MatType >::vertsplit (const MatType & x, casadi_int incr) static
Definition at line 680 of file sparsity_interface.hpp.
{
     casadi_assert_dev(incr>=1);
     casadi_int sz1 = x.size1();
     std::vector<casadi_int> offset1 = range(0, sz1, incr);
     offset1.push_back(sz1);
     return MatType::vertsplit(x, offset1);
   }
References casadi::range().
The documentation for this class was generated from the following file:
sparsity_interface.hpp