CasADi: casadi::LinsolQr Class Reference
casadi::LinsolQr Class Reference
'qr' plugin for LinsolInternal
#include <linsol_qr.hpp>
Detailed Description
List of available options
Id Type Description
cache OT_DOUBLE Amount of factorisations to remember (thread-local) [0]
eps OT_DOUBLE Minimum R entry before singularity is declared [1e-12]
List of available options
Id Type Description Used in
cache OT_DOUBLE Amount of factorisations to remember (thread-local) [0] casadi::LinsolQr
eps OT_DOUBLE Minimum R entry before singularity is declared [1e-12] casadi::LinsolQr
Definition at line 55 of file linsol_qr.hpp.
Public Types
typedef LinsolInternal *(* Creator) (const std::string &name, const Sparsity &sp)
typedef int(* RegFcn) (Plugin *plugin)
Public Member Functions
LinsolQr (const std::string &name, const Sparsity &sp)
~LinsolQr () override
void init (const Dict &opts) override
Initialize.
void finalize () override
Finalize the object creation.
void * alloc_mem () const override
Create memory block.
int init_mem (void *mem) const override
Initalize memory block.
void free_mem (void *mem) const override
Free memory block.
int nfact (void *mem, const double *A) const override
Numeric factorization.
int sfact (void *mem, const double *A) const override
int solve (void *mem, const double *A, double *x, casadi_int nrhs, bool tr) const override
void generate (CodeGenerator &g, const std::string &A, const std::string &x, casadi_int nrhs, bool tr) const override
Generate C code.
const char * plugin_name () const override
std::string class_name () const override
Readable name of the internal class.
void serialize_body (SerializingStream &s) const override
Serialize an object without type information.
void disp (std::ostream &stream, bool more) const override
Display object.
virtual void disp_more (std::ostream &stream) const
Print more.
virtual void linsol_eval_sx (const SXElem **arg, SXElem **res, casadi_int *iw, SXElem *w, void *mem, bool tr, casadi_int nrhs) const
Evaluate SX, possibly transposed.
virtual casadi_int neig (void *mem, const double *A) const
Number of negative eigenvalues.
virtual casadi_int rank (void *mem, const double *A) const
Matrix rank.
casadi_int nrow () const
Get sparsity pattern.
casadi_int ncol () const
const casadi_int * colind () const
const casadi_int * row () const
casadi_int nnz () const
void serialize_type (SerializingStream &s) const override
Serialize type information.
void construct (const Dict &opts)
Construct.
virtual Dict generate_options (const std::string &target) const
Reconstruct options dict.
void print_options (std::ostream &stream) const
Print list of options.
void print_option (const std::string &name, std::ostream &stream) const
Print all information there is to know about a certain option.
bool has_option (const std::string &option_name) const
Does a particular option exist.
virtual void change_option (const std::string &option_name, const GenericType &option_value)
Change option after object creation for debugging.
int checkout () const
Checkout a memory object.
void release (int mem) const
Release a memory object.
void * memory (int ind) const
Memory objects.
virtual Dict get_stats (void *mem) const
Get all statistics.
void clear_mem ()
Clear all memory (called from destructor)
void print (const char *fmt,...) const
C-style formatted printing during evaluation.
void sprint (char *buf, size_t buf_sz, const char *fmt,...) const
C-style formatted printing to string.
void format_time (char *buffer, double time) const
Format time in a fixed width 8 format.
void print_time (const std::map< std::string, FStats > &fstats) const
Print timing statistics.
void serialize (SerializingStream &s) const
Serialize an object.
virtual std::string serialize_base_function () const
String used to identify the immediate FunctionInternal subclass.
casadi_int getCount () const
Get the reference count.
WeakRef * weak ()
Get a weak reference to the object.
Static Public Member Functions
static LinsolInternal * creator (const std::string &name, const Sparsity &sp)
Create a new LinsolInternal.
static ProtoFunction * deserialize (DeserializingStream &s)
Deserialize with type disambiguation.
static bool has_plugin (const std::string &pname, bool verbose=false)
Check if a plugin is available or can be loaded.
static const Options & plugin_options (const std::string &pname)
Get the plugin options.
static Deserialize plugin_deserialize (const std::string &pname)
Get the plugin deserialize_map.
static Plugin pluginFromRegFcn (RegFcn regfcn)
Instantiate a Plugin struct from a factory function.
static Plugin load_plugin (const std::string &pname, bool register_plugin=true)
Load a plugin dynamically.
static handle_t load_library (const std::string &libname, std::string &resultpath, bool global)
Load a library dynamically.
static void registerPlugin (const Plugin &plugin)
Register an integrator in the factory.
static void registerPlugin (RegFcn regfcn)
Register an integrator in the factory.
static Plugin & getPlugin (const std::string &pname)
Load and get the creator function.
static LinsolInternal * instantiate (const std::string &fname, const std::string &pname, Problem problem)
Public Attributes
std::vector< casadi_int > prinv_
Symbolic factorization.
std::vector< casadi_int > pc_
Sparsity sp_v_
Sparsity sp_r_
double eps_
casadi_int n_cache_
Cache size.
casadi_int cache_stride_
Sparsity sp_
std::string name_
Name.
bool verbose_
Verbose printout.
bool print_time_
bool record_time_
bool regularity_check_
Errors are thrown when NaN is produced.
bool error_on_fail_
Throw an exception on failure?
Static Public Attributes
static const std::string meta_doc
A documentation string.
static std::map< std::string, Plugin > solvers_
Collection of solvers.
static const std::string infix_ = "linsol"
Infix.
Protected Member Functions
LinsolQr (DeserializingStream &s)
Deserializing constructor.
void initSingleton ()
void destroySingleton ()
template<class B >
B shared_from_this ()
Get a shared object from the current internal object.
template<class B >
const B shared_from_this () const
Get a shared object from the current internal object.
static const Options options_
Options.
const Options & get_options () const override
Options.
Member Typedef Documentation
Creator
typedef LinsolInternal*(* casadi::LinsolInternal::Creator) (const std::string &name, const Sparsity &sp) inherited
Definition at line 121 of file linsol_internal.hpp.
RegFcn
typedef int(* casadi::PluginInterface< LinsolInternal >::RegFcn) (Plugin *plugin) inherited
Definition at line 72 of file plugin_interface.hpp.
Constructor & Destructor Documentation
LinsolQr() [1/2]
casadi::LinsolQr::LinsolQr (const std::string & name, const Sparsity & sp)
Definition at line 48 of file linsol_qr.cpp.
     : LinsolInternal(name, sp) {
   }
~LinsolQr()
casadi::LinsolQr::~LinsolQr () override
Definition at line 52 of file linsol_qr.cpp.
                       {
     clear_mem();
   }
References casadi::ProtoFunction::clear_mem().
LinsolQr() [2/2]
casadi::LinsolQr::LinsolQr (DeserializingStream & s) explicit protected
Definition at line 220 of file linsol_qr.cpp.
                                            : LinsolInternal(s) {
     int version = s.version("LinsolQr", 1, 2);
     s.unpack("LinsolQr::prinv", prinv_);
     s.unpack("LinsolQr::pc", pc_);
     s.unpack("LinsolQr::sp_v", sp_v_);
     s.unpack("LinsolQr::sp_r", sp_r_);
     s.unpack("LinsolQr::eps", eps_);
     if (version>1) {
       s.unpack("LinsolQr::n_cache", n_cache_);
     } else {
       n_cache_ = 1;
     }
   }
References eps_, n_cache_, pc_, prinv_, sp_r_, sp_v_, casadi::DeserializingStream::unpack(), and casadi::DeserializingStream::version().
Member Function Documentation
alloc_mem()
void* casadi::LinsolQr::alloc_mem () const inline override virtual
Reimplemented from casadi::LinsolInternal.
Definition at line 82 of file linsol_qr.hpp.
 { return new LinsolQrMemory();}
change_option()
void casadi::ProtoFunction::change_option (const std::string & option_name, const GenericType & option_value) virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_jk
Reimplemented in casadi::MXFunction, casadi::FunctionInternal, and casadi::FmuFunction.
Definition at line 919 of file function_internal.cpp.
{
     if (option_name == "verbose") {
       verbose_ = option_value;
     } else if (option_name == "regularity_check") {
       regularity_check_ = option_value;
     } else {
       // Failure
       casadi_error("Option '" + option_name + "' cannot be changed");
     }
   }
References casadi::ProtoFunction::regularity_check_, and casadi::ProtoFunction::verbose_.
Referenced by casadi::FunctionInternal::change_option().
checkout()
int casadi::ProtoFunction::checkout () const inherited
Definition at line 3540 of file function_internal.cpp.
{
 #ifdef CASADI_WITH_THREAD
     std::lock_guard<std::mutex> lock(mtx_);
 #endif //CASADI_WITH_THREAD
     if (unused_.empty()) {
       // Allocate a new memory object
       void* m = alloc_mem();
       mem_.push_back(m);
       if (init_mem(m)) {
         casadi_error("Failed to create or initialize memory object");
       }
       return static_cast<int>(mem_.size()) - 1;
     } else {
       // Use an unused memory object
       int m = unused_.top();
       unused_.pop();
       return m;
     }
   }
References casadi::ProtoFunction::alloc_mem(), and casadi::ProtoFunction::init_mem().
Referenced by casadi::ProtoFunction::finalize(), casadi::FunctionBuffer::FunctionBuffer(), and casadi::Sqpmethod::init_mem().
class_name()
std::string casadi::LinsolQr::class_name () const inline override virtual
Implements casadi::SharedObjectInternal.
Definition at line 107 of file linsol_qr.hpp.
 { return "LinsolQr";}
clear_mem()
void casadi::ProtoFunction::clear_mem () inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_jq
Definition at line 3432 of file function_internal.cpp.
{
     for (auto&& i : mem_) {
       if (i!=nullptr) free_mem(i);
     }
     mem_.clear();
   }
References casadi::ProtoFunction::free_mem().
Referenced by casadi::AlpaqaInterface::~AlpaqaInterface(), casadi::AmplInterface::~AmplInterface(), casadi::Blocksqp::~Blocksqp(), casadi::BonminInterface::~BonminInterface(), casadi::BSplineInterpolant::~BSplineInterpolant(), casadi::CallbackInternal::~CallbackInternal(), casadi::CbcInterface::~CbcInterface(), casadi::ClpInterface::~ClpInterface(), casadi::CplexInterface::~CplexInterface(), casadi::CsparseInterface::~CsparseInterface(), casadi::CvodesInterface::~CvodesInterface(), casadi::DaqpInterface::~DaqpInterface(), casadi::External::~External(), casadi::FastNewton::~FastNewton(), casadi::FatropConicInterface::~FatropConicInterface(), casadi::FatropInterface::~FatropInterface(), casadi::Feasiblesqpmethod::~Feasiblesqpmethod(), casadi::FiniteDiff::~FiniteDiff(), casadi::FixedStepIntegrator::~FixedStepIntegrator(), casadi::FmuFunction::~FmuFunction(), casadi::GurobiInterface::~GurobiInterface(), casadi::HighsInterface::~HighsInterface(), casadi::HpipmInterface::~HpipmInterface(), casadi::HpmpcInterface::~HpmpcInterface(), casadi::IdasInterface::~IdasInterface(), casadi::ImplicitToNlp::~ImplicitToNlp(), casadi::IpoptInterface::~IpoptInterface(), casadi::Ipqp::~Ipqp(), casadi::JitFunction::~JitFunction(), casadi::KinsolInterface::~KinsolInterface(), casadi::KnitroInterface::~KnitroInterface(), casadi::LapackLu::~LapackLu(), casadi::LapackQr::~LapackQr(), casadi::LinearInterpolant::~LinearInterpolant(), casadi::LinearInterpolantJac::~LinearInterpolantJac(), casadi::LinsolLdl::~LinsolLdl(), ~LinsolQr(), casadi::LinsolTridiag::~LinsolTridiag(), casadi::Lsqr::~Lsqr(), casadi::Ma27Interface::~Ma27Interface(), casadi::MadnlpInterface::~MadnlpInterface(), casadi::Map::~Map(), casadi::MapSum::~MapSum(), casadi::MumpsInterface::~MumpsInterface(), casadi::MXFunction::~MXFunction(), casadi::Newton::~Newton(), casadi::Nlpsol::~Nlpsol(), casadi::OmpMap::~OmpMap(), casadi::OoqpInterface::~OoqpInterface(), casadi::OsqpInterface::~OsqpInterface(), casadi::ProxqpInterface::~ProxqpInterface(), casadi::QpoasesInterface::~QpoasesInterface(), casadi::QpToNlp::~QpToNlp(), casadi::Qrqp::~Qrqp(), casadi::Qrsqp::~Qrsqp(), casadi::Scpgen::~Scpgen(), casadi::SLEQPInterface::~SLEQPInterface(), casadi::SlicotDple::~SlicotDple(), casadi::SlicotExpm::~SlicotExpm(), casadi::SnoptInterface::~SnoptInterface(), casadi::Sqpmethod::~Sqpmethod(), casadi::SuperscsInterface::~SuperscsInterface(), casadi::Switch::~Switch(), casadi::SymbolicQr::~SymbolicQr(), casadi::ThreadMap::~ThreadMap(), and casadi::WorhpInterface::~WorhpInterface().
colind()
const casadi_int* casadi::LinsolInternal::colind () const inline inherited
Definition at line 138 of file linsol_internal.hpp.
 { return sp_.colind();}
Referenced by casadi::CsparseInterface::init_mem(), casadi::MumpsInterface::init_mem(), casadi::Ma27Interface::nfact(), and casadi::MumpsInterface::nfact().
construct()
void casadi::ProtoFunction::construct (const Dict & opts) inherited
Prepares the function for evaluation
Extra doc: https://github.com/casadi/casadi/wiki/L_jf
Definition at line 132 of file function_internal.cpp.
{
     // Sanitize dictionary is needed
     if (!Options::is_sane(opts)) {
       // Call recursively
       return construct(Options::sanitize(opts));
     }
     // Make sure all options exist
     get_options().check(opts);
     // Initialize the class hierarchy
     try {
       init(opts);
     } catch(std::exception& e) {
       casadi_error("Error calling " + class_name() + "::init for '" + name_ + "':\n"
         + std::string(e.what()));
     }
     // Revisit class hierarchy in reverse order
     try {
       finalize();
     } catch(std::exception& e) {
       casadi_error("Error calling " + class_name() + "::finalize for '" + name_ + "':\n"
         + std::string(e.what()));
     }
   }
References casadi::Options::check(), casadi::SharedObjectInternal::class_name(), casadi::ProtoFunction::finalize(), casadi::ProtoFunction::get_options(), casadi::ProtoFunction::init(), casadi::Options::is_sane(), casadi::ProtoFunction::name_, and casadi::Options::sanitize().
Referenced by casadi::Function::create(), casadi::FmuFunction::factory(), casadi::FmuFunction::get_forward(), casadi::FmuFunction::get_jacobian(), casadi::LinearInterpolant::get_jacobian(), and casadi::FmuFunction::get_reverse().
creator()
static LinsolInternal* casadi::LinsolQr::creator (const std::string & name, const Sparsity & sp) inline static
Definition at line 62 of file linsol_qr.hpp.
{
       return new LinsolQr(name, sp);
     }
Referenced by casadi::casadi_register_linsol_qr().
deserialize()
static ProtoFunction* casadi::LinsolQr::deserialize (DeserializingStream & s) inline static
Definition at line 125 of file linsol_qr.hpp.
 { return new LinsolQr(s); }
Referenced by casadi::casadi_register_linsol_qr().
destroySingleton()
void casadi::SharedObjectInternal::destroySingleton () inline protected inherited
Called in the destructor of singletons
Definition at line 79 of file shared_object_internal.hpp.
{
       count--;
     }
disp()
void casadi::LinsolInternal::disp (std::ostream & stream, bool more) const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_e4
Implements casadi::SharedObjectInternal.
Definition at line 43 of file linsol_internal.cpp.
{
     stream << "Linear solver " << class_name();
     if (more) {
       stream << std::endl;
       disp_more(stream);
     }
   }
References casadi::SharedObjectInternal::class_name(), and casadi::LinsolInternal::disp_more().
disp_more()
virtual void casadi::LinsolInternal::disp_more (std::ostream & stream) const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_e5
Definition at line 65 of file linsol_internal.hpp.
 {}
Referenced by casadi::LinsolInternal::disp().
finalize()
void casadi::LinsolQr::finalize () override virtual
Reimplemented from casadi::ProtoFunction.
Definition at line 86 of file linsol_qr.cpp.
{
     cache_stride_ = sp_.nnz()+sp_v_.nnz()+sp_r_.nnz()+ncol();
     LinsolInternal::finalize();
   }
References cache_stride_, casadi::ProtoFunction::finalize(), casadi::LinsolInternal::ncol(), casadi::Sparsity::nnz(), casadi::LinsolInternal::sp_, sp_r_, and sp_v_.
format_time()
void casadi::ProtoFunction::format_time (char * buffer, double time) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_jt
Definition at line 3722 of file function_internal.cpp.
{
     // Always of width 8
     casadi_assert_dev(time>=0);
     double log_time = log10(time);
     int magn = static_cast<int>(floor(log_time));
     int iprefix = static_cast<int>(floor(log_time/3));
     if (iprefix<-4) {
       sprint(buffer, 10, "       0");
       return;
     }
     if (iprefix>=5) {
       sprint(buffer, 10, "     inf");
       return;
     }
     char prefixes[] = "TGMk munp";
     char prefix = prefixes[4-iprefix];
     int rem = magn-3*iprefix;
     double time_normalized = time/pow(10, 3*iprefix);
     if (rem==0) {
       sprint(buffer, 10, "  %1.2f%cs", time_normalized, prefix);
     } else if (rem==1) {
       sprint(buffer, 10, " %2.2f%cs", time_normalized, prefix);
     } else {
       sprint(buffer, 10, "%3.2f%cs", time_normalized, prefix);
     }
   }
References casadi::ProtoFunction::sprint().
Referenced by casadi::ProtoFunction::print_time().
free_mem()
void casadi::LinsolQr::free_mem (void * mem) const inline override virtual
Reimplemented from casadi::LinsolInternal.
Definition at line 88 of file linsol_qr.hpp.
 { delete static_cast<LinsolQrMemory*>(mem);}
generate()
void casadi::LinsolQr::generate (CodeGenerator & g, const std::string & A, const std::string & x, casadi_int nrhs, bool tr) const override virtual
Reimplemented from casadi::LinsolInternal.
Definition at line 165 of file linsol_qr.cpp.
{
     // Codegen the integer vectors
     std::string prinv = g.constant(prinv_);
     std::string pc = g.constant(pc_);
     std::string sp = g.sparsity(sp_);
     std::string sp_v = g.sparsity(sp_v_);
     std::string sp_r = g.sparsity(sp_r_);
     // Place in block to avoid conflicts caused by local variables
     g << "{\n";
     g.comment("FIXME(@jaeandersson): Memory allocation can be avoided");
     g << "casadi_real v[" << sp_v_.nnz() << "], "
          "r[" << sp_r_.nnz() << "], "
          "beta[" << ncol() << "], "
          "w[" << nrow() + ncol() << "];\n";
     if (n_cache_) {
       g << "casadi_real *c;\n";
       g << "casadi_real cache[" << cache_stride_*n_cache_ << "];\n";
       g << "int cache_loc[" << n_cache_ << "] = {";
       for (casadi_int i=0;i<n_cache_;++i) {
         g << "-1,";
       }
       g << "};\n";
       g << "if (" << g.cache_check(A, "cache", "cache_loc",
         cache_stride_, n_cache_, sp_.nnz(), "&c") << ") {\n";
       casadi_int offset = sp_.nnz();
       g.comment("Retrieve from cache");
       g << g.copy("c+" + str(offset), sp_v_.nnz(), "v") << "\n"; offset+=sp_v_.nnz();
       g << g.copy("c+" + str(offset), sp_r_.nnz(), "r") << "\n"; offset+=sp_r_.nnz();
       g << g.copy("c+" + str(offset), ncol(), "beta") << "\n"; offset+=ncol();
       g << "} else {\n";
     }
     // Factorize
     g << g.qr(sp, A, "w", sp_v, "v", sp_r, "r", "beta", prinv, pc) << "\n";
     if (n_cache_) {
       casadi_int offset = 0;
       g.comment("Store in cache");
       g << g.copy(A, sp_.nnz(), "c") << "\n";; offset+=sp_.nnz();
       g << g.copy("v", sp_v_.nnz(), "c+"+str(offset)) << "\n"; offset+=sp_v_.nnz();
       g << g.copy("r", sp_r_.nnz(), "c+"+str(offset)) << "\n"; offset+=sp_r_.nnz();
       g << g.copy("beta", ncol(), "c+"+str(offset)) << "\n"; offset+=ncol();
       g << "}\n";
     }
     // Solve
     g << g.qr_solve(x, nrhs, tr, sp_v, "v", sp_r, "r", "beta", prinv, pc, "w") << "\n";
     // End of block
     g << "}\n";
   }
References casadi::CodeGenerator::cache_check(), cache_stride_, casadi::CodeGenerator::comment(), casadi::CodeGenerator::constant(), casadi::CodeGenerator::copy(), n_cache_, casadi::LinsolInternal::ncol(), casadi::Sparsity::nnz(), casadi::LinsolInternal::nrow(), pc_, prinv_, casadi::CodeGenerator::qr(), casadi::CodeGenerator::qr_solve(), casadi::LinsolInternal::sp_, sp_r_, sp_v_, casadi::CodeGenerator::sparsity(), and casadi::str().
generate_options()
Dict casadi::ProtoFunction::generate_options (const std::string & target) const virtual inherited
Reimplemented in casadi::SXFunction, casadi::MXFunction, and casadi::FunctionInternal.
Definition at line 367 of file function_internal.cpp.
{
     Dict opts;
     opts["verbose"] = verbose_;
     opts["print_time"] = print_time_;
     opts["record_time"] = record_time_;
     opts["regularity_check"] = regularity_check_;
     opts["error_on_fail"] = error_on_fail_;
     return opts;
   }
References casadi::ProtoFunction::error_on_fail_, casadi::ProtoFunction::print_time_, casadi::ProtoFunction::record_time_, casadi::ProtoFunction::regularity_check_, and casadi::ProtoFunction::verbose_.
Referenced by casadi::FunctionInternal::generate_options().
get_options()
const Options& casadi::LinsolQr::get_options () const inline override virtual
Reimplemented from casadi::ProtoFunction.
Definition at line 78 of file linsol_qr.hpp.
 { return options_;}
get_stats()
Dict casadi::ProtoFunction::get_stats (void * mem) const virtual inherited
Reimplemented in casadi::Sqpmethod, casadi::Scpgen, casadi::Qrsqp, casadi::Qrqp, casadi::QpToNlp, casadi::Newton, casadi::Ipqp, casadi::ImplicitToNlp, casadi::Feasiblesqpmethod, casadi::FastNewton, casadi::WorhpInterface, casadi::SuperscsInterface, casadi::SundialsInterface, casadi::SnoptInterface, casadi::SLEQPInterface, casadi::QpoasesInterface, casadi::ProxqpInterface, casadi::OsqpInterface, casadi::OoqpInterface, casadi::MadnlpInterface, casadi::KnitroInterface, casadi::IpoptInterface, casadi::HpmpcInterface, casadi::HpipmInterface, casadi::HighsInterface, casadi::GurobiInterface, casadi::FatropInterface, casadi::FatropConicInterface, casadi::DaqpInterface, casadi::CplexInterface, casadi::ClpInterface, casadi::CbcInterface, casadi::BonminInterface, casadi::AlpaqaInterface, casadi::Rootfinder, casadi::OracleFunction, casadi::Nlpsol, casadi::MXFunction, casadi::FmuFunction, and casadi::Conic.
Definition at line 2859 of file function_internal.cpp.
{
     auto m = static_cast<ProtoFunctionMemory*>(mem);
     // Add timing statistics
     Dict stats;
     for (const auto& s : m->fstats) {
       stats["n_call_" +s.first] = s.second.n_call;
       stats["t_wall_" +s.first] = s.second.t_wall;
       stats["t_proc_" +s.first] = s.second.t_proc;
     }
     return stats;
   }
Referenced by casadi::Conic::get_stats(), casadi::FmuFunction::get_stats(), casadi::MXFunction::get_stats(), casadi::OracleFunction::get_stats(), and casadi::QpToNlp::get_stats().
getCount()
casadi_int casadi::SharedObjectInternal::getCount () const inherited
Definition at line 58 of file shared_object_internal.cpp.
{
     return count;
   }
getPlugin()
PluginInterface< LinsolInternal >::Plugin & casadi::PluginInterface< LinsolInternal >::getPlugin (const std::string & pname) static inherited
Definition at line 100 of file plugin_interface.hpp.
{
     // Check if the solver has been loaded
     auto it=Derived::solvers_.find(pname);
     // Load the solver if needed
     if (it==Derived::solvers_.end()) {
       load_plugin(pname);
       it=Derived::solvers_.find(pname);
     }
     casadi_assert_dev(it!=Derived::solvers_.end());
     return it->second;
   }
has_option()
bool casadi::ProtoFunction::has_option (const std::string & option_name) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_jj
Definition at line 915 of file function_internal.cpp.
{
     return get_options().find(option_name) != 0;
   }
References casadi::Options::find(), and casadi::ProtoFunction::get_options().
has_plugin()
bool casadi::PluginInterface< LinsolInternal >::has_plugin (const std::string & pname, bool verbose = false) static inherited
Definition at line 75 of file plugin_interface.hpp.
{
     // Quick return if available
     if (Derived::solvers_.find(pname) != Derived::solvers_.end()) {
       return true;
     }
     // Try loading the plugin
     try {
       (void)load_plugin(pname, false);
       return true;
     } catch (CasadiException& ex) {
       if (verbose) {
         casadi_warning(ex.what());
       }
       return false;
     }
   }
init()
void casadi::LinsolQr::init (const Dict & opts) override virtual
Reimplemented from casadi::LinsolInternal.
Definition at line 67 of file linsol_qr.cpp.
{
     // Call the init method of the base class
     LinsolInternal::init(opts);
     // Read options
     eps_ = 1e-12;
     n_cache_ = 0;
     for (auto&& op : opts) {
       if (op.first=="eps") {
         eps_ = op.second;
       } else if (op.first=="cache") {
         n_cache_ = op.second;
       }
     }
     // Symbolic factorization
     sp_.qr_sparse(sp_v_, sp_r_, prinv_, pc_);
   }
References eps_, casadi::LinsolInternal::init(), n_cache_, pc_, prinv_, casadi::Sparsity::qr_sparse(), casadi::LinsolInternal::sp_, sp_r_, and sp_v_.
init_mem()
int casadi::LinsolQr::init_mem (void * mem) const override virtual
Reimplemented from casadi::LinsolInternal.
Definition at line 91 of file linsol_qr.cpp.
{
     if (LinsolInternal::init_mem(mem)) return 1;
     auto m = static_cast<LinsolQrMemory*>(mem);
     // Memory for numerical solution
     m->v.resize(sp_v_.nnz());
     m->r.resize(sp_r_.nnz());
     m->beta.resize(ncol());
     m->w.resize(nrow() + ncol());
     m->cache.resize(cache_stride_*n_cache_);
     m->cache_loc.resize(n_cache_, -1);
     return 0;
   }
References cache_stride_, casadi::LinsolInternal::init_mem(), n_cache_, casadi::LinsolInternal::ncol(), casadi::Sparsity::nnz(), casadi::LinsolInternal::nrow(), sp_r_, sp_v_, and casadi::LinsolQrMemory::v.
initSingleton()
void casadi::SharedObjectInternal::initSingleton () inline protected inherited
Called in the constructor of singletons to avoid that the counter reaches zero
Definition at line 73 of file shared_object_internal.hpp.
{
       casadi_assert_dev(count==0);
       count++;
     }
instantiate()
LinsolInternal * casadi::PluginInterface< LinsolInternal >::instantiate (const std::string & fname, const std::string & pname, Problem problem) static inherited
Definition at line 104 of file plugin_interface.hpp.
{
     // Assert the plugin exists (needed for adaptors)
     if (!has_plugin(pname, true)) {
       casadi_error("Plugin '" + pname + "' is not found.");
     }
     return getPlugin(pname).creator(fname, problem);
   }
linsol_eval_sx()
void casadi::LinsolInternal::linsol_eval_sx (const SXElem ** arg, SXElem ** res, casadi_int * iw, SXElem * w, void * mem, bool tr, casadi_int nrhs) const virtual inherited
Reimplemented in casadi::SymbolicQr.
Definition at line 63 of file linsol_internal.cpp.
{
     casadi_error("eval_sx not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
load_library()
handle_t casadi::PluginInterface< LinsolInternal >::load_library (const std::string & libname, std::string & resultpath, bool global) static inherited
Definition at line 90 of file plugin_interface.hpp.
{
 #ifndef WITH_DL
     casadi_error("WITH_DL option needed for dynamic loading");
 #else // WITH_DL
     // Get the name of the shared library
     std::string lib = SHARED_LIBRARY_PREFIX + libname + SHARED_LIBRARY_SUFFIX;
     // Build up search paths;
     std::vector<std::string> search_paths = get_search_paths();
     return open_shared_library(lib, search_paths, resultpath,
       "PluginInterface::load_plugin", global);
 #endif // WITH_DL
   }
load_plugin()
PluginInterface< LinsolInternal >::Plugin casadi::PluginInterface< LinsolInternal >::load_plugin (const std::string & pname, bool register_plugin = true) static inherited
Definition at line 87 of file plugin_interface.hpp.
{
     // Issue warning and quick return if already loaded
     if (Derived::solvers_.find(pname) != Derived::solvers_.end()) {
       casadi_warning("PluginInterface: Solver " + pname + " is already in use. Ignored.");
       return Plugin();
     }
 #ifndef WITH_DL
     casadi_error("WITH_DL option needed for dynamic loading");
 #else // WITH_DL
     // Retrieve the registration function
     RegFcn reg;
     // Load the dll
     std::string regName = "casadi_register_" + Derived::infix_ + "_" + pname;
     std::string searchpath;
     handle_t handle = load_library("casadi_" + Derived::infix_ + "_" + pname, searchpath,
       false);
 #ifdef _WIN32
 #if __GNUC__
 #pragma GCC diagnostic push
 #pragma GCC diagnostic ignored "-Wcast-function-type"
 #endif
     reg = reinterpret_cast<RegFcn>(GetProcAddress(handle, TEXT(regName.c_str())));
 #if __GNUC__
 #pragma GCC diagnostic pop
 #endif
 #else // _WIN32
     // Reset error
     dlerror();
     // Load creator
     reg = reinterpret_cast<RegFcn>(dlsym(handle, regName.c_str()));
 #endif // _WIN32
     casadi_assert(reg!=nullptr,
       "PluginInterface::load_plugin: no \"" + regName + "\" found in " + searchpath + ".");
     // Create a temporary struct
     Plugin plugin = pluginFromRegFcn(reg);
     // Register the plugin
     if (register_plugin) {
       registerPlugin(plugin);
     }
     return plugin;
 #endif // WITH_DL
   }
memory()
void * casadi::ProtoFunction::memory (int ind) const inherited
Definition at line 3533 of file function_internal.cpp.
{
 #ifdef CASADI_WITH_THREAD
     std::lock_guard<std::mutex> lock(mtx_);
 #endif //CASADI_WITH_THREAD
     return mem_.at(ind);
   }
Referenced by casadi::FunctionInternal::call_gen(), casadi::FunctionInternal::get_jac_sparsity_gen(), casadi::FunctionInternal::get_jac_sparsity_hierarchical(), casadi::Sqpmethod::solve_ela_QP(), and casadi::Sqpmethod::solve_QP().
ncol()
casadi_int casadi::LinsolInternal::ncol () const inline inherited
Definition at line 137 of file linsol_internal.hpp.
 { return sp_.size2();}
Referenced by finalize(), generate(), casadi::Lsqr::generate(), casadi::CsparseInterface::init_mem(), casadi::Ma27Interface::init_mem(), casadi::LapackLu::init_mem(), casadi::LapackQr::init_mem(), init_mem(), casadi::Lsqr::init_mem(), casadi::Ma27Interface::nfact(), casadi::LapackLu::nfact(), casadi::LapackQr::nfact(), nfact(), casadi::CsparseInterface::solve(), casadi::Ma27Interface::solve(), casadi::LapackLu::solve(), casadi::LinsolTridiag::solve(), and casadi::LapackQr::solve_batch().
neig()
casadi_int casadi::LinsolInternal::neig (void * mem, const double * A) const virtual inherited
Reimplemented in casadi::LinsolLdl, and casadi::Ma27Interface.
Definition at line 102 of file linsol_internal.cpp.
{
     casadi_error("'neig' not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
nfact()
int casadi::LinsolQr::nfact (void * mem, const double * A) const override virtual
Reimplemented from casadi::LinsolInternal.
Definition at line 111 of file linsol_qr.cpp.
{
     auto m = static_cast<LinsolQrMemory*>(mem);
     // Check for a cache hit
     double* cache = nullptr;
     bool cache_hit = cache_check(A, get_ptr(m->cache), get_ptr(m->cache_loc),
       cache_stride_, n_cache_, sp_.nnz(), &cache);
     if (cache && cache_hit) {
       cache += sp_.nnz();
       // Retrieve from cache and return early
       casadi_copy(cache, sp_v_.nnz(), get_ptr(m->v)); cache+=sp_v_.nnz();
       casadi_copy(cache, sp_r_.nnz(), get_ptr(m->r)); cache+=sp_r_.nnz();
       casadi_copy(cache, ncol(), get_ptr(m->beta)); cache+=ncol();
       return 0;
     }
     // Cache miss -> compute result
     casadi_qr(sp_, A, get_ptr(m->w),
               sp_v_, get_ptr(m->v), sp_r_, get_ptr(m->r),
               get_ptr(m->beta), get_ptr(prinv_), get_ptr(pc_));
     // Check singularity
     double rmin;
     casadi_int irmin, nullity;
     nullity = casadi_qr_singular(&rmin, &irmin, get_ptr(m->r), sp_r_, get_ptr(pc_), eps_);
     if (nullity) {
       if (verbose_) {
         print("Singularity detected: Rank %lld<%lld\n", ncol()-nullity, ncol());
         print("First singular R entry: %g<%g, corresponding to row %lld\n", rmin, eps_, irmin);
         casadi_qr_colcomb(get_ptr(m->w), get_ptr(m->r), sp_r_, get_ptr(pc_), eps_, 0);
         print("Linear combination of columns:\n[");
         for (casadi_int k=0; k<ncol(); ++k) print(k==0 ? "%g" : ", %g", m->w[k]);
         print("]\n");
       }
       return 1;
     }
     if (cache) { // Store result in cache
       casadi_copy(A, sp_.nnz(), cache); cache+=sp_.nnz();
       casadi_copy(get_ptr(m->v), sp_v_.nnz(), cache); cache+=sp_v_.nnz();
       casadi_copy(get_ptr(m->r), sp_r_.nnz(), cache); cache+=sp_r_.nnz();
       casadi_copy(get_ptr(m->beta), ncol(), cache); cache+=ncol();
     }
     return 0;
   }
References cache_stride_, casadi::casadi_copy(), eps_, casadi::get_ptr(), n_cache_, casadi::LinsolInternal::ncol(), casadi::Sparsity::nnz(), pc_, casadi::ProtoFunction::print(), prinv_, casadi::LinsolInternal::sp_, sp_r_, sp_v_, and casadi::ProtoFunction::verbose_.
nnz()
casadi_int casadi::LinsolInternal::nnz () const inline inherited
Definition at line 140 of file linsol_internal.hpp.
 { return sp_.nnz();}
Referenced by casadi::CsparseInterface::init_mem(), casadi::Ma27Interface::init_mem(), casadi::MumpsInterface::init_mem(), casadi::SymbolicQr::linsol_eval_sx(), casadi::CsparseInterface::nfact(), casadi::Ma27Interface::nfact(), and casadi::MumpsInterface::nfact().
nrow()
casadi_int casadi::LinsolInternal::nrow () const inline inherited
Definition at line 136 of file linsol_internal.hpp.
 { return sp_.size1();}
Referenced by casadi::LinsolLdl::generate(), generate(), casadi::Lsqr::generate(), casadi::CsparseInterface::init_mem(), casadi::LapackLu::init_mem(), casadi::MumpsInterface::init_mem(), casadi::LinsolLdl::init_mem(), init_mem(), casadi::LinsolTridiag::init_mem(), casadi::Lsqr::init_mem(), casadi::LinsolLdl::neig(), casadi::LapackLu::nfact(), casadi::MumpsInterface::nfact(), casadi::LinsolLdl::rank(), casadi::LapackLu::solve(), casadi::LapackQr::solve(), casadi::LinsolTridiag::solve(), and casadi::SymbolicQr::solve().
plugin_deserialize()
Deserialize casadi::PluginInterface< LinsolInternal >::plugin_deserialize (const std::string & pname) static inherited
Definition at line 81 of file plugin_interface.hpp.
{
     Deserialize m = getPlugin(pname).deserialize;
     casadi_assert(m, "Plugin \"" + pname + "\" does not support deserialize");
     return m;
   }
plugin_name()
const char* casadi::LinsolQr::plugin_name () const inline override virtual
Implements casadi::LinsolInternal.
Definition at line 104 of file linsol_qr.hpp.
 { return "qr";}
plugin_options()
const Options & casadi::PluginInterface< LinsolInternal >::plugin_options (const std::string & pname) static inherited
Definition at line 78 of file plugin_interface.hpp.
{
     const Options *op = getPlugin(pname).options;
     casadi_assert(op!=nullptr, "Plugin \"" + pname + "\" does not support options");
     return *op;
   }
pluginFromRegFcn()
PluginInterface< LinsolInternal >::Plugin casadi::PluginInterface< LinsolInternal >::pluginFromRegFcn (RegFcn regfcn) static inherited
Definition at line 84 of file plugin_interface.hpp.
{
     // Create a temporary struct
     Plugin plugin;
     // Set the fields
     int flag = regfcn(&plugin);
     casadi_assert(flag==0, "Registration of plugin failed.");
     return plugin;
   }
print()
void casadi::ProtoFunction::print (const char * fmt, ...) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_jr
Definition at line 3763 of file function_internal.cpp.
{
     // Variable number of arguments
     va_list args;
     va_start(args, fmt);
     // Static & dynamic buffers
     char buf[256];
     size_t buf_sz = sizeof(buf);
     char* buf_dyn = nullptr;
     // Try to print with a small buffer
     casadi_int n = vsnprintf(buf, buf_sz, fmt, args);
     // Need a larger buffer?
     if (n>static_cast<casadi_int>(buf_sz)) {
       buf_sz = static_cast<size_t>(n+1);
       buf_dyn = new char[buf_sz];
       n = vsnprintf(buf_dyn, buf_sz, fmt, args);
     }
     // Print buffer content
     if (n>=0) uout() << (buf_dyn ? buf_dyn : buf) << std::flush;
     // Cleanup
     delete[] buf_dyn;
     va_end(args);
     // Throw error if failure
     casadi_assert(n>=0, "Print failure while processing '" + std::string(fmt) + "'");
   }
References casadi::uout().
Referenced by casadi::Feasiblesqpmethod::anderson_acc_step_update(), casadi::Nlpsol::callback(), casadi::Blocksqp::convertHessian(), casadi::FmuFunction::eval_task(), casadi::Feasiblesqpmethod::feasibility_iterations(), casadi::Blocksqp::feasibilityRestorationPhase(), casadi::Blocksqp::fullstep(), casadi::Blocksqp::init(), casadi::Feasiblesqpmethod::init(), casadi::Ipqp::init(), casadi::Qrqp::init(), casadi::Qrsqp::init(), casadi::Sqpmethod::init(), nfact(), casadi::Feasiblesqpmethod::print_iteration(), casadi::Qrsqp::print_iteration(), casadi::Sqpmethod::print_iteration(), casadi::SundialsInterface::print_stats(), casadi::ProtoFunction::print_time(), casadi::Blocksqp::printInfo(), casadi::Blocksqp::printProgress(), casadi::Blocksqp::run(), casadi::Blocksqp::solve(), casadi::Feasiblesqpmethod::solve(), casadi::Qrsqp::solve(), casadi::Sqpmethod::solve(), casadi::Sqpmethod::solve_ela_QP(), casadi::Feasiblesqpmethod::solve_LP(), casadi::Feasiblesqpmethod::solve_QP(), casadi::Qrsqp::solve_QP(), casadi::Sqpmethod::solve_QP(), and casadi::Blocksqp::solveQP().
print_option()
void casadi::ProtoFunction::print_option (const std::string & name, std::ostream & stream) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ji
Definition at line 911 of file function_internal.cpp.
{
     get_options().print_one(name, stream);
   }
References casadi::ProtoFunction::get_options(), and casadi::Options::print_one().
print_options()
void casadi::ProtoFunction::print_options (std::ostream & stream) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_jh
Definition at line 907 of file function_internal.cpp.
{
     get_options().print_all(stream);
   }
References casadi::ProtoFunction::get_options(), and casadi::Options::print_all().
print_time()
void casadi::ProtoFunction::print_time (const std::map< std::string, FStats > & fstats) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ju
Definition at line 3683 of file function_internal.cpp.
{
     if (!print_time_) return;
     // Length of the name being printed
     size_t name_len=0;
     for (auto &&s : fstats) {
       name_len = std::max(s.first.size(), name_len);
     }
     name_len = std::max(name_.size(), name_len);
     // Print name with a given length. Format: "%NNs "
     char namefmt[10];
     sprint(namefmt, sizeof(namefmt), "%%%ds ", static_cast<casadi_int>(name_len));
     // Print header
     print(namefmt, name_.c_str());
     print(" : %8s %10s %8s %10s %9s\n", "t_proc", "(avg)", "t_wall", "(avg)", "n_eval");
     char buffer_proc[10];
     char buffer_wall[10];
     char buffer_proc_avg[10];
     char buffer_wall_avg[10];
     // Print keys
     for (const auto &s : fstats) {
       if (s.second.n_call!=0) {
         print(namefmt, s.first.c_str());
         format_time(buffer_proc, s.second.t_proc);
         format_time(buffer_wall, s.second.t_wall);
         format_time(buffer_proc_avg, s.second.t_proc/s.second.n_call);
         format_time(buffer_wall_avg, s.second.t_wall/s.second.n_call);
         print(" | %s (%s) %s (%s) %9d\n",
           buffer_proc, buffer_proc_avg,
           buffer_wall, buffer_wall_avg, s.second.n_call);
       }
     }
   }
References casadi::ProtoFunction::format_time(), casadi::ProtoFunction::name_, casadi::ProtoFunction::print(), casadi::ProtoFunction::print_time_, and casadi::ProtoFunction::sprint().
Referenced by casadi::FunctionInternal::eval_gen().
rank()
casadi_int casadi::LinsolInternal::rank (void * mem, const double * A) const virtual inherited
Reimplemented in casadi::LinsolLdl, and casadi::Ma27Interface.
Definition at line 106 of file linsol_internal.cpp.
{
     casadi_error("'rank' not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
registerPlugin() [1/2]
void casadi::PluginInterface< LinsolInternal >::registerPlugin (const Plugin & plugin) static inherited
Definition at line 94 of file plugin_interface.hpp.
{
     // Check if the solver name is in use
     typename std::map<std::string, Plugin>::iterator it=Derived::solvers_.find(plugin.name);
     casadi_assert(it==Derived::solvers_.end(),
       "Solver " + str(plugin.name) + " is already in use");
     // Add to list of solvers
     Derived::solvers_[plugin.name] = plugin;
   }
registerPlugin() [2/2]
void casadi::PluginInterface< LinsolInternal >::registerPlugin (RegFcn regfcn) static inherited
Definition at line 97 of file plugin_interface.hpp.
{
     registerPlugin(pluginFromRegFcn(regfcn));
   }
release()
void casadi::ProtoFunction::release (int mem) const inherited
Definition at line 3560 of file function_internal.cpp.
{
 #ifdef CASADI_WITH_THREAD
     std::lock_guard<std::mutex> lock(mtx_);
 #endif //CASADI_WITH_THREAD
     unused_.push(mem);
   }
row()
const casadi_int* casadi::LinsolInternal::row () const inline inherited
Definition at line 139 of file linsol_internal.hpp.
 { return sp_.row();}
Referenced by casadi::CsparseInterface::init_mem(), casadi::MumpsInterface::init_mem(), casadi::Ma27Interface::nfact(), and casadi::MumpsInterface::nfact().
serialize()
void casadi::ProtoFunction::serialize (SerializingStream & s) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_jv
Definition at line 4039 of file function_internal.cpp.
{
     serialize_type(s);
     serialize_body(s);
   }
References casadi::ProtoFunction::serialize_body(), and casadi::ProtoFunction::serialize_type().
serialize_base_function()
virtual std::string casadi::ProtoFunction::serialize_base_function () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_jy
Reimplemented in casadi::LinearInterpolantJac, casadi::Rootfinder, casadi::Nlpsol, casadi::MapSum, casadi::Map, casadi::Interpolant, casadi::Integrator, casadi::External, and casadi::Conic.
Definition at line 229 of file function_internal.hpp.
{
       return class_name();
     }
Referenced by casadi::FunctionInternal::serialize_type().
serialize_body()
void casadi::LinsolQr::serialize_body (SerializingStream & s) const override virtual
Reimplemented from casadi::LinsolInternal.
Definition at line 234 of file linsol_qr.cpp.
{
     LinsolInternal::serialize_body(s);
     s.version("LinsolQr", 2);
     s.pack("LinsolQr::prinv", prinv_);
     s.pack("LinsolQr::pc", pc_);
     s.pack("LinsolQr::sp_v", sp_v_);
     s.pack("LinsolQr::sp_r", sp_r_);
     s.pack("LinsolQr::eps", eps_);
     s.pack("LinsolQr::n_cache", n_cache_);
   }
References eps_, n_cache_, casadi::SerializingStream::pack(), pc_, prinv_, casadi::LinsolInternal::serialize_body(), sp_r_, sp_v_, and casadi::SerializingStream::version().
serialize_type()
void casadi::LinsolInternal::serialize_type (SerializingStream & s) const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_e9
Reimplemented from casadi::ProtoFunction.
Definition at line 120 of file linsol_internal.cpp.
{
     ProtoFunction::serialize_type(s);
     PluginInterface<LinsolInternal>::serialize_type(s);
   }
References casadi::ProtoFunction::serialize_type(), and casadi::PluginInterface< Derived >::serialize_type().
sfact()
int casadi::LinsolQr::sfact (void * mem, const double * A) const override virtual
Reimplemented from casadi::LinsolInternal.
Definition at line 107 of file linsol_qr.cpp.
{
     return 0;
   }
shared_from_this() [1/2]
template<class B > B casadi::SharedObjectInternal::shared_from_this protected inherited
Template function implementations.
Definition at line 136 of file shared_object_internal.hpp.
{
     casadi_assert_dev(B::test_cast(this));
     B ret;
     ret.own(this);
     return ret;
   }
shared_from_this() [2/2]
template<class B > const B casadi::SharedObjectInternal::shared_from_this protected inherited
Definition at line 144 of file shared_object_internal.hpp.
{
     casadi_assert_dev(B::test_cast(this));
     B ret;
     ret.own(const_cast<SharedObjectInternal*>(this));
     return ret;
   }
solve()
int casadi::LinsolQr::solve (void * mem, const double * A, double * x, casadi_int nrhs, bool tr) const override virtual
Reimplemented from casadi::LinsolInternal.
Definition at line 157 of file linsol_qr.cpp.
{
     auto m = static_cast<LinsolQrMemory*>(mem);
     casadi_qr_solve(x, nrhs, tr,
                     sp_v_, get_ptr(m->v), sp_r_, get_ptr(m->r),
                     get_ptr(m->beta), get_ptr(prinv_), get_ptr(pc_), get_ptr(m->w));
     return 0;
   }
References casadi::get_ptr(), pc_, prinv_, sp_r_, and sp_v_.
sprint()
void casadi::ProtoFunction::sprint (char * buf, size_t buf_sz, const char * fmt, ...) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_js
Definition at line 3751 of file function_internal.cpp.
{
     // Variable number of arguments
     va_list args;
     va_start(args, fmt);
     // Print to buffer
     casadi_int n = vsnprintf(buf, buf_sz, fmt, args);
     // Cleanup
     va_end(args);
     // Throw error if failure
     casadi_assert(n>=0 && n<buf_sz, "Print failure while processing '" + std::string(fmt) + "'");
   }
Referenced by casadi::ProtoFunction::format_time(), and casadi::ProtoFunction::print_time().
weak()
WeakRef * casadi::SharedObjectInternal::weak () inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1ai
Definition at line 62 of file shared_object_internal.cpp.
{
     if (weak_ref_==nullptr) {
       weak_ref_ = new WeakRef(this);
     }
     return weak_ref_;
   }
Referenced by casadi::SharedObject::weak().
Member Data Documentation
cache_stride_
casadi_int casadi::LinsolQr::cache_stride_
Definition at line 119 of file linsol_qr.hpp.
Referenced by finalize(), generate(), init_mem(), and nfact().
eps_
double casadi::LinsolQr::eps_
Definition at line 115 of file linsol_qr.hpp.
Referenced by init(), LinsolQr(), nfact(), and serialize_body().
error_on_fail_
bool casadi::ProtoFunction::error_on_fail_ inherited
Definition at line 249 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::call_gen(), casadi::DaqpInterface::codegen_body(), casadi::FatropInterface::codegen_body(), casadi::HighsInterface::codegen_body(), casadi::HpipmInterface::codegen_body(), casadi::IpoptInterface::codegen_body(), casadi::MadnlpInterface::codegen_body(), casadi::OsqpInterface::codegen_body(), casadi::Qrqp::codegen_body(), casadi::Conic::Conic(), casadi::Conic::eval(), casadi::Nlpsol::eval(), casadi::Rootfinder::eval(), casadi::ProtoFunction::generate_options(), casadi::ProtoFunction::init(), casadi::Nlpsol::Nlpsol(), casadi::ProtoFunction::ProtoFunction(), casadi::Rootfinder::Rootfinder(), casadi::ProtoFunction::serialize_body(), and casadi::KinsolInterface::solve().
infix_
const std::string casadi::LinsolInternal::infix_ = "linsol" static inherited
Definition at line 130 of file linsol_internal.hpp.
meta_doc
const std::string casadi::LinsolQr::meta_doc static
Initial value:
=
      "\n"
"\n"
Definition at line 110 of file linsol_qr.hpp.
Referenced by casadi::casadi_register_linsol_qr().
n_cache_
casadi_int casadi::LinsolQr::n_cache_
Definition at line 118 of file linsol_qr.hpp.
Referenced by generate(), init(), init_mem(), LinsolQr(), nfact(), and serialize_body().
name_
std::string casadi::ProtoFunction::name_ inherited
Definition at line 234 of file function_internal.hpp.
Referenced by casadi::MXFunction::ad_forward(), casadi::MXFunction::ad_reverse(), casadi::Integrator::augmented_dae(), casadi::OracleFunction::calc_function(), casadi::FunctionInternal::call_forward(), casadi::FunctionInternal::call_reverse(), casadi::FunctionInternal::codegen_body(), casadi::External::codegen_body(), casadi::External::codegen_checkout(), casadi::External::codegen_declarations(), casadi::MXFunction::codegen_declarations(), casadi::External::codegen_decref(), casadi::External::codegen_incref(), casadi::FunctionInternal::codegen_meta(), casadi::FunctionInternal::codegen_name(), casadi::External::codegen_release(), casadi::FunctionInternal::codegen_sparsities(), casadi::ProtoFunction::construct(), casadi::OracleFunction::create_function(), casadi::FunctionInternal::definition(), casadi::FunctionInternal::eval(), casadi::MXFunction::eval(), casadi::FunctionInternal::eval_mx(), casadi::MXFunction::eval_mx(), casadi::FmuFunction::factory(), casadi::FunctionInternal::finalize(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::FunctionInternal(), casadi::Integrator::get_forward(), casadi::Integrator::get_forward_dae(), casadi::Map::get_function(), casadi::MapSum::get_function(), casadi::OracleFunction::get_function(), casadi::GenericExternal::get_jac_sparsity(), casadi::FunctionInternal::get_n_in(), casadi::External::get_n_in(), casadi::FunctionInternal::get_n_out(), casadi::External::get_n_out(), casadi::FunctionInternal::get_name_in(), casadi::External::get_name_in(), casadi::FunctionInternal::get_name_out(), casadi::External::get_name_out(), casadi::FunctionInternal::get_partition(), casadi::Integrator::get_reverse(), casadi::FunctionInternal::get_sparsity_in(), casadi::GenericExternal::get_sparsity_in(), casadi::FunctionInternal::get_sparsity_out(), casadi::GenericExternal::get_sparsity_out(), casadi::External::has_forward(), casadi::GenericExternal::has_jac_sparsity(), casadi::External::has_jacobian(), casadi::External::has_reverse(), casadi::External::init(), casadi::FunctionInternal::init(), casadi::MXFunction::init(), casadi::CvodesInterface::init(), casadi::IdasInterface::init(), casadi::External::init_external(), casadi::GenericExternal::init_external(), casadi::FunctionInternal::jac_is_symm(), casadi::FunctionInternal::jacobian(), casadi::FunctionInternal::map(), casadi::OracleFunction::monitored(), casadi::MXFunction::print_arg(), casadi::FunctionInternal::print_in(), casadi::FunctionInternal::print_out(), casadi::MXFunction::print_res(), casadi::ProtoFunction::print_time(), casadi::ProtoFunction::ProtoFunction(), casadi::CvodesInterface::reset(), casadi::IdasInterface::reset(), casadi::IdasInterface::resetB(), casadi::FunctionInternal::reverse(), casadi::ProtoFunction::serialize_body(), casadi::GurobiInterface::solve(), casadi::SnoptInterface::solve(), casadi::Integrator::sp_forward(), casadi::Integrator::sp_reverse(), casadi::FunctionInternal::wrap(), and casadi::FunctionInternal::wrap_as_needed().
options_
const Options casadi::LinsolQr::options_ static
Initial value:
= {{&LinsolInternal::options_},
     {{"eps",
       {OT_DOUBLE,
        "Minimum R entry before singularity is declared [1e-12]"}},
      {"cache",
       {OT_DOUBLE,
        "Amount of factorisations to remember (thread-local) [0]"}}
     }
  }
Definition at line 77 of file linsol_qr.hpp.
Referenced by casadi::casadi_register_linsol_qr().
pc_
std::vector<casadi_int> casadi::LinsolQr::pc_
Definition at line 113 of file linsol_qr.hpp.
Referenced by generate(), init(), LinsolQr(), nfact(), serialize_body(), and solve().
print_time_
bool casadi::ProtoFunction::print_time_ inherited
Definition at line 240 of file function_internal.hpp.
Referenced by casadi::FixedStepIntegrator::create_advanced(), casadi::ProtoFunction::generate_options(), casadi::ProtoFunction::init(), casadi::FunctionInternal::init(), casadi::Nlpsol::Nlpsol(), casadi::ProtoFunction::print_time(), casadi::ProtoFunction::ProtoFunction(), and casadi::ProtoFunction::serialize_body().
prinv_
std::vector<casadi_int> casadi::LinsolQr::prinv_
Definition at line 113 of file linsol_qr.hpp.
Referenced by generate(), init(), LinsolQr(), nfact(), serialize_body(), and solve().
record_time_
bool casadi::ProtoFunction::record_time_ inherited
Definition at line 243 of file function_internal.hpp.
Referenced by casadi::ProtoFunction::generate_options(), casadi::ProtoFunction::init(), casadi::FunctionInternal::init(), casadi::ProtoFunction::init_mem(), casadi::LinsolInternal::init_mem(), casadi::ProtoFunction::ProtoFunction(), and casadi::ProtoFunction::serialize_body().
regularity_check_
bool casadi::ProtoFunction::regularity_check_ inherited
Definition at line 246 of file function_internal.hpp.
Referenced by casadi::OracleFunction::calc_function(), casadi::ProtoFunction::change_option(), casadi::FunctionInternal::eval_gen(), casadi::FunctionInternal::FunctionInternal(), casadi::ProtoFunction::generate_options(), casadi::ProtoFunction::init(), casadi::ProtoFunction::ProtoFunction(), and casadi::ProtoFunction::serialize_body().
solvers_
std::map< std::string, LinsolInternal::Plugin > casadi::LinsolInternal::solvers_ static inherited
Definition at line 127 of file linsol_internal.hpp.
sp_
Sparsity casadi::LinsolInternal::sp_ inherited
Definition at line 157 of file linsol_internal.hpp.
Referenced by finalize(), casadi::LinsolLdl::generate(), generate(), casadi::Lsqr::generate(), casadi::LinsolLdl::init(), init(), casadi::SymbolicQr::init(), casadi::MumpsInterface::init_mem(), casadi::Lsqr::init_mem(), casadi::SymbolicQr::init_mem(), casadi::SymbolicQr::linsol_eval_sx(), casadi::LinsolInternal::LinsolInternal(), casadi::CsparseInterface::nfact(), casadi::LapackLu::nfact(), casadi::LapackQr::nfact(), casadi::LinsolLdl::nfact(), nfact(), casadi::LinsolInternal::serialize_body(), casadi::LinsolTridiag::solve(), and casadi::Lsqr::solve().
sp_r_
Sparsity casadi::LinsolQr::sp_r_
Definition at line 114 of file linsol_qr.hpp.
Referenced by finalize(), generate(), init(), init_mem(), LinsolQr(), nfact(), serialize_body(), and solve().
sp_v_
Sparsity casadi::LinsolQr::sp_v_
Definition at line 114 of file linsol_qr.hpp.
Referenced by finalize(), generate(), init(), init_mem(), LinsolQr(), nfact(), serialize_body(), and solve().
verbose_
bool casadi::ProtoFunction::verbose_ inherited
Definition at line 237 of file function_internal.hpp.
Referenced by casadi::MXFunction::ad_forward(), casadi::MXFunction::ad_reverse(), casadi::ProtoFunction::change_option(), casadi::BSplineInterpolant::construct_graph(), casadi::OracleFunction::create_function(), casadi::FmuFunction::eval(), casadi::Integrator::eval(), casadi::MXFunction::eval(), casadi::MXFunction::eval_mx(), casadi::FmuFunction::factory(), casadi::FunctionInternal::finalize(), casadi::KinsolInterface::func(), casadi::ProtoFunction::generate_options(), casadi::FmuFunction::get_forward(), casadi::Integrator::get_forward(), casadi::Integrator::get_forward_dae(), casadi::FunctionInternal::get_jac_sparsity_gen(), casadi::FunctionInternal::get_jac_sparsity_hierarchical(), casadi::FunctionInternal::get_jac_sparsity_hierarchical_symm(), casadi::FmuFunction::get_jacobian(), casadi::FunctionInternal::get_partition(), casadi::FmuFunction::get_reverse(), casadi::Integrator::get_reverse(), casadi::ProtoFunction::init(), casadi::FiniteDiff::init(), casadi::FmuFunction::init(), casadi::FunctionInternal::init(), casadi::MXFunction::init(), casadi::Blocksqp::init(), casadi::FatropConicInterface::init(), casadi::FatropInterface::init(), casadi::HpipmInterface::init(), casadi::HpmpcInterface::init(), casadi::IpoptInterface::init(), casadi::MadnlpInterface::init(), casadi::CvodesInterface::init(), casadi::IdasInterface::init(), casadi::Feasiblesqpmethod::init(), casadi::Scpgen::init(), casadi::Sqpmethod::init(), casadi::IpoptInterface::init_mem(), casadi::IdasInterface::init_mem(), casadi::BonminInterface::intermediate_callback(), casadi::OracleFunction::jit_dependencies(), casadi::CsparseInterface::nfact(), casadi::LapackLu::nfact(), casadi::LapackQr::nfact(), nfact(), casadi::ProtoFunction::ProtoFunction(), casadi::CvodesInterface::reset(), casadi::IdasInterface::reset(), casadi::IdasInterface::resetB(), casadi::ProtoFunction::serialize_body(), casadi::CbcInterface::solve(), casadi::ClpInterface::solve(), casadi::CplexInterface::solve(), casadi::GurobiInterface::solve(), casadi::HpipmInterface::solve(), casadi::QpoasesInterface::solve(), casadi::Ipqp::solve(), casadi::Qrqp::solve(), casadi::AlpaqaInterface::solve(), casadi::AmplInterface::solve(), casadi::SnoptInterface::solve(), casadi::KinsolInterface::solve(), casadi::WorhpInterface::solve(), casadi::Newton::solve(), casadi::Qrsqp::solve(), casadi::Scpgen::solve(), casadi::Sqpmethod::solve(), casadi::Sqpmethod::solve_ela_QP(), casadi::Feasiblesqpmethod::solve_LP(), casadi::Feasiblesqpmethod::solve_QP(), casadi::Qrsqp::solve_QP(), casadi::Sqpmethod::solve_QP(), casadi::Integrator::sp_forward(), and casadi::Integrator::sp_reverse().
The documentation for this class was generated from the following files:
linsol_qr.hpp
linsol_qr.cpp
linsol_qr_meta.cpp