CasADi: casadi::Matrix< Scalar > Class Template Reference
casadi::Matrix< Scalar > Class Template Reference
Sparse matrix class. SX and DM are specializations.
#include <matrix_decl.hpp>
Detailed Description
template<typename Scalar>
class casadi::Matrix< Scalar >
General sparse matrix class that is designed with the idea that "everything is a matrix", that is, also scalars and vectors.
This philosophy makes it easy to use and to interface in particularly with Python and Matlab/Octave.
Index starts with 0.
Index vec happens as follows: (rr, cc) -> k = rr+cc*size1()
Vectors are column vectors.
The storage format is Compressed Column Storage (CCS), similar to that used for sparse matrices in Matlab,
but unlike this format, we do allow for elements to be structurally non-zero but numerically zero.
Matrix<Scalar> is polymorphic with a std::vector<Scalar> that contain all non-identical-zero elements.
The sparsity can be accessed with Sparsity& sparsity()
Author
Joel Andersson
Date
2010-2014
Extra doc: https://github.com/casadi/casadi/wiki/L_18e
Definition at line 95 of file matrix_decl.hpp.
Public Types
typedef Scalar ScalarType
Scalar type.
typedef GenericMatrix< Matrix< Scalar > > B
Base class.
Public Member Functions
Matrix ()
constructors
Matrix (const Matrix< Scalar > &m)
Copy constructor.
Matrix< Scalar > & operator= (const Matrix< Scalar > &m)
Assignment (normal)
Matrix (casadi_int nrow, casadi_int ncol)
Create a sparse matrix with all structural zeros.
Matrix (const std::pair< casadi_int, casadi_int > &rc)
Create a sparse matrix with all structural zeros.
std::vector< Scalar > * operator-> ()
Access functions of the node.
const std::vector< Scalar > * operator-> () const
Const access functions of the node.
Matrix (const Sparsity &sp)
Create a sparse matrix from a sparsity pattern.
Matrix (const Sparsity &sp, const Matrix< Scalar > &d)
Construct matrix with a given sparsity and nonzeros.
Matrix (double val)
This constructor enables implicit type conversion from a numeric type.
Matrix (const std::vector< std::vector< double > > &m)
Dense matrix constructor with data given as vector of vectors.
template<typename A >
Matrix (const std::vector< A > &x)
Create an expression from a vector.
template<typename A >
Matrix (const Matrix< A > &x)
Create a matrix from another matrix with a different entry type.
Matrix (const std::vector< Scalar > &x)
Construct from a vector.
Matrix (std::initializer_list< Scalar > x)
Construct from initializer list.
const Scalar scalar () const
Convert to scalar type.
bool has_nz (casadi_int rr, casadi_int cc) const
Returns true if the matrix has a non-zero at location rr, cc.
bool __nonzero__ () const
Returns the truth value of a Matrix.
Matrix< Scalar > operator+ () const
Matrix< Scalar > operator- () const
Matrix< Scalar > printme (const Matrix< Scalar > &y) const
Matrix< Scalar > T () const
Transpose the matrix.
void print_split (std::vector< std::string > &nz, std::vector< std::string > &inter) const
Get strings corresponding to the nonzeros and the interdependencies.
void disp (std::ostream &stream, bool more=false) const
Print a representation of the object.
std::string get_str (bool more=false) const
Get string representation.
void print_scalar (std::ostream &stream) const
Print scalar.
void print_vector (std::ostream &stream, bool truncate=true) const
Print vector-style.
void print_dense (std::ostream &stream, bool truncate=true) const
Print dense matrix-stype.
void print_sparse (std::ostream &stream, bool truncate=true) const
Print sparse matrix style.
void clear ()
void resize (casadi_int nrow, casadi_int ncol)
void reserve (casadi_int nnz)
void reserve (casadi_int nnz, casadi_int ncol)
void erase (const std::vector< casadi_int > &rr, const std::vector< casadi_int > &cc, bool ind1=false)
Erase a submatrix (leaving structural zeros in its place)
void erase (const std::vector< casadi_int > &rr, bool ind1=false)
Erase a submatrix (leaving structural zeros in its place)
void remove (const std::vector< casadi_int > &rr, const std::vector< casadi_int > &cc)
Remove columns and rows.
void enlarge (casadi_int nrow, casadi_int ncol, const std::vector< casadi_int > &rr, const std::vector< casadi_int > &cc, bool ind1=false)
Enlarge matrix.
const Sparsity & sparsity () const
Const access the sparsity - reference to data member.
Sparsity get_sparsity () const
Get an owning reference to the sparsity pattern.
Matrix< Scalar > get_output (casadi_int oind) const
Get an output.
casadi_int element_hash () const
Returns a number that is unique for a given symbolic scalar.
bool is_regular () const
Checks if expression does not contain NaN or Inf.
bool is_smooth () const
Check if smooth.
bool is_leaf () const
Check if SX is a leaf of the SX graph.
bool is_commutative () const
Check whether a binary SX is commutative.
bool is_symbolic () const
Check if symbolic (Dense)
bool is_valid_input () const
Check if matrix can be used to define function inputs.
bool has_duplicates () const
Detect duplicate symbolic expressions.
void reset_input () const
Reset the marker for an input expression.
bool is_constant () const
Check if the matrix is constant (note that false negative answers are possible)
bool is_call () const
Check if function call.
bool is_output () const
Check if evaluation output.
bool has_output () const
Check if a multiple output node.
casadi_int which_output () const
Get the index of evaluation output - only valid when is_output() is true.
Function which_function () const
Get function - only valid when is_call() is true.
bool is_integer () const
Check if the matrix is integer-valued.
bool is_zero () const
check if the matrix is 0 (note that false negative answers are possible)
bool is_one () const
check if the matrix is 1 (note that false negative answers are possible)
bool is_minus_one () const
check if the matrix is -1 (note that false negative answers are possible)
bool is_eye () const
check if the matrix is an identity matrix (note that false negative answers
casadi_int op () const
Get operation type.
bool is_op (casadi_int op) const
Is it a certain operation.
bool has_zeros () const
Check if the matrix has any zero entries which are not structural zeros.
std::vector< Scalar > get_nonzeros () const
Get all nonzeros.
std::vector< Scalar > get_elements () const
Get all elements.
template<typename A >
std::vector< A > get_nonzeros () const
Get all nonzeros.
operator double () const
Type conversion to double.
operator casadi_int () const
Type conversion to casadi_int.
template<typename A >
operator std::vector< A > () const
Type conversion to a vector.
std::string name () const
Get name (only if symbolic scalar)
Matrix< Scalar > dep (casadi_int ch=0) const
Get expressions of the children of the expression.
casadi_int n_dep () const
Get the number of dependencies of a binary SXElem.
void export_code (const std::string &lang, std::ostream &stream=casadi::uout(), const Dict &options=Dict()) const
Export matrix in specific language.
Dict info () const
void serialize (std::ostream &stream) const
Serialize an object.
std::string serialize () const
Serialize.
void serialize (SerializingStream &s) const
Serialize an object.
void to_file (const std::string &filename, const std::string &format="") const
Matrix (const Sparsity &sp, const Scalar &val, bool dummy)
Sparse matrix with a given sparsity with all values same.
Matrix (const Sparsity &sp, const std::vector< Scalar > &d, bool dummy)
Sparse matrix with a given sparsity and non-zero elements.
casadi_int nnz () const
Get the number of (structural) non-zero elements.
casadi_int nnz_lower () const
Get the number of non-zeros in the lower triangular half.
casadi_int nnz_upper () const
Get the number of non-zeros in the upper triangular half.
casadi_int nnz_diag () const
Get get the number of non-zeros on the diagonal.
casadi_int numel () const
Get the number of elements.
casadi_int size1 () const
Get the first dimension (i.e. number of rows)
casadi_int rows () const
Get the number of rows, Octave-style syntax.
casadi_int size2 () const
Get the second dimension (i.e. number of columns)
casadi_int columns () const
Get the number of columns, Octave-style syntax.
std::string dim (bool with_nz=false) const
Get string representation of dimensions.
std::pair< casadi_int, casadi_int > size () const
Get the shape.
casadi_int size (casadi_int axis) const
Get the size along a particular dimensions.
bool is_empty (bool both=false) const
Check if the sparsity is empty, i.e. if one of the dimensions is zero.
bool is_dense () const
Check if the matrix expression is dense.
bool is_scalar (bool scalar_and_dense=false) const
Check if the matrix expression is scalar.
bool is_square () const
Check if the matrix expression is square.
bool is_vector () const
Check if the matrix is a row or column vector.
bool is_row () const
Check if the matrix is a row vector (i.e. size1()==1)
bool is_column () const
Check if the matrix is a column vector (i.e. size2()==1)
bool is_triu () const
Check if the matrix is upper triangular.
bool is_tril () const
Check if the matrix is lower triangular.
const Matrix< Scalar > nz (const K &k) const
Get vector nonzero or slice of nonzeros.
NonZeros< Matrix< Scalar >, K > nz (const K &k)
Access vector nonzero or slice of nonzeros.
const Matrix< Scalar > operator() (const RR &rr) const
Get vector element or slice.
const Matrix< Scalar > operator() (const RR &rr, const CC &cc) const
Get Matrix element or slice.
SubIndex< Matrix< Scalar >, RR > operator() (const RR &rr)
Access Matrix elements (one argument)
SubMatrix< Matrix< Scalar >, RR, CC > operator() (const RR &rr, const CC &cc)
Access Matrix elements (two arguments)
void get (Matrix< Scalar > &m, bool ind1, const Slice &rr) const
void get (Matrix< Scalar > &m, bool ind1, const Matrix< casadi_int > &rr) const
void get (Matrix< Scalar > &m, bool ind1, const Sparsity &sp) const
void get (Matrix< Scalar > &m, bool ind1, const Slice &rr, const Slice &cc) const
void get (Matrix< Scalar > &m, bool ind1, const Slice &rr, const Matrix< casadi_int > &cc) const
void get (Matrix< Scalar > &m, bool ind1, const Matrix< casadi_int > &rr, const Slice &cc) const
void get (Matrix< Scalar > &m, bool ind1, const Matrix< casadi_int > &rr, const Matrix< casadi_int > &cc) const
void set (const Matrix< Scalar > &m, bool ind1, const Slice &rr)
void set (const Matrix< Scalar > &m, bool ind1, const Matrix< casadi_int > &rr)
void set (const Matrix< Scalar > &m, bool ind1, const Sparsity &sp)
void set (const Matrix< Scalar > &m, bool ind1, const Slice &rr, const Slice &cc)
void set (const Matrix< Scalar > &m, bool ind1, const Slice &rr, const Matrix< casadi_int > &cc)
void set (const Matrix< Scalar > &m, bool ind1, const Matrix< casadi_int > &rr, const Slice &cc)
void set (const Matrix< Scalar > &m, bool ind1, const Matrix< casadi_int > &rr, const Matrix< casadi_int > &cc)
void get_nz (Matrix< Scalar > &m, bool ind1, const Slice &k) const
void get_nz (Matrix< Scalar > &m, bool ind1, const Matrix< casadi_int > &k) const
void set_nz (const Matrix< Scalar > &m, bool ind1, const Slice &k)
void set_nz (const Matrix< Scalar > &m, bool ind1, const Matrix< casadi_int > &k)
std::vector< Scalar > & nonzeros ()
const std::vector< Scalar > & nonzeros () const
std::vector< casadi_int > get_row () const
Get the sparsity pattern. See the Sparsity class for details.
std::vector< casadi_int > get_colind () const
Get the sparsity pattern. See the Sparsity class for details.
const casadi_int * row () const
Get the sparsity pattern. See the Sparsity class for details.
casadi_int row (casadi_int el) const
Get the sparsity pattern. See the Sparsity class for details.
const casadi_int * colind () const
Get the sparsity pattern. See the Sparsity class for details.
casadi_int colind (casadi_int col) const
Get the sparsity pattern. See the Sparsity class for details.
Static Public Member Functions
static void set_max_depth (casadi_int eq_depth=1)
Set or reset the depth to which equalities are being checked for simplifications.
static casadi_int get_max_depth ()
Get the depth to which equalities are being checked for simplifications.
static std::vector< Matrix< Scalar > > get_input (const Function &f)
Get function input.
static std::vector< Matrix< Scalar > > get_free (const Function &f)
Get free.
static std::string type_name ()
Get name of the class.
static void print_default (std::ostream &stream, const Sparsity &sp, const Scalar *nonzeros, bool truncate=true)
Print default style.
static void print_scalar (std::ostream &stream, const Scalar &e)
Print scalar.
static void print_vector (std::ostream &stream, const Sparsity &sp, const Scalar *nonzeros, bool truncate=true)
Print vector-style.
static void print_sparse (std::ostream &stream, const Sparsity &sp, const Scalar *nonzeros, bool truncate=true)
Print scalar.
static void print_split (casadi_int nnz, const Scalar *nonzeros, std::vector< std::string > &nz, std::vector< std::string > &inter)
Get strings corresponding to the nonzeros and the interdependencies.
static void print_dense (std::ostream &stream, const Sparsity &sp, const Scalar *nonzeros, bool truncate=true)
Print dense matrix-stype.
static Matrix< Scalar > eye (casadi_int n)
create an n-by-n identity matrix
static void set_precision (casadi_int precision)
Set the 'precision, width & scientific' used in printing and serializing to streams.
static void set_width (casadi_int width)
static void set_scientific (bool scientific)
static void rng (casadi_int seed)
Seed the random number generator.
static Matrix< Scalar > deserialize (std::istream &stream)
Build Sparsity from serialization.
static Matrix< Scalar > deserialize (const std::string &s)
Build Sparsity from serialization.
static Matrix< Scalar > deserialize (DeserializingStream &s)
static void to_file (const std::string &filename, const Sparsity &sp, const Scalar *nonzeros, const std::string &format="")
static Matrix< double > from_file (const std::string &filename, const std::string &format_hint="")
static Matrix< Scalar > _sym (const std::string &name, const Sparsity &sp)
static Matrix< Scalar > logsumexp (const Matrix< Scalar > &x)
static Matrix< Scalar > binary (casadi_int op, const Matrix< Scalar > &x, const Matrix< Scalar > &y)
Create nodes by their ID.
static Matrix< Scalar > unary (casadi_int op, const Matrix< Scalar > &x)
Create nodes by their ID.
static Matrix< Scalar > scalar_matrix (casadi_int op, const Matrix< Scalar > &x, const Matrix< Scalar > &y)
Create nodes by their ID.
static Matrix< Scalar > matrix_scalar (casadi_int op, const Matrix< Scalar > &x, const Matrix< Scalar > &y)
Create nodes by their ID.
static Matrix< Scalar > matrix_matrix (casadi_int op, const Matrix< Scalar > &x, const Matrix< Scalar > &y)
Create nodes by their ID.
static std::vector< Matrix< Scalar > > call (const Function &f, const std::vector< Matrix< Scalar > > &x)
Create nodes by their ID.
static std::vector< Scalar > call (const Function &f, const std::vector< Scalar > &x)
Create nodes by their ID.
static bool is_equal (const Matrix< Scalar > &x, const Matrix< Scalar > &y, casadi_int depth=0)
static Matrix< Scalar > mmin (const Matrix< Scalar > &x)
static Matrix< Scalar > mmax (const Matrix< Scalar > &x)
static Matrix< Scalar > simplify (const Matrix< Scalar > &x)
static Matrix< Scalar > jacobian (const Matrix< Scalar > &f, const Matrix< Scalar > &x, const Dict &opts=Dict())
static Sparsity jacobian_sparsity (const Matrix< Scalar > &f, const Matrix< Scalar > &x)
static Matrix< Scalar > hessian (const Matrix< Scalar > &f, const Matrix< Scalar > &x, const Dict &opts=Dict())
static Matrix< Scalar > hessian (const Matrix< Scalar > &f, const Matrix< Scalar > &x, Matrix< Scalar > &g, const Dict &opts=Dict())
static Matrix< Scalar > substitute (const Matrix< Scalar > &ex, const Matrix< Scalar > &v, const Matrix< Scalar > &vdef)
static std::vector< Matrix< Scalar > > substitute (const std::vector< Matrix< Scalar > > &ex, const std::vector< Matrix< Scalar > > &v, const std::vector< Matrix< Scalar > > &vdef)
static void substitute_inplace (const std::vector< Matrix< Scalar > > &v, std::vector< Matrix< Scalar > > &vdef, std::vector< Matrix< Scalar > > &ex, bool revers)
static Matrix< Scalar > pinv (const Matrix< Scalar > &x)
static Matrix< Scalar > pinv (const Matrix< Scalar > &A, const std::string &lsolver, const Dict &opts)
static Matrix< Scalar > expm_const (const Matrix< Scalar > &A, const Matrix< Scalar > &t)
static Matrix< Scalar > expm (const Matrix< Scalar > &A)
static Matrix< Scalar > solve (const Matrix< Scalar > &A, const Matrix< Scalar > &b)
static Matrix< Scalar > solve (const Matrix< Scalar > &A, const Matrix< Scalar > &b, const std::string &lsolver, const Dict &opts)
static Matrix< Scalar > inv (const Matrix< Scalar > &A)
static Matrix< Scalar > inv (const Matrix< Scalar > &A, const std::string &lsolver, const Dict &opts)
static casadi_int n_nodes (const Matrix< Scalar > &x)
static std::string print_operator (const Matrix< Scalar > &x, const std::vector< std::string > &args)
static void extract (std::vector< Matrix< Scalar >> &ex, std::vector< Matrix< Scalar >> &v, std::vector< Matrix< Scalar >> &vdef, const Dict &opts=Dict())
static void shared (std::vector< Matrix< Scalar > > &ex, std::vector< Matrix< Scalar > > &v, std::vector< Matrix< Scalar > > &vdef, const std::string &v_prefix, const std::string &v_suffix)
static Matrix< Scalar > _bilin (const Matrix< Scalar > &A, const Matrix< Scalar > &x, const Matrix< Scalar > &y)
static Matrix< Scalar > _rank1 (const Matrix< Scalar > &A, const Matrix< Scalar > &alpha, const Matrix< Scalar > &x, const Matrix< Scalar > &y)
static Matrix< Scalar > if_else (const Matrix< Scalar > &x, const Matrix< Scalar > &if_true, const Matrix< Scalar > &if_false, bool short_circuit=false)
static Matrix< Scalar > conditional (const Matrix< Scalar > &ind, const std::vector< Matrix< Scalar > > &x, const Matrix< Scalar > &x_default, bool short_circuit=false)
static bool depends_on (const Matrix< Scalar > &x, const Matrix< Scalar > &arg)
static bool contains (const std::vector< Matrix< Scalar > > &v, const Matrix< Scalar > &n)
static bool contains_all (const std::vector< Matrix< Scalar > > &v, const std::vector< Matrix< Scalar > > &n)
static bool contains_any (const std::vector< Matrix< Scalar > > &v, const std::vector< Matrix< Scalar > > &n)
static Matrix< Scalar > mrdivide (const Matrix< Scalar > &x, const Matrix< Scalar > &y)
static Matrix< Scalar > mldivide (const Matrix< Scalar > &x, const Matrix< Scalar > &y)
static std::vector< Matrix< Scalar > > symvar (const Matrix< Scalar > &x)
static Matrix< Scalar > det (const Matrix< Scalar > &x)
static Matrix< Scalar > inv_minor (const Matrix< Scalar > &x)
static Matrix< Scalar > trace (const Matrix< Scalar > &x)
static Matrix< Scalar > norm_1 (const Matrix< Scalar > &x)
static Matrix< Scalar > norm_2 (const Matrix< Scalar > &x)
static Matrix< Scalar > norm_fro (const Matrix< Scalar > &x)
static Matrix< Scalar > norm_inf (const Matrix< Scalar > &x)
static Matrix< Scalar > sum2 (const Matrix< Scalar > &x)
static Matrix< Scalar > sum1 (const Matrix< Scalar > &x)
static Matrix< Scalar > dot (const Matrix< Scalar > &x, const Matrix< Scalar > &y)
static Matrix< Scalar > nullspace (const Matrix< Scalar > &x)
static Matrix< Scalar > diag (const Matrix< Scalar > &x)
static Matrix< Scalar > unite (const Matrix< Scalar > &A, const Matrix< Scalar > &B)
static Matrix< Scalar > project (const Matrix< Scalar > &x, const Sparsity &sp, bool intersect=false)
static Matrix< Scalar > polyval (const Matrix< Scalar > &p, const Matrix< Scalar > &x)
static Matrix< Scalar > densify (const Matrix< Scalar > &x, const Matrix< Scalar > &val)
static Matrix< Scalar > densify (const Matrix< Scalar > &x)
static Matrix< Scalar > einstein (const Matrix< Scalar > &A, const Matrix< Scalar > &B, const Matrix< Scalar > &C, const std::vector< casadi_int > &dim_a, const std::vector< casadi_int > &dim_b, const std::vector< casadi_int > &dim_c, const std::vector< casadi_int > &a, const std::vector< casadi_int > &b, const std::vector< casadi_int > &c)
static Matrix< Scalar > einstein (const Matrix< Scalar > &A, const Matrix< Scalar > &B, const std::vector< casadi_int > &dim_a, const std::vector< casadi_int > &dim_b, const std::vector< casadi_int > &dim_c, const std::vector< casadi_int > &a, const std::vector< casadi_int > &b, const std::vector< casadi_int > &c)
static Matrix< Scalar > cumsum (const Matrix< Scalar > &x, casadi_int axis=-1)
static Matrix< Scalar > _logsumexp (const Matrix< Scalar > &x)
static std::vector< Matrix< Scalar > > cse (const std::vector< Matrix< Scalar > > &e)
static Matrix< Scalar > blockcat (const std::vector< std::vector< Matrix< Scalar > > > &v)
static Matrix< Scalar > horzcat (const std::vector< Matrix< Scalar > > &v)
static std::vector< Matrix< Scalar > > horzsplit (const Matrix< Scalar > &x, const std::vector< casadi_int > &offset)
static Matrix< Scalar > vertcat (const std::vector< Matrix< Scalar > > &v)
static std::vector< Matrix< Scalar > > vertsplit (const Matrix< Scalar > &x, const std::vector< casadi_int > &offset)
static std::vector< Matrix< Scalar > > diagsplit (const Matrix< Scalar > &x, const std::vector< casadi_int > &offset1, const std::vector< casadi_int > &offset2)
static Matrix< Scalar > reshape (const Matrix< Scalar > &x, casadi_int nrow, casadi_int ncol)
static Matrix< Scalar > reshape (const Matrix< Scalar > &x, const Sparsity &sp)
static Matrix< Scalar > sparsity_cast (const Matrix< Scalar > &x, const Sparsity &sp)
static Matrix< Scalar > kron (const Matrix< Scalar > &x, const Matrix< Scalar > &y)
static Matrix< Scalar > mtimes (const Matrix< Scalar > &x, const Matrix< Scalar > &y)
static Matrix< Scalar > mac (const Matrix< Scalar > &x, const Matrix< Scalar > &y, const Matrix< Scalar > &z)
static void extract_parametric (const Matrix< Scalar > &expr, const Matrix< Scalar > &par, Matrix< Scalar > &expr_ret, std::vector< Matrix< Scalar > > &symbols, std::vector< Matrix< Scalar >> &parametric, const Dict &opts)
static void separate_linear (const Matrix< Scalar > &expr, const Matrix< Scalar > &sym_lin, const Matrix< Scalar > &sym_const, Matrix< Scalar > &expr_const, Matrix< Scalar > &expr_lin, Matrix< Scalar > &expr_nonlin)
static Matrix< Scalar > sparsify (const Matrix< Scalar > &x, double tol=0)
static void expand (const Matrix< Scalar > &x, Matrix< Scalar > &weights, Matrix< Scalar > &terms)
static Matrix< Scalar > pw_const (const Matrix< Scalar > &t, const Matrix< Scalar > &tval, const Matrix< Scalar > &val)
static Matrix< Scalar > pw_lin (const Matrix< Scalar > &t, const Matrix< Scalar > &tval, const Matrix< Scalar > &val)
static Matrix< Scalar > heaviside (const Matrix< Scalar > &x)
static Matrix< Scalar > rectangle (const Matrix< Scalar > &x)
static Matrix< Scalar > triangle (const Matrix< Scalar > &x)
static Matrix< Scalar > ramp (const Matrix< Scalar > &x)
static Matrix< Scalar > gauss_quadrature (const Matrix< Scalar > &f, const Matrix< Scalar > &x, const Matrix< Scalar > &a, const Matrix< Scalar > &b, casadi_int order=5)
static Matrix< Scalar > gauss_quadrature (const Matrix< Scalar > &f, const Matrix< Scalar > &x, const Matrix< Scalar > &a, const Matrix< Scalar > &b, casadi_int order, const Matrix< Scalar > &w)
static std::vector< std::vector< Matrix< Scalar > > > forward (const std::vector< Matrix< Scalar > > &ex, const std::vector< Matrix< Scalar > > &arg, const std::vector< std::vector< Matrix< Scalar > > > &v, const Dict &opts=Dict())
static std::vector< std::vector< Matrix< Scalar > > > reverse (const std::vector< Matrix< Scalar > > &ex, const std::vector< Matrix< Scalar > > &arg, const std::vector< std::vector< Matrix< Scalar > > > &v, const Dict &opts=Dict())
static std::vector< bool > which_depends (const Matrix< Scalar > &expr, const Matrix< Scalar > &var, casadi_int order=1, bool tr=false)
static Matrix< Scalar > taylor (const Matrix< Scalar > &ex, const Matrix< Scalar > &x, const Matrix< Scalar > &a, casadi_int order)
static Matrix< Scalar > mtaylor (const Matrix< Scalar > &ex, const Matrix< Scalar > &x, const Matrix< Scalar > &a, casadi_int order)
static Matrix< Scalar > mtaylor (const Matrix< Scalar > &ex, const Matrix< Scalar > &x, const Matrix< Scalar > &a, casadi_int order, const std::vector< casadi_int > &order_contributions)
static Matrix< Scalar > poly_coeff (const Matrix< Scalar > &ex, const Matrix< Scalar > &x)
static Matrix< Scalar > poly_roots (const Matrix< Scalar > &p)
static Matrix< Scalar > eig_symbolic (const Matrix< Scalar > &m)
static Matrix< double > evalf (const Matrix< Scalar > &m)
static void qr_sparse (const Matrix< Scalar > &A, Matrix< Scalar > &V, Matrix< Scalar > &R, Matrix< Scalar > &beta, std::vector< casadi_int > &prinv, std::vector< casadi_int > &pc, bool amd=true)
static Matrix< Scalar > qr_solve (const Matrix< Scalar > &b, const Matrix< Scalar > &v, const Matrix< Scalar > &r, const Matrix< Scalar > &beta, const std::vector< casadi_int > &prinv, const std::vector< casadi_int > &pc, bool tr=false)
static void qr (const Matrix< Scalar > &A, Matrix< Scalar > &Q, Matrix< Scalar > &R)
static void ldl (const Matrix< Scalar > &A, Matrix< Scalar > &D, Matrix< Scalar > &LT, std::vector< casadi_int > &p, bool amd=true)
static Matrix< Scalar > ldl_solve (const Matrix< Scalar > &b, const Matrix< Scalar > &D, const Matrix< Scalar > &LT, const std::vector< casadi_int > &p)
static Matrix< Scalar > all (const Matrix< Scalar > &x)
static Matrix< Scalar > any (const Matrix< Scalar > &x)
static Matrix< Scalar > adj (const Matrix< Scalar > &x)
static Matrix< Scalar > minor (const Matrix< Scalar > &x, casadi_int i, casadi_int j)
static Matrix< Scalar > cofactor (const Matrix< Scalar > &A, casadi_int i, casadi_int j)
static Matrix< Scalar > chol (const Matrix< Scalar > &A)
static Matrix< Scalar > norm_inf_mul (const Matrix< Scalar > &x, const Matrix< Scalar > &y)
static Matrix< Scalar > diagcat (const std::vector< Matrix< Scalar > > &A)
static Matrix< Scalar > triplet (const std::vector< casadi_int > &row, const std::vector< casadi_int > &col, const Matrix< Scalar > &d)
Construct a sparse matrix from triplet form.
static Matrix< Scalar > triplet (const std::vector< casadi_int > &row, const std::vector< casadi_int > &col, const Matrix< Scalar > &d, casadi_int nrow, casadi_int ncol)
Construct a sparse matrix from triplet form.
static Matrix< Scalar > triplet (const std::vector< casadi_int > &row, const std::vector< casadi_int > &col, const Matrix< Scalar > &d, const std::pair< casadi_int, casadi_int > &rc)
Construct a sparse matrix from triplet form.
static Matrix< Scalar > inf (const Sparsity &sp)
create a matrix with all inf
static Matrix< Scalar > inf (casadi_int nrow=1, casadi_int ncol=1)
create a matrix with all inf
static Matrix< Scalar > inf (const std::pair< casadi_int, casadi_int > &rc)
create a matrix with all inf
static Matrix< Scalar > nan (const Sparsity &sp)
create a matrix with all nan
static Matrix< Scalar > nan (casadi_int nrow=1, casadi_int ncol=1)
create a matrix with all nan
static Matrix< Scalar > nan (const std::pair< casadi_int, casadi_int > &rc)
create a matrix with all nan
static Matrix< Scalar > rand (casadi_int nrow=1, casadi_int ncol=1)
Create a matrix with uniformly distributed random numbers.
static Matrix< Scalar > rand (const Sparsity &sp)
Create a matrix with uniformly distributed random numbers.
static Matrix< Scalar > rand (const std::pair< casadi_int, casadi_int > &rc)
Create a matrix with uniformly distributed random numbers.
static Matrix< Scalar > interp1d (const std::vector< double > &x, const Matrix< Scalar > &v, const std::vector< double > &xq, const std::string &mode, bool equidistant)
Functions called by friend functions defined here.
static casadi_int sprank (const Matrix< Scalar > &x)
Functions called by friend functions defined here.
static casadi_int norm_0_mul (const Matrix< Scalar > &x, const Matrix< Scalar > &y)
Functions called by friend functions defined here.
static Matrix< Scalar > tril (const Matrix< Scalar > &x, bool includeDiagonal=true)
Functions called by friend functions defined here.
static Matrix< Scalar > triu (const Matrix< Scalar > &x, bool includeDiagonal=true)
Functions called by friend functions defined here.
static Matrix< Scalar > sumsqr (const Matrix< Scalar > &x)
Functions called by friend functions defined here.
static Matrix< Scalar > linspace (const Matrix< Scalar > &a, const Matrix< Scalar > &b, casadi_int nsteps)
Functions called by friend functions defined here.
static Matrix< Scalar > cross (const Matrix< Scalar > &a, const Matrix< Scalar > &b, casadi_int dim=-1)
Functions called by friend functions defined here.
static Matrix< Scalar > skew (const Matrix< Scalar > &a)
Functions called by friend functions defined here.
static Matrix< Scalar > inv_skew (const Matrix< Scalar > &a)
Functions called by friend functions defined here.
static Matrix< Scalar > tril2symm (const Matrix< Scalar > &x)
Functions called by friend functions defined here.
static Matrix< Scalar > triu2symm (const Matrix< Scalar > &x)
Functions called by friend functions defined here.
static Matrix< Scalar > repsum (const Matrix< Scalar > &x, casadi_int n, casadi_int m=1)
Functions called by friend functions defined here.
static Matrix< Scalar > diff (const Matrix< Scalar > &x, casadi_int n=1, casadi_int axis=-1)
Functions called by friend functions defined here.
static bool is_linear (const Matrix< Scalar > &expr, const Matrix< Scalar > &var)
Functions called by friend functions defined here.
static bool is_quadratic (const Matrix< Scalar > &expr, const Matrix< Scalar > &var)
Functions called by friend functions defined here.
static void quadratic_coeff (const Matrix< Scalar > &expr, const Matrix< Scalar > &var, Matrix< Scalar > &A, Matrix< Scalar > &b, Matrix< Scalar > &c, bool check)
Functions called by friend functions defined here.
static void linear_coeff (const Matrix< Scalar > &expr, const Matrix< Scalar > &var, Matrix< Scalar > &A, Matrix< Scalar > &b, bool check)
Functions called by friend functions defined here.
static Matrix< Scalar > mpower (const Matrix< Scalar > &x, const Matrix< Scalar > &y)
static Matrix< Scalar > soc (const Matrix< Scalar > &x, const Matrix< Scalar > &y)
static Matrix< Scalar > linearize (const Matrix< Scalar > &f, const Matrix< Scalar > &x, const Matrix< Scalar > &x0, const Dict &opts=Dict())
static Matrix< Scalar > gradient (const Matrix< Scalar > &ex, const Matrix< Scalar > &arg, const Dict &opts=Dict())
static Matrix< Scalar > tangent (const Matrix< Scalar > &ex, const Matrix< Scalar > &arg, const Dict &opts=Dict())
static Matrix< Scalar > jtimes (const Matrix< Scalar > &ex, const Matrix< Scalar > &arg, const Matrix< Scalar > &v, bool tr=false, const Dict &opts=Dict())
static Matrix< Scalar > bilin (const Matrix< Scalar > &A, const Matrix< Scalar > &x, const Matrix< Scalar > &y)
Calculate bilinear/quadratic form x^T A y.
static Matrix< Scalar > rank1 (const Matrix< Scalar > &A, const Matrix< Scalar > &alpha, const Matrix< Scalar > &x, const Matrix< Scalar > &y)
Make a rank-1 update to a matrix A.
Construct symbolic primitives
The "sym" function is intended to work in a similar way as "sym" used in the Symbolic Toolbox for Matlab but instead creating a CasADi symbolic primitive.
static Matrix< Scalar > sym (const std::string &name, casadi_int nrow=1, casadi_int ncol=1)
Create an nrow-by-ncol symbolic primitive.
static Matrix< Scalar > sym (const std::string &name, const std::pair< casadi_int, casadi_int > &rc)
Construct a symbolic primitive with given dimensions.
static Matrix< Scalar > sym (const std::string &name, const Sparsity &sp)
Create symbolic primitive with a given sparsity pattern.
static std::vector< Matrix< Scalar > > sym (const std::string &name, const Sparsity &sp, casadi_int p)
Create a vector of length p with with matrices.
static std::vector< Matrix< Scalar > > sym (const std::string &name, casadi_int nrow, casadi_int ncol, casadi_int p)
Create a vector of length p with nrow-by-ncol symbolic primitives.
static std::vector< std::vector< Matrix< Scalar > > > sym (const std::string &name, const Sparsity &sp, casadi_int p, casadi_int r)
Create a vector of length r of vectors of length p with.
static std::vector< std::vector< Matrix< Scalar > > > sym (const std::string &name, casadi_int nrow, casadi_int ncol, casadi_int p, casadi_int r)
Create a vector of length r of vectors of length p.
static Matrix< Scalar > zeros (casadi_int nrow=1, casadi_int ncol=1)
Create a dense matrix or a matrix with specified sparsity with all entries zero.
static Matrix< Scalar > zeros (const Sparsity &sp)
Create a dense matrix or a matrix with specified sparsity with all entries zero.
static Matrix< Scalar > zeros (const std::pair< casadi_int, casadi_int > &rc)
Create a dense matrix or a matrix with specified sparsity with all entries zero.
static Matrix< Scalar > ones (casadi_int nrow=1, casadi_int ncol=1)
Create a dense matrix or a matrix with specified sparsity with all entries one.
static Matrix< Scalar > ones (const Sparsity &sp)
Create a dense matrix or a matrix with specified sparsity with all entries one.
static Matrix< Scalar > ones (const std::pair< casadi_int, casadi_int > &rc)
Create a dense matrix or a matrix with specified sparsity with all entries one.
Static Private Member Functions
static Matrix< Scalar > printme (const Matrix< Scalar > &x, const Matrix< Scalar > &y)
Friends
Matrix< Scalar > adj (const Matrix< Scalar > &A)
Matrix adjoint.
Matrix< Scalar > minor (const Matrix< Scalar > &x, casadi_int i, casadi_int j)
Get the (i,j) minor matrix.
Matrix< Scalar > cofactor (const Matrix< Scalar > &x, casadi_int i, casadi_int j)
Get the (i,j) cofactor matrix.
void qr (const Matrix< Scalar > &A, Matrix< Scalar > &Q, Matrix< Scalar > &R)
QR factorization using the modified Gram-Schmidt algorithm.
void qr_sparse (const Matrix< Scalar > &A, Matrix< Scalar > &V, Matrix< Scalar > &R, Matrix< Scalar > &beta, std::vector< casadi_int > &prinv, std::vector< casadi_int > &pc, bool amd=true)
Sparse direct QR factorization.
Matrix< Scalar > qr_solve (const Matrix< Scalar > &b, const Matrix< Scalar > &v, const Matrix< Scalar > &r, const Matrix< Scalar > &beta, const std::vector< casadi_int > &prinv, const std::vector< casadi_int > &pc, bool tr=false)
Solve using a sparse QR factorization.
Matrix< Scalar > chol (const Matrix< Scalar > &A)
Obtain a Cholesky factorisation of a matrix.
void ldl (const Matrix< Scalar > &A, Matrix< Scalar > &D, Matrix< Scalar > &LT, std::vector< casadi_int > &p, bool amd=true)
Sparse LDL^T factorization.
Matrix< Scalar > ldl_solve (const Matrix< Scalar > &b, const Matrix< Scalar > &D, const Matrix< Scalar > &LT, const std::vector< casadi_int > &p)
Solve using a sparse LDL^T factorization.
Matrix< Scalar > any (const Matrix< Scalar > &x)
Returns true only if any element in the matrix is true.
Matrix< Scalar > all (const Matrix< Scalar > &x)
Returns true only if every element in the matrix is true.
Matrix< Scalar > norm_inf_mul (const Matrix< Scalar > &x, const Matrix< Scalar > &y)
Inf-norm of a Matrix-Matrix product.
Matrix< Scalar > sparsify (const Matrix< Scalar > &A, double tol=0)
Make a matrix sparse by removing numerical zeros.
void expand (const Matrix< Scalar > &ex, Matrix< Scalar > &weights, Matrix< Scalar > &terms)
Expand the expression as a weighted sum (with constant weights)
Matrix< Scalar > pw_const (const Matrix< Scalar > &t, const Matrix< Scalar > &tval, const Matrix< Scalar > &val)
Create a piecewise constant function.
Matrix< Scalar > pw_lin (const Matrix< Scalar > &t, const Matrix< Scalar > &tval, const Matrix< Scalar > &val)
t a scalar variable (e.g. time)
Matrix< Scalar > heaviside (const Matrix< Scalar > &x)
Heaviside function.
Matrix< Scalar > rectangle (const Matrix< Scalar > &x)
rectangle function
Matrix< Scalar > triangle (const Matrix< Scalar > &x)
triangle function
Matrix< Scalar > ramp (const Matrix< Scalar > &x)
ramp function
Matrix< Scalar > mtaylor (const Matrix< Scalar > &ex, const Matrix< Scalar > &x, const Matrix< Scalar > &a, casadi_int order=1)
multivariate Taylor series expansion
Matrix< Scalar > mtaylor (const Matrix< Scalar > &ex, const Matrix< Scalar > &x, const Matrix< Scalar > &a, casadi_int order, const std::vector< casadi_int > &order_contributions)
multivariate Taylor series expansion
Matrix< Scalar > poly_coeff (const Matrix< Scalar > &f, const Matrix< Scalar > &x)
extracts polynomial coefficients from an expression
Matrix< Scalar > poly_roots (const Matrix< Scalar > &p)
Attempts to find the roots of a polynomial.
Matrix< Scalar > eig_symbolic (const Matrix< Scalar > &m)
Attempts to find the eigenvalues of a symbolic matrix.
Matrix< double > evalf (const Matrix< Scalar > &expr)
Evaluates the expression numerically.
Matrix< Scalar > gauss_quadrature (const Matrix< Scalar > &f, const Matrix< Scalar > &x, const Matrix< Scalar > &a, const Matrix< Scalar > &b, casadi_int order=5)
Integrate f from a to b using Gaussian quadrature with n points.
Matrix< Scalar > gauss_quadrature (const Matrix< Scalar > &f, const Matrix< Scalar > &x, const Matrix< Scalar > &a, const Matrix< Scalar > &b, casadi_int order, const Matrix< Scalar > &w)
Integrate f from a to b using Gaussian quadrature with n points.
Matrix< Scalar > taylor (const Matrix< Scalar > &ex, const Matrix< Scalar > &x, const Matrix< Scalar > &a, casadi_int order=1)
univariate Taylor series expansion
Matrix< Scalar > taylor (const Matrix< Scalar > &ex, const Matrix< Scalar > &x)
univariate Taylor series expansion
Scalar * ptr ()
const Scalar * ptr () const
Scalar * get_ptr (Matrix< Scalar > &v)
const Scalar * get_ptr (const Matrix< Scalar > &v)
Member Typedef Documentation
B
template<typename Scalar > typedef GenericMatrix<Matrix<Scalar> > casadi::Matrix< Scalar >::B
Definition at line 193 of file matrix_decl.hpp.
ScalarType
template<typename Scalar > typedef Scalar casadi::Matrix< Scalar >::ScalarType
Definition at line 190 of file matrix_decl.hpp.
Constructor & Destructor Documentation
Matrix() [1/14]
template<typename Scalar > casadi::Matrix< Scalar >::Matrix
Extra doc: https://github.com/casadi/casadi/wiki/L_18f empty 0-by-0 matrix constructor
Definition at line 576 of file matrix_impl.hpp.
                          : sparsity_(Sparsity(0, 0)) {
   }
Matrix() [2/14]
template<typename Scalar > casadi::Matrix< Scalar >::Matrix (const Matrix< Scalar > & m)
Definition at line 580 of file matrix_impl.hpp.
                                                 : sparsity_(m.sparsity_), nonzeros_(m.nonzeros_) {
   }
Matrix() [3/14]
template<typename Scalar > casadi::Matrix< Scalar >::Matrix (casadi_int nrow, casadi_int ncol)
Extra doc: https://github.com/casadi/casadi/wiki/L_18g
Matrix() [4/14]
template<typename Scalar > casadi::Matrix< Scalar >::Matrix (const std::pair< casadi_int, casadi_int > & rc) explicit
Extra doc: https://github.com/casadi/casadi/wiki/L_18h
Matrix() [5/14]
template<typename Scalar > casadi::Matrix< Scalar >::Matrix (const Sparsity & sp) explicit
Same as Matrix::ones(sparsity)
Extra doc: https://github.com/casadi/casadi/wiki/L_18k
Matrix() [6/14]
template<typename Scalar > casadi::Matrix< Scalar >::Matrix (const Sparsity & sp, const Matrix< Scalar > & d)
Extra doc: https://github.com/casadi/casadi/wiki/L_18l
Matrix() [7/14]
template<typename Scalar > casadi::Matrix< Scalar >::Matrix (double val)
Matrix() [8/14]
template<typename Scalar > casadi::Matrix< Scalar >::Matrix (const std::vector< std::vector< double > > & m) explicit
Matrix() [9/14]
template<typename Scalar > template<typename A > casadi::Matrix< Scalar >::Matrix (const std::vector< A > & x) inline
Extra doc: https://github.com/casadi/casadi/wiki/L_18m
Definition at line 161 of file matrix_decl.hpp.
                                   : sparsity_(Sparsity::dense(x.size(), 1)),
       nonzeros_(std::vector<Scalar>(x.size())) {
         auto x_it = x.begin();
         for (auto&& d : nonzeros_) d = static_cast<Scalar>(*x_it++);
     }
Matrix() [10/14]
template<typename Scalar > template<typename A > casadi::Matrix< Scalar >::Matrix (const Matrix< A > & x) inline
Assumes that the scalar conversion is valid.
Extra doc: https://github.com/casadi/casadi/wiki/L_18n
Definition at line 174 of file matrix_decl.hpp.
                                : sparsity_(x.sparsity()), nonzeros_(std::vector<Scalar>(x.nnz())) {
       auto x_it = x->begin();
       for (auto&& d : nonzeros_) d = static_cast<Scalar>(*x_it++);
     }
Matrix() [11/14]
template<typename Scalar > casadi::Matrix< Scalar >::Matrix (const std::vector< Scalar > & x)
Definition at line 584 of file matrix_impl.hpp.
                                                    :
       sparsity_(Sparsity::dense(x.size(), 1)), nonzeros_(x) {
   }
Matrix() [12/14]
template<typename Scalar > casadi::Matrix< Scalar >::Matrix (std::initializer_list< Scalar > x) inline
Definition at line 184 of file matrix_decl.hpp.
 : Matrix<Scalar>(std::vector<Scalar>(x)) {}
Matrix() [13/14]
template<typename Scalar > casadi::Matrix< Scalar >::Matrix (const Sparsity & sp, const Scalar & val, bool dummy)
Matrix() [14/14]
template<typename Scalar > casadi::Matrix< Scalar >::Matrix (const Sparsity & sp, const std::vector< Scalar > & d, bool dummy)
Member Function Documentation
__nonzero__()
bool CASADI_EXPORT casadi::SX::__nonzero__
Definition at line 70 of file matrix_impl.hpp.
{
     if (numel()!=1) {
       casadi_error("Only scalar Matrix could have a truth value, but you "
                    "provided a shape" + dim());
     }
     return nonzeros().at(0)!=0;
   }
_bilin()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::_bilin (const Matrix< Scalar > & A, const Matrix< Scalar > & x, const Matrix< Scalar > & y) static
Functions called by friend functions defined for GenericMatrix
_logsumexp()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::_logsumexp (const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
_rank1()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::_rank1 (const Matrix< Scalar > & A, const Matrix< Scalar > & alpha, const Matrix< Scalar > & x, const Matrix< Scalar > & y) static
Functions called by friend functions defined for GenericMatrix
_sym()
SX CASADI_EXPORT casadi::SX::_sym (const std::string & name, const Sparsity & sp) static
Definition at line 52 of file sx_instantiator.cpp.
{
     // Create a dense n-by-m matrix
     std::vector<SXElem> retv;
     // Check if individial names have been provided
     if (name[0]=='[') {
       // Make a copy of the string and modify it as to remove the special characters
       std::string modname = name;
       for (std::string::iterator it=modname.begin(); it!=modname.end(); ++it) {
         switch (*it) {
         case '(': case ')': case '[': case ']': case '{': case '}': case ',': case ';': *it = ' ';
         }
       }
       std::istringstream iss(modname);
       std::string varname;
       // Loop over elements
       while (!iss.fail()) {
         // Read the name
         iss >> varname;
         // Append to the return vector
         if (!iss.fail())
           retv.push_back(SXElem::sym(varname));
       }
     } else if (sp.is_scalar(true)) {
       retv.push_back(SXElem::sym(name));
     } else {
       // Scalar
       std::stringstream ss;
       for (casadi_int k=0; k<sp.nnz(); ++k) {
         ss.str("");
         ss << name << "_" << k;
         retv.push_back(SXElem::sym(ss.str()));
       }
     }
     // Determine dimensions automatically if empty
     if (sp.is_scalar(true)) {
       return SX(retv);
     } else {
       return SX(sp, retv, false);
     }
   }
References casadi::Sparsity::is_scalar(), casadi::Matrix< Scalar >::name(), casadi::Sparsity::nnz(), and casadi::SXElem::sym().
adj()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::adj (const Matrix< Scalar > & x) static
Functions called by friend functions defined here
all()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::all (const Matrix< Scalar > & x) static
Functions called by friend functions defined here
any()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::any (const Matrix< Scalar > & x) static
Functions called by friend functions defined here
bilin()
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::bilin (const Matrix< Scalar > & A, const Matrix< Scalar > & x, const Matrix< Scalar > & y) static inherited
Parameters
[in] y can be omitted, in which case x^T A x is calculated
Extra doc: https://github.com/casadi/casadi/wiki/L_1bo
binary()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::binary (casadi_int op, const Matrix< Scalar > & x, const Matrix< Scalar > & y) static
Extra doc: https://github.com/casadi/casadi/wiki/L_18o
blockcat()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::blockcat (const std::vector< std::vector< Matrix< Scalar > > > & v) static
Functions called by friend functions defined for SparsityInterface
call() [1/2]
template<typename Scalar > static std::vector< Matrix<Scalar> > casadi::Matrix< Scalar >::call (const Function & f, const std::vector< Matrix< Scalar > > & x) static
Extra doc: https://github.com/casadi/casadi/wiki/L_18o
call() [2/2]
template<typename Scalar > static std::vector< Scalar > casadi::Matrix< Scalar >::call (const Function & f, const std::vector< Scalar > & x) static
Extra doc: https://github.com/casadi/casadi/wiki/L_18o
chol()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::chol (const Matrix< Scalar > & A) static
Functions called by friend functions defined here
clear()
template<typename Scalar > void casadi::Matrix< Scalar >::clear ()
cofactor()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::cofactor (const Matrix< Scalar > & A, casadi_int i, casadi_int j) static
Functions called by friend functions defined here
colind() [1/2]
const casadi_int* casadi::GenericMatrix< Matrix< Scalar > >::colind () const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1b8
Definition at line 198 of file generic_matrix.hpp.
 { return sparsity().colind(); }
colind() [2/2]
casadi_int casadi::GenericMatrix< Matrix< Scalar > >::colind (casadi_int col) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1b8
Definition at line 201 of file generic_matrix.hpp.
 { return sparsity().colind(col); }
columns()
casadi_int casadi::GenericMatrix< Matrix< Scalar > >::columns () const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1av
Definition at line 124 of file generic_matrix.hpp.
 {return size2();}
conditional()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::conditional (const Matrix< Scalar > & ind, const std::vector< Matrix< Scalar > > & x, const Matrix< Scalar > & x_default, bool short_circuit = false) static
Functions called by friend functions defined for GenericMatrix
contains()
template<typename Scalar > static bool casadi::Matrix< Scalar >::contains (const std::vector< Matrix< Scalar > > & v, const Matrix< Scalar > & n) static
Functions called by friend functions defined for GenericMatrix
contains_all()
template<typename Scalar > static bool casadi::Matrix< Scalar >::contains_all (const std::vector< Matrix< Scalar > > & v, const std::vector< Matrix< Scalar > > & n) static
Functions called by friend functions defined for GenericMatrix
contains_any()
template<typename Scalar > static bool casadi::Matrix< Scalar >::contains_any (const std::vector< Matrix< Scalar > > & v, const std::vector< Matrix< Scalar > > & n) static
Functions called by friend functions defined for GenericMatrix
cross()
Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::cross (const Matrix< Scalar > & a, const Matrix< Scalar > & b, casadi_int dim = -1) static inherited
Definition at line 227 of file generic_matrix.hpp.
{
     casadi_assert(a.size1()==b.size1() && a.size2()==b.size2(),
       "cross(a, b): Inconsistent dimensions. Dimension of a ("
       + a.dim() + " ) must equal that of b (" + b.dim() + ").");
     casadi_assert(a.size1()==3 || a.size2()==3,
       "cross(a, b): One of the dimensions of a should have length 3, but got "
         + a.dim() + ".");
     casadi_assert(dim==-1 || dim==1 || dim==2,
       "cross(a, b, dim): Dim must be 1, 2 or -1 (automatic).");
     std::vector<MatType> ret(3);
     bool t = a.size1()==3;
     if (dim==1) t = true;
     if (dim==2) t = false;
     MatType a1 = t ? a(0, Slice()) : a(Slice(), 0);
     MatType a2 = t ? a(1, Slice()) : a(Slice(), 1);
     MatType a3 = t ? a(2, Slice()) : a(Slice(), 2);
     MatType b1 = t ? b(0, Slice()) : b(Slice(), 0);
     MatType b2 = t ? b(1, Slice()) : b(Slice(), 1);
     MatType b3 = t ? b(2, Slice()) : b(Slice(), 2);
     ret[0] = a2*b3-a3*b2;
     ret[1] = a3*b1-a1*b3;
     ret[2] = a1*b2-a2*b1;
     return t ? vertcat(ret) : horzcat(ret);
   }
cse()
template<typename Scalar > static std::vector< Matrix<Scalar> > casadi::Matrix< Scalar >::cse (const std::vector< Matrix< Scalar > > & e) static
Functions called by friend functions defined for GenericMatrix
cumsum()
template<typename Scalar > Matrix< Scalar > casadi::Matrix< Scalar >::cumsum (const Matrix< Scalar > & x, casadi_int axis = -1) static
Functions called by friend functions defined for GenericMatrix
Definition at line 527 of file matrix_impl.hpp.
{
     if (axis==-1) axis = x.is_row();
     Matrix<Scalar> ret = x;
     if (axis==0) {
       for (casadi_int i=1;i<x.size1();++i)
         ret(i, Slice()) += ret(i-1, Slice());
     } else {
       for (casadi_int i=1;i<x.size2();++i)
         ret(Slice(), i) += ret(Slice(), i-1);
     }
     return ret;
   }
References casadi::GenericMatrix< MatType >::is_row(), casadi::GenericMatrix< MatType >::size1(), and casadi::GenericMatrix< MatType >::size2().
densify() [1/2]
template<typename Scalar > Matrix< Scalar > casadi::Matrix< Scalar >::densify (const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
Definition at line 492 of file matrix_impl.hpp.
{
     return densify(x, 0);
   }
densify() [2/2]
template<typename Scalar > Matrix< Scalar > casadi::Matrix< Scalar >::densify (const Matrix< Scalar > & x, const Matrix< Scalar > & val) static
Functions called by friend functions defined for GenericMatrix
Definition at line 497 of file matrix_impl.hpp.
{
     // Check argument
     casadi_assert_dev(val.is_scalar());
     // Quick return if possible
     if (x.is_dense()) return x;
     // Get sparsity pattern
     casadi_int nrow = x.size1();
     casadi_int ncol = x.size2();
     const casadi_int* colind = x.colind();
     const casadi_int* row = x.row();
     auto it = x.nonzeros().cbegin();
     // New data vector
     std::vector<Scalar> d(nrow*ncol, val.scalar());
     // Copy nonzeros
     for (casadi_int cc=0; cc<ncol; ++cc) {
       for (casadi_int el=colind[cc]; el<colind[cc+1]; ++el) {
         d[cc*nrow + row[el]] = *it++;
       }
     }
     // Construct return matrix
     return Matrix<Scalar>(Sparsity::dense(x.size()), d);
   }
References casadi::GenericMatrix< MatType >::colind(), casadi::Sparsity::dense(), casadi::GenericMatrix< MatType >::is_dense(), casadi::GenericMatrix< MatType >::is_scalar(), casadi::Matrix< Scalar >::nonzeros(), casadi::GenericMatrix< MatType >::row(), casadi::Matrix< Scalar >::scalar(), casadi::GenericMatrix< MatType >::size(), casadi::GenericMatrix< MatType >::size1(), and casadi::GenericMatrix< MatType >::size2().
dep()
SX CASADI_EXPORT casadi::SX::dep (casadi_int ch = 0) const
Only defined if symbolic scalar. Wraps SXElem SXElem::dep(casadi_int ch=0) const.
Extra doc: https://github.com/casadi/casadi/wiki/L_1a9
Definition at line 223 of file sx_instantiator.cpp.
{
     return scalar().dep(ch);
   }
References casadi::Matrix< Scalar >::scalar().
depends_on()
template<typename Scalar > static bool casadi::Matrix< Scalar >::depends_on (const Matrix< Scalar > & x, const Matrix< Scalar > & arg) static
Functions called by friend functions defined for GenericMatrix
deserialize() [1/3]
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::deserialize (const std::string & s) static
Extra doc: https://github.com/casadi/casadi/wiki/L_1ag
deserialize() [2/3]
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::deserialize (DeserializingStream & s) static
deserialize() [3/3]
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::deserialize (std::istream & stream) static
Extra doc: https://github.com/casadi/casadi/wiki/L_1af
Referenced by casadi::DeserializingStream::unpack().
det()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::det (const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
diag()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::diag (const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
diagcat()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::diagcat (const std::vector< Matrix< Scalar > > & A) static
Functions called by friend functions defined here
diagsplit()
template<typename Scalar > static std::vector< Matrix<Scalar> > casadi::Matrix< Scalar >::diagsplit (const Matrix< Scalar > & x, const std::vector< casadi_int > & offset1, const std::vector< casadi_int > & offset2) static
Functions called by friend functions defined for SparsityInterface
diff()
Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::diff (const Matrix< Scalar > & x, casadi_int n = 1, casadi_int axis = -1) static inherited
Definition at line 233 of file generic_matrix.hpp.
{
     casadi_assert(axis==-1 || axis==0 || axis==1, "Axis argument invalid");
     casadi_assert(n>=1, "n argument invalid");
     MatType ret = x;
     for (casadi_int i=0;i<n;++i) {
       // Matlab's special case
       if (axis==-1 && ret.is_scalar()) return MatType();
       casadi_int local_axis = (axis==-1) ? ret.is_row() : axis;
       if (local_axis==0) {
         if (ret.size1()<=1) {
           ret = MatType::zeros(0, ret.size2());
         } else {
           ret = ret(Slice(1, ret.size1()), Slice())-ret(Slice(0, ret.size1()-1), Slice());
         }
       } else {
         if (ret.size2()<=1) {
           ret = MatType::zeros(ret.size1(), 0);
         } else {
           ret = ret(Slice(), Slice(1, ret.size2()))-ret(Slice(), Slice(0, ret.size2()-1));
         }
       }
     }
     return ret;
   }
dim()
std::string casadi::GenericMatrix< Matrix< Scalar > >::dim (bool with_nz = false) const inherited
The representation is e.g. "4x5" or "4x5,10nz"
Extra doc: https://github.com/casadi/casadi/wiki/L_1aw
Definition at line 131 of file generic_matrix.hpp.
{
     return sparsity().dim(with_nz);
   }
disp()
template<typename Scalar > void casadi::Matrix< Scalar >::disp (std::ostream & stream, bool more = false) const
dot()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::dot (const Matrix< Scalar > & x, const Matrix< Scalar > & y) static
Functions called by friend functions defined for GenericMatrix
eig_symbolic()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::eig_symbolic (const Matrix< Scalar > & m) static
Functions called by friend functions defined here
einstein() [1/2]
template<typename Scalar > Matrix< Scalar > casadi::Matrix< Scalar >::einstein (const Matrix< Scalar > & A, const Matrix< Scalar > & B, const Matrix< Scalar > & C, const std::vector< casadi_int > & dim_a, const std::vector< casadi_int > & dim_b, const std::vector< casadi_int > & dim_c, const std::vector< casadi_int > & a, const std::vector< casadi_int > & b, const std::vector< casadi_int > & c) static
Functions called by friend functions defined for GenericMatrix
Definition at line 541 of file matrix_impl.hpp.
{
     std::vector<casadi_int> iter_dims;
     std::vector<casadi_int> strides_a;
     std::vector<casadi_int> strides_b;
     std::vector<casadi_int> strides_c;
     casadi_int n_iter = einstein_process(A, B, C, dim_a, dim_b, dim_c, a, b, c,
           iter_dims, strides_a, strides_b, strides_c);
     const std::vector<Scalar>& Av = A.nonzeros();
     const std::vector<Scalar>& Bv = B.nonzeros();
     Matrix<Scalar> ret = C;
     std::vector<Scalar>& Cv = ret.nonzeros();
     einstein_eval(n_iter, iter_dims, strides_a, strides_b, strides_c,
       get_ptr(Av), get_ptr(Bv), get_ptr(Cv));
     return ret;
   }
References casadi::C, casadi::einstein_eval(), casadi::einstein_process(), casadi::get_ptr(), and casadi::Matrix< Scalar >::nonzeros().
Referenced by casadi::Matrix< Scalar >::einstein().
einstein() [2/2]
template<typename Scalar > Matrix< Scalar > casadi::Matrix< Scalar >::einstein (const Matrix< Scalar > & A, const Matrix< Scalar > & B, const std::vector< casadi_int > & dim_a, const std::vector< casadi_int > & dim_b, const std::vector< casadi_int > & dim_c, const std::vector< casadi_int > & a, const std::vector< casadi_int > & b, const std::vector< casadi_int > & c) static
Functions called by friend functions defined for GenericMatrix
Definition at line 566 of file matrix_impl.hpp.
{
     return Matrix<Scalar>::einstein(A, B, Matrix<Scalar>::zeros(product(dim_c), 1),
       dim_a, dim_b, dim_c, a, b, c);
   }
References casadi::Matrix< Scalar >::einstein(), and casadi::product().
element_hash()
casadi_int CASADI_EXPORT casadi::SX::element_hash
Only defined if symbolic scalar.
Extra doc: https://github.com/casadi/casadi/wiki/L_19n
Definition at line 126 of file sx_instantiator.cpp.
{
     return scalar().__hash__();
   }
References casadi::Matrix< Scalar >::scalar().
enlarge()
template<typename Scalar > void casadi::Matrix< Scalar >::enlarge (casadi_int nrow, casadi_int ncol, const std::vector< casadi_int > & rr, const std::vector< casadi_int > & cc, bool ind1 = false)
Make the matrix larger by inserting empty rows and columns, keeping the existing non-zeros
Extra doc: https://github.com/casadi/casadi/wiki/L_19i
erase() [1/2]
template<typename Scalar > void casadi::Matrix< Scalar >::erase (const std::vector< casadi_int > & rr, bool ind1 = false)
Erase elements of a matrix
Extra doc: https://github.com/casadi/casadi/wiki/L_19g
erase() [2/2]
template<typename Scalar > void casadi::Matrix< Scalar >::erase (const std::vector< casadi_int > & rr, const std::vector< casadi_int > & cc, bool ind1 = false)
Erase rows and/or columns of a matrix
Extra doc: https://github.com/casadi/casadi/wiki/L_19f
evalf()
template<typename Scalar > static Matrix<double> casadi::Matrix< Scalar >::evalf (const Matrix< Scalar > & m) static
Functions called by friend functions defined here
expand()
template<typename Scalar > static void casadi::Matrix< Scalar >::expand (const Matrix< Scalar > & x, Matrix< Scalar > & weights, Matrix< Scalar > & terms) static
Functions called by friend functions defined here
expm()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::expm (const Matrix< Scalar > & A) static
Functions called by friend functions defined for GenericMatrix
expm_const()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::expm_const (const Matrix< Scalar > & A, const Matrix< Scalar > & t) static
Functions called by friend functions defined for GenericMatrix
export_code()
template<typename Scalar > void casadi::Matrix< Scalar >::export_code (const std::string & lang, std::ostream & stream = casadi::uout(), const Dict & options = Dict()) const
lang: only 'matlab' supported for now
* options:
*   inline: Indicates if you want everything on a single line (default: False)
*   name: Name of exported variable (default: 'm')
*   indent_level: Level of indentation (default: 0)
*   spoof_zero: Replace numerical zero by a 1e-200 (default: false)
*               might be needed for matlab sparse construct,
*               which doesn't allow numerical zero
*
Extra doc: https://github.com/casadi/casadi/wiki/L_1ac
Referenced by casadi::MXFunction::export_code_body().
extract()
template<typename Scalar > static void casadi::Matrix< Scalar >::extract (std::vector< Matrix< Scalar >> & ex, std::vector< Matrix< Scalar >> & v, std::vector< Matrix< Scalar >> & vdef, const Dict & opts = Dict()) static
Functions called by friend functions defined for GenericMatrix
extract_parametric()
template<typename Scalar > static void casadi::Matrix< Scalar >::extract_parametric (const Matrix< Scalar > & expr, const Matrix< Scalar > & par, Matrix< Scalar > & expr_ret, std::vector< Matrix< Scalar > > & symbols, std::vector< Matrix< Scalar >> & parametric, const Dict & opts) static
Functions called by friend functions defined for SparsityInterface
eye()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::eye (casadi_int n) static
Extra doc: https://github.com/casadi/casadi/wiki/L_19m
forward()
template<typename Scalar > static std::vector<std::vector<Matrix<Scalar> > > casadi::Matrix< Scalar >::forward (const std::vector< Matrix< Scalar > > & ex, const std::vector< Matrix< Scalar > > & arg, const std::vector< std::vector< Matrix< Scalar > > > & v, const Dict & opts = Dict()) static
Functions called by friend functions defined here
from_file()
template<typename Scalar > static Matrix<double> casadi::Matrix< Scalar >::from_file (const std::string & filename, const std::string & format_hint = "") static
gauss_quadrature() [1/2]
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::gauss_quadrature (const Matrix< Scalar > & f, const Matrix< Scalar > & x, const Matrix< Scalar > & a, const Matrix< Scalar > & b, casadi_int order, const Matrix< Scalar > & w) static
Functions called by friend functions defined here
gauss_quadrature() [2/2]
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::gauss_quadrature (const Matrix< Scalar > & f, const Matrix< Scalar > & x, const Matrix< Scalar > & a, const Matrix< Scalar > & b, casadi_int order = 5) static
Functions called by friend functions defined here
get() [1/7]
template<typename Scalar > void casadi::Matrix< Scalar >::get (Matrix< Scalar > & m, bool ind1, const Matrix< casadi_int > & rr) const
Get a submatrix, single argument
Definition at line 152 of file matrix_impl.hpp.
{
     // Scalar
     if (rr.is_scalar(true)) {
       return get(m, ind1, to_slice(rr, ind1));
     }
     // If the indexed matrix is dense, use nonzero indexing
     if (is_dense()) {
       return get_nz(m, ind1, rr);
     }
     // Get the sparsity pattern - does bounds checking
     std::vector<casadi_int> mapping;
     Sparsity sp = sparsity().sub(rr.nonzeros(), rr.sparsity(), mapping, ind1);
     // If indexed matrix was a row/column vector, make sure that the result is too
     bool tr = (is_column() && rr.is_row()) || (is_row() && rr.is_column());
     // Copy nonzeros
     m = Matrix<Scalar>::zeros(tr ? sp.T() : sp);
     for (casadi_int k=0; k<mapping.size(); ++k) m->at(k) = nonzeros().at(mapping[k]);
   }
References casadi::GenericMatrix< MatType >::is_column(), casadi::GenericMatrix< MatType >::is_row(), casadi::GenericMatrix< MatType >::is_scalar(), casadi::Matrix< Scalar >::nonzeros(), casadi::Matrix< Scalar >::sparsity(), casadi::Sparsity::sub(), casadi::Sparsity::T(), casadi::to_slice(), and casadi::GenericMatrix< Matrix< Scalar > >::zeros().
get() [2/7]
template<typename Scalar > void casadi::Matrix< Scalar >::get (Matrix< Scalar > & m, bool ind1, const Matrix< casadi_int > & rr, const Matrix< casadi_int > & cc) const
Get a submatrix, two arguments
Definition at line 111 of file matrix_impl.hpp.
{
     // Scalar
     if (rr.is_scalar(true) && cc.is_scalar(true)) {
       return get(m, ind1, to_slice(rr, ind1), to_slice(cc, ind1));
     }
     // Make sure dense vectors
     casadi_assert(rr.is_dense() && rr.is_vector(),
                           "Marix::get: First index must be a dense vector");
     casadi_assert(cc.is_dense() && cc.is_vector(),
                           "Marix::get: Second index must be a dense vector");
     // Get the sparsity pattern - does bounds checking
     std::vector<casadi_int> mapping;
     Sparsity sp = sparsity().sub(rr.nonzeros(), cc.nonzeros(), mapping, ind1);
     // Copy nonzeros
     m = Matrix<Scalar>::zeros(sp);
     for (casadi_int k=0; k<mapping.size(); ++k) m->at(k) = nonzeros().at(mapping[k]);
   }
get() [3/7]
template<typename Scalar > void casadi::Matrix< Scalar >::get (Matrix< Scalar > & m, bool ind1, const Matrix< casadi_int > & rr, const Slice & cc) const
Get a submatrix, two arguments
Definition at line 104 of file matrix_impl.hpp.
{
     // Fall back on IM-IM
     get(m, ind1, rr, cc.all(size2(), ind1));
   }
get() [4/7]
template<typename Scalar > void casadi::Matrix< Scalar >::get (Matrix< Scalar > & m, bool ind1, const Slice & rr) const
Get a submatrix, single argument
Definition at line 134 of file matrix_impl.hpp.
{
     // Scalar
     if (rr.is_scalar(numel())) {
       casadi_int r = rr.scalar(numel());
       casadi_int k = sparsity().get_nz(r % size1(), r / size1());
       if (k>=0) {
         m = nonzeros().at(k);
       } else {
         m = Matrix<Scalar>(1, 1);
       }
       return;
     }
     // Fall back on IM
     get(m, ind1, rr.all(numel(), ind1));
   }
get() [5/7]
template<typename Scalar > void casadi::Matrix< Scalar >::get (Matrix< Scalar > & m, bool ind1, const Slice & rr, const Matrix< casadi_int > & cc) const
Get a submatrix, two arguments
Definition at line 97 of file matrix_impl.hpp.
{
     // Fall back on IM-IM
     get(m, ind1, rr.all(size1(), ind1), cc);
   }
References casadi::Slice::all().
get() [6/7]
template<typename Scalar > void casadi::Matrix< Scalar >::get (Matrix< Scalar > & m, bool ind1, const Slice & rr, const Slice & cc) const
Get a submatrix, two arguments
Definition at line 79 of file matrix_impl.hpp.
{
     // Both are scalar
     if (rr.is_scalar(size1()) && cc.is_scalar(size2())) {
       casadi_int k = sparsity().get_nz(rr.scalar(size1()), cc.scalar(size2()));
       if (k>=0) {
         m = nonzeros().at(k);
       } else {
         m = Matrix<Scalar>(1, 1);
       }
       return;
     }
     // Fall back on IM-IM
     get(m, ind1, rr.all(size1(), ind1), cc.all(size2(), ind1));
   }
References casadi::Slice::all(), casadi::Slice::is_scalar(), and casadi::Slice::scalar().
get() [7/7]
template<typename Scalar > void casadi::Matrix< Scalar >::get (Matrix< Scalar > & m, bool ind1, const Sparsity & sp) const
Get a submatrix, single argument
Definition at line 176 of file matrix_impl.hpp.
{
     casadi_assert(size()==sp.size(),
                           "Shape mismatch. This matrix has shape "
                           + str(size()) + ", but supplied sparsity index has shape "
                           + str(sp.size()) + ".");
     m = project(*this, sp);
   }
References casadi::Sparsity::size(), and casadi::str().
get_colind()
std::vector<casadi_int> casadi::GenericMatrix< Matrix< Scalar > >::get_colind () const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1b8
Definition at line 195 of file generic_matrix.hpp.
 { return sparsity().get_colind(); }
get_elements()
template<typename Scalar > std::vector<Scalar> casadi::Matrix< Scalar >::get_elements () const
Extra doc: https://github.com/casadi/casadi/wiki/L_1a3
Referenced by casadi::OptiNode::show_infeasibilities().
get_free()
std::vector< SX > CASADI_EXPORT casadi::SX::get_free (const Function & f) static
Extra doc: https://github.com/casadi/casadi/wiki/L_19e
Definition at line 1554 of file sx_instantiator.cpp.
{
     return f.free_sx();
   }
References casadi::Function::free_sx().
get_input()
std::vector< SX > CASADI_EXPORT casadi::SX::get_input (const Function & f) static
Extra doc: https://github.com/casadi/casadi/wiki/L_19d
Definition at line 1550 of file sx_instantiator.cpp.
{
     return f.sx_in();
   }
References casadi::Function::sx_in().
get_max_depth()
casadi_int CASADI_EXPORT casadi::SX::get_max_depth static
Extra doc: https://github.com/casadi/casadi/wiki/L_19c
Definition at line 47 of file sx_instantiator.cpp.
{
     return SXNode::eq_depth_;
   }
References casadi::SXNode::eq_depth_.
get_nonzeros() [1/2]
template<typename Scalar > std::vector< A > casadi::Matrix< Scalar >::get_nonzeros () const
Implementation of Matrix::get_nonzeros (in public API)
Extra doc: https://github.com/casadi/casadi/wiki/L_1a2
Definition at line 1392 of file matrix_decl.hpp.
{
     std::vector<A> ret(nnz());
     auto r = ret.begin();
     for (auto&& e : nonzeros()) *r++ = static_cast<A>(e);
     return ret;
   }
get_nonzeros() [2/2]
template<typename Scalar > template<typename A > std::vector<A> casadi::Matrix< Scalar >::get_nonzeros () const
Extra doc: https://github.com/casadi/casadi/wiki/L_1a4
get_nz() [1/2]
template<typename Scalar > void casadi::Matrix< Scalar >::get_nz (Matrix< Scalar > & m, bool ind1, const Matrix< casadi_int > & k) const
Get a set of nonzeros
Definition at line 406 of file matrix_impl.hpp.
{
     // Scalar
     if (kk.is_scalar(true)) {
       return get_nz(m, ind1, to_slice(kk, ind1));
     }
     // Get nonzeros of kk
     const std::vector<casadi_int>& k = kk.nonzeros();
     casadi_int sz = nnz();
     // Check bounds
     casadi_assert_in_range(k, -sz+ind1, sz+ind1);
     // If indexed matrix was a row/column vector, make sure that the result is too
     bool tr = (is_column() && kk.is_row()) || (is_row() && kk.is_column());
     // Copy nonzeros
     m = zeros(tr ? kk.sparsity().T() : kk.sparsity());
     for (casadi_int el=0; el<k.size(); ++el) {
       casadi_assert(!(ind1 && k[el]<=0), "Matlab is 1-based, but requested index "
                                                 + str(k[el]) + ". Note that negative slices are"
                                                 " disabled in the Matlab interface. "
                                                 "Possibly you may want to use 'end'.");
       casadi_int k_el = k[el]-ind1;
       m->at(el) = nonzeros().at(k_el>=0 ? k_el : k_el+sz);
     }
   }
get_nz() [2/2]
template<typename Scalar > void casadi::Matrix< Scalar >::get_nz (Matrix< Scalar > & m, bool ind1, const Slice & k) const
Get a set of nonzeros
Definition at line 394 of file matrix_impl.hpp.
{
     // Scalar
     if (kk.is_scalar(nnz())) {
       m = nonzeros().at(kk.scalar(nnz()));
       return;
     }
     // Fall back on IM
     get_nz(m, ind1, kk.all(nnz(), ind1));
   }
get_output()
SX CASADI_EXPORT casadi::SX::get_output (casadi_int oind) const
Extra doc: https://github.com/casadi/casadi/wiki/L_28i
Definition at line 165 of file sx_instantiator.cpp.
{
     return scalar().get_output(oind);
   }
References casadi::Matrix< Scalar >::scalar().
get_row()
std::vector<casadi_int> casadi::GenericMatrix< Matrix< Scalar > >::get_row () const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1b8
Definition at line 194 of file generic_matrix.hpp.
 { return sparsity().get_row(); }
get_sparsity()
template<typename Scalar > Sparsity casadi::Matrix< Scalar >::get_sparsity () const
Extra doc: https://github.com/casadi/casadi/wiki/L_19j
get_str()
template<typename Scalar > std::string casadi::Matrix< Scalar >::get_str (bool more = false) const
Referenced by casadi::ConstantFile::disp(), and casadi::ConstantPool::disp().
gradient()
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::gradient (const Matrix< Scalar > & ex, const Matrix< Scalar > & arg, const Dict & opts = Dict()) static inherited
Functions called by friend functions defined here
has_duplicates()
bool CASADI_EXPORT casadi::SX::has_duplicates
If there are symbolic primitives appearing more than once, the function will return true and the names of the duplicate expressions will be passed to casadi_warning. Note: Will mark the node using SXElem::set_temp. Make sure to call reset_input() after usage.
Extra doc: https://github.com/casadi/casadi/wiki/L_19t
Definition at line 198 of file sx_instantiator.cpp.
{
     bool has_duplicates = false;
     for (auto&& i : nonzeros_) {
       bool is_duplicate = i.get_temp()!=0;
       if (is_duplicate) {
         casadi_warning("Duplicate expression: " + str(i));
       }
       has_duplicates = has_duplicates || is_duplicate;
       i.set_temp(1);
     }
     return has_duplicates;
   }
References casadi::str().
has_nz()
template<typename Scalar > bool casadi::Matrix< Scalar >::has_nz (casadi_int rr, casadi_int cc) const
Definition at line 65 of file matrix_impl.hpp.
{
     return sparsity().has_nz(rr, cc);
   }
has_output()
bool CASADI_EXPORT casadi::SX::has_output
Extra doc: https://github.com/casadi/casadi/wiki/L_28l
Definition at line 160 of file sx_instantiator.cpp.
{
     return scalar().has_output();
   }
References casadi::Matrix< Scalar >::scalar().
has_zeros()
template<typename Scalar > bool casadi::Matrix< Scalar >::has_zeros () const
Extra doc: https://github.com/casadi/casadi/wiki/L_1a1
heaviside()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::heaviside (const Matrix< Scalar > & x) static
Functions called by friend functions defined here
hessian() [1/2]
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::hessian (const Matrix< Scalar > & f, const Matrix< Scalar > & x, const Dict & opts = Dict()) static
Functions called by friend functions defined for GenericMatrix
hessian() [2/2]
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::hessian (const Matrix< Scalar > & f, const Matrix< Scalar > & x, Matrix< Scalar > & g, const Dict & opts = Dict()) static
Functions called by friend functions defined for GenericMatrix
horzcat()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::horzcat (const std::vector< Matrix< Scalar > > & v) static
Functions called by friend functions defined for SparsityInterface
horzsplit()
template<typename Scalar > static std::vector<Matrix<Scalar> > casadi::Matrix< Scalar >::horzsplit (const Matrix< Scalar > & x, const std::vector< casadi_int > & offset) static
Functions called by friend functions defined for SparsityInterface
if_else()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::if_else (const Matrix< Scalar > & x, const Matrix< Scalar > & if_true, const Matrix< Scalar > & if_false, bool short_circuit = false) static
Functions called by friend functions defined for GenericMatrix
inf() [1/3]
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::inf (casadi_int nrow = 1, casadi_int ncol = 1) static
Extra doc: https://github.com/casadi/casadi/wiki/L_19k
inf() [2/3]
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::inf (const Sparsity & sp) static
Extra doc: https://github.com/casadi/casadi/wiki/L_19k
inf() [3/3]
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::inf (const std::pair< casadi_int, casadi_int > & rc) static
Extra doc: https://github.com/casadi/casadi/wiki/L_19k
info()
Dict CASADI_EXPORT casadi::SX::info
Obtain information about sparsity
Definition at line 1559 of file sx_instantiator.cpp.
{
     return {{"function", Function("f", std::vector<SX>{}, std::vector<SX>{*this})}};
   }
interp1d()
Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::interp1d (const std::vector< double > & x, const Matrix< Scalar > & v, const std::vector< double > & xq, const std::string & mode, bool equidistant) static inherited
Definition at line 213 of file generic_matrix.hpp.
{
     bool mode_floor = false;
     bool mode_ceil = false;
     if (mode=="floor") {
       mode_floor = true;
     } else if (mode=="ceil") {
       mode_ceil = true;
     } else if (mode=="linear") {
       //
     } else {
       casadi_error("interp1d(x, v, xq, mode): "
         "Mode must be 'floor', 'ceil' or 'linear'. Got '" + mode + "' instead.");
     }
     casadi_assert(is_increasing(x), "interp1d(x, v, xq): x must be increasing.");
     casadi_assert(x.size()==v.size1(),
       "interp1d(x, v, xq): dimensions mismatch. v expected to have " + str(x.size()) + " rows,"
       " but got " + str(v.size1()) + " instead.");
     // Need at least two elements
     casadi_assert(x.size()>=2, "interp1d(x, v, xq): x must be at least length 2.");
     // Vectors to compose a sparse matrix
     std::vector<double> val;
     std::vector<casadi_int> colind(1, 0);
     std::vector<casadi_int> row;
     // Number of nonzeros in to-be composed matrix
     casadi_int nnz = 0;
     for (casadi_int i=0;i<xq.size();++i) {
       // Obtain index corresponding to xq[i]
       double ind = index_interp1d(x, xq[i], equidistant);
       if (mode_floor) ind = floor(ind);
       if (mode_ceil) ind = ceil(ind);
       // Split into integer and fractional part
       double int_partd;
       double frac_part = modf(ind, &int_partd);
       casadi_int int_part = static_cast<casadi_int>(int_partd);
       if (frac_part==0) {
          // Create a single entry
          val.push_back(1);
          row.push_back(int_part);
          nnz+=1;
          colind.push_back(nnz);
        } else {
          // Create a double entry
          val.push_back(1-frac_part);
          val.push_back(frac_part);
          row.push_back(int_part);
          row.push_back(int_part+1);
          nnz+=2;
          colind.push_back(nnz);
        }
      }
      // Construct sparsity for composed matrix
      Sparsity sp(x.size(), xq.size() , colind, row);
      return MatType::mtimes(MatType(sp, val).T(), v);
   }
inv() [1/2]
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::inv (const Matrix< Scalar > & A) static
Functions called by friend functions defined for GenericMatrix
inv() [2/2]
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::inv (const Matrix< Scalar > & A, const std::string & lsolver, const Dict & opts) static
Functions called by friend functions defined for GenericMatrix
inv_minor()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::inv_minor (const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
inv_skew()
Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::inv_skew (const Matrix< Scalar > & a) static inherited
Definition at line 229 of file generic_matrix.hpp.
{
     casadi_assert(a.size1()==3 && a.size2()==3,
       "inv_skew(a): Expecting 3-by-3 matrix, got " + a.dim() + ".");
     return 0.5*vertcat(std::vector<MatType>({a(2, 1)-a(1, 2), a(0, 2)-a(2, 0), a(1, 0)-a(0, 1)}));
   }
is_call()
bool CASADI_EXPORT casadi::SX::is_call
Extra doc: https://github.com/casadi/casadi/wiki/L_28j
Definition at line 150 of file sx_instantiator.cpp.
{
     return scalar().is_call();
   }
References casadi::Matrix< Scalar >::scalar().
is_column()
bool casadi::GenericMatrix< Matrix< Scalar > >::is_column () const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1b5
Definition at line 178 of file generic_matrix.hpp.
 { return sparsity().is_column();}
is_commutative()
bool CASADI_EXPORT casadi::SX::is_commutative
Only defined if symbolic scalar.
Extra doc: https://github.com/casadi/casadi/wiki/L_19q
Definition at line 136 of file sx_instantiator.cpp.
{
     return scalar().is_commutative();
   }
References casadi::Matrix< Scalar >::scalar().
is_constant()
template<typename Scalar > bool casadi::Matrix< Scalar >::is_constant () const
Extra doc: https://github.com/casadi/casadi/wiki/L_19v
is_dense()
bool casadi::GenericMatrix< Matrix< Scalar > >::is_dense () const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1b0
Definition at line 153 of file generic_matrix.hpp.
 { return sparsity().is_dense();}
is_empty()
bool casadi::GenericMatrix< Matrix< Scalar > >::is_empty (bool both = false) const inline inherited
(or optionally both dimensions)
Extra doc: https://github.com/casadi/casadi/wiki/L_1az
Definition at line 148 of file generic_matrix.hpp.
 { return sparsity().is_empty(both);}
is_equal()
template<typename Scalar > static bool casadi::Matrix< Scalar >::is_equal (const Matrix< Scalar > & x, const Matrix< Scalar > & y, casadi_int depth = 0) static
Functions called by friend functions defined for GenericExpression
is_eye()
template<typename Scalar > bool casadi::Matrix< Scalar >::is_eye () const
are possible)
Extra doc: https://github.com/casadi/casadi/wiki/L_1a0
Referenced by casadi::ConstantDM::is_eye().
is_integer()
template<typename Scalar > bool casadi::Matrix< Scalar >::is_integer () const
(note that false negative answers are possible)
Extra doc: https://github.com/casadi/casadi/wiki/L_19w
is_leaf()
bool CASADI_EXPORT casadi::SX::is_leaf
Only defined if symbolic scalar.
Extra doc: https://github.com/casadi/casadi/wiki/L_19p
Definition at line 131 of file sx_instantiator.cpp.
{
     return scalar().is_leaf();
   }
References casadi::Matrix< Scalar >::scalar().
is_linear()
bool casadi::GenericMatrix< Matrix< Scalar > >::is_linear (const Matrix< Scalar > & expr, const Matrix< Scalar > & var) static inherited
Definition at line 235 of file generic_matrix.hpp.
{
     return !any(MatType::which_depends(expr, var, 2, true));
   }
is_minus_one()
template<typename Scalar > bool casadi::Matrix< Scalar >::is_minus_one () const
Extra doc: https://github.com/casadi/casadi/wiki/L_19z
Referenced by casadi::ConstantDM::is_minus_one().
is_one()
template<typename Scalar > bool casadi::Matrix< Scalar >::is_one () const
Extra doc: https://github.com/casadi/casadi/wiki/L_19y
Referenced by casadi::ConstantDM::is_one().
is_op()
bool CASADI_EXPORT casadi::SX::is_op (casadi_int op) const
Definition at line 194 of file sx_instantiator.cpp.
{
     return scalar().is_op(op);
   }
References casadi::Matrix< Scalar >::op(), and casadi::Matrix< Scalar >::scalar().
is_output()
bool CASADI_EXPORT casadi::SX::is_output
Extra doc: https://github.com/casadi/casadi/wiki/L_28k
Definition at line 155 of file sx_instantiator.cpp.
{
     return scalar().is_output();
   }
References casadi::Matrix< Scalar >::scalar().
is_quadratic()
bool casadi::GenericMatrix< Matrix< Scalar > >::is_quadratic (const Matrix< Scalar > & expr, const Matrix< Scalar > & var) static inherited
Definition at line 236 of file generic_matrix.hpp.
{
     return is_linear(gradient(expr, var), var);
   }
is_regular()
bool CASADI_EXPORT casadi::SX::is_regular
Definition at line 100 of file sx_instantiator.cpp.
{
     // First pass: ignore symbolics
     for (casadi_int i=0; i<nnz(); ++i) {
       const SXElem& x = nonzeros().at(i);
       if (x.is_constant()) {
         if (x.is_nan() || x.is_inf() || x.is_minus_inf()) return false;
       }
     }
     // Second pass: don't ignore symbolics
     for (casadi_int i=0; i<nnz(); ++i) {
       if (!nonzeros().at(i).is_regular()) return false;
     }
     return true;
   }
References casadi::SXElem::is_constant(), casadi::SXElem::is_inf(), casadi::SXElem::is_minus_inf(), casadi::SXElem::is_nan(), casadi::GenericMatrix< Matrix< Scalar > >::nnz(), and casadi::Matrix< Scalar >::nonzeros().
Referenced by casadi::MX::is_regular().
is_row()
bool casadi::GenericMatrix< Matrix< Scalar > >::is_row () const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1b4
Definition at line 173 of file generic_matrix.hpp.
 { return sparsity().is_row();}
is_scalar()
bool casadi::GenericMatrix< Matrix< Scalar > >::is_scalar (bool scalar_and_dense = false) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1b1
Definition at line 158 of file generic_matrix.hpp.
{
     return sparsity().is_scalar(scalar_and_dense);
   }
is_smooth()
bool CASADI_EXPORT casadi::SX::is_smooth
Extra doc: https://github.com/casadi/casadi/wiki/L_19o
Definition at line 116 of file sx_instantiator.cpp.
{
     // Make a function
     Function temp("tmp_is_smooth", {SX()}, {*this}, Dict{{"max_io", 0}, {"allow_free", true}});
     // Run the function on the temporary variable
     SXFunction* t = temp.get<SXFunction>();
     return t->is_smooth();
   }
References casadi::SXFunction::is_smooth().
is_square()
bool casadi::GenericMatrix< Matrix< Scalar > >::is_square () const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1b2
Definition at line 163 of file generic_matrix.hpp.
 { return sparsity().is_square();}
is_symbolic()
bool CASADI_EXPORT casadi::SX::is_symbolic
Check if an expression is a pure symbol. Pure means that no operations should happen on the symbol (not even vec, transpose, index, concatenation, ...) By consequence, a slice of a vector-shaped MX symbol is not a symbol. However, the SX type is really a container format with scalar entries. Therefore, a slice of a vector-shaped SX symbol is still a symbol.
Sparse matrices invariable return false
\seealso is_valid_input
Extra doc: https://github.com/casadi/casadi/wiki/L_19r
Definition at line 180 of file sx_instantiator.cpp.
{
     if (is_dense()) {
       return is_valid_input();
     } else {
       return false;
     }
   }
References casadi::GenericMatrix< Matrix< Scalar > >::is_dense(), and casadi::Matrix< Scalar >::is_valid_input().
is_tril()
bool casadi::GenericMatrix< Matrix< Scalar > >::is_tril () const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1b7
Definition at line 188 of file generic_matrix.hpp.
 { return sparsity().is_tril();}
is_triu()
bool casadi::GenericMatrix< Matrix< Scalar > >::is_triu () const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1b6
Definition at line 183 of file generic_matrix.hpp.
 { return sparsity().is_triu();}
is_valid_input()
bool CASADI_EXPORT casadi::SX::is_valid_input
is_valid_input is more forgiving than is_symbolic. Some compositions are allowed: vec, vertcat.
Sparse matrices can return true if all non-zero elements are symbolic
\seealso is_symbolic
Extra doc: https://github.com/casadi/casadi/wiki/L_19s
Definition at line 141 of file sx_instantiator.cpp.
{
     for (casadi_int k=0; k<nnz(); ++k) // loop over non-zero elements
       if (!nonzeros().at(k)->is_symbolic()) // if an element is not symbolic
         return false;
     return true;
   }
References casadi::GenericMatrix< Matrix< Scalar > >::nnz(), and casadi::Matrix< Scalar >::nonzeros().
Referenced by casadi::Matrix< Scalar >::is_symbolic().
is_vector()
bool casadi::GenericMatrix< Matrix< Scalar > >::is_vector () const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1b3
Definition at line 168 of file generic_matrix.hpp.
 { return sparsity().is_vector();}
is_zero()
template<typename Scalar > bool casadi::Matrix< Scalar >::is_zero () const
Extra doc: https://github.com/casadi/casadi/wiki/L_19x
Referenced by casadi::ConstantDM::is_zero().
jacobian()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::jacobian (const Matrix< Scalar > & f, const Matrix< Scalar > & x, const Dict & opts = Dict()) static
Functions called by friend functions defined for GenericMatrix
Referenced by casadi::AmplInterface::init().
jacobian_sparsity()
template<typename Scalar > static Sparsity casadi::Matrix< Scalar >::jacobian_sparsity (const Matrix< Scalar > & f, const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
jtimes()
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::jtimes (const Matrix< Scalar > & ex, const Matrix< Scalar > & arg, const Matrix< Scalar > & v, bool tr = false, const Dict & opts = Dict()) static inherited
Functions called by friend functions defined here
kron()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::kron (const Matrix< Scalar > & x, const Matrix< Scalar > & y) static
Functions called by friend functions defined for SparsityInterface
ldl()
template<typename Scalar > static void casadi::Matrix< Scalar >::ldl (const Matrix< Scalar > & A, Matrix< Scalar > & D, Matrix< Scalar > & LT, std::vector< casadi_int > & p, bool amd = true) static
Functions called by friend functions defined here
ldl_solve()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::ldl_solve (const Matrix< Scalar > & b, const Matrix< Scalar > & D, const Matrix< Scalar > & LT, const std::vector< casadi_int > & p) static
Functions called by friend functions defined here
linear_coeff()
void casadi::GenericMatrix< Matrix< Scalar > >::linear_coeff (const Matrix< Scalar > & expr, const Matrix< Scalar > & var, Matrix< Scalar > & A, Matrix< Scalar > & b, bool check) static inherited
Definition at line 239 of file generic_matrix.hpp.
{
     casadi_assert(expr.is_vector(), "'linear_coeff' only defined for vector expressions.");
     if (check)
       casadi_assert(is_linear(expr, var), "'linear_coeff' called on non-linear expression.");
     A = substitute(jacobian(expr, var), var, 0);
     b = vec(substitute(expr, var, 0));
   }
linearize()
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::linearize (const Matrix< Scalar > & f, const Matrix< Scalar > & x, const Matrix< Scalar > & x0, const Dict & opts = Dict()) static inherited
Functions called by friend functions defined here
linspace()
Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::linspace (const Matrix< Scalar > & a, const Matrix< Scalar > & b, casadi_int nsteps) static inherited
Definition at line 226 of file generic_matrix.hpp.
{
     std::vector<MatType> ret(nsteps);
     ret[0] = a;
     MatType step = (b-a)/static_cast<MatType>(nsteps-1);
     for (casadi_int i=1; i<nsteps-1; ++i)
       ret[i] = a + i * step;
     ret[nsteps-1] = b;
     return vertcat(ret);
   }
logsumexp()
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::logsumexp (const Matrix< Scalar > & x) static inherited
mac()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::mac (const Matrix< Scalar > & x, const Matrix< Scalar > & y, const Matrix< Scalar > & z) static
Functions called by friend functions defined for SparsityInterface
matrix_matrix()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::matrix_matrix (casadi_int op, const Matrix< Scalar > & x, const Matrix< Scalar > & y) static
Extra doc: https://github.com/casadi/casadi/wiki/L_18o
matrix_scalar()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::matrix_scalar (casadi_int op, const Matrix< Scalar > & x, const Matrix< Scalar > & y) static
Extra doc: https://github.com/casadi/casadi/wiki/L_18o
minor()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::minor (const Matrix< Scalar > & x, casadi_int i, casadi_int j) static
Functions called by friend functions defined here
mldivide()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::mldivide (const Matrix< Scalar > & x, const Matrix< Scalar > & y) static
Functions called by friend functions defined for GenericMatrix
mmax()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::mmax (const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericExpression
mmin()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::mmin (const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericExpression
mpower()
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::mpower (const Matrix< Scalar > & x, const Matrix< Scalar > & y) static inherited
Functions called by friend functions defined here
mrdivide()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::mrdivide (const Matrix< Scalar > & x, const Matrix< Scalar > & y) static
Functions called by friend functions defined for GenericMatrix
mtaylor() [1/2]
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::mtaylor (const Matrix< Scalar > & ex, const Matrix< Scalar > & x, const Matrix< Scalar > & a, casadi_int order) static
Functions called by friend functions defined here
mtaylor() [2/2]
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::mtaylor (const Matrix< Scalar > & ex, const Matrix< Scalar > & x, const Matrix< Scalar > & a, casadi_int order, const std::vector< casadi_int > & order_contributions) static
Functions called by friend functions defined here
mtimes()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::mtimes (const Matrix< Scalar > & x, const Matrix< Scalar > & y) static
Functions called by friend functions defined for SparsityInterface
n_dep()
casadi_int CASADI_EXPORT casadi::SX::n_dep
Only defined if symbolic scalar.
Extra doc: https://github.com/casadi/casadi/wiki/L_1aa
Definition at line 228 of file sx_instantiator.cpp.
{
     return scalar().n_dep();
   }
References casadi::Matrix< Scalar >::scalar().
n_nodes()
template<typename Scalar > static casadi_int casadi::Matrix< Scalar >::n_nodes (const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
name()
std::string CASADI_EXPORT casadi::SX::name
Extra doc: https://github.com/casadi/casadi/wiki/L_1a8
Definition at line 218 of file sx_instantiator.cpp.
{
     return scalar().name();
   }
References casadi::Matrix< Scalar >::scalar().
Referenced by casadi::Matrix< Scalar >::_sym().
nan() [1/3]
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::nan (casadi_int nrow = 1, casadi_int ncol = 1) static
Extra doc: https://github.com/casadi/casadi/wiki/L_19l
nan() [2/3]
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::nan (const Sparsity & sp) static
Extra doc: https://github.com/casadi/casadi/wiki/L_19l
nan() [3/3]
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::nan (const std::pair< casadi_int, casadi_int > & rc) static
Extra doc: https://github.com/casadi/casadi/wiki/L_19l
nnz()
casadi_int casadi::GenericMatrix< Matrix< Scalar > >::nnz inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1an
Definition at line 84 of file generic_matrix.hpp.
{
     return sparsity().nnz();
   }
nnz_diag()
casadi_int casadi::GenericMatrix< Matrix< Scalar > >::nnz_diag inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1aq
Definition at line 99 of file generic_matrix.hpp.
{
     return sparsity().nnz_diag();
   }
nnz_lower()
casadi_int casadi::GenericMatrix< Matrix< Scalar > >::nnz_lower inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1ao
Definition at line 89 of file generic_matrix.hpp.
{
     return sparsity().nnz_lower();
   }
nnz_upper()
casadi_int casadi::GenericMatrix< Matrix< Scalar > >::nnz_upper inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1ap
Definition at line 94 of file generic_matrix.hpp.
{
     return sparsity().nnz_upper();
   }
nonzeros() [1/2]
template<typename Scalar > std::vector<Scalar>& casadi::Matrix< Scalar >::nonzeros ()
Access the non-zero elements
Referenced by casadi::MX::bspline(), casadi::ConstantMX::create(), casadi::Matrix< Scalar >::densify(), casadi::Matrix< Scalar >::einstein(), casadi::ConstantDM::generate(), casadi::Function::generate_in(), casadi::Function::generate_out(), casadi::Matrix< Scalar >::get(), casadi::MX::get(), casadi::MX::get_nz(), casadi::SuperscsInterface::init(), casadi::QpToNlp::init(), casadi::Matrix< Scalar >::is_regular(), casadi::is_slice(), casadi::Matrix< Scalar >::is_valid_input(), casadi::ConstantDM::serialize_body(), casadi::Matrix< Scalar >::set(), casadi::MX::set(), casadi::Matrix< Scalar >::set_nz(), casadi::MX::set_nz(), casadi::SnoptInterface::solve(), casadi::to_slice(), and casadi::SnoptInterface::userfun().
nonzeros() [2/2]
template<typename Scalar > const std::vector<Scalar>& casadi::Matrix< Scalar >::nonzeros () const
Access the non-zero elements
norm_0_mul()
static casadi_int casadi::GenericMatrix< Matrix< Scalar > >::norm_0_mul (const Matrix< Scalar > & x, const Matrix< Scalar > & y) inline static inherited
Definition at line 216 of file generic_matrix.hpp.
{
       return Sparsity::norm_0_mul(x.sparsity(), y.sparsity());
     }
norm_1()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::norm_1 (const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
norm_2()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::norm_2 (const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
norm_fro()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::norm_fro (const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
norm_inf()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::norm_inf (const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
norm_inf_mul()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::norm_inf_mul (const Matrix< Scalar > & x, const Matrix< Scalar > & y) static
Functions called by friend functions defined here
nullspace()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::nullspace (const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
Referenced by casadi::MX::nullspace().
numel()
casadi_int casadi::GenericMatrix< Matrix< Scalar > >::numel inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1ar
Definition at line 104 of file generic_matrix.hpp.
{
     return sparsity().numel();
   }
nz() [1/2]
NonZeros<Matrix< Scalar > , K> casadi::GenericMatrix< Matrix< Scalar > >::nz (const K & k) inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1bc
Definition at line 258 of file generic_matrix.hpp.
{
       return NonZeros<MatType, K>(self(), k);
     }
nz() [2/2]
const Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::nz (const K & k) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1bb
Definition at line 248 of file generic_matrix.hpp.
{
       MatType ret;
       self().get_nz(ret, false, k);
       return ret;
     }
ones() [1/3]
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::ones (casadi_int nrow = 1, casadi_int ncol = 1) inline static inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1di
Definition at line 1275 of file generic_matrix.hpp.
{
       return ones(Sparsity::dense(nrow, ncol));
     }
ones() [2/3]
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::ones (const Sparsity & sp) inline static inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1di
Definition at line 1278 of file generic_matrix.hpp.
 { return MatType(sp, 1, false);}
ones() [3/3]
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::ones (const std::pair< casadi_int, casadi_int > & rc) inline static inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1di
Definition at line 1279 of file generic_matrix.hpp.
{
       return ones(rc.first, rc.second);
     }
op()
casadi_int CASADI_EXPORT casadi::SX::op
Definition at line 189 of file sx_instantiator.cpp.
{
     return scalar().op();
   }
References casadi::Matrix< Scalar >::scalar().
Referenced by casadi::Matrix< Scalar >::is_op().
operator casadi_int()
template<typename Scalar > casadi::Matrix< Scalar >::operator casadi_int () const explicit
Extra doc: https://github.com/casadi/casadi/wiki/L_1a6
operator double()
template<typename Scalar > casadi::Matrix< Scalar >::operator double () const explicit
Extra doc: https://github.com/casadi/casadi/wiki/L_1a5
operator std::vector< A >()
template<typename Scalar > template<typename A > casadi::Matrix< Scalar >::operator std::vector< A > explicit
Implementation of std::vector(Matrix) (in public API)
Extra doc: https://github.com/casadi/casadi/wiki/L_1a7
Definition at line 1402 of file matrix_decl.hpp.
{
     // Get sparsity pattern
     casadi_int size1 = this->size1(), size2 = this->size2();
     const casadi_int *colind = this->colind(), *row = this->row();
     // Copy the nonzeros
     auto it = nonzeros().begin();
     std::vector<A> ret(numel(), 0);
     for (casadi_int cc=0; cc<size2; ++cc) {
       for (casadi_int el=colind[cc]; el<colind[cc+1]; ++el) {
         ret[row[el] + cc*size1] = static_cast<A>(*it++);
       }
     }
     return ret;
   }
operator()() [1/4]
SubIndex<Matrix< Scalar > , RR> casadi::GenericMatrix< Matrix< Scalar > >::operator() (const RR & rr) inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1bf
Definition at line 286 of file generic_matrix.hpp.
{
       return SubIndex<MatType, RR>(self(), rr);
     }
operator()() [2/4]
const Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::operator() (const RR & rr) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1bd
Definition at line 266 of file generic_matrix.hpp.
{
       MatType ret;
       self().get(ret, false, rr);
       return ret;
     }
operator()() [3/4]
SubMatrix<Matrix< Scalar > , RR, CC> casadi::GenericMatrix< Matrix< Scalar > >::operator() (const RR & rr, const CC & cc) inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1bg
Definition at line 294 of file generic_matrix.hpp.
{
       return SubMatrix<MatType, RR, CC>(self(), rr, cc);
     }
operator()() [4/4]
const Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::operator() (const RR & rr, const CC & cc) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1be
Definition at line 276 of file generic_matrix.hpp.
{
       MatType ret;
       self().get(ret, false, rr, cc);
       return ret;
     }
operator+()
template<typename Scalar > Matrix<Scalar> casadi::Matrix< Scalar >::operator+ () const
Examples
SX/SXaddition.cc.
operator-()
template<typename Scalar > Matrix<Scalar> casadi::Matrix< Scalar >::operator- () const
operator->() [1/2]
template<typename Scalar > std::vector< Scalar > * casadi::Matrix< Scalar >::operator->
Extra doc: https://github.com/casadi/casadi/wiki/L_18i
Definition at line 596 of file matrix_impl.hpp.
{
     return &nonzeros_;
   }
operator->() [2/2]
template<typename Scalar > const std::vector< Scalar > * casadi::Matrix< Scalar >::operator->
Extra doc: https://github.com/casadi/casadi/wiki/L_18j
Definition at line 601 of file matrix_impl.hpp.
{
     return &nonzeros_;
   }
operator=()
template<typename Scalar > Matrix< Scalar > & casadi::Matrix< Scalar >::operator= (const Matrix< Scalar > & m)
Definition at line 589 of file matrix_impl.hpp.
{
     sparsity_ = m.sparsity_;
     nonzeros_ = m.nonzeros_;
     return *this;
   }
pinv() [1/2]
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::pinv (const Matrix< Scalar > & A, const std::string & lsolver, const Dict & opts) static
Functions called by friend functions defined for GenericMatrix
pinv() [2/2]
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::pinv (const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
poly_coeff()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::poly_coeff (const Matrix< Scalar > & ex, const Matrix< Scalar > & x) static
Functions called by friend functions defined here
poly_roots()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::poly_roots (const Matrix< Scalar > & p) static
Functions called by friend functions defined here
polyval()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::polyval (const Matrix< Scalar > & p, const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
print_default()
template<typename Scalar > void casadi::Matrix< Scalar >::print_default (std::ostream & stream, const Sparsity & sp, const Scalar * nonzeros, bool truncate = true) static
Definition at line 703 of file matrix_impl.hpp.
{
     if (sp.is_empty()) {
       stream << sp.size1() << "x" << sp.size2();
     } else if (sp.numel()==1) {
       if (sp.nnz()==0) {
         stream << "00";
       } else {
         print_scalar(stream, *nonzeros);
       }
     } else if (sp.is_column()) {
       print_vector(stream, sp, nonzeros, truncate);
     } else if (std::max(sp.size1(), sp.size2())<=10 ||
         static_cast<double>(sp.nnz())/static_cast<double>(sp.numel())>=0.5) {
       // if "small" or "dense"
       print_dense(stream, sp, nonzeros, truncate);
     } else {
       print_sparse(stream, sp, nonzeros, truncate);
     }
   }
References casadi::Sparsity::is_column(), casadi::Sparsity::is_empty(), casadi::Sparsity::nnz(), casadi::Sparsity::numel(), casadi::Sparsity::size1(), and casadi::Sparsity::size2().
print_dense() [1/2]
template<typename Scalar > void casadi::Matrix< Scalar >::print_dense (std::ostream & stream, bool truncate = true) const
Definition at line 686 of file matrix_impl.hpp.
{
     print_dense(stream, sparsity(), ptr(), truncate);
   }
print_dense() [2/2]
template<typename Scalar > void casadi::Matrix< Scalar >::print_dense (std::ostream & stream, const Sparsity & sp, const Scalar * nonzeros, bool truncate = true) static
Definition at line 817 of file matrix_impl.hpp.
References casadi::Sparsity::colind(), casadi::Sparsity::nnz(), casadi::Sparsity::row(), casadi::Sparsity::size1(), and casadi::Sparsity::size2().
print_operator()
template<typename Scalar > static std::string casadi::Matrix< Scalar >::print_operator (const Matrix< Scalar > & x, const std::vector< std::string > & args) static
Functions called by friend functions defined for GenericMatrix
print_scalar() [1/2]
template<typename Scalar > void casadi::Matrix< Scalar >::print_scalar (std::ostream & stream) const
Definition at line 609 of file matrix_impl.hpp.
{
     casadi_assert(numel()==1, "Not a scalar");
     std::streamsize precision = stream.precision();
     std::streamsize width = stream.width();
     std::ios_base::fmtflags flags = stream.flags();
     stream.precision(stream_precision_);
     stream.width(stream_width_);
     if (stream_scientific_) {
       stream.setf(std::ios::scientific);
     } else {
       stream.unsetf(std::ios::scientific);
     }
     if (nnz()==0) {
       stream << "00";
     } else {
       stream << scalar();
     }
     stream << std::flush;
     stream.precision(precision);
     stream.width(width);
     stream.flags(flags);
   }
print_scalar() [2/2]
template<typename Scalar > void casadi::Matrix< Scalar >::print_scalar (std::ostream & stream, const Scalar & e) static
Definition at line 725 of file matrix_impl.hpp.
{
     std::streamsize precision = stream.precision();
     std::streamsize width = stream.width();
     std::ios_base::fmtflags flags = stream.flags();
     stream.precision(stream_precision_);
     stream.width(stream_width_);
     if (stream_scientific_) {
       stream.setf(std::ios::scientific);
     } else {
       stream.unsetf(std::ios::scientific);
     }
     stream << e;
     stream << std::flush;
     stream.precision(precision);
     stream.width(width);
     stream.flags(flags);
   }
print_sparse() [1/2]
template<typename Scalar > void casadi::Matrix< Scalar >::print_sparse (std::ostream & stream, bool truncate = true) const
Definition at line 691 of file matrix_impl.hpp.
{
     print_sparse(stream, sparsity(), ptr(), truncate);
   }
Referenced by casadi::CsparseInterface::nfact().
print_sparse() [2/2]
template<typename Scalar > void casadi::Matrix< Scalar >::print_sparse (std::ostream & stream, const Sparsity & sp, const Scalar * nonzeros, bool truncate = true) static
Definition at line 771 of file matrix_impl.hpp.
{
     // Access data structures
     casadi_int size1 = sp.size1();
     casadi_int size2 = sp.size2();
     const casadi_int* colind = sp.colind();
     const casadi_int* row = sp.row();
     casadi_int nnz = sp.nnz();
     // Quick return if all zero sparse
     if (nnz==0) {
       stream << "all zero sparse: " << size1 << "-by-" << size2 << std::flush;
       return;
     }
     // Print header
     stream << "sparse: " << size1 << "-by-" << size2 << ", " << nnz << " nnz";
     // Get components
     std::vector<std::string> nz, inter;
     print_split(nnz, nonzeros, nz, inter);
     // Print intermediate expressions
     for (casadi_int i=0; i<inter.size(); ++i)
       stream << std::endl << " @" << (i+1) << "=" << inter[i] << ",";
     inter.clear();
     // No need to truncate if less than 1000 nonzeros
     const casadi_int max_nnz = 1000;
     if (truncate && nnz<=max_nnz) truncate=false;
     // Print nonzeros
     for (casadi_int cc=0; cc<size2; ++cc) {
       for (casadi_int el=colind[cc]; el<colind[cc+1]; ++el) {
         if (truncate && el>=3 && el<nnz-3) {
           if (el==3) stream << std::endl << " ...";
         } else {
           stream << std::endl << " (" << row[el] << ", " << cc << ") -> " << nz.at(el);
           InterruptHandler::check();
         }
       }
     }
     stream << std::flush;
   }
References casadi::InterruptHandler::check(), casadi::Sparsity::colind(), casadi::Sparsity::nnz(), casadi::Sparsity::row(), casadi::Sparsity::size1(), and casadi::Sparsity::size2().
print_split() [1/2]
template<typename Scalar > void casadi::Matrix< Scalar >::print_split (casadi_int nnz, const Scalar * nonzeros, std::vector< std::string > & nz, std::vector< std::string > & inter) static
Definition at line 746 of file matrix_impl.hpp.
{
     nz.resize(nnz);
     inter.resize(0);
     // Temporary
     std::stringstream ss;
     ss.precision(stream_precision_);
     ss.width(stream_width_);
     if (stream_scientific_) {
       ss.setf(std::ios::scientific);
     } else {
       ss.unsetf(std::ios::scientific);
     }
     // Print nonzeros
     for (casadi_int i=0; i<nz.size(); ++i) {
       ss.str(std::string());
       ss << nonzeros[i];
       nz[i] = ss.str();
     }
   }
print_split() [2/2]
template<typename Scalar > void casadi::Matrix< Scalar >::print_split (std::vector< std::string > & nz, std::vector< std::string > & inter) const
Definition at line 696 of file matrix_impl.hpp.
{
     print_split(nnz(), ptr(), nz, inter);
   }
print_vector() [1/2]
template<typename Scalar > void casadi::Matrix< Scalar >::print_vector (std::ostream & stream, bool truncate = true) const
Definition at line 636 of file matrix_impl.hpp.
{
     print_vector(stream, sparsity(), ptr(), truncate);
   }
print_vector() [2/2]
template<typename Scalar > void casadi::Matrix< Scalar >::print_vector (std::ostream & stream, const Sparsity & sp, const Scalar * nonzeros, bool truncate = true) static
Definition at line 641 of file matrix_impl.hpp.
{
     casadi_assert(sp.is_column(), "Not a vector");
     // Get components
     std::vector<std::string> nz, inter;
     print_split(sp.nnz(), nonzeros, nz, inter);
     // Print intermediate expressions
     for (casadi_int i=0; i<inter.size(); ++i)
       stream << "@" << (i+1) << "=" << inter[i] << ", ";
     inter.clear();
     // Access data structures
     const casadi_int* row = sp.row();
     casadi_int nnz = sp.nnz();
     casadi_int size1 = sp.size1();
     // No need to truncate if less than 1000 entries
     const casadi_int max_numel = 1000;
     if (truncate && size1<=max_numel) truncate=false;
     // Nonzero
     casadi_int el=0;
     // Loop over rows
     stream << "[";
     for (casadi_int rr=0; rr<size1; ++rr) {
       // String representation
       std::string s = el<nnz && rr==row[el] ? nz.at(el++) : "00";
       // Truncate?
       if (truncate && rr>=3 && rr<size1-3) {
         // Do not print
         if (rr==3) stream << ", ...";
       } else {
         // Print
         if (rr!=0) stream << ", ";
         stream << s;
       }
     }
     stream << "]" << std::flush;
   }
References casadi::Sparsity::is_column(), casadi::Sparsity::nnz(), casadi::Sparsity::row(), and casadi::Sparsity::size1().
printme()
template<typename Scalar > Matrix<Scalar> casadi::Matrix< Scalar >::printme (const Matrix< Scalar > & y) const
project()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::project (const Matrix< Scalar > & x, const Sparsity & sp, bool intersect = false) static
Functions called by friend functions defined for GenericMatrix
ptr() [1/2]
template<typename Scalar > Scalar* casadi::Matrix< Scalar >::ptr ()
Get a pointer to the data
Referenced by casadi::SuperscsInterface::init(), casadi::Linsol::neig(), casadi::Linsol::nfact(), casadi::FunctionInternal::nz_in(), casadi::FunctionInternal::nz_out(), casadi::Linsol::rank(), casadi::Linsol::sfact(), casadi::Linsol::solve(), casadi::CplexInterface::solve(), and casadi::GurobiInterface::solve().
ptr() [2/2]
template<typename Scalar > const Scalar* casadi::Matrix< Scalar >::ptr () const
Get a pointer to the data
pw_const()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::pw_const (const Matrix< Scalar > & t, const Matrix< Scalar > & tval, const Matrix< Scalar > & val) static
Functions called by friend functions defined here
pw_lin()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::pw_lin (const Matrix< Scalar > & t, const Matrix< Scalar > & tval, const Matrix< Scalar > & val) static
Functions called by friend functions defined here
qr()
template<typename Scalar > static void casadi::Matrix< Scalar >::qr (const Matrix< Scalar > & A, Matrix< Scalar > & Q, Matrix< Scalar > & R) static
Functions called by friend functions defined here
qr_solve()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::qr_solve (const Matrix< Scalar > & b, const Matrix< Scalar > & v, const Matrix< Scalar > & r, const Matrix< Scalar > & beta, const std::vector< casadi_int > & prinv, const std::vector< casadi_int > & pc, bool tr = false) static
Functions called by friend functions defined here
qr_sparse()
template<typename Scalar > static void casadi::Matrix< Scalar >::qr_sparse (const Matrix< Scalar > & A, Matrix< Scalar > & V, Matrix< Scalar > & R, Matrix< Scalar > & beta, std::vector< casadi_int > & prinv, std::vector< casadi_int > & pc, bool amd = true) static
Functions called by friend functions defined here
quadratic_coeff()
void casadi::GenericMatrix< Matrix< Scalar > >::quadratic_coeff (const Matrix< Scalar > & expr, const Matrix< Scalar > & var, Matrix< Scalar > & A, Matrix< Scalar > & b, Matrix< Scalar > & c, bool check) static inherited
Definition at line 237 of file generic_matrix.hpp.
{
     casadi_assert(expr.is_scalar(), "'quadratic_coeff' only defined for scalar expressions.");
     A = hessian(expr, var);
     b = substitute(jacobian(expr, var), var, 0).T();
     if (check)
       casadi_assert(!depends_on(A, var), "'quadratic_coeff' called on non-quadratic expression.");
     c = substitute(expr, var, 0);
   }
ramp()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::ramp (const Matrix< Scalar > & x) static
Functions called by friend functions defined here
rand() [1/3]
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::rand (casadi_int nrow = 1, casadi_int ncol = 1) static
Extra doc: https://github.com/casadi/casadi/wiki/L_1ab
rand() [2/3]
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::rand (const Sparsity & sp) static
Extra doc: https://github.com/casadi/casadi/wiki/L_1ab
rand() [3/3]
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::rand (const std::pair< casadi_int, casadi_int > & rc) static
Extra doc: https://github.com/casadi/casadi/wiki/L_1ab
rank1()
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::rank1 (const Matrix< Scalar > & A, const Matrix< Scalar > & alpha, const Matrix< Scalar > & x, const Matrix< Scalar > & y) static inherited
Calculates A + 1/2 * alpha * x*y'
Extra doc: https://github.com/casadi/casadi/wiki/L_1bp
rectangle()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::rectangle (const Matrix< Scalar > & x) static
Functions called by friend functions defined here
remove()
template<typename Scalar > void casadi::Matrix< Scalar >::remove (const std::vector< casadi_int > & rr, const std::vector< casadi_int > & cc)
Remove/delete rows and/or columns of a matrix
Extra doc: https://github.com/casadi/casadi/wiki/L_19h
repsum()
Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::repsum (const Matrix< Scalar > & x, casadi_int n, casadi_int m = 1) static inherited
Definition at line 232 of file generic_matrix.hpp.
{
     casadi_assert_dev(x.size1() % n==0);
     casadi_assert_dev(x.size2() % m==0);
     std::vector< std::vector< MatType> > s =
       blocksplit(x, x.size1()/n, x.size2()/m);
     MatType sum = 0;
     for (casadi_int i=0;i<s.size();++i) {
       for (casadi_int j=0;j<s[i].size();++j) {
         sum = sum + s[i][j];
       }
     }
     return sum;
   }
reserve() [1/2]
template<typename Scalar > void casadi::Matrix< Scalar >::reserve (casadi_int nnz)
reserve() [2/2]
template<typename Scalar > void casadi::Matrix< Scalar >::reserve (casadi_int nnz, casadi_int ncol)
reset_input()
void CASADI_EXPORT casadi::SX::reset_input
Extra doc: https://github.com/casadi/casadi/wiki/L_19u
Definition at line 211 of file sx_instantiator.cpp.
{
     for (auto&& i : nonzeros_) {
       i.set_temp(0);
     }
   }
reshape() [1/2]
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::reshape (const Matrix< Scalar > & x, casadi_int nrow, casadi_int ncol) static
Functions called by friend functions defined for SparsityInterface
reshape() [2/2]
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::reshape (const Matrix< Scalar > & x, const Sparsity & sp) static
Functions called by friend functions defined for SparsityInterface
resize()
template<typename Scalar > void casadi::Matrix< Scalar >::resize (casadi_int nrow, casadi_int ncol)
reverse()
template<typename Scalar > static std::vector<std::vector<Matrix<Scalar> > > casadi::Matrix< Scalar >::reverse (const std::vector< Matrix< Scalar > > & ex, const std::vector< Matrix< Scalar > > & arg, const std::vector< std::vector< Matrix< Scalar > > > & v, const Dict & opts = Dict()) static
Functions called by friend functions defined here
rng()
template<typename Scalar > void casadi::Matrix< Scalar >::rng (casadi_int seed) static
Definition at line 60 of file matrix_impl.hpp.
{
     rng_.seed(seed);
   }
row() [1/2]
const casadi_int* casadi::GenericMatrix< Matrix< Scalar > >::row () const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1b8
Definition at line 197 of file generic_matrix.hpp.
 { return sparsity().row(); }
row() [2/2]
casadi_int casadi::GenericMatrix< Matrix< Scalar > >::row (casadi_int el) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1b8
Definition at line 200 of file generic_matrix.hpp.
 { return sparsity().row(el); }
rows()
casadi_int casadi::GenericMatrix< Matrix< Scalar > >::rows () const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1at
Definition at line 114 of file generic_matrix.hpp.
 {return size1();}
scalar()
template<typename Scalar > const Scalar casadi::Matrix< Scalar >::scalar () const
Referenced by casadi::ConstantMX::create(), casadi::Matrix< Scalar >::densify(), casadi::Matrix< Scalar >::dep(), casadi::Matrix< Scalar >::element_hash(), casadi::Matrix< Scalar >::get_output(), casadi::Matrix< Scalar >::has_output(), casadi::Matrix< Scalar >::is_call(), casadi::Matrix< Scalar >::is_commutative(), casadi::Matrix< Scalar >::is_leaf(), casadi::Matrix< Scalar >::is_op(), casadi::Matrix< Scalar >::is_output(), casadi::Matrix< Scalar >::n_dep(), casadi::Matrix< Scalar >::name(), casadi::Matrix< Scalar >::op(), casadi::Matrix< Scalar >::set(), casadi::Matrix< Scalar >::set_nz(), casadi::to_slice(), casadi::Matrix< Scalar >::which_function(), and casadi::Matrix< Scalar >::which_output().
scalar_matrix()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::scalar_matrix (casadi_int op, const Matrix< Scalar > & x, const Matrix< Scalar > & y) static
Extra doc: https://github.com/casadi/casadi/wiki/L_18o
separate_linear()
template<typename Scalar > static void casadi::Matrix< Scalar >::separate_linear (const Matrix< Scalar > & expr, const Matrix< Scalar > & sym_lin, const Matrix< Scalar > & sym_const, Matrix< Scalar > & expr_const, Matrix< Scalar > & expr_lin, Matrix< Scalar > & expr_nonlin) static
Functions called by friend functions defined for SparsityInterface
serialize() [1/3]
template<typename Scalar > std::string casadi::Matrix< Scalar >::serialize () const
Extra doc: https://github.com/casadi/casadi/wiki/L_1ae
serialize() [2/3]
template<typename Scalar > void casadi::Matrix< Scalar >::serialize (SerializingStream & s) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1ah
serialize() [3/3]
template<typename Scalar > void casadi::Matrix< Scalar >::serialize (std::ostream & stream) const
Extra doc: https://github.com/casadi/casadi/wiki/L_1ad
Referenced by casadi::SerializingStream::pack().
set() [1/7]
template<typename Scalar > void casadi::Matrix< Scalar >::set (const Matrix< Scalar > & m, bool ind1, const Matrix< casadi_int > & rr)
Set a submatrix, single argument
Definition at line 304 of file matrix_impl.hpp.
{
     // Scalar
     if (rr.is_scalar(true) && m.is_dense()) {
       return set(m, ind1, to_slice(rr, ind1));
     }
     // Assert dimensions of assigning matrix
     if (rr.sparsity() != m.sparsity()) {
       if (rr.size() == m.size()) {
         // Remove submatrix to be replaced
         erase(rr.nonzeros(), ind1);
         // Find the intersection between rr's and m's sparsity patterns
         Sparsity sp = rr.sparsity() * m.sparsity();
         // Project both matrices to this sparsity
         return set(project(m, sp), ind1, Matrix<casadi_int>::project(rr, sp));
       } else if (m.is_scalar()) {
         // m scalar means "set all"
         if (m.is_dense()) {
           return set(Matrix<Scalar>(rr.sparsity(), m), ind1, rr);
         } else {
           return set(Matrix<Scalar>(rr.size()), ind1, rr);
         }
       } else if (rr.size1() == m.size2() && rr.size2() == m.size1()
                  && std::min(m.size1(), m.size2()) == 1) {
         // m is transposed if necessary
         return set(m.T(), ind1, rr);
       } else {
         // Error otherwise
         casadi_error("Dimension mismatch. lhs is " + str(rr.size())
                      + ", while rhs is " + str(m.size()));
       }
     }
     // Dimensions of this
     casadi_int sz1 = size1(), sz2 = size2(), sz = nnz(), nel = numel(), rrsz = rr.nnz();
     // Quick return if nothing to set
     if (rrsz==0) return;
     // Check bounds
     casadi_assert_in_range(rr.nonzeros(), -nel+ind1, nel+ind1);
     // Dense mode
     if (is_dense() && m.is_dense()) {
       return set_nz(m, ind1, rr);
     }
     // Construct new sparsity pattern
     std::vector<casadi_int> new_row =
       sparsity().get_row(), new_col=sparsity().get_col(), nz(rr.nonzeros());
     new_row.reserve(sz+rrsz);
     new_col.reserve(sz+rrsz);
     nz.reserve(rrsz);
     for (std::vector<casadi_int>::iterator i=nz.begin(); i!=nz.end(); ++i) {
       if (ind1) (*i)--;
       if (*i<0) *i += nel;
       new_row.push_back(*i % sz1);
       new_col.push_back(*i / sz1);
     }
     Sparsity sp = Sparsity::triplet(sz1, sz2, new_row, new_col);
     // If needed, update pattern
     if (sp != sparsity()) *this = project(*this, sp);
     // Find the nonzeros corresponding to rr
     sparsity().get_nz(nz);
     // Carry out the assignments
     for (casadi_int i=0; i<nz.size(); ++i) {
       nonzeros().at(nz[i]) = m->at(i);
     }
   }
References casadi::GenericMatrix< MatType >::is_dense(), casadi::GenericMatrix< MatType >::is_scalar(), casadi::GenericMatrix< MatType >::nnz(), casadi::Matrix< Scalar >::nonzeros(), casadi::GenericMatrix< MatType >::size(), casadi::GenericMatrix< MatType >::size1(), casadi::GenericMatrix< MatType >::size2(), casadi::Matrix< Scalar >::sparsity(), casadi::str(), casadi::Matrix< Scalar >::T(), casadi::to_slice(), and casadi::Sparsity::triplet().
set() [2/7]
template<typename Scalar > void casadi::Matrix< Scalar >::set (const Matrix< Scalar > & m, bool ind1, const Matrix< casadi_int > & rr, const Matrix< casadi_int > & cc)
Set a submatrix, two arguments
Definition at line 218 of file matrix_impl.hpp.
{
     // Scalar
     if (rr.is_scalar(true) && cc.is_scalar(true) && m.is_dense()) {
       return set(m, ind1, to_slice(rr, ind1), to_slice(cc, ind1));
     }
     // Row vector rr (e.g. in MATLAB) is transposed to column vector
     if (rr.size1()==1 && rr.size2()>1) {
       return set(m, ind1, rr.T(), cc);
     }
     // Row vector cc (e.g. in MATLAB) is transposed to column vector
     if (cc.size1()==1 && cc.size2()>1) {
       return set(m, ind1, rr, cc.T());
     }
     // Make sure rr and cc are dense vectors
     casadi_assert(rr.is_dense() && rr.is_column(),
                           "Matrix::set: First index not dense vector");
     casadi_assert(cc.is_dense() && cc.is_column(),
                           "Matrix::set: Second index not dense vector");
     // Assert dimensions of assigning matrix
     if (rr.size1() != m.size1() || cc.size1() != m.size2()) {
       if (m.is_scalar()) {
         // m scalar means "set all"
         return set(repmat(m, rr.size1(), cc.size1()), ind1, rr, cc);
       } else if (rr.size1() == m.size2() && cc.size1() == m.size1()
                  && std::min(m.size1(), m.size2()) == 1) {
         // m is transposed if necessary
         return set(m.T(), ind1, rr, cc);
       } else {
         // Error otherwise
         casadi_error("Dimension mismatch. lhs is " + str(rr.size1()) + "-by-"
                      + str(cc.size1()) + ", while rhs is " + str(m.size()));
       }
     }
     // Dimensions
     casadi_int sz1 = size1(), sz2 = size2();
     // Report out-of-bounds
     casadi_assert_in_range(rr.nonzeros(), -sz1+ind1, sz1+ind1);
     casadi_assert_in_range(cc.nonzeros(), -sz2+ind1, sz2+ind1);
     // If we are assigning with something sparse, first remove existing entries
     if (!m.is_dense()) {
       erase(rr.nonzeros(), cc.nonzeros(), ind1);
     }
     // Collect all assignments
     IM el = IM::zeros(m.sparsity());
     for (casadi_int j=0; j<el.size2(); ++j) { // Loop over columns of m
       casadi_int this_j = cc->at(j) - ind1; // Corresponding column in this
       if (this_j<0) this_j += sz2;
       for (casadi_int k=el.colind(j); k<el.colind(j+1); ++k) { // Loop over rows of m
         casadi_int i = m.row(k);
         casadi_int this_i = rr->at(i) - ind1; // Corresponding row in this
         if (this_i<0) this_i += sz1;
         el->at(k) = this_i + this_j*sz1;
       }
     }
     return set(m, false, el);
   }
References casadi::GenericMatrix< MatType >::is_dense(), casadi::GenericMatrix< MatType >::is_scalar(), and casadi::to_slice().
set() [3/7]
template<typename Scalar > void casadi::Matrix< Scalar >::set (const Matrix< Scalar > & m, bool ind1, const Matrix< casadi_int > & rr, const Slice & cc)
Set a submatrix, two arguments
Definition at line 211 of file matrix_impl.hpp.
{
     // Fall back on (IM, IM)
     set(m, ind1, rr, cc.all(size2(), ind1));
   }
References casadi::Slice::all().
set() [4/7]
template<typename Scalar > void casadi::Matrix< Scalar >::set (const Matrix< Scalar > & m, bool ind1, const Slice & rr)
Set a submatrix, single argument
Definition at line 285 of file matrix_impl.hpp.
{
     // Scalar
     if (rr.is_scalar(numel()) && m.is_dense()) {
       casadi_int r = rr.scalar(numel());
       casadi_int oldsize = sparsity_.nnz();
       casadi_int ind = sparsity_.add_nz(r % size1(), r / size1());
       if (oldsize == sparsity_.nnz()) {
         nonzeros_.at(ind) = m.scalar();
       } else {
         nonzeros_.insert(nonzeros_.begin()+ind, m.scalar());
       }
       return;
     }
     // Fall back on IM
     set(m, ind1, rr.all(numel(), ind1));
   }
References casadi::Slice::all(), casadi::GenericMatrix< MatType >::is_dense(), casadi::Slice::is_scalar(), casadi::Matrix< Scalar >::scalar(), and casadi::Slice::scalar().
Referenced by casadi::override_num().
set() [5/7]
template<typename Scalar > void casadi::Matrix< Scalar >::set (const Matrix< Scalar > & m, bool ind1, const Slice & rr, const Matrix< casadi_int > & cc)
Set a submatrix, two arguments
Definition at line 204 of file matrix_impl.hpp.
{
     // Fall back on (IM, IM)
     set(m, ind1, rr.all(size1(), ind1), cc);
   }
References casadi::Slice::all().
set() [6/7]
template<typename Scalar > void casadi::Matrix< Scalar >::set (const Matrix< Scalar > & m, bool ind1, const Slice & rr, const Slice & cc)
Set a submatrix, two arguments
Definition at line 185 of file matrix_impl.hpp.
{
     // Both are scalar
     if (rr.is_scalar(size1()) && cc.is_scalar(size2()) && m.is_dense()) {
       casadi_int oldsize = sparsity_.nnz();
       casadi_int ind = sparsity_.add_nz(rr.scalar(size1()), cc.scalar(size2()));
       if (oldsize == sparsity_.nnz()) {
         nonzeros_.at(ind) = m.scalar();
       } else {
         nonzeros_.insert(nonzeros_.begin()+ind, m.scalar());
       }
       return;
     }
     // Fall back on (IM, IM)
     set(m, ind1, rr.all(size1(), ind1), cc.all(size2(), ind1));
   }
References casadi::Slice::all(), casadi::GenericMatrix< MatType >::is_dense(), casadi::Slice::is_scalar(), casadi::Matrix< Scalar >::scalar(), and casadi::Slice::scalar().
set() [7/7]
template<typename Scalar > void casadi::Matrix< Scalar >::set (const Matrix< Scalar > & m, bool ind1, const Sparsity & sp)
Set a submatrix, single argument
Definition at line 380 of file matrix_impl.hpp.
{
     casadi_assert(size()==sp.size(),
                           "set(Sparsity sp): shape mismatch. This matrix has shape "
                           + str(size()) + ", but supplied sparsity index has shape "
                           + str(sp.size()) + ".");
     std::vector<casadi_int> ii = sp.find();
     if (m.is_scalar()) {
       (*this)(ii) = densify(m);
     } else {
       (*this)(ii) = densify(m(ii));
     }
   }
References casadi::Sparsity::find(), casadi::GenericMatrix< MatType >::is_scalar(), casadi::Sparsity::size(), and casadi::str().
set_max_depth()
void CASADI_EXPORT casadi::SX::set_max_depth (casadi_int eq_depth = 1) static
Extra doc: https://github.com/casadi/casadi/wiki/L_19b
Definition at line 42 of file sx_instantiator.cpp.
{
     SXNode::eq_depth_ = eq_depth;
   }
References casadi::SXNode::eq_depth_.
set_nz() [1/2]
template<typename Scalar > void casadi::Matrix< Scalar >::set_nz (const Matrix< Scalar > & m, bool ind1, const Matrix< casadi_int > & k)
Set a set of nonzeros
Definition at line 447 of file matrix_impl.hpp.
{
     // Scalar
     if (kk.is_scalar(true)) {
       return set_nz(m, ind1, to_slice(kk, ind1));
     }
     // Assert dimensions of assigning matrix
     if (kk.sparsity() != m.sparsity()) {
       if (m.is_scalar()) {
         // m scalar means "set all"
         if (!m.is_dense()) return; // Nothing to set
         return set_nz(Matrix<Scalar>(kk.sparsity(), m), ind1, kk);
       } else if (kk.size() == m.size()) {
         // Project sparsity if needed
         return set_nz(project(m, kk.sparsity()), ind1, kk);
       } else if (kk.size1() == m.size2() && kk.size2() == m.size1()
                  && std::min(m.size1(), m.size2()) == 1) {
         // m is transposed if necessary
         return set_nz(m.T(), ind1, kk);
       } else {
         // Error otherwise
         casadi_error("Dimension mismatch. lhs is " + str(kk.size())
                      + ", while rhs is " + str(m.size()));
       }
     }
     // Get nonzeros
     const std::vector<casadi_int>& k = kk.nonzeros();
     casadi_int sz = nnz();
     // Check bounds
     casadi_assert_in_range(k, -sz+ind1, sz+ind1);
     // Set nonzeros, ignoring negative indices
     for (casadi_int el=0; el<k.size(); ++el) {
       casadi_assert(!(ind1 && k[el]<=0),
         "Matlab is 1-based, but requested index " + str(k[el])
         +  ". Note that negative slices are disabled in the Matlab interface. "
            "Possibly you may want to use 'end'.");
       casadi_int k_el = k[el]-ind1;
       nonzeros().at(k_el>=0 ? k_el : k_el+sz) = m->at(el);
     }
   }
References casadi::GenericMatrix< MatType >::is_dense(), casadi::GenericMatrix< MatType >::is_scalar(), casadi::Matrix< Scalar >::nonzeros(), casadi::GenericMatrix< MatType >::size(), casadi::GenericMatrix< MatType >::size1(), casadi::GenericMatrix< MatType >::size2(), casadi::Matrix< Scalar >::sparsity(), casadi::str(), casadi::Matrix< Scalar >::T(), and casadi::to_slice().
set_nz() [2/2]
template<typename Scalar > void casadi::Matrix< Scalar >::set_nz (const Matrix< Scalar > & m, bool ind1, const Slice & k)
Set a set of nonzeros
Definition at line 435 of file matrix_impl.hpp.
{
     // Scalar
     if (kk.is_scalar(nnz())) {
       nonzeros().at(kk.scalar(nnz())) = m.scalar();
       return;
     }
     // Fallback on IM
     set_nz(m, ind1, kk.all(nnz(), ind1));
   }
References casadi::Slice::all(), casadi::Slice::is_scalar(), casadi::Matrix< Scalar >::scalar(), and casadi::Slice::scalar().
set_precision()
template<typename Scalar > void casadi::Matrix< Scalar >::set_precision (casadi_int precision) static
Definition at line 39 of file matrix_impl.hpp.
 { stream_precision_ = precision; }
set_scientific()
template<typename Scalar > void casadi::Matrix< Scalar >::set_scientific (bool scientific) static
Definition at line 45 of file matrix_impl.hpp.
 { stream_scientific_ = scientific; }
set_width()
template<typename Scalar > void casadi::Matrix< Scalar >::set_width (casadi_int width) static
Definition at line 42 of file matrix_impl.hpp.
 { stream_width_ = width; }
shared()
template<typename Scalar > static void casadi::Matrix< Scalar >::shared (std::vector< Matrix< Scalar > > & ex, std::vector< Matrix< Scalar > > & v, std::vector< Matrix< Scalar > > & vdef, const std::string & v_prefix, const std::string & v_suffix) static
Functions called by friend functions defined for GenericMatrix
simplify()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::simplify (const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
size() [1/2]
std::pair< casadi_int, casadi_int > casadi::GenericMatrix< Matrix< Scalar > >::size inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1ax
Definition at line 136 of file generic_matrix.hpp.
{
     return sparsity().size();
   }
size() [2/2]
casadi_int casadi::GenericMatrix< Matrix< Scalar > >::size (casadi_int axis) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1ay
Definition at line 141 of file generic_matrix.hpp.
{
     return sparsity().size(axis);
   }
size1()
casadi_int casadi::GenericMatrix< Matrix< Scalar > >::size1 inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1as
Definition at line 109 of file generic_matrix.hpp.
{
     return sparsity().size1();
   }
size2()
casadi_int casadi::GenericMatrix< Matrix< Scalar > >::size2 inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1au
Definition at line 119 of file generic_matrix.hpp.
{
     return sparsity().size2();
   }
skew()
Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::skew (const Matrix< Scalar > & a) static inherited
Definition at line 228 of file generic_matrix.hpp.
{
     casadi_assert(a.is_vector() && (a.size1()==3 || a.size2()==3),
       "skew(a): Expecting 3-vector, got " + a.dim() + ".");
     MatType x = a(0);
     MatType y = a(1);
     MatType z = a(2);
     return blockcat(std::vector< std::vector<MatType> >({{0, -z, y}, {z, 0, -x}, {-y, x, 0}}));
   }
soc()
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::soc (const Matrix< Scalar > & x, const Matrix< Scalar > & y) static inherited
Functions called by friend functions defined here
solve() [1/2]
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::solve (const Matrix< Scalar > & A, const Matrix< Scalar > & b) static
Functions called by friend functions defined for GenericMatrix
Referenced by casadi::SymbolicQr::init().
solve() [2/2]
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::solve (const Matrix< Scalar > & A, const Matrix< Scalar > & b, const std::string & lsolver, const Dict & opts) static
Functions called by friend functions defined for GenericMatrix
sparsify()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::sparsify (const Matrix< Scalar > & x, double tol = 0) static
Functions called by friend functions defined here
sparsity()
template<typename Scalar > const Sparsity& casadi::Matrix< Scalar >::sparsity () const
Referenced by casadi::HpmpcInterface::blocksparsity(), casadi::HpipmInterface::blocksparsity(), casadi::FatropConicInterface::blocksparsity(), casadi::ConstantMX::create(), casadi::dplesol(), casadi::Matrix< Scalar >::get(), casadi::MX::get(), casadi::FunctionInternal::get_jac_sparsity_hierarchical(), casadi::FunctionInternal::get_jac_sparsity_hierarchical_symm(), casadi::MX::get_nz(), casadi::SnoptInterface::init(), casadi::SuperscsInterface::init(), casadi::SymbolicQr::init(), casadi::CplexInterface::init_mem(), casadi::SuperscsInterface::init_mem(), casadi::Linsol::neig(), casadi::Linsol::nfact(), casadi::CsparseInterface::nfact(), casadi::Linsol::rank(), casadi::Matrix< Scalar >::set(), casadi::MX::set(), casadi::Matrix< Scalar >::set_nz(), casadi::MX::set_nz(), casadi::Linsol::sfact(), casadi::CplexInterface::solve(), casadi::GurobiInterface::solve(), casadi::SuperscsInterface::solve(), casadi::SnoptInterface::userfun(), and casadi::OptiNode::value().
sparsity_cast()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::sparsity_cast (const Matrix< Scalar > & x, const Sparsity & sp) static
Functions called by friend functions defined for SparsityInterface
sprank()
static casadi_int casadi::GenericMatrix< Matrix< Scalar > >::sprank (const Matrix< Scalar > & x) inline static inherited
Definition at line 215 of file generic_matrix.hpp.
 { return Sparsity::sprank(x.sparsity());}
substitute() [1/2]
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::substitute (const Matrix< Scalar > & ex, const Matrix< Scalar > & v, const Matrix< Scalar > & vdef) static
Functions called by friend functions defined for GenericMatrix
substitute() [2/2]
template<typename Scalar > static std::vector<Matrix<Scalar> > casadi::Matrix< Scalar >::substitute (const std::vector< Matrix< Scalar > > & ex, const std::vector< Matrix< Scalar > > & v, const std::vector< Matrix< Scalar > > & vdef) static
Functions called by friend functions defined for GenericMatrix
substitute_inplace()
template<typename Scalar > static void casadi::Matrix< Scalar >::substitute_inplace (const std::vector< Matrix< Scalar > > & v, std::vector< Matrix< Scalar > > & vdef, std::vector< Matrix< Scalar > > & ex, bool revers) static
Functions called by friend functions defined for GenericMatrix
sum1()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::sum1 (const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
sum2()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::sum2 (const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
sumsqr()
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::sumsqr (const Matrix< Scalar > & x) inline static inherited
Definition at line 225 of file generic_matrix.hpp.
 { return dot(x, x);}
sym() [1/7]
static std::vector<Matrix< Scalar > > casadi::GenericMatrix< Matrix< Scalar > >::sym (const std::string & name, casadi_int nrow, casadi_int ncol, casadi_int p) inline static inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1de
Definition at line 1234 of file generic_matrix.hpp.
{
       return sym(name, Sparsity::dense(nrow, ncol), p);
     }
sym() [2/7]
static std::vector<std::vector<Matrix< Scalar > > > casadi::GenericMatrix< Matrix< Scalar > >::sym (const std::string & name, casadi_int nrow, casadi_int ncol, casadi_int p, casadi_int r) inline static inherited
with nrow-by-ncol symbolic primitives
Extra doc: https://github.com/casadi/casadi/wiki/L_1dg
Definition at line 1253 of file generic_matrix.hpp.
{
       return sym(name, Sparsity::dense(nrow, ncol), p, r);
     }
sym() [3/7]
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::sym (const std::string & name, casadi_int nrow = 1, casadi_int ncol = 1) inline static inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1da
Examples
SX/SXaddition.cc, and SX/ssym.py.
Definition at line 1206 of file generic_matrix.hpp.
{
       return sym(name, Sparsity::dense(nrow, ncol));
     }
sym() [4/7]
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::sym (const std::string & name, const Sparsity & sp) inline static inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1dc
Definition at line 1220 of file generic_matrix.hpp.
{
       return MatType::_sym(name, sp);
     }
sym() [5/7]
std::vector< Matrix< Scalar > > casadi::GenericMatrix< Matrix< Scalar > >::sym (const std::string & name, const Sparsity & sp, casadi_int p) static inherited
with symbolic primitives of given sparsity
Extra doc: https://github.com/casadi/casadi/wiki/L_1dd
Definition at line 1229 of file generic_matrix.hpp.
{
     std::vector<MatType> ret(p);
     std::stringstream ss;
     for (casadi_int k=0; k<p; ++k) {
       ss.str("");
       ss << name << k;
       ret[k] = sym(ss.str(), sp);
     }
     return ret;
   }
sym() [6/7]
std::vector< std::vector< Matrix< Scalar > > > casadi::GenericMatrix< Matrix< Scalar > >::sym (const std::string & name, const Sparsity & sp, casadi_int p, casadi_int r) static inherited
symbolic primitives with given sparsity
Extra doc: https://github.com/casadi/casadi/wiki/L_1df
Definition at line 1245 of file generic_matrix.hpp.
{
     std::vector<std::vector<MatType> > ret(r);
     for (casadi_int k=0; k<r; ++k) {
       std::stringstream ss;
       ss << name << "_" << k;
       ret[k] = sym(ss.str(), sp, p);
     }
     return ret;
   }
sym() [7/7]
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::sym (const std::string & name, const std::pair< casadi_int, casadi_int > & rc) inline static inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1db
Definition at line 1213 of file generic_matrix.hpp.
{
       return sym(name, rc.first, rc.second);
     }
symvar()
template<typename Scalar > static std::vector<Matrix<Scalar> > casadi::Matrix< Scalar >::symvar (const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
T()
template<typename Scalar > Matrix<Scalar> casadi::Matrix< Scalar >::T () const
Referenced by casadi::Matrix< double >::__nonzero__(), casadi::BSpline::dual(), casadi::Matrix< double >::has_nz(), casadi::QpToNlp::init(), casadi::SymbolicQr::init(), casadi::Conic::sdp_to_socp_init(), casadi::Matrix< Scalar >::set(), casadi::MX::set(), and casadi::Matrix< Scalar >::set_nz().
tangent()
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::tangent (const Matrix< Scalar > & ex, const Matrix< Scalar > & arg, const Dict & opts = Dict()) static inherited
Functions called by friend functions defined here
taylor()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::taylor (const Matrix< Scalar > & ex, const Matrix< Scalar > & x, const Matrix< Scalar > & a, casadi_int order) static
Functions called by friend functions defined here
to_file() [1/2]
template<typename Scalar > static void casadi::Matrix< Scalar >::to_file (const std::string & filename, const Sparsity & sp, const Scalar * nonzeros, const std::string & format = "") static
to_file() [2/2]
template<typename Scalar > void casadi::Matrix< Scalar >::to_file (const std::string & filename, const std::string & format = "") const
Export numerical matrix to file
Supported formats:
*   - .mtx   Matrix Market (sparse)
*   - .txt   Ascii full precision representation (sparse)
*            Whitespace separated, aligned.
*            Comments with # % or /
*            Uses C locale
*            Structural zeros represented by 00
*            Does not scale well for large sparse matrices
*
trace()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::trace (const Matrix< Scalar > & x) static
Functions called by friend functions defined for GenericMatrix
triangle()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::triangle (const Matrix< Scalar > & x) static
Functions called by friend functions defined here
tril()
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::tril (const Matrix< Scalar > & x, bool includeDiagonal = true) inline static inherited
Definition at line 219 of file generic_matrix.hpp.
{
       return project(x, Sparsity::tril(x.sparsity(), includeDiagonal));
     }
tril2symm()
Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::tril2symm (const Matrix< Scalar > & x) static inherited
Definition at line 230 of file generic_matrix.hpp.
{
     casadi_assert(x.is_square(),
       "Shape error in tril2symm. Expecting square shape but got " + x.dim());
     casadi_assert(x.nnz_upper()-x.nnz_diag()==0,
       "Sparsity error in tril2symm. Found above-diagonal entries in argument: " + x.dim());
     return x +  x.T() - diag(diag(x));
   }
triplet() [1/3]
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::triplet (const std::vector< casadi_int > & row, const std::vector< casadi_int > & col, const Matrix< Scalar > & d) static
Default matrix size is max(col) x max(row)
Extra doc: https://github.com/casadi/casadi/wiki/L_23t
triplet() [2/3]
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::triplet (const std::vector< casadi_int > & row, const std::vector< casadi_int > & col, const Matrix< Scalar > & d, casadi_int nrow, casadi_int ncol) static
Default matrix size is max(col) x max(row)
Extra doc: https://github.com/casadi/casadi/wiki/L_23t
triplet() [3/3]
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::triplet (const std::vector< casadi_int > & row, const std::vector< casadi_int > & col, const Matrix< Scalar > & d, const std::pair< casadi_int, casadi_int > & rc) static
Default matrix size is max(col) x max(row)
Extra doc: https://github.com/casadi/casadi/wiki/L_23t
triu()
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::triu (const Matrix< Scalar > & x, bool includeDiagonal = true) inline static inherited
Definition at line 222 of file generic_matrix.hpp.
{
       return project(x, Sparsity::triu(x.sparsity(), includeDiagonal));
     }
triu2symm()
Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::triu2symm (const Matrix< Scalar > & x) static inherited
Definition at line 231 of file generic_matrix.hpp.
{
     casadi_assert(x.is_square(),
       "Shape error in triu2symm. Expecting square shape but got " + x.dim());
     casadi_assert(x.nnz_lower()-x.nnz_diag()==0,
       "Sparsity error in triu2symm. Found below-diagonal entries in argument: " + x.dim());
     return x + x.T() - diag(diag(x));
   }
type_name()
template<typename Scalar > std::string casadi::Matrix< Scalar >::type_name static
Definition at line 606 of file matrix_impl.hpp.
 { return matrixName<Scalar>(); }
unary()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::unary (casadi_int op, const Matrix< Scalar > & x) static
Extra doc: https://github.com/casadi/casadi/wiki/L_18o
unite()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::unite (const Matrix< Scalar > & A, const Matrix< Scalar > & B) static
Functions called by friend functions defined for GenericMatrix
vertcat()
template<typename Scalar > static Matrix<Scalar> casadi::Matrix< Scalar >::vertcat (const std::vector< Matrix< Scalar > > & v) static
Functions called by friend functions defined for SparsityInterface
vertsplit()
template<typename Scalar > static std::vector< Matrix<Scalar> > casadi::Matrix< Scalar >::vertsplit (const Matrix< Scalar > & x, const std::vector< casadi_int > & offset) static
Functions called by friend functions defined for SparsityInterface
which_depends()
template<typename Scalar > static std::vector<bool> casadi::Matrix< Scalar >::which_depends (const Matrix< Scalar > & expr, const Matrix< Scalar > & var, casadi_int order = 1, bool tr = false) static
Functions called by friend functions defined here
which_function()
Function CASADI_EXPORT casadi::SX::which_function
Extra doc: https://github.com/casadi/casadi/wiki/L_28n
Definition at line 170 of file sx_instantiator.cpp.
{
     return scalar().which_function();
   }
References casadi::Matrix< Scalar >::scalar().
which_output()
casadi_int CASADI_EXPORT casadi::SX::which_output
Extra doc: https://github.com/casadi/casadi/wiki/L_28m
Definition at line 175 of file sx_instantiator.cpp.
{
     return scalar().which_output();
   }
References casadi::Matrix< Scalar >::scalar().
zeros() [1/3]
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::zeros (casadi_int nrow = 1, casadi_int ncol = 1) inline static inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1dh
Definition at line 1262 of file generic_matrix.hpp.
{
       return zeros(Sparsity::dense(nrow, ncol));
     }
zeros() [2/3]
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::zeros (const Sparsity & sp) inline static inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1dh
Definition at line 1265 of file generic_matrix.hpp.
 { return MatType(sp, 0, false);}
zeros() [3/3]
static Matrix< Scalar > casadi::GenericMatrix< Matrix< Scalar > >::zeros (const std::pair< casadi_int, casadi_int > & rc) inline static inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1dh
Definition at line 1266 of file generic_matrix.hpp.
{
       return zeros(rc.first, rc.second);
     }
Friends And Related Function Documentation
get_ptr [1/2]
template<typename Scalar > const Scalar* get_ptr (const Matrix< Scalar > & v) friend
Get a pointer to the data
Definition at line 1001 of file matrix_decl.hpp.
 { return v.ptr(); }
get_ptr [2/2]
template<typename Scalar > Scalar* get_ptr (Matrix< Scalar > & v) friend
Get a pointer to the data
Definition at line 1000 of file matrix_decl.hpp.
 { return v.ptr(); }
The documentation for this class was generated from the following files:
casadi_common.hpp
matrix_decl.hpp
matrix_impl.hpp
sx.hpp
sx_instantiator.cpp