CasADi: casadi::SerializerBase Class Reference
casadi::SerializerBase Class Reference
#include <serializer.hpp>
Detailed Description
Definition at line 48 of file serializer.hpp.
Public Types
enum SerializationType {
SERIALIZED_SPARSITY , SERIALIZED_MX , SERIALIZED_DM , SERIALIZED_SX ,
SERIALIZED_LINSOL , SERIALIZED_FUNCTION , SERIALIZED_GENERICTYPE , SERIALIZED_INT ,
SERIALIZED_DOUBLE , SERIALIZED_STRING , SERIALIZED_SPARSITY_VECTOR , SERIALIZED_MX_VECTOR ,
SERIALIZED_DM_VECTOR , SERIALIZED_SX_VECTOR , SERIALIZED_LINSOL_VECTOR , SERIALIZED_FUNCTION_VECTOR ,
SERIALIZED_GENERICTYPE_VECTOR , SERIALIZED_INT_VECTOR , SERIALIZED_DOUBLE_VECTOR , SERIALIZED_STRING_VECTOR
}
Public Member Functions
SerializerBase (std::unique_ptr< std::ostream > stream, const Dict &opts=Dict())
~SerializerBase ()
void pack (const Sparsity &e)
void pack (const MX &e)
void pack (const Matrix< double > &e)
void pack (const Matrix< SXElem > &e)
void pack (const Linsol &e)
void pack (const Function &e)
void pack (const GenericType &e)
void pack (const casadi_int &e)
void pack (const double &e)
void pack (const std::string &e)
void pack (const std::vector< Sparsity > &e)
void pack (const std::vector< MX > &e)
void pack (const std::vector< Matrix< double > > &e)
void pack (const std::vector< Matrix< SXElem > > &e)
void pack (const std::vector< Linsol > &e)
void pack (const std::vector< Function > &e)
void pack (const std::vector< GenericType > &e)
void pack (const std::vector< casadi_int > &e)
void pack (const std::vector< double > &e)
void pack (const std::vector< std::string > &e)
void connect (DeserializerBase &s)
void reset ()
Static Public Member Functions
static std::string type_to_string (SerializationType type)
Protected Member Functions
SerializingStream & serializer ()
Protected Attributes
std::unique_ptr< std::ostream > sstream_
std::unique_ptr< SerializingStream > serializer_
Friends
class DeserializerBase
Member Enumeration Documentation
SerializationType
enum casadi::SerializerBase::SerializationType
Enumerator
SERIALIZED_SPARSITY
SERIALIZED_MX
SERIALIZED_DM
SERIALIZED_SX
SERIALIZED_LINSOL
SERIALIZED_FUNCTION
SERIALIZED_GENERICTYPE
SERIALIZED_INT
SERIALIZED_DOUBLE
SERIALIZED_STRING
SERIALIZED_SPARSITY_VECTOR
SERIALIZED_MX_VECTOR
SERIALIZED_DM_VECTOR
SERIALIZED_SX_VECTOR
SERIALIZED_LINSOL_VECTOR
SERIALIZED_FUNCTION_VECTOR
SERIALIZED_GENERICTYPE_VECTOR
SERIALIZED_INT_VECTOR
SERIALIZED_DOUBLE_VECTOR
SERIALIZED_STRING_VECTOR
Definition at line 78 of file serializer.hpp.
{
       SERIALIZED_SPARSITY,
       SERIALIZED_MX,
       SERIALIZED_DM,
       SERIALIZED_SX,
       SERIALIZED_LINSOL,
       SERIALIZED_FUNCTION,
       SERIALIZED_GENERICTYPE,
       SERIALIZED_INT,
       SERIALIZED_DOUBLE,
       SERIALIZED_STRING,
       SERIALIZED_SPARSITY_VECTOR,
       SERIALIZED_MX_VECTOR,
       SERIALIZED_DM_VECTOR,
       SERIALIZED_SX_VECTOR,
       SERIALIZED_LINSOL_VECTOR,
       SERIALIZED_FUNCTION_VECTOR,
       SERIALIZED_GENERICTYPE_VECTOR,
       SERIALIZED_INT_VECTOR,
       SERIALIZED_DOUBLE_VECTOR,
       SERIALIZED_STRING_VECTOR,
     };
Constructor & Destructor Documentation
SerializerBase()
casadi::SerializerBase::SerializerBase (std::unique_ptr< std::ostream > stream, const Dict & opts = Dict())
Definition at line 51 of file serializer.cpp.
                                                                                      :
         sstream_(std::move(stream)),
         serializer_(new SerializingStream(*sstream_, opts)) {
     }
~SerializerBase()
casadi::SerializerBase::~SerializerBase ()
Definition at line 98 of file serializer.cpp.
 { }
Member Function Documentation
connect()
void casadi::SerializerBase::connect (DeserializerBase & s)
Definition at line 203 of file serializer.cpp.
{
     serializer_->connect(*s.deserializer_);
   }
References connect().
Referenced by connect().
pack() [1/20]
void casadi::SerializerBase::pack (const casadi_int & e)
pack() [2/20]
void casadi::SerializerBase::pack (const double & e)
pack() [3/20]
void casadi::SerializerBase::pack (const Function & e)
pack() [4/20]
void casadi::SerializerBase::pack (const GenericType & e)
pack() [5/20]
void casadi::SerializerBase::pack (const Linsol & e)
pack() [6/20]
void casadi::SerializerBase::pack (const Matrix< double > & e)
pack() [7/20]
void casadi::SerializerBase::pack (const Matrix< SXElem > & e)
pack() [8/20]
void casadi::SerializerBase::pack (const MX & e)
pack() [9/20]
void casadi::SerializerBase::pack (const Sparsity & e)
Referenced by casadi::Function::save().
pack() [10/20]
void casadi::SerializerBase::pack (const std::string & e)
pack() [11/20]
void casadi::SerializerBase::pack (const std::vector< casadi_int > & e)
pack() [12/20]
void casadi::SerializerBase::pack (const std::vector< double > & e)
pack() [13/20]
void casadi::SerializerBase::pack (const std::vector< Function > & e)
pack() [14/20]
void casadi::SerializerBase::pack (const std::vector< GenericType > & e)
pack() [15/20]
void casadi::SerializerBase::pack (const std::vector< Linsol > & e)
pack() [16/20]
void casadi::SerializerBase::pack (const std::vector< Matrix< double > > & e)
pack() [17/20]
void casadi::SerializerBase::pack (const std::vector< Matrix< SXElem > > & e)
pack() [18/20]
void casadi::SerializerBase::pack (const std::vector< MX > & e)
pack() [19/20]
void casadi::SerializerBase::pack (const std::vector< Sparsity > & e)
pack() [20/20]
void casadi::SerializerBase::pack (const std::vector< std::string > & e)
reset()
void casadi::SerializerBase::reset ()
Definition at line 206 of file serializer.cpp.
{
     serializer_->reset();
   }
References serializer_.
serializer()
SerializingStream & casadi::SerializerBase::serializer () protected
Definition at line 123 of file serializer.cpp.
{
       return *serializer_;
     }
References serializer_.
type_to_string()
std::string casadi::SerializerBase::type_to_string (SerializationType type) static
Definition at line 56 of file serializer.cpp.
{
       switch (type) {
         case SERIALIZED_SPARSITY: return "sparsity";
         case SERIALIZED_MX: return "mx";
         case SERIALIZED_DM: return "dm";
         case SERIALIZED_SX: return "sx";
         case SERIALIZED_LINSOL: return "linsol";
         case SERIALIZED_FUNCTION: return "function";
         case SERIALIZED_GENERICTYPE: return "generictype";
         case SERIALIZED_INT: return "int";
         case SERIALIZED_DOUBLE: return "double";
         case SERIALIZED_STRING: return "string";
         case SERIALIZED_SPARSITY_VECTOR: return "sparsity_vector";
         case SERIALIZED_MX_VECTOR: return "mx_vector";
         case SERIALIZED_DM_VECTOR: return "dm_vector";
         case SERIALIZED_SX_VECTOR: return "sx_vector";
         case SERIALIZED_LINSOL_VECTOR: return "linsol_vector";
         case SERIALIZED_FUNCTION_VECTOR: return "function_vector";
         case SERIALIZED_GENERICTYPE_VECTOR: return "generictype_vector";
         case SERIALIZED_INT_VECTOR: return "int_vector";
         case SERIALIZED_DOUBLE_VECTOR: return "double_vector";
         case SERIALIZED_STRING_VECTOR: return "string_vector";
         default: casadi_error("Unknown type" + str(type));
       }
     }
References SERIALIZED_DM, SERIALIZED_DM_VECTOR, SERIALIZED_DOUBLE, SERIALIZED_DOUBLE_VECTOR, SERIALIZED_FUNCTION, SERIALIZED_FUNCTION_VECTOR, SERIALIZED_GENERICTYPE, SERIALIZED_GENERICTYPE_VECTOR, SERIALIZED_INT, SERIALIZED_INT_VECTOR, SERIALIZED_LINSOL, SERIALIZED_LINSOL_VECTOR, SERIALIZED_MX, SERIALIZED_MX_VECTOR, SERIALIZED_SPARSITY, SERIALIZED_SPARSITY_VECTOR, SERIALIZED_STRING, SERIALIZED_STRING_VECTOR, SERIALIZED_SX, SERIALIZED_SX_VECTOR, and casadi::str().
Friends And Related Function Documentation
DeserializerBase
friend class DeserializerBase friend
Definition at line 49 of file serializer.hpp.
Member Data Documentation
serializer_
std::unique_ptr<SerializingStream> casadi::SerializerBase::serializer_ protected
Definition at line 109 of file serializer.hpp.
Referenced by casadi::DeserializerBase::connect(), reset(), and serializer().
sstream_
std::unique_ptr<std::ostream> casadi::SerializerBase::sstream_ protected
Definition at line 108 of file serializer.hpp.
Referenced by casadi::StringSerializer::encode(), and casadi::FileSerializer::FileSerializer().
The documentation for this class was generated from the following files:
serializer.hpp
serializer.cpp