CasADi: casadi::DirResource Class Reference
casadi::DirResource Class Reference
#include <resource_internal.hpp>
Detailed Description
Definition at line 66 of file resource_internal.hpp.
Public Types
using weak_ref_type = WeakRefInternal
Public Member Functions
DirResource (const std::string &path)
Initialize with a path.
~DirResource () override
const std::string & path () const override
Get path for a consumer.
std::string class_name () const override
Get type name.
void disp (std::ostream &stream, bool more) const override
Print description.
void serialize_type (SerializingStream &s) const override
void serialize_body (SerializingStream &s) const override
void serialize (SerializingStream &s) const
void change_option (const std::string &option_name, const GenericType &option_value)
casadi_int getCount () const
Get the reference count.
std::string debug_repr (const SharedObjectInternal *) const
GenericWeakRef< SharedObject, SharedObjectInternal > * weak ()
Get a weak reference to the object.
Static Public Member Functions
static ResourceInternal * deserialize (DeserializingStream &s)
Protected Member Functions
DirResource (DeserializingStream &s)
void initSingleton ()
void destroySingleton ()
B shared_from_this ()
Get a shared object from the current internal object.
const B shared_from_this () const
Get a shared object from the current internal object.
Protected Attributes
std::string serialize_mode_
Member Typedef Documentation
weak_ref_type
using casadi::SharedObjectInternal::weak_ref_type = WeakRefInternal inherited
Definition at line 152 of file shared_object.hpp.
Constructor & Destructor Documentation
DirResource() [1/2]
casadi::DirResource::DirResource (const std::string & path)
Extra doc: https://github.com/casadi/casadi/wiki/L_2cu
Definition at line 40 of file resource_internal.cpp.
     : ResourceInternal(),
       path_(path) {
   path_ = path;
 }
References path().
Referenced by deserialize().
~DirResource()
casadi::DirResource::~DirResource () override
Definition at line 50 of file resource_internal.cpp.
{
 }
DirResource() [2/2]
casadi::DirResource::DirResource (DeserializingStream & s) explicit protected
Definition at line 211 of file resource_internal.cpp.
                                                : ResourceInternal(s) {
   s.version("DirResource", 1);
   s.unpack("DirResource::path", path_);
 }
References casadi::DeserializingStream::unpack(), and casadi::DeserializingStream::version().
Member Function Documentation
change_option()
void casadi::ResourceInternal::change_option (const std::string & option_name, const GenericType & option_value) inherited
Definition at line 53 of file resource_internal.cpp.
{
   if (option_name=="serialize_mode") {
     serialize_mode_ = option_value.to_string();
     casadi_assert(serialize_mode_=="embed" || serialize_mode_=="link",
       "Invalid serialization mode: " + serialize_mode_ + ". Pick 'link' or 'embed'.");
   } else {
     casadi_error("Option '" + option_name + "' does not exist");
   }
 }
References casadi::ResourceInternal::serialize_mode_, and casadi::GenericType::to_string().
class_name()
std::string casadi::DirResource::class_name () const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_2cv
Implements casadi::SharedObjectInternal.
Definition at line 79 of file resource_internal.hpp.
 {return "DirResource";}
Referenced by serialize_type().
debug_repr()
std::string casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::debug_repr (const Internal * i) const inherited
Definition at line 62 of file generic_shared_internal.hpp.
{
     // Note: i != this because of something something multiple inheritance
     return str( (casadi_int)(i)) + "/" + static_cast<const Internal*>(this)->class_name();
   }
deserialize()
ResourceInternal * casadi::DirResource::deserialize (DeserializingStream & s) static
Definition at line 191 of file resource_internal.cpp.
{
   DirResource* ret = new DirResource(s);
   return ret;
 }
References DirResource().
Referenced by casadi::ResourceInternal::deserialize().
destroySingleton()
void casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::destroySingleton () inline protected inherited
Called in the destructor of singletons
Definition at line 77 of file generic_shared_internal.hpp.
{
       static_cast<Internal*>(this)->count--;
     }
disp()
void casadi::DirResource::disp (std::ostream & stream, bool more) const override virtual
Implements casadi::SharedObjectInternal.
Definition at line 46 of file resource_internal.cpp.
{
   stream << "DirResource(\"" << path_ << "\")";
 }
getCount()
casadi_int casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::getCount inherited
Definition at line 60 of file generic_shared_internal.hpp.
{
     return static_cast<const Internal*>(this)->count;
   }
initSingleton()
void casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::initSingleton () inline protected inherited
Called in the constructor of singletons to avoid that the counter reaches zero
Definition at line 71 of file generic_shared_internal.hpp.
{
       casadi_assert_dev(static_cast<Internal*>(this)->count==0);
       static_cast<Internal*>(this)->count++;
     }
path()
const std::string& casadi::DirResource::path () const inline override virtual
Implements casadi::ResourceInternal.
Definition at line 74 of file resource_internal.hpp.
 {return path_;}
Referenced by DirResource().
serialize()
void casadi::ResourceInternal::serialize (SerializingStream & s) const inherited
Definition at line 147 of file resource_internal.cpp.
{
   s.version("ResourceInternal", 1);
   serialize_type(s);
   serialize_body(s);
 }
References casadi::ResourceInternal::serialize_body(), casadi::ResourceInternal::serialize_type(), and casadi::SerializingStream::version().
serialize_body()
void casadi::DirResource::serialize_body (SerializingStream & s) const override virtual
Reimplemented from casadi::ResourceInternal.
Definition at line 257 of file resource_internal.cpp.
{
   ResourceInternal::serialize_body(s);
   s.version("DirResource", 1);
   if (serialize_mode_=="embed") {
     // Decay into ZipMemResource
     std::stringstream ss;
     Archiver::getPlugin("libzip").exposed.pack_to_stream(path_, ss);
     ss.clear();
     ss.seekg(0, std::ios::beg);
     s.pack("ZipMemResource::blob", ss);
   } else {
     s.pack("DirResource::path", path_);
   }
 }
References casadi::PluginInterface< Archiver >::getPlugin(), casadi::SerializingStream::pack(), casadi::ResourceInternal::serialize_body(), casadi::ResourceInternal::serialize_mode_, and casadi::SerializingStream::version().
serialize_type()
void casadi::DirResource::serialize_type (SerializingStream & s) const override virtual
Reimplemented from casadi::ResourceInternal.
Definition at line 229 of file resource_internal.cpp.
{
   if (serialize_mode_=="embed") {
     // Decay into ZipMemResource
     std::string class_name = "ZipMemResource";
     s.pack("ResourceInternal::type", class_name);
   } else if (serialize_mode_=="link") {
     std::string class_name = "DirResource";
     s.pack("ResourceInternal::type", class_name);
   } else {
     casadi_error("Unknown serialization mode: " + serialize_mode_);
   }
 }
References class_name(), casadi::SerializingStream::pack(), and casadi::ResourceInternal::serialize_mode_.
shared_from_this() [1/2]
B casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::shared_from_this () inline protected inherited
Definition at line 83 of file generic_shared_internal.hpp.
{
       casadi_assert_dev(B::test_cast(static_cast<Internal*>(this)));
       B ret;
       ret.own(static_cast<Internal*>(this));
       return ret;
     }
shared_from_this() [2/2]
const B casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::shared_from_this () const inline protected inherited
Definition at line 92 of file generic_shared_internal.hpp.
{
       casadi_assert_dev(B::test_cast(static_cast<const Internal*>(this)));
       B ret;
       ret.own(const_cast<Internal*>(static_cast<const Internal*>(this)));
       return ret;
     }
weak()
GenericWeakRef< SharedObject , SharedObjectInternal > * casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::weak inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1ai
Definition at line 67 of file generic_shared_internal.hpp.
{
     if (weak_ref_==nullptr) {
       weak_ref_ = new GenericWeakRef<Shared, Internal>(static_cast<Internal*>(this));
     }
     return weak_ref_;
   }
Member Data Documentation
serialize_mode_
std::string casadi::ResourceInternal::serialize_mode_ protected inherited
Definition at line 63 of file resource_internal.hpp.
Referenced by casadi::ResourceInternal::change_option(), casadi::ResourceInternal::ResourceInternal(), casadi::ResourceInternal::serialize_body(), serialize_body(), casadi::ZipResource::serialize_body(), serialize_type(), and casadi::ZipResource::serialize_type().
The documentation for this class was generated from the following files:
resource_internal.hpp
resource_internal.cpp