CasADi: casadi::UnarySX Class Reference
casadi::UnarySX Class Reference
Represents a basic unary operation on an SXElem node.
#include <unary_sx.hpp>
Detailed Description
Author
Joel Andersson
Date
2012
Extra doc: https://github.com/casadi/casadi/wiki/L_dt
Definition at line 42 of file unary_sx.hpp.
Public Member Functions
~UnarySX () override
Destructor.
std::string class_name () const override
Get type name.
bool is_smooth () const override
Check if smooth.
bool is_op (casadi_int op) const override
check properties of a node
bool is_equal (const SXNode *node, casadi_int depth) const override
Check if two nodes are equivalent up to a given depth.
casadi_int n_dep () const override
Number of dependencies.
const SXElem & dep (casadi_int i) const override
get the reference of a dependency
SXElem & dep (casadi_int i) override
get the reference of a child
casadi_int op () const override
Get the operation.
std::string print (const std::string &arg1, const std::string &arg2) const override
Print expression.
void serialize_node (SerializingStream &s) const override
virtual const std::string & name () const
virtual void disp (std::ostream &stream, bool more) const
print
void can_inline (std::map< const SXNode *, casadi_int > &nodeind) const
Find out which nodes can be inlined.
std::string print_compact (std::map< const SXNode *, casadi_int > &nodeind, std::vector< std::string > &intermed) const
Print compact.
bool marked () const
void mark () const
void serialize (SerializingStream &s) const
Serialize an object.
virtual bool is_constant () const
check properties of a node
virtual bool is_integer () const
check properties of a node
virtual bool is_symbolic () const
check properties of a node
virtual bool is_zero () const
check properties of a node
virtual bool is_almost_zero (double tol) const
check properties of a node
virtual bool is_one () const
check properties of a node
virtual bool is_minus_one () const
check properties of a node
virtual bool is_nan () const
check properties of a node
virtual bool is_inf () const
check properties of a node
virtual bool is_minus_inf () const
check properties of a node
virtual double to_double () const
Get value of a constant node.
virtual casadi_int to_int () const
Get value of a constant node.
Static Public Member Functions
static SXElem create (unsigned char op, const SXElem &dep)
Create a unary expression.
static SXNode * deserialize (DeserializingStream &s, casadi_int op)
static void safe_delete (SXNode *n)
Non-recursive delete.
static SXNode * deserialize (DeserializingStream &s)
Public Attributes
unsigned char op_
The binary operation as an 1 byte integer (allows 256 values)
SXElem dep_
The dependencies of the node.
int temp
unsigned int count
Static Public Attributes
static casadi_int eq_depth_ = 1
static std::map< casadi_int, SXNode *(*)(DeserializingStream &)> deserialize_map
Constructor & Destructor Documentation
~UnarySX()
casadi::UnarySX::~UnarySX () inline override
Extra doc: https://github.com/casadi/casadi/wiki/L_dw
Definition at line 71 of file unary_sx.hpp.
{
       safe_delete(dep_.assignNoDelete(casadi_limits<SXElem>::nan));
     }
References casadi::SXElem::assignNoDelete(), dep_, and casadi::SXNode::safe_delete().
Member Function Documentation
can_inline()
void casadi::SXNode::can_inline (std::map< const SXNode *, casadi_int > & nodeind) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_a6
Definition at line 103 of file sx_node.cpp.
{
     // Add or mark node in map
     std::map<const SXNode*, casadi_int>::iterator it=nodeind.find(this);
     if (it==nodeind.end()) {
       // First time encountered, mark inlined
       nodeind.insert(it, std::make_pair(this, 0));
       // Handle dependencies with recursion
       for (casadi_int i=0; i<n_dep(); ++i) {
         dep(i)->can_inline(nodeind);
       }
     } else if (it->second==0 && op()!=OP_PARAMETER) {
       // Node encountered before, do not inline (except if symbolic primitive)
       it->second = -1;
     }
   }
References casadi::SXNode::can_inline(), casadi::SXNode::dep(), casadi::SXNode::n_dep(), casadi::SXNode::op(), and casadi::OP_PARAMETER.
Referenced by casadi::SXNode::can_inline(), and casadi::SXNode::disp().
class_name()
std::string casadi::UnarySX::class_name () const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_9y
Implements casadi::SXNode.
Definition at line 76 of file unary_sx.hpp.
 {return "UnarySX";}
create()
static SXElem casadi::UnarySX::create (unsigned char op, const SXElem & dep) inline static
Extra doc: https://github.com/casadi/casadi/wiki/L_dv
Definition at line 55 of file unary_sx.hpp.
{
       if (dep.is_constant()) {
         // Evaluate constant
         double dep_val(dep);
         double ret_val;
         casadi_math<double>::fun(op, dep_val, dep_val, ret_val);
         return ret_val;
       } else {
         // Expression containing free variables
         return SXElem::create(new UnarySX(op, dep));
       }
     }
References casadi::SXElem::create(), dep(), casadi::casadi_math< T >::fun(), casadi::SXElem::is_constant(), and op().
Referenced by casadi::SXElem::inv(), casadi::SXElem::operator-(), and casadi::SXElem::unary().
dep() [1/2]
const SXElem& casadi::UnarySX::dep (casadi_int i) const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_dz
Reimplemented from casadi::SXNode.
Definition at line 98 of file unary_sx.hpp.
 { return dep_; }
References dep_.
Referenced by create(), and deserialize().
dep() [2/2]
SXElem& casadi::UnarySX::dep (casadi_int i) inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_a3
Reimplemented from casadi::SXNode.
Definition at line 99 of file unary_sx.hpp.
 { return dep_; }
References dep_.
deserialize() [1/2]
SXNode * casadi::SXNode::deserialize (DeserializingStream & s) static inherited
Definition at line 209 of file sx_node.cpp.
{
     casadi_int op;
     s.unpack("SXNode::op", op);
     if (casadi_math<MX>::is_binary(op)) {
       return BinarySX::deserialize(s, op);
     } else if (casadi_math<MX>::is_unary(op)) {
       return UnarySX::deserialize(s, op);
     }
     auto it = SXNode::deserialize_map.find(op);
     if (it==SXNode::deserialize_map.end()) {
       casadi_error("Not implemented op " + str(casadi_int(op)));
     } else {
       return it->second(s);
     }
   }
References casadi::BinarySX::deserialize(), deserialize(), casadi::SXNode::deserialize_map, casadi::SXNode::op(), casadi::str(), and casadi::DeserializingStream::unpack().
Referenced by casadi::SXElem::deserialize().
deserialize() [2/2]
static SXNode* casadi::UnarySX::deserialize (DeserializingStream & s, casadi_int op) inline static
Definition at line 127 of file unary_sx.hpp.
{
       SXElem dep;
       s.unpack("UnarySX::dep", dep);
       return new UnarySX(op, dep);
     }
References dep(), op(), and casadi::DeserializingStream::unpack().
Referenced by casadi::SXNode::deserialize().
disp()
void casadi::SXNode::disp (std::ostream & stream, bool more) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_a5
Definition at line 78 of file sx_node.cpp.
{
     // Find out which noded can be inlined
     std::map<const SXNode*, casadi_int> nodeind;
     can_inline(nodeind);
     // Print expression
     std::vector<std::string> intermed;
     std::string s = print_compact(nodeind, intermed);
     // Print intermediate expressions
     for (casadi_int i=0; i<intermed.size(); ++i)
       stream << "@" << (i+1) << "=" << intermed[i] << ", ";
     // Print this
     stream << s;
   }
References casadi::SXNode::can_inline(), and casadi::SXNode::print_compact().
Referenced by casadi::SXElem::disp().
is_almost_zero()
virtual bool casadi::SXNode::is_almost_zero (double tol) const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::ZeroSX, and casadi::RealtypeSX.
Definition at line 74 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::is_almost_zero().
is_constant()
virtual bool casadi::SXNode::is_constant () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::ConstantSX.
Definition at line 69 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::binary(), casadi::SXFunction::init(), and casadi::SXElem::is_constant().
is_equal()
bool casadi::UnarySX::is_equal (const SXNode * node, casadi_int depth) const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_dx
Reimplemented from casadi::SXNode.
Definition at line 85 of file unary_sx.hpp.
{
       const UnarySX* n = dynamic_cast<const UnarySX*>(node);
       return n && n->op_ == op_ &&  SXElem::is_equal(n->dep_, dep_, depth-1);
     }
References dep_, casadi::SXElem::is_equal(), and op_.
is_inf()
virtual bool casadi::SXNode::is_inf () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::InfSX.
Definition at line 78 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::is_inf().
is_integer()
virtual bool casadi::SXNode::is_integer () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::MinusOneSX, casadi::OneSX, casadi::ZeroSX, and casadi::IntegerSX.
Definition at line 70 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::binary(), and casadi::SXElem::is_integer().
is_minus_inf()
virtual bool casadi::SXNode::is_minus_inf () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::MinusInfSX.
Definition at line 79 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::is_minus_inf().
is_minus_one()
virtual bool casadi::SXNode::is_minus_one () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::MinusOneSX.
Definition at line 76 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::binary(), and casadi::SXElem::is_minus_one().
is_nan()
virtual bool casadi::SXNode::is_nan () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::NanSX.
Definition at line 77 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::is_nan().
is_one()
virtual bool casadi::SXNode::is_one () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::OneSX.
Definition at line 75 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::binary(), and casadi::SXElem::is_one().
is_op()
bool casadi::UnarySX::is_op (casadi_int op) const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented from casadi::SXNode.
Definition at line 80 of file unary_sx.hpp.
 { return op_==op; }
References op(), and op_.
is_smooth()
bool casadi::UnarySX::is_smooth () const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_a4
Reimplemented from casadi::SXNode.
Definition at line 78 of file unary_sx.hpp.
 { return operation_checker<SmoothChecker>(op_);}
References op_.
is_symbolic()
virtual bool casadi::SXNode::is_symbolic () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::SymbolicSX.
Definition at line 71 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXFunction::init(), and casadi::SXElem::is_symbolic().
is_zero()
virtual bool casadi::SXNode::is_zero () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::ZeroSX.
Definition at line 72 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::binary(), and casadi::SXElem::is_zero().
mark()
void casadi::SXNode::mark () const inherited
Definition at line 99 of file sx_node.cpp.
{
     temp = -temp-1;
   }
References casadi::SXNode::temp.
marked()
bool casadi::SXNode::marked () const inherited
Definition at line 95 of file sx_node.cpp.
{
     return temp<0;
   }
References casadi::SXNode::temp.
n_dep()
casadi_int casadi::UnarySX::n_dep () const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_dy
Reimplemented from casadi::SXNode.
Definition at line 93 of file unary_sx.hpp.
 { return 1;}
name()
const std::string & casadi::SXNode::name () const virtual inherited
Reimplemented in casadi::SymbolicSX.
Definition at line 66 of file sx_node.cpp.
{
     casadi_error("'name' not defined for " + class_name());
   }
References casadi::SXNode::class_name().
Referenced by casadi::SXElem::name().
op()
casadi_int casadi::UnarySX::op () const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_e0
Implements casadi::SXNode.
Definition at line 104 of file unary_sx.hpp.
 { return op_;}
References op_.
Referenced by create(), deserialize(), and is_op().
print()
std::string casadi::UnarySX::print (const std::string & arg1, const std::string & arg2) const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_e1
Implements casadi::SXNode.
Definition at line 109 of file unary_sx.hpp.
{
       return casadi_math<double>::print(op_, arg1);
     }
References op_, and casadi::casadi_math< T >::print().
print_compact()
std::string casadi::SXNode::print_compact (std::map< const SXNode *, casadi_int > & nodeind, std::vector< std::string > & intermed) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_a7
Definition at line 120 of file sx_node.cpp.
{
     // Get reference to node index
     casadi_int& ind = nodeind[this];
     // If positive, already in intermediate expressions
     if (ind>0) {
       std::stringstream ss;
       ss << "@" << ind;
       return ss.str();
     }
     // Get expressions for dependencies
     std::string arg[2];
     for (casadi_int i=0; i<n_dep(); ++i) {
       arg[i] = dep(i)->print_compact(nodeind, intermed);
     }
     // Get expression for this
     std::string s = print(arg[0], arg[1]);
     // Decide what to do with the expression
     if (ind==0) {
       // Inline expression
       return s;
     } else {
       // Add to list of intermediate expressions and return reference
       intermed.push_back(s);
       ind = intermed.size(); // For subsequent references
       std::stringstream ss;
       ss << "@" << ind;
       return ss.str();
     }
   }
References casadi::SXNode::dep(), casadi::SXNode::n_dep(), casadi::SXNode::print(), and casadi::SXNode::print_compact().
Referenced by casadi::SXNode::disp(), and casadi::SXNode::print_compact().
safe_delete()
void casadi::SXNode::safe_delete (SXNode * n) static inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_a9
Definition at line 155 of file sx_node.cpp.
{
     // Quick return if more owners
     if (n->count>0) return;
     // Delete straight away if it doesn't have any dependencies
     if (!n->n_dep()) {
       delete n;
       return;
     }
     // Stack of expressions to be deleted
     std::stack<SXNode*> deletion_stack;
     // Add the node to the deletion stack
     deletion_stack.push(n);
     // Process stack
     while (!deletion_stack.empty()) {
       // Top element
       SXNode *t = deletion_stack.top();
       // Check if the top element has dependencies with dependencies
       bool added_to_stack = false;
       for (casadi_int c2=0; c2<t->n_dep(); ++c2) { // for all dependencies of the dependency
         // Get the node of the dependency of the top element
         // and remove it from the smart pointer
         SXNode *n2 = t->dep(c2).assignNoDelete(casadi_limits<SXElem>::nan);
         // Check if this is the only reference to the element
         if (n2->count == 0) {
           // Check if unary or binary
           if (!n2->n_dep()) {
             // Delete straight away if not binary
             delete n2;
           } else {
             // Add to deletion stack
             deletion_stack.push(n2);
             added_to_stack = true;
           }
         }
       }
       // Delete and pop from stack if nothing added to the stack
       if (!added_to_stack) {
         delete deletion_stack.top();
         deletion_stack.pop();
       }
     }
   }
References casadi::SXElem::assignNoDelete(), casadi::SXNode::count, casadi::SXNode::dep(), and casadi::SXNode::n_dep().
Referenced by casadi::BinarySX::~BinarySX(), and ~UnarySX().
serialize()
void casadi::SXNode::serialize (SerializingStream & s) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_aa
Definition at line 204 of file sx_node.cpp.
{
     s.pack("SXNode::op", op());
     serialize_node(s);
   }
References casadi::SXNode::op(), casadi::SerializingStream::pack(), and casadi::SXNode::serialize_node().
serialize_node()
void casadi::UnarySX::serialize_node (SerializingStream & s) const inline override virtual
Reimplemented from casadi::SXNode.
Definition at line 123 of file unary_sx.hpp.
{
       s.pack("UnarySX::dep", dep_);
     }
References dep_, and casadi::SerializingStream::pack().
to_double()
double casadi::SXNode::to_double () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9x
Reimplemented in casadi::ConstantSX, casadi::NanSX, casadi::MinusInfSX, casadi::InfSX, casadi::MinusOneSX, casadi::OneSX, casadi::ZeroSX, casadi::IntegerSX, and casadi::RealtypeSX.
Definition at line 54 of file sx_node.cpp.
{
     return std::numeric_limits<double>::quiet_NaN();
   }
Referenced by casadi::SXElem::binary(), and casadi::SXFunction::init().
to_int()
casadi_int casadi::SXNode::to_int () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9x
Reimplemented in casadi::MinusOneSX, casadi::OneSX, casadi::ZeroSX, casadi::IntegerSX, and casadi::RealtypeSX.
Definition at line 58 of file sx_node.cpp.
{
     casadi_error("to_int not defined for " + class_name());
   }
References casadi::SXNode::class_name().
Referenced by casadi::SXElem::binary().
Member Data Documentation
count
unsigned int casadi::SXNode::count inherited
Definition at line 170 of file sx_node.hpp.
Referenced by casadi::SXElem::assignNoDelete(), casadi::SXElem::operator=(), casadi::SXNode::safe_delete(), casadi::SXElem::SXElem(), casadi::SXNode::SXNode(), casadi::UniversalNodeOwner::UniversalNodeOwner(), casadi::InfSX::~InfSX(), casadi::MinusInfSX::~MinusInfSX(), casadi::MinusOneSX::~MinusOneSX(), casadi::NanSX::~NanSX(), casadi::OneSX::~OneSX(), casadi::SXElem::~SXElem(), casadi::SXNode::~SXNode(), and casadi::ZeroSX::~ZeroSX().
dep_
SXElem casadi::UnarySX::dep_
Extra doc: https://github.com/casadi/casadi/wiki/L_e3
Definition at line 121 of file unary_sx.hpp.
Referenced by dep(), is_equal(), serialize_node(), and ~UnarySX().
deserialize_map
std::map< casadi_int, SXNode *(*)(DeserializingStream &)> casadi::SXNode::deserialize_map static inherited
Initial value:
= {
    {OP_PARAMETER, SymbolicSX::deserialize},
    {OP_CONST, ConstantSX_deserialize}}
Definition at line 181 of file sx_node.hpp.
Referenced by casadi::SXNode::deserialize().
eq_depth_
casadi_int casadi::SXNode::eq_depth_ = 1 static inherited
Definition at line 161 of file sx_node.hpp.
Referenced by casadi::SXElem::binary(), casadi::Matrix< Scalar >::get_max_depth(), casadi::SXElem::is_doubled(), and casadi::Matrix< Scalar >::set_max_depth().
op_
unsigned char casadi::UnarySX::op_
Extra doc: https://github.com/casadi/casadi/wiki/L_e2
Definition at line 116 of file unary_sx.hpp.
Referenced by is_equal(), is_op(), is_smooth(), op(), and print().
temp
int casadi::SXNode::temp mutable inherited
Temporary variables to be used in user algorithms like sorting, the user is responsible of making sure that use is thread-safe The variable is initialized to zero
Definition at line 167 of file sx_node.hpp.
Referenced by casadi::SXFunction::init(), casadi::SXNode::mark(), casadi::SXNode::marked(), and casadi::SXNode::SXNode().
The documentation for this class was generated from the following file:
unary_sx.hpp