CasADi: casadi::WeakRef Class Reference
casadi::WeakRef Class Reference
Weak reference type.
#include <shared_object.hpp>
Detailed Description
A weak reference to a SharedObject
Author
Joel Andersson
Date
2013
Extra doc: https://github.com/casadi/casadi/wiki/L_ax
Definition at line 181 of file shared_object.hpp.
Public Member Functions
WeakRef (int dummy=0)
Default constructor.
WeakRef (SharedObject shared)
Construct from a shared object (also implicit type conversion)
SharedObject shared ()
Get a shared (owning) reference.
bool alive () const
Check if alive.
WeakRefInternal * operator-> ()
Access functions of the node.
const WeakRefInternal * operator-> () const
Const access functions of the node.
void own (SharedObjectInternal *node)
void assign (SharedObjectInternal *node)
Assign the node to a node class pointer without reference counting.
SharedObjectInternal * get () const
Get a const pointer to the node.
casadi_int getCount () const
Get the reference count.
void swap (SharedObject &other)
Swap content with another instance.
std::string class_name () const
Get class name.
void disp (std::ostream &stream, bool more=false) const
Print a description of the object.
std::string get_str (bool more=false) const
Get string representation.
void print_ptr (std::ostream &stream=casadi::uout()) const
bool is_null () const
Is a null pointer?
casadi_int __hash__ () const
Returns a number that is unique for a given Node.
WeakRef * weak ()
Get a weak reference to the object.
Protected Member Functions
void count_up ()
void count_down ()
Friends
class SharedObjectInternal
Constructor & Destructor Documentation
WeakRef() [1/2]
casadi::WeakRef::WeakRef (int dummy = 0)
Extra doc: https://github.com/casadi/casadi/wiki/L_ay
Definition at line 133 of file shared_object.cpp.
{
     casadi_assert_dev(dummy==0);
   }
WeakRef() [2/2]
casadi::WeakRef::WeakRef (SharedObject shared)
Extra doc: https://github.com/casadi/casadi/wiki/L_az
Definition at line 157 of file shared_object.cpp.
{
     own(shared.weak()->get());
   }
References casadi::SharedObject::own(), shared(), and casadi::SharedObject::weak().
Member Function Documentation
__hash__()
casadi_int casadi::SharedObject::__hash__ () const inherited
If the Object does not point to any node, "0" is returned.
Extra doc: https://github.com/casadi/casadi/wiki/L_av
Definition at line 129 of file shared_object.cpp.
{
     return reinterpret_cast<casadi_int>(get());
   }
References casadi::SharedObject::get().
alive()
bool casadi::WeakRef::alive () const
Extra doc: https://github.com/casadi/casadi/wiki/L_b1
Definition at line 137 of file shared_object.cpp.
{
     return !is_null() && (*this)->raw_ != nullptr;
   }
References casadi::SharedObject::is_null().
Referenced by casadi::Nlpsol::kkt(), and shared().
assign()
void casadi::SharedObject::assign (SharedObjectInternal * node) inherited
improper use will cause memory leaks!
Extra doc: https://github.com/casadi/casadi/wiki/L_at
Definition at line 52 of file shared_object.cpp.
{
     node = node_;
   }
Referenced by casadi::GenericType::to_double_vector_vector().
class_name()
std::string casadi::SharedObject::class_name () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_au
Definition at line 99 of file shared_object.cpp.
{
     return (*this)->class_name();
   }
Referenced by casadi::MXFunction::export_code_body().
count_down()
void casadi::SharedObject::count_down () protected inherited
Definition at line 84 of file shared_object.cpp.
{
 #ifdef WITH_EXTRA_CHECKS
     casadi_assert_dev(Function::call_depth_==0);
 #endif // WITH_EXTRA_CHECKS
     if (node && --node->count == 0) {
       delete node;
       node = nullptr;
     }
   }
Referenced by casadi::SharedObject::operator=(), casadi::SharedObject::own(), and casadi::SharedObject::~SharedObject().
count_up()
void casadi::SharedObject::count_up () protected inherited
Definition at line 77 of file shared_object.cpp.
{
 #ifdef WITH_EXTRA_CHECKS
     casadi_assert_dev(Function::call_depth_==0);
 #endif // WITH_EXTRA_CHECKS
     if (node) node->count++;
   }
Referenced by casadi::SharedObject::operator=(), casadi::SharedObject::own(), and casadi::SharedObject::SharedObject().
disp()
void casadi::SharedObject::disp (std::ostream & stream, bool more = false) const inherited
Definition at line 103 of file shared_object.cpp.
{
     if (is_null()) {
       stream << "NULL";
     } else {
       (*this)->disp(stream, more);
     }
   }
References casadi::SharedObject::is_null().
Referenced by casadi::Nlpsol::disp_more(), and casadi::CsparseInterface::nfact().
get()
SharedObjectInternal * casadi::SharedObject::get () const inherited
Definition at line 69 of file shared_object.cpp.
{
     return node;
   }
Referenced by casadi::SharedObject::__hash__(), casadi::GenericType::as_bool(), casadi::GenericType::as_bool_vector(), casadi::GenericType::as_dict(), casadi::GenericType::as_double(), casadi::GenericType::as_double_vector(), casadi::GenericType::as_double_vector_vector(), casadi::GenericType::as_function(), casadi::GenericType::as_function_vector(), casadi::GenericType::as_int(), casadi::GenericType::as_int_vector(), casadi::GenericType::as_int_vector_vector(), casadi::GenericType::as_string(), casadi::GenericType::as_string_vector(), casadi::GenericType::as_void_pointer(), casadi::Function::get(), casadi::MX::get(), casadi::Sparsity::get(), casadi::DaeBuilder::get(), casadi::GenericType::getType(), and casadi::GenericType::serialize().
get_str()
std::string casadi::SharedObject::get_str (bool more = false) const inline inherited
Definition at line 138 of file shared_object.hpp.
{
       std::stringstream ss;
       disp(ss, more);
       return ss.str();
     }
getCount()
casadi_int casadi::SharedObject::getCount () const inherited
Definition at line 121 of file shared_object.cpp.
{
     return (*this)->getCount();
   }
Referenced by casadi::MXNode::~MXNode().
is_null()
bool casadi::SharedObject::is_null () const inherited
Definition at line 73 of file shared_object.cpp.
{
     return node==nullptr;
   }
Referenced by casadi::FunctionInternal::add_embedded(), alive(), casadi::FunctionInternal::alloc(), casadi::Nlpsol::callback(), casadi::DaeBuilderInternal::clear_cache(), casadi::Switch::codegen_body(), casadi::Conic::Conic(), casadi::conic_debug(), casadi::Callback::construct(), casadi::Function::deserialize(), casadi::SharedObject::disp(), casadi::FunctionInternal::finalize(), casadi::Switch::find(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::get_n_in(), casadi::Switch::get_n_in(), casadi::FunctionInternal::get_n_out(), casadi::Switch::get_n_out(), casadi::FunctionInternal::get_name_in(), casadi::FunctionInternal::get_name_out(), casadi::FunctionInternal::get_partition(), casadi::FunctionInternal::get_sparsity_in(), casadi::Switch::get_sparsity_in(), casadi::FunctionInternal::get_sparsity_out(), casadi::Switch::get_sparsity_out(), casadi::MXFunction::get_stats(), casadi::GenericType::getType(), casadi::Sparsity::info(), casadi::Nlpsol::init(), casadi::Rootfinder::init(), casadi::Switch::init(), casadi::SnoptInterface::init(), casadi::SundialsInterface::init(), casadi::FastNewton::init(), casadi::Newton::init(), casadi::Scpgen::init(), casadi::BonminInterface::intermediate_callback(), casadi::IpoptInterface::intermediate_callback(), casadi::XFunction< DerivedType, MatType, NodeType >::jac(), casadi::FunctionInternal::jac_is_symm(), casadi::FunctionInternal::jac_sparsity(), casadi::OracleFunction::jit_dependencies(), casadi::SparsityInternal::maxtrans(), casadi::Function::name(), casadi::Function::operator->(), casadi::SharedObject::operator->(), casadi::Function::operator==(), casadi::DaeBuilderInternal::oracle(), casadi::Function::serialize(), casadi::Sparsity::serialize(), casadi::SnoptInterface::set_work(), casadi::OptiNode::solve(), casadi::KnitroInterface::solve(), casadi::WorhpInterface::solve(), casadi::FunctionInternal::sp_forward_block(), casadi::FunctionInternal::sp_reverse(), casadi::Sparsity::uni_coloring(), and casadi::Callback::~Callback().
operator->() [1/2]
WeakRefInternal * casadi::WeakRef::operator-> ()
Extra doc: https://github.com/casadi/casadi/wiki/L_b2
Definition at line 153 of file shared_object.cpp.
{
     return static_cast<WeakRefInternal*>(SharedObject::operator->());
   }
References casadi::SharedObject::operator->().
operator->() [2/2]
const WeakRefInternal * casadi::WeakRef::operator-> () const
Extra doc: https://github.com/casadi/casadi/wiki/L_b3
Definition at line 149 of file shared_object.cpp.
{
     return static_cast<const WeakRefInternal*>(SharedObject::operator->());
   }
References casadi::SharedObject::operator->().
own()
void casadi::SharedObject::own (SharedObjectInternal * node) inherited
Assign the node to a node class pointer (or null)
Definition at line 46 of file shared_object.cpp.
{
     count_down();
     node = node_;
     count_up();
   }
References casadi::SharedObject::count_down(), and casadi::SharedObject::count_up().
Referenced by casadi::Callback::construct(), casadi::Function::construct(), casadi::Function::create(), casadi::Importer::create(), casadi::Linsol::create(), casadi::GenericType::create(), casadi::Sparsity::create(), casadi::DaeBuilder::DaeBuilder(), casadi::FunctionInternal::deserialize(), casadi::Linsol::deserialize(), casadi::GenericType::GenericType(), casadi::LinearInterpolant::get_jacobian(), casadi::Importer::Importer(), casadi::MXFunction::init(), casadi::Linsol::Linsol(), casadi::MX::MX(), casadi::Opti::Opti(), shared(), WeakRef(), and casadi::XmlFile::XmlFile().
print_ptr()
void casadi::SharedObject::print_ptr (std::ostream & stream = casadi::uout()) const inherited
Print the pointer to the internal class
Definition at line 111 of file shared_object.cpp.
{
     stream << node;
   }
shared()
SharedObject casadi::WeakRef::shared ()
Extra doc: https://github.com/casadi/casadi/wiki/L_b0
Definition at line 141 of file shared_object.cpp.
{
     SharedObject ret;
     if (alive()) {
       ret.own((*this)->raw_);
     }
     return ret;
   }
References alive(), and casadi::SharedObject::own().
Referenced by casadi::Nlpsol::kkt(), and WeakRef().
swap()
void casadi::SharedObject::swap (SharedObject & other) inherited
Definition at line 115 of file shared_object.cpp.
{
     SharedObject temp = *this;
     *this = other;
     other = temp;
   }
weak()
WeakRef * casadi::SharedObject::weak () inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_aw
Definition at line 125 of file shared_object.cpp.
{
     return (*this)->weak();
   }
References casadi::SharedObjectInternal::weak().
Referenced by WeakRef().
Friends And Related Function Documentation
SharedObjectInternal
friend class SharedObjectInternal friend
Definition at line 183 of file shared_object.hpp.
The documentation for this class was generated from the following files:
shared_object.hpp
shared_object.cpp