CasADi: casadi::MinusOneSX Class Reference
casadi::MinusOneSX Class Reference
Represents a minus one SX.
#include <constant_sx.hpp>
Detailed Description
Author
Joel Andersson
Date
2010
Extra doc: https://github.com/casadi/casadi/wiki/L_1k5
Definition at line 350 of file constant_sx.hpp.
Public Member Functions
~MinusOneSX () override
void serialize_node (SerializingStream &s) const override
std::string class_name () const override
Get type name.
bool is_constant () const override
Properties.
casadi_int op () const override
Get the operation.
bool is_equal (const SXNode *node, casadi_int depth) const override
Check if two nodes are equivalent up to a given depth.
virtual const std::string & name () const
virtual Function which_function () const
Get called function.
virtual casadi_int which_output () const
Get function output.
virtual casadi_int n_dep () const
Number of dependencies.
virtual SXElem get_output (casadi_int oind) const
Get an output.
virtual const SXElem & dep (casadi_int i) const
get the reference of a child
virtual SXElem & dep (casadi_int i)
get the reference of a child
virtual bool is_smooth () const
Check if smooth.
virtual void disp (std::ostream &stream, bool more) const
print
void can_inline (std::map< const SXNode *, casadi_int > &nodeind) const
Find out which nodes can be inlined.
std::string print_compact (std::map< const SXNode *, casadi_int > &nodeind, std::vector< std::string > &intermed) const
Print compact.
bool marked () const
void mark () const
SXElem shared_from_this ()
Get a shared object from the current internal object.
const SXElem shared_from_this () const
Get a shared object from the current internal object.
void serialize (SerializingStream &s) const
Serialize an object.
double to_double () const override
Get the value.
casadi_int to_int () const override
Get the value.
bool is_integer () const override
Properties.
bool is_minus_one () const override
Properties.
virtual bool is_symbolic () const
check properties of a node
virtual bool is_zero () const
check properties of a node
virtual bool is_op (casadi_int op) const
check properties of a node
virtual bool is_almost_zero (double tol) const
check properties of a node
virtual bool is_one () const
check properties of a node
virtual bool is_nan () const
check properties of a node
virtual bool is_inf () const
check properties of a node
virtual bool is_minus_inf () const
check properties of a node
virtual bool is_call () const
check properties of a node
virtual bool is_output () const
check properties of a node
virtual bool has_output () const
check properties of a node
Static Public Member Functions
static MinusOneSX * singleton ()
static void safe_delete (SXNode *n)
Non-recursive delete.
static SXNode * deserialize (DeserializingStream &s)
Public Attributes
int temp
unsigned int count
Static Public Attributes
static casadi_int eq_depth_ = 1
static std::map< casadi_int, SXNode *(*)(DeserializingStream &)> deserialize_map
Protected Member Functions
std::string print (const std::string &arg1, const std::string &arg2) const override
Print expression.
Constructor & Destructor Documentation
~MinusOneSX()
casadi::MinusOneSX::~MinusOneSX () inline override
Definition at line 361 of file constant_sx.hpp.
 {this->count--;}
References casadi::SXNode::count.
Member Function Documentation
can_inline()
void casadi::SXNode::can_inline (std::map< const SXNode *, casadi_int > & nodeind) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_a6
Definition at line 113 of file sx_node.cpp.
{
     // Add or mark node in map
     std::map<const SXNode*, casadi_int>::iterator it=nodeind.find(this);
     if (it==nodeind.end()) {
       // First time encountered, mark inlined
       nodeind.insert(it, std::make_pair(this, 0));
       // Handle dependencies with recursion
       for (casadi_int i=0; i<n_dep(); ++i) {
         dep(i)->can_inline(nodeind);
       }
     } else if (it->second==0 && op()!=OP_PARAMETER) {
       // Node encountered before, do not inline (except if symbolic primitive)
       it->second = -1;
     }
   }
References casadi::SXNode::can_inline(), casadi::SXNode::dep(), casadi::SXNode::n_dep(), casadi::SXNode::op(), and casadi::OP_PARAMETER.
Referenced by casadi::SXNode::can_inline(), and casadi::SXNode::disp().
class_name()
std::string casadi::ConstantSX::class_name () const inline override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9y
Implements casadi::SXNode.
Definition at line 54 of file constant_sx.hpp.
 {return "ConstantSX";}
dep() [1/2]
SXElem & casadi::SXNode::dep (casadi_int i) virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_a3
Reimplemented in casadi::UnarySX, casadi::OutputSX, casadi::CallSX, and casadi::BinarySX.
Definition at line 84 of file sx_node.cpp.
{
     casadi_error("'dep' not defined for " + class_name());
   }
References casadi::SXNode::class_name().
dep() [2/2]
const SXElem & casadi::SXNode::dep (casadi_int i) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_a2
Reimplemented in casadi::UnarySX, casadi::OutputSX, casadi::CallSX, and casadi::BinarySX.
Definition at line 80 of file sx_node.cpp.
{
     casadi_error("'dep' not defined for " + class_name());
   }
References casadi::SXNode::class_name().
Referenced by casadi::SXFunction::ad_forward(), casadi::SXFunction::ad_reverse(), casadi::SXElem::binary(), casadi::SXNode::can_inline(), casadi::SXElem::dep(), casadi::LinsolCall< Tr >::eval_sx(), casadi::SXFunction::eval_sx(), casadi::SXFunction::init(), casadi::SXNode::print_compact(), and casadi::SXNode::safe_delete().
deserialize()
SXNode * casadi::SXNode::deserialize (DeserializingStream & s) static inherited
Definition at line 243 of file sx_node.cpp.
{
     casadi_int op;
     s.unpack("SXNode::op", op);
     if (casadi_math<MX>::is_binary(op)) {
       return BinarySX::deserialize(s, op);
     } else if (casadi_math<MX>::is_unary(op)) {
       return UnarySX::deserialize(s, op);
     }
     auto it = SXNode::deserialize_map.find(op);
     if (it==SXNode::deserialize_map.end()) {
       casadi_error("Not implemented op " + str(casadi_int(op)));
     } else {
       return it->second(s);
     }
   }
References casadi::BinarySX::deserialize(), casadi::UnarySX::deserialize(), casadi::SXNode::deserialize_map, casadi::SXNode::op(), casadi::str(), and casadi::DeserializingStream::unpack().
Referenced by casadi::SXElem::deserialize().
disp()
void casadi::SXNode::disp (std::ostream & stream, bool more) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_a5
Definition at line 88 of file sx_node.cpp.
{
     // Find out which noded can be inlined
     std::map<const SXNode*, casadi_int> nodeind;
     can_inline(nodeind);
     // Print expression
     std::vector<std::string> intermed;
     std::string s = print_compact(nodeind, intermed);
     // Print intermediate expressions
     for (casadi_int i=0; i<intermed.size(); ++i)
       stream << "@" << (i+1) << "=" << intermed[i] << ", ";
     // Print this
     stream << s;
   }
References casadi::SXNode::can_inline(), and casadi::SXNode::print_compact().
Referenced by casadi::SXElem::disp().
get_output()
SXElem casadi::SXNode::get_output (casadi_int oind) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_293
Reimplemented in casadi::CallSX.
Definition at line 227 of file sx_node.cpp.
{
     casadi_assert(oind==0, "Output index out of bounds");
     return shared_from_this();
   }
References casadi::SXNode::shared_from_this().
Referenced by casadi::SXElem::get_output().
has_output()
virtual bool casadi::SXNode::has_output () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::CallSX.
Definition at line 82 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::has_output().
is_almost_zero()
virtual bool casadi::SXNode::is_almost_zero (double tol) const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::ZeroSX, and casadi::RealtypeSX.
Definition at line 74 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::is_almost_zero().
is_call()
virtual bool casadi::SXNode::is_call () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::CallSX.
Definition at line 80 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::is_call().
is_constant()
bool casadi::ConstantSX::is_constant () const inline override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1jl
Reimplemented from casadi::SXNode.
Definition at line 64 of file constant_sx.hpp.
 { return true; }
is_equal()
bool casadi::ConstantSX::is_equal (const SXNode * node, casadi_int depth) const inline override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1jn
Reimplemented from casadi::SXNode.
Definition at line 74 of file constant_sx.hpp.
{
   const ConstantSX* n = dynamic_cast<const ConstantSX*>(node);
   return n && n->to_double()==to_double();
 }
References casadi::ConstantSX::to_double().
is_inf()
virtual bool casadi::SXNode::is_inf () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::InfSX.
Definition at line 78 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::is_inf().
is_integer()
bool casadi::MinusOneSX::is_integer () const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_1k7
Reimplemented from casadi::SXNode.
Definition at line 375 of file constant_sx.hpp.
 { return true; }
is_minus_inf()
virtual bool casadi::SXNode::is_minus_inf () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::MinusInfSX.
Definition at line 79 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::is_minus_inf().
is_minus_one()
bool casadi::MinusOneSX::is_minus_one () const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_1k7
Reimplemented from casadi::SXNode.
Definition at line 376 of file constant_sx.hpp.
 { return true; }
is_nan()
virtual bool casadi::SXNode::is_nan () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::NanSX.
Definition at line 77 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::is_nan().
is_one()
virtual bool casadi::SXNode::is_one () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::OneSX.
Definition at line 75 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::binary(), and casadi::SXElem::is_one().
is_op()
virtual bool casadi::SXNode::is_op (casadi_int op) const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::UnarySX, casadi::SymbolicSX, casadi::CallSX, and casadi::BinarySX.
Definition at line 73 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::is_op().
is_output()
virtual bool casadi::SXNode::is_output () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::OutputSX.
Definition at line 81 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::is_output().
is_smooth()
virtual bool casadi::SXNode::is_smooth () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_a4
Reimplemented in casadi::UnarySX, and casadi::BinarySX.
Definition at line 144 of file sx_node.hpp.
 { return true; }
is_symbolic()
virtual bool casadi::SXNode::is_symbolic () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::SymbolicSX.
Definition at line 71 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXFunction::init(), and casadi::SXElem::is_symbolic().
is_zero()
virtual bool casadi::SXNode::is_zero () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::ZeroSX.
Definition at line 72 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::binary(), and casadi::SXElem::is_zero().
mark()
void casadi::SXNode::mark () const inherited
Definition at line 109 of file sx_node.cpp.
{
     temp = -temp-1;
   }
References casadi::SXNode::temp.
marked()
bool casadi::SXNode::marked () const inherited
Definition at line 105 of file sx_node.cpp.
{
     return temp<0;
   }
References casadi::SXNode::temp.
n_dep()
virtual casadi_int casadi::SXNode::n_dep () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_a1
Reimplemented in casadi::UnarySX, casadi::OutputSX, casadi::CallSX, and casadi::BinarySX.
Definition at line 124 of file sx_node.hpp.
 { return 0;}
Referenced by casadi::SXNode::can_inline(), casadi::SXElem::n_dep(), casadi::SXNode::print_compact(), and casadi::SXNode::safe_delete().
name()
const std::string & casadi::SXNode::name () const virtual inherited
Reimplemented in casadi::SymbolicSX.
Definition at line 76 of file sx_node.cpp.
{
     casadi_error("'name' not defined for " + class_name());
   }
References casadi::SXNode::class_name().
Referenced by casadi::SXElem::name().
op()
casadi_int casadi::ConstantSX::op () const inline override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1jm
Implements casadi::SXNode.
Definition at line 69 of file constant_sx.hpp.
 { return OP_CONST;}
References casadi::OP_CONST.
print()
std::string casadi::ConstantSX::print (const std::string & arg1, const std::string & arg2) const inline override protected virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1jo
Implements casadi::SXNode.
Definition at line 84 of file constant_sx.hpp.
{
    std::stringstream ss;
    ss << to_double();
    return ss.str();
  }
References casadi::ConstantSX::to_double().
print_compact()
std::string casadi::SXNode::print_compact (std::map< const SXNode *, casadi_int > & nodeind, std::vector< std::string > & intermed) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_a7
Definition at line 130 of file sx_node.cpp.
{
     // Get reference to node index
     casadi_int& ind = nodeind[this];
     // If positive, already in intermediate expressions
     if (ind>0) {
       std::stringstream ss;
       ss << "@" << ind;
       return ss.str();
     }
     std::string s;
     if (op()==OP_CALL) {
       const Function& f = which_function();
       // Get expressions for dependencies
       s = which_function().name() + "(";
       casadi_int k = 0;
       for (casadi_int i=0; i<f.n_in(); ++i) {
         if (f.nnz_in(i)>1) s += "[";
         for (casadi_int j=0; j<f.nnz_in(i); ++j) {
           s += dep(k++)->print_compact(nodeind, intermed);
           if (j<f.nnz_in(i)-1) s+=",";
         }
         if (f.nnz_in(i)>1) s += "]";
         if (i<f.n_in()-1) s+=",";
       }
       s += ")";
     } else {
       // Get expressions for dependencies
       std::string arg[2];
       for (casadi_int i=0; i<n_dep(); ++i) {
         arg[i] = dep(i)->print_compact(nodeind, intermed);
       }
       // Get expression for this
       s = print(arg[0], arg[1]);
     }
     // Decide what to do with the expression
     if (ind==0) {
       // Inline expression
       return s;
     } else {
       // Add to list of intermediate expressions and return reference
       intermed.push_back(s);
       ind = intermed.size(); // For subsequent references
       std::stringstream ss;
       ss << "@" << ind;
       return ss.str();
     }
   }
References casadi::SXNode::dep(), casadi::SXNode::n_dep(), casadi::Function::n_in(), casadi::Function::name(), casadi::Function::nnz_in(), casadi::SXNode::op(), casadi::OP_CALL, casadi::SXNode::print(), casadi::SXNode::print_compact(), and casadi::SXNode::which_function().
Referenced by casadi::SXNode::disp(), and casadi::SXNode::print_compact().
safe_delete()
void casadi::SXNode::safe_delete (SXNode * n) static inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_a9
Definition at line 184 of file sx_node.cpp.
{
     // Quick return if more owners
     if (n->count>0) return;
     // Delete straight away if it doesn't have any dependencies
     if (!n->n_dep()) {
       delete n;
       return;
     }
     // Stack of expressions to be deleted
     std::stack<SXNode*> deletion_stack;
     // Add the node to the deletion stack
     deletion_stack.push(n);
     // Process stack
     while (!deletion_stack.empty()) {
       // Top element
       SXNode *t = deletion_stack.top();
       // Check if the top element has dependencies with dependencies
       bool added_to_stack = false;
       for (casadi_int c2=0; c2<t->n_dep(); ++c2) { // for all dependencies of the dependency
         // Get the node of the dependency of the top element
         // and remove it from the smart pointer
         SXNode *n2 = t->dep(c2).assignNoDelete(casadi_limits<SXElem>::nan);
         // Check if this is the only reference to the element
         if (n2->count == 0) {
           // Check if unary or binary
           if (!n2->n_dep()) {
             // Delete straight away if not binary
             delete n2;
           } else {
             // Add to deletion stack
             deletion_stack.push(n2);
             added_to_stack = true;
           }
         }
       }
       // Delete and pop from stack if nothing added to the stack
       if (!added_to_stack) {
         delete deletion_stack.top();
         deletion_stack.pop();
       }
     }
   }
References casadi::SXElem::assignNoDelete(), casadi::SXNode::count, casadi::SXNode::dep(), and casadi::SXNode::n_dep().
Referenced by casadi::BinarySX::~BinarySX(), and casadi::UnarySX::~UnarySX().
serialize()
void casadi::SXNode::serialize (SerializingStream & s) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_aa
Definition at line 238 of file sx_node.cpp.
{
     s.pack("SXNode::op", op());
     serialize_node(s);
   }
References casadi::SXNode::op(), casadi::SerializingStream::pack(), and casadi::SXNode::serialize_node().
serialize_node()
void casadi::MinusOneSX::serialize_node (SerializingStream & s) const inline override virtual
Reimplemented from casadi::SXNode.
Definition at line 379 of file constant_sx.hpp.
{
     s.pack("ConstantSX::type", 'm');
   }
References casadi::SerializingStream::pack().
shared_from_this() [1/2]
SXElem casadi::SXNode::shared_from_this () inherited
Definition at line 261 of file sx_node.cpp.
{
     return SXElem(this, false);
   }
References casadi::SXNode::SXElem.
Referenced by casadi::SXNode::get_output(), and casadi::CallSX::get_output().
shared_from_this() [2/2]
const SXElem casadi::SXNode::shared_from_this () const inherited
Definition at line 265 of file sx_node.cpp.
{
     return SXElem(const_cast<SXNode*>(this), false);
   }
References casadi::SXNode::SXElem.
singleton()
static MinusOneSX* casadi::MinusOneSX::singleton () inline static
Definition at line 356 of file constant_sx.hpp.
{
     static MinusOneSX instance;
     return &instance;
   }
to_double()
double casadi::MinusOneSX::to_double () const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_1k6
Implements casadi::ConstantSX.
Definition at line 367 of file constant_sx.hpp.
 { return -1;}
to_int()
casadi_int casadi::MinusOneSX::to_int () const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_1k6
Reimplemented from casadi::SXNode.
Definition at line 368 of file constant_sx.hpp.
 { return -1;}
which_function()
Function casadi::SXNode::which_function () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_291
Reimplemented in casadi::CallSX.
Definition at line 64 of file sx_node.cpp.
{
     casadi_error("'which_function' not defined for class " + class_name());
   }
References casadi::SXNode::class_name().
Referenced by casadi::SXNode::print_compact(), and casadi::SXElem::which_function().
which_output()
casadi_int casadi::SXNode::which_output () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_292
Reimplemented in casadi::OutputSX.
Definition at line 68 of file sx_node.cpp.
{
     casadi_error("'which_output' not defined for class " + class_name());
   }
References casadi::SXNode::class_name().
Referenced by casadi::SXElem::which_output().
Member Data Documentation
count
unsigned int casadi::SXNode::count inherited
Definition at line 197 of file sx_node.hpp.
Referenced by casadi::SXElem::assignNoDelete(), casadi::SXElem::operator=(), casadi::SXNode::safe_delete(), casadi::SXElem::SXElem(), casadi::SXNode::SXNode(), casadi::UniversalNodeOwner::UniversalNodeOwner(), casadi::InfSX::~InfSX(), casadi::MinusInfSX::~MinusInfSX(), ~MinusOneSX(), casadi::NanSX::~NanSX(), casadi::OneSX::~OneSX(), casadi::SXElem::~SXElem(), casadi::SXNode::~SXNode(), and casadi::ZeroSX::~ZeroSX().
deserialize_map
std::map< casadi_int, SXNode *(*)(DeserializingStream &)> casadi::SXNode::deserialize_map static inherited
Initial value:
= {
    {OP_PARAMETER, SymbolicSX::deserialize},
    {OP_CONST, ConstantSX_deserialize},
    {OP_CALL, CallSX::deserialize},
    {-1, OutputSX::deserialize}}
Definition at line 209 of file sx_node.hpp.
Referenced by casadi::SXNode::deserialize().
eq_depth_
casadi_int casadi::SXNode::eq_depth_ = 1 static inherited
Definition at line 179 of file sx_node.hpp.
Referenced by casadi::SXElem::binary(), casadi::Matrix< Scalar >::get_max_depth(), casadi::SXElem::is_doubled(), and casadi::Matrix< Scalar >::set_max_depth().
temp
int casadi::SXNode::temp mutable inherited
Temporary variables to be used in user algorithms like sorting, the user is responsible of making sure that use is thread-safe The variable is initialized to zero
Definition at line 191 of file sx_node.hpp.
Referenced by casadi::SXFunction::init(), casadi::SXNode::mark(), casadi::SXNode::marked(), and casadi::SXNode::SXNode().
The documentation for this class was generated from the following file:
constant_sx.hpp