CasADi: casadi::CodeGenerator Class Reference
casadi::CodeGenerator Class Reference
Helper class for C code generation.
#include <code_generator.hpp>
Detailed Description
Author
Joel Andersson
Date
2016
Extra doc: https://github.com/casadi/casadi/wiki/L_ru
Definition at line 43 of file code_generator.hpp.
Classes
struct FunctionMeta
Public Types
enum Auxiliary {
AUX_COPY , AUX_CVX , AUX_CONVEXIFY , AUX_SWAP ,
AUX_SCAL , AUX_AXPY , AUX_DOT , AUX_BILIN ,
AUX_RANK1 , AUX_NORM_1 , AUX_NORM_2 , AUX_CLIP_MAX ,
AUX_CLIP_MIN , AUX_VECTOR_FMAX , AUX_VECTOR_FMIN , AUX_NORM_INF ,
AUX_MASKED_NORM_INF , AUX_IAMAX , AUX_CLEAR , AUX_FILL ,
AUX_MV , AUX_MV_DENSE , AUX_MTIMES , AUX_TRILSOLVE ,
AUX_TRIUSOLVE , AUX_PROJECT , AUX_TRI_PROJECT , AUX_DENSIFY ,
AUX_SPARSIFY , AUX_TRANS , AUX_TO_MEX , AUX_FROM_MEX ,
AUX_INTERPN , AUX_INTERPN_GRAD , AUX_FLIP , AUX_INTERPN_WEIGHTS ,
AUX_LOW , AUX_INTERPN_INTERPOLATE , AUX_DE_BOOR , AUX_ND_BOOR_EVAL ,
AUX_FINITE_DIFF , AUX_QR , AUX_QP , AUX_QRQP ,
AUX_NLP , AUX_SQPMETHOD , AUX_FEASIBLESQPMETHOD , AUX_LDL ,
AUX_NEWTON , AUX_TO_DOUBLE , AUX_TO_INT , AUX_CAST ,
AUX_SQ , AUX_SIGN , AUX_IF_ELSE , AUX_PRINTF ,
AUX_FMIN , AUX_FMAX , AUX_FABS , AUX_MIN ,
AUX_MAX , AUX_VFMIN , AUX_VFMAX , AUX_MAX_VIOL ,
AUX_SUM_VIOL , AUX_SUM , AUX_REGULARIZE , AUX_INF ,
AUX_NAN , AUX_REAL_MIN , AUX_ISINF , AUX_BOUNDS_CONSISTENCY ,
AUX_LSQR , AUX_FILE_SLURP , AUX_CACHE , AUX_LOG1P ,
AUX_EXPM1 , AUX_HYPOT , AUX_MMIN , AUX_MMAX ,
AUX_LOGSUMEXP , AUX_SPARSITY , AUX_BFGS , AUX_ORACLE_CALLBACK ,
AUX_OCP_BLOCK , AUX_ORACLE , AUX_SCALED_COPY
}
Auxiliary functions.
Public Member Functions
CodeGenerator (const std::string &name, const Dict &opts=Dict())
Constructor.
void add (const Function &f, bool with_jac_sparsity=false)
Add a function (name generated)
void dump (std::ostream &s)
Generate the code to a stream.
std::string dump ()
Generate a file, return code as string.
std::string generate (const std::string &prefix="")
Generate file(s)
void add_include (const std::string &new_include, bool relative_path=false, const std::string &use_ifdef=std::string())
Add an include file optionally using a relative path "..." instead of an absolute path <...>
std::string add_dependency (const Function &f)
Add a function dependency.
void add_external (const std::string &new_external)
Add an external function declaration.
std::string shorthand (const std::string &name) const
Get a shorthand.
std::string shorthand (const std::string &name, bool allow_adding=true)
Add/get a shorthand.
std::string sparsity (const Sparsity &sp)
casadi_int add_sparsity (const Sparsity &sp)
casadi_int get_sparsity (const Sparsity &sp) const
Get the index of an existing sparsity pattern.
casadi_int get_constant (const std::vector< double > &v, bool allow_adding=false)
Get or add a constant.
casadi_int get_constant (const std::vector< casadi_int > &v, bool allow_adding=false)
Get or add an integer constant.
casadi_int get_constant (const std::vector< char > &v, bool allow_adding=false)
Get or add a char constant.
casadi_int get_constant (const std::vector< std::string > &v, bool allow_adding=false)
Get or add a vector<string> constant.
std::string constant (const std::vector< casadi_int > &v)
Represent an array constant; adding it when new.
std::string constant (const std::vector< int > &v)
Represent an array constant; adding it when new.
void constant_copy (const std::string &var_name, const std::vector< casadi_int > &v, const std::string &type="casadi_int")
Represent an array constant; adding it when new.
std::string constant (const std::vector< double > &v)
Represent an array constant; adding it when new.
std::string constant (const std::vector< char > &v)
Represent an array constant; adding it when new.
std::string constant (const std::vector< std::string > &v)
Represent an array constant; adding it when new.
void define_rom_double (const void *id, casadi_int size)
Allocate file scope double read-only memory.
std::string rom_double (const void *id) const
Access file scope double read-only memory.
void define_rom_integer (const void *id, casadi_int size)
Allocate file scope integer read-only memory.
void setup_callback (const std::string &s, const Function &f)
Setup a callback.
std::string rom_integer (const void *id) const
Access file scope integer read-only memory.
std::string operator() (const Function &f, const std::string &arg, const std::string &res, const std::string &iw, const std::string &w, const std::string &failure_ret="1")
Generate a call to a function (generic signature)
CodeGenerator & operator<< (const std::string &s)
Print a string to buffer.
void print_formatted (const std::string &s)
Print without newline characters.
template<typename T >
CodeGenerator & operator<< (T s)
Print an arbitrary type to buffer.
void flush (std::ostream &s)
Flush the buffer to a stream of choice.
void local (const std::string &name, const std::string &type, const std::string &ref="")
Declare a local variable.
void scope_enter ()
Enter a local scope.
void scope_exit ()
Exit a local scope.
std::string sx_work (casadi_int i)
Declare a work vector element.
void init_local (const std::string &name, const std::string &def)
Specify the default value for a local variable.
void indent ()
Increase indentation.
void unindent ()
Decrease indentation.
bool avoid_stack ()
Avoid stack?
std::string constant (double v)
Print a constant in a lossless but compact manner.
std::string constant (casadi_int v)
std::string constant (const std::string &v)
std::string initializer (const std::vector< double > &v)
Print an intializer.
std::string initializer (const std::vector< casadi_int > &v)
std::string initializer (const std::vector< char > &v)
std::string initializer (const std::vector< std::string > &v)
std::string sanitize_source (const std::string &src, const std::vector< std::string > &inst, bool add_shorthand=true)
Sanitize source files for codegen.
std::string dot (casadi_int n, const std::string &x, const std::string &y)
Codegen inner product.
std::string mv (const std::string &x, const Sparsity &sp_x, const std::string &y, const std::string &z, bool tr)
Codegen sparse matrix-vector multiplication.
std::string mv (const std::string &x, casadi_int nrow_x, casadi_int ncol_x, const std::string &y, const std::string &z, bool tr)
Codegen dense matrix-vector multiplication.
std::string axpy (casadi_int n, const std::string &a, const std::string &x, const std::string &y)
Codegen axpy: y += a*x.
std::string clip_min (const std::string &x, casadi_int n, const std::string &min, const std::string &mask)
Codegen clip_min: Clips the smaller entries in a vector than min to the min.
std::string clip_max (const std::string &x, casadi_int n, const std::string &min, const std::string &mask)
Codegen clip_max: Clips the larger entries in a vector than max to the max.
std::string vector_fmax (casadi_int n, const std::string &x, const std::string &y, const std::string &z)
Codegen vector_fmax: Takes vectorwise max of a vector and writes the result to second vector.
std::string vector_fmin (casadi_int n, const std::string &x, const std::string &y, const std::string &z)
Codegen vector_fmin: Takes vectorwise min of a vector and writes the result to second vector.
std::string masked_norm_inf (casadi_int n, const std::string &x, const std::string &mask)
codegen masked_norm_inf: The mask tells what entry is used in the inf-norm.
std::string scal (casadi_int n, const std::string &alpha, const std::string &x)
What does scal do??
std::string mtimes (const std::string &x, const Sparsity &sp_x, const std::string &y, const Sparsity &sp_y, const std::string &z, const Sparsity &sp_z, const std::string &w, bool tr)
Codegen sparse matrix-matrix multiplication.
std::string trilsolve (const Sparsity &sp_x, const std::string &x, const std::string &y, bool tr, bool unity, casadi_int nrhs)
Codegen lower triangular solve.
std::string triusolve (const Sparsity &sp_x, const std::string &x, const std::string &y, bool tr, bool unity, casadi_int nrhs)
Codegen upper triangular solve.
std::string bilin (const std::string &A, const Sparsity &sp_A, const std::string &x, const std::string &y)
Codegen bilinear form.
std::string rank1 (const std::string &A, const Sparsity &sp_A, const std::string &alpha, const std::string &x, const std::string &y)
Rank-1 update.
std::string logsumexp (const std::string &A, casadi_int n)
std::string interpn (const std::string &res, casadi_int ndim, const std::string &grid, const std::string &offset, const std::string &values, const std::string &x, const std::string &lookup_mode, casadi_int m, const std::string &iw, const std::string &w)
Multilinear interpolation.
std::string interpn_grad (const std::string &grad, casadi_int ndim, const std::string &grid, const std::string &offset, const std::string &values, const std::string &x, const std::string &lookup_mode, casadi_int m, const std::string &iw, const std::string &w)
Multilinear interpolation - calculate gradient.
std::string trans (const std::string &x, const Sparsity &sp_x, const std::string &y, const Sparsity &sp_y, const std::string &iw)
Transpose.
std::string qr (const std::string &sp, const std::string &A, const std::string &w, const std::string &sp_v, const std::string &v, const std::string &sp_r, const std::string &r, const std::string &beta, const std::string &prinv, const std::string &pc)
QR factorization.
std::string qr_solve (const std::string &x, casadi_int nrhs, bool tr, const std::string &sp_v, const std::string &v, const std::string &sp_r, const std::string &r, const std::string &beta, const std::string &prinv, const std::string &pc, const std::string &w)
QR solve.
std::string lsqr_solve (const std::string &A, const std::string &x, casadi_int nrhs, bool tr, const std::string &sp, const std::string &w)
std::string ldl (const std::string &sp_a, const std::string &a, const std::string &sp_lt, const std::string &lt, const std::string &d, const std::string &p, const std::string &w)
LDL factorization.
std::string ldl_solve (const std::string &x, casadi_int nrhs, const std::string &sp_lt, const std::string &lt, const std::string &d, const std::string &p, const std::string &w)
LDL solve.
std::string fmax (const std::string &x, const std::string &y)
fmax
std::string fmin (const std::string &x, const std::string &y)
fmin
std::string mmax (const std::string &x, casadi_int n, bool is_dense)
mmax
std::string mmin (const std::string &x, casadi_int n, bool is_dense)
mmin
std::string vfmax (const std::string &x, casadi_int n, const std::string &y)
vfmax
std::string vfmin (const std::string &x, casadi_int n, const std::string &y)
vfmin
std::string vfmax (const std::string &x, const std::string &n, const std::string &y)
vfmax
std::string vfmin (const std::string &x, const std::string &n, const std::string &y)
vfmin
std::string max (const std::string &x, const std::string &y)
max
std::string min (const std::string &x, const std::string &y)
min
std::string norm_inf (casadi_int n, const std::string &x)
norm_inf
std::string norm_2 (casadi_int n, const std::string &x)
norm_2
std::string max_viol (casadi_int n, const std::string &x, const std::string &lb, const std::string &ub)
max_viol
std::string sum_viol (casadi_int n, const std::string &x, const std::string &lb, const std::string &ub)
sum_viol
std::string bound_consistency (casadi_int n, const std::string &x, const std::string &lam, const std::string &lbx, const std::string &ubx)
bound_consistency
std::string lb_eig (const Sparsity &sp_h, const std::string &h)
lb_eig
std::string regularize (const Sparsity &sp_h, const std::string &h, const std::string &reg)
regularize
std::string convexify_eval (const ConvexifyData &d, const std::string &Hin, const std::string &Hout, const std::string &iw, const std::string &w)
convexify
std::string low (const std::string &x, const std::string &grid, casadi_int ng, casadi_int lookup_mode)
low
std::string declare (std::string s)
Declare a function.
void comment (const std::string &s)
Write a comment line (ignored if not verbose)
void add_auxiliary (Auxiliary f, const std::vector< std::string > &inst={"casadi_real"})
Add a built-in auxiliary function.
void add_io_sparsities (const std::string &name, const std::vector< Sparsity > &sp_in, const std::vector< Sparsity > &sp_out)
Add io sparsity patterns of a function.
std::string work (casadi_int n, casadi_int sz) const
std::string workel (casadi_int n) const
void print_vector (std::ostream &s, const std::string &name, const std::vector< casadi_int > &v)
Print casadi_int vector to a c file.
void print_vector (std::ostream &s, const std::string &name, const std::vector< char > &v)
Print char vector to a c file.
void print_vector (std::ostream &s, const std::string &name, const std::vector< double > &v)
Print real vector to a c file.
void print_vector (std::ostream &s, const std::string &name, const std::vector< std::string > &v)
Print string vector to a c file.
std::string copy (const std::string &arg, std::size_t n, const std::string &res)
Create a copy operation.
void copy_check (const std::string &arg, std::size_t n, const std::string &res, bool check_lhs=true, bool check_rhs=true)
void copy_default (const std::string &arg, std::size_t n, const std::string &res, const std::string &def, bool check_rhs=true)
std::string fill (const std::string &res, std::size_t n, const std::string &v)
Create a fill operation.
std::string clear (const std::string &res, std::size_t n)
Create a fill operation.
std::string arg (casadi_int i) const
Refer to argument.
std::string res (casadi_int i) const
Refer to resuly.
std::string mem (const Function &f)
Access thread-local memory.
std::string project (const std::string &arg, const Sparsity &sp_arg, const std::string &res, const Sparsity &sp_res, const std::string &w)
Sparse assignment.
std::string tri_project (const std::string &arg, const Sparsity &sp_arg, const std::string &res, bool lower)
Project triangular part.
std::string densify (const std::string &arg, const Sparsity &sp_arg, const std::string &res, bool tr=false)
Densify.
std::string sparsify (const std::string &arg, const std::string &res, const Sparsity &sp_res, bool tr=false)
Sparsify.
std::string to_mex (const Sparsity &sp, const std::string &arg)
Create matrix in MATLAB's MEX format.
std::string from_mex (std::string &arg, const std::string &res, std::size_t res_off, const Sparsity &sp_res, const std::string &w)
Get matrix from MATLAB's MEX format.
std::string printf (const std::string &str, const std::vector< std::string > &arg=std::vector< std::string >())
Printf.
std::string printf (const std::string &str, const std::string &arg1)
std::string printf (const std::string &str, const std::string &arg1, const std::string &arg2)
std::string printf (const std::string &str, const std::string &arg1, const std::string &arg2, const std::string &arg3)
std::string print_op (casadi_int op, const std::string &a0)
Print an operation to a c file.
std::string print_op (casadi_int op, const std::string &a0, const std::string &a1)
std::string file_slurp (const std::string &fname, casadi_int n, const std::string &a)
Slurp a file.
std::string cache_check (const std::string &key, const std::string &cache, const std::string &loc, casadi_int stride, casadi_int sz, casadi_int key_sz, const std::string &val)
cache check
void sz_work (size_t &sz_arg, size_t &sz_res, size_t &sz_iw, size_t &sz_w) const
Get number of temporary variables needed for all functions.
std::string wrapper (const Function &base, const std::string &name)
Static Public Member Functions
static std::string array (const std::string &type, const std::string &name, casadi_int len, const std::string &def=std::string())
static std::string fmu_helpers (const std::string &modelname)
FMU helper functions.
static std::string casadi_version ()
Current CasADi version as string.
static void file_open (std::ofstream &f, const std::string &name, bool cpp)
Print file header.
static void file_close (std::ofstream &f, bool cpp)
Print file header.
static size_t hash (const std::vector< double > &v)
static size_t hash (const std::vector< casadi_int > &v)
static size_t hash (const std::vector< char > &v)
static size_t hash (const std::vector< std::string > &v)
template<typename T >
static bool equal (const std::vector< T > &v1, const std::vector< T > &v2)
Public Attributes
std::string name
std::string suffix
std::string casadi_real_type
std::string casadi_int_type
bool with_mem
bool with_header
bool mex
bool with_sfunction
std::vector< std::string > added_sfunctions
bool unroll_args
bool verbose
bool verbose_runtime
bool cpp
bool main
bool include_math
bool avoid_stack_
std::string infinity
std::string nan
std::string real_min
bool codegen_scalars
Codegen scalar.
bool with_export
bool with_import
std::string dll_export
std::string dll_import
std::string prefix
std::stringstream includes
std::stringstream auxiliaries
std::stringstream body
std::stringstream header
std::stringstream buffer
bool newline_
casadi_int indent_
casadi_int current_indent_
std::vector< std::string > exposed_fname
std::set< std::string > sparsity_meta
std::set< std::string > added_includes_
std::set< std::string > added_externals_
std::set< std::string > added_shorthands_
std::multimap< Auxiliary, std::vector< std::string > > added_auxiliaries_
std::multimap< size_t, size_t > added_double_constants_
std::multimap< size_t, size_t > added_integer_constants_
std::multimap< size_t, size_t > added_char_constants_
std::multimap< size_t, size_t > added_string_constants_
std::map< std::string, std::pair< std::string, std::string > > local_variables_
std::map< std::string, std::string > local_default_
std::map< const void *, casadi_int > file_scope_double_
std::map< const void *, casadi_int > file_scope_integer_
std::vector< FunctionMeta > added_functions_
std::map< std::string, std::map< FunctionInternal *, casadi_int > > added_wrappers_
std::vector< std::vector< double > > double_constants_
std::vector< std::vector< casadi_int > > integer_constants_
std::vector< std::vector< char > > char_constants_
std::vector< std::vector< std::string > > string_constants_
bool needs_mem_
Member Enumeration Documentation
Auxiliary
enum casadi::CodeGenerator::Auxiliary
Extra doc: https://github.com/casadi/casadi/wiki/L_to
Enumerator
AUX_COPY
AUX_CVX
AUX_CONVEXIFY
AUX_SWAP
AUX_SCAL
AUX_AXPY
AUX_DOT
AUX_BILIN
AUX_RANK1
AUX_NORM_1
AUX_NORM_2
AUX_CLIP_MAX
AUX_CLIP_MIN
AUX_VECTOR_FMAX
AUX_VECTOR_FMIN
AUX_NORM_INF
AUX_MASKED_NORM_INF
AUX_IAMAX
AUX_CLEAR
AUX_FILL
AUX_MV
AUX_MV_DENSE
AUX_MTIMES
AUX_TRILSOLVE
AUX_TRIUSOLVE
AUX_PROJECT
AUX_TRI_PROJECT
AUX_DENSIFY
AUX_SPARSIFY
AUX_TRANS
AUX_TO_MEX
AUX_FROM_MEX
AUX_INTERPN
AUX_INTERPN_GRAD
AUX_FLIP
AUX_INTERPN_WEIGHTS
AUX_LOW
AUX_INTERPN_INTERPOLATE
AUX_DE_BOOR
AUX_ND_BOOR_EVAL
AUX_FINITE_DIFF
AUX_QR
AUX_QP
AUX_QRQP
AUX_NLP
AUX_SQPMETHOD
AUX_FEASIBLESQPMETHOD
AUX_LDL
AUX_NEWTON
AUX_TO_DOUBLE
AUX_TO_INT
AUX_CAST
AUX_SQ
AUX_SIGN
AUX_IF_ELSE
AUX_PRINTF
AUX_FMIN
AUX_FMAX
AUX_FABS
AUX_MIN
AUX_MAX
AUX_VFMIN
AUX_VFMAX
AUX_MAX_VIOL
AUX_SUM_VIOL
AUX_SUM
AUX_REGULARIZE
AUX_INF
AUX_NAN
AUX_REAL_MIN
AUX_ISINF
AUX_BOUNDS_CONSISTENCY
AUX_LSQR
AUX_FILE_SLURP
AUX_CACHE
AUX_LOG1P
AUX_EXPM1
AUX_HYPOT
AUX_MMIN
AUX_MMAX
AUX_LOGSUMEXP
AUX_SPARSITY
AUX_BFGS
AUX_ORACLE_CALLBACK
AUX_OCP_BLOCK
AUX_ORACLE
AUX_SCALED_COPY
Definition at line 550 of file code_generator.hpp.
                    {
       AUX_COPY,
       AUX_CVX,
       AUX_CONVEXIFY,
       AUX_SWAP,
       AUX_SCAL,
       AUX_AXPY,
       AUX_DOT,
       AUX_BILIN,
       AUX_RANK1,
       AUX_NORM_1,
       AUX_NORM_2,
       AUX_CLIP_MAX,
       AUX_CLIP_MIN,
       AUX_VECTOR_FMAX,
       AUX_VECTOR_FMIN,
       AUX_NORM_INF,
       AUX_MASKED_NORM_INF,
       AUX_IAMAX,
       AUX_CLEAR,
       AUX_FILL,
       AUX_MV,
       AUX_MV_DENSE,
       AUX_MTIMES,
       AUX_TRILSOLVE,
       AUX_TRIUSOLVE,
       AUX_PROJECT,
       AUX_TRI_PROJECT,
       AUX_DENSIFY,
       AUX_SPARSIFY,
       AUX_TRANS,
       AUX_TO_MEX,
       AUX_FROM_MEX,
       AUX_INTERPN,
       AUX_INTERPN_GRAD,
       AUX_FLIP,
       AUX_INTERPN_WEIGHTS,
       AUX_LOW,
       AUX_INTERPN_INTERPOLATE,
       AUX_DE_BOOR,
       AUX_ND_BOOR_EVAL,
       AUX_FINITE_DIFF,
       AUX_QR,
       AUX_QP,
       AUX_QRQP,
       AUX_NLP,
       AUX_SQPMETHOD,
       AUX_FEASIBLESQPMETHOD,
       AUX_LDL,
       AUX_NEWTON,
       AUX_TO_DOUBLE,
       AUX_TO_INT,
       AUX_CAST,
       AUX_SQ,
       AUX_SIGN,
       AUX_IF_ELSE,
       AUX_PRINTF,
       AUX_FMIN,
       AUX_FMAX,
       AUX_FABS,
       AUX_MIN,
       AUX_MAX,
       AUX_VFMIN,
       AUX_VFMAX,
       AUX_MAX_VIOL,
       AUX_SUM_VIOL,
       AUX_SUM,
       AUX_REGULARIZE,
       AUX_INF,
       AUX_NAN,
       AUX_REAL_MIN,
       AUX_ISINF,
       AUX_BOUNDS_CONSISTENCY,
       AUX_LSQR,
       AUX_FILE_SLURP,
       AUX_CACHE,
       AUX_LOG1P,
       AUX_EXPM1,
       AUX_HYPOT,
       AUX_MMIN,
       AUX_MMAX,
       AUX_LOGSUMEXP,
       AUX_SPARSITY,
       AUX_BFGS,
       AUX_ORACLE_CALLBACK,
       AUX_OCP_BLOCK,
       AUX_ORACLE,
       AUX_SCALED_COPY
     };
Constructor & Destructor Documentation
CodeGenerator()
casadi::CodeGenerator::CodeGenerator (const std::string & name, const Dict & opts = Dict())
Definition at line 35 of file code_generator.cpp.
{
     // Default options
     this->verbose = true;
     this->verbose_runtime = false;
     this->mex = false;
     this->with_sfunction = false;
     this->unroll_args = false;
     this->cpp = false;
     this->main = false;
     this->casadi_real_type = "double";
     this->casadi_int_type = CASADI_INT_TYPE_STR;
     this->codegen_scalars = false;
     this->with_header = false;
     this->with_mem = false;
     this->with_export = true;
     this->with_import = false;
     this->include_math = true;
     this->infinity = "INFINITY";
     this->nan = "NAN";
     this->real_min = "";
     bool prefix_set = false;
     this->prefix = "";
     avoid_stack_ = false;
     indent_ = 2;
     // Read options
     for (auto&& e : opts) {
       if (e.first=="verbose") {
         this->verbose = e.second;
       } else if (e.first=="verbose_runtime") {
         this->verbose_runtime = e.second;
       } else if (e.first=="mex") {
         this->mex = e.second;
       } else if (e.first=="with_sfunction") {
         this->with_sfunction = e.second;
       } else if (e.first=="unroll_args") {
         this->unroll_args = e.second;
       } else if (e.first=="cpp") {
         this->cpp = e.second;
       } else if (e.first=="main") {
         this->main = e.second;
       } else if (e.first=="casadi_real") {
         this->casadi_real_type = e.second.to_string();
       } else if (e.first=="casadi_int") {
         this->casadi_int_type = e.second.to_string();
       } else if (e.first=="codegen_scalars") {
         this->codegen_scalars = e.second;
       } else if (e.first=="with_header") {
         this->with_header = e.second;
       } else if (e.first=="with_mem") {
         this->with_mem = e.second;
       } else if (e.first=="with_export") {
         this->with_export = e.second;
       } else if (e.first=="with_import") {
         this->with_import = e.second;
       } else if (e.first=="include_math") {
         this->include_math = e.second;
       } else if (e.first=="infinity") {
         this->infinity = e.second.to_string();
       } else if (e.first=="nan") {
         this->nan = e.second.to_string();
       } else if (e.first=="real_min") {
         this->real_min = e.second.to_string();
       } else if (e.first=="indent") {
         indent_ = e.second;
         casadi_assert_dev(indent_>=0);
       } else if (e.first=="avoid_stack") {
         avoid_stack_ = e.second;
       } else if (e.first=="prefix") {
         this->prefix = e.second.to_string();
         prefix_set = true;
       } else {
         casadi_error("Unrecognized option: " + str(e.first));
       }
     }
     // If real_min is not specified, make an educated guess
     if (this->real_min.empty()) {
       std::stringstream ss;
       ss << std::scientific << std::setprecision(std::numeric_limits<double>::digits10 + 1);
       if (casadi_real_type=="float") {
         ss << std::numeric_limits<float>::min();
         this->real_min = ss.str();
       } else if (casadi_real_type=="double") {
         ss << std::numeric_limits<double>::min();
         this->real_min = ss.str();
       } else {
         this->real_min = "<NOT SPECIFIED>";
       }
     }
     // Start at new line with no indentation
     newline_ = true;
     current_indent_ = 0;
     // Start off without the need for thread-local memory
     needs_mem_ = false;
     // Divide name into base and suffix (if any)
     std::string::size_type dotpos = name.rfind('.');
     if (dotpos==std::string::npos) {
       this->name = name;
       this->suffix = this->cpp ? ".cpp" : ".c";
     } else {
       this->name = name.substr(0, dotpos);
       this->suffix = name.substr(dotpos);
     }
     // Symbol prefix
     if (this->with_export) dll_export = "CASADI_SYMBOL_EXPORT ";
     if (this->with_import) dll_import = "CASADI_SYMBOL_IMPORT ";
     // Make sure that the base name is sane
     casadi_assert_dev(Function::check_name(this->name));
     // Includes needed
     if (this->include_math) add_include("math.h");
     if (this->main) add_include("stdio.h");
     if (this->verbose_runtime) add_auxiliary(AUX_PRINTF);
     // Mex and main need string.h
     if (this->mex || this->main) {
       add_include("string.h");
     }
     // Mex
     if (this->mex) {
       add_include("mex.h", false, "MATLAB_MEX_FILE");
     }
     // s-Function
     if (this->with_sfunction) {
       this->casadi_real_type = "real_T";
       this->casadi_int_type = "int_T";
       this->with_header = true;
       add_include("simstruc.h");
     }
     // Memory struct entry point
     if (this->with_mem) {
       this->header << "#include <casadi/mem.h>\n";
     }
     // Use name as default prefix
     if (!prefix_set) {
       this->prefix = this->name;
     }
   }
References add_auxiliary(), add_include(), AUX_PRINTF, avoid_stack_, casadi_int_type, casadi_real_type, casadi::Function::check_name(), codegen_scalars, cpp, current_indent_, dll_export, dll_import, header, include_math, indent_, infinity, main, mex, name, nan, needs_mem_, newline_, prefix, real_min, casadi::str(), suffix, unroll_args, verbose, verbose_runtime, with_export, with_header, with_import, with_mem, and with_sfunction.
Member Function Documentation
add()
void casadi::CodeGenerator::add (const Function & f, bool with_jac_sparsity = false)
Definition at line 304 of file code_generator.cpp.
{
     // Add if not already added
     std::string codegen_name = add_dependency(f);
     // Define function
     *this << declare(f->signature(f.name())) << "{\n"
           << "return " << codegen_name <<  "(arg, res, iw, w, mem);\n"
           << "}\n\n";
     if (this->unroll_args) {
       // Define function
       *this << declare(f->signature_unrolled(f.name())) << "{\n";
       for (casadi_int i=0; i<f.n_in(); ++i) {
         *this << "arg[" << i << "] = " << f.name_in(i) << ";\n";
       }
       for (casadi_int i=0; i<f.n_out(); ++i) {
         *this << "res[" << i << "] = " << f.name_out(i) << ";\n";
       }
       *this << "return " << codegen_name <<  "(arg, res, iw, w, mem);\n";
       *this << "}\n\n";
       // Flush buffers
       flush(this->body);
     }
     // Generate meta information
     f->codegen_meta(*this);
     // Generate Jacobian sparsity information
     if (with_jac_sparsity) {
       // Generate/get Jacobian sparsity
       std::vector<Sparsity> jac = f.jac_sparsity();
       // Code generate the sparsity pattern
       add_io_sparsities("jac_" + f.name(), f->sparsity_in_, jac);
       // Flush buffers
       flush(this->body);
     }
     // Generate function specific code for Simulink sfunction
     if (this->with_sfunction) this->added_sfunctions.push_back( this->codegen_sfunction(f) );
     // Add to list of exposed symbols
     this->exposed_fname.push_back(f.name());
   }
References add_dependency(), add_io_sparsities(), added_sfunctions, body, casadi::FunctionInternal::codegen_meta(), declare(), exposed_fname, flush(), casadi::Function::jac_sparsity(), casadi::Function::n_in(), casadi::Function::n_out(), casadi::Function::name(), casadi::Function::name_in(), casadi::Function::name_out(), casadi::FunctionInternal::signature(), casadi::FunctionInternal::signature_unrolled(), casadi::FunctionInternal::sparsity_in_, unroll_args, and with_sfunction.
Referenced by casadi::DaeBuilderInternal::export_fmu(), casadi::FunctionInternal::finalize(), casadi::Function::generate(), casadi::OracleFunction::generate_dependencies(), and casadi::Scpgen::init().
add_auxiliary()
void casadi::CodeGenerator::add_auxiliary (Auxiliary f, const std::vector< std::string > & inst = {"casadi_real"})
Extra doc: https://github.com/casadi/casadi/wiki/L_tp
Definition at line 1244 of file code_generator.cpp.
{
     // Look for existing instantiations
     auto f_match = added_auxiliaries_.equal_range(f);
     // Look for duplicates
     for (auto it=f_match.first; it!=f_match.second; ++it) {
       if (it->second==inst) return;
     }
     added_auxiliaries_.insert(std::make_pair(f, inst));
     // Add the appropriate function
     switch (f) {
     case AUX_COPY:
       this->auxiliaries << sanitize_source(casadi_copy_str, inst);
       break;
     case AUX_SCALED_COPY:
       this->auxiliaries << sanitize_source(casadi_scaled_copy_str, inst);
       break;
     case AUX_SWAP:
       this->auxiliaries << sanitize_source(casadi_swap_str, inst);
       break;
     case AUX_SCAL:
       this->auxiliaries << sanitize_source(casadi_scal_str, inst);
       break;
     case AUX_AXPY:
       this->auxiliaries << sanitize_source(casadi_axpy_str, inst);
       break;
     case AUX_DOT:
       this->auxiliaries << sanitize_source(casadi_dot_str, inst);
       break;
     case AUX_BILIN:
       this->auxiliaries << sanitize_source(casadi_bilin_str, inst);
       break;
     case AUX_RANK1:
       this->auxiliaries << sanitize_source(casadi_rank1_str, inst);
       break;
     case AUX_IAMAX:
       this->auxiliaries << sanitize_source(casadi_iamax_str, inst);
       break;
     case AUX_INTERPN:
       add_auxiliary(AUX_INTERPN_WEIGHTS);
       add_auxiliary(AUX_INTERPN_INTERPOLATE);
       add_auxiliary(AUX_FLIP, {});
       add_auxiliary(AUX_CLEAR);
       add_auxiliary(AUX_CLEAR, {"casadi_int"});
       this->auxiliaries << sanitize_source(casadi_interpn_str, inst);
       break;
     case AUX_INTERPN_GRAD:
       add_auxiliary(AUX_INTERPN);
       this->auxiliaries << sanitize_source(casadi_interpn_grad_str, inst);
       break;
     case AUX_DE_BOOR:
       this->auxiliaries << sanitize_source(casadi_de_boor_str, inst);
       break;
     case AUX_ND_BOOR_EVAL:
       add_auxiliary(AUX_DE_BOOR);
       add_auxiliary(AUX_FILL);
       add_auxiliary(AUX_FILL, {"casadi_int"});
       add_auxiliary(AUX_CLEAR);
       add_auxiliary(AUX_CLEAR, {"casadi_int"});
       add_auxiliary(AUX_LOW);
       this->auxiliaries << sanitize_source(casadi_nd_boor_eval_str, inst);
       break;
     case AUX_FLIP:
       this->auxiliaries << sanitize_source(casadi_flip_str, inst);
       break;
     case AUX_LOW:
       this->auxiliaries << sanitize_source(casadi_low_str, inst);
       break;
     case AUX_INTERPN_WEIGHTS:
       add_auxiliary(AUX_LOW);
       this->auxiliaries << sanitize_source(casadi_interpn_weights_str, inst);
       break;
     case AUX_INTERPN_INTERPOLATE:
       this->auxiliaries << sanitize_source(casadi_interpn_interpolate_str, inst);
       break;
     case AUX_NORM_1:
       this->auxiliaries << sanitize_source(casadi_norm_1_str, inst);
       break;
     case AUX_NORM_2:
       add_auxiliary(AUX_DOT);
       this->auxiliaries << sanitize_source(casadi_norm_2_str, inst);
       break;
     case AUX_NORM_INF:
       add_auxiliary(AUX_FMAX);
       this->auxiliaries << sanitize_source(casadi_norm_inf_str, inst);
       break;
     case AUX_VECTOR_FMAX:
       add_auxiliary(AUX_FMAX);
       this->auxiliaries << sanitize_source(casadi_vector_fmax_str, inst);
       break;
     case AUX_VECTOR_FMIN:
       add_auxiliary(AUX_FMIN);
       this->auxiliaries << sanitize_source(casadi_vector_fmin_str, inst);
       break;
     case AUX_MASKED_NORM_INF:
       add_auxiliary(AUX_FMAX);
       this->auxiliaries << sanitize_source(casadi_masked_norm_inf_str, inst);
       break;
     case AUX_CLIP_MIN:
       // add_auxiliary(AUX_CLIP_MIN);
       this->auxiliaries << sanitize_source(casadi_clip_min_str, inst);
       break;
     case AUX_CLIP_MAX:
       // add_auxiliary(AUX_CLIP_MAX);
       this->auxiliaries << sanitize_source(casadi_clip_max_str, inst);
       break;
     case AUX_CLEAR:
       this->auxiliaries << sanitize_source(casadi_clear_str, inst);
       break;
     case AUX_FILL:
       this->auxiliaries << sanitize_source(casadi_fill_str, inst);
       break;
     case AUX_MV:
       this->auxiliaries << sanitize_source(casadi_mv_str, inst);
       break;
     case AUX_MV_DENSE:
       this->auxiliaries << sanitize_source(casadi_mv_dense_str, inst);
       break;
     case AUX_MTIMES:
       this->auxiliaries << sanitize_source(casadi_mtimes_str, inst);
       break;
     case AUX_TRILSOLVE:
       this->auxiliaries << sanitize_source(casadi_trilsolve_str, inst);
       break;
     case AUX_TRIUSOLVE:
       this->auxiliaries << sanitize_source(casadi_triusolve_str, inst);
       break;
     case AUX_PROJECT:
       this->auxiliaries << sanitize_source(casadi_project_str, inst);
       break;
     case AUX_TRI_PROJECT:
       this->auxiliaries << sanitize_source(casadi_tri_project_str, inst);
       break;
     case AUX_DENSIFY:
       add_auxiliary(AUX_CLEAR);
       add_auxiliary(AUX_CAST);
       {
         std::vector<std::string> inst2 = inst;
         if (inst.size()==1) inst2.push_back(inst[0]);
         this->auxiliaries << sanitize_source(casadi_densify_str, inst2);
       }
       break;
     case AUX_SPARSIFY:
       add_auxiliary(AUX_CAST);
       {
         std::vector<std::string> inst2 = inst;
         if (inst.size()==1) inst2.push_back(inst[0]);
         this->auxiliaries << sanitize_source(casadi_sparsify_str, inst2);
       }
       break;
     case AUX_TRANS:
       this->auxiliaries << sanitize_source(casadi_trans_str, inst);
       break;
     case AUX_TO_MEX:
       add_auxiliary(AUX_TO_DOUBLE);
       this->auxiliaries << "#ifdef MATLAB_MEX_FILE\n"
                         << sanitize_source(casadi_to_mex_str, inst)
                         << "#endif\n\n";
       break;
     case AUX_FROM_MEX:
       add_auxiliary(AUX_FILL);
       this->auxiliaries << "#ifdef MATLAB_MEX_FILE\n"
                         << sanitize_source(casadi_from_mex_str, inst)
                         << "#endif\n\n";
       break;
     case AUX_FINITE_DIFF:
       add_auxiliary(AUX_FMAX);
       this->auxiliaries << sanitize_source(casadi_finite_diff_str, inst);
       break;
     case AUX_QR:
       add_auxiliary(AUX_IF_ELSE);
       add_auxiliary(AUX_SCAL);
       add_auxiliary(AUX_DOT);
       add_auxiliary(AUX_CLEAR);
       this->auxiliaries << sanitize_source(casadi_qr_str, inst);
       break;
     case AUX_LSQR:
       add_auxiliary(AUX_COPY);
       add_auxiliary(AUX_CLEAR);
       add_auxiliary(AUX_NORM_2);
       add_auxiliary(AUX_MV);
       add_auxiliary(AUX_FABS);
       add_auxiliary(AUX_SIGN);
       this->auxiliaries << sanitize_source(casadi_lsqr_str, inst);
       break;
     case AUX_QP:
       this->auxiliaries << sanitize_source(casadi_qp_str, inst);
       break;
     case AUX_QRQP:
       add_auxiliary(AUX_QP);
       add_auxiliary(AUX_COPY);
       add_auxiliary(AUX_QR);
       add_auxiliary(AUX_MAX);
       add_auxiliary(AUX_FMIN);
       add_auxiliary(AUX_FMAX);
       add_auxiliary(AUX_TRANS);
       add_auxiliary(AUX_AXPY);
       add_auxiliary(AUX_MV);
       add_auxiliary(AUX_BILIN);
       add_auxiliary(AUX_INF);
       add_auxiliary(AUX_REAL_MIN);
       add_auxiliary(AUX_CLEAR);
       add_include("stdarg.h");
       add_include("stdio.h");
       add_include("math.h");
       this->auxiliaries << sanitize_source(casadi_qrqp_str, inst);
       break;
     case AUX_NLP:
       add_auxiliary(AUX_ORACLE);
       this->auxiliaries << sanitize_source(casadi_nlp_str, inst);
       break;
     case AUX_SQPMETHOD:
       add_auxiliary(AUX_QP);
       add_auxiliary(AUX_NLP);
       add_auxiliary(AUX_FILL);
       add_auxiliary(AUX_FABS);
       this->auxiliaries << sanitize_source(casadi_sqpmethod_str, inst);
       break;
     case AUX_FEASIBLESQPMETHOD:
       add_auxiliary(AUX_QP);
       add_auxiliary(AUX_NLP);
       this->auxiliaries << sanitize_source(casadi_feasiblesqpmethod_str, inst);
       break;
     case AUX_LDL:
       this->auxiliaries << sanitize_source(casadi_ldl_str, inst);
       break;
     case AUX_NEWTON:
       add_auxiliary(AUX_COPY);
       add_auxiliary(AUX_AXPY);
       add_auxiliary(AUX_NORM_INF);
       add_auxiliary(AUX_QR);
       this->auxiliaries << sanitize_source(casadi_newton_str, inst);
       break;
     case AUX_MAX_VIOL:
       add_auxiliary(AUX_FMAX);
       this->auxiliaries << sanitize_source(casadi_max_viol_str, inst);
       break;
     case AUX_SUM_VIOL:
       this->auxiliaries << sanitize_source(casadi_sum_viol_str, inst);
       break;
     case AUX_SUM:
       this->auxiliaries << sanitize_source(casadi_sum_str, inst);
       break;
     case AUX_VFMIN:
       add_auxiliary(AUX_FMIN);
       this->auxiliaries << sanitize_source(casadi_vfmin_str, inst);
       break;
     case AUX_VFMAX:
       add_auxiliary(AUX_FMAX);
       this->auxiliaries << sanitize_source(casadi_vfmax_str, inst);
       break;
     case AUX_REGULARIZE:
       add_auxiliary(AUX_FABS);
       add_auxiliary(AUX_FMIN);
       this->auxiliaries << sanitize_source(casadi_regularize_str, inst);
       break;
     case AUX_BOUNDS_CONSISTENCY:
       add_auxiliary(AUX_ISINF);
       add_auxiliary(AUX_FMAX);
       add_auxiliary(AUX_FMIN);
       this->auxiliaries << sanitize_source(casadi_bound_consistency_str, inst);
       break;
     case AUX_FILE_SLURP:
       add_include("stdio.h");
       this->auxiliaries << sanitize_source(casadi_file_slurp_str, inst);
       break;
     case AUX_CACHE:
       this->auxiliaries << sanitize_source(casadi_cache_str, inst);
       break;
     case AUX_CVX:
       add_auxiliary(AUX_CLEAR);
       add_auxiliary(AUX_FABS);
       add_auxiliary(AUX_COPY);
       add_auxiliary(AUX_DOT);
       add_auxiliary(AUX_AXPY);
       add_auxiliary(AUX_FMAX);
       this->auxiliaries << sanitize_source(casadi_cvx_str, inst);
       break;
     case AUX_CONVEXIFY:
       add_auxiliary(AUX_CVX);
       add_auxiliary(AUX_PROJECT);
       add_auxiliary(AUX_REGULARIZE);
       add_auxiliary(AUX_COPY);
       this->auxiliaries << sanitize_source(casadi_convexify_str, inst);
       break;
     case AUX_LOGSUMEXP:
       add_auxiliary(AUX_LOG1P);
       add_auxiliary(AUX_FMAX);
       this->auxiliaries << sanitize_source(casadi_logsumexp_str, inst);
       break;
     case AUX_SPARSITY:
       this->auxiliaries << sanitize_source(casadi_sparsity_str, inst);
       break;
     case AUX_BFGS:
       add_auxiliary(AUX_COPY);
       add_auxiliary(AUX_AXPY);
       add_auxiliary(AUX_CLEAR);
       add_auxiliary(AUX_MV);
       add_auxiliary(AUX_DOT);
       add_auxiliary(AUX_IF_ELSE);
       add_auxiliary(AUX_SCAL);
       add_auxiliary(AUX_RANK1);
       this->auxiliaries << sanitize_source(casadi_bfgs_str, inst);
       break;
     case AUX_ORACLE:
       this->auxiliaries << sanitize_source(casadi_oracle_str, inst);
       break;
     case AUX_ORACLE_CALLBACK:
       this->auxiliaries << sanitize_source(casadi_oracle_callback_str, inst);
       break;
     case AUX_OCP_BLOCK:
       this->auxiliaries << sanitize_source(casadi_ocp_block_str, inst);
       break;
     case AUX_TO_DOUBLE:
       this->auxiliaries << "#define casadi_to_double(x) "
                         << "(" << (this->cpp ? "static_cast<double>(x)" : "(double) x") << ")\n\n";
       break;
     case AUX_TO_INT:
       this->auxiliaries << "#define casadi_to_int(x) "
                         << "(" << (this->cpp ? "static_cast<casadi_int>(x)" : "(casadi_int) x")
                         << ")\n\n";
       break;
     case AUX_CAST:
       this->auxiliaries << "#define CASADI_CAST(x,y) "
                         << "(" << (this->cpp ? "static_cast<x>(y)" : "(x) y") << ")\n\n";
       break;
     case AUX_SQ:
       shorthand("sq");
       this->auxiliaries << "casadi_real casadi_sq(casadi_real x) { return x*x;}\n\n";
       break;
     case AUX_SIGN:
       shorthand("sign");
       this->auxiliaries << "casadi_real casadi_sign(casadi_real x) "
                         << "{ return x<0 ? -1 : x>0 ? 1 : x;}\n\n";
       break;
     case AUX_IF_ELSE:
       shorthand("if_else");
       this->auxiliaries << "casadi_real casadi_if_else"
                         << "(casadi_real c, casadi_real x, casadi_real y) "
                         << "{ return c!=0 ? x : y;}\n\n";
       break;
     case AUX_PRINTF:
       this->auxiliaries << "#ifndef CASADI_PRINTF\n";
       if (this->mex) {
         this->auxiliaries << "#ifdef MATLAB_MEX_FILE\n"
                           << "  #define CASADI_PRINTF mexPrintf\n"
                           << "#else\n"
                           << "  #define CASADI_PRINTF printf\n"
                           << "#endif\n";
       } else {
         add_include("stdio.h");
         this->auxiliaries << "#define CASADI_PRINTF printf\n";
         this->auxiliaries << "#ifndef CASADI_SNPRINTF\n";
         this->auxiliaries << "#define CASADI_SNPRINTF snprintf\n";
         this->auxiliaries << "#endif\n\n";
       }
       this->auxiliaries << "#endif\n\n";
       break;
     case AUX_FMIN:
       shorthand("fmin");
       this->auxiliaries << "casadi_real casadi_fmin(casadi_real x, casadi_real y) {\n"
                         << "/* Pre-c99 compatibility */\n"
                         << "#if __STDC_VERSION__ < 199901L\n"
                         << "  return x<y ? x : y;\n"
                         << "#else\n"
                         << "  return fmin(x, y);\n"
                         << "#endif\n"
                         << "}\n\n";
       break;
     case AUX_FMAX:
       shorthand("fmax");
       this->auxiliaries << "casadi_real casadi_fmax(casadi_real x, casadi_real y) {\n"
                         << "/* Pre-c99 compatibility */\n"
                         << "#if __STDC_VERSION__ < 199901L\n"
                         << "  return x>y ? x : y;\n"
                         << "#else\n"
                         << "  return fmax(x, y);\n"
                         << "#endif\n"
                         << "}\n\n";
       break;
     case AUX_FABS:
       shorthand("fabs");
       this->auxiliaries << "casadi_real casadi_fabs(casadi_real x) {\n"
                         << "/* Pre-c99 compatibility */\n"
                         << "#if __STDC_VERSION__ < 199901L\n"
                         << "  return x>0 ? x : -x;\n"
                         << "#else\n"
                         << "  return fabs(x);\n"
                         << "#endif\n"
                         << "}\n\n";
       break;
     case AUX_ISINF:
       shorthand("isinf");
       this->auxiliaries << "casadi_real casadi_isinf(casadi_real x) {\n"
                         << "/* Pre-c99 compatibility */\n"
                         << "#if __STDC_VERSION__ < 199901L\n"
                         << "  return x== INFINITY || x==-INFINITY;\n"
                         << "#else\n"
                         << "  return isinf(x);\n"
                         << "#endif\n"
                         << "}\n\n";
       break;
     case AUX_MIN:
       this->auxiliaries << "casadi_int casadi_min(casadi_int x, casadi_int y) {\n"
                         << "  return x>y ? y : x;\n"
                         << "}\n\n";
       break;
     case AUX_MAX:
       this->auxiliaries << "casadi_int casadi_max(casadi_int x, casadi_int y) {\n"
                         << "  return x>y ? x : y;\n"
                         << "}\n\n";
       break;
     case AUX_MMIN:
       add_auxiliary(AUX_VFMIN);
       add_auxiliary(AUX_INF);
       this->auxiliaries << sanitize_source(casadi_mmin_str, inst);
       break;
     case AUX_MMAX:
       add_auxiliary(AUX_VFMAX);
       add_auxiliary(AUX_INF);
       this->auxiliaries << sanitize_source(casadi_mmax_str, inst);
       break;
     case AUX_INF:
       this->auxiliaries << "#ifndef casadi_inf\n"
                         << "  #define casadi_inf " << this->infinity << "\n"
                         << "#endif\n\n";
       break;
     case AUX_NAN:
       this->auxiliaries << "#ifndef casadi_nan\n"
                         << "  #define casadi_nan " << this->nan << "\n"
                         << "#endif\n\n";
       break;
     case AUX_REAL_MIN:
       this->auxiliaries << "#ifndef casadi_real_min\n"
                         << "  #define casadi_real_min " << this->real_min << "\n"
                         << "#endif\n\n";
       break;
     case AUX_LOG1P:
       shorthand("log1p");
       this->auxiliaries << "casadi_real casadi_log1p(casadi_real x) {\n"
                         << "/* Pre-c99 compatibility */\n"
                         << "#if __STDC_VERSION__ < 199901L\n"
                         << "  return log(1+x);\n"
                         << "#else\n"
                         << "  return log1p(x);\n"
                         << "#endif\n"
                         << "}\n\n";
       break;
     case AUX_EXPM1:
       shorthand("expm1");
       this->auxiliaries << "casadi_real casadi_expm1(casadi_real x) {\n"
                         << "/* Pre-c99 compatibility */\n"
                         << "#if __STDC_VERSION__ < 199901L\n"
                         << "  return exp(x)-1;\n"
                         << "#else\n"
                         << "  return expm1(x);\n"
                         << "#endif\n"
                         << "}\n\n";
       break;
     case AUX_HYPOT:
       shorthand("hypot");
       this->auxiliaries << "casadi_real casadi_hypot(casadi_real x, casadi_real y) {\n"
                         << "/* Pre-c99 compatibility */\n"
                         << "#if __STDC_VERSION__ < 199901L\n"
                         << "  return sqrt(x*x+y*y);\n"
                         << "#else\n"
                         << "  return hypot(x, y);\n"
                         << "#endif\n"
                         << "}\n\n";
       break;
     }
   }
References add_include(), added_auxiliaries_, AUX_AXPY, AUX_BFGS, AUX_BILIN, AUX_BOUNDS_CONSISTENCY, AUX_CACHE, AUX_CAST, AUX_CLEAR, AUX_CLIP_MAX, AUX_CLIP_MIN, AUX_CONVEXIFY, AUX_COPY, AUX_CVX, AUX_DE_BOOR, AUX_DENSIFY, AUX_DOT, AUX_EXPM1, AUX_FABS, AUX_FEASIBLESQPMETHOD, AUX_FILE_SLURP, AUX_FILL, AUX_FINITE_DIFF, AUX_FLIP, AUX_FMAX, AUX_FMIN, AUX_FROM_MEX, AUX_HYPOT, AUX_IAMAX, AUX_IF_ELSE, AUX_INF, AUX_INTERPN, AUX_INTERPN_GRAD, AUX_INTERPN_INTERPOLATE, AUX_INTERPN_WEIGHTS, AUX_ISINF, AUX_LDL, AUX_LOG1P, AUX_LOGSUMEXP, AUX_LOW, AUX_LSQR, AUX_MASKED_NORM_INF, AUX_MAX, AUX_MAX_VIOL, AUX_MIN, AUX_MMAX, AUX_MMIN, AUX_MTIMES, AUX_MV, AUX_MV_DENSE, AUX_NAN, AUX_ND_BOOR_EVAL, AUX_NEWTON, AUX_NLP, AUX_NORM_1, AUX_NORM_2, AUX_NORM_INF, AUX_OCP_BLOCK, AUX_ORACLE, AUX_ORACLE_CALLBACK, AUX_PRINTF, AUX_PROJECT, AUX_QP, AUX_QR, AUX_QRQP, AUX_RANK1, AUX_REAL_MIN, AUX_REGULARIZE, AUX_SCAL, AUX_SCALED_COPY, AUX_SIGN, AUX_SPARSIFY, AUX_SPARSITY, AUX_SQ, AUX_SQPMETHOD, AUX_SUM, AUX_SUM_VIOL, AUX_SWAP, AUX_TO_DOUBLE, AUX_TO_INT, AUX_TO_MEX, AUX_TRANS, AUX_TRI_PROJECT, AUX_TRILSOLVE, AUX_TRIUSOLVE, AUX_VECTOR_FMAX, AUX_VECTOR_FMIN, AUX_VFMAX, AUX_VFMIN, auxiliaries, cpp, infinity, mex, nan, real_min, sanitize_source(), and shorthand().
Referenced by axpy(), bilin(), bound_consistency(), cache_check(), clear(), clip_max(), clip_min(), casadi::MapSum::codegen_body(), casadi::Switch::codegen_body(), casadi::DaqpInterface::codegen_body(), casadi::HighsInterface::codegen_body(), casadi::HpipmInterface::codegen_body(), casadi::OsqpInterface::codegen_body(), casadi::FastNewton::codegen_body(), casadi::Feasiblesqpmethod::codegen_body(), casadi::Qrqp::codegen_body(), casadi::Sqpmethod::codegen_body(), casadi::FiniteDiff::codegen_declarations(), casadi::Nlpsol::codegen_declarations(), casadi::FatropInterface::codegen_declarations(), casadi::IpoptInterface::codegen_declarations(), casadi::MadnlpInterface::codegen_declarations(), casadi::Sqpmethod::codegen_declarations(), CodeGenerator(), constant(), convexify_eval(), copy(), densify(), dot(), dump(), file_slurp(), fill(), fmax(), fmin(), from_mex(), casadi::BSplineCommon::generate(), casadi::HorzRepsum::generate(), interpn(), interpn_grad(), lb_eig(), ldl(), ldl_solve(), logsumexp(), low(), lsqr_solve(), masked_norm_inf(), max(), max_viol(), min(), mmax(), mmin(), mtimes(), mv(), norm_2(), norm_inf(), print_op(), printf(), project(), casadi::Conic::qp_codegen_body(), qr(), qr_solve(), rank1(), regularize(), scal(), sparsify(), sum_viol(), to_mex(), trans(), tri_project(), trilsolve(), triusolve(), vector_fmax(), vector_fmin(), vfmax(), and vfmin().
add_dependency()
std::string casadi::CodeGenerator::add_dependency (const Function & f)
Definition at line 223 of file code_generator.cpp.
{
     // Quick return if it already exists
     for (auto&& e : added_functions_) if (e.f==f) return e.codegen_name;
     // Give it a name
     std::string fname = shorthand("f" + str(added_functions_.size()));
     // Add to list of functions
     added_functions_.push_back({f, fname});
     // Generate declarations
     f->codegen_declarations(*this);
     // Print to file
     f->codegen(*this, fname);
     // Codegen reference count functions, if needed
     if (f->has_refcount_) {
       // Increase reference counter
       *this << "void " << fname << "_incref(void) {\n";
       f->codegen_incref(*this);
       *this << "}\n\n";
       // Decrease reference counter
       *this << "void " << fname << "_decref(void) {\n";
       f->codegen_decref(*this);
       *this << "}\n\n";
     }
     bool fun_needs_mem = !f->codegen_mem_type().empty();
     needs_mem_ |= fun_needs_mem;
     if (fun_needs_mem) {
       // Alloc memory
       *this << "int " << fname << "_alloc_mem(void) {\n";
       flush(this->body);
       scope_enter();
       f->codegen_alloc_mem(*this);
       scope_exit();
       *this << "}\n\n";
       // Initialize memory
       *this << "int " << fname << "_init_mem(int mem) {\n";
       flush(this->body);
       scope_enter();
       f->codegen_init_mem(*this);
       scope_exit();
       *this << "}\n\n";
       // Clear memory
       *this << "void " << fname << "_free_mem(int mem) {\n";
       flush(this->body);
       scope_enter();
       f->codegen_free_mem(*this);
       scope_exit();
       *this << "}\n\n";
       // Checkout
       *this << "int " << fname << "_checkout(void) {\n";
       flush(this->body);
       scope_enter();
       f->codegen_checkout(*this);
       scope_exit();
       *this << "}\n\n";
       // Clear memory
       *this << "void " << fname << "_release(int mem) {\n";
       flush(this->body);
       scope_enter();
       f->codegen_release(*this);
       scope_exit();
       *this << "}\n\n";
     }
     // Flush to body
     flush(this->body);
     return fname;
   }
References added_functions_, body, casadi::FunctionInternal::codegen(), casadi::FunctionInternal::codegen_alloc_mem(), casadi::FunctionInternal::codegen_checkout(), casadi::FunctionInternal::codegen_declarations(), casadi::FunctionInternal::codegen_decref(), casadi::FunctionInternal::codegen_free_mem(), casadi::FunctionInternal::codegen_incref(), casadi::FunctionInternal::codegen_init_mem(), casadi::FunctionInternal::codegen_mem_type(), casadi::FunctionInternal::codegen_release(), flush(), casadi::FunctionInternal::has_refcount_, needs_mem_, scope_enter(), scope_exit(), shorthand(), and casadi::str().
Referenced by add(), casadi::Call::add_dependency(), casadi::FiniteDiff::codegen_declarations(), casadi::Map::codegen_declarations(), casadi::MapSum::codegen_declarations(), casadi::Nlpsol::codegen_declarations(), casadi::Switch::codegen_declarations(), casadi::FatropInterface::codegen_declarations(), casadi::IpoptInterface::codegen_declarations(), casadi::MadnlpInterface::codegen_declarations(), casadi::FastNewton::codegen_declarations(), casadi::Feasiblesqpmethod::codegen_declarations(), casadi::Sqpmethod::codegen_declarations(), operator()(), and setup_callback().
add_external()
void casadi::CodeGenerator::add_external (const std::string & new_external)
Definition at line 1060 of file code_generator.cpp.
{
     added_externals_.insert(new_external);
   }
References added_externals_.
Referenced by casadi::External::codegen_declarations().
add_include()
void casadi::CodeGenerator::add_include (const std::string & new_include, bool relative_path = false, const std::string & use_ifdef = std::string())
Definition at line 999 of file code_generator.cpp.
{
     // Register the new element
     bool added = added_includes_.insert(new_include).second;
     // Quick return if it already exists
     if (!added) return;
     // Ifdef opening
     if (!use_ifdef.empty()) this->includes << "#ifdef " << use_ifdef << std::endl;
     // Print to the header section
     if (relative_path) {
       this->includes << "#include \"" << new_include << "\"\n";
     } else {
       this->includes << "#include <" << new_include << ">\n";
     }
     // Ifdef closing
     if (!use_ifdef.empty()) this->includes << "#endif\n";
   }
References added_includes_, and includes.
Referenced by add_auxiliary(), casadi::DaqpInterface::codegen_body(), casadi::HighsInterface::codegen_body(), casadi::HpipmInterface::codegen_body(), casadi::OsqpInterface::codegen_body(), casadi::FatropInterface::codegen_declarations(), casadi::IpoptInterface::codegen_declarations(), casadi::MadnlpInterface::codegen_declarations(), and CodeGenerator().
add_io_sparsities()
void casadi::CodeGenerator::add_io_sparsities (const std::string & name, const std::vector< Sparsity > & sp_in, const std::vector< Sparsity > & sp_out)
Extra doc: https://github.com/casadi/casadi/wiki/L_tq
Definition at line 2318 of file code_generator.cpp.
{
     // Insert element, quick return if it already exists
     if (!sparsity_meta.insert(name).second) return;
     // Input sparsities
     *this << declare("const casadi_int* " + name + "_sparsity_in(casadi_int i)") << " {\n"
       << "switch (i) {\n";
     for (casadi_int i=0; i<sp_in.size(); ++i) {
       *this << "case " << i << ": return " << sparsity(sp_in[i]) << ";\n";
     }
     *this << "default: return 0;\n}\n"
       << "}\n\n";
     // Output sparsities
     *this << declare("const casadi_int* " + name + "_sparsity_out(casadi_int i)") << " {\n"
       << "switch (i) {\n";
     for (casadi_int i=0; i<sp_out.size(); ++i) {
       *this << "case " << i << ": return " << sparsity(sp_out[i]) << ";\n";
     }
     *this << "default: return 0;\n}\n"
       << "}\n\n";
   }
References declare(), name, sparsity(), and sparsity_meta.
Referenced by add(), and casadi::FunctionInternal::codegen_sparsities().
add_sparsity()
casadi_int casadi::CodeGenerator::add_sparsity (const Sparsity & sp)
Definition at line 1077 of file code_generator.cpp.
{
     return get_constant(sp, true);
   }
References get_constant().
Referenced by sparsity().
arg()
std::string casadi::CodeGenerator::arg (casadi_int i) const
Extra doc: https://github.com/casadi/casadi/wiki/L_tw
Definition at line 1869 of file code_generator.cpp.
{
     return "arg[" + str(i) + "]";
   }
References casadi::str().
Referenced by casadi::FiniteDiff::codegen_body(), casadi::OmpMap::codegen_body(), casadi::SXFunction::codegen_body(), casadi::OsqpInterface::codegen_body(), casadi::FastNewton::codegen_body(), casadi::Feasiblesqpmethod::codegen_body(), casadi::LinearInterpolant::codegen_body(), casadi::LinearInterpolantJac::codegen_body(), casadi::Qrqp::codegen_body(), copy(), copy_check(), copy_default(), densify(), from_mex(), casadi::Input::generate(), operator()(), printf(), project(), sparsify(), to_mex(), and tri_project().
array()
std::string casadi::CodeGenerator::array (const std::string & type, const std::string & name, casadi_int len, const std::string & def = std::string()) static
Declare an array
Definition at line 928 of file code_generator.cpp.
{
     std::stringstream s;
     s << type << " ";
     if (len==0) {
       s << "*" << name << " = 0";
     } else {
       s << name << "[" << len << "]";
       if (!def.empty()) s << " = " << def;
     }
     s << ";\n";
     return s.str();
   }
References name.
Referenced by casadi::FunctionInternal::codegen_meta(), and print_vector().
avoid_stack()
bool casadi::CodeGenerator::avoid_stack () inline
Extra doc: https://github.com/casadi/casadi/wiki/L_si
Definition at line 245 of file code_generator.hpp.
 { return avoid_stack_;}
Referenced by casadi::FunctionInternal::codegen_meta().
axpy()
std::string casadi::CodeGenerator::axpy (casadi_int n, const std::string & a, const std::string & x, const std::string & y)
Extra doc: https://github.com/casadi/casadi/wiki/L_sp
Definition at line 2045 of file code_generator.cpp.
{
     add_auxiliary(AUX_AXPY);
     return "casadi_axpy(" + str(n) + ", " + a + ", " + x + ", " + y + ");";
   }
References add_auxiliary(), AUX_AXPY, and casadi::str().
Referenced by casadi::FiniteDiff::codegen_body(), casadi::MapSum::codegen_body(), casadi::Feasiblesqpmethod::codegen_body(), casadi::Sqpmethod::codegen_body(), and casadi::Feasiblesqpmethod::codegen_feasibility_iterations().
bilin()
std::string casadi::CodeGenerator::bilin (const std::string & A, const Sparsity & sp_A, const std::string & x, const std::string & y)
Extra doc: https://github.com/casadi/casadi/wiki/L_su
Definition at line 1901 of file code_generator.cpp.
{
     add_auxiliary(AUX_BILIN);
     std::stringstream s;
     s << "casadi_bilin(" << A << ", " << sparsity(sp_A) << ", " << x << ", " << y << ")";
     return s.str();
   }
References add_auxiliary(), AUX_BILIN, and sparsity().
Referenced by casadi::Feasiblesqpmethod::codegen_eval_m_k(), and casadi::Bilin::generate().
bound_consistency()
std::string casadi::CodeGenerator::bound_consistency (casadi_int n, const std::string & x, const std::string & lam, const std::string & lbx, const std::string & ubx)
Extra doc: https://github.com/casadi/casadi/wiki/L_th
Definition at line 2502 of file code_generator.cpp.
{
       add_auxiliary(CodeGenerator::AUX_BOUNDS_CONSISTENCY);
       return "casadi_bound_consistency(" + str(n) + ", " + x + ", " + lam +
              ", " + lbx + ", " + ubx + ")";
     }
References add_auxiliary(), AUX_BOUNDS_CONSISTENCY, and casadi::str().
Referenced by casadi::Feasiblesqpmethod::codegen_body(), and casadi::Nlpsol::codegen_body_exit().
cache_check()
std::string casadi::CodeGenerator::cache_check (const std::string & key, const std::string & cache, const std::string & loc, casadi_int stride, casadi_int sz, casadi_int key_sz, const std::string & val)
Extra doc: https://github.com/casadi/casadi/wiki/L_u8
Definition at line 2516 of file code_generator.cpp.
{
     add_auxiliary(CodeGenerator::AUX_CACHE);
     return "cache_check(" + key + ", " + cache + ", " + loc + ", " +
     str(stride) + ", " + str(sz) + ", " + str(key_sz) + ", " + val + ")";
   }
References add_auxiliary(), AUX_CACHE, and casadi::str().
Referenced by casadi::LinsolQr::generate().
casadi_version()
std::string casadi::CodeGenerator::casadi_version () static
Definition at line 355 of file code_generator.cpp.
{
     std::stringstream ss;
     ss << CASADI_MAJOR_VERSION << "." << CASADI_MINOR_VERSION << "." << CASADI_PATCH_VERSION;
     if (!CASADI_IS_RELEASE) ss << "+";
     return ss.str();
   }
Referenced by file_open().
clear()
std::string casadi::CodeGenerator::clear (const std::string & res, std::size_t n)
Extra doc: https://github.com/casadi/casadi/wiki/L_tv
Definition at line 1861 of file code_generator.cpp.
{
     std::stringstream s;
     // Perform operation
     add_auxiliary(AUX_CLEAR);
     s << "casadi_clear(" << res << ", " << n << ");";
     return s.str();
   }
References add_auxiliary(), AUX_CLEAR, and res().
Referenced by casadi::Feasiblesqpmethod::codegen_body(), casadi::Sqpmethod::codegen_body(), casadi::OsqpInterface::codegen_init_mem(), casadi::Sqpmethod::codegen_solve_elastic_mode(), fill(), casadi::BSplineCommon::generate(), casadi::Constant< Value >::generate(), and casadi::HorzRepsum::generate().
clip_max()
std::string casadi::CodeGenerator::clip_max (const std::string & x, casadi_int n, const std::string & min, const std::string & mask)
Definition at line 2057 of file code_generator.cpp.
{
     add_auxiliary(AUX_CLIP_MAX);
     return "casadi_clip_max(" + x + ", " + str(n) + ", " + min + ", " + mask + ");";
   }
References add_auxiliary(), AUX_CLIP_MAX, min(), and casadi::str().
Referenced by casadi::Feasiblesqpmethod::codegen_body(), and casadi::Feasiblesqpmethod::codegen_feasibility_iterations().
clip_min()
std::string casadi::CodeGenerator::clip_min (const std::string & x, casadi_int n, const std::string & min, const std::string & mask)
Definition at line 2051 of file code_generator.cpp.
{
     add_auxiliary(AUX_CLIP_MIN);
     return "casadi_clip_min(" + x + ", " + str(n) + ", " + min + ", " + mask + ");";
   }
References add_auxiliary(), AUX_CLIP_MIN, min(), and casadi::str().
Referenced by casadi::Feasiblesqpmethod::codegen_body(), and casadi::Feasiblesqpmethod::codegen_feasibility_iterations().
comment()
void casadi::CodeGenerator::comment (const std::string & s)
Extra doc: https://github.com/casadi/casadi/wiki/L_tn
Definition at line 2312 of file code_generator.cpp.
{
     if (verbose) {
       *this << "/* " << s << " */\n";
     }
   }
References verbose.
Referenced by casadi::FiniteDiff::codegen_body(), casadi::OsqpInterface::codegen_body(), casadi::FastNewton::codegen_body(), casadi::Feasiblesqpmethod::codegen_body(), casadi::Qrqp::codegen_body(), casadi::Sqpmethod::codegen_body(), casadi::Feasiblesqpmethod::codegen_feasibility_iterations(), casadi::Sqpmethod::codegen_solve_elastic_mode(), casadi::Feasiblesqpmethod::codegen_tr_update(), casadi::LinsolLdl::generate(), casadi::LinsolQr::generate(), and casadi::Lsqr::generate().
constant() [1/8]
std::string casadi::CodeGenerator::constant (casadi_int v)
Definition at line 1761 of file code_generator.cpp.
{
     return constant(static_cast<double>(v));
   }
References constant().
constant() [2/8]
std::string casadi::CodeGenerator::constant (const std::string & v)
Definition at line 1754 of file code_generator.cpp.
{
     std::string ret = v;
     ret = replace(ret, "\\", "\\\\");
     ret = replace(ret, "\"", "\\\"");
     return "\"" + ret + "\"";
   }
References casadi::replace().
constant() [3/8]
std::string casadi::CodeGenerator::constant (const std::vector< casadi_int > & v)
Extra doc: https://github.com/casadi/casadi/wiki/L_rz
Definition at line 1212 of file code_generator.cpp.
{
     return shorthand("s" + str(get_constant(v, true)));
   }
References get_constant(), shorthand(), and casadi::str().
Referenced by casadi::SXFunction::codegen_body(), casadi::HighsInterface::codegen_body(), casadi::OsqpInterface::codegen_body(), casadi::FastNewton::codegen_body(), casadi::Feasiblesqpmethod::codegen_body(), casadi::LinearInterpolant::codegen_body(), casadi::LinearInterpolantJac::codegen_body(), casadi::Qrqp::codegen_body(), casadi::Nlpsol::codegen_body_enter(), casadi::External::codegen_incref(), casadi::FunctionInternal::codegen_meta(), casadi::Sqpmethod::codegen_solve_elastic_mode(), casadi::codegen_unpack_block(), constant(), constant_copy(), casadi::Convexify::generate(), casadi::LinsolLdl::generate(), casadi::LinsolQr::generate(), casadi::BSpline::generate(), casadi::BSplineCommon::generate(), casadi::ConstantDM::generate(), casadi::Constant< Value >::generate(), casadi::GetNonzerosVector::generate(), casadi::GetNonzerosParamVector::generate(), casadi::GetNonzerosSliceParam::generate(), casadi::GetNonzerosParamSlice::generate(), casadi::GetNonzerosParamParam::generate(), casadi::SetNonzerosVector< Add >::generate(), initializer(), and casadi::FatropInterface::set_fatrop_prob().
constant() [4/8]
std::string casadi::CodeGenerator::constant (const std::vector< char > & v)
Extra doc: https://github.com/casadi/casadi/wiki/L_27m
Definition at line 1216 of file code_generator.cpp.
{
     return shorthand("b" + str(get_constant(v, true)));
   }
References get_constant(), shorthand(), and casadi::str().
constant() [5/8]
std::string casadi::CodeGenerator::constant (const std::vector< double > & v)
Extra doc: https://github.com/casadi/casadi/wiki/L_s1
Definition at line 1240 of file code_generator.cpp.
{
     return shorthand("c" + str(get_constant(v, true)));
   }
References get_constant(), shorthand(), and casadi::str().
constant() [6/8]
std::string casadi::CodeGenerator::constant (const std::vector< int > & v) inline
Extra doc: https://github.com/casadi/casadi/wiki/L_255
Definition at line 124 of file code_generator.hpp.
{
         return constant(vector_static_cast<casadi_int>(v));
     }
constant() [7/8]
std::string casadi::CodeGenerator::constant (const std::vector< std::string > & v)
Extra doc: https://github.com/casadi/casadi/wiki/L_280
Definition at line 1220 of file code_generator.cpp.
{
     return shorthand("a" + str(get_constant(v, true)));
   }
References get_constant(), shorthand(), and casadi::str().
constant() [8/8]
std::string casadi::CodeGenerator::constant (double v)
Extra doc: https://github.com/casadi/casadi/wiki/L_sj
Definition at line 1764 of file code_generator.cpp.
{
     std::stringstream s;
     if (isnan(v)) {
       add_auxiliary(AUX_NAN);
       s << "casadi_nan";
     } else if (isinf(v)) {
       add_auxiliary(AUX_INF);
       if (v<0) s << "-";
       s << "casadi_inf";
     } else {
       casadi_int v_int = static_cast<casadi_int>(v);
       if (static_cast<double>(v_int)==v) {
         // Print integer
         s << v_int << ".";
       } else {
         // Print real
         std::ios_base::fmtflags fmtfl = s.flags(); // get current format flags
         s << std::scientific << std::setprecision(std::numeric_limits<double>::digits10 + 1) << v;
         s.flags(fmtfl); // reset current format flags
       }
     }
     return s.str();
   }
References add_auxiliary(), AUX_INF, and AUX_NAN.
constant_copy()
void casadi::CodeGenerator::constant_copy (const std::string & var_name, const std::vector< casadi_int > & v, const std::string & type = "casadi_int")
Extra doc: https://github.com/casadi/casadi/wiki/L_s0
Definition at line 1224 of file code_generator.cpp.
{
     std::string ref = constant(v);
     if (!v.empty()) {
       local(name+"[" + str(v.size()) + "]", type);
     } else {
       local(name, type, "*");
     }
     if (!v.empty()) {
       local("i", type);
       (*this) << "for (i=0;i<" << v.size() << ";++i) " + name + "[i] = " + ref + "[i];\n";
     } else {
       init_local(name, "0");
     }
   }
References constant(), init_local(), local(), name, and casadi::str().
Referenced by casadi::OsqpInterface::codegen_init_mem().
convexify_eval()
std::string casadi::CodeGenerator::convexify_eval (const ConvexifyData & d, const std::string & Hin, const std::string & Hout, const std::string & iw, const std::string & w)
Extra doc: https://github.com/casadi/casadi/wiki/L_tk
Definition at line 2489 of file code_generator.cpp.
{
       add_auxiliary(CodeGenerator::AUX_CONVEXIFY);
       return Convexify::generate(*this, d, Hin, Hout, iw, w);
   }
References add_auxiliary(), AUX_CONVEXIFY, and casadi::Convexify::generate().
Referenced by casadi::Sqpmethod::codegen_body(), and casadi::Convexify::generate().
copy()
std::string casadi::CodeGenerator::copy (const std::string & arg, std::size_t n, const std::string & res)
Extra doc: https://github.com/casadi/casadi/wiki/L_tt
Definition at line 1832 of file code_generator.cpp.
{
     std::stringstream s;
     // Perform operation
     add_auxiliary(AUX_COPY);
     s << "casadi_copy(" << arg << ", " << n << ", " << res << ");";
     return s.str();
   }
References add_auxiliary(), arg(), AUX_COPY, and res().
Referenced by casadi::FiniteDiff::codegen_body(), casadi::JitFunction::codegen_body(), casadi::FastNewton::codegen_body(), casadi::Feasiblesqpmethod::codegen_body(), casadi::Sqpmethod::codegen_body(), casadi::Nlpsol::codegen_body_exit(), casadi::Feasiblesqpmethod::codegen_feasibility_iterations(), casadi::Sqpmethod::codegen_solve_elastic_mode(), casadi::Feasiblesqpmethod::codegen_step_update(), copy_check(), copy_default(), casadi::LinsolQr::generate(), casadi::Assertion::generate(), casadi::ConstantDM::generate(), casadi::ConstantFile::generate(), casadi::Einstein::generate(), casadi::Input::generate(), casadi::Output::generate(), casadi::Monitor::generate(), casadi::Multiplication::generate(), casadi::DenseMultiplication::generate(), casadi::Rank1::generate(), casadi::HorzRepmat::generate(), casadi::Reshape::generate(), casadi::SetNonzerosVector< Add >::generate(), casadi::SetNonzerosSlice< Add >::generate(), casadi::SetNonzerosSlice2< Add >::generate(), casadi::SetNonzerosParam< Add >::generate(), casadi::LinsolCall< Tr >::generate(), casadi::TriuSolve< Tr >::generate(), casadi::TrilSolve< Tr >::generate(), casadi::TriuSolveUnity< Tr >::generate(), casadi::TrilSolveUnity< Tr >::generate(), casadi::SparsityCast::generate(), casadi::Split::generate(), and project().
copy_check()
void casadi::CodeGenerator::copy_check (const std::string & arg, std::size_t n, const std::string & res, bool check_lhs = true, bool check_rhs = true)
Definition at line 1841 of file code_generator.cpp.
{
     std::vector<std::string> checks;
     if (check_lhs) checks.push_back(arg);
     if (check_rhs) checks.push_back(res);
     if (!checks.empty()) *this << "if (" << join(checks, " && ") << ") ";
     *this << copy(arg, n, res) << "\n";
   }
References arg(), copy(), casadi::join(), and res().
Referenced by casadi::OsqpInterface::codegen_body(), casadi::Feasiblesqpmethod::codegen_body(), casadi::Qrqp::codegen_body(), and casadi::Nlpsol::codegen_body_exit().
copy_default()
void casadi::CodeGenerator::copy_default (const std::string & arg, std::size_t n, const std::string & res, const std::string & def, bool check_rhs = true)
Definition at line 1850 of file code_generator.cpp.
{
     *this << "if (" << arg << ") {\n";
     if (check_rhs) *this << "if (" << res << ") ";
     *this << copy(arg, n, res) << "\n";
     *this << "} else {\n";
     if (check_rhs) *this << "if (" << res << ") ";
     *this << fill(res, n, def) << "\n";
     *this << "}\n";
   }
References arg(), copy(), fill(), and res().
Referenced by casadi::OsqpInterface::codegen_body(), casadi::Feasiblesqpmethod::codegen_body(), casadi::Qrqp::codegen_body(), and casadi::Nlpsol::codegen_body_enter().
declare()
std::string casadi::CodeGenerator::declare (std::string s)
Extra doc: https://github.com/casadi/casadi/wiki/L_tm
Definition at line 1952 of file code_generator.cpp.
{
     // Add c linkage
     std::string cpp_prefix = this->cpp ? "extern \"C\" " : "";
     // To header file
     if (this->with_header) {
       this->header << cpp_prefix << this->dll_import << s << ";\n";
     }
     // Return name with declarations
     return cpp_prefix + this->dll_export + s;
   }
References cpp, dll_import, header, and with_header.
Referenced by add(), add_io_sparsities(), and casadi::FunctionInternal::codegen_meta().
define_rom_double()
void casadi::CodeGenerator::define_rom_double (const void * id, casadi_int size)
Extra doc: https://github.com/casadi/casadi/wiki/L_s2
Definition at line 758 of file code_generator.cpp.
{
     auto it = file_scope_double_.find(id);
     casadi_assert(it==file_scope_double_.end(), "Already defined.");
     shorthand("rd" + str(file_scope_double_.size()));
     file_scope_double_[id] = size;
   }
References file_scope_double_, shorthand(), and casadi::str().
Referenced by casadi::ConstantFile::add_dependency().
define_rom_integer()
void casadi::CodeGenerator::define_rom_integer (const void * id, casadi_int size)
Extra doc: https://github.com/casadi/casadi/wiki/L_s4
Definition at line 772 of file code_generator.cpp.
{
     auto it = file_scope_double_.find(id);
     casadi_assert(it==file_scope_double_.end(), "Already defined.");
     shorthand("ri" + str(file_scope_double_.size()));
     file_scope_double_[id] = size;
   }
References file_scope_double_, shorthand(), and casadi::str().
densify()
std::string casadi::CodeGenerator::densify (const std::string & arg, const Sparsity & sp_arg, const std::string & res, bool tr = false)
Extra doc: https://github.com/casadi/casadi/wiki/L_u1
Definition at line 1992 of file code_generator.cpp.
{
     // Create call
     add_auxiliary(AUX_DENSIFY);
     std::stringstream s;
     s << "casadi_densify(" << arg << ", " << sparsity(sp_arg) << ", " << res << ", "
       << (tr ? 1 : 0) << ");";
     return s.str();
   }
References add_auxiliary(), arg(), AUX_DENSIFY, res(), and sparsity().
Referenced by casadi::Densify::generate().
dot()
std::string casadi::CodeGenerator::dot (casadi_int n, const std::string & x, const std::string & y)
Extra doc: https://github.com/casadi/casadi/wiki/L_sm
Definition at line 1893 of file code_generator.cpp.
{
     add_auxiliary(AUX_DOT);
     std::stringstream s;
     s << "casadi_dot(" << n << ", " << x << ", " << y << ")";
     return s.str();
   }
References add_auxiliary(), and AUX_DOT.
Referenced by casadi::Sqpmethod::codegen_body(), casadi::Feasiblesqpmethod::codegen_eval_m_k(), casadi::Dot::generate(), and casadi::NormF::generate().
dump() [1/2]
std::string casadi::CodeGenerator::dump ()
Definition at line 349 of file code_generator.cpp.
{
     std::stringstream s;
     dump(s);
     return s.str();
   }
Referenced by generate().
dump() [2/2]
void casadi::CodeGenerator::dump (std::ostream & s)
Definition at line 786 of file code_generator.cpp.
{
     // Consistency check
     casadi_assert_dev(current_indent_ == 0);
     // Prefix internal symbols to avoid symbol collisions
     s << "/* How to prefix internal symbols */\n"
       << "#ifdef CASADI_CODEGEN_PREFIX\n"
       << "  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)\n"
       << "  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID\n"
       << "  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)\n"
       << "#else\n"
       << "  #define CASADI_PREFIX(ID) " << this->prefix << "_ ## ID\n"
       << "#endif\n\n";
     s << this->includes.str();
     s << std::endl;
     // Numeric types after includes: may depend on them. e.g. mex type
     // Real type (usually double)
     generate_casadi_real(s);
     // Integer type (usually long long)
     generate_casadi_int(s);
     if (needs_mem_) {
       s << "#ifndef CASADI_MAX_NUM_THREADS\n";
       s << "#define CASADI_MAX_NUM_THREADS 1\n";
       s << "#endif\n\n";
     }
     // casadi/mem after numeric types to define derived types
     // Memory struct entry point
     if (this->with_mem) {
       s << "#include <casadi/mem.h>\n" << std::endl;
     }
     // Macros
     if (!added_shorthands_.empty()) {
       s << "/* Add prefix to internal symbols */\n";
       for (auto&& i : added_shorthands_) {
         s << "#define " << "casadi_" << i <<  " CASADI_PREFIX(" << i <<  ")\n";
       }
       s << std::endl;
     }
     if (this->with_export) generate_export_symbol(s);
     // Check if inf/nan is needed
     for (const auto& d : double_constants_) {
       for (double e : d) {
         if (isinf(e)) add_auxiliary(AUX_INF);
         if (isnan(e)) add_auxiliary(AUX_NAN);
       }
     }
     // Codegen auxiliary functions
     s << this->auxiliaries.str();
     // Print integer constants
     if (!integer_constants_.empty()) {
       for (casadi_int i=0; i<integer_constants_.size(); ++i) {
         print_vector(s, "casadi_s" + str(i), integer_constants_[i]);
       }
       s << std::endl;
     }
     // Print double constants
     if (!double_constants_.empty()) {
       for (casadi_int i=0; i<double_constants_.size(); ++i) {
         print_vector(s, "casadi_c" + str(i), double_constants_[i]);
       }
       s << std::endl;
     }
     // Print char constants
     if (!char_constants_.empty()) {
       for (casadi_int i=0; i<char_constants_.size(); ++i) {
         print_vector(s, "casadi_b" + str(i), char_constants_[i]);
       }
       s << std::endl;
     }
     // Print string constants
     if (!string_constants_.empty()) {
       for (casadi_int i=0; i<string_constants_.size(); ++i) {
         print_vector(s, "casadi_a" + str(i), string_constants_[i]);
       }
       s << std::endl;
     }
     // Print file scope double work
     if (!file_scope_double_.empty()) {
       casadi_int i=0;
       for (const auto& it : file_scope_double_) {
         s << "static casadi_real casadi_rd" + str(i++) + "[" + str(it.second) + "];\n";
       }
       s << std::endl;
     }
     // Print file scope integer work
     if (!file_scope_integer_.empty()) {
       casadi_int i=0;
       for (const auto& it : file_scope_integer_) {
         s << "static casadi_real casadi_ri" + str(i++) + "[" + str(it.second) + "];\n";
       }
       s << std::endl;
     }
     // External function declarations
     if (!added_externals_.empty()) {
       s << "/* External functions */\n";
       for (auto&& i : added_externals_) {
         s << i << std::endl;
       }
       s << std::endl << std::endl;
     }
     // Codegen body
     s << this->body.str();
     // End with new line
     s << std::endl;
   }
References add_auxiliary(), added_externals_, added_shorthands_, AUX_INF, AUX_NAN, auxiliaries, body, char_constants_, current_indent_, double_constants_, file_scope_double_, file_scope_integer_, includes, integer_constants_, needs_mem_, prefix, print_vector(), casadi::str(), string_constants_, with_export, and with_mem.
equal()
template<typename T > static bool casadi::CodeGenerator::equal (const std::vector< T > & v1, const std::vector< T > & v2) inline static
Definition at line 961 of file code_generator.hpp.
{
       if (v1.size()!=v2.size()) return false;
       for (casadi_int j=0; j<v1.size(); ++j) {
         if (v1[j]!=v2[j]) return false;
       }
       return true;
     }
Referenced by get_constant().
file_close()
void casadi::CodeGenerator::file_close (std::ofstream & f, bool cpp) static
Definition at line 383 of file code_generator.cpp.
{
     // C linkage
     if (!cpp) {
       f << "#ifdef __cplusplus\n"
         << "} /* extern \"C\" */\n"
         << "#endif\n";
     }
     // Close file(s)
     f.close();
   }
References cpp.
Referenced by generate(), and casadi::DaeBuilderInternal::generate_wrapper().
file_open()
void casadi::CodeGenerator::file_open (std::ofstream & f, const std::string & name, bool cpp) static
Definition at line 362 of file code_generator.cpp.
{
     // Open a file for writing
     f.open(name);
     // Print header
     f << "/* This file was automatically generated by CasADi " << casadi_version() << ".\n"
       << " *  It consists of: \n"
       << " *   1) content generated by CasADi runtime: not copyrighted\n"
       << " *   2) template code copied from CasADi source: permissively licensed (MIT-0)\n"
       << " *   3) user code: owned by the user\n"
       << " *\n"
       << " */\n";
     // C linkage
     if (!cpp) {
       f << "#ifdef __cplusplus\n"
         << "extern \"C\" {\n"
         << "#endif\n\n";
     }
   }
References casadi_version(), cpp, and name.
Referenced by generate(), and casadi::DaeBuilderInternal::generate_wrapper().
file_slurp()
std::string casadi::CodeGenerator::file_slurp (const std::string & fname, casadi_int n, const std::string & a)
Extra doc: https://github.com/casadi/casadi/wiki/L_u7
Definition at line 2510 of file code_generator.cpp.
{
     add_auxiliary(CodeGenerator::AUX_FILE_SLURP);
     return "casadi_file_slurp(\"" + fname + "\", " + str(n) + ", " + a + ")";
   }
References add_auxiliary(), AUX_FILE_SLURP, and casadi::str().
Referenced by casadi::ConstantFile::codegen_incref().
fill()
std::string casadi::CodeGenerator::fill (const std::string & res, std::size_t n, const std::string & v)
Extra doc: https://github.com/casadi/casadi/wiki/L_tu
Definition at line 1883 of file code_generator.cpp.
{
     if (v=="0") return clear(res, n);
     std::stringstream s;
     // Perform operation
     add_auxiliary(AUX_FILL);
     s << "casadi_fill(" << res << ", " << n << ", " << v << ");";
     return s.str();
   }
References add_auxiliary(), AUX_FILL, clear(), and res().
Referenced by casadi::Qrqp::codegen_body(), casadi::Sqpmethod::codegen_body(), casadi::Sqpmethod::codegen_solve_elastic_mode(), copy_default(), and casadi::Constant< Value >::generate().
flush()
void casadi::CodeGenerator::flush (std::ostream & s)
Extra doc: https://github.com/casadi/casadi/wiki/L_sa
Definition at line 2178 of file code_generator.cpp.
{
     s << this->buffer.str();
     this->buffer.str(std::string());
   }
References buffer.
Referenced by add(), add_dependency(), casadi::FunctionInternal::codegen(), casadi::IpoptInterface::codegen_declarations(), and casadi::FunctionInternal::codegen_meta().
fmax()
std::string casadi::CodeGenerator::fmax (const std::string & x, const std::string & y)
Extra doc: https://github.com/casadi/casadi/wiki/L_t4
Definition at line 2393 of file code_generator.cpp.
{
     add_auxiliary(CodeGenerator::AUX_FMAX);
     return "casadi_fmax(" + x + ", " + y + ");";
   }
References add_auxiliary(), and AUX_FMAX.
Referenced by casadi::Sqpmethod::codegen_body(), and casadi::Sqpmethod::codegen_calc_gamma_1().
fmin()
std::string casadi::CodeGenerator::fmin (const std::string & x, const std::string & y)
Extra doc: https://github.com/casadi/casadi/wiki/L_t5
Definition at line 2399 of file code_generator.cpp.
{
     add_auxiliary(CodeGenerator::AUX_FMIN);
     return "casadi_fmin(" + x + ", " + y + ");";
   }
References add_auxiliary(), and AUX_FMIN.
Referenced by casadi::Feasiblesqpmethod::codegen_tr_update().
fmu_helpers()
std::string casadi::CodeGenerator::fmu_helpers (const std::string & modelname) static
Extra doc: https://github.com/casadi/casadi/wiki/L_257
Definition at line 1738 of file code_generator.cpp.
{
     // Process C++ source
     std::stringstream ret;
     std::string line;
     std::istringstream stream(casadi_fmu_str);
     while (std::getline(stream, line)) {
       // Replacements
       if (line.find("MODELNAME") != std::string::npos) {
         line = replace(line, "MODELNAME", modelname);
       }
       // Append to return
       ret << line << "\n";
     }
     return ret.str();
   }
References casadi::replace().
Referenced by casadi::DaeBuilderInternal::generate_wrapper().
from_mex()
std::string casadi::CodeGenerator::from_mex (std::string & arg, const std::string & res, std::size_t res_off, const Sparsity & sp_res, const std::string & w)
Extra doc: https://github.com/casadi/casadi/wiki/L_u4
Definition at line 1725 of file code_generator.cpp.
{
     // Handle offset with recursion
     if (res_off!=0) return from_mex(arg, res+"+"+str(res_off), 0, sp_res, w);
     add_auxiliary(AUX_FROM_MEX);
     std::stringstream s;
     s << "casadi_from_mex(" << arg
       << ", " << res << ", " << sparsity(sp_res) << ", " << w << ");";
     return s.str();
   }
References add_auxiliary(), arg(), AUX_FROM_MEX, res(), sparsity(), and casadi::str().
Referenced by casadi::FunctionInternal::codegen_meta().
generate()
std::string casadi::CodeGenerator::generate (const std::string & prefix = "")
The "prefix" argument will be prepended to the generated files and may be a directory or a file prefix. returns the filename
Extra doc: https://github.com/casadi/casadi/wiki/L_rv
Definition at line 441 of file code_generator.cpp.
{
     // Throw an error if the prefix contains the filename, since since syntax
     // has changed
     casadi_assert(prefix.find(this->name + this->suffix)==std::string::npos,
        "The signature of CodeGenerator::generate has changed. "
        "Instead of providing the filename, only provide the prefix.");
     // Create c file
     std::ofstream s;
     std::string fullname = prefix + this->name + this->suffix;
     file_open(s, fullname, this->cpp);
     // Dump code to file
     dump(s);
     // Mex entry point
     if (this->mex) generate_mex(s);
     // Main entry point
     if (this->main) generate_main(s);
     // Finalize file
     file_close(s, this->cpp);
     // Generate s-function
     if (this->with_sfunction) {
       for (unsigned ii=0; ii<this->added_sfunctions.size(); ii++) {
         std::string sfunction_code = this->added_sfunctions.at(ii);
         std::string sfunction_name = this->exposed_fname.at(ii);
         generate_sfunction(sfunction_name, sfunction_code);
       }
     }
     // Generate header
     if (this->with_header) {
       // Create a header file
       file_open(s, prefix + this->name + ".h", this->cpp);
       // Define the casadi_real type (typically double)
       generate_casadi_real(s);
       // Define the casadi_int type
       generate_casadi_int(s);
       // Generate export symbol macros
       if (this->with_import) generate_import_symbol(s);
       // Add declarations
       s << this->header.str();
       // Finalize file
       file_close(s, this->cpp);
     }
     return fullname;
   }
References added_sfunctions, cpp, dump(), exposed_fname, file_close(), file_open(), header, main, mex, name, prefix, suffix, with_header, with_import, and with_sfunction.
Referenced by casadi::DaeBuilderInternal::export_fmu(), casadi::FunctionInternal::finalize(), casadi::Function::generate(), casadi::OracleFunction::generate_dependencies(), and casadi::Scpgen::init().
get_constant() [1/4]
casadi_int casadi::CodeGenerator::get_constant (const std::vector< casadi_int > & v, bool allow_adding = false)
Extra doc: https://github.com/casadi/casadi/wiki/L_ry
Definition at line 1143 of file code_generator.cpp.
{
     // Hash the vector
     size_t h = hash(v);
     // Try to locate it in already added constants
     std::pair<std::multimap<size_t, size_t>::iterator, std::multimap<size_t, size_t>::iterator> eq =
       added_integer_constants_.equal_range(h);
     for (std::multimap<size_t, size_t>::iterator i=eq.first; i!=eq.second; ++i) {
       if (equal(v, integer_constants_[i->second])) return i->second;
     }
     if (allow_adding) {
       // Add to constants
       casadi_int ind = integer_constants_.size();
       integer_constants_.push_back(v);
       added_integer_constants_.insert(std::pair<size_t, size_t>(h, ind));
       return ind;
     } else {
       casadi_error("Constant not found");
       return -1;
     }
   }
References added_integer_constants_, equal(), hash(), and integer_constants_.
get_constant() [2/4]
casadi_int casadi::CodeGenerator::get_constant (const std::vector< char > & v, bool allow_adding = false)
Extra doc: https://github.com/casadi/casadi/wiki/L_27l
Definition at line 1166 of file code_generator.cpp.
{
     // Hash the vector
     size_t h = hash(v);
     // Try to locate it in already added constants
     std::pair<std::multimap<size_t, size_t>::iterator, std::multimap<size_t, size_t>::iterator> eq =
       added_char_constants_.equal_range(h);
     for (std::multimap<size_t, size_t>::iterator i=eq.first; i!=eq.second; ++i) {
       if (equal(v, char_constants_[i->second])) return i->second;
     }
     if (allow_adding) {
       // Add to constants
       casadi_int ind = char_constants_.size();
       char_constants_.push_back(v);
       added_char_constants_.insert(std::pair<size_t, size_t>(h, ind));
       return ind;
     } else {
       casadi_error("Constant not found");
       return -1;
     }
   }
References added_char_constants_, char_constants_, equal(), and hash().
get_constant() [3/4]
casadi_int casadi::CodeGenerator::get_constant (const std::vector< double > & v, bool allow_adding = false)
Extra doc: https://github.com/casadi/casadi/wiki/L_rx
Definition at line 1121 of file code_generator.cpp.
{
     // Hash the vector
     size_t h = hash(v);
     // Try to locate it in already added constants
     auto eq = added_double_constants_.equal_range(h);
     for (auto i=eq.first; i!=eq.second; ++i) {
       if (equal(v, double_constants_[i->second])) return i->second;
     }
     if (allow_adding) {
       // Add to constants
       casadi_int ind = double_constants_.size();
       double_constants_.push_back(v);
       added_double_constants_.insert(std::make_pair(h, ind));
       return ind;
     } else {
       casadi_error("Constant not found");
       return -1;
     }
   }
References added_double_constants_, double_constants_, equal(), and hash().
Referenced by add_sparsity(), constant(), and get_sparsity().
get_constant() [4/4]
casadi_int casadi::CodeGenerator::get_constant (const std::vector< std::string > & v, bool allow_adding = false)
Extra doc: https://github.com/casadi/casadi/wiki/L_27z
Definition at line 1189 of file code_generator.cpp.
{
     // Hash the vector
     size_t h = hash(v);
     // Try to locate it in already added constants
     std::pair<std::multimap<size_t, size_t>::iterator, std::multimap<size_t, size_t>::iterator> eq =
       added_string_constants_.equal_range(h);
     for (std::multimap<size_t, size_t>::iterator i=eq.first; i!=eq.second; ++i) {
       if (equal(v, string_constants_[i->second])) return i->second;
     }
     if (allow_adding) {
       // Add to constants
       casadi_int ind = string_constants_.size();
       string_constants_.push_back(v);
       added_string_constants_.insert(std::pair<size_t, size_t>(h, ind));
       return ind;
     } else {
       casadi_error("Constant not found");
       return -1;
     }
   }
References added_string_constants_, equal(), hash(), and string_constants_.
get_sparsity()
casadi_int casadi::CodeGenerator::get_sparsity (const Sparsity & sp) const
Extra doc: https://github.com/casadi/casadi/wiki/L_rw
Definition at line 1085 of file code_generator.cpp.
{
     return const_cast<CodeGenerator&>(*this).get_constant(sp, false);
   }
References get_constant().
hash() [1/4]
size_t casadi::CodeGenerator::hash (const std::vector< casadi_int > & v) static
Definition at line 1103 of file code_generator.cpp.
{
     size_t seed=0;
     hash_combine(seed, v);
     return seed;
   }
References casadi::hash_combine().
hash() [2/4]
size_t casadi::CodeGenerator::hash (const std::vector< char > & v) static
Definition at line 1109 of file code_generator.cpp.
{
     size_t seed=0;
     hash_combine(seed, v);
     return seed;
   }
References casadi::hash_combine().
hash() [3/4]
size_t casadi::CodeGenerator::hash (const std::vector< double > & v) static
Definition at line 1089 of file code_generator.cpp.
{
     // Calculate a hash value for the vector
     std::size_t seed=0;
     if (!v.empty()) {
       casadi_assert_dev(sizeof(double) % sizeof(size_t)==0);
       const casadi_int int_len = v.size()*(sizeof(double)/sizeof(size_t));
       const size_t* int_v = reinterpret_cast<const size_t*>(&v.front());
       for (size_t i=0; i<int_len; ++i) {
         hash_combine(seed, int_v[i]);
       }
     }
     return seed;
   }
References casadi::hash_combine().
Referenced by get_constant().
hash() [4/4]
size_t casadi::CodeGenerator::hash (const std::vector< std::string > & v) static
Definition at line 1115 of file code_generator.cpp.
{
     size_t seed=0;
     hash_combine(seed, v);
     return seed;
   }
References casadi::hash_combine().
indent()
void casadi::CodeGenerator::indent () inline
Extra doc: https://github.com/casadi/casadi/wiki/L_sg
Definition at line 235 of file code_generator.hpp.
 {current_indent_++;}
Referenced by print_formatted().
init_local()
void casadi::CodeGenerator::init_local (const std::string & name, const std::string & def)
Extra doc: https://github.com/casadi/casadi/wiki/L_sf
Definition at line 2210 of file code_generator.cpp.
{
     auto it = local_default_.find(name);
     if (it!=local_default_.end()) {
       casadi_assert(it->second==def, "Initial value mismatch for " + name);
     }
     local_default_.insert(std::make_pair(name, def));
   }
References local_default_, and name.
Referenced by casadi::FiniteDiff::codegen_body(), casadi::MXFunction::codegen_body(), casadi::DaqpInterface::codegen_body(), casadi::FatropInterface::codegen_body(), casadi::HighsInterface::codegen_body(), casadi::IpoptInterface::codegen_body(), casadi::MadnlpInterface::codegen_body(), casadi::OsqpInterface::codegen_body(), casadi::Feasiblesqpmethod::codegen_body(), casadi::Sqpmethod::codegen_body(), casadi::Nlpsol::codegen_body_exit(), casadi::Feasiblesqpmethod::codegen_feasibility_iterations(), casadi::codegen_local(), and constant_copy().
initializer() [1/4]
std::string casadi::CodeGenerator::initializer (const std::vector< casadi_int > & v)
Definition at line 1799 of file code_generator.cpp.
{
     std::stringstream s;
     s << "{";
     for (casadi_int i=0; i<v.size(); ++i) {
       if (i!=0) s << ", ";
       s << v[i];
     }
     s << "}";
     return s.str();
   }
initializer() [2/4]
std::string casadi::CodeGenerator::initializer (const std::vector< char > & v)
Definition at line 1810 of file code_generator.cpp.
{
     std::stringstream s;
     s << "{";
     for (casadi_int i=0; i<v.size(); ++i) {
       if (i!=0) s << ", ";
       s << size_t(v[i]);
     }
     s << "}";
     return s.str();
   }
initializer() [3/4]
std::string casadi::CodeGenerator::initializer (const std::vector< double > & v)
Extra doc: https://github.com/casadi/casadi/wiki/L_sk
Definition at line 1788 of file code_generator.cpp.
{
     std::stringstream s;
     s << "{";
     for (casadi_int i=0; i<v.size(); ++i) {
       if (i!=0) s << ", ";
       s << constant(v[i]);
     }
     s << "}";
     return s.str();
   }
References constant().
Referenced by print_vector().
initializer() [4/4]
std::string casadi::CodeGenerator::initializer (const std::vector< std::string > & v)
Definition at line 1821 of file code_generator.cpp.
{
     std::stringstream s;
     s << "{";
     for (casadi_int i=0; i<v.size(); ++i) {
       if (i!=0) s << ", ";
       s << "\"" << v[i] << "\"";
     }
     s << "}";
     return s.str();
   }
interpn()
std::string casadi::CodeGenerator::interpn (const std::string & res, casadi_int ndim, const std::string & grid, const std::string & offset, const std::string & values, const std::string & x, const std::string & lookup_mode, casadi_int m, const std::string & iw, const std::string & w)
Extra doc: https://github.com/casadi/casadi/wiki/L_sw
Definition at line 1919 of file code_generator.cpp.
{
     add_auxiliary(AUX_INTERPN);
     std::stringstream s;
     s << "casadi_interpn(" << res << ", " << ndim << ", " << grid << ", "  << offset << ", "
       << values << ", " << x << ", " << lookup_mode << ", " << m << ", " << iw << ", " << w << ");";
     return s.str();
   }
References add_auxiliary(), AUX_INTERPN, and res().
Referenced by casadi::LinearInterpolant::codegen_body().
interpn_grad()
std::string casadi::CodeGenerator::interpn_grad (const std::string & grad, casadi_int ndim, const std::string & grid, const std::string & offset, const std::string & values, const std::string & x, const std::string & lookup_mode, casadi_int m, const std::string & iw, const std::string & w)
Extra doc: https://github.com/casadi/casadi/wiki/L_sx
Definition at line 1932 of file code_generator.cpp.
{
     add_auxiliary(AUX_INTERPN_GRAD);
     std::stringstream s;
     s << "casadi_interpn_grad(" << grad << ", " << ndim << ", " << grid << ", " << offset << ", "
       << values << ", " << x << ", " << lookup_mode << "," << m << ", " << iw << ", " << w << ");";
     return s.str();
   }
References add_auxiliary(), and AUX_INTERPN_GRAD.
Referenced by casadi::LinearInterpolantJac::codegen_body().
lb_eig()
std::string casadi::CodeGenerator::lb_eig (const Sparsity & sp_h, const std::string & h)
Extra doc: https://github.com/casadi/casadi/wiki/L_ti
Definition at line 2477 of file code_generator.cpp.
{
     add_auxiliary(CodeGenerator::AUX_REGULARIZE);
     return "casadi_lb_eig(" + sparsity(sp_h) + ", " + h + ")";
   }
References add_auxiliary(), AUX_REGULARIZE, and sparsity().
ldl()
std::string casadi::CodeGenerator::ldl (const std::string & sp_a, const std::string & a, const std::string & sp_lt, const std::string & lt, const std::string & d, const std::string & p, const std::string & w)
Extra doc: https://github.com/casadi/casadi/wiki/L_t2
Definition at line 2375 of file code_generator.cpp.
{
     add_auxiliary(CodeGenerator::AUX_LDL);
     return "casadi_ldl(" + sp_a + ", " + a + ", " + sp_lt + ", " + lt + ", "
            + d + ", " + p + ", " + w + ");";
   }
References add_auxiliary(), and AUX_LDL.
Referenced by casadi::LinsolLdl::generate().
ldl_solve()
std::string casadi::CodeGenerator::ldl_solve (const std::string & x, casadi_int nrhs, const std::string & sp_lt, const std::string & lt, const std::string & d, const std::string & p, const std::string & w)
Extra doc: https://github.com/casadi/casadi/wiki/L_t3
Definition at line 2384 of file code_generator.cpp.
{
     add_auxiliary(CodeGenerator::AUX_LDL);
     return "casadi_ldl_solve(" + x + ", " + str(nrhs) + ", " + sp_lt + ", "
            + lt + ", " + d + ", " + p + ", " + w + ");";
   }
References add_auxiliary(), AUX_LDL, and casadi::str().
Referenced by casadi::LinsolLdl::generate().
local()
void casadi::CodeGenerator::local (const std::string & name, const std::string & type, const std::string & ref = "")
Extra doc: https://github.com/casadi/casadi/wiki/L_sb
Definition at line 2183 of file code_generator.cpp.
{
     // Check if the variable already exists
     auto it = local_variables_.find(name);
     if (it==local_variables_.end()) {
       // Add it
       local_variables_[name] = std::make_pair(type, ref);
     } else {
       // Consistency check
       casadi_assert(it->second.first==type, "Type mismatch for " + name);
       casadi_assert(it->second.second==ref, "Type mismatch for " + name);
     }
   }
References local_variables_, and name.
Referenced by casadi::FiniteDiff::codegen_body(), casadi::JitFunction::codegen_body(), casadi::Map::codegen_body(), casadi::MapSum::codegen_body(), casadi::Switch::codegen_body(), casadi::DaqpInterface::codegen_body(), casadi::FatropInterface::codegen_body(), casadi::HighsInterface::codegen_body(), casadi::HpipmInterface::codegen_body(), casadi::IpoptInterface::codegen_body(), casadi::MadnlpInterface::codegen_body(), casadi::OsqpInterface::codegen_body(), casadi::FastNewton::codegen_body(), casadi::Feasiblesqpmethod::codegen_body(), casadi::Qrqp::codegen_body(), casadi::Sqpmethod::codegen_body(), casadi::OracleFunction::codegen_body_enter(), casadi::Nlpsol::codegen_body_enter(), casadi::Nlpsol::codegen_body_exit(), casadi::Feasiblesqpmethod::codegen_feasibility_iterations(), casadi::OsqpInterface::codegen_init_mem(), casadi::codegen_local(), casadi::codegen_unpack_block(), constant_copy(), casadi::Convexify::generate(), casadi::BinaryMX< ScX, ScY >::generate(), casadi::Call::generate(), casadi::Find::generate(), casadi::Low::generate(), casadi::Concat::generate(), casadi::Einstein::generate(), casadi::GetNonzerosVector::generate(), casadi::GetNonzerosSlice::generate(), casadi::GetNonzerosSlice2::generate(), casadi::GetNonzerosParamVector::generate(), casadi::GetNonzerosSliceParam::generate(), casadi::GetNonzerosParamSlice::generate(), casadi::GetNonzerosParamParam::generate(), casadi::Monitor::generate(), casadi::DenseMultiplication::generate(), casadi::HorzRepmat::generate(), casadi::HorzRepsum::generate(), casadi::SetNonzerosVector< Add >::generate(), casadi::SetNonzerosSlice< Add >::generate(), casadi::SetNonzerosSlice2< Add >::generate(), casadi::SetNonzerosParamVector< Add >::generate(), casadi::SetNonzerosParamSlice< Add >::generate(), casadi::SetNonzerosSliceParam< Add >::generate(), casadi::SetNonzerosParamParam< Add >::generate(), casadi::LinsolCall< Tr >::generate(), casadi::DenseTranspose::generate(), casadi::UnaryMX::generate(), operator()(), casadi::Conic::qp_codegen_body(), and sx_work().
logsumexp()
std::string casadi::CodeGenerator::logsumexp (const std::string & A, casadi_int n)
\brie LogSumExp
Definition at line 2124 of file code_generator.cpp.
{
     add_auxiliary(AUX_LOGSUMEXP);
     std::stringstream s;
     s << "casadi_logsumexp(" << A << ", " << n << ");";
     return s.str();
   }
References add_auxiliary(), and AUX_LOGSUMEXP.
Referenced by casadi::LogSumExp::generate().
low()
std::string casadi::CodeGenerator::low (const std::string & x, const std::string & grid, casadi_int ng, casadi_int lookup_mode)
Extra doc: https://github.com/casadi/casadi/wiki/L_tl
Definition at line 2496 of file code_generator.cpp.
{
     add_auxiliary(CodeGenerator::AUX_LOW);
     return "casadi_low(" + x + ", " + grid + ", " + str(ng) + ", " + str(lookup_mode) + ");";
   }
References add_auxiliary(), AUX_LOW, and casadi::str().
Referenced by casadi::Low::generate().
lsqr_solve()
std::string casadi::CodeGenerator::lsqr_solve (const std::string & A, const std::string & x, casadi_int nrhs, bool tr, const std::string & sp, const std::string & w)
\brief LSQR solve
Extra doc: https://github.com/casadi/casadi/wiki/L_t1
Definition at line 2367 of file code_generator.cpp.
{
     add_auxiliary(CodeGenerator::AUX_LSQR);
     return "casadi_lsqr_solve(" + A + ", " + x + ", " + str(nrhs) + ", "
            + (tr ? "1" : "0") + ", " + sp + ", " + w + ");";
   }
References add_auxiliary(), AUX_LSQR, and casadi::str().
Referenced by casadi::Lsqr::generate().
masked_norm_inf()
std::string casadi::CodeGenerator::masked_norm_inf (casadi_int n, const std::string & x, const std::string & mask)
Definition at line 2075 of file code_generator.cpp.
{
     add_auxiliary(AUX_MASKED_NORM_INF);
     return "casadi_masked_norm_inf(" + str(n) + ", " + x + ", " + mask + ")";
   }
References add_auxiliary(), AUX_MASKED_NORM_INF, and casadi::str().
Referenced by casadi::Feasiblesqpmethod::codegen_body(), casadi::Feasiblesqpmethod::codegen_feasibility_iterations(), and casadi::Feasiblesqpmethod::codegen_tr_update().
max()
std::string casadi::CodeGenerator::max (const std::string & x, const std::string & y)
Extra doc: https://github.com/casadi/casadi/wiki/L_tc
Definition at line 2429 of file code_generator.cpp.
{
     add_auxiliary(CodeGenerator::AUX_MAX);
     return "casadi_max(" + x + ", " + y + ")";
   }
References add_auxiliary(), and AUX_MAX.
max_viol()
std::string casadi::CodeGenerator::max_viol (casadi_int n, const std::string & x, const std::string & lb, const std::string & ub)
Extra doc: https://github.com/casadi/casadi/wiki/L_tf
Definition at line 2453 of file code_generator.cpp.
{
     add_auxiliary(CodeGenerator::AUX_MAX_VIOL);
     return "casadi_max_viol(" + str(n) + ", " + x+ ", " + lb + ", " + ub + ")";
   }
References add_auxiliary(), AUX_MAX_VIOL, and casadi::str().
Referenced by casadi::Feasiblesqpmethod::codegen_body(), casadi::Sqpmethod::codegen_body(), and casadi::Feasiblesqpmethod::codegen_feasibility_iterations().
mem()
std::string casadi::CodeGenerator::mem (const Function & f)
Extra doc: https://github.com/casadi/casadi/wiki/L_ty
Definition at line 1877 of file code_generator.cpp.
{
     std::string name = f->codegen_name(*this, false);
     std::string mem_array = shorthand(name + "_mem");
     return mem_array+"[mem]";
   }
References casadi::FunctionInternal::codegen_name(), name, and shorthand().
Referenced by operator()().
min()
std::string casadi::CodeGenerator::min (const std::string & x, const std::string & y)
Extra doc: https://github.com/casadi/casadi/wiki/L_td
Definition at line 2435 of file code_generator.cpp.
{
     add_auxiliary(CodeGenerator::AUX_MIN);
     return "casadi_min(" + x + ", " + y + ")";
   }
References add_auxiliary(), and AUX_MIN.
Referenced by clip_max(), and clip_min().
mmax()
std::string casadi::CodeGenerator::mmax (const std::string & x, casadi_int n, bool is_dense)
Extra doc: https://github.com/casadi/casadi/wiki/L_t6
Definition at line 2441 of file code_generator.cpp.
{
     add_auxiliary(CodeGenerator::AUX_MMAX);
     return "casadi_mmax(" + x + ", " + str(n) + ", " + str(casadi_int(is_dense)) + ")";
   }
References add_auxiliary(), AUX_MMAX, and casadi::str().
Referenced by casadi::MMax::generate().
mmin()
std::string casadi::CodeGenerator::mmin (const std::string & x, casadi_int n, bool is_dense)
Extra doc: https://github.com/casadi/casadi/wiki/L_t7
Definition at line 2447 of file code_generator.cpp.
{
     add_auxiliary(CodeGenerator::AUX_MMIN);
     return "casadi_mmin(" + x + ", " + str(n) + ", " + str(casadi_int(is_dense)) + ")";
   }
References add_auxiliary(), AUX_MMIN, and casadi::str().
Referenced by casadi::MMin::generate().
mtimes()
std::string casadi::CodeGenerator::mtimes (const std::string & x, const Sparsity & sp_x, const std::string & y, const Sparsity & sp_y, const std::string & z, const Sparsity & sp_z, const std::string & w, bool tr)
Extra doc: https://github.com/casadi/casadi/wiki/L_sr
Definition at line 2100 of file code_generator.cpp.
{
     add_auxiliary(AUX_MTIMES);
     return "casadi_mtimes(" + x + ", " + sparsity(sp_x) + ", " + y + ", " + sparsity(sp_y) + ", "
       + z + ", " + sparsity(sp_z) + ", " + w + ", " +  (tr ? "1" : "0") + ");";
   }
References add_auxiliary(), AUX_MTIMES, and sparsity().
Referenced by casadi::Multiplication::generate().
mv() [1/2]
std::string casadi::CodeGenerator::mv (const std::string & x, casadi_int nrow_x, casadi_int ncol_x, const std::string & y, const std::string & z, bool tr)
Extra doc: https://github.com/casadi/casadi/wiki/L_so
Definition at line 2093 of file code_generator.cpp.
{
     add_auxiliary(AUX_MV_DENSE);
     return "casadi_mv_dense(" + x + ", " + str(nrow_x) + ", " + str(ncol_x) + ", "
            + y + ", " + z + ", " +  (tr ? "1" : "0") + ");";
   }
References add_auxiliary(), AUX_MV_DENSE, and casadi::str().
mv() [2/2]
std::string casadi::CodeGenerator::mv (const std::string & x, const Sparsity & sp_x, const std::string & y, const std::string & z, bool tr)
Extra doc: https://github.com/casadi/casadi/wiki/L_sn
Definition at line 2086 of file code_generator.cpp.
{
     add_auxiliary(AUX_MV);
     return "casadi_mv(" + x + ", " + sparsity(sp_x) + ", " + y + ", "
            + z + ", " +  (tr ? "1" : "0") + ");";
   }
References add_auxiliary(), AUX_MV, and sparsity().
Referenced by casadi::Feasiblesqpmethod::codegen_body(), casadi::Sqpmethod::codegen_body(), casadi::Feasiblesqpmethod::codegen_feasibility_iterations(), and casadi::Sqpmethod::codegen_solve_elastic_mode().
norm_2()
std::string casadi::CodeGenerator::norm_2 (casadi_int n, const std::string & x)
     Extra doc: https://github.com/casadi/casadi/wiki/L_256
Definition at line 2471 of file code_generator.cpp.
{
     add_auxiliary(CodeGenerator::AUX_NORM_2);
     return "casadi_norm_2(" + str(n) + ", " + x + ")";
   }
References add_auxiliary(), AUX_NORM_2, and casadi::str().
Referenced by casadi::Feasiblesqpmethod::codegen_feasibility_iterations().
norm_inf()
std::string casadi::CodeGenerator::norm_inf (casadi_int n, const std::string & x)
Extra doc: https://github.com/casadi/casadi/wiki/L_te
Definition at line 2465 of file code_generator.cpp.
{
     add_auxiliary(CodeGenerator::AUX_NORM_INF);
     return "casadi_norm_inf(" + str(n) + ", " + x + ")";
   }
References add_auxiliary(), AUX_NORM_INF, and casadi::str().
Referenced by casadi::Feasiblesqpmethod::codegen_body(), casadi::Sqpmethod::codegen_body(), and casadi::Sqpmethod::codegen_calc_gamma_1().
operator()()
std::string casadi::CodeGenerator::operator() (const Function & f, const std::string & arg, const std::string & res, const std::string & iw, const std::string & w, const std::string & failure_ret = "1")
Extra doc: https://github.com/casadi/casadi/wiki/L_s6
Definition at line 1038 of file code_generator.cpp.
{
     std::string name = add_dependency(f);
     bool needs_mem = !f->codegen_mem_type().empty();
     if (needs_mem) {
       std::string mem = "mid";
       local("flag", "int");
       local(mem, "int");
       *this << mem << " = " << name << "_checkout();\n";
       *this << "if (" << mem << "<0) return " << failure_ret << ";\n";
       *this << "flag = " + name + "(" + arg + ", " + res + ", "
               + iw + ", " + w + ", " << mem << ");\n";
       *this << name << "_release(" << mem << ");\n";
       return "flag";
     } else {
       return name + "(" + arg + ", " + res + ", "
               + iw + ", " + w + ", 0)";
     }
   }
References add_dependency(), arg(), casadi::FunctionInternal::codegen_mem_type(), local(), mem(), name, and res().
operator<<() [1/2]
CodeGenerator & casadi::CodeGenerator::operator<< (const std::string & s)
Extra doc: https://github.com/casadi/casadi/wiki/L_s7
Definition at line 2157 of file code_generator.cpp.
{
     // Loop over newline characters
     size_t off=0;
     while (true) {
       size_t pos = s.find('\n', off);
       if (pos==std::string::npos) {
         // No more newline characters
         print_formatted(s.substr(off));
         break;
       } else {
         // Ends with newline
         print_formatted(s.substr(off, pos-off));
         this->buffer << '\n';
         newline_ = true;
         off = pos+1;
       }
     }
     return *this;
   }
References buffer, newline_, and print_formatted().
operator<<() [2/2]
template<typename T > CodeGenerator& casadi::CodeGenerator::operator<< (T s) inline
Extra doc: https://github.com/casadi/casadi/wiki/L_s9
Definition at line 196 of file code_generator.hpp.
{
       std::stringstream ss;
       ss << s;
       return (*this) << ss.str();
     }
print_formatted()
void casadi::CodeGenerator::print_formatted (const std::string & s)
Extra doc: https://github.com/casadi/casadi/wiki/L_s8
Definition at line 2131 of file code_generator.cpp.
{
     // Quick return if empty
     if (s.empty()) return;
     // If new line, add indentation
     if (newline_) {
       casadi_int shift = s.front()=='}' ? -1 : 0;
       casadi_assert_dev(current_indent_+shift>=0);
       this->buffer << std::string(indent_*(current_indent_+shift), ' ');
       newline_ = false;
     }
     // Print to body
     this->buffer << s;
     // Brackets change indentation for next row
     // NOTE(@jaeandersson): Should ignore strings, comments
     for (char c : s) {
       if (c=='{') {
         indent();
       } else if (c=='}') {
         unindent();
       }
     }
   }
References buffer, current_indent_, indent(), indent_, newline_, and unindent().
Referenced by operator<<().
print_op() [1/2]
std::string casadi::CodeGenerator::print_op (casadi_int op, const std::string & a0)
Extra doc: https://github.com/casadi/casadi/wiki/L_u6
Definition at line 962 of file code_generator.cpp.
{
     switch (op) {
       case OP_FABS:
         add_auxiliary(AUX_FABS);
         return "casadi_fabs("+a0+")";
       case OP_SQ:
         add_auxiliary(AUX_SQ);
         return "casadi_sq("+a0+")";
       case OP_SIGN:
         add_auxiliary(AUX_SIGN);
         return "casadi_sign("+a0+")";
       case OP_LOG1P:
         add_auxiliary(AUX_LOG1P);
         return "casadi_log1p("+a0+")";
       case OP_EXPM1:
         add_auxiliary(AUX_EXPM1);
         return "casadi_expm1("+a0+")";
       default:
         return casadi_math<double>::print(op, a0);
     }
   }
References add_auxiliary(), AUX_EXPM1, AUX_FABS, AUX_LOG1P, AUX_SIGN, AUX_SQ, casadi::OP_EXPM1, casadi::OP_FABS, casadi::OP_LOG1P, casadi::OP_SIGN, casadi::OP_SQ, and casadi::casadi_math< T >::print().
Referenced by casadi::SXFunction::codegen_body(), casadi::BinaryMX< ScX, ScY >::generate(), and casadi::UnaryMX::generate().
print_op() [2/2]
std::string casadi::CodeGenerator::print_op (casadi_int op, const std::string & a0, const std::string & a1)
Definition at line 983 of file code_generator.cpp.
{
     switch (op) {
       case OP_FMIN:
         add_auxiliary(AUX_FMIN);
         return "casadi_fmin("+a0+","+a1+")";
       case OP_FMAX:
         add_auxiliary(AUX_FMAX);
         return "casadi_fmax("+a0+","+a1+")";
       case OP_HYPOT:
         add_auxiliary(AUX_HYPOT);
         return "casadi_hypot("+a0+","+a1+")";
       default:
         return casadi_math<double>::print(op, a0, a1);
     }
   }
References add_auxiliary(), AUX_FMAX, AUX_FMIN, AUX_HYPOT, casadi::OP_FMAX, casadi::OP_FMIN, casadi::OP_HYPOT, and casadi::casadi_math< T >::print().
print_vector() [1/4]
void casadi::CodeGenerator::print_vector (std::ostream & s, const std::string & name, const std::vector< casadi_int > & v)
Extra doc: https://github.com/casadi/casadi/wiki/L_tr
Definition at line 942 of file code_generator.cpp.
{
     s << array("static const casadi_int", name, v.size(), initializer(v));
   }
References array(), initializer(), and name.
Referenced by dump().
print_vector() [2/4]
void casadi::CodeGenerator::print_vector (std::ostream & s, const std::string & name, const std::vector< char > & v)
Extra doc: https://github.com/casadi/casadi/wiki/L_27n
Definition at line 947 of file code_generator.cpp.
{
     s << array("static const char", name, v.size(), initializer(v));
   }
References array(), initializer(), and name.
print_vector() [3/4]
void casadi::CodeGenerator::print_vector (std::ostream & s, const std::string & name, const std::vector< double > & v)
Extra doc: https://github.com/casadi/casadi/wiki/L_ts
Definition at line 952 of file code_generator.cpp.
{
     s << array("static const casadi_real", name, v.size(), initializer(v));
   }
References array(), initializer(), and name.
print_vector() [4/4]
void casadi::CodeGenerator::print_vector (std::ostream & s, const std::string & name, const std::vector< std::string > & v)
Extra doc: https://github.com/casadi/casadi/wiki/L_281
Definition at line 957 of file code_generator.cpp.
{
     s << array("static const char*", name, v.size(), initializer(v));
   }
References array(), initializer(), and name.
printf() [1/4]
std::string casadi::CodeGenerator::printf (const std::string & str, const std::string & arg1)
Definition at line 2022 of file code_generator.cpp.
{
     std::vector<std::string> arg;
     arg.push_back(arg1);
     return printf(str, arg);
   }
References arg(), printf(), and casadi::str().
printf() [2/4]
std::string casadi::CodeGenerator::printf (const std::string & str, const std::string & arg1, const std::string & arg2)
Definition at line 2028 of file code_generator.cpp.
{
     std::vector<std::string> arg;
     arg.push_back(arg1);
     arg.push_back(arg2);
     return printf(str, arg);
   }
References arg(), printf(), and casadi::str().
printf() [3/4]
std::string casadi::CodeGenerator::printf (const std::string & str, const std::string & arg1, const std::string & arg2, const std::string & arg3)
Definition at line 2036 of file code_generator.cpp.
{
     std::vector<std::string> arg;
     arg.push_back(arg1);
     arg.push_back(arg2);
     arg.push_back(arg3);
     return printf(str, arg);
   }
References arg(), printf(), and casadi::str().
printf() [4/4]
std::string casadi::CodeGenerator::printf (const std::string & str, const std::vector< std::string > & arg = std::vector<std::string>())
Extra doc: https://github.com/casadi/casadi/wiki/L_u5
Definition at line 2013 of file code_generator.cpp.
{
     add_auxiliary(AUX_PRINTF);
     std::stringstream s;
     s << "CASADI_PRINTF(\"" << str << "\"";
     for (casadi_int i=0; i<arg.size(); ++i) s << ", " << arg[i];
     s << ");";
     return s.str();
   }
References add_auxiliary(), arg(), AUX_PRINTF, and casadi::str().
Referenced by casadi::Feasiblesqpmethod::codegen_body(), casadi::Qrqp::codegen_body(), casadi::FunctionInternal::codegen_meta(), casadi::Monitor::generate(), and printf().
project()
std::string casadi::CodeGenerator::project (const std::string & arg, const Sparsity & sp_arg, const std::string & res, const Sparsity & sp_res, const std::string & w)
Extra doc: https://github.com/casadi/casadi/wiki/L_tz
Definition at line 1966 of file code_generator.cpp.
{
     // If sparsity match, simple copy
     if (sp_arg==sp_res) return copy(arg, sp_arg.nnz(), res);
     // Create call
     add_auxiliary(AUX_PROJECT);
     std::stringstream s;
     s << "casadi_project(" << arg << ", " << sparsity(sp_arg) << ", " << res << ", "
       << sparsity(sp_res) << ", " << w << ");";
     return s.str();
   }
References add_auxiliary(), arg(), AUX_PROJECT, copy(), casadi::Sparsity::nnz(), res(), and sparsity().
Referenced by casadi::Switch::codegen_body(), and casadi::Project::generate().
qr()
std::string casadi::CodeGenerator::qr (const std::string & sp, const std::string & A, const std::string & w, const std::string & sp_v, const std::string & v, const std::string & sp_r, const std::string & r, const std::string & beta, const std::string & prinv, const std::string & pc)
Extra doc: https://github.com/casadi/casadi/wiki/L_sz
Definition at line 2344 of file code_generator.cpp.
{
     add_auxiliary(CodeGenerator::AUX_QR);
     return "casadi_qr(" + sp + ", " + A + ", " + w + ", "
            + sp_v + ", " + v + ", " + sp_r + ", " + r + ", "
            + beta + ", " + prinv + ", " + pc + ");";
   }
References add_auxiliary(), and AUX_QR.
Referenced by casadi::LinsolQr::generate().
qr_solve()
std::string casadi::CodeGenerator::qr_solve (const std::string & x, casadi_int nrhs, bool tr, const std::string & sp_v, const std::string & v, const std::string & sp_r, const std::string & r, const std::string & beta, const std::string & prinv, const std::string & pc, const std::string & w)
Extra doc: https://github.com/casadi/casadi/wiki/L_t0
Definition at line 2355 of file code_generator.cpp.
{
     add_auxiliary(CodeGenerator::AUX_QR);
     return "casadi_qr_solve(" + x + ", " + str(nrhs) + ", " + (tr ? "1" : "0") + ", "
            + sp_v + ", " + v + ", " + sp_r + ", " + r + ", "
            + beta + ", " + prinv + ", " + pc + ", " + w + ");";
   }
References add_auxiliary(), AUX_QR, and casadi::str().
Referenced by casadi::LinsolQr::generate().
rank1()
std::string casadi::CodeGenerator::rank1 (const std::string & A, const Sparsity & sp_A, const std::string & alpha, const std::string & x, const std::string & y)
Extra doc: https://github.com/casadi/casadi/wiki/L_sv
Definition at line 1909 of file code_generator.cpp.
{
     add_auxiliary(AUX_RANK1);
     std::stringstream s;
     s << "casadi_rank1(" << A << ", " << sparsity(sp_A) << ", "
       << alpha << ", " << x << ", " << y << ");";
     return s.str();
   }
References add_auxiliary(), AUX_RANK1, and sparsity().
Referenced by casadi::Rank1::generate().
regularize()
std::string casadi::CodeGenerator::regularize (const Sparsity & sp_h, const std::string & h, const std::string & reg)
Extra doc: https://github.com/casadi/casadi/wiki/L_tj
Definition at line 2483 of file code_generator.cpp.
{
     add_auxiliary(CodeGenerator::AUX_REGULARIZE);
     return "casadi_regularize(" + sparsity(sp_h) + ", " + h + ", " + reg + ");";
   }
References add_auxiliary(), AUX_REGULARIZE, and sparsity().
res()
std::string casadi::CodeGenerator::res (casadi_int i) const
Extra doc: https://github.com/casadi/casadi/wiki/L_tx
Definition at line 1873 of file code_generator.cpp.
{
     return "res[" + str(i) + "]";
   }
References casadi::str().
Referenced by clear(), casadi::FiniteDiff::codegen_body(), casadi::OmpMap::codegen_body(), casadi::Switch::codegen_body(), casadi::SXFunction::codegen_body(), casadi::OsqpInterface::codegen_body(), casadi::FastNewton::codegen_body(), casadi::Feasiblesqpmethod::codegen_body(), casadi::Qrqp::codegen_body(), casadi::FunctionInternal::codegen_meta(), copy(), copy_check(), copy_default(), densify(), fill(), from_mex(), casadi::Output::generate(), interpn(), operator()(), project(), sparsify(), and tri_project().
rom_double()
std::string casadi::CodeGenerator::rom_double (const void * id) const
Extra doc: https://github.com/casadi/casadi/wiki/L_s3
Definition at line 765 of file code_generator.cpp.
{
     auto it = file_scope_double_.find(id);
     casadi_assert(it!=file_scope_double_.end(), "Not defined.");
     casadi_int size = std::distance(file_scope_double_.begin(), it);
     return "casadi_rd" + str(size);
   }
References file_scope_double_, and casadi::str().
Referenced by casadi::ConstantFile::codegen_incref(), and casadi::ConstantFile::generate().
rom_integer()
std::string casadi::CodeGenerator::rom_integer (const void * id) const
Extra doc: https://github.com/casadi/casadi/wiki/L_s5
Definition at line 779 of file code_generator.cpp.
{
     auto it = file_scope_double_.find(id);
     casadi_assert(it!=file_scope_double_.end(), "Not defined.");
     casadi_int size = std::distance(file_scope_double_.begin(), it);
     return "casadi_ri" + str(size);
   }
References file_scope_double_, and casadi::str().
sanitize_source()
std::string casadi::CodeGenerator::sanitize_source (const std::string & src, const std::vector< std::string > & inst, bool add_shorthand = true)
Extra doc: https://github.com/casadi/casadi/wiki/L_sl
Definition at line 2218 of file code_generator.cpp.
{
     // Create suffix if templates type are not all "casadi_real"
     std::string suffix;
     for (const std::string& s : inst) {
       if (s!="casadi_real") {
         for (const std::string& s : inst) suffix += "_" + s;
         break;
       }
     }
     // Construct map of name replacements
     std::vector<std::pair<std::string, std::string> > rep;
     for (casadi_int i=0; i<inst.size(); ++i) {
       rep.push_back(std::make_pair("T" + str(i+1), inst[i]));
     }
     // Return object
     std::stringstream ret;
     // Process C++ source
     std::string line;
     std::istringstream stream(src);
     while (std::getline(stream, line)) {
       size_t n1, n2;
       // C++ template declarations are ignored
       if (line.find("template")==0) continue;
       // Macro definitions are ignored
       if (line.find("#define")==0) continue;
       if (line.find("#undef")==0) continue;
       // Inline declaration
       if (line == "inline") continue;
       // If line starts with "// SYMBOL", add shorthand
       if (line.find("// SYMBOL") != std::string::npos) {
         n1 = line.find("\"");
         n2 = line.find("\"", n1+1);
         std::string sym = line.substr(n1+1, n2-n1-1);
         if (add_shorthand) shorthand(sym + suffix);
         if (!suffix.empty()) {
           rep.push_back(std::make_pair(sym, sym + suffix));
         }
         continue;
       }
       // If line starts with "// C-REPLACE", add to list of replacements
       if (line.find("// C-REPLACE") != std::string::npos) {
         // Get C++ string
         n1 = line.find("\"");
         n2 = line.find("\"", n1+1);
         std::string key = line.substr(n1+1, n2-n1-1);
         // Get C string
         n1 = line.find("\"", n2+1);
         n2 = line.find("\"", n1+1);
         std::string sub = line.substr(n1+1, n2-n1-1);
         // Add to replacements
         rep.push_back(std::make_pair(key, sub));
         continue;
       }
       // If line starts with "// C-VERBOSE", skip the next line
       if (!verbose_runtime && line.find("// C-VERBOSE") != std::string::npos) {
         // Ignore next line
         std::getline(stream, line);
         continue;
       }
       // Ignore other C++ style comment
       if ((n1 = line.find("//")) != std::string::npos) line.erase(n1);
       // Remove trailing spaces
       if ((n1 = line.find_last_not_of(' ')) != std::string::npos) {
         line.erase(n1 + 1);
       } else {
         continue;
       }
       // Perform string replacements
       for (auto&& it = rep.rbegin(); it!=rep.rend(); ++it) {
         line = replace(line, it->first, it->second);
       }
       // Append to return
       ret << line << "\n";
     }
     // Trailing newline
     ret << "\n";
     return ret.str();
   }
References casadi::replace(), shorthand(), casadi::str(), suffix, and verbose_runtime.
Referenced by add_auxiliary(), casadi::DaqpInterface::codegen_body(), casadi::FatropInterface::codegen_body(), casadi::HighsInterface::codegen_body(), casadi::HpipmInterface::codegen_body(), casadi::IpoptInterface::codegen_body(), and casadi::MadnlpInterface::codegen_body().
scal()
std::string casadi::CodeGenerator::scal (casadi_int n, const std::string & alpha, const std::string & x)
Extra doc: https://github.com/casadi/casadi/wiki/L_sq
Definition at line 2081 of file code_generator.cpp.
{
     add_auxiliary(AUX_SCAL);
     return "casadi_scal(" + str(n) + ", " + alpha + ", " + x + ");";
   }
References add_auxiliary(), AUX_SCAL, and casadi::str().
Referenced by casadi::Sqpmethod::codegen_body(), and casadi::Nlpsol::codegen_body_exit().
scope_enter()
void casadi::CodeGenerator::scope_enter ()
Extra doc: https://github.com/casadi/casadi/wiki/L_sc
Definition at line 185 of file code_generator.cpp.
{
     local_variables_.clear();
     local_default_.clear();
   }
References local_default_, and local_variables_.
Referenced by add_dependency(), casadi::FunctionInternal::codegen(), and casadi::IpoptInterface::codegen_declarations().
scope_exit()
void casadi::CodeGenerator::scope_exit ()
Extra doc: https://github.com/casadi/casadi/wiki/L_sd
Definition at line 190 of file code_generator.cpp.
{
     // Order local variables
     std::map<std::string, std::set<std::pair<std::string, std::string>>> local_variables_by_type;
     for (auto&& e : local_variables_) {
       local_variables_by_type[e.second.first].insert(std::make_pair(e.first, e.second.second));
     }
     // Codegen local variables
     for (auto&& e : local_variables_by_type) {
       body << "  " << e.first;
       for (auto it=e.second.begin(); it!=e.second.end(); ++it) {
         body << (it==e.second.begin() ? " " : ", ") << it->second << it->first;
         // Insert definition, if any
         auto k=local_default_.find(it->first);
         if (k!=local_default_.end()) body << "=" << k->second;
       }
       body << ";\n";
     }
   }
References body, local_default_, and local_variables_.
Referenced by add_dependency(), casadi::FunctionInternal::codegen(), and casadi::IpoptInterface::codegen_declarations().
setup_callback()
void casadi::CodeGenerator::setup_callback (const std::string & s, const Function & f)
Extra doc: https://github.com/casadi/casadi/wiki/L_27s
Definition at line 1021 of file code_generator.cpp.
{
     std::string name = add_dependency(f);
     bool needs_mem = !f->codegen_mem_type().empty();
     if (needs_mem) {
       *this << s << ".checkout = " << name << "_checkout;\n";
     } else {
       *this << s << ".checkout = 0;\n";
     }
     *this << s << ".eval = " << name << ";\n";
     if (needs_mem) {
       *this << s << ".release = " << name << "_release;\n";
     } else {
       *this << s << ".release = 0;\n";
     }
   }
References add_dependency(), casadi::FunctionInternal::codegen_mem_type(), and name.
Referenced by casadi::FatropInterface::set_fatrop_prob(), and casadi::MadnlpInterface::set_madnlp_prob().
shorthand() [1/2]
std::string casadi::CodeGenerator::shorthand (const std::string & name) const
Definition at line 1064 of file code_generator.cpp.
{
     casadi_assert(added_shorthands_.count(name), "No such macro: " + name);
     return "casadi_" + name;
   }
References added_shorthands_, and name.
Referenced by add_auxiliary(), add_dependency(), casadi::FunctionInternal::codegen_alloc_mem(), casadi::Nlpsol::codegen_body_enter(), casadi::FunctionInternal::codegen_checkout(), casadi::Nlpsol::codegen_declarations(), casadi::IpoptInterface::codegen_declarations(), casadi::FunctionInternal::codegen_mem(), casadi::FunctionInternal::codegen_release(), constant(), define_rom_double(), define_rom_integer(), mem(), sanitize_source(), casadi::IpoptInterface::set_ipopt_prob(), and sparsity().
shorthand() [2/2]
std::string casadi::CodeGenerator::shorthand (const std::string & name, bool allow_adding = true)
Definition at line 1069 of file code_generator.cpp.
{
     bool added = added_shorthands_.insert(name).second;
     if (!allow_adding) {
       casadi_assert(added, "Duplicate macro: " + name);
     }
     return "casadi_" + name;
   }
References added_shorthands_, and name.
sparsify()
std::string casadi::CodeGenerator::sparsify (const std::string & arg, const std::string & res, const Sparsity & sp_res, bool tr = false)
Extra doc: https://github.com/casadi/casadi/wiki/L_u2
Definition at line 2003 of file code_generator.cpp.
{
     // Create call
     add_auxiliary(AUX_SPARSIFY);
     std::stringstream s;
     s << "casadi_sparsify(" << arg << ", " << res << ", "
       << sparsity(sp_res) << ", " << (tr ? 1 : 0) << ");";
     return s.str();
   }
References add_auxiliary(), arg(), AUX_SPARSIFY, res(), and sparsity().
Referenced by casadi::Sparsify::generate().
sparsity()
std::string casadi::CodeGenerator::sparsity (const Sparsity & sp)
Definition at line 1081 of file code_generator.cpp.
{
     return shorthand("s" + str(add_sparsity(sp)));
   }
References add_sparsity(), shorthand(), and casadi::str().
Referenced by add_io_sparsities(), bilin(), casadi::FastNewton::codegen_body(), casadi::Feasiblesqpmethod::codegen_body(), casadi::Qrqp::codegen_body(), casadi::Sqpmethod::codegen_body(), densify(), from_mex(), casadi::Convexify::generate(), casadi::LinsolLdl::generate(), casadi::LinsolQr::generate(), casadi::Lsqr::generate(), casadi::Find::generate(), lb_eig(), mtimes(), mv(), project(), casadi::Conic::qp_codegen_body(), rank1(), regularize(), casadi::FatropInterface::set_fatrop_prob(), casadi::HpipmInterface::set_hpipm_prob(), casadi::IpoptInterface::set_ipopt_prob(), casadi::MadnlpInterface::set_madnlp_prob(), sparsify(), to_mex(), trans(), tri_project(), trilsolve(), and triusolve().
sum_viol()
std::string casadi::CodeGenerator::sum_viol (casadi_int n, const std::string & x, const std::string & lb, const std::string & ub)
Extra doc: https://github.com/casadi/casadi/wiki/L_tg
Definition at line 2459 of file code_generator.cpp.
{
     add_auxiliary(CodeGenerator::AUX_SUM_VIOL);
     return "casadi_sum_viol(" + str(n) + ", " + x+ ", " + lb + ", " + ub + ")";
   }
References add_auxiliary(), AUX_SUM_VIOL, and casadi::str().
Referenced by casadi::Sqpmethod::codegen_body().
sx_work()
std::string casadi::CodeGenerator::sx_work (casadi_int i)
Extra doc: https://github.com/casadi/casadi/wiki/L_se
Definition at line 2197 of file code_generator.cpp.
{
     if (avoid_stack_) {
       return "w[" + str(i) + "]";
     } else {
       std::string name = "a"+str(i);
       // Make sure work vector element has been declared
       local(name, "casadi_real");
       return name;
     }
   }
References avoid_stack_, local(), name, and casadi::str().
Referenced by casadi::SXFunction::codegen_body().
sz_work()
void casadi::CodeGenerator::sz_work (size_t & sz_arg, size_t & sz_res, size_t & sz_iw, size_t & sz_w) const
Extra doc: https://github.com/casadi/casadi/wiki/L_258
Definition at line 2524 of file code_generator.cpp.
{
     sz_arg = sz_res = sz_iw = sz_w = 0;
     for (auto&& f : added_functions_) {
       sz_arg = std::max(sz_arg, f.f.sz_arg());
       sz_res = std::max(sz_res, f.f.sz_res());
       sz_iw = std::max(sz_iw, f.f.sz_iw());
       sz_w = std::max(sz_w, f.f.sz_w());
     }
   }
References added_functions_.
Referenced by casadi::DaeBuilderInternal::generate_wrapper().
to_mex()
std::string casadi::CodeGenerator::to_mex (const Sparsity & sp, const std::string & arg)
Extra doc: https://github.com/casadi/casadi/wiki/L_u3
Definition at line 1718 of file code_generator.cpp.
{
     add_auxiliary(AUX_TO_MEX);
     std::stringstream s;
     s << "casadi_to_mex(" << sparsity(sp) << ", " << arg << ");";
     return s.str();
   }
References add_auxiliary(), arg(), AUX_TO_MEX, and sparsity().
Referenced by casadi::FunctionInternal::codegen_meta().
trans()
std::string casadi::CodeGenerator::trans (const std::string & x, const Sparsity & sp_x, const std::string & y, const Sparsity & sp_y, const std::string & iw)
Extra doc: https://github.com/casadi/casadi/wiki/L_sy
Definition at line 1944 of file code_generator.cpp.
{
     add_auxiliary(CodeGenerator::AUX_TRANS);
     return "casadi_trans(" + x + "," + sparsity(sp_x) + ", "
             + y + ", " + sparsity(sp_y) + ", " + iw + ")";
   }
References add_auxiliary(), AUX_TRANS, and sparsity().
Referenced by casadi::Transpose::generate().
tri_project()
std::string casadi::CodeGenerator::tri_project (const std::string & arg, const Sparsity & sp_arg, const std::string & res, bool lower)
Extra doc: https://github.com/casadi/casadi/wiki/L_u0
Definition at line 1981 of file code_generator.cpp.
{
     // Create call
     add_auxiliary(AUX_TRI_PROJECT);
     std::stringstream s;
     s << "casadi_tri_project(" << arg << ", " << sparsity(sp_arg) << ", ";
     s << res  << ", " << (lower ? 1: 0) << ");";
     return s.str();
   }
References add_auxiliary(), arg(), AUX_TRI_PROJECT, res(), and sparsity().
Referenced by casadi::OsqpInterface::codegen_body().
trilsolve()
std::string casadi::CodeGenerator::trilsolve (const Sparsity & sp_x, const std::string & x, const std::string & y, bool tr, bool unity, casadi_int nrhs)
Extra doc: https://github.com/casadi/casadi/wiki/L_ss
Definition at line 2109 of file code_generator.cpp.
{
     add_auxiliary(AUX_TRILSOLVE);
     return "casadi_trilsolve(" + sparsity(sp_x) + ", " + x + ", " + y + ", " + str(tr) + ", "
         + str(unity) + ", " + str(nrhs) + ");";
   }
References add_auxiliary(), AUX_TRILSOLVE, sparsity(), and casadi::str().
Referenced by casadi::TrilSolve< Tr >::generate(), and casadi::TrilSolveUnity< Tr >::generate().
triusolve()
std::string casadi::CodeGenerator::triusolve (const Sparsity & sp_x, const std::string & x, const std::string & y, bool tr, bool unity, casadi_int nrhs)
Extra doc: https://github.com/casadi/casadi/wiki/L_st
Definition at line 2116 of file code_generator.cpp.
{
     add_auxiliary(AUX_TRIUSOLVE);
     return "casadi_triusolve(" + sparsity(sp_x) + ", " + x + ", " + y + ", " + str(tr) + ", "
         + str(unity) + ", " + str(nrhs) + ");";
   }
References add_auxiliary(), AUX_TRIUSOLVE, sparsity(), and casadi::str().
Referenced by casadi::TriuSolve< Tr >::generate(), and casadi::TriuSolveUnity< Tr >::generate().
unindent()
void casadi::CodeGenerator::unindent () inline
Extra doc: https://github.com/casadi/casadi/wiki/L_sh
Definition at line 240 of file code_generator.hpp.
 {current_indent_--;}
Referenced by print_formatted().
vector_fmax()
std::string casadi::CodeGenerator::vector_fmax (casadi_int n, const std::string & x, const std::string & y, const std::string & z)
Definition at line 2063 of file code_generator.cpp.
{
     add_auxiliary(AUX_VECTOR_FMAX);
     return "casadi_vector_fmax(" + str(n) + ", " + x + ", " + y + ", " + z + ");";
   }
References add_auxiliary(), AUX_VECTOR_FMAX, and casadi::str().
Referenced by casadi::Feasiblesqpmethod::codegen_feasibility_iterations().
vector_fmin()
std::string casadi::CodeGenerator::vector_fmin (casadi_int n, const std::string & x, const std::string & y, const std::string & z)
Definition at line 2069 of file code_generator.cpp.
{
     add_auxiliary(AUX_VECTOR_FMIN);
     return "casadi_vector_fmin(" + str(n) + ", " + x + ", " + y + ", " + z + ");";
   }
References add_auxiliary(), AUX_VECTOR_FMIN, and casadi::str().
Referenced by casadi::Feasiblesqpmethod::codegen_feasibility_iterations().
vfmax() [1/2]
std::string casadi::CodeGenerator::vfmax (const std::string & x, casadi_int n, const std::string & y)
Extra doc: https://github.com/casadi/casadi/wiki/L_t8
Definition at line 2405 of file code_generator.cpp.
{
     add_auxiliary(CodeGenerator::AUX_VFMAX);
     return "casadi_vfmax(" + x + ", " + str(n) + ", " + y + ");";
   }
References add_auxiliary(), AUX_VFMAX, and casadi::str().
vfmax() [2/2]
std::string casadi::CodeGenerator::vfmax (const std::string & x, const std::string & n, const std::string & y)
Extra doc: https://github.com/casadi/casadi/wiki/L_ta
Definition at line 2417 of file code_generator.cpp.
{
     add_auxiliary(CodeGenerator::AUX_VFMAX);
     return "casadi_vfmax(" + x + ", " + n + ", " + y + ");";
   }
References add_auxiliary(), and AUX_VFMAX.
vfmin() [1/2]
std::string casadi::CodeGenerator::vfmin (const std::string & x, casadi_int n, const std::string & y)
Extra doc: https://github.com/casadi/casadi/wiki/L_t9
Definition at line 2411 of file code_generator.cpp.
{
     add_auxiliary(CodeGenerator::AUX_VFMIN);
     return "casadi_vfmin(" + x + ", " + str(n) + ", " + y + ");";
   }
References add_auxiliary(), AUX_VFMIN, and casadi::str().
vfmin() [2/2]
std::string casadi::CodeGenerator::vfmin (const std::string & x, const std::string & n, const std::string & y)
Extra doc: https://github.com/casadi/casadi/wiki/L_tb
Definition at line 2423 of file code_generator.cpp.
{
     add_auxiliary(CodeGenerator::AUX_VFMIN);
     return "casadi_vfmin(" + x + ", " + n + ", " + y + ");";
   }
References add_auxiliary(), and AUX_VFMIN.
work()
std::string casadi::CodeGenerator::work (casadi_int n, casadi_int sz) const
Get work vector name from index
Definition at line 910 of file code_generator.cpp.
{
     if (n<0 || sz==0) {
       return "0";
     } else if (sz==1 && !this->codegen_scalars) {
       return "(&w" + str(n) + ")";
     } else {
       return "w" + str(n);
     }
   }
References codegen_scalars, and casadi::str().
Referenced by casadi::BSplineParametric::generate(), casadi::Assertion::generate(), casadi::Bilin::generate(), casadi::BinaryMX< ScX, ScY >::generate(), casadi::BSplineCommon::generate(), casadi::Call::generate(), casadi::Find::generate(), casadi::Low::generate(), casadi::Concat::generate(), casadi::ConstantDM::generate(), casadi::ConstantFile::generate(), casadi::Constant< Value >::generate(), casadi::Convexify::generate(), casadi::Dot::generate(), casadi::Einstein::generate(), casadi::GetNonzerosVector::generate(), casadi::GetNonzerosSlice::generate(), casadi::GetNonzerosSlice2::generate(), casadi::GetNonzerosParamVector::generate(), casadi::GetNonzerosSliceParam::generate(), casadi::GetNonzerosParamSlice::generate(), casadi::GetNonzerosParamParam::generate(), casadi::Input::generate(), casadi::Output::generate(), casadi::LogSumExp::generate(), casadi::MMin::generate(), casadi::MMax::generate(), casadi::Monitor::generate(), casadi::Multiplication::generate(), casadi::DenseMultiplication::generate(), casadi::NormF::generate(), casadi::Project::generate(), casadi::Densify::generate(), casadi::Sparsify::generate(), casadi::Rank1::generate(), casadi::HorzRepmat::generate(), casadi::HorzRepsum::generate(), casadi::Reshape::generate(), casadi::SetNonzerosVector< Add >::generate(), casadi::SetNonzerosSlice< Add >::generate(), casadi::SetNonzerosSlice2< Add >::generate(), casadi::SetNonzerosParam< Add >::generate(), casadi::SetNonzerosParamVector< Add >::generate(), casadi::SetNonzerosParamSlice< Add >::generate(), casadi::SetNonzerosSliceParam< Add >::generate(), casadi::SetNonzerosParamParam< Add >::generate(), casadi::LinsolCall< Tr >::generate(), casadi::TriuSolve< Tr >::generate(), casadi::TrilSolve< Tr >::generate(), casadi::TriuSolveUnity< Tr >::generate(), casadi::TrilSolveUnity< Tr >::generate(), casadi::SparsityCast::generate(), casadi::Split::generate(), casadi::Transpose::generate(), casadi::DenseTranspose::generate(), and casadi::UnaryMX::generate().
workel()
std::string casadi::CodeGenerator::workel (casadi_int n) const
Get work vector element from index
Definition at line 920 of file code_generator.cpp.
{
     if (n<0) return "0";
     std::stringstream s;
     if (this->codegen_scalars) s << "*";
     s << "w" << n;
     return s.str();
   }
References codegen_scalars.
Referenced by casadi::Assertion::generate(), casadi::Bilin::generate(), casadi::BinaryMX< ScX, ScY >::generate(), casadi::Find::generate(), casadi::Concat::generate(), casadi::Constant< Value >::generate(), casadi::Dot::generate(), casadi::Input::generate(), casadi::Output::generate(), casadi::LogSumExp::generate(), casadi::MMin::generate(), casadi::MMax::generate(), casadi::Monitor::generate(), casadi::NormF::generate(), casadi::Rank1::generate(), casadi::Split::generate(), and casadi::UnaryMX::generate().
wrapper()
std::string casadi::CodeGenerator::wrapper (const Function & base, const std::string & name)
Definition at line 210 of file code_generator.cpp.
{
     FunctionInternal* f = base.get();
     std::map<FunctionInternal*, casadi_int>& funs = added_wrappers_[name];
     auto it = funs.find(f);
     if (it==funs.end()) {
       casadi_int n = funs.size();
       funs[f] = n;
       return name + str(n);
     } else {
       return name + str(it->second);
     }
   }
References added_wrappers_, casadi::Function::get(), name, and casadi::str().
Referenced by casadi::Nlpsol::codegen_body_enter(), casadi::Nlpsol::codegen_declarations(), casadi::IpoptInterface::codegen_declarations(), and casadi::IpoptInterface::set_ipopt_prob().
Member Data Documentation
added_auxiliaries_
std::multimap<Auxiliary, std::vector<std::string> > casadi::CodeGenerator::added_auxiliaries_
Definition at line 920 of file code_generator.hpp.
Referenced by add_auxiliary().
added_char_constants_
std::multimap<size_t, size_t> casadi::CodeGenerator::added_char_constants_
Definition at line 923 of file code_generator.hpp.
Referenced by get_constant().
added_double_constants_
std::multimap<size_t, size_t> casadi::CodeGenerator::added_double_constants_
Definition at line 921 of file code_generator.hpp.
Referenced by get_constant().
added_externals_
std::set<std::string> casadi::CodeGenerator::added_externals_
Definition at line 918 of file code_generator.hpp.
Referenced by add_external(), and dump().
added_functions_
std::vector<FunctionMeta> casadi::CodeGenerator::added_functions_
Definition at line 937 of file code_generator.hpp.
Referenced by add_dependency(), casadi::FunctionInternal::codegen_name(), and sz_work().
added_includes_
std::set<std::string> casadi::CodeGenerator::added_includes_
Definition at line 917 of file code_generator.hpp.
Referenced by add_include().
added_integer_constants_
std::multimap<size_t, size_t> casadi::CodeGenerator::added_integer_constants_
Definition at line 922 of file code_generator.hpp.
Referenced by get_constant().
added_sfunctions
std::vector<std::string> casadi::CodeGenerator::added_sfunctions
Definition at line 854 of file code_generator.hpp.
Referenced by add(), and generate().
added_shorthands_
std::set<std::string> casadi::CodeGenerator::added_shorthands_
Definition at line 919 of file code_generator.hpp.
Referenced by dump(), and shorthand().
added_string_constants_
std::multimap<size_t, size_t> casadi::CodeGenerator::added_string_constants_
Definition at line 924 of file code_generator.hpp.
Referenced by get_constant().
added_wrappers_
std::map<std::string, std::map<FunctionInternal*, casadi_int> > casadi::CodeGenerator::added_wrappers_
Definition at line 940 of file code_generator.hpp.
Referenced by wrapper().
auxiliaries
std::stringstream casadi::CodeGenerator::auxiliaries
Definition at line 898 of file code_generator.hpp.
Referenced by add_auxiliary(), casadi::DaqpInterface::codegen_body(), casadi::FatropInterface::codegen_body(), casadi::HighsInterface::codegen_body(), casadi::HpipmInterface::codegen_body(), casadi::IpoptInterface::codegen_body(), casadi::MadnlpInterface::codegen_body(), casadi::FunctionInternal::codegen_checkout(), and dump().
avoid_stack_
bool casadi::CodeGenerator::avoid_stack_
Definition at line 875 of file code_generator.hpp.
Referenced by CodeGenerator(), and sx_work().
body
std::stringstream casadi::CodeGenerator::body
Definition at line 899 of file code_generator.hpp.
Referenced by add(), add_dependency(), casadi::FunctionInternal::codegen(), casadi::IpoptInterface::codegen_declarations(), casadi::FunctionInternal::codegen_meta(), dump(), and scope_exit().
buffer
std::stringstream casadi::CodeGenerator::buffer
Definition at line 901 of file code_generator.hpp.
Referenced by flush(), operator<<(), and print_formatted().
casadi_int_type
std::string casadi::CodeGenerator::casadi_int_type
Definition at line 841 of file code_generator.hpp.
Referenced by CodeGenerator().
casadi_real_type
std::string casadi::CodeGenerator::casadi_real_type
Definition at line 838 of file code_generator.hpp.
Referenced by CodeGenerator().
char_constants_
std::vector<std::vector<char> > casadi::CodeGenerator::char_constants_
Definition at line 945 of file code_generator.hpp.
Referenced by dump(), and get_constant().
codegen_scalars
bool casadi::CodeGenerator::codegen_scalars
Use the work vector for storing work vector elements of length 1 (typically scalar) instead of using local variables
Extra doc: https://github.com/casadi/casadi/wiki/L_u9
Definition at line 885 of file code_generator.hpp.
Referenced by casadi::MXFunction::codegen_body(), CodeGenerator(), casadi::BinaryMX< ScX, ScY >::generate(), work(), and workel().
cpp
bool casadi::CodeGenerator::cpp
Definition at line 866 of file code_generator.hpp.
Referenced by add_auxiliary(), CodeGenerator(), declare(), file_close(), file_open(), and generate().
current_indent_
casadi_int casadi::CodeGenerator::current_indent_
Definition at line 908 of file code_generator.hpp.
Referenced by CodeGenerator(), dump(), and print_formatted().
dll_export
std::string casadi::CodeGenerator::dll_export
Definition at line 891 of file code_generator.hpp.
Referenced by CodeGenerator().
dll_import
std::string casadi::CodeGenerator::dll_import
Definition at line 891 of file code_generator.hpp.
Referenced by CodeGenerator(), and declare().
double_constants_
std::vector<std::vector<double> > casadi::CodeGenerator::double_constants_
Definition at line 943 of file code_generator.hpp.
Referenced by dump(), and get_constant().
exposed_fname
std::vector<std::string> casadi::CodeGenerator::exposed_fname
Definition at line 911 of file code_generator.hpp.
Referenced by add(), and generate().
file_scope_double_
std::map<const void *, casadi_int> casadi::CodeGenerator::file_scope_double_
Definition at line 927 of file code_generator.hpp.
Referenced by define_rom_double(), define_rom_integer(), dump(), rom_double(), and rom_integer().
file_scope_integer_
std::map<const void *, casadi_int> casadi::CodeGenerator::file_scope_integer_
Definition at line 928 of file code_generator.hpp.
Referenced by dump().
header
std::stringstream casadi::CodeGenerator::header
Definition at line 900 of file code_generator.hpp.
Referenced by casadi::FunctionInternal::codegen_meta(), CodeGenerator(), declare(), and generate().
include_math
bool casadi::CodeGenerator::include_math
Definition at line 872 of file code_generator.hpp.
Referenced by CodeGenerator().
includes
std::stringstream casadi::CodeGenerator::includes
Definition at line 897 of file code_generator.hpp.
Referenced by add_include(), and dump().
indent_
casadi_int casadi::CodeGenerator::indent_
Definition at line 907 of file code_generator.hpp.
Referenced by CodeGenerator(), and print_formatted().
infinity
std::string casadi::CodeGenerator::infinity
Definition at line 877 of file code_generator.hpp.
Referenced by add_auxiliary(), and CodeGenerator().
integer_constants_
std::vector<std::vector<casadi_int> > casadi::CodeGenerator::integer_constants_
Definition at line 944 of file code_generator.hpp.
Referenced by dump(), and get_constant().
local_default_
std::map<std::string, std::string> casadi::CodeGenerator::local_default_
Definition at line 926 of file code_generator.hpp.
Referenced by init_local(), scope_enter(), and scope_exit().
local_variables_
std::map<std::string, std::pair<std::string, std::string> > casadi::CodeGenerator::local_variables_
Definition at line 925 of file code_generator.hpp.
Referenced by local(), scope_enter(), and scope_exit().
main
bool casadi::CodeGenerator::main
Definition at line 869 of file code_generator.hpp.
Referenced by casadi::FunctionInternal::codegen_meta(), CodeGenerator(), and generate().
mex
bool casadi::CodeGenerator::mex
Definition at line 850 of file code_generator.hpp.
Referenced by add_auxiliary(), casadi::FunctionInternal::codegen_meta(), CodeGenerator(), and generate().
name
std::string casadi::CodeGenerator::name
Definition at line 835 of file code_generator.hpp.
Referenced by add_io_sparsities(), array(), CodeGenerator(), constant_copy(), file_open(), generate(), init_local(), local(), mem(), operator()(), print_vector(), setup_callback(), shorthand(), sx_work(), and wrapper().
nan
std::string casadi::CodeGenerator::nan
Definition at line 877 of file code_generator.hpp.
Referenced by add_auxiliary(), and CodeGenerator().
needs_mem_
bool casadi::CodeGenerator::needs_mem_
Definition at line 949 of file code_generator.hpp.
Referenced by add_dependency(), CodeGenerator(), and dump().
newline_
bool casadi::CodeGenerator::newline_
Definition at line 904 of file code_generator.hpp.
Referenced by CodeGenerator(), operator<<(), and print_formatted().
prefix
std::string casadi::CodeGenerator::prefix
Definition at line 894 of file code_generator.hpp.
Referenced by CodeGenerator(), dump(), and generate().
real_min
std::string casadi::CodeGenerator::real_min
Definition at line 877 of file code_generator.hpp.
Referenced by add_auxiliary(), and CodeGenerator().
sparsity_meta
std::set<std::string> casadi::CodeGenerator::sparsity_meta
Definition at line 914 of file code_generator.hpp.
Referenced by add_io_sparsities().
string_constants_
std::vector<std::vector<std::string> > casadi::CodeGenerator::string_constants_
Definition at line 946 of file code_generator.hpp.
Referenced by dump(), and get_constant().
suffix
std::string casadi::CodeGenerator::suffix
Definition at line 835 of file code_generator.hpp.
Referenced by CodeGenerator(), generate(), and sanitize_source().
unroll_args
bool casadi::CodeGenerator::unroll_args
Definition at line 857 of file code_generator.hpp.
Referenced by add(), and CodeGenerator().
verbose
bool casadi::CodeGenerator::verbose
Definition at line 860 of file code_generator.hpp.
Referenced by casadi::MXFunction::codegen_body(), CodeGenerator(), and comment().
verbose_runtime
bool casadi::CodeGenerator::verbose_runtime
Definition at line 863 of file code_generator.hpp.
Referenced by CodeGenerator(), and sanitize_source().
with_export
bool casadi::CodeGenerator::with_export
Definition at line 888 of file code_generator.hpp.
Referenced by CodeGenerator(), and dump().
with_header
bool casadi::CodeGenerator::with_header
Definition at line 847 of file code_generator.hpp.
Referenced by casadi::FunctionInternal::codegen_meta(), CodeGenerator(), declare(), and generate().
with_import
bool casadi::CodeGenerator::with_import
Definition at line 888 of file code_generator.hpp.
Referenced by CodeGenerator(), and generate().
with_mem
bool casadi::CodeGenerator::with_mem
Definition at line 844 of file code_generator.hpp.
Referenced by casadi::FunctionInternal::codegen_meta(), CodeGenerator(), and dump().
with_sfunction
bool casadi::CodeGenerator::with_sfunction
Definition at line 853 of file code_generator.hpp.
Referenced by add(), CodeGenerator(), and generate().
The documentation for this class was generated from the following files:
code_generator.hpp
code_generator.cpp