CasADi: casadi::BonminUserClass Class Reference
casadi::BonminUserClass Class Reference
#include <bonmin_nlp.hpp>
Detailed Description
Definition at line 46 of file bonmin_nlp.hpp.
Public Member Functions
BonminUserClass (const BonminInterface &bonminInterface, BonminMemory *mem)
~BonminUserClass () override
bool get_nlp_info (Index &n, Index &m, Index &nnz_jac_g, Index &nnz_h_lag, TNLP::IndexStyleEnum &index_style) override
bool get_bounds_info (Index n, Number *x_l, Number *x_u, Index m, Number *g_l, Number *g_u) override
bool get_starting_point (Index n, bool init_x, Number *x, bool init_z, Number *z_L, Number *z_U, Index m, bool init_lambda, Number *lambda) override
bool eval_f (Index n, const Number *x, bool new_x, Number &obj_value) override
bool eval_grad_f (Index n, const Number *x, bool new_x, Number *grad_f) override
bool eval_g (Index n, const Number *x, bool new_x, Index m, Number *g) override
bool eval_jac_g (Index n, const Number *x, bool new_x, Index m, Index nele_jac, Index *iRow, Index *jCol, Number *values) override
bool eval_h (Index n, const Number *x, bool new_x, Number obj_factor, Index m, const Number *lambda, bool new_lambda, Index nele_hess, Index *iRow, Index *jCol, Number *values) override
void finalize_solution (TMINLP::SolverReturn status, Index n, const Number *x, Number obj_value) override
virtual Index get_number_of_nonlinear_variables ()
virtual bool get_list_of_nonlinear_variables (Index num_nonlin_vars, Index *pos_nonlin_vars)
virtual bool intermediate_callback (AlgorithmMode mode, Index iter, Number obj_value, Number inf_pr, Number inf_du, Number mu, Number d_norm, Number regularization_size, Number alpha_du, Number alpha_pr, Index ls_trials, const IpoptData *ip_data, IpoptCalculatedQuantities *ip_cq)
bool get_variables_types (Index n, VariableType *var_types) override
bool get_variables_linearity (Index n, Ipopt::TNLP::LinearityType *var_types) override
bool get_constraints_linearity (Index m, Ipopt::TNLP::LinearityType *const_types) override
const SosInfo * sosConstraints () const override
const BranchingInfo * branchingInfo () const override
Constructor & Destructor Documentation
BonminUserClass()
casadi::BonminUserClass::BonminUserClass (const BonminInterface & bonminInterface, BonminMemory * mem)
Definition at line 32 of file bonmin_nlp.cpp.
     : solver_(solver), mem_(mem) {
     n_ = solver_.nx_;
     m_ = solver_.ng_;
   }
References casadi::Nlpsol::ng_, and casadi::Nlpsol::nx_.
~BonminUserClass()
casadi::BonminUserClass::~BonminUserClass () override
Definition at line 38 of file bonmin_nlp.cpp.
{
   }
Member Function Documentation
branchingInfo()
const BranchingInfo* casadi::BonminUserClass::branchingInfo () const inline override
Definition at line 119 of file bonmin_nlp.hpp.
 {return nullptr;}
eval_f()
bool casadi::BonminUserClass::eval_f (Index n, const Number * x, bool new_x, Number & obj_value) override
Method to return the objective value
Definition at line 71 of file bonmin_nlp.cpp.
{
     mem_->arg[0] = x;
     mem_->arg[1] = mem_->d_nlp.p;
     mem_->res[0] = &obj_value;
     return solver_.calc_function(mem_, "nlp_f")==0;
   }
References casadi::OracleMemory::arg, casadi::OracleFunction::calc_function(), casadi::NlpsolMemory::d_nlp, casadi_nlpsol_data< T1 >::p, and casadi::OracleMemory::res.
eval_g()
bool casadi::BonminUserClass::eval_g (Index n, const Number * x, bool new_x, Index m, Number * g) override
Method to return the constraint residuals
Definition at line 88 of file bonmin_nlp.cpp.
{
     mem_->arg[0] = x;
     mem_->arg[1] = mem_->d_nlp.p;
     mem_->res[0] = g;
     return solver_.calc_function(mem_, "nlp_g")==0;
   }
References casadi::OracleMemory::arg, casadi::OracleFunction::calc_function(), casadi::NlpsolMemory::d_nlp, casadi_nlpsol_data< T1 >::p, and casadi::OracleMemory::res.
eval_grad_f()
bool casadi::BonminUserClass::eval_grad_f (Index n, const Number * x, bool new_x, Number * grad_f) override
Method to return the gradient of the objective
Definition at line 79 of file bonmin_nlp.cpp.
{
     mem_->arg[0] = x;
     mem_->arg[1] = mem_->d_nlp.p;
     mem_->res[0] = nullptr;
     mem_->res[1] = grad_f;
     return solver_.calc_function(mem_, "nlp_grad_f")==0;
   }
References casadi::OracleMemory::arg, casadi::OracleFunction::calc_function(), casadi::NlpsolMemory::d_nlp, casadi_nlpsol_data< T1 >::p, and casadi::OracleMemory::res.
eval_h()
bool casadi::BonminUserClass::eval_h (Index n, const Number * x, bool new_x, Number obj_factor, Index m, const Number * lambda, bool new_lambda, Index nele_hess, Index * iRow, Index * jCol, Number * values) override
Method to return: 1) The structure of the hessian of the Lagrangian (if "values" is NULL) 2) The values of the hessian of the Lagrangian (if "values" is not NULL)
Definition at line 125 of file bonmin_nlp.cpp.
{
     if (values) {
       // Evaluate numerically
       mem_->arg[0] = x;
       mem_->arg[1] = mem_->d_nlp.p;
       mem_->arg[2] = &obj_factor;
       mem_->arg[3] = lambda;
       mem_->res[0] = values;
       return !solver_.calc_function(mem_, "nlp_hess_l");
     } else {
       // Get the sparsity pattern
       casadi_int ncol = solver_.hesslag_sp_.size2();
       const casadi_int* colind = solver_.hesslag_sp_.colind();
       const casadi_int* row = solver_.hesslag_sp_.row();
       // Pass to BONMIN
       for (casadi_int cc=0; cc<ncol; ++cc) {
         for (casadi_int el=colind[cc]; el<colind[cc+1]; ++el) {
           *iRow++ = row[el];
           *jCol++ = cc;
         }
       }
       return true;
     }
   }
References casadi::OracleMemory::arg, casadi::OracleFunction::calc_function(), casadi::Sparsity::colind(), casadi::NlpsolMemory::d_nlp, casadi::BonminInterface::hesslag_sp_, casadi_nlpsol_data< T1 >::p, casadi::OracleMemory::res, casadi::Sparsity::row(), and casadi::Sparsity::size2().
eval_jac_g()
bool casadi::BonminUserClass::eval_jac_g (Index n, const Number * x, bool new_x, Index m, Index nele_jac, Index * iRow, Index * jCol, Number * values) override
Method to return: 1) The structure of the Jacobian (if "values" is NULL) 2) The values of the Jacobian (if "values" is not NULL)
Definition at line 96 of file bonmin_nlp.cpp.
{
     if (values) {
       // Evaluate numerically
       mem_->arg[0] = x;
       mem_->arg[1] = mem_->d_nlp.p;
       mem_->res[0] = nullptr;
       mem_->res[1] = values;
       return solver_.calc_function(mem_, "nlp_jac_g")==0;
     } else {
       // Get the sparsity pattern
       casadi_int ncol = solver_.jacg_sp_.size2();
       const casadi_int* colind = solver_.jacg_sp_.colind();
       const casadi_int* row = solver_.jacg_sp_.row();
       if (nele_jac!=colind[ncol]) return false; // consistency check
       // Pass to BONMIN
       for (casadi_int cc=0; cc<ncol; ++cc) {
         for (casadi_int el=colind[cc]; el<colind[cc+1]; ++el) {
           *iRow++ = row[el];
           *jCol++ = cc;
         }
       }
       return true;
     }
   }
References casadi::OracleMemory::arg, casadi::OracleFunction::calc_function(), casadi::Sparsity::colind(), casadi::NlpsolMemory::d_nlp, casadi::BonminInterface::jacg_sp_, casadi_nlpsol_data< T1 >::p, casadi::OracleMemory::res, casadi::Sparsity::row(), and casadi::Sparsity::size2().
finalize_solution()
void casadi::BonminUserClass::finalize_solution (TMINLP::SolverReturn status, Index n, const Number * x, Number obj_value) override
This method is called when the algorithm is complete so the TNLP can store/write the solution
Definition at line 154 of file bonmin_nlp.cpp.
{
     solver_.finalize_solution(mem_, status, x, obj_value);
   }
References casadi::BonminInterface::finalize_solution().
get_bounds_info()
bool casadi::BonminUserClass::get_bounds_info (Index n, Number * x_l, Number * x_u, Index m, Number * g_l, Number * g_u) override
Method to return the bounds for my problem
Definition at line 53 of file bonmin_nlp.cpp.
{
     casadi_assert_dev(n==solver_.nx_);
     casadi_assert_dev(m==solver_.ng_);
     return solver_.get_bounds_info(mem_, x_l, x_u, g_l, g_u);
   }
References casadi::BonminInterface::get_bounds_info(), casadi::Nlpsol::ng_, and casadi::Nlpsol::nx_.
get_constraints_linearity()
bool casadi::BonminUserClass::get_constraints_linearity (Index m, Ipopt::TNLP::LinearityType * const_types) override
Definition at line 211 of file bonmin_nlp.cpp.
{
    casadi_assert_dev(m==solver_.nl_g_.size());
    for (casadi_int i=0; i<m; ++i)
     const_types[i] = solver_.nl_g_[i] ? Ipopt::TNLP::NON_LINEAR : Ipopt::TNLP::LINEAR;
    return true;
  }
References casadi::BonminInterface::nl_g_.
get_list_of_nonlinear_variables()
bool casadi::BonminUserClass::get_list_of_nonlinear_variables (Index num_nonlin_vars, Index * pos_nonlin_vars) virtual
Specify which variables that appear in the Hessian
Definition at line 187 of file bonmin_nlp.cpp.
{
     return solver_.get_list_of_nonlinear_variables(num_nonlin_vars, pos_nonlin_vars);
   }
References casadi::BonminInterface::get_list_of_nonlinear_variables().
get_nlp_info()
bool casadi::BonminUserClass::get_nlp_info (Index & n, Index & m, Index & nnz_jac_g, Index & nnz_h_lag, TNLP::IndexStyleEnum & index_style) override
Method to return some info about the nlp
Definition at line 42 of file bonmin_nlp.cpp.
{
     solver_.get_nlp_info(mem_, n, m, nnz_jac_g, nnz_h_lag);
     // use the C style indexing (0-based)
     index_style = TNLP::C_STYLE;
     return true;
   }
References casadi::BonminInterface::get_nlp_info().
get_number_of_nonlinear_variables()
Index casadi::BonminUserClass::get_number_of_nonlinear_variables () virtual
Specify the number of variables that appear in the Hessian
Definition at line 183 of file bonmin_nlp.cpp.
{
     return solver_.get_number_of_nonlinear_variables();
   }
References casadi::BonminInterface::get_number_of_nonlinear_variables().
get_starting_point()
bool casadi::BonminUserClass::get_starting_point (Index n, bool init_x, Number * x, bool init_z, Number * z_L, Number * z_U, Index m, bool init_lambda, Number * lambda) override
Method to return the starting point for the algorithm
Definition at line 61 of file bonmin_nlp.cpp.
{
     casadi_assert_dev(n==solver_.nx_);
     casadi_assert_dev(m==solver_.ng_);
     return solver_.get_starting_point(mem_, init_x, x, init_z, z_L, z_U, init_lambda, lambda);
   }
References casadi::BonminInterface::get_starting_point(), casadi::Nlpsol::ng_, and casadi::Nlpsol::nx_.
get_variables_linearity()
bool casadi::BonminUserClass::get_variables_linearity (Index n, Ipopt::TNLP::LinearityType * var_types) override
Definition at line 204 of file bonmin_nlp.cpp.
{
    casadi_assert_dev(n==solver_.nl_ex_.size());
    for (casadi_int i=0; i<n; ++i)
     var_types[i] = solver_.nl_ex_[i] ? Ipopt::TNLP::NON_LINEAR : Ipopt::TNLP::LINEAR;
    return true;
  }
References casadi::BonminInterface::nl_ex_.
get_variables_types()
bool casadi::BonminUserClass::get_variables_types (Index n, VariableType * var_types) override
Definition at line 192 of file bonmin_nlp.cpp.
{
    if (solver_.discrete_.empty()) {
      std::fill_n(var_types, n, CONTINUOUS);
    } else {
      if (solver_.discrete_.size()!=n) return false;
      for (auto&& d : solver_.discrete_) {
        *var_types++ = d ? INTEGER : CONTINUOUS;
      }
    }
    return true;
  }
References casadi::CONTINUOUS, casadi::Nlpsol::discrete_, and casadi::INTEGER.
intermediate_callback()
bool casadi::BonminUserClass::intermediate_callback (AlgorithmMode mode, Index iter, Number obj_value, Number inf_pr, Number inf_du, Number mu, Number d_norm, Number regularization_size, Number alpha_du, Number alpha_pr, Index ls_trials, const IpoptData * ip_data, IpoptCalculatedQuantities * ip_cq) virtual
This method is called at every iteration
Code copied from TNLPAdapter::FinalizeSolution See also: http://list.coin-or.org/pipermail/ipopt/2010-July/002078.html
Definition at line 160 of file bonmin_nlp.cpp.
{
     // Only do the callback every few iterations
     if (iter % solver_.callback_step_!=0) return true;
     // http://list.coin-or.org/pipermail/ipopt/2010-April/001965.html
     bool full_callback = false;
     return solver_.intermediate_callback(mem_, x_, z_L_, z_U_, g_, lambda_, obj_value, iter,
                                          inf_pr, inf_du, mu, d_norm, regularization_size,
                                          alpha_du, alpha_pr, ls_trials, full_callback);
   }
References casadi::Nlpsol::callback_step_, and casadi::BonminInterface::intermediate_callback().
sosConstraints()
const Bonmin::TMINLP::SosInfo * casadi::BonminUserClass::sosConstraints () const override
Definition at line 218 of file bonmin_nlp.cpp.
{
    return &solver_.sosConstraints(mem_);
  }
References casadi::BonminInterface::sosConstraints().
The documentation for this class was generated from the following files:
bonmin_nlp.hpp
bonmin_nlp.cpp