CasADi: casadi::DeserializingStream Class Reference
casadi::DeserializingStream Class Reference
Helper class for Serialization.
#include <serializing_stream.hpp>
Detailed Description
Author
Joris Gillis
Date
2018
Extra doc: https://github.com/casadi/casadi/wiki/L_ak
Definition at line 73 of file serializing_stream.hpp.
Public Member Functions
DeserializingStream (std::istream &in_s)
Constructor.
DeserializingStream (const DeserializingStream &)=delete
void setup ()
void unpack (Sparsity &e)
Reconstruct an object from the input stream.
void unpack (MX &e)
void unpack (SXElem &e)
void unpack (Linsol &e)
template<class T >
void unpack (Matrix< T > &e)
void unpack (Function &e)
void unpack (Importer &e)
void unpack (Resource &e)
void unpack (Fmu &e)
void unpack (GenericType &e)
void unpack (std::ostream &s)
void unpack (Slice &e)
void unpack (int &e)
void unpack (bool &e)
void unpack (casadi_int &e)
void unpack (size_t &e)
void unpack (std::string &e)
void unpack (double &e)
void unpack (char &e)
template<class T >
void unpack (std::vector< T > &e)
template<class K , class V >
void unpack (std::map< K, V > &e)
template<class A , class B >
void unpack (std::pair< A, B > &e)
template<class T >
void unpack (const std::string &descr, T &e)
void version (const std::string &name, int v)
int version (const std::string &name)
int version (const std::string &name, int min, int max)
void connect (SerializingStream &s)
void reset ()
template<>
void unpack (std::vector< bool > &e)
Friends
class SerializingStream
Constructor & Destructor Documentation
DeserializingStream() [1/2]
casadi::DeserializingStream::DeserializingStream (std::istream & in_s)
Definition at line 47 of file serializing_stream.cpp.
                                                              : in(in_s), debug_(false) {
       casadi_assert(in_s.good(), "Invalid input stream. If you specified an input file, "
         "make sure it exists relative to the current directory.");
       if (in_s.peek() != std::char_traits<char>::eof()) {
         setup();
       }
     }
References setup().
DeserializingStream() [2/2]
casadi::DeserializingStream::DeserializingStream (const DeserializingStream &) delete
Member Function Documentation
connect()
void casadi::DeserializingStream::connect (SerializingStream & s)
Definition at line 446 of file serializing_stream.cpp.
{
     shared_map_ = &s.shared_map_;
   }
reset()
void casadi::DeserializingStream::reset ()
Definition at line 454 of file serializing_stream.cpp.
{
     nodes_.clear();
   }
setup()
void casadi::DeserializingStream::setup ()
Definition at line 56 of file serializing_stream.cpp.
{
       if (set_up_) return;
       // Sanity check
       casadi_int check;
       unpack(check);
       casadi_assert(check==serialization_check,
         "DeserializingStream sanity check failed. "
         "Expected " + str(serialization_check) + ", but got " + str(check) + ".");
       // API version check
       casadi_int v;
       unpack(v);
       casadi_assert(v==serialization_protocol_version,
         "Serialization protocol is not compatible. "
         "Got version " + str(v) + ", while " +
         str(serialization_protocol_version) + " was expected.");
       bool debug;
       unpack(debug);
       debug_ = debug;
       set_up_ = true;
     }
References casadi::serialization_check, casadi::serialization_protocol_version, casadi::str(), and unpack().
Referenced by DeserializingStream().
unpack() [1/24]
void casadi::DeserializingStream::unpack (bool & e)
Definition at line 183 of file serializing_stream.cpp.
{
       assert_decoration('b');
       char n;
       unpack(n);
       e = n;
     }
References unpack().
unpack() [2/24]
void casadi::DeserializingStream::unpack (casadi_int & e)
Definition at line 117 of file serializing_stream.cpp.
{
       assert_decoration('J');
       int64_t n;
       char* c = reinterpret_cast<char*>(&n);
       for (int j=0;j<8;++j) unpack(c[j]);
       e = n;
     }
References unpack().
unpack() [3/24]
void casadi::DeserializingStream::unpack (char & e)
Definition at line 195 of file serializing_stream.cpp.
{
       unsigned char ref = 'a';
       in.get(e);
       char t;
       in.get(t);
       e = (reinterpret_cast<unsigned char&>(e)-ref) +
           ((reinterpret_cast<unsigned char&>(t)-ref) << 4);
     }
unpack() [4/24]
template<class T > void casadi::DeserializingStream::unpack (const std::string & descr, T & e) inline
Definition at line 147 of file serializing_stream.hpp.
{
       if (debug_) {
         std::string d;
         unpack(d);
         casadi_assert(d==descr, "Mismatch: '" + descr + "' expected, got '" + d + "'.");
       }
       unpack(e);
     }
unpack() [5/24]
void casadi::DeserializingStream::unpack (double & e)
Definition at line 228 of file serializing_stream.cpp.
{
       assert_decoration('d');
       char* c = reinterpret_cast<char*>(&e);
       for (int j=0;j<8;++j) unpack(c[j]);
     }
References unpack().
unpack() [6/24]
void casadi::DeserializingStream::unpack (Fmu & e)
Definition at line 295 of file serializing_stream.cpp.
{
       assert_decoration('F');
       shared_unpack<Fmu, FmuInternal>(e);
     }
unpack() [7/24]
void casadi::DeserializingStream::unpack (Function & e)
Definition at line 265 of file serializing_stream.cpp.
{
       assert_decoration('F');
       shared_unpack<Function, FunctionInternal>(e);
     }
unpack() [8/24]
void casadi::DeserializingStream::unpack (GenericType & e)
Definition at line 315 of file serializing_stream.cpp.
{
       assert_decoration('G');
       shared_unpack<GenericType, SharedObjectInternal>(e);
     }
unpack() [9/24]
void casadi::DeserializingStream::unpack (Importer & e)
Definition at line 275 of file serializing_stream.cpp.
{
       assert_decoration('M');
       shared_unpack<Importer, ImporterInternal>(e);
     }
unpack() [10/24]
void casadi::DeserializingStream::unpack (int & e)
Definition at line 149 of file serializing_stream.cpp.
{
       assert_decoration('i');
       int32_t n;
       char* c = reinterpret_cast<char*>(&n);
       for (int j=0;j<4;++j) unpack(c[j]);
       e = n;
     }
References unpack().
unpack() [11/24]
void casadi::DeserializingStream::unpack (Linsol & e)
Definition at line 305 of file serializing_stream.cpp.
{
       assert_decoration('L');
       shared_unpack<Linsol, LinsolInternal>(e);
     }
unpack() [12/24]
template<class T > void casadi::DeserializingStream::unpack (Matrix< T > & e) inline
Definition at line 94 of file serializing_stream.hpp.
{
       e = Matrix<T>::deserialize(*this);
     }
References casadi::Matrix< Scalar >::deserialize().
unpack() [13/24]
void casadi::DeserializingStream::unpack (MX & e)
Definition at line 255 of file serializing_stream.cpp.
{
       assert_decoration('X');
       shared_unpack<MX, MXNode>(e);
     }
unpack() [14/24]
void casadi::DeserializingStream::unpack (Resource & e)
Definition at line 285 of file serializing_stream.cpp.
{
       assert_decoration('R');
       shared_unpack<Resource, ResourceInternal>(e);
     }
unpack() [15/24]
void casadi::DeserializingStream::unpack (size_t & e)
Definition at line 140 of file serializing_stream.cpp.
{
       assert_decoration('K');
       uint64_t n;
       char* c = reinterpret_cast<char*>(&n);
       for (int j=0;j<8;++j) unpack(c[j]);
       e = n;
     }
References unpack().
unpack() [16/24]
void casadi::DeserializingStream::unpack (Slice & e)
Definition at line 353 of file serializing_stream.cpp.
{
       assert_decoration('S');
       e = Slice::deserialize(*this);
     }
References casadi::Slice::deserialize().
unpack() [17/24]
void casadi::DeserializingStream::unpack (Sparsity & e)
If the reference is not of the same type as the object encoded in the stream. an error will be raised.
Extra doc: https://github.com/casadi/casadi/wiki/L_al
Definition at line 245 of file serializing_stream.cpp.
{
       assert_decoration('S');
       shared_unpack<Sparsity, SparsityInternal>(e);
     }
Referenced by casadi::AlpaqaInterface::AlpaqaInterface(), casadi::Assertion::Assertion(), casadi::BinaryMX< ScX, ScY >::BinaryMX(), casadi::BlazingSplineFunction::BlazingSplineFunction(), casadi::DeserializerBase::blind_unpack_mx(), casadi::DeserializerBase::blind_unpack_mx_v1(), casadi::DeserializerBase::blind_unpack_mx_vector(), casadi::DeserializerBase::blind_unpack_mx_vector_v1(), casadi::DeserializerBase::blind_unpack_sx(), casadi::DeserializerBase::blind_unpack_sx_v1(), casadi::DeserializerBase::blind_unpack_sx_vector(), casadi::DeserializerBase::blind_unpack_sx_vector_v1(), casadi::Blocksqp::Blocksqp(), casadi::BonminInterface::BonminInterface(), casadi::BSpline::BSpline(), casadi::BSplineCommon::BSplineCommon(), casadi::BSplineInterpolant::BSplineInterpolant(), casadi::Call::Call(), casadi::CbcInterface::CbcInterface(), casadi::ClarabelInterface::ClarabelInterface(), casadi::ClpInterface::ClpInterface(), casadi::Collocation::Collocation(), casadi::Conic::Conic(), casadi::ConstantDM::ConstantDM(), casadi::ConstantFile::ConstantFile(), casadi::ConstantPool::ConstantPool(), casadi::ConstantSX_deserialize(), casadi::CplexInterface::CplexInterface(), casadi::CvodesInterface::CvodesInterface(), casadi::DaqpInterface::DaqpInterface(), casadi::XFunction< DerivedType, MatType, NodeType >::delayed_deserialize_members(), casadi::BinaryMX< ScX, ScY >::deserialize(), casadi::BSplineCommon::deserialize(), casadi::CallSX::deserialize(), casadi::ConstantMX::deserialize(), casadi::RuntimeConst< T >::deserialize(), casadi::External::deserialize(), casadi::FmuInternal::deserialize(), casadi::Function::deserialize(), casadi::FunctionInternal::deserialize(), casadi::GenericType::deserialize(), casadi::GenericTypeInternal< ID, T >::deserialize(), casadi::GetNonzeros::deserialize(), casadi::GetNonzerosParam::deserialize(), casadi::ImporterInternal::deserialize(), casadi::Map::deserialize(), casadi::MapSum::deserialize(), casadi::Multiplication::deserialize(), casadi::MXNode::deserialize(), casadi::OutputSX::deserialize(), casadi::PluginInterface< Derived >::deserialize(), casadi::Project::deserialize(), casadi::ResourceInternal::deserialize(), casadi::SetNonzeros< Add >::deserialize(), casadi::SetNonzerosParam< Add >::deserialize(), casadi::Slice::deserialize(), casadi::Solve< Tr >::deserialize(), casadi::LinsolCall< Tr >::deserialize(), casadi::Sparsity::deserialize(), casadi::SXNode::deserialize(), casadi::SymbolicSX::deserialize(), casadi::Transpose::deserialize(), casadi::LinearInterpolant::deserialize(), casadi::BinarySX::deserialize(), casadi::UnarySX::deserialize(), casadi::Convexify::deserialize(), casadi::Conic::deserialize(), casadi::DirResource::DirResource(), casadi::External::External(), casadi::FastNewton::FastNewton(), casadi::FatropInterface::FatropInterface(), casadi::Feasiblesqpmethod::Feasiblesqpmethod(), casadi::FixedStepIntegrator::FixedStepIntegrator(), casadi::Fmu2::Fmu2(), casadi::Fmu3::Fmu3(), casadi::FmuFunction::FmuFunction(), casadi::FmuInternal::FmuInternal(), casadi::FunctionInternal::FunctionInternal(), casadi::GetNonzerosParamSlice::GetNonzerosParamSlice(), casadi::GetNonzerosSlice::GetNonzerosSlice(), casadi::GetNonzerosSlice2::GetNonzerosSlice2(), casadi::GetNonzerosSliceParam::GetNonzerosSliceParam(), casadi::GetNonzerosVector::GetNonzerosVector(), casadi::GurobiInterface::GurobiInterface(), casadi::HighsInterface::HighsInterface(), casadi::HorzRepmat::HorzRepmat(), casadi::HorzRepsum::HorzRepsum(), casadi::IdasInterface::IdasInterface(), casadi::ImporterInternal::ImporterInternal(), casadi::Integrator::Integrator(), casadi::Interpolant::Interpolant(), casadi::IOInstruction::IOInstruction(), casadi::IpoptInterface::IpoptInterface(), casadi::Ipqp::Ipqp(), casadi::KnitroInterface::KnitroInterface(), casadi::LapackLu::LapackLu(), casadi::LapackQr::LapackQr(), casadi::LinearInterpolant::LinearInterpolant(), casadi::LinsolCall< Tr >::LinsolCall(), casadi::LinsolInternal::LinsolInternal(), casadi::LinsolLdl::LinsolLdl(), casadi::LinsolQr::LinsolQr(), casadi::Low::Low(), casadi::MadnlpInterface::MadnlpInterface(), casadi::Map::Map(), casadi::MapSum::MapSum(), casadi::Monitor::Monitor(), casadi::MumpsInterface::MumpsInterface(), casadi::MXFunction::MXFunction(), casadi::MXNode::MXNode(), casadi::Newton::Newton(), casadi::Nlpsol::Nlpsol(), casadi::OoqpInterface::OoqpInterface(), casadi::OracleFunction::OracleFunction(), casadi::OsqpInterface::OsqpInterface(), casadi::OutputNode::OutputNode(), casadi::DeserializerBase::pop_type(), casadi::ProtoFunction::ProtoFunction(), casadi::ProxqpInterface::ProxqpInterface(), casadi::QpoasesInterface::QpoasesInterface(), casadi::QpToNlp::QpToNlp(), casadi::Qrqp::Qrqp(), casadi::ResourceInternal::ResourceInternal(), casadi::Rootfinder::Rootfinder(), casadi::SetNonzerosParamSlice< Add >::SetNonzerosParamSlice(), casadi::SetNonzerosSlice< Add >::SetNonzerosSlice(), casadi::SetNonzerosSlice2< Add >::SetNonzerosSlice2(), casadi::SetNonzerosSliceParam< Add >::SetNonzerosSliceParam(), casadi::SetNonzerosVector< Add >::SetNonzerosVector(), setup(), casadi::SLEQPInterface::SLEQPInterface(), casadi::SnoptInterface::SnoptInterface(), casadi::Split::Split(), casadi::Sqpmethod::Sqpmethod(), casadi::SundialsInterface::SundialsInterface(), casadi::SuperscsInterface::SuperscsInterface(), casadi::Switch::Switch(), casadi::SXFunction::SXFunction(), casadi::SymbolicMX::SymbolicMX(), casadi::SymbolicQr::SymbolicQr(), casadi::UnaryMX::UnaryMX(), unpack(), version(), casadi::WorhpInterface::WorhpInterface(), casadi::XFunction< DerivedType, MatType, NodeType >::XFunction(), casadi::ZipMemResource::ZipMemResource(), and casadi::ZipResource::ZipResource().
unpack() [18/24]
template<class K , class V > void casadi::DeserializingStream::unpack (std::map< K, V > & e) inline
Definition at line 125 of file serializing_stream.hpp.
{
       assert_decoration('D');
       casadi_int s;
       unpack(s);
       e.clear();
       for (casadi_int i=0;i<s;++i) {
         K k;
         V v;
         unpack(k);
         unpack(v);
         e[k] = v;
       }
     }
unpack() [19/24]
void casadi::DeserializingStream::unpack (std::ostream & s)
Definition at line 337 of file serializing_stream.cpp.
{
       assert_decoration('B');
       size_t len;
       unpack(len);
       for (size_t i=0;i<len;++i) {
         char c;
         unpack(c);
         s.put(c);
       }
     }
References unpack().
unpack() [20/24]
template<class A , class B > void casadi::DeserializingStream::unpack (std::pair< A, B > & e) inline
Definition at line 140 of file serializing_stream.hpp.
{
       assert_decoration('p');
       unpack(e.first);
       unpack(e.second);
     }
unpack() [21/24]
void casadi::DeserializingStream::unpack (std::string & e)
Definition at line 220 of file serializing_stream.cpp.
{
       assert_decoration('s');
       int s;
       unpack(s);
       e.resize(s);
       for (int j=0;j<s;++j) unpack(e[j]);
     }
References unpack().
unpack() [22/24]
template<> CASADI_EXPORT void casadi::DeserializingStream::unpack (std::vector< bool > & e)
Definition at line 369 of file serializing_stream.cpp.
{
     assert_decoration('V');
     casadi_int s;
     unpack(s);
     e.resize(s);
     for (casadi_int i=0;i<s;++i) {
       bool b;
       unpack(b);
       e[i] = b;
     }
   }
References unpack().
unpack() [23/24]
template<class T > void casadi::DeserializingStream::unpack (std::vector< T > & e) inline
Definition at line 116 of file serializing_stream.hpp.
{
       assert_decoration('V');
       casadi_int s;
       unpack(s);
       e.resize(s);
       for (T& i : e) unpack(i);
     }
References casadi::T.
unpack() [24/24]
void casadi::DeserializingStream::unpack (SXElem & e)
Definition at line 363 of file serializing_stream.cpp.
{
       assert_decoration('E');
       shared_unpack<SXElem, SXNode>(e);
     }
version() [1/3]
int casadi::DeserializingStream::version (const std::string & name)
Definition at line 381 of file serializing_stream.cpp.
{
     int load_version;
     unpack(name+"::serialization::version", load_version);
     return load_version;
   }
References unpack().
version() [2/3]
int casadi::DeserializingStream::version (const std::string & name, int min, int max)
Definition at line 387 of file serializing_stream.cpp.
{
     int load_version = version(name);
     casadi_assert(load_version>=min && load_version<=max,
       "DeSerialization of " + name + " failed. "
       "Object written in version " + str(load_version) +
       " but can only read version " + str(min) + "..." + str(max) + ".");
     return load_version;
   }
References casadi::str(), and version().
version() [3/3]
void casadi::DeserializingStream::version (const std::string & name, int v)
Definition at line 396 of file serializing_stream.cpp.
{
     int load_version = version(name);
     casadi_assert(load_version==v,
       "DeSerialization of " + name + " failed. "
       "Object written in version " + str(load_version) +
       " but can only read in version " + str(v) + ".");
   }
References casadi::str().
Referenced by casadi::AlpaqaInterface::AlpaqaInterface(), casadi::BlazingSplineFunction::BlazingSplineFunction(), casadi::Blocksqp::Blocksqp(), casadi::BonminInterface::BonminInterface(), casadi::BSplineInterpolant::BSplineInterpolant(), casadi::CbcInterface::CbcInterface(), casadi::ClarabelInterface::ClarabelInterface(), casadi::ClpInterface::ClpInterface(), casadi::Collocation::Collocation(), casadi::Conic::Conic(), casadi::CplexInterface::CplexInterface(), casadi::CvodesInterface::CvodesInterface(), casadi::DaqpInterface::DaqpInterface(), casadi::External::deserialize(), casadi::ResourceInternal::deserialize(), casadi::LinearInterpolant::deserialize(), casadi::Convexify::deserialize(), casadi::DirResource::DirResource(), casadi::External::External(), casadi::FastNewton::FastNewton(), casadi::FatropConicInterface::FatropConicInterface(), casadi::FatropInterface::FatropInterface(), casadi::Feasiblesqpmethod::Feasiblesqpmethod(), casadi::FixedStepIntegrator::FixedStepIntegrator(), casadi::Fmu2::Fmu2(), casadi::Fmu3::Fmu3(), casadi::FmuFunction::FmuFunction(), casadi::FmuInternal::FmuInternal(), casadi::FunctionInternal::FunctionInternal(), casadi::GurobiInterface::GurobiInterface(), casadi::HighsInterface::HighsInterface(), casadi::HpipmInterface::HpipmInterface(), casadi::IdasInterface::IdasInterface(), casadi::ImplicitFixedStepIntegrator::ImplicitFixedStepIntegrator(), casadi::ImporterInternal::ImporterInternal(), casadi::Integrator::Integrator(), casadi::Interpolant::Interpolant(), casadi::IpoptInterface::IpoptInterface(), casadi::Ipqp::Ipqp(), casadi::KnitroInterface::KnitroInterface(), casadi::LapackLu::LapackLu(), casadi::LinsolLdl::LinsolLdl(), casadi::LinsolQr::LinsolQr(), casadi::MadnlpInterface::MadnlpInterface(), casadi::MumpsInterface::MumpsInterface(), casadi::MXFunction::MXFunction(), casadi::Newton::Newton(), casadi::Nlpsol::Nlpsol(), casadi::OoqpInterface::OoqpInterface(), casadi::OracleFunction::OracleFunction(), casadi::OsqpInterface::OsqpInterface(), casadi::ProtoFunction::ProtoFunction(), casadi::ProxqpInterface::ProxqpInterface(), casadi::QpoasesInterface::QpoasesInterface(), casadi::QpToNlp::QpToNlp(), casadi::Qrqp::Qrqp(), casadi::Rootfinder::Rootfinder(), casadi::RungeKutta::RungeKutta(), casadi::SLEQPInterface::SLEQPInterface(), casadi::SnoptInterface::SnoptInterface(), casadi::Sqpmethod::Sqpmethod(), casadi::SundialsInterface::SundialsInterface(), casadi::SuperscsInterface::SuperscsInterface(), casadi::Switch::Switch(), casadi::SXFunction::SXFunction(), casadi::SymbolicQr::SymbolicQr(), version(), casadi::WorhpInterface::WorhpInterface(), casadi::XFunction< DerivedType, MatType, NodeType >::XFunction(), casadi::ZipMemResource::ZipMemResource(), and casadi::ZipResource::ZipResource().
Friends And Related Function Documentation
SerializingStream
friend class SerializingStream friend
Definition at line 74 of file serializing_stream.hpp.
The documentation for this class was generated from the following files:
serializing_stream.hpp
serializing_stream.cpp