CasADi: casadi::Rank1 Class Reference
casadi::Rank1 Class Reference
Calculate rank1 update.
#include <rank1.hpp>
Detailed Description
Author
Joel Andersson
Date
2015
Extra doc: https://github.com/casadi/casadi/wiki/L_1
Definition at line 42 of file rank1.hpp.
Public Types
using weak_ref_type = WeakRefInternal
Public Member Functions
Rank1 (const MX &A, const MX &alpha, const MX &x, const MX &y)
Constructor.
~Rank1 () override
Destructor.
template<typename T >
int eval_gen (const T **arg, T **res, casadi_int *iw, T *w) const
Evaluate the function (template)
int eval (const double **arg, double **res, casadi_int *iw, double *w) const override
Evaluate the function numerically.
int eval_sx (const SXElem **arg, SXElem **res, casadi_int *iw, SXElem *w) const override
Evaluate the function symbolically (SX)
int sp_forward (const bvec_t **arg, bvec_t **res, casadi_int *iw, bvec_t *w) const override
Propagate sparsity forward.
int sp_reverse (bvec_t **arg, bvec_t **res, casadi_int *iw, bvec_t *w) const override
Propagate sparsity backwards.
void eval_mx (const std::vector< MX > &arg, std::vector< MX > &res) const override
Evaluate symbolically (MX)
void ad_forward (const std::vector< std::vector< MX > > &fseed, std::vector< std::vector< MX > > &fsens) const override
Calculate forward mode directional derivatives.
void ad_reverse (const std::vector< std::vector< MX > > &aseed, std::vector< std::vector< MX > > &asens) const override
Calculate reverse mode directional derivatives.
void generate (CodeGenerator &g, const std::vector< casadi_int > &arg, const std::vector< casadi_int > &res, const std::vector< bool > &arg_is_ref, std::vector< bool > &res_is_ref) const override
Generate code for the operation.
casadi_int n_inplace () const override
Can the operation be performed inplace (i.e. overwrite the result)
std::string disp (const std::vector< std::string > &arg) const override
Print expression.
casadi_int op () const override
Get the operation.
virtual bool __nonzero__ () const
Check the truth value of this node.
virtual bool is_zero () const
Check if identically zero.
virtual bool is_one () const
Check if identically one.
virtual bool is_minus_one () const
Check if identically minus one.
virtual bool is_value (double val) const
Check if a certain value.
virtual bool is_eye () const
Check if identity matrix.
virtual bool is_unary () const
Check if unary operation.
virtual bool is_binary () const
Check if binary operation.
void can_inline (std::map< const MXNode *, casadi_int > &nodeind) const
Find out which nodes can be inlined.
std::string print_compact (std::map< const MXNode *, casadi_int > &nodeind, std::vector< std::string > &intermed) const
Print compact.
void disp (std::ostream &stream, bool more) const override
Print a description.
virtual void add_dependency (CodeGenerator &g) const
Add a dependent function.
virtual bool has_refcount () const
Is reference counting needed in codegen?
virtual void codegen_incref (CodeGenerator &g, std::set< void * > &added) const
Codegen incref.
virtual void codegen_decref (CodeGenerator &g, std::set< void * > &added) const
Codegen decref.
void generate_copy (CodeGenerator &g, const std::vector< casadi_int > &arg, const std::vector< casadi_int > &res, const std::vector< bool > &arg_is_ref, std::vector< bool > &res_is_ref, casadi_int i) const
virtual void eval_linear (const std::vector< std::array< MX, 3 > > &arg, std::vector< std::array< MX, 3 > > &res) const
Evaluate the MX node on a const/linear/nonlinear partition.
void eval_linear_unary (const std::vector< std::array< MX, 3 > > &arg, std::vector< std::array< MX, 3 > > &res) const
Evaluate the MX node on a const/linear/nonlinear partition.
void eval_linear_rearrange (const std::vector< std::array< MX, 3 > > &arg, std::vector< std::array< MX, 3 > > &res) const
Evaluate the MX node on a const/linear/nonlinear partition.
virtual const std::string & name () const
Get the name.
std::string class_name () const override
Get name of public class.
virtual bool is_valid_input () const
Check if valid function input.
virtual casadi_int n_primitives () const
Get the number of symbolic primitives.
virtual void primitives (std::vector< MX >::iterator &it) const
Get symbolic primitives.
template<typename T >
T join_primitives_gen (typename std::vector< T >::const_iterator &it) const
Join an expression along symbolic primitives (template)
virtual bool has_duplicates () const
Detect duplicate symbolic expressions.
virtual void reset_input () const
Reset the marker for an input expression.
virtual bool is_output () const
Check if evaluation output.
virtual bool has_output () const
Check if a multiple output node.
virtual casadi_int which_output () const
Get function output.
virtual const Function & which_function () const
Get called function.
virtual Dict info () const
void serialize (SerializingStream &s) const
Serialize an object.
virtual void serialize_body (SerializingStream &s) const
Serialize an object without type information.
virtual void serialize_type (SerializingStream &s) const
Serialize type information.
virtual bool is_equal (const MXNode *node, casadi_int depth) const
bool sameOpAndDeps (const MXNode *node, casadi_int depth) const
Checks if two nodes have the same operation and have.
const MX & dep (casadi_int ind=0) const
dependencies - functions that have to be evaluated before this one
casadi_int n_dep () const
Number of dependencies.
virtual casadi_int nout () const
Number of outputs.
virtual MX get_output (casadi_int oind) const
Get an output.
const Sparsity & sparsity () const
Get the sparsity.
virtual const Sparsity & sparsity (casadi_int oind) const
Get the sparsity of output oind.
template<class T >
bool matches_sparsity (const std::vector< T > &arg) const
casadi_int numel () const
Get shape.
casadi_int nnz (casadi_int i=0) const
casadi_int size1 () const
casadi_int size2 () const
std::pair< casadi_int, casadi_int > size () const
virtual casadi_int ind () const
virtual casadi_int segment () const
virtual casadi_int offset () const
void set_sparsity (const Sparsity &sparsity)
Set the sparsity.
virtual size_t sz_arg () const
Get required length of arg field.
virtual size_t sz_res () const
Get required length of res field.
virtual size_t sz_iw () const
Get required length of iw field.
virtual size_t sz_w () const
Get required length of w field.
void set_dep (const MX &dep)
Set unary dependency.
void set_dep (const MX &dep1, const MX &dep2)
Set binary dependencies.
void set_dep (const MX &dep1, const MX &dep2, const MX &dep3)
Set ternary dependencies.
void set_dep (const std::vector< MX > &dep)
Set multiple dependencies.
void check_dep () const
Check validatity of dependencies.
virtual double to_double () const
Get the value (only for scalar constant nodes)
virtual DM get_DM () const
Get the value (only for constant nodes)
virtual Matrix< casadi_int > mapping () const
Get an IM representation of a GetNonzeros or SetNonzeros node.
virtual MX get_horzcat (const std::vector< MX > &x) const
Create a horizontal concatenation node.
virtual std::vector< MX > get_horzsplit (const std::vector< casadi_int > &output_offset) const
Create a horizontal split node.
virtual MX get_repmat (casadi_int m, casadi_int n) const
Create a repeated matrix node.
virtual MX get_repsum (casadi_int m, casadi_int n) const
Create a repeated sum node.
virtual MX get_vertcat (const std::vector< MX > &x) const
Create a vertical concatenation node (vectors only)
virtual std::vector< MX > get_vertsplit (const std::vector< casadi_int > &output_offset) const
Create a vertical split node (vectors only)
virtual MX get_diagcat (const std::vector< MX > &x) const
Create a diagonal concatenation node.
virtual std::vector< MX > get_diagsplit (const std::vector< casadi_int > &offset1, const std::vector< casadi_int > &offset2) const
Create a diagonal split node.
virtual MX get_transpose () const
Transpose.
virtual MX get_reshape (const Sparsity &sp) const
Reshape.
virtual MX get_sparsity_cast (const Sparsity &sp) const
Sparsity cast.
virtual MX get_mac (const MX &y, const MX &z) const
Matrix multiplication and addition.
virtual MX get_einstein (const MX &A, const MX &B, const std::vector< casadi_int > &dim_c, const std::vector< casadi_int > &dim_a, const std::vector< casadi_int > &dim_b, const std::vector< casadi_int > &c, const std::vector< casadi_int > &a, const std::vector< casadi_int > &b) const
Einstein product and addition.
virtual MX get_bilin (const MX &x, const MX &y) const
Bilinear form.
virtual MX get_rank1 (const MX &alpha, const MX &x, const MX &y) const
Bilinear form.
virtual MX get_logsumexp () const
Logsumexp.
virtual MX get_solve (const MX &r, bool tr, const Linsol &linear_solver) const
Solve a system of linear equations.
virtual MX get_solve_triu (const MX &r, bool tr) const
Solve a system of linear equations, upper triangular A.
virtual MX get_solve_tril (const MX &r, bool tr) const
Solve a system of linear equations, lower triangular A.
virtual MX get_solve_triu_unity (const MX &r, bool tr) const
Solve a system of linear equations, upper triangular A, unity diagonal.
virtual MX get_solve_tril_unity (const MX &r, bool tr) const
Solve a system of linear equations, lower triangular A, unity diagnal.
virtual MX get_nzref (const Sparsity &sp, const std::vector< casadi_int > &nz) const
Get the nonzeros of matrix.
virtual MX get_nz_ref (const MX &nz) const
Get the nonzeros of matrix, parametrically.
virtual MX get_nz_ref (const MX &inner, const Slice &outer) const
Get the nonzeros of matrix, parametrically.
virtual MX get_nz_ref (const Slice &inner, const MX &outer) const
Get the nonzeros of matrix, parametrically.
virtual MX get_nz_ref (const MX &inner, const MX &outer) const
Get the nonzeros of matrix, parametrically.
virtual MX get_nzassign (const MX &y, const std::vector< casadi_int > &nz) const
Assign the nonzeros of a matrix to another matrix.
virtual MX get_nzassign (const MX &y, const MX &nz) const
Assign the nonzeros of a matrix to another matrix, parametrically.
virtual MX get_nzassign (const MX &y, const MX &inner, const Slice &outer) const
Assign the nonzeros of a matrix to another matrix, parametrically.
virtual MX get_nzassign (const MX &y, const Slice &inner, const MX &outer) const
Assign the nonzeros of a matrix to another matrix, parametrically.
virtual MX get_nzassign (const MX &y, const MX &inner, const MX &outer) const
Assign the nonzeros of a matrix to another matrix, parametrically.
virtual MX get_nzadd (const MX &y, const std::vector< casadi_int > &nz) const
Add the nonzeros of a matrix to another matrix.
virtual MX get_nzadd (const MX &y, const MX &nz) const
Add the nonzeros of a matrix to another matrix, parametrically.
virtual MX get_nzadd (const MX &y, const MX &inner, const Slice &outer) const
Add the nonzeros of a matrix to another matrix, parametrically.
virtual MX get_nzadd (const MX &y, const Slice &inner, const MX &outer) const
Add the nonzeros of a matrix to another matrix, parametrically.
virtual MX get_nzadd (const MX &y, const MX &inner, const MX &outer) const
Add the nonzeros of a matrix to another matrix, parametrically.
virtual MX get_subref (const Slice &i, const Slice &j) const
Get submatrix reference.
virtual MX get_subassign (const MX &y, const Slice &i, const Slice &j) const
Get submatrix assignment.
virtual MX get_project (const Sparsity &sp) const
Create set sparse.
virtual MX get_unary (casadi_int op) const
Get a unary operation.
MX get_binary (casadi_int op, const MX &y) const
Get a binary operation operation.
virtual MX _get_binary (casadi_int op, const MX &y, bool scX, bool scY) const
Get a binary operation operation (matrix-matrix)
virtual MX get_det () const
Determinant.
virtual MX get_inv () const
Inverse.
virtual MX get_dot (const MX &y) const
Inner product.
virtual MX get_norm_fro () const
Frobenius norm.
virtual MX get_norm_2 () const
Spectral norm.
virtual MX get_norm_inf () const
Infinity norm.
virtual MX get_norm_1 () const
1-norm
virtual MX get_mmin () const
Min.
virtual MX get_mmax () const
Max.
MX get_assert (const MX &y, const std::string &fail_message) const
Assertion.
MX get_monitor (const std::string &comment) const
Monitor.
MX get_find () const
Find.
MX get_low (const MX &v, const Dict &options) const
Find.
MX get_bspline (const std::vector< double > &knots, const std::vector< casadi_int > &offset, const std::vector< double > &coeffs, const std::vector< casadi_int > &degree, casadi_int m, const std::vector< casadi_int > &lookup_mode) const
BSpline.
MX get_bspline (const MX &coeffs, const std::vector< double > &knots, const std::vector< casadi_int > &offset, const std::vector< casadi_int > &degree, casadi_int m, const std::vector< casadi_int > &lookup_mode) const
BSpline.
MX get_convexify (const Dict &opts) const
Convexify.
casadi_int getCount () const
Get the reference count.
std::string debug_repr (const SharedObjectInternal *) const
GenericWeakRef< SharedObject, SharedObjectInternal > * weak ()
Get a weak reference to the object.
virtual void split_primitives (const MX &x, std::vector< MX >::iterator &it) const
Split up an expression along symbolic primitives.
virtual void split_primitives (const SX &x, std::vector< SX >::iterator &it) const
Split up an expression along symbolic primitives.
virtual void split_primitives (const DM &x, std::vector< DM >::iterator &it) const
Split up an expression along symbolic primitives.
virtual MX join_primitives (std::vector< MX >::const_iterator &it) const
Join an expression along symbolic primitives.
virtual SX join_primitives (std::vector< SX >::const_iterator &it) const
Join an expression along symbolic primitives.
virtual DM join_primitives (std::vector< DM >::const_iterator &it) const
Join an expression along symbolic primitives.
Static Public Member Functions
static MXNode * deserialize (DeserializingStream &s)
Deserialize without type information.
static bool is_equal (const MXNode *x, const MXNode *y, casadi_int depth)
Check if two nodes are equivalent up to a given depth.
static bool maxDepth ()
Get equality checking depth.
static MX to_matrix (const MX &x, const Sparsity &sp)
Convert scalar to matrix.
static void copy_fwd (const bvec_t *arg, bvec_t *res, casadi_int len)
Propagate sparsities forward through a copy operation.
static void copy_rev (bvec_t *arg, bvec_t *res, casadi_int len)
Propagate sparsities backwards through a copy operation.
Public Attributes
casadi_int temp
std::vector< MX > dep_
dependencies - functions that have to be evaluated before this one
Sparsity sparsity_
The sparsity pattern.
Static Public Attributes
static std::map< casadi_int, MXNode *(*)(DeserializingStream &)> deserialize_map
Protected Member Functions
Rank1 (DeserializingStream &s)
void initSingleton ()
void destroySingleton ()
B shared_from_this ()
Get a shared object from the current internal object.
const B shared_from_this () const
Get a shared object from the current internal object.
Member Typedef Documentation
weak_ref_type
using casadi::SharedObjectInternal::weak_ref_type = WeakRefInternal inherited
Definition at line 152 of file shared_object.hpp.
Constructor & Destructor Documentation
Rank1() [1/2]
casadi::Rank1::Rank1 (const MX & A, const MX & alpha, const MX & x, const MX & y)
Definition at line 29 of file rank1.cpp.
{
     set_dep({A, alpha, x, y});
     set_sparsity(A.sparsity());
   }
References casadi::MXNode::set_dep(), casadi::MXNode::set_sparsity(), and casadi::MX::sparsity().
~Rank1()
casadi::Rank1::~Rank1 () inline override
Definition at line 49 of file rank1.hpp.
 {}
Rank1() [2/2]
casadi::Rank1::Rank1 (DeserializingStream & s) inline explicit protected
Definition at line 116 of file rank1.hpp.
 : MXNode(s) {}
Member Function Documentation
__nonzero__()
bool casadi::MXNode::__nonzero__ () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1qd
Reimplemented in casadi::ConstantMX.
Definition at line 202 of file mx_node.cpp.
{
     casadi_error("Can only determine truth value of a numeric MX.");
   }
_get_binary()
MX casadi::MXNode::_get_binary (casadi_int op, const MX & y, bool scX, bool scY) const virtual inherited
Reimplemented in casadi::UnaryMX, casadi::Constant< Value >, casadi::ZeroByZero, and casadi::BinaryMX< ScX, ScY >.
Definition at line 843 of file mx_node.cpp.
{
     casadi_assert_dev(sparsity()==y.sparsity() || scX || scY);
     if (GlobalOptions::simplification_on_the_fly) {
       // If identically zero due to one argument being zero
       if ((operation_checker<F0XChecker>(op) && nnz()==0) ||
          (operation_checker<FX0Checker>(op) && y->nnz()==0)) {
         return MX::zeros(Sparsity(size()));
       }
       if ((operation_checker<F0XChecker>(op) && is_zero()) ||
          (operation_checker<FX0Checker>(op) && y->is_zero())) {
         return MX::zeros(sparsity());
       }
       // Handle special operations (independent of type)
       switch (op) {
       case OP_ADD:
         if (MXNode::is_equal(y.get(), this, maxDepth())) return get_unary(OP_TWICE);
         break;
       case OP_SUB:
       case OP_NE:
       case OP_LT:
         if (MXNode::is_equal(y.get(), this, maxDepth())) return MX::zeros(sparsity());
         break;
       case OP_DIV:
         if (y->is_zero()) return MX::nan(sparsity());
         // fall-through
       case OP_EQ:
       case OP_LE:
         if (MXNode::is_equal(y.get(), this, maxDepth())) return MX::ones(sparsity());
         break;
       case OP_MUL:
         if (MXNode::is_equal(y.get(), this, maxDepth())) return get_unary(OP_SQ);
         break;
       default: break; // no rule
       }
       // Handle special cases for the second argument
       switch (y->op()) {
       case OP_CONST:
         // Make the constant the first argument, if possible
         if (this->op()!=OP_CONST && operation_checker<CommChecker>(op)) {
           return y->_get_binary(op, shared_from_this<MX>(), scY, scX);
         } else {
           switch (op) {
           case OP_POW:
             return _get_binary(OP_CONSTPOW, y, scX, scY);
           case OP_CONSTPOW:
             if (y->is_value(-1)) return get_unary(OP_INV);
             else if (y->is_value(0)) return MX::ones(size());
             else if (y->is_value(1)) return shared_from_this<MX>();
             else if (y->is_value(2)) return get_unary(OP_SQ);
             break;
           case OP_ADD:
           case OP_SUB:
             if (y->is_zero())
                 return scX ? repmat(shared_from_this<MX>(), y.size()) : shared_from_this<MX>();
             break;
           case OP_MUL:
             if (y->is_value(1)) return shared_from_this<MX>();
             break;
           case OP_DIV:
             if (y->is_value(1)) return shared_from_this<MX>();
             else if (y->is_value(0.5)) return get_unary(OP_TWICE);
             break;
           default: break; // no rule
           }
         }
         break;
       case OP_NEG:
         if (op==OP_ADD) {
           return _get_binary(OP_SUB, y->dep(), scX, scY);
         } else if (op==OP_SUB) {
           return _get_binary(OP_ADD, y->dep(), scX, scY);
         } else if (op==OP_MUL) {
           return -_get_binary(OP_MUL, y->dep(), scX, scY);
         } else if (op==OP_DIV) {
           return -_get_binary(OP_DIV, y->dep(), scX, scY);
         }
         break;
       case OP_INV:
         if (op==OP_MUL) {
           return _get_binary(OP_DIV, y->dep(), scX, scY);
         } else if (op==OP_DIV) {
           return _get_binary(OP_MUL, y->dep(), scX, scY);
         }
         break;
       default: break; // no rule
       }
     }
     if (scX) {
       // Check if it is ok to loop over nonzeros only
       if (y.is_dense() || operation_checker<FX0Checker>(op) ||
           (is_zero() && operation_checker<F00Checker>(op))) {
         // Loop over nonzeros
         return MX::create(new BinaryMX<true, false>(Operation(op), shared_from_this<MX>(), y));
       } else {
         // Put a densification node in between
         return _get_binary(op, densify(y), true, false);
       }
     } else if (scY) {
       // Check if it is ok to loop over nonzeros only
       if (sparsity().is_dense() || operation_checker<F0XChecker>(op) ||
           (y.is_zero() && operation_checker<F00Checker>(op)) ||
           (y.is_constant() && static_cast<double>(y)>0 && (op==OP_CONSTPOW || op==OP_POW))) {
         // Loop over nonzeros
         return MX::create(new BinaryMX<false, true>(Operation(op), shared_from_this<MX>(), y));
       } else {
         // Put a densification node in between
         return densify(shared_from_this<MX>())->_get_binary(op, y, false, true);
       }
     } else {
       // Loop over nonzeros only
       MX rr = MX::create(new BinaryMX<false, false>(Operation(op), shared_from_this<MX>(), y));
       // Handle structural zeros giving rise to nonzero result, e.g. cos(0) == 1
       if (!rr.is_dense() && !operation_checker<F00Checker>(op)) {
         // Get the value for the structural zeros
         double fcn_0(0);
         casadi_math<double>::fun(op, 0, 0, fcn_0);
         rr = densify(rr, fcn_0);
       }
       return rr;
     }
   }
References casadi::MXNode::_get_binary(), casadi::MX::create(), casadi::MXNode::dep(), casadi::casadi_math< T >::fun(), casadi::MX::get(), casadi::MXNode::get_unary(), casadi::MX::is_constant(), casadi::GenericMatrix< MatType >::is_dense(), casadi::MXNode::is_equal(), casadi::MXNode::is_value(), casadi::MX::is_zero(), casadi::MXNode::is_zero(), casadi::MXNode::maxDepth(), casadi::MX::nan(), casadi::MXNode::nnz(), casadi::GenericMatrix< MX >::ones(), casadi::MXNode::op(), casadi::OP_ADD, casadi::OP_CONST, casadi::OP_CONSTPOW, casadi::OP_DIV, casadi::OP_EQ, casadi::OP_INV, casadi::OP_LE, casadi::OP_LT, casadi::OP_MUL, casadi::OP_NE, casadi::OP_NEG, casadi::OP_POW, casadi::OP_SQ, casadi::OP_SUB, casadi::OP_TWICE, casadi::GlobalOptions::simplification_on_the_fly, casadi::GenericMatrix< MatType >::size(), casadi::MXNode::size(), casadi::MX::sparsity(), casadi::MXNode::sparsity(), and casadi::GenericMatrix< MX >::zeros().
Referenced by casadi::MXNode::_get_binary(), casadi::BinaryMX< ScX, ScY >::_get_binary(), casadi::Constant< Value >::_get_binary(), casadi::UnaryMX::_get_binary(), casadi::MXNode::get_binary(), and casadi::MX::lift().
ad_forward()
void casadi::Rank1::ad_forward (const std::vector< std::vector< MX > > & fseed, std::vector< std::vector< MX > > & fsens) const override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_5
Reimplemented from casadi::MXNode.
Definition at line 43 of file rank1.cpp.
{
     for (casadi_int d=0; d<fsens.size(); ++d) {
       MX v = project(fseed[d][0], sparsity());
       v = rank1(v, fseed[d][1], dep(2), dep(3));
       v = rank1(v, dep(1), fseed[d][2], dep(3));
       v = rank1(v, dep(1), dep(2), fseed[d][3]);
       fsens[d][0] = v;
     }
   }
References casadi::MXNode::dep(), and casadi::MXNode::sparsity().
ad_reverse()
void casadi::Rank1::ad_reverse (const std::vector< std::vector< MX > > & aseed, std::vector< std::vector< MX > > & asens) const override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_6
Reimplemented from casadi::MXNode.
Definition at line 54 of file rank1.cpp.
{
     for (casadi_int d=0; d<aseed.size(); ++d) {
       asens[d][1] += bilin(aseed[d][0], dep(2), dep(3));
       asens[d][2] += dep(1) * mtimes(aseed[d][0], dep(3));
       asens[d][3] += dep(1) * mtimes(aseed[d][0].T(), dep(2));
       asens[d][0] += aseed[d][0];
     }
   }
References casadi::MXNode::dep(), and casadi::T.
add_dependency()
virtual void casadi::MXNode::add_dependency (CodeGenerator & g) const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1qo
Reimplemented in casadi::ConstantPool, casadi::ConstantFile, and casadi::Call.
Definition at line 122 of file mx_node.hpp.
 {}
can_inline()
void casadi::MXNode::can_inline (std::map< const MXNode *, casadi_int > & nodeind) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1ql
Definition at line 284 of file mx_node.cpp.
{
     // Add or mark node in map
     std::map<const MXNode*, casadi_int>::iterator it=nodeind.find(this);
     if (it==nodeind.end()) {
       // First time encountered, mark inlined
       nodeind.insert(it, std::make_pair(this, 0));
       // Handle dependencies with recursion
       for (casadi_int i=0; i<n_dep(); ++i) {
         dep(i)->can_inline(nodeind);
       }
     } else if (it->second==0 && op()!=OP_PARAMETER) {
       // Node encountered before, do not inline (except if symbolic primitive)
       it->second = -1;
     }
   }
References casadi::MXNode::can_inline(), casadi::MXNode::dep(), casadi::MXNode::n_dep(), casadi::MXNode::op(), and casadi::OP_PARAMETER.
Referenced by casadi::MXNode::can_inline(), and casadi::MXNode::disp().
check_dep()
void casadi::MXNode::check_dep () const inherited
Definition at line 252 of file mx_node.cpp.
{
     for (const MX& e : dep_) {
       if (e->has_output()) {
         casadi_assert(is_output(),
           "You cannot build an expression out of a MultipleOutput node. "
           "You must select a concrete output by making a get_output() call.");
       }
     }
   }
References casadi::MXNode::dep_, and casadi::MXNode::is_output().
Referenced by casadi::MXNode::set_dep().
class_name()
std::string casadi::MXNode::class_name () const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1r1
Implements casadi::SharedObjectInternal.
Definition at line 197 of file mx_node.cpp.
{
     // Lazy solution
     return typeid(*this).name();
   }
Referenced by casadi::MXNode::ad_forward(), casadi::MXNode::ad_reverse(), casadi::MXNode::eval(), casadi::MXNode::eval_mx(), casadi::MXNode::eval_sx(), casadi::MXNode::generate(), casadi::MXNode::get_DM(), casadi::MXNode::has_duplicates(), casadi::MXNode::ind(), casadi::MXNode::mapping(), casadi::MXNode::name(), casadi::MXNode::offset(), casadi::MXNode::reset_input(), casadi::MXNode::segment(), casadi::MXNode::to_double(), casadi::MXNode::which_function(), and casadi::MXNode::which_output().
codegen_decref()
virtual void casadi::MXNode::codegen_decref (CodeGenerator & g, std::set< void * > & added) const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1qr
Reimplemented in casadi::Call.
Definition at line 137 of file mx_node.hpp.
 {}
codegen_incref()
virtual void casadi::MXNode::codegen_incref (CodeGenerator & g, std::set< void * > & added) const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1qq
Reimplemented in casadi::ConstantFile, and casadi::Call.
Definition at line 132 of file mx_node.hpp.
 {}
copy_fwd()
void casadi::MXNode::copy_fwd (const bvec_t * arg, bvec_t * res, casadi_int len) static inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1sl
Definition at line 1241 of file mx_node.cpp.
{
     if (arg!=res) {
       std::copy(arg, arg+len, res);
     }
   }
Referenced by casadi::Multiplication::sp_forward(), casadi::Reshape::sp_forward(), casadi::SparsityCast::sp_forward(), and casadi::UnaryMX::sp_forward().
copy_rev()
void casadi::MXNode::copy_rev (bvec_t * arg, bvec_t * res, casadi_int len) static inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1sm
Definition at line 1247 of file mx_node.cpp.
{
     if (arg!=res) {
       for (casadi_int k=0; k<len; ++k) {
         *arg++ |= *res;
         *res++ = 0;
       }
     }
   }
Referenced by casadi::Einstein::sp_reverse(), casadi::Multiplication::sp_reverse(), sp_reverse(), casadi::Reshape::sp_reverse(), casadi::SetNonzerosVector< Add >::sp_reverse(), casadi::SetNonzerosSlice< Add >::sp_reverse(), casadi::SetNonzerosSlice2< Add >::sp_reverse(), casadi::SparsityCast::sp_reverse(), and casadi::UnaryMX::sp_reverse().
debug_repr()
std::string casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::debug_repr (const Internal * i) const inherited
Definition at line 62 of file generic_shared_internal.hpp.
{
     // Note: i != this because of something something multiple inheritance
     return str( (casadi_int)(i)) + "/" + static_cast<const Internal*>(this)->class_name();
   }
dep()
const MX& casadi::MXNode::dep (casadi_int ind = 0) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1rm
Definition at line 354 of file mx_node.hpp.
 { return dep_.at(ind);}
Referenced by casadi::MXNode::_get_binary(), casadi::UnaryMX::_get_binary(), casadi::Bilin::ad_forward(), casadi::Call::ad_forward(), casadi::Determinant::ad_forward(), casadi::Dot::ad_forward(), casadi::Einstein::ad_forward(), casadi::GetNonzeros::ad_forward(), casadi::GetNonzerosParamVector::ad_forward(), casadi::GetNonzerosSliceParam::ad_forward(), casadi::GetNonzerosParamSlice::ad_forward(), casadi::GetNonzerosParamParam::ad_forward(), casadi::LogSumExp::ad_forward(), casadi::MMin::ad_forward(), casadi::MMax::ad_forward(), casadi::Multiplication::ad_forward(), casadi::NormF::ad_forward(), casadi::Norm1::ad_forward(), casadi::NormInf::ad_forward(), casadi::Project::ad_forward(), ad_forward(), casadi::SparsityCast::ad_forward(), casadi::UnaryMX::ad_forward(), casadi::Bilin::ad_reverse(), casadi::Call::ad_reverse(), casadi::Determinant::ad_reverse(), casadi::Dot::ad_reverse(), casadi::Einstein::ad_reverse(), casadi::GetNonzeros::ad_reverse(), casadi::GetNonzerosParamVector::ad_reverse(), casadi::GetNonzerosSliceParam::ad_reverse(), casadi::GetNonzerosParamSlice::ad_reverse(), casadi::GetNonzerosParamParam::ad_reverse(), casadi::LogSumExp::ad_reverse(), casadi::MMin::ad_reverse(), casadi::MMax::ad_reverse(), casadi::Multiplication::ad_reverse(), casadi::NormF::ad_reverse(), casadi::Norm1::ad_reverse(), casadi::NormInf::ad_reverse(), casadi::Project::ad_reverse(), ad_reverse(), casadi::Reshape::ad_reverse(), casadi::SparsityCast::ad_reverse(), casadi::UnaryMX::ad_reverse(), casadi::MXNode::can_inline(), casadi::MX::dep(), casadi::Reshape::disp(), casadi::Find::eval(), casadi::Low::eval(), casadi::GetNonzerosParamVector::eval(), casadi::GetNonzerosSliceParam::eval(), casadi::GetNonzerosParamSlice::eval(), casadi::GetNonzerosParamParam::eval(), casadi::MMin::eval(), casadi::MMax::eval(), casadi::Bilin::eval_gen(), casadi::Dot::eval_gen(), casadi::Einstein::eval_gen(), casadi::LogSumExp::eval_gen(), casadi::Multiplication::eval_gen(), casadi::NormF::eval_gen(), casadi::Norm1::eval_gen(), casadi::NormInf::eval_gen(), casadi::Project::eval_gen(), casadi::Densify::eval_gen(), eval_gen(), casadi::HorzRepmat::eval_gen(), casadi::Concat::eval_gen(), casadi::Transpose::eval_gen(), casadi::DenseTranspose::eval_gen(), casadi::GetNonzeros::eval_mx(), casadi::GetNonzerosParamVector::eval_mx(), casadi::GetNonzerosSliceParam::eval_mx(), casadi::GetNonzerosParamSlice::eval_mx(), casadi::GetNonzerosParamParam::eval_mx(), casadi::MMin::eval_sx(), casadi::MMax::eval_sx(), casadi::BSplineParametric::generate(), casadi::Bilin::generate(), casadi::Find::generate(), casadi::Low::generate(), casadi::Concat::generate(), casadi::Convexify::generate(), casadi::Dot::generate(), casadi::Einstein::generate(), casadi::GetNonzerosVector::generate(), casadi::GetNonzerosSlice::generate(), casadi::GetNonzerosSlice2::generate(), casadi::GetNonzerosParamVector::generate(), casadi::GetNonzerosSliceParam::generate(), casadi::GetNonzerosParamSlice::generate(), casadi::GetNonzerosParamParam::generate(), casadi::Output::generate(), casadi::LogSumExp::generate(), casadi::MMin::generate(), casadi::MMax::generate(), casadi::Monitor::generate(), casadi::Multiplication::generate(), casadi::DenseMultiplication::generate(), casadi::NormF::generate(), casadi::Norm1::generate(), casadi::NormInf::generate(), casadi::Project::generate(), casadi::Densify::generate(), casadi::Sparsify::generate(), generate(), casadi::HorzRepmat::generate(), casadi::HorzRepsum::generate(), casadi::Split::generate(), casadi::Transpose::generate(), casadi::DenseTranspose::generate(), casadi::MXNode::get_binary(), casadi::Diagsplit::get_diagcat(), casadi::Horzsplit::get_horzcat(), casadi::MXNode::get_horzsplit(), casadi::Concat::get_nzref(), casadi::GetNonzeros::get_nzref(), casadi::SparsityCast::get_nzref(), casadi::Reshape::get_reshape(), casadi::SparsityCast::get_reshape(), casadi::SparsityCast::get_sparsity_cast(), casadi::Reshape::get_transpose(), casadi::SparsityCast::get_transpose(), casadi::UnaryMX::get_unary(), casadi::Vertsplit::get_vertcat(), casadi::MXNode::get_vertsplit(), casadi::Concat::has_duplicates(), casadi::Reshape::has_duplicates(), casadi::SparsityCast::has_duplicates(), casadi::BinaryMX< ScX, ScY >::is_equal(), casadi::Concat::is_valid_input(), casadi::Reshape::is_valid_input(), casadi::SparsityCast::is_valid_input(), casadi::BSpline::jac_cached(), casadi::BSplineParametric::jac_cached(), casadi::Horzcat::join_primitives_gen(), casadi::Vertcat::join_primitives_gen(), casadi::Diagcat::join_primitives_gen(), casadi::Reshape::join_primitives_gen(), casadi::SparsityCast::join_primitives_gen(), casadi::Concat::n_primitives(), casadi::Reshape::n_primitives(), casadi::SparsityCast::n_primitives(), casadi::Horzcat::off(), casadi::Vertcat::off(), casadi::Diagcat::off(), casadi::MX::operator-(), casadi::OutputNode::OutputNode(), casadi::Concat::primitives(), casadi::Reshape::primitives(), casadi::SparsityCast::primitives(), casadi::MXFunction::print_arg(), casadi::MXNode::print_compact(), casadi::Concat::reset_input(), casadi::Reshape::reset_input(), casadi::SparsityCast::reset_input(), casadi::MXNode::sameOpAndDeps(), casadi::MXNode::set_dep(), casadi::MXNode::sp_forward(), casadi::Bilin::sp_forward(), casadi::Concat::sp_forward(), casadi::Dot::sp_forward(), casadi::GetNonzerosParam::sp_forward(), casadi::Multiplication::sp_forward(), casadi::Project::sp_forward(), sp_forward(), casadi::Transpose::sp_forward(), casadi::DenseTranspose::sp_forward(), casadi::MXNode::sp_reverse(), casadi::Bilin::sp_reverse(), casadi::Concat::sp_reverse(), casadi::Dot::sp_reverse(), casadi::GetNonzerosParam::sp_reverse(), casadi::Multiplication::sp_reverse(), casadi::Project::sp_reverse(), casadi::HorzRepmat::sp_reverse(), casadi::Transpose::sp_reverse(), casadi::DenseTranspose::sp_reverse(), casadi::Horzcat::split_primitives_gen(), casadi::Vertcat::split_primitives_gen(), casadi::Diagcat::split_primitives_gen(), casadi::Reshape::split_primitives_gen(), casadi::SparsityCast::split_primitives_gen(), casadi::GetNonzerosParamSlice::sz_iw(), and casadi::GetNonzerosParamParam::sz_iw().
deserialize()
static MXNode* casadi::Rank1::deserialize (DeserializingStream & s) inline static
Extra doc: https://github.com/casadi/casadi/wiki/L_a
Definition at line 113 of file rank1.hpp.
 { return new Rank1(s); }
destroySingleton()
void casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::destroySingleton () inline protected inherited
Called in the destructor of singletons
Definition at line 77 of file generic_shared_internal.hpp.
{
       static_cast<Internal*>(this)->count--;
     }
disp() [1/2]
std::string casadi::Rank1::disp (const std::vector< std::string > & arg) const override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_8
Implements casadi::MXNode.
Definition at line 34 of file rank1.cpp.
{
     return "rank1(" + arg.at(0) + ", " + arg.at(1)
       + ", " + arg.at(2) + ", " + arg.at(3) + ")";
   }
disp() [2/2]
void casadi::MXNode::disp (std::ostream & stream, bool more) const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1r2
Implements casadi::SharedObjectInternal.
Definition at line 267 of file mx_node.cpp.
{
     // Find out which noded can be inlined
     std::map<const MXNode*, casadi_int> nodeind;
     can_inline(nodeind);
     // Print expression
     std::vector<std::string> intermed;
     std::string s = print_compact(nodeind, intermed);
     // Print intermediate expressions
     for (casadi_int i=0; i<intermed.size(); ++i)
       stream << "@" << (i+1) << "=" << intermed[i] << ", ";
     // Print this
     stream << s;
   }
References casadi::MXNode::can_inline(), and casadi::MXNode::print_compact().
eval()
int casadi::Rank1::eval (const double ** arg, double ** res, casadi_int * iw, double * w) const override virtual
Reimplemented from casadi::MXNode.
Definition at line 64 of file rank1.cpp.
{
     return eval_gen<double>(arg, res, iw, w);
   }
eval_gen()
template<typename T > int casadi::Rank1::eval_gen (const T ** arg, T ** res, casadi_int * iw, T * w) const
Definition at line 73 of file rank1.cpp.
{
     if (arg[0]!=res[0]) casadi_copy(arg[0], dep(0).nnz(), res[0]);
     casadi_rank1(res[0], sparsity(), *arg[1], arg[2], arg[3]);
     return 0;
   }
References casadi::casadi_copy(), casadi::casadi_rank1(), casadi::MXNode::dep(), casadi::MXNode::nnz(), and casadi::MXNode::sparsity().
eval_linear()
void casadi::MXNode::eval_linear (const std::vector< std::array< MX, 3 > > & arg, std::vector< std::array< MX, 3 > > & res) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_28b
Reimplemented in casadi::UnaryMX, casadi::Transpose, casadi::Split, casadi::SparsityCast, casadi::SetNonzeros< Add >, casadi::Reshape, casadi::HorzRepmat, casadi::Project, casadi::Multiplication, casadi::Monitor, casadi::GetNonzeros, casadi::Dot, casadi::Concat, and casadi::BinaryMX< ScX, ScY >.
Definition at line 352 of file mx_node.cpp.
{
     std::vector<MX> arg_sum(arg.size());
     for (casadi_int i=0; i<arg.size(); ++i) {
       arg_sum[i] = arg[i][0] + arg[i][1] + arg[i][2];
     }
     std::vector<MX> res_nonlin(res.size());
     eval_mx(arg_sum, res_nonlin);
     for (casadi_int i=0; i<res.size(); ++i) {
       res[i][0] = MX::zeros(sparsity());
       res[i][1] = MX::zeros(sparsity());
       res[i][2] = res_nonlin[i];
     }
   }
References casadi::MXNode::eval_mx(), casadi::MXNode::sparsity(), and casadi::GenericMatrix< MX >::zeros().
eval_linear_rearrange()
void casadi::MXNode::eval_linear_rearrange (const std::vector< std::array< MX, 3 > > & arg, std::vector< std::array< MX, 3 > > & res) const inherited
Default implementation for operations that do not modify numerical values, but only rearrange them.
Extra doc: https://github.com/casadi/casadi/wiki/L_2cj
Definition at line 367 of file mx_node.cpp.
{
     // Treat each category separately
     for (casadi_int i=0; i<3; ++i) {
       // Read arguments for categiry i
       std::vector<MX> eval_arg(n_dep());
       for (casadi_int j=0; j<n_dep(); ++j) {
         eval_arg[j] = arg[j][i];
       }
       std::vector<MX> eval_res(nout());
       // Normal symbolic evaluation
       eval_mx(eval_arg, eval_res);
       // Assign results
       for (casadi_int j=0; j<nout(); ++j) {
         res[j][i] = eval_res[j];
       }
     }
   }
References casadi::MXNode::eval_mx(), casadi::MXNode::n_dep(), and casadi::MXNode::nout().
Referenced by casadi::GetNonzeros::eval_linear().
eval_linear_unary()
void casadi::MXNode::eval_linear_unary (const std::vector< std::array< MX, 3 > > & arg, std::vector< std::array< MX, 3 > > & res) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_28c
eval_mx()
void casadi::Rank1::eval_mx (const std::vector< MX > & arg, std::vector< MX > & res) const override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_4
Reimplemented from casadi::MXNode.
Definition at line 39 of file rank1.cpp.
{
     res[0] = rank1(arg[0], arg[1], arg[2], arg[3]);
   }
eval_sx()
int casadi::Rank1::eval_sx (const SXElem ** arg, SXElem ** res, casadi_int * iw, SXElem * w) const override virtual
Reimplemented from casadi::MXNode.
Definition at line 68 of file rank1.cpp.
{
     return eval_gen<SXElem>(arg, res, iw, w);
   }
generate()
void casadi::Rank1::generate (CodeGenerator & g, const std::vector< casadi_int > & arg, const std::vector< casadi_int > & res, const std::vector< bool > & arg_is_ref, std::vector< bool > & res_is_ref) const override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_7
Reimplemented from casadi::MXNode.
Definition at line 127 of file rank1.cpp.
{
     // Copy first argument if not inplace
     if (arg[0]!=res[0] || arg_is_ref[0]) {
       g << g.copy(g.work(arg[0], nnz(), arg_is_ref[0]),
               nnz(),
               g.work(res[0], nnz(), false)) << "\n";
     }
     // First argument of casadi_rank1 is non-const
     std::string a = g.work(res[0], dep(0).nnz(), false);
     std::string b = g.work(arg[2], dep(2).nnz(), arg_is_ref[2]);
     std::string c = g.work(arg[3], dep(3).nnz(), arg_is_ref[3]);
     // Perform operation inplace
     g << g.rank1(a, sparsity(), g.workel(arg[1]), b, c) << "\n";
   }
References casadi::CodeGenerator::copy(), casadi::MXNode::dep(), casadi::MXNode::nnz(), casadi::CodeGenerator::rank1(), casadi::MXNode::sparsity(), casadi::CodeGenerator::work(), and casadi::CodeGenerator::workel().
generate_copy()
void casadi::MXNode::generate_copy (CodeGenerator & g, const std::vector< casadi_int > & arg, const std::vector< casadi_int > & res, const std::vector< bool > & arg_is_ref, std::vector< bool > & res_is_ref, casadi_int i) const inherited
Definition at line 457 of file mx_node.cpp.
{
     res_is_ref[i] = arg_is_ref[i];
     if (arg[i]==res[i]) return;
     if (nnz()==1) {
       g << g.workel(res[i]) << " = " << g.workel(arg[i]) << ";\n";
     } else if (arg_is_ref[i]) {
       g << g.work(res[i], nnz(), true) << " = " << g.work(arg[i], nnz(), true) << ";\n";
     } else {
       g << g.copy(g.work(arg[i], nnz(), false), nnz(), g.work(res[i], nnz(), false)) << "\n";
     }
   }
References casadi::CodeGenerator::copy(), casadi::MXNode::nnz(), casadi::CodeGenerator::work(), and casadi::CodeGenerator::workel().
Referenced by casadi::Assertion::generate(), casadi::Monitor::generate(), casadi::Reshape::generate(), and casadi::SparsityCast::generate().
get_assert()
MX casadi::MXNode::get_assert (const MX & y, const std::string & fail_message) const inherited
Definition at line 987 of file mx_node.cpp.
{
     return MX::create(new Assertion(shared_from_this<MX>(), y, fail_message));
   }
References casadi::MX::create().
get_bilin()
MX casadi::MXNode::get_bilin (const MX & x, const MX & y) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1rw
Definition at line 605 of file mx_node.cpp.
{
     return MX::create(new Bilin(shared_from_this<MX>(), x, y));
   }
References casadi::MX::create().
Referenced by casadi::MX::_bilin().
get_binary()
MX casadi::MXNode::get_binary (casadi_int op, const MX & y) const inherited
Definition at line 788 of file mx_node.cpp.
{
     // If-else-zero nodes are always simplified at top level to avoid NaN propagation
     if (y.op() == OP_IF_ELSE_ZERO) {
       if (op == OP_MUL) {
         // (Rule 1.) x * if_else_zero(c, y), simplified to if_else_zero(c, x * y)
         // Background: x is often a partial derivative and may evaluate to INF or NAN.
         // The simplification ensures that the zero seed corresponding to an inactive branch does
         // not give rise to any NaN contribution to the derivative due to NaN * 0 == NaN.
         return if_else_zero(y.dep(0), shared_from_this<MX>() * y.dep(1));
       } else if (op == OP_ADD && this->op() == OP_IF_ELSE_ZERO && MX::is_equal(dep(0), y.dep(0))) {
         // (Rule 2.) if_else_zero(c, x) + if_else_zero(c, y) is simplified to if_else_zero(c, x + y)
         // Background: During the backward propagation, seeds are added together. Without this rule,
         // the addition node can prevent rule (1.) from working in subsequent steps.
         return if_else_zero(y.dep(0), dep(1) + y.dep(1));
       }
     } else if (this->op() == OP_IF_ELSE_ZERO && op == OP_MUL) {
       // Same as Rule 1. above, but with factors swapped. For symmetry.
       return if_else_zero(dep(0), dep(1) * y);
     }
     // Create binary node
     if (sparsity().is_scalar(false)) {
       if (nnz()==0) {
         if (operation_checker<F0XChecker>(op)) return MX::zeros(Sparsity(y.size()));
         return to_matrix(MX(0)->_get_binary(op, y, true, false), y.sparsity());
       } else {
         return to_matrix(_get_binary(op, y, true, false), y.sparsity());
       }
     } else if (y.is_scalar()) {
       if (y.nnz()==0) {
         if (operation_checker<FX0Checker>(op)) return MX::zeros(Sparsity(size()));
         return to_matrix(_get_binary(op, MX(0), false, true), sparsity());
       } else {
         return to_matrix(_get_binary(op, y, false, true), sparsity());
       }
     } else {
       casadi_assert(sparsity().size() == y.sparsity().size(), "Dimension mismatch.");
       if (sparsity()==y.sparsity()) {
         // Matching sparsities
         return _get_binary(op, y, false, false);
       } else {
         // Get the sparsity pattern of the result
         // (ignoring structural zeros giving rise to nonzero result)
         const Sparsity& x_sp = sparsity();
         const Sparsity& y_sp = y.sparsity();
         Sparsity r_sp = x_sp.combine(y_sp, operation_checker<F0XChecker>(op),
                                             operation_checker<FX0Checker>(op));
         // Project the arguments to this sparsity
         MX xx = project(shared_from_this<MX>(), r_sp);
         MX yy = project(y, r_sp);
         return xx->_get_binary(op, yy, false, false);
       }
     }
   }
References casadi::MXNode::_get_binary(), casadi::Sparsity::combine(), casadi::MX::dep(), casadi::MXNode::dep(), casadi::if_else_zero(), casadi::MX::is_equal(), casadi::GenericMatrix< MatType >::is_scalar(), casadi::MXNode::MX, casadi::GenericMatrix< MatType >::nnz(), casadi::MXNode::nnz(), casadi::MX::op(), casadi::MXNode::op(), casadi::OP_ADD, casadi::OP_IF_ELSE_ZERO, casadi::OP_MUL, casadi::GenericMatrix< MatType >::size(), casadi::MXNode::size(), casadi::Sparsity::size(), casadi::MX::sparsity(), casadi::MXNode::sparsity(), casadi::MXNode::to_matrix(), and casadi::GenericMatrix< MX >::zeros().
Referenced by casadi::MX::binary(), and casadi::MXNode::get_dot().
get_bspline() [1/2]
MX casadi::MXNode::get_bspline (const MX & coeffs, const std::vector< double > & knots, const std::vector< casadi_int > & offset, const std::vector< casadi_int > & degree, casadi_int m, const std::vector< casadi_int > & lookup_mode) const inherited
Definition at line 1023 of file mx_node.cpp.
{
     MX x = shared_from_this<MX>();
     return MX::create(new BSplineParametric(x, coeffs, knots, offset, degree, m, lookup_mode));
   }
References casadi::MX::create(), and casadi::MXNode::offset().
get_bspline() [2/2]
MX casadi::MXNode::get_bspline (const std::vector< double > & knots, const std::vector< casadi_int > & offset, const std::vector< double > & coeffs, const std::vector< casadi_int > & degree, casadi_int m, const std::vector< casadi_int > & lookup_mode) const inherited
Definition at line 1013 of file mx_node.cpp.
{
     MX x = shared_from_this<MX>();
     return MX::create(new BSpline(x, knots, offset, coeffs, degree, m, lookup_mode));
   }
References casadi::MX::create(), and casadi::MXNode::offset().
Referenced by casadi::BSplineParametric::create(), and casadi::BSpline::create().
get_convexify()
MX casadi::MXNode::get_convexify (const Dict & opts) const inherited
Definition at line 1033 of file mx_node.cpp.
{
     return MX::create(new Convexify(shared_from_this<MX>(), opts));
   }
References casadi::MX::create().
Referenced by casadi::MX::convexify().
get_det()
MX casadi::MXNode::get_det () const virtual inherited
Definition at line 1037 of file mx_node.cpp.
{
     return MX::create(new Determinant(shared_from_this<MX>()));
   }
References casadi::MX::create().
Referenced by casadi::MX::det().
get_diagcat()
MX casadi::MXNode::get_diagcat (const std::vector< MX > & x) const virtual inherited
Reimplemented in casadi::Diagsplit.
Definition at line 1118 of file mx_node.cpp.
{
     // Create a Horzcat node
     return MX::create(new Diagcat(x));
   }
References casadi::MX::create().
Referenced by casadi::Diagsplit::get_diagcat().
get_diagsplit()
std::vector< MX > casadi::MXNode::get_diagsplit (const std::vector< casadi_int > & offset1, const std::vector< casadi_int > & offset2) const virtual inherited
Definition at line 1193 of file mx_node.cpp.
{
     if (is_zero()) {
       std::vector<MX> ret =
           MX::createMultipleOutput(new Diagsplit(shared_from_this<MX>(), offset1, offset2));
       for (casadi_int i=0;i<ret.size();++i) {
         ret[i]=MX::zeros(ret[i].sparsity());
       }
       return ret;
     }
     std::vector<MX> ret =
         MX::createMultipleOutput(new Diagsplit(shared_from_this<MX>(), offset1, offset2));
     return ret;
   }
References casadi::MX::createMultipleOutput(), casadi::MXNode::is_zero(), casadi::MXNode::sparsity(), and casadi::GenericMatrix< MX >::zeros().
Referenced by casadi::MX::diagsplit().
get_DM()
DM casadi::MXNode::get_DM () const virtual inherited
Reimplemented in casadi::ConstantMX, casadi::Constant< Value >, casadi::ZeroByZero, casadi::ConstantPool, casadi::ConstantFile, and casadi::ConstantDM.
Definition at line 480 of file mx_node.cpp.
{
     casadi_error("'get_DM' not defined for class " + class_name());
   }
References casadi::MXNode::class_name().
Referenced by casadi::ConstantMX::get_dot(), and casadi::MXNode::get_einstein().
get_dot()
MX casadi::MXNode::get_dot (const MX & y) const virtual inherited
Reimplemented in casadi::ConstantMX.
Definition at line 1046 of file mx_node.cpp.
{
     casadi_assert(
       size2()==y.size2() && size1()==y.size1(),
       "MXNode::dot: Dimension mismatch. dot requires its "
       "two arguments to have equal shapes, but got ("
       + str(size2()) + ", " + str(size1()) + ") and ("
       + str(y.size2()) + ", " + str(y.size1()) + ").");
     if (sparsity()==y.sparsity()) {
       if (sparsity().nnz()==0) {
         return 0;
       } else if (sparsity().is_scalar()) {
         return get_binary(OP_MUL, y);
       } else {
         if (shared_from_this<MX>().is_zero() || y.is_zero()) return 0;
         return MX::create(new Dot(shared_from_this<MX>(), y));
       }
     } else {
       // Project to pattern intersection
       Sparsity sp = sparsity().intersect(y.sparsity());
       MX xx = project(shared_from_this<MX>(), sp);
       MX yy = project(y, sp);
       return xx->get_dot(yy);
     }
   }
References casadi::MX::create(), casadi::MXNode::get_binary(), casadi::MXNode::get_dot(), casadi::Sparsity::intersect(), casadi::MX::is_zero(), casadi::MXNode::is_zero(), casadi::MXNode::nnz(), casadi::OP_MUL, casadi::GenericMatrix< MatType >::size1(), casadi::MXNode::size1(), casadi::GenericMatrix< MatType >::size2(), casadi::MXNode::size2(), casadi::MX::sparsity(), casadi::MXNode::sparsity(), and casadi::str().
Referenced by casadi::Dot::ad_forward(), casadi::NormF::ad_forward(), casadi::Norm1::ad_forward(), casadi::MX::dot(), casadi::MXNode::get_dot(), and casadi::ConstantMX::get_dot().
get_einstein()
MX casadi::MXNode::get_einstein (const MX & A, const MX & B, const std::vector< casadi_int > & dim_c, const std::vector< casadi_int > & dim_a, const std::vector< casadi_int > & dim_b, const std::vector< casadi_int > & c, const std::vector< casadi_int > & a, const std::vector< casadi_int > & b) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1rv
Definition at line 582 of file mx_node.cpp.
{
     if (A.is_zero() || B.is_zero())
       return shared_from_this<MX>();
     MX C = densify(shared_from_this<MX>());
     if (A.is_constant() && B.is_constant() && C.is_constant()) {
       // Constant folding
       DM Ac = A->get_DM();
       DM Bc = B->get_DM();
       DM Cc = C->get_DM();
       return einstein(vec(densify(Ac)), vec(densify(Bc)), vec(densify(Cc)),
         dim_a, dim_b, dim_c, a, b, c);
     }
     return MX::create(new Einstein(C, densify(A), densify(B), dim_c, dim_a, dim_b, c, a, b));
   }
References casadi::C, casadi::MX::create(), casadi::MXNode::get_DM(), casadi::MX::is_constant(), and casadi::MX::is_zero().
Referenced by casadi::MX::einstein().
get_find()
MX casadi::MXNode::get_find () const inherited
Definition at line 999 of file mx_node.cpp.
{
     MX x = shared_from_this<MX>();
     casadi_assert(x.is_vector(), "Argument must be vector, got " + x.dim() + ".");
     if (x.is_column()) {
       return MX::create(new Find(shared_from_this<MX>()));
     } else {
       return find(x.T());
     }
   }
References casadi::MX::create(), casadi::GenericMatrix< MatType >::dim(), casadi::find(), casadi::GenericMatrix< MatType >::is_column(), casadi::GenericMatrix< MatType >::is_vector(), and casadi::MX::T().
Referenced by casadi::MX::find().
get_horzcat()
MX casadi::MXNode::get_horzcat (const std::vector< MX > & x) const virtual inherited
Reimplemented in casadi::Horzsplit, casadi::OutputNode, and casadi::Constant< Value >.
Definition at line 1097 of file mx_node.cpp.
{
     // Check if there is any existing horzcat operation
     for (auto i=x.begin(); i!=x.end(); ++i) {
       if (i->op()==OP_HORZCAT) {
         // Split up
         std::vector<MX> x_split(x.begin(), i);
         for (; i!=x.end(); ++i) {
           if (i->op()==OP_HORZCAT) {
             x_split.insert(x_split.end(), (*i)->dep_.begin(), (*i)->dep_.end());
           } else {
             x_split.push_back(*i);
           }
         }
         return horzcat(x_split);
       }
     }
     // Create a Horzcat node
     return MX::create(new Horzcat(x));
   }
References casadi::MX::create(), and casadi::OP_HORZCAT.
Referenced by casadi::Constant< Value >::get_horzcat(), casadi::OutputNode::get_horzcat(), and casadi::Horzsplit::get_horzcat().
get_horzsplit()
std::vector< MX > casadi::MXNode::get_horzsplit (const std::vector< casadi_int > & output_offset) const virtual inherited
Definition at line 1143 of file mx_node.cpp.
{
     if (is_zero()) {
       std::vector<MX> ret =
           MX::createMultipleOutput(new Horzsplit(shared_from_this<MX>(), output_offset));
       for (casadi_int i=0;i<ret.size();++i) {
         ret[i]=MX::zeros(ret[i].sparsity());
       }
       return ret;
     }
     std::vector<MX> ret =
         MX::createMultipleOutput(new Horzsplit(shared_from_this<MX>(), output_offset));
     if (GlobalOptions::simplification_on_the_fly) {
       // Simplify horzsplit(horzcat)
       if (op()==OP_HORZCAT) {
         casadi_int offset_deps = 0;
         casadi_int j = 0;
         for (casadi_int i=0;i<output_offset.size();++i) {
           while (offset_deps<output_offset[i]) { offset_deps+=dep(j).size2();++j; }
           if (j>=n_dep()) j = n_dep()-1;
           if (output_offset[i]==offset_deps &&
               (i+1<output_offset.size()?output_offset[i+1]:size2()) ==
                offset_deps +dep(j).size2()) {
             // Aligned with vertcat dependency
             ret[i] = dep(j);
           }
         }
       }
     }
     return ret;
   }
References casadi::MX::createMultipleOutput(), casadi::MXNode::dep(), casadi::MXNode::is_zero(), casadi::MXNode::n_dep(), casadi::MXNode::op(), casadi::OP_HORZCAT, casadi::GlobalOptions::simplification_on_the_fly, casadi::GenericMatrix< MatType >::size2(), casadi::MXNode::size2(), casadi::MXNode::sparsity(), and casadi::GenericMatrix< MX >::zeros().
Referenced by casadi::MX::horzsplit().
get_inv()
MX casadi::MXNode::get_inv () const virtual inherited
Definition at line 1041 of file mx_node.cpp.
{
     return MX::create(new Inverse(shared_from_this<MX>()));
   }
References casadi::MX::create().
Referenced by casadi::MX::inv_node().
get_logsumexp()
MX casadi::MXNode::get_logsumexp () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1ry
Definition at line 613 of file mx_node.cpp.
{
     return MX::create(new LogSumExp(shared_from_this<MX>()));
   }
References casadi::MX::create().
Referenced by casadi::MX::_logsumexp().
get_low()
MX casadi::MXNode::get_low (const MX & v, const Dict & options) const inherited
Definition at line 1009 of file mx_node.cpp.
{
     return MX::create(new Low(v, shared_from_this<MX>(), options));
   }
References casadi::MX::create().
Referenced by casadi::MX::low().
get_mac()
MX casadi::MXNode::get_mac (const MX & y, const MX & z) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1ru
Definition at line 559 of file mx_node.cpp.
{
     if (sparsity().is_orthonormal() && y.is_column() && y.is_dense()
         && y.sparsity()==z.sparsity() && z.is_zero()) {
       std::vector<casadi_int> perm = sparsity().permutation_vector();
       MX nz = sparsity_cast(shared_from_this<MX>(), Sparsity::dense(nnz()));
       return (nz*y)(perm);
     }
     // Get reference to transposed first argument
     MX x = shared_from_this<MX>();
     casadi_assert(y.size2()==z.size2(),
       "Dimension error x.mac(z). Got y=" + str(y.size2()) + " and z=" + z.dim() + ".");
     casadi_assert(x.size1()==z.size1(),
       "Dimension error x.mac(z). Got x=" + x.dim() + " and z=" + z.dim() + ".");
     casadi_assert(y.size1()==x.size2(),
       "Dimension error x.mac(z). Got y=" + str(y.size1()) + " and x" + x.dim() + ".");
     if (x.is_dense() && y.is_dense() && z.is_dense()) {
       return MX::create(new DenseMultiplication(z, x, y));
     } else {
       return MX::create(new Multiplication(z, x, y));
     }
   }
References casadi::MX::create(), casadi::Sparsity::dense(), casadi::GenericMatrix< MatType >::dim(), casadi::GenericMatrix< MatType >::is_column(), casadi::GenericMatrix< MatType >::is_dense(), casadi::MX::is_zero(), casadi::MXNode::nnz(), casadi::Sparsity::permutation_vector(), casadi::GenericMatrix< MatType >::size1(), casadi::GenericMatrix< MatType >::size2(), casadi::MX::sparsity(), casadi::MXNode::sparsity(), and casadi::str().
Referenced by casadi::MX::mac().
get_mmax()
MX casadi::MXNode::get_mmax () const virtual inherited
Definition at line 1092 of file mx_node.cpp.
{
     if (sparsity_.is_empty()) return MX();
     return MX::create(new MMax(shared_from_this<MX>()));
   }
References casadi::MX::create(), casadi::Sparsity::is_empty(), casadi::MXNode::MX, and casadi::MXNode::sparsity_.
Referenced by casadi::MX::mmax().
get_mmin()
MX casadi::MXNode::get_mmin () const virtual inherited
Definition at line 1087 of file mx_node.cpp.
{
     if (sparsity_.is_empty()) return MX();
     return MX::create(new MMin(shared_from_this<MX>()));
   }
References casadi::MX::create(), casadi::Sparsity::is_empty(), casadi::MXNode::MX, and casadi::MXNode::sparsity_.
Referenced by casadi::MX::mmin().
get_monitor()
MX casadi::MXNode::get_monitor (const std::string & comment) const inherited
Definition at line 991 of file mx_node.cpp.
{
     if (nnz()==0) {
       return shared_from_this<MX>();
     } else {
       return MX::create(new Monitor(shared_from_this<MX>(), comment));
     }
   }
References casadi::MX::create(), and casadi::MXNode::nnz().
Referenced by casadi::MX::monitor().
get_norm_1()
MX casadi::MXNode::get_norm_1 () const virtual inherited
Definition at line 1083 of file mx_node.cpp.
{
     return MX::create(new Norm1(shared_from_this<MX>()));
   }
References casadi::MX::create().
Referenced by casadi::MX::norm_1().
get_norm_2()
MX casadi::MXNode::get_norm_2 () const virtual inherited
Definition at line 1075 of file mx_node.cpp.
{
     return MX::create(new Norm2(shared_from_this<MX>()));
   }
References casadi::MX::create().
Referenced by casadi::MX::norm_2().
get_norm_fro()
MX casadi::MXNode::get_norm_fro () const virtual inherited
Definition at line 1071 of file mx_node.cpp.
{
     return MX::create(new NormF(shared_from_this<MX>()));
   }
References casadi::MX::create().
Referenced by casadi::MX::norm_fro().
get_norm_inf()
MX casadi::MXNode::get_norm_inf () const virtual inherited
Definition at line 1079 of file mx_node.cpp.
{
     return MX::create(new NormInf(shared_from_this<MX>()));
   }
References casadi::MX::create().
Referenced by casadi::MX::norm_inf().
get_nz_ref() [1/4]
MX casadi::MXNode::get_nz_ref (const MX & inner, const MX & outer) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1s8
Definition at line 684 of file mx_node.cpp.
{
     return GetNonzerosParam::create(shared_from_this<MX>(), inner, outer);
   }
References casadi::GetNonzerosParam::create().
get_nz_ref() [2/4]
MX casadi::MXNode::get_nz_ref (const MX & inner, const Slice & outer) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1s6
Definition at line 668 of file mx_node.cpp.
{
     if (outer.all()==std::vector<casadi_int>{0}) {
       return get_nz_ref(inner);
     } else {
       return GetNonzerosParam::create(shared_from_this<MX>(), inner, outer);
     }
   }
References casadi::Slice::all(), casadi::GetNonzerosParam::create(), and casadi::MXNode::get_nz_ref().
get_nz_ref() [3/4]
MX casadi::MXNode::get_nz_ref (const MX & nz) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1s5
Definition at line 664 of file mx_node.cpp.
{
     return GetNonzerosParam::create(shared_from_this<MX>(), nz);
   }
References casadi::GetNonzerosParam::create().
Referenced by casadi::GetNonzerosParamVector::ad_forward(), casadi::GetNonzerosSliceParam::ad_forward(), casadi::GetNonzerosParamSlice::ad_forward(), casadi::GetNonzerosParamParam::ad_forward(), casadi::SetNonzerosParamVector< Add >::ad_reverse(), casadi::SetNonzerosParamSlice< Add >::ad_reverse(), casadi::SetNonzerosSliceParam< Add >::ad_reverse(), casadi::SetNonzerosParamParam< Add >::ad_reverse(), casadi::MX::get(), casadi::MX::get_nz(), and casadi::MXNode::get_nz_ref().
get_nz_ref() [4/4]
MX casadi::MXNode::get_nz_ref (const Slice & inner, const MX & outer) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1s7
Definition at line 676 of file mx_node.cpp.
{
     if (inner.all()==std::vector<casadi_int>{0}) {
       return get_nz_ref(outer);
     } else {
       return GetNonzerosParam::create(shared_from_this<MX>(), inner, outer);
     }
   }
References casadi::Slice::all(), casadi::GetNonzerosParam::create(), and casadi::MXNode::get_nz_ref().
get_nzadd() [1/5]
MX casadi::MXNode::get_nzadd (const MX & y, const MX & inner, const MX & outer) const virtual inherited
a->get_nzadd(b,nz) returns b with b[nz]+=a
Extra doc: https://github.com/casadi/casadi/wiki/L_1si
Definition at line 748 of file mx_node.cpp.
{
     if (inner.is_empty() || outer.is_empty() || is_zero()) {
       return y;
     } else {
       return SetNonzerosParam<true>::create(y, shared_from_this<MX>(), inner, outer);
     }
   }
References casadi::SetNonzerosParam< Add >::create(), casadi::GenericMatrix< MatType >::is_empty(), and casadi::MXNode::is_zero().
get_nzadd() [2/5]
MX casadi::MXNode::get_nzadd (const MX & y, const MX & inner, const Slice & outer) const virtual inherited
a->get_nzadd(b,nz) returns b with b[nz]+=a
Extra doc: https://github.com/casadi/casadi/wiki/L_1sg
Definition at line 732 of file mx_node.cpp.
{
     if (inner.is_empty() || outer.is_empty() || is_zero()) {
       return y;
     } else {
       return SetNonzerosParam<true>::create(y, shared_from_this<MX>(), inner, outer);
     }
   }
References casadi::SetNonzerosParam< Add >::create(), casadi::Slice::is_empty(), casadi::GenericMatrix< MatType >::is_empty(), and casadi::MXNode::is_zero().
get_nzadd() [3/5]
MX casadi::MXNode::get_nzadd (const MX & y, const MX & nz) const virtual inherited
a->get_nzadd(b,nz) returns b with b[nz]+=a
Extra doc: https://github.com/casadi/casadi/wiki/L_1sf
Definition at line 724 of file mx_node.cpp.
{
     if (nz.is_empty() || is_zero()) {
       return y;
     } else {
       return SetNonzerosParam<true>::create(y, shared_from_this<MX>(), nz);
     }
   }
References casadi::SetNonzerosParam< Add >::create(), casadi::GenericMatrix< MatType >::is_empty(), and casadi::MXNode::is_zero().
get_nzadd() [4/5]
MX casadi::MXNode::get_nzadd (const MX & y, const Slice & inner, const MX & outer) const virtual inherited
a->get_nzadd(b,nz) returns b with b[nz]+=a
Extra doc: https://github.com/casadi/casadi/wiki/L_1sh
Definition at line 740 of file mx_node.cpp.
{
     if (outer.is_empty() || outer.is_empty() || is_zero()) {
       return y;
     } else {
       return SetNonzerosParam<true>::create(y, shared_from_this<MX>(), inner, outer);
     }
   }
References casadi::SetNonzerosParam< Add >::create(), casadi::GenericMatrix< MatType >::is_empty(), and casadi::MXNode::is_zero().
get_nzadd() [5/5]
MX casadi::MXNode::get_nzadd (const MX & y, const std::vector< casadi_int > & nz) const virtual inherited
a->get_nzadd(b,nz) returns b with b[nz]+=a
Extra doc: https://github.com/casadi/casadi/wiki/L_1sa
Definition at line 700 of file mx_node.cpp.
{
     if (nz.empty() || is_zero()) {
       return y;
     } else {
       return SetNonzeros<true>::create(y, shared_from_this<MX>(), nz);
     }
   }
References casadi::SetNonzeros< Add >::create(), and casadi::MXNode::is_zero().
Referenced by casadi::SetNonzeros< Add >::ad_forward(), casadi::SetNonzerosParamVector< Add >::ad_forward(), casadi::SetNonzerosParamSlice< Add >::ad_forward(), casadi::SetNonzerosSliceParam< Add >::ad_forward(), casadi::SetNonzerosParamParam< Add >::ad_forward(), casadi::GetNonzeros::ad_reverse(), casadi::GetNonzerosParamVector::ad_reverse(), casadi::GetNonzerosSliceParam::ad_reverse(), casadi::GetNonzerosParamSlice::ad_reverse(), casadi::GetNonzerosParamParam::ad_reverse(), casadi::SetNonzerosParamVector< Add >::eval_mx(), casadi::SetNonzerosParamSlice< Add >::eval_mx(), casadi::SetNonzerosSliceParam< Add >::eval_mx(), and casadi::SetNonzerosParamParam< Add >::eval_mx().
get_nzassign() [1/5]
MX casadi::MXNode::get_nzassign (const MX & y, const MX & inner, const MX & outer) const virtual inherited
a->get_nzassign(b,nz) returns b with b[nz]=a
Extra doc: https://github.com/casadi/casadi/wiki/L_1se
Definition at line 720 of file mx_node.cpp.
{
     return SetNonzerosParam<false>::create(y, shared_from_this<MX>(), inner, outer);
   }
References casadi::SetNonzerosParam< Add >::create().
get_nzassign() [2/5]
MX casadi::MXNode::get_nzassign (const MX & y, const MX & inner, const Slice & outer) const virtual inherited
a->get_nzassign(b,nz) returns b with b[nz]=a
Extra doc: https://github.com/casadi/casadi/wiki/L_1sc
Definition at line 712 of file mx_node.cpp.
{
     return SetNonzerosParam<false>::create(y, shared_from_this<MX>(), inner, outer);
   }
References casadi::SetNonzerosParam< Add >::create().
get_nzassign() [3/5]
MX casadi::MXNode::get_nzassign (const MX & y, const MX & nz) const virtual inherited
a->get_nzassign(b,nz) returns b with b[nz]=a
Extra doc: https://github.com/casadi/casadi/wiki/L_1sb
Definition at line 708 of file mx_node.cpp.
{
     return SetNonzerosParam<false>::create(y, shared_from_this<MX>(), nz);
   }
References casadi::SetNonzerosParam< Add >::create().
get_nzassign() [4/5]
MX casadi::MXNode::get_nzassign (const MX & y, const Slice & inner, const MX & outer) const virtual inherited
a->get_nzassign(b,nz) returns b with b[nz]=a
Extra doc: https://github.com/casadi/casadi/wiki/L_1sd
Definition at line 716 of file mx_node.cpp.
{
     return SetNonzerosParam<false>::create(y, shared_from_this<MX>(), inner, outer);
   }
References casadi::SetNonzerosParam< Add >::create().
get_nzassign() [5/5]
MX casadi::MXNode::get_nzassign (const MX & y, const std::vector< casadi_int > & nz) const virtual inherited
a->get_nzassign(b,nz) returns b with b[nz]=a
Extra doc: https://github.com/casadi/casadi/wiki/L_1s9
Reimplemented in casadi::Constant< Value >, and casadi::ZeroByZero.
Definition at line 688 of file mx_node.cpp.
{
     // Check if any element needs to be set at all
     bool set_any = false;
     for (auto i=nz.begin(); i!=nz.end() && !set_any; ++i) {
       set_any = *i >= 0;
     }
     if (!set_any) return y;
     return SetNonzeros<false>::create(y, shared_from_this<MX>(), nz);
   }
References casadi::SetNonzeros< Add >::create().
Referenced by casadi::SetNonzeros< Add >::ad_forward(), casadi::SetNonzerosParamVector< Add >::ad_forward(), casadi::SetNonzerosParamSlice< Add >::ad_forward(), casadi::SetNonzerosSliceParam< Add >::ad_forward(), casadi::SetNonzerosParamParam< Add >::ad_forward(), casadi::SetNonzeros< Add >::ad_reverse(), casadi::SetNonzerosParamVector< Add >::ad_reverse(), casadi::SetNonzerosParamSlice< Add >::ad_reverse(), casadi::SetNonzerosSliceParam< Add >::ad_reverse(), casadi::SetNonzerosParamParam< Add >::ad_reverse(), casadi::SetNonzeros< Add >::eval_mx(), casadi::SetNonzerosParamVector< Add >::eval_mx(), casadi::SetNonzerosParamSlice< Add >::eval_mx(), casadi::SetNonzerosSliceParam< Add >::eval_mx(), casadi::SetNonzerosParamParam< Add >::eval_mx(), casadi::Constant< Value >::get_nzassign(), casadi::MX::set(), casadi::MX::set_nz(), and casadi::MX::unite().
get_nzref()
MX casadi::MXNode::get_nzref (const Sparsity & sp, const std::vector< casadi_int > & nz) const virtual inherited
a->get_nzref(sp,nz)
returns Matrix(sp,a[nz])
Extra doc: https://github.com/casadi/casadi/wiki/L_1s4
Reimplemented in casadi::SparsityCast, casadi::GetNonzeros, casadi::Constant< Value >, casadi::ZeroByZero, and casadi::Concat.
Definition at line 657 of file mx_node.cpp.
{
     if (sparsity().is_dense() && is_range(nz, 0, nnz())) {
       return sparsity_cast(shared_from_this<MX>(), sp);
     }
     return GetNonzeros::create(sp, shared_from_this<MX>(), nz);
   }
References casadi::GetNonzeros::create(), casadi::is_range(), casadi::MXNode::nnz(), and casadi::MXNode::sparsity().
Referenced by casadi::GetNonzeros::ad_forward(), casadi::MX::diag(), casadi::MX::enlarge(), casadi::MX::erase(), casadi::MX::get(), casadi::MX::get_nz(), casadi::Concat::get_nzref(), casadi::Constant< Value >::get_nzref(), casadi::GetNonzeros::get_nzref(), and casadi::MX::MX().
get_output()
MX casadi::MXNode::get_output (casadi_int oind) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1rp
Reimplemented in casadi::MultipleOutput, and casadi::Call.
Definition at line 441 of file mx_node.cpp.
{
     casadi_assert(oind==0, "Output index out of bounds");
     return shared_from_this<MX>();
   }
Referenced by casadi::MX::get_output(), and casadi::MX::graph_substitute().
get_project()
MX casadi::MXNode::get_project (const Sparsity & sp) const virtual inherited
Reimplemented in casadi::Constant< Value >, and casadi::ZeroByZero.
Definition at line 756 of file mx_node.cpp.
{
     if (sp==sparsity()) {
       return shared_from_this<MX>();
     } else if (sp.nnz()==0) {
       return MX::zeros(sp);
     } else if (sp.is_dense()) {
       return MX::create(new Densify(shared_from_this<MX>(), sp));
     } else if (sparsity().is_dense()) {
       return MX::create(new Sparsify(shared_from_this<MX>(), sp));
     } else {
       return MX::create(new Project(shared_from_this<MX>(), sp));
     }
   }
References casadi::MX::create(), casadi::Sparsity::is_dense(), casadi::Sparsity::nnz(), casadi::MXNode::sparsity(), and casadi::GenericMatrix< MX >::zeros().
Referenced by casadi::SetNonzeros< Add >::ad_forward(), casadi::GetNonzeros::ad_reverse(), casadi::Constant< Value >::get_project(), and casadi::MX::project().
get_rank1()
MX casadi::MXNode::get_rank1 (const MX & alpha, const MX & x, const MX & y) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1rx
Definition at line 609 of file mx_node.cpp.
{
     return MX::create(new Rank1(shared_from_this<MX>(), alpha, x, y));
   }
References casadi::MX::create().
Referenced by casadi::MX::_rank1().
get_repmat()
MX casadi::MXNode::get_repmat (casadi_int m, casadi_int n) const virtual inherited
Definition at line 1175 of file mx_node.cpp.
{
     if (n==1) {
       return MX::create(new HorzRepmat(shared_from_this<MX>(), m));
     } else {
       // Fallback to generic_matrix impl
       return GenericMatrix<MX>::repmat(shared_from_this<MX>(), n, m);
     }
   }
References casadi::MX::create(), and casadi::SparsityInterface< MatType >::repmat().
Referenced by casadi::MX::repmat().
get_repsum()
MX casadi::MXNode::get_repsum (casadi_int m, casadi_int n) const virtual inherited
Definition at line 1184 of file mx_node.cpp.
{
     if (n==1) {
       return MX::create(new HorzRepsum(shared_from_this<MX>(), m));
     } else {
       // Fallback to generic_matrix impl
       return GenericMatrix<MX>::repsum(shared_from_this<MX>(), n, m);
     }
   }
References casadi::MX::create(), and casadi::GenericMatrix< MatType >::repsum().
Referenced by casadi::MX::repsum().
get_reshape()
MX casadi::MXNode::get_reshape (const Sparsity & sp) const virtual inherited
Reimplemented in casadi::SparsityCast, casadi::Reshape, casadi::Constant< Value >, and casadi::ZeroByZero.
Definition at line 496 of file mx_node.cpp.
{
     casadi_assert_dev(sp.is_reshape(sparsity()));
     if (sp==sparsity()) {
       return shared_from_this<MX>();
     } else {
       return MX::create(new Reshape(shared_from_this<MX>(), sp));
     }
   }
References casadi::MX::create(), casadi::Sparsity::is_reshape(), and casadi::MXNode::sparsity().
Referenced by casadi::SparsityCast::get_reshape(), casadi::MXNode::get_transpose(), and casadi::MX::reshape().
get_solve()
MX casadi::MXNode::get_solve (const MX & r, bool tr, const Linsol & linear_solver) const virtual inherited
For system Ax = b:
A->get_solve(b)
Extra doc: https://github.com/casadi/casadi/wiki/L_1rz
Definition at line 649 of file mx_node.cpp.
{
     if (tr) {
       return MX::create(new LinsolCall<true>(densify(r), shared_from_this<MX>(), linear_solver));
     } else {
       return MX::create(new LinsolCall<false>(densify(r), shared_from_this<MX>(), linear_solver));
     }
   }
References casadi::MX::create().
Referenced by casadi::Rootfinder::ad_forward(), casadi::Rootfinder::ad_reverse(), and casadi::Linsol::solve().
get_solve_tril()
MX casadi::MXNode::get_solve_tril (const MX & r, bool tr) const virtual inherited
For system Ax = b:
A->get_solve_tril(b)
Extra doc: https://github.com/casadi/casadi/wiki/L_1s1
Reimplemented in casadi::Transpose, and casadi::BinaryMX< ScX, ScY >.
Definition at line 625 of file mx_node.cpp.
{
     if (tr) {
       return MX::create(new TrilSolve<true>(densify(r), shared_from_this<MX>()));
     } else {
       return MX::create(new TrilSolve<false>(densify(r), shared_from_this<MX>()));
     }
   }
References casadi::MX::create().
Referenced by casadi::BinaryMX< ScX, ScY >::get_solve_tril(), casadi::Transpose::get_solve_triu(), casadi::MX::solve(), and casadi::TrilSolve< Tr >::solve().
get_solve_tril_unity()
MX casadi::MXNode::get_solve_tril_unity (const MX & r, bool tr) const virtual inherited
For system Ax = b:
A->get_solve_tril(b)
Extra doc: https://github.com/casadi/casadi/wiki/L_1s3
Reimplemented in casadi::Transpose.
Definition at line 641 of file mx_node.cpp.
{
     if (tr) {
       return MX::create(new TrilSolveUnity<true>(densify(r), shared_from_this<MX>()));
     } else {
       return MX::create(new TrilSolveUnity<false>(densify(r), shared_from_this<MX>()));
     }
   }
References casadi::MX::create().
Referenced by casadi::BinaryMX< ScX, ScY >::get_solve_tril(), casadi::Transpose::get_solve_triu_unity(), and casadi::TrilSolveUnity< Tr >::solve().
get_solve_triu()
MX casadi::MXNode::get_solve_triu (const MX & r, bool tr) const virtual inherited
For system Ax = b:
A->get_solve_triu(b)
Extra doc: https://github.com/casadi/casadi/wiki/L_1s0
Reimplemented in casadi::Transpose, and casadi::BinaryMX< ScX, ScY >.
Definition at line 617 of file mx_node.cpp.
{
     if (tr) {
       return MX::create(new TriuSolve<true>(densify(r), shared_from_this<MX>()));
     } else {
       return MX::create(new TriuSolve<false>(densify(r), shared_from_this<MX>()));
     }
   }
References casadi::MX::create().
Referenced by casadi::Transpose::get_solve_tril(), casadi::BinaryMX< ScX, ScY >::get_solve_triu(), casadi::MX::solve(), and casadi::TriuSolve< Tr >::solve().
get_solve_triu_unity()
MX casadi::MXNode::get_solve_triu_unity (const MX & r, bool tr) const virtual inherited
For system Ax = b:
A->get_solve_triu(b)
Extra doc: https://github.com/casadi/casadi/wiki/L_1s2
Reimplemented in casadi::Transpose.
Definition at line 633 of file mx_node.cpp.
{
     if (tr) {
       return MX::create(new TriuSolveUnity<true>(densify(r), shared_from_this<MX>()));
     } else {
       return MX::create(new TriuSolveUnity<false>(densify(r), shared_from_this<MX>()));
     }
   }
References casadi::MX::create().
Referenced by casadi::Transpose::get_solve_tril_unity(), casadi::BinaryMX< ScX, ScY >::get_solve_triu(), and casadi::TriuSolveUnity< Tr >::solve().
get_sparsity_cast()
MX casadi::MXNode::get_sparsity_cast (const Sparsity & sp) const virtual inherited
Reimplemented in casadi::SparsityCast.
Definition at line 505 of file mx_node.cpp.
{
     casadi_assert_dev(sp.nnz()==nnz());
     if (sp==sparsity()) {
       return shared_from_this<MX>();
     } else {
       return MX::create(new SparsityCast(shared_from_this<MX>(), sp));
     }
   }
References casadi::MX::create(), casadi::Sparsity::nnz(), casadi::MXNode::nnz(), and casadi::MXNode::sparsity().
Referenced by casadi::SparsityCast::get_transpose(), and casadi::MX::sparsity_cast().
get_subassign()
MX casadi::MXNode::get_subassign (const MX & y, const Slice & i, const Slice & j) const virtual inherited
Definition at line 774 of file mx_node.cpp.
{
     return MX::create(new SubAssign(shared_from_this<MX>(), y, i, j));
   }
References casadi::MX::create().
get_subref()
MX casadi::MXNode::get_subref (const Slice & i, const Slice & j) const virtual inherited
Definition at line 770 of file mx_node.cpp.
{
     return MX::create(new SubRef(shared_from_this<MX>(), i, j));
   }
References casadi::MX::create().
get_transpose()
MX casadi::MXNode::get_transpose () const virtual inherited
Reimplemented in casadi::Transpose, casadi::SparsityCast, casadi::Reshape, casadi::Constant< Value >, and casadi::ZeroByZero.
Definition at line 484 of file mx_node.cpp.
{
     if (sparsity().is_scalar()) {
       return shared_from_this<MX>();
     } else if (sparsity().is_vector()) {
       return get_reshape(sparsity().T());
     } else if (sparsity().is_dense()) {
       return MX::create(new DenseTranspose(shared_from_this<MX>()));
     } else {
       return MX::create(new Transpose(shared_from_this<MX>()));
     }
   }
References casadi::MX::create(), casadi::MXNode::get_reshape(), casadi::MXNode::sparsity(), and casadi::T.
Referenced by casadi::Reshape::get_transpose(), casadi::SparsityCast::get_transpose(), and casadi::MX::T().
get_unary()
MX casadi::MXNode::get_unary (casadi_int op) const virtual inherited
Reimplemented in casadi::UnaryMX, casadi::Constant< Value >, casadi::ZeroByZero, and casadi::BinaryMX< ScX, ScY >.
Definition at line 778 of file mx_node.cpp.
{
     if (operation_checker<F0XChecker>(op) && is_zero()) {
       // If identically zero
       return MX::zeros(sparsity());
     } else {
       // Create a new node
       return MX::create(new UnaryMX(Operation(op), shared_from_this<MX>()));
     }
   }
References casadi::MX::create(), casadi::MXNode::is_zero(), casadi::MXNode::op(), casadi::MXNode::sparsity(), and casadi::GenericMatrix< MX >::zeros().
Referenced by casadi::MXNode::_get_binary(), casadi::Constant< Value >::_get_binary(), casadi::BinaryMX< ScX, ScY >::get_unary(), casadi::UnaryMX::get_unary(), casadi::MX::operator-(), and casadi::MX::unary().
get_vertcat()
MX casadi::MXNode::get_vertcat (const std::vector< MX > & x) const virtual inherited
Reimplemented in casadi::Vertsplit, casadi::OutputNode, and casadi::Constant< Value >.
Definition at line 1123 of file mx_node.cpp.
{
     // Check if there is any existing vertcat operation
     for (auto i=x.begin(); i!=x.end(); ++i) {
       if (i->op()==OP_VERTCAT) {
         // Split up
         std::vector<MX> x_split(x.begin(), i);
         for (; i!=x.end(); ++i) {
           if (i->op()==OP_VERTCAT) {
             x_split.insert(x_split.end(), (*i)->dep_.begin(), (*i)->dep_.end());
           } else {
             x_split.push_back(*i);
           }
         }
         return vertcat(x_split);
       }
     }
     return MX::create(new Vertcat(x));
   }
References casadi::MX::create(), and casadi::OP_VERTCAT.
Referenced by casadi::Constant< Value >::get_vertcat(), casadi::OutputNode::get_vertcat(), casadi::Vertsplit::get_vertcat(), and casadi::MX::vertcat().
get_vertsplit()
std::vector< MX > casadi::MXNode::get_vertsplit (const std::vector< casadi_int > & output_offset) const virtual inherited
Definition at line 1209 of file mx_node.cpp.
{
     if (is_zero()) {
       std::vector<MX> ret =
           MX::createMultipleOutput(new Vertsplit(shared_from_this<MX>(), output_offset));
       for (casadi_int i=0;i<ret.size();++i) {
         ret[i]=MX::zeros(ret[i].sparsity());
       }
       return ret;
     }
     std::vector<MX> ret =
         MX::createMultipleOutput(new Vertsplit(shared_from_this<MX>(), output_offset));
     if (GlobalOptions::simplification_on_the_fly) {
       // Simplify vertsplit(vertcat)
       if (op()==OP_VERTCAT) {
         casadi_int offset_deps = 0;
         casadi_int j = 0;
         for (casadi_int i=0;i<output_offset.size();++i) {
           while (offset_deps<output_offset[i]) { offset_deps+=dep(j).size1();++j; }
           if (j>=n_dep()) j = n_dep()-1;
           if (output_offset[i]==offset_deps &&
               (i+1<output_offset.size()?output_offset[i+1]:size1()) ==
                offset_deps +dep(j).size1()) {
             // Aligned with vertcat dependency
             ret[i] = dep(j);
           }
         }
       }
     }
     return ret;
   }
References casadi::MX::createMultipleOutput(), casadi::MXNode::dep(), casadi::MXNode::is_zero(), casadi::MXNode::n_dep(), casadi::MXNode::op(), casadi::OP_VERTCAT, casadi::GlobalOptions::simplification_on_the_fly, casadi::GenericMatrix< MatType >::size1(), casadi::MXNode::size1(), casadi::MXNode::sparsity(), and casadi::GenericMatrix< MX >::zeros().
Referenced by casadi::MX::vertsplit().
getCount()
casadi_int casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::getCount inherited
Definition at line 60 of file generic_shared_internal.hpp.
{
     return static_cast<const Internal*>(this)->count;
   }
has_duplicates()
bool casadi::MXNode::has_duplicates () const virtual inherited
Not thread-safe
Extra doc: https://github.com/casadi/casadi/wiki/L_1r8
Reimplemented in casadi::SymbolicMX, casadi::SparsityCast, casadi::Reshape, casadi::ConstantMX, and casadi::Concat.
Definition at line 146 of file mx_node.cpp.
{
     casadi_error("'has_duplicates' not defined for class " + class_name());
   }
References casadi::MXNode::class_name().
Referenced by casadi::Concat::has_duplicates(), casadi::Reshape::has_duplicates(), and casadi::SparsityCast::has_duplicates().
has_output()
virtual bool casadi::MXNode::has_output () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1rb
Reimplemented in casadi::MultipleOutput.
Definition at line 287 of file mx_node.hpp.
 {return false;}
Referenced by casadi::MX::graph_substitute().
has_refcount()
virtual bool casadi::MXNode::has_refcount () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1qp
Reimplemented in casadi::Call.
Definition at line 127 of file mx_node.hpp.
 { return false;}
ind()
casadi_int casadi::MXNode::ind () const virtual inherited
Reimplemented in casadi::IOInstruction.
Definition at line 210 of file mx_node.cpp.
{
     casadi_error("'ind' not defined for class " + class_name());
   }
References casadi::MXNode::class_name().
Referenced by casadi::GetNonzerosSliceParam::eval(), casadi::GetNonzerosParamParam::eval(), casadi::ConstantDM::generate(), casadi::GetNonzerosVector::generate(), casadi::MXFunction::print(), casadi::MXNode::print_compact(), and casadi::Einstein::sp_reverse().
info()
Dict casadi::MXNode::info () const virtual inherited
Obtain information about node
Reimplemented in casadi::SubRef, casadi::SubAssign, casadi::Split, casadi::Solve< Tr >, casadi::SetNonzerosSlice2< Add >, casadi::SetNonzerosSlice< Add >, casadi::SetNonzerosVector< Add >, casadi::OutputNode, casadi::IOInstruction, casadi::GetNonzerosParamParam, casadi::GetNonzerosParamSlice, casadi::GetNonzerosSliceParam, casadi::GetNonzerosSlice2, casadi::GetNonzerosSlice, casadi::GetNonzerosVector, and casadi::Einstein.
Definition at line 514 of file mx_node.cpp.
{
     return Dict();
   }
initSingleton()
void casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::initSingleton () inline protected inherited
Called in the constructor of singletons to avoid that the counter reaches zero
Definition at line 71 of file generic_shared_internal.hpp.
{
       casadi_assert_dev(static_cast<Internal*>(this)->count==0);
       static_cast<Internal*>(this)->count++;
     }
is_binary()
virtual bool casadi::MXNode::is_binary () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1qk
Reimplemented in casadi::BinaryMX< ScX, ScY >.
Definition at line 101 of file mx_node.hpp.
 { return false;}
is_equal() [1/2]
virtual bool casadi::MXNode::is_equal (const MXNode * node, casadi_int depth) const inline virtual inherited
Reimplemented in casadi::UnaryMX, casadi::Transpose, casadi::SparsityCast, casadi::SetNonzerosSlice2< Add >, casadi::SetNonzerosSlice< Add >, casadi::SetNonzerosVector< Add >, casadi::Reshape, casadi::Multiplication, casadi::GetNonzerosSlice2, casadi::GetNonzerosSlice, casadi::GetNonzerosVector, casadi::Einstein, casadi::Constant< Value >, casadi::ConstantDM, casadi::Concat, and casadi::BinaryMX< ScX, ScY >.
Definition at line 337 of file mx_node.hpp.
 { return false;}
is_equal() [2/2]
bool casadi::MXNode::is_equal (const MXNode * x, const MXNode * y, casadi_int depth) static inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1rj
Definition at line 1256 of file mx_node.cpp.
{
     if (x==y) {
       return true;
     } else if (depth>0) {
       return x->is_equal(y, depth);
     } else {
       return false;
     }
   }
References casadi::MXNode::is_equal().
Referenced by casadi::MXNode::_get_binary(), casadi::MX::is_equal(), and casadi::MXNode::is_equal().
is_eye()
virtual bool casadi::MXNode::is_eye () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1qi
Reimplemented in casadi::Constant< Value >, and casadi::ConstantDM.
Definition at line 91 of file mx_node.hpp.
 { return false;}
is_minus_one()
virtual bool casadi::MXNode::is_minus_one () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1qg
Reimplemented in casadi::ConstantDM.
Definition at line 81 of file mx_node.hpp.
 { return false;}
is_one()
virtual bool casadi::MXNode::is_one () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1qf
Reimplemented in casadi::Constant< Value >, and casadi::ConstantDM.
Definition at line 76 of file mx_node.hpp.
 { return false;}
is_output()
virtual bool casadi::MXNode::is_output () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1ra
Reimplemented in casadi::OutputNode.
Definition at line 282 of file mx_node.hpp.
 {return false;}
Referenced by casadi::MXNode::check_dep(), casadi::Diagsplit::get_diagcat(), casadi::Horzsplit::get_horzcat(), and casadi::Vertsplit::get_vertcat().
is_unary()
virtual bool casadi::MXNode::is_unary () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1qj
Reimplemented in casadi::UnaryMX.
Definition at line 96 of file mx_node.hpp.
 { return false;}
is_valid_input()
virtual bool casadi::MXNode::is_valid_input () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1r3
Reimplemented in casadi::SymbolicMX, casadi::SparsityCast, casadi::Reshape, casadi::ZeroByZero, casadi::ConstantMX, and casadi::Concat.
Definition at line 231 of file mx_node.hpp.
 { return false;}
Referenced by casadi::Concat::is_valid_input(), casadi::Reshape::is_valid_input(), and casadi::SparsityCast::is_valid_input().
is_value()
virtual bool casadi::MXNode::is_value (double val) const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1qh
Reimplemented in casadi::Constant< Value >.
Definition at line 86 of file mx_node.hpp.
 { return false;}
Referenced by casadi::MXNode::_get_binary(), and casadi::Constant< Value >::is_equal().
is_zero()
virtual bool casadi::MXNode::is_zero () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1qe
Reimplemented in casadi::Constant< Value >, and casadi::ConstantDM.
Definition at line 71 of file mx_node.hpp.
 { return false;}
Referenced by casadi::ConstantMX::__nonzero__(), casadi::MXNode::_get_binary(), casadi::Constant< Value >::_get_binary(), casadi::MX::densify(), casadi::MXNode::get_diagsplit(), casadi::MXNode::get_dot(), casadi::MXNode::get_horzsplit(), casadi::MXNode::get_nzadd(), casadi::Constant< Value >::get_nzassign(), casadi::MXNode::get_unary(), and casadi::MXNode::get_vertsplit().
join_primitives() [1/3]
DM casadi::MXNode::join_primitives (std::vector< DM >::const_iterator & it) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1r7
Reimplemented in casadi::SparsityCast, casadi::Reshape, casadi::ConstantMX, casadi::Diagcat, casadi::Vertcat, and casadi::Horzcat.
Definition at line 185 of file mx_node.cpp.
{
     return join_primitives_gen<DM>(it);
   }
join_primitives() [2/3]
MX casadi::MXNode::join_primitives (std::vector< MX >::const_iterator & it) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1r7
Reimplemented in casadi::SparsityCast, casadi::Reshape, casadi::ConstantMX, casadi::Diagcat, casadi::Vertcat, and casadi::Horzcat.
Definition at line 181 of file mx_node.cpp.
{
     return join_primitives_gen<MX>(it);
   }
Referenced by casadi::MX::join_primitives(), casadi::ConstantMX::join_primitives(), casadi::Horzcat::join_primitives_gen(), casadi::Vertcat::join_primitives_gen(), casadi::Diagcat::join_primitives_gen(), and casadi::ConstantMX::join_primitives_gen().
join_primitives() [3/3]
SX casadi::MXNode::join_primitives (std::vector< SX >::const_iterator & it) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1r7
Reimplemented in casadi::SparsityCast, casadi::Reshape, casadi::ConstantMX, casadi::Diagcat, casadi::Vertcat, and casadi::Horzcat.
Definition at line 189 of file mx_node.cpp.
{
     return join_primitives_gen<SX>(it);
   }
join_primitives_gen()
template<typename T > T casadi::MXNode::join_primitives_gen (typename std::vector< T >::const_iterator & it) const inherited
Definition at line 171 of file mx_node.cpp.
{
     T ret = *it++;
     if (ret.size()==size()) {
       return ret;
     } else {
       casadi_assert_dev(ret.is_empty(true));
       return T(size());
     }
   }
References casadi::MXNode::size(), and casadi::T.
mapping()
Matrix< casadi_int > casadi::MXNode::mapping () const virtual inherited
Reimplemented in casadi::SetNonzeros< Add >, and casadi::GetNonzeros.
Definition at line 973 of file mx_node.cpp.
{
     casadi_error("'mapping' not defined for class " + class_name());
   }
References casadi::MXNode::class_name().
Referenced by casadi::BSplineCommon::derivative_coeff().
matches_sparsity()
template<class T > bool casadi::MXNode::matches_sparsity (const std::vector< T > & arg) const inline inherited
Definition at line 378 of file mx_node.hpp.
{
         for (casadi_int i=0;i<dep_.size();++i) {
             if (dep_[i].sparsity()!=arg[i].sparsity()) {
                 return false;
             }
         }
         return true;
     }
Referenced by casadi::GetNonzerosVector::eval_mx(), casadi::SetNonzerosVector< Add >::eval_mx(), casadi::SetNonzerosSlice< Add >::eval_mx(), and casadi::SetNonzerosSlice2< Add >::eval_mx().
maxDepth()
static bool casadi::MXNode::maxDepth () inline static inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1rk
Definition at line 342 of file mx_node.hpp.
 { return MX::get_max_depth();}
References casadi::MX::get_max_depth().
Referenced by casadi::MXNode::_get_binary(), and casadi::UnaryMX::_get_binary().
n_dep()
casadi_int casadi::MXNode::n_dep () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1rn
Definition at line 206 of file mx_node.cpp.
{
     return dep_.size();
   }
References casadi::MXNode::dep_.
Referenced by casadi::Call::ad_forward(), casadi::Call::ad_reverse(), casadi::Horzcat::ad_reverse(), casadi::Vertcat::ad_reverse(), casadi::Diagcat::ad_reverse(), casadi::MXNode::can_inline(), casadi::Call::disp(), casadi::Horzcat::disp(), casadi::Vertcat::disp(), casadi::Diagcat::disp(), casadi::Concat::eval_gen(), casadi::MXNode::eval_linear_rearrange(), casadi::MXNode::get_horzsplit(), casadi::Concat::get_nzref(), casadi::MXNode::get_vertsplit(), casadi::Concat::has_duplicates(), casadi::Concat::is_valid_input(), casadi::Horzcat::join_primitives_gen(), casadi::Vertcat::join_primitives_gen(), casadi::Diagcat::join_primitives_gen(), casadi::Concat::n_primitives(), casadi::Horzcat::off(), casadi::Vertcat::off(), casadi::Diagcat::off(), casadi::Concat::primitives(), casadi::MXNode::print_compact(), casadi::Concat::reset_input(), casadi::MXNode::sameOpAndDeps(), casadi::MXNode::sp_forward(), casadi::Concat::sp_forward(), casadi::MXNode::sp_reverse(), and casadi::Concat::sp_reverse().
n_inplace()
casadi_int casadi::Rank1::n_inplace () const inline override virtual
Reimplemented from casadi::MXNode.
Definition at line 98 of file rank1.hpp.
 { return 1;}
n_primitives()
casadi_int casadi::MXNode::n_primitives () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1r4
Reimplemented in casadi::SparsityCast, casadi::Reshape, casadi::ConstantMX, and casadi::Concat.
Definition at line 142 of file mx_node.cpp.
{
     return 1;
   }
Referenced by casadi::Concat::n_primitives(), casadi::ConstantMX::n_primitives(), casadi::Reshape::n_primitives(), and casadi::SparsityCast::n_primitives().
name()
const std::string & casadi::MXNode::name () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1r0
Reimplemented in casadi::SymbolicMX, and casadi::ZeroByZero.
Definition at line 193 of file mx_node.cpp.
{
     casadi_error("'name' not defined for class " + class_name());
   }
References casadi::MXNode::class_name().
Referenced by casadi::ConstantMX::create().
nnz()
casadi_int casadi::MXNode::nnz (casadi_int i = 0) const inline inherited
Definition at line 389 of file mx_node.hpp.
 { return sparsity(i).nnz(); }
Referenced by casadi::ConstantMX::__nonzero__(), casadi::MXNode::_get_binary(), casadi::ConstantFile::add_dependency(), casadi::ConstantFile::codegen_incref(), casadi::ConstantFile::ConstantFile(), casadi::BSpline::dual(), casadi::Assertion::eval(), casadi::Find::eval(), casadi::Low::eval(), casadi::GetNonzerosParamVector::eval(), casadi::GetNonzerosSliceParam::eval(), casadi::GetNonzerosParamSlice::eval(), casadi::GetNonzerosParamParam::eval(), casadi::MMin::eval(), casadi::MMax::eval(), casadi::Monitor::eval(), casadi::UnaryMX::eval(), casadi::Dot::eval_gen(), casadi::Einstein::eval_gen(), casadi::LogSumExp::eval_gen(), casadi::Multiplication::eval_gen(), casadi::NormF::eval_gen(), casadi::Norm1::eval_gen(), casadi::NormInf::eval_gen(), eval_gen(), casadi::HorzRepmat::eval_gen(), casadi::Reshape::eval_gen(), casadi::SparsityCast::eval_gen(), casadi::HorzRepsum::eval_gen(), casadi::Assertion::eval_sx(), casadi::MMin::eval_sx(), casadi::MMax::eval_sx(), casadi::Monitor::eval_sx(), casadi::UnaryMX::eval_sx(), casadi::BSplineParametric::generate(), casadi::Bilin::generate(), casadi::Find::generate(), casadi::Concat::generate(), casadi::ConstantDM::generate(), casadi::ConstantFile::generate(), casadi::ConstantPool::generate(), casadi::Convexify::generate(), casadi::Dot::generate(), casadi::Einstein::generate(), casadi::GetNonzerosVector::generate(), casadi::GetNonzerosSlice::generate(), casadi::GetNonzerosSlice2::generate(), casadi::GetNonzerosParamVector::generate(), casadi::GetNonzerosSliceParam::generate(), casadi::GetNonzerosParamSlice::generate(), casadi::GetNonzerosParamParam::generate(), casadi::Input::generate(), casadi::Output::generate(), casadi::LogSumExp::generate(), casadi::MMin::generate(), casadi::MMax::generate(), casadi::Monitor::generate(), casadi::Multiplication::generate(), casadi::DenseMultiplication::generate(), casadi::NormF::generate(), casadi::Norm1::generate(), casadi::NormInf::generate(), casadi::Project::generate(), casadi::Densify::generate(), casadi::Sparsify::generate(), generate(), casadi::HorzRepmat::generate(), casadi::HorzRepsum::generate(), casadi::Split::generate(), casadi::Transpose::generate(), casadi::DenseTranspose::generate(), casadi::UnaryMX::generate(), casadi::MXNode::generate_copy(), casadi::MXNode::get_binary(), casadi::MXNode::get_dot(), casadi::MXNode::get_mac(), casadi::MXNode::get_monitor(), casadi::MXNode::get_nzref(), casadi::MXNode::get_sparsity_cast(), casadi::ConstantMX::is_valid_input(), casadi::ConstantMX::join_primitives(), casadi::ConstantMX::join_primitives_gen(), casadi::ConstantMX::n_primitives(), casadi::ConstantMX::primitives(), casadi::SetNonzerosVector< Add >::SetNonzerosVector(), casadi::Assertion::sp_forward(), casadi::Low::sp_forward(), casadi::ConstantMX::sp_forward(), casadi::GetNonzerosParam::sp_forward(), casadi::Monitor::sp_forward(), casadi::Multiplication::sp_forward(), sp_forward(), casadi::HorzRepsum::sp_forward(), casadi::Reshape::sp_forward(), casadi::SparsityCast::sp_forward(), casadi::SymbolicMX::sp_forward(), casadi::Transpose::sp_forward(), casadi::UnaryMX::sp_forward(), casadi::Assertion::sp_reverse(), casadi::Low::sp_reverse(), casadi::ConstantMX::sp_reverse(), casadi::Einstein::sp_reverse(), casadi::GetNonzerosParam::sp_reverse(), casadi::Monitor::sp_reverse(), casadi::Multiplication::sp_reverse(), casadi::Project::sp_reverse(), sp_reverse(), casadi::HorzRepmat::sp_reverse(), casadi::HorzRepsum::sp_reverse(), casadi::Reshape::sp_reverse(), casadi::SparsityCast::sp_reverse(), casadi::SymbolicMX::sp_reverse(), casadi::Transpose::sp_reverse(), casadi::UnaryMX::sp_reverse(), and casadi::ConstantMX::split_primitives_gen().
nout()
virtual casadi_int casadi::MXNode::nout () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1ro
Reimplemented in casadi::MultipleOutput, casadi::Split, casadi::Output, and casadi::Call.
Definition at line 364 of file mx_node.hpp.
 { return 1;}
Referenced by casadi::MX::createMultipleOutput(), casadi::MXNode::eval_linear_rearrange(), casadi::MXNode::sp_forward(), and casadi::MXNode::sp_reverse().
numel()
casadi_int casadi::MXNode::numel () const inline inherited
Definition at line 388 of file mx_node.hpp.
 { return sparsity().numel(); }
Referenced by casadi::ConstantMX::__nonzero__().
offset()
casadi_int casadi::MXNode::offset () const virtual inherited
Reimplemented in casadi::IOInstruction.
Definition at line 218 of file mx_node.cpp.
{
     casadi_error("'offset' not defined for class " + class_name());
   }
References casadi::MXNode::class_name().
Referenced by casadi::BSplineParametric::create(), casadi::BSpline::create(), casadi::BSplineCommon::derivative_coeff(), casadi::BSpline::dual(), casadi::MXNode::get_bspline(), casadi::BSplineCommon::get_coeff_size(), and casadi::BSplineCommon::prepare().
op()
casadi_int casadi::Rank1::op () const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_9
Implements casadi::MXNode.
Definition at line 108 of file rank1.hpp.
 { return OP_RANK1;}
References casadi::OP_RANK1.
primitives()
void casadi::MXNode::primitives (std::vector< MX >::iterator & it) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1r5
Reimplemented in casadi::SparsityCast, casadi::Reshape, casadi::ConstantMX, and casadi::Concat.
Definition at line 154 of file mx_node.cpp.
{
     *it++ = shared_from_this<MX>();
   }
Referenced by casadi::Concat::primitives(), casadi::ConstantMX::primitives(), casadi::Reshape::primitives(), and casadi::SparsityCast::primitives().
print_compact()
std::string casadi::MXNode::print_compact (std::map< const MXNode *, casadi_int > & nodeind, std::vector< std::string > & intermed) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1qm
Definition at line 301 of file mx_node.cpp.
{
     // Get reference to node index
     casadi_int& ind = nodeind[this];
     // If positive, already in intermediate expressions
     if (ind>0) return "@" + str(ind);
     // Get expressions for dependencies
     std::vector<std::string> arg(n_dep());
     for (casadi_int i=0; i<arg.size(); ++i) {
       arg[i] = dep(i)->print_compact(nodeind, intermed);
     }
     // Get expression for this
     std::string s = disp(arg);
     // Decide what to do with the expression
     if (ind==0) {
       // Inline expression
       return s;
     } else {
       // Add to list of intermediate expressions and return reference
       intermed.push_back(s);
       ind = intermed.size(); // For subsequent references
       return "@" + str(ind);
     }
   }
References casadi::MXNode::dep(), casadi::MXNode::disp(), casadi::MXNode::ind(), casadi::MXNode::n_dep(), casadi::MXNode::print_compact(), and casadi::str().
Referenced by casadi::MXNode::disp(), and casadi::MXNode::print_compact().
reset_input()
void casadi::MXNode::reset_input () const virtual inherited
Not thread-safe
Extra doc: https://github.com/casadi/casadi/wiki/L_1r9
Reimplemented in casadi::SymbolicMX, casadi::SparsityCast, casadi::Reshape, casadi::ConstantMX, and casadi::Concat.
Definition at line 150 of file mx_node.cpp.
{
     casadi_error("'reset_input' not defined for class " + class_name());
   }
References casadi::MXNode::class_name().
Referenced by casadi::Concat::reset_input(), casadi::Reshape::reset_input(), and casadi::SparsityCast::reset_input().
sameOpAndDeps()
bool casadi::MXNode::sameOpAndDeps (const MXNode * node, casadi_int depth) const inherited
equivalent dependencies up to a given depth
Extra doc: https://github.com/casadi/casadi/wiki/L_1rl
Definition at line 977 of file mx_node.cpp.
{
     if (op()!=node->op() || n_dep()!=node->n_dep())
       return false;
     for (casadi_int i=0; i<n_dep(); ++i) {
       if (!MX::is_equal(dep(i), node->dep(i), depth-1))
         return false;
     }
     return true;
   }
References casadi::MXNode::dep(), casadi::MX::is_equal(), casadi::MXNode::n_dep(), and casadi::MXNode::op().
Referenced by casadi::GetNonzerosVector::is_equal(), casadi::GetNonzerosSlice::is_equal(), and casadi::GetNonzerosSlice2::is_equal().
segment()
casadi_int casadi::MXNode::segment () const virtual inherited
Reimplemented in casadi::IOInstruction.
Definition at line 214 of file mx_node.cpp.
{
     casadi_error("'segment' not defined for class " + class_name());
   }
References casadi::MXNode::class_name().
Referenced by casadi::MXFunction::print().
serialize()
void casadi::MXNode::serialize (SerializingStream & s) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1rf
Definition at line 518 of file mx_node.cpp.
{
     serialize_type(s);
     serialize_body(s);
   }
References casadi::MXNode::serialize_body(), and casadi::MXNode::serialize_type().
serialize_body()
void casadi::MXNode::serialize_body (SerializingStream & s) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1rg
Reimplemented in casadi::UnaryMX, casadi::SymbolicMX, casadi::Split, casadi::LinsolCall< Tr >, casadi::Solve< Tr >, casadi::SetNonzerosSliceParam< Add >, casadi::SetNonzerosParamSlice< Add >, casadi::SetNonzerosParamVector< Add >, casadi::SetNonzerosSlice2< Add >, casadi::SetNonzerosSlice< Add >, casadi::SetNonzerosVector< Add >, casadi::HorzRepsum, casadi::HorzRepmat, casadi::OutputNode, casadi::Monitor, casadi::IOInstruction, casadi::GetNonzerosParamSlice, casadi::GetNonzerosSliceParam, casadi::GetNonzerosParamVector, casadi::GetNonzerosSlice2, casadi::GetNonzerosSlice, casadi::GetNonzerosVector, casadi::Convexify, casadi::Constant< Value >, casadi::ZeroByZero, casadi::ConstantPool, casadi::ConstantFile, casadi::ConstantDM, casadi::Low, casadi::Call, casadi::BSpline, casadi::BSplineCommon, casadi::BinaryMX< ScX, ScY >, and casadi::Assertion.
Definition at line 523 of file mx_node.cpp.
{
     s.pack("MXNode::deps", dep_);
     s.pack("MXNode::sp", sparsity_);
   }
References casadi::MXNode::dep_, casadi::SerializingStream::pack(), and casadi::MXNode::sparsity_.
Referenced by casadi::MXNode::serialize(), casadi::Assertion::serialize_body(), casadi::BinaryMX< ScX, ScY >::serialize_body(), casadi::BSplineCommon::serialize_body(), casadi::Call::serialize_body(), casadi::Low::serialize_body(), casadi::ConstantDM::serialize_body(), casadi::ConstantFile::serialize_body(), casadi::ConstantPool::serialize_body(), casadi::Constant< Value >::serialize_body(), casadi::Convexify::serialize_body(), casadi::GetNonzerosVector::serialize_body(), casadi::GetNonzerosSlice::serialize_body(), casadi::GetNonzerosSlice2::serialize_body(), casadi::GetNonzerosParamVector::serialize_body(), casadi::GetNonzerosSliceParam::serialize_body(), casadi::GetNonzerosParamSlice::serialize_body(), casadi::IOInstruction::serialize_body(), casadi::Monitor::serialize_body(), casadi::OutputNode::serialize_body(), casadi::HorzRepmat::serialize_body(), casadi::HorzRepsum::serialize_body(), casadi::SetNonzerosVector< Add >::serialize_body(), casadi::SetNonzerosSlice< Add >::serialize_body(), casadi::SetNonzerosSlice2< Add >::serialize_body(), casadi::SetNonzerosParamVector< Add >::serialize_body(), casadi::SetNonzerosParamSlice< Add >::serialize_body(), casadi::SetNonzerosSliceParam< Add >::serialize_body(), casadi::Solve< Tr >::serialize_body(), casadi::Split::serialize_body(), casadi::SymbolicMX::serialize_body(), and casadi::UnaryMX::serialize_body().
serialize_type()
void casadi::MXNode::serialize_type (SerializingStream & s) const virtual inherited
Information needed to unambiguously find the (lowest level sub)class, such that its deserializing constructor can be called.
Extra doc: https://github.com/casadi/casadi/wiki/L_1rh
Reimplemented in casadi::DenseTranspose, casadi::Transpose, casadi::LinsolCall< Tr >, casadi::Solve< Tr >, casadi::SetNonzerosParamParam< Add >, casadi::SetNonzerosSliceParam< Add >, casadi::SetNonzerosParamSlice< Add >, casadi::SetNonzerosParamVector< Add >, casadi::SetNonzerosSlice2< Add >, casadi::SetNonzerosSlice< Add >, casadi::SetNonzerosVector< Add >, casadi::Sparsify, casadi::Densify, casadi::Project, casadi::DenseMultiplication, casadi::Multiplication, casadi::GetNonzerosParamParam, casadi::GetNonzerosParamSlice, casadi::GetNonzerosSliceParam, casadi::GetNonzerosParamVector, casadi::GetNonzerosSlice2, casadi::GetNonzerosSlice, casadi::GetNonzerosVector, casadi::Constant< Value >, casadi::ZeroByZero, casadi::ConstantPool, casadi::ConstantFile, casadi::ConstantDM, casadi::BSplineParametric, casadi::BSpline, and casadi::BinaryMX< ScX, ScY >.
Definition at line 528 of file mx_node.cpp.
{
     s.pack("MXNode::op", static_cast<int>(op()));
   }
References casadi::MXNode::op(), and casadi::SerializingStream::pack().
Referenced by casadi::MXNode::serialize(), casadi::BinaryMX< ScX, ScY >::serialize_type(), casadi::BSpline::serialize_type(), casadi::BSplineParametric::serialize_type(), casadi::ConstantDM::serialize_type(), casadi::ConstantFile::serialize_type(), casadi::ConstantPool::serialize_type(), casadi::ZeroByZero::serialize_type(), casadi::Constant< Value >::serialize_type(), casadi::GetNonzerosVector::serialize_type(), casadi::GetNonzerosSlice::serialize_type(), casadi::GetNonzerosSlice2::serialize_type(), casadi::GetNonzerosParamVector::serialize_type(), casadi::GetNonzerosSliceParam::serialize_type(), casadi::GetNonzerosParamSlice::serialize_type(), casadi::GetNonzerosParamParam::serialize_type(), casadi::Multiplication::serialize_type(), casadi::DenseMultiplication::serialize_type(), casadi::Project::serialize_type(), casadi::Densify::serialize_type(), casadi::Sparsify::serialize_type(), casadi::SetNonzerosVector< Add >::serialize_type(), casadi::SetNonzerosSlice< Add >::serialize_type(), casadi::SetNonzerosSlice2< Add >::serialize_type(), casadi::SetNonzerosParamVector< Add >::serialize_type(), casadi::SetNonzerosParamSlice< Add >::serialize_type(), casadi::SetNonzerosSliceParam< Add >::serialize_type(), casadi::SetNonzerosParamParam< Add >::serialize_type(), casadi::Solve< Tr >::serialize_type(), casadi::Transpose::serialize_type(), and casadi::DenseTranspose::serialize_type().
set_dep() [1/4]
void casadi::MXNode::set_dep (const MX & dep) inherited
Definition at line 226 of file mx_node.cpp.
{
     dep_.resize(1);
     dep_[0] = dep;
     check_dep();
   }
References casadi::MXNode::check_dep(), casadi::MXNode::dep(), and casadi::MXNode::dep_.
Referenced by casadi::Assertion::Assertion(), casadi::Bilin::Bilin(), casadi::BinaryMX< ScX, ScY >::BinaryMX(), casadi::BSpline::BSpline(), casadi::BSplineParametric::BSplineParametric(), casadi::Call::Call(), casadi::Concat::Concat(), casadi::Convexify::Convexify(), casadi::Determinant::Determinant(), casadi::Dot::Dot(), casadi::Einstein::Einstein(), casadi::Find::Find(), casadi::GetNonzeros::GetNonzeros(), casadi::GetNonzerosParam::GetNonzerosParam(), casadi::HorzRepmat::HorzRepmat(), casadi::HorzRepsum::HorzRepsum(), casadi::Inverse::Inverse(), casadi::LogSumExp::LogSumExp(), casadi::Low::Low(), casadi::MMax::MMax(), casadi::MMin::MMin(), casadi::Monitor::Monitor(), casadi::Multiplication::Multiplication(), casadi::Norm::Norm(), casadi::Output::Output(), casadi::OutputNode::OutputNode(), casadi::Project::Project(), Rank1(), casadi::Reshape::Reshape(), casadi::SparsityCast::SparsityCast(), casadi::Split::Split(), casadi::SubAssign::SubAssign(), casadi::SubRef::SubRef(), casadi::Transpose::Transpose(), and casadi::UnaryMX::UnaryMX().
set_dep() [2/4]
void casadi::MXNode::set_dep (const MX & dep1, const MX & dep2) inherited
Definition at line 232 of file mx_node.cpp.
{
     dep_.resize(2);
     dep_[0] = dep1;
     dep_[1] = dep2;
     check_dep();
   }
References casadi::MXNode::check_dep(), and casadi::MXNode::dep_.
set_dep() [3/4]
void casadi::MXNode::set_dep (const MX & dep1, const MX & dep2, const MX & dep3) inherited
Definition at line 239 of file mx_node.cpp.
{
     dep_.resize(3);
     dep_[0] = dep1;
     dep_[1] = dep2;
     dep_[2] = dep3;
     check_dep();
   }
References casadi::MXNode::check_dep(), and casadi::MXNode::dep_.
set_dep() [4/4]
void casadi::MXNode::set_dep (const std::vector< MX > & dep) inherited
Definition at line 247 of file mx_node.cpp.
{
     dep_ = dep;
     check_dep();
   }
References casadi::MXNode::check_dep(), casadi::MXNode::dep(), and casadi::MXNode::dep_.
set_sparsity()
void casadi::MXNode::set_sparsity (const Sparsity & sparsity) inherited
Definition at line 222 of file mx_node.cpp.
{
     sparsity_ = sparsity;
   }
References casadi::MXNode::sparsity(), and casadi::MXNode::sparsity_.
Referenced by casadi::Assertion::Assertion(), casadi::Bilin::Bilin(), casadi::BinaryMX< ScX, ScY >::BinaryMX(), casadi::BSpline::BSpline(), casadi::BSplineParametric::BSplineParametric(), casadi::Call::Call(), casadi::ConstantMX::ConstantMX(), casadi::Convexify::Convexify(), casadi::Determinant::Determinant(), casadi::Diagcat::Diagcat(), casadi::Dot::Dot(), casadi::Einstein::Einstein(), casadi::Find::Find(), casadi::GetNonzeros::GetNonzeros(), casadi::GetNonzerosParam::GetNonzerosParam(), casadi::Horzcat::Horzcat(), casadi::HorzRepmat::HorzRepmat(), casadi::HorzRepsum::HorzRepsum(), casadi::Input::Input(), casadi::Inverse::Inverse(), casadi::LogSumExp::LogSumExp(), casadi::Low::Low(), casadi::MMax::MMax(), casadi::MMin::MMin(), casadi::Monitor::Monitor(), casadi::Multiplication::Multiplication(), casadi::Norm::Norm(), casadi::OutputNode::OutputNode(), casadi::Project::Project(), Rank1(), casadi::Reshape::Reshape(), casadi::SparsityCast::SparsityCast(), casadi::Split::Split(), casadi::SymbolicMX::SymbolicMX(), casadi::Transpose::Transpose(), casadi::UnaryMX::UnaryMX(), and casadi::Vertcat::Vertcat().
shared_from_this() [1/2]
B casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::shared_from_this () inline protected inherited
Definition at line 83 of file generic_shared_internal.hpp.
{
       casadi_assert_dev(B::test_cast(static_cast<Internal*>(this)));
       B ret;
       ret.own(static_cast<Internal*>(this));
       return ret;
     }
shared_from_this() [2/2]
const B casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::shared_from_this () const inline protected inherited
Definition at line 92 of file generic_shared_internal.hpp.
{
       casadi_assert_dev(B::test_cast(static_cast<const Internal*>(this)));
       B ret;
       ret.own(const_cast<Internal*>(static_cast<const Internal*>(this)));
       return ret;
     }
size()
std::pair<casadi_int, casadi_int> casadi::MXNode::size () const inline inherited
Definition at line 392 of file mx_node.hpp.
 { return sparsity().size();}
Referenced by casadi::MXNode::_get_binary(), casadi::Reshape::ad_forward(), casadi::Reshape::ad_reverse(), casadi::Reshape::eval_mx(), casadi::MXNode::get_binary(), casadi::MXNode::join_primitives_gen(), casadi::Reshape::join_primitives_gen(), and casadi::Reshape::split_primitives_gen().
size1()
casadi_int casadi::MXNode::size1 () const inline inherited
Definition at line 390 of file mx_node.hpp.
 { return sparsity().size1(); }
Referenced by casadi::ConstantMX::ad_forward(), casadi::MXNode::get_dot(), and casadi::MXNode::get_vertsplit().
size2()
casadi_int casadi::MXNode::size2 () const inline inherited
Definition at line 391 of file mx_node.hpp.
 { return sparsity().size2(); }
Referenced by casadi::ConstantMX::ad_forward(), casadi::MXNode::get_dot(), and casadi::MXNode::get_horzsplit().
sp_forward()
int casadi::Rank1::sp_forward (const bvec_t ** arg, bvec_t ** res, casadi_int * iw, bvec_t * w) const override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_2
Reimplemented from casadi::MXNode.
Definition at line 79 of file rank1.cpp.
{
     /* If not inline, copy to result */
     if (arg[0]!=res[0]) std::copy(arg[0], arg[0]+dep(0).nnz(), res[0]);
     /* Get sparsities */
     casadi_int ncol_A = sparsity().size2();
     const casadi_int *colind_A = sparsity().colind(), *row_A = sparsity().row();
     /* Loop over the columns of A */
     casadi_int cc, rr, el;
     for (cc=0; cc<ncol_A; ++cc) {
       /* Loop over the nonzeros of A */
       for (el=colind_A[cc]; el<colind_A[cc+1]; ++el) {
         /* Get row */
         rr = row_A[el];
         /* Add the multiple */
         res[0][el] |= *arg[1] | arg[2][rr] | arg[3][cc];
       }
     }
     return 0;
   }
References casadi::Sparsity::colind(), casadi::MXNode::dep(), casadi::MXNode::nnz(), casadi::Sparsity::row(), casadi::Sparsity::size2(), and casadi::MXNode::sparsity().
sp_reverse()
int casadi::Rank1::sp_reverse (bvec_t ** arg, bvec_t ** res, casadi_int * iw, bvec_t * w) const override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_3
Reimplemented from casadi::MXNode.
Definition at line 102 of file rank1.cpp.
{
     /* Get sparsities */
     casadi_int ncol_A = sparsity().size2();
     const casadi_int *colind_A = sparsity().colind(), *row_A = sparsity().row();
     /* Loop over the columns of A */
     casadi_int cc, rr, el;
     for (cc=0; cc<ncol_A; ++cc) {
       /* Loop over the nonzeros of A */
       for (el=colind_A[cc]; el<colind_A[cc+1]; ++el) {
         /* Get row */
         rr = row_A[el];
         /* Add the multiple */
         *arg[1] |= res[0][el];
         arg[2][rr] |= res[0][el];
         arg[3][cc] |= res[0][el];
       }
     }
     // Clear seeds
     copy_rev(arg[0], res[0], nnz());
     return 0;
   }
References casadi::Sparsity::colind(), casadi::MXNode::copy_rev(), casadi::MXNode::nnz(), casadi::Sparsity::row(), casadi::Sparsity::size2(), and casadi::MXNode::sparsity().
sparsity() [1/2]
const Sparsity& casadi::MXNode::sparsity () const inline inherited
Definition at line 372 of file mx_node.hpp.
 { return sparsity_;}
Referenced by casadi::MXNode::_get_binary(), casadi::GetNonzeros::ad_forward(), casadi::GetNonzerosParamVector::ad_forward(), casadi::GetNonzerosSliceParam::ad_forward(), casadi::GetNonzerosParamSlice::ad_forward(), casadi::GetNonzerosParamParam::ad_forward(), casadi::LogSumExp::ad_forward(), casadi::Multiplication::ad_forward(), casadi::Project::ad_forward(), ad_forward(), casadi::SparsityCast::ad_forward(), casadi::Bilin::ad_reverse(), casadi::GetNonzeros::ad_reverse(), casadi::GetNonzerosParamVector::ad_reverse(), casadi::GetNonzerosSliceParam::ad_reverse(), casadi::GetNonzerosParamSlice::ad_reverse(), casadi::GetNonzerosParamParam::ad_reverse(), casadi::Multiplication::ad_reverse(), casadi::Project::ad_reverse(), casadi::SparsityCast::ad_reverse(), casadi::Diagcat::Diagcat(), casadi::ConstantFile::disp(), casadi::ConstantPool::disp(), casadi::Project::disp(), casadi::Reshape::disp(), casadi::SparsityCast::disp(), casadi::Bilin::eval_gen(), casadi::Multiplication::eval_gen(), casadi::Project::eval_gen(), casadi::Densify::eval_gen(), casadi::Sparsify::eval_gen(), eval_gen(), casadi::HorzRepsum::eval_gen(), casadi::Transpose::eval_gen(), casadi::MXNode::eval_linear(), casadi::GetNonzeros::eval_mx(), casadi::GetNonzerosVector::eval_mx(), casadi::GetNonzerosParamVector::eval_mx(), casadi::GetNonzerosSliceParam::eval_mx(), casadi::GetNonzerosParamSlice::eval_mx(), casadi::GetNonzerosParamParam::eval_mx(), casadi::Project::eval_mx(), casadi::SparsityCast::eval_mx(), casadi::Bilin::generate(), casadi::Find::generate(), casadi::Multiplication::generate(), casadi::Project::generate(), casadi::Densify::generate(), casadi::Sparsify::generate(), generate(), casadi::HorzRepmat::generate(), casadi::HorzRepsum::generate(), casadi::Transpose::generate(), casadi::UnaryMX::generate(), casadi::MXNode::get_binary(), casadi::MXNode::get_diagsplit(), casadi::MXNode::get_dot(), casadi::Horzsplit::get_horzcat(), casadi::MXNode::get_horzsplit(), casadi::MXNode::get_mac(), casadi::MXNode::get_nzref(), casadi::Call::get_output(), casadi::MultipleOutput::get_output(), casadi::MXNode::get_project(), casadi::MXNode::get_reshape(), casadi::SparsityCast::get_reshape(), casadi::MXNode::get_sparsity_cast(), casadi::MXNode::get_transpose(), casadi::Reshape::get_transpose(), casadi::SparsityCast::get_transpose(), casadi::MXNode::get_unary(), casadi::MXNode::get_vertsplit(), casadi::Horzcat::Horzcat(), casadi::ConstantDM::is_equal(), casadi::Constant< Value >::is_equal(), casadi::GetNonzerosVector::is_equal(), casadi::GetNonzerosSlice::is_equal(), casadi::GetNonzerosSlice2::is_equal(), casadi::Reshape::is_equal(), casadi::SetNonzerosVector< Add >::is_equal(), casadi::SetNonzerosSlice< Add >::is_equal(), casadi::SetNonzerosSlice2< Add >::is_equal(), casadi::SparsityCast::is_equal(), casadi::ConstantMX::join_primitives_gen(), casadi::SparsityCast::join_primitives_gen(), casadi::GetNonzeros::mapping(), casadi::OutputNode::OutputNode(), casadi::MXFunction::print_res(), casadi::MXNode::set_sparsity(), casadi::MXNode::sp_forward(), casadi::Multiplication::sp_forward(), casadi::Project::sp_forward(), sp_forward(), casadi::HorzRepsum::sp_forward(), casadi::Split::sp_forward(), casadi::Transpose::sp_forward(), casadi::MXNode::sp_reverse(), casadi::Multiplication::sp_reverse(), casadi::Project::sp_reverse(), sp_reverse(), casadi::HorzRepmat::sp_reverse(), casadi::HorzRepsum::sp_reverse(), casadi::Split::sp_reverse(), casadi::Transpose::sp_reverse(), casadi::SparsityCast::split_primitives_gen(), casadi::UnaryMX::UnaryMX(), and casadi::Vertcat::Vertcat().
sparsity() [2/2]
const Sparsity & casadi::MXNode::sparsity (casadi_int oind) const virtual inherited
Reimplemented in casadi::MultipleOutput, casadi::Split, and casadi::Call.
Definition at line 262 of file mx_node.cpp.
{
     casadi_assert(oind==0, "Index out of bounds");
     return sparsity_;
   }
References casadi::MXNode::sparsity_.
split_primitives() [1/3]
void casadi::MXNode::split_primitives (const DM & x, std::vector< DM >::iterator & it) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1r6
Reimplemented in casadi::SparsityCast, casadi::Reshape, casadi::ConstantMX, casadi::Diagcat, casadi::Vertcat, and casadi::Horzcat.
Definition at line 166 of file mx_node.cpp.
{
     *it++ = x;
   }
split_primitives() [2/3]
void casadi::MXNode::split_primitives (const MX & x, std::vector< MX >::iterator & it) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1r6
Reimplemented in casadi::SparsityCast, casadi::Reshape, casadi::ConstantMX, casadi::Diagcat, casadi::Vertcat, and casadi::Horzcat.
Definition at line 158 of file mx_node.cpp.
{
     *it++ = x;
   }
Referenced by casadi::Horzcat::split_primitives_gen(), casadi::Vertcat::split_primitives_gen(), casadi::Diagcat::split_primitives_gen(), casadi::ConstantMX::split_primitives_gen(), casadi::Reshape::split_primitives_gen(), and casadi::SparsityCast::split_primitives_gen().
split_primitives() [3/3]
void casadi::MXNode::split_primitives (const SX & x, std::vector< SX >::iterator & it) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1r6
Reimplemented in casadi::SparsityCast, casadi::Reshape, casadi::ConstantMX, casadi::Diagcat, casadi::Vertcat, and casadi::Horzcat.
Definition at line 162 of file mx_node.cpp.
{
     *it++ = x;
   }
sz_arg()
virtual size_t casadi::MXNode::sz_arg () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1rq
Reimplemented in casadi::Call.
Definition at line 409 of file mx_node.hpp.
 { return n_dep();}
sz_iw()
virtual size_t casadi::MXNode::sz_iw () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1rs
Reimplemented in casadi::DenseTranspose, casadi::Transpose, casadi::SetNonzerosParamParam< Add >, casadi::SetNonzerosParamSlice< Add >, casadi::GetNonzerosParamParam, casadi::GetNonzerosParamSlice, casadi::Convexify, casadi::Call, and casadi::BSplineCommon.
Definition at line 419 of file mx_node.hpp.
 { return 0;}
sz_res()
virtual size_t casadi::MXNode::sz_res () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1rr
Reimplemented in casadi::Call.
Definition at line 414 of file mx_node.hpp.
 { return nout();}
sz_w()
virtual size_t casadi::MXNode::sz_w () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1rt
Reimplemented in casadi::LinsolCall< Tr >, casadi::Sparsify, casadi::Densify, casadi::Project, casadi::Multiplication, casadi::Einstein, casadi::Convexify, casadi::Call, and casadi::BSplineCommon.
Definition at line 424 of file mx_node.hpp.
 { return 0;}
to_double()
double casadi::MXNode::to_double () const virtual inherited
Reimplemented in casadi::ConstantMX, casadi::Constant< Value >, casadi::ZeroByZero, casadi::ConstantPool, casadi::ConstantFile, and casadi::ConstantDM.
Definition at line 476 of file mx_node.cpp.
{
     casadi_error("'to_double' not defined for class " + class_name());
   }
References casadi::MXNode::class_name().
Referenced by casadi::Constant< Value >::_get_binary(), and casadi::MX::operator double().
to_matrix()
static MX casadi::MXNode::to_matrix (const MX & x, const Sparsity & sp) inline static inherited
Definition at line 442 of file mx_node.hpp.
{
       if (x.size()==sp.size()) {
         return x;
       } else {
         return MX(sp, x);
       }
     }
References casadi::GenericMatrix< MatType >::size(), and casadi::Sparsity::size().
Referenced by casadi::MXNode::get_binary().
weak()
GenericWeakRef< SharedObject , SharedObjectInternal > * casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::weak inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1ai
Definition at line 67 of file generic_shared_internal.hpp.
{
     if (weak_ref_==nullptr) {
       weak_ref_ = new GenericWeakRef<Shared, Internal>(static_cast<Internal*>(this));
     }
     return weak_ref_;
   }
which_function()
const Function & casadi::MXNode::which_function () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1rd
Reimplemented in casadi::Call.
Definition at line 330 of file mx_node.cpp.
{
     casadi_error("'which_function' not defined for class " + class_name());
   }
References casadi::MXNode::class_name().
which_output()
casadi_int casadi::MXNode::which_output () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1rc
Reimplemented in casadi::OutputNode, and casadi::Call.
Definition at line 334 of file mx_node.cpp.
{
     casadi_error("'which_output' not defined for class " + class_name());
   }
References casadi::MXNode::class_name().
Referenced by casadi::Diagsplit::get_diagcat(), casadi::Horzsplit::get_horzcat(), and casadi::Vertsplit::get_vertcat().
Member Data Documentation
dep_
std::vector<MX> casadi::MXNode::dep_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1sj
Definition at line 762 of file mx_node.hpp.
Referenced by casadi::MXNode::check_dep(), casadi::MX::cse(), casadi::BlazingSplineFunction::merge(), casadi::MXNode::MXNode(), casadi::MXNode::n_dep(), casadi::MXNode::serialize_body(), casadi::MXNode::set_dep(), and casadi::MXNode::~MXNode().
deserialize_map
std::map< casadi_int, MXNode *(*)(DeserializingStream &)> casadi::MXNode::deserialize_map static inherited
Definition at line 779 of file mx_node.hpp.
Referenced by casadi::MXNode::deserialize().
sparsity_
Sparsity casadi::MXNode::sparsity_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1sk
Definition at line 767 of file mx_node.hpp.
Referenced by casadi::ConstantDM::ConstantDM(), casadi::MXNode::get_mmax(), casadi::MXNode::get_mmin(), casadi::MXNode::MXNode(), casadi::MXNode::serialize_body(), casadi::MXNode::set_sparsity(), and casadi::MXNode::sparsity().
temp
casadi_int casadi::MXNode::temp mutable inherited
Temporary variables to be used in user algorithms like sorting, the user is responsible of making sure that use is thread-safe The variable is initialized to zero
Definition at line 757 of file mx_node.hpp.
Referenced by casadi::SymbolicMX::has_duplicates(), casadi::MXNode::MXNode(), and casadi::SymbolicMX::reset_input().
The documentation for this class was generated from the following files:
rank1.hpp
rank1.cpp