CasADi: casadi::LinsolQrMemory Struct Reference
casadi::LinsolQrMemory Struct Reference
#include <linsol_qr.hpp>
Detailed Description
Definition at line 43 of file linsol_qr.hpp.
Public Member Functions
void add_stat (const std::string &s)
Public Attributes
std::vector< double > v
std::vector< double > r
std::vector< double > beta
std::vector< double > w
std::vector< double > cache
std::vector< int > cache_loc
bool is_sfact
bool is_nfact
std::map< std::string, FStats > fstats
FStats * t_total
Member Function Documentation
add_stat()
void casadi::ProtoFunctionMemory::add_stat (const std::string & s) inline inherited
Definition at line 74 of file function_internal.hpp.
{
       bool added = fstats.insert(std::make_pair(s, FStats())).second;
       casadi_assert(added, "Duplicate stat: '" + s + "'");
     }
Referenced by casadi::ProtoFunction::init_mem(), casadi::LinsolInternal::init_mem(), casadi::Nlpsol::init_mem(), casadi::OracleFunction::init_mem(), casadi::CbcInterface::init_mem(), casadi::ClpInterface::init_mem(), casadi::FatropConicInterface::init_mem(), casadi::HpipmInterface::init_mem(), casadi::Feasiblesqpmethod::init_mem(), casadi::Sqpmethod::init_mem(), and casadi::OracleFunction::local_init_mem().
Member Data Documentation
beta
std::vector<double> casadi::LinsolQrMemory::beta
Definition at line 44 of file linsol_qr.hpp.
cache
std::vector<double> casadi::LinsolQrMemory::cache
Definition at line 45 of file linsol_qr.hpp.
cache_loc
std::vector<int> casadi::LinsolQrMemory::cache_loc
Definition at line 48 of file linsol_qr.hpp.
fstats
std::map<std::string, FStats> casadi::ProtoFunctionMemory::fstats inherited
Definition at line 68 of file function_internal.hpp.
Referenced by casadi::Nlpsol::callback(), casadi::IpoptUserClass::eval_h(), casadi::BonminInterface::intermediate_callback(), casadi::IpoptInterface::intermediate_callback(), casadi::OracleFunction::join_results(), casadi::ClarabelInterface::solve(), casadi::DaqpInterface::solve(), casadi::HighsInterface::solve(), casadi::HpipmInterface::solve(), casadi::HpmpcInterface::solve(), casadi::ProxqpInterface::solve(), casadi::QpoasesInterface::solve(), casadi::Sqpmethod::solve_ela_QP(), casadi::Feasiblesqpmethod::solve_LP(), casadi::Feasiblesqpmethod::solve_QP(), and casadi::Sqpmethod::solve_QP().
is_nfact
bool casadi::LinsolMemory::is_nfact inherited
Definition at line 39 of file linsol_internal.hpp.
Referenced by casadi::Linsol::nfact().
is_sfact
bool casadi::LinsolMemory::is_sfact inherited
Definition at line 39 of file linsol_internal.hpp.
Referenced by casadi::Linsol::sfact().
r
std::vector<double> casadi::LinsolQrMemory::r
Definition at line 44 of file linsol_qr.hpp.
t_total
FStats* casadi::ProtoFunctionMemory::t_total inherited
Definition at line 71 of file function_internal.hpp.
Referenced by casadi::LinsolCall< Tr >::eval(), and casadi::Linsol::solve().
v
std::vector<double> casadi::LinsolQrMemory::v
Definition at line 44 of file linsol_qr.hpp.
Referenced by casadi::LinsolQr::init_mem().
w
std::vector<double> casadi::LinsolQrMemory::w
Definition at line 44 of file linsol_qr.hpp.
The documentation for this struct was generated from the following file:
linsol_qr.hpp