CasADi: casadi::Opti Class Reference
casadi::Opti Class Reference
A simplified interface for NLP modeling/solving.
#include <optistack.hpp>
Detailed Description
This class offers a view with model description facilities The API is guaranteed to be stable.
Example NLP:
  opti = casadi.Opti();
  x = opti.variable();
  y = opti.variable();
  opti.minimize(  (y-x^2)^2   );
  opti.subject_to( x^2+y^2==1 );
  opti.subject_to(     x+y>=1 );
  opti.solver('ipopt');
  sol = opti.solve();
  sol.value(x)
  sol.value(y)
Example parametric NLP:
  opti = casadi.Opti();
  x = opti.variable(2,1);
  p = opti.parameter();
  opti.minimize(  (p*x(2)-x(1)^2)^2   );
  opti.subject_to( 1<=sum(x)<=2 );
  opti.solver('ipopt');
  opti.set_value(p, 3);
  sol = opti.solve();
  sol.value(x)
  opti.set_value(p, 5);
  sol = opti.solve();
  sol.value(x)
Date
2017
Author
Joris Gillis, Erik Lambrechts, Joel Andersson
Extra doc: https://github.com/casadi/casadi/wiki/L_16
Definition at line 88 of file optistack.hpp.
Public Types
using internal_base_type = SharedObjectInternal
using base_type = SharedObject
Public Member Functions
Opti (const std::string &problem_type="nlp")
Create Opti Context.
MX variable (casadi_int n=1, casadi_int m=1, const std::string &attribute="full")
Create a decision variable (symbol)
MX variable (const Sparsity &sp, const std::string &attribute="full")
MX variable (const MX &symbol, const std::string &attribute="full")
MX parameter (casadi_int n=1, casadi_int m=1, const std::string &attribute="full")
Create a parameter (symbol); fixed during optimization.
MX parameter (const Sparsity &sp, const std::string &attribute="full")
MX parameter (const MX &symbol, const std::string &attribute="full")
void minimize (const MX &f, double linear_scale=1)
Set objective.
void subject_to ()
Clear constraints.
void solver (const std::string &solver, const Dict &plugin_options=Dict(), const Dict &solver_options=Dict())
Set a solver.
Dict stats () const
Get statistics.
std::string return_status () const
Get return status of solver.
std::vector< MX > initial () const
get assignment expressions for initial values
std::vector< MX > value_variables () const
get assignment expressions for latest values
std::vector< MX > value_parameters () const
Function scale_helper (const Function &h) const
Scale a helper function constructed via opti.x, opti.g, ...
MX dual (const MX &m) const
get the dual variable
casadi_int nx () const
Number of (scalarised) decision variables.
casadi_int np () const
Number of (scalarised) parameters.
casadi_int ng () const
Number of (scalarised) constraints.
MX x () const
Get all (scalarised) decision variables as a symbolic column vector.
MX p () const
Get all (scalarised) parameters as a symbolic column vector.
MX g () const
Get all (scalarised) constraint expressions as a column vector.
MX f () const
Get objective expression.
MX lbg () const
Get all (scalarised) bounds on constraints as a column vector.
MX ubg () const
DM x_linear_scale () const
DM x_linear_scale_offset () const
DM g_linear_scale () const
double f_linear_scale () const
MX lam_g () const
Get all (scalarised) dual variables as a symbolic column vector.
OptiAdvanced debug () const
Get a copy with advanced functionality.
OptiAdvanced advanced () const
Get a copy with advanced functionality.
Opti copy () const
Get a copy of the.
void update_user_dict (const MX &m, const Dict &meta)
add user data
void update_user_dict (const std::vector< MX > &m, const Dict &meta)
Dict user_dict (const MX &m) const
Get user data.
std::string type_name () const
Readable name of the class.
void disp (std::ostream &stream, bool more=false) const
Print representation.
std::string get_str (bool more=false) const
Get string representation.
Opti (const Opti &x)
~Opti ()
Destructor.
Opti (OptiNode *node)
std::string class_name () const
Get class name.
void print_ptr (std::ostream &stream=casadi::uout()) const
void own (SharedObjectInternal *node)
void assign (SharedObjectInternal *node)
Assign the node to a node class pointer without reference counting.
SharedObjectInternal * get () const
Get a const pointer to the node.
casadi_int getCount () const
Get the reference count.
void swap (GenericShared &other)
Swap content with another instance.
std::string debug_repr () const
bool is_null () const
Is a null pointer?
casadi_int __hash__ () const
Returns a number that is unique for a given Node.
GenericWeakRef< SharedObject, SharedObjectInternal > * weak ()
Get a weak reference to the object.
void subject_to (const MX &g, const Dict &options=Dict())
Add constraints.
void subject_to (const std::vector< MX > &g, const Dict &options=Dict())
Add constraints.
void subject_to (const MX &g, const DM &linear_scale, const Dict &options=Dict())
Add constraints.
void subject_to (const std::vector< MX > &g, const DM &linear_scale, const Dict &options=Dict())
Add constraints.
void set_initial (const MX &x, const DM &v)
void set_initial (const std::vector< MX > &assignments)
void set_value (const MX &x, const DM &v)
Set value of parameter.
void set_value (const std::vector< MX > &assignments)
Set value of parameter.
void set_domain (const MX &x, const std::string &domain)
Set domain of a decision variable.
void set_linear_scale (const MX &x, const DM &scale, const DM &offset=0)
Set scale of a decision variable.
OptiSol solve ()
Crunch the numbers; solve the problem.
OptiSol solve_limited ()
Crunch the numbers; solve the problem.
native_DM value (const MX &x, const std::vector< MX > &values=std::vector< MX >()) const
native_DM value (const DM &x, const std::vector< MX > &values=std::vector< MX >()) const
Set domain of a decision variable.
native_DM value (const SX &x, const std::vector< MX > &values=std::vector< MX >()) const
Set domain of a decision variable.
Function to_function (const std::string &name, const std::vector< MX > &args, const std::vector< MX > &res, const Dict &opts=Dict())
Create a CasADi Function from the Opti solver.
Function to_function (const std::string &name, const std::vector< MX > &args, const std::vector< MX > &res, const std::vector< std::string > &name_in, const std::vector< std::string > &name_out, const Dict &opts=Dict())
Create a CasADi Function from the Opti solver.
Function to_function (const std::string &name, const std::map< std::string, MX > &dict, const std::vector< std::string > &name_in, const std::vector< std::string > &name_out, const Dict &opts=Dict())
Create a CasADi Function from the Opti solver.
void callback_class (OptiCallback *callback)
Helper methods for callback()
void callback_class ()
Helper methods for callback()
OptiNode * operator-> ()
Access a member of the node.
const OptiNode * operator-> () const
Const access a member of the node.
Static Public Member Functions
static MX bounded (const MX &lb, const MX &expr, const MX &ub)
Construct a double inequality.
static Opti create (OptiNode *node)
Protected Member Functions
void count_up ()
void count_down ()
Friends
class InternalOptiCallback
Member Typedef Documentation
base_type
using casadi::SharedObject::base_type = SharedObject inherited
Definition at line 103 of file shared_object.hpp.
internal_base_type
using casadi::SharedObject::internal_base_type = SharedObjectInternal inherited
Definition at line 102 of file shared_object.hpp.
Constructor & Destructor Documentation
Opti() [1/3]
casadi::Opti::Opti (const std::string & problem_type = "nlp")
Parameters
[in] problem_type of optimization 'nlp' or 'conic' (default nlp)
Extra doc: https://github.com/casadi/casadi/wiki/L_17
Definition at line 47 of file optistack.cpp.
{
   own(OptiNode::create(problem_type));
 }
References casadi::OptiNode::create(), and casadi::GenericShared< SharedObject, SharedObjectInternal >::own().
Referenced by create().
Opti() [2/3]
casadi::Opti::Opti (const Opti & x)
Definition at line 79 of file optistack.cpp.
                           : SharedObject(rhs) {
   callback_class();
 }
References callback_class().
~Opti()
casadi::Opti::~Opti () inline
Extra doc: https://github.com/casadi/casadi/wiki/L_1q
Definition at line 464 of file optistack.hpp.
 {}
Opti() [3/3]
casadi::Opti::Opti (OptiNode * node)
Definition at line 75 of file optistack.cpp.
{
   own(node);
 }
References casadi::GenericShared< SharedObject, SharedObjectInternal >::own().
Member Function Documentation
__hash__()
casadi_int casadi::GenericShared< SharedObject , SharedObjectInternal >::__hash__ inherited
If the Object does not point to any node, "0" is returned.
Extra doc: https://github.com/casadi/casadi/wiki/L_av
Definition at line 124 of file generic_shared_impl.hpp.
{
     return reinterpret_cast<casadi_int>(get());
   }
advanced()
OptiAdvanced casadi::Opti::advanced () const
You get access to more methods, but you have no guarantees about API stability
The copy is effectively a deep copy: Updating the state of the copy does not update the original.
Extra doc: https://github.com/casadi/casadi/wiki/L_1m
Definition at line 850 of file optistack.cpp.
{
   return copy();
 }
References copy().
assign()
void casadi::GenericShared< SharedObject , SharedObjectInternal >::assign (Internal * node) inherited
improper use will cause memory leaks!
Extra doc: https://github.com/casadi/casadi/wiki/L_at
Definition at line 97 of file generic_shared_impl.hpp.
{
     node = node_;
   }
bounded()
static MX casadi::Opti::bounded (const MX & lb, const MX & expr, const MX & ub) inline static
Constructs: lb(p) <= g(x,p) <= ub(p)
Python prohibits such syntax directly
Extra doc: https://github.com/casadi/casadi/wiki/L_1k
Definition at line 397 of file optistack.hpp.
 { return (lb<=expr)<= ub; }
callback_class() [1/2]
void casadi::Opti::callback_class ()
Do not use directly.
Extra doc: https://github.com/casadi/casadi/wiki/L_1p
Definition at line 471 of file optistack.cpp.
{
   try {
     (*this)->callback_class();
   } catch(std::exception& e) {
     THROW_ERROR("callback_class", e.what());
   }
 }
Referenced by Opti().
callback_class() [2/2]
void casadi::Opti::callback_class (OptiCallback * callback)
Do not use directly.
Extra doc: https://github.com/casadi/casadi/wiki/L_1p
Definition at line 463 of file optistack.cpp.
{
   try {
     (*this)->callback_class(callback);
   } catch(std::exception& e) {
     THROW_ERROR("callback_class", e.what());
   }
 }
class_name()
std::string casadi::SharedObject::class_name () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_au
Definition at line 31 of file shared_object.cpp.
{
     return (*this)->class_name();
   }
Referenced by casadi::FmuFunction::check_mem_count(), casadi::MXFunction::export_code_body(), and casadi::BlazingSplineFunction::merge().
copy()
Opti casadi::Opti::copy () const
The copy is effectively a deep copy: Updating the state of the copy does not update the original.
Extra doc: https://github.com/casadi/casadi/wiki/L_1n
Definition at line 853 of file optistack.cpp.
                       {
   return (*this)->copy();
 }
References casadi::OptiNode::copy().
Referenced by advanced(), and debug().
count_down()
void casadi::GenericShared< SharedObject , SharedObjectInternal >::count_down protected inherited
Definition at line 134 of file generic_shared_impl.hpp.
{
 #ifdef WITH_EXTRA_CHECKS
     casadi_assert_dev(Function::call_depth_==0);
 #endif // WITH_EXTRA_CHECKS
     if (!node) return;
     if (node->weak_ref_) {
 #ifdef CASADI_WITH_THREADSAFE_SYMBOLICS
       auto mutex = node->weak_ref_->get_mutex();
       // Avoid triggering a delete while a weak_ref.shared_if_alive is being called
       std::lock_guard<std::mutex> lock(*mutex);
       // Could it be that this mutex is destroyed when the lock goes out of scope?
 #endif // CASADI_WITH_THREADSAFE_SYMBOLICS
       if (--static_cast<Internal*>(node)->count == 0) {
         delete node;
         node = nullptr;
       }
     } else {
       if (--static_cast<Internal*>(node)->count == 0) {
         delete node;
         node = nullptr;
       }
     }
   }
count_up()
void casadi::GenericShared< SharedObject , SharedObjectInternal >::count_up protected inherited
Definition at line 133 of file generic_shared_impl.hpp.
{
 #ifdef WITH_EXTRA_CHECKS
     casadi_assert_dev(Function::call_depth_==0);
 #endif // WITH_EXTRA_CHECKS
     if (node) static_cast<Internal*>(node)->count++;
   }
create()
Opti casadi::Opti::create (OptiNode * node) static
Definition at line 86 of file optistack.cpp.
{
   return Opti(node);
 }
References Opti().
Referenced by casadi::OptiNode::copy().
debug()
OptiAdvanced casadi::Opti::debug () const
You get access to more methods, but you have no guarantees about API stability
The copy is effectively a deep copy: Updating the state of the copy does not update the original.
Extra doc: https://github.com/casadi/casadi/wiki/L_1l
Definition at line 847 of file optistack.cpp.
{
   return copy();
 }
References copy().
Referenced by disp().
debug_repr()
std::string casadi::GenericShared< SharedObject , SharedObjectInternal >::debug_repr inherited
Definition at line 113 of file generic_shared_impl.hpp.
{
     if (node) {
         return node->debug_repr(node);
     } else {
         return "NULL";
     }
   }
disp()
void casadi::Opti::disp (std::ostream & stream, bool more = false) const
Definition at line 750 of file optistack.cpp.
{
   stream << "Opti {" << std::endl;
   OptiAdvanced mycopy = debug();
   stream << "  instance #" << mycopy.instance_number() << std::endl;
   if (mycopy.problem_dirty()) mycopy.bake();
   stream << "  #variables: " << mycopy.active_symvar(OPTI_VAR).size()
     << " (nx = " << mycopy.nx() << ")" <<  std::endl;
   stream << "  #parameters: " << mycopy.active_symvar(OPTI_PAR).size()
     << " (np = " << mycopy.np() << ")" << std::endl;
   stream << "  #constraints: " << mycopy.active_symvar(OPTI_DUAL_G).size()
     << " (ng = " << mycopy.ng() << ")" << std::endl;
   if (mycopy.solver_dirty()) {
     stream << "  CasADi solver needs updating." << std::endl;
   } else {
     stream << "  CasADi solver allocated." << std::endl;
   }
   if (mycopy.solved()) {
     stream << "  CasADi solver was called: " << mycopy.return_status() << std::endl;
   }
   stream << "}";
 }
References casadi::OptiAdvanced::active_symvar(), casadi::OptiAdvanced::bake(), debug(), casadi::OptiAdvanced::instance_number(), ng(), np(), nx(), casadi::OPTI_DUAL_G, casadi::OPTI_PAR, casadi::OPTI_VAR, casadi::OptiAdvanced::problem_dirty(), return_status(), casadi::OptiAdvanced::solved(), and casadi::OptiAdvanced::solver_dirty().
Referenced by casadi::OptiSol::disp(), and get_str().
dual()
MX casadi::Opti::dual (const MX & m) const
m must be a constraint expression. The returned value is still a symbolic expression. Use value on it to obtain the numerical value.
Extra doc: https://github.com/casadi/casadi/wiki/L_1h
Definition at line 302 of file optistack.cpp.
{
   try {
     return (*this)->dual(m);
   } catch(std::exception& e) {
     THROW_ERROR("dual", e.what());
   }
 }
f()
MX casadi::Opti::f () const
Extra doc: https://github.com/casadi/casadi/wiki/L_26e
Definition at line 358 of file optistack.cpp.
                  {
   try {
     return (*this)->f();
   } catch(std::exception& e) {
     THROW_ERROR("f", e.what());
   }
 }
Referenced by minimize(), and casadi::OptiAdvanced::objective().
f_linear_scale()
double casadi::Opti::f_linear_scale () const
Definition at line 415 of file optistack.cpp.
{
   try {
     return (*this)->f_linear_scale();
   } catch(std::exception& e) {
     THROW_ERROR("f_linear_scale", e.what());
   }
 }
g()
MX casadi::Opti::g () const
Extra doc: https://github.com/casadi/casadi/wiki/L_26d
Definition at line 350 of file optistack.cpp.
                  {
   try {
     return (*this)->g();
   } catch(std::exception& e) {
     THROW_ERROR("g", e.what());
   }
 }
Referenced by subject_to().
g_linear_scale()
DM casadi::Opti::g_linear_scale () const
Definition at line 407 of file optistack.cpp.
{
   try {
     return (*this)->g_linear_scale();
   } catch(std::exception& e) {
     THROW_ERROR("g_linear_scale", e.what());
   }
 }
get()
SharedObjectInternal * casadi::GenericShared< SharedObject , SharedObjectInternal >::get inherited
Definition at line 100 of file generic_shared_impl.hpp.
{
     return node;
   }
get_str()
std::string casadi::Opti::get_str (bool more = false) const
Definition at line 772 of file optistack.cpp.
{
     std::stringstream ss;
     disp(ss, more);
     return ss.str();
 }
References disp().
Referenced by casadi::OptiSol::get_str().
getCount()
casadi_int casadi::GenericShared< SharedObject , SharedObjectInternal >::getCount inherited
Definition at line 103 of file generic_shared_impl.hpp.
{
     return (*this)->getCount();
   }
initial()
std::vector< MX > casadi::Opti::initial () const
Extra doc: https://github.com/casadi/casadi/wiki/L_266
Definition at line 278 of file optistack.cpp.
{
   try {
     return (*this)->initial();
   } catch(std::exception& e) {
     THROW_ERROR("initial", e.what());
   }
 }
is_null()
bool casadi::GenericShared< SharedObject , SharedObjectInternal >::is_null inherited
Definition at line 117 of file generic_shared_impl.hpp.
{
     return node==nullptr;
   }
lam_g()
MX casadi::Opti::lam_g () const
Useful for obtaining the Lagrange Hessian:
* sol.value(hessian(opti.f+opti.lam_g'*opti.g,opti.x)) % MATLAB
* sol.value(hessian(opti.f+dot(opti.lam_g,opti.g),opti.x)[0]) # Python
*
Extra doc: https://github.com/casadi/casadi/wiki/L_1i
Definition at line 383 of file optistack.cpp.
                      {
   try {
     return (*this)->lam_g();
   } catch(std::exception& e) {
     THROW_ERROR("lam_g", e.what());
   }
 }
lbg()
MX casadi::Opti::lbg () const
Extra doc: https://github.com/casadi/casadi/wiki/L_26f
Definition at line 366 of file optistack.cpp.
                    {
   try {
     return (*this)->lbg();
   } catch(std::exception& e) {
     THROW_ERROR("lbg", e.what());
   }
 }
minimize()
void casadi::Opti::minimize (const MX & f, double linear_scale = 1)
Objective must be a scalar. Default objective: 0 When method is called multiple times, the last call takes effect
Extra doc: https://github.com/casadi/casadi/wiki/L_1a
Definition at line 114 of file optistack.cpp.
{
   try {
     (*this)->minimize(f, linear_scale);
   } catch(std::exception& e) {
     THROW_ERROR("minimize", e.what());
   }
 }
References f().
ng()
casadi_int casadi::Opti::ng () const
Extra doc: https://github.com/casadi/casadi/wiki/L_26a
Definition at line 326 of file optistack.cpp.
{
   try {
     return (*this)->ng();
   } catch(std::exception& e) {
     THROW_ERROR("ng", e.what());
   }
 }
Referenced by disp().
np()
casadi_int casadi::Opti::np () const
Extra doc: https://github.com/casadi/casadi/wiki/L_269
Definition at line 318 of file optistack.cpp.
{
   try {
     return (*this)->np();
   } catch(std::exception& e) {
     THROW_ERROR("nx", e.what());
   }
 }
Referenced by disp().
nx()
casadi_int casadi::Opti::nx () const
Extra doc: https://github.com/casadi/casadi/wiki/L_268
Definition at line 310 of file optistack.cpp.
{
   try {
     return (*this)->nx();
   } catch(std::exception& e) {
     THROW_ERROR("nx", e.what());
   }
 }
Referenced by disp().
operator->() [1/2]
OptiNode * casadi::Opti::operator-> ()
Extra doc: https://github.com/casadi/casadi/wiki/L_1r
Definition at line 38 of file optistack.cpp.
{
   return static_cast<OptiNode*>(SharedObject::operator->());
 }
References casadi::GenericShared< SharedObject, SharedObjectInternal >::operator->().
operator->() [2/2]
const OptiNode * casadi::Opti::operator-> () const
Extra doc: https://github.com/casadi/casadi/wiki/L_1s
Definition at line 42 of file optistack.cpp.
{
   return static_cast<const OptiNode*>(SharedObject::operator->());
 }
References casadi::GenericShared< SharedObject, SharedObjectInternal >::operator->().
own()
void casadi::GenericShared< SharedObject , SharedObjectInternal >::own (Internal * node) inherited
Assign the node to a node class pointer (or null)
Definition at line 90 of file generic_shared_impl.hpp.
{
     count_down();
     node = node_;
     count_up();
   }
p()
MX casadi::Opti::p () const
Extra doc: https://github.com/casadi/casadi/wiki/L_26c
Definition at line 342 of file optistack.cpp.
                  {
   try {
     return (*this)->p();
   } catch(std::exception& e) {
     THROW_ERROR("p", e.what());
   }
 }
parameter() [1/3]
MX casadi::Opti::parameter (casadi_int n = 1, casadi_int m = 1, const std::string & attribute = "full")
The order of creation does not matter. It is not required for parameter to actualy appear in the optimization problem. Parameters that do appear, must be given a value before the problem can be solved.
Parameters
[in] n number of rows (default 1)
[in] m number of columnss (default 1)
[in] attribute 'full' (default) or 'symmetric'
Extra doc: https://github.com/casadi/casadi/wiki/L_19
Definition at line 90 of file optistack.cpp.
{
   try {
     return (*this)->parameter(n, m, attribute);
   } catch(std::exception& e) {
     THROW_ERROR("parameter", e.what());
   }
 }
parameter() [2/3]
MX casadi::Opti::parameter (const MX & symbol, const std::string & attribute = "full")
Definition at line 106 of file optistack.cpp.
{
   try {
     return (*this)->parameter(symbol, attribute);
   } catch(std::exception& e) {
     THROW_ERROR("parameter", e.what());
   }
 }
parameter() [3/3]
MX casadi::Opti::parameter (const Sparsity & sp, const std::string & attribute = "full")
Definition at line 98 of file optistack.cpp.
{
   try {
     return (*this)->parameter(sp, attribute);
   } catch(std::exception& e) {
     THROW_ERROR("parameter", e.what());
   }
 }
print_ptr()
void casadi::SharedObject::print_ptr (std::ostream & stream = casadi::uout()) const inherited
Print the pointer to the internal class
Definition at line 43 of file shared_object.cpp.
{
     stream << get();
   }
References casadi::GenericShared< SharedObject, SharedObjectInternal >::get().
return_status()
std::string casadi::Opti::return_status () const
   passed as-is from nlpsol
No stability can be guaranteed about this part of the API
Extra doc: https://github.com/casadi/casadi/wiki/L_1g
Definition at line 270 of file optistack.cpp.
{
   try {
     return (*this)->return_status();
   } catch(std::exception& e) {
     THROW_ERROR("return_status", e.what());
   }
 }
Referenced by disp().
scale_helper()
Function casadi::Opti::scale_helper (const Function & h) const
Extra doc: https://github.com/casadi/casadi/wiki/L_2ci
Definition at line 254 of file optistack.cpp.
{
   try {
     return (*this)->scale_helper(h);
   } catch(std::exception& e) {
     THROW_ERROR("scale_helper", e.what());
   }
 }
Referenced by casadi::OptiNode::scale_helper().
set_domain()
void casadi::Opti::set_domain (const MX & x, const std::string & domain)
Parameters
[in] x decision variable
[in] type 'real', 'integer' (default: real)
* opti.set_domain(x, "real")
* opti.set_domain(x, "integer")
*
Extra doc: https://github.com/casadi/casadi/wiki/L_27t
Definition at line 189 of file optistack.cpp.
{
   try {
     (*this)->set_domain(x, domain);
   } catch(std::exception& e) {
     THROW_ERROR("set_domain", e.what());
   }
 }
References x().
set_initial() [1/2]
void casadi::Opti::set_initial (const MX & x, const DM & v)
Set initial guess for decision variables
* opti.set_initial(x, 2)
* opti.set_initial(10*x(1), 2)
*
Definition at line 165 of file optistack.cpp.
{
   try {
     (*this)->set_initial(x, v);
   } catch(std::exception& e) {
     THROW_ERROR("set_initial", e.what());
   }
 }
References x().
set_initial() [2/2]
void casadi::Opti::set_initial (const std::vector< MX > & assignments)
Set initial guess for decision variables
* opti.set_initial(x, 2)
* opti.set_initial(10*x(1), 2)
*
Definition at line 172 of file optistack.cpp.
{
   try {
     (*this)->set_initial(assignments);
   } catch(std::exception& e) {
     THROW_ERROR("set_initial", e.what());
   }
 }
set_linear_scale()
void casadi::Opti::set_linear_scale (const MX & x, const DM & scale, const DM & offset = 0)
(x-offset)/scale will be used in the optimization problem
Parameters
[in] x decision variable
[in] scale scaling value (default: 1)
[in] offset scaling value (default: 0)
* opti.set_linear_scale(x, 20)
* opti.set_linear_scale(x, 20, 273.15)
*
Extra doc: https://github.com/casadi/casadi/wiki/L_2bs
Definition at line 197 of file optistack.cpp.
{
   try {
     (*this)->set_linear_scale(x, scale, offset);
   } catch(std::exception& e) {
     THROW_ERROR("set_linear_scale", e.what());
   }
 }
References x().
set_value() [1/2]
void casadi::Opti::set_value (const MX & x, const DM & v)
Each parameter must be given a value before 'solve' can be called
Extra doc: https://github.com/casadi/casadi/wiki/L_1d
Definition at line 181 of file optistack.cpp.
{
   try {
     (*this)->set_value(x, v);
   } catch(std::exception& e) {
     THROW_ERROR("set_value", e.what());
   }
 }
References x().
set_value() [2/2]
void casadi::Opti::set_value (const std::vector< MX > & assignments)
Each parameter must be given a value before 'solve' can be called
Extra doc: https://github.com/casadi/casadi/wiki/L_1d
Definition at line 205 of file optistack.cpp.
{
   try {
     (*this)->set_value(assignments);
   } catch(std::exception& e) {
     THROW_ERROR("set_value", e.what());
   }
 }
solve()
OptiSol casadi::Opti::solve ()
Definition at line 213 of file optistack.cpp.
                     {
   try {
     return (*this)->solve(false);
   } catch(std::exception& e) {
     THROW_ERROR("solve", e.what());
   }
 }
solve_limited()
OptiSol casadi::Opti::solve_limited ()
Allows the solver to return without error when an iteration or time limit is reached
Extra doc: https://github.com/casadi/casadi/wiki/L_1e
Definition at line 221 of file optistack.cpp.
{
   try {
     return (*this)->solve(true);
   } catch(std::exception& e) {
     THROW_ERROR("solve", e.what());
   }
 }
solver()
void casadi::Opti::solver (const std::string & solver, const Dict & plugin_options = Dict(), const Dict & solver_options = Dict())
Parameters
[in] solver any of the nlpsol plugins can be used here In practice, not all nlpsol plugins may be supported yet
[in] options passed on to nlpsol plugin No stability can be guaranteed about this part of the API
[in] options to be passed to nlpsol solver No stability can be guaranteed about this part of the API
Extra doc: https://github.com/casadi/casadi/wiki/L_1c
Definition at line 155 of file optistack.cpp.
{
   try {
     (*this)->solver(solver, plugin_options, solver_options);
   } catch(std::exception& e) {
     THROW_ERROR("solver", e.what());
   }
 }
stats()
Dict casadi::Opti::stats () const
nlpsol stats are passed as-is. No stability can be guaranteed about this part of the API
Extra doc: https://github.com/casadi/casadi/wiki/L_1f
Definition at line 262 of file optistack.cpp.
{
   try {
     return (*this)->stats();
   } catch(std::exception& e) {
     THROW_ERROR("stats", e.what());
   }
 }
Referenced by casadi::OptiSol::stats().
subject_to() [1/5]
void casadi::Opti::subject_to ()
Definition at line 146 of file optistack.cpp.
                       {
   try {
     (*this)->subject_to();
   } catch(std::exception& e) {
     THROW_ERROR("subject_to", e.what());
   }
 }
Referenced by subject_to().
subject_to() [2/5]
void casadi::Opti::subject_to (const MX & g, const Dict & options = Dict())
Examples:
* \begin{itemize}
* opti.subject_to(sqrt(x+y) >= 1);
* opti.subject_to(sqrt(x+y) > 1)}: same as above
* opti.subject_to(1<= sqrt(x+y))}: same as above
* opti.subject_to(5*x+y==1)}: equality
*
* Python
* opti.subject_to([x*y>=1,x==3])
* opti.subject_to(opti.bounded(0,x,1))
*
* MATLAB
* opti.subject_to({x*y>=1,x==3})
* opti.subject_to(0<=x<=1)
*
Related functionalities:
opti.lbg,opti.g,opti.ubg represent the vector of flattened constraints
opti.debug.show_infeasibilities() may be used to inspect which constraints are violated
Extra doc: https://github.com/casadi/casadi/wiki/L_1b
Definition at line 122 of file optistack.cpp.
{
   try {
     (*this)->subject_to(g, 1, options);
   } catch(std::exception& e) {
     THROW_ERROR("subject_to", e.what());
   }
 }
References g().
subject_to() [3/5]
void casadi::Opti::subject_to (const MX & g, const DM & linear_scale, const Dict & options = Dict())
Examples:
* \begin{itemize}
* opti.subject_to(sqrt(x+y) >= 1);
* opti.subject_to(sqrt(x+y) > 1)}: same as above
* opti.subject_to(1<= sqrt(x+y))}: same as above
* opti.subject_to(5*x+y==1)}: equality
*
* Python
* opti.subject_to([x*y>=1,x==3])
* opti.subject_to(opti.bounded(0,x,1))
*
* MATLAB
* opti.subject_to({x*y>=1,x==3})
* opti.subject_to(0<=x<=1)
*
Related functionalities:
opti.lbg,opti.g,opti.ubg represent the vector of flattened constraints
opti.debug.show_infeasibilities() may be used to inspect which constraints are violated
Extra doc: https://github.com/casadi/casadi/wiki/L_1b
Definition at line 134 of file optistack.cpp.
{
   try {
     (*this)->subject_to(g, linear_scale, options);
   } catch(std::exception& e) {
     THROW_ERROR("subject_to", e.what());
   }
 }
References g().
subject_to() [4/5]
void casadi::Opti::subject_to (const std::vector< MX > & g, const Dict & options = Dict())
Examples:
* \begin{itemize}
* opti.subject_to(sqrt(x+y) >= 1);
* opti.subject_to(sqrt(x+y) > 1)}: same as above
* opti.subject_to(1<= sqrt(x+y))}: same as above
* opti.subject_to(5*x+y==1)}: equality
*
* Python
* opti.subject_to([x*y>=1,x==3])
* opti.subject_to(opti.bounded(0,x,1))
*
* MATLAB
* opti.subject_to({x*y>=1,x==3})
* opti.subject_to(0<=x<=1)
*
Related functionalities:
opti.lbg,opti.g,opti.ubg represent the vector of flattened constraints
opti.debug.show_infeasibilities() may be used to inspect which constraints are violated
Extra doc: https://github.com/casadi/casadi/wiki/L_1b
Definition at line 130 of file optistack.cpp.
{
   for (const auto& gs : g) subject_to(gs, 1, options);
 }
References g(), and subject_to().
subject_to() [5/5]
void casadi::Opti::subject_to (const std::vector< MX > & g, const DM & linear_scale, const Dict & options = Dict())
Examples:
* \begin{itemize}
* opti.subject_to(sqrt(x+y) >= 1);
* opti.subject_to(sqrt(x+y) > 1)}: same as above
* opti.subject_to(1<= sqrt(x+y))}: same as above
* opti.subject_to(5*x+y==1)}: equality
*
* Python
* opti.subject_to([x*y>=1,x==3])
* opti.subject_to(opti.bounded(0,x,1))
*
* MATLAB
* opti.subject_to({x*y>=1,x==3})
* opti.subject_to(0<=x<=1)
*
Related functionalities:
opti.lbg,opti.g,opti.ubg represent the vector of flattened constraints
opti.debug.show_infeasibilities() may be used to inspect which constraints are violated
Extra doc: https://github.com/casadi/casadi/wiki/L_1b
Definition at line 142 of file optistack.cpp.
{
   for (const auto& gs : g) subject_to(gs, linear_scale, options);
 }
References g(), and subject_to().
swap()
void casadi::GenericShared< SharedObject , SharedObjectInternal >::swap (GenericShared< SharedObject, SharedObjectInternal > & other) inherited
Definition at line 106 of file generic_shared_impl.hpp.
{
     GenericShared<Shared, Internal> temp = *this;
     *this = other;
     other = temp;
   }
to_function() [1/3]
Function casadi::Opti::to_function (const std::string & name, const std::map< std::string, MX > & dict, const std::vector< std::string > & name_in, const std::vector< std::string > & name_out, const Dict & opts = Dict())
Parameters
[in] name Name of the resulting CasADi Function
[in] args List of parameters and decision/dual variables (which can be given an initial guess) with the resulting Function
[in] res List of expressions that will get evaluated at the optimal solution
[in] opts Standard CasADi Funcion options
Extra doc: https://github.com/casadi/casadi/wiki/L_1j
Definition at line 441 of file optistack.cpp.
                       {
   std::vector<MX> ex_in(name_in.size()), ex_out(name_out.size());
   for (auto&& i : dict) {
     std::vector<std::string>::const_iterator it;
     if ((it=find(name_in.begin(), name_in.end(), i.first))!=name_in.end()) {
       // Input expression
       ex_in[it-name_in.begin()] = i.second;
     } else if ((it=find(name_out.begin(), name_out.end(), i.first))!=name_out.end()) {
       // Output expression
       ex_out[it-name_out.begin()] = i.second;
     } else {
       // Neither
       casadi_error("Unknown dictionary entry: '" + i.first + "'");
     }
   }
   return to_function(name, ex_in, ex_out, name_in, name_out, opts);
 }
References casadi::find(), and to_function().
to_function() [2/3]
Function casadi::Opti::to_function (const std::string & name, const std::vector< MX > & args, const std::vector< MX > & res, const Dict & opts = Dict())
Parameters
[in] name Name of the resulting CasADi Function
[in] args List of parameters and decision/dual variables (which can be given an initial guess) with the resulting Function
[in] res List of expressions that will get evaluated at the optimal solution
[in] opts Standard CasADi Funcion options
Extra doc: https://github.com/casadi/casadi/wiki/L_1j
Definition at line 435 of file optistack.cpp.
                       {
   return to_function(name, args, res, {}, {}, opts);
 }
Referenced by to_function(), and casadi::OptiNode::to_function().
to_function() [3/3]
Function casadi::Opti::to_function (const std::string & name, const std::vector< MX > & args, const std::vector< MX > & res, const std::vector< std::string > & name_in, const std::vector< std::string > & name_out, const Dict & opts = Dict())
Parameters
[in] name Name of the resulting CasADi Function
[in] args List of parameters and decision/dual variables (which can be given an initial guess) with the resulting Function
[in] res List of expressions that will get evaluated at the optimal solution
[in] opts Standard CasADi Funcion options
Extra doc: https://github.com/casadi/casadi/wiki/L_1j
Definition at line 423 of file optistack.cpp.
                       {
   try {
     return (*this)->to_function(name, args, res, name_in, name_out, opts);
   } catch(std::exception& e) {
     THROW_ERROR("to_function", e.what());
   }
 }
type_name()
std::string casadi::Opti::type_name () const inline
Definition at line 440 of file optistack.hpp.
 { return "Opti"; }
ubg()
MX casadi::Opti::ubg () const
Definition at line 374 of file optistack.cpp.
                    {
   try {
     return (*this)->ubg();
   } catch(std::exception& e) {
     THROW_ERROR("ubg", e.what());
   }
 }
update_user_dict() [1/2]
void casadi::Opti::update_user_dict (const MX & m, const Dict & meta)
Add arbitrary data in the form of a dictionary to symbols or constraints
Extra doc: https://github.com/casadi/casadi/wiki/L_1o
Definition at line 479 of file optistack.cpp.
{
   try {
     (*this)->update_user_dict(m, meta);
   } catch(std::exception& e) {
     THROW_ERROR("update_user_dict", e.what());
   }
 }
Referenced by update_user_dict().
update_user_dict() [2/2]
void casadi::Opti::update_user_dict (const std::vector< MX > & m, const Dict & meta)
Definition at line 487 of file optistack.cpp.
{
   for (const auto& m : ms)
      update_user_dict(m, meta);
 }
References update_user_dict().
user_dict()
Dict casadi::Opti::user_dict (const MX & m) const
Definition at line 492 of file optistack.cpp.
{
   try {
     return (*this)->user_dict(m);
   } catch(std::exception& e) {
     THROW_ERROR("user_dict", e.what());
   }
 }
value() [1/3]
DM casadi::Opti::value (const DM & x, const std::vector< MX > & values = std::vector<MX>()) const
Parameters
[in] x decision variable
[in] type 'real', 'integer' (default: real)
* opti.set_domain(x, "real")
* opti.set_domain(x, "integer")
*
Extra doc: https://github.com/casadi/casadi/wiki/L_27t
Definition at line 238 of file optistack.cpp.
{
   try {
     return (*this)->value(x, values);
   } catch(std::exception& e) {
     THROW_ERROR("value", e.what());
   }
 }
References x().
value() [2/3]
DM casadi::Opti::value (const MX & x, const std::vector< MX > & values = std::vector<MX>()) const
Obtain value of expression at the current value
In regular mode, teh current value is the converged solution In debug mode, the value can be non-converged
Parameters
[in] values Optional assignment expressions (e.g. x==3) to overrule the current value
Definition at line 229 of file optistack.cpp.
{
   try {
     return (*this)->value(x, values);
   } catch(std::exception& e) {
     THROW_ERROR("value", e.what());
   }
 }
References x().
Referenced by casadi::OptiSol::value().
value() [3/3]
DM casadi::Opti::value (const SX & x, const std::vector< MX > & values = std::vector<MX>()) const
Parameters
[in] x decision variable
[in] type 'real', 'integer' (default: real)
* opti.set_domain(x, "real")
* opti.set_domain(x, "integer")
*
Extra doc: https://github.com/casadi/casadi/wiki/L_27t
Definition at line 246 of file optistack.cpp.
{
   try {
     return (*this)->value(x, values);
   } catch(std::exception& e) {
     THROW_ERROR("value", e.what());
   }
 }
References x().
value_parameters()
std::vector< MX > casadi::Opti::value_parameters () const
Definition at line 294 of file optistack.cpp.
{
   try {
     return (*this)->value_parameters();
   } catch(std::exception& e) {
     THROW_ERROR("value_parameters", e.what());
   }
 }
Referenced by casadi::OptiSol::value_parameters().
value_variables()
std::vector< MX > casadi::Opti::value_variables () const
Extra doc: https://github.com/casadi/casadi/wiki/L_267
Definition at line 286 of file optistack.cpp.
{
   try {
     return (*this)->value_variables();
   } catch(std::exception& e) {
     THROW_ERROR("value_variables", e.what());
   }
 }
Referenced by casadi::OptiSol::value_variables().
variable() [1/3]
MX casadi::Opti::variable (casadi_int n = 1, casadi_int m = 1, const std::string & attribute = "full")
The order of creation matters. The order will be reflected in the optimization problem. It is not required for decision variables to actualy appear in the optimization problem.
Parameters
[in] n number of rows (default 1)
[in] m number of columnss (default 1)
[in] attribute 'full' (default) or 'symmetric'
Extra doc: https://github.com/casadi/casadi/wiki/L_18
Definition at line 51 of file optistack.cpp.
{
   try {
     return (*this)->variable(n, m, attribute);
   } catch(std::exception& e) {
     THROW_ERROR("variable", e.what());
   }
 }
variable() [2/3]
MX casadi::Opti::variable (const MX & symbol, const std::string & attribute = "full")
Definition at line 67 of file optistack.cpp.
{
   try {
     return (*this)->variable(symbol, attribute);
   } catch(std::exception& e) {
     THROW_ERROR("variable", e.what());
   }
 }
variable() [3/3]
MX casadi::Opti::variable (const Sparsity & sp, const std::string & attribute = "full")
Definition at line 59 of file optistack.cpp.
{
   try {
     return (*this)->variable(sp, attribute);
   } catch(std::exception& e) {
     THROW_ERROR("variable", e.what());
   }
 }
weak()
GenericWeakRef< SharedObject , SharedObjectInternal > * casadi::GenericShared< SharedObject , SharedObjectInternal >::weak inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_aw
Definition at line 131 of file generic_shared_impl.hpp.
{
     return (*this)->weak();
   }
x()
MX casadi::Opti::x () const
Extra doc: https://github.com/casadi/casadi/wiki/L_26b
Definition at line 334 of file optistack.cpp.
                  {
   try {
     return (*this)->x();
   } catch(std::exception& e) {
     THROW_ERROR("x", e.what());
   }
 }
Referenced by casadi::OptiAdvanced::describe(), set_domain(), set_initial(), set_linear_scale(), set_value(), and value().
x_linear_scale()
DM casadi::Opti::x_linear_scale () const
Definition at line 391 of file optistack.cpp.
{
   try {
     return (*this)->x_linear_scale();
   } catch(std::exception& e) {
     THROW_ERROR("x_linear_scale", e.what());
   }
 }
x_linear_scale_offset()
DM casadi::Opti::x_linear_scale_offset () const
Definition at line 399 of file optistack.cpp.
{
   try {
     return (*this)->x_linear_scale_offset();
   } catch(std::exception& e) {
     THROW_ERROR("x_linear_scale_offset", e.what());
   }
 }
Friends And Related Function Documentation
InternalOptiCallback
friend class InternalOptiCallback friend
Definition at line 91 of file optistack.hpp.
The documentation for this class was generated from the following files:
optistack.hpp
optistack.cpp