CasADi: casadi::AlpaqaProblem Class Reference
casadi::AlpaqaProblem Class Reference
#include <alpaqa_problem.hpp>
Detailed Description
Definition at line 14 of file alpaqa_problem.hpp.
Public Member Functions
AlpaqaProblem (const AlpaqaInterface &solver, AlpaqaMemory *mem)
~AlpaqaProblem ()
real_t eval_f (crvec x) const
void eval_grad_f (crvec x, rvec grad_fx) const
real_t eval_f_grad_f (crvec x, rvec grad_fx) const
void eval_g (crvec x, rvec g) const
void eval_grad_g_prod (crvec x, crvec y, rvec grad_gxy) const
void eval_grad_ψ (crvec x, crvec y, crvec Σ, rvec grad_ψ, rvec work_n, rvec work_m) const
real_t eval_ψ_grad_ψ (crvec x, crvec y, crvec Σ, rvec grad_ψ, rvec work_n, rvec work_m) const
void eval_grad_L (crvec x, crvec y, rvec grad_L, rvec work_n) const
real_t eval_ψ (crvec x, crvec y, crvec Σ, rvec ŷ) const
void eval_grad_gi (crvec x, index_t i, rvec grad_i) const
length_t get_jac_g_num_nonzeros () const
void eval_jac_g (crvec x, rindexvec inner_idx, rindexvec outer_ptr, rvec J_values) const
void eval_hess_L_prod (crvec x, crvec y, real_t scale, crvec v, rvec Hv) const
length_t get_hess_L_num_nonzeros () const
void eval_hess_L (crvec x, crvec y, real_t scale, rindexvec inner_idx, rindexvec outer_ptr, rvec H_values) const
void eval_hess_ψ_prod (crvec x, crvec y, crvec Σ, real_t scale, crvec v, rvec Hv) const
length_t get_hess_ψ_num_nonzeros () const
void eval_hess_ψ (crvec x, crvec y, crvec Σ, real_t scale, rindexvec inner_idx, rindexvec outer_ptr, rvec H_values) const
bool provides_eval_grad_gi () const
bool provides_eval_jac_g () const
bool provides_eval_hess_L_prod () const
bool provides_eval_hess_L () const
bool provides_eval_hess_ψ_prod () const
bool provides_eval_hess_ψ () const
Constructor & Destructor Documentation
AlpaqaProblem()
casadi::AlpaqaProblem::AlpaqaProblem (const AlpaqaInterface & solver, AlpaqaMemory * mem)
Definition at line 7 of file alpaqa_problem.cpp.
   : alpaqa::BoxConstrProblem<alpaqa::DefaultConfig>{solver.nx_, solver.ng_},
     solver_(solver), mem_(mem) {
 }
References casadi::Nlpsol::ng_, and casadi::Nlpsol::nx_.
~AlpaqaProblem()
casadi::AlpaqaProblem::~AlpaqaProblem () default
Member Function Documentation
eval_f()
double casadi::AlpaqaProblem::eval_f (crvec x) const
Definition at line 19 of file alpaqa_problem.cpp.
{
   double obj_value;
   mem_->arg[0] = x.data();
   mem_->arg[1] = mem_->d_nlp.p;
   mem_->res[0] = &obj_value;
   try {
     casadi_assert(solver_.calc_function(mem_, "nlp_f")==0, "Failing evaluating eval_f");
   } catch(KeyboardInterruptException& ex) {
     casadi_warning("KeyboardInterruptException");
     throw KeyboardInterruptException();
   } catch (std::exception& ex) {
     if (solver_.show_eval_warnings_) {
       casadi_warning("AlpaqaProblem::eval_f failed:" + std::string(ex.what()));
     }
   }
   return obj_value;
 }
References casadi::OracleMemory::arg, casadi::OracleFunction::calc_function(), casadi::NlpsolMemory::d_nlp, casadi_nlpsol_data< T1 >::p, casadi::OracleMemory::res, casadi::OracleFunction::show_eval_warnings_, and casadi::CasadiException::what().
Referenced by casadi::AlpaqaInterface::solve().
eval_f_grad_f()
double casadi::AlpaqaProblem::eval_f_grad_f (crvec x, rvec grad_fx) const
Definition at line 42 of file alpaqa_problem.cpp.
{
   double obj_value;
   mem_->arg[0] = x.data();
   mem_->arg[1] = mem_->d_nlp.p;
   mem_->res[0] = &obj_value;
   mem_->res[1] = grad_fx.data();
   try {
     casadi_assert(solver_.calc_function(mem_, "nlp_f_grad_f")==0, "Failing evaluating eval_f_grad_f");
   } catch(KeyboardInterruptException& ex) {
     casadi_warning("KeyboardInterruptException");
     throw KeyboardInterruptException();
   } catch (std::exception& ex) {
     if (solver_.show_eval_warnings_) {
       casadi_warning("AlpaqaProblem::eval_f_grad_f failed:" + std::string(ex.what()));
     }
   }
   return obj_value;
 }
References casadi::OracleMemory::arg, casadi::OracleFunction::calc_function(), casadi::NlpsolMemory::d_nlp, casadi_nlpsol_data< T1 >::p, casadi::OracleMemory::res, casadi::OracleFunction::show_eval_warnings_, and casadi::CasadiException::what().
Referenced by eval_grad_f().
eval_g()
void casadi::AlpaqaProblem::eval_g (crvec x, rvec g) const
Definition at line 74 of file alpaqa_problem.cpp.
{
     mem_->arg[0] = x.data();
     mem_->arg[1] = mem_->d_nlp.p;
     mem_->res[0] = g.data();
     try {
       casadi_assert(solver_.calc_function(mem_, "nlp_g")==0, "Failing evaluating eval_f_grad_f");
     } catch(KeyboardInterruptException& ex) {
       casadi_warning("KeyboardInterruptException");
       throw KeyboardInterruptException();
     } catch (std::exception& ex) {
       if (solver_.show_eval_warnings_) {
         casadi_warning("AlpaqaProblem::eval_g failed:" + std::string(ex.what()));
       }
     }
 }
References casadi::OracleMemory::arg, casadi::OracleFunction::calc_function(), casadi::NlpsolMemory::d_nlp, casadi_nlpsol_data< T1 >::p, casadi::OracleMemory::res, casadi::OracleFunction::show_eval_warnings_, and casadi::CasadiException::what().
Referenced by casadi::AlpaqaInterface::solve().
eval_grad_f()
void casadi::AlpaqaProblem::eval_grad_f (crvec x, rvec grad_fx) const
Definition at line 38 of file alpaqa_problem.cpp.
{
   eval_f_grad_f(x, grad_fx);
 }
References eval_f_grad_f().
eval_grad_g_prod()
void casadi::AlpaqaProblem::eval_grad_g_prod (crvec x, crvec y, rvec grad_gxy) const
Definition at line 163 of file alpaqa_problem.cpp.
{
   casadi_error("Not implemented");
 }
eval_grad_gi()
void casadi::AlpaqaProblem::eval_grad_gi (crvec x, index_t i, rvec grad_i) const
Definition at line 167 of file alpaqa_problem.cpp.
{
   casadi_error("Not implemented");
 }
eval_grad_L()
void casadi::AlpaqaProblem::eval_grad_L (crvec x, crvec y, rvec grad_L, rvec work_n) const
Definition at line 223 of file alpaqa_problem.cpp.
{
   mem_->arg[0] = x.data();
   mem_->arg[1] = mem_->d_nlp.p;
   mem_->arg[2] = y.data();
   mem_->res[0] = grad_L.data();
   try {
     casadi_assert(solver_.calc_function(mem_, "nlp_grad_L")==0, "Failing evaluating eval_f_grad_f");
   } catch(KeyboardInterruptException& ex) {
     casadi_warning("KeyboardInterruptException");
     throw KeyboardInterruptException();
   } catch (std::exception& ex) {
     if (solver_.show_eval_warnings_) {
       casadi_warning("AlpaqaProblem::eval_grad_L failed:" + std::string(ex.what()));
     }
   }
 }
References casadi::OracleMemory::arg, casadi::OracleFunction::calc_function(), casadi::NlpsolMemory::d_nlp, casadi_nlpsol_data< T1 >::p, casadi::OracleMemory::res, casadi::OracleFunction::show_eval_warnings_, and casadi::CasadiException::what().
eval_grad_ψ()
void casadi::AlpaqaProblem::eval_grad_ψ (crvec x, crvec y, crvec Σ, rvec grad_ψ, rvec work_n, rvec work_m) const
Definition at line 218 of file alpaqa_problem.cpp.
{
   eval_ψ_grad_ψ(x, y, Σ, grad_ψ, a, b);
 }
References eval_ψ_grad_ψ().
eval_hess_L()
void casadi::AlpaqaProblem::eval_hess_L (crvec x, crvec y, real_t scale, rindexvec inner_idx, rindexvec outer_ptr, rvec H_values) const
Definition at line 115 of file alpaqa_problem.cpp.
{
   if (H_values.size()>0) {
     mem_->arg[0] = x.data();
     mem_->arg[1] = mem_->d_nlp.p;
     mem_->arg[2] = y.data();
     mem_->arg[3] = &scale;
     mem_->res[0] = H_values.data();
     try {
       casadi_assert(solver_.calc_function(mem_, "nlp_hess_L")==0, "Failing evaluating eval_f_grad_f");
     } catch(KeyboardInterruptException& ex) {
       casadi_warning("KeyboardInterruptException");
       throw KeyboardInterruptException();
     } catch (std::exception& ex) {
       if (solver_.show_eval_warnings_) {
         casadi_warning("AlpaqaProblem::eval_hess_L failed:" + std::string(ex.what()));
       }
     }
   } else {
     const Sparsity& sp = solver_.get_function("nlp_hess_L").sparsity_out(0);
     if (!sp.is_dense()) {
       copy(sp.row(), sp.nnz(), inner_idx.data());
       copy(sp.colind(), get_n()+1, outer_ptr.data());
     }
   }
 }
References casadi::OracleMemory::arg, casadi::OracleFunction::calc_function(), casadi::Sparsity::colind(), casadi::copy(), casadi::NlpsolMemory::d_nlp, casadi::OracleFunction::get_function(), casadi::Sparsity::is_dense(), casadi::Sparsity::nnz(), casadi_nlpsol_data< T1 >::p, casadi::OracleMemory::res, casadi::Sparsity::row(), casadi::OracleFunction::show_eval_warnings_, and casadi::CasadiException::what().
eval_hess_L_prod()
void casadi::AlpaqaProblem::eval_hess_L_prod (crvec x, crvec y, real_t scale, crvec v, rvec Hv) const
Definition at line 143 of file alpaqa_problem.cpp.
{
   mem_->arg[0] = x.data();
   mem_->arg[1] = mem_->d_nlp.p;
   mem_->arg[2] = y.data();
   mem_->arg[3] = &scale;
   mem_->arg[4] = v.data();
   mem_->res[0] = Hv.data();
   try {
     casadi_assert(solver_.calc_function(mem_, "nlp_hess_L_prod")==0, "Failing evaluating eval_f_grad_f");
   } catch(KeyboardInterruptException& ex) {
     casadi_warning("KeyboardInterruptException");
     throw KeyboardInterruptException();
   } catch (std::exception& ex) {
     if (solver_.show_eval_warnings_) {
       casadi_warning("AlpaqaProblem::eval_hess_L_prod failed:" + std::string(ex.what()));
     }
   }
 }
References casadi::OracleMemory::arg, casadi::OracleFunction::calc_function(), casadi::NlpsolMemory::d_nlp, casadi_nlpsol_data< T1 >::p, casadi::OracleMemory::res, casadi::OracleFunction::show_eval_warnings_, and casadi::CasadiException::what().
eval_hess_ψ()
void casadi::AlpaqaProblem::eval_hess_ψ (crvec x, crvec y, crvec Σ, real_t scale, rindexvec inner_idx, rindexvec outer_ptr, rvec H_values) const
Definition at line 241 of file alpaqa_problem.cpp.
{
     if (H_values.size()>0) {
       mem_->arg[0] = x.data();
       mem_->arg[1] = mem_->d_nlp.p;
       mem_->arg[2] = y.data();
       mem_->arg[3] = Σ.data();
       mem_->arg[4] = &scale;
       mem_->arg[5] = this->D.lowerbound.data();
       mem_->arg[6] = this->D.upperbound.data();
       mem_->res[0] = H_values.data();
       try {
         casadi_assert(solver_.calc_function(mem_, "nlp_hess_psi")==0, "Failing evaluating eval_f_grad_f");
       } catch(KeyboardInterruptException& ex) {
         casadi_warning("KeyboardInterruptException");
         throw KeyboardInterruptException();
       } catch (std::exception& ex) {
         if (solver_.show_eval_warnings_) {
           casadi_warning("AlpaqaProblem::eval_hess_psi failed:" + std::string(ex.what()));
         }
       }
     } else {
       const Sparsity& sp = solver_.get_function("nlp_hess_psi").sparsity_out(0);
       if (!sp.is_dense()) {
         copy(sp.row(), sp.nnz(), inner_idx.data());
         copy(sp.colind(), get_n()+1, outer_ptr.data());
       }
     }
 }
References casadi::OracleMemory::arg, casadi::OracleFunction::calc_function(), casadi::Sparsity::colind(), casadi::copy(), casadi::D, casadi::NlpsolMemory::d_nlp, casadi::OracleFunction::get_function(), casadi::Sparsity::is_dense(), casadi::Sparsity::nnz(), casadi_nlpsol_data< T1 >::p, casadi::OracleMemory::res, casadi::Sparsity::row(), casadi::OracleFunction::show_eval_warnings_, and casadi::CasadiException::what().
eval_hess_ψ_prod()
void casadi::AlpaqaProblem::eval_hess_ψ_prod (crvec x, crvec y, crvec Σ, real_t scale, crvec v, rvec Hv) const
Definition at line 272 of file alpaqa_problem.cpp.
{
   mem_->arg[0] = x.data();
   mem_->arg[1] = mem_->d_nlp.p;
   mem_->arg[2] = y.data();
   mem_->arg[3] = Σ.data();
   mem_->arg[4] = &scale;
   mem_->arg[5] = this->D.lowerbound.data();
   mem_->arg[6] = this->D.upperbound.data();
   mem_->arg[7] = v.data();
   mem_->res[0] = Hv.data();
   try {
     casadi_assert(solver_.calc_function(mem_, "nlp_hess_psi_prod")==0, "Failing evaluating eval_f_grad_f");
   } catch(KeyboardInterruptException& ex) {
     casadi_warning("KeyboardInterruptException");
     throw KeyboardInterruptException();
   } catch (std::exception& ex) {
     if (solver_.show_eval_warnings_) {
       casadi_warning("AlpaqaProblem::eval_hess_psi_prod failed:" + std::string(ex.what()));
     }
   }
 }
References casadi::OracleMemory::arg, casadi::OracleFunction::calc_function(), casadi::D, casadi::NlpsolMemory::d_nlp, casadi_nlpsol_data< T1 >::p, casadi::OracleMemory::res, casadi::OracleFunction::show_eval_warnings_, and casadi::CasadiException::what().
eval_jac_g()
void casadi::AlpaqaProblem::eval_jac_g (crvec x, rindexvec inner_idx, rindexvec outer_ptr, rvec J_values) const
Definition at line 90 of file alpaqa_problem.cpp.
{
   if (J_values.size()>0) {
     mem_->arg[0] = x.data();
     mem_->arg[1] = mem_->d_nlp.p;
     mem_->res[0] = J_values.data();
     try {
       casadi_assert(solver_.calc_function(mem_, "nlp_jac_g")==0, "Failing evaluating eval_f_grad_f");
     } catch(KeyboardInterruptException& ex) {
       casadi_warning("KeyboardInterruptException");
       throw KeyboardInterruptException();
     } catch (std::exception& ex) {
       if (solver_.show_eval_warnings_) {
         casadi_warning("AlpaqaProblem::eval_jac_g failed:" + std::string(ex.what()));
       }
     }
   } else {
     const Sparsity& sp = solver_.jacg_sp_;
     if (!sp.is_dense()) {
       copy(sp.row(), sp.nnz(), inner_idx.data());
       copy(sp.colind(), get_n()+1, outer_ptr.data());
     }
   }
 }
References casadi::OracleMemory::arg, casadi::OracleFunction::calc_function(), casadi::Sparsity::colind(), casadi::copy(), casadi::NlpsolMemory::d_nlp, casadi::Sparsity::is_dense(), casadi::AlpaqaInterface::jacg_sp_, casadi::Sparsity::nnz(), casadi_nlpsol_data< T1 >::p, casadi::OracleMemory::res, casadi::Sparsity::row(), casadi::OracleFunction::show_eval_warnings_, and casadi::CasadiException::what().
eval_ψ()
double casadi::AlpaqaProblem::eval_ψ (crvec x, crvec y, crvec Σ, rvec ŷ) const
Definition at line 171 of file alpaqa_problem.cpp.
{
   double res;
   mem_->arg[0] = x.data();
   mem_->arg[1] = mem_->d_nlp.p;
   mem_->arg[2] = y.data();
   mem_->arg[3] = Σ.data();
   mem_->arg[4] = this->D.lowerbound.data();
   mem_->arg[5] = this->D.upperbound.data();
   mem_->res[0] = &res;
   mem_->res[1] = ŷ.data();
   try {
     casadi_assert(solver_.calc_function(mem_, "nlp_psi")==0, "Failing evaluating eval_f_grad_f");
   } catch(KeyboardInterruptException& ex) {
     casadi_warning("KeyboardInterruptException");
     throw KeyboardInterruptException();
   } catch (std::exception& ex) {
     if (solver_.show_eval_warnings_) {
       casadi_warning("AlpaqaProblem::eval_psi failed:" + std::string(ex.what()));
     }
   }
   return res;
 }
References casadi::OracleMemory::arg, casadi::OracleFunction::calc_function(), casadi::D, casadi::NlpsolMemory::d_nlp, casadi_nlpsol_data< T1 >::p, casadi::OracleMemory::res, casadi::OracleFunction::show_eval_warnings_, and casadi::CasadiException::what().
eval_ψ_grad_ψ()
double casadi::AlpaqaProblem::eval_ψ_grad_ψ (crvec x, crvec y, crvec Σ, rvec grad_ψ, rvec work_n, rvec work_m) const
Definition at line 194 of file alpaqa_problem.cpp.
{
   double res;
   mem_->arg[0] = x.data();
   mem_->arg[1] = mem_->d_nlp.p;
   mem_->arg[2] = y.data();
   mem_->arg[3] = Σ.data();
   mem_->arg[4] = this->D.lowerbound.data();
   mem_->arg[5] = this->D.upperbound.data();
   mem_->res[0] = &res;
   mem_->res[1] = grad_ψ.data();
   try {
     casadi_assert(solver_.calc_function(mem_, "nlp_grad_psi")==0, "Failing evaluating eval_f_grad_f");
   } catch(KeyboardInterruptException& ex) {
     casadi_warning("KeyboardInterruptException");
     throw KeyboardInterruptException();
   } catch (std::exception& ex) {
     if (solver_.show_eval_warnings_) {
       casadi_warning("AlpaqaProblem::eval_grad_psi failed:" + std::string(ex.what()));
     }
   }
   return res;
 }
References casadi::OracleMemory::arg, casadi::OracleFunction::calc_function(), casadi::D, casadi::NlpsolMemory::d_nlp, casadi_nlpsol_data< T1 >::p, casadi::OracleMemory::res, casadi::OracleFunction::show_eval_warnings_, and casadi::CasadiException::what().
Referenced by eval_grad_ψ().
get_hess_L_num_nonzeros()
alpaqa::DefaultConfig::length_t casadi::AlpaqaProblem::get_hess_L_num_nonzeros () const
Definition at line 296 of file alpaqa_problem.cpp.
{
     const Sparsity& sp = solver_.get_function("nlp_hess_L").sparsity_out(0);
     return sp.is_dense() ? 0 : sp.nnz();
 }
References casadi::OracleFunction::get_function(), casadi::Sparsity::is_dense(), and casadi::Sparsity::nnz().
get_hess_ψ_num_nonzeros()
alpaqa::DefaultConfig::length_t casadi::AlpaqaProblem::get_hess_ψ_num_nonzeros () const
Definition at line 301 of file alpaqa_problem.cpp.
{
     const Sparsity& sp = solver_.get_function("nlp_hess_psi").sparsity_out(0);
     return sp.is_dense() ? 0 : sp.nnz();
 }
References casadi::OracleFunction::get_function(), casadi::Sparsity::is_dense(), and casadi::Sparsity::nnz().
get_jac_g_num_nonzeros()
alpaqa::DefaultConfig::length_t casadi::AlpaqaProblem::get_jac_g_num_nonzeros () const
Definition at line 307 of file alpaqa_problem.cpp.
{
   const Sparsity& sp = solver_.jacg_sp_;
   return sp.is_dense() ? 0 : sp.nnz();
 }
References casadi::Sparsity::is_dense(), casadi::AlpaqaInterface::jacg_sp_, and casadi::Sparsity::nnz().
provides_eval_grad_gi()
bool casadi::AlpaqaProblem::provides_eval_grad_gi () const inline
See also
TypeErasedProblem::provides_eval_grad_gi
Definition at line 46 of file alpaqa_problem.hpp.
 { return false; }
provides_eval_hess_L()
bool casadi::AlpaqaProblem::provides_eval_hess_L () const inline
See also
TypeErasedProblem::provides_eval_hess_L
Definition at line 52 of file alpaqa_problem.hpp.
 { return true; }
provides_eval_hess_L_prod()
bool casadi::AlpaqaProblem::provides_eval_hess_L_prod () const inline
See also
TypeErasedProblem::provides_eval_hess_L_prod
Definition at line 50 of file alpaqa_problem.hpp.
 { return true; }
provides_eval_hess_ψ()
bool casadi::AlpaqaProblem::provides_eval_hess_ψ () const inline
See also
TypeErasedProblem::provides_eval_hess_ψ
Definition at line 56 of file alpaqa_problem.hpp.
 { return true; }
provides_eval_hess_ψ_prod()
bool casadi::AlpaqaProblem::provides_eval_hess_ψ_prod () const inline
See also
TypeErasedProblem::provides_eval_hess_ψ_prod
Definition at line 54 of file alpaqa_problem.hpp.
 { return true; }
provides_eval_jac_g()
bool casadi::AlpaqaProblem::provides_eval_jac_g () const inline
See also
TypeErasedProblem::provides_eval_jac_g
Definition at line 48 of file alpaqa_problem.hpp.
 { return true; }
The documentation for this class was generated from the following files:
alpaqa_problem.hpp
alpaqa_problem.cpp