CasADi: casadi::DaeBuilderInternal::CallIO Struct Reference
casadi::DaeBuilderInternal::CallIO Struct Reference
Helper class, represents inputs and outputs for a function call node.
#include <dae_builder_internal.hpp>
Detailed Description
Definition at line 591 of file dae_builder_internal.hpp.
Public Member Functions
void calc_jac ()
void calc_grad ()
void calc_hess ()
const MX & jac (casadi_int oind, casadi_int iind) const
const MX & hess (casadi_int iind1, casadi_int iind2) const
Public Attributes
Function f
Function adj1_f
Function J
Function H
std::vector< size_t > v
std::vector< size_t > vdef
std::vector< MX > arg
std::vector< MX > res
std::vector< MX > jac_res
std::vector< MX > adj1_arg
std::vector< MX > adj1_res
std::vector< MX > hess_res
Member Function Documentation
calc_grad()
void casadi::DaeBuilderInternal::CallIO::calc_grad ()
Definition at line 2025 of file dae_builder_internal.cpp.
{
   // Consistency checks
   for (casadi_int i = 0; i < this->f.n_in(); ++i) {
     casadi_assert(this->f.size_in(i) == this->arg.at(i).size(), "Call input not provided");
   }
   casadi_assert(this->adj1_arg.size() == this->res.size(), "Input 'lam_vdef' not provided");
   for (casadi_int i = 0; i < this->f.n_out(); ++i) {
     casadi_assert(this->f.size_out(i) == this->res.at(i).size(), "Call output not provided");
     casadi_assert(this->adj1_arg.at(i).size() == this->res.at(i).size(),
       "Call adjoint seed not provided");
   }
   // We should make use of the Jacobian blocks here, if available
   if (!this->jac_res.empty())
     casadi_warning("Jacobian blocks currently not reused for gradient calculation");
   // Get/generate the (cached) adjoint function
   // casadi_message("Retrieving the gradient of " + str(this->f));
   this->adj1_f = this->f.reverse(1);
   // casadi_message("Retrieving the gradient of " + str(this->f) + " done");
   // Input expressions for the call to adj1_f
   std::vector<MX> call_in = this->arg;
   call_in.insert(call_in.end(), this->res.begin(), this->res.end());
   call_in.insert(call_in.end(), this->adj1_arg.begin(), this->adj1_arg.end());
   // Create expressions for adjoint sweep and save to struct
   this->adj1_res = this->adj1_f(call_in);
 }
calc_hess()
void casadi::DaeBuilderInternal::CallIO::calc_hess ()
Definition at line 2051 of file dae_builder_internal.cpp.
{
   // Calculate gradient, if needed
   if (this->adj1_f.is_null()) calc_grad();
   // Get/generate the (cached) Hessian function
   // casadi_message("Retrieving the Hessian of " + str(this->f));
   this->H = this->adj1_f.jacobian();
   // casadi_message("Retrieving the Hessian of " + str(this->f) + " done");
   // Input expressions for the call to H
   std::vector<MX> call_in = this->arg;
   call_in.insert(call_in.end(), this->res.begin(), this->res.end());
   call_in.insert(call_in.end(), this->adj1_arg.begin(), this->adj1_arg.end());
   call_in.insert(call_in.end(), this->adj1_res.begin(), this->adj1_res.end());
   // Create expressions for Hessian blocks and save to struct
   this->hess_res = this->H(call_in);
 }
calc_jac()
void casadi::DaeBuilderInternal::CallIO::calc_jac ()
Definition at line 2006 of file dae_builder_internal.cpp.
{
   // Consistency checks
   for (casadi_int i = 0; i < this->f.n_in(); ++i) {
     casadi_assert(this->f.size_in(i) == this->arg.at(i).size(), "Call input not provided");
   }
   for (casadi_int i = 0; i < this->f.n_out(); ++i) {
     casadi_assert(this->f.size_out(i) == this->res.at(i).size(), "Call output not provided");
   }
   // Get/generate the (cached) Jacobian function
   // casadi_message("Retrieving the Jacobian of " + str(this->f));
   this->J = this->f.jacobian();
   // casadi_message("Retrieving the Jacobian of " + str(this->f) + " done");
   // Input expressions for the call to J
   std::vector<MX> call_in = this->arg;
   call_in.insert(call_in.end(), this->res.begin(), this->res.end());
   // Create expressions for Jacobian blocks and save to struct
   this->jac_res = this->J(call_in);
 }
References arg, f, J, jac_res, casadi::Function::jacobian(), casadi::Function::n_in(), casadi::Function::n_out(), casadi::Function::size_in(), and casadi::Function::size_out().
hess()
const MX & casadi::DaeBuilderInternal::CallIO::hess (casadi_int iind1, casadi_int iind2) const
Definition at line 2074 of file dae_builder_internal.cpp.
{
   // Flat index
   casadi_int ind = iind1 + iind1 * this->adj1_arg.size();
   // Return reference
   return this->hess_res.at(ind);
 }
References casadi::GenericMatrix< MatType >::size().
jac()
const MX & casadi::DaeBuilderInternal::CallIO::jac (casadi_int oind, casadi_int iind) const
Definition at line 2067 of file dae_builder_internal.cpp.
{
   // Flat index
   casadi_int ind = iind + oind * this->arg.size();
   // Return reference
   return this->jac_res.at(ind);
 }
References casadi::GenericMatrix< MatType >::size().
Member Data Documentation
adj1_arg
std::vector<MX> casadi::DaeBuilderInternal::CallIO::adj1_arg
Definition at line 603 of file dae_builder_internal.hpp.
Referenced by casadi::DaeBuilderInternal::create().
adj1_f
Function casadi::DaeBuilderInternal::CallIO::adj1_f
Definition at line 593 of file dae_builder_internal.hpp.
adj1_res
std::vector<MX> casadi::DaeBuilderInternal::CallIO::adj1_res
Definition at line 605 of file dae_builder_internal.hpp.
arg
std::vector<MX> casadi::DaeBuilderInternal::CallIO::arg
Definition at line 597 of file dae_builder_internal.hpp.
Referenced by calc_jac(), and casadi::DaeBuilderInternal::create().
f
Function casadi::DaeBuilderInternal::CallIO::f
Definition at line 593 of file dae_builder_internal.hpp.
Referenced by calc_jac(), and casadi::DaeBuilderInternal::create().
H
Function casadi::DaeBuilderInternal::CallIO::H
Definition at line 593 of file dae_builder_internal.hpp.
hess_res
std::vector<MX> casadi::DaeBuilderInternal::CallIO::hess_res
Definition at line 607 of file dae_builder_internal.hpp.
J
Function casadi::DaeBuilderInternal::CallIO::J
Definition at line 593 of file dae_builder_internal.hpp.
Referenced by calc_jac().
jac_res
std::vector<MX> casadi::DaeBuilderInternal::CallIO::jac_res
Definition at line 601 of file dae_builder_internal.hpp.
Referenced by calc_jac().
res
std::vector<MX> casadi::DaeBuilderInternal::CallIO::res
Definition at line 599 of file dae_builder_internal.hpp.
Referenced by casadi::DaeBuilderInternal::create().
v
std::vector<size_t> casadi::DaeBuilderInternal::CallIO::v
Definition at line 595 of file dae_builder_internal.hpp.
Referenced by casadi::DaeBuilderInternal::create().
vdef
std::vector<size_t> casadi::DaeBuilderInternal::CallIO::vdef
Definition at line 595 of file dae_builder_internal.hpp.
Referenced by casadi::DaeBuilderInternal::create().
The documentation for this struct was generated from the following files:
dae_builder_internal.hpp
dae_builder_internal.cpp