CasADi: casadi::CallSX Class Reference
casadi::CallSX Class Reference
#include <call_sx.hpp>
Detailed Description
Definition at line 42 of file call_sx.hpp.
Public Member Functions
~CallSX () override
Destructor.
std::string class_name () const override
Get type name.
bool is_op (casadi_int op) const override
check properties of a node
casadi_int n_dep () const override
Number of dependencies.
SXElem get_output (casadi_int oind) const override
Get an output.
const SXElem & dep (casadi_int i) const override
get the reference of a dependency
SXElem & dep (casadi_int i) override
get the reference of a child
casadi_int op () const override
Get the operation.
bool is_call () const override
Check if call node.
bool has_output () const override
Check if a multiple output node.
Function which_function () const override
Get function.
std::string print (const std::string &arg1, const std::string &arg2) const override
Print expression.
void serialize_node (SerializingStream &s) const override
virtual const std::string & name () const
virtual casadi_int which_output () const
Get function output.
virtual bool is_equal (const SXNode *node, casadi_int depth) const
Check if two nodes are equivalent up to a given depth.
virtual bool is_smooth () const
Check if smooth.
virtual void disp (std::ostream &stream, bool more) const
print
void can_inline (std::map< const SXNode *, casadi_int > &nodeind) const
Find out which nodes can be inlined.
std::string print_compact (std::map< const SXNode *, casadi_int > &nodeind, std::vector< std::string > &intermed) const
Print compact.
bool marked () const
void mark () const
SXElem shared_from_this ()
Get a shared object from the current internal object.
const SXElem shared_from_this () const
Get a shared object from the current internal object.
void serialize (SerializingStream &s) const
Serialize an object.
virtual bool is_constant () const
check properties of a node
virtual bool is_integer () const
check properties of a node
virtual bool is_symbolic () const
check properties of a node
virtual bool is_zero () const
check properties of a node
virtual bool is_almost_zero (double tol) const
check properties of a node
virtual bool is_one () const
check properties of a node
virtual bool is_minus_one () const
check properties of a node
virtual bool is_nan () const
check properties of a node
virtual bool is_inf () const
check properties of a node
virtual bool is_minus_inf () const
check properties of a node
virtual bool is_output () const
check properties of a node
virtual double to_double () const
Get value of a constant node.
virtual casadi_int to_int () const
Get value of a constant node.
Static Public Member Functions
static SXElem create (const Function &f, const std::vector< SXElem > &dep)
Create a binary expression.
static int eval_sx (const Function &f, const SXElem **arg, SXElem **res)
static SXNode * deserialize (DeserializingStream &s)
static void safe_delete (SXNode *n)
Non-recursive delete.
Public Attributes
Function f_
std::vector< SXElem > dep_
The dependencies of the node.
int temp
unsigned int count
Static Public Attributes
static casadi_int eq_depth_ = 1
static std::map< casadi_int, SXNode *(*)(DeserializingStream &)> deserialize_map
Constructor & Destructor Documentation
~CallSX()
casadi::CallSX::~CallSX () inline override
This is a rather complex destructor which is necessary since the default destructor can cause stack overflow due to recursive calling.
Extra doc: https://github.com/casadi/casadi/wiki/L_28q
Definition at line 88 of file call_sx.hpp.
{
       for (auto & d  : dep_)
         safe_delete(d.assignNoDelete(casadi_limits<SXElem>::nan));
     }
Member Function Documentation
can_inline()
void casadi::SXNode::can_inline (std::map< const SXNode *, casadi_int > & nodeind) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_a6
Definition at line 113 of file sx_node.cpp.
{
     // Add or mark node in map
     std::map<const SXNode*, casadi_int>::iterator it=nodeind.find(this);
     if (it==nodeind.end()) {
       // First time encountered, mark inlined
       nodeind.insert(it, std::make_pair(this, 0));
       // Handle dependencies with recursion
       for (casadi_int i=0; i<n_dep(); ++i) {
         dep(i)->can_inline(nodeind);
       }
     } else if (it->second==0 && op()!=OP_PARAMETER) {
       // Node encountered before, do not inline (except if symbolic primitive)
       it->second = -1;
     }
   }
References casadi::SXNode::can_inline(), casadi::SXNode::dep(), casadi::SXNode::n_dep(), casadi::SXNode::op(), and casadi::OP_PARAMETER.
Referenced by casadi::SXNode::can_inline(), and casadi::SXNode::disp().
class_name()
std::string casadi::CallSX::class_name () const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_9y
Implements casadi::SXNode.
Definition at line 94 of file call_sx.hpp.
 {return "CallSX";}
create()
static SXElem casadi::CallSX::create (const Function & f, const std::vector< SXElem > & dep) inline static
Extra doc: https://github.com/casadi/casadi/wiki/L_28p
Definition at line 57 of file call_sx.hpp.
{
       casadi_assert(f.nnz_in()==dep.size(),
         "CallSX::create(f,dep): dimension mismatch: " + str(f.nnz_in()) + " vs " + str(dep.size()));
       return SXElem::create(new CallSX(f, dep));
     }
References casadi::SXElem::create(), casadi::Function::nnz_in(), and casadi::str().
Referenced by casadi::SXElem::call().
dep() [1/2]
const SXElem& casadi::CallSX::dep (casadi_int i) const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_28t
Reimplemented from casadi::SXNode.
Definition at line 119 of file call_sx.hpp.
 { return dep_[i];}
Referenced by casadi::SXFunction::ad_forward(), and casadi::SXFunction::ad_reverse().
dep() [2/2]
SXElem& casadi::CallSX::dep (casadi_int i) inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_a3
Reimplemented from casadi::SXNode.
Definition at line 120 of file call_sx.hpp.
 { return dep_[i];}
deserialize()
static SXNode* casadi::CallSX::deserialize (DeserializingStream & s) inline static
Definition at line 161 of file call_sx.hpp.
{
       std::vector<SXElem> dep;
       Function f;
       s.unpack("CallSX::f", f);
       s.unpack("CallSX::dep", dep);
       return new CallSX(f, dep);
     }
References casadi::DeserializingStream::unpack().
disp()
void casadi::SXNode::disp (std::ostream & stream, bool more) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_a5
Definition at line 88 of file sx_node.cpp.
{
     // Find out which noded can be inlined
     std::map<const SXNode*, casadi_int> nodeind;
     can_inline(nodeind);
     // Print expression
     std::vector<std::string> intermed;
     std::string s = print_compact(nodeind, intermed);
     // Print intermediate expressions
     for (casadi_int i=0; i<intermed.size(); ++i)
       stream << "@" << (i+1) << "=" << intermed[i] << ", ";
     // Print this
     stream << s;
   }
References casadi::SXNode::can_inline(), and casadi::SXNode::print_compact().
Referenced by casadi::SXElem::disp().
eval_sx()
static int casadi::CallSX::eval_sx (const Function & f, const SXElem ** arg, SXElem ** res) inline static
Definition at line 63 of file call_sx.hpp.
{
       // Collect dep from arg
       std::vector<SXElem> dep;
       for (casadi_int i=0;i<f.n_in();++i) {
         dep.insert(dep.end(), arg[i], arg[i]+f.nnz_in(i));
       }
       std::vector<SXElem> ret = SXElem::call(f, dep);
       // Copy ret to res
       casadi_int offset = 0;
       for (casadi_int i=0;i<f.n_out();++i) {
         casadi_copy(get_ptr(ret)+offset, f.nnz_out(i), res[i]);
         offset += f.nnz_out(i);
       }
       return 0;
     }
References casadi::SXElem::call(), casadi::casadi_copy(), casadi::get_ptr(), casadi::Function::n_in(), casadi::Function::n_out(), casadi::Function::nnz_in(), and casadi::Function::nnz_out().
Referenced by casadi::FunctionInternal::eval_sx().
get_output()
SXElem casadi::CallSX::get_output (casadi_int oind) const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_28s
Reimplemented from casadi::SXNode.
Definition at line 106 of file call_sx.hpp.
{
       SharedSXElem ret;
       // If not found, add it,
       if (!cache_.incache(oind, ret)) {
         ret.own(new OutputSX(SXNode::shared_from_this(), oind));
         cache_.tocache_if_missing(oind, ret);
       }
       return SXElem::create(ret.get());
     }
References casadi::SXElem::create(), casadi::GenericShared< Shared, Internal >::get(), casadi::WeakCache< K, T >::incache(), casadi::GenericShared< Shared, Internal >::own(), casadi::SXNode::shared_from_this(), and casadi::WeakCache< K, T >::tocache_if_missing().
Referenced by casadi::SXFunction::ad_forward(), and casadi::SXFunction::ad_reverse().
has_output()
bool casadi::CallSX::has_output () const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_28w
Reimplemented from casadi::SXNode.
Definition at line 135 of file call_sx.hpp.
 { return true; }
is_almost_zero()
virtual bool casadi::SXNode::is_almost_zero (double tol) const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::ZeroSX, and casadi::RealtypeSX.
Definition at line 74 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::is_almost_zero().
is_call()
bool casadi::CallSX::is_call () const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_28v
Reimplemented from casadi::SXNode.
Definition at line 130 of file call_sx.hpp.
 { return true; }
is_constant()
virtual bool casadi::SXNode::is_constant () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::ConstantSX.
Definition at line 69 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::binary(), casadi::SXFunction::init(), and casadi::SXElem::is_constant().
is_equal()
bool casadi::SXNode::is_equal (const SXNode * node, casadi_int depth) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_a0
Reimplemented in casadi::UnarySX, casadi::ConstantSX, and casadi::BinarySX.
Definition at line 72 of file sx_node.cpp.
{
     return false;
   }
Referenced by casadi::SXElem::is_equal().
is_inf()
virtual bool casadi::SXNode::is_inf () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::InfSX.
Definition at line 78 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::is_inf().
is_integer()
virtual bool casadi::SXNode::is_integer () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::MinusOneSX, casadi::OneSX, casadi::ZeroSX, and casadi::IntegerSX.
Definition at line 70 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::binary(), and casadi::SXElem::is_integer().
is_minus_inf()
virtual bool casadi::SXNode::is_minus_inf () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::MinusInfSX.
Definition at line 79 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::is_minus_inf().
is_minus_one()
virtual bool casadi::SXNode::is_minus_one () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::MinusOneSX.
Definition at line 76 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::binary(), and casadi::SXElem::is_minus_one().
is_nan()
virtual bool casadi::SXNode::is_nan () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::NanSX.
Definition at line 77 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::is_nan().
is_one()
virtual bool casadi::SXNode::is_one () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::OneSX.
Definition at line 75 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::binary(), and casadi::SXElem::is_one().
is_op()
bool casadi::CallSX::is_op (casadi_int op) const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented from casadi::SXNode.
Definition at line 96 of file call_sx.hpp.
 { return OP_CALL==op; }
References casadi::OP_CALL.
is_output()
virtual bool casadi::SXNode::is_output () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::OutputSX.
Definition at line 81 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::is_output().
is_smooth()
virtual bool casadi::SXNode::is_smooth () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_a4
Reimplemented in casadi::UnarySX, and casadi::BinarySX.
Definition at line 144 of file sx_node.hpp.
 { return true; }
is_symbolic()
virtual bool casadi::SXNode::is_symbolic () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::SymbolicSX.
Definition at line 71 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXFunction::init(), and casadi::SXElem::is_symbolic().
is_zero()
virtual bool casadi::SXNode::is_zero () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::ZeroSX.
Definition at line 72 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::binary(), and casadi::SXElem::is_zero().
mark()
void casadi::SXNode::mark () const inherited
Definition at line 109 of file sx_node.cpp.
{
     temp = -temp-1;
   }
References casadi::SXNode::temp.
marked()
bool casadi::SXNode::marked () const inherited
Definition at line 105 of file sx_node.cpp.
{
     return temp<0;
   }
References casadi::SXNode::temp.
n_dep()
casadi_int casadi::CallSX::n_dep () const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_28r
Reimplemented from casadi::SXNode.
Definition at line 101 of file call_sx.hpp.
 { return dep_.size();}
name()
const std::string & casadi::SXNode::name () const virtual inherited
Reimplemented in casadi::SymbolicSX.
Definition at line 76 of file sx_node.cpp.
{
     casadi_error("'name' not defined for " + class_name());
   }
References casadi::SXNode::class_name().
Referenced by casadi::SXElem::name().
op()
casadi_int casadi::CallSX::op () const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_28u
Implements casadi::SXNode.
Definition at line 125 of file call_sx.hpp.
 { return OP_CALL; }
References casadi::OP_CALL.
print()
std::string casadi::CallSX::print (const std::string & arg1, const std::string & arg2) const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_28y
Implements casadi::SXNode.
Definition at line 145 of file call_sx.hpp.
{
       return f_.name();
     }
print_compact()
std::string casadi::SXNode::print_compact (std::map< const SXNode *, casadi_int > & nodeind, std::vector< std::string > & intermed) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_a7
Definition at line 130 of file sx_node.cpp.
{
     // Get reference to node index
     casadi_int& ind = nodeind[this];
     // If positive, already in intermediate expressions
     if (ind>0) {
       std::stringstream ss;
       ss << "@" << ind;
       return ss.str();
     }
     std::string s;
     if (op()==OP_CALL) {
       const Function& f = which_function();
       // Get expressions for dependencies
       s = which_function().name() + "(";
       casadi_int k = 0;
       for (casadi_int i=0; i<f.n_in(); ++i) {
         if (f.nnz_in(i)>1) s += "[";
         for (casadi_int j=0; j<f.nnz_in(i); ++j) {
           s += dep(k++)->print_compact(nodeind, intermed);
           if (j<f.nnz_in(i)-1) s+=",";
         }
         if (f.nnz_in(i)>1) s += "]";
         if (i<f.n_in()-1) s+=",";
       }
       s += ")";
     } else {
       // Get expressions for dependencies
       std::string arg[2];
       for (casadi_int i=0; i<n_dep(); ++i) {
         arg[i] = dep(i)->print_compact(nodeind, intermed);
       }
       // Get expression for this
       s = print(arg[0], arg[1]);
     }
     // Decide what to do with the expression
     if (ind==0) {
       // Inline expression
       return s;
     } else {
       // Add to list of intermediate expressions and return reference
       intermed.push_back(s);
       ind = intermed.size(); // For subsequent references
       std::stringstream ss;
       ss << "@" << ind;
       return ss.str();
     }
   }
References casadi::SXNode::dep(), casadi::SXNode::n_dep(), casadi::Function::n_in(), casadi::Function::name(), casadi::Function::nnz_in(), casadi::SXNode::op(), casadi::OP_CALL, casadi::SXNode::print(), casadi::SXNode::print_compact(), and casadi::SXNode::which_function().
Referenced by casadi::SXNode::disp(), and casadi::SXNode::print_compact().
safe_delete()
void casadi::SXNode::safe_delete (SXNode * n) static inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_a9
Definition at line 184 of file sx_node.cpp.
{
     // Quick return if more owners
     if (n->count>0) return;
     // Delete straight away if it doesn't have any dependencies
     if (!n->n_dep()) {
       delete n;
       return;
     }
     // Stack of expressions to be deleted
     std::stack<SXNode*> deletion_stack;
     // Add the node to the deletion stack
     deletion_stack.push(n);
     // Process stack
     while (!deletion_stack.empty()) {
       // Top element
       SXNode *t = deletion_stack.top();
       // Check if the top element has dependencies with dependencies
       bool added_to_stack = false;
       for (casadi_int c2=0; c2<t->n_dep(); ++c2) { // for all dependencies of the dependency
         // Get the node of the dependency of the top element
         // and remove it from the smart pointer
         SXNode *n2 = t->dep(c2).assignNoDelete(casadi_limits<SXElem>::nan);
         // Check if this is the only reference to the element
         if (n2->count == 0) {
           // Check if unary or binary
           if (!n2->n_dep()) {
             // Delete straight away if not binary
             delete n2;
           } else {
             // Add to deletion stack
             deletion_stack.push(n2);
             added_to_stack = true;
           }
         }
       }
       // Delete and pop from stack if nothing added to the stack
       if (!added_to_stack) {
         delete deletion_stack.top();
         deletion_stack.pop();
       }
     }
   }
References casadi::SXElem::assignNoDelete(), casadi::SXNode::count, casadi::SXNode::dep(), and casadi::SXNode::n_dep().
Referenced by casadi::BinarySX::~BinarySX(), and casadi::UnarySX::~UnarySX().
serialize()
void casadi::SXNode::serialize (SerializingStream & s) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_aa
Definition at line 238 of file sx_node.cpp.
{
     s.pack("SXNode::op", op());
     serialize_node(s);
   }
References casadi::SXNode::op(), casadi::SerializingStream::pack(), and casadi::SXNode::serialize_node().
serialize_node()
void casadi::CallSX::serialize_node (SerializingStream & s) const inline override virtual
Reimplemented from casadi::SXNode.
Definition at line 156 of file call_sx.hpp.
{
       s.pack("CallSX::f", f_);
       s.pack("CallSX::dep", dep_);
     }
References casadi::SerializingStream::pack().
shared_from_this() [1/2]
SXElem casadi::SXNode::shared_from_this () inherited
Definition at line 261 of file sx_node.cpp.
{
     return SXElem(this, false);
   }
References casadi::SXNode::SXElem.
Referenced by casadi::SXNode::get_output(), and get_output().
shared_from_this() [2/2]
const SXElem casadi::SXNode::shared_from_this () const inherited
Definition at line 265 of file sx_node.cpp.
{
     return SXElem(const_cast<SXNode*>(this), false);
   }
References casadi::SXNode::SXElem.
to_double()
double casadi::SXNode::to_double () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9x
Reimplemented in casadi::ConstantSX, casadi::NanSX, casadi::MinusInfSX, casadi::InfSX, casadi::MinusOneSX, casadi::OneSX, casadi::ZeroSX, casadi::IntegerSX, and casadi::RealtypeSX.
Definition at line 56 of file sx_node.cpp.
{
     return std::numeric_limits<double>::quiet_NaN();
   }
Referenced by casadi::SXElem::binary(), and casadi::SXFunction::init().
to_int()
casadi_int casadi::SXNode::to_int () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9x
Reimplemented in casadi::MinusOneSX, casadi::OneSX, casadi::ZeroSX, casadi::IntegerSX, and casadi::RealtypeSX.
Definition at line 60 of file sx_node.cpp.
{
     casadi_error("to_int not defined for " + class_name());
   }
References casadi::SXNode::class_name().
Referenced by casadi::SXElem::binary().
which_function()
Function casadi::CallSX::which_function () const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_28x
Reimplemented from casadi::SXNode.
Definition at line 140 of file call_sx.hpp.
 { return f_; }
which_output()
casadi_int casadi::SXNode::which_output () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_292
Reimplemented in casadi::OutputSX.
Definition at line 68 of file sx_node.cpp.
{
     casadi_error("'which_output' not defined for class " + class_name());
   }
References casadi::SXNode::class_name().
Referenced by casadi::SXElem::which_output().
Member Data Documentation
count
unsigned int casadi::SXNode::count inherited
Definition at line 197 of file sx_node.hpp.
Referenced by casadi::SXElem::assignNoDelete(), casadi::SXElem::operator=(), casadi::SXNode::safe_delete(), casadi::SXElem::SXElem(), casadi::SXNode::SXNode(), casadi::UniversalNodeOwner::UniversalNodeOwner(), casadi::InfSX::~InfSX(), casadi::MinusInfSX::~MinusInfSX(), casadi::MinusOneSX::~MinusOneSX(), casadi::NanSX::~NanSX(), casadi::OneSX::~OneSX(), casadi::SXElem::~SXElem(), casadi::SXNode::~SXNode(), and casadi::ZeroSX::~ZeroSX().
dep_
std::vector<SXElem> casadi::CallSX::dep_
Extra doc: https://github.com/casadi/casadi/wiki/L_28z
Definition at line 154 of file call_sx.hpp.
deserialize_map
std::map< casadi_int, SXNode *(*)(DeserializingStream &)> casadi::SXNode::deserialize_map static inherited
Initial value:
= {
    {OP_PARAMETER, SymbolicSX::deserialize},
    {OP_CONST, ConstantSX_deserialize},
    {OP_CALL, CallSX::deserialize},
    {-1, OutputSX::deserialize}}
Definition at line 209 of file sx_node.hpp.
Referenced by casadi::SXNode::deserialize().
eq_depth_
casadi_int casadi::SXNode::eq_depth_ = 1 static inherited
Definition at line 179 of file sx_node.hpp.
Referenced by casadi::SXElem::binary(), casadi::Matrix< Scalar >::get_max_depth(), casadi::SXElem::is_doubled(), and casadi::Matrix< Scalar >::set_max_depth().
f_
Function casadi::CallSX::f_
Definition at line 149 of file call_sx.hpp.
temp
int casadi::SXNode::temp mutable inherited
Temporary variables to be used in user algorithms like sorting, the user is responsible of making sure that use is thread-safe The variable is initialized to zero
Definition at line 191 of file sx_node.hpp.
Referenced by casadi::SXFunction::init(), casadi::SXNode::mark(), casadi::SXNode::marked(), and casadi::SXNode::SXNode().
The documentation for this class was generated from the following file:
call_sx.hpp