CasADi: casadi::ZipMemResource Class Reference
casadi::ZipMemResource Class Reference
RAII class for reading from a zip held in memory.
#include <resource_internal.hpp>
Detailed Description
Extra doc: https://github.com/casadi/casadi/wiki/L_2cy
Definition at line 141 of file resource_internal.hpp.
Public Types
using weak_ref_type = WeakRefInternal
Public Member Functions
ZipMemResource (const std::istream &src)
~ZipMemResource () override
const std::string & path () const override
Get path for a consumer.
void unpack ()
std::string class_name () const override
Get type name.
void disp (std::ostream &stream, bool more) const override
Print description.
void serialize_body (SerializingStream &s) const override
void serialize (SerializingStream &s) const
virtual void serialize_type (SerializingStream &s) const
void change_option (const std::string &option_name, const GenericType &option_value)
casadi_int getCount () const
Get the reference count.
std::string debug_repr (const SharedObjectInternal *) const
GenericWeakRef< SharedObject, SharedObjectInternal > * weak ()
Get a weak reference to the object.
Static Public Member Functions
static ResourceInternal * deserialize (DeserializingStream &s)
Protected Member Functions
ZipMemResource (DeserializingStream &s)
void initSingleton ()
void destroySingleton ()
B shared_from_this ()
Get a shared object from the current internal object.
const B shared_from_this () const
Get a shared object from the current internal object.
Protected Attributes
std::string serialize_mode_
Member Typedef Documentation
weak_ref_type
using casadi::SharedObjectInternal::weak_ref_type = WeakRefInternal inherited
Definition at line 152 of file shared_object.hpp.
Constructor & Destructor Documentation
ZipMemResource() [1/2]
casadi::ZipMemResource::ZipMemResource (const std::istream & src)
Definition at line 107 of file resource_internal.cpp.
     : ResourceInternal() {
   blob_ << src.rdbuf();
   unpack();
 }
References unpack().
Referenced by deserialize().
~ZipMemResource()
casadi::ZipMemResource::~ZipMemResource () override
Definition at line 134 of file resource_internal.cpp.
{
   try {
     casadi_assert_dev(Filesystem::remove_all(dir_));
   } catch (...) {
       casadi_warning("Error: Cannot remove temporary directory: " + dir_);
   }
   try {
     casadi_assert_dev(Filesystem::remove(lock_file_));
   } catch (...) {
       casadi_warning("Error: Cannot remove lock file: " + lock_file_);
   }
 }
References casadi::Filesystem::remove(), and casadi::Filesystem::remove_all().
ZipMemResource() [2/2]
casadi::ZipMemResource::ZipMemResource (DeserializingStream & s) explicit protected
Definition at line 202 of file resource_internal.cpp.
                                                      : ResourceInternal(s) {
 #ifdef CASADI_WITH_THREADSAFE_SYMBOLICS
   std::lock_guard<std::mutex> lock(mutex_blob_);
 #endif // CASADI_WITH_THREADSAFE_SYMBOLICS
   s.version("ZipMemResource", 1);
   s.unpack("ZipMemResource::blob", blob_);
   unpack();
 }
References unpack(), casadi::DeserializingStream::unpack(), and casadi::DeserializingStream::version().
Member Function Documentation
change_option()
void casadi::ResourceInternal::change_option (const std::string & option_name, const GenericType & option_value) inherited
Definition at line 53 of file resource_internal.cpp.
{
   if (option_name=="serialize_mode") {
     serialize_mode_ = option_value.to_string();
     casadi_assert(serialize_mode_=="embed" || serialize_mode_=="link",
       "Invalid serialization mode: " + serialize_mode_ + ". Pick 'link' or 'embed'.");
   } else {
     casadi_error("Option '" + option_name + "' does not exist");
   }
 }
References casadi::ResourceInternal::serialize_mode_, and casadi::GenericType::to_string().
class_name()
std::string casadi::ZipMemResource::class_name () const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_2d5
Implements casadi::SharedObjectInternal.
Definition at line 152 of file resource_internal.hpp.
 {return "ZipMemResource";}
debug_repr()
std::string casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::debug_repr (const Internal * i) const inherited
Definition at line 62 of file generic_shared_internal.hpp.
{
     // Note: i != this because of something something multiple inheritance
     return str( (casadi_int)(i)) + "/" + static_cast<const Internal*>(this)->class_name();
   }
deserialize()
ResourceInternal * casadi::ZipMemResource::deserialize (DeserializingStream & s) static
Definition at line 186 of file resource_internal.cpp.
{
 ZipMemResource* ret = new ZipMemResource(s);
   return ret;
 }
References ZipMemResource().
Referenced by casadi::ResourceInternal::deserialize().
destroySingleton()
void casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::destroySingleton () inline protected inherited
Called in the destructor of singletons
Definition at line 77 of file generic_shared_internal.hpp.
{
       static_cast<Internal*>(this)->count--;
     }
disp()
void casadi::ZipMemResource::disp (std::ostream & stream, bool more) const override virtual
Implements casadi::SharedObjectInternal.
Definition at line 117 of file resource_internal.cpp.
{
   stream << "ZipMemResource(blob) -> \"" << dir_ << "\"";
 }
getCount()
casadi_int casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::getCount inherited
Definition at line 60 of file generic_shared_internal.hpp.
{
     return static_cast<const Internal*>(this)->count;
   }
initSingleton()
void casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::initSingleton () inline protected inherited
Called in the constructor of singletons to avoid that the counter reaches zero
Definition at line 71 of file generic_shared_internal.hpp.
{
       casadi_assert_dev(static_cast<Internal*>(this)->count==0);
       static_cast<Internal*>(this)->count++;
     }
path()
const std::string& casadi::ZipMemResource::path () const inline override virtual
Implements casadi::ResourceInternal.
Definition at line 146 of file resource_internal.hpp.
 {return dir_;}
serialize()
void casadi::ResourceInternal::serialize (SerializingStream & s) const inherited
Definition at line 147 of file resource_internal.cpp.
{
   s.version("ResourceInternal", 1);
   serialize_type(s);
   serialize_body(s);
 }
References casadi::ResourceInternal::serialize_body(), casadi::ResourceInternal::serialize_type(), and casadi::SerializingStream::version().
serialize_body()
void casadi::ZipMemResource::serialize_body (SerializingStream & s) const override virtual
Reimplemented from casadi::ResourceInternal.
Definition at line 274 of file resource_internal.cpp.
{
 #ifdef CASADI_WITH_THREADSAFE_SYMBOLICS
   std::lock_guard<std::mutex> lock(mutex_blob_);
 #endif // CASADI_WITH_THREADSAFE_SYMBOLICS
   ResourceInternal::serialize_body(s);
   s.version("ZipMemResource", 1);
   s.pack("ZipMemResource::blob", blob_);
   // rewind
   blob_.clear();
   blob_.seekg(0, std::ios::beg);
 }
References casadi::SerializingStream::pack(), casadi::ResourceInternal::serialize_body(), and casadi::SerializingStream::version().
serialize_type()
void casadi::ResourceInternal::serialize_type (SerializingStream & s) const virtual inherited
Reimplemented in casadi::ZipResource, and casadi::DirResource.
Definition at line 153 of file resource_internal.cpp.
{
   s.pack("ResourceInternal::type", class_name());
 }
References casadi::SharedObjectInternal::class_name(), and casadi::SerializingStream::pack().
Referenced by casadi::ResourceInternal::serialize().
shared_from_this() [1/2]
B casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::shared_from_this () inline protected inherited
Definition at line 83 of file generic_shared_internal.hpp.
{
       casadi_assert_dev(B::test_cast(static_cast<Internal*>(this)));
       B ret;
       ret.own(static_cast<Internal*>(this));
       return ret;
     }
shared_from_this() [2/2]
const B casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::shared_from_this () const inline protected inherited
Definition at line 92 of file generic_shared_internal.hpp.
{
       casadi_assert_dev(B::test_cast(static_cast<const Internal*>(this)));
       B ret;
       ret.own(const_cast<Internal*>(static_cast<const Internal*>(this)));
       return ret;
     }
unpack()
void casadi::ZipMemResource::unpack ()
Definition at line 87 of file resource_internal.cpp.
{
   std::string zip_file = "zip";
   lock_file_ = Filesystem::absolute(temporary_file(zip_file + ".", ".lock"));
   dir_ = lock_file_.substr(0, lock_file_.size()-5) + ".unzipped";
   casadi_assert(Archiver::has_plugin("libzip"),
   "Unzipping stream requires libzip. Compile CasADi with WITH_LIBZIP=ON.\n"
   "Alternatively, save with serialize option set to link. ");
   Archiver::getPlugin("libzip").exposed.unpack_from_stringstream(blob_, dir_);
   // rewind
   blob_.clear();
   blob_.seekg(0, std::ios::beg);
 }
References casadi::Filesystem::absolute(), casadi::PluginInterface< Archiver >::getPlugin(), casadi::PluginInterface< Archiver >::has_plugin(), and casadi::temporary_file().
Referenced by ZipMemResource().
weak()
GenericWeakRef< SharedObject , SharedObjectInternal > * casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::weak inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1ai
Definition at line 67 of file generic_shared_internal.hpp.
{
     if (weak_ref_==nullptr) {
       weak_ref_ = new GenericWeakRef<Shared, Internal>(static_cast<Internal*>(this));
     }
     return weak_ref_;
   }
Member Data Documentation
serialize_mode_
std::string casadi::ResourceInternal::serialize_mode_ protected inherited
Definition at line 63 of file resource_internal.hpp.
Referenced by casadi::ResourceInternal::change_option(), casadi::ResourceInternal::ResourceInternal(), casadi::ResourceInternal::serialize_body(), casadi::DirResource::serialize_body(), casadi::ZipResource::serialize_body(), casadi::DirResource::serialize_type(), and casadi::ZipResource::serialize_type().
The documentation for this class was generated from the following files:
resource_internal.hpp
resource_internal.cpp