CasADi: casadi::LinsolLdlMemory Struct Reference
casadi::LinsolLdlMemory Struct Reference
#include <linsol_ldl.hpp>
Detailed Description
Definition at line 43 of file linsol_ldl.hpp.
Public Member Functions
void add_stat (const std::string &s)
Public Attributes
std::vector< double > l
std::vector< double > d
std::vector< double > w
bool is_sfact
bool is_nfact
std::map< std::string, FStats > fstats
FStats * t_total
Member Function Documentation
add_stat()
void casadi::ProtoFunctionMemory::add_stat (const std::string & s) inline inherited
Definition at line 74 of file function_internal.hpp.
{
       bool added = fstats.insert(std::make_pair(s, FStats())).second;
       casadi_assert(added, "Duplicate stat: '" + s + "'");
     }
Referenced by casadi::ProtoFunction::init_mem(), casadi::LinsolInternal::init_mem(), casadi::Nlpsol::init_mem(), casadi::OracleFunction::init_mem(), casadi::CbcInterface::init_mem(), casadi::ClpInterface::init_mem(), casadi::FatropConicInterface::init_mem(), casadi::HpipmInterface::init_mem(), casadi::Feasiblesqpmethod::init_mem(), casadi::Sqpmethod::init_mem(), and casadi::OracleFunction::local_init_mem().
Member Data Documentation
d
std::vector<double> casadi::LinsolLdlMemory::d
Definition at line 44 of file linsol_ldl.hpp.
fstats
std::map<std::string, FStats> casadi::ProtoFunctionMemory::fstats inherited
Definition at line 68 of file function_internal.hpp.
Referenced by casadi::Nlpsol::callback(), casadi::IpoptUserClass::eval_h(), casadi::BonminInterface::intermediate_callback(), casadi::IpoptInterface::intermediate_callback(), casadi::OracleFunction::join_results(), casadi::ClarabelInterface::solve(), casadi::DaqpInterface::solve(), casadi::HighsInterface::solve(), casadi::HpipmInterface::solve(), casadi::HpmpcInterface::solve(), casadi::ProxqpInterface::solve(), casadi::QpoasesInterface::solve(), casadi::Sqpmethod::solve_ela_QP(), casadi::Feasiblesqpmethod::solve_LP(), casadi::Feasiblesqpmethod::solve_QP(), and casadi::Sqpmethod::solve_QP().
is_nfact
bool casadi::LinsolMemory::is_nfact inherited
Definition at line 39 of file linsol_internal.hpp.
Referenced by casadi::Linsol::nfact().
is_sfact
bool casadi::LinsolMemory::is_sfact inherited
Definition at line 39 of file linsol_internal.hpp.
Referenced by casadi::Linsol::sfact().
l
std::vector<double> casadi::LinsolLdlMemory::l
Definition at line 44 of file linsol_ldl.hpp.
t_total
FStats* casadi::ProtoFunctionMemory::t_total inherited
Definition at line 71 of file function_internal.hpp.
Referenced by casadi::LinsolCall< Tr >::eval(), and casadi::Linsol::solve().
w
std::vector<double> casadi::LinsolLdlMemory::w
Definition at line 44 of file linsol_ldl.hpp.
The documentation for this struct was generated from the following file:
linsol_ldl.hpp