CasADi: casadi::FunctionBuffer Class Reference
casadi::FunctionBuffer Class Reference
Class to achieve minimal overhead function evaluations.
#include <function.hpp>
Detailed Description
Extra doc: https://github.com/casadi/casadi/wiki/L_1y9
Definition at line 1318 of file function.hpp.
Public Member Functions
FunctionBuffer (const Function &f)
Main constructor.
~FunctionBuffer ()
FunctionBuffer (const FunctionBuffer &f)
FunctionBuffer & operator= (const FunctionBuffer &f)
void set_arg (casadi_int i, const double *a, casadi_int size)
Set input buffer for input i.
void set_res (casadi_int i, double *a, casadi_int size)
Set output buffer for ouput i.
int ret ()
Get last return value.
void _eval ()
void * _self ()
Dict stats () const
Constructor & Destructor Documentation
FunctionBuffer() [1/2]
casadi::FunctionBuffer::FunctionBuffer (const Function & f)
Extra doc: https://github.com/casadi/casadi/wiki/L_1ya
Definition at line 1954 of file function.cpp.
                                                   : f_(f) {
     w_.resize(f_.sz_w());
     iw_.resize(f_.sz_iw());
     arg_.resize(f_.sz_arg());
     res_.resize(f_.sz_res());
     mem_ = f_->checkout();
     mem_internal_ = f.memory(mem_);
     f_node_ = f.operator->();
   }
References casadi::ProtoFunction::checkout(), casadi::Function::memory(), casadi::Function::sz_arg(), casadi::Function::sz_iw(), casadi::Function::sz_res(), and casadi::Function::sz_w().
~FunctionBuffer()
casadi::FunctionBuffer::~FunctionBuffer ()
Definition at line 1964 of file function.cpp.
{
     if (f_->release_) {
       f_->release_(mem_);
     } else {
       f_.release(mem_);
     }
   }
References casadi::Function::release(), and casadi::FunctionInternal::release_.
FunctionBuffer() [2/2]
casadi::FunctionBuffer::FunctionBuffer (const FunctionBuffer & f)
Definition at line 1972 of file function.cpp.
                                                         : f_(f.f_) {
     operator=(f);
   }
References operator=().
Member Function Documentation
_eval()
void casadi::FunctionBuffer::_eval ()
Definition at line 2002 of file function.cpp.
{
     if (f_node_->eval_) {
       ret_ = f_node_->eval_(get_ptr(arg_), get_ptr(res_), get_ptr(iw_), get_ptr(w_), mem_);
     } else {
       ret_ = f_node_->eval(get_ptr(arg_), get_ptr(res_), get_ptr(iw_), get_ptr(w_), mem_internal_);
     }
   }
References casadi::FunctionInternal::eval(), casadi::FunctionInternal::eval_, and casadi::get_ptr().
_self()
void* casadi::FunctionBuffer::_self () inline
Definition at line 1359 of file function.hpp.
 { return this; }
operator=()
FunctionBuffer & casadi::FunctionBuffer::operator= (const FunctionBuffer & f)
Definition at line 1976 of file function.cpp.
{
     f_ = f.f_;
     w_ = f.w_; iw_ = f.iw_; arg_ = f.arg_; res_ = f.res_; f_node_ = f.f_node_;
     // Checkout fresh memory
     if (f_->checkout_) {
       mem_ = f_->checkout_();
     } else {
       mem_ = f_.checkout();
       mem_internal_ = f_.memory(mem_);
     }
     return *this;
   }
References casadi::Function::checkout(), casadi::FunctionInternal::checkout_, and casadi::Function::memory().
Referenced by FunctionBuffer().
ret()
int casadi::FunctionBuffer::ret ()
Definition at line 2009 of file function.cpp.
{
     return ret_;
   }
set_arg()
void casadi::FunctionBuffer::set_arg (casadi_int i, const double * a, casadi_int size)
mem.set_arg(0, memoryview(a))
Note that CasADi uses 'fortran' order: column-by-column
Extra doc: https://github.com/casadi/casadi/wiki/L_1yb
Definition at line 1990 of file function.cpp.
{
     casadi_assert(size>=f_.nnz_in(i)*sizeof(double),
      "Buffer is not large enough. Needed " + str(f_.nnz_in(i)*sizeof(double)) +
      " bytes, got " + str(size) + ".");
     arg_.at(i) = a;
   }
References casadi::Function::nnz_in(), and casadi::str().
set_res()
void casadi::FunctionBuffer::set_res (casadi_int i, double * a, casadi_int size)
mem.set_res(0, memoryview(a))
Note that CasADi uses 'fortran' order: column-by-column
Extra doc: https://github.com/casadi/casadi/wiki/L_1yc
Definition at line 1996 of file function.cpp.
{
     casadi_assert(size>=f_.nnz_out(i)*sizeof(double),
      "Buffer is not large enough. Needed " + str(f_.nnz_out(i)*sizeof(double)) +
      " bytes, got " + str(size) + ".");
     res_.at(i) = a;
   }
References casadi::Function::nnz_out(), and casadi::str().
stats()
Dict casadi::FunctionBuffer::stats () const
Definition at line 2017 of file function.cpp.
{
     return f_.stats(mem_);
   }
References casadi::Function::stats().
The documentation for this class was generated from the following files:
function.hpp
function.cpp