CasADi: Title
Title
Functions
Function casadi::expmsol (const std::string &name, const std::string &solver, const Sparsity &A, const Dict &opts)
casadi_int casadi::expm_n_in ()
Get the number of expm solver inputs.
casadi_int casadi::expm_n_out ()
Get the number of expm solver outputs.
bool casadi::has_expm (const std::string &name)
Check if a particular plugin is available.
void casadi::load_expm (const std::string &name)
Explicitly load a plugin dynamically.
std::string casadi::doc_expm (const std::string &name)
Get the documentation string for a plugin.
Detailed Description
Performs a matrix exponentiation expm(A)
General information
List of available options
Id Type Description Used in
ad_weight OT_DOUBLE Weighting factor for derivative calculation.When there is an option of either using forward or reverse mode directional derivatives, the condition ad_weight*nf<=(1-ad_weight)*na is used where nf and na are estimates of the number of forward/reverse mode directional derivatives needed. By default, ad_weight is calculated automatically, but this can be overridden by setting this option. In particular, 0 means forcing forward mode and 1 forcing reverse mode. Leave unset for (class specific) heuristics. casadi::FunctionInternal
ad_weight_sp OT_DOUBLE Weighting factor for sparsity pattern calculation calculation.Overrides default behavior. Set to 0 and 1 to force forward and reverse mode respectively. Cf. option "ad_weight". When set to -1, sparsity is completely ignored and dense matrices are used. casadi::FunctionInternal
always_inline OT_BOOL Force inlining. casadi::FunctionInternal
cache OT_DICT Prepopulate the function cache. Default: empty casadi::FunctionInternal
compiler OT_STRING Just-in-time compiler plugin to be used. casadi::FunctionInternal
const_A OT_BOOL Assume A is constant. Default: false. casadi::Expm
custom_jacobian OT_FUNCTION Override CasADi's AD. Use together with 'jac_penalty': 0. Note: Highly experimental. Syntax may break often. casadi::FunctionInternal
der_options OT_DICT Default options to be used to populate forward_options, reverse_options, and jacobian_options before those options are merged in. casadi::FunctionInternal
derivative_of OT_FUNCTION The function is a derivative of another function. The type of derivative (directional derivative, Jacobian) is inferred from the function name. casadi::FunctionInternal
dump OT_BOOL Dump function to file upon first evaluation. [false] casadi::FunctionInternal
dump_dir OT_STRING Directory to dump inputs/outputs to. Make sure the directory exists [.] casadi::FunctionInternal
dump_format OT_STRING Choose file format to dump matrices. See DM.from_file [mtx] casadi::FunctionInternal
dump_in OT_BOOL Dump numerical values of inputs to file (readable with DM.from_file) [default: false] casadi::FunctionInternal
dump_out OT_BOOL Dump numerical values of outputs to file (readable with DM.from_file) [default: false] casadi::FunctionInternal
enable_fd OT_BOOL Enable derivative calculation by finite differencing. [default: false]] casadi::FunctionInternal
enable_forward OT_BOOL Enable derivative calculation using generated functions for Jacobian-times-vector products - typically using forward mode AD - if available. [default: true] casadi::FunctionInternal
enable_jacobian OT_BOOL Enable derivative calculation using generated functions for Jacobians of all differentiable outputs with respect to all differentiable inputs - if available. [default: true] casadi::FunctionInternal
enable_reverse OT_BOOL Enable derivative calculation using generated functions for transposed Jacobian-times-vector products - typically using reverse mode AD - if available. [default: true] casadi::FunctionInternal
error_on_fail OT_BOOL Throw exceptions when function evaluation fails (default true). casadi::ProtoFunction
external_transform OT_VECTORVECTOR List of external_transform instruction arguments. Default: empty casadi::FunctionInternal
fd_method OT_STRING Method for finite differencing [default 'central'] casadi::FunctionInternal
fd_options OT_DICT Options to be passed to the finite difference instance casadi::FunctionInternal
forward_options OT_DICT Options to be passed to a forward mode constructor casadi::FunctionInternal
gather_stats OT_BOOL Deprecated option (ignored): Statistics are now always collected. casadi::FunctionInternal
input_scheme OT_STRINGVECTOR Deprecated option (ignored) casadi::FunctionInternal
inputs_check OT_BOOL Throw exceptions when the numerical values of the inputs don't make sense casadi::FunctionInternal
is_diff_in OT_BOOLVECTOR Indicate for each input if it should be differentiable. casadi::FunctionInternal
is_diff_out OT_BOOLVECTOR Indicate for each output if it should be differentiable. casadi::FunctionInternal
jac_penalty OT_DOUBLE When requested for a number of forward/reverse directions, it may be cheaper to compute first the full jacobian and then multiply with seeds, rather than obtain the requested directions in a straightforward manner. Casadi uses a heuristic to decide which is cheaper. A high value of 'jac_penalty' makes it less likely for the heurstic to chose the full Jacobian strategy. The special value -1 indicates never to use the full Jacobian strategy casadi::FunctionInternal
jacobian_options OT_DICT Options to be passed to a Jacobian constructor casadi::FunctionInternal
jit OT_BOOL Use just-in-time compiler to speed up the evaluation casadi::FunctionInternal
jit_cleanup OT_BOOL Cleanup up the temporary source file that jit creates. Default: true casadi::FunctionInternal
jit_name OT_STRING The file name used to write out code. The actual file names used depend on 'jit_temp_suffix' and include extensions. Default: 'jit_tmp' casadi::FunctionInternal
jit_options OT_DICT Options to be passed to the jit compiler. casadi::FunctionInternal
jit_serialize OT_STRING Specify behaviour when serializing a jitted function: SOURCE|link|embed. casadi::FunctionInternal
jit_temp_suffix OT_BOOL Use a temporary (seemingly random) filename suffix for generated code and libraries. This is desired for thread-safety. This behaviour may defeat caching compiler wrappers. Default: true casadi::FunctionInternal
max_io OT_INT Acceptable number of inputs and outputs. Warn if exceeded. casadi::FunctionInternal
max_num_dir OT_INT Specify the maximum number of directions for derivative functions. Overrules the builtin optimized_num_dir. casadi::FunctionInternal
never_inline OT_BOOL Forbid inlining. casadi::FunctionInternal
output_scheme OT_STRINGVECTOR Deprecated option (ignored) casadi::FunctionInternal
post_expand OT_BOOL After construction, expand this Function. Default: False casadi::FunctionInternal
post_expand_options OT_DICT Options to be passed to post-construction expansion. Default: empty casadi::FunctionInternal
print_in OT_BOOL Print numerical values of inputs [default: false] casadi::FunctionInternal
print_out OT_BOOL Print numerical values of outputs [default: false] casadi::FunctionInternal
print_time OT_BOOL print information about execution time. Implies record_time. casadi::ProtoFunction
record_time OT_BOOL record information about execution time, for retrieval with stats(). casadi::ProtoFunction
regularity_check OT_BOOL Throw exceptions when NaN or Inf appears during evaluation casadi::ProtoFunction
reverse_options OT_DICT Options to be passed to a reverse mode constructor casadi::FunctionInternal
user_data OT_VOIDPTR A user-defined field that can be used to identify the function or pass additional information casadi::FunctionInternal
verbose OT_BOOL Verbose evaluation – for debugging casadi::ProtoFunction
List of plugins
- slicot
Note: some of the plugins in this list might not be available on your system. Also, there might be extra plugins available to you that are not listed here. You can obtain their documentation with Expm.doc("myextraplugin")
slicot
Extra doc: https://github.com/casadi/casadi/wiki/L_22l
Author
Joris Gillis
Date
2017
Extra doc: https://github.com/casadi/casadi/wiki/L_21l
Function Documentation
doc_expm()
CASADI_EXPORT std::string casadi::doc_expm (const std::string & name)
Definition at line 40 of file expm.cpp.
{
     return Expm::getPlugin(name).doc;
   }
References casadi::PluginInterface< Expm >::getPlugin().
expm_n_in()
CASADI_EXPORT casadi_int casadi::expm_n_in ()
Extra doc: https://github.com/casadi/casadi/wiki/L_rs
Definition at line 49 of file expm.cpp.
{
     return 2;
   }
expm_n_out()
CASADI_EXPORT casadi_int casadi::expm_n_out ()
Extra doc: https://github.com/casadi/casadi/wiki/L_rt
Definition at line 53 of file expm.cpp.
{
     return 1;
   }
expmsol()
CASADI_EXPORT Function casadi::expmsol (const std::string & name, const std::string & solver, const Sparsity & A, const Dict & opts = Dict())
Definition at line 44 of file expm.cpp.
{
     return Function::create(Expm::instantiate(name, solver, A), opts);
   }
References casadi::Function::create(), and casadi::PluginInterface< Expm >::instantiate().
Referenced by casadi::MX::expm(), and casadi::MX::expm_const().
has_expm()
CASADI_EXPORT bool casadi::has_expm (const std::string & name)
Definition at line 32 of file expm.cpp.
{
     return Expm::has_plugin(name);
   }
References casadi::PluginInterface< Expm >::has_plugin().
load_expm()
CASADI_EXPORT void casadi::load_expm (const std::string & name)
Definition at line 36 of file expm.cpp.
{
     Expm::load_plugin(name);
   }
References casadi::PluginInterface< Expm >::load_plugin().