CasADi: casadi::QpoasesInterface Class Reference
casadi::QpoasesInterface Class Reference
'qpoases' plugin for Conic
#include <qpoases_interface.hpp>
Detailed Description
Interface to QPOases Solver for quadratic programming
Extra doc: https://github.com/casadi/casadi/wiki/L_22o
List of available options
Id Type Description
CPUtime OT_DOUBLE The maximum allowed CPU time in seconds for the whole initialisation (and the actually required one on output). Disabled if unset.
boundRelaxation OT_DOUBLE Initial relaxation of bounds to start homotopy and initial value for far bounds.
boundTolerance OT_DOUBLE If upper and lower bounds differ less than this tolerance, they are regarded equal, i.e. as equality constraint.
enableCholeskyRefactorisation OT_INT Specifies the frequency of a full re-factorisation of projected Hessian matrix: 0: turns them off, 1: uses them at each iteration etc.
enableDriftCorrection OT_INT Specifies the frequency of drift corrections: 0: turns them off.
enableEqualities OT_BOOL Specifies whether equalities should be treated as always active (True) or not (False)
enableFarBounds OT_BOOL Enables the use of far bounds.
enableFlippingBounds OT_BOOL Enables the use of flipping bounds.
enableFullLITests OT_BOOL Enables condition-hardened (but more expensive) LI test.
enableInertiaCorrection OT_BOOL Should working set be repaired when negative curvature is discovered during hotstart.
enableNZCTests OT_BOOL Enables nonzero curvature tests.
enableRamping OT_BOOL Enables ramping.
enableRegularisation OT_BOOL Enables automatic Hessian regularisation.
epsDen OT_DOUBLE Denominator tolerance for ratio tests.
epsFlipping OT_DOUBLE Tolerance of squared Cholesky diagonal factor which triggers flipping bound.
epsIterRef OT_DOUBLE Early termination tolerance for iterative refinement.
epsLITests OT_DOUBLE Tolerance for linear independence tests.
epsNZCTests OT_DOUBLE Tolerance for nonzero curvature tests.
epsNum OT_DOUBLE Numerator tolerance for ratio tests.
epsRegularisation OT_DOUBLE Scaling factor of identity matrix used for Hessian regularisation.
finalRamping OT_DOUBLE Final value for ramping strategy.
growFarBounds OT_DOUBLE Factor to grow far bounds.
hessian_type OT_STRING Type of Hessian - see qpOASES documentation [UNKNOWN|posdef|semidef|indef|zero|identity]]
initialFarBounds OT_DOUBLE Initial size for far bounds.
initialRamping OT_DOUBLE Start value for ramping strategy.
initialStatusBounds OT_STRING Initial status of bounds at first iteration.
linsol_plugin OT_STRING Linear solver plugin
maxDualJump OT_DOUBLE Maximum allowed jump in dual variables in linear independence tests.
maxPrimalJump OT_DOUBLE Maximum allowed jump in primal variables in nonzero curvature tests.
max_schur OT_INT Maximal number of Schur updates [75]
nWSR OT_INT The maximum number of working set recalculations to be performed during the initial homotopy. Default is 5(nx + nc)
numRefinementSteps OT_INT Maximum number of iterative refinement steps.
numRegularisationSteps OT_INT Maximum number of successive regularisation steps.
printLevel OT_STRING Defines the amount of text output during QP solution, see Section 5.7
schur OT_BOOL Use Schur Complement Approach [false]
sparse OT_BOOL Formulate the QP using sparse matrices. [false]
terminationTolerance OT_DOUBLE Relative termination tolerance to stop homotopy.
Author
Joris Gillis, Joel Andersson
Date
2011
List of available options
Id Type Description Used in
CPUtime OT_DOUBLE The maximum allowed CPU time in seconds for the whole initialisation (and the actually required one on output). Disabled if unset. casadi::QpoasesInterface
ad_weight OT_DOUBLE Weighting factor for derivative calculation.When there is an option of either using forward or reverse mode directional derivatives, the condition ad_weight*nf<=(1-ad_weight)*na is used where nf and na are estimates of the number of forward/reverse mode directional derivatives needed. By default, ad_weight is calculated automatically, but this can be overridden by setting this option. In particular, 0 means forcing forward mode and 1 forcing reverse mode. Leave unset for (class specific) heuristics. casadi::FunctionInternal
ad_weight_sp OT_DOUBLE Weighting factor for sparsity pattern calculation calculation.Overrides default behavior. Set to 0 and 1 to force forward and reverse mode respectively. Cf. option "ad_weight". When set to -1, sparsity is completely ignored and dense matrices are used. casadi::FunctionInternal
always_inline OT_BOOL Force inlining. casadi::FunctionInternal
boundRelaxation OT_DOUBLE Initial relaxation of bounds to start homotopy and initial value for far bounds. casadi::QpoasesInterface
boundTolerance OT_DOUBLE If upper and lower bounds differ less than this tolerance, they are regarded equal, i.e. as equality constraint. casadi::QpoasesInterface
cache OT_DICT Prepopulate the function cache. Default: empty casadi::FunctionInternal
compiler OT_STRING Just-in-time compiler plugin to be used. casadi::FunctionInternal
custom_jacobian OT_FUNCTION Override CasADi's AD. Use together with 'jac_penalty': 0. Note: Highly experimental. Syntax may break often. casadi::FunctionInternal
der_options OT_DICT Default options to be used to populate forward_options, reverse_options, and jacobian_options before those options are merged in. casadi::FunctionInternal
derivative_of OT_FUNCTION The function is a derivative of another function. The type of derivative (directional derivative, Jacobian) is inferred from the function name. casadi::FunctionInternal
discrete OT_BOOLVECTOR Indicates which of the variables are discrete, i.e. integer-valued casadi::Conic
dump OT_BOOL Dump function to file upon first evaluation. [false] casadi::FunctionInternal
dump_dir OT_STRING Directory to dump inputs/outputs to. Make sure the directory exists [.] casadi::FunctionInternal
dump_format OT_STRING Choose file format to dump matrices. See DM.from_file [mtx] casadi::FunctionInternal
dump_in OT_BOOL Dump numerical values of inputs to file (readable with DM.from_file) [default: false] casadi::FunctionInternal
dump_out OT_BOOL Dump numerical values of outputs to file (readable with DM.from_file) [default: false] casadi::FunctionInternal
enableCholeskyRefactorisation OT_INT Specifies the frequency of a full re-factorisation of projected Hessian matrix: 0: turns them off, 1: uses them at each iteration etc. casadi::QpoasesInterface
enableDriftCorrection OT_INT Specifies the frequency of drift corrections: 0: turns them off. casadi::QpoasesInterface
enableEqualities OT_BOOL Specifies whether equalities should be treated as always active (True) or not (False) casadi::QpoasesInterface
enableFarBounds OT_BOOL Enables the use of far bounds. casadi::QpoasesInterface
enableFlippingBounds OT_BOOL Enables the use of flipping bounds. casadi::QpoasesInterface
enableFullLITests OT_BOOL Enables condition-hardened (but more expensive) LI test. casadi::QpoasesInterface
enableInertiaCorrection OT_BOOL Should working set be repaired when negative curvature is discovered during hotstart. casadi::QpoasesInterface
enableNZCTests OT_BOOL Enables nonzero curvature tests. casadi::QpoasesInterface
enableRamping OT_BOOL Enables ramping. casadi::QpoasesInterface
enableRegularisation OT_BOOL Enables automatic Hessian regularisation. casadi::QpoasesInterface
enable_fd OT_BOOL Enable derivative calculation by finite differencing. [default: false]] casadi::FunctionInternal
enable_forward OT_BOOL Enable derivative calculation using generated functions for Jacobian-times-vector products - typically using forward mode AD - if available. [default: true] casadi::FunctionInternal
enable_jacobian OT_BOOL Enable derivative calculation using generated functions for Jacobians of all differentiable outputs with respect to all differentiable inputs - if available. [default: true] casadi::FunctionInternal
enable_reverse OT_BOOL Enable derivative calculation using generated functions for transposed Jacobian-times-vector products - typically using reverse mode AD - if available. [default: true] casadi::FunctionInternal
epsDen OT_DOUBLE Denominator tolerance for ratio tests. casadi::QpoasesInterface
epsFlipping OT_DOUBLE Tolerance of squared Cholesky diagonal factor which triggers flipping bound. casadi::QpoasesInterface
epsIterRef OT_DOUBLE Early termination tolerance for iterative refinement. casadi::QpoasesInterface
epsLITests OT_DOUBLE Tolerance for linear independence tests. casadi::QpoasesInterface
epsNZCTests OT_DOUBLE Tolerance for nonzero curvature tests. casadi::QpoasesInterface
epsNum OT_DOUBLE Numerator tolerance for ratio tests. casadi::QpoasesInterface
epsRegularisation OT_DOUBLE Scaling factor of identity matrix used for Hessian regularisation. casadi::QpoasesInterface
error_on_fail OT_BOOL Throw exceptions when function evaluation fails (default true). casadi::ProtoFunction
fd_method OT_STRING Method for finite differencing [default 'central'] casadi::FunctionInternal
fd_options OT_DICT Options to be passed to the finite difference instance casadi::FunctionInternal
finalRamping OT_DOUBLE Final value for ramping strategy. casadi::QpoasesInterface
forward_options OT_DICT Options to be passed to a forward mode constructor casadi::FunctionInternal
gather_stats OT_BOOL Deprecated option (ignored): Statistics are now always collected. casadi::FunctionInternal
growFarBounds OT_DOUBLE Factor to grow far bounds. casadi::QpoasesInterface
hessian_type OT_STRING Type of Hessian - see qpOASES documentation [UNKNOWN|posdef|semidef|indef|zero|identity]] casadi::QpoasesInterface
initialFarBounds OT_DOUBLE Initial size for far bounds. casadi::QpoasesInterface
initialRamping OT_DOUBLE Start value for ramping strategy. casadi::QpoasesInterface
initialStatusBounds OT_STRING Initial status of bounds at first iteration. casadi::QpoasesInterface
input_scheme OT_STRINGVECTOR Deprecated option (ignored) casadi::FunctionInternal
inputs_check OT_BOOL Throw exceptions when the numerical values of the inputs don't make sense casadi::FunctionInternal
is_diff_in OT_BOOLVECTOR Indicate for each input if it should be differentiable. casadi::FunctionInternal
is_diff_out OT_BOOLVECTOR Indicate for each output if it should be differentiable. casadi::FunctionInternal
jac_penalty OT_DOUBLE When requested for a number of forward/reverse directions, it may be cheaper to compute first the full jacobian and then multiply with seeds, rather than obtain the requested directions in a straightforward manner. Casadi uses a heuristic to decide which is cheaper. A high value of 'jac_penalty' makes it less likely for the heurstic to chose the full Jacobian strategy. The special value -1 indicates never to use the full Jacobian strategy casadi::FunctionInternal
jacobian_options OT_DICT Options to be passed to a Jacobian constructor casadi::FunctionInternal
jit OT_BOOL Use just-in-time compiler to speed up the evaluation casadi::FunctionInternal
jit_cleanup OT_BOOL Cleanup up the temporary source file that jit creates. Default: true casadi::FunctionInternal
jit_name OT_STRING The file name used to write out code. The actual file names used depend on 'jit_temp_suffix' and include extensions. Default: 'jit_tmp' casadi::FunctionInternal
jit_options OT_DICT Options to be passed to the jit compiler. casadi::FunctionInternal
jit_serialize OT_STRING Specify behaviour when serializing a jitted function: SOURCE|link|embed. casadi::FunctionInternal
jit_temp_suffix OT_BOOL Use a temporary (seemingly random) filename suffix for generated code and libraries. This is desired for thread-safety. This behaviour may defeat caching compiler wrappers. Default: true casadi::FunctionInternal
linsol_plugin OT_STRING Linear solver plugin casadi::QpoasesInterface
maxDualJump OT_DOUBLE Maximum allowed jump in dual variables in linear independence tests. casadi::QpoasesInterface
maxPrimalJump OT_DOUBLE Maximum allowed jump in primal variables in nonzero curvature tests. casadi::QpoasesInterface
max_io OT_INT Acceptable number of inputs and outputs. Warn if exceeded. casadi::FunctionInternal
max_num_dir OT_INT Specify the maximum number of directions for derivative functions. Overrules the builtin optimized_num_dir. casadi::FunctionInternal
max_schur OT_INT Maximal number of Schur updates [75] casadi::QpoasesInterface
nWSR OT_INT The maximum number of working set recalculations to be performed during the initial homotopy. Default is 5(nx + nc) casadi::QpoasesInterface
never_inline OT_BOOL Forbid inlining. casadi::FunctionInternal
numRefinementSteps OT_INT Maximum number of iterative refinement steps. casadi::QpoasesInterface
numRegularisationSteps OT_INT Maximum number of successive regularisation steps. casadi::QpoasesInterface
output_scheme OT_STRINGVECTOR Deprecated option (ignored) casadi::FunctionInternal
post_expand OT_BOOL After construction, expand this Function. Default: False casadi::FunctionInternal
post_expand_options OT_DICT Options to be passed to post-construction expansion. Default: empty casadi::FunctionInternal
printLevel OT_STRING Defines the amount of text output during QP solution, see Section 5.7 casadi::QpoasesInterface
print_in OT_BOOL Print numerical values of inputs [default: false] casadi::FunctionInternal
print_out OT_BOOL Print numerical values of outputs [default: false] casadi::FunctionInternal
print_problem OT_BOOL Print a numeric description of the problem casadi::Conic
print_time OT_BOOL print information about execution time. Implies record_time. casadi::ProtoFunction
record_time OT_BOOL record information about execution time, for retrieval with stats(). casadi::ProtoFunction
regularity_check OT_BOOL Throw exceptions when NaN or Inf appears during evaluation casadi::ProtoFunction
reverse_options OT_DICT Options to be passed to a reverse mode constructor casadi::FunctionInternal
schur OT_BOOL Use Schur Complement Approach [false] casadi::QpoasesInterface
sparse OT_BOOL Formulate the QP using sparse matrices. [false] casadi::QpoasesInterface
terminationTolerance OT_DOUBLE Relative termination tolerance to stop homotopy. casadi::QpoasesInterface
user_data OT_VOIDPTR A user-defined field that can be used to identify the function or pass additional information casadi::FunctionInternal
verbose OT_BOOL Verbose evaluation – for debugging casadi::ProtoFunction
Definition at line 98 of file qpoases_interface.hpp.
Public Types
typedef Conic *(* Creator) (const std::string &name, const std::map< std::string, Sparsity > &st)
typedef int(* RegFcn) (Plugin *plugin)
Public Member Functions
QpoasesInterface ()
Constructor.
QpoasesInterface (const std::string &name, const std::map< std::string, Sparsity > &st)
Create a new Solver.
~QpoasesInterface () override
Destructor.
const char * plugin_name () const override
std::string class_name () const override
Readable name of the internal class.
void init (const Dict &opts) override
Initialize.
void * alloc_mem () const override
Create memory block.
int init_mem (void *mem) const override
Initalize memory block.
void free_mem (void *mem) const override
Free memory block.
int solve (const double **arg, double **res, casadi_int *iw, double *w, void *mem) const override
Evaluate numerically.
Dict get_stats (void *mem) const override
Get all statistics.
void serialize_body (SerializingStream &s) const override
Serialize an object without type information.
int eval (const double **arg, double **res, casadi_int *iw, double *w, void *mem) const final
Solve the QP.
void set_work (void *mem, const double **&arg, double **&res, casadi_int *&iw, double *&w) const override
Set the (persistent) work vectors.
virtual void check_inputs (const double *lbx, const double *ubx, const double *lba, const double *uba) const
Check if the numerical values of the supplied bounds make sense.
virtual void generateNativeCode (std::ostream &file) const
bool is_a (const std::string &type, bool recursive) const override
Check if the function is of a particular type.
double get_default_in (casadi_int ind) const override
Get default input value.
virtual bool integer_support () const
Can discrete variables be treated.
virtual bool psd_support () const
Can psd constraints be treated.
void qp_codegen_body (CodeGenerator &g) const
Generate code for the function body.
void serialize (SerializingStream &s) const
Serialize an object.
void serialize_type (SerializingStream &s) const override
Serialize type information.
std::string serialize_base_function () const override
String used to identify the immediate FunctionInternal subclass.
virtual std::string getAdaptorSolverName () const
Obtain solver name from Adaptor.
Dict generate_options (const std::string &target) const override
Reconstruct options dict.
void change_option (const std::string &option_name, const GenericType &option_value) override
Change option after object creation for debugging.
void finalize () override
Finalize the object creation.
Function self () const
Get a public class instance.
virtual Function factory (const std::string &name, const std::vector< std::string > &s_in, const std::vector< std::string > &s_out, const Function::AuxOut &aux, const Dict &opts) const
virtual std::vector< std::string > get_function () const
virtual const Function & get_function (const std::string &name) const
virtual bool has_function (const std::string &fname) const
void add_embedded (std::map< FunctionInternal *, Function > &all_fun, const Function &dep, casadi_int max_depth) const
virtual void find (std::map< FunctionInternal *, Function > &all_fun, casadi_int max_depth) const
virtual std::vector< bool > which_depends (const std::string &s_in, const std::vector< std::string > &s_out, casadi_int order, bool tr=false) const
Which variables enter with some order.
virtual int eval_sx (const SXElem **arg, SXElem **res, casadi_int *iw, SXElem *w, void *mem) const
Evaluate with symbolic scalars.
virtual void eval_mx (const MXVector &arg, MXVector &res, bool always_inline, bool never_inline) const
Evaluate with symbolic matrices.
template<typename M >
void call (const std::vector< M > &arg, std::vector< M > &res, bool always_inline, bool never_inline) const
Call a function, templated.
template<typename M >
bool matching_arg (const std::vector< M > &arg, casadi_int &npar) const
Check if input arguments that needs to be replaced.
template<typename M >
bool matching_res (const std::vector< M > &arg, casadi_int &npar) const
Check if output arguments that needs to be replaced.
template<typename M >
std::vector< M > replace_arg (const std::vector< M > &arg, casadi_int npar) const
Replace 0-by-0 inputs.
template<typename M >
std::vector< M > project_arg (const std::vector< M > &arg, casadi_int npar) const
Project sparsities.
template<typename M >
std::vector< M > project_res (const std::vector< M > &arg, casadi_int npar) const
Project sparsities.
template<typename M >
std::vector< M > replace_res (const std::vector< M > &res, casadi_int npar) const
Replace 0-by-0 outputs.
template<typename M >
std::vector< std::vector< M > > replace_fseed (const std::vector< std::vector< M >> &fseed, casadi_int npar) const
Replace 0-by-0 forward seeds.
template<typename M >
std::vector< std::vector< M > > replace_fseed (const std::vector< std::vector< M > > &fseed, casadi_int npar) const
template<typename M >
std::vector< std::vector< M > > replace_aseed (const std::vector< std::vector< M >> &aseed, casadi_int npar) const
Replace 0-by-0 reverse seeds.
template<typename M >
std::vector< std::vector< M > > replace_aseed (const std::vector< std::vector< M > > &aseed, casadi_int npar) const
std::vector< MX > mapsum_mx (const std::vector< MX > &arg, const std::string &parallelization)
Parallel evaluation.
virtual bool uses_output () const
Do the derivative functions need nondifferentiated outputs?
std::string diff_prefix (const std::string &prefix) const
Determine prefix for differentiated functions.
virtual Function slice (const std::string &name, const std::vector< casadi_int > &order_in, const std::vector< casadi_int > &order_out, const Dict &opts) const
returns a new function with a selection of inputs/outputs of the original
virtual const Function & oracle () const
Get oracle.
bool has_derivative () const
Can derivatives be calculated in any way?
virtual double ad_weight () const
Weighting factor for chosing forward/reverse mode.
virtual double sp_weight () const
Weighting factor for chosing forward/reverse mode,.
virtual std::vector< MX > free_mx () const
Get free variables (MX)
virtual std::vector< SX > free_sx () const
Get free variables (SX)
virtual bool has_free () const
Does the function have free variables.
virtual void generate_lifted (Function &vdef_fcn, Function &vinit_fcn) const
Extract the functions needed for the Lifted Newton method.
virtual casadi_int n_instructions () const
Get the number of atomic operations.
virtual casadi_int instruction_id (casadi_int k) const
Get an atomic operation operator index.
virtual std::vector< casadi_int > instruction_input (casadi_int k) const
Get the (integer) input arguments of an atomic operation.
virtual double instruction_constant (casadi_int k) const
Get the floating point output argument of an atomic operation.
virtual std::vector< casadi_int > instruction_output (casadi_int k) const
Get the (integer) output argument of an atomic operation.
virtual casadi_int n_nodes () const
Number of nodes in the algorithm.
virtual MX instruction_MX (casadi_int k) const
get MX expression associated with instruction
virtual SX instructions_sx () const
get SX expression associated with instructions
Function wrap () const
Wrap in an Function instance consisting of only one MX call.
Function wrap_as_needed (const Dict &opts) const
Wrap in an Function instance consisting of only one MX call.
Dict cache () const
Get all functions in the cache.
bool incache (const std::string &fname, Function &f, const std::string &suffix="") const
Get function in cache.
void tocache (const Function &f, const std::string &suffix="") const
Save function to cache.
void codegen (CodeGenerator &g, const std::string &fname) const
Generate code the function.
void codegen_meta (CodeGenerator &g) const
Generate meta-information allowing a user to evaluate a generated function.
void codegen_sparsities (CodeGenerator &g) const
Codegen sparsities.
virtual std::string codegen_name (const CodeGenerator &g, bool ns=true) const
Get name in codegen.
std::string codegen_mem (CodeGenerator &g, const std::string &index="mem") const
Get thread-local memory object.
virtual void codegen_incref (CodeGenerator &g) const
Codegen incref for dependencies.
virtual void codegen_decref (CodeGenerator &g) const
Codegen decref for dependencies.
virtual void codegen_alloc_mem (CodeGenerator &g) const
Codegen decref for alloc_mem.
virtual void codegen_init_mem (CodeGenerator &g) const
Codegen decref for init_mem.
virtual void codegen_free_mem (CodeGenerator &g) const
Codegen for free_mem.
virtual void codegen_checkout (CodeGenerator &g) const
Codegen for checkout.
virtual void codegen_release (CodeGenerator &g) const
Codegen for release.
std::string signature (const std::string &fname) const
Code generate the function.
virtual void codegen_declarations (CodeGenerator &g) const
Generate code for the declarations of the C function.
virtual void codegen_body (CodeGenerator &g) const
Generate code for the function body.
virtual std::string codegen_mem_type () const
Thread-local memory object type.
virtual std::string generate_dependencies (const std::string &fname, const Dict &opts) const
Export / Generate C code for the dependency function.
virtual bool has_codegen () const
Is codegen supported?
virtual void jit_dependencies (const std::string &fname)
Jit dependencies.
virtual void export_code (const std::string &lang, std::ostream &stream, const Dict &options) const
Export function in a specific language.
void disp (std::ostream &stream, bool more) const override
Display object.
virtual void disp_more (std::ostream &stream) const
Print more.
std::string definition () const
Get function signature: name:(inputs)->(outputs)
void print_dimensions (std::ostream &stream) const
Print dimensions of inputs and outputs.
virtual std::vector< std::string > get_free () const
Print free variables.
void get_partition (casadi_int iind, casadi_int oind, Sparsity &D1, Sparsity &D2, bool compact, bool symmetric, bool allow_forward, bool allow_reverse) const
Get the unidirectional or bidirectional partition.
virtual double get_max_in (casadi_int ind) const
Get largest input value.
virtual double get_min_in (casadi_int ind) const
Get smallest input value.
virtual std::vector< double > get_nominal_in (casadi_int ind) const
virtual std::vector< double > get_nominal_out (casadi_int ind) const
virtual double get_reltol () const
Get relative tolerance.
virtual double get_abstol () const
Get absolute tolerance.
virtual bool get_diff_in (casadi_int i)
Which inputs are differentiable.
virtual bool get_diff_out (casadi_int i)
Which outputs are differentiable.
casadi_int index_in (const std::string &name) const
Get input scheme index by name.
casadi_int index_out (const std::string &name) const
Get output scheme index by name.
virtual int sp_forward (const bvec_t **arg, bvec_t **res, casadi_int *iw, bvec_t *w, void *mem) const
Propagate sparsity forward.
virtual int sp_forward_block (const bvec_t **arg, bvec_t **res, casadi_int *iw, bvec_t *w, void *mem, casadi_int oind, casadi_int iind) const
Propagate sparsity forward, specific block.
virtual int sp_reverse (bvec_t **arg, bvec_t **res, casadi_int *iw, bvec_t *w, void *mem) const
Propagate sparsity backwards.
void sz_work (size_t &sz_arg, size_t &sz_res, size_t &sz_iw, size_t &sz_w) const
Get number of temporary variables needed.
size_t sz_arg () const
Get required length of arg field.
size_t sz_res () const
Get required length of res field.
size_t sz_iw () const
Get required length of iw field.
size_t sz_w () const
Get required length of w field.
void alloc_arg (size_t sz_arg, bool persistent=false)
Ensure required length of arg field.
void alloc_res (size_t sz_res, bool persistent=false)
Ensure required length of res field.
void alloc_iw (size_t sz_iw, bool persistent=false)
Ensure required length of iw field.
void alloc_w (size_t sz_w, bool persistent=false)
Ensure required length of w field.
void alloc (const Function &f, bool persistent=false, int num_threads=1)
Ensure work vectors long enough to evaluate function.
virtual void set_temp (void *mem, const double **arg, double **res, casadi_int *iw, double *w) const
Set the (temporary) work vectors.
void setup (void *mem, const double **arg, double **res, casadi_int *iw, double *w) const
Set the (persistent and temporary) work vectors.
virtual Dict info () const
Function map (casadi_int n, const std::string &parallelization) const
Generate/retrieve cached serial map.
void generate_in (const std::string &fname, const double **arg) const
Export an input file that can be passed to generate C code with a main.
void generate_out (const std::string &fname, double **res) const
template<typename MatType >
std::vector< std::vector< MatType > > fwd_seed (casadi_int nfwd) const
Symbolic expressions for the forward seeds.
template<typename MatType >
std::vector< std::vector< MatType > > symbolicAdjSeed (casadi_int nadj, const std::vector< MatType > &v) const
Symbolic expressions for the adjoint seeds.
void print_in (std::ostream &stream, const double **arg, bool truncate) const
Print inputs.
void print_out (std::ostream &stream, double **res, bool truncate) const
Print outputs.
void construct (const Dict &opts)
Construct.
void print_options (std::ostream &stream) const
Print list of options.
void print_option (const std::string &name, std::ostream &stream) const
Print all information there is to know about a certain option.
bool has_option (const std::string &option_name) const
Does a particular option exist.
int checkout () const
Checkout a memory object.
void release (int mem) const
Release a memory object.
void * memory (int ind) const
Memory objects.
void clear_mem ()
Clear all memory (called from destructor)
void print (const char *fmt,...) const
C-style formatted printing during evaluation.
void sprint (char *buf, size_t buf_sz, const char *fmt,...) const
C-style formatted printing to string.
void format_time (char *buffer, double time) const
Format time in a fixed width 8 format.
void print_time (const std::map< std::string, FStats > &fstats) const
Print timing statistics.
casadi_int getCount () const
Get the reference count.
WeakRef * weak ()
Get a weak reference to the object.
size_t get_n_in () override
Number of function inputs and outputs.
size_t get_n_out () override
Number of function inputs and outputs.
Sparsity get_sparsity_in (casadi_int i) override
Sparsities of function inputs and outputs.
Sparsity get_sparsity_out (casadi_int i) override
Sparsities of function inputs and outputs.
std::string get_name_in (casadi_int i) override
Names of function input and outputs.
std::string get_name_out (casadi_int i) override
Names of function input and outputs.
virtual bool has_spfwd () const
Is the class able to propagate seeds through the algorithm?
virtual bool has_sprev () const
Is the class able to propagate seeds through the algorithm?
int eval_gen (const double **arg, double **res, casadi_int *iw, double *w, void *mem) const
Evaluate numerically.
int eval_gen (const SXElem **arg, SXElem **res, casadi_int *iw, SXElem *w, void *mem) const
Evaluate a function, overloaded.
int eval_gen (const bvec_t **arg, bvec_t **res, casadi_int *iw, bvec_t *w, void *mem) const
Evaluate a function, overloaded.
virtual std::vector< DM > eval_dm (const std::vector< DM > &arg) const
Evaluate with DM matrices.
virtual bool has_eval_dm () const
Evaluate with DM matrices.
void call_gen (const MXVector &arg, MXVector &res, casadi_int npar, bool always_inline, bool never_inline) const
Call a function, overloaded.
template<typename D >
void call_gen (const std::vector< Matrix< D > > &arg, std::vector< Matrix< D > > &res, casadi_int npar, bool always_inline, bool never_inline) const
Call a function, overloaded.
template<typename M >
void check_arg (const std::vector< M > &arg, casadi_int &npar) const
Check if input arguments have correct length and dimensions.
template<typename M >
void check_res (const std::vector< M > &res, casadi_int &npar) const
Check if output arguments have correct length and dimensions.
template<typename M >
std::map< std::string, M > convert_arg (const std::vector< M > &arg) const
Convert from/to input/output lists/map.
template<typename M >
std::vector< M > convert_arg (const std::map< std::string, M > &arg) const
Convert from/to input/output lists/map.
template<typename M >
std::map< std::string, M > convert_res (const std::vector< M > &res) const
Convert from/to input/output lists/map.
template<typename M >
std::vector< M > convert_res (const std::map< std::string, M > &res) const
Convert from/to input/output lists/map.
std::vector< double > nz_in (const std::vector< DM > &arg) const
Convert from/to flat vector of input/output nonzeros.
std::vector< DM > nz_in (const std::vector< double > &arg) const
Convert from/to flat vector of input/output nonzeros.
std::vector< double > nz_out (const std::vector< DM > &res) const
Convert from/to flat vector of input/output nonzeros.
std::vector< DM > nz_out (const std::vector< double > &res) const
Convert from/to flat vector of input/output nonzeros.
virtual void call_forward (const std::vector< MX > &arg, const std::vector< MX > &res, const std::vector< std::vector< MX > > &fseed, std::vector< std::vector< MX > > &fsens, bool always_inline, bool never_inline) const
Forward mode AD, virtual functions overloaded in derived classes.
virtual void call_forward (const std::vector< SX > &arg, const std::vector< SX > &res, const std::vector< std::vector< SX > > &fseed, std::vector< std::vector< SX > > &fsens, bool always_inline, bool never_inline) const
Forward mode AD, virtual functions overloaded in derived classes.
virtual void call_reverse (const std::vector< MX > &arg, const std::vector< MX > &res, const std::vector< std::vector< MX > > &aseed, std::vector< std::vector< MX > > &asens, bool always_inline, bool never_inline) const
Reverse mode, virtual functions overloaded in derived classes.
virtual void call_reverse (const std::vector< SX > &arg, const std::vector< SX > &res, const std::vector< std::vector< SX > > &aseed, std::vector< std::vector< SX > > &asens, bool always_inline, bool never_inline) const
Reverse mode, virtual functions overloaded in derived classes.
Function jacobian () const
Return Jacobian of all input elements with respect to all output elements.
virtual bool has_jacobian () const
Return Jacobian of all input elements with respect to all output elements.
virtual Function get_jacobian (const std::string &name, const std::vector< std::string > &inames, const std::vector< std::string > &onames, const Dict &opts) const
Return Jacobian of all input elements with respect to all output elements.
Sparsity & jac_sparsity (casadi_int oind, casadi_int iind, bool compact, bool symmetric) const
Get Jacobian sparsity.
virtual bool has_jac_sparsity (casadi_int oind, casadi_int iind) const
Get Jacobian sparsity.
virtual Sparsity get_jac_sparsity (casadi_int oind, casadi_int iind, bool symmetric) const
Get Jacobian sparsity.
Function forward (casadi_int nfwd) const
Return function that calculates forward derivatives.
virtual bool has_forward (casadi_int nfwd) const
Return function that calculates forward derivatives.
virtual Function get_forward (casadi_int nfwd, const std::string &name, const std::vector< std::string > &inames, const std::vector< std::string > &onames, const Dict &opts) const
Return function that calculates forward derivatives.
Function reverse (casadi_int nadj) const
Return function that calculates adjoint derivatives.
virtual bool has_reverse (casadi_int nadj) const
Return function that calculates adjoint derivatives.
virtual Function get_reverse (casadi_int nadj, const std::string &name, const std::vector< std::string > &inames, const std::vector< std::string > &onames, const Dict &opts) const
Return function that calculates adjoint derivatives.
virtual const SX sx_in (casadi_int ind) const
Get function input(s) and output(s)
virtual const std::vector< SX > sx_in () const
Get function input(s) and output(s)
virtual const SX sx_out (casadi_int ind) const
Get function input(s) and output(s)
virtual const std::vector< SX > sx_out () const
Get function input(s) and output(s)
virtual const MX mx_in (casadi_int ind) const
Get function input(s) and output(s)
virtual const std::vector< MX > mx_in () const
Get function input(s) and output(s)
virtual const MX mx_out (casadi_int ind) const
Get function input(s) and output(s)
virtual const std::vector< MX > mx_out () const
Get function input(s) and output(s)
const DM dm_in (casadi_int ind) const
Get function input(s) and output(s)
const std::vector< DM > dm_in () const
Get function input(s) and output(s)
const DM dm_out (casadi_int ind) const
Get function input(s) and output(s)
const std::vector< DM > dm_out () const
Get function input(s) and output(s)
casadi_int nnz_in () const
Number of input/output nonzeros.
casadi_int nnz_in (casadi_int ind) const
Number of input/output nonzeros.
casadi_int nnz_out () const
Number of input/output nonzeros.
casadi_int nnz_out (casadi_int ind) const
Number of input/output nonzeros.
casadi_int numel_in () const
Number of input/output elements.
casadi_int numel_in (casadi_int ind) const
Number of input/output elements.
casadi_int numel_out (casadi_int ind) const
Number of input/output elements.
casadi_int numel_out () const
Number of input/output elements.
casadi_int size1_in (casadi_int ind) const
Input/output dimensions.
casadi_int size2_in (casadi_int ind) const
Input/output dimensions.
casadi_int size1_out (casadi_int ind) const
Input/output dimensions.
casadi_int size2_out (casadi_int ind) const
Input/output dimensions.
std::pair< casadi_int, casadi_int > size_in (casadi_int ind) const
Input/output dimensions.
std::pair< casadi_int, casadi_int > size_out (casadi_int ind) const
Input/output dimensions.
const Sparsity & sparsity_in (casadi_int ind) const
Input/output sparsity.
const Sparsity & sparsity_out (casadi_int ind) const
Input/output sparsity.
bool all_scalar () const
Are all inputs and outputs scalar.
virtual bool jac_is_symm (casadi_int oind, casadi_int iind) const
Is a Jacobian block known to be symmetric a priori?
Sparsity to_compact (casadi_int oind, casadi_int iind, const Sparsity &sp) const
Convert to compact Jacobian sparsity pattern.
Sparsity from_compact (casadi_int oind, casadi_int iind, const Sparsity &sp) const
Convert from compact Jacobian sparsity pattern.
template<bool fwd>
Sparsity get_jac_sparsity_gen (casadi_int oind, casadi_int iind) const
Get the sparsity pattern via sparsity seed propagation.
Sparsity get_jac_sparsity_hierarchical (casadi_int oind, casadi_int iind) const
A flavor of get_jac_sparsity_gen that does hierarchical block structure recognition.
Sparsity get_jac_sparsity_hierarchical_symm (casadi_int oind, casadi_int iind) const
virtual std::vector< MX > symbolic_output (const std::vector< MX > &arg) const
Get a vector of symbolic variables corresponding to the outputs.
virtual bool fwdViaJac (casadi_int nfwd) const
Calculate derivatives by multiplying the full Jacobian and multiplying.
virtual bool adjViaJac (casadi_int nadj) const
Calculate derivatives by multiplying the full Jacobian and multiplying.
Static Public Member Functions
static Conic * creator (const std::string &name, const std::map< std::string, Sparsity > &st)
Create a new QP Solver.
static int qpoases_init (void *mem, int dim, int nnz, const int *row, const int *col)
qpOASES linear solver initialization
static int qpoases_sfact (void *mem, const double *vals)
qpOASES linear solver symbolical factorization
static int qpoases_nfact (void *mem, const double *vals, int *neig, int *rank)
qpOASES linear solver numerical factorization
static int qpoases_solve (void *mem, int nrhs, double *rhs)
qpOASES linear solver solve
static void qpoases_printf (const char *s)
qpOases printing function
static ProtoFunction * deserialize (DeserializingStream &s)
Deserialize into MX.
static std::string shortname ()
Short name.
static std::string forward_name (const std::string &fcn, casadi_int nfwd)
Helper function: Get name of forward derivative function.
static std::string reverse_name (const std::string &fcn, casadi_int nadj)
Helper function: Get name of adjoint derivative function.
template<typename MatType >
static MatType ensure_stacked (const MatType &v, const Sparsity &sp, casadi_int n)
Ensure that a matrix's sparsity is a horizontal multiple of another, or empty.
template<typename MatType >
static bool purgable (const std::vector< MatType > &seed)
Can a derivative direction be skipped.
static std::string string_from_UnifiedReturnStatus (UnifiedReturnStatus status)
static bool has_plugin (const std::string &pname, bool verbose=false)
Check if a plugin is available or can be loaded.
static const Options & plugin_options (const std::string &pname)
Get the plugin options.
static Deserialize plugin_deserialize (const std::string &pname)
Get the plugin deserialize_map.
static Plugin pluginFromRegFcn (RegFcn regfcn)
Instantiate a Plugin struct from a factory function.
static Plugin load_plugin (const std::string &pname, bool register_plugin=true)
Load a plugin dynamically.
static handle_t load_library (const std::string &libname, std::string &resultpath, bool global)
Load a library dynamically.
static void registerPlugin (const Plugin &plugin)
Register an integrator in the factory.
static void registerPlugin (RegFcn regfcn)
Register an integrator in the factory.
static Plugin & getPlugin (const std::string &pname)
Load and get the creator function.
static Conic * instantiate (const std::string &fname, const std::string &pname, Problem problem)
static bool check_mat (const Sparsity &arg, const Sparsity &inp, casadi_int &npar)
Public Attributes
casadi_qp_prob< double > p_qp_
bool always_inline_
bool never_inline_
size_t n_in_
Number of inputs and outputs.
size_t n_out_
std::vector< bool > is_diff_in_
Are inputs and outputs differentiable?
std::vector< bool > is_diff_out_
std::vector< Sparsity > sparsity_in_
Input and output sparsity.
std::vector< Sparsity > sparsity_out_
std::vector< std::string > name_in_
Input and output scheme.
std::vector< std::string > name_out_
bool jit_
Use just-in-time compiler.
bool jit_cleanup_
Cleanup jit source file.
std::string jit_serialize_
Serialize behaviour.
std::string jit_name_
Name if jit source file.
std::string jit_base_name_
bool jit_temp_suffix_
Use a temporary name.
eval_t eval_
Numerical evaluation redirected to a C function.
casadi_checkout_t checkout_
Checkout redirected to a C function.
casadi_release_t release_
Release redirected to a C function.
Dict stats_
Dict of statistics (resulting from evaluate)
bool has_refcount_
Reference counting in codegen?
Dict cache_init_
Values to prepopulate the function cache with.
std::map< std::string, WeakRef > cache_
Function cache.
std::vector< Sparsity > jac_sparsity_ [2]
Cache for sparsities of the Jacobian blocks.
Function derivative_of_
If the function is the derivative of another function.
void * user_data_
User-set field.
std::string compiler_plugin_
Just-in-time compiler.
Importer compiler_
Dict jit_options_
double jac_penalty_
Penalty factor for using a complete Jacobian to calculate directional derivatives.
bool enable_forward_
bool enable_reverse_
bool enable_jacobian_
bool enable_fd_
bool enable_forward_op_
bool enable_reverse_op_
bool enable_jacobian_op_
bool enable_fd_op_
double ad_weight_
Weighting factor for derivative calculation and sparsity pattern calculation.
double ad_weight_sp_
casadi_int max_num_dir_
Maximum number of sensitivity directions.
bool inputs_check_
Errors are thrown if numerical values of inputs look bad.
Dict fd_options_
double fd_step_
std::string fd_method_
bool print_in_
bool print_out_
casadi_int max_io_
bool dump_in_
bool dump_out_
bool dump_
std::string dump_dir_
std::string dump_format_
Dict forward_options_
Dict reverse_options_
Dict jacobian_options_
Dict der_options_
Function custom_jacobian_
casadi_int dump_count_ = 0
std::string name_
Name.
bool verbose_
Verbose printout.
bool print_time_
bool record_time_
bool regularity_check_
Errors are thrown when NaN is produced.
bool error_on_fail_
Throw an exception on failure?
Static Public Attributes
static const std::string meta_doc
A documentation string.
static std::map< std::string, Plugin > solvers_
Collection of solvers.
static const std::string infix_ = "conic"
Infix.
static std::map< std::string, ProtoFunction *(*)(DeserializingStream &)> deserialize_map
Protected Member Functions
QpoasesInterface (DeserializingStream &s)
Deserializing constructor.
void sdp_to_socp_init (SDPToSOCPMem &mem) const
SDP to SOCP conversion initialization.
void serialize (SerializingStream &s, const SDPToSOCPMem &m) const
void deserialize (DeserializingStream &s, SDPToSOCPMem &m)
void set_jac_sparsity (casadi_int oind, casadi_int iind, const Sparsity &sp)
Populate jac_sparsity_ and jac_sparsity_compact_ during initialization.
void initSingleton ()
void destroySingleton ()
template<class B >
B shared_from_this ()
Get a shared object from the current internal object.
template<class B >
const B shared_from_this () const
Get a shared object from the current internal object.
Static Protected Member Functions
static void qpoases_error (const std::string &module, casadi_int flag)
Throw error.
static std::string getErrorMessage (casadi_int flag)
Get qpOASES error message.
static bool from_BooleanType (qpOASES::BooleanType b)
static qpOASES::BooleanType to_BooleanType (bool b)
static std::string from_SubjectToStatus (qpOASES::SubjectToStatus b)
static qpOASES::SubjectToStatus to_SubjectToStatus (std::string b)
static std::string from_PrintLevel (qpOASES::PrintLevel b)
static qpOASES::PrintLevel to_PrintLevel (std::string b)
Protected Attributes
std::vector< bool > discrete_
Options.
bool print_problem_
Sparsity H_
Problem structure.
Sparsity A_
Sparsity Q_
Sparsity P_
casadi_int nx_
Number of decision variables.
casadi_int na_
The number of constraints (counting both equality and inequality) == A.size1()
casadi_int np_
The shape of psd constraint matrix.
casadi_int max_nWSR_
double max_cputime_
qpOASES::Options ops_
qpOASES::HessianType hess_
bool sparse_
bool schur_
casadi_int max_schur_
std::string linsol_plugin_
static const Options options_
Options.
const Options & get_options () const override
Options.
Member Typedef Documentation
Creator
typedef Conic*(* casadi::Conic::Creator) (const std::string &name, const std::map< std::string, Sparsity > &st) inherited
Definition at line 116 of file conic_impl.hpp.
RegFcn
typedef int(* casadi::PluginInterface< Conic >::RegFcn) (Plugin *plugin) inherited
Definition at line 72 of file plugin_interface.hpp.
Constructor & Destructor Documentation
QpoasesInterface() [1/3]
casadi::QpoasesInterface::QpoasesInterface () explicit
QpoasesInterface() [2/3]
casadi::QpoasesInterface::QpoasesInterface (const std::string & name, const std::map< std::string, Sparsity > & st) explicit
Definition at line 51 of file qpoases_interface.cpp.
     : Conic(name, st) {
     // Redirect output to CasADi
     static bool first_call = true;
     if (first_call) {
       qpOASES::setPrintf(qpoases_printf);
       first_call = false;
     }
   }
References qpoases_printf().
~QpoasesInterface()
casadi::QpoasesInterface::~QpoasesInterface () override
Definition at line 66 of file qpoases_interface.cpp.
{
     clear_mem();
   }
References casadi::ProtoFunction::clear_mem().
QpoasesInterface() [3/3]
casadi::QpoasesInterface::QpoasesInterface (DeserializingStream & s) explicit protected
Definition at line 940 of file qpoases_interface.cpp.
                                                            : Conic(s) {
     s.version("QpoasesInterface", 1);
     s.unpack("QpoasesInterface::max_nWSR", max_nWSR_);
     s.unpack("QpoasesInterface::max_cputime", max_cputime_);
     casadi_int hess;
     s.unpack("QpoasesInterface::hess", hess);
     hess_ = static_cast<qpOASES::HessianType>(hess);
     s.unpack("QpoasesInterface::sparse", sparse_);
     s.unpack("QpoasesInterface::schur", schur_);
     s.unpack("QpoasesInterface::max_schur", max_schur_);
     s.unpack("QpoasesInterface::linsol_plugin", linsol_plugin_);
     ops_.setToDefault();
     casadi_int print_level;
     s.unpack("QpoasesInterface::ops::printLevel", print_level);
     bool enableRamping;
     s.unpack("QpoasesInterface::ops::enableRamping", enableRamping);
     ops_.enableRamping = to_BooleanType(enableRamping);
     bool enableFarBounds;
     s.unpack("QpoasesInterface::ops::enableFarBounds", enableFarBounds);
     ops_.enableFarBounds = to_BooleanType(enableFarBounds);
     bool enableFlippingBounds;
     s.unpack("QpoasesInterface::ops::enableFlippingBounds", enableFlippingBounds);
     ops_.enableFlippingBounds = to_BooleanType(enableFlippingBounds);
     bool enableRegularisation;
     s.unpack("QpoasesInterface::ops::enableRegularisation", enableRegularisation);
     ops_.enableRegularisation = to_BooleanType(enableRegularisation);
     bool enableFullLITests;
     s.unpack("QpoasesInterface::ops::enableFullLITests", enableFullLITests);
     ops_.enableFullLITests = to_BooleanType(enableFullLITests);
     bool enableNZCTests;
     s.unpack("QpoasesInterface::ops::enableNZCTests", enableNZCTests);
     ops_.enableNZCTests = to_BooleanType(enableNZCTests);
     s.unpack("QpoasesInterface::ops::enableDriftCorrection", ops_.enableDriftCorrection);
     s.unpack("QpoasesInterface::ops::enableCholeskyRefactorisation",
       ops_.enableCholeskyRefactorisation);
     bool enableEqualities;
     s.unpack("QpoasesInterface::ops::enableEqualities", enableEqualities);
     ops_.enableEqualities = to_BooleanType(enableEqualities);
     s.unpack("QpoasesInterface::ops::terminationTolerance", ops_.terminationTolerance);
     s.unpack("QpoasesInterface::ops::boundTolerance", ops_.boundTolerance);
     s.unpack("QpoasesInterface::ops::boundRelaxation", ops_.boundRelaxation);
     s.unpack("QpoasesInterface::ops::epsNum", ops_.epsNum);
     s.unpack("QpoasesInterface::ops::epsDen", ops_.epsDen);
     s.unpack("QpoasesInterface::ops::maxPrimalJump", ops_.maxPrimalJump);
     s.unpack("QpoasesInterface::ops::maxDualJump", ops_.maxDualJump);
     s.unpack("QpoasesInterface::ops::initialRamping", ops_.initialRamping);
     s.unpack("QpoasesInterface::ops::finalRamping", ops_.finalRamping);
     s.unpack("QpoasesInterface::ops::initialFarBounds", ops_.initialFarBounds);
     s.unpack("QpoasesInterface::ops::growFarBounds", ops_.growFarBounds);
     std::string initialStatusBounds;
     s.unpack("QpoasesInterface::ops::initialStatusBounds", initialStatusBounds);
     ops_.initialStatusBounds = to_SubjectToStatus(initialStatusBounds);
     s.unpack("QpoasesInterface::ops::epsFlipping", ops_.epsFlipping);
     s.unpack("QpoasesInterface::ops::numRegularisationSteps", ops_.numRegularisationSteps);
     s.unpack("QpoasesInterface::ops::epsRegularisation", ops_.epsRegularisation);
     s.unpack("QpoasesInterface::ops::numRefinementSteps", ops_.numRefinementSteps);
     s.unpack("QpoasesInterface::ops::epsIterRef", ops_.epsIterRef);
     s.unpack("QpoasesInterface::ops::epsLITests", ops_.epsLITests);
     s.unpack("QpoasesInterface::ops::epsNZCTests", ops_.epsNZCTests);
     bool enableInertiaCorrection;
     s.unpack("QpoasesInterface::ops::enableInertiaCorrection", enableInertiaCorrection);
     ops_.enableInertiaCorrection = to_BooleanType(enableInertiaCorrection);
   }
References hess_, linsol_plugin_, max_cputime_, max_nWSR_, max_schur_, ops_, schur_, sparse_, to_BooleanType(), to_SubjectToStatus(), casadi::DeserializingStream::unpack(), and casadi::DeserializingStream::version().
Member Function Documentation
ad_weight()
double casadi::FunctionInternal::ad_weight () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_l5
Definition at line 3113 of file function_internal.cpp.
{
     // If reverse mode derivatives unavailable, use forward
     if (!enable_reverse_) return 0;
     // If forward mode derivatives unavailable, use reverse
     if (!enable_forward_ && !enable_fd_) return 1;
     // Use the (potentially user set) option
     return ad_weight_;
   }
References casadi::FunctionInternal::ad_weight_, casadi::FunctionInternal::enable_fd_, casadi::FunctionInternal::enable_forward_, and casadi::FunctionInternal::enable_reverse_.
Referenced by casadi::FunctionInternal::adjViaJac(), casadi::Function::expand(), casadi::FunctionInternal::fwdViaJac(), casadi::FunctionInternal::get_partition(), casadi::FunctionInternal::wrap(), and casadi::FunctionInternal::wrap_as_needed().
add_embedded()
void casadi::FunctionInternal::add_embedded (std::map< FunctionInternal *, Function > & all_fun, const Function & dep, casadi_int max_depth) const inherited
Definition at line 3544 of file function_internal.cpp.
{
     // Add, if not already in graph and not null
     if (!dep.is_null() && all_fun.find(dep.get()) == all_fun.end()) {
       // Add to map
       all_fun[dep.get()] = dep;
       // Also add its dependencies
       if (max_depth > 0) dep->find(all_fun, max_depth - 1);
     }
   }
References casadi::FunctionInternal::find(), casadi::Function::get(), and casadi::SharedObject::is_null().
Referenced by casadi::MXFunction::find(), and casadi::Switch::find().
adjViaJac()
bool casadi::FunctionInternal::adjViaJac (casadi_int nadj) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_nc
Definition at line 2848 of file function_internal.cpp.
{
     if (!enable_reverse_) return true;
     if (jac_penalty_==-1) return false;
     // Heuristic 1: Jac calculated via reverse mode likely cheaper
     if (jac_penalty_*static_cast<double>(nnz_out())<nadj) return true;
     // Heuristic 2: Jac calculated via forward mode likely cheaper
     double w = ad_weight();
     if ((enable_forward_ || enable_fd_) &&
         jac_penalty_*w*static_cast<double>(nnz_in())<(1-w)*static_cast<double>(nadj))
       return true; // NOLINT
     return false;
   }
References casadi::FunctionInternal::ad_weight(), casadi::FunctionInternal::enable_fd_, casadi::FunctionInternal::enable_forward_, casadi::FunctionInternal::enable_reverse_, casadi::FunctionInternal::jac_penalty_, casadi::FunctionInternal::nnz_in(), and casadi::FunctionInternal::nnz_out().
Referenced by casadi::FunctionInternal::call_reverse().
all_scalar()
bool casadi::FunctionInternal::all_scalar () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mi
Definition at line 3574 of file function_internal.cpp.
{
     // Check inputs
     for (casadi_int i=0; i<n_in_; ++i) {
       if (!sparsity_in_[i].is_scalar()) return false;
     }
     // Check outputs
     for (casadi_int i=0; i<n_out_; ++i) {
       if (!sparsity_out_[i].is_scalar()) return false;
     }
     // All are scalar
     return true;
   }
References casadi::FunctionInternal::n_in_, casadi::FunctionInternal::n_out_, casadi::FunctionInternal::sparsity_in_, and casadi::FunctionInternal::sparsity_out_.
Referenced by casadi::FunctionInternal::call().
alloc()
void casadi::FunctionInternal::alloc (const Function & f, bool persistent = false, int num_threads = 1) inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_n8
Definition at line 2806 of file function_internal.cpp.
{
     if (f.is_null()) return;
     size_t sz_arg, sz_res, sz_iw, sz_w;
     f.sz_work(sz_arg, sz_res, sz_iw, sz_w);
     alloc_arg(sz_arg*num_threads, persistent);
     alloc_res(sz_res*num_threads, persistent);
     alloc_iw(sz_iw*num_threads, persistent);
     alloc_w(sz_w*num_threads, persistent);
   }
References casadi::FunctionInternal::alloc_arg(), casadi::FunctionInternal::alloc_iw(), casadi::FunctionInternal::alloc_res(), casadi::FunctionInternal::alloc_w(), casadi::SharedObject::is_null(), casadi::FunctionInternal::sz_arg(), casadi::FunctionInternal::sz_iw(), casadi::FunctionInternal::sz_res(), casadi::FunctionInternal::sz_w(), and casadi::Function::sz_work().
Referenced by casadi::OracleFunction::finalize(), casadi::KinsolInterface::get_jtimes(), casadi::FiniteDiff::init(), casadi::Nlpsol::init(), casadi::Rootfinder::init(), casadi::Switch::init(), casadi::Feasiblesqpmethod::init(), casadi::ImplicitToNlp::init(), casadi::QpToNlp::init(), casadi::Qrsqp::init(), casadi::Scpgen::init(), and casadi::Sqpmethod::init().
alloc_arg()
void casadi::FunctionInternal::alloc_arg (size_t sz_arg, bool persistent = false) inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_n4
Definition at line 2774 of file function_internal.cpp.
{
     if (persistent) {
       sz_arg_per_ += sz_arg;
     } else {
       sz_arg_tmp_ = std::max(sz_arg_tmp_, sz_arg);
     }
   }
References casadi::FunctionInternal::sz_arg().
Referenced by casadi::FunctionInternal::alloc(), casadi::External::init(), casadi::FunctionInternal::init(), casadi::Map::init(), casadi::OmpMap::init(), casadi::ThreadMap::init(), casadi::MapSum::init(), casadi::MXFunction::init(), casadi::Nlpsol::init(), casadi::HighsInterface::init(), casadi::HpipmInterface::init(), casadi::BSplineInterpolant::init(), and casadi::Qrqp::init().
alloc_iw()
void casadi::FunctionInternal::alloc_iw (size_t sz_iw, bool persistent = false) inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_n6
Definition at line 2790 of file function_internal.cpp.
{
     if (persistent) {
       sz_iw_per_ += sz_iw;
     } else {
       sz_iw_tmp_ = std::max(sz_iw_tmp_, sz_iw);
     }
   }
References casadi::FunctionInternal::sz_iw().
Referenced by casadi::FunctionInternal::alloc(), casadi::External::init(), casadi::FmuFunction::init(), casadi::Interpolant::init(), casadi::Map::init(), casadi::OmpMap::init(), casadi::ThreadMap::init(), casadi::MapSum::init(), casadi::MXFunction::init(), casadi::Nlpsol::init(), casadi::Blocksqp::init(), casadi::GurobiInterface::init(), casadi::HighsInterface::init(), casadi::HpipmInterface::init(), casadi::IpoptInterface::init(), casadi::OoqpInterface::init(), casadi::SlicotDple::init(), casadi::SlicotExpm::init(), casadi::SundialsInterface::init(), casadi::BSplineInterpolant::init(), casadi::Feasiblesqpmethod::init(), casadi::Ipqp::init(), casadi::LinearInterpolant::init(), casadi::LinearInterpolantJac::init(), casadi::Qrqp::init(), and casadi::Sqpmethod::init().
alloc_mem()
void* casadi::QpoasesInterface::alloc_mem () const inline override virtual
Reimplemented from casadi::ProtoFunction.
Definition at line 132 of file qpoases_interface.hpp.
 { return new QpoasesMemory();}
alloc_res()
void casadi::FunctionInternal::alloc_res (size_t sz_res, bool persistent = false) inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_n5
Definition at line 2782 of file function_internal.cpp.
{
     if (persistent) {
       sz_res_per_ += sz_res;
     } else {
       sz_res_tmp_ = std::max(sz_res_tmp_, sz_res);
     }
   }
References casadi::FunctionInternal::sz_res().
Referenced by casadi::FunctionInternal::alloc(), casadi::External::init(), casadi::FiniteDiff::init(), casadi::FunctionInternal::init(), casadi::Map::init(), casadi::OmpMap::init(), casadi::ThreadMap::init(), casadi::MapSum::init(), casadi::MXFunction::init(), casadi::Nlpsol::init(), casadi::Blocksqp::init(), casadi::HighsInterface::init(), casadi::HpipmInterface::init(), casadi::BSplineInterpolant::init(), and casadi::Qrqp::init().
alloc_w()
void casadi::FunctionInternal::alloc_w (size_t sz_w, bool persistent = false) inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_n7
Definition at line 2798 of file function_internal.cpp.
{
     if (persistent) {
       sz_w_per_ += sz_w;
     } else {
       sz_w_tmp_ = std::max(sz_w_tmp_, sz_w);
     }
   }
References casadi::FunctionInternal::sz_w().
Referenced by casadi::FunctionInternal::alloc(), casadi::External::init(), casadi::FiniteDiff::init(), casadi::FmuFunction::init(), casadi::Integrator::init(), casadi::FixedStepIntegrator::init(), casadi::Interpolant::init(), casadi::JitFunction::init(), casadi::Map::init(), casadi::OmpMap::init(), casadi::ThreadMap::init(), casadi::MapSum::init(), casadi::MXFunction::init(), casadi::Nlpsol::init(), casadi::Rootfinder::init(), casadi::Switch::init(), casadi::Blocksqp::init(), casadi::BonminInterface::init(), casadi::CbcInterface::init(), casadi::ClpInterface::init(), casadi::CplexInterface::init(), casadi::GurobiInterface::init(), casadi::HighsInterface::init(), casadi::HpipmInterface::init(), casadi::IpoptInterface::init(), casadi::KnitroInterface::init(), casadi::OoqpInterface::init(), casadi::OsqpInterface::init(), casadi::ProxqpInterface::init(), init(), casadi::SlicotDple::init(), casadi::SlicotExpm::init(), casadi::SnoptInterface::init(), casadi::CvodesInterface::init(), casadi::IdasInterface::init(), casadi::KinsolInterface::init(), casadi::SundialsInterface::init(), casadi::SuperscsInterface::init(), casadi::WorhpInterface::init(), casadi::BSplineInterpolant::init(), casadi::FastNewton::init(), casadi::Feasiblesqpmethod::init(), casadi::ImplicitToNlp::init(), casadi::Ipqp::init(), casadi::LinearInterpolant::init(), casadi::LinearInterpolantJac::init(), casadi::Newton::init(), casadi::QpToNlp::init(), casadi::Qrqp::init(), casadi::Qrsqp::init(), casadi::Scpgen::init(), and casadi::Sqpmethod::init().
cache()
Dict casadi::FunctionInternal::cache () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_26g
Definition at line 950 of file function_internal.cpp.
{
     // Return value
     Dict ret;
     // Add all Function instances that haven't been deleted
     for (auto&& cf : cache_) {
       if (cf.second.alive()) {
         // Get the name of the key
         std::string s = cf.first;
         casadi_assert_dev(s.size() > 0);
         // Replace ':' with '_'
         std::replace(s.begin(), s.end(), ':', '_');
         // Remove trailing underscore, if any
         if (s.back() == '_') s.resize(s.size() - 1);
         // Add entry to function return
         ret[s] = shared_cast<Function>(cf.second.shared());
       }
     }
     return ret;
   }
References casadi::FunctionInternal::cache_.
call()
template<typename M > void casadi::FunctionInternal::call (const std::vector< M > & arg, std::vector< M > & res, bool always_inline, bool never_inline) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kh
Definition at line 1475 of file function_internal.hpp.
{
     // If all inputs are scalar ...
     if (all_scalar()) {
       // ... and some arguments are matrix-valued with matching dimensions ...
       bool matrix_call = false;
       std::pair<casadi_int, casadi_int> sz;
       for (auto&& a : arg) {
         if (!a.is_scalar() && !a.is_empty()) {
           if (!matrix_call) {
             // Matrix call
             matrix_call = true;
             sz = a.size();
           } else if (a.size()!=sz) {
             // Not same dimensions
             matrix_call = false;
             break;
           }
         }
       }
       // ... then, call multiple times
       if (matrix_call) {
         // Start with zeros
         res.resize(n_out_);
         M z = M::zeros(sz);
         for (auto&& a : res) a = z;
         // Call multiple times
         std::vector<M> arg1 = arg, res1;
         for (casadi_int c=0; c<sz.second; ++c) {
           for (casadi_int r=0; r<sz.first; ++r) {
             // Get scalar arguments
             for (casadi_int i=0; i<arg.size(); ++i) {
               if (arg[i].size()==sz) arg1[i] = arg[i](r, c);
             }
             // Call recursively with scalar arguments
             call(arg1, res1, always_inline, never_inline);
             // Get results
             casadi_assert_dev(res.size() == res1.size());
             for (casadi_int i=0; i<res.size(); ++i) res[i](r, c) = res1[i];
           }
         }
         // All elements assigned
         return;
       }
     }
     // Check if inputs need to be replaced
     casadi_int npar = 1;
     if (!matching_arg(arg, npar)) {
       return call(replace_arg(arg, npar), res, always_inline, never_inline);
     }
     // Call the type-specific method
     call_gen(arg, res, npar, always_inline, never_inline);
   }
References casadi::FunctionInternal::all_scalar(), casadi::FunctionInternal::call_gen(), casadi::FunctionInternal::matching_arg(), casadi::FunctionInternal::n_out_, and casadi::FunctionInternal::replace_arg().
call_forward() [1/2]
void casadi::FunctionInternal::call_forward (const std::vector< MX > & arg, const std::vector< MX > & res, const std::vector< std::vector< MX > > & fseed, std::vector< std::vector< MX > > & fsens, bool always_inline, bool never_inline) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ku
Definition at line 2868 of file function_internal.cpp.
{
     casadi_assert(!(always_inline && never_inline), "Inconsistent options");
     casadi_assert(!always_inline, "Class " + class_name() +
                           " cannot be inlined in an MX expression");
     // Derivative information must be available
     casadi_assert(has_derivative(),
                           "Derivatives cannot be calculated for " + name_);
     // Number of directional derivatives
     casadi_int nfwd = fseed.size();
     fsens.resize(nfwd);
     // Quick return if no seeds
     if (nfwd==0) return;
     // Check if seeds need to have dimensions corrected
     casadi_int npar = 1;
     for (auto&& r : fseed) {
       if (!matching_arg(r, npar)) {
         return FunctionInternal::call_forward(arg, res, replace_fseed(fseed, npar),
                                             fsens, always_inline, never_inline);
       }
     }
     // Calculating full Jacobian and then multiplying
     if (fwdViaJac(nfwd)) {
       // Multiply the Jacobian from the right
       std::vector<MX> darg = arg;
       darg.insert(darg.end(), res.begin(), res.end());
       std::vector<MX> J = jacobian()(darg);
       // Join forward seeds
       std::vector<MX> v(nfwd), all_fseed(n_in_);
       for (size_t i = 0; i < n_in_; ++i) {
         for (size_t d = 0; d < nfwd; ++d) v[d] = vec(fseed.at(d).at(i));
         all_fseed[i] = horzcat(v);
       }
       // Calculate forward sensitivities
       std::vector<MX> all_fsens(n_out_);
       std::vector<MX>::const_iterator J_it = J.begin();
       for (size_t oind = 0; oind < n_out_; ++oind) {
         for (size_t iind = 0; iind < n_in_; ++iind) {
           // Add contribution
           MX a = mtimes(*J_it++, all_fseed[iind]);
           all_fsens[oind] = all_fsens[oind].is_empty(true) ? a : all_fsens[oind] + a;
         }
       }
       // Split forward sensitivities
       for (size_t d = 0; d < nfwd; ++d) fsens[d].resize(n_out_);
       for (size_t i = 0; i < n_out_; ++i) {
         v = horzsplit(all_fsens[i]);
         casadi_assert_dev(v.size() == nfwd);
         for (size_t d = 0; d < nfwd; ++d) fsens[d][i] = reshape(v[d], size_out(i));
       }
     } else {
       // Evaluate in batches
       casadi_assert_dev(enable_forward_ || enable_fd_);
       casadi_int max_nfwd = max_num_dir_;
       if (!enable_fd_) {
         while (!has_forward(max_nfwd)) max_nfwd/=2;
       }
       casadi_int offset = 0;
       while (offset<nfwd) {
         // Number of derivatives, in this batch
         casadi_int nfwd_batch = std::min(nfwd-offset, max_nfwd);
         // All inputs and seeds
         std::vector<MX> darg;
         darg.reserve(n_in_ + n_out_ + n_in_);
         darg.insert(darg.end(), arg.begin(), arg.end());
         darg.insert(darg.end(), res.begin(), res.end());
         std::vector<MX> v(nfwd_batch);
         for (casadi_int i=0; i<n_in_; ++i) {
           for (casadi_int d=0; d<nfwd_batch; ++d) v[d] = fseed[offset+d][i];
           darg.push_back(horzcat(v));
         }
         // Create the evaluation node
         Function dfcn = self().forward(nfwd_batch);
         std::vector<MX> x = dfcn(darg);
         casadi_assert_dev(x.size()==n_out_);
         // Retrieve sensitivities
         for (casadi_int d=0; d<nfwd_batch; ++d) fsens[offset+d].resize(n_out_);
         for (casadi_int i=0; i<n_out_; ++i) {
           if (size2_out(i)>0) {
             v = horzsplit(x[i], size2_out(i));
             casadi_assert_dev(v.size()==nfwd_batch);
           } else {
             v = std::vector<MX>(nfwd_batch, MX(size_out(i)));
           }
           for (casadi_int d=0; d<nfwd_batch; ++d) fsens[offset+d][i] = v[d];
         }
         // Update offset
         offset += nfwd_batch;
       }
     }
   }
References casadi::SharedObjectInternal::class_name(), casadi::FunctionInternal::enable_fd_, casadi::FunctionInternal::enable_forward_, casadi::FunctionInternal::forward(), casadi::FunctionInternal::fwdViaJac(), casadi::FunctionInternal::has_derivative(), casadi::FunctionInternal::has_forward(), casadi::FunctionInternal::jacobian(), casadi::FunctionInternal::matching_arg(), casadi::FunctionInternal::max_num_dir_, casadi::FunctionInternal::n_in_, casadi::FunctionInternal::n_out_, casadi::ProtoFunction::name_, casadi::FunctionInternal::replace_fseed(), casadi::FunctionInternal::size2_out(), and casadi::FunctionInternal::size_out().
Referenced by casadi::Rootfinder::ad_forward(), casadi::Call::ad_forward(), casadi::MXFunction::ad_forward(), casadi::XFunction< DerivedType, MatType, NodeType >::call_forward(), casadi::MX::forward(), casadi::Integrator::get_forward_dae(), and casadi::Scpgen::init().
call_forward() [2/2]
void casadi::FunctionInternal::call_forward (const std::vector< SX > & arg, const std::vector< SX > & res, const std::vector< std::vector< SX > > & fseed, std::vector< std::vector< SX > > & fsens, bool always_inline, bool never_inline) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ku
Definition at line 3087 of file function_internal.cpp.
{
     casadi_assert(!(always_inline && never_inline), "Inconsistent options");
     if (fseed.empty()) { // Quick return if no seeds
       fsens.clear();
       return;
     }
     casadi_error("'forward' (SX) not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
call_gen() [1/2]
void casadi::FunctionInternal::call_gen (const MXVector & arg, MXVector & res, casadi_int npar, bool always_inline, bool never_inline) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kg
Definition at line 3744 of file function_internal.cpp.
{
     if (npar==1) {
       eval_mx(arg, res, always_inline, never_inline);
     } else {
       // Split it up arguments
       std::vector<std::vector<MX>> v(npar, arg);
       std::vector<MX> t;
       for (int i=0; i<n_in_; ++i) {
         if (arg[i].size2()!=size2_in(i)) {
           t = horzsplit(arg[i], size2_in(i));
           casadi_assert_dev(t.size()==npar);
           for (int p=0; p<npar; ++p) v[p][i] = t[p];
         }
       }
       // Unroll the loop
       for (int p=0; p<npar; ++p) {
         eval_mx(v[p], t, always_inline, never_inline);
         v[p] = t;
       }
       // Concatenate results
       t.resize(npar);
       res.resize(n_out_);
       for (int i=0; i<n_out_; ++i) {
         for (int p=0; p<npar; ++p) t[p] = v[p][i];
         res[i] = horzcat(t);
       }
     }
   }
References casadi::FunctionInternal::eval_mx(), casadi::FunctionInternal::n_in_, casadi::FunctionInternal::n_out_, and casadi::FunctionInternal::size2_in().
Referenced by casadi::FunctionInternal::call().
call_gen() [2/2]
template<typename D > void casadi::FunctionInternal::call_gen (const std::vector< Matrix< D > > & arg, std::vector< Matrix< D > > & res, casadi_int npar, bool always_inline, bool never_inline) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kg
Definition at line 1579 of file function_internal.hpp.
{
     casadi_assert(!never_inline, "Call-nodes only possible in MX expressions");
     std::vector< Matrix<D> > arg2 = project_arg(arg, npar);
     // Which arguments require mapped evaluation
     std::vector<bool> mapped(n_in_);
     for (casadi_int i=0; i<n_in_; ++i) {
       mapped[i] = arg[i].size2()!=size2_in(i);
     }
     // Allocate results
     res.resize(n_out_);
     for (casadi_int i=0; i<n_out_; ++i) {
       if (!res[i].sparsity().is_stacked(sparsity_out(i), npar)) {
         res[i] = Matrix<D>::zeros(repmat(sparsity_out(i), 1, npar));
       }
     }
     // Allocate temporary memory if needed
     std::vector<casadi_int> iw_tmp(sz_iw());
     std::vector<D> w_tmp(sz_w());
     // Get pointers to input arguments
     std::vector<const D*> argp(sz_arg());
     for (casadi_int i=0; i<n_in_; ++i) argp[i]=get_ptr(arg2[i]);
     // Get pointers to output arguments
     std::vector<D*> resp(sz_res());
     for (casadi_int i=0; i<n_out_; ++i) resp[i]=get_ptr(res[i]);
     // For all parallel calls
     for (casadi_int p=0; p<npar; ++p) {
       // Call memory-less
       if (eval_gen(get_ptr(argp), get_ptr(resp),
                    get_ptr(iw_tmp), get_ptr(w_tmp), memory(0))) {
         if (error_on_fail_) casadi_error("Evaluation failed");
       }
       // Update offsets
       if (p==npar-1) break;
       for (casadi_int i=0; i<n_in_; ++i) if (mapped[i]) argp[i] += nnz_in(i);
       for (casadi_int i=0; i<n_out_; ++i) resp[i] += nnz_out(i);
     }
   }
References casadi::ProtoFunction::error_on_fail_, casadi::FunctionInternal::eval_gen(), casadi::get_ptr(), casadi::ProtoFunction::memory(), casadi::FunctionInternal::n_in_, casadi::FunctionInternal::n_out_, casadi::FunctionInternal::nnz_in(), casadi::FunctionInternal::nnz_out(), casadi::FunctionInternal::project_arg(), casadi::FunctionInternal::size2_in(), casadi::FunctionInternal::sparsity_out(), casadi::FunctionInternal::sz_arg(), casadi::FunctionInternal::sz_iw(), casadi::FunctionInternal::sz_res(), casadi::FunctionInternal::sz_w(), and casadi::GenericMatrix< Matrix< Scalar > >::zeros().
call_reverse() [1/2]
void casadi::FunctionInternal::call_reverse (const std::vector< MX > & arg, const std::vector< MX > & res, const std::vector< std::vector< MX > > & aseed, std::vector< std::vector< MX > > & asens, bool always_inline, bool never_inline) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kv
Definition at line 2973 of file function_internal.cpp.
{
     casadi_assert(!(always_inline && never_inline), "Inconsistent options");
     casadi_assert(!always_inline, "Class " + class_name() +
                           " cannot be inlined in an MX expression");
     // Derivative information must be available
     casadi_assert(has_derivative(),
                           "Derivatives cannot be calculated for " + name_);
     // Number of directional derivatives
     casadi_int nadj = aseed.size();
     asens.resize(nadj);
     // Quick return if no seeds
     if (nadj==0) return;
     // Check if seeds need to have dimensions corrected
     casadi_int npar = 1;
     for (auto&& r : aseed) {
       if (!matching_res(r, npar)) {
         return FunctionInternal::call_reverse(arg, res, replace_aseed(aseed, npar),
                                             asens, always_inline, never_inline);
       }
     }
     // Calculating full Jacobian and then multiplying likely cheaper
     if (adjViaJac(nadj)) {
       // Multiply the transposed Jacobian from the right
       std::vector<MX> darg = arg;
       darg.insert(darg.end(), res.begin(), res.end());
       std::vector<MX> J = jacobian()(darg);
       // Join adjoint seeds
       std::vector<MX> v(nadj), all_aseed(n_out_);
       for (size_t i = 0; i < n_out_; ++i) {
         for (size_t d = 0; d < nadj; ++d) v[d] = vec(aseed.at(d).at(i));
         all_aseed[i] = horzcat(v);
       }
       // Calculate adjoint sensitivities
       std::vector<MX> all_asens(n_in_);
       std::vector<MX>::const_iterator J_it = J.begin();
       for (size_t oind = 0; oind < n_out_; ++oind) {
         for (size_t iind = 0; iind < n_in_; ++iind) {
           // Add contribution
           MX a = mtimes((*J_it++).T(), all_aseed[oind]);
           all_asens[iind] = all_asens[iind].is_empty(true) ? a : all_asens[iind] + a;
         }
       }
       // Split adjoint sensitivities
       for (size_t d = 0; d < nadj; ++d) asens[d].resize(n_in_);
       for (size_t i = 0; i < n_in_; ++i) {
         v = horzsplit(all_asens[i]);
         casadi_assert_dev(v.size() == nadj);
         for (size_t d = 0; d < nadj; ++d) {
           if (asens[d][i].is_empty(true)) {
             asens[d][i] = reshape(v[d], size_in(i));
           } else {
             asens[d][i] += reshape(v[d], size_in(i));
           }
         }
       }
     } else {
       // Evaluate in batches
       casadi_assert_dev(enable_reverse_);
       casadi_int max_nadj = max_num_dir_;
       while (!has_reverse(max_nadj)) max_nadj/=2;
       casadi_int offset = 0;
       while (offset<nadj) {
         // Number of derivatives, in this batch
         casadi_int nadj_batch =  std::min(nadj-offset, max_nadj);
         // All inputs and seeds
         std::vector<MX> darg;
         darg.reserve(n_in_ + n_out_ + n_out_);
         darg.insert(darg.end(), arg.begin(), arg.end());
         darg.insert(darg.end(), res.begin(), res.end());
         std::vector<MX> v(nadj_batch);
         for (casadi_int i=0; i<n_out_; ++i) {
           for (casadi_int d=0; d<nadj_batch; ++d) v[d] = aseed[offset+d][i];
           darg.push_back(horzcat(v));
         }
         // Create the evaluation node
         Function dfcn = self().reverse(nadj_batch);
         std::vector<MX> x = dfcn(darg);
         casadi_assert_dev(x.size()==n_in_);
         // Retrieve sensitivities
         for (casadi_int d=0; d<nadj_batch; ++d) asens[offset+d].resize(n_in_);
         for (casadi_int i=0; i<n_in_; ++i) {
           if (size2_in(i)>0) {
             v = horzsplit(x[i], size2_in(i));
             casadi_assert_dev(v.size()==nadj_batch);
           } else {
             v = std::vector<MX>(nadj_batch, MX(size_in(i)));
           }
           for (casadi_int d=0; d<nadj_batch; ++d) {
             if (asens[offset+d][i].is_empty(true)) {
               asens[offset+d][i] = v[d];
             } else {
               asens[offset+d][i] += v[d];
             }
           }
         }
         // Update offset
         offset += nadj_batch;
       }
     }
   }
References casadi::FunctionInternal::adjViaJac(), casadi::SharedObjectInternal::class_name(), casadi::FunctionInternal::enable_reverse_, casadi::FunctionInternal::has_derivative(), casadi::FunctionInternal::has_reverse(), casadi::FunctionInternal::jacobian(), casadi::FunctionInternal::matching_res(), casadi::FunctionInternal::max_num_dir_, casadi::FunctionInternal::n_in_, casadi::FunctionInternal::n_out_, casadi::ProtoFunction::name_, casadi::FunctionInternal::replace_aseed(), casadi::FunctionInternal::reverse(), casadi::FunctionInternal::size2_in(), and casadi::FunctionInternal::size_in().
Referenced by casadi::Rootfinder::ad_reverse(), casadi::MXFunction::ad_reverse(), casadi::Call::ad_reverse(), casadi::XFunction< DerivedType, MatType, NodeType >::call_reverse(), casadi::Scpgen::init(), and casadi::MX::reverse().
call_reverse() [2/2]
void casadi::FunctionInternal::call_reverse (const std::vector< SX > & arg, const std::vector< SX > & res, const std::vector< std::vector< SX > > & aseed, std::vector< std::vector< SX > > & asens, bool always_inline, bool never_inline) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kv
Definition at line 3100 of file function_internal.cpp.
{
     casadi_assert(!(always_inline && never_inline), "Inconsistent options");
     if (aseed.empty()) { // Quick return if no seeds
       asens.clear();
       return;
     }
     casadi_error("'reverse' (SX) not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
change_option()
void casadi::FunctionInternal::change_option (const std::string & option_name, const GenericType & option_value) override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_k5
Reimplemented from casadi::ProtoFunction.
Reimplemented in casadi::MXFunction.
Definition at line 414 of file function_internal.cpp.
{
     if (option_name == "print_in") {
       print_in_ = option_value;
     } else if (option_name == "print_out") {
       print_out_ = option_value;
     } else if (option_name=="ad_weight") {
       ad_weight_ = option_value;
     } else if (option_name=="ad_weight_sp") {
       ad_weight_sp_ = option_value;
     } else if (option_name=="dump") {
       dump_ = option_value;
     } else if (option_name=="dump_in") {
       dump_in_ = option_value;
     } else if (option_name=="dump_out") {
       dump_out_ = option_value;
     } else if (option_name=="dump_dir") {
       dump_dir_ = option_value.to_string();
     } else if (option_name=="dump_format") {
       dump_format_ = option_value.to_string();
     } else {
       // Option not found - continue to base classes
       ProtoFunction::change_option(option_name, option_value);
     }
   }
References casadi::FunctionInternal::ad_weight_, casadi::FunctionInternal::ad_weight_sp_, casadi::ProtoFunction::change_option(), casadi::FunctionInternal::dump_, casadi::FunctionInternal::dump_dir_, casadi::FunctionInternal::dump_format_, casadi::FunctionInternal::dump_in_, casadi::FunctionInternal::dump_out_, casadi::FunctionInternal::print_in_, casadi::FunctionInternal::print_out_, and casadi::GenericType::to_string().
Referenced by casadi::MXFunction::change_option().
check_arg()
template<typename M > void casadi::FunctionInternal::check_arg (const std::vector< M > & arg, casadi_int & npar) const inherited
Raises errors.
Parameters
npar[in] normal usage: 1, disallow pararallel calls: -1
[out] npar max number of horizontal repetitions across all arguments (or -1)
Extra doc: https://github.com/casadi/casadi/wiki/L_ki
Definition at line 1626 of file function_internal.hpp.
{
     casadi_assert(arg.size()==n_in_, "Incorrect number of inputs: Expected "
                           + str(n_in_) + ", got " + str(arg.size()));
     for (casadi_int i=0; i<n_in_; ++i) {
       if (!check_mat(arg[i].sparsity(), sparsity_in(i), npar)) {
         // Dimensions
         std::string d_arg = str(arg[i].size1()) + "-by-" + str(arg[i].size2());
         std::string d_in = str(size1_in(i)) + "-by-" + str(size2_in(i));
         std::string e = "Input " + str(i) + " (" + name_in_[i] + ") has mismatching shape. "
                      "Got " + d_arg + ". Allowed dimensions, in general, are:\n"
                      " - The input dimension N-by-M (here " + d_in + ")\n"
                      " - A scalar, i.e. 1-by-1\n"
                      " - M-by-N if N=1 or M=1 (i.e. a transposed vector)\n"
                      " - N-by-M1 if K*M1=M for some K (argument repeated horizontally)\n";
         if (npar!=-1) {
           e += " - N-by-P*M, indicating evaluation with multiple arguments (P must be a "
                      "multiple of " + str(npar) + " for consistency with previous inputs)";
         }
         casadi_error(e);
       }
     }
   }
References casadi::FunctionInternal::check_mat(), casadi::FunctionInternal::n_in_, casadi::FunctionInternal::name_in_, casadi::FunctionInternal::size1_in(), casadi::FunctionInternal::size2_in(), casadi::FunctionInternal::sparsity_in(), and casadi::str().
Referenced by casadi::FunctionInternal::mapsum_mx(), and casadi::FunctionInternal::matching_arg().
check_inputs()
void casadi::Conic::check_inputs (const double * lbx, const double * ubx, const double * lba, const double * uba) const virtual inherited
Definition at line 472 of file conic.cpp.
{
     for (casadi_int i=0; i<nx_; ++i) {
       double lb = lbx ? lbx[i] : 0., ub = ubx ? ubx[i] : 0.;
       casadi_assert(lb <= ub && lb!=inf && ub!=-inf,
         "Ill-posed problem detected: "
         "LBX[" + str(i) + "] <= UBX[" + str(i) + "] was violated. "
         "Got LBX[" + str(i) + "]=" + str(lb) + " and UBX[" + str(i) + "] = " + str(ub) + ".");
     }
     for (casadi_int i=0; i<na_; ++i) {
       double lb = lba ? lba[i] : 0., ub = uba ? uba[i] : 0.;
       casadi_assert(lb <= ub && lb!=inf && ub!=-inf,
         "Ill-posed problem detected: "
         "LBA[" + str(i) + "] <= UBA[" + str(i) + "] was violated. "
         "Got LBA[" + str(i) + "] = " + str(lb) + " and UBA[" + str(i) + "] = " + str(ub) + ".");
     }
   }
References casadi::inf, casadi::Conic::na_, casadi::Conic::nx_, and casadi::str().
Referenced by casadi::Conic::eval(), casadi::SqicInterface::evaluate(), and casadi::GurobiInterface::solve().
check_mat()
bool casadi::FunctionInternal::check_mat (const Sparsity & arg, const Sparsity & inp, casadi_int & npar) static inherited
Helper function
Parameters
npar[in] normal usage: 1, disallow pararallel calls: -1
npar[out] required number of parallel calls (or -1)
Definition at line 3294 of file function_internal.cpp.
{
     // Matching dimensions
     if (arg.size()==inp.size()) return true;
     // Calling with empty matrix - set all to zero
     if (arg.is_empty()) return true;
     // Calling with a scalar - set all
     if (arg.is_scalar()) return true;
     // Vectors that are transposes of each other
     if (arg.is_vector() && inp.size()==std::make_pair(arg.size2(), arg.size1())) return true;
     // Horizontal repmat
     if (arg.size1()==inp.size1() && arg.size2()>0 && inp.size2()>0
         && inp.size2()%arg.size2()==0) return true;
     if (npar==-1) return false;
     // Evaluate with multiple arguments
     if (arg.size1()==inp.size1() && arg.size2()>0 && inp.size2()>0
         && arg.size2()%(npar*inp.size2())==0) {
       npar *= arg.size2()/(npar*inp.size2());
       return true;
     }
     // No match
     return false;
   }
References casadi::Sparsity::is_empty(), casadi::Sparsity::is_scalar(), casadi::Sparsity::is_vector(), casadi::Sparsity::size(), casadi::Sparsity::size1(), and casadi::Sparsity::size2().
Referenced by casadi::FunctionInternal::check_arg(), casadi::FunctionInternal::check_res(), and casadi::FunctionInternal::mapsum_mx().
check_res()
template<typename M > void casadi::FunctionInternal::check_res (const std::vector< M > & res, casadi_int & npar) const inherited
Raises errors.
Parameters
npar[in] normal usage: 1, disallow pararallel calls: -1
[out] npar max number of horizontal repetitions across all arguments (or -1)
Extra doc: https://github.com/casadi/casadi/wiki/L_kj
Definition at line 1650 of file function_internal.hpp.
{
     casadi_assert(res.size()==n_out_, "Incorrect number of outputs: Expected "
                           + str(n_out_) + ", got " + str(res.size()));
     for (casadi_int i=0; i<n_out_; ++i) {
       casadi_assert(check_mat(res[i].sparsity(), sparsity_out(i), npar),
                     "Output " + str(i) + " (" + name_out_[i] + ") has mismatching shape. "
                     "Expected " + str(size_out(i)) + ", got " + str(res[i].size()));
     }
   }
References casadi::FunctionInternal::check_mat(), casadi::FunctionInternal::n_out_, casadi::FunctionInternal::name_out_, casadi::FunctionInternal::size_out(), casadi::FunctionInternal::sparsity_out(), and casadi::str().
Referenced by casadi::FunctionInternal::matching_res().
checkout()
int casadi::ProtoFunction::checkout () const inherited
Definition at line 3497 of file function_internal.cpp.
{
 #ifdef CASADI_WITH_THREAD
     std::lock_guard<std::mutex> lock(mtx_);
 #endif //CASADI_WITH_THREAD
     if (unused_.empty()) {
       // Allocate a new memory object
       void* m = alloc_mem();
       mem_.push_back(m);
       if (init_mem(m)) {
         casadi_error("Failed to create or initialize memory object");
       }
       return static_cast<int>(mem_.size()) - 1;
     } else {
       // Use an unused memory object
       int m = unused_.top();
       unused_.pop();
       return m;
     }
   }
References casadi::ProtoFunction::alloc_mem(), and casadi::ProtoFunction::init_mem().
Referenced by casadi::ProtoFunction::finalize(), and casadi::FunctionBuffer::FunctionBuffer().
class_name()
std::string casadi::QpoasesInterface::class_name () const inline override virtual
Implements casadi::SharedObjectInternal.
Definition at line 120 of file qpoases_interface.hpp.
 { return "QpoasesInterface";}
clear_mem()
void casadi::ProtoFunction::clear_mem () inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_jq
Definition at line 3389 of file function_internal.cpp.
{
     for (auto&& i : mem_) {
       if (i!=nullptr) free_mem(i);
     }
     mem_.clear();
   }
References casadi::ProtoFunction::free_mem().
Referenced by casadi::AmplInterface::~AmplInterface(), casadi::Blocksqp::~Blocksqp(), casadi::BonminInterface::~BonminInterface(), casadi::BSplineInterpolant::~BSplineInterpolant(), casadi::CallbackInternal::~CallbackInternal(), casadi::CbcInterface::~CbcInterface(), casadi::ClpInterface::~ClpInterface(), casadi::CplexInterface::~CplexInterface(), casadi::CsparseInterface::~CsparseInterface(), casadi::CvodesInterface::~CvodesInterface(), casadi::External::~External(), casadi::FastNewton::~FastNewton(), casadi::Feasiblesqpmethod::~Feasiblesqpmethod(), casadi::FiniteDiff::~FiniteDiff(), casadi::FixedStepIntegrator::~FixedStepIntegrator(), casadi::FmuFunction::~FmuFunction(), casadi::GurobiInterface::~GurobiInterface(), casadi::HighsInterface::~HighsInterface(), casadi::HpipmInterface::~HpipmInterface(), casadi::HpmpcInterface::~HpmpcInterface(), casadi::IdasInterface::~IdasInterface(), casadi::ImplicitToNlp::~ImplicitToNlp(), casadi::IpoptInterface::~IpoptInterface(), casadi::Ipqp::~Ipqp(), casadi::JitFunction::~JitFunction(), casadi::KinsolInterface::~KinsolInterface(), casadi::KnitroInterface::~KnitroInterface(), casadi::LapackLu::~LapackLu(), casadi::LapackQr::~LapackQr(), casadi::LinearInterpolant::~LinearInterpolant(), casadi::LinearInterpolantJac::~LinearInterpolantJac(), casadi::LinsolLdl::~LinsolLdl(), casadi::LinsolQr::~LinsolQr(), casadi::LinsolTridiag::~LinsolTridiag(), casadi::Lsqr::~Lsqr(), casadi::Ma27Interface::~Ma27Interface(), casadi::Map::~Map(), casadi::MapSum::~MapSum(), casadi::MumpsInterface::~MumpsInterface(), casadi::MXFunction::~MXFunction(), casadi::Newton::~Newton(), casadi::Nlpsol::~Nlpsol(), casadi::OmpMap::~OmpMap(), casadi::OoqpInterface::~OoqpInterface(), casadi::OsqpInterface::~OsqpInterface(), casadi::ProxqpInterface::~ProxqpInterface(), ~QpoasesInterface(), casadi::QpToNlp::~QpToNlp(), casadi::Qrqp::~Qrqp(), casadi::Qrsqp::~Qrsqp(), casadi::Scpgen::~Scpgen(), casadi::SlicotDple::~SlicotDple(), casadi::SlicotExpm::~SlicotExpm(), casadi::SnoptInterface::~SnoptInterface(), casadi::Sqpmethod::~Sqpmethod(), casadi::SuperscsInterface::~SuperscsInterface(), casadi::Switch::~Switch(), casadi::SymbolicQr::~SymbolicQr(), casadi::ThreadMap::~ThreadMap(), and casadi::WorhpInterface::~WorhpInterface().
codegen()
void casadi::FunctionInternal::codegen (CodeGenerator & g, const std::string & fname) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lm
Definition at line 2275 of file function_internal.cpp.
{
     // Define function
     g << "/* " << definition() << " */\n";
     g << "static " << signature(fname) << " {\n";
     // Reset local variables, flush buffer
     g.flush(g.body);
     g.scope_enter();
     // Generate function body (to buffer)
     codegen_body(g);
     g.scope_exit();
     // Finalize the function
     g << "return 0;\n";
     g << "}\n\n";
     // Flush to function body
     g.flush(g.body);
   }
References casadi::CodeGenerator::body, casadi::FunctionInternal::codegen_body(), casadi::FunctionInternal::definition(), casadi::CodeGenerator::flush(), casadi::CodeGenerator::scope_enter(), casadi::CodeGenerator::scope_exit(), and casadi::FunctionInternal::signature().
Referenced by casadi::CodeGenerator::add_dependency().
codegen_alloc_mem()
void casadi::FunctionInternal::codegen_alloc_mem (CodeGenerator & g) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lt
Reimplemented in casadi::External.
Definition at line 2307 of file function_internal.cpp.
{
     bool needs_mem = !codegen_mem_type().empty();
     if (needs_mem) {
     std::string name = codegen_name(g, false);
     std::string mem_counter = g.shorthand(name + "_mem_counter");
     g << "return " + mem_counter + "++;\n";
     }
   }
References casadi::FunctionInternal::codegen_mem_type(), casadi::FunctionInternal::codegen_name(), and casadi::CodeGenerator::shorthand().
Referenced by casadi::CodeGenerator::add_dependency().
codegen_body()
void casadi::FunctionInternal::codegen_body (CodeGenerator & g) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_m0
Reimplemented in casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >, casadi::Sqpmethod, casadi::Qrqp, casadi::LinearInterpolantJac, casadi::LinearInterpolant, casadi::Feasiblesqpmethod, casadi::FastNewton, casadi::BSplineInterpolant, casadi::OsqpInterface, casadi::HpipmInterface, casadi::HighsInterface, casadi::SXFunction, casadi::Switch, casadi::MXFunction, casadi::MapSum, casadi::ThreadMap, casadi::OmpMap, casadi::Map, casadi::JitFunction, casadi::FiniteDiff, and casadi::External.
Definition at line 2687 of file function_internal.cpp.
{
     casadi_warning("The function \"" + name_ + "\", which is of type \""
                    + class_name() + "\" cannot be code generated. The generation "
                    "will proceed, but compilation of the code will not be possible.");
     g << "#error Code generation not supported for " << class_name() << "\n";
   }
References casadi::SharedObjectInternal::class_name(), and casadi::ProtoFunction::name_.
Referenced by casadi::FunctionInternal::codegen(), and casadi::BSplineInterpolant::codegen_body().
codegen_checkout()
void casadi::FunctionInternal::codegen_checkout (CodeGenerator & g) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lw
Reimplemented in casadi::External.
Definition at line 2316 of file function_internal.cpp.
{
     std::string name = codegen_name(g, false);
     std::string stack_counter = g.shorthand(name + "_unused_stack_counter");
     std::string stack = g.shorthand(name + "_unused_stack");
     std::string mem_counter = g.shorthand(name + "_mem_counter");
     std::string mem_array = g.shorthand(name + "_mem");
     std::string alloc_mem = g.shorthand(name + "_alloc_mem");
     std::string init_mem = g.shorthand(name + "_init_mem");
     g.auxiliaries << "static int " << mem_counter  << " = 0;\n";
     g.auxiliaries << "static int " << stack_counter  << " = -1;\n";
     g.auxiliaries << "static int " << stack << "[CASADI_MAX_NUM_THREADS];\n";
     g.auxiliaries << "static " << codegen_mem_type() <<
                " " << mem_array << "[CASADI_MAX_NUM_THREADS];\n\n";
     g << "int mid;\n";
     g << "if (" << stack_counter << ">=0) {\n";
     g << "return " << stack << "[" << stack_counter << "--];\n";
     g << "} else {\n";
     g << "if (" << mem_counter << "==CASADI_MAX_NUM_THREADS) return -1;\n";
     g << "mid = " << alloc_mem << "();\n";
     g << "if (mid<0) return -1;\n";
     g << "if(" << init_mem << "(mid)) return -1;\n";
     g << "return mid;\n";
     g << "}\n";
   }
References casadi::ProtoFunction::alloc_mem(), casadi::CodeGenerator::auxiliaries, casadi::FunctionInternal::codegen_mem_type(), casadi::FunctionInternal::codegen_name(), casadi::ProtoFunction::init_mem(), and casadi::CodeGenerator::shorthand().
Referenced by casadi::CodeGenerator::add_dependency().
codegen_declarations()
void casadi::FunctionInternal::codegen_declarations (CodeGenerator & g) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lz
Reimplemented in casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >, casadi::Sqpmethod, casadi::Feasiblesqpmethod, casadi::FastNewton, casadi::BSplineInterpolant, casadi::SXFunction, casadi::Switch, casadi::MXFunction, casadi::MapSum, casadi::Map, casadi::FiniteDiff, and casadi::External.
Definition at line 2683 of file function_internal.cpp.
{
     // Nothing to declare
   }
Referenced by casadi::CodeGenerator::add_dependency(), and casadi::BSplineInterpolant::codegen_declarations().
codegen_decref()
virtual void casadi::FunctionInternal::codegen_decref (CodeGenerator & g) const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ls
Reimplemented in casadi::MXFunction, and casadi::External.
Definition at line 815 of file function_internal.hpp.
 {}
Referenced by casadi::CodeGenerator::add_dependency(), and casadi::FunctionInternal::codegen_meta().
codegen_free_mem()
virtual void casadi::FunctionInternal::codegen_free_mem (CodeGenerator & g) const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lv
Reimplemented in casadi::OsqpInterface, casadi::HighsInterface, and casadi::External.
Definition at line 830 of file function_internal.hpp.
 {}
Referenced by casadi::CodeGenerator::add_dependency().
codegen_incref()
virtual void casadi::FunctionInternal::codegen_incref (CodeGenerator & g) const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lr
Reimplemented in casadi::MXFunction, and casadi::External.
Definition at line 810 of file function_internal.hpp.
 {}
Referenced by casadi::CodeGenerator::add_dependency(), and casadi::FunctionInternal::codegen_meta().
codegen_init_mem()
void casadi::FunctionInternal::codegen_init_mem (CodeGenerator & g) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lu
Reimplemented in casadi::OsqpInterface, casadi::HighsInterface, and casadi::External.
Definition at line 2303 of file function_internal.cpp.
{
     g << "return 0;\n";
   }
Referenced by casadi::CodeGenerator::add_dependency().
codegen_mem()
std::string casadi::FunctionInternal::codegen_mem (CodeGenerator & g, const std::string & index = "mem") const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lq
Definition at line 2677 of file function_internal.cpp.
{
     std::string name = codegen_name(g, false);
     std::string mem_array = g.shorthand(name + "_mem");
     return mem_array+"[" + index + "]";
   }
References casadi::FunctionInternal::codegen_name(), and casadi::CodeGenerator::shorthand().
Referenced by casadi::HighsInterface::codegen_body(), casadi::OsqpInterface::codegen_body(), casadi::HighsInterface::codegen_free_mem(), casadi::OsqpInterface::codegen_free_mem(), casadi::HighsInterface::codegen_init_mem(), and casadi::OsqpInterface::codegen_init_mem().
codegen_mem_type()
virtual std::string casadi::FunctionInternal::codegen_mem_type () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_m1
Reimplemented in casadi::OsqpInterface, casadi::HighsInterface, and casadi::External.
Definition at line 860 of file function_internal.hpp.
 { return ""; }
Referenced by casadi::CodeGenerator::add_dependency(), casadi::FunctionInternal::codegen_alloc_mem(), casadi::FunctionInternal::codegen_checkout(), casadi::FunctionInternal::codegen_meta(), and casadi::CodeGenerator::operator()().
codegen_meta()
void casadi::FunctionInternal::codegen_meta (CodeGenerator & g) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ln
Definition at line 2353 of file function_internal.cpp.
{
     bool needs_mem = !codegen_mem_type().empty();
     g << g.declare("int " + name_ + "_alloc_mem(void)") << " {\n";
     if (needs_mem) {
       g << "return " << codegen_name(g) << "_alloc_mem();\n";
     } else {
       g << "return 0;\n";
     }
     g << "}\n\n";
     g << g.declare("int " + name_ + "_init_mem(int mem)") << " {\n";
     if (needs_mem) {
       g << "return " << codegen_name(g) << "_init_mem(mem);\n";
     } else {
       g << "return 0;\n";
     }
     g << "}\n\n";
     g << g.declare("void " + name_ + "_free_mem(int mem)") << " {\n";
     if (needs_mem) {
       g << codegen_name(g) << "_free_mem(mem);\n";
     }
     g << "}\n\n";
     // Checkout/release routines
     g << g.declare("int " + name_ + "_checkout(void)") << " {\n";
     if (needs_mem) {
       g << "return " << codegen_name(g) << "_checkout();\n";
     } else {
       g << "return 0;\n";
     }
     g << "}\n\n";
     if (needs_mem) {
       g << g.declare("void " + name_ + "_release(int mem)") << " {\n";
       g << codegen_name(g) << "_release(mem);\n";
     } else {
       g << g.declare("void " + name_ + "_release(int mem)") << " {\n";
     }
     g << "}\n\n";
     // Reference counter routines
     g << g.declare("void " + name_ + "_incref(void)") << " {\n";
     codegen_incref(g);
     g << "}\n\n"
       << g.declare("void " + name_ + "_decref(void)") << " {\n";
     codegen_decref(g);
     g << "}\n\n";
     // Number of inputs and outptus
     g << g.declare("casadi_int " + name_ + "_n_in(void)")
       << " { return " << n_in_ << ";}\n\n"
       << g.declare("casadi_int " + name_ + "_n_out(void)")
       << " { return " << n_out_ << ";}\n\n";
     // Default inputs
     g << g.declare("casadi_real " + name_ + "_default_in(casadi_int i)") << " {\n"
       << "switch (i) {\n";
     for (casadi_int i=0; i<n_in_; ++i) {
       double def = get_default_in(i);
       if (def!=0) g << "case " << i << ": return " << g.constant(def) << ";\n";
     }
     g << "default: return 0;\n}\n"
       << "}\n\n";
     // Input names
     g << g.declare("const char* " + name_ + "_name_in(casadi_int i)") << " {\n"
       << "switch (i) {\n";
     for (casadi_int i=0; i<n_in_; ++i) {
       g << "case " << i << ": return \"" << name_in_[i] << "\";\n";
     }
     g << "default: return 0;\n}\n"
       << "}\n\n";
     // Output names
     g << g.declare("const char* " + name_ + "_name_out(casadi_int i)") << " {\n"
       << "switch (i) {\n";
     for (casadi_int i=0; i<n_out_; ++i) {
       g << "case " << i << ": return \"" << name_out_[i] << "\";\n";
     }
     g << "default: return 0;\n}\n"
       << "}\n\n";
     // Codegen sparsities
     codegen_sparsities(g);
     // Determine work vector size
     casadi_int sz_w_codegen = sz_w();
     if (is_a("SXFunction", true) && !g.avoid_stack()) sz_w_codegen = 0;
     // Function that returns work vector lengths
     g << g.declare(
         "int " + name_ + "_work(casadi_int *sz_arg, casadi_int* sz_res, "
         "casadi_int *sz_iw, casadi_int *sz_w)")
       << " {\n"
       << "if (sz_arg) *sz_arg = " << sz_arg() << ";\n"
       << "if (sz_res) *sz_res = " << sz_res() << ";\n"
       << "if (sz_iw) *sz_iw = " << sz_iw() << ";\n"
       << "if (sz_w) *sz_w = " << sz_w_codegen << ";\n"
       << "return 0;\n"
       << "}\n\n";
     // Also add to header file to allow getting
      if (g.with_header) {
       g.header
         << "#define " << name_ << "_SZ_ARG " << sz_arg() << "\n"
         << "#define " << name_ << "_SZ_RES " << sz_res() << "\n"
         << "#define " << name_ << "_SZ_IW " << sz_iw() << "\n"
         << "#define " << name_ << "_SZ_W " << sz_w() << "\n";
      }
     // Which inputs are differentiable
     if (!all(is_diff_in_)) {
       g << g.declare("int " + name_ + "_diff_in(casadi_int i)") << " {\n"
         << "switch (i) {\n";
       for (casadi_int i=0; i<n_in_; ++i) {
         g << "case " << i << ": return " << is_diff_in_[i] << ";\n";
       }
       g << "default: return -1;\n}\n"
         << "}\n\n";
     }
     // Which outputs are differentiable
     if (!all(is_diff_out_)) {
       g << g.declare("int " + name_ + "_diff_out(casadi_int i)") << " {\n"
         << "switch (i) {\n";
       for (casadi_int i=0; i<n_out_; ++i) {
         g << "case " << i << ": return " << is_diff_out_[i] << ";\n";
       }
       g << "default: return -1;\n}\n"
         << "}\n\n";
     }
     // Generate mex gateway for the function
     if (g.mex) {
       // Begin conditional compilation
       g << "#ifdef MATLAB_MEX_FILE\n";
       // Declare wrapper
       g << "void mex_" << name_
         << "(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {\n"
         << "casadi_int i;\n";
       g << "int mem;\n";
       // Work vectors, including input and output buffers
       casadi_int i_nnz = nnz_in(), o_nnz = nnz_out();
       size_t sz_w = this->sz_w();
       for (casadi_int i=0; i<n_in_; ++i) {
         const Sparsity& s = sparsity_in_[i];
         sz_w = std::max(sz_w, static_cast<size_t>(s.size1())); // To be able to copy a column
         sz_w = std::max(sz_w, static_cast<size_t>(s.size2())); // To be able to copy a row
       }
       sz_w += i_nnz + o_nnz;
       g << CodeGenerator::array("casadi_real", "w", sz_w);
       g << CodeGenerator::array("casadi_int", "iw", sz_iw());
       std::string fw = "w+" + str(i_nnz + o_nnz);
       // Copy inputs to buffers
       casadi_int offset=0;
       g << CodeGenerator::array("const casadi_real*", "arg", sz_arg(), "{0}");
       // Allocate output buffers
       g << "casadi_real* res[" << sz_res() << "] = {0};\n";
       // Check arguments
       g << "if (argc>" << n_in_ << ") mexErrMsgIdAndTxt(\"Casadi:RuntimeError\","
         << "\"Evaluation of \\\"" << name_ << "\\\" failed. Too many input arguments "
         << "(%d, max " << n_in_ << ")\", argc);\n";
       g << "if (resc>" << n_out_ << ") mexErrMsgIdAndTxt(\"Casadi:RuntimeError\","
         << "\"Evaluation of \\\"" << name_ << "\\\" failed. "
         << "Too many output arguments (%d, max " << n_out_ << ")\", resc);\n";
       for (casadi_int i=0; i<n_in_; ++i) {
         std::string p = "argv[" + str(i) + "]";
         g << "if (--argc>=0) arg[" << i << "] = "
           << g.from_mex(p, "w", offset, sparsity_in_[i], fw) << "\n";
         offset += nnz_in(i);
       }
       for (casadi_int i=0; i<n_out_; ++i) {
         if (i==0) {
           // if i==0, always store output (possibly ans output)
           g << "--resc;\n";
         } else {
           // Store output, if it exists
           g << "if (--resc>=0) ";
         }
         // Create and get pointer
         g << g.res(i) << " = w+" << str(offset) << ";\n";
         offset += nnz_out(i);
       }
       g << name_ << "_incref();\n";
       g << "mem = " << name_ << "_checkout();\n";
       // Call the function
       g << "i = " << name_ << "(arg, res, iw, " << fw << ", mem);\n"
         << "if (i) mexErrMsgIdAndTxt(\"Casadi:RuntimeError\",\"Evaluation of \\\"" << name_
         << "\\\" failed.\");\n";
       g << name_ << "_release(mem);\n";
       g << name_ << "_decref();\n";
       // Save results
       for (casadi_int i=0; i<n_out_; ++i) {
         g << "if (" << g.res(i) << ") resv[" << i << "] = "
           << g.to_mex(sparsity_out_[i], g.res(i)) << "\n";
       }
       // End conditional compilation and function
       g << "}\n"
         << "#endif\n\n";
     }
     if (g.main) {
       // Declare wrapper
       g << "casadi_int main_" << name_ << "(casadi_int argc, char* argv[]) {\n";
       g << "casadi_int j;\n";
       g << "casadi_real* a;\n";
       g << "const casadi_real* r;\n";
       g << "casadi_int flag;\n";
       if (needs_mem) g << "int mem;\n";
       // Work vectors and input and output buffers
       size_t nr = sz_w() + nnz_in() + nnz_out();
       g << CodeGenerator::array("casadi_int", "iw", sz_iw())
         << CodeGenerator::array("casadi_real", "w", nr);
       // Input buffers
       g << "const casadi_real* arg[" << sz_arg() << "];\n";
       // Output buffers
       g << "casadi_real* res[" << sz_res() << "];\n";
       casadi_int off=0;
       for (casadi_int i=0; i<n_in_; ++i) {
         g << "arg[" << i << "] = w+" << off << ";\n";
         off += nnz_in(i);
       }
       for (casadi_int i=0; i<n_out_; ++i) {
         g << "res[" << i << "] = w+" << off << ";\n";
         off += nnz_out(i);
       }
       // TODO(@jaeandersson): Read inputs from file. For now; read from stdin
       g << "a = w;\n"
         << "for (j=0; j<" << nnz_in() << "; ++j) "
         << "if (scanf(\"%lg\", a++)<=0) return 2;\n";
       if (needs_mem) {
         g << "mem = " << name_ << "_checkout();\n";
       }
       // Call the function
       g << "flag = " << name_ << "(arg, res, iw, w+" << off << ", ";
       if (needs_mem) {
         g << "mem";
       } else {
         g << "0";
       }
       g << ");\n";
       if (needs_mem) {
         g << name_ << "_release(mem);\n";
       }
       g << "if (flag) return flag;\n";
       // TODO(@jaeandersson): Write outputs to file. For now: print to stdout
       g << "r = w+" << nnz_in() << ";\n"
         << "for (j=0; j<" << nnz_out() << "; ++j) "
         << g.printf("%g ", "*r++") << "\n";
       // End with newline
       g << g.printf("\\n") << "\n";
       // Finalize function
       g << "return 0;\n"
         << "}\n\n";
     }
     if (g.with_mem) {
       // Allocate memory
       g << g.declare("casadi_functions* " + name_ + "_functions(void)") << " {\n"
         << "static casadi_functions fun = {\n"
         << name_ << "_incref,\n"
         << name_ << "_decref,\n"
         << name_ << "_checkout,\n"
         << name_ << "_release,\n"
         << name_ << "_default_in,\n"
         //<< name_ << "_alloc_mem,\n"
         //<< name_ << "_init_mem,\n"
         //<< name_ << "_free_mem,\n"
         << name_ << "_n_in,\n"
         << name_ << "_n_out,\n"
         << name_ << "_name_in,\n"
         << name_ << "_name_out,\n"
         << name_ << "_sparsity_in,\n"
         << name_ << "_sparsity_out,\n"
         << name_ << "_work,\n"
         << name_ << "\n"
         << "};\n"
         << "return &fun;\n"
         << "}\n";
     }
     // Flush
     g.flush(g.body);
   }
References casadi::all(), casadi::CodeGenerator::array(), casadi::CodeGenerator::avoid_stack(), casadi::CodeGenerator::body, casadi::FunctionInternal::codegen_decref(), casadi::FunctionInternal::codegen_incref(), casadi::FunctionInternal::codegen_mem_type(), casadi::FunctionInternal::codegen_name(), casadi::FunctionInternal::codegen_sparsities(), casadi::CodeGenerator::constant(), casadi::CodeGenerator::declare(), casadi::CodeGenerator::flush(), casadi::CodeGenerator::from_mex(), casadi::FunctionInternal::get_default_in(), casadi::CodeGenerator::header, casadi::FunctionInternal::is_a(), casadi::FunctionInternal::is_diff_in_, casadi::FunctionInternal::is_diff_out_, casadi::CodeGenerator::main, casadi::CodeGenerator::mex, casadi::FunctionInternal::n_in_, casadi::FunctionInternal::n_out_, casadi::ProtoFunction::name_, casadi::FunctionInternal::name_in_, casadi::FunctionInternal::name_out_, casadi::FunctionInternal::nnz_in(), casadi::FunctionInternal::nnz_out(), casadi::CodeGenerator::printf(), casadi::CodeGenerator::res(), casadi::Sparsity::size1(), casadi::Sparsity::size2(), casadi::FunctionInternal::sparsity_in_, casadi::FunctionInternal::sparsity_out_, casadi::str(), casadi::FunctionInternal::sz_arg(), casadi::FunctionInternal::sz_iw(), casadi::FunctionInternal::sz_res(), casadi::FunctionInternal::sz_w(), casadi::CodeGenerator::to_mex(), casadi::CodeGenerator::with_header, and casadi::CodeGenerator::with_mem.
Referenced by casadi::CodeGenerator::add().
codegen_name()
std::string casadi::FunctionInternal::codegen_name (const CodeGenerator & g, bool ns = true) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lp
Definition at line 2662 of file function_internal.cpp.
{
     if (ns) {
       // Get the index of the function
       for (auto&& e : g.added_functions_) {
         if (e.f.get()==this) return e.codegen_name;
       }
     } else {
       for (casadi_int i=0;i<g.added_functions_.size();++i) {
         const auto & e = g.added_functions_[i];
         if (e.f.get()==this) return "f" + str(i);
       }
     }
     casadi_error("Function '" + name_ + "' not found");
   }
References casadi::CodeGenerator::added_functions_, casadi::ProtoFunction::name_, and casadi::str().
Referenced by casadi::FunctionInternal::codegen_alloc_mem(), casadi::FunctionInternal::codegen_checkout(), casadi::Call::codegen_decref(), casadi::Call::codegen_incref(), casadi::FunctionInternal::codegen_mem(), casadi::FunctionInternal::codegen_meta(), casadi::FunctionInternal::codegen_release(), and casadi::CodeGenerator::mem().
codegen_release()
void casadi::FunctionInternal::codegen_release (CodeGenerator & g) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lx
Reimplemented in casadi::External.
Definition at line 2342 of file function_internal.cpp.
{
     std::string name = codegen_name(g, false);
     std::string stack_counter = g.shorthand(name + "_unused_stack_counter");
     std::string stack = g.shorthand(name + "_unused_stack");
     g << stack << "[++" << stack_counter << "] = mem;\n";
   }
References casadi::FunctionInternal::codegen_name(), and casadi::CodeGenerator::shorthand().
Referenced by casadi::CodeGenerator::add_dependency().
codegen_sparsities()
void casadi::FunctionInternal::codegen_sparsities (CodeGenerator & g) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lo
Definition at line 2349 of file function_internal.cpp.
{
     g.add_io_sparsities(name_, sparsity_in_, sparsity_out_);
   }
References casadi::CodeGenerator::add_io_sparsities(), casadi::ProtoFunction::name_, casadi::FunctionInternal::sparsity_in_, and casadi::FunctionInternal::sparsity_out_.
Referenced by casadi::FunctionInternal::codegen_meta().
construct()
void casadi::ProtoFunction::construct (const Dict & opts) inherited
Prepares the function for evaluation
Extra doc: https://github.com/casadi/casadi/wiki/L_jf
Definition at line 131 of file function_internal.cpp.
{
     // Sanitize dictionary is needed
     if (!Options::is_sane(opts)) {
       // Call recursively
       return construct(Options::sanitize(opts));
     }
     // Make sure all options exist
     get_options().check(opts);
     // Initialize the class hierarchy
     try {
       init(opts);
     } catch(std::exception& e) {
       casadi_error("Error calling " + class_name() + "::init for '" + name_ + "':\n"
         + std::string(e.what()));
     }
     // Revisit class hierarchy in reverse order
     try {
       finalize();
     } catch(std::exception& e) {
       casadi_error("Error calling " + class_name() + "::finalize for '" + name_ + "':\n"
         + std::string(e.what()));
     }
   }
References casadi::Options::check(), casadi::SharedObjectInternal::class_name(), casadi::ProtoFunction::finalize(), casadi::ProtoFunction::get_options(), casadi::ProtoFunction::init(), casadi::Options::is_sane(), casadi::ProtoFunction::name_, and casadi::Options::sanitize().
Referenced by casadi::Function::create(), casadi::FmuFunction::factory(), casadi::FmuFunction::get_jacobian(), casadi::LinearInterpolant::get_jacobian(), and casadi::FmuFunction::get_reverse().
convert_arg() [1/2]
template<typename M > std::vector< M > casadi::FunctionInternal::convert_arg (const std::map< std::string, M > & arg) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ks
Definition at line 1750 of file function_internal.hpp.
{
     // Get default inputs
     std::vector<M> arg_v(n_in_);
     for (casadi_int i=0; i<arg_v.size(); ++i) {
       arg_v[i] = get_default_in(i);
     }
     // Assign provided inputs
     for (auto&& e : arg) {
       arg_v.at(index_in(e.first)) = e.second;
     }
     return arg_v;
   }
References casadi::FunctionInternal::get_default_in(), casadi::FunctionInternal::index_in(), and casadi::FunctionInternal::n_in_.
convert_arg() [2/2]
template<typename M > std::map< std::string, M > casadi::FunctionInternal::convert_arg (const std::vector< M > & arg) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ks
Definition at line 1738 of file function_internal.hpp.
{
     casadi_assert(arg.size()==n_in_, "Incorrect number of inputs: Expected "
                       + str(n_in_) + ", got " + str(arg.size()));
     std::map<std::string, M> ret;
     for (casadi_int i=0;i<n_in_;++i) {
       ret[name_in_[i]] = arg[i];
     }
     return ret;
   }
References casadi::FunctionInternal::n_in_, casadi::FunctionInternal::name_in_, and casadi::str().
convert_res() [1/2]
template<typename M > std::vector< M > casadi::FunctionInternal::convert_res (const std::map< std::string, M > & res) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ks
Definition at line 1779 of file function_internal.hpp.
{
     // Get default inputs
     std::vector<M> res_v(n_out_);
     for (casadi_int i=0; i<res_v.size(); ++i) {
       res_v[i] = std::numeric_limits<double>::quiet_NaN();
     }
     // Assign provided inputs
     for (auto&& e : res) {
       M a = e.second;
       res_v.at(index_out(e.first)) = a;
     }
     return res_v;
   }
References casadi::FunctionInternal::index_out(), and casadi::FunctionInternal::n_out_.
convert_res() [2/2]
template<typename M > std::map< std::string, M > casadi::FunctionInternal::convert_res (const std::vector< M > & res) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ks
Definition at line 1767 of file function_internal.hpp.
{
     casadi_assert(res.size()==n_out_, "Incorrect number of outputs: Expected "
                       + str(n_out_) + ", got " + str(res.size()));
     std::map<std::string, M> ret;
     for (casadi_int i=0;i<n_out_;++i) {
       ret[name_out_[i]] = res[i];
     }
     return ret;
   }
References casadi::FunctionInternal::n_out_, casadi::FunctionInternal::name_out_, and casadi::str().
creator()
static Conic* casadi::QpoasesInterface::creator (const std::string & name, const std::map< std::string, Sparsity > & st) inline static
Definition at line 104 of file qpoases_interface.hpp.
{
       return new QpoasesInterface(name, st);
     }
Referenced by casadi::casadi_register_conic_qpoases().
definition()
std::string casadi::FunctionInternal::definition () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ma
Definition at line 921 of file function_internal.cpp.
{
     std::stringstream s;
     // Print name
     s << name_ << ":(";
     // Print input arguments
     for (casadi_int i=0; i<n_in_; ++i) {
       if (!is_diff_in_.empty() && !is_diff_in_[i]) s << "#";
       s << name_in_[i] << sparsity_in_[i].postfix_dim() << (i==n_in_-1 ? "" : ",");
     }
     s << ")->(";
     // Print output arguments
     for (casadi_int i=0; i<n_out_; ++i) {
       if (!is_diff_out_.empty() && !is_diff_out_[i]) s << "#";
       s << name_out_[i] << sparsity_out_[i].postfix_dim() << (i==n_out_-1 ? "" : ",");
     }
     s << ")";
     return s.str();
   }
References casadi::FunctionInternal::is_diff_in_, casadi::FunctionInternal::is_diff_out_, casadi::FunctionInternal::n_in_, casadi::FunctionInternal::n_out_, casadi::ProtoFunction::name_, casadi::FunctionInternal::name_in_, casadi::FunctionInternal::name_out_, casadi::FunctionInternal::sparsity_in_, and casadi::FunctionInternal::sparsity_out_.
Referenced by casadi::FunctionInternal::codegen(), casadi::FunctionInternal::disp(), and casadi::MXFunction::should_inline().
deserialize() [1/2]
static ProtoFunction* casadi::QpoasesInterface::deserialize (DeserializingStream & s) inline static
Definition at line 170 of file qpoases_interface.hpp.
 { return new QpoasesInterface(s); }
Referenced by casadi::casadi_register_conic_qpoases().
deserialize() [2/2]
void casadi::Conic::deserialize (DeserializingStream & s, SDPToSOCPMem & m) protected inherited
Definition at line 707 of file conic.cpp.
{
     s.unpack("Conic::SDPToSOCPMem::r", m.r);
     s.unpack("Conic::SDPToSOCPMem::AT", m.AT);
     s.unpack("Conic::SDPToSOCPMem::A_mapping", m.A_mapping);
     s.unpack("Conic::SDPToSOCPMem::map_Q", m.map_Q);
     s.unpack("Conic::SDPToSOCPMem::map_P", m.map_P);
     s.unpack("Conic::SDPToSOCPMem::indval_size", m.indval_size);
   }
References casadi::Conic::SDPToSOCPMem::A_mapping, casadi::Conic::SDPToSOCPMem::AT, casadi::Conic::SDPToSOCPMem::indval_size, casadi::Conic::SDPToSOCPMem::map_P, casadi::Conic::SDPToSOCPMem::map_Q, casadi::Conic::SDPToSOCPMem::r, and casadi::DeserializingStream::unpack().
Referenced by casadi::CplexInterface::CplexInterface(), casadi::GurobiInterface::GurobiInterface(), and casadi::SuperscsInterface::SuperscsInterface().
destroySingleton()
void casadi::SharedObjectInternal::destroySingleton () inline protected inherited
Called in the destructor of singletons
Definition at line 79 of file shared_object_internal.hpp.
{
       count--;
     }
diff_prefix()
std::string casadi::FunctionInternal::diff_prefix (const std::string & prefix) const inherited
Definition at line 2012 of file function_internal.cpp.
{
     // Highest index found in current inputs and outputs
     casadi_int highest_index = 0;
     // Loop over both input names and output names
     for (const std::vector<std::string>& name_io : {name_in_, name_out_}) {
       for (const std::string& n : name_io) {
         // Find end of prefix, skip if no prefix
         size_t end = n.find('_');
         if (end >= n.size()) continue;
         // Skip if too short
         if (end < prefix.size()) continue;
         // Skip if wrong prefix
         if (n.compare(0, prefix.size(), prefix) != 0) continue;
         // Beginning of index
         size_t begin = prefix.size();
         // Check if any index
         casadi_int this_index;
         if (begin == end) {
           // No prefix, implicitly 1
           this_index = 1;
         } else {
           // Read index from string
           this_index = std::stoi(n.substr(begin, end - begin));
         }
         // Find the highest index
         if (this_index > highest_index) highest_index = this_index;
       }
     }
     // Return one higher index
     if (highest_index == 0) {
       return prefix + "_";
     } else {
       return prefix + std::to_string(highest_index + 1) + "_";
     }
   }
References casadi::FunctionInternal::name_in_, and casadi::FunctionInternal::name_out_.
Referenced by casadi::FunctionInternal::forward(), and casadi::FunctionInternal::reverse().
disp()
void casadi::FunctionInternal::disp (std::ostream & stream, bool more) const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_m8
Implements casadi::SharedObjectInternal.
Definition at line 942 of file function_internal.cpp.
{
     stream << definition() << " " << class_name();
     if (more) {
       stream << std::endl;
       disp_more(stream);
     }
   }
References casadi::SharedObjectInternal::class_name(), casadi::FunctionInternal::definition(), and casadi::FunctionInternal::disp_more().
Referenced by casadi::MXFunction::eval().
disp_more()
virtual void casadi::FunctionInternal::disp_more (std::ostream & stream) const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_m9
Reimplemented in casadi::SXFunction, casadi::Switch, casadi::Nlpsol, and casadi::MXFunction.
Definition at line 901 of file function_internal.hpp.
 {}
Referenced by casadi::FunctionInternal::disp().
dm_in() [1/2]
const std::vector< DM > casadi::FunctionInternal::dm_in () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_l7
Definition at line 3167 of file function_internal.cpp.
{
     std::vector<DM> ret(n_in_);
     for (casadi_int i=0; i<ret.size(); ++i) {
       ret[i] = dm_in(i);
     }
     return ret;
   }
References casadi::FunctionInternal::n_in_.
Referenced by casadi::FunctionInternal::nz_in().
dm_in() [2/2]
const DM casadi::FunctionInternal::dm_in (casadi_int ind) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_l7
Definition at line 3143 of file function_internal.cpp.
{
     return DM::zeros(sparsity_in(ind));
   }
References casadi::FunctionInternal::sparsity_in(), and casadi::GenericMatrix< MatType >::zeros().
dm_out() [1/2]
const std::vector< DM > casadi::FunctionInternal::dm_out () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_l7
Definition at line 3175 of file function_internal.cpp.
{
     std::vector<DM> ret(n_out_);
     for (casadi_int i=0; i<ret.size(); ++i) {
       ret[i] = dm_out(i);
     }
     return ret;
   }
References casadi::FunctionInternal::n_out_.
Referenced by casadi::FunctionInternal::nz_out().
dm_out() [2/2]
const DM casadi::FunctionInternal::dm_out (casadi_int ind) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_l7
Definition at line 3147 of file function_internal.cpp.
{
     return DM::zeros(sparsity_out(ind));
   }
References casadi::FunctionInternal::sparsity_out(), and casadi::GenericMatrix< MatType >::zeros().
ensure_stacked()
template<typename MatType > MatType casadi::FunctionInternal::ensure_stacked (const MatType & v, const Sparsity & sp, casadi_int n) static inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_26j
Definition at line 1796 of file function_internal.hpp.
{
     // Check dimensions
     if (v.size1() == sp.size1() && v.size2() == n * sp.size2()) {
       // Ensure that sparsity is a horizontal multiple of original input, or has no entries
       if (v.nnz() != 0 && !v.sparsity().is_stacked(sp, n)) {
         return project(v, repmat(sp, 1, n));
       }
     } else {
       // Correct empty sparsity
       casadi_assert_dev(v.is_empty());
       return MatType(sp.size1(), sp.size2() * n);
     }
     // No correction needed
     return v;
   }
References casadi::Sparsity::size1(), and casadi::Sparsity::size2().
eval()
int casadi::Conic::eval (const double ** arg, double ** res, casadi_int * iw, double * w, void * mem) const final virtual inherited
Reimplemented from casadi::FunctionInternal.
Definition at line 511 of file conic.cpp.
{
     if (print_problem_) {
       uout() << "H:";
       DM::print_dense(uout(), H_, arg[CONIC_H], false);
       uout() << std::endl;
       uout() << "G:" << std::vector<double>(arg[CONIC_G], arg[CONIC_G]+nx_) << std::endl;
       uout() << "A:";
       DM::print_dense(uout(), A_, arg[CONIC_A], false);
       uout() << std::endl;
       uout() << "lba:" << std::vector<double>(arg[CONIC_LBA], arg[CONIC_LBA]+na_) << std::endl;
       uout() << "uba:" << std::vector<double>(arg[CONIC_UBA], arg[CONIC_UBA]+na_) << std::endl;
       uout() << "lbx:" << std::vector<double>(arg[CONIC_LBX], arg[CONIC_LBX]+nx_) << std::endl;
       uout() << "ubx:" << std::vector<double>(arg[CONIC_UBX], arg[CONIC_UBX]+nx_) << std::endl;
     }
     auto m = static_cast<ConicMemory*>(mem);
     if (inputs_check_) {
       check_inputs(arg[CONIC_LBX], arg[CONIC_UBX], arg[CONIC_LBA], arg[CONIC_UBA]);
     }
     setup(mem, arg, res, iw, w);
     int ret = solve(arg, res, iw, w, mem);
     if (error_on_fail_ && !m->d_qp.success)
       casadi_error("conic process failed. "
                    "Set 'error_on_fail' option to false to ignore this error.");
     return ret;
   }
References casadi::Conic::A_, casadi::Conic::check_inputs(), casadi::CONIC_A, casadi::CONIC_G, casadi::CONIC_H, casadi::CONIC_LBA, casadi::CONIC_LBX, casadi::CONIC_UBA, casadi::CONIC_UBX, casadi::ProtoFunction::error_on_fail_, casadi::Conic::H_, casadi::FunctionInternal::inputs_check_, casadi::Conic::na_, casadi::Conic::nx_, casadi::Matrix< double >::print_dense(), casadi::Conic::print_problem_, casadi::FunctionInternal::setup(), casadi::Conic::solve(), and casadi::uout().
Referenced by casadi::ProxqpInterface::solve().
eval_dm()
std::vector< DM > casadi::FunctionInternal::eval_dm (const std::vector< DM > & arg) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ke
Reimplemented in casadi::CallbackInternal.
Definition at line 2003 of file function_internal.cpp.
{
     casadi_error("'eval_dm' not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
Referenced by casadi::FunctionInternal::eval().
eval_gen() [1/3]
int casadi::FunctionInternal::eval_gen (const bvec_t ** arg, bvec_t ** res, casadi_int * iw, bvec_t * w, void * mem) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kf
Definition at line 403 of file function_internal.hpp.
{
       return sp_forward(arg, res, iw, w, mem);
     }
eval_gen() [2/3]
int casadi::FunctionInternal::eval_gen (const double ** arg, double ** res, casadi_int * iw, double * w, void * mem) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kb
Definition at line 824 of file function_internal.cpp.
{
     casadi_int dump_id = (dump_in_ || dump_out_ || dump_) ? get_dump_id() : 0;
     if (dump_in_) dump_in(dump_id, arg);
     if (dump_ && dump_id==0) dump();
     if (print_in_) print_in(uout(), arg, false);
     auto m = static_cast<ProtoFunctionMemory*>(mem);
     // Reset statistics
     for (auto&& s : m->fstats) s.second.reset();
     if (m->t_total) m->t_total->tic();
     int ret;
     if (eval_) {
       int mem = 0;
       if (checkout_) {
 #ifdef CASADI_WITH_THREAD
     std::lock_guard<std::mutex> lock(mtx_);
 #endif //CASADI_WITH_THREAD
         mem = checkout_();
       }
       ret = eval_(arg, res, iw, w, mem);
       if (release_) {
 #ifdef CASADI_WITH_THREAD
     std::lock_guard<std::mutex> lock(mtx_);
 #endif //CASADI_WITH_THREAD
         release_(mem);
       }
     } else {
       ret = eval(arg, res, iw, w, mem);
     }
     if (m->t_total) m->t_total->toc();
     // Show statistics
     print_time(m->fstats);
     if (dump_out_) dump_out(dump_id, res);
     if (print_out_) print_out(uout(), res, false);
     // Check all outputs for NaNs
     if (regularity_check_) {
       for (casadi_int i = 0; i < n_out_; ++i) {
         // Skip of not calculated
         if (!res[i]) continue;
         // Loop over nonzeros
         casadi_int nnz = this->nnz_out(i);
         for (casadi_int nz = 0; nz < nnz; ++nz) {
           if (isnan(res[i][nz]) || isinf(res[i][nz])) {
             // Throw readable error message
             casadi_error(str(res[i][nz]) + " detected for output " + name_out_[i] + " at "
               + sparsity_out(i).repr_el(nz));
           }
         }
       }
     }
     return ret;
   }
References casadi::FunctionInternal::checkout_, casadi::FunctionInternal::dump_, casadi::FunctionInternal::dump_in_, casadi::FunctionInternal::dump_out_, casadi::FunctionInternal::eval(), casadi::FunctionInternal::eval_, casadi::FunctionInternal::n_out_, casadi::FunctionInternal::name_out_, casadi::FunctionInternal::nnz_out(), casadi::FunctionInternal::print_in(), casadi::FunctionInternal::print_in_, casadi::FunctionInternal::print_out(), casadi::FunctionInternal::print_out_, casadi::ProtoFunction::print_time(), casadi::ProtoFunction::regularity_check_, casadi::FunctionInternal::release_, casadi::FunctionInternal::sparsity_out(), casadi::str(), casadi::ProtoFunctionMemory::t_total, casadi::FStats::tic(), and casadi::uout().
Referenced by casadi::FunctionInternal::call_gen().
eval_gen() [3/3]
int casadi::FunctionInternal::eval_gen (const SXElem ** arg, SXElem ** res, casadi_int * iw, SXElem * w, void * mem) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kf
Definition at line 400 of file function_internal.hpp.
{
       return eval_sx(arg, res, iw, w, mem);
     }
eval_mx()
void casadi::FunctionInternal::eval_mx (const MXVector & arg, MXVector & res, bool always_inline, bool never_inline) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kd
Reimplemented in casadi::MXFunction.
Definition at line 2210 of file function_internal.cpp.
{
     always_inline = always_inline || always_inline_;
     never_inline = never_inline || never_inline_;
     // The code below creates a call node, to inline, wrap in an MXFunction
     if (always_inline) {
       casadi_assert(!never_inline, "Inconsistent options for " + str(name_));
       return wrap().call(arg, res, true);
     }
     // Create a call-node
     res = Call::create(self(), arg);
   }
References casadi::FunctionInternal::always_inline_, casadi::Function::call(), casadi::Call::create(), casadi::ProtoFunction::name_, casadi::FunctionInternal::never_inline_, casadi::str(), and casadi::FunctionInternal::wrap().
Referenced by casadi::FunctionInternal::call_gen(), and casadi::MXFunction::eval_mx().
eval_sx()
int casadi::FunctionInternal::eval_sx (const SXElem ** arg, SXElem ** res, casadi_int * iw, SXElem * w, void * mem) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kc
Reimplemented in casadi::SXFunction, casadi::Switch, casadi::MXFunction, casadi::MapSum, and casadi::Map.
Definition at line 2007 of file function_internal.cpp.
{
     casadi_error("'eval_sx' not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
export_code()
void casadi::FunctionInternal::export_code (const std::string & lang, std::ostream & stream, const Dict & options) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_m5
Reimplemented in casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, and casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >.
Definition at line 2170 of file function_internal.cpp.
{
     casadi_error("'export_code' not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
factory()
Function casadi::FunctionInternal::factory (const std::string & name, const std::vector< std::string > & s_in, const std::vector< std::string > & s_out, const Function::AuxOut & aux, const Dict & opts) const virtual inherited
Reimplemented in casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >, casadi::FmuFunction, and casadi::External.
Definition at line 3524 of file function_internal.cpp.
{
     return wrap().factory(name, s_in, s_out, aux, opts);
   }
References casadi::Function::factory(), and casadi::FunctionInternal::wrap().
Referenced by casadi::Function::factory(), casadi::External::factory(), and casadi::FmuFunction::factory().
finalize()
void casadi::FunctionInternal::finalize () override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_k7
Reimplemented from casadi::ProtoFunction.
Reimplemented in casadi::OracleFunction.
Definition at line 677 of file function_internal.cpp.
{
     if (jit_) {
       jit_name_ = jit_base_name_;
       if (jit_temp_suffix_) {
         jit_name_ = temporary_file(jit_name_, ".c");
         jit_name_ = std::string(jit_name_.begin(), jit_name_.begin()+jit_name_.size()-2);
       }
       if (has_codegen()) {
         if (compiler_.is_null()) {
           if (verbose_) casadi_message("Codegenerating function '" + name_ + "'.");
           // JIT everything
           Dict opts;
           // Override the default to avoid random strings in the generated code
           opts["prefix"] = "jit";
           CodeGenerator gen(jit_name_, opts);
           gen.add(self());
           if (verbose_) casadi_message("Compiling function '" + name_ + "'..");
           std::string jit_directory = get_from_dict(jit_options_, "directory", std::string(""));
           compiler_ = Importer(gen.generate(jit_directory), compiler_plugin_, jit_options_);
           if (verbose_) casadi_message("Compiling function '" + name_ + "' done.");
         }
         // Try to load
         eval_ = (eval_t) compiler_.get_function(name_);
         checkout_ = (casadi_checkout_t) compiler_.get_function(name_ + "checkout");
         release_ = (casadi_release_t) compiler_.get_function(name_ + "release");
         casadi_assert(eval_!=nullptr, "Cannot load JIT'ed function.");
       } else {
         // Just jit dependencies
         jit_dependencies(jit_name_);
       }
     }
     // Finalize base classes
     ProtoFunction::finalize();
     // Dump if requested
     if (dump_) dump();
   }
References casadi::CodeGenerator::add(), casadi::FunctionInternal::checkout_, casadi::FunctionInternal::compiler_, casadi::FunctionInternal::compiler_plugin_, casadi::FunctionInternal::dump_, casadi::FunctionInternal::eval_, casadi::ProtoFunction::finalize(), casadi::CodeGenerator::generate(), casadi::get_from_dict(), casadi::Importer::get_function(), casadi::FunctionInternal::has_codegen(), casadi::SharedObject::is_null(), casadi::FunctionInternal::jit_, casadi::FunctionInternal::jit_base_name_, casadi::FunctionInternal::jit_dependencies(), casadi::FunctionInternal::jit_name_, casadi::FunctionInternal::jit_options_, casadi::FunctionInternal::jit_temp_suffix_, casadi::ProtoFunction::name_, casadi::FunctionInternal::release_, casadi::temporary_file(), and casadi::ProtoFunction::verbose_.
Referenced by casadi::FunctionInternal::deserialize(), casadi::CallbackInternal::finalize(), and casadi::OracleFunction::finalize().
find()
virtual void casadi::FunctionInternal::find (std::map< FunctionInternal *, Function > & all_fun, casadi_int max_depth) const inline virtual inherited
Reimplemented in casadi::Switch, and casadi::MXFunction.
Definition at line 346 of file function_internal.hpp.
 {}
Referenced by casadi::FunctionInternal::add_embedded(), casadi::FunctionInternal::from_compact(), and casadi::FunctionInternal::to_compact().
format_time()
void casadi::ProtoFunction::format_time (char * buffer, double time) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_jt
Definition at line 3678 of file function_internal.cpp.
{
     // Always of width 8
     casadi_assert_dev(time>=0);
     double log_time = log10(time);
     int magn = static_cast<int>(floor(log_time));
     int iprefix = static_cast<int>(floor(log_time/3));
     if (iprefix<-4) {
       sprint(buffer, 10, "       0");
       return;
     }
     if (iprefix>=5) {
       sprint(buffer, 10, "     inf");
       return;
     }
     char prefixes[] = "TGMk munp";
     char prefix = prefixes[4-iprefix];
     int rem = magn-3*iprefix;
     double time_normalized = time/pow(10, 3*iprefix);
     if (rem==0) {
       sprint(buffer, 10, "  %1.2f%cs", time_normalized, prefix);
     } else if (rem==1) {
       sprint(buffer, 10, " %2.2f%cs", time_normalized, prefix);
     } else {
       sprint(buffer, 10, "%3.2f%cs", time_normalized, prefix);
     }
   }
References casadi::ProtoFunction::sprint().
Referenced by casadi::ProtoFunction::print_time().
forward()
Function casadi::FunctionInternal::forward (casadi_int nfwd) const inherited
forward(nfwd) returns a cached instance if available, and calls Function get_forward(casadi_int nfwd) if no cached version is available.
Extra doc: https://github.com/casadi/casadi/wiki/L_l0
Definition at line 2048 of file function_internal.cpp.
{
     casadi_assert_dev(nfwd>=0);
     // Used wrapped function if forward not available
     if (!enable_forward_ && !enable_fd_) {
       // Derivative information must be available
       casadi_assert(has_derivative(), "Derivatives cannot be calculated for " + name_);
       return wrap().forward(nfwd);
     }
     // Retrieve/generate cached
     Function f;
     std::string fname = forward_name(name_, nfwd);
     if (!incache(fname, f)) {
       casadi_int i;
       // Prefix to be used for forward seeds, sensitivities
       std::string pref = diff_prefix("fwd");
       // Names of inputs
       std::vector<std::string> inames;
       for (i=0; i<n_in_; ++i) inames.push_back(name_in_[i]);
       for (i=0; i<n_out_; ++i) inames.push_back("out_" + name_out_[i]);
       for (i=0; i<n_in_; ++i) inames.push_back(pref + name_in_[i]);
       // Names of outputs
       std::vector<std::string> onames;
       for (i=0; i<n_out_; ++i) onames.push_back(pref + name_out_[i]);
       // Options
       Dict opts = combine(forward_options_, der_options_);
       opts = combine(opts, generate_options("forward"));
       if (!enable_forward_) opts = fd_options_;
       opts["derivative_of"] = self();
       // Generate derivative function
       casadi_assert_dev(enable_forward_ || enable_fd_);
       if (enable_forward_) {
         f = get_forward(nfwd, fname, inames, onames, opts);
       } else {
         // Get FD method
         if (fd_method_.empty() || fd_method_=="central") {
           f = Function::create(new CentralDiff(fname, nfwd), opts);
         } else if (fd_method_=="forward") {
           f = Function::create(new ForwardDiff(fname, nfwd), opts);
         } else if (fd_method_=="backward") {
           f = Function::create(new BackwardDiff(fname, nfwd), opts);
         } else if (fd_method_=="smoothing") {
           f = Function::create(new Smoothing(fname, nfwd), opts);
         } else {
           casadi_error("Unknown 'fd_method': " + fd_method_);
         }
       }
       // Consistency check for inputs
       casadi_assert_dev(f.n_in()==n_in_ + n_out_ + n_in_);
       casadi_int ind=0;
       for (i=0; i<n_in_; ++i) f.assert_size_in(ind++, size1_in(i), size2_in(i));
       for (i=0; i<n_out_; ++i) f.assert_size_in(ind++, size1_out(i), size2_out(i));
       for (i=0; i<n_in_; ++i) f.assert_size_in(ind++, size1_in(i), nfwd*size2_in(i));
       // Consistency check for outputs
       casadi_assert_dev(f.n_out()==n_out_);
       for (i=0; i<n_out_; ++i) f.assert_sparsity_out(i, sparsity_out(i), nfwd);
       // Save to cache
       tocache(f);
     }
     return f;
   }
References casadi::Function::assert_size_in(), casadi::Function::assert_sparsity_out(), casadi::combine(), casadi::Function::create(), casadi::FunctionInternal::der_options_, casadi::FunctionInternal::diff_prefix(), casadi::FunctionInternal::enable_fd_, casadi::FunctionInternal::enable_forward_, casadi::FunctionInternal::fd_method_, casadi::FunctionInternal::fd_options_, casadi::Function::forward(), casadi::FunctionInternal::forward_name(), casadi::FunctionInternal::forward_options_, casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::get_forward(), casadi::FunctionInternal::has_derivative(), casadi::FunctionInternal::incache(), casadi::Function::n_in(), casadi::FunctionInternal::n_in_, casadi::Function::n_out(), casadi::FunctionInternal::n_out_, casadi::ProtoFunction::name_, casadi::FunctionInternal::name_in_, casadi::FunctionInternal::name_out_, casadi::FunctionInternal::size1_in(), casadi::FunctionInternal::size1_out(), casadi::FunctionInternal::size2_in(), casadi::FunctionInternal::size2_out(), casadi::FunctionInternal::sparsity_out(), casadi::FunctionInternal::tocache(), and casadi::FunctionInternal::wrap().
Referenced by casadi::FunctionInternal::call_forward(), and casadi::Function::forward().
forward_name()
static std::string casadi::FunctionInternal::forward_name (const std::string & fcn, casadi_int nfwd) inline static inherited
Definition at line 605 of file function_internal.hpp.
{
       return "fwd" + str(nfwd) + "_" + fcn;
     }
References casadi::str().
Referenced by casadi::Integrator::bdae_sp_forward(), casadi::Integrator::bdae_sp_reverse(), casadi::Integrator::bquad_sp_forward(), casadi::Integrator::bquad_sp_reverse(), casadi::SundialsInterface::calc_daeB(), casadi::SundialsInterface::calc_daeF(), casadi::SundialsInterface::calc_jtimesF(), casadi::SundialsInterface::calc_quadB(), casadi::SundialsInterface::calc_quadF(), casadi::OracleFunction::create_forward(), casadi::Integrator::fdae_sp_forward(), casadi::Integrator::fdae_sp_reverse(), casadi::FunctionInternal::forward(), casadi::Integrator::fquad_sp_forward(), casadi::Integrator::fquad_sp_reverse(), casadi::Integrator::sp_jac_dae(), casadi::Integrator::sp_jac_rdae(), casadi::FixedStepIntegrator::stepB(), and casadi::FixedStepIntegrator::stepF().
free_mem()
void casadi::QpoasesInterface::free_mem (void * mem) const inline override virtual
Reimplemented from casadi::ProtoFunction.
Definition at line 138 of file qpoases_interface.hpp.
 { delete static_cast<QpoasesMemory*>(mem);}
free_mx()
std::vector< MX > casadi::FunctionInternal::free_mx () const virtual inherited
Reimplemented in casadi::MXFunction.
Definition at line 3211 of file function_internal.cpp.
{
     casadi_error("'free_mx' only defined for 'MXFunction'");
   }
free_sx()
std::vector< SX > casadi::FunctionInternal::free_sx () const virtual inherited
Reimplemented in casadi::SXFunction.
Definition at line 3215 of file function_internal.cpp.
{
     casadi_error("'free_sx' only defined for 'SXFunction'");
   }
from_BooleanType()
bool casadi::QpoasesInterface::from_BooleanType (qpOASES::BooleanType b) static protected
Convert between qpOASES types and standard types
Definition at line 773 of file qpoases_interface.cpp.
{
     switch (b) {
     case qpOASES::BT_TRUE:              return true;
     case qpOASES::BT_FALSE:             return false;
     }
     casadi_error("not_implemented");
   }
Referenced by serialize_body().
from_compact()
Sparsity casadi::FunctionInternal::from_compact (casadi_int oind, casadi_int iind, const Sparsity & sp) const inherited
Definition at line 1825 of file function_internal.cpp.
{
     // Return value
     Sparsity r = sp;
     // Insert rows if sparse output
     if (numel_out(oind) != r.size1()) {
       casadi_assert_dev(r.size1() == nnz_out(oind));
       r.enlargeRows(numel_out(oind), sparsity_out(oind).find());
     }
     // Insert columns if sparse input
     if (numel_in(iind) != r.size2()) {
       casadi_assert_dev(r.size2() == nnz_in(iind));
       r.enlargeColumns(numel_in(iind), sparsity_in(iind).find());
     }
     // Return non-compact pattern
     return r;
   }
References casadi::Sparsity::enlargeColumns(), casadi::Sparsity::enlargeRows(), casadi::FunctionInternal::find(), casadi::FunctionInternal::nnz_in(), casadi::FunctionInternal::nnz_out(), casadi::FunctionInternal::numel_in(), casadi::FunctionInternal::numel_out(), casadi::Sparsity::size1(), casadi::Sparsity::size2(), casadi::FunctionInternal::sparsity_in(), and casadi::FunctionInternal::sparsity_out().
Referenced by casadi::FunctionInternal::jac_sparsity().
from_PrintLevel()
std::string casadi::QpoasesInterface::from_PrintLevel (qpOASES::PrintLevel b) static protected
Convert between qpOASES types and standard types
Definition at line 813 of file qpoases_interface.cpp.
{
     switch (b) {
     case qpOASES::PL_TABULAR:           return "tabular";
     case qpOASES::PL_NONE:              return "none";
     case qpOASES::PL_LOW:               return "low";
     case qpOASES::PL_MEDIUM:            return "medium";
     case qpOASES::PL_HIGH:              return "high";
     case qpOASES::PL_DEBUG_ITER:        return "debug_iter";
     }
     casadi_error("not_implemented");
   }
from_SubjectToStatus()
std::string casadi::QpoasesInterface::from_SubjectToStatus (qpOASES::SubjectToStatus b) static protected
Convert between qpOASES types and standard types
Definition at line 785 of file qpoases_interface.cpp.
{
     switch (b) {
     case qpOASES::ST_INACTIVE:          return "inactive";
     case qpOASES::ST_LOWER:             return "lower";
     case qpOASES::ST_UPPER:             return "upper";
     case qpOASES::ST_INFEASIBLE_LOWER:  return "infeasible_lower";
     case qpOASES::ST_INFEASIBLE_UPPER:  return "infeasible_upper";
     case qpOASES::ST_UNDEFINED:         return "undefined";
     }
     casadi_error("not_implemented");
   }
Referenced by serialize_body().
fwd_seed()
template<typename MatType > std::vector< std::vector< MatType > > casadi::FunctionInternal::fwd_seed (casadi_int nfwd) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_nr
Definition at line 1435 of file function_internal.hpp.
{
     std::vector<std::vector<MatType>> fseed(nfwd);
     for (casadi_int dir=0; dir<nfwd; ++dir) {
       fseed[dir].resize(n_in_);
       for (casadi_int iind=0; iind<n_in_; ++iind) {
         std::string n = "f" + str(dir) + "_" +  name_in_[iind];
         Sparsity sp = is_diff_in_[iind] ? sparsity_in(iind) : Sparsity(size_in(iind));
         fseed[dir][iind] = MatType::sym(n, sp);
       }
     }
     return fseed;
   }
References casadi::FunctionInternal::is_diff_in_, casadi::FunctionInternal::n_in_, casadi::FunctionInternal::name_in_, casadi::FunctionInternal::size_in(), casadi::FunctionInternal::sparsity_in(), and casadi::str().
fwdViaJac()
bool casadi::FunctionInternal::fwdViaJac (casadi_int nfwd) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_nc
Definition at line 2832 of file function_internal.cpp.
{
     if (!enable_forward_ && !enable_fd_) return true;
     if (jac_penalty_==-1) return false;
     // Heuristic 1: Jac calculated via forward mode likely cheaper
     if (jac_penalty_*static_cast<double>(nnz_in())<nfwd) return true;
     // Heuristic 2: Jac calculated via reverse mode likely cheaper
     double w = ad_weight();
     if (enable_reverse_ &&
         jac_penalty_*(1-w)*static_cast<double>(nnz_out())<w*static_cast<double>(nfwd))
       return true; // NOLINT
     return false;
   }
References casadi::FunctionInternal::ad_weight(), casadi::FunctionInternal::enable_fd_, casadi::FunctionInternal::enable_forward_, casadi::FunctionInternal::enable_reverse_, casadi::FunctionInternal::jac_penalty_, casadi::FunctionInternal::nnz_in(), and casadi::FunctionInternal::nnz_out().
Referenced by casadi::FunctionInternal::call_forward().
generate_dependencies()
std::string casadi::FunctionInternal::generate_dependencies (const std::string & fname, const Dict & opts) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_m2
Reimplemented in casadi::OracleFunction.
Definition at line 2694 of file function_internal.cpp.
{
     casadi_error("'generate_dependencies' not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
generate_in()
void casadi::FunctionInternal::generate_in (const std::string & fname, const double ** arg) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ne
Definition at line 722 of file function_internal.cpp.
{
     // Set up output stream
     std::ofstream of(fname);
     casadi_assert(of.good(), "Error opening stream '" + fname + "'.");
     normalized_setup(of);
     // Encode each input
     for (casadi_int i=0; i<n_in_; ++i) {
       const double* v = arg[i];
       for (casadi_int k=0;k<nnz_in(i);++k) {
         normalized_out(of, v ? v[k] : 0);
         of << std::endl;
       }
     }
   }
References casadi::FunctionInternal::n_in_, casadi::FunctionInternal::nnz_in(), casadi::normalized_out(), and casadi::normalized_setup().
generate_lifted()
void casadi::FunctionInternal::generate_lifted (Function & vdef_fcn, Function & vinit_fcn) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_l9
Reimplemented in casadi::MXFunction.
Definition at line 3219 of file function_internal.cpp.
{
     casadi_error("'generate_lifted' only defined for 'MXFunction'");
   }
generate_options()
Dict casadi::FunctionInternal::generate_options (const std::string & target) const override virtual inherited
Reimplemented from casadi::ProtoFunction.
Reimplemented in casadi::SXFunction, and casadi::MXFunction.
Definition at line 373 of file function_internal.cpp.
{
     Dict opts = ProtoFunction::generate_options(target);
     opts["jac_penalty"] = jac_penalty_;
     opts["user_data"] = user_data_;
     opts["inputs_check"] = inputs_check_;
     if (target!="tmp") opts["jit"] = jit_;
     opts["jit_cleanup"] = jit_cleanup_;
     opts["jit_serialize"] = jit_serialize_;
     opts["compiler"] = compiler_plugin_;
     opts["jit_options"] = jit_options_;
     opts["jit_name"] = jit_base_name_;
     opts["jit_temp_suffix"] = jit_temp_suffix_;
     opts["ad_weight"] = ad_weight_;
     opts["ad_weight_sp"] = ad_weight_sp_;
     opts["always_inline"] = always_inline_;
     opts["never_inline"] = never_inline_;
     opts["max_num_dir"] = max_num_dir_;
     if (target=="clone" || target=="tmp") {
       opts["enable_forward"] = enable_forward_op_;
       opts["enable_reverse"] = enable_reverse_op_;
       opts["enable_jacobian"] = enable_jacobian_op_;
       opts["enable_fd"] = enable_fd_op_;
       opts["reverse_options"] = reverse_options_;
       opts["forward_options"] = forward_options_;
       opts["jacobian_options"] = jacobian_options_;
       opts["der_options"] = der_options_;
       opts["derivative_of"] = derivative_of_;
     }
     opts["fd_options"] = fd_options_;
     opts["fd_method"] = fd_method_;
     opts["print_in"] = print_in_;
     opts["print_out"] = print_out_;
     opts["max_io"] = max_io_;
     opts["dump_in"] = dump_in_;
     opts["dump_out"] = dump_out_;
     opts["dump_dir"] = dump_dir_;
     opts["dump_format"] = dump_format_;
     opts["dump"] = dump_;
     return opts;
   }
References casadi::FunctionInternal::ad_weight_, casadi::FunctionInternal::ad_weight_sp_, casadi::FunctionInternal::always_inline_, casadi::FunctionInternal::compiler_plugin_, casadi::FunctionInternal::der_options_, casadi::FunctionInternal::derivative_of_, casadi::FunctionInternal::dump_, casadi::FunctionInternal::dump_dir_, casadi::FunctionInternal::dump_format_, casadi::FunctionInternal::dump_in_, casadi::FunctionInternal::dump_out_, casadi::FunctionInternal::enable_fd_op_, casadi::FunctionInternal::enable_forward_op_, casadi::FunctionInternal::enable_jacobian_op_, casadi::FunctionInternal::enable_reverse_op_, casadi::FunctionInternal::fd_method_, casadi::FunctionInternal::fd_options_, casadi::FunctionInternal::forward_options_, casadi::ProtoFunction::generate_options(), casadi::FunctionInternal::inputs_check_, casadi::FunctionInternal::jac_penalty_, casadi::FunctionInternal::jacobian_options_, casadi::FunctionInternal::jit_, casadi::FunctionInternal::jit_base_name_, casadi::FunctionInternal::jit_cleanup_, casadi::FunctionInternal::jit_options_, casadi::FunctionInternal::jit_serialize_, casadi::FunctionInternal::jit_temp_suffix_, casadi::FunctionInternal::max_io_, casadi::FunctionInternal::max_num_dir_, casadi::FunctionInternal::never_inline_, casadi::FunctionInternal::print_in_, casadi::FunctionInternal::print_out_, casadi::FunctionInternal::reverse_options_, and casadi::FunctionInternal::user_data_.
Referenced by casadi::FunctionInternal::forward(), casadi::MXFunction::generate_options(), and casadi::FunctionInternal::reverse().
generate_out()
void casadi::FunctionInternal::generate_out (const std::string & fname, double ** res) const inherited
Definition at line 738 of file function_internal.cpp.
{
     // Set up output stream
     std::ofstream of(fname);
     casadi_assert(of.good(), "Error opening stream '" + fname + "'.");
     normalized_setup(of);
     // Encode each input
     for (casadi_int i=0; i<n_out_; ++i) {
       const double* v = res[i];
       for (casadi_int k=0;k<nnz_out(i);++k) {
         normalized_out(of, v ? v[k] : std::numeric_limits<double>::quiet_NaN());
         of << std::endl;
       }
     }
   }
References casadi::FunctionInternal::n_out_, casadi::FunctionInternal::nnz_out(), casadi::normalized_out(), and casadi::normalized_setup().
generateNativeCode()
void casadi::Conic::generateNativeCode (std::ostream & file) const virtual inherited
Generate native code in the interfaced language for debugging
Reimplemented in casadi::SqicInterface.
Definition at line 490 of file conic.cpp.
{
     casadi_error("generateNativeCode not defined for class " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
Referenced by casadi::conic_debug().
get_abstol()
virtual double casadi::FunctionInternal::get_abstol () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mp
Reimplemented in casadi::SundialsInterface, casadi::Smoothing, casadi::CentralDiff, and casadi::ForwardDiff.
Definition at line 1055 of file function_internal.hpp.
{
       return eps;
     }
References casadi::eps.
Referenced by casadi::FiniteDiff::init().
get_default_in()
double casadi::Conic::get_default_in (casadi_int ind) const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1jd
Reimplemented from casadi::FunctionInternal.
Definition at line 498 of file conic.cpp.
{
     switch (ind) {
     case CONIC_LBX:
     case CONIC_LBA:
       return -std::numeric_limits<double>::infinity();
     case CONIC_UBX:
     case CONIC_UBA:
       return std::numeric_limits<double>::infinity();
     default:
       return 0;
     }
   }
References casadi::CONIC_LBA, casadi::CONIC_LBX, casadi::CONIC_UBA, and casadi::CONIC_UBX.
get_diff_in()
virtual bool casadi::FunctionInternal::get_diff_in (casadi_int i) inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ms
Reimplemented in casadi::BSplineInterpolant, casadi::Interpolant, casadi::GenericExternal, and casadi::Expm.
Definition at line 1072 of file function_internal.hpp.
 { return true; }
Referenced by casadi::GenericExternal::get_diff_in(), and casadi::FunctionInternal::init().
get_diff_out()
virtual bool casadi::FunctionInternal::get_diff_out (casadi_int i) inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mt
Reimplemented in casadi::GenericExternal.
Definition at line 1077 of file function_internal.hpp.
 { return true; }
Referenced by casadi::GenericExternal::get_diff_out(), and casadi::FunctionInternal::init().
get_forward()
Function casadi::FunctionInternal::get_forward (casadi_int nfwd, const std::string & name, const std::vector< std::string > & inames, const std::vector< std::string > & onames, const Dict & opts) const virtual inherited
forward(nfwd) returns a cached instance if available, and calls Function get_forward(casadi_int nfwd) if no cached version is available.
Extra doc: https://github.com/casadi/casadi/wiki/L_l0
Reimplemented in casadi::BSplineInterpolant, casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >, casadi::Switch, casadi::Rootfinder, casadi::Nlpsol, casadi::MapSum, casadi::Map, casadi::Integrator, casadi::Smoothing, casadi::CentralDiff, casadi::ForwardDiff, casadi::External, casadi::Expm, casadi::Dple, and casadi::CallbackInternal.
Definition at line 2154 of file function_internal.cpp.
{
     casadi_error("'get_forward' not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
Referenced by casadi::FunctionInternal::forward(), and casadi::BSplineInterpolant::get_forward().
get_free()
std::vector< std::string > casadi::FunctionInternal::get_free () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mc
Reimplemented in casadi::SXFunction, and casadi::MXFunction.
Definition at line 916 of file function_internal.cpp.
{
     casadi_assert_dev(!has_free());
     return std::vector<std::string>();
   }
References casadi::FunctionInternal::has_free().
get_function() [1/2]
std::vector< std::string > casadi::FunctionInternal::get_function () const virtual inherited
Reimplemented in casadi::OracleFunction, casadi::MapSum, and casadi::Map.
Definition at line 3533 of file function_internal.cpp.
{
     // No functions
     return std::vector<std::string>();
   }
get_function() [2/2]
const Function & casadi::FunctionInternal::get_function (const std::string & name) const virtual inherited
Reimplemented in casadi::OracleFunction, casadi::MapSum, and casadi::Map.
Definition at line 3538 of file function_internal.cpp.
{
     casadi_error("'get_function' not defined for " + class_name());
     static Function singleton;
     return singleton;
   }
References casadi::SharedObjectInternal::class_name().
get_jac_sparsity()
Sparsity casadi::FunctionInternal::get_jac_sparsity (casadi_int oind, casadi_int iind, bool symmetric) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kz Get, if necessary generate, the sparsity of a Jacobian block
Reimplemented in casadi::FmuFunction, casadi::GenericExternal, casadi::Expm, and casadi::CallbackInternal.
Definition at line 1773 of file function_internal.cpp.
{
     // Check if we are able to propagate dependencies through the function
     if (has_spfwd() || has_sprev()) {
       // Get weighting factor
       double w = sp_weight();
       // Skip generation, assume dense
       if (w == -1) return Sparsity();
       Sparsity sp;
       if (nnz_in(iind) > 3*bvec_size && nnz_out(oind) > 3*bvec_size &&
             GlobalOptions::hierarchical_sparsity) {
         if (symmetric) {
           sp = get_jac_sparsity_hierarchical_symm(oind, iind);
         } else {
           sp = get_jac_sparsity_hierarchical(oind, iind);
         }
       } else {
         // Number of nonzero inputs and outputs
         casadi_int nz_in = nnz_in(iind);
         casadi_int nz_out = nnz_out(oind);
         // Number of forward sweeps we must make
         casadi_int nsweep_fwd = nz_in/bvec_size;
         if (nz_in%bvec_size) nsweep_fwd++;
         // Number of adjoint sweeps we must make
         casadi_int nsweep_adj = nz_out/bvec_size;
         if (nz_out%bvec_size) nsweep_adj++;
         // Use forward mode?
         if (w*static_cast<double>(nsweep_fwd) <= (1-w)*static_cast<double>(nsweep_adj)) {
           sp = get_jac_sparsity_gen<true>(oind, iind);
         } else {
           sp = get_jac_sparsity_gen<false>(oind, iind);
         }
       }
       return sp;
     } else {
       // Not calculated
       return Sparsity();
     }
   }
References casadi::bvec_size, casadi::FunctionInternal::get_jac_sparsity_hierarchical(), casadi::FunctionInternal::get_jac_sparsity_hierarchical_symm(), casadi::FunctionInternal::has_spfwd(), casadi::FunctionInternal::has_sprev(), casadi::GlobalOptions::hierarchical_sparsity, casadi::FunctionInternal::nnz_in(), casadi::FunctionInternal::nnz_out(), casadi::FunctionInternal::nz_in(), casadi::FunctionInternal::nz_out(), and casadi::FunctionInternal::sp_weight().
Referenced by casadi::Expm::get_jac_sparsity(), casadi::GenericExternal::get_jac_sparsity(), and casadi::FunctionInternal::jac_sparsity().
get_jac_sparsity_gen()
template<bool fwd> Sparsity casadi::FunctionInternal::get_jac_sparsity_gen (casadi_int oind, casadi_int iind) const inherited
Definition at line 1118 of file function_internal.cpp.
{
     // Number of nonzero inputs and outputs
     casadi_int nz_in = nnz_in(iind);
     casadi_int nz_out = nnz_out(oind);
     // Evaluation buffers
     std::vector<typename JacSparsityTraits<fwd>::arg_t> arg(sz_arg(), nullptr);
     std::vector<bvec_t*> res(sz_res(), nullptr);
     std::vector<casadi_int> iw(sz_iw());
     std::vector<bvec_t> w(sz_w(), 0);
     // Seeds and sensitivities
     std::vector<bvec_t> seed(nz_in, 0);
     arg[iind] = get_ptr(seed);
     std::vector<bvec_t> sens(nz_out, 0);
     res[oind] = get_ptr(sens);
     if (!fwd) std::swap(seed, sens);
     // Number of forward sweeps we must make
     casadi_int nsweep = seed.size() / bvec_size;
     if (seed.size() % bvec_size) nsweep++;
     // Print
     if (verbose_) {
       casadi_message(str(nsweep) + std::string(fwd ? " forward" : " reverse") + " sweeps "
                      "needed for " + str(seed.size()) + " directions");
     }
     // Progress
     casadi_int progress = -10;
     // Temporary vectors
     std::vector<casadi_int> jcol, jrow;
     // Loop over the variables, bvec_size variables at a time
     for (casadi_int s=0; s<nsweep; ++s) {
       // Print progress
       if (verbose_) {
         casadi_int progress_new = (s*100)/nsweep;
         // Print when entering a new decade
         if (progress_new / 10 > progress / 10) {
           progress = progress_new;
           casadi_message(str(progress) + " %");
         }
       }
       // Nonzero offset
       casadi_int offset = s*bvec_size;
       // Number of local seed directions
       casadi_int ndir_local = seed.size()-offset;
       ndir_local = std::min(static_cast<casadi_int>(bvec_size), ndir_local);
       for (casadi_int i=0; i<ndir_local; ++i) {
         seed[offset+i] |= bvec_t(1)<<i;
       }
       // Propagate the dependencies
       JacSparsityTraits<fwd>::sp(this, get_ptr(arg), get_ptr(res),
                                   get_ptr(iw), get_ptr(w), memory(0));
       // Loop over the nonzeros of the output
       for (casadi_int el=0; el<sens.size(); ++el) {
         // Get the sparsity sensitivity
         bvec_t spsens = sens[el];
         if (!fwd) {
           // Clear the sensitivities for the next sweep
           sens[el] = 0;
         }
         // If there is a dependency in any of the directions
         if (spsens!=0) {
           // Loop over seed directions
           for (casadi_int i=0; i<ndir_local; ++i) {
             // If dependents on the variable
             if ((bvec_t(1) << i) & spsens) {
               // Add to pattern
               jcol.push_back(el);
               jrow.push_back(i+offset);
             }
           }
         }
       }
       // Remove the seeds
       for (casadi_int i=0; i<ndir_local; ++i) {
         seed[offset+i] = 0;
       }
     }
     // Construct sparsity pattern and return
     if (!fwd) swap(jrow, jcol);
     Sparsity ret = Sparsity::triplet(nz_out, nz_in, jcol, jrow);
     if (verbose_) {
       casadi_message("Formed Jacobian sparsity pattern (dimension " + str(ret.size()) + ", "
           + str(ret.nnz()) + " (" + str(ret.density()) + " %) nonzeros.");
     }
     return ret;
   }
References casadi::bvec_size, casadi::Sparsity::density(), casadi::get_ptr(), casadi::ProtoFunction::memory(), casadi::Sparsity::nnz(), casadi::FunctionInternal::nnz_in(), casadi::FunctionInternal::nnz_out(), casadi::FunctionInternal::nz_in(), casadi::FunctionInternal::nz_out(), casadi::Sparsity::size(), casadi::str(), casadi::FunctionInternal::sz_arg(), casadi::FunctionInternal::sz_iw(), casadi::FunctionInternal::sz_res(), casadi::FunctionInternal::sz_w(), casadi::Sparsity::triplet(), and casadi::ProtoFunction::verbose_.
get_jac_sparsity_hierarchical()
Sparsity casadi::FunctionInternal::get_jac_sparsity_hierarchical (casadi_int oind, casadi_int iind) const inherited
Decide which ad_mode to take
Definition at line 1458 of file function_internal.cpp.
{
     // Number of nonzero inputs
     casadi_int nz_in = nnz_in(iind);
     // Number of nonzero outputs
     casadi_int nz_out = nnz_out(oind);
     // Seeds and sensitivities
     std::vector<bvec_t> s_in(nz_in, 0);
     std::vector<bvec_t> s_out(nz_out, 0);
     // Evaluation buffers
     std::vector<const bvec_t*> arg_fwd(sz_arg(), nullptr);
     std::vector<bvec_t*> arg_adj(sz_arg(), nullptr);
     arg_fwd[iind] = arg_adj[iind] = get_ptr(s_in);
     std::vector<bvec_t*> res(sz_res(), nullptr);
     res[oind] = get_ptr(s_out);
     std::vector<casadi_int> iw(sz_iw());
     std::vector<bvec_t> w(sz_w());
     // Sparsity triplet accumulator
     std::vector<casadi_int> jcol, jrow;
     // Cols of the coarse blocks
     std::vector<casadi_int> coarse_col(2, 0); coarse_col[1] = nz_out;
     // Rows of the coarse blocks
     std::vector<casadi_int> coarse_row(2, 0); coarse_row[1] = nz_in;
     // Cols of the fine blocks
     std::vector<casadi_int> fine_col;
     // Rows of the fine blocks
     std::vector<casadi_int> fine_row;
     // In each iteration, subdivide each coarse block in this many fine blocks
     casadi_int subdivision = bvec_size;
     Sparsity r = Sparsity::dense(1, 1);
     // The size of a block
     casadi_int granularity_row = nz_in;
     casadi_int granularity_col = nz_out;
     bool use_fwd = true;
     casadi_int nsweeps = 0;
     bool hasrun = false;
     // Get weighting factor
     double sp_w = sp_weight();
     // Lookup table for bvec_t
     std::vector<bvec_t> bvec_lookup;
     bvec_lookup.reserve(bvec_size);
     for (casadi_int i=0;i<bvec_size;++i) {
       bvec_lookup.push_back(bvec_t(1) << i);
     }
     while (!hasrun || coarse_col.size()!=nz_out+1 || coarse_row.size()!=nz_in+1) {
       if (verbose_) {
         casadi_message("Block size: " + str(granularity_col) + " x " + str(granularity_row));
       }
       // Clear the sparsity triplet acccumulator
       jcol.clear();
       jrow.clear();
       // Clear the fine block structure
       fine_row.clear();
       fine_col.clear();
       // r transpose will be needed in the algorithm
       Sparsity rT = r.T();
       // Forward mode
       Sparsity D1 = rT.uni_coloring(r);
       // Adjoint mode
       Sparsity D2 = r.uni_coloring(rT);
       if (verbose_) {
         casadi_message("Coloring on " + str(r.dim()) + " (fwd seeps: " + str(D1.size2()) +
                  " , adj sweeps: " + str(D2.size1()) + ")");
       }
       // Use whatever required less colors if we tried both (with preference to forward mode)
       double fwd_cost = static_cast<double>(use_fwd ? granularity_row : granularity_col) *
         sp_w*static_cast<double>(D1.size2());
       double adj_cost = static_cast<double>(use_fwd ? granularity_col : granularity_row) *
         (1-sp_w)*static_cast<double>(D2.size2());
       use_fwd = fwd_cost <= adj_cost;
       if (verbose_) {
         casadi_message(std::string(use_fwd ? "Forward" : "Reverse") + " mode chosen "
             "(fwd cost: " + str(fwd_cost) + ", adj cost: " + str(adj_cost) + ")");
       }
       // Get seeds and sensitivities
       bvec_t* seed_v = use_fwd ? get_ptr(s_in) : get_ptr(s_out);
       bvec_t* sens_v = use_fwd ? get_ptr(s_out) : get_ptr(s_in);
       // The number of zeros in the seed and sensitivity directions
       casadi_int nz_seed = use_fwd ? nz_in  : nz_out;
       casadi_int nz_sens = use_fwd ? nz_out : nz_in;
       // Clear the seeds
       for (casadi_int i=0; i<nz_seed; ++i) seed_v[i]=0;
       // Choose the active jacobian coloring scheme
       Sparsity D = use_fwd ? D1 : D2;
       // Adjoint mode amounts to swapping
       if (!use_fwd) {
         std::swap(coarse_col, coarse_row);
         std::swap(granularity_col, granularity_row);
         std::swap(r, rT);
       }
       // Subdivide the coarse block cols
       for (casadi_int k=0;k<coarse_col.size()-1;++k) {
         casadi_int diff = coarse_col[k+1]-coarse_col[k];
         casadi_int new_diff = diff/subdivision;
         if (diff%subdivision>0) new_diff++;
         std::vector<casadi_int> temp = range(coarse_col[k], coarse_col[k+1], new_diff);
         fine_col.insert(fine_col.end(), temp.begin(), temp.end());
       }
       // Subdivide the coarse block rows
       for (casadi_int k=0;k<coarse_row.size()-1;++k) {
         casadi_int diff = coarse_row[k+1]-coarse_row[k];
         casadi_int new_diff = diff/subdivision;
         if (diff%subdivision>0) new_diff++;
         std::vector<casadi_int> temp = range(coarse_row[k], coarse_row[k+1], new_diff);
         fine_row.insert(fine_row.end(), temp.begin(), temp.end());
       }
       if (fine_row.back()!=coarse_row.back()) fine_row.push_back(coarse_row.back());
       if (fine_col.back()!=coarse_col.back()) fine_col.push_back(coarse_col.back());
       granularity_col = fine_col[1] - fine_col[0];
       granularity_row = fine_row[1] - fine_row[0];
       // The index into the bvec bit vector
       casadi_int bvec_i = 0;
       // Create lookup tables for the fine blocks
       std::vector<casadi_int> fine_col_lookup = lookupvector(fine_col, nz_sens+1);
       std::vector<casadi_int> fine_row_lookup = lookupvector(fine_row, nz_seed+1);
       // Triplet data used as a lookup table
       std::vector<casadi_int> lookup_col;
       std::vector<casadi_int> lookup_row;
       std::vector<casadi_int> lookup_value;
       // The maximum number of fine blocks contained in one coarse block
       casadi_int n_fine_blocks_max = 0;
       for (casadi_int i=0;i<coarse_row.size()-1;++i) {
         casadi_int del = fine_row_lookup[coarse_row[i+1]]-fine_row_lookup[coarse_row[i]];
         n_fine_blocks_max = std::max(n_fine_blocks_max, del);
       }
       // Loop over all coarse seed directions from the coloring
       for (casadi_int csd=0; csd<D.size2(); ++csd) {
         casadi_int fci_offset = 0;
         casadi_int fci_cap = bvec_size-bvec_i;
         // Flag to indicate if all fine blocks have been handled
         bool f_finished = false;
         // Loop while not finished
         while (!f_finished) {
           // Loop over all coarse rows that are found in the coloring for this coarse seed direction
           for (casadi_int k=D.colind(csd); k<D.colind(csd+1); ++k) {
             casadi_int cci = D.row(k);
             // The first and last rows of the fine block
             casadi_int fci_start = fine_row_lookup[coarse_row[cci]];
             casadi_int fci_end   = fine_row_lookup[coarse_row[cci+1]];
             // Local counter that modifies index into bvec
             casadi_int bvec_i_mod = 0;
             casadi_int value = -bvec_i + fci_offset + fci_start;
             // Loop over the rows of the fine block
             for (casadi_int fci = fci_offset; fci < std::min(fci_end-fci_start, fci_cap); ++fci) {
               // Loop over the coarse block cols that appear in the coloring
               // for the current coarse seed direction
               for (casadi_int cri=rT.colind(cci);cri<rT.colind(cci+1);++cri) {
                 lookup_col.push_back(rT.row(cri));
                 lookup_row.push_back(bvec_i+bvec_i_mod);
                 lookup_value.push_back(value);
               }
               // Toggle on seeds
               bvec_toggle(seed_v, fine_row[fci+fci_start], fine_row[fci+fci_start+1],
                           bvec_i+bvec_i_mod);
               bvec_i_mod++;
             }
           }
           // Bump bvec_i for next major coarse direction
           bvec_i+= std::min(n_fine_blocks_max, fci_cap);
           // Check if bvec buffer is full
           if (bvec_i==bvec_size || csd==D.size2()-1) {
             // Calculate sparsity for bvec_size directions at once
             // Statistics
             nsweeps+=1;
             // Construct lookup table
             IM lookup = IM::triplet(lookup_row, lookup_col, lookup_value, bvec_size,
                                     coarse_col.size());
             // Propagate the dependencies
             if (use_fwd) {
               JacSparsityTraits<true>::sp(this, get_ptr(arg_fwd), get_ptr(res),
                 get_ptr(iw), get_ptr(w), memory(0));
             } else {
               std::fill(w.begin(), w.end(), 0);
               JacSparsityTraits<false>::sp(this, get_ptr(arg_adj), get_ptr(res),
                 get_ptr(iw), get_ptr(w), memory(0));
             }
             // Temporary bit work vector
             bvec_t spsens;
             // Loop over the cols of coarse blocks
             for (casadi_int cri=0;cri<coarse_col.size()-1;++cri) {
               // Loop over the cols of fine blocks within the current coarse block
               for (casadi_int fri=fine_col_lookup[coarse_col[cri]];
                    fri<fine_col_lookup[coarse_col[cri+1]];++fri) {
                 // Lump individual sensitivities together into fine block
                 bvec_or(sens_v, spsens, fine_col[fri], fine_col[fri+1]);
                 // Next iteration if no sparsity
                 if (!spsens) continue;
                 // Loop over all bvec_bits
                 for (casadi_int bvec_i=0;bvec_i<bvec_size;++bvec_i) {
                   if (spsens & bvec_lookup[bvec_i]) {
                     // if dependency is found, add it to the new sparsity pattern
                     casadi_int ind = lookup.sparsity().get_nz(bvec_i, cri);
                     if (ind==-1) continue;
                     jrow.push_back(bvec_i+lookup->at(ind));
                     jcol.push_back(fri);
                   }
                 }
               }
             }
             // Clear the forward seeds/adjoint sensitivities, ready for next bvec sweep
             std::fill(s_in.begin(), s_in.end(), 0);
             // Clear the adjoint seeds/forward sensitivities, ready for next bvec sweep
             std::fill(s_out.begin(), s_out.end(), 0);
             // Clean lookup table
             lookup_col.clear();
             lookup_row.clear();
             lookup_value.clear();
           }
           if (n_fine_blocks_max>fci_cap) {
             fci_offset += std::min(n_fine_blocks_max, fci_cap);
             bvec_i = 0;
             fci_cap = bvec_size;
           } else {
             f_finished = true;
           }
         }
       }
       // Swap results if adjoint mode was used
       if (use_fwd) {
         // Construct fine sparsity pattern
         r = Sparsity::triplet(fine_row.size()-1, fine_col.size()-1, jrow, jcol);
         coarse_col = fine_col;
         coarse_row = fine_row;
       } else {
         // Construct fine sparsity pattern
         r = Sparsity::triplet(fine_col.size()-1, fine_row.size()-1, jcol, jrow);
         coarse_col = fine_row;
         coarse_row = fine_col;
       }
       hasrun = true;
     }
     if (verbose_) {
       casadi_message("Number of sweeps: " + str(nsweeps));
       casadi_message("Formed Jacobian sparsity pattern (dimension " + str(r.size()) + ", " +
           str(r.nnz()) + " (" + str(r.density()) + " %) nonzeros.");
     }
     return r.T();
   }
References casadi::bvec_or(), casadi::bvec_size, casadi::bvec_toggle(), casadi::Sparsity::colind(), casadi::Sparsity::dense(), casadi::Sparsity::density(), casadi::diff(), casadi::Sparsity::dim(), casadi::Sparsity::get_nz(), casadi::get_ptr(), casadi::lookupvector(), casadi::ProtoFunction::memory(), casadi::Sparsity::nnz(), casadi::FunctionInternal::nnz_in(), casadi::FunctionInternal::nnz_out(), casadi::FunctionInternal::nz_in(), casadi::FunctionInternal::nz_out(), casadi::range(), casadi::Sparsity::row(), casadi::Sparsity::size(), casadi::Sparsity::size1(), casadi::Sparsity::size2(), casadi::FunctionInternal::sp_weight(), casadi::Matrix< Scalar >::sparsity(), casadi::str(), casadi::FunctionInternal::sz_arg(), casadi::FunctionInternal::sz_iw(), casadi::FunctionInternal::sz_res(), casadi::FunctionInternal::sz_w(), casadi::Sparsity::T(), casadi::Sparsity::triplet(), casadi::Matrix< casadi_int >::triplet(), casadi::Sparsity::uni_coloring(), and casadi::ProtoFunction::verbose_.
Referenced by casadi::FunctionInternal::get_jac_sparsity().
get_jac_sparsity_hierarchical_symm()
Sparsity casadi::FunctionInternal::get_jac_sparsity_hierarchical_symm (casadi_int oind, casadi_int iind) const inherited
A flavor of get_jac_sparsity_gen that does hierarchical block structure recognition for symmetric Jacobians
Definition at line 1223 of file function_internal.cpp.
{
     casadi_assert_dev(has_spfwd());
     // Number of nonzero inputs
     casadi_int nz = nnz_in(iind);
     casadi_assert_dev(nz==nnz_out(oind));
     // Evaluation buffers
     std::vector<const bvec_t*> arg(sz_arg(), nullptr);
     std::vector<bvec_t*> res(sz_res(), nullptr);
     std::vector<casadi_int> iw(sz_iw());
     std::vector<bvec_t> w(sz_w());
     // Seeds
     std::vector<bvec_t> seed(nz, 0);
     arg[iind] = get_ptr(seed);
     // Sensitivities
     std::vector<bvec_t> sens(nz, 0);
     res[oind] = get_ptr(sens);
     // Sparsity triplet accumulator
     std::vector<casadi_int> jcol, jrow;
     // Cols/rows of the coarse blocks
     std::vector<casadi_int> coarse(2, 0); coarse[1] = nz;
     // Cols/rows of the fine blocks
     std::vector<casadi_int> fine;
     // In each iteration, subdivide each coarse block in this many fine blocks
     casadi_int subdivision = bvec_size;
     Sparsity r = Sparsity::dense(1, 1);
     // The size of a block
     casadi_int granularity = nz;
     casadi_int nsweeps = 0;
     bool hasrun = false;
     while (!hasrun || coarse.size()!=nz+1) {
       if (verbose_) casadi_message("Block size: " + str(granularity));
       // Clear the sparsity triplet acccumulator
       jcol.clear();
       jrow.clear();
       // Clear the fine block structure
       fine.clear();
       Sparsity D = r.star_coloring();
       if (verbose_) {
         casadi_message("Star coloring on " + str(r.dim()) + ": "
           + str(D.size2()) + " <-> " + str(D.size1()));
       }
       // Clear the seeds
       std::fill(seed.begin(), seed.end(), 0);
       // Subdivide the coarse block
       for (casadi_int k=0; k<coarse.size()-1; ++k) {
         casadi_int diff = coarse[k+1]-coarse[k];
         casadi_int new_diff = diff/subdivision;
         if (diff%subdivision>0) new_diff++;
         std::vector<casadi_int> temp = range(coarse[k], coarse[k+1], new_diff);
         fine.insert(fine.end(), temp.begin(), temp.end());
       }
       if (fine.back()!=coarse.back()) fine.push_back(coarse.back());
       granularity = fine[1] - fine[0];
       // The index into the bvec bit vector
       casadi_int bvec_i = 0;
       // Create lookup tables for the fine blocks
       std::vector<casadi_int> fine_lookup = lookupvector(fine, nz+1);
       // Triplet data used as a lookup table
       std::vector<casadi_int> lookup_col;
       std::vector<casadi_int> lookup_row;
       std::vector<casadi_int> lookup_value;
       // The maximum number of fine blocks contained in one coarse block
       casadi_int n_fine_blocks_max = 0;
       for (casadi_int i=0;i<coarse.size()-1;++i) {
         casadi_int del = fine_lookup[coarse[i+1]]-fine_lookup[coarse[i]];
         n_fine_blocks_max = std::max(n_fine_blocks_max, del);
       }
       // Loop over all coarse seed directions from the coloring
       for (casadi_int csd=0; csd<D.size2(); ++csd) {
         casadi_int fci_offset = 0;
         casadi_int fci_cap = bvec_size-bvec_i;
         // Flag to indicate if all fine blocks have been handled
         bool f_finished = false;
         // Loop while not finished
         while (!f_finished) {
           // Loop over all coarse rows that are found in the coloring for this coarse seed direction
           for (casadi_int k=D.colind(csd); k<D.colind(csd+1); ++k) {
             casadi_int cci = D.row(k);
             // The first and last rows of the fine block
             casadi_int fci_start = fine_lookup[coarse[cci]];
             casadi_int fci_end   = fine_lookup[coarse[cci+1]];
             // Local counter that modifies index into bvec
             casadi_int bvec_i_mod = 0;
             casadi_int value = -bvec_i + fci_offset + fci_start;
             //casadi_assert_dev(value>=0);
             // Loop over the rows of the fine block
             for (casadi_int fci = fci_offset; fci<std::min(fci_end-fci_start, fci_cap); ++fci) {
               // Loop over the coarse block cols that appear in the
               // coloring for the current coarse seed direction
               for (casadi_int cri=r.colind(cci);cri<r.colind(cci+1);++cri) {
                 lookup_col.push_back(r.row(cri));
                 lookup_row.push_back(bvec_i+bvec_i_mod);
                 lookup_value.push_back(value);
               }
               // Toggle on seeds
               bvec_toggle(get_ptr(seed), fine[fci+fci_start], fine[fci+fci_start+1],
                           bvec_i+bvec_i_mod);
               bvec_i_mod++;
             }
           }
           // Bump bvec_i for next major coarse direction
           bvec_i += std::min(n_fine_blocks_max, fci_cap);
           // Check if bvec buffer is full
           if (bvec_i==bvec_size || csd==D.size2()-1) {
             // Calculate sparsity for bvec_size directions at once
             // Statistics
             nsweeps+=1;
             // Construct lookup table
             IM lookup = IM::triplet(lookup_row, lookup_col, lookup_value,
                                     bvec_size, coarse.size());
             std::reverse(lookup_col.begin(), lookup_col.end());
             std::reverse(lookup_row.begin(), lookup_row.end());
             std::reverse(lookup_value.begin(), lookup_value.end());
             IM duplicates =
               IM::triplet(lookup_row, lookup_col, lookup_value, bvec_size, coarse.size())
               - lookup;
             duplicates = sparsify(duplicates);
             lookup(duplicates.sparsity()) = -bvec_size;
             // Propagate the dependencies
             JacSparsityTraits<true>::sp(this, get_ptr(arg), get_ptr(res),
               get_ptr(iw), get_ptr(w), nullptr);
             // Temporary bit work vector
             bvec_t spsens;
             // Loop over the cols of coarse blocks
             for (casadi_int cri=0; cri<coarse.size()-1; ++cri) {
               // Loop over the cols of fine blocks within the current coarse block
               for (casadi_int fri=fine_lookup[coarse[cri]];fri<fine_lookup[coarse[cri+1]];++fri) {
                 // Lump individual sensitivities together into fine block
                 bvec_or(get_ptr(sens), spsens, fine[fri], fine[fri+1]);
                 // Loop over all bvec_bits
                 for (casadi_int bvec_i=0;bvec_i<bvec_size;++bvec_i) {
                   if (spsens & (bvec_t(1) << bvec_i)) {
                     // if dependency is found, add it to the new sparsity pattern
                     casadi_int ind = lookup.sparsity().get_nz(bvec_i, cri);
                     if (ind==-1) continue;
                     casadi_int lk = lookup->at(ind);
                     if (lk>-bvec_size) {
                       jrow.push_back(bvec_i+lk);
                       jcol.push_back(fri);
                       jrow.push_back(fri);
                       jcol.push_back(bvec_i+lk);
                     }
                   }
                 }
               }
             }
             // Clear the forward seeds/adjoint sensitivities, ready for next bvec sweep
             std::fill(seed.begin(), seed.end(), 0);
             // Clean lookup table
             lookup_col.clear();
             lookup_row.clear();
             lookup_value.clear();
           }
           if (n_fine_blocks_max>fci_cap) {
             fci_offset += std::min(n_fine_blocks_max, fci_cap);
             bvec_i = 0;
             fci_cap = bvec_size;
           } else {
             f_finished = true;
           }
         }
       }
       // Construct fine sparsity pattern
       r = Sparsity::triplet(fine.size()-1, fine.size()-1, jrow, jcol);
       // There may be false positives here that are not present
       // in the reverse mode that precedes it.
       // This can lead to an assymetrical result
       //  cf. #1522
       r=r*r.T();
       coarse = fine;
       hasrun = true;
     }
     if (verbose_) {
       casadi_message("Number of sweeps: " + str(nsweeps));
       casadi_message("Formed Jacobian sparsity pattern (dimension " + str(r.size()) +
           ", " + str(r.nnz()) + " (" + str(r.density()) + " %) nonzeros.");
     }
     return r.T();
   }
References casadi::bvec_or(), casadi::bvec_size, casadi::bvec_toggle(), casadi::Sparsity::colind(), casadi::Sparsity::dense(), casadi::Sparsity::density(), casadi::diff(), casadi::Sparsity::dim(), casadi::Sparsity::get_nz(), casadi::get_ptr(), casadi::FunctionInternal::has_spfwd(), casadi::lookupvector(), casadi::Sparsity::nnz(), casadi::FunctionInternal::nnz_in(), casadi::FunctionInternal::nnz_out(), casadi::range(), casadi::Sparsity::row(), casadi::Sparsity::size(), casadi::Sparsity::size1(), casadi::Sparsity::size2(), casadi::Matrix< Scalar >::sparsity(), casadi::Sparsity::star_coloring(), casadi::str(), casadi::FunctionInternal::sz_arg(), casadi::FunctionInternal::sz_iw(), casadi::FunctionInternal::sz_res(), casadi::FunctionInternal::sz_w(), casadi::Sparsity::T(), casadi::Sparsity::triplet(), casadi::Matrix< casadi_int >::triplet(), and casadi::ProtoFunction::verbose_.
Referenced by casadi::FunctionInternal::get_jac_sparsity().
get_jacobian()
Function casadi::FunctionInternal::get_jacobian (const std::string & name, const std::vector< std::string > & inames, const std::vector< std::string > & onames, const Dict & opts) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ky
Reimplemented in casadi::LinearInterpolantJac, casadi::LinearInterpolant, casadi::BSplineInterpolant, casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >, casadi::JitFunction, casadi::FmuFunction, casadi::External, and casadi::CallbackInternal.
Definition at line 2267 of file function_internal.cpp.
{
     casadi_error("'get_jacobian' not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
Referenced by casadi::External::get_jacobian(), casadi::BSplineInterpolant::get_jacobian(), casadi::LinearInterpolantJac::get_jacobian(), and casadi::FunctionInternal::jacobian().
get_max_in()
virtual double casadi::FunctionInternal::get_max_in (casadi_int ind) const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mm
Definition at line 1026 of file function_internal.hpp.
{
       return inf;
     }
References casadi::inf.
get_min_in()
virtual double casadi::FunctionInternal::get_min_in (casadi_int ind) const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mn
Definition at line 1033 of file function_internal.hpp.
{
       return -inf;
     }
References casadi::inf.
get_n_in()
size_t casadi::Conic::get_n_in () inline override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1j6
Reimplemented from casadi::FunctionInternal.
Definition at line 59 of file conic_impl.hpp.
 { return CONIC_NUM_IN;}
References casadi::CONIC_NUM_IN.
get_n_out()
size_t casadi::Conic::get_n_out () inline override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1j6
Reimplemented from casadi::FunctionInternal.
Definition at line 60 of file conic_impl.hpp.
 { return CONIC_NUM_OUT;}
References casadi::CONIC_NUM_OUT.
get_name_in()
std::string casadi::Conic::get_name_in (casadi_int i) inline override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1j8
Reimplemented from casadi::FunctionInternal.
Definition at line 75 of file conic_impl.hpp.
 { return conic_in(i);}
References casadi::conic_in().
get_name_out()
std::string casadi::Conic::get_name_out (casadi_int i) inline override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1j8
Reimplemented from casadi::FunctionInternal.
Definition at line 76 of file conic_impl.hpp.
 { return conic_out(i);}
References casadi::conic_out().
get_nominal_in()
virtual std::vector<double> casadi::FunctionInternal::get_nominal_in (casadi_int ind) const inline virtual inherited
Reimplemented in casadi::FmuFunction.
Definition at line 1037 of file function_internal.hpp.
{
       return std::vector<double>(nnz_in(ind), 1.);
     }
Referenced by casadi::FmuFunction::get_nominal_in().
get_nominal_out()
virtual std::vector<double> casadi::FunctionInternal::get_nominal_out (casadi_int ind) const inline virtual inherited
Reimplemented in casadi::FmuFunction.
Definition at line 1041 of file function_internal.hpp.
{
       return std::vector<double>(nnz_out(ind), 1.);
     }
Referenced by casadi::FmuFunction::get_nominal_out().
get_options()
const Options& casadi::QpoasesInterface::get_options () const inline override virtual
Reimplemented from casadi::Conic.
Definition at line 125 of file qpoases_interface.hpp.
 { return options_;}
get_partition()
void casadi::FunctionInternal::get_partition (casadi_int iind, casadi_int oind, Sparsity & D1, Sparsity & D2, bool compact, bool symmetric, bool allow_forward, bool allow_reverse) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_md
Definition at line 1904 of file function_internal.cpp.
{
     if (verbose_) casadi_message(name_ + "::get_partition");
     casadi_assert(allow_forward || allow_reverse, "Inconsistent options");
     // Sparsity pattern with transpose
     Sparsity &AT = jac_sparsity(oind, iind, compact, symmetric);
     Sparsity A = symmetric ? AT : AT.T();
     // Get seed matrices by graph coloring
     if (symmetric) {
       casadi_assert_dev(enable_forward_ || enable_fd_);
       casadi_assert_dev(allow_forward);
       // Star coloring if symmetric
       if (verbose_) casadi_message("FunctionInternal::getPartition star_coloring");
       D1 = A.star_coloring();
       if (verbose_) {
         casadi_message("Star coloring completed: " + str(D1.size2())
           + " directional derivatives needed ("
                  + str(A.size1()) + " without coloring).");
       }
     } else {
       casadi_assert_dev(enable_forward_ || enable_fd_ || enable_reverse_);
       // Get weighting factor
       double w = ad_weight();
       // Which AD mode?
       if (w==1) allow_forward = false;
       if (w==0) allow_reverse = false;
       casadi_assert(allow_forward || allow_reverse, "Conflicting ad weights");
       // Best coloring encountered so far (relatively tight upper bound)
       double best_coloring = std::numeric_limits<double>::infinity();
       // Test forward mode first?
       bool test_fwd_first = allow_forward && w*static_cast<double>(A.size1()) <=
         (1-w)*static_cast<double>(A.size2());
       casadi_int mode_fwd = test_fwd_first ? 0 : 1;
       // Test both coloring modes
       for (casadi_int mode=0; mode<2; ++mode) {
         // Is this the forward mode?
         bool fwd = mode==mode_fwd;
         // Skip?
         if (!allow_forward && fwd) continue;
         if (!allow_reverse && !fwd) continue;
         // Perform the coloring
         if (fwd) {
           if (verbose_) casadi_message("Unidirectional coloring (forward mode)");
           bool d = best_coloring>=w*static_cast<double>(A.size1());
           casadi_int max_colorings_to_test =
             d ? A.size1() : static_cast<casadi_int>(floor(best_coloring/w));
           D1 = AT.uni_coloring(A, max_colorings_to_test);
           if (D1.is_null()) {
             if (verbose_) {
               casadi_message("Forward mode coloring interrupted (more than "
                              + str(max_colorings_to_test) + " needed).");
             }
           } else {
             if (verbose_) {
               casadi_message("Forward mode coloring completed: "
                              + str(D1.size2()) + " directional derivatives needed ("
                              + str(A.size1()) + " without coloring).");
             }
             D2 = Sparsity();
             best_coloring = w*static_cast<double>(D1.size2());
           }
         } else {
           if (verbose_) casadi_message("Unidirectional coloring (adjoint mode)");
           bool d = best_coloring>=(1-w)*static_cast<double>(A.size2());
           casadi_int max_colorings_to_test =
             d ? A.size2() : static_cast<casadi_int>(floor(best_coloring/(1-w)));
           D2 = A.uni_coloring(AT, max_colorings_to_test);
           if (D2.is_null()) {
             if (verbose_) {
               casadi_message("Adjoint mode coloring interrupted (more than "
                             + str(max_colorings_to_test) + " needed).");
             }
           } else {
             if (verbose_) {
               casadi_message("Adjoint mode coloring completed: "
                              + str(D2.size2()) + " directional derivatives needed ("
                              + str(A.size2()) + " without coloring).");
             }
             D1 = Sparsity();
             best_coloring = (1-w)*static_cast<double>(D2.size2());
           }
         }
       }
     }
   }
References casadi::FunctionInternal::ad_weight(), casadi::FunctionInternal::enable_fd_, casadi::FunctionInternal::enable_forward_, casadi::FunctionInternal::enable_reverse_, casadi::SharedObject::is_null(), casadi::FunctionInternal::jac_sparsity(), casadi::ProtoFunction::name_, casadi::Sparsity::size1(), casadi::Sparsity::size2(), casadi::Sparsity::star_coloring(), casadi::str(), casadi::Sparsity::T(), casadi::Sparsity::uni_coloring(), and casadi::ProtoFunction::verbose_.
get_reltol()
virtual double casadi::FunctionInternal::get_reltol () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mo
Reimplemented in casadi::SundialsInterface.
Definition at line 1048 of file function_internal.hpp.
{
       return eps;
     }
References casadi::eps.
Referenced by casadi::FiniteDiff::init().
get_reverse()
Function casadi::FunctionInternal::get_reverse (casadi_int nadj, const std::string & name, const std::vector< std::string > & inames, const std::vector< std::string > & onames, const Dict & opts) const virtual inherited
reverse(nadj) returns a cached instance if available, and calls Function get_reverse(casadi_int nadj) if no cached version is available.
Extra doc: https://github.com/casadi/casadi/wiki/L_l1
Reimplemented in casadi::BSplineInterpolant, casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >, casadi::Switch, casadi::Rootfinder, casadi::Nlpsol, casadi::MapSum, casadi::Map, casadi::Integrator, casadi::FmuFunction, casadi::External, casadi::Expm, casadi::Dple, and casadi::CallbackInternal.
Definition at line 2162 of file function_internal.cpp.
{
     casadi_error("'get_reverse' not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
Referenced by casadi::BSplineInterpolant::get_reverse(), and casadi::FunctionInternal::reverse().
get_sparsity_in()
Sparsity casadi::Conic::get_sparsity_in (casadi_int i) override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1j7
Reimplemented from casadi::FunctionInternal.
Definition at line 354 of file conic.cpp.
{
     switch (static_cast<ConicInput>(i)) {
     case CONIC_X0:
     case CONIC_G:
     case CONIC_LBX:
     case CONIC_UBX:
     case CONIC_LAM_X0:
       return get_sparsity_out(CONIC_X);
     case CONIC_Q:
       return Q_;
     case CONIC_P:
       return P_;
     case CONIC_LBA:
     case CONIC_UBA:
     case CONIC_LAM_A0:
       return get_sparsity_out(CONIC_LAM_A);
     case CONIC_A:
       return A_;
     case CONIC_H:
       return H_;
     case CONIC_NUM_IN: break;
     }
     return Sparsity();
   }
References casadi::Conic::A_, casadi::CONIC_A, casadi::CONIC_G, casadi::CONIC_H, casadi::CONIC_LAM_A, casadi::CONIC_LAM_A0, casadi::CONIC_LAM_X0, casadi::CONIC_LBA, casadi::CONIC_LBX, casadi::CONIC_NUM_IN, casadi::CONIC_P, casadi::CONIC_Q, casadi::CONIC_UBA, casadi::CONIC_UBX, casadi::CONIC_X, casadi::CONIC_X0, casadi::Conic::get_sparsity_out(), casadi::Conic::H_, casadi::Conic::P_, and casadi::Conic::Q_.
get_sparsity_out()
Sparsity casadi::Conic::get_sparsity_out (casadi_int i) override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1j7
Reimplemented from casadi::FunctionInternal.
Definition at line 379 of file conic.cpp.
{
     switch (static_cast<ConicOutput>(i)) {
     case CONIC_COST:
       return Sparsity::scalar();
     case CONIC_X:
     case CONIC_LAM_X:
       return Sparsity::dense(nx_, 1);
     case CONIC_LAM_A:
       return Sparsity::dense(na_, 1);
     case CONIC_NUM_OUT: break;
     }
     return Sparsity();
   }
References casadi::CONIC_COST, casadi::CONIC_LAM_A, casadi::CONIC_LAM_X, casadi::CONIC_NUM_OUT, casadi::CONIC_X, casadi::Sparsity::dense(), casadi::Conic::na_, casadi::Conic::nx_, and casadi::Sparsity::scalar().
Referenced by casadi::Conic::get_sparsity_in().
get_stats()
Dict casadi::QpoasesInterface::get_stats (void * mem) const override virtual
Reimplemented from casadi::Conic.
Definition at line 933 of file qpoases_interface.cpp.
{
     Dict stats = Conic::get_stats(mem);
     auto m = static_cast<QpoasesMemory*>(mem);
     stats["return_status"] = getErrorMessage(m->return_status);
     return stats;
   }
References casadi::Conic::get_stats(), and getErrorMessage().
getAdaptorSolverName()
virtual std::string casadi::FunctionInternal::getAdaptorSolverName () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_k3
Definition at line 292 of file function_internal.hpp.
 { return ""; }
getCount()
casadi_int casadi::SharedObjectInternal::getCount () const inherited
Definition at line 58 of file shared_object_internal.cpp.
{
     return count;
   }
getErrorMessage()
std::string casadi::QpoasesInterface::getErrorMessage (casadi_int flag) static protected
Definition at line 492 of file qpoases_interface.cpp.
{
     switch (flag) {
     case qpOASES::SUCCESSFUL_RETURN:
       return "Successful return.";
     case qpOASES::RET_DIV_BY_ZERO:
       return "Division by zero.";
     case qpOASES::RET_INDEX_OUT_OF_BOUNDS:
       return "Index out of bounds.";
     case qpOASES::RET_INVALID_ARGUMENTS:
       return "At least one of the arguments is invalid.";
     case qpOASES::RET_ERROR_UNDEFINED:
       return "Error number undefined.";
     case qpOASES::RET_WARNING_UNDEFINED:
       return "Warning number undefined.";
     case qpOASES::RET_INFO_UNDEFINED:
       return "Info number undefined.";
     case qpOASES::RET_EWI_UNDEFINED:
       return "Error/warning/info number undefined.";
     case qpOASES::RET_AVAILABLE_WITH_LINUX_ONLY:
       return "This function is available under Linux only.";
     case qpOASES::RET_UNKNOWN_BUG:
       return "The error occured is not yet known.";
     case qpOASES::RET_PRINTLEVEL_CHANGED:
       return "Print level changed.";
     case qpOASES::RET_NOT_YET_IMPLEMENTED:
       return "Requested function is not yet implemented in this version of qpOASES.";
       // Indexlist
     case qpOASES::RET_INDEXLIST_MUST_BE_REORDERD:
       return "Index list has to be reordered.";
     case qpOASES::RET_INDEXLIST_EXCEEDS_MAX_LENGTH:
       return "Index list exceeds its maximal physical length.";
     case qpOASES::RET_INDEXLIST_CORRUPTED:
       return "Index list corrupted.";
     case qpOASES::RET_INDEXLIST_OUTOFBOUNDS:
       return "Physical index is out of bounds.";
     case qpOASES::RET_INDEXLIST_ADD_FAILED:
       return "Adding indices from another index set failed.";
     case qpOASES::RET_INDEXLIST_INTERSECT_FAILED:
       return "Intersection with another index set failed.";
       // SubjectTo / Bounds / Constraints
     case qpOASES::RET_INDEX_ALREADY_OF_DESIRED_STATUS:
       return "Index is already of desired status.";
     case qpOASES::RET_ADDINDEX_FAILED:
       return "Adding index to index set failed.";
     case qpOASES::RET_REMOVEINDEX_FAILED:
       return "Removing index from index set failed.";
     case qpOASES::RET_SWAPINDEX_FAILED:
       return "Cannot swap between different indexsets.";
     case qpOASES::RET_NOTHING_TO_DO:
       return "Nothing to do.";
     case qpOASES::RET_SETUP_BOUND_FAILED:
       return "Setting up bound index failed.";
     case qpOASES::RET_SETUP_CONSTRAINT_FAILED:
       return "Setting up constraint index failed.";
     case qpOASES::RET_MOVING_BOUND_FAILED:
       return "Moving bound between index sets failed.";
     case qpOASES::RET_MOVING_CONSTRAINT_FAILED:
       return "Moving constraint between index sets failed.";
     case qpOASES::RET_SHIFTING_FAILED:
       return "Shifting of bounds/constraints failed.";
     case qpOASES::RET_ROTATING_FAILED:
       return "Rotating of bounds/constraints failed.";
       // QProblem
     case qpOASES::RET_QPOBJECT_NOT_SETUP:
       return "The QP object has not been setup correctly, use another constructor.";
     case qpOASES::RET_QP_ALREADY_INITIALISED:
       return "QProblem has already been initialized.";
     case qpOASES::RET_NO_INIT_WITH_STANDARD_SOLVER:
       return "Initialisation via extern QP solver is not yet implemented.";
     case qpOASES::RET_RESET_FAILED:
       return "Reset failed.";
     case qpOASES::RET_INIT_FAILED:
       return "Initialisation failed.";
     case qpOASES::RET_INIT_FAILED_TQ:
       return "Initialisation failed due to TQ factorisation.";
     case qpOASES::RET_INIT_FAILED_CHOLESKY:
       return "Initialisation failed due to Cholesky decomposition.";
     case qpOASES::RET_INIT_FAILED_HOTSTART:
       return "Initialisation failed! QP could not be solved!";
     case qpOASES::RET_INIT_FAILED_INFEASIBILITY:
       return "Initial QP could not be solved due to infeasibility!";
     case qpOASES::RET_INIT_FAILED_UNBOUNDEDNESS:
       return "Initial QP could not be solved due to unboundedness!";
     case qpOASES::RET_INIT_SUCCESSFUL:
       return "Initialisation done.";
     case qpOASES::RET_OBTAINING_WORKINGSET_FAILED:
       return "Failed to obtain working set for auxiliary QP.";
     case qpOASES::RET_SETUP_WORKINGSET_FAILED:
       return "Failed to setup working set for auxiliary QP.";
     case qpOASES::RET_SETUP_AUXILIARYQP_FAILED:
       return "Failed to setup auxiliary QP for initialized homotopy.";
     case qpOASES::RET_NO_EXTERN_SOLVER:
       return "No extern QP solver available.";
     case qpOASES::RET_QP_UNBOUNDED:
       return "QP is unbounded.";
     case qpOASES::RET_QP_INFEASIBLE:
       return "QP is infeasible.";
     case qpOASES::RET_QP_NOT_SOLVED:
       return "Problems occured while solving QP with standard solver.";
     case qpOASES::RET_QP_SOLVED:
       return "QP successfully solved.";
     case qpOASES::RET_UNABLE_TO_SOLVE_QP:
       return "Problems occured while solving QP.";
     case qpOASES::RET_INITIALISATION_STARTED:
       return "Starting problem initialisation.";
     case qpOASES::RET_HOTSTART_FAILED:
       return "Unable to perform homotopy due to internal error.";
     case qpOASES::RET_HOTSTART_FAILED_TO_INIT:
       return "Unable to initialise problem.";
     case qpOASES::RET_HOTSTART_FAILED_AS_QP_NOT_INITIALISED:
       return "Unable to perform homotopy as previous QP is not solved.";
     case qpOASES::RET_ITERATION_STARTED:
       return "Iteration...";
     case qpOASES::RET_SHIFT_DETERMINATION_FAILED:
       return "Determination of shift of the QP data failed.";
     case qpOASES::RET_STEPDIRECTION_DETERMINATION_FAILED:
       return "Determination of step direction failed.";
     case qpOASES::RET_STEPLENGTH_DETERMINATION_FAILED:
       return "Determination of step direction failed.";
     case qpOASES::RET_OPTIMAL_SOLUTION_FOUND:
       return "Optimal solution of neighbouring QP found.";
     case qpOASES::RET_HOMOTOPY_STEP_FAILED:
       return "Unable to perform homotopy step.";
     case qpOASES::RET_HOTSTART_STOPPED_INFEASIBILITY:
       return "Premature homotopy termination because QP is infeasible.";
     case qpOASES::RET_HOTSTART_STOPPED_UNBOUNDEDNESS:
       return "Premature homotopy termination because QP is unbounded.";
     case qpOASES::RET_WORKINGSET_UPDATE_FAILED:
       return "Unable to update working sets according to initial guesses.";
     case qpOASES::RET_MAX_NWSR_REACHED:
       return "Maximum number of working set recalculations performed.";
     case qpOASES::RET_CONSTRAINTS_NOT_SPECIFIED:
       return "Problem does comprise constraints! "
         "You also have to specify new constraints' bounds.";
     case qpOASES::RET_INVALID_FACTORISATION_FLAG:
       return "Invalid factorisation flag.";
     case qpOASES::RET_UNABLE_TO_SAVE_QPDATA:
       return "Unable to save QP data.";
     case qpOASES::RET_STEPDIRECTION_FAILED_TQ:
       return "Abnormal termination due to TQ factorisation.";
     case qpOASES::RET_STEPDIRECTION_FAILED_CHOLESKY:
       return "Abnormal termination due to Cholesky factorisation.";
     case qpOASES::RET_CYCLING_DETECTED:
       return "Cycling detected.";
     case qpOASES::RET_CYCLING_NOT_RESOLVED:
       return "Cycling cannot be resolved, QP probably infeasible.";
     case qpOASES::RET_CYCLING_RESOLVED:
       return "Cycling probably resolved.";
     case qpOASES::RET_STEPSIZE:
       return "For displaying performed stepsize.";
     case qpOASES::RET_STEPSIZE_NONPOSITIVE:
       return "For displaying non-positive stepsize.";
     case qpOASES::RET_SETUPSUBJECTTOTYPE_FAILED:
       return "Setup of SubjectToTypes failed.";
     case qpOASES::RET_ADDCONSTRAINT_FAILED:
       return "Addition of constraint to working set failed.";
     case qpOASES::RET_ADDCONSTRAINT_FAILED_INFEASIBILITY:
       return "Addition of constraint to working set failed (due to QP infeasibility).";
     case qpOASES::RET_ADDBOUND_FAILED:
       return "Addition of bound to working set failed.";
     case qpOASES::RET_ADDBOUND_FAILED_INFEASIBILITY:
       return "Addition of bound to working set failed (due to QP infeasibility).";
     case qpOASES::RET_REMOVECONSTRAINT_FAILED:
       return "Removal of constraint from working set failed.";
     case qpOASES::RET_REMOVEBOUND_FAILED:
       return "Removal of bound from working set failed.";
     case qpOASES::RET_REMOVE_FROM_ACTIVESET:
       return "Removing from active set...";
     case qpOASES::RET_ADD_TO_ACTIVESET:
       return "Adding to active set...";
     case qpOASES::RET_REMOVE_FROM_ACTIVESET_FAILED:
       return "Removing from active set failed.";
     case qpOASES::RET_ADD_TO_ACTIVESET_FAILED:
       return "Adding to active set failed.";
     case qpOASES::RET_CONSTRAINT_ALREADY_ACTIVE:
       return "Constraint is already active.";
     case qpOASES::RET_ALL_CONSTRAINTS_ACTIVE:
       return "All constraints are active, no further constraint can be added.";
     case qpOASES::RET_LINEARLY_DEPENDENT:
       return "New bound/constraint is linearly dependent.";
     case qpOASES::RET_LINEARLY_INDEPENDENT:
       return "New bound/constraint is linearly independent.";
     case qpOASES::RET_LI_RESOLVED:
       return "Linear indepence of active contraint matrix successfully resolved.";
     case qpOASES::RET_ENSURELI_FAILED:
       return "Failed to ensure linear indepence of active contraint matrix.";
     case qpOASES::RET_ENSURELI_FAILED_TQ:
       return "Abnormal termination due to TQ factorisation.";
     case qpOASES::RET_ENSURELI_FAILED_NOINDEX:
       return "QP is infeasible.";
     case qpOASES::RET_ENSURELI_FAILED_CYCLING:
       return "QP is infeasible.";
     case qpOASES::RET_BOUND_ALREADY_ACTIVE:
       return "Bound is already active.";
     case qpOASES::RET_ALL_BOUNDS_ACTIVE:
       return "All bounds are active, no further bound can be added.";
     case qpOASES::RET_CONSTRAINT_NOT_ACTIVE:
       return "Constraint is not active.";
     case qpOASES::RET_BOUND_NOT_ACTIVE:
       return "Bound is not active.";
     case qpOASES::RET_HESSIAN_NOT_SPD:
       return "Projected Hessian matrix not positive definite.";
     case qpOASES::RET_HESSIAN_INDEFINITE:
       return "Hessian matrix is indefinite.";
     case qpOASES::RET_MATRIX_SHIFT_FAILED:
       return "Unable to update matrices or to transform vectors.";
     case qpOASES::RET_MATRIX_FACTORISATION_FAILED:
       return "Unable to calculate new matrix factorisations.";
     case qpOASES::RET_PRINT_ITERATION_FAILED:
       return "Unable to print information on current iteration.";
     case qpOASES::RET_NO_GLOBAL_MESSAGE_OUTPUTFILE:
       return "No global message output file initialized.";
     case qpOASES::RET_DISABLECONSTRAINTS_FAILED:
       return "Unable to disbable constraints.";
     case qpOASES::RET_ENABLECONSTRAINTS_FAILED:
       return "Unable to enbable constraints.";
     case qpOASES::RET_ALREADY_ENABLED:
       return "Bound or constraint is already enabled.";
     case qpOASES::RET_ALREADY_DISABLED:
       return "Bound or constraint is already disabled.";
     case qpOASES::RET_NO_HESSIAN_SPECIFIED:
       return "No Hessian matrix has been specified.";
     case qpOASES::RET_USING_REGULARISATION:
       return "Using regularisation as Hessian matrix is not positive definite.";
     case qpOASES::RET_EPS_MUST_BE_POSITVE:
       return "Eps for regularisation must be sufficiently positive.";
     case qpOASES::RET_REGSTEPS_MUST_BE_POSITVE:
       return "Maximum number of regularisation steps must be non-negative.";
     case qpOASES::RET_HESSIAN_ALREADY_REGULARISED:
       return "Hessian has been already regularised.";
     case qpOASES::RET_CANNOT_REGULARISE_IDENTITY:
       return "Identity Hessian matrix cannot be regularised.";
     case qpOASES::RET_NO_REGSTEP_NWSR:
       return "No additional regularisation step could be performed due to limits.";
     case qpOASES::RET_FEWER_REGSTEPS_NWSR:
       return "Fewer additional regularisation steps have been performed due to limits.";
     case qpOASES::RET_CHOLESKY_OF_ZERO_HESSIAN:
       return "Cholesky decomposition of (unregularised) zero Hessian matrix.";
     case qpOASES::RET_CONSTRAINTS_ARE_NOT_SCALED:
       return "When defining __MANY_CONSTRAINTS__, l1 norm of each "
         "constraint must be not greater than one.";
     case qpOASES::RET_ERROR_IN_CONSTRAINTPRODUCT:
       return "Error in user-defined constraint product function.";
       // SQProblem
     case qpOASES::RET_UPDATEMATRICES_FAILED:
       return "Unable to update QP matrices.";
     case qpOASES::RET_UPDATEMATRICES_FAILED_AS_QP_NOT_SOLVED:
       return "Unable to update matrices as previous QP is not solved.";
       // Utils
     case qpOASES::RET_UNABLE_TO_OPEN_FILE:
       return "Unable to open file.";
     case qpOASES::RET_UNABLE_TO_WRITE_FILE:
       return "Unable to write into file.";
     case qpOASES::RET_UNABLE_TO_READ_FILE:
       return "Unable to read from file.";
     case qpOASES::RET_FILEDATA_INCONSISTENT:
       return "File contains inconsistent data.";
       // SolutionAnalysis
     case qpOASES::RET_UNABLE_TO_ANALYSE_QPROBLEM:
       return "Unable to analyse (S)QProblem(B) object";
       // Benchmark
     case qpOASES::RET_NWSR_SET_TO_ONE:
       return "Maximum number of working set changes was set to 1.";
     case qpOASES::RET_BENCHMARK_ABORTED:
       return "Benchmark aborted.";
     case qpOASES::RET_UNABLE_TO_READ_BENCHMARK:
       return "Unable to read benchmark data.";
     case qpOASES::RET_INITIAL_QP_SOLVED:
       return "Initial QP solved.";
     case qpOASES::RET_QP_SOLUTION_STARTED:
       return "Solving QP...";
     case qpOASES::RET_BENCHMARK_SUCCESSFUL:
       return "Benchmark terminated successfully.";
     }
     // Default error message
     std::stringstream ss;
     ss << "Unknown error flag: " << flag << ". Consult qpOASES documentation.";
     return ss.str();
   }
Referenced by get_stats(), and solve().
getPlugin()
PluginInterface< Conic >::Plugin & casadi::PluginInterface< Conic >::getPlugin (const std::string & pname) static inherited
Definition at line 100 of file plugin_interface.hpp.
{
     // Check if the solver has been loaded
     auto it=Derived::solvers_.find(pname);
     // Load the solver if needed
     if (it==Derived::solvers_.end()) {
       load_plugin(pname);
       it=Derived::solvers_.find(pname);
     }
     casadi_assert_dev(it!=Derived::solvers_.end());
     return it->second;
   }
has_codegen()
virtual bool casadi::FunctionInternal::has_codegen () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_m3
Reimplemented in casadi::LinearInterpolantJac, casadi::LinearInterpolant, casadi::BSplineInterpolant, casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >, casadi::Switch, casadi::MapSum, casadi::Map, casadi::JitFunction, and casadi::FiniteDiff.
Definition at line 870 of file function_internal.hpp.
 { return false;}
Referenced by casadi::FunctionInternal::finalize().
has_derivative()
bool casadi::FunctionInternal::has_derivative () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_l4
Definition at line 2828 of file function_internal.cpp.
{
     return enable_forward_ || enable_reverse_ || enable_jacobian_ || enable_fd_;
   }
References casadi::FunctionInternal::enable_fd_, casadi::FunctionInternal::enable_forward_, casadi::FunctionInternal::enable_jacobian_, and casadi::FunctionInternal::enable_reverse_.
Referenced by casadi::FunctionInternal::call_forward(), casadi::FunctionInternal::call_reverse(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::jacobian(), and casadi::FunctionInternal::reverse().
has_eval_dm()
virtual bool casadi::FunctionInternal::has_eval_dm () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ke
Reimplemented in casadi::CallbackInternal.
Definition at line 393 of file function_internal.hpp.
 { return false;}
Referenced by casadi::FunctionInternal::eval().
has_forward()
virtual bool casadi::FunctionInternal::has_forward (casadi_int nfwd) const inline virtual inherited
forward(nfwd) returns a cached instance if available, and calls Function get_forward(casadi_int nfwd) if no cached version is available.
Extra doc: https://github.com/casadi/casadi/wiki/L_l0
Reimplemented in casadi::BSplineInterpolant, casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >, casadi::Switch, casadi::Rootfinder, casadi::Nlpsol, casadi::MapSum, casadi::Map, casadi::Integrator, casadi::Smoothing, casadi::CentralDiff, casadi::ForwardDiff, casadi::External, casadi::Expm, casadi::Dple, and casadi::CallbackInternal.
Definition at line 621 of file function_internal.hpp.
 { return false;}
Referenced by casadi::FunctionInternal::call_forward(), and casadi::FunctionInternal::init().
has_free()
virtual bool casadi::FunctionInternal::has_free () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_l8
Reimplemented in casadi::SXFunction, and casadi::MXFunction.
Definition at line 710 of file function_internal.hpp.
 { return false;}
Referenced by casadi::FunctionInternal::get_free().
has_function()
virtual bool casadi::FunctionInternal::has_function (const std::string & fname) const inline virtual inherited
Reimplemented in casadi::OracleFunction, casadi::MapSum, and casadi::Map.
Definition at line 339 of file function_internal.hpp.
 {return false;}
has_jac_sparsity()
virtual bool casadi::FunctionInternal::has_jac_sparsity (casadi_int oind, casadi_int iind) const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kz Get, if necessary generate, the sparsity of a Jacobian block
Reimplemented in casadi::FmuFunction, casadi::GenericExternal, casadi::Expm, and casadi::CallbackInternal.
Definition at line 600 of file function_internal.hpp.
 { return false;}
Referenced by casadi::FunctionInternal::get_sparsity_out(), casadi::GenericExternal::has_jac_sparsity(), and casadi::FunctionInternal::jac_sparsity().
has_jacobian()
virtual bool casadi::FunctionInternal::has_jacobian () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ky
Reimplemented in casadi::LinearInterpolantJac, casadi::LinearInterpolant, casadi::BSplineInterpolant, casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >, casadi::JitFunction, casadi::FmuFunction, casadi::External, and casadi::CallbackInternal.
Definition at line 587 of file function_internal.hpp.
 { return false;}
Referenced by casadi::External::has_jacobian(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::jacobian().
has_option()
bool casadi::ProtoFunction::has_option (const std::string & option_name) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_jj
Definition at line 900 of file function_internal.cpp.
{
     return get_options().find(option_name) != 0;
   }
References casadi::Options::find(), and casadi::ProtoFunction::get_options().
has_plugin()
bool casadi::PluginInterface< Conic >::has_plugin (const std::string & pname, bool verbose = false) static inherited
Definition at line 75 of file plugin_interface.hpp.
{
     // Quick return if available
     if (Derived::solvers_.find(pname) != Derived::solvers_.end()) {
       return true;
     }
     // Try loading the plugin
     try {
       (void)load_plugin(pname, false);
       return true;
     } catch (CasadiException& ex) {
       if (verbose) {
         casadi_warning(ex.what());
       }
       return false;
     }
   }
has_reverse()
virtual bool casadi::FunctionInternal::has_reverse (casadi_int nadj) const inline virtual inherited
reverse(nadj) returns a cached instance if available, and calls Function get_reverse(casadi_int nadj) if no cached version is available.
Extra doc: https://github.com/casadi/casadi/wiki/L_l1
Reimplemented in casadi::BSplineInterpolant, casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >, casadi::Switch, casadi::Rootfinder, casadi::Nlpsol, casadi::MapSum, casadi::Map, casadi::Integrator, casadi::FmuFunction, casadi::External, casadi::Expm, casadi::Dple, and casadi::CallbackInternal.
Definition at line 642 of file function_internal.hpp.
 { return false;}
Referenced by casadi::FunctionInternal::call_reverse(), and casadi::FunctionInternal::init().
has_spfwd()
virtual bool casadi::FunctionInternal::has_spfwd () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ka
Reimplemented in casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >, casadi::Rootfinder, casadi::MapSum, casadi::Map, and casadi::Integrator.
Definition at line 364 of file function_internal.hpp.
 { return false;}
Referenced by casadi::FunctionInternal::get_jac_sparsity(), casadi::FunctionInternal::get_jac_sparsity_hierarchical_symm(), casadi::FunctionInternal::jac_sparsity(), and casadi::FunctionInternal::sp_weight().
has_sprev()
virtual bool casadi::FunctionInternal::has_sprev () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ka
Reimplemented in casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >, casadi::Rootfinder, casadi::MapSum, casadi::Map, and casadi::Integrator.
Definition at line 365 of file function_internal.hpp.
 { return false;}
Referenced by casadi::FunctionInternal::get_jac_sparsity(), casadi::FunctionInternal::jac_sparsity(), and casadi::FunctionInternal::sp_weight().
incache()
bool casadi::FunctionInternal::incache (const std::string & fname, Function & f, const std::string & suffix = "") const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lk
Definition at line 970 of file function_internal.cpp.
{
     auto it = cache_.find(fname + ":" + suffix);
     if (it!=cache_.end() && it->second.alive()) {
       f = shared_cast<Function>(it->second.shared());
       return true;
     } else {
       return false;
     }
   }
References casadi::FunctionInternal::cache_.
Referenced by casadi::MapSum::create(), casadi::OracleFunction::create_function(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::jacobian(), casadi::FunctionInternal::map(), casadi::FunctionInternal::reverse(), and casadi::FunctionInternal::wrap().
index_in()
casadi_int casadi::FunctionInternal::index_in (const std::string & name) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mu
Definition at line 1082 of file function_internal.hpp.
{
       for (casadi_int i=0; i<name_in_.size(); ++i) {
         if (name_in_[i]==name) return i;
       }
       casadi_error("FunctionInternal::index_in: could not find entry \""
                    + name + "\". Available names are: " + str(name_in_) + ".");
       return -1;
     }
References casadi::str().
Referenced by casadi::FunctionInternal::convert_arg().
index_out()
casadi_int casadi::FunctionInternal::index_out (const std::string & name) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mv
Definition at line 1094 of file function_internal.hpp.
{
       for (casadi_int i=0; i<name_out_.size(); ++i) {
         if (name_out_[i]==name) return i;
       }
       casadi_error("FunctionInternal::index_out: could not find entry \""
                    + name + "\". Available names are: " + str(name_out_) + ".");
       return -1;
     }
References casadi::str().
Referenced by casadi::FunctionInternal::convert_res().
info()
Dict casadi::FunctionInternal::info () const virtual inherited
Obtain information about function
Reimplemented in casadi::Switch, and casadi::Map.
Definition at line 2864 of file function_internal.cpp.
{
     return Dict();
   }
Referenced by casadi::MXFunction::export_code_body(), casadi::Blocksqp::feasibilityRestorationPhase(), casadi::Blocksqp::filterLineSearch(), casadi::Blocksqp::fullstep(), casadi::BSplineInterpolant::init(), casadi::Blocksqp::kktErrorReduction(), casadi::Feasiblesqpmethod::print_iteration(), casadi::Sqpmethod::print_iteration(), casadi::Blocksqp::secondOrderCorrection(), casadi::SnoptInterface::solve(), casadi::Feasiblesqpmethod::solve(), casadi::Sqpmethod::solve(), and casadi::Sqpmethod::solve_elastic_mode().
init()
void casadi::QpoasesInterface::init (const Dict & opts) override virtual
Reimplemented from casadi::Conic.
Definition at line 192 of file qpoases_interface.cpp.
{
     Conic::init(opts);
     // Default options
     sparse_ = false;
     schur_ = false;
     hess_ = qpOASES::HessianType::HST_UNKNOWN;
     max_schur_ = 75;
     max_nWSR_ = 5 *(nx_ + na_);
     max_cputime_ = -1;
     ops_.setToDefault();
     linsol_plugin_ = "ma27";
     // Read options
     for (auto&& op : opts) {
       if (op.first=="sparse") {
         sparse_ = op.second;
       } else if (op.first=="schur") {
         schur_=  op.second;
       } else if (op.first=="hessian_type") {
         std::string h = op.second;
         if (h=="unknown") {
           hess_ = qpOASES::HessianType::HST_UNKNOWN;
         } else if (h=="posdef") {
           hess_ = qpOASES::HessianType::HST_POSDEF;
         } else if (h=="semidef") {
           hess_ = qpOASES::HessianType::HST_SEMIDEF;
         } else if (h=="indef") {
           hess_ = qpOASES::HessianType::HST_INDEF;
         } else if (h=="zero") {
           hess_ = qpOASES::HessianType::HST_ZERO;
         } else if (h=="identity") {
           hess_ = qpOASES::HessianType::HST_IDENTITY;
         } else {
           casadi_error("Unknown Hessian type \"" + h + "\"");
         }
       } else if (op.first=="max_schur") {
         max_schur_ = op.second;
       } else if (op.first=="linsol_plugin") {
         linsol_plugin_ = std::string(op.second);
       } else if (op.first=="nWSR") {
         max_nWSR_ = op.second;
       } else if (op.first=="CPUtime") {
         max_cputime_ = op.second;
       } else if (op.first=="printLevel") {
         ops_.printLevel = to_PrintLevel(op.second);
       } else if (op.first=="enableRamping") {
         ops_.enableRamping = to_BooleanType(op.second);
       } else if (op.first=="enableFarBounds") {
         ops_.enableFarBounds = to_BooleanType(op.second);
       } else if (op.first=="enableFlippingBounds") {
         ops_.enableFlippingBounds = to_BooleanType(op.second);
       } else if (op.first=="enableRegularisation") {
         ops_.enableRegularisation = to_BooleanType(op.second);
       } else if (op.first=="enableFullLITests") {
         ops_.enableFullLITests = to_BooleanType(op.second);
       } else if (op.first=="enableNZCTests") {
         ops_.enableNZCTests = to_BooleanType(op.second);
       } else if (op.first=="enableDriftCorrection") {
         ops_.enableRegularisation = to_BooleanType(op.second);
       } else if (op.first=="enableCholeskyRefactorisation") {
         ops_.enableCholeskyRefactorisation = op.second;
       } else if (op.first=="enableEqualities") {
         ops_.enableEqualities = to_BooleanType(op.second);
       } else if (op.first=="terminationTolerance") {
         ops_.terminationTolerance = op.second;
       } else if (op.first=="boundTolerance") {
         ops_.boundTolerance = op.second;
       } else if (op.first=="boundRelaxation") {
         ops_.boundRelaxation = op.second;
       } else if (op.first=="epsNum") {
         ops_.epsNum = op.second;
       } else if (op.first=="epsDen") {
         ops_.epsDen = op.second;
       } else if (op.first=="maxPrimalJump") {
         ops_.maxPrimalJump = op.second;
       } else if (op.first=="maxDualJump") {
         ops_.maxDualJump = op.second;
       } else if (op.first=="initialRamping") {
         ops_.initialRamping = op.second;
       } else if (op.first=="finalRamping") {
         ops_.finalRamping = op.second;
       } else if (op.first=="initialFarBounds") {
         ops_.initialFarBounds = op.second;
       } else if (op.first=="growFarBounds") {
         ops_.growFarBounds = op.second;
       } else if (op.first=="initialStatusBounds") {
         ops_.initialStatusBounds = to_SubjectToStatus(op.second);
       } else if (op.first=="epsFlipping") {
         ops_.epsFlipping = op.second;
       } else if (op.first=="numRegularisationSteps") {
         ops_.numRegularisationSteps = op.second;
       } else if (op.first=="epsRegularisation") {
         ops_.epsRegularisation = op.second;
       } else if (op.first=="numRefinementSteps") {
         ops_.numRefinementSteps = op.second;
       } else if (op.first=="epsIterRef") {
         ops_.epsIterRef = op.second;
       } else if (op.first=="epsLITests") {
         ops_.epsLITests = op.second;
       } else if (op.first=="epsNZCTests") {
         ops_.epsNZCTests = op.second;
       } else if (op.first=="enableInertiaCorrection") {
         ops_.enableInertiaCorrection = to_BooleanType(op.second);
       }
     }
     // Bug #2358
     if (sparse_ && na_ == 0) {
       casadi_error("With no linear constraints, qpOASES fails in sparse mode: "
       "https://github.com/casadi/casadi/issues/2358");
     }
     // Allocate work vectors
     if (sparse_) {
       alloc_w(nnz_in(CONIC_H), true); // h
       alloc_w(nnz_in(CONIC_A), true); // a
     } else {
       alloc_w(nx_*nx_, true); // h
       alloc_w(nx_*na_, true); // a
     }
     alloc_w(nx_, true); // g
     alloc_w(nx_, true); // lbx
     alloc_w(nx_, true); // ubx
     alloc_w(na_, true); // lba
     alloc_w(na_, true); // uba
     alloc_w(nx_+na_, true); // dual
   }
References casadi::FunctionInternal::alloc_w(), casadi::CONIC_A, casadi::CONIC_H, hess_, casadi::Conic::init(), linsol_plugin_, max_cputime_, max_nWSR_, max_schur_, casadi::Conic::na_, casadi::FunctionInternal::nnz_in(), casadi::Conic::nx_, ops_, schur_, sparse_, to_BooleanType(), to_PrintLevel(), and to_SubjectToStatus().
init_mem()
int casadi::QpoasesInterface::init_mem (void * mem) const override virtual
Reimplemented from casadi::Conic.
Definition at line 321 of file qpoases_interface.cpp.
{
     if (Conic::init_mem(mem)) return 1;
     auto m = static_cast<QpoasesMemory*>(mem);
     m->called_once = false;
     // Linear solver, if any
     m->linsol_plugin = linsol_plugin_;
     // Create qpOASES instance
     delete m->qp;
     if (schur_) {
       m->sqp = new qpOASES::SQProblemSchur(nx_, na_, hess_, max_schur_,
         mem, qpoases_init, qpoases_sfact, qpoases_nfact, qpoases_solve);
     } else if (na_==0) {
       m->qp = new qpOASES::QProblemB(nx_, hess_);
     } else {
       m->sqp = new qpOASES::SQProblem(nx_, na_, hess_);
     }
     // Pass to qpOASES
     m->qp->setOptions(ops_);
     m->add_stat("preprocessing");
     m->add_stat("solver");
     m->add_stat("postprocessing");
     m->h_row.resize(H_.nnz());
     m->h_colind.resize(H_.size2()+1);
     m->a_row.resize(A_.nnz());
     m->a_colind.resize(A_.size2()+1);
     return 0;
   }
References casadi::Conic::A_, casadi::QpoasesMemory::called_once, casadi::Conic::H_, hess_, casadi::Conic::init_mem(), linsol_plugin_, max_schur_, casadi::Conic::na_, casadi::Sparsity::nnz(), casadi::Conic::nx_, ops_, qpoases_init(), qpoases_nfact(), qpoases_sfact(), qpoases_solve(), schur_, and casadi::Sparsity::size2().
initSingleton()
void casadi::SharedObjectInternal::initSingleton () inline protected inherited
Called in the constructor of singletons to avoid that the counter reaches zero
Definition at line 73 of file shared_object_internal.hpp.
{
       casadi_assert_dev(count==0);
       count++;
     }
instantiate()
Conic * casadi::PluginInterface< Conic >::instantiate (const std::string & fname, const std::string & pname, Problem problem) static inherited
Definition at line 104 of file plugin_interface.hpp.
{
     // Assert the plugin exists (needed for adaptors)
     if (!has_plugin(pname, true)) {
       casadi_error("Plugin '" + pname + "' is not found.");
     }
     return getPlugin(pname).creator(fname, problem);
   }
instruction_constant()
double casadi::FunctionInternal::instruction_constant (casadi_int k) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ld
Reimplemented in casadi::SXFunction.
Definition at line 3236 of file function_internal.cpp.
{
     casadi_error("'instruction_constant' not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
instruction_id()
casadi_int casadi::FunctionInternal::instruction_id (casadi_int k) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lb
Reimplemented in casadi::SXFunction, and casadi::MXFunction.
Definition at line 3228 of file function_internal.cpp.
{
     casadi_error("'instruction_id' not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
instruction_input()
std::vector< casadi_int > casadi::FunctionInternal::instruction_input (casadi_int k) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lc
Reimplemented in casadi::SXFunction, and casadi::MXFunction.
Definition at line 3232 of file function_internal.cpp.
{
     casadi_error("'instruction_input' not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
instruction_MX()
MX casadi::FunctionInternal::instruction_MX (casadi_int k) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lg
Reimplemented in casadi::MXFunction.
Definition at line 3244 of file function_internal.cpp.
{
     casadi_error("'instruction_MX' not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
instruction_output()
std::vector< casadi_int > casadi::FunctionInternal::instruction_output (casadi_int k) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_le
Reimplemented in casadi::SXFunction, and casadi::MXFunction.
Definition at line 3240 of file function_internal.cpp.
{
     casadi_error("'instruction_output' not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
instructions_sx()
SX casadi::FunctionInternal::instructions_sx () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lh
Reimplemented in casadi::SXFunction.
Definition at line 3248 of file function_internal.cpp.
{
     casadi_error("'instructions_sx' not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
integer_support()
virtual bool casadi::Conic::integer_support () const inline virtual inherited
Reimplemented in casadi::SuperscsInterface, casadi::ProxqpInterface, casadi::OsqpInterface, casadi::HighsInterface, casadi::GurobiInterface, casadi::CplexInterface, and casadi::CbcInterface.
Definition at line 142 of file conic_impl.hpp.
 { return false;}
Referenced by casadi::Conic::init().
is_a()
bool casadi::Conic::is_a (const std::string & type, bool recursive) const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1jc
Reimplemented from casadi::FunctionInternal.
Definition at line 554 of file conic.cpp.
{
     return type=="Conic" || (recursive && FunctionInternal::is_a(type, recursive));
   }
References casadi::FunctionInternal::is_a().
jac_is_symm()
bool casadi::FunctionInternal::jac_is_symm (casadi_int oind, casadi_int iind) const virtual inherited
Definition at line 1760 of file function_internal.cpp.
{
     // If derivative expression
     if (!derivative_of_.is_null()) {
       std::string n = derivative_of_.name();
       // Reverse move
       if (name_ == "adj1_" + n) {
         if (iind == oind) return true;
       }
     }
     // Not symmetric by default
     return false;
   }
References casadi::FunctionInternal::derivative_of_, casadi::SharedObject::is_null(), casadi::Function::name(), and casadi::ProtoFunction::name_.
jac_sparsity()
Sparsity & casadi::FunctionInternal::jac_sparsity (casadi_int oind, casadi_int iind, bool compact, bool symmetric) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kz Get, if necessary generate, the sparsity of a Jacobian block
Definition at line 1843 of file function_internal.cpp.
{
     // If first call, allocate cache
     for (bool c : {false, true}) {
       if (jac_sparsity_[c].empty()) jac_sparsity_[c].resize(n_in_ * n_out_);
     }
     // Flat index
     casadi_int ind = iind + oind * n_in_;
     // Reference to the block
     Sparsity& jsp = jac_sparsity_[compact].at(ind);
     // If null, generate
     if (jsp.is_null()) {
       // Use (non)-compact pattern, if given
       Sparsity& jsp_other = jac_sparsity_[!compact].at(ind);
       if (!jsp_other.is_null()) {
         jsp = compact ? to_compact(oind, iind, jsp_other) : from_compact(oind, iind, jsp_other);
       } else {
         // Generate pattern
         Sparsity sp;
         bool sp_is_compact;
         if (!is_diff_out_.at(oind) || !is_diff_in_.at(iind)) {
           // All-zero sparse
           sp = Sparsity(nnz_out(oind), nnz_in(iind));
           sp_is_compact = true;
         } else {
           // Use internal routine to determine sparsity
           if (has_spfwd() || has_sprev() || has_jac_sparsity(oind, iind)) {
             sp = get_jac_sparsity(oind, iind, symmetric);
           }
           // If null, dense
           if (sp.is_null()) sp = Sparsity::dense(nnz_out(oind), nnz_in(iind));
           // Is the return the compact pattern?
           sp_is_compact = sp.size1() == nnz_out(oind) && sp.size2() == nnz_in(iind);
         }
         // Save to cache and convert if needed
         if (sp_is_compact == compact) {
           jsp = sp;
         } else {
           jsp_other = sp;
           jsp = compact ? to_compact(oind, iind, sp) : from_compact(oind, iind, sp);
         }
       }
     }
     // Make sure the Jacobian is symmetric if requested, cf. #1522, #3074, #3134
     if (symmetric) {
       if (compact) {
         Sparsity sp = from_compact(oind, iind, jsp);
         if (!sp.is_symmetric()) {
           sp = sp * sp.T();
           jsp = to_compact(oind, iind, sp);
         }
       } else {
         if (!jsp.is_symmetric()) jsp = jsp * jsp.T();
       }
     }
     // Return a reference to the block
     return jsp;
   }
References casadi::Sparsity::dense(), casadi::FunctionInternal::from_compact(), casadi::FunctionInternal::get_jac_sparsity(), casadi::FunctionInternal::has_jac_sparsity(), casadi::FunctionInternal::has_spfwd(), casadi::FunctionInternal::has_sprev(), casadi::FunctionInternal::is_diff_in_, casadi::FunctionInternal::is_diff_out_, casadi::SharedObject::is_null(), casadi::Sparsity::is_symmetric(), casadi::FunctionInternal::jac_sparsity_, casadi::FunctionInternal::n_in_, casadi::FunctionInternal::n_out_, casadi::FunctionInternal::nnz_in(), casadi::FunctionInternal::nnz_out(), casadi::Sparsity::size1(), casadi::Sparsity::size2(), casadi::Sparsity::T(), and casadi::FunctionInternal::to_compact().
Referenced by casadi::FunctionInternal::get_partition(), casadi::FunctionInternal::sp_forward_block(), and casadi::FunctionInternal::sp_reverse().
jacobian()
Function casadi::FunctionInternal::jacobian () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ky
Definition at line 2226 of file function_internal.cpp.
{
     // Used wrapped function if jacobian not available
     if (!has_jacobian()) {
       // Derivative information must be available
       casadi_assert(has_derivative(),
                             "Derivatives cannot be calculated for " + name_);
       return wrap().jacobian();
     }
     // Retrieve/generate cached
     Function f;
     std::string fname = "jac_" + name_;
     if (!incache(fname, f)) {
       // Names of inputs
       std::vector<std::string> inames;
       for (casadi_int i=0; i<n_in_; ++i) inames.push_back(name_in_[i]);
       for (casadi_int i=0; i<n_out_; ++i) inames.push_back("out_" + name_out_[i]);
       // Names of outputs
       std::vector<std::string> onames;
       onames.reserve(n_in_ * n_out_);
       for (size_t oind = 0; oind < n_out_; ++oind) {
         for (size_t iind = 0; iind < n_in_; ++iind) {
           onames.push_back("jac_" + name_out_[oind] + "_" + name_in_[iind]);
         }
       }
       // Options
       Dict opts = combine(jacobian_options_, der_options_);
       opts["derivative_of"] = self();
       // Generate derivative function
       casadi_assert_dev(enable_jacobian_);
       f = get_jacobian(fname, inames, onames, opts);
       // Consistency checks
       casadi_assert(f.n_in() == inames.size(),
         "Mismatching input signature, expected " + str(inames));
       casadi_assert(f.n_out() == onames.size(),
         "Mismatching output signature, expected " + str(onames));
       // Save to cache
       tocache(f);
     }
     return f;
   }
References casadi::combine(), casadi::FunctionInternal::der_options_, casadi::FunctionInternal::enable_jacobian_, casadi::FunctionInternal::get_jacobian(), casadi::FunctionInternal::has_derivative(), casadi::FunctionInternal::has_jacobian(), casadi::FunctionInternal::incache(), casadi::Function::jacobian(), casadi::FunctionInternal::jacobian_options_, casadi::Function::n_in(), casadi::FunctionInternal::n_in_, casadi::Function::n_out(), casadi::FunctionInternal::n_out_, casadi::ProtoFunction::name_, casadi::FunctionInternal::name_in_, casadi::FunctionInternal::name_out_, casadi::str(), casadi::FunctionInternal::tocache(), and casadi::FunctionInternal::wrap().
Referenced by casadi::FunctionInternal::call_forward(), casadi::FunctionInternal::call_reverse(), and casadi::Function::jacobian().
jit_dependencies()
virtual void casadi::FunctionInternal::jit_dependencies (const std::string & fname) inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_m4
Reimplemented in casadi::OracleFunction.
Definition at line 875 of file function_internal.hpp.
 {}
Referenced by casadi::FunctionInternal::finalize().
load_library()
handle_t casadi::PluginInterface< Conic >::load_library (const std::string & libname, std::string & resultpath, bool global) static inherited
Definition at line 90 of file plugin_interface.hpp.
{
 #ifndef WITH_DL
     casadi_error("WITH_DL option needed for dynamic loading");
 #else // WITH_DL
     // Get the name of the shared library
     std::string lib = SHARED_LIBRARY_PREFIX + libname + SHARED_LIBRARY_SUFFIX;
     // Build up search paths;
     std::vector<std::string> search_paths = get_search_paths();
     return open_shared_library(lib, search_paths, resultpath,
       "PluginInterface::load_plugin", global);
 #endif // WITH_DL
   }
load_plugin()
PluginInterface< Conic >::Plugin casadi::PluginInterface< Conic >::load_plugin (const std::string & pname, bool register_plugin = true) static inherited
Definition at line 87 of file plugin_interface.hpp.
{
     // Issue warning and quick return if already loaded
     if (Derived::solvers_.find(pname) != Derived::solvers_.end()) {
       casadi_warning("PluginInterface: Solver " + pname + " is already in use. Ignored.");
       return Plugin();
     }
 #ifndef WITH_DL
     casadi_error("WITH_DL option needed for dynamic loading");
 #else // WITH_DL
     // Retrieve the registration function
     RegFcn reg;
     // Load the dll
     std::string regName = "casadi_register_" + Derived::infix_ + "_" + pname;
     std::string searchpath;
     handle_t handle = load_library("casadi_" + Derived::infix_ + "_" + pname, searchpath,
       false);
 #ifdef _WIN32
 #if __GNUC__
 #pragma GCC diagnostic push
 #pragma GCC diagnostic ignored "-Wcast-function-type"
 #endif
     reg = reinterpret_cast<RegFcn>(GetProcAddress(handle, TEXT(regName.c_str())));
 #if __GNUC__
 #pragma GCC diagnostic pop
 #endif
 #else // _WIN32
     // Reset error
     dlerror();
     // Load creator
     reg = reinterpret_cast<RegFcn>(dlsym(handle, regName.c_str()));
 #endif // _WIN32
     casadi_assert(reg!=nullptr,
       "PluginInterface::load_plugin: no \"" + regName + "\" found in " + searchpath + ".");
     // Create a temporary struct
     Plugin plugin = pluginFromRegFcn(reg);
     // Register the plugin
     if (register_plugin) {
       registerPlugin(plugin);
     }
     return plugin;
 #endif // WITH_DL
   }
map()
Function casadi::FunctionInternal::map (casadi_int n, const std::string & parallelization) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_nd
Definition at line 993 of file function_internal.cpp.
{
     Function f;
     if (parallelization=="serial") {
       // Serial maps are cached
       std::string fname = "map" + str(n) + "_" + name_;
       if (!incache(fname, f)) {
         // Create new serial map
         f = Map::create(parallelization, self(), n);
         casadi_assert_dev(f.name()==fname);
         // Save in cache
         tocache(f);
       }
     } else {
       // Non-serial maps are not cached
       f = Map::create(parallelization, self(), n);
     }
     return f;
   }
References casadi::Map::create(), casadi::FunctionInternal::incache(), casadi::Function::name(), casadi::ProtoFunction::name_, casadi::str(), and casadi::FunctionInternal::tocache().
Referenced by casadi::Dple::get_forward(), casadi::Dple::get_reverse(), and casadi::FunctionInternal::mapsum_mx().
mapsum_mx()
std::vector< MX > casadi::FunctionInternal::mapsum_mx (const std::vector< MX > & arg, const std::string & parallelization) inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kw
Definition at line 3257 of file function_internal.cpp.
{
     if (x.empty()) return x;
     // Check number of arguments
     casadi_assert(x.size()==n_in_, "mapsum_mx: Wrong number_i of arguments");
     // Number of parallel calls
     casadi_int npar = 1;
     // Check/replace arguments
     std::vector<MX> x_mod(x.size());
     for (casadi_int i=0; i<n_in_; ++i) {
       if (check_mat(x[i].sparsity(), sparsity_in_[i], npar)) {
         x_mod[i] = replace_mat(x[i], sparsity_in_[i], npar);
       } else {
         // Mismatching sparsity: The following will throw an error message
         npar = 0;
         check_arg(x, npar);
       }
     }
     casadi_int n = 1;
     for (casadi_int i=0; i<x_mod.size(); ++i) {
       n = std::max(x_mod[i].size2() / size2_in(i), n);
     }
     std::vector<casadi_int> reduce_in;
     for (casadi_int i=0; i<x_mod.size(); ++i) {
       if (x_mod[i].size2()/size2_in(i)!=n) {
         reduce_in.push_back(i);
       }
     }
     Function ms = self().map("mapsum", parallelization, n, reduce_in, range(n_out_));
     // Call the internal function
     return ms(x_mod);
   }
References casadi::FunctionInternal::check_arg(), casadi::FunctionInternal::check_mat(), casadi::FunctionInternal::map(), casadi::FunctionInternal::n_in_, casadi::FunctionInternal::n_out_, casadi::range(), casadi::replace_mat(), casadi::FunctionInternal::size2_in(), and casadi::FunctionInternal::sparsity_in_.
matching_arg()
template<typename M > bool casadi::FunctionInternal::matching_arg (const std::vector< M > & arg, casadi_int & npar) const inherited
Raises errors
Parameters
npar[in] normal usage: 1, disallow pararallel calls: -1
[out] npar max number of horizontal repetitions across all arguments (or -1)
Extra doc: https://github.com/casadi/casadi/wiki/L_kk
Definition at line 1661 of file function_internal.hpp.
{
     check_arg(arg, npar);
     for (casadi_int i=0; i<n_in_; ++i) {
       if (arg.at(i).size1()!=size1_in(i)) return false;
       if (arg.at(i).size2()!=size2_in(i) && arg.at(i).size2()!=npar*size2_in(i)) return false;
     }
     return true;
   }
References casadi::FunctionInternal::check_arg(), casadi::FunctionInternal::n_in_, casadi::FunctionInternal::size1_in(), and casadi::FunctionInternal::size2_in().
Referenced by casadi::MXFunction::ad_forward(), casadi::FunctionInternal::call(), casadi::FunctionInternal::call_forward(), and casadi::FunctionInternal::nz_in().
matching_res()
template<typename M > bool casadi::FunctionInternal::matching_res (const std::vector< M > & arg, casadi_int & npar) const inherited
Raises errors
Parameters
npar[in] normal usage: 1, disallow pararallel calls: -1
[out] npar max number of horizontal repetitions across all arguments (or -1)
Extra doc: https://github.com/casadi/casadi/wiki/L_kl
Definition at line 1671 of file function_internal.hpp.
{
     check_res(res, npar);
     for (casadi_int i=0; i<n_out_; ++i) {
       if (res.at(i).size1()!=size1_out(i)) return false;
       if (res.at(i).size2()!=size2_out(i) && res.at(i).size2()!=npar*size2_out(i)) return false;
     }
     return true;
   }
References casadi::FunctionInternal::check_res(), casadi::FunctionInternal::n_out_, casadi::FunctionInternal::size1_out(), and casadi::FunctionInternal::size2_out().
Referenced by casadi::MXFunction::ad_reverse(), casadi::FunctionInternal::call_reverse(), and casadi::FunctionInternal::nz_out().
memory()
void * casadi::ProtoFunction::memory (int ind) const inherited
Definition at line 3490 of file function_internal.cpp.
{
 #ifdef CASADI_WITH_THREAD
     std::lock_guard<std::mutex> lock(mtx_);
 #endif //CASADI_WITH_THREAD
     return mem_.at(ind);
   }
Referenced by casadi::FunctionInternal::call_gen(), casadi::FunctionInternal::get_jac_sparsity_gen(), casadi::FunctionInternal::get_jac_sparsity_hierarchical(), casadi::Sqpmethod::solve_ela_QP(), and casadi::Sqpmethod::solve_QP().
mx_in() [1/2]
const std::vector< MX > casadi::FunctionInternal::mx_in () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_l7
Reimplemented in casadi::MXFunction.
Definition at line 3191 of file function_internal.cpp.
{
     std::vector<MX> ret(n_in_);
     for (casadi_int i=0; i<ret.size(); ++i) {
       ret[i] = mx_in(i);
     }
     return ret;
   }
References casadi::FunctionInternal::n_in_.
Referenced by casadi::Nlpsol::get_forward(), casadi::LinearInterpolantJac::get_jacobian(), casadi::Nlpsol::get_reverse(), casadi::FunctionInternal::wrap(), and casadi::FunctionInternal::wrap_as_needed().
mx_in() [2/2]
const MX casadi::FunctionInternal::mx_in (casadi_int ind) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_l7
Reimplemented in casadi::MXFunction.
Definition at line 3183 of file function_internal.cpp.
{
     return MX::sym(name_in_.at(ind), sparsity_in(ind));
   }
References casadi::FunctionInternal::name_in_, casadi::FunctionInternal::sparsity_in(), and casadi::GenericMatrix< MX >::sym().
mx_out() [1/2]
const std::vector< MX > casadi::FunctionInternal::mx_out () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_l7
Definition at line 3199 of file function_internal.cpp.
{
     std::vector<MX> ret(n_out_);
     for (casadi_int i=0; i<ret.size(); ++i) {
       ret[i] = mx_out(i);
     }
     return ret;
   }
References casadi::FunctionInternal::n_out_.
Referenced by casadi::Nlpsol::get_forward(), and casadi::Nlpsol::get_reverse().
mx_out() [2/2]
const MX casadi::FunctionInternal::mx_out (casadi_int ind) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_l7
Definition at line 3187 of file function_internal.cpp.
{
     return MX::sym(name_out_.at(ind), sparsity_out(ind));
   }
References casadi::FunctionInternal::name_out_, casadi::FunctionInternal::sparsity_out(), and casadi::GenericMatrix< MX >::sym().
n_instructions()
casadi_int casadi::FunctionInternal::n_instructions () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_la
Reimplemented in casadi::SXFunction, and casadi::MXFunction.
Definition at line 3224 of file function_internal.cpp.
{
     casadi_error("'n_instructions' not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
n_nodes()
casadi_int casadi::FunctionInternal::n_nodes () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lf
Reimplemented in casadi::SXFunction, and casadi::MXFunction.
Definition at line 3252 of file function_internal.cpp.
{
     casadi_error("'n_nodes' not defined for " + class_name());
   }
References casadi::SharedObjectInternal::class_name().
nnz_in() [1/2]
casadi_int casadi::FunctionInternal::nnz_in () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_me
Definition at line 2186 of file function_internal.cpp.
{
     casadi_int ret=0;
     for (casadi_int iind=0; iind<n_in_; ++iind) ret += nnz_in(iind);
     return ret;
   }
References casadi::FunctionInternal::n_in_.
Referenced by casadi::FunctionInternal::adjViaJac(), casadi::FunctionInternal::call_gen(), casadi::JitFunction::codegen_body(), casadi::FunctionInternal::codegen_meta(), casadi::CallbackInternal::finalize(), casadi::FunctionInternal::from_compact(), casadi::FunctionInternal::fwdViaJac(), casadi::FunctionInternal::generate_in(), casadi::FunctionInternal::get_jac_sparsity(), casadi::Expm::get_jac_sparsity(), casadi::FmuFunction::get_jac_sparsity(), casadi::FunctionInternal::get_jac_sparsity_gen(), casadi::FunctionInternal::get_jac_sparsity_hierarchical(), casadi::FunctionInternal::get_jac_sparsity_hierarchical_symm(), casadi::JitFunction::init(), casadi::Nlpsol::init(), casadi::CbcInterface::init(), casadi::ClpInterface::init(), casadi::CplexInterface::init(), casadi::OoqpInterface::init(), casadi::ProxqpInterface::init(), init(), casadi::ImplicitToNlp::init(), casadi::FunctionInternal::jac_sparsity(), casadi::FunctionInternal::nz_in(), casadi::ImplicitToNlp::set_work(), casadi::CbcInterface::solve(), casadi::ClpInterface::solve(), casadi::CplexInterface::solve(), casadi::OoqpInterface::solve(), casadi::ProxqpInterface::solve(), casadi::QpToNlp::solve(), casadi::KinsolInterface::solve(), casadi::FunctionInternal::sp_forward(), and casadi::FunctionInternal::sp_reverse().
nnz_in() [2/2]
casadi_int casadi::FunctionInternal::nnz_in (casadi_int ind) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_me
Definition at line 930 of file function_internal.hpp.
 { return sparsity_in(ind).nnz(); }
nnz_out() [1/2]
casadi_int casadi::FunctionInternal::nnz_out () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_me
Definition at line 2192 of file function_internal.cpp.
{
     casadi_int ret=0;
     for (casadi_int oind=0; oind<n_out_; ++oind) ret += nnz_out(oind);
     return ret;
   }
References casadi::FunctionInternal::n_out_.
Referenced by casadi::FunctionInternal::adjViaJac(), casadi::FunctionInternal::call_gen(), casadi::Nlpsol::check_inputs(), casadi::JitFunction::codegen_body(), casadi::FunctionInternal::codegen_meta(), casadi::FunctionInternal::eval_gen(), casadi::Switch::eval_sx(), casadi::CallbackInternal::finalize(), casadi::FunctionInternal::from_compact(), casadi::FunctionInternal::fwdViaJac(), casadi::FunctionInternal::generate_out(), casadi::FunctionInternal::get_jac_sparsity(), casadi::Expm::get_jac_sparsity(), casadi::FmuFunction::get_jac_sparsity(), casadi::FunctionInternal::get_jac_sparsity_gen(), casadi::FunctionInternal::get_jac_sparsity_hierarchical(), casadi::FunctionInternal::get_jac_sparsity_hierarchical_symm(), casadi::JitFunction::init(), casadi::Nlpsol::init(), casadi::FunctionInternal::jac_sparsity(), casadi::FunctionInternal::nz_out(), casadi::KinsolInterface::solve(), casadi::FunctionInternal::sp_forward(), and casadi::FunctionInternal::sp_reverse().
nnz_out() [2/2]
casadi_int casadi::FunctionInternal::nnz_out (casadi_int ind) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_me
Definition at line 932 of file function_internal.hpp.
 { return sparsity_out(ind).nnz(); }
numel_in() [1/2]
casadi_int casadi::FunctionInternal::numel_in () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mf
Definition at line 2198 of file function_internal.cpp.
{
     casadi_int ret=0;
     for (casadi_int iind=0; iind<n_in_; ++iind) ret += numel_in(iind);
     return ret;
   }
References casadi::FunctionInternal::n_in_.
Referenced by casadi::FunctionInternal::from_compact(), and casadi::Integrator::get_reverse().
numel_in() [2/2]
casadi_int casadi::FunctionInternal::numel_in (casadi_int ind) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mf
Definition at line 940 of file function_internal.hpp.
 { return sparsity_in(ind).numel(); }
numel_out() [1/2]
casadi_int casadi::FunctionInternal::numel_out () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mf
Definition at line 2204 of file function_internal.cpp.
{
     casadi_int ret=0;
     for (casadi_int oind=0; oind<n_out_; ++oind) ret += numel_out(oind);
     return ret;
   }
References casadi::FunctionInternal::n_out_.
Referenced by casadi::FunctionInternal::from_compact(), and casadi::Integrator::get_reverse().
numel_out() [2/2]
casadi_int casadi::FunctionInternal::numel_out (casadi_int ind) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mf
Definition at line 941 of file function_internal.hpp.
 { return sparsity_out(ind).numel(); }
nz_in() [1/2]
std::vector< double > casadi::FunctionInternal::nz_in (const std::vector< DM > & arg) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kt
Definition at line 3347 of file function_internal.cpp.
{
     // Disallow parallel inputs
     casadi_int npar = -1;
     if (!matching_arg(arg, npar)) {
       return nz_in(replace_arg(arg, npar));
     }
     std::vector<DM> arg2 = project_arg(arg, 1);
     std::vector<double> ret(nnz_in());
     casadi_int offset = 0;
     for (casadi_int i=0;i<n_in_;++i) {
       const double* e = arg2.at(i).ptr();
       std::copy(e, e+nnz_in(i), ret.begin()+offset);
       offset+= nnz_in(i);
     }
     return ret;
   }
References casadi::FunctionInternal::matching_arg(), casadi::FunctionInternal::n_in_, casadi::FunctionInternal::nnz_in(), casadi::FunctionInternal::project_arg(), and casadi::FunctionInternal::replace_arg().
Referenced by casadi::FunctionInternal::get_jac_sparsity(), casadi::FunctionInternal::get_jac_sparsity_gen(), and casadi::FunctionInternal::get_jac_sparsity_hierarchical().
nz_in() [2/2]
std::vector< DM > casadi::FunctionInternal::nz_in (const std::vector< double > & arg) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kt
Definition at line 3317 of file function_internal.cpp.
{
     casadi_assert(nnz_in()==arg.size(),
       "Dimension mismatch. Expecting " + str(nnz_in()) +
       ", got " + str(arg.size()) + " instead.");
     std::vector<DM> ret = dm_in();
     casadi_int offset = 0;
     for (casadi_int i=0;i<n_in_;++i) {
       DM& r = ret.at(i);
       std::copy(arg.begin()+offset, arg.begin()+offset+nnz_in(i), r.ptr());
       offset+= nnz_in(i);
     }
     return ret;
   }
References casadi::FunctionInternal::dm_in(), casadi::FunctionInternal::n_in_, casadi::FunctionInternal::nnz_in(), casadi::Matrix< Scalar >::ptr(), and casadi::str().
nz_out() [1/2]
std::vector< double > casadi::FunctionInternal::nz_out (const std::vector< DM > & res) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kt
Definition at line 3365 of file function_internal.cpp.
{
     // Disallow parallel inputs
     casadi_int npar = -1;
     if (!matching_res(res, npar)) {
       return nz_out(replace_res(res, npar));
     }
     std::vector<DM> res2 = project_res(res, 1);
     std::vector<double> ret(nnz_out());
     casadi_int offset = 0;
     for (casadi_int i=0;i<n_out_;++i) {
       const double* e = res2.at(i).ptr();
       std::copy(e, e+nnz_out(i), ret.begin()+offset);
       offset+= nnz_out(i);
     }
     return ret;
   }
References casadi::FunctionInternal::matching_res(), casadi::FunctionInternal::n_out_, casadi::FunctionInternal::nnz_out(), casadi::FunctionInternal::project_res(), and casadi::FunctionInternal::replace_res().
Referenced by casadi::FunctionInternal::get_jac_sparsity(), casadi::FunctionInternal::get_jac_sparsity_gen(), and casadi::FunctionInternal::get_jac_sparsity_hierarchical().
nz_out() [2/2]
std::vector< DM > casadi::FunctionInternal::nz_out (const std::vector< double > & res) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kt
Definition at line 3332 of file function_internal.cpp.
{
     casadi_assert(nnz_out()==res.size(),
       "Dimension mismatch. Expecting " + str(nnz_out()) +
       ", got " + str(res.size()) + " instead.");
     std::vector<DM> ret = dm_out();
     casadi_int offset = 0;
     for (casadi_int i=0;i<n_out_;++i) {
       DM& r = ret.at(i);
       std::copy(res.begin()+offset, res.begin()+offset+nnz_out(i), r.ptr());
       offset+= nnz_out(i);
     }
     return ret;
   }
References casadi::FunctionInternal::dm_out(), casadi::FunctionInternal::n_out_, casadi::FunctionInternal::nnz_out(), casadi::Matrix< Scalar >::ptr(), and casadi::str().
oracle()
const Function & casadi::FunctionInternal::oracle () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_l3
Reimplemented in casadi::OracleFunction.
Definition at line 3562 of file function_internal.cpp.
{
     casadi_error("'oracle' not defined for " + class_name());
     static Function singleton;
     return singleton;
   }
References casadi::SharedObjectInternal::class_name().
Referenced by casadi::Function::oracle(), and casadi::DaeBuilder::oracle().
plugin_deserialize()
Deserialize casadi::PluginInterface< Conic >::plugin_deserialize (const std::string & pname) static inherited
Definition at line 81 of file plugin_interface.hpp.
{
     Deserialize m = getPlugin(pname).deserialize;
     casadi_assert(m, "Plugin \"" + pname + "\" does not support deserialize");
     return m;
   }
plugin_name()
const char* casadi::QpoasesInterface::plugin_name () const inline override virtual
Implements casadi::PluginInterface< Conic >.
Definition at line 117 of file qpoases_interface.hpp.
 { return "qpoases";}
plugin_options()
const Options & casadi::PluginInterface< Conic >::plugin_options (const std::string & pname) static inherited
Definition at line 78 of file plugin_interface.hpp.
{
     const Options *op = getPlugin(pname).options;
     casadi_assert(op!=nullptr, "Plugin \"" + pname + "\" does not support options");
     return *op;
   }
pluginFromRegFcn()
PluginInterface< Conic >::Plugin casadi::PluginInterface< Conic >::pluginFromRegFcn (RegFcn regfcn) static inherited
Definition at line 84 of file plugin_interface.hpp.
{
     // Create a temporary struct
     Plugin plugin;
     // Set the fields
     int flag = regfcn(&plugin);
     casadi_assert(flag==0, "Registration of plugin failed.");
     return plugin;
   }
print()
void casadi::ProtoFunction::print (const char * fmt, ...) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_jr
Definition at line 3719 of file function_internal.cpp.
{
     // Variable number of arguments
     va_list args;
     va_start(args, fmt);
     // Static & dynamic buffers
     char buf[256];
     size_t buf_sz = sizeof(buf);
     char* buf_dyn = nullptr;
     // Try to print with a small buffer
     casadi_int n = vsnprintf(buf, buf_sz, fmt, args);
     // Need a larger buffer?
     if (n>static_cast<casadi_int>(buf_sz)) {
       buf_sz = static_cast<size_t>(n+1);
       buf_dyn = new char[buf_sz];
       n = vsnprintf(buf_dyn, buf_sz, fmt, args);
     }
     // Print buffer content
     if (n>=0) uout() << (buf_dyn ? buf_dyn : buf) << std::flush;
     // Cleanup
     delete[] buf_dyn;
     va_end(args);
     // Throw error if failure
     casadi_assert(n>=0, "Print failure while processing '" + std::string(fmt) + "'");
   }
References casadi::uout().
Referenced by casadi::Feasiblesqpmethod::anderson_acc_step_update(), casadi::Nlpsol::callback(), casadi::Blocksqp::convertHessian(), casadi::FmuFunction::eval_task(), casadi::Feasiblesqpmethod::feasibility_iterations(), casadi::Blocksqp::feasibilityRestorationPhase(), casadi::Blocksqp::fullstep(), casadi::Blocksqp::init(), casadi::Feasiblesqpmethod::init(), casadi::Ipqp::init(), casadi::Qrqp::init(), casadi::Qrsqp::init(), casadi::Sqpmethod::init(), casadi::LinsolQr::nfact(), casadi::Feasiblesqpmethod::print_iteration(), casadi::Qrsqp::print_iteration(), casadi::Sqpmethod::print_iteration(), casadi::SundialsInterface::print_stats(), casadi::ProtoFunction::print_time(), casadi::Blocksqp::printInfo(), casadi::Blocksqp::printProgress(), casadi::Blocksqp::run(), casadi::Blocksqp::solve(), casadi::Feasiblesqpmethod::solve(), casadi::Qrsqp::solve(), casadi::Sqpmethod::solve(), casadi::Sqpmethod::solve_ela_QP(), casadi::Feasiblesqpmethod::solve_LP(), casadi::Feasiblesqpmethod::solve_QP(), casadi::Qrsqp::solve_QP(), casadi::Sqpmethod::solve_QP(), and casadi::Blocksqp::solveQP().
print_dimensions()
void casadi::FunctionInternal::print_dimensions (std::ostream & stream) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mb
Definition at line 879 of file function_internal.cpp.
{
     stream << " Number of inputs: " << n_in_ << std::endl;
     for (casadi_int i=0; i<n_in_; ++i) {
       stream << "  Input " << i  << " (\"" << name_in_[i] << "\"): "
              << sparsity_in_[i].dim() << std::endl;
     }
     stream << " Number of outputs: " << n_out_ << std::endl;
     for (casadi_int i=0; i<n_out_; ++i) {
       stream << "  Output " << i  << " (\"" << name_out_[i] << "\"): "
              << sparsity_out_[i].dim() << std::endl;
     }
   }
References casadi::FunctionInternal::n_in_, casadi::FunctionInternal::n_out_, casadi::FunctionInternal::name_in_, casadi::FunctionInternal::name_out_, casadi::FunctionInternal::sparsity_in_, and casadi::FunctionInternal::sparsity_out_.
print_in()
void casadi::FunctionInternal::print_in (std::ostream & stream, const double ** arg, bool truncate) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_nv
Definition at line 798 of file function_internal.cpp.
{
     stream << "Function " << name_ << " (" << this << ")" << std::endl;
     for (casadi_int i=0; i<n_in_; ++i) {
       stream << "Input " << i << " (" << name_in_[i] << "): ";
       if (arg[i]) {
         DM::print_default(stream, sparsity_in_[i], arg[i], truncate);
         stream << std::endl;
       } else {
         stream << "NULL" << std::endl;
       }
     }
   }
References casadi::FunctionInternal::n_in_, casadi::ProtoFunction::name_, casadi::FunctionInternal::name_in_, casadi::Matrix< double >::print_default(), and casadi::FunctionInternal::sparsity_in_.
Referenced by casadi::FunctionInternal::eval_gen().
print_option()
void casadi::ProtoFunction::print_option (const std::string & name, std::ostream & stream) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ji
Definition at line 896 of file function_internal.cpp.
{
     get_options().print_one(name, stream);
   }
References casadi::ProtoFunction::get_options(), and casadi::Options::print_one().
print_options()
void casadi::ProtoFunction::print_options (std::ostream & stream) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_jh
Definition at line 892 of file function_internal.cpp.
{
     get_options().print_all(stream);
   }
References casadi::ProtoFunction::get_options(), and casadi::Options::print_all().
print_out()
void casadi::FunctionInternal::print_out (std::ostream & stream, double ** res, bool truncate) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_nw
Definition at line 811 of file function_internal.cpp.
{
     stream << "Function " << name_ << " (" << this << ")" << std::endl;
     for (casadi_int i=0; i<n_out_; ++i) {
       stream << "Output " << i << " (" << name_out_[i] << "): ";
       if (res[i]) {
         DM::print_default(stream, sparsity_out_[i], res[i], truncate);
         stream << std::endl;
       } else {
         stream << "NULL" << std::endl;
       }
     }
   }
References casadi::FunctionInternal::n_out_, casadi::ProtoFunction::name_, casadi::FunctionInternal::name_out_, casadi::Matrix< double >::print_default(), and casadi::FunctionInternal::sparsity_out_.
Referenced by casadi::FunctionInternal::eval_gen().
print_time()
void casadi::ProtoFunction::print_time (const std::map< std::string, FStats > & fstats) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ju
Definition at line 3639 of file function_internal.cpp.
{
     if (!print_time_) return;
     // Length of the name being printed
     size_t name_len=0;
     for (auto &&s : fstats) {
       name_len = std::max(s.first.size(), name_len);
     }
     name_len = std::max(name_.size(), name_len);
     // Print name with a given length. Format: "%NNs "
     char namefmt[10];
     sprint(namefmt, sizeof(namefmt), "%%%ds ", static_cast<casadi_int>(name_len));
     // Print header
     print(namefmt, name_.c_str());
     print(" : %8s %10s %8s %10s %9s\n", "t_proc", "(avg)", "t_wall", "(avg)", "n_eval");
     char buffer_proc[10];
     char buffer_wall[10];
     char buffer_proc_avg[10];
     char buffer_wall_avg[10];
     // Print keys
     for (const auto &s : fstats) {
       if (s.second.n_call!=0) {
         print(namefmt, s.first.c_str());
         format_time(buffer_proc, s.second.t_proc);
         format_time(buffer_wall, s.second.t_wall);
         format_time(buffer_proc_avg, s.second.t_proc/s.second.n_call);
         format_time(buffer_wall_avg, s.second.t_wall/s.second.n_call);
         print(" | %s (%s) %s (%s) %9d\n",
           buffer_proc, buffer_proc_avg,
           buffer_wall, buffer_wall_avg, s.second.n_call);
       }
     }
   }
References casadi::ProtoFunction::format_time(), casadi::ProtoFunction::name_, casadi::ProtoFunction::print(), casadi::ProtoFunction::print_time_, and casadi::ProtoFunction::sprint().
Referenced by casadi::FunctionInternal::eval_gen().
project_arg()
template<typename M > std::vector< M > casadi::FunctionInternal::project_arg (const std::vector< M > & arg, casadi_int npar) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kn
Definition at line 1533 of file function_internal.hpp.
{
     casadi_assert_dev(arg.size()==n_in_);
     // Which arguments require mapped evaluation
     std::vector<bool> mapped(n_in_);
     for (casadi_int i=0; i<n_in_; ++i) {
       mapped[i] = arg[i].size2()!=size2_in(i);
     }
     // Check if matching input sparsity
     std::vector<bool> matching(n_in_);
     bool any_mismatch = false;
     for (casadi_int i=0; i<n_in_; ++i) {
       if (mapped[i]) {
         matching[i] = arg[i].sparsity().is_stacked(sparsity_in(i), npar);
       } else {
         matching[i] = arg[i].sparsity()==sparsity_in(i);
       }
       any_mismatch = any_mismatch || !matching[i];
     }
     // Correct input sparsity
     if (any_mismatch) {
       std::vector<M> arg2(arg);
       for (casadi_int i=0; i<n_in_; ++i) {
         if (!matching[i]) {
           if (mapped[i]) {
             arg2[i] = project(arg2[i], repmat(sparsity_in(i), 1, npar));
           } else {
             arg2[i] = project(arg2[i], sparsity_in(i));
           }
         }
       }
       return arg2;
     }
     return arg;
   }
References casadi::FunctionInternal::n_in_, casadi::FunctionInternal::size2_in(), and casadi::FunctionInternal::sparsity_in().
Referenced by casadi::FunctionInternal::call_gen(), and casadi::FunctionInternal::nz_in().
project_res()
template<typename M > std::vector< M > casadi::FunctionInternal::project_res (const std::vector< M > & arg, casadi_int npar) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ko
Definition at line 1573 of file function_internal.hpp.
{
       return arg;
   }
Referenced by casadi::FunctionInternal::nz_out().
psd_support()
virtual bool casadi::Conic::psd_support () const inline virtual inherited
Reimplemented in casadi::SuperscsInterface, casadi::ProxqpInterface, casadi::OsqpInterface, casadi::GurobiInterface, and casadi::CplexInterface.
Definition at line 145 of file conic_impl.hpp.
 { return false;}
Referenced by casadi::Conic::init().
purgable()
template<typename MatType > bool casadi::FunctionInternal::purgable (const std::vector< MatType > & seed) static inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_nq
Definition at line 1426 of file function_internal.hpp.
{
     for (auto i=v.begin(); i!=v.end(); ++i) {
       if (!i->is_zero()) return false;
     }
     return true;
   }
Referenced by casadi::MXFunction::ad_forward(), and casadi::MXFunction::ad_reverse().
qp_codegen_body()
void casadi::Conic::qp_codegen_body (CodeGenerator & g) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_24y
Definition at line 763 of file conic.cpp.
{
     g.add_auxiliary(CodeGenerator::AUX_QP);
     g.local("d_qp", "struct casadi_qp_data");
     g.local("p_qp", "struct casadi_qp_prob");
     g << "d_qp.prob = &p_qp;\n";
     g << "p_qp.sp_a = " << g.sparsity(A_) << ";\n";
     g << "p_qp.sp_h = " << g.sparsity(H_) << ";\n";
     g << "casadi_qp_setup(&p_qp);\n";
     g << "casadi_qp_init(&d_qp, &iw, &w);\n";
     g << "d_qp.h = arg[" << CONIC_H << "];\n";
     g << "d_qp.g = arg[" << CONIC_G << "];\n";
     g << "d_qp.a = arg[" << CONIC_A << "];\n";
     g << "d_qp.lbx = arg[" << CONIC_LBX << "];\n";
     g << "d_qp.ubx = arg[" << CONIC_UBX << "];\n";
     g << "d_qp.lba = arg[" << CONIC_LBA << "];\n";
     g << "d_qp.uba = arg[" << CONIC_UBA << "];\n";
     g << "d_qp.x0 = arg[" << CONIC_X0 << "];\n";
     g << "d_qp.lam_x0 = arg[" << CONIC_LAM_X0 << "];\n";
     g << "d_qp.lam_a0 = arg[" << CONIC_LAM_A0 << "];\n";
     g << "d_qp.f = res[" << CONIC_COST << "];\n";
     g << "d_qp.x = res[" << CONIC_X << "];\n";
     g << "d_qp.lam_x = res[" << CONIC_LAM_X << "];\n";
     g << "d_qp.lam_a = res[" << CONIC_LAM_A << "];\n";
   }
References casadi::Conic::A_, casadi::CodeGenerator::add_auxiliary(), casadi::CodeGenerator::AUX_QP, casadi::CONIC_A, casadi::CONIC_COST, casadi::CONIC_G, casadi::CONIC_H, casadi::CONIC_LAM_A, casadi::CONIC_LAM_A0, casadi::CONIC_LAM_X, casadi::CONIC_LAM_X0, casadi::CONIC_LBA, casadi::CONIC_LBX, casadi::CONIC_UBA, casadi::CONIC_UBX, casadi::CONIC_X, casadi::CONIC_X0, casadi::Conic::H_, casadi::CodeGenerator::local(), and casadi::CodeGenerator::sparsity().
Referenced by casadi::HighsInterface::codegen_body(), casadi::HpipmInterface::codegen_body(), and casadi::Qrqp::codegen_body().
qpoases_error()
static void casadi::QpoasesInterface::qpoases_error (const std::string & module, casadi_int flag) static protected
qpoases_init()
int casadi::QpoasesInterface::qpoases_init (void * mem, int dim, int nnz, const int * row, const int * col) static
Definition at line 855 of file qpoases_interface.cpp.
{
     casadi_assert_dev(mem!=nullptr);
     QpoasesMemory* m = static_cast<QpoasesMemory*>(mem);
     // Get sparsity pattern in sparse triplet format
     m->row.clear();
     m->col.clear();
     m->nz_map.clear();
     for (casadi_int k=0; k<nnz; ++k) {
       // Add upper(?) triangular part (and diagonal)
       m->row.push_back(row[k]-1);
       m->col.push_back(col[k]-1);
       m->nz_map.push_back(k);
       // Add lower(?) triangular part
       if (row[k]!=col[k]) {
         m->row.push_back(col[k]-1);
         m->col.push_back(row[k]-1);
         m->nz_map.push_back(k);
       }
     }
     // Create sparsity pattern: TODO(@jaeandersson) No memory allocation
     Sparsity sp = Sparsity::triplet(dim, dim, m->row, m->col, m->lin_map, false);
     for (casadi_int& e : m->lin_map) e = m->nz_map[e];
     // Allocate memory for nonzeros
     m->nz.resize(sp.nnz());
     // Create linear solver
     m->linsol = Linsol("linsol", m->linsol_plugin, sp);
     return 0;
   }
References casadi::QpoasesMemory::col, casadi::QpoasesMemory::lin_map, casadi::QpoasesMemory::linsol, casadi::QpoasesMemory::linsol_plugin, casadi::Sparsity::nnz(), casadi::QpoasesMemory::nz, casadi::QpoasesMemory::nz_map, casadi::QpoasesMemory::row, and casadi::Sparsity::triplet().
Referenced by init_mem(), and casadi::Blocksqp::solve().
qpoases_nfact()
int casadi::QpoasesInterface::qpoases_nfact (void * mem, const double * vals, int * neig, int * rank) static
Definition at line 903 of file qpoases_interface.cpp.
{
     casadi_assert_dev(mem!=nullptr);
     QpoasesMemory* m = static_cast<QpoasesMemory*>(mem);
     // Get nonzero elements (entire elements)
     for (casadi_int i=0; i<m->nz.size(); ++i) m->nz[i] = vals[m->lin_map[i]];
     // Pass to linear solver
     m->linsol.nfact(get_ptr(m->nz));
     // Number of negative eigenvalues
     if (neig) *neig = m->linsol.neig(get_ptr(m->nz));
     // Rank of the matrix
     if (rank) *rank = m->linsol.rank(get_ptr(m->nz));
     return 0;
   }
References casadi::get_ptr(), casadi::QpoasesMemory::lin_map, casadi::QpoasesMemory::linsol, casadi::Linsol::neig(), casadi::Linsol::nfact(), casadi::QpoasesMemory::nz, and casadi::Linsol::rank().
Referenced by init_mem(), and casadi::Blocksqp::solve().
qpoases_printf()
void casadi::QpoasesInterface::qpoases_printf (const char * s) static
Definition at line 62 of file qpoases_interface.cpp.
{
     uout() << s;
   }
References casadi::uout().
Referenced by QpoasesInterface().
qpoases_sfact()
int casadi::QpoasesInterface::qpoases_sfact (void * mem, const double * vals) static
Definition at line 890 of file qpoases_interface.cpp.
{
     casadi_assert_dev(mem!=nullptr);
     QpoasesMemory* m = static_cast<QpoasesMemory*>(mem);
     // Get nonzero elements (entire elements)
     for (int i=0; i<m->nz.size(); ++i) m->nz[i] = vals[m->lin_map[i]];
     // Pass to linear solver
     m->linsol.sfact(get_ptr(m->nz));
     return 0;
   }
References casadi::get_ptr(), casadi::QpoasesMemory::lin_map, casadi::QpoasesMemory::linsol, casadi::QpoasesMemory::nz, and casadi::Linsol::sfact().
Referenced by init_mem(), and casadi::Blocksqp::solve().
qpoases_solve()
int casadi::QpoasesInterface::qpoases_solve (void * mem, int nrhs, double * rhs) static
Definition at line 923 of file qpoases_interface.cpp.
{
     casadi_assert_dev(mem!=nullptr);
     QpoasesMemory* m = static_cast<QpoasesMemory*>(mem);
     // Pass to linear solver
     m->linsol.solve(get_ptr(m->nz), rhs, nrhs);
     return 0;
   }
References casadi::get_ptr(), casadi::QpoasesMemory::linsol, casadi::QpoasesMemory::nz, and casadi::Linsol::solve().
Referenced by init_mem(), and casadi::Blocksqp::solve().
registerPlugin() [1/2]
void casadi::PluginInterface< Conic >::registerPlugin (const Plugin & plugin) static inherited
Definition at line 94 of file plugin_interface.hpp.
{
     // Check if the solver name is in use
     typename std::map<std::string, Plugin>::iterator it=Derived::solvers_.find(plugin.name);
     casadi_assert(it==Derived::solvers_.end(),
       "Solver " + str(plugin.name) + " is already in use");
     // Add to list of solvers
     Derived::solvers_[plugin.name] = plugin;
   }
registerPlugin() [2/2]
void casadi::PluginInterface< Conic >::registerPlugin (RegFcn regfcn) static inherited
Definition at line 97 of file plugin_interface.hpp.
{
     registerPlugin(pluginFromRegFcn(regfcn));
   }
release()
void casadi::ProtoFunction::release (int mem) const inherited
Definition at line 3517 of file function_internal.cpp.
{
 #ifdef CASADI_WITH_THREAD
     std::lock_guard<std::mutex> lock(mtx_);
 #endif //CASADI_WITH_THREAD
     unused_.push(mem);
   }
replace_arg()
template<typename M > std::vector< M > casadi::FunctionInternal::replace_arg (const std::vector< M > & arg, casadi_int npar) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_km
Definition at line 1706 of file function_internal.hpp.
{
     std::vector<M> r(arg.size());
     for (casadi_int i=0; i<r.size(); ++i) r[i] = replace_mat(arg[i], sparsity_in(i), npar);
     return r;
   }
References casadi::replace_mat(), and casadi::FunctionInternal::sparsity_in().
Referenced by casadi::FunctionInternal::call(), casadi::FunctionInternal::nz_in(), and casadi::FunctionInternal::replace_fseed().
replace_aseed() [1/2]
template<typename M > std::vector<std::vector<M> > casadi::FunctionInternal::replace_aseed (const std::vector< std::vector< M > > & aseed, casadi_int npar) const inherited
Definition at line 1730 of file function_internal.hpp.
{
     std::vector<std::vector<M> > r(aseed.size());
     for (casadi_int d=0; d<r.size(); ++d) r[d] = replace_res(aseed[d], npar);
     return r;
   }
References casadi::FunctionInternal::replace_res().
replace_aseed() [2/2]
template<typename M > std::vector<std::vector<M> > casadi::FunctionInternal::replace_aseed (const std::vector< std::vector< M >> & aseed, casadi_int npar) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kr
Referenced by casadi::MXFunction::ad_reverse(), and casadi::FunctionInternal::call_reverse().
replace_fseed() [1/2]
template<typename M > std::vector<std::vector<M> > casadi::FunctionInternal::replace_fseed (const std::vector< std::vector< M > > & fseed, casadi_int npar) const inherited
Definition at line 1722 of file function_internal.hpp.
{
     std::vector<std::vector<M> > r(fseed.size());
     for (casadi_int d=0; d<r.size(); ++d) r[d] = replace_arg(fseed[d], npar);
     return r;
   }
References casadi::FunctionInternal::replace_arg().
replace_fseed() [2/2]
template<typename M > std::vector<std::vector<M> > casadi::FunctionInternal::replace_fseed (const std::vector< std::vector< M >> & fseed, casadi_int npar) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kq
Referenced by casadi::MXFunction::ad_forward(), and casadi::FunctionInternal::call_forward().
replace_res()
template<typename M > std::vector< M > casadi::FunctionInternal::replace_res (const std::vector< M > & res, casadi_int npar) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kp
Definition at line 1714 of file function_internal.hpp.
{
     std::vector<M> r(res.size());
     for (casadi_int i=0; i<r.size(); ++i) r[i] = replace_mat(res[i], sparsity_out(i), npar);
     return r;
   }
References casadi::replace_mat(), and casadi::FunctionInternal::sparsity_out().
Referenced by casadi::FunctionInternal::nz_out(), and casadi::FunctionInternal::replace_aseed().
reverse()
Function casadi::FunctionInternal::reverse (casadi_int nadj) const inherited
reverse(nadj) returns a cached instance if available, and calls Function get_reverse(casadi_int nadj) if no cached version is available.
Extra doc: https://github.com/casadi/casadi/wiki/L_l1
Definition at line 2109 of file function_internal.cpp.
{
     casadi_assert_dev(nadj>=0);
     // Used wrapped function if reverse not available
     if (!enable_reverse_) {
       // Derivative information must be available
       casadi_assert(has_derivative(), "Derivatives cannot be calculated for " + name_);
       return wrap().reverse(nadj);
     }
     // Retrieve/generate cached
     Function f;
     std::string fname = reverse_name(name_, nadj);
     if (!incache(fname, f)) {
       casadi_int i;
       // Prefix to be used for adjoint seeds, sensitivities
       std::string pref = diff_prefix("adj");
       // Names of inputs
       std::vector<std::string> inames;
       for (i=0; i<n_in_; ++i) inames.push_back(name_in_[i]);
       for (i=0; i<n_out_; ++i) inames.push_back("out_" + name_out_[i]);
       for (i=0; i<n_out_; ++i) inames.push_back(pref + name_out_[i]);
       // Names of outputs
       std::vector<std::string> onames;
       for (casadi_int i=0; i<n_in_; ++i) onames.push_back(pref + name_in_[i]);
       // Options
       Dict opts = combine(reverse_options_, der_options_);
       opts = combine(opts, generate_options("reverse"));
       opts["derivative_of"] = self();
       // Generate derivative function
       casadi_assert_dev(enable_reverse_);
       f = get_reverse(nadj, fname, inames, onames, opts);
       // Consistency check for inputs
       casadi_assert_dev(f.n_in()==n_in_ + n_out_ + n_out_);
       casadi_int ind=0;
       for (i=0; i<n_in_; ++i) f.assert_size_in(ind++, size1_in(i), size2_in(i));
       for (i=0; i<n_out_; ++i) f.assert_size_in(ind++, size1_out(i), size2_out(i));
       for (i=0; i<n_out_; ++i) f.assert_size_in(ind++, size1_out(i), nadj*size2_out(i));
       // Consistency check for outputs
       casadi_assert_dev(f.n_out()==n_in_);
       for (i=0; i<n_in_; ++i) f.assert_sparsity_out(i, sparsity_in(i), nadj);
       // Save to cache
       tocache(f);
     }
     return f;
   }
References casadi::Function::assert_size_in(), casadi::Function::assert_sparsity_out(), casadi::combine(), casadi::FunctionInternal::der_options_, casadi::FunctionInternal::diff_prefix(), casadi::FunctionInternal::enable_reverse_, casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::get_reverse(), casadi::FunctionInternal::has_derivative(), casadi::FunctionInternal::incache(), casadi::Function::n_in(), casadi::FunctionInternal::n_in_, casadi::Function::n_out(), casadi::FunctionInternal::n_out_, casadi::ProtoFunction::name_, casadi::FunctionInternal::name_in_, casadi::FunctionInternal::name_out_, casadi::Function::reverse(), casadi::FunctionInternal::reverse_name(), casadi::FunctionInternal::reverse_options_, casadi::FunctionInternal::size1_in(), casadi::FunctionInternal::size1_out(), casadi::FunctionInternal::size2_in(), casadi::FunctionInternal::size2_out(), casadi::FunctionInternal::sparsity_in(), casadi::FunctionInternal::tocache(), and casadi::FunctionInternal::wrap().
Referenced by casadi::FunctionInternal::call_reverse(), and casadi::Function::reverse().
reverse_name()
static std::string casadi::FunctionInternal::reverse_name (const std::string & fcn, casadi_int nadj) inline static inherited
Definition at line 629 of file function_internal.hpp.
{
       return "adj" + str(nadj) + "_" + fcn;
     }
References casadi::str().
Referenced by casadi::FunctionInternal::reverse(), and casadi::FixedStepIntegrator::stepB().
sdp_to_socp_init()
void casadi::Conic::sdp_to_socp_init (SDPToSOCPMem & mem) const protected inherited
general soc constraints: ||Ax + b ||_2 <= c'x + d
Need to represent as X'X <= Z'Z
with X and Z helper variables and Ax + b = X c'x + d = Z
[A;c'] x - [X;Z] = [b;d]
we look for the vertical concatenation of these constraints for all blocks:
Q(map_Q) [x;X1;Z1;X2;Z2;...] = P.nz(map_P)
Definition at line 558 of file conic.cpp.
{
     Sparsity qsum = reshape(sum2(Q_), np_, np_);
     // Block detection
     Sparsity aggregate = qsum+P_;
     std::vector<casadi_int> p;
     casadi_int nb = aggregate.scc(p, mem.r);
     std::string pattern_message = "Pattern not recognised";
     casadi_assert(p==range(p.size()), pattern_message);
     const casadi_int* row = aggregate.row();
     const casadi_int* colind = aggregate.colind();
     // Check fishbone-structure
     for (casadi_int i=0;i<nb;++i) {
       casadi_int block_size = mem.r[i+1]-mem.r[i];
       // number of nonzeros in column mem.r[i+1]-1
       casadi_int nz = colind[mem.r[i+1]]-colind[mem.r[i+1]-1];
       // Last column of block should be dense
       casadi_assert(nz==block_size, pattern_message);
       for (casadi_int k=0;k<block_size-1;++k) {
         casadi_assert(colind[mem.r[i]+k+1]-colind[mem.r[i]+k], pattern_message);
         casadi_assert(*(row++)==k+mem.r[i], pattern_message);
         casadi_assert(*(row++)==mem.r[i]+block_size-1, pattern_message);
       }
       for (casadi_int k=0;k<block_size;++k)
         casadi_assert(*(row++)==k+mem.r[i], pattern_message);
     }
     /*
     Aggregate pattern:
     x (x)
      x(x)
     xx(x)
        x (x)
         x(x)
        xx(x)
     We are interested in the parts in parenthesis (target).
     Find out which rows in Q correspond to those targets
     */
     // Lookup vector for target start and end
     std::vector<casadi_int> target_start(nb), target_stop(nb);
     for (casadi_int i=0;i<nb;++i) {
       target_start[i] = (mem.r[i+1]-1)*aggregate.size1()+mem.r[i];
       target_stop[i] = target_start[i]+mem.r[i+1]-mem.r[i];
     }
     // Collect the nonzero indices in Q that that correspond to the target area
     std::vector<casadi_int> q_nz;
     // Triplet form for map_Q sparsity
     std::vector<casadi_int> q_row, q_col;
     // Loop over Q's columns (decision variables)
     for (casadi_int j=0; j<Q_.size2(); ++j) {
       casadi_int block_index = 0;
       // Loop over Q's rows
       for (casadi_int k=Q_.colind(j); k<Q_.colind(j+1); ++k) {
         casadi_int i = Q_.row(k);
         // Increment block_index if i runs ahead
         while (i>target_stop[block_index] && block_index<nb-1) block_index++;
         if (i>=target_start[block_index] && i<target_stop[block_index]) {
           // Got a nonzero in the target region
           q_nz.push_back(k);
           q_row.push_back(mem.r[block_index]+i-target_start[block_index]);
           q_col.push_back(j);
         }
       }
     }
     mem.map_Q = IM::triplet(q_row, q_col, q_nz, mem.r[nb], nx_);
     // Add the [X1;Z1;X2;Z2;...] part
     mem.map_Q = horzcat(mem.map_Q, -IM::eye(mem.r[nb])).T();
     // Get maximum nonzero count of any column
     casadi_int max_nnz = 0;
     for (casadi_int i=0;i<mem.map_Q.size2();++i) {
       max_nnz = std::max(max_nnz, mem.map_Q.colind(i+1)-mem.map_Q.colind(i));
     }
     // ind/val size needs to cover max nonzero count
     mem.indval_size = std::max(nx_, max_nnz);
     // Collect the indices for the P target area
     mem.map_P.resize(mem.r[nb], -1);
     for (casadi_int i=0;i<nb;++i) {
       for (casadi_int k=P_.colind(mem.r[i+1]-1); k<P_.colind(mem.r[i+1]); ++k) {
         casadi_int r = P_.row(k);
         mem.map_P[r] = k;
       }
     }
     // ind/val size needs to cover blocksize
     for (casadi_int i=0;i<nb;++i)
       mem.indval_size = std::max(mem.indval_size, mem.r[i+1]-mem.r[i]);
     // Get the transpose and mapping
     mem.AT = A_.transpose(mem.A_mapping);
   }
References casadi::Conic::A_, casadi::Conic::SDPToSOCPMem::A_mapping, casadi::Conic::SDPToSOCPMem::AT, casadi::GenericMatrix< MatType >::colind(), casadi::Sparsity::colind(), casadi::Matrix< casadi_int >::eye(), casadi::Conic::SDPToSOCPMem::indval_size, casadi::Conic::SDPToSOCPMem::map_P, casadi::Conic::SDPToSOCPMem::map_Q, casadi::Conic::np_, casadi::Conic::nx_, casadi::Conic::P_, casadi::Conic::Q_, casadi::Conic::SDPToSOCPMem::r, casadi::range(), casadi::Sparsity::row(), casadi::Sparsity::scc(), casadi::Sparsity::size1(), casadi::GenericMatrix< MatType >::size2(), casadi::Sparsity::size2(), casadi::Matrix< Scalar >::T(), casadi::Sparsity::transpose(), and casadi::Matrix< casadi_int >::triplet().
Referenced by casadi::CplexInterface::init(), casadi::GurobiInterface::init(), and casadi::SuperscsInterface::init().
self()
Function casadi::FunctionInternal::self () const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_k8
Definition at line 323 of file function_internal.hpp.
 { return shared_from_this<Function>();}
serialize() [1/2]
void casadi::ProtoFunction::serialize (SerializingStream & s) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_jv
Definition at line 3995 of file function_internal.cpp.
{
     serialize_type(s);
     serialize_body(s);
   }
References casadi::ProtoFunction::serialize_body(), and casadi::ProtoFunction::serialize_type().
serialize() [2/2]
void casadi::Conic::serialize (SerializingStream & s, const SDPToSOCPMem & m) const protected inherited
Definition at line 699 of file conic.cpp.
{
     s.pack("Conic::SDPToSOCPMem::r", m.r);
     s.pack("Conic::SDPToSOCPMem::AT", m.AT);
     s.pack("Conic::SDPToSOCPMem::A_mapping", m.A_mapping);
     s.pack("Conic::SDPToSOCPMem::map_Q", m.map_Q);
     s.pack("Conic::SDPToSOCPMem::map_P", m.map_P);
     s.pack("Conic::SDPToSOCPMem::indval_size", m.indval_size);
   }
References casadi::Conic::SDPToSOCPMem::A_mapping, casadi::Conic::SDPToSOCPMem::AT, casadi::Conic::SDPToSOCPMem::indval_size, casadi::Conic::SDPToSOCPMem::map_P, casadi::Conic::SDPToSOCPMem::map_Q, casadi::SerializingStream::pack(), and casadi::Conic::SDPToSOCPMem::r.
Referenced by casadi::CplexInterface::serialize_body(), casadi::GurobiInterface::serialize_body(), and casadi::SuperscsInterface::serialize_body().
serialize_base_function()
std::string casadi::Conic::serialize_base_function () const inline override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1jg
Reimplemented from casadi::ProtoFunction.
Definition at line 210 of file conic_impl.hpp.
 { return "Conic"; }
serialize_body()
void casadi::QpoasesInterface::serialize_body (SerializingStream & s) const override virtual
Reimplemented from casadi::Conic.
Definition at line 1020 of file qpoases_interface.cpp.
{
     Conic::serialize_body(s);
     s.version("QpoasesInterface", 1);
     s.pack("QpoasesInterface::max_nWSR", max_nWSR_);
     s.pack("QpoasesInterface::max_cputime", max_cputime_);
     s.pack("QpoasesInterface::hess", static_cast<casadi_int>(hess_));
     s.pack("QpoasesInterface::sparse", sparse_);
     s.pack("QpoasesInterface::schur", schur_);
     s.pack("QpoasesInterface::max_schur", max_schur_);
     s.pack("QpoasesInterface::linsol_plugin", linsol_plugin_);
     s.pack("QpoasesInterface::ops::printLevel", static_cast<casadi_int>(ops_.printLevel));
     s.pack("QpoasesInterface::ops::enableRamping", from_BooleanType(ops_.enableRamping));
     s.pack("QpoasesInterface::ops::enableFarBounds",
       from_BooleanType(ops_.enableFarBounds));
     s.pack("QpoasesInterface::ops::enableFlippingBounds",
       from_BooleanType(ops_.enableFlippingBounds));
     s.pack("QpoasesInterface::ops::enableRegularisation",
       from_BooleanType(ops_.enableRegularisation));
     s.pack("QpoasesInterface::ops::enableFullLITests",
       from_BooleanType(ops_.enableFullLITests));
     s.pack("QpoasesInterface::ops::enableNZCTests", from_BooleanType(ops_.enableNZCTests));
     s.pack("QpoasesInterface::ops::enableDriftCorrection", ops_.enableDriftCorrection);
     s.pack("QpoasesInterface::ops::enableCholeskyRefactorisation",
       ops_.enableCholeskyRefactorisation);
     s.pack("QpoasesInterface::ops::enableEqualities", from_BooleanType(ops_.enableEqualities));
     s.pack("QpoasesInterface::ops::terminationTolerance", ops_.terminationTolerance);
     s.pack("QpoasesInterface::ops::boundTolerance", ops_.boundTolerance);
     s.pack("QpoasesInterface::ops::boundRelaxation", ops_.boundRelaxation);
     s.pack("QpoasesInterface::ops::epsNum", ops_.epsNum);
     s.pack("QpoasesInterface::ops::epsDen", ops_.epsDen);
     s.pack("QpoasesInterface::ops::maxPrimalJump", ops_.maxPrimalJump);
     s.pack("QpoasesInterface::ops::maxDualJump", ops_.maxDualJump);
     s.pack("QpoasesInterface::ops::initialRamping", ops_.initialRamping);
     s.pack("QpoasesInterface::ops::finalRamping", ops_.finalRamping);
     s.pack("QpoasesInterface::ops::initialFarBounds", ops_.initialFarBounds);
     s.pack("QpoasesInterface::ops::growFarBounds", ops_.growFarBounds);
     s.pack("QpoasesInterface::ops::initialStatusBounds",
       from_SubjectToStatus(ops_.initialStatusBounds));
     s.pack("QpoasesInterface::ops::epsFlipping", ops_.epsFlipping);
     s.pack("QpoasesInterface::ops::numRegularisationSteps", ops_.numRegularisationSteps);
     s.pack("QpoasesInterface::ops::epsRegularisation", ops_.epsRegularisation);
     s.pack("QpoasesInterface::ops::numRefinementSteps", ops_.numRefinementSteps);
     s.pack("QpoasesInterface::ops::epsIterRef", ops_.epsIterRef);
     s.pack("QpoasesInterface::ops::epsLITests", ops_.epsLITests);
     s.pack("QpoasesInterface::ops::epsNZCTests", ops_.epsNZCTests);
     s.pack("QpoasesInterface::ops::enableInertiaCorrection",
       from_BooleanType(ops_.enableInertiaCorrection));
   }
References from_BooleanType(), from_SubjectToStatus(), hess_, linsol_plugin_, max_cputime_, max_nWSR_, max_schur_, ops_, casadi::SerializingStream::pack(), schur_, casadi::Conic::serialize_body(), sparse_, and casadi::SerializingStream::version().
serialize_type()
void casadi::Conic::serialize_type (SerializingStream & s) const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1jf
Reimplemented from casadi::ProtoFunction.
Definition at line 731 of file conic.cpp.
{
     FunctionInternal::serialize_type(s);
     PluginInterface<Conic>::serialize_type(s);
   }
References casadi::PluginInterface< Derived >::serialize_type(), and casadi::FunctionInternal::serialize_type().
set_jac_sparsity()
void casadi::FunctionInternal::set_jac_sparsity (casadi_int oind, casadi_int iind, const Sparsity & sp) protected inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_nx
Definition at line 3587 of file function_internal.cpp.
{
     casadi_int ind = iind + oind * n_in_;
     jac_sparsity_[false].resize(n_in_ * n_out_);
     jac_sparsity_[false].at(ind) = sp;
     jac_sparsity_[true].resize(n_in_ * n_out_);
     jac_sparsity_[true].at(ind) = to_compact(oind, iind, sp);
   }
References casadi::FunctionInternal::jac_sparsity_, casadi::FunctionInternal::n_in_, casadi::FunctionInternal::n_out_, and casadi::FunctionInternal::to_compact().
set_temp()
virtual void casadi::FunctionInternal::set_temp (void * mem, const double ** arg, double ** res, casadi_int * iw, double * w) const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_na
Reimplemented in casadi::OracleFunction.
Definition at line 1179 of file function_internal.hpp.
                                                            {}
Referenced by casadi::FunctionInternal::setup().
set_work()
void casadi::Conic::set_work (void * mem, const double **& arg, double **& res, casadi_int *& iw, double *& w) const override virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1jb
Reimplemented from casadi::FunctionInternal.
Reimplemented in casadi::Qrqp, casadi::HpipmInterface, and casadi::HighsInterface.
Definition at line 442 of file conic.cpp.
{
     auto m = static_cast<ConicMemory*>(mem);
     casadi_qp_data<double>& d_qp = m->d_qp;
     d_qp.h = arg[CONIC_H];
     d_qp.g = arg[CONIC_G];
     d_qp.a = arg[CONIC_A];
     d_qp.lbx = arg[CONIC_LBX];
     d_qp.ubx = arg[CONIC_UBX];
     d_qp.uba = arg[CONIC_UBA];
     d_qp.lba = arg[CONIC_LBA];
     d_qp.x0 = arg[CONIC_X0];
     d_qp.lam_x0 = arg[CONIC_LAM_X0];
     d_qp.lam_a0 = arg[CONIC_LAM_A0];
     d_qp.x = res[CONIC_X];
     d_qp.lam_x = res[CONIC_LAM_X];
     d_qp.lam_a = res[CONIC_LAM_A];
     d_qp.f = res[CONIC_COST];
     // Problem has not been solved at this point
     d_qp.success = false;
     d_qp.unified_return_status = SOLVER_RET_UNKNOWN;
     d_qp.iter_count = -1;
   }
References casadi_qp_data< T1 >::a, casadi::CONIC_A, casadi::CONIC_COST, casadi::CONIC_G, casadi::CONIC_H, casadi::CONIC_LAM_A, casadi::CONIC_LAM_A0, casadi::CONIC_LAM_X, casadi::CONIC_LAM_X0, casadi::CONIC_LBA, casadi::CONIC_LBX, casadi::CONIC_UBA, casadi::CONIC_UBX, casadi::CONIC_X, casadi::CONIC_X0, casadi_qp_data< T1 >::f, casadi_qp_data< T1 >::g, casadi_qp_data< T1 >::h, casadi_qp_data< T1 >::iter_count, casadi_qp_data< T1 >::lam_a, casadi_qp_data< T1 >::lam_a0, casadi_qp_data< T1 >::lam_x, casadi_qp_data< T1 >::lam_x0, casadi_qp_data< T1 >::lba, casadi_qp_data< T1 >::lbx, casadi::SOLVER_RET_UNKNOWN, casadi_qp_data< T1 >::success, casadi_qp_data< T1 >::uba, casadi_qp_data< T1 >::ubx, casadi_qp_data< T1 >::unified_return_status, casadi_qp_data< T1 >::x, and casadi_qp_data< T1 >::x0.
Referenced by casadi::HighsInterface::set_work(), casadi::HpipmInterface::set_work(), and casadi::Qrqp::set_work().
setup()
void casadi::FunctionInternal::setup (void * mem, const double ** arg, double ** res, casadi_int * iw, double * w) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_nb
Definition at line 3383 of file function_internal.cpp.
{
     set_work(mem, arg, res, iw, w);
     set_temp(mem, arg, res, iw, w);
   }
References casadi::FunctionInternal::set_temp(), and casadi::FunctionInternal::set_work().
Referenced by casadi::Conic::eval(), casadi::Nlpsol::eval(), casadi::Integrator::eval(), casadi::Rootfinder::eval(), casadi::SlicotDple::eval(), and casadi::SlicotExpm::eval().
shared_from_this() [1/2]
template<class B > B casadi::SharedObjectInternal::shared_from_this protected inherited
Template function implementations.
Definition at line 136 of file shared_object_internal.hpp.
{
     casadi_assert_dev(B::test_cast(this));
     B ret;
     ret.own(this);
     return ret;
   }
shared_from_this() [2/2]
template<class B > const B casadi::SharedObjectInternal::shared_from_this protected inherited
Definition at line 144 of file shared_object_internal.hpp.
{
     casadi_assert_dev(B::test_cast(this));
     B ret;
     ret.own(const_cast<SharedObjectInternal*>(this));
     return ret;
   }
shortname()
static std::string casadi::Conic::shortname () inline static inherited
Definition at line 129 of file conic_impl.hpp.
 { return "conic";}
signature()
std::string casadi::FunctionInternal::signature (const std::string & fname) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ly
Definition at line 2298 of file function_internal.cpp.
{
     return "int " + fname + "(const casadi_real** arg, casadi_real** res, "
                             "casadi_int* iw, casadi_real* w, int mem)";
   }
Referenced by casadi::CodeGenerator::add(), casadi::FunctionInternal::codegen(), and casadi::External::codegen_declarations().
size1_in()
casadi_int casadi::FunctionInternal::size1_in (casadi_int ind) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mg
Definition at line 949 of file function_internal.hpp.
 { return sparsity_in(ind).size1(); }
Referenced by casadi::FunctionInternal::check_arg(), casadi::FunctionInternal::forward(), casadi::Integrator::get_forward(), casadi::Integrator::get_reverse(), casadi::FunctionInternal::matching_arg(), and casadi::FunctionInternal::reverse().
size1_out()
casadi_int casadi::FunctionInternal::size1_out (casadi_int ind) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mg
Definition at line 951 of file function_internal.hpp.
 { return sparsity_out(ind).size1(); }
Referenced by casadi::FunctionInternal::forward(), casadi::Integrator::get_forward(), casadi::LinearInterpolantJac::get_jacobian(), casadi::FunctionInternal::matching_res(), and casadi::FunctionInternal::reverse().
size2_in()
casadi_int casadi::FunctionInternal::size2_in (casadi_int ind) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mg
Definition at line 950 of file function_internal.hpp.
 { return sparsity_in(ind).size2(); }
Referenced by casadi::FunctionInternal::call_gen(), casadi::FunctionInternal::call_reverse(), casadi::FunctionInternal::check_arg(), casadi::FunctionInternal::forward(), casadi::Integrator::get_reverse(), casadi::FunctionInternal::mapsum_mx(), casadi::FunctionInternal::matching_arg(), casadi::FunctionInternal::project_arg(), and casadi::FunctionInternal::reverse().
size2_out()
casadi_int casadi::FunctionInternal::size2_out (casadi_int ind) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mg
Definition at line 952 of file function_internal.hpp.
 { return sparsity_out(ind).size2(); }
Referenced by casadi::FunctionInternal::call_forward(), casadi::FunctionInternal::forward(), casadi::Integrator::get_forward(), casadi::LinearInterpolantJac::get_jacobian(), casadi::FunctionInternal::matching_res(), and casadi::FunctionInternal::reverse().
size_in()
std::pair<casadi_int, casadi_int> casadi::FunctionInternal::size_in (casadi_int ind) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mg
Definition at line 953 of file function_internal.hpp.
{
       return sparsity_in(ind).size();
     }
Referenced by casadi::Rootfinder::ad_forward(), casadi::Rootfinder::ad_reverse(), casadi::MXFunction::ad_reverse(), casadi::FunctionInternal::call_reverse(), casadi::FunctionInternal::fwd_seed(), casadi::Dple::get_forward(), and casadi::Dple::get_reverse().
size_out()
std::pair<casadi_int, casadi_int> casadi::FunctionInternal::size_out (casadi_int ind) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mg
Definition at line 956 of file function_internal.hpp.
{
       return sparsity_out(ind).size();
     }
Referenced by casadi::MXFunction::ad_forward(), casadi::Rootfinder::ad_reverse(), casadi::FunctionInternal::call_forward(), casadi::FunctionInternal::check_res(), casadi::FunctionInternal::eval(), casadi::Integrator::get_forward(), casadi::Integrator::get_reverse(), and casadi::Nlpsol::init().
slice()
Function casadi::FunctionInternal::slice (const std::string & name, const std::vector< casadi_int > & order_in, const std::vector< casadi_int > & order_out, const Dict & opts) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_l2
Reimplemented in casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, and casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >.
Definition at line 3568 of file function_internal.cpp.
{
     return wrap().slice(name, order_in, order_out, opts);
   }
References casadi::Function::slice(), and casadi::FunctionInternal::wrap().
Referenced by casadi::Function::slice().
solve()
int casadi::QpoasesInterface::solve (const double ** arg, double ** res, casadi_int * iw, double * w, void * mem) const override virtual
Implements casadi::Conic.
Definition at line 354 of file qpoases_interface.cpp.
{
     auto m = static_cast<QpoasesMemory*>(mem);
     m->fstats.at("preprocessing").tic();
     // Problem has not been solved at this point
     m->return_status = -1;
     // Maxiumum number of working set changes
     int nWSR = max_nWSR_;
     double cputime = max_cputime_;
     double *cputime_ptr = cputime<=0 ? nullptr : &cputime;
     // Get the arguments to call qpOASES with
     double* g=w; w += nx_;
     casadi_copy(arg[CONIC_G], nx_, g);
     double* lb=w; w += nx_;
     casadi_copy(arg[CONIC_LBX], nx_, lb);
     double* ub=w; w += nx_;
     casadi_copy(arg[CONIC_UBX], nx_, ub);
     double* lbA=w; w += na_;
     casadi_copy(arg[CONIC_LBA], na_, lbA);
     double* ubA=w; w += na_;
     casadi_copy(arg[CONIC_UBA], na_, ubA);
     // Return flag
     casadi_int flag;
     // Sparse or dense mode?
     if (sparse_) {
       // Get quadratic term
       copy_vector(H_.colind(), m->h_colind);
       copy_vector(H_.row(), m->h_row);
       double* h=w; w += H_.nnz();
       casadi_copy(arg[CONIC_H], H_.nnz(), h);
       delete m->h;
       m->h = new qpOASES::SymSparseMat(H_.size1(), H_.size2(),
         get_ptr(m->h_row), get_ptr(m->h_colind), h);
       m->h->createDiagInfo();
       // Get linear term
       copy_vector(A_.colind(), m->a_colind);
       copy_vector(A_.row(), m->a_row);
       double* a=w; w += A_.nnz();
       casadi_copy(arg[CONIC_A], A_.nnz(), a);
       delete m->a;
       m->a = new qpOASES::SparseMatrix(A_.size1(), A_.size2(),
         get_ptr(m->a_row), get_ptr(m->a_colind), a);
       m->fstats.at("preprocessing").toc();
       m->fstats.at("solver").tic();
       // Solve sparse
       if (m->called_once) {
         flag = m->sqp->hotstart(m->h, g, m->a, lb, ub, lbA, ubA, nWSR, cputime_ptr);
       } else {
         flag = m->sqp->init(m->h, g, m->a, lb, ub, lbA, ubA, nWSR, cputime_ptr);
       }
       m->fstats.at("solver").toc();
     } else {
       // Get quadratic term
       double* h=w; w += nx_*nx_;
       casadi_densify(arg[CONIC_H], H_, h, false);
       // Get linear term
       double* a = w; w += nx_*na_;
       casadi_densify(arg[CONIC_A], A_, a, true);
       m->fstats.at("preprocessing").toc();
       m->fstats.at("solver").tic();
       // Solve dense
       if (na_==0) {
         if (m->called_once) {
           // Broken?
           //flag = m->qp->hotstart(g, lb, ub, nWSR, cputime_ptr);
           m->qp->reset();
           flag = m->qp->init(h, g, lb, ub, nWSR, cputime_ptr);
         } else {
           flag = m->qp->init(h, g, lb, ub, nWSR, cputime_ptr);
         }
       } else {
         if (m->called_once) {
           flag = m->sqp->hotstart(h, g, a, lb, ub, lbA, ubA, nWSR, cputime_ptr);
         } else {
           flag = m->sqp->init(h, g, a, lb, ub, lbA, ubA, nWSR, cputime_ptr);
         }
       }
       m->fstats.at("solver").toc();
     }
     // Solver is "warm" now
     m->called_once = true;
     m->fstats.at("postprocessing").tic();
     m->return_status = flag;
     m->d_qp.success = flag==qpOASES::SUCCESSFUL_RETURN;
     if (m->d_qp.success) m->d_qp.unified_return_status = SOLVER_RET_SUCCESS;
     if (flag == qpOASES::RET_MAX_NWSR_REACHED) {
       m->d_qp.unified_return_status = SOLVER_RET_LIMITED;
     }
     if (flag==qpOASES::RET_INIT_FAILED_INFEASIBILITY
         || flag == qpOASES::RET_QP_INFEASIBLE
         || flag == qpOASES::RET_HOTSTART_STOPPED_INFEASIBILITY
         || flag == qpOASES::RET_ADDCONSTRAINT_FAILED_INFEASIBILITY
         || flag == qpOASES::RET_ADDBOUND_FAILED_INFEASIBILITY
         || flag == qpOASES::RET_ENSURELI_FAILED_NOINDEX
         || flag == qpOASES::RET_ENSURELI_FAILED_CYCLING) {
       m->d_qp.unified_return_status = SOLVER_RET_INFEASIBLE;
     }
     m->d_qp.iter_count = nWSR;
     if (verbose_) casadi_message("qpOASES return status: " + getErrorMessage(m->return_status));
     // Get optimal cost
     if (res[CONIC_COST]) *res[CONIC_COST] = m->qp->getObjVal();
     // Get the primal solution
     if (res[CONIC_X]) m->qp->getPrimalSolution(res[CONIC_X]);
     // Get the dual solution
     if (res[CONIC_LAM_X] || res[CONIC_LAM_A]) {
       double* dual=w; w += nx_+na_;
       m->qp->getDualSolution(dual);
       casadi_scal(nx_+na_, -1., dual);
       casadi_copy(dual, nx_, res[CONIC_LAM_X]);
       casadi_copy(dual+nx_, na_, res[CONIC_LAM_A]);
     }
     m->fstats.at("postprocessing").toc();
     return m->d_qp.unified_return_status;
   }
References casadi::Conic::A_, casadi::casadi_copy(), casadi::casadi_densify(), casadi::casadi_scal(), casadi::Sparsity::colind(), casadi::CONIC_A, casadi::CONIC_COST, casadi::CONIC_G, casadi::CONIC_H, casadi::CONIC_LAM_A, casadi::CONIC_LAM_X, casadi::CONIC_LBA, casadi::CONIC_LBX, casadi::CONIC_UBA, casadi::CONIC_UBX, casadi::CONIC_X, casadi::copy_vector(), casadi::ProtoFunctionMemory::fstats, casadi::get_ptr(), getErrorMessage(), casadi::Conic::H_, max_cputime_, max_nWSR_, casadi::Conic::na_, casadi::Sparsity::nnz(), casadi::Conic::nx_, casadi::Sparsity::row(), casadi::Sparsity::size1(), casadi::Sparsity::size2(), casadi::SOLVER_RET_INFEASIBLE, casadi::SOLVER_RET_LIMITED, casadi::SOLVER_RET_SUCCESS, sparse_, and casadi::ProtoFunction::verbose_.
sp_forward()
int casadi::FunctionInternal::sp_forward (const bvec_t ** arg, bvec_t ** res, casadi_int * iw, bvec_t * w, void * mem) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mw
Reimplemented in casadi::BSplineInterpolant, casadi::SXFunction, casadi::Rootfinder, casadi::MXFunction, casadi::MapSum, casadi::Map, and casadi::Integrator.
Definition at line 2699 of file function_internal.cpp.
{
     // Loop over outputs
     for (casadi_int oind=0; oind<n_out_; ++oind) {
       // Skip if nothing to assign
       if (res[oind]==nullptr || nnz_out(oind)==0) continue;
       // Clear result
       casadi_clear(res[oind], nnz_out(oind));
       // Loop over inputs
       for (casadi_int iind=0; iind<n_in_; ++iind) {
         // Skip if no seeds
         if (arg[iind]==nullptr || nnz_in(iind)==0) continue;
         // Propagate sparsity for the specific block
         if (sp_forward_block(arg, res, iw, w, mem, oind, iind)) return 1;
       }
     }
     return 0;
   }
References casadi::casadi_clear(), casadi::FunctionInternal::n_in_, casadi::FunctionInternal::n_out_, casadi::FunctionInternal::nnz_in(), casadi::FunctionInternal::nnz_out(), and casadi::FunctionInternal::sp_forward_block().
Referenced by casadi::MXFunction::sp_forward(), and casadi::BSplineInterpolant::sp_forward().
sp_forward_block()
int casadi::FunctionInternal::sp_forward_block (const bvec_t ** arg, bvec_t ** res, casadi_int * iw, bvec_t * w, void * mem, casadi_int oind, casadi_int iind) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mx
Definition at line 2718 of file function_internal.cpp.
{
     // Get the sparsity of the Jacobian block
     Sparsity sp = jac_sparsity(oind, iind, true, false);
     if (sp.is_null() || sp.nnz() == 0) return 0; // Skip if zero
     // Carry out the sparse matrix-vector multiplication
     casadi_int d1 = sp.size2();
     const casadi_int *colind = sp.colind(), *row = sp.row();
     for (casadi_int cc=0; cc<d1; ++cc) {
       for (casadi_int el = colind[cc]; el < colind[cc+1]; ++el) {
         res[oind][row[el]] |= arg[iind][cc];
       }
     }
     return 0;
   }
References casadi::Sparsity::colind(), casadi::SharedObject::is_null(), casadi::FunctionInternal::jac_sparsity(), casadi::Sparsity::nnz(), casadi::Sparsity::row(), and casadi::Sparsity::size2().
Referenced by casadi::FunctionInternal::sp_forward().
sp_reverse()
int casadi::FunctionInternal::sp_reverse (bvec_t ** arg, bvec_t ** res, casadi_int * iw, bvec_t * w, void * mem) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_my
Reimplemented in casadi::BSplineInterpolant, casadi::SXFunction, casadi::Rootfinder, casadi::MXFunction, casadi::MapSum, casadi::Map, and casadi::Integrator.
Definition at line 2734 of file function_internal.cpp.
{
     // Loop over outputs
     for (casadi_int oind=0; oind<n_out_; ++oind) {
       // Skip if nothing to assign
       if (res[oind]==nullptr || nnz_out(oind)==0) continue;
       // Loop over inputs
       for (casadi_int iind=0; iind<n_in_; ++iind) {
         // Skip if no seeds
         if (arg[iind]==nullptr || nnz_in(iind)==0) continue;
         // Get the sparsity of the Jacobian block
         Sparsity sp = jac_sparsity(oind, iind, true, false);
         if (sp.is_null() || sp.nnz() == 0) continue; // Skip if zero
         // Carry out the sparse matrix-vector multiplication
         casadi_int d1 = sp.size2();
         const casadi_int *colind = sp.colind(), *row = sp.row();
         for (casadi_int cc=0; cc<d1; ++cc) {
           for (casadi_int el = colind[cc]; el < colind[cc+1]; ++el) {
             arg[iind][cc] |= res[oind][row[el]];
           }
         }
       }
       // Clear seeds
       casadi_clear(res[oind], nnz_out(oind));
     }
     return 0;
   }
References casadi::casadi_clear(), casadi::Sparsity::colind(), casadi::SharedObject::is_null(), casadi::FunctionInternal::jac_sparsity(), casadi::FunctionInternal::n_in_, casadi::FunctionInternal::n_out_, casadi::Sparsity::nnz(), casadi::FunctionInternal::nnz_in(), casadi::FunctionInternal::nnz_out(), casadi::Sparsity::row(), and casadi::Sparsity::size2().
Referenced by casadi::MXFunction::sp_reverse(), and casadi::BSplineInterpolant::sp_reverse().
sp_weight()
double casadi::FunctionInternal::sp_weight () const virtual inherited
sparsity propagation
Extra doc: https://github.com/casadi/casadi/wiki/L_l6
Definition at line 3124 of file function_internal.cpp.
{
     // If reverse mode propagation unavailable, use forward
     if (!has_sprev()) return 0;
     // If forward mode propagation unavailable, use reverse
     if (!has_spfwd()) return 1;
     // Use the (potentially user set) option
     return ad_weight_sp_;
   }
References casadi::FunctionInternal::ad_weight_sp_, casadi::FunctionInternal::has_spfwd(), and casadi::FunctionInternal::has_sprev().
Referenced by casadi::FunctionInternal::get_jac_sparsity(), casadi::FunctionInternal::get_jac_sparsity_hierarchical(), casadi::MXFunction::sp_forward(), casadi::MXFunction::sp_reverse(), casadi::FunctionInternal::wrap(), and casadi::FunctionInternal::wrap_as_needed().
sparsity_in()
const Sparsity& casadi::FunctionInternal::sparsity_in (casadi_int ind) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mh
Definition at line 965 of file function_internal.hpp.
 { return sparsity_in_.at(ind); }
Referenced by casadi::FunctionInternal::check_arg(), casadi::FixedStepIntegrator::create_advanced(), casadi::FunctionInternal::dm_in(), casadi::FunctionInternal::from_compact(), casadi::FunctionInternal::fwd_seed(), casadi::Integrator::get_forward(), casadi::Integrator::get_reverse(), casadi::JitFunction::JitFunction(), casadi::FunctionInternal::mx_in(), casadi::FunctionInternal::project_arg(), casadi::FunctionInternal::replace_arg(), casadi::FunctionInternal::reverse(), casadi::HpipmInterface::set_hpipm_prob(), casadi::FunctionInternal::sx_in(), and casadi::FunctionInternal::to_compact().
sparsity_out()
const Sparsity& casadi::FunctionInternal::sparsity_out (casadi_int ind) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mh
Definition at line 966 of file function_internal.hpp.
 { return sparsity_out_.at(ind); }
Referenced by casadi::FunctionInternal::call_gen(), casadi::FunctionInternal::check_res(), casadi::FunctionInternal::dm_out(), casadi::FmuFunction::eval(), casadi::FunctionInternal::eval_gen(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::from_compact(), casadi::Integrator::get_reverse(), casadi::FmuFunction::init(), casadi::JitFunction::JitFunction(), casadi::FunctionInternal::mx_out(), casadi::FunctionInternal::replace_res(), casadi::FunctionInternal::sx_out(), and casadi::FunctionInternal::to_compact().
sprint()
void casadi::ProtoFunction::sprint (char * buf, size_t buf_sz, const char * fmt, ...) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_js
Definition at line 3707 of file function_internal.cpp.
{
     // Variable number of arguments
     va_list args;
     va_start(args, fmt);
     // Print to buffer
     casadi_int n = vsnprintf(buf, buf_sz, fmt, args);
     // Cleanup
     va_end(args);
     // Throw error if failure
     casadi_assert(n>=0 && n<buf_sz, "Print failure while processing '" + std::string(fmt) + "'");
   }
Referenced by casadi::ProtoFunction::format_time(), and casadi::ProtoFunction::print_time().
string_from_UnifiedReturnStatus()
std::string casadi::FunctionInternal::string_from_UnifiedReturnStatus (UnifiedReturnStatus status) static inherited
Definition at line 3775 of file function_internal.cpp.
{
     switch (status) {
       case SOLVER_RET_LIMITED:  return "SOLVER_RET_LIMITED";
       case SOLVER_RET_NAN:  return "SOLVER_RET_NAN";
       case SOLVER_RET_SUCCESS:  return "SOLVER_RET_SUCCESS";
       default: return "SOLVER_RET_UNKNOWN";
     }
   }
References casadi::SOLVER_RET_LIMITED, casadi::SOLVER_RET_NAN, and casadi::SOLVER_RET_SUCCESS.
Referenced by casadi::Conic::get_stats(), casadi::Nlpsol::get_stats(), and casadi::Rootfinder::get_stats().
sx_in() [1/2]
const std::vector< SX > casadi::FunctionInternal::sx_in () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_l7
Reimplemented in casadi::SXFunction.
Definition at line 3151 of file function_internal.cpp.
{
     std::vector<SX> ret(n_in_);
     for (casadi_int i=0; i<ret.size(); ++i) {
       ret[i] = sx_in(i);
     }
     return ret;
   }
References casadi::FunctionInternal::n_in_.
sx_in() [2/2]
const SX casadi::FunctionInternal::sx_in (casadi_int ind) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_l7
Reimplemented in casadi::SXFunction.
Definition at line 3135 of file function_internal.cpp.
{
     return SX::sym(name_in_.at(ind), sparsity_in(ind));
   }
References casadi::FunctionInternal::name_in_, casadi::FunctionInternal::sparsity_in(), and casadi::GenericMatrix< Matrix< Scalar > >::sym().
sx_out() [1/2]
const std::vector< SX > casadi::FunctionInternal::sx_out () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_l7
Definition at line 3159 of file function_internal.cpp.
{
     std::vector<SX> ret(n_out_);
     for (casadi_int i=0; i<ret.size(); ++i) {
       ret[i] = sx_out(i);
     }
     return ret;
   }
References casadi::FunctionInternal::n_out_.
sx_out() [2/2]
const SX casadi::FunctionInternal::sx_out (casadi_int ind) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_l7
Definition at line 3139 of file function_internal.cpp.
{
     return SX::sym(name_out_.at(ind), sparsity_out(ind));
   }
References casadi::FunctionInternal::name_out_, casadi::FunctionInternal::sparsity_out(), and casadi::GenericMatrix< Matrix< Scalar > >::sym().
symbolic_output()
std::vector< MX > casadi::FunctionInternal::symbolic_output (const std::vector< MX > & arg) const virtual inherited
Reimplemented in casadi::MXFunction.
Definition at line 1052 of file function_internal.cpp.
{
     return self()(arg);
   }
Referenced by casadi::MXFunction::symbolic_output().
symbolicAdjSeed()
template<typename MatType > std::vector< std::vector< MatType > > casadi::FunctionInternal::symbolicAdjSeed (casadi_int nadj, const std::vector< MatType > & v) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ns
Definition at line 1451 of file function_internal.hpp.
{
     std::vector<std::vector<MatType> > aseed(nadj, v);
     for (casadi_int dir=0; dir<nadj; ++dir) {
       // Replace symbolic inputs
       casadi_int oind=0;
       for (typename std::vector<MatType>::iterator i=aseed[dir].begin();
           i!=aseed[dir].end();
           ++i, ++oind) {
         // Name of the adjoint seed
         std::stringstream ss;
         ss << "a";
         if (nadj>1) ss << dir << "_";
         ss << oind;
         // Save to matrix
         *i = MatType::sym(ss.str(), is_diff_out_[oind] ? i->sparsity() : Sparsity(i->size()));
       }
     }
     return aseed;
   }
References casadi::FunctionInternal::is_diff_out_.
sz_arg()
size_t casadi::FunctionInternal::sz_arg () const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_n0
Definition at line 1128 of file function_internal.hpp.
 { return sz_arg_per_ + sz_arg_tmp_;}
Referenced by casadi::FunctionInternal::alloc(), casadi::FunctionInternal::alloc_arg(), casadi::FunctionInternal::call_gen(), casadi::OmpMap::codegen_body(), casadi::FunctionInternal::codegen_meta(), casadi::OmpMap::eval(), casadi::MXFunction::eval_sx(), casadi::OracleFunction::finalize(), casadi::FunctionInternal::get_jac_sparsity_gen(), casadi::FunctionInternal::get_jac_sparsity_hierarchical(), casadi::FunctionInternal::get_jac_sparsity_hierarchical_symm(), casadi::External::init(), casadi::Nlpsol::init(), casadi::HighsInterface::init(), casadi::HpipmInterface::init(), casadi::Qrqp::init(), and casadi::FunctionInternal::sz_work().
sz_iw()
size_t casadi::FunctionInternal::sz_iw () const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_n2
Definition at line 1138 of file function_internal.hpp.
 { return sz_iw_per_ + sz_iw_tmp_;}
Referenced by casadi::FunctionInternal::alloc(), casadi::FunctionInternal::alloc_iw(), casadi::FunctionInternal::call_gen(), casadi::OmpMap::codegen_body(), casadi::FunctionInternal::codegen_meta(), casadi::OmpMap::eval(), casadi::OracleFunction::finalize(), casadi::FunctionInternal::get_jac_sparsity_gen(), casadi::FunctionInternal::get_jac_sparsity_hierarchical(), casadi::FunctionInternal::get_jac_sparsity_hierarchical_symm(), casadi::External::init(), casadi::Nlpsol::init(), casadi::HighsInterface::init(), casadi::HpipmInterface::init(), casadi::Feasiblesqpmethod::init(), casadi::Qrqp::init(), casadi::Sqpmethod::init(), and casadi::FunctionInternal::sz_work().
sz_res()
size_t casadi::FunctionInternal::sz_res () const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_n1
Definition at line 1133 of file function_internal.hpp.
 { return sz_res_per_ + sz_res_tmp_;}
Referenced by casadi::FunctionInternal::alloc(), casadi::FunctionInternal::alloc_res(), casadi::FunctionInternal::call_gen(), casadi::OmpMap::codegen_body(), casadi::FunctionInternal::codegen_meta(), casadi::OmpMap::eval(), casadi::MXFunction::eval_sx(), casadi::OracleFunction::finalize(), casadi::FunctionInternal::get_jac_sparsity_gen(), casadi::FunctionInternal::get_jac_sparsity_hierarchical(), casadi::FunctionInternal::get_jac_sparsity_hierarchical_symm(), casadi::External::init(), casadi::Nlpsol::init(), casadi::HighsInterface::init(), casadi::HpipmInterface::init(), casadi::Qrqp::init(), and casadi::FunctionInternal::sz_work().
sz_w()
size_t casadi::FunctionInternal::sz_w () const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_n3
Definition at line 1143 of file function_internal.hpp.
 { return sz_w_per_ + sz_w_tmp_;}
Referenced by casadi::FunctionInternal::alloc(), casadi::FunctionInternal::alloc_w(), casadi::FunctionInternal::call_gen(), casadi::OmpMap::codegen_body(), casadi::FunctionInternal::codegen_meta(), casadi::OmpMap::eval(), casadi::OracleFunction::finalize(), casadi::FunctionInternal::get_jac_sparsity_gen(), casadi::FunctionInternal::get_jac_sparsity_hierarchical(), casadi::FunctionInternal::get_jac_sparsity_hierarchical_symm(), casadi::External::init(), casadi::MXFunction::init(), casadi::Nlpsol::init(), casadi::Rootfinder::init(), casadi::HighsInterface::init(), casadi::HpipmInterface::init(), casadi::Feasiblesqpmethod::init(), casadi::Qrqp::init(), casadi::Sqpmethod::init(), casadi::MXFunction::sp_reverse(), and casadi::FunctionInternal::sz_work().
sz_work()
void casadi::FunctionInternal::sz_work (size_t & sz_arg, size_t & sz_res, size_t & sz_iw, size_t & sz_w) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_mz
Definition at line 2766 of file function_internal.cpp.
{
     sz_arg = this->sz_arg();
     sz_res = this->sz_res();
     sz_iw = this->sz_iw();
     sz_w = this->sz_w();
   }
References casadi::FunctionInternal::sz_arg(), casadi::FunctionInternal::sz_iw(), casadi::FunctionInternal::sz_res(), and casadi::FunctionInternal::sz_w().
to_BooleanType()
qpOASES::BooleanType casadi::QpoasesInterface::to_BooleanType (bool b) static protected
Convert between qpOASES types and standard types
Definition at line 781 of file qpoases_interface.cpp.
{
     return b ? qpOASES::BT_TRUE : qpOASES::BT_FALSE;
   }
Referenced by init(), and QpoasesInterface().
to_compact()
Sparsity casadi::FunctionInternal::to_compact (casadi_int oind, casadi_int iind, const Sparsity & sp) const inherited
Definition at line 1818 of file function_internal.cpp.
{
     // Strip rows and columns
     std::vector<casadi_int> mapping;
     return sp.sub(sparsity_out(oind).find(), sparsity_in(iind).find(), mapping);
   }
References casadi::FunctionInternal::find(), casadi::FunctionInternal::sparsity_in(), casadi::FunctionInternal::sparsity_out(), and casadi::Sparsity::sub().
Referenced by casadi::FunctionInternal::jac_sparsity(), and casadi::FunctionInternal::set_jac_sparsity().
to_PrintLevel()
qpOASES::PrintLevel casadi::QpoasesInterface::to_PrintLevel (std::string b) static protected
Convert between qpOASES types and standard types
Definition at line 825 of file qpoases_interface.cpp.
{
     if (b == "tabular") {
       return qpOASES::PL_TABULAR;
     } else if (b == "none") {
       return qpOASES::PL_NONE;
     } else if (b == "low") {
       return qpOASES::PL_LOW;
     } else if (b == "medium") {
       return qpOASES::PL_MEDIUM;
     } else if (b == "high") {
       return qpOASES::PL_HIGH;
     } else if (b == "debug_iter") {
       return qpOASES::PL_DEBUG_ITER;
     } else {
       casadi_error("No such qpOASES::PrintLevel: " + b);
     }
   }
Referenced by init().
to_SubjectToStatus()
qpOASES::SubjectToStatus casadi::QpoasesInterface::to_SubjectToStatus (std::string b) static protected
Convert between qpOASES types and standard types
Definition at line 797 of file qpoases_interface.cpp.
{
     if (b == "inactive") {
       return qpOASES::ST_INACTIVE;
     } else if (b == "lower") {
       return qpOASES::ST_LOWER;
     } else if (b == "infeasible_lower") {
       return qpOASES::ST_INFEASIBLE_LOWER;
     } else if (b == "infeasible_upper") {
       return qpOASES::ST_INFEASIBLE_UPPER;
     } else if (b == "undefined") {
       return qpOASES::ST_UNDEFINED;
     } else {
       casadi_error("No such qpOASES::SubjectToStatus: " + b);
     }
   }
Referenced by init(), and QpoasesInterface().
tocache()
void casadi::FunctionInternal::tocache (const Function & f, const std::string & suffix = "") const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ll
Definition at line 981 of file function_internal.cpp.
{
     // Add to cache
     cache_.insert(std::make_pair(f.name() + ":" + suffix, f));
     // Remove a lost reference, if any, to prevent uncontrolled growth
     for (auto it = cache_.begin(); it!=cache_.end(); ++it) {
       if (!it->second.alive()) {
         cache_.erase(it);
         break; // just one dead reference is enough
       }
     }
   }
References casadi::FunctionInternal::cache_, and casadi::Function::name().
Referenced by casadi::MapSum::create(), casadi::OracleFunction::create_function(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::init(), casadi::FunctionInternal::jacobian(), casadi::FunctionInternal::map(), casadi::FunctionInternal::reverse(), and casadi::FunctionInternal::wrap().
uses_output()
virtual bool casadi::FunctionInternal::uses_output () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_kx
Reimplemented in casadi::Rootfinder, casadi::Nlpsol, casadi::FiniteDiff, and casadi::CallbackInternal.
Definition at line 580 of file function_internal.hpp.
 {return false;}
Referenced by casadi::FunctionInternal::get_sparsity_in().
weak()
WeakRef * casadi::SharedObjectInternal::weak () inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1ai
Definition at line 62 of file shared_object_internal.cpp.
{
     if (weak_ref_==nullptr) {
       weak_ref_ = new WeakRef(this);
     }
     return weak_ref_;
   }
Referenced by casadi::SharedObject::weak().
which_depends()
std::vector< bool > casadi::FunctionInternal::which_depends (const std::string & s_in, const std::vector< std::string > & s_out, casadi_int order, bool tr = false) const virtual inherited
Parameters
[in] s_in Input name
[in] s_out Output name(s)
[in] order Only 1 (linear) and 2 (nonlinear) allowed
[in] tr Flip the relationship. Return which expressions contain the variables
Extra doc: https://github.com/casadi/casadi/wiki/L_k9
Reimplemented in casadi::XFunction< DerivedType, MatType, NodeType >, casadi::XFunction< MXFunction, MX, MXNode >, and casadi::XFunction< SXFunction, Matrix< SXElem >, SXNode >.
Definition at line 3555 of file function_internal.cpp.
{
     casadi_error("'which_depends' not defined for " + class_name());
     return std::vector<bool>();
   }
References casadi::SharedObjectInternal::class_name().
wrap()
Function casadi::FunctionInternal::wrap () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_li
Definition at line 1030 of file function_internal.cpp.
{
     Function f;
     std::string fname = "wrap_" + name_;
     if (!incache(fname, f)) {
       // Options
       Dict opts;
       opts["derivative_of"] = derivative_of_;
       opts["ad_weight"] = ad_weight();
       opts["ad_weight_sp"] = sp_weight();
       opts["max_num_dir"] = max_num_dir_;
       opts["is_diff_in"] = is_diff_in_;
       opts["is_diff_out"] = is_diff_out_;
       // Wrap the function
       std::vector<MX> arg = mx_in();
       std::vector<MX> res = self()(arg);
       f = Function(fname, arg, res, name_in_, name_out_, opts);
       // Save in cache
       tocache(f);
     }
     return f;
   }
References casadi::FunctionInternal::ad_weight(), casadi::FunctionInternal::derivative_of_, casadi::FunctionInternal::Function, casadi::FunctionInternal::incache(), casadi::FunctionInternal::is_diff_in_, casadi::FunctionInternal::is_diff_out_, casadi::FunctionInternal::max_num_dir_, casadi::FunctionInternal::mx_in(), casadi::ProtoFunction::name_, casadi::FunctionInternal::name_in_, casadi::FunctionInternal::name_out_, casadi::FunctionInternal::sp_weight(), and casadi::FunctionInternal::tocache().
Referenced by casadi::FunctionInternal::eval_mx(), casadi::FunctionInternal::factory(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::jacobian(), casadi::FunctionInternal::reverse(), casadi::FunctionInternal::slice(), and casadi::Function::wrap().
wrap_as_needed()
Function casadi::FunctionInternal::wrap_as_needed (const Dict & opts) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_lj
Definition at line 1012 of file function_internal.cpp.
{
     if (opts.empty()) return shared_from_this<Function>();
     std::string fname = "wrap_" + name_;
     // Options
     Dict my_opts = opts;
     my_opts["derivative_of"] = derivative_of_;
     if (my_opts.find("ad_weight")==my_opts.end())
       my_opts["ad_weight"] = ad_weight();
     if (my_opts.find("ad_weight_sp")==my_opts.end())
       my_opts["ad_weight_sp"] = sp_weight();
     if (my_opts.find("max_num_dir")==my_opts.end())
       my_opts["max_num_dir"] = max_num_dir_;
     // Wrap the function
     std::vector<MX> arg = mx_in();
     std::vector<MX> res = self()(arg);
     return Function(fname, arg, res, name_in_, name_out_, my_opts);
   }
References casadi::FunctionInternal::ad_weight(), casadi::FunctionInternal::derivative_of_, casadi::FunctionInternal::Function, casadi::FunctionInternal::max_num_dir_, casadi::FunctionInternal::mx_in(), casadi::ProtoFunction::name_, casadi::FunctionInternal::name_in_, casadi::FunctionInternal::name_out_, and casadi::FunctionInternal::sp_weight().
Referenced by casadi::Function::wrap_as_needed().
Member Data Documentation
A_
Sparsity casadi::Conic::A_ protected inherited
Definition at line 161 of file conic_impl.hpp.
Referenced by casadi::OsqpInterface::codegen_body(), casadi::OsqpInterface::codegen_init_mem(), casadi::Conic::Conic(), casadi::Conic::eval(), casadi::Conic::get_sparsity_in(), casadi::SqicInterface::init(), casadi::HpipmInterface::init(), casadi::HpmpcInterface::init(), casadi::OoqpInterface::init(), casadi::OsqpInterface::init(), casadi::SuperscsInterface::init(), casadi::Ipqp::init(), casadi::QpToNlp::init(), casadi::Qrqp::init(), casadi::HighsInterface::init_dependent(), casadi::CbcInterface::init_mem(), casadi::ClpInterface::init_mem(), casadi::CplexInterface::init_mem(), casadi::OsqpInterface::init_mem(), init_mem(), casadi::Conic::qp_codegen_body(), casadi::Conic::sdp_to_socp_init(), casadi::Conic::serialize_body(), casadi::CbcInterface::solve(), casadi::ClpInterface::solve(), casadi::HpmpcInterface::solve(), casadi::OoqpInterface::solve(), casadi::OsqpInterface::solve(), casadi::ProxqpInterface::solve(), solve(), casadi::SuperscsInterface::solve(), and casadi::Ipqp::solve().
ad_weight_
double casadi::FunctionInternal::ad_weight_ inherited
Definition at line 1305 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::ad_weight(), casadi::FunctionInternal::change_option(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
ad_weight_sp_
double casadi::FunctionInternal::ad_weight_sp_ inherited
Definition at line 1305 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::change_option(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), casadi::FunctionInternal::serialize_body(), and casadi::FunctionInternal::sp_weight().
always_inline_
bool casadi::FunctionInternal::always_inline_ inherited
Definition at line 1209 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::eval_mx(), casadi::MXFunction::eval_mx(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
cache_
std::map<std::string, WeakRef> casadi::FunctionInternal::cache_ mutable inherited
Definition at line 1281 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::cache(), casadi::FunctionInternal::incache(), and casadi::FunctionInternal::tocache().
cache_init_
Dict casadi::FunctionInternal::cache_init_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_26h
Definition at line 1278 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
checkout_
casadi_checkout_t casadi::FunctionInternal::checkout_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_nl
Definition at line 1258 of file function_internal.hpp.
Referenced by casadi::GenericExternal::any_symbol_found(), casadi::External::codegen_checkout(), casadi::External::codegen_declarations(), casadi::External::codegen_mem_type(), casadi::FunctionInternal::eval_gen(), casadi::FunctionInternal::finalize(), casadi::FunctionInternal::FunctionInternal(), casadi::GenericExternal::init_external(), and casadi::FunctionBuffer::operator=().
compiler_
Importer casadi::FunctionInternal::compiler_ inherited
Definition at line 1294 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::finalize(), casadi::FunctionInternal::FunctionInternal(), casadi::Scpgen::init(), casadi::OracleFunction::jit_dependencies(), and casadi::FunctionInternal::serialize_body().
compiler_plugin_
std::string casadi::FunctionInternal::compiler_plugin_ inherited
Definition at line 1293 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::finalize(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), casadi::Scpgen::init(), casadi::OracleFunction::jit_dependencies(), and casadi::FunctionInternal::serialize_body().
custom_jacobian_
Function casadi::FunctionInternal::custom_jacobian_ inherited
Definition at line 1342 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
der_options_
Dict casadi::FunctionInternal::der_options_ inherited
Definition at line 1339 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::forward(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), casadi::FunctionInternal::jacobian(), casadi::FunctionInternal::reverse(), and casadi::FunctionInternal::serialize_body().
derivative_of_
Function casadi::FunctionInternal::derivative_of_ inherited
Definition at line 1287 of file function_internal.hpp.
Referenced by casadi::FiniteDiff::codegen_body(), casadi::LinearInterpolantJac::codegen_body(), casadi::FiniteDiff::codegen_declarations(), casadi::FiniteDiff::eval(), casadi::LinearInterpolantJac::eval(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FiniteDiff::get_default_in(), casadi::CentralDiff::get_forward(), casadi::FunctionInternal::get_n_in(), casadi::FiniteDiff::get_n_in(), casadi::FunctionInternal::get_n_out(), casadi::FiniteDiff::get_n_out(), casadi::FunctionInternal::get_name_in(), casadi::FiniteDiff::get_name_in(), casadi::FunctionInternal::get_name_out(), casadi::FiniteDiff::get_name_out(), casadi::FunctionInternal::get_sparsity_in(), casadi::FiniteDiff::get_sparsity_in(), casadi::FunctionInternal::get_sparsity_out(), casadi::FiniteDiff::get_sparsity_out(), casadi::LinearInterpolantJac::has_parametric_grid(), casadi::LinearInterpolantJac::has_parametric_values(), casadi::FiniteDiff::init(), casadi::FunctionInternal::init(), casadi::SundialsInterface::init(), casadi::LinearInterpolantJac::init(), casadi::FunctionInternal::jac_is_symm(), casadi::FunctionInternal::serialize_body(), casadi::LinearInterpolantJac::serialize_type(), casadi::FunctionInternal::wrap(), and casadi::FunctionInternal::wrap_as_needed().
deserialize_map
std::map< std::string, ProtoFunction *(*)(DeserializingStream &)> casadi::FunctionInternal::deserialize_map static inherited
Initial value:
= {
    {"MXFunction", MXFunction::deserialize},
    {"SXFunction", SXFunction::deserialize},
    {"Interpolant", Interpolant::deserialize},
    {"Switch", Switch::deserialize},
    {"Map", Map::deserialize},
    {"MapSum", MapSum::deserialize},
    {"Nlpsol", Nlpsol::deserialize},
    {"Rootfinder", Rootfinder::deserialize},
    {"Integrator", Integrator::deserialize},
    {"External", External::deserialize},
    {"Conic", Conic::deserialize},
  }
Definition at line 1386 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::deserialize().
discrete_
std::vector<bool> casadi::Conic::discrete_ protected inherited
Definition at line 157 of file conic_impl.hpp.
Referenced by casadi::Conic::Conic(), casadi::Conic::init(), casadi::CplexInterface::init(), casadi::HighsInterface::init_dependent(), casadi::Conic::serialize_body(), casadi::HighsInterface::set_highs_prob(), casadi::CbcInterface::solve(), casadi::CplexInterface::solve(), and casadi::GurobiInterface::solve().
dump_
bool casadi::FunctionInternal::dump_ inherited
Definition at line 1330 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::change_option(), casadi::FunctionInternal::eval_gen(), casadi::FunctionInternal::finalize(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), and casadi::FunctionInternal::init().
dump_count_
casadi_int casadi::FunctionInternal::dump_count_ = 0 mutable inherited
Definition at line 1345 of file function_internal.hpp.
dump_dir_
std::string casadi::FunctionInternal::dump_dir_ inherited
Definition at line 1333 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::change_option(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
dump_format_
std::string casadi::FunctionInternal::dump_format_ inherited
Definition at line 1336 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::change_option(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
dump_in_
bool casadi::FunctionInternal::dump_in_ inherited
Definition at line 1330 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::change_option(), casadi::FunctionInternal::eval_gen(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
dump_out_
bool casadi::FunctionInternal::dump_out_ inherited
Definition at line 1330 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::change_option(), casadi::FunctionInternal::eval_gen(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
enable_fd_
bool casadi::FunctionInternal::enable_fd_ inherited
Definition at line 1301 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::ad_weight(), casadi::FunctionInternal::adjViaJac(), casadi::FunctionInternal::call_forward(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::fwdViaJac(), casadi::FunctionInternal::get_partition(), casadi::FunctionInternal::has_derivative(), casadi::FunctionInternal::init(), casadi::JitFunction::JitFunction(), and casadi::FunctionInternal::serialize_body().
enable_fd_op_
bool casadi::FunctionInternal::enable_fd_op_ inherited
Definition at line 1302 of file function_internal.hpp.
Referenced by casadi::FmuFunction::FmuFunction(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
enable_forward_
bool casadi::FunctionInternal::enable_forward_ inherited
Definition at line 1301 of file function_internal.hpp.
Referenced by casadi::MXFunction::ad_forward(), casadi::FunctionInternal::ad_weight(), casadi::FunctionInternal::adjViaJac(), casadi::FunctionInternal::call_forward(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::fwdViaJac(), casadi::FunctionInternal::get_partition(), casadi::FunctionInternal::has_derivative(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
enable_forward_op_
bool casadi::FunctionInternal::enable_forward_op_ inherited
Definition at line 1302 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
enable_jacobian_
bool casadi::FunctionInternal::enable_jacobian_ inherited
Definition at line 1301 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::has_derivative(), casadi::FunctionInternal::init(), casadi::FunctionInternal::jacobian(), and casadi::FunctionInternal::serialize_body().
enable_jacobian_op_
bool casadi::FunctionInternal::enable_jacobian_op_ inherited
Definition at line 1302 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
enable_reverse_
bool casadi::FunctionInternal::enable_reverse_ inherited
Definition at line 1301 of file function_internal.hpp.
Referenced by casadi::MXFunction::ad_reverse(), casadi::FunctionInternal::ad_weight(), casadi::FunctionInternal::adjViaJac(), casadi::FunctionInternal::call_reverse(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::fwdViaJac(), casadi::FunctionInternal::get_partition(), casadi::FunctionInternal::has_derivative(), casadi::FunctionInternal::init(), casadi::FunctionInternal::reverse(), and casadi::FunctionInternal::serialize_body().
enable_reverse_op_
bool casadi::FunctionInternal::enable_reverse_op_ inherited
Definition at line 1302 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
error_on_fail_
bool casadi::ProtoFunction::error_on_fail_ inherited
Definition at line 249 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::call_gen(), casadi::HighsInterface::codegen_body(), casadi::HpipmInterface::codegen_body(), casadi::OsqpInterface::codegen_body(), casadi::Qrqp::codegen_body(), casadi::Conic::Conic(), casadi::Conic::eval(), casadi::Nlpsol::eval(), casadi::Rootfinder::eval(), casadi::ProtoFunction::generate_options(), casadi::ProtoFunction::init(), casadi::Nlpsol::Nlpsol(), casadi::ProtoFunction::ProtoFunction(), casadi::Rootfinder::Rootfinder(), casadi::ProtoFunction::serialize_body(), casadi::CplexInterface::solve(), and casadi::KinsolInterface::solve().
eval_
eval_t casadi::FunctionInternal::eval_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_nk
Definition at line 1253 of file function_internal.hpp.
Referenced by casadi::FunctionBuffer::_eval(), casadi::GenericExternal::any_symbol_found(), casadi::FunctionInternal::eval_gen(), casadi::FunctionInternal::finalize(), casadi::FunctionInternal::FunctionInternal(), and casadi::GenericExternal::init_external().
fd_method_
std::string casadi::FunctionInternal::fd_method_ inherited
Definition at line 1320 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::forward(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FmuFunction::init(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
fd_options_
Dict casadi::FunctionInternal::fd_options_ inherited
Definition at line 1314 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::forward(), casadi::FunctionInternal::generate_options(), and casadi::FunctionInternal::init().
fd_step_
double casadi::FunctionInternal::fd_step_ inherited
Definition at line 1317 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
forward_options_
Dict casadi::FunctionInternal::forward_options_ inherited
Definition at line 1339 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::forward(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
H_
Sparsity casadi::Conic::H_ protected inherited
Definition at line 161 of file conic_impl.hpp.
Referenced by casadi::OsqpInterface::codegen_body(), casadi::OsqpInterface::codegen_init_mem(), casadi::Conic::Conic(), casadi::Conic::eval(), casadi::Conic::get_sparsity_in(), casadi::CbcInterface::init(), casadi::ClpInterface::init(), casadi::HpipmInterface::init(), casadi::HpmpcInterface::init(), casadi::OoqpInterface::init(), casadi::OsqpInterface::init(), casadi::SuperscsInterface::init(), casadi::Ipqp::init(), casadi::QpToNlp::init(), casadi::Qrqp::init(), casadi::HighsInterface::init_dependent(), casadi::CplexInterface::init_mem(), casadi::OsqpInterface::init_mem(), casadi::ProxqpInterface::init_mem(), init_mem(), casadi::Conic::qp_codegen_body(), casadi::Conic::serialize_body(), casadi::GurobiInterface::solve(), casadi::HpmpcInterface::solve(), casadi::OoqpInterface::solve(), casadi::OsqpInterface::solve(), casadi::ProxqpInterface::solve(), solve(), casadi::SuperscsInterface::solve(), and casadi::Ipqp::solve().
has_refcount_
bool casadi::FunctionInternal::has_refcount_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_no
Definition at line 1273 of file function_internal.hpp.
Referenced by casadi::CodeGenerator::add_dependency(), casadi::FunctionInternal::FunctionInternal(), casadi::Call::has_refcount(), casadi::External::init(), casadi::MXFunction::init(), casadi::OsqpInterface::OsqpInterface(), and casadi::FunctionInternal::serialize_body().
hess_
qpOASES::HessianType casadi::QpoasesInterface::hess_ protected
Options
Definition at line 191 of file qpoases_interface.hpp.
Referenced by init(), init_mem(), QpoasesInterface(), and serialize_body().
infix_
const std::string casadi::Conic::infix_ = "conic" static inherited
Definition at line 126 of file conic_impl.hpp.
inputs_check_
bool casadi::FunctionInternal::inputs_check_ inherited
Definition at line 1311 of file function_internal.hpp.
Referenced by casadi::Nlpsol::check_inputs(), casadi::Conic::eval(), casadi::SqicInterface::evaluate(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), casadi::FunctionInternal::serialize_body(), and casadi::GurobiInterface::solve().
is_diff_in_
std::vector<bool> casadi::FunctionInternal::is_diff_in_ inherited
Definition at line 1215 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::codegen_meta(), casadi::FunctionInternal::definition(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::fwd_seed(), casadi::FunctionInternal::init(), casadi::Map::init(), casadi::MapSum::init(), casadi::FunctionInternal::jac_sparsity(), casadi::FunctionInternal::serialize_body(), and casadi::FunctionInternal::wrap().
is_diff_out_
std::vector<bool> casadi::FunctionInternal::is_diff_out_ inherited
Definition at line 1215 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::codegen_meta(), casadi::FunctionInternal::definition(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::init(), casadi::Map::init(), casadi::MapSum::init(), casadi::FunctionInternal::jac_sparsity(), casadi::FunctionInternal::serialize_body(), casadi::FunctionInternal::symbolicAdjSeed(), and casadi::FunctionInternal::wrap().
jac_penalty_
double casadi::FunctionInternal::jac_penalty_ inherited
Definition at line 1298 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::adjViaJac(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::fwdViaJac(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
jac_sparsity_
std::vector<Sparsity> casadi::FunctionInternal::jac_sparsity_[2] mutable inherited
Definition at line 1284 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::jac_sparsity(), and casadi::FunctionInternal::set_jac_sparsity().
jacobian_options_
Dict casadi::FunctionInternal::jacobian_options_ inherited
Definition at line 1339 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), casadi::FunctionInternal::jacobian(), and casadi::FunctionInternal::serialize_body().
jit_
bool casadi::FunctionInternal::jit_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_nf
Definition at line 1226 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::finalize(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), casadi::JitFunction::JitFunction(), casadi::OracleFunction::OracleFunction(), casadi::FunctionInternal::serialize_body(), casadi::OracleFunction::serialize_body(), and casadi::FunctionInternal::~FunctionInternal().
jit_base_name_
std::string casadi::FunctionInternal::jit_base_name_ inherited
Definition at line 1243 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::finalize(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
jit_cleanup_
bool casadi::FunctionInternal::jit_cleanup_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ng
Definition at line 1231 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), casadi::FunctionInternal::serialize_body(), and casadi::FunctionInternal::~FunctionInternal().
jit_name_
std::string casadi::FunctionInternal::jit_name_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_ni
Definition at line 1241 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::finalize(), and casadi::FunctionInternal::~FunctionInternal().
jit_options_
Dict casadi::FunctionInternal::jit_options_ inherited
Definition at line 1295 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::finalize(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), casadi::Scpgen::init(), casadi::OracleFunction::jit_dependencies(), casadi::FunctionInternal::serialize_body(), and casadi::FunctionInternal::~FunctionInternal().
jit_serialize_
std::string casadi::FunctionInternal::jit_serialize_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_nh
Definition at line 1236 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), casadi::OracleFunction::OracleFunction(), casadi::FunctionInternal::serialize_body(), and casadi::OracleFunction::serialize_body().
jit_temp_suffix_
bool casadi::FunctionInternal::jit_temp_suffix_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_nj
Definition at line 1248 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::finalize(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
linsol_plugin_
std::string casadi::QpoasesInterface::linsol_plugin_ protected
Options
Definition at line 195 of file qpoases_interface.hpp.
Referenced by init(), init_mem(), QpoasesInterface(), and serialize_body().
max_cputime_
double casadi::QpoasesInterface::max_cputime_ protected
Options
Definition at line 189 of file qpoases_interface.hpp.
Referenced by init(), QpoasesInterface(), serialize_body(), and solve().
max_io_
casadi_int casadi::FunctionInternal::max_io_ inherited
Definition at line 1327 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
max_num_dir_
casadi_int casadi::FunctionInternal::max_num_dir_ inherited
Definition at line 1308 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::call_forward(), casadi::FunctionInternal::call_reverse(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), casadi::FunctionInternal::serialize_body(), casadi::FunctionInternal::wrap(), and casadi::FunctionInternal::wrap_as_needed().
max_nWSR_
casadi_int casadi::QpoasesInterface::max_nWSR_ protected
Options
Definition at line 188 of file qpoases_interface.hpp.
Referenced by init(), QpoasesInterface(), serialize_body(), and solve().
max_schur_
casadi_int casadi::QpoasesInterface::max_schur_ protected
Options
Definition at line 194 of file qpoases_interface.hpp.
Referenced by init(), init_mem(), QpoasesInterface(), and serialize_body().
meta_doc
const std::string casadi::QpoasesInterface::meta_doc static
Definition at line 145 of file qpoases_interface.hpp.
Referenced by casadi::casadi_register_conic_qpoases().
n_in_
size_t casadi::FunctionInternal::n_in_ inherited
Definition at line 1212 of file function_internal.hpp.
Referenced by casadi::Rootfinder::ad_reverse(), casadi::MXFunction::ad_reverse(), casadi::FunctionInternal::all_scalar(), casadi::KinsolInterface::bjac(), casadi::FunctionInternal::call_forward(), casadi::FunctionInternal::call_gen(), casadi::FunctionInternal::call_reverse(), casadi::FunctionInternal::check_arg(), casadi::JitFunction::codegen_body(), casadi::Map::codegen_body(), casadi::OmpMap::codegen_body(), casadi::MapSum::codegen_body(), casadi::MXFunction::codegen_body(), casadi::Switch::codegen_body(), casadi::FastNewton::codegen_body(), casadi::FunctionInternal::codegen_meta(), casadi::FunctionInternal::convert_arg(), casadi::FunctionInternal::definition(), casadi::KinsolInterface::djac(), casadi::FunctionInternal::dm_in(), casadi::FunctionInternal::eval(), casadi::OmpMap::eval(), casadi::MXFunction::eval(), casadi::Switch::eval(), casadi::Map::eval_gen(), casadi::MapSum::eval_gen(), casadi::MXFunction::eval_mx(), casadi::Switch::eval_sx(), casadi::CallbackInternal::finalize(), casadi::FunctionInternal::forward(), casadi::KinsolInterface::func(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::fwd_seed(), casadi::FunctionInternal::generate_in(), casadi::GenericExternal::get_jac_sparsity(), casadi::GenericExternal::has_jac_sparsity(), casadi::FunctionInternal::init(), casadi::MXFunction::init(), casadi::Switch::init(), casadi::ImplicitToNlp::init(), casadi::FunctionInternal::jac_sparsity(), casadi::FunctionInternal::jacobian(), casadi::KinsolInterface::jtimes(), casadi::FunctionInternal::mapsum_mx(), casadi::FunctionInternal::matching_arg(), casadi::FunctionInternal::mx_in(), casadi::FunctionInternal::nnz_in(), casadi::FunctionInternal::numel_in(), casadi::FunctionInternal::nz_in(), casadi::FunctionInternal::print_dimensions(), casadi::FunctionInternal::print_in(), casadi::FunctionInternal::project_arg(), casadi::KinsolInterface::psetup(), casadi::FunctionInternal::reverse(), casadi::FunctionInternal::set_jac_sparsity(), casadi::Rootfinder::set_work(), casadi::QpToNlp::solve(), casadi::KinsolInterface::solve(), casadi::FastNewton::solve(), casadi::ImplicitToNlp::solve(), casadi::Newton::solve(), casadi::FunctionInternal::sp_forward(), casadi::Integrator::sp_forward(), casadi::MXFunction::sp_forward(), casadi::Rootfinder::sp_forward(), casadi::FunctionInternal::sp_reverse(), casadi::Integrator::sp_reverse(), casadi::Map::sp_reverse(), casadi::MapSum::sp_reverse(), casadi::MXFunction::sp_reverse(), casadi::Rootfinder::sp_reverse(), and casadi::FunctionInternal::sx_in().
n_out_
size_t casadi::FunctionInternal::n_out_ inherited
Definition at line 1212 of file function_internal.hpp.
Referenced by casadi::Rootfinder::ad_forward(), casadi::MXFunction::ad_forward(), casadi::Rootfinder::ad_reverse(), casadi::FunctionInternal::all_scalar(), casadi::KinsolInterface::bjac(), casadi::FunctionInternal::call(), casadi::FunctionInternal::call_forward(), casadi::FunctionInternal::call_gen(), casadi::FunctionInternal::call_reverse(), casadi::FunctionInternal::check_res(), casadi::JitFunction::codegen_body(), casadi::Map::codegen_body(), casadi::OmpMap::codegen_body(), casadi::MapSum::codegen_body(), casadi::MXFunction::codegen_body(), casadi::Switch::codegen_body(), casadi::FastNewton::codegen_body(), casadi::FunctionInternal::codegen_meta(), casadi::FunctionInternal::convert_res(), casadi::FunctionInternal::definition(), casadi::KinsolInterface::djac(), casadi::FunctionInternal::dm_out(), casadi::FunctionInternal::eval(), casadi::OmpMap::eval(), casadi::MXFunction::eval(), casadi::Switch::eval(), casadi::FunctionInternal::eval_gen(), casadi::Map::eval_gen(), casadi::MapSum::eval_gen(), casadi::Switch::eval_sx(), casadi::CallbackInternal::finalize(), casadi::FunctionInternal::forward(), casadi::KinsolInterface::func(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_out(), casadi::LinearInterpolantJac::get_jacobian(), casadi::FunctionInternal::init(), casadi::MapSum::init(), casadi::Nlpsol::init(), casadi::Switch::init(), casadi::FunctionInternal::jac_sparsity(), casadi::FunctionInternal::jacobian(), casadi::FunctionInternal::mapsum_mx(), casadi::FunctionInternal::matching_res(), casadi::FunctionInternal::mx_out(), casadi::FunctionInternal::nnz_out(), casadi::FunctionInternal::numel_out(), casadi::FunctionInternal::nz_out(), casadi::FunctionInternal::print_dimensions(), casadi::FunctionInternal::print_out(), casadi::KinsolInterface::psetup(), casadi::FunctionInternal::reverse(), casadi::FunctionInternal::set_jac_sparsity(), casadi::Rootfinder::set_work(), casadi::QpToNlp::solve(), casadi::KinsolInterface::solve(), casadi::FastNewton::solve(), casadi::ImplicitToNlp::solve(), casadi::Newton::solve(), casadi::FunctionInternal::sp_forward(), casadi::Integrator::sp_forward(), casadi::MXFunction::sp_forward(), casadi::Rootfinder::sp_forward(), casadi::FunctionInternal::sp_reverse(), casadi::Integrator::sp_reverse(), casadi::Map::sp_reverse(), casadi::MapSum::sp_reverse(), casadi::MXFunction::sp_reverse(), casadi::Rootfinder::sp_reverse(), and casadi::FunctionInternal::sx_out().
na_
casadi_int casadi::Conic::na_ protected inherited
Definition at line 167 of file conic_impl.hpp.
Referenced by casadi::Conic::check_inputs(), casadi::OsqpInterface::codegen_body(), casadi::Qrqp::codegen_body(), casadi::OsqpInterface::codegen_init_mem(), casadi::Conic::Conic(), casadi::Conic::eval(), casadi::Conic::get_sparsity_out(), casadi::CbcInterface::init(), casadi::ClpInterface::init(), casadi::CplexInterface::init(), casadi::HpipmInterface::init(), casadi::HpmpcInterface::init(), casadi::OoqpInterface::init(), casadi::OsqpInterface::init(), casadi::ProxqpInterface::init(), init(), casadi::Ipqp::init(), casadi::Qrqp::init(), casadi::CplexInterface::init_mem(), casadi::HpmpcInterface::init_mem(), casadi::OsqpInterface::init_mem(), casadi::ProxqpInterface::init_mem(), init_mem(), casadi::Conic::serialize_body(), casadi::CbcInterface::solve(), casadi::ClpInterface::solve(), casadi::CplexInterface::solve(), casadi::GurobiInterface::solve(), casadi::HpmpcInterface::solve(), casadi::OoqpInterface::solve(), casadi::OsqpInterface::solve(), casadi::ProxqpInterface::solve(), solve(), casadi::SuperscsInterface::solve(), and casadi::Qrqp::solve().
name_
std::string casadi::ProtoFunction::name_ inherited
Definition at line 234 of file function_internal.hpp.
Referenced by casadi::MXFunction::ad_forward(), casadi::MXFunction::ad_reverse(), casadi::Integrator::augmented_dae(), casadi::OracleFunction::calc_function(), casadi::FunctionInternal::call_forward(), casadi::FunctionInternal::call_reverse(), casadi::FunctionInternal::codegen_body(), casadi::External::codegen_body(), casadi::External::codegen_checkout(), casadi::External::codegen_declarations(), casadi::MXFunction::codegen_declarations(), casadi::External::codegen_decref(), casadi::External::codegen_incref(), casadi::FunctionInternal::codegen_meta(), casadi::FunctionInternal::codegen_name(), casadi::External::codegen_release(), casadi::FunctionInternal::codegen_sparsities(), casadi::ProtoFunction::construct(), casadi::OracleFunction::create_function(), casadi::FunctionInternal::definition(), casadi::FunctionInternal::eval(), casadi::MXFunction::eval(), casadi::FunctionInternal::eval_mx(), casadi::MXFunction::eval_mx(), casadi::FmuFunction::factory(), casadi::FunctionInternal::finalize(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::FunctionInternal(), casadi::Integrator::get_forward(), casadi::Integrator::get_forward_dae(), casadi::Map::get_function(), casadi::MapSum::get_function(), casadi::OracleFunction::get_function(), casadi::GenericExternal::get_jac_sparsity(), casadi::FunctionInternal::get_n_in(), casadi::External::get_n_in(), casadi::FunctionInternal::get_n_out(), casadi::External::get_n_out(), casadi::FunctionInternal::get_name_in(), casadi::External::get_name_in(), casadi::FunctionInternal::get_name_out(), casadi::External::get_name_out(), casadi::FunctionInternal::get_partition(), casadi::Integrator::get_reverse(), casadi::FunctionInternal::get_sparsity_in(), casadi::GenericExternal::get_sparsity_in(), casadi::FunctionInternal::get_sparsity_out(), casadi::GenericExternal::get_sparsity_out(), casadi::External::has_forward(), casadi::GenericExternal::has_jac_sparsity(), casadi::External::has_jacobian(), casadi::External::has_reverse(), casadi::External::init(), casadi::FunctionInternal::init(), casadi::MXFunction::init(), casadi::CvodesInterface::init(), casadi::IdasInterface::init(), casadi::External::init_external(), casadi::GenericExternal::init_external(), casadi::FunctionInternal::jac_is_symm(), casadi::FunctionInternal::jacobian(), casadi::FunctionInternal::map(), casadi::OracleFunction::monitored(), casadi::MXFunction::print_arg(), casadi::FunctionInternal::print_in(), casadi::FunctionInternal::print_out(), casadi::MXFunction::print_res(), casadi::ProtoFunction::print_time(), casadi::ProtoFunction::ProtoFunction(), casadi::CvodesInterface::reset(), casadi::IdasInterface::reset(), casadi::IdasInterface::resetB(), casadi::FunctionInternal::reverse(), casadi::ProtoFunction::serialize_body(), casadi::GurobiInterface::solve(), casadi::SnoptInterface::solve(), casadi::Integrator::sp_forward(), casadi::Integrator::sp_reverse(), casadi::FunctionInternal::wrap(), and casadi::FunctionInternal::wrap_as_needed().
name_in_
std::vector<std::string> casadi::FunctionInternal::name_in_ inherited
Definition at line 1221 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::check_arg(), casadi::JitFunction::codegen_body(), casadi::FunctionInternal::codegen_meta(), casadi::FunctionInternal::convert_arg(), casadi::FunctionInternal::definition(), casadi::FunctionInternal::diff_prefix(), casadi::FmuFunction::FmuFunction(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::fwd_seed(), casadi::FmuFunction::get_stats(), casadi::FunctionInternal::init(), casadi::FunctionInternal::jacobian(), casadi::JitFunction::JitFunction(), casadi::FunctionInternal::mx_in(), casadi::FunctionInternal::print_dimensions(), casadi::FunctionInternal::print_in(), casadi::FunctionInternal::reverse(), casadi::FunctionInternal::serialize_body(), casadi::FunctionInternal::sx_in(), casadi::FunctionInternal::wrap(), casadi::FunctionInternal::wrap_as_needed(), and casadi::XFunction< DerivedType, MatType, NodeType >::XFunction().
name_out_
std::vector<std::string> casadi::FunctionInternal::name_out_ inherited
Definition at line 1221 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::check_res(), casadi::JitFunction::codegen_body(), casadi::FunctionInternal::codegen_meta(), casadi::FunctionInternal::convert_res(), casadi::FunctionInternal::definition(), casadi::FunctionInternal::diff_prefix(), casadi::FunctionInternal::eval_gen(), casadi::FmuFunction::FmuFunction(), casadi::FunctionInternal::forward(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::init(), casadi::FunctionInternal::jacobian(), casadi::JitFunction::JitFunction(), casadi::FunctionInternal::mx_out(), casadi::FunctionInternal::print_dimensions(), casadi::FunctionInternal::print_out(), casadi::FunctionInternal::reverse(), casadi::FunctionInternal::serialize_body(), casadi::FunctionInternal::sx_out(), casadi::FunctionInternal::wrap(), casadi::FunctionInternal::wrap_as_needed(), and casadi::XFunction< DerivedType, MatType, NodeType >::XFunction().
never_inline_
bool casadi::FunctionInternal::never_inline_ inherited
Definition at line 1209 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::eval_mx(), casadi::MXFunction::eval_mx(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
np_
casadi_int casadi::Conic::np_ protected inherited
Definition at line 170 of file conic_impl.hpp.
Referenced by casadi::Conic::Conic(), casadi::Conic::init(), casadi::Conic::sdp_to_socp_init(), and casadi::Conic::serialize_body().
nx_
casadi_int casadi::Conic::nx_ protected inherited
Definition at line 164 of file conic_impl.hpp.
Referenced by casadi::Conic::check_inputs(), casadi::OsqpInterface::codegen_body(), casadi::Qrqp::codegen_body(), casadi::OsqpInterface::codegen_init_mem(), casadi::Conic::Conic(), casadi::Conic::eval(), casadi::Conic::get_sparsity_out(), casadi::Conic::init(), casadi::CbcInterface::init(), casadi::ClpInterface::init(), casadi::CplexInterface::init(), casadi::GurobiInterface::init(), casadi::HpipmInterface::init(), casadi::HpmpcInterface::init(), casadi::OoqpInterface::init(), casadi::OsqpInterface::init(), casadi::ProxqpInterface::init(), init(), casadi::SuperscsInterface::init(), casadi::Ipqp::init(), casadi::QpToNlp::init(), casadi::Qrqp::init(), casadi::HighsInterface::init_dependent(), casadi::CplexInterface::init_mem(), casadi::HpmpcInterface::init_mem(), casadi::OsqpInterface::init_mem(), casadi::ProxqpInterface::init_mem(), init_mem(), casadi::SuperscsInterface::init_mem(), casadi::Conic::sdp_to_socp_init(), casadi::Conic::serialize_body(), casadi::CbcInterface::solve(), casadi::ClpInterface::solve(), casadi::CplexInterface::solve(), casadi::GurobiInterface::solve(), casadi::HpmpcInterface::solve(), casadi::OoqpInterface::solve(), casadi::OsqpInterface::solve(), casadi::ProxqpInterface::solve(), solve(), casadi::SuperscsInterface::solve(), and casadi::Qrqp::solve().
ops_
qpOASES::Options casadi::QpoasesInterface::ops_ protected
Options
Definition at line 190 of file qpoases_interface.hpp.
Referenced by init(), init_mem(), QpoasesInterface(), and serialize_body().
options_
const Options casadi::QpoasesInterface::options_ static
Definition at line 124 of file qpoases_interface.hpp.
Referenced by casadi::casadi_register_conic_qpoases().
P_
Sparsity casadi::Conic::P_ protected inherited
Definition at line 161 of file conic_impl.hpp.
Referenced by casadi::Conic::Conic(), casadi::Conic::get_sparsity_in(), casadi::Conic::sdp_to_socp_init(), and casadi::Conic::serialize_body().
p_qp_
casadi_qp_prob<double> casadi::Conic::p_qp_ inherited
Definition at line 47 of file conic_impl.hpp.
Referenced by casadi::HighsInterface::set_highs_prob(), and casadi::HpipmInterface::set_hpipm_prob().
print_in_
bool casadi::FunctionInternal::print_in_ inherited
Definition at line 1323 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::change_option(), casadi::FunctionInternal::eval_gen(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
print_out_
bool casadi::FunctionInternal::print_out_ inherited
Definition at line 1324 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::change_option(), casadi::FunctionInternal::eval_gen(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), and casadi::FunctionInternal::serialize_body().
print_problem_
bool casadi::Conic::print_problem_ protected inherited
Definition at line 158 of file conic_impl.hpp.
Referenced by casadi::Conic::Conic(), casadi::Conic::eval(), casadi::Conic::init(), and casadi::Conic::serialize_body().
print_time_
bool casadi::ProtoFunction::print_time_ inherited
Definition at line 240 of file function_internal.hpp.
Referenced by casadi::FixedStepIntegrator::create_advanced(), casadi::ProtoFunction::generate_options(), casadi::ProtoFunction::init(), casadi::FunctionInternal::init(), casadi::Nlpsol::Nlpsol(), casadi::ProtoFunction::print_time(), casadi::ProtoFunction::ProtoFunction(), and casadi::ProtoFunction::serialize_body().
Q_
Sparsity casadi::Conic::Q_ protected inherited
Definition at line 161 of file conic_impl.hpp.
Referenced by casadi::Conic::Conic(), casadi::Conic::get_sparsity_in(), casadi::SuperscsInterface::init(), casadi::Conic::sdp_to_socp_init(), casadi::Conic::serialize_body(), and casadi::SuperscsInterface::solve().
record_time_
bool casadi::ProtoFunction::record_time_ inherited
Definition at line 243 of file function_internal.hpp.
Referenced by casadi::ProtoFunction::generate_options(), casadi::ProtoFunction::init(), casadi::FunctionInternal::init(), casadi::ProtoFunction::init_mem(), casadi::LinsolInternal::init_mem(), casadi::ProtoFunction::ProtoFunction(), and casadi::ProtoFunction::serialize_body().
regularity_check_
bool casadi::ProtoFunction::regularity_check_ inherited
Definition at line 246 of file function_internal.hpp.
Referenced by casadi::OracleFunction::calc_function(), casadi::ProtoFunction::change_option(), casadi::FunctionInternal::eval_gen(), casadi::FunctionInternal::FunctionInternal(), casadi::ProtoFunction::generate_options(), casadi::ProtoFunction::init(), casadi::ProtoFunction::ProtoFunction(), and casadi::ProtoFunction::serialize_body().
release_
casadi_release_t casadi::FunctionInternal::release_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_nm
Definition at line 1263 of file function_internal.hpp.
Referenced by casadi::GenericExternal::any_symbol_found(), casadi::External::codegen_declarations(), casadi::External::codegen_release(), casadi::FunctionInternal::eval_gen(), casadi::FunctionInternal::finalize(), casadi::FunctionInternal::FunctionInternal(), casadi::GenericExternal::init_external(), and casadi::FunctionBuffer::~FunctionBuffer().
reverse_options_
Dict casadi::FunctionInternal::reverse_options_ inherited
Definition at line 1339 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), casadi::FunctionInternal::init(), casadi::FunctionInternal::reverse(), and casadi::FunctionInternal::serialize_body().
schur_
bool casadi::QpoasesInterface::schur_ protected
Options
Definition at line 193 of file qpoases_interface.hpp.
Referenced by init(), init_mem(), QpoasesInterface(), and serialize_body().
solvers_
std::map< std::string, Conic::Plugin > casadi::Conic::solvers_ static inherited
Definition at line 123 of file conic_impl.hpp.
sparse_
bool casadi::QpoasesInterface::sparse_ protected
Options
Definition at line 192 of file qpoases_interface.hpp.
Referenced by init(), QpoasesInterface(), serialize_body(), and solve().
sparsity_in_
std::vector<Sparsity> casadi::FunctionInternal::sparsity_in_ inherited
Definition at line 1218 of file function_internal.hpp.
Referenced by casadi::CodeGenerator::add(), casadi::FunctionInternal::all_scalar(), casadi::Switch::codegen_body(), casadi::FunctionInternal::codegen_meta(), casadi::FunctionInternal::codegen_sparsities(), casadi::FunctionInternal::definition(), casadi::FunctionInternal::eval(), casadi::Switch::eval(), casadi::Switch::eval_sx(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::init(), casadi::Switch::init(), casadi::ImplicitToNlp::init(), casadi::JitFunction::JitFunction(), casadi::FunctionInternal::mapsum_mx(), casadi::FunctionInternal::print_dimensions(), casadi::FunctionInternal::print_in(), casadi::FunctionInternal::serialize_body(), and casadi::HpmpcInterface::solve().
sparsity_out_
std::vector<Sparsity> casadi::FunctionInternal::sparsity_out_ inherited
Definition at line 1218 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::all_scalar(), casadi::Switch::codegen_body(), casadi::FunctionInternal::codegen_meta(), casadi::FunctionInternal::codegen_sparsities(), casadi::FunctionInternal::definition(), casadi::FunctionInternal::eval(), casadi::Switch::eval(), casadi::Switch::eval_sx(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::init(), casadi::Nlpsol::init(), casadi::Switch::init(), casadi::JitFunction::JitFunction(), casadi::FunctionInternal::print_dimensions(), casadi::FunctionInternal::print_out(), and casadi::FunctionInternal::serialize_body().
stats_
Dict casadi::FunctionInternal::stats_ inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_nn
Definition at line 1268 of file function_internal.hpp.
user_data_
void* casadi::FunctionInternal::user_data_ inherited
Definition at line 1290 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::generate_options(), and casadi::FunctionInternal::init().
verbose_
bool casadi::ProtoFunction::verbose_ inherited
Definition at line 237 of file function_internal.hpp.
Referenced by casadi::MXFunction::ad_forward(), casadi::MXFunction::ad_reverse(), casadi::ProtoFunction::change_option(), casadi::BSplineInterpolant::construct_graph(), casadi::OracleFunction::create_function(), casadi::FmuFunction::eval(), casadi::Integrator::eval(), casadi::MXFunction::eval(), casadi::MXFunction::eval_mx(), casadi::FmuFunction::factory(), casadi::FunctionInternal::finalize(), casadi::KinsolInterface::func(), casadi::ProtoFunction::generate_options(), casadi::Integrator::get_forward(), casadi::Integrator::get_forward_dae(), casadi::FunctionInternal::get_jac_sparsity_gen(), casadi::FunctionInternal::get_jac_sparsity_hierarchical(), casadi::FunctionInternal::get_jac_sparsity_hierarchical_symm(), casadi::FmuFunction::get_jacobian(), casadi::FunctionInternal::get_partition(), casadi::FmuFunction::get_reverse(), casadi::Integrator::get_reverse(), casadi::ProtoFunction::init(), casadi::FiniteDiff::init(), casadi::FmuFunction::init(), casadi::FunctionInternal::init(), casadi::MXFunction::init(), casadi::Blocksqp::init(), casadi::HpipmInterface::init(), casadi::HpmpcInterface::init(), casadi::IpoptInterface::init(), casadi::CvodesInterface::init(), casadi::IdasInterface::init(), casadi::Feasiblesqpmethod::init(), casadi::Scpgen::init(), casadi::Sqpmethod::init(), casadi::IpoptInterface::init_mem(), casadi::IdasInterface::init_mem(), casadi::BonminInterface::intermediate_callback(), casadi::OracleFunction::jit_dependencies(), casadi::CsparseInterface::nfact(), casadi::LapackLu::nfact(), casadi::LapackQr::nfact(), casadi::LinsolQr::nfact(), casadi::ProtoFunction::ProtoFunction(), casadi::CvodesInterface::reset(), casadi::IdasInterface::reset(), casadi::IdasInterface::resetB(), casadi::ProtoFunction::serialize_body(), casadi::CbcInterface::solve(), casadi::ClpInterface::solve(), casadi::CplexInterface::solve(), casadi::GurobiInterface::solve(), solve(), casadi::Ipqp::solve(), casadi::Qrqp::solve(), casadi::AmplInterface::solve(), casadi::SnoptInterface::solve(), casadi::KinsolInterface::solve(), casadi::WorhpInterface::solve(), casadi::Newton::solve(), casadi::Qrsqp::solve(), casadi::Scpgen::solve(), casadi::Sqpmethod::solve(), casadi::Sqpmethod::solve_ela_QP(), casadi::Feasiblesqpmethod::solve_LP(), casadi::Feasiblesqpmethod::solve_QP(), casadi::Qrsqp::solve_QP(), casadi::Sqpmethod::solve_QP(), casadi::Integrator::sp_forward(), and casadi::Integrator::sp_reverse().
The documentation for this class was generated from the following files:
qpoases_interface.hpp
qpoases_interface.cpp
qpoases_interface_meta.cpp