CasADi: casadi::Filesystem Class Reference
casadi::Filesystem Class Reference abstract
Filesystem interface.
#include <filesystem_impl.hpp>
Detailed Description
Talk to the filesystem without introducing a core dependency
Author
Joris Gillis
Date
2025
Extra doc: https://github.com/casadi/casadi/wiki/L_2d7
Definition at line 44 of file filesystem_impl.hpp.
Classes
struct Exposed
Public Types
typedef bool(* IsDirectory) (const std::string &path)
typedef bool(* CreateDirectories) (const std::string &path)
typedef bool(* Remove) (const std::string &path)
typedef casadi_int(* RemoveAll) (const std::string &path)
typedef std::string(* Filename) (const std::string &path)
typedef bool(* HasParentPath) (const std::string &path)
typedef std::string(* ParentPath) (const std::string &path)
typedef std::vector< std::string >(* IterateDirectoryNames) (const std::string &path)
typedef std::string(* Absolute) (const std::string &path)
typedef Filesystem *(* Creator) ()
typedef int(* RegFcn) (Plugin *plugin)
Public Member Functions
virtual const char * plugin_name () const=0
void serialize_type (SerializingStream &s) const
Serialize type information.
Static Public Member Functions
static void assert_enabled ()
static bool is_directory (const std::string &path)
static bool remove (const std::string &path)
static casadi_int remove_all (const std::string &path)
static std::string filename (const std::string &path)
static bool is_enabled ()
static bool has_parent_path (const std::string &path)
static std::string parent_path (const std::string &path)
static std::string absolute (const std::string &path)
static bool ensure_directory_exists (const std::string &path)
static bool create_directories (const std::string &path)
static std::vector< std::string > iterate_directory_names (const std::string &path)
static std::unique_ptr< std::ostream > ofstream_ptr (const std::string &path, std::ios_base::openmode mode=std::ios_base::out)
static std::unique_ptr< std::istream > ifstream_ptr (const std::string &path, std::ios_base::openmode mode=std::ios_base::in, bool fail=true)
static bool exists (const std::string &path)
static bool has_plugin (const std::string &pname, bool verbose=false)
Check if a plugin is available or can be loaded.
static const Options & plugin_options (const std::string &pname)
Get the plugin options.
static Deserialize plugin_deserialize (const std::string &pname)
Get the plugin deserialize_map.
static Plugin pluginFromRegFcn (RegFcn regfcn)
Instantiate a Plugin struct from a factory function.
static Plugin load_plugin (const std::string &pname, bool register_plugin=true, bool needs_lock=true)
Load a plugin dynamically.
static handle_t load_library (const std::string &libname, std::string &resultpath, bool global)
Load a library dynamically.
static void registerPlugin (const Plugin &plugin, bool needs_lock=true)
Register an integrator in the factory.
static void registerPlugin (RegFcn regfcn, bool needs_lock=true)
Register an integrator in the factory.
static Plugin & getPlugin (const std::string &pname)
Load and get the creator function.
static Filesystem * instantiate (const std::string &fname, const std::string &pname, Problem problem)
static ProtoFunction * deserialize (DeserializingStream &s)
Deserialize with type disambiguation.
Static Public Attributes
static const std::string meta_doc
static std::map< std::string, Plugin > solvers_
Collection of solvers.
static const std::string infix_ = "filesystem"
Infix.
Member Typedef Documentation
Absolute
typedef std::string(* casadi::Filesystem::Absolute) (const std::string &path)
Definition at line 55 of file filesystem_impl.hpp.
CreateDirectories
typedef bool(* casadi::Filesystem::CreateDirectories) (const std::string &path)
Definition at line 48 of file filesystem_impl.hpp.
Creator
typedef Filesystem*(* casadi::Filesystem::Creator) ()
Definition at line 58 of file filesystem_impl.hpp.
Filename
typedef std::string(* casadi::Filesystem::Filename) (const std::string &path)
Definition at line 51 of file filesystem_impl.hpp.
HasParentPath
typedef bool(* casadi::Filesystem::HasParentPath) (const std::string &path)
Definition at line 52 of file filesystem_impl.hpp.
IsDirectory
typedef bool(* casadi::Filesystem::IsDirectory) (const std::string &path)
Definition at line 47 of file filesystem_impl.hpp.
IterateDirectoryNames
typedef std::vector<std::string>(* casadi::Filesystem::IterateDirectoryNames) (const std::string &path)
Definition at line 54 of file filesystem_impl.hpp.
ParentPath
typedef std::string(* casadi::Filesystem::ParentPath) (const std::string &path)
Definition at line 53 of file filesystem_impl.hpp.
RegFcn
typedef int(* casadi::PluginInterface< Filesystem >::RegFcn) (Plugin *plugin) inherited
Definition at line 73 of file plugin_interface.hpp.
Remove
typedef bool(* casadi::Filesystem::Remove) (const std::string &path)
Definition at line 49 of file filesystem_impl.hpp.
RemoveAll
typedef casadi_int(* casadi::Filesystem::RemoveAll) (const std::string &path)
Definition at line 50 of file filesystem_impl.hpp.
Member Function Documentation
absolute()
std::string casadi::Filesystem::absolute (const std::string & path) static
Definition at line 78 of file filesystem.cpp.
{
   assert_enabled();
   return Filesystem::getPlugin("ghc").exposed.absolute(path);
 }
References assert_enabled(), casadi::PluginInterface< Filesystem >::getPlugin(), and casadi::path().
Referenced by casadi::FmuInternal::finalize(), casadi::ZipResource::unpack(), and casadi::ZipMemResource::unpack().
assert_enabled()
void casadi::Filesystem::assert_enabled () static
Definition at line 87 of file filesystem.cpp.
{
   casadi_assert(Filesystem::is_enabled(),
   "This action requires advanced filesystem access. Compile CasADi with WITH_GHC_FILESYSTEM=ON.");
 }
References is_enabled().
Referenced by absolute(), create_directories(), casadi::extract_zip_internal(), filename(), has_parent_path(), is_directory(), iterate_directory_names(), parent_path(), remove(), and remove_all().
create_directories()
bool casadi::Filesystem::create_directories (const std::string & path) static
Definition at line 63 of file filesystem.cpp.
{
   assert_enabled();
   return Filesystem::getPlugin("ghc").exposed.create_directories(path);
 }
References assert_enabled(), casadi::PluginInterface< Filesystem >::getPlugin(), and casadi::path().
Referenced by ensure_directory_exists().
deserialize()
static ProtoFunction* casadi::PluginInterface< Filesystem >::deserialize (DeserializingStream & s) inline static inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_rr
Definition at line 121 of file plugin_interface.hpp.
{
       std::string class_name, plugin_name;
       s.unpack("PluginInterface::plugin_name", plugin_name);
       Deserialize deserialize = plugin_deserialize(plugin_name);
       return deserialize(s);
     }
ensure_directory_exists()
bool casadi::Filesystem::ensure_directory_exists (const std::string & path) static
Definition at line 105 of file filesystem.cpp.
{
   if (has_parent_path(filename)) {
     std::string dir = parent_path(filename);
     if (!is_directory(dir)) {
       return create_directories(dir);
     }
   }
   return true;
 }
References create_directories(), filename(), has_parent_path(), is_directory(), and parent_path().
Referenced by ofstream_ptr().
exists()
bool casadi::Filesystem::exists (const std::string & path) static
Definition at line 144 of file filesystem.cpp.
{
   auto ret = ifstream_compat(path);
   return static_cast<bool>(ret);
 }
References casadi::ifstream_compat(), and casadi::path().
Referenced by casadi::DaeBuilderInternal::load_fmi_description().
filename()
std::string casadi::Filesystem::filename (const std::string & path) static
Definition at line 73 of file filesystem.cpp.
{
   assert_enabled();
   return Filesystem::getPlugin("ghc").exposed.filename(path);
 }
References assert_enabled(), casadi::PluginInterface< Filesystem >::getPlugin(), and casadi::path().
Referenced by ensure_directory_exists(), and casadi::ZipResource::unpack().
getPlugin()
PluginInterface< Filesystem >::Plugin & casadi::PluginInterface< Filesystem >::getPlugin (const std::string & pname) static inherited
Definition at line 102 of file plugin_interface.hpp.
{
 #ifdef CASADI_WITH_THREADSAFE_SYMBOLICS
     std::lock_guard<std::mutex> lock(Derived::mutex_solvers_);
 #endif // CASADI_WITH_THREADSAFE_SYMBOLICS
     // Check if the solver has been loaded
     auto it=Derived::solvers_.find(pname);
     // Load the solver if needed
     if (it==Derived::solvers_.end()) {
       load_plugin(pname, true, false);
       it=Derived::solvers_.find(pname);
     }
     casadi_assert_dev(it!=Derived::solvers_.end());
     return it->second;
   }
has_parent_path()
bool casadi::Filesystem::has_parent_path (const std::string & path) static
Definition at line 53 of file filesystem.cpp.
{
   assert_enabled();
   return Filesystem::getPlugin("ghc").exposed.has_parent_path(path);
 }
References assert_enabled(), casadi::PluginInterface< Filesystem >::getPlugin(), and casadi::path().
Referenced by ensure_directory_exists(), and casadi::DllLibrary::init_handle().
has_plugin()
bool casadi::PluginInterface< Filesystem >::has_plugin (const std::string & pname, bool verbose = false) static inherited
Definition at line 76 of file plugin_interface.hpp.
{
 #ifdef CASADI_WITH_THREADSAFE_SYMBOLICS
     std::lock_guard<std::mutex> lock(Derived::mutex_solvers_);
 #endif // CASADI_WITH_THREADSAFE_SYMBOLICS
     // Quick return if available
     if (Derived::solvers_.find(pname) != Derived::solvers_.end()) {
       return true;
     }
     // Try loading the plugin
     try {
       (void)load_plugin(pname, false, false);
       return true;
     } catch (CasadiException& ex) {
       if (verbose) {
         casadi_warning(ex.what());
       }
       return false;
     }
   }
ifstream_ptr()
std::unique_ptr< std::istream > casadi::Filesystem::ifstream_ptr (const std::string & path, std::ios_base::openmode mode = std::ios_base::in, bool fail = true) static
Definition at line 135 of file filesystem.cpp.
{
   auto ret = ifstream_compat(path, mode);
   if (fail && !ret) {
     casadi_error("Could not open '" + path + "'.");
   }
   return ret;
 }
References casadi::ifstream_compat(), and casadi::path().
Referenced by casadi::add_file_to_zip(), casadi::Sparsity::from_file(), casadi::FunctionInternal::FunctionInternal(), casadi::ClangCompiler::getIncludes(), casadi::ImporterInternal::init(), casadi::NlImporter::NlImporter(), casadi::FunctionInternal::serialize_body(), casadi::ZipResource::serialize_body(), and casadi::AmplInterface::solve().
instantiate()
Filesystem * casadi::PluginInterface< Filesystem >::instantiate (const std::string & fname, const std::string & pname, Problem problem) static inherited
Definition at line 106 of file plugin_interface.hpp.
{
     // Assert the plugin exists (needed for adaptors)
     if (!has_plugin(pname, true)) {
       casadi_error("Plugin '" + pname + "' is not found.");
     }
     return getPlugin(pname).creator(fname, problem);
   }
is_directory()
bool casadi::Filesystem::is_directory (const std::string & path) static
Definition at line 38 of file filesystem.cpp.
{
   assert_enabled();
   return Filesystem::getPlugin("ghc").exposed.is_directory(path);
 }
References assert_enabled(), casadi::PluginInterface< Filesystem >::getPlugin(), and casadi::path().
Referenced by ensure_directory_exists(), and casadi::Resource::Resource().
is_enabled()
bool casadi::Filesystem::is_enabled () static
Definition at line 83 of file filesystem.cpp.
{
   return Filesystem::has_plugin("ghc");
 }
References casadi::PluginInterface< Filesystem >::has_plugin().
Referenced by assert_enabled(), casadi::FmuInternal::finalize(), casadi::DllLibrary::init_handle(), casadi::DaeBuilderInternal::load_fmi_description(), ofstream_ptr(), casadi::Resource::Resource(), and casadi::ZipResource::unpack().
iterate_directory_names()
std::vector< std::string > casadi::Filesystem::iterate_directory_names (const std::string & path) static
Definition at line 68 of file filesystem.cpp.
{
   assert_enabled();
   return Filesystem::getPlugin("ghc").exposed.iterate_directory_names(path);
 }
References assert_enabled(), casadi::PluginInterface< Filesystem >::getPlugin(), and casadi::path().
load_library()
handle_t casadi::PluginInterface< Filesystem >::load_library (const std::string & libname, std::string & resultpath, bool global) static inherited
Definition at line 92 of file plugin_interface.hpp.
{
 #ifndef WITH_DL
     casadi_error("WITH_DL option needed for dynamic loading");
 #else // WITH_DL
     // Get the name of the shared library
     std::string lib = SHARED_LIBRARY_PREFIX + libname + SHARED_LIBRARY_SUFFIX;
     // Build up search paths;
     std::vector<std::string> search_paths = get_search_paths();
     return open_shared_library(lib, search_paths, resultpath,
       "PluginInterface::load_plugin", global);
 #endif // WITH_DL
   }
load_plugin()
PluginInterface< Filesystem >::Plugin casadi::PluginInterface< Filesystem >::load_plugin (const std::string & pname, bool register_plugin = true, bool needs_lock = true) static inherited
Definition at line 88 of file plugin_interface.hpp.
{
 #ifdef CASADI_WITH_THREADSAFE_SYMBOLICS
     casadi::conditional_lock_guard<std::mutex> lock(Derived::mutex_solvers_, needs_lock);
 #endif // CASADI_WITH_THREADSAFE_SYMBOLICS
     // Issue warning and quick return if already loaded
     if (Derived::solvers_.find(pname) != Derived::solvers_.end()) {
       casadi_warning("PluginInterface: Solver " + pname + " is already in use. Ignored.");
       return Plugin();
     }
     // Logger singletons are lazily instantiated on first uout()/uerr() calls
     // This instantation may lead to a data race with potential instatiations in plugin
     // To be safe, trigger instantatin before any plugin loading
     uout();
     uerr();
 #ifndef WITH_DL
     casadi_error("WITH_DL option needed for dynamic loading");
 #else // WITH_DL
     // Retrieve the registration function
     RegFcn reg;
     // Load the dll
     std::string regName = "casadi_register_" + Derived::infix_ + "_" + pname;
     std::string searchpath;
     handle_t handle = load_library("casadi_" + Derived::infix_ + "_" + pname, searchpath,
       false);
 #ifdef _WIN32
 #if __GNUC__
 #pragma GCC diagnostic push
 #pragma GCC diagnostic ignored "-Wcast-function-type"
 #endif
     reg = reinterpret_cast<RegFcn>(GetProcAddress(handle, TEXT(regName.c_str())));
 #if __GNUC__
 #pragma GCC diagnostic pop
 #endif
 #else // _WIN32
     // Reset error
     dlerror();
     // Load creator
     reg = reinterpret_cast<RegFcn>(dlsym(handle, regName.c_str()));
 #endif // _WIN32
     casadi_assert(reg!=nullptr,
       "PluginInterface::load_plugin: no \"" + regName + "\" found in " + searchpath + ".");
     // Create a temporary struct
     Plugin plugin = pluginFromRegFcn(reg);
     // Register the plugin
     if (register_plugin) {
       registerPlugin(plugin, false);
     }
     return plugin;
 #endif // WITH_DL
   }
ofstream_ptr()
std::unique_ptr< std::ostream > casadi::Filesystem::ofstream_ptr (const std::string & path, std::ios_base::openmode mode = std::ios_base::out) static
Definition at line 115 of file filesystem.cpp.
{
   if (is_enabled()) {
     casadi_assert(ensure_directory_exists(path),
      "Unable to create the required directory for '" + path + "'.");
   }
   auto stream_ptr = ofstream_compat(path, mode);
   if (is_enabled()) {
     casadi_assert(stream_ptr,
       "Error opening stream '" + path + "'.");
   } else {
     casadi_assert(stream_ptr,
       "Error opening stream '" + path + "'. "
       "Does the directory exits? "
       "Note that CasADi needs to be compiled with WITH_GHC_FILESYSTEM=ON "
       "for directories to be automatically created");
   }
   return stream_ptr;
 }
References ensure_directory_exists(), is_enabled(), casadi::ofstream_compat(), and casadi::path().
Referenced by casadi::conic_debug(), casadi::FmuInternal::eval_fd(), casadi::Function::export_code(), casadi::extract_zip_internal(), casadi::FunctionInternal::FunctionInternal(), casadi::CodeGenerator::generate(), casadi::FunctionInternal::generate_in(), casadi::Function::generate_in(), casadi::Function::generate_out(), casadi::FunctionInternal::generate_out(), casadi::DaeBuilderInternal::generate_wrapper(), casadi::FmuFunction::init(), casadi::Linsol::nfact(), casadi::AmplInterface::solve(), casadi::SparsityInternal::spy_matlab(), casadi::Sparsity::to_file(), and casadi::zip_to_path().
parent_path()
std::string casadi::Filesystem::parent_path (const std::string & path) static
Definition at line 58 of file filesystem.cpp.
{
   assert_enabled();
   return Filesystem::getPlugin("ghc").exposed.parent_path(path);
 }
References assert_enabled(), casadi::PluginInterface< Filesystem >::getPlugin(), and casadi::path().
Referenced by ensure_directory_exists(), and casadi::DllLibrary::init_handle().
plugin_deserialize()
Deserialize casadi::PluginInterface< Filesystem >::plugin_deserialize (const std::string & pname) static inherited
Definition at line 82 of file plugin_interface.hpp.
{
     Deserialize m = getPlugin(pname).deserialize;
     casadi_assert(m, "Plugin \"" + pname + "\" does not support deserialize");
     return m;
   }
plugin_name()
virtual const char* casadi::PluginInterface< Filesystem >::plugin_name () const pure virtual inherited
plugin_options()
const Options & casadi::PluginInterface< Filesystem >::plugin_options (const std::string & pname) static inherited
Definition at line 79 of file plugin_interface.hpp.
{
     const Options *op = getPlugin(pname).options;
     casadi_assert(op!=nullptr, "Plugin \"" + pname + "\" does not support options");
     return *op;
   }
pluginFromRegFcn()
PluginInterface< Filesystem >::Plugin casadi::PluginInterface< Filesystem >::pluginFromRegFcn (RegFcn regfcn) static inherited
Definition at line 85 of file plugin_interface.hpp.
{
     // Create a temporary struct
     Plugin plugin;
     // Set the fields
     int flag = regfcn(&plugin);
     casadi_assert(flag==0, "Registration of plugin failed.");
     return plugin;
   }
registerPlugin() [1/2]
void casadi::PluginInterface< Filesystem >::registerPlugin (const Plugin & plugin, bool needs_lock = true) static inherited
Definition at line 96 of file plugin_interface.hpp.
{
 #ifdef CASADI_WITH_THREADSAFE_SYMBOLICS
     casadi::conditional_lock_guard<std::mutex> lock(Derived::mutex_solvers_, needs_lock);
 #endif // CASADI_WITH_THREADSAFE_SYMBOLICS
     // Check if the solver name is in use
     typename std::map<std::string, Plugin>::iterator it=Derived::solvers_.find(plugin.name);
     casadi_assert(it==Derived::solvers_.end(),
       "Solver " + str(plugin.name) + " is already in use");
     // Add to list of solvers
     Derived::solvers_[plugin.name] = plugin;
   }
registerPlugin() [2/2]
void casadi::PluginInterface< Filesystem >::registerPlugin (RegFcn regfcn, bool needs_lock = true) static inherited
Definition at line 99 of file plugin_interface.hpp.
{
     registerPlugin(pluginFromRegFcn(regfcn), needs_lock);
   }
remove()
bool casadi::Filesystem::remove (const std::string & path) static
Definition at line 43 of file filesystem.cpp.
{
   assert_enabled();
   return Filesystem::getPlugin("ghc").exposed.remove(path);
 }
References assert_enabled(), casadi::PluginInterface< Filesystem >::getPlugin(), and casadi::path().
Referenced by casadi::ZipMemResource::~ZipMemResource(), and casadi::ZipResource::~ZipResource().
remove_all()
casadi_int casadi::Filesystem::remove_all (const std::string & path) static
Definition at line 48 of file filesystem.cpp.
{
   assert_enabled();
   return Filesystem::getPlugin("ghc").exposed.remove_all(path);
 }
References assert_enabled(), casadi::PluginInterface< Filesystem >::getPlugin(), and casadi::path().
Referenced by casadi::ZipMemResource::~ZipMemResource(), and casadi::ZipResource::~ZipResource().
serialize_type()
void casadi::PluginInterface< Filesystem >::serialize_type (SerializingStream & s) const inline inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_rq
Definition at line 114 of file plugin_interface.hpp.
{
       s.pack("PluginInterface::plugin_name", std::string(plugin_name()));
     }
Member Data Documentation
infix_
const std::string casadi::Filesystem::infix_ = "filesystem" static
Definition at line 104 of file filesystem_impl.hpp.
meta_doc
const std::string casadi::Filesystem::meta_doc static
Definition at line 60 of file filesystem_impl.hpp.
solvers_
std::map< std::string, Filesystem::Plugin > casadi::Filesystem::solvers_ static
Definition at line 76 of file filesystem_impl.hpp.
The documentation for this class was generated from the following files:
filesystem_impl.hpp
filesystem.cpp