CasADi: casadi::RuntimeConst< T > Struct Template Reference
casadi::RuntimeConst< T > Struct Template Reference
Constant known at runtime.
#include <constant_mx.hpp>
Detailed Description
template<typename T>
struct casadi::RuntimeConst< T >
Extra doc: https://github.com/casadi/casadi/wiki/L_106
Definition at line 545 of file constant_mx.hpp.
Public Member Functions
RuntimeConst ()
RuntimeConst (T v)
void serialize_type (SerializingStream &s) const
char type_char ()
char type_char ()
Static Public Member Functions
static char type_char ()
static RuntimeConst deserialize (DeserializingStream &s)
Public Attributes
const T value
Constructor & Destructor Documentation
RuntimeConst() [1/2]
template<typename T > casadi::RuntimeConst< T >::RuntimeConst () inline
Definition at line 547 of file constant_mx.hpp.
 {}
Referenced by casadi::RuntimeConst< T >::deserialize().
RuntimeConst() [2/2]
template<typename T > casadi::RuntimeConst< T >::RuntimeConst (T v) inline
Definition at line 548 of file constant_mx.hpp.
 : value(v) {}
Member Function Documentation
deserialize()
template<typename T > static RuntimeConst casadi::RuntimeConst< T >::deserialize (DeserializingStream & s) inline static
Definition at line 553 of file constant_mx.hpp.
{
       T v;
       s.unpack("Constant::value", v);
       return RuntimeConst(v);
     }
References casadi::RuntimeConst< T >::RuntimeConst(), casadi::T, and casadi::DeserializingStream::unpack().
Referenced by casadi::ConstantMX::deserialize().
serialize_type()
template<typename T > void casadi::RuntimeConst< T >::serialize_type (SerializingStream & s) const inline
Definition at line 550 of file constant_mx.hpp.
{
       s.pack("Constant::value", value);
     }
References casadi::SerializingStream::pack(), and casadi::RuntimeConst< T >::value.
type_char() [1/3]
template<typename T > char casadi::RuntimeConst< T >::type_char inline static
Definition at line 561 of file constant_mx.hpp.
 { return 'u'; }
type_char() [2/3]
char casadi::RuntimeConst< casadi_int >::type_char () inline
Definition at line 564 of file constant_mx.hpp.
 { return 'I'; }
type_char() [3/3]
char casadi::RuntimeConst< double >::type_char () inline
Definition at line 567 of file constant_mx.hpp.
 { return 'D'; }
Member Data Documentation
value
template<typename T > const T casadi::RuntimeConst< T >::value
Definition at line 546 of file constant_mx.hpp.
Referenced by casadi::RuntimeConst< T >::serialize_type().
The documentation for this struct was generated from the following file:
constant_mx.hpp