CasADi: casadi::XmlFile Class Reference
casadi::XmlFile Class Reference
XML parser.
#include <xml_file.hpp>
Detailed Description
Can be used for parsing XML files into CasADi data structures.
Author
Joel Andersson
Date
2014
Extra doc: https://github.com/casadi/casadi/wiki/L_7k
Definition at line 47 of file xml_file.hpp.
Public Member Functions
XmlFile ()
XmlFile (const std::string &name)
~XmlFile ()
XmlFileInternal * operator-> ()
Access functions of the node.
const XmlFileInternal * operator-> () const
Const access functions of the node.
XmlNode parse (const std::string &filename)
void dump (const std::string &filename, const XmlNode &node)
void own (SharedObjectInternal *node)
void assign (SharedObjectInternal *node)
Assign the node to a node class pointer without reference counting.
SharedObjectInternal * get () const
Get a const pointer to the node.
casadi_int getCount () const
Get the reference count.
void swap (SharedObject &other)
Swap content with another instance.
std::string class_name () const
Get class name.
void disp (std::ostream &stream, bool more=false) const
Print a description of the object.
std::string get_str (bool more=false) const
Get string representation.
void print_ptr (std::ostream &stream=casadi::uout()) const
bool is_null () const
Is a null pointer?
casadi_int __hash__ () const
Returns a number that is unique for a given Node.
WeakRef * weak ()
Get a weak reference to the object.
Static Public Member Functions
static std::string type_name ()
Get type name.
static void load_plugin (const std::string &name)
Load a plugin dynamically.
static std::string doc (const std::string &name)
Get solver specific documentation.
Protected Member Functions
void count_up ()
void count_down ()
Constructor & Destructor Documentation
XmlFile() [1/2]
casadi::XmlFile::XmlFile ()
Definition at line 30 of file xml_file.cpp.
                  {
 }
XmlFile() [2/2]
casadi::XmlFile::XmlFile (const std::string & name)
Definition at line 33 of file xml_file.cpp.
{
   own(XmlFileInternal::getPlugin(name).creator());
 }
References casadi::PluginInterface< XmlFileInternal >::getPlugin(), and casadi::SharedObject::own().
~XmlFile()
casadi::XmlFile::~XmlFile ()
Definition at line 37 of file xml_file.cpp.
                   {
 }
Member Function Documentation
__hash__()
casadi_int casadi::SharedObject::__hash__ () const inherited
If the Object does not point to any node, "0" is returned.
Extra doc: https://github.com/casadi/casadi/wiki/L_av
Definition at line 129 of file shared_object.cpp.
{
     return reinterpret_cast<casadi_int>(get());
   }
References casadi::SharedObject::get().
assign()
void casadi::SharedObject::assign (SharedObjectInternal * node) inherited
improper use will cause memory leaks!
Extra doc: https://github.com/casadi/casadi/wiki/L_at
Definition at line 52 of file shared_object.cpp.
{
     node = node_;
   }
Referenced by casadi::GenericType::to_double_vector_vector().
class_name()
std::string casadi::SharedObject::class_name () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_au
Definition at line 99 of file shared_object.cpp.
{
     return (*this)->class_name();
   }
Referenced by casadi::MXFunction::export_code_body().
count_down()
void casadi::SharedObject::count_down () protected inherited
Definition at line 84 of file shared_object.cpp.
{
 #ifdef WITH_EXTRA_CHECKS
     casadi_assert_dev(Function::call_depth_==0);
 #endif // WITH_EXTRA_CHECKS
     if (node && --node->count == 0) {
       delete node;
       node = nullptr;
     }
   }
Referenced by casadi::SharedObject::operator=(), casadi::SharedObject::own(), and casadi::SharedObject::~SharedObject().
count_up()
void casadi::SharedObject::count_up () protected inherited
Definition at line 77 of file shared_object.cpp.
{
 #ifdef WITH_EXTRA_CHECKS
     casadi_assert_dev(Function::call_depth_==0);
 #endif // WITH_EXTRA_CHECKS
     if (node) node->count++;
   }
Referenced by casadi::SharedObject::operator=(), casadi::SharedObject::own(), and casadi::SharedObject::SharedObject().
disp()
void casadi::SharedObject::disp (std::ostream & stream, bool more = false) const inherited
Definition at line 103 of file shared_object.cpp.
{
     if (is_null()) {
       stream << "NULL";
     } else {
       (*this)->disp(stream, more);
     }
   }
References casadi::SharedObject::is_null().
Referenced by casadi::Nlpsol::disp_more(), and casadi::CsparseInterface::nfact().
doc()
std::string casadi::XmlFile::doc (const std::string & name) static
Definition at line 60 of file xml_file.cpp.
{
   return XmlFileInternal::getPlugin(name).doc;
 }
References casadi::PluginInterface< XmlFileInternal >::getPlugin().
dump()
void casadi::XmlFile::dump (const std::string & filename, const XmlNode & node)
Definition at line 52 of file xml_file.cpp.
{
   return (*this)->dump(filename, node);
 }
Referenced by casadi::DaeBuilderInternal::generate_build_description(), and casadi::DaeBuilderInternal::generate_model_description().
get()
SharedObjectInternal * casadi::SharedObject::get () const inherited
Definition at line 69 of file shared_object.cpp.
{
     return node;
   }
Referenced by casadi::SharedObject::__hash__(), casadi::GenericType::as_bool(), casadi::GenericType::as_bool_vector(), casadi::GenericType::as_dict(), casadi::GenericType::as_double(), casadi::GenericType::as_double_vector(), casadi::GenericType::as_double_vector_vector(), casadi::GenericType::as_function(), casadi::GenericType::as_function_vector(), casadi::GenericType::as_int(), casadi::GenericType::as_int_vector(), casadi::GenericType::as_int_vector_vector(), casadi::GenericType::as_string(), casadi::GenericType::as_string_vector(), casadi::GenericType::as_void_pointer(), casadi::Fmu::get(), casadi::Function::get(), casadi::MX::get(), casadi::Sparsity::get(), casadi::DaeBuilder::get(), casadi::GenericType::getType(), and casadi::GenericType::serialize().
get_str()
std::string casadi::SharedObject::get_str (bool more = false) const inline inherited
Definition at line 138 of file shared_object.hpp.
{
       std::stringstream ss;
       disp(ss, more);
       return ss.str();
     }
getCount()
casadi_int casadi::SharedObject::getCount () const inherited
Definition at line 121 of file shared_object.cpp.
{
     return (*this)->getCount();
   }
Referenced by casadi::MXNode::~MXNode().
is_null()
bool casadi::SharedObject::is_null () const inherited
Definition at line 73 of file shared_object.cpp.
{
     return node==nullptr;
   }
Referenced by casadi::FunctionInternal::add_embedded(), casadi::WeakRef::alive(), casadi::FunctionInternal::alloc(), casadi::Nlpsol::callback(), casadi::DaeBuilderInternal::clear_cache(), casadi::Switch::codegen_body(), casadi::Conic::Conic(), casadi::conic_debug(), casadi::Callback::construct(), casadi::Function::deserialize(), casadi::SharedObject::disp(), casadi::FunctionInternal::finalize(), casadi::Switch::find(), casadi::FunctionInternal::FunctionInternal(), casadi::FunctionInternal::get_n_in(), casadi::Switch::get_n_in(), casadi::FunctionInternal::get_n_out(), casadi::Switch::get_n_out(), casadi::FunctionInternal::get_name_in(), casadi::FunctionInternal::get_name_out(), casadi::FunctionInternal::get_partition(), casadi::FunctionInternal::get_sparsity_in(), casadi::Switch::get_sparsity_in(), casadi::FunctionInternal::get_sparsity_out(), casadi::Switch::get_sparsity_out(), casadi::MXFunction::get_stats(), casadi::GenericType::getType(), casadi::Sparsity::info(), casadi::Nlpsol::init(), casadi::Rootfinder::init(), casadi::Switch::init(), casadi::SLEQPInterface::init(), casadi::SnoptInterface::init(), casadi::SundialsInterface::init(), casadi::FastNewton::init(), casadi::Newton::init(), casadi::Scpgen::init(), casadi::BonminInterface::intermediate_callback(), casadi::IpoptInterface::intermediate_callback(), casadi::XFunction< DerivedType, MatType, NodeType >::jac(), casadi::FunctionInternal::jac_is_symm(), casadi::FunctionInternal::jac_sparsity(), casadi::OracleFunction::jit_dependencies(), casadi::SparsityInternal::maxtrans(), casadi::Fmu::name(), casadi::Function::name(), casadi::Function::operator->(), casadi::SharedObject::operator->(), casadi::Function::operator==(), casadi::DaeBuilderInternal::oracle(), casadi::Function::serialize(), casadi::Sparsity::serialize(), casadi::SLEQPInterface::set_work(), casadi::SnoptInterface::set_work(), casadi::OptiNode::solve(), casadi::KnitroInterface::solve(), casadi::SLEQPInterface::solve(), casadi::WorhpInterface::solve(), casadi::FunctionInternal::sp_forward_block(), casadi::FunctionInternal::sp_reverse(), casadi::Sparsity::uni_coloring(), and casadi::Callback::~Callback().
load_plugin()
void casadi::XmlFile::load_plugin (const std::string & name) static
Definition at line 56 of file xml_file.cpp.
{
   XmlFileInternal::load_plugin(name);
 }
References casadi::PluginInterface< XmlFileInternal >::load_plugin().
operator->() [1/2]
XmlFileInternal * casadi::XmlFile::operator-> ()
Extra doc: https://github.com/casadi/casadi/wiki/L_7m
Definition at line 44 of file xml_file.cpp.
{
   return static_cast<XmlFileInternal*>(SharedObject::operator->());
 }
References casadi::SharedObject::operator->().
operator->() [2/2]
const XmlFileInternal * casadi::XmlFile::operator-> () const
Extra doc: https://github.com/casadi/casadi/wiki/L_7n
Definition at line 40 of file xml_file.cpp.
{
   return static_cast<const XmlFileInternal*>(SharedObject::operator->());
 }
References casadi::SharedObject::operator->().
own()
void casadi::SharedObject::own (SharedObjectInternal * node) inherited
Assign the node to a node class pointer (or null)
Definition at line 46 of file shared_object.cpp.
{
     count_down();
     node = node_;
     count_up();
   }
References casadi::SharedObject::count_down(), and casadi::SharedObject::count_up().
Referenced by casadi::Callback::construct(), casadi::Function::construct(), casadi::Fmu::create(), casadi::Function::create(), casadi::Importer::create(), casadi::Linsol::create(), casadi::GenericType::create(), casadi::Sparsity::create(), casadi::DaeBuilder::DaeBuilder(), casadi::FunctionInternal::deserialize(), casadi::Linsol::deserialize(), casadi::FmuFunction::factory(), casadi::Fmu::Fmu(), casadi::GenericType::GenericType(), casadi::FmuFunction::get_forward(), casadi::FmuFunction::get_jacobian(), casadi::LinearInterpolant::get_jacobian(), casadi::FmuFunction::get_reverse(), casadi::Importer::Importer(), casadi::MXFunction::init(), casadi::Linsol::Linsol(), casadi::MX::MX(), casadi::Opti::Opti(), casadi::WeakRef::shared(), casadi::WeakRef::WeakRef(), and XmlFile().
parse()
XmlNode casadi::XmlFile::parse (const std::string & filename)
Definition at line 48 of file xml_file.cpp.
{
   return (*this)->parse(filename);
 }
Referenced by casadi::DaeBuilderInternal::load_fmi_description().
print_ptr()
void casadi::SharedObject::print_ptr (std::ostream & stream = casadi::uout()) const inherited
Print the pointer to the internal class
Definition at line 111 of file shared_object.cpp.
{
     stream << node;
   }
swap()
void casadi::SharedObject::swap (SharedObject & other) inherited
Definition at line 115 of file shared_object.cpp.
{
     SharedObject temp = *this;
     *this = other;
     other = temp;
   }
type_name()
static std::string casadi::XmlFile::type_name () inline static
Extra doc: https://github.com/casadi/casadi/wiki/L_7l
Definition at line 54 of file xml_file.hpp.
 {return "XmlFile";}
weak()
WeakRef * casadi::SharedObject::weak () inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_aw
Definition at line 125 of file shared_object.cpp.
{
     return (*this)->weak();
   }
References casadi::SharedObjectInternal::weak().
Referenced by casadi::WeakRef::WeakRef().
The documentation for this class was generated from the following files:
xml_file.hpp
xml_file.cpp