CasADi: casadi::OoqpMemory Struct Reference
casadi::OoqpMemory Struct Reference
#include <ooqp_interface.hpp>
Detailed Description
Definition at line 47 of file ooqp_interface.hpp.
Public Member Functions
void add_stat (const std::string &s)
Public Attributes
int return_status
casadi_qp_data< double > d_qp
std::map< std::string, FStats > fstats
FStats * t_total
Member Function Documentation
add_stat()
void casadi::ProtoFunctionMemory::add_stat (const std::string & s) inline inherited
Definition at line 74 of file function_internal.hpp.
{
       bool added = fstats.insert(std::make_pair(s, FStats())).second;
       casadi_assert(added, "Duplicate stat: '" + s + "'");
     }
Referenced by casadi::ProtoFunction::init_mem(), casadi::LinsolInternal::init_mem(), casadi::Nlpsol::init_mem(), casadi::OracleFunction::init_mem(), casadi::CbcInterface::init_mem(), casadi::ClpInterface::init_mem(), casadi::FatropConicInterface::init_mem(), casadi::HpipmInterface::init_mem(), casadi::Feasiblesqpmethod::init_mem(), casadi::Sqpmethod::init_mem(), and casadi::OracleFunction::local_init_mem().
Member Data Documentation
d_qp
casadi_qp_data<double> casadi::ConicMemory::d_qp inherited
Definition at line 39 of file conic_impl.hpp.
Referenced by casadi::Conic::get_stats().
fstats
std::map<std::string, FStats> casadi::ProtoFunctionMemory::fstats inherited
Definition at line 68 of file function_internal.hpp.
Referenced by casadi::Nlpsol::callback(), casadi::IpoptUserClass::eval_h(), casadi::BonminInterface::intermediate_callback(), casadi::IpoptInterface::intermediate_callback(), casadi::OracleFunction::join_results(), casadi::DaqpInterface::solve(), casadi::HighsInterface::solve(), casadi::HpipmInterface::solve(), casadi::HpmpcInterface::solve(), casadi::ProxqpInterface::solve(), casadi::QpoasesInterface::solve(), casadi::Sqpmethod::solve_ela_QP(), casadi::Feasiblesqpmethod::solve_LP(), casadi::Feasiblesqpmethod::solve_QP(), and casadi::Sqpmethod::solve_QP().
return_status
int casadi::OoqpMemory::return_status
Definition at line 48 of file ooqp_interface.hpp.
Referenced by casadi::OoqpInterface::get_stats(), and casadi::OoqpInterface::solve().
t_total
FStats* casadi::ProtoFunctionMemory::t_total inherited
Definition at line 71 of file function_internal.hpp.
Referenced by casadi::LinsolCall< Tr >::eval(), and casadi::Linsol::solve().
The documentation for this struct was generated from the following file:
ooqp_interface.hpp