CasADi: casadi::DaeBuilder Class Reference
casadi::DaeBuilder Class Reference
A symbolic representation of a differential-algebraic equations model.
#include <dae_builder.hpp>
Detailed Description
Variables:
t:      independent variable (usually time)
c:      constants
p:      parameters
d:      dependent parameters (time independent)
u:      controls
w:      dependent variables  (time dependent)
x:      differential states
z:      algebraic variables
q:      quadrature states
y:      outputs
Equations:
differential equations: \dot{x} ==  ode(...)
algebraic equations:          0 ==  alg(...)
quadrature equations:   \dot{q} == quad(...)
dependent parameters:         d == ddef(d_prev,p)
dependent variables:          w == wdef(w_prev,x,z,u,p,t)
output equations:             y == ydef(...)
initial equations:     init_lhs == init_rhs(...)
events:      when when_cond < 0: when_lhs := when_rhs
Date
2012-2021
Author
Joel Andersson
Extra doc: https://github.com/casadi/casadi/wiki/L_5c
Definition at line 68 of file dae_builder.hpp.
Public Types
using internal_base_type = SharedObjectInternal
using base_type = SharedObject
Public Member Functions
std::string type_name () const
Readable name of the class.
DaeBuilder ()
Default constructor.
DaeBuilder (const std::string &name, const std::string &path="", const Dict &opts=Dict())
Construct a DaeBuilder instance.
const std::string & name () const
Name of instance.
void reorder (const std::string &cat, const std::vector< std::string > &v)
Reorder variables in a category.
void clear_all (const std::string &v)
[DEPRECATED] Use set_variability, set_causality or set_category to change variable category
void set_all (const std::string &v, const std::vector< std::string > &name)
[DEPRECATED] Use set_variability, set_causality, set_category and/or reorder
void eliminate_d ()
[DEPRECATED] Use eliminate("d")
void eliminate_w ()
[DEPRECATED] Use eliminate("w")
void eliminate_quad ()
[DEPRECATED] Use eliminate("q")
void sort_d ()
[DEPRECATED] Use sort("d")
void sort_w ()
[DEPRECATED] Use sort("w")
void sort_z (const std::vector< std::string > &z_order)
[DEPRECATED] Use reorder("z", new_order)
Function create (const std::string &fname, const Dict &opts=Dict()) const
Create a function with standard integrator DAE signature.
Function create () const
Create a function with standard integrator DAE signature, default naming.
Function dependent_fun (const std::string &fname, const std::vector< std::string > &s_in, const std::vector< std::string > &s_out) const
Construct a function for evaluating dependent parameters.
Function transition (const std::string &fname, casadi_int index) const
Construct a function describing transition at a specific events.
Function transition (const std::string &fname) const
Construct a function describing transition at any events.
Function transition () const
Construct an event transition function, default naming.
std::vector< std::string > der (const std::vector< std::string > &name) const
Get the time derivative of model variables.
std::vector< std::string > pre (const std::vector< std::string > &name) const
Get the pre-variables of model variables.
MX pre (const MX &v) const
Get the pre-expression given variable expression.
bool has_beq (const std::string &name) const
Does a variable have a binding equation?
MX beq (const std::string &name) const
Get the binding equation for a variable.
std::string causality (const std::string &name) const
Get the causality.
void set_causality (const std::string &name, const std::string &val)
Set the causality, if permitted.
std::string variability (const std::string &name) const
Get the variability.
void set_variability (const std::string &name, const std::string &val)
Set the variability, if permitted.
std::string category (const std::string &name) const
Get the variable category.
void set_category (const std::string &name, const std::string &val)
Set the variable category, if permitted.
casadi_int numel (const std::string &name) const
Get the number of elements of a variable.
std::vector< casadi_int > dimension (const std::string &name) const
Get the dimensions of a variable.
double start_time () const
Get the start time.
void set_start_time (double val)
Set the start time.
double stop_time () const
Get the stop time.
void set_stop_time (double val)
Set the stop time.
double tolerance () const
Get the tolerance.
void set_tolerance (double val)
Set the tolerance.
double step_size () const
Get the step size.
void set_step_size (double val)
Set the step size.
std::string der (const std::string &name) const
Get the time derivative of model variables, single variable.
std::string pre (const std::string &name) const
Get the pre-variables of model variables.
double attribute (const std::string &a, const std::string &name) const
Get an attribute, single variable.
void set_attribute (const std::string &a, const std::string &name, double val)
Set an attribute, single variable.
double min (const std::string &name) const
Get the lower bound, single variable.
void set_min (const std::string &name, double val)
Set the lower bound, single variable.
double max (const std::string &name) const
Get the upper bound, single variable.
void set_max (const std::string &name, double val)
Set the upper bound, single variable.
double nominal (const std::string &name) const
Get the nominal value, single variable.
void set_nominal (const std::string &name, double val)
Set the nominal value, single variable.
std::vector< double > start (const std::string &name) const
Get the start attribute, single variable.
void set_start (const std::string &name, double val)
Set the start attribute, single variable.
void set_start (const std::string &name, const std::vector< double > &val)
Set the start attribute, vector argument.
void reset ()
void set (const std::string &name, double val)
void set (const std::string &name, const std::string &val)
GenericType get (const std::string &name) const
Evaluate the values for a set of variables at the initial time, single value.
std::vector< double > attribute (const std::string &a, const std::vector< std::string > &name) const
Get an attribute.
void set_attribute (const std::string &a, const std::vector< std::string > &name, const std::vector< double > &val)
Set an attribute.
std::vector< double > min (const std::vector< std::string > &name) const
Get the lower bound.
void set_min (const std::vector< std::string > &name, const std::vector< double > &val)
Set the lower bound.
std::vector< double > max (const std::vector< std::string > &name) const
Get the upper bound.
void set_max (const std::vector< std::string > &name, const std::vector< double > &val)
Set the upper bound.
std::vector< double > nominal (const std::vector< std::string > &name) const
Get the nominal value.
void set_nominal (const std::vector< std::string > &name, const std::vector< double > &val)
Set the nominal value.
std::vector< double > start (const std::vector< std::string > &name) const
Get the start attribute.
void set_start (const std::vector< std::string > &name, const std::vector< double > &val)
Set the start attribute.
void set (const std::vector< std::string > &name, const std::vector< double > &val)
Set the current value.
void set (const std::vector< std::string > &name, const std::vector< std::string > &val)
Set the current value (string)
std::vector< GenericType > get (const std::vector< std::string > &name) const
Evaluate the values for a set of variables at the initial time.
bool has (const std::string &name) const
Check if a particular variable exists.
std::vector< std::string > all () const
Get a list of all variables.
std::vector< std::string > all (const std::string &cat) const
Get a list of all variables of a particular category.
MX add_variable (const std::string &name, casadi_int n=1)
[DEPRECATED] Use add
MX add_variable (const std::string &name, const Sparsity &sp)
[DEPRECATED] Use add
void add_variable (const MX &new_v)
Add a new variable from symbolic expressions.
size_t add_variable_new (const std::string &name, casadi_int n=1)
[DEPRECATED] Use add
size_t add_variable_new (const std::string &name, const Sparsity &sp)
[DEPRECATED] Use add
size_t add_variable_new (const MX &new_v)
[DEPRECATED] Use add
bool has_variable (const std::string &name) const
[DEPRECATED] Ranamed "has"
std::vector< std::string > all_variables () const
Get a list of all variables.
Function oracle (bool sx=false, bool elim_w=false, bool lifted_calls=false) const
Get the (cached) oracle, SX or MX.
Sparsity jac_sparsity (const std::vector< std::string > &onames, const std::vector< std::string > &inames) const
Get Jacobian sparsity.
Variable & new_variable (const std::string &name, casadi_int numel=1)
[DEPRECATED] Use add
const DaeBuilderInternal * operator-> () const
Access a member function or object.
DaeBuilderInternal * operator-> ()
Access a member function or object.
std::string class_name () const
Get class name.
void disp (std::ostream &stream, bool more=false) const
Print a description of the object.
std::string get_str (bool more=false) const
Get string representation.
void print_ptr (std::ostream &stream=casadi::uout()) const
void own (SharedObjectInternal *node)
void assign (SharedObjectInternal *node)
Assign the node to a node class pointer without reference counting.
SharedObjectInternal * get () const
Get a const pointer to the node.
casadi_int getCount () const
Get the reference count.
void swap (GenericShared &other)
Swap content with another instance.
std::string debug_repr () const
bool is_null () const
Is a null pointer?
casadi_int __hash__ () const
Returns a number that is unique for a given Node.
GenericWeakRef< SharedObject, SharedObjectInternal > * weak ()
Get a weak reference to the object.
Variables and equations
const MX & time () const
Expression for independent variable (usually time)
std::vector< std::string > t_new () const
Independent variable (usually time)
std::vector< std::string > x () const
Differential states.
std::vector< std::string > y () const
Outputs *‍/.
std::vector< MX > ode () const
Ordinary differential equations (ODE)
std::vector< std::string > z () const
Algebraic variables.
std::vector< MX > alg () const
Algebraic equations.
std::vector< std::string > q () const
Quadrature states.
std::vector< MX > quad () const
Quadrature equations.
std::vector< MX > zero () const
Zero-crossing functions.
std::vector< MX > ydef () const
Definitions of output variables.
std::vector< std::string > u () const
Free controls.
std::vector< std::string > p () const
Parameters.
std::vector< std::string > c () const
Named constants.
std::vector< MX > cdef () const
Definitions of named constants.
std::vector< std::string > d () const
Dependent parameters.
std::vector< MX > ddef () const
Definitions of dependent parameters.
std::vector< std::string > w () const
Dependent variables.
std::vector< MX > wdef () const
Dependent variables and corresponding definitions.
std::vector< MX > init_lhs () const
Initial conditions, left-hand-side.
std::vector< MX > init_rhs () const
Initial conditions, right-hand-side.
std::vector< std::string > outputs () const
Model structure: outputs.
std::vector< std::string > derivatives () const
Model structure: derivatives.
std::vector< std::string > initial_unknowns () const
Model structure: initial unknowns.
bool has_t () const
Is there a time variable?
casadi_int nx () const
Differential states.
casadi_int nz () const
Algebraic variables.
casadi_int nq () const
Quadrature states.
casadi_int nzero () const
Zero-crossing functions.
casadi_int ny () const
Output variables.
casadi_int nu () const
Free controls.
casadi_int np () const
Parameters.
casadi_int nc () const
Named constants.
casadi_int nd () const
Dependent parameters.
casadi_int nw () const
Dependent variables.
Symbolic modeling
Formulate a dynamic system model
MX add (const std::string &name, const std::string &causality, const std::string &variability, const Dict &opts=Dict())
Add a new model variable.
MX add (const std::string &name, const std::string &causality, const Dict &opts=Dict())
Add a new model variable, default variability.
MX add (const std::string &name, const Dict &opts=Dict())
Add a new model variable, default variability and causality.
void add (const std::string &name, const std::string &causality, const std::string &variability, const MX &expr, const Dict &opts=Dict())
Add a new model variable, symbolic expression already available.
const MX & t () const
[DEPRECATED] Renamed "time"
MX add_t (const std::string &name="t")
[DEPRECATED] Replaced by add
MX add_p (const std::string &name=std::string())
[DEPRECATED] Replaced by add
MX add_u (const std::string &name=std::string())
[DEPRECATED] Replaced by add
MX add_x (const std::string &name=std::string())
[DEPRECATED] Replaced by add
MX add_z (const std::string &name=std::string())
[DEPRECATED] Replaced by add
MX add_q (const std::string &name=std::string())
[DEPRECATED] Replaced by add
MX add_c (const std::string &name, const MX &new_cdef)
[DEPRECATED] Replaced by add and eq
MX add_d (const std::string &name, const MX &new_ddef)
[DEPRECATED] Replaced by add and eq
MX add_w (const std::string &name, const MX &new_wdef)
[DEPRECATED] Replaced by add and eq
MX add_y (const std::string &name, const MX &new_ydef)
[DEPRECATED] Replaced by add and eq
void set_beq (const std::string &name, const MX &val)
[DEPRECATED] Replaced by eq
void eq (const MX &lhs, const MX &rhs, const Dict &opts=Dict())
Add a simple equation.
void when (const MX &cond, const std::vector< std::string > &eqs, const Dict &opts=Dict())
Add when equations.
std::string assign (const std::string &name, const MX &val)
Assignment inside a when-equation or if-else equation.
std::string reinit (const std::string &name, const MX &val)
Reinitialize a state inside when-equations.
void set_init (const std::string &name, const MX &init_rhs)
Specify the initial equation for a variable.
void set_ode (const std::string &name, const MX &ode_rhs)
[DEPRECATED] Replaced by eq
void set_alg (const std::string &name, const MX &alg_rhs)
[DEPRECATED] Replaced by eq
void add_init (const MX &lhs, const MX &rhs)
[DEPRECATED] Replaced by set_init
casadi_int ne () const
[DEPRECATED] Replaced by nzero()
std::vector< std::string > e () const
[DEPRECATED] Use all("zero") *‍/
void sanity_check () const
Check if dimensions match.
[DEPRECATED] Register an existing variable
void register_t (const std::string &name)
void register_p (const std::string &name)
void register_u (const std::string &name)
void register_x (const std::string &name)
void register_z (const std::string &name)
void register_q (const std::string &name)
void register_c (const std::string &name)
void register_d (const std::string &name)
void register_w (const std::string &name)
void register_y (const std::string &name)
void register_e (const std::string &name)
Manipulation
Reformulate the dynamic optimization problem.
void eliminate (const std::string &cat)
Eliminate all dependent parameters.
void sort (const std::string &cat)
Sort dependent parameters.
void lift (bool lift_shared=true, bool lift_calls=true)
Lift problem formulation by extracting shared subexpressions.
void prune (bool prune_p=true, bool prune_u=true)
Prune unused controls.
void tear ()
Identify iteration variables and residual equations using naming convention.
Functions
Add or load auxiliary functions
Function add_fun (const std::string &name, const std::vector< std::string > &arg, const std::vector< std::string > &res, const Dict &opts=Dict())
Add a function from loaded expressions.
Function add_fun (const Function &f)
Add an already existing function.
Function add_fun (const std::string &name, const Importer &compiler, const Dict &opts=Dict())
Add an external function.
bool has_fun (const std::string &name) const
Does a particular function already exist?
Function fun (const std::string &name) const
Get function by name.
std::vector< Function > fun () const
Get all functions.
void gather_fun (casadi_int max_depth=-1)
Collect embedded functions from the expression graph.
Import and export
void parse_fmi (const std::string &filename)
bool provides_directional_derivatives () const
Does the FMU provide support for analytic derivatives.
bool provides_directional_derivative () const
Does the FMU provide support for analytic derivatives (FMI 2 naming)
void load_fmi_description (const std::string &filename)
Import problem description from FMI or XML.
std::vector< std::string > export_fmu (const Dict &opts=Dict())
Export instance into an FMU.
void add_lc (const std::string &name, const std::vector< std::string > &f_out)
Add a named linear combination of output expressions.
Function create (const std::string &fname, const std::vector< std::string > &name_in, const std::vector< std::string > &name_out, bool sx, bool lifted_calls=false) const
Construct a function object, legacy syntax.
Function create (const std::string &name, const std::vector< std::string > &name_in, const std::vector< std::string > &name_out, const Dict &opts=Dict()) const
Construct a function object, names provided.
MX var (const std::string &name) const
MX operator() (const std::string &name) const
MX der (const MX &v) const
MX der (const MX &v)
casadi_int value_reference (const std::string &name) const
void set_value_reference (const std::string &name, casadi_int val)
std::string description (const std::string &name) const
void set_description (const std::string &name, const std::string &val)
std::string type (const std::string &name, casadi_int fmi_version=3) const
void set_type (const std::string &name, const std::string &val)
std::string initial (const std::string &name) const
void set_initial (const std::string &name, const std::string &val)
std::string unit (const std::string &name) const
void set_unit (const std::string &name, const std::string &val)
std::string display_unit (const std::string &name) const
void set_display_unit (const std::string &name, const std::string &val)
Variable & variable (const std::string &name)
const Variable & variable (const std::string &name) const
Variable & variable (size_t ind)
const Variable & variable (size_t ind) const
size_t find (const std::string &name) const
std::vector< size_t > find (const std::vector< std::string > &name) const
const std::string & name (size_t ind) const
std::vector< std::string > name (const std::vector< size_t > &ind) const
const MX & var (size_t ind) const
std::vector< MX > var (const std::vector< size_t > &ind) const
Static Public Member Functions
static bool test_cast (const SharedObjectInternal *ptr)
Check if a particular cast is allowed.
Protected Member Functions
void count_up ()
void count_down ()
Member Typedef Documentation
base_type
using casadi::SharedObject::base_type = SharedObject inherited
Definition at line 103 of file shared_object.hpp.
internal_base_type
using casadi::SharedObject::internal_base_type = SharedObjectInternal inherited
Definition at line 102 of file shared_object.hpp.
Constructor & Destructor Documentation
DaeBuilder() [1/2]
casadi::DaeBuilder::DaeBuilder ()
Definition at line 51 of file dae_builder.cpp.
{
 }
DaeBuilder() [2/2]
casadi::DaeBuilder::DaeBuilder (const std::string & name, const std::string & path = "", const Dict & opts = Dict()) explicit
Definition at line 54 of file dae_builder.cpp.
{
   own(new DaeBuilderInternal(name, path, opts));
   if (!path.empty()) load_fmi_description((*this)->resource_.path() + "/modelDescription.xml");
 }
References load_fmi_description(), name(), casadi::GenericShared< SharedObject, SharedObjectInternal >::own(), and casadi::path().
Member Function Documentation
__hash__()
casadi_int casadi::GenericShared< SharedObject , SharedObjectInternal >::__hash__ inherited
If the Object does not point to any node, "0" is returned.
Extra doc: https://github.com/casadi/casadi/wiki/L_av
Definition at line 124 of file generic_shared_impl.hpp.
{
     return reinterpret_cast<casadi_int>(get());
   }
add() [1/4]
MX casadi::DaeBuilder::add (const std::string & name, const Dict & opts = Dict())
Definition at line 587 of file dae_builder.cpp.
{
   try {
     return (*this)->add(name, opts).v;
   } catch (std::exception& e) {
     THROW_ERROR("add", e.what());
     return MX();
   }
 }
References e(), and name().
add() [2/4]
MX casadi::DaeBuilder::add (const std::string & name, const std::string & causality, const Dict & opts = Dict())
Definition at line 578 of file dae_builder.cpp.
{
   try {
     return (*this)->add(name, to_enum<Causality>(causality), opts).v;
   } catch (std::exception& e) {
     THROW_ERROR("add", e.what());
     return MX();
   }
 }
References causality(), e(), and name().
add() [3/4]
MX casadi::DaeBuilder::add (const std::string & name, const std::string & causality, const std::string & variability, const Dict & opts = Dict())
Definition at line 567 of file dae_builder.cpp.
{
   try {
     return (*this)->add(name, to_enum<Causality>(causality),
       to_enum<Variability>(variability), opts).v;
   } catch (std::exception& e) {
     THROW_ERROR("add", e.what());
     return MX();
   }
 }
References causality(), e(), name(), and variability().
Referenced by add_c(), add_d(), add_p(), add_q(), add_t(), add_u(), add_w(), add_x(), add_y(), and add_z().
add() [4/4]
void casadi::DaeBuilder::add (const std::string & name, const std::string & causality, const std::string & variability, const MX & expr, const Dict & opts = Dict())
Definition at line 596 of file dae_builder.cpp.
{
   try {
     // Ensure pure symbolic expression
     casadi_assert(expr.is_symbolic(), "Expression must be symbolic");
     // Make sure name matches expression
     casadi_assert(name == expr.name(), "Name must match expression");
     // Add variable
     (*this)->add(name, to_enum<Causality>(causality), to_enum<Variability>(variability),
       expr, opts);
   } catch (std::exception& e) {
     THROW_ERROR("add", e.what());
   }
 }
References causality(), e(), casadi::MX::is_symbolic(), name(), casadi::MX::name(), and variability().
add_c()
MX casadi::DaeBuilder::add_c (const std::string & name, const MX & new_cdef)
Definition at line 641 of file dae_builder.cpp.
{
   MX v = add(name, "local", "constant");
   set_beq(name, new_cdef);
   return v;
 }
References add(), name(), and set_beq().
add_d()
MX casadi::DaeBuilder::add_d (const std::string & name, const MX & new_ddef)
Definition at line 647 of file dae_builder.cpp.
{
   MX v = add(name, "calculatedParameter", "fixed");
   set_beq(name, new_ddef);
   return v;
 }
References add(), name(), and set_beq().
add_fun() [1/3]
Function casadi::DaeBuilder::add_fun (const Function & f)
Definition at line 1071 of file dae_builder.cpp.
{
   try {
     return (*this)->add_fun(f);
   } catch (std::exception& e) {
     THROW_ERROR("add_fun", e.what());
     return Function();  // never reached
   }
 }
References e().
add_fun() [2/3]
Function casadi::DaeBuilder::add_fun (const std::string & name, const Importer & compiler, const Dict & opts = Dict())
Definition at line 1090 of file dae_builder.cpp.
{
   casadi_assert(!has_fun(name), "Function '" + name + "' already exists");
   return add_fun(external(name, compiler, opts));
 }
References add_fun(), casadi::external(), has_fun(), and name().
add_fun() [3/3]
Function casadi::DaeBuilder::add_fun (const std::string & name, const std::vector< std::string > & arg, const std::vector< std::string > & res, const Dict & opts = Dict())
Definition at line 1080 of file dae_builder.cpp.
{
   try {
     return (*this)->add_fun(name, arg, res, opts);
   } catch (std::exception& e) {
     THROW_ERROR("add_fun", e.what());
     return Function();  // never reached
   }
 }
References e(), and name().
Referenced by add_fun(), and gather_fun().
add_init()
void casadi::DaeBuilder::add_init (const MX & lhs, const MX & rhs) inline
Definition at line 365 of file dae_builder.hpp.
{
     set_init(lhs.name(), rhs);
   }
References casadi::MX::name().
add_lc()
void casadi::DaeBuilder::add_lc (const std::string & name, const std::vector< std::string > & f_out)
Definition at line 1031 of file dae_builder.cpp.
{
   try {
     (*this)->add_lc(name, f_out);
   } catch (std::exception& e) {
     THROW_ERROR("add_lc", e.what());
   }
 }
References e(), and name().
add_p()
MX casadi::DaeBuilder::add_p (const std::string & name = std::string())
Definition at line 616 of file dae_builder.cpp.
{
   casadi_assert(!name.empty(), "Variable name is required");
   return add(name, "parameter", "tunable");
 }
References add(), and name().
add_q()
MX casadi::DaeBuilder::add_q (const std::string & name = std::string())
Definition at line 636 of file dae_builder.cpp.
{
   casadi_assert(!name.empty(), "Variable name is required");
   return add(name);
 }
References add(), and name().
add_t()
MX casadi::DaeBuilder::add_t (const std::string & name = "t")
Definition at line 612 of file dae_builder.cpp.
{
   return add(name, "independent");
 }
References add(), and name().
add_u()
MX casadi::DaeBuilder::add_u (const std::string & name = std::string())
Definition at line 621 of file dae_builder.cpp.
{
   casadi_assert(!name.empty(), "Variable name is required");
   return add(name, "input");
 }
References add(), and name().
add_variable() [1/3]
void casadi::DaeBuilder::add_variable (const MX & new_v)
Definition at line 412 of file dae_builder.cpp.
{
   Variable& v = new_variable(new_v.name());
   v.v = new_v;
 }
References casadi::MX::name(), new_variable(), and casadi::Variable::v.
add_variable() [2/3]
MX casadi::DaeBuilder::add_variable (const std::string & name, casadi_int n = 1)
Definition at line 402 of file dae_builder.cpp.
{
   return add_variable(name, Sparsity::dense(n));
 }
References casadi::Sparsity::dense(), and name().
add_variable() [3/3]
MX casadi::DaeBuilder::add_variable (const std::string & name, const Sparsity & sp)
Definition at line 406 of file dae_builder.cpp.
{
   Variable& v = new_variable(name);
   v.v = MX::sym(name, sp);
   return v.v;
 }
References name(), new_variable(), casadi::GenericMatrix< MX >::sym(), and casadi::Variable::v.
add_variable_new() [1/3]
size_t casadi::DaeBuilder::add_variable_new (const MX & new_v)
Definition at line 427 of file dae_builder.cpp.
{
   Variable& v = new_variable(new_v.name());
   v.v = new_v;
   return v.index;
 }
References casadi::Variable::index, casadi::MX::name(), new_variable(), and casadi::Variable::v.
add_variable_new() [2/3]
size_t casadi::DaeBuilder::add_variable_new (const std::string & name, casadi_int n = 1)
Definition at line 417 of file dae_builder.cpp.
{
   return add_variable_new(name, Sparsity::dense(n));
 }
References casadi::Sparsity::dense(), and name().
add_variable_new() [3/3]
size_t casadi::DaeBuilder::add_variable_new (const std::string & name, const Sparsity & sp)
Definition at line 421 of file dae_builder.cpp.
{
   Variable& v = new_variable(name);
   v.v = MX::sym(name, sp);
   return v.index;
 }
References casadi::Variable::index, name(), new_variable(), casadi::GenericMatrix< MX >::sym(), and casadi::Variable::v.
add_w()
MX casadi::DaeBuilder::add_w (const std::string & name, const MX & new_wdef)
Definition at line 653 of file dae_builder.cpp.
{
   MX v = add(name);
   eq(v, new_wdef);
   return v;
 }
References add(), eq(), and name().
add_x()
MX casadi::DaeBuilder::add_x (const std::string & name = std::string())
Definition at line 626 of file dae_builder.cpp.
{
   casadi_assert(!name.empty(), "Variable name is required");
   return add(name);
 }
References add(), and name().
add_y()
MX casadi::DaeBuilder::add_y (const std::string & name, const MX & new_ydef)
Definition at line 659 of file dae_builder.cpp.
{
   MX v = add(name, "output");
   eq(v, new_ydef);
   return v;
 }
References add(), eq(), and name().
add_z()
MX casadi::DaeBuilder::add_z (const std::string & name = std::string())
Definition at line 631 of file dae_builder.cpp.
{
   casadi_assert(!name.empty(), "Variable name is required");
   return add(name);
 }
References add(), and name().
alg()
std::vector< MX > casadi::DaeBuilder::alg () const
Extra doc: https://github.com/casadi/casadi/wiki/L_5i
Definition at line 91 of file dae_builder.cpp.
{
   try {
     return (*this)->output(OutputCategory::ALG);
   } catch (std::exception& e) {
     THROW_ERROR("alg", e.what());
     return {};  // never reached
   }
 }
References casadi::ALG, and e().
all() [1/2]
std::vector< std::string > casadi::DaeBuilder::all () const
Definition at line 288 of file dae_builder.cpp.
{
   try {
     return (*this)->all();
   } catch (std::exception& e) {
     THROW_ERROR("all", e.what());
     return {};  // never reached
   }
 }
References e().
all() [2/2]
std::vector< std::string > casadi::DaeBuilder::all (const std::string & cat) const
Definition at line 297 of file dae_builder.cpp.
{
   try {
     return (*this)->all(to_enum<Category>(cat));
   } catch (std::exception& e) {
     THROW_ERROR("all", e.what());
     return {};  // never reached
   }
 }
References e().
all_variables()
std::vector<std::string> casadi::DaeBuilder::all_variables () const inline
Definition at line 814 of file dae_builder.hpp.
 {return all();}
References casadi::all().
assign() [1/2]
std::string casadi::DaeBuilder::assign (const std::string & name, const MX & val)
Definition at line 691 of file dae_builder.cpp.
{
   try {
     return (*this)->assign(name, val).name;
   } catch (std::exception& e) {
     THROW_ERROR("assign", e.what());
     return std::string();  // never reached
   }
 }
References e(), and name().
assign() [2/2]
void casadi::GenericShared< SharedObject , SharedObjectInternal >::assign (Internal * node) inherited
improper use will cause memory leaks!
Extra doc: https://github.com/casadi/casadi/wiki/L_at
Definition at line 97 of file generic_shared_impl.hpp.
{
     node = node_;
   }
attribute() [1/2]
double casadi::DaeBuilder::attribute (const std::string & a, const std::string & name) const
Definition at line 1206 of file dae_builder.cpp.
{
   try {
     return (*this)->attribute(to_enum<Attribute>(a), name);
   } catch (std::exception& e) {
     THROW_ERROR("attribute", e.what());
     return 0; // never reached
   }
 }
References e(), and name().
attribute() [2/2]
std::vector< double > casadi::DaeBuilder::attribute (const std::string & a, const std::vector< std::string > & name) const
Definition at line 1215 of file dae_builder.cpp.
{
   try {
     return (*this)->attribute(to_enum<Attribute>(a), name);
   } catch (std::exception& e) {
     THROW_ERROR("attribute", e.what());
     return {}; // never reached
   }
 }
References e(), and name().
beq()
MX casadi::DaeBuilder::beq (const std::string & name) const
Definition at line 810 of file dae_builder.cpp.
{
   try {
     const Variable& v = (*this)->variable(name);
     return (*this)->variable(v.bind).v;
   } catch (std::exception& e) {
     THROW_ERROR("beq", e.what());
     return MX();  // never reached
   }
 }
References casadi::Variable::bind, e(), name(), and casadi::Variable::v.
c()
std::vector<std::string> casadi::DaeBuilder::c () const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_5p
Definition at line 156 of file dae_builder.hpp.
 {return all("c");}
References casadi::all().
category()
std::string casadi::DaeBuilder::category (const std::string & name) const
Definition at line 914 of file dae_builder.cpp.
{
   try {
     return to_string((*this)->category((*this)->find(name)));
   } catch (std::exception& e) {
     THROW_ERROR("category", e.what());
     return std::string();  // never reached
   }
 }
References e(), name(), and casadi::to_string().
causality()
std::string casadi::DaeBuilder::causality (const std::string & name) const
Definition at line 880 of file dae_builder.cpp.
{
   try {
     return to_string((*this)->causality((*this)->find(name)));
   } catch (std::exception& e) {
     THROW_ERROR("causality", e.what());
     return std::string();  // never reached
   }
 }
References e(), name(), and casadi::to_string().
Referenced by add().
cdef()
std::vector< MX > casadi::DaeBuilder::cdef () const
Extra doc: https://github.com/casadi/casadi/wiki/L_5q
Definition at line 126 of file dae_builder.cpp.
{
   try {
     return (*this)->cdef();
   } catch (std::exception& e) {
     THROW_ERROR("cdef", e.what());
     return {};  // never reached
   }
 }
References e().
class_name()
std::string casadi::SharedObject::class_name () const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_au
Definition at line 31 of file shared_object.cpp.
{
     return (*this)->class_name();
   }
Referenced by casadi::FmuFunction::check_mem_count(), casadi::MXFunction::export_code_body(), and casadi::BlazingSplineFunction::merge().
clear_all()
void casadi::DaeBuilder::clear_all (const std::string & v)
Definition at line 527 of file dae_builder.cpp.
{
   try {
     (*this)->clear_cache_ = true;  // Clear cache after this
     (*this)->indices(to_enum<Category>(v)).clear();
   } catch (std::exception& e) {
     THROW_ERROR("clear_all", e.what());
   }
 }
References e().
count_down()
void casadi::GenericShared< SharedObject , SharedObjectInternal >::count_down protected inherited
Definition at line 134 of file generic_shared_impl.hpp.
{
 #ifdef WITH_EXTRA_CHECKS
     casadi_assert_dev(Function::call_depth_==0);
 #endif // WITH_EXTRA_CHECKS
     if (!node) return;
     if (node->weak_ref_) {
 #ifdef CASADI_WITH_THREADSAFE_SYMBOLICS
       auto mutex = node->weak_ref_->get_mutex();
       // Avoid triggering a delete while a weak_ref.shared_if_alive is being called
       std::lock_guard<std::mutex> lock(*mutex);
       // Could it be that this mutex is destroyed when the lock goes out of scope?
 #endif // CASADI_WITH_THREADSAFE_SYMBOLICS
       if (--static_cast<Internal*>(node)->count == 0) {
         delete node;
         node = nullptr;
       }
     } else {
       if (--static_cast<Internal*>(node)->count == 0) {
         delete node;
         node = nullptr;
       }
     }
   }
count_up()
void casadi::GenericShared< SharedObject , SharedObjectInternal >::count_up protected inherited
Definition at line 133 of file generic_shared_impl.hpp.
{
 #ifdef WITH_EXTRA_CHECKS
     casadi_assert_dev(Function::call_depth_==0);
 #endif // WITH_EXTRA_CHECKS
     if (node) static_cast<Internal*>(node)->count++;
   }
create() [1/4]
Function casadi::DaeBuilder::create () const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_2c1
Definition at line 529 of file dae_builder.hpp.
 {return create(name() + "_dae");}
References create().
Referenced by create(), and get().
create() [2/4]
Function casadi::DaeBuilder::create (const std::string & fname, const Dict & opts = Dict()) const
Parameters
name Name assigned to the resulting function object
opts Optional settings
Extra doc: https://github.com/casadi/casadi/wiki/L_2c0
Definition at line 1062 of file dae_builder.cpp.
{
   try {
     return (*this)->create(name, dyn_in(), dyn_out(), opts, false, false);
   } catch (std::exception& e) {
     THROW_ERROR("create", e.what());
     return Function(); // never reached
   }
 }
References casadi::dyn_in(), casadi::dyn_out(), e(), and name().
create() [3/4]
Function casadi::DaeBuilder::create (const std::string & fname, const std::vector< std::string > & name_in, const std::vector< std::string > & name_out, bool sx, bool lifted_calls = false) const
Definition at line 1040 of file dae_builder.cpp.
{
   try {
     return (*this)->create(fname, name_in, name_out, Dict(), sx, lifted_calls);
   } catch (std::exception& e) {
     THROW_ERROR("create", e.what());
     return Function();  // never reached
   }
 }
References e().
create() [4/4]
Function casadi::DaeBuilder::create (const std::string & name, const std::vector< std::string > & name_in, const std::vector< std::string > & name_out, const Dict & opts = Dict()) const
Parameters
name Name assigned to the resulting function object
name_in Names of all the inputs
name_out Names of all the outputs
opts Optional settings
Extra doc: https://github.com/casadi/casadi/wiki/L_6e
Definition at line 1051 of file dae_builder.cpp.
{
   try {
     return (*this)->create(fname, name_in, name_out, opts, false, false);
   } catch (std::exception& e) {
     THROW_ERROR("create", e.what());
     return Function();  // never reached
   }
 }
References e().
d()
std::vector<std::string> casadi::DaeBuilder::d () const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_5r
Definition at line 166 of file dae_builder.hpp.
 {return all("d");}
References casadi::all().
ddef()
std::vector< MX > casadi::DaeBuilder::ddef () const
Interdependencies are allowed but must be non-cyclic.
Extra doc: https://github.com/casadi/casadi/wiki/L_5s
Definition at line 135 of file dae_builder.cpp.
{
   try {
     return (*this)->output(OutputCategory::DDEF);
   } catch (std::exception& e) {
     THROW_ERROR("ddef", e.what());
     return {};  // never reached
   }
 }
References casadi::DDEF, and e().
debug_repr()
std::string casadi::GenericShared< SharedObject , SharedObjectInternal >::debug_repr inherited
Definition at line 113 of file generic_shared_impl.hpp.
{
     if (node) {
         return node->debug_repr(node);
     } else {
         return "NULL";
     }
   }
dependent_fun()
Function casadi::DaeBuilder::dependent_fun (const std::string & fname, const std::vector< std::string > & s_in, const std::vector< std::string > & s_out) const
Definition at line 1147 of file dae_builder.cpp.
{
   try {
     return (*this)->dependent_fun(fname, s_in, s_out);
   } catch (std::exception& e) {
     THROW_ERROR("dependent_fun", e.what());
     return Function(); // never reached
   }
 }
References e().
der() [1/4]
MX casadi::DaeBuilder::der (const MX & v)
Differentiate an expression with respect to time
Definition at line 1197 of file dae_builder.cpp.
{
   try {
     return (*this)->der(v);
   } catch (std::exception& e) {
     THROW_ERROR("der", e.what());
     return MX();  // never reached
   }
 }
References e().
der() [2/4]
MX casadi::DaeBuilder::der (const MX & v) const
Differentiate an expression with respect to time
Definition at line 1188 of file dae_builder.cpp.
{
   try {
     return (*this)->der(v);
   } catch (std::exception& e) {
     THROW_ERROR("der", e.what());
     return MX();  // never reached
   }
 }
References e().
der() [3/4]
std::string casadi::DaeBuilder::der (const std::string & name) const
Definition at line 734 of file dae_builder.cpp.
{
   try {
     // Get variable index
     size_t ind = (*this)->find(name);
     // Differentiate
     ind = (*this)->variable(ind).der;
     casadi_assert(ind != size_t(-1), "No derivative expression for " + name);
     // Return name
     return (*this)->variable(ind).name;
   } catch (std::exception& e) {
     THROW_ERROR("der", e.what());
     return std::string();  // never reached
   }
 }
References e(), and name().
der() [4/4]
std::vector< std::string > casadi::DaeBuilder::der (const std::vector< std::string > & name) const
Definition at line 779 of file dae_builder.cpp.
{
   try {
     std::vector<std::string> r(name.size());
     for (size_t i = 0; i < r.size(); ++i) r[i] = der(name[i]);
     return r;
   } catch (std::exception& e) {
     THROW_ERROR("der", e.what());
     return {};  // never reached
   }
 }
References e(), and name().
derivatives()
std::vector< std::string > casadi::DaeBuilder::derivatives () const
Extra doc: https://github.com/casadi/casadi/wiki/L_62
Definition at line 170 of file dae_builder.cpp.
{
   try {
     return (*this)->name((*this)->derivatives_);
   } catch (std::exception& e) {
     THROW_ERROR("derivatives", e.what());
     return {};  // never reached
   }
 }
References e().
description()
std::string casadi::DaeBuilder::description (const std::string & name) const
Get/set description
Definition at line 852 of file dae_builder.cpp.
{
   return (*this)->variable(name).description;
 }
References name().
dimension()
std::vector< casadi_int > casadi::DaeBuilder::dimension (const std::string & name) const
Definition at line 959 of file dae_builder.cpp.
{
   return (*this)->variable(name).dimension;
 }
References name().
disp()
void casadi::SharedObject::disp (std::ostream & stream, bool more = false) const inherited
Definition at line 35 of file shared_object.cpp.
{
     if (is_null()) {
       stream << "NULL";
     } else {
       (*this)->disp(stream, more);
     }
   }
References casadi::GenericShared< SharedObject, SharedObjectInternal >::is_null().
Referenced by casadi::Nlpsol::disp_more(), and casadi::CsparseInterface::nfact().
display_unit()
std::string casadi::DaeBuilder::display_unit (const std::string & name) const
Get/set the display unit
Definition at line 947 of file dae_builder.cpp.
{
   return (*this)->variable(name).display_unit;
 }
References name().
e()
std::vector<std::string> casadi::DaeBuilder::e () const inline
Definition at line 373 of file dae_builder.hpp.
 {return all("zero");}
References casadi::all().
Referenced by add(), add_fun(), add_lc(), alg(), all(), assign(), attribute(), beq(), category(), causality(), cdef(), clear_all(), create(), ddef(), dependent_fun(), der(), derivatives(), eliminate(), eliminate_d(), eliminate_quad(), eliminate_w(), eq(), export_fmu(), find(), fun(), gather_fun(), get(), has(), has_beq(), has_fun(), has_t(), initial_unknowns(), jac_sparsity(), lift(), load_fmi_description(), max(), min(), name(), new_variable(), nominal(), ode(), oracle(), outputs(), pre(), provides_directional_derivatives(), prune(), quad(), reinit(), reorder(), reset(), sanity_check(), set(), set_all(), set_attribute(), set_beq(), set_category(), set_causality(), set_init(), set_max(), set_min(), set_nominal(), set_start(), set_start_time(), set_step_size(), set_stop_time(), set_tolerance(), set_variability(), sort(), sort_d(), sort_w(), sort_z(), start(), start_time(), step_size(), stop_time(), tear(), time(), tolerance(), transition(), var(), variability(), variable(), wdef(), when(), y(), ydef(), and zero().
eliminate()
void casadi::DaeBuilder::eliminate (const std::string & cat)
Definition at line 820 of file dae_builder.cpp.
{
   try {
     return (*this)->eliminate(to_enum<Category>(cat));
   } catch (std::exception& e) {
     THROW_ERROR("eliminate", e.what());
   }
 }
References e().
Referenced by eliminate_d(), eliminate_quad(), and eliminate_w().
eliminate_d()
void casadi::DaeBuilder::eliminate_d ()
Definition at line 479 of file dae_builder.cpp.
{
   try {
     return eliminate("d");
   } catch (std::exception& e) {
     THROW_ERROR("eliminate_d", e.what());
   }
 }
References e(), and eliminate().
eliminate_quad()
void casadi::DaeBuilder::eliminate_quad ()
Definition at line 495 of file dae_builder.cpp.
{
   try {
     return eliminate("q");
   } catch (std::exception& e) {
     THROW_ERROR("eliminate_quad", e.what());
   }
 }
References e(), and eliminate().
eliminate_w()
void casadi::DaeBuilder::eliminate_w ()
Definition at line 487 of file dae_builder.cpp.
{
   try {
     return eliminate("w");
   } catch (std::exception& e) {
     THROW_ERROR("eliminate_w", e.what());
   }
 }
References e(), and eliminate().
eq()
void casadi::DaeBuilder::eq (const MX & lhs, const MX & rhs, const Dict & opts = Dict())
Definition at line 675 of file dae_builder.cpp.
{
   try {
     (*this)->eq(lhs, rhs, opts);
   } catch (std::exception& e) {
     THROW_ERROR("eq", e.what());
   }
 }
References e().
Referenced by add_w(), add_y(), and set_beq().
export_fmu()
std::vector< std::string > casadi::DaeBuilder::export_fmu (const Dict & opts = Dict())
Definition at line 255 of file dae_builder.cpp.
{
   try {
     return (*this)->export_fmu(opts);
   } catch (std::exception& e) {
     THROW_ERROR("export_fmu", e.what());
   }
 }
References e().
find() [1/2]
size_t casadi::DaeBuilder::find (const std::string & name) const
[DEPRECATED] Access to internal class and corresponding indexing removed
Definition at line 347 of file dae_builder.cpp.
{
   try {
     return (*this)->find(name);
   } catch (std::exception& e) {
     THROW_ERROR("find", e.what());
     return -1; // never reached
   }
 }
References e(), and name().
Referenced by register_c(), register_d(), register_e(), register_p(), register_q(), register_t(), register_u(), register_w(), register_x(), register_y(), and register_z().
find() [2/2]
std::vector< size_t > casadi::DaeBuilder::find (const std::vector< std::string > & name) const
[DEPRECATED] Access to internal class and corresponding indexing removed
Definition at line 356 of file dae_builder.cpp.
{
   try {
     return (*this)->find(name);
   } catch (std::exception& e) {
     THROW_ERROR("find", e.what());
     return {}; // never reached
   }
 }
References e(), and name().
fun() [1/2]
std::vector< Function > casadi::DaeBuilder::fun () const
Definition at line 1134 of file dae_builder.cpp.
{
   return (*this)->fun_;
 }
fun() [2/2]
Function casadi::DaeBuilder::fun (const std::string & name) const
Definition at line 1104 of file dae_builder.cpp.
{
   try {
     return (*this)->fun(name);
   } catch (std::exception& e) {
     THROW_ERROR("fun", e.what());
     return Function();  // never reached
   }
 }
References e(), and name().
gather_fun()
void casadi::DaeBuilder::gather_fun (casadi_int max_depth = -1)
Definition at line 1113 of file dae_builder.cpp.
{
   try {
     // Get a function corresponding to all equations (no inputs)
     Function all_eq = (*this)->gather_eq();
     // Gather all functions
     std::vector<Function> allfun = all_eq.find_functions(max_depth);
     // Add to list of functions
     for (const Function& f : allfun) {
       if (has_fun(f.name())) {
         // Skip functions with duplicate names
         casadi_warning("Duplicate function: '" + f.name() + "', ignored");
       } else {
         // Add to list of functions
         add_fun(f);
       }
     }
   } catch (std::exception& e) {
     THROW_ERROR("gather_fun", e.what());
   }
 }
References add_fun(), e(), casadi::Function::find_functions(), and has_fun().
get() [1/3]
SharedObjectInternal * casadi::GenericShared< SharedObject , SharedObjectInternal >::get inherited
Definition at line 100 of file generic_shared_impl.hpp.
{
     return node;
   }
get() [2/3]
GenericType casadi::DaeBuilder::get (const std::string & name) const
Definition at line 1427 of file dae_builder.cpp.
{
   return get(std::vector<std::string>{name}).front();
 }
References casadi::GenericShared< SharedObject, SharedObjectInternal >::get(), and name().
get() [3/3]
std::vector< GenericType > casadi::DaeBuilder::get (const std::vector< std::string > & name) const
Definition at line 1431 of file dae_builder.cpp.
{
   try {
     // Create a temporary FmuFunction instance
     Function f = create(this->name() + "_get", {}, {}, Dict{{"aux", name}});
     // Get the stats
     Dict stats = f.stats().at("aux");
     // Return in the same order as inputs
     std::vector<GenericType> ret;
     ret.reserve(name.size());
     for (const std::string& n : name) ret.push_back(stats.at(n));
     return ret;
   } catch (std::exception& e) {
     THROW_ERROR("get", e.what());
     return {};
   }
 }
References create(), e(), name(), and casadi::Function::stats().
get_str()
std::string casadi::SharedObject::get_str (bool more = false) const inline inherited
Definition at line 91 of file shared_object.hpp.
{
         std::stringstream ss;
         disp(ss, more);
         return ss.str();
       }
getCount()
casadi_int casadi::GenericShared< SharedObject , SharedObjectInternal >::getCount inherited
Definition at line 103 of file generic_shared_impl.hpp.
{
     return (*this)->getCount();
   }
has()
bool casadi::DaeBuilder::has (const std::string & name) const
Definition at line 279 of file dae_builder.cpp.
{
   try {
     return (*this)->has(name);
   } catch (std::exception& e) {
     THROW_ERROR("has", e.what());
     return false;  // never reached
   }
 }
References e(), and name().
has_beq()
bool casadi::DaeBuilder::has_beq (const std::string & name) const
Definition at line 801 of file dae_builder.cpp.
{
   try {
     return !(*this)->variable(name).has_beq();
   } catch (std::exception& e) {
     THROW_ERROR("has_beq", e.what());
     return false;  // never reached
   }
 }
References e(), and name().
has_fun()
bool casadi::DaeBuilder::has_fun (const std::string & name) const
Definition at line 1095 of file dae_builder.cpp.
{
   try {
     return (*this)->has_fun(name);
   } catch (std::exception& e) {
     THROW_ERROR("has_fun", e.what());
     return false;  // never reached
   }
 }
References e(), and name().
Referenced by add_fun(), and gather_fun().
has_t()
bool casadi::DaeBuilder::has_t () const
Extra doc: https://github.com/casadi/casadi/wiki/L_64
Definition at line 188 of file dae_builder.cpp.
{
   try {
     return (*this)->has_t();
   } catch (std::exception& e) {
     THROW_ERROR("has_t", e.what());
     return false;  // never reached
   }
 }
References e().
Referenced by register_t().
has_variable()
bool casadi::DaeBuilder::has_variable (const std::string & name) const inline
Definition at line 811 of file dae_builder.hpp.
 {return has(name);}
init_lhs()
std::vector< MX > casadi::DaeBuilder::init_lhs () const
Extra doc: https://github.com/casadi/casadi/wiki/L_2b1
Definition at line 153 of file dae_builder.cpp.
{
   return (*this)->init_lhs();
 }
init_rhs()
std::vector< MX > casadi::DaeBuilder::init_rhs () const
Extra doc: https://github.com/casadi/casadi/wiki/L_2b2
Definition at line 157 of file dae_builder.cpp.
{
   return (*this)->init_rhs();
 }
Referenced by set_init().
initial()
std::string casadi::DaeBuilder::initial (const std::string & name) const
Get/set the initial property
Definition at line 931 of file dae_builder.cpp.
{
   return to_string((*this)->variable(name).initial);
 }
References name(), and casadi::to_string().
initial_unknowns()
std::vector< std::string > casadi::DaeBuilder::initial_unknowns () const
Extra doc: https://github.com/casadi/casadi/wiki/L_63
Definition at line 179 of file dae_builder.cpp.
{
   try {
     return (*this)->name((*this)->initial_unknowns_);
   } catch (std::exception& e) {
     THROW_ERROR("initial_unknowns", e.what());
     return {};  // never reached
   }
 }
References e().
is_null()
bool casadi::GenericShared< SharedObject , SharedObjectInternal >::is_null inherited
Definition at line 117 of file generic_shared_impl.hpp.
{
     return node==nullptr;
   }
jac_sparsity()
Sparsity casadi::DaeBuilder::jac_sparsity (const std::vector< std::string > & onames, const std::vector< std::string > & inames) const
Extra doc: https://github.com/casadi/casadi/wiki/L_6g
Definition at line 1448 of file dae_builder.cpp.
{
   try {
     return (*this)->jac_sparsity((*this)->find(onames), (*this)->find(inames));
   } catch (std::exception& e) {
     THROW_ERROR("jac_sparsity", e.what());
     return Sparsity();  // never reached
   }
 }
References e().
lift()
void casadi::DaeBuilder::lift (bool lift_shared = true, bool lift_calls = true)
Definition at line 836 of file dae_builder.cpp.
{
   try {
     (*this)->lift(lift_shared, lift_calls);
   } catch (std::exception& e) {
     THROW_ERROR("lift", e.what());
   }
 }
References e().
load_fmi_description()
void casadi::DaeBuilder::load_fmi_description (const std::string & filename)
Definition at line 237 of file dae_builder.cpp.
{
   try {
     (*this)->load_fmi_description(filename);
   } catch (std::exception& e) {
     THROW_ERROR("load_fmi_description", e.what());
   }
 }
References e(), and casadi::filename().
Referenced by DaeBuilder().
max() [1/2]
double casadi::DaeBuilder::max (const std::string & name) const
Definition at line 1276 of file dae_builder.cpp.
{
   try {
     return (*this)->variable(name).max;
   } catch (std::exception& e) {
     THROW_ERROR("max", e.what());
     return 0; // never reached
   }
 }
References e(), and name().
max() [2/2]
std::vector< double > casadi::DaeBuilder::max (const std::vector< std::string > & name) const
Definition at line 1285 of file dae_builder.cpp.
{
   try {
     return (*this)->attribute(Attribute::MAX, name);
   } catch (std::exception& e) {
     THROW_ERROR("max", e.what());
     return {}; // never reached
   }
 }
References e(), casadi::MAX, and name().
min() [1/2]
double casadi::DaeBuilder::min (const std::string & name) const
Definition at line 1242 of file dae_builder.cpp.
{
   try {
     return (*this)->variable(name).min;
   } catch (std::exception& e) {
     THROW_ERROR("min", e.what());
     return 0; // never reached
   }
 }
References e(), and name().
min() [2/2]
std::vector< double > casadi::DaeBuilder::min (const std::vector< std::string > & name) const
Definition at line 1251 of file dae_builder.cpp.
{
   try {
     return (*this)->attribute(Attribute::MIN, name);
   } catch (std::exception& e) {
     THROW_ERROR("min", e.what());
     return {}; // never reached
   }
 }
References e(), casadi::MIN, and name().
name() [1/3]
const std::string & casadi::DaeBuilder::name () const
Extra doc: https://github.com/casadi/casadi/wiki/L_5d
Definition at line 59 of file dae_builder.cpp.
{
   return (*this)->name_;
 }
Referenced by add(), add_c(), add_d(), add_fun(), add_lc(), add_p(), add_q(), add_t(), add_u(), add_variable(), add_variable_new(), add_w(), add_x(), add_y(), add_z(), assign(), attribute(), beq(), category(), causality(), create(), DaeBuilder(), der(), description(), dimension(), display_unit(), find(), fun(), get(), has(), has_beq(), has_fun(), initial(), max(), min(), new_variable(), nominal(), numel(), pre(), register_c(), register_d(), register_e(), register_p(), register_q(), register_t(), register_u(), register_w(), register_x(), register_y(), register_z(), reinit(), set(), set_all(), set_attribute(), set_beq(), set_category(), set_causality(), set_description(), set_display_unit(), set_init(), set_initial(), set_max(), set_min(), set_nominal(), set_start(), set_type(), set_unit(), set_value_reference(), set_variability(), start(), type(), unit(), value_reference(), var(), variability(), and variable().
name() [2/3]
std::vector< std::string > casadi::DaeBuilder::name (const std::vector< size_t > & ind) const
[DEPRECATED] Access to internal class and corresponding indexing removed
Definition at line 375 of file dae_builder.cpp.
{
   try {
     return (*this)->name(ind);
   } catch (std::exception& e) {
     THROW_ERROR("name", e.what());
     return {}; // never reached
   }
 }
References e().
name() [3/3]
const std::string & casadi::DaeBuilder::name (size_t ind) const
[DEPRECATED] Access to internal class and corresponding indexing removed
Definition at line 365 of file dae_builder.cpp.
{
   try {
     return (*this)->name(ind);
   } catch (std::exception& e) {
     THROW_ERROR("name", e.what());
     static std::string dummy;
     return dummy; // never reached
   }
 }
References e().
nc()
casadi_int casadi::DaeBuilder::nc () const
Extra doc: https://github.com/casadi/casadi/wiki/L_6b
Definition at line 225 of file dae_builder.cpp.
{
   return (*this)->size(Category::C);
 }
References casadi::C.
nd()
casadi_int casadi::DaeBuilder::nd () const
Extra doc: https://github.com/casadi/casadi/wiki/L_6c
Definition at line 229 of file dae_builder.cpp.
{
   return (*this)->size(Category::D);
 }
References casadi::D.
ne()
casadi_int casadi::DaeBuilder::ne () const inline
Definition at line 370 of file dae_builder.hpp.
 {return nzero();}
new_variable()
Variable & casadi::DaeBuilder::new_variable (const std::string & name, casadi_int numel = 1)
Definition at line 307 of file dae_builder.cpp.
{
   try {
     return (*this)->new_variable(name, {numel});
   } catch (std::exception& e) {
     THROW_ERROR("new_variable", e.what());
   }
 }
References e(), and name().
Referenced by add_variable(), and add_variable_new().
nominal() [1/2]
double casadi::DaeBuilder::nominal (const std::string & name) const
Definition at line 1310 of file dae_builder.cpp.
{
   try {
     return (*this)->variable(name).nominal;
   } catch (std::exception& e) {
     THROW_ERROR("nominal", e.what());
     return 0; // never reached
   }
 }
References e(), and name().
nominal() [2/2]
std::vector< double > casadi::DaeBuilder::nominal (const std::vector< std::string > & name) const
Definition at line 1319 of file dae_builder.cpp.
{
   try {
     return (*this)->attribute(Attribute::NOMINAL, name);
   } catch (std::exception& e) {
     THROW_ERROR("nominal", e.what());
     return {}; // never reached
   }
 }
References e(), name(), and casadi::NOMINAL.
np()
casadi_int casadi::DaeBuilder::np () const
Extra doc: https://github.com/casadi/casadi/wiki/L_6a
Definition at line 221 of file dae_builder.cpp.
{
   return (*this)->size(Category::P);
 }
References casadi::P.
nq()
casadi_int casadi::DaeBuilder::nq () const
Extra doc: https://github.com/casadi/casadi/wiki/L_67
Definition at line 205 of file dae_builder.cpp.
{
   return (*this)->size(Category::Q);
 }
References casadi::Q.
nu()
casadi_int casadi::DaeBuilder::nu () const
Extra doc: https://github.com/casadi/casadi/wiki/L_69
Definition at line 217 of file dae_builder.cpp.
{
   return (*this)->size(Category::U);
 }
References casadi::U.
numel()
casadi_int casadi::DaeBuilder::numel (const std::string & name) const
Definition at line 955 of file dae_builder.cpp.
{
   return (*this)->variable(name).numel;
 }
References name().
nw()
casadi_int casadi::DaeBuilder::nw () const
Extra doc: https://github.com/casadi/casadi/wiki/L_6d
Definition at line 233 of file dae_builder.cpp.
{
   return (*this)->size(Category::W);
 }
References casadi::W.
nx()
casadi_int casadi::DaeBuilder::nx () const
Extra doc: https://github.com/casadi/casadi/wiki/L_65
Definition at line 197 of file dae_builder.cpp.
{
   return (*this)->size(Category::X);
 }
References casadi::X.
ny()
casadi_int casadi::DaeBuilder::ny () const
Extra doc: https://github.com/casadi/casadi/wiki/L_68
Definition at line 213 of file dae_builder.cpp.
{
   return (*this)->outputs_.size();
 }
nz()
casadi_int casadi::DaeBuilder::nz () const
Extra doc: https://github.com/casadi/casadi/wiki/L_66
Definition at line 201 of file dae_builder.cpp.
{
   return (*this)->size(Category::Z);
 }
References casadi::Z.
nzero()
casadi_int casadi::DaeBuilder::nzero () const
Extra doc: https://github.com/casadi/casadi/wiki/L_2cb
Definition at line 209 of file dae_builder.cpp.
{
   return (*this)->event_indicators_.size();
 }
ode()
std::vector< MX > casadi::DaeBuilder::ode () const
Extra doc: https://github.com/casadi/casadi/wiki/L_5g
Definition at line 82 of file dae_builder.cpp.
{
   try {
     return (*this)->output(OutputCategory::ODE);
   } catch (std::exception& e) {
     THROW_ERROR("ode", e.what());
     return {};  // never reached
   }
 }
References e(), and casadi::ODE.
operator()()
MX casadi::DaeBuilder::operator() (const std::string & name) const inline
Get variable expression by name
Definition at line 548 of file dae_builder.hpp.
 {return var(name);}
operator->() [1/2]
DaeBuilderInternal * casadi::DaeBuilder::operator-> ()
Definition at line 1180 of file dae_builder.cpp.
{
   return static_cast<DaeBuilderInternal*>(SharedObject::operator->());
 }
References casadi::GenericShared< SharedObject, SharedObjectInternal >::operator->().
operator->() [2/2]
const DaeBuilderInternal * casadi::DaeBuilder::operator-> () const
Definition at line 1184 of file dae_builder.cpp.
{
   return static_cast<const DaeBuilderInternal*>(SharedObject::operator->());
 }
References casadi::GenericShared< SharedObject, SharedObjectInternal >::operator->().
oracle()
Function casadi::DaeBuilder::oracle (bool sx = false, bool elim_w = false, bool lifted_calls = false) const
Definition at line 1138 of file dae_builder.cpp.
{
   try {
     return (*this)->oracle(sx, elim_w, lifted_calls);
   } catch (std::exception& e) {
     THROW_ERROR("oracle", e.what());
     return Function(); // never reached
   }
 }
References e(), and casadi::FunctionInternal::oracle().
outputs()
std::vector< std::string > casadi::DaeBuilder::outputs () const
Extra doc: https://github.com/casadi/casadi/wiki/L_61
Definition at line 161 of file dae_builder.cpp.
{
   try {
     return (*this)->name((*this)->outputs_);
   } catch (std::exception& e) {
     THROW_ERROR("outputs", e.what());
     return {};  // never reached
   }
 }
References e().
own()
void casadi::GenericShared< SharedObject , SharedObjectInternal >::own (Internal * node) inherited
Assign the node to a node class pointer (or null)
Definition at line 90 of file generic_shared_impl.hpp.
{
     count_down();
     node = node_;
     count_up();
   }
p()
std::vector<std::string> casadi::DaeBuilder::p () const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_5o
Definition at line 151 of file dae_builder.hpp.
 {return all("p");}
References casadi::all().
parse_fmi()
void casadi::DaeBuilder::parse_fmi (const std::string & filename) inline
Import existing problem from FMI/XML
Definition at line 482 of file dae_builder.hpp.
 {load_fmi_description(filename); }
References casadi::filename().
pre() [1/3]
MX casadi::DaeBuilder::pre (const MX & v) const
Definition at line 764 of file dae_builder.cpp.
{
   try {
     // Not implemented
     static bool warned = false;
     if (!warned) {
       casadi_warning("DaeBuilder::pre has not been implemented: Returning identity mapping");
       warned = true;
     }
     return v;
   } catch (std::exception& e) {
     THROW_ERROR("pre", e.what());
     return MX();  // never reached
   }
 }
References e().
pre() [2/3]
std::string casadi::DaeBuilder::pre (const std::string & name) const
Definition at line 749 of file dae_builder.cpp.
{
   try {
     // Not implemented
     static bool warned = false;
     if (!warned) {
       casadi_warning("DaeBuilder::pre has not been implemented: Returning identity mapping");
       warned = true;
     }
     return name;
   } catch (std::exception& e) {
     THROW_ERROR("pre", e.what());
     return std::string();  // never reached
   }
 }
References e(), and name().
pre() [3/3]
std::vector< std::string > casadi::DaeBuilder::pre (const std::vector< std::string > & name) const
Definition at line 790 of file dae_builder.cpp.
{
   try {
     std::vector<std::string> r(name.size());
     for (size_t i = 0; i < r.size(); ++i) r[i] = pre(name[i]);
     return r;
   } catch (std::exception& e) {
     THROW_ERROR("pre", e.what());
     return {};  // never reached
   }
 }
References e(), and name().
print_ptr()
void casadi::SharedObject::print_ptr (std::ostream & stream = casadi::uout()) const inherited
Print the pointer to the internal class
Definition at line 43 of file shared_object.cpp.
{
     stream << get();
   }
References casadi::GenericShared< SharedObject, SharedObjectInternal >::get().
provides_directional_derivative()
bool casadi::DaeBuilder::provides_directional_derivative () const inline
Definition at line 488 of file dae_builder.hpp.
 {return provides_directional_derivatives();}
provides_directional_derivatives()
bool casadi::DaeBuilder::provides_directional_derivatives () const
Definition at line 245 of file dae_builder.cpp.
{
   try {
     casadi_assert(!(*this)->symbolic_, "Functionality only applies to imported standard FMUs");
     return (*this)->provides_directional_derivatives_;
   } catch (std::exception& e) {
     THROW_ERROR("provides_directional_derivatives", e.what());
     return false;
   }
 }
References e().
prune()
void casadi::DaeBuilder::prune (bool prune_p = true, bool prune_u = true)
Definition at line 263 of file dae_builder.cpp.
{
   try {
     (*this)->prune(prune_p, prune_u);
   } catch (std::exception& e) {
     THROW_ERROR("prune", e.what());
   }
 }
References e().
q()
std::vector<std::string> casadi::DaeBuilder::q () const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_5j
Definition at line 126 of file dae_builder.hpp.
 {return all("q");}
References casadi::all().
quad()
std::vector< MX > casadi::DaeBuilder::quad () const
Extra doc: https://github.com/casadi/casadi/wiki/L_5k
Definition at line 100 of file dae_builder.cpp.
{
   try {
     return (*this)->output(OutputCategory::QUAD);
   } catch (std::exception& e) {
     THROW_ERROR("quad", e.what());
     return {};  // never reached
   }
 }
References e(), and casadi::QUAD.
register_c()
void casadi::DaeBuilder::register_c (const std::string & name)
Definition at line 459 of file dae_builder.cpp.
{
   (*this)->indices(Category::C).push_back(find(name));
 }
References casadi::C, find(), and name().
register_d()
void casadi::DaeBuilder::register_d (const std::string & name)
Definition at line 463 of file dae_builder.cpp.
{
   (*this)->indices(Category::D).push_back(find(name));
 }
References casadi::D, find(), and name().
register_e()
void casadi::DaeBuilder::register_e (const std::string & name)
Definition at line 475 of file dae_builder.cpp.
{
   (*this)->event_indicators_.push_back(find(name));
 }
References find(), and name().
register_p()
void casadi::DaeBuilder::register_p (const std::string & name)
Definition at line 439 of file dae_builder.cpp.
{
   (*this)->indices(Category::P).push_back(find(name));
 }
References find(), name(), and casadi::P.
register_q()
void casadi::DaeBuilder::register_q (const std::string & name)
Definition at line 455 of file dae_builder.cpp.
{
   (*this)->indices(Category::Q).push_back(find(name));
 }
References find(), name(), and casadi::Q.
register_t()
void casadi::DaeBuilder::register_t (const std::string & name)
Definition at line 433 of file dae_builder.cpp.
{
   // Save to class
   casadi_assert(!has_t(), "'t' already defined");
   (*this)->indices(Category::T).push_back(find(name));
 }
References find(), has_t(), name(), and casadi::T.
register_u()
void casadi::DaeBuilder::register_u (const std::string & name)
Definition at line 443 of file dae_builder.cpp.
{
   (*this)->indices(Category::U).push_back(find(name));
 }
References find(), name(), and casadi::U.
register_w()
void casadi::DaeBuilder::register_w (const std::string & name)
Definition at line 467 of file dae_builder.cpp.
{
   (*this)->indices(Category::W).push_back(find(name));
 }
References find(), name(), and casadi::W.
register_x()
void casadi::DaeBuilder::register_x (const std::string & name)
Definition at line 447 of file dae_builder.cpp.
{
   (*this)->indices(Category::X).push_back(find(name));
 }
References find(), name(), and casadi::X.
register_y()
void casadi::DaeBuilder::register_y (const std::string & name)
Definition at line 471 of file dae_builder.cpp.
{
   (*this)->outputs_.push_back(find(name));
 }
References find(), and name().
register_z()
void casadi::DaeBuilder::register_z (const std::string & name)
Definition at line 451 of file dae_builder.cpp.
{
   (*this)->indices(Category::Z).push_back(find(name));
 }
References find(), name(), and casadi::Z.
reinit()
std::string casadi::DaeBuilder::reinit (const std::string & name, const MX & val)
Definition at line 700 of file dae_builder.cpp.
{
   try {
     return (*this)->reinit(name, val).name;
   } catch (std::exception& e) {
     THROW_ERROR("reinit", e.what());
     return std::string();  // never reached
   }
 }
References e(), and name().
reorder()
void casadi::DaeBuilder::reorder (const std::string & cat, const std::vector< std::string > & v)
Definition at line 552 of file dae_builder.cpp.
{
   try {
     auto vind = (*this)->find(v);
     if (cat == "y") {
       // Reorder outputs
       (*this)->reorder("y", (*this)->outputs_, vind);
     } else {
       // Reorder inputs
       (*this)->reorder(to_enum<Category>(cat), vind);
     }
   } catch (std::exception& e) {
     THROW_ERROR("reorder", e.what());
   }
 }
References e().
Referenced by sort_z().
reset()
void casadi::DaeBuilder::reset ()
Definition at line 1386 of file dae_builder.cpp.
{
   try {
     (*this)->reset();
   } catch (std::exception& e) {
     THROW_ERROR("reset", e.what());
   }
 }
References e().
sanity_check()
void casadi::DaeBuilder::sanity_check () const
Definition at line 717 of file dae_builder.cpp.
{
   try {
     (*this)->sanity_check();
   } catch (std::exception& e) {
     THROW_ERROR("sanity_check", e.what());
   }
 }
References e().
set() [1/4]
void casadi::DaeBuilder::set (const std::string & name, const std::string & val)
Definition at line 1402 of file dae_builder.cpp.
{
   try {
     (*this)->set_string_attribute(Attribute::STRINGVALUE, name, val);
   } catch (std::exception& e) {
     THROW_ERROR("set", e.what());
   }
 }
References e(), name(), and casadi::STRINGVALUE.
set() [2/4]
void casadi::DaeBuilder::set (const std::string & name, double val)
Definition at line 1394 of file dae_builder.cpp.
{
   try {
     (*this)->set_attribute(Attribute::VALUE, name, val);
   } catch (std::exception& e) {
     THROW_ERROR("set", e.what());
   }
 }
References e(), name(), and casadi::VALUE.
set() [3/4]
void casadi::DaeBuilder::set (const std::vector< std::string > & name, const std::vector< double > & val)
Definition at line 1410 of file dae_builder.cpp.
{
   try {
     (*this)->set_attribute(Attribute::VALUE, name, val);
   } catch (std::exception& e) {
     THROW_ERROR("set", e.what());
   }
 }
References e(), name(), and casadi::VALUE.
set() [4/4]
void casadi::DaeBuilder::set (const std::vector< std::string > & name, const std::vector< std::string > & val)
Definition at line 1418 of file dae_builder.cpp.
{
   try {
     (*this)->set_string_attribute(Attribute::STRINGVALUE, name, val);
   } catch (std::exception& e) {
     THROW_ERROR("set", e.what());
   }
 }
References e(), name(), and casadi::STRINGVALUE.
set_alg()
void casadi::DaeBuilder::set_alg (const std::string & name, const MX & alg_rhs) inline
Definition at line 359 of file dae_builder.hpp.
{
     (void)name;
     eq(0, alg_rhs);
   }
set_all()
void casadi::DaeBuilder::set_all (const std::string & v, const std::vector< std::string > & name)
Definition at line 536 of file dae_builder.cpp.
{
   try {
     (*this)->clear_cache_ = true;  // Clear cache after this
     const std::vector<size_t>& new_ind = (*this)->find(name);
     if (v == "y") {
       (*this)->outputs_ = new_ind;
     } else {
       (*this)->indices(to_enum<Category>(v)) = new_ind;
     }
   } catch (std::exception& e) {
     THROW_ERROR("set_all", e.what());
   }
 }
References e(), and name().
set_attribute() [1/2]
void casadi::DaeBuilder::set_attribute (const std::string & a, const std::string & name, double val)
Definition at line 1225 of file dae_builder.cpp.
{
   try {
     (*this)->set_attribute(to_enum<Attribute>(a), name, val);
   } catch (std::exception& e) {
     THROW_ERROR("set_attribute", e.what());
   }
 }
References e(), and name().
set_attribute() [2/2]
void casadi::DaeBuilder::set_attribute (const std::string & a, const std::vector< std::string > & name, const std::vector< double > & val)
Definition at line 1233 of file dae_builder.cpp.
{
   try {
     (*this)->set_attribute(to_enum<Attribute>(a), name, val);
   } catch (std::exception& e) {
     THROW_ERROR("set_attribute", e.what());
   }
 }
References e(), and name().
set_beq()
void casadi::DaeBuilder::set_beq (const std::string & name, const MX & val)
Definition at line 665 of file dae_builder.cpp.
{
   try {
     eq(var(name), val);
   } catch (std::exception& e) {
     THROW_ERROR("set_beq", e.what());
   }
 }
References e(), eq(), name(), and var().
Referenced by add_c(), and add_d().
set_category()
void casadi::DaeBuilder::set_category (const std::string & name, const std::string & val)
The following changes are permitted: Controls 'u' can be changed to/from tunable parameters 'p' or fixed parameters 'c' Differential states that do not appear in the right-hand-sides can be changed between regular states 'x' and quadrature states 'q'
Other changes are not permitted. Causality and variability is updated accordingly.
Extra doc: https://github.com/casadi/casadi/wiki/L_2c4
Definition at line 923 of file dae_builder.cpp.
{
   try {
     (*this)->set_category((*this)->find(name), to_enum<Category>(val));
   } catch (std::exception& e) {
     THROW_ERROR("set_category", e.what());
   }
 }
References e(), and name().
set_causality()
void casadi::DaeBuilder::set_causality (const std::string & name, const std::string & val)
The following changes are permitted: For controls 'u' (variability 'continuous', causality 'input'), free parameters 'p' (variability 'tunable', causality 'parameter') and fixed parameters 'c' (variability 'fixed', causality 'parameter'), causality can only be changed indirectly, by updating the variability Add or remove an output 'y' by setting the causality to 'output' or 'local', respectively
No other changes are permitted.
Extra doc: https://github.com/casadi/casadi/wiki/L_2c2
Definition at line 889 of file dae_builder.cpp.
{
   try {
     (*this)->set_causality((*this)->find(name), to_enum<Causality>(val));
   } catch (std::exception& e) {
     THROW_ERROR("set_causality", e.what());
   }
 }
References e(), and name().
set_description()
void casadi::DaeBuilder::set_description (const std::string & name, const std::string & val)
Get/set description
Definition at line 856 of file dae_builder.cpp.
{
   (*this)->variable(name).description = val;
 }
References name().
set_display_unit()
void casadi::DaeBuilder::set_display_unit (const std::string & name, const std::string & val)
Get/set the display unit
Definition at line 951 of file dae_builder.cpp.
{
   (*this)->variable(name).display_unit = val;
 }
References name().
set_init()
void casadi::DaeBuilder::set_init (const std::string & name, const MX & init_rhs)
Definition at line 709 of file dae_builder.cpp.
{
   try {
     (*this)->set_init(name, init_rhs);
   } catch (std::exception& e) {
     THROW_ERROR("set_init", e.what());
   }
 }
References e(), init_rhs(), and name().
set_initial()
void casadi::DaeBuilder::set_initial (const std::string & name, const std::string & val)
Get/set the initial property
Definition at line 935 of file dae_builder.cpp.
{
   (*this)->variable(name).initial = to_enum<Initial>(val);
 }
References name().
set_max() [1/2]
void casadi::DaeBuilder::set_max (const std::string & name, double val)
Definition at line 1294 of file dae_builder.cpp.
{
   try {
     (*this)->variable(name).max = val;
   } catch (std::exception& e) {
     THROW_ERROR("set_max", e.what());
   }
 }
References e(), and name().
set_max() [2/2]
void casadi::DaeBuilder::set_max (const std::vector< std::string > & name, const std::vector< double > & val)
Definition at line 1302 of file dae_builder.cpp.
{
   try {
     (*this)->set_attribute(Attribute::MAX, name, val);
   } catch (std::exception& e) {
     THROW_ERROR("set_max", e.what());
   }
 }
References e(), casadi::MAX, and name().
set_min() [1/2]
void casadi::DaeBuilder::set_min (const std::string & name, double val)
Definition at line 1260 of file dae_builder.cpp.
{
   try {
     (*this)->variable(name).min = val;
   } catch (std::exception& e) {
     THROW_ERROR("set_min", e.what());
   }
 }
References e(), and name().
set_min() [2/2]
void casadi::DaeBuilder::set_min (const std::vector< std::string > & name, const std::vector< double > & val)
Definition at line 1268 of file dae_builder.cpp.
{
   try {
     (*this)->set_attribute(Attribute::MIN, name, val);
   } catch (std::exception& e) {
     THROW_ERROR("set_min", e.what());
   }
 }
References e(), casadi::MIN, and name().
set_nominal() [1/2]
void casadi::DaeBuilder::set_nominal (const std::string & name, double val)
Definition at line 1328 of file dae_builder.cpp.
{
   try {
     (*this)->variable(name).nominal = val;
   } catch (std::exception& e) {
     THROW_ERROR("set_nominal", e.what());
   }
 }
References e(), and name().
set_nominal() [2/2]
void casadi::DaeBuilder::set_nominal (const std::vector< std::string > & name, const std::vector< double > & val)
Definition at line 1336 of file dae_builder.cpp.
{
   try {
     (*this)->set_attribute(Attribute::NOMINAL, name, val);
   } catch (std::exception& e) {
     THROW_ERROR("set_mininal", e.what());
   }
 }
References e(), name(), and casadi::NOMINAL.
set_ode()
void casadi::DaeBuilder::set_ode (const std::string & name, const MX & ode_rhs) inline
Definition at line 354 of file dae_builder.hpp.
{
     eq(var(name), ode_rhs);
   }
set_start() [1/3]
void casadi::DaeBuilder::set_start (const std::string & name, const std::vector< double > & val)
Definition at line 1370 of file dae_builder.cpp.
{
   try {
     (*this)->set_attribute(Attribute::START, std::vector<std::string>{name}, val);
   } catch (std::exception& e) {
     THROW_ERROR("set_start", e.what());
   }
 }
References e(), name(), and casadi::START.
set_start() [2/3]
void casadi::DaeBuilder::set_start (const std::string & name, double val)
Definition at line 1362 of file dae_builder.cpp.
{
   try {
     (*this)->set_attribute(Attribute::START, name, val);
   } catch (std::exception& e) {
     THROW_ERROR("set_start", e.what());
   }
 }
References e(), name(), and casadi::START.
set_start() [3/3]
void casadi::DaeBuilder::set_start (const std::vector< std::string > & name, const std::vector< double > & val)
Definition at line 1378 of file dae_builder.cpp.
{
   try {
     (*this)->set_attribute(Attribute::START, name, val);
   } catch (std::exception& e) {
     THROW_ERROR("set_start", e.what());
   }
 }
References e(), name(), and casadi::START.
set_start_time()
void casadi::DaeBuilder::set_start_time (double val)
Definition at line 972 of file dae_builder.cpp.
{
   try {
     (*this)->start_time_ = val;
   } catch (std::exception& e) {
     THROW_ERROR("set_start_time", e.what());
   }
 }
References e().
set_step_size()
void casadi::DaeBuilder::set_step_size (double val)
Definition at line 1023 of file dae_builder.cpp.
{
   try {
     (*this)->step_size_ = val;
   } catch (std::exception& e) {
     THROW_ERROR("set_step_size", e.what());
   }
 }
References e().
set_stop_time()
void casadi::DaeBuilder::set_stop_time (double val)
Definition at line 989 of file dae_builder.cpp.
{
   try {
     (*this)->stop_time_ = val;
   } catch (std::exception& e) {
     THROW_ERROR("set_stop_time", e.what());
   }
 }
References e().
set_tolerance()
void casadi::DaeBuilder::set_tolerance (double val)
Definition at line 1006 of file dae_builder.cpp.
{
   try {
     (*this)->tolerance_ = val;
   } catch (std::exception& e) {
     THROW_ERROR("set_tolerance", e.what());
   }
 }
References e().
set_type()
void casadi::DaeBuilder::set_type (const std::string & name, const std::string & val)
Get/set the type
Definition at line 871 of file dae_builder.cpp.
{
   // Fallback to FMI 2, if necessary
   if (has_enum<TypeFmi2>(val) && !has_enum<Type>(val)) {
     (*this)->variable(name).type = from_fmi2(to_enum<TypeFmi2>(val));
   }
   // Assume FMI 3
   (*this)->variable(name).type = to_enum<Type>(val);
 }
References casadi::from_fmi2(), and name().
set_unit()
void casadi::DaeBuilder::set_unit (const std::string & name, const std::string & val)
Get/set the unit
Definition at line 943 of file dae_builder.cpp.
{
   (*this)->variable(name).unit = val;
 }
References name().
set_value_reference()
void casadi::DaeBuilder::set_value_reference (const std::string & name, casadi_int val)
Get/set value reference
Definition at line 848 of file dae_builder.cpp.
{
   (*this)->variable(name).value_reference = val;
 }
References name().
set_variability()
void casadi::DaeBuilder::set_variability (const std::string & name, const std::string & val)
For controls 'u' (variability 'continuous', causality 'input'), free parameters 'p' (variability 'tunable', causality 'parameter') and fixed parameters 'c' (variability 'fixed', causality 'parameter'), update variability in order to change the category. Causality is updated accordingly.
Other changes are not permitted
Extra doc: https://github.com/casadi/casadi/wiki/L_2c3
Definition at line 906 of file dae_builder.cpp.
{
   try {
     (*this)->set_variability((*this)->find(name), to_enum<Variability>(val));
   } catch (std::exception& e) {
     THROW_ERROR("set_variability", e.what());
   }
 }
References e(), and name().
sort()
void casadi::DaeBuilder::sort (const std::string & cat)
Definition at line 828 of file dae_builder.cpp.
{
   try {
     return (*this)->sort(to_enum<Category>(cat));
   } catch (std::exception& e) {
     THROW_ERROR("sort", e.what());
   }
 }
References e().
Referenced by sort_d(), and sort_w().
sort_d()
void casadi::DaeBuilder::sort_d ()
Definition at line 503 of file dae_builder.cpp.
{
   try {
     return sort("d");
   } catch (std::exception& e) {
     THROW_ERROR("sort_d", e.what());
   }
 }
References e(), and sort().
sort_w()
void casadi::DaeBuilder::sort_w ()
Definition at line 511 of file dae_builder.cpp.
{
   try {
     return sort("w");
   } catch (std::exception& e) {
     THROW_ERROR("sort_w", e.what());
   }
 }
References e(), and sort().
sort_z()
void casadi::DaeBuilder::sort_z (const std::vector< std::string > & z_order)
Definition at line 519 of file dae_builder.cpp.
{
   try {
     return reorder("z", z_order);
   } catch (std::exception& e) {
     THROW_ERROR("sort_z", e.what());
   }
 }
References e(), and reorder().
start() [1/2]
std::vector< double > casadi::DaeBuilder::start (const std::string & name) const
Definition at line 1344 of file dae_builder.cpp.
{
   try {
     return (*this)->attribute(Attribute::START, std::vector<std::string>{name});
   } catch (std::exception& e) {
     THROW_ERROR("start", e.what());
     return {}; // never reached
   }
 }
References e(), and casadi::START.
start() [2/2]
std::vector< double > casadi::DaeBuilder::start (const std::vector< std::string > & name) const
Definition at line 1353 of file dae_builder.cpp.
{
   try {
     return (*this)->attribute(Attribute::START, name);
   } catch (std::exception& e) {
     THROW_ERROR("start", e.what());
     return {}; // never reached
   }
 }
References e(), name(), and casadi::START.
start_time()
double casadi::DaeBuilder::start_time () const
Definition at line 963 of file dae_builder.cpp.
{
   try {
     return (*this)->start_time_;
   } catch (std::exception& e) {
     THROW_ERROR("start_time", e.what());
     return nan;
   }
 }
References e(), and casadi::nan.
step_size()
double casadi::DaeBuilder::step_size () const
Definition at line 1014 of file dae_builder.cpp.
{
   try {
     return (*this)->step_size_;
   } catch (std::exception& e) {
     THROW_ERROR("step_size", e.what());
     return nan;
   }
 }
References e(), and casadi::nan.
stop_time()
double casadi::DaeBuilder::stop_time () const
Definition at line 980 of file dae_builder.cpp.
{
   try {
     return (*this)->stop_time_;
   } catch (std::exception& e) {
     THROW_ERROR("stop_time", e.what());
     return nan;
   }
 }
References e(), and casadi::nan.
swap()
void casadi::GenericShared< SharedObject , SharedObjectInternal >::swap (GenericShared< SharedObject, SharedObjectInternal > & other) inherited
Definition at line 106 of file generic_shared_impl.hpp.
{
     GenericShared<Shared, Internal> temp = *this;
     *this = other;
     other = temp;
   }
t()
const MX& casadi::DaeBuilder::t () const inline
Definition at line 300 of file dae_builder.hpp.
 { return time();}
Referenced by time().
t_new()
std::vector<std::string> casadi::DaeBuilder::t_new () const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_2bz
Definition at line 98 of file dae_builder.hpp.
 {return all("t");}
References casadi::all().
tear()
void casadi::DaeBuilder::tear ()
Definition at line 271 of file dae_builder.cpp.
                       {
   try {
     (*this)->tear();
   } catch (std::exception& e) {
     THROW_ERROR("tear", e.what());
   }
 }
References e().
test_cast()
bool casadi::DaeBuilder::test_cast (const SharedObjectInternal * ptr) static
Definition at line 1176 of file dae_builder.cpp.
{
   return dynamic_cast<const DaeBuilderInternal*>(ptr) != nullptr;
 }
time()
const MX & casadi::DaeBuilder::time () const
Extra doc: https://github.com/casadi/casadi/wiki/L_2by
Definition at line 63 of file dae_builder.cpp.
{
   try {
     return (*this)->time();
   } catch (std::exception& e) {
     THROW_ERROR("time", e.what());
     static const MX t;
     return t;  // never reached
   }
 }
References e(), and t().
tolerance()
double casadi::DaeBuilder::tolerance () const
Definition at line 997 of file dae_builder.cpp.
{
   try {
     return (*this)->tolerance_;
   } catch (std::exception& e) {
     THROW_ERROR("tolerance", e.what());
     return nan;
   }
 }
References e(), and casadi::nan.
transition() [1/3]
Function casadi::DaeBuilder::transition () const inline
Definition at line 543 of file dae_builder.hpp.
 {return transition(name() + "_transition");}
References transition().
Referenced by transition().
transition() [2/3]
Function casadi::DaeBuilder::transition (const std::string & fname) const
Definition at line 1167 of file dae_builder.cpp.
{
   try {
     return (*this)->transition(fname);
   } catch (std::exception& e) {
     THROW_ERROR("transition", e.what());
     return Function(); // never reached
   }
 }
References e().
transition() [3/3]
Function casadi::DaeBuilder::transition (const std::string & fname, casadi_int index) const
Definition at line 1158 of file dae_builder.cpp.
{
   try {
     return (*this)->transition(fname, index);
   } catch (std::exception& e) {
     THROW_ERROR("transition", e.what());
     return Function(); // never reached
   }
 }
References e().
type()
std::string casadi::DaeBuilder::type (const std::string & name, casadi_int fmi_version = 3) const
Get/set the type
Definition at line 860 of file dae_builder.cpp.
{
   // Check version
   casadi_assert(fmi_version == 2 || fmi_version == 3, "Only FMI version 2 or 3 supported");
   // Handle FMI 2
   if (fmi_version == 2) {
     return to_string(to_fmi2((*this)->variable(name).type));
   }
   // Assume FMI 3
   return to_string((*this)->variable(name).type);
 }
References name(), casadi::to_fmi2(), and casadi::to_string().
type_name()
std::string casadi::DaeBuilder::type_name () const inline
Definition at line 74 of file dae_builder.hpp.
 {return "DaeBuilder";}
u()
std::vector<std::string> casadi::DaeBuilder::u () const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_5n
Definition at line 146 of file dae_builder.hpp.
 {return all("u");}
References casadi::all().
unit()
std::string casadi::DaeBuilder::unit (const std::string & name) const
Get/set the unit
Definition at line 939 of file dae_builder.cpp.
{
   return (*this)->variable(name).unit;
 }
References name().
value_reference()
casadi_int casadi::DaeBuilder::value_reference (const std::string & name) const
Get/set value reference
Definition at line 844 of file dae_builder.cpp.
{
   return (*this)->variable(name).value_reference;
 }
References name().
var() [1/3]
MX casadi::DaeBuilder::var (const std::string & name) const
Get variable expression by name
Definition at line 725 of file dae_builder.cpp.
{
   try {
     return (*this)->variable(name).v;
   } catch (std::exception& e) {
     THROW_ERROR("var", e.what());
     return MX();  // never reached
   }
 }
References e(), and name().
Referenced by set_beq().
var() [2/3]
std::vector< MX > casadi::DaeBuilder::var (const std::vector< size_t > & ind) const
[DEPRECATED] Use string name, not internal index to access variables
Definition at line 393 of file dae_builder.cpp.
{
   try {
     return (*this)->var(ind);
   } catch (std::exception& e) {
     THROW_ERROR("var", e.what());
     return {}; // never reached
   }
 }
References e().
var() [3/3]
const MX & casadi::DaeBuilder::var (size_t ind) const
[DEPRECATED] Use string name, not internal index to access variables
Definition at line 383 of file dae_builder.cpp.
{
   try {
     return (*this)->var(ind);
   } catch (std::exception& e) {
     THROW_ERROR("var", e.what());
     static MX dummy;
     return dummy; // never reached
   }
 }
References e().
variability()
std::string casadi::DaeBuilder::variability (const std::string & name) const
Definition at line 897 of file dae_builder.cpp.
{
   try {
     return to_string((*this)->variability((*this)->find(name)));
   } catch (std::exception& e) {
     THROW_ERROR("variability", e.what());
     return std::string();  // never reached
   }
 }
References e(), name(), and casadi::to_string().
Referenced by add().
variable() [1/4]
Variable & casadi::DaeBuilder::variable (const std::string & name)
[DEPRECATED] Access to internal class and corresponding indexing removed
Definition at line 315 of file dae_builder.cpp.
{
   try {
     return (*this)->variable(name);
   } catch (std::exception& e) {
     THROW_ERROR("variable", e.what());
   }
 }
References e(), and name().
variable() [2/4]
const Variable & casadi::DaeBuilder::variable (const std::string & name) const
[DEPRECATED] Access to internal class and corresponding indexing removed
Definition at line 323 of file dae_builder.cpp.
{
   try {
     return (*this)->variable(name);
   } catch (std::exception& e) {
     THROW_ERROR("variable", e.what());
   }
 }
References e(), and name().
variable() [3/4]
Variable & casadi::DaeBuilder::variable (size_t ind)
[DEPRECATED] Access to internal class and corresponding indexing removed
Definition at line 331 of file dae_builder.cpp.
{
   try {
     return (*this)->variable(ind);
   } catch (std::exception& e) {
     THROW_ERROR("variable", e.what());
   }
 }
References e().
variable() [4/4]
const Variable & casadi::DaeBuilder::variable (size_t ind) const
[DEPRECATED] Access to internal class and corresponding indexing removed
Definition at line 339 of file dae_builder.cpp.
{
   try {
     return (*this)->variable(ind);
   } catch (std::exception& e) {
     THROW_ERROR("variable", e.what());
   }
 }
References e().
w()
std::vector<std::string> casadi::DaeBuilder::w () const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_5t
Definition at line 178 of file dae_builder.hpp.
 {return all("w");}
References casadi::all().
wdef()
std::vector< MX > casadi::DaeBuilder::wdef () const
Interdependencies are allowed but must be non-cyclic.
Extra doc: https://github.com/casadi/casadi/wiki/L_5u
Definition at line 144 of file dae_builder.cpp.
{
   try {
     return (*this)->output(OutputCategory::WDEF);
   } catch (std::exception& e) {
     THROW_ERROR("wdef", e.what());
     return {};  // never reached
   }
 }
References e(), and casadi::WDEF.
weak()
GenericWeakRef< SharedObject , SharedObjectInternal > * casadi::GenericShared< SharedObject , SharedObjectInternal >::weak inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_aw
Definition at line 131 of file generic_shared_impl.hpp.
{
     return (*this)->weak();
   }
when()
void casadi::DaeBuilder::when (const MX & cond, const std::vector< std::string > & eqs, const Dict & opts = Dict())
Definition at line 683 of file dae_builder.cpp.
{
   try {
     (*this)->when(cond, eqs, opts);
   } catch (std::exception& e) {
     THROW_ERROR("when", e.what());
   }
 }
References e().
x()
std::vector<std::string> casadi::DaeBuilder::x () const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_5f
Definition at line 103 of file dae_builder.hpp.
 {return all("x");}
References casadi::all().
y()
std::vector< std::string > casadi::DaeBuilder::y () const
Definition at line 73 of file dae_builder.cpp.
{
   try {
     return (*this)->name((*this)->outputs_);
   } catch (std::exception& e) {
     THROW_ERROR("y", e.what());
     return {};  // never reached
   }
 }
References e().
ydef()
std::vector< MX > casadi::DaeBuilder::ydef () const
Extra doc: https://github.com/casadi/casadi/wiki/L_5m
Definition at line 117 of file dae_builder.cpp.
{
   try {
     return (*this)->output(OutputCategory::Y);
   } catch (std::exception& e) {
     THROW_ERROR("ydef", e.what());
     return {};  // never reached
   }
 }
References e(), and casadi::Y.
z()
std::vector<std::string> casadi::DaeBuilder::z () const inline
Extra doc: https://github.com/casadi/casadi/wiki/L_5h
Definition at line 116 of file dae_builder.hpp.
 {return all("z");}
References casadi::all().
zero()
std::vector< MX > casadi::DaeBuilder::zero () const
Extra doc: https://github.com/casadi/casadi/wiki/L_2b0
Definition at line 109 of file dae_builder.cpp.
{
   try {
     return (*this)->output(OutputCategory::ZERO);
   } catch (std::exception& e) {
     THROW_ERROR("zero", e.what());
   }
 }
References e(), and casadi::ZERO.
The documentation for this class was generated from the following files:
dae_builder.hpp
dae_builder.cpp