CasADi: casadi::SlicotDpleMemory Struct Reference
casadi::SlicotDpleMemory Struct Reference
#include <slicot_dple.hpp>
Detailed Description
Definition at line 58 of file slicot_dple.hpp.
Public Member Functions
SlicotDpleMemory ()
Constructor.
~SlicotDpleMemory ()
Destructor.
void add_stat (const std::string &s)
Public Attributes
double * VZ
double * T
double * Z
double * X
double * Xbar
double * nnKa
double * nnKb
double * eig_real
double * eig_imag
double * F
double * FF
double * A
double * B
double * dwork
double * wruntime
casadi_int * partition
casadi_int * iwruntime
std::vector< std::vector< Linsol > > dpse_solvers
Solvers for low-order Discrete Periodic Sylvester Equations.
std::map< std::string, FStats > fstats
FStats * t_total
Constructor & Destructor Documentation
SlicotDpleMemory()
casadi::SlicotDpleMemory::SlicotDpleMemory () inline
Definition at line 82 of file slicot_dple.hpp.
 {}
~SlicotDpleMemory()
casadi::SlicotDpleMemory::~SlicotDpleMemory () inline
Definition at line 85 of file slicot_dple.hpp.
 {}
Member Function Documentation
add_stat()
void casadi::ProtoFunctionMemory::add_stat (const std::string & s) inline inherited
Definition at line 74 of file function_internal.hpp.
{
       bool added = fstats.insert(std::make_pair(s, FStats())).second;
       casadi_assert(added, "Duplicate stat: '" + s + "'");
     }
Referenced by casadi::ProtoFunction::init_mem(), casadi::LinsolInternal::init_mem(), casadi::Nlpsol::init_mem(), casadi::OracleFunction::init_mem(), casadi::CbcInterface::init_mem(), casadi::ClpInterface::init_mem(), casadi::FatropConicInterface::init_mem(), casadi::HpipmInterface::init_mem(), casadi::Feasiblesqpmethod::init_mem(), casadi::Sqpmethod::init_mem(), and casadi::OracleFunction::local_init_mem().
Member Data Documentation
A
double * casadi::SlicotDpleMemory::A
Definition at line 74 of file slicot_dple.hpp.
B
double * casadi::SlicotDpleMemory::B
Definition at line 74 of file slicot_dple.hpp.
dpse_solvers
std::vector< std::vector< Linsol> > casadi::SlicotDpleMemory::dpse_solvers
Definition at line 79 of file slicot_dple.hpp.
Referenced by casadi::SlicotDple::init_mem().
dwork
double* casadi::SlicotDpleMemory::dwork
Definition at line 75 of file slicot_dple.hpp.
eig_imag
double * casadi::SlicotDpleMemory::eig_imag
Definition at line 74 of file slicot_dple.hpp.
eig_real
double * casadi::SlicotDpleMemory::eig_real
Definition at line 74 of file slicot_dple.hpp.
F
double * casadi::SlicotDpleMemory::F
Definition at line 74 of file slicot_dple.hpp.
FF
double * casadi::SlicotDpleMemory::FF
Definition at line 74 of file slicot_dple.hpp.
fstats
std::map<std::string, FStats> casadi::ProtoFunctionMemory::fstats inherited
Definition at line 68 of file function_internal.hpp.
Referenced by casadi::Nlpsol::callback(), casadi::IpoptUserClass::eval_h(), casadi::BonminInterface::intermediate_callback(), casadi::IpoptInterface::intermediate_callback(), casadi::OracleFunction::join_results(), casadi::ClarabelInterface::solve(), casadi::DaqpInterface::solve(), casadi::HighsInterface::solve(), casadi::HpipmInterface::solve(), casadi::HpmpcInterface::solve(), casadi::ProxqpInterface::solve(), casadi::QpoasesInterface::solve(), casadi::Sqpmethod::solve_ela_QP(), casadi::Feasiblesqpmethod::solve_LP(), casadi::Feasiblesqpmethod::solve_QP(), and casadi::Sqpmethod::solve_QP().
iwruntime
casadi_int * casadi::SlicotDpleMemory::iwruntime
Definition at line 76 of file slicot_dple.hpp.
nnKa
double * casadi::SlicotDpleMemory::nnKa
Definition at line 74 of file slicot_dple.hpp.
nnKb
double * casadi::SlicotDpleMemory::nnKb
Definition at line 74 of file slicot_dple.hpp.
partition
casadi_int* casadi::SlicotDpleMemory::partition
Definition at line 76 of file slicot_dple.hpp.
T
double * casadi::SlicotDpleMemory::T
Definition at line 74 of file slicot_dple.hpp.
t_total
FStats* casadi::ProtoFunctionMemory::t_total inherited
Definition at line 71 of file function_internal.hpp.
Referenced by casadi::LinsolCall< Tr >::eval(), and casadi::Linsol::solve().
VZ
double* casadi::SlicotDpleMemory::VZ
T Hessenberg-triangular data Z Schur form multiplier data X Schur form multiplier data VZ Transformed V data nnKa Temp data (n x n) x K nnKb Temp data (n x n) x K eig_real Real parts of eigenvalues eig_imag Imaginary parts of eigenvalues Temp data F Temp data FF dwork Work vector for periodic Schur form
Definition at line 74 of file slicot_dple.hpp.
wruntime
double * casadi::SlicotDpleMemory::wruntime
Definition at line 75 of file slicot_dple.hpp.
X
double * casadi::SlicotDpleMemory::X
Definition at line 74 of file slicot_dple.hpp.
Xbar
double * casadi::SlicotDpleMemory::Xbar
Definition at line 74 of file slicot_dple.hpp.
Z
double * casadi::SlicotDpleMemory::Z
Definition at line 74 of file slicot_dple.hpp.
The documentation for this struct was generated from the following file:
slicot_dple.hpp