CasADi: casadi::SlicotExpmMemory Struct Reference
casadi::SlicotExpmMemory Struct Reference
#include <slicot_expm.hpp>
Detailed Description
Definition at line 48 of file slicot_expm.hpp.
Public Member Functions
SlicotExpmMemory ()
Constructor.
~SlicotExpmMemory ()
Destructor.
void add_stat (const std::string &s)
Public Attributes
double * A
double * H
double * dwork
int * iwork
bool stats_available
std::map< std::string, FStats > fstats
FStats * t_total
Constructor & Destructor Documentation
SlicotExpmMemory()
casadi::SlicotExpmMemory::SlicotExpmMemory () inline
Definition at line 55 of file slicot_expm.hpp.
 {}
~SlicotExpmMemory()
casadi::SlicotExpmMemory::~SlicotExpmMemory () inline
Definition at line 58 of file slicot_expm.hpp.
 {}
Member Function Documentation
add_stat()
void casadi::ProtoFunctionMemory::add_stat (const std::string & s) inline inherited
Definition at line 74 of file function_internal.hpp.
{
       bool added = fstats.insert(std::make_pair(s, FStats())).second;
       casadi_assert(added, "Duplicate stat: '" + s + "'");
     }
Referenced by casadi::ProtoFunction::init_mem(), casadi::LinsolInternal::init_mem(), casadi::Nlpsol::init_mem(), casadi::OracleFunction::init_mem(), casadi::CbcInterface::init_mem(), casadi::ClpInterface::init_mem(), casadi::FatropConicInterface::init_mem(), casadi::HpipmInterface::init_mem(), casadi::Feasiblesqpmethod::init_mem(), casadi::Sqpmethod::init_mem(), and casadi::OracleFunction::local_init_mem().
Member Data Documentation
A
double* casadi::SlicotExpmMemory::A
Definition at line 50 of file slicot_expm.hpp.
dwork
double* casadi::SlicotExpmMemory::dwork
Definition at line 51 of file slicot_expm.hpp.
fstats
std::map<std::string, FStats> casadi::ProtoFunctionMemory::fstats inherited
Definition at line 68 of file function_internal.hpp.
Referenced by casadi::Nlpsol::callback(), casadi::IpoptUserClass::eval_h(), casadi::BonminInterface::intermediate_callback(), casadi::IpoptInterface::intermediate_callback(), casadi::OracleFunction::join_results(), casadi::ClarabelInterface::solve(), casadi::DaqpInterface::solve(), casadi::HighsInterface::solve(), casadi::HpipmInterface::solve(), casadi::HpmpcInterface::solve(), casadi::ProxqpInterface::solve(), casadi::QpoasesInterface::solve(), casadi::Sqpmethod::solve_ela_QP(), casadi::Feasiblesqpmethod::solve_LP(), casadi::Feasiblesqpmethod::solve_QP(), and casadi::Sqpmethod::solve_QP().
H
double * casadi::SlicotExpmMemory::H
Definition at line 50 of file slicot_expm.hpp.
iwork
int* casadi::SlicotExpmMemory::iwork
Definition at line 52 of file slicot_expm.hpp.
stats_available
bool casadi::FunctionMemory::stats_available inherited
Definition at line 84 of file function_internal.hpp.
Referenced by casadi::FunctionInternal::eval_gen(), and casadi::FunctionInternal::setup().
t_total
FStats* casadi::ProtoFunctionMemory::t_total inherited
Definition at line 71 of file function_internal.hpp.
Referenced by casadi::LinsolCall< Tr >::eval(), and casadi::Linsol::solve().
The documentation for this struct was generated from the following file:
slicot_expm.hpp