CasADi: casadi::GenericTypeInternal< ID, T > Class Template Reference
casadi::GenericTypeInternal< ID, T > Class Template Reference
#include <generic_type_internal.hpp>
Detailed Description
template<TypeID ID, typename T>
class casadi::GenericTypeInternal< ID, T >
Definition at line 46 of file generic_type_internal.hpp.
Public Types
using weak_ref_type = WeakRefInternal
Public Member Functions
GenericTypeInternal (const T &d)
~GenericTypeInternal () override
std::string class_name () const override
Readable name of the internal class.
void disp (std::ostream &stream, bool more) const override
Print a description of the object.
TypeID getType () const override
void serialize (SerializingStream &s) const override
casadi_int getCount () const
Get the reference count.
std::string debug_repr (const SharedObjectInternal *) const
GenericWeakRef< SharedObject, SharedObjectInternal > * weak ()
Get a weak reference to the object.
Static Public Member Functions
static GenericType deserialize (DeserializingStream &s)
Public Attributes
T d_
Protected Member Functions
void initSingleton ()
void destroySingleton ()
B shared_from_this ()
Get a shared object from the current internal object.
const B shared_from_this () const
Get a shared object from the current internal object.
Member Typedef Documentation
weak_ref_type
using casadi::SharedObjectInternal::weak_ref_type = WeakRefInternal inherited
Definition at line 152 of file shared_object.hpp.
Constructor & Destructor Documentation
GenericTypeInternal()
template<TypeID ID, typename T > casadi::GenericTypeInternal< ID, T >::GenericTypeInternal (const T & d) inline explicit
Definition at line 48 of file generic_type_internal.hpp.
 : d_(d) {}
~GenericTypeInternal()
template<TypeID ID, typename T > casadi::GenericTypeInternal< ID, T >::~GenericTypeInternal () inline override
Definition at line 49 of file generic_type_internal.hpp.
 {}
Member Function Documentation
class_name()
template<TypeID ID, typename T > std::string casadi::GenericTypeInternal< ID, T >::class_name () const inline override virtual
Implements casadi::SharedObjectInternal.
Definition at line 50 of file generic_type_internal.hpp.
 {return "GenericTypeInternal";}
debug_repr()
std::string casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::debug_repr (const Internal * i) const inherited
Definition at line 62 of file generic_shared_internal.hpp.
{
     // Note: i != this because of something something multiple inheritance
     return str( (casadi_int)(i)) + "/" + static_cast<const Internal*>(this)->class_name();
   }
deserialize()
template<TypeID ID, typename T > static GenericType casadi::GenericTypeInternal< ID, T >::deserialize (DeserializingStream & s) inline static
Definition at line 57 of file generic_type_internal.hpp.
{
       T d;
       s.unpack("GenericType::d", d);
       return GenericType(d);
     }
References casadi::T, and casadi::DeserializingStream::unpack().
Referenced by casadi::GenericType::deserialize().
destroySingleton()
void casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::destroySingleton () inline protected inherited
Called in the destructor of singletons
Definition at line 77 of file generic_shared_internal.hpp.
{
       static_cast<Internal*>(this)->count--;
     }
disp()
template<TypeID ID, typename T > void casadi::GenericTypeInternal< ID, T >::disp (std::ostream & stream, bool more) const inline override virtual
Implements casadi::SharedObjectInternal.
Definition at line 51 of file generic_type_internal.hpp.
 { stream << d_; }
getCount()
casadi_int casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::getCount inherited
Definition at line 60 of file generic_shared_internal.hpp.
{
     return static_cast<const Internal*>(this)->count;
   }
getType()
template<TypeID ID, typename T > TypeID casadi::GenericTypeInternal< ID, T >::getType () const inline override virtual
Implements casadi::GenericTypeBase.
Definition at line 52 of file generic_type_internal.hpp.
 { return ID;}
initSingleton()
void casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::initSingleton () inline protected inherited
Called in the constructor of singletons to avoid that the counter reaches zero
Definition at line 71 of file generic_shared_internal.hpp.
{
       casadi_assert_dev(static_cast<Internal*>(this)->count==0);
       static_cast<Internal*>(this)->count++;
     }
serialize()
template<TypeID ID, typename T > void casadi::GenericTypeInternal< ID, T >::serialize (SerializingStream & s) const inline override virtual
Implements casadi::GenericTypeBase.
Definition at line 54 of file generic_type_internal.hpp.
{
       s.pack("GenericType::d", d_);
     }
References casadi::SerializingStream::pack().
shared_from_this() [1/2]
B casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::shared_from_this () inline protected inherited
Definition at line 83 of file generic_shared_internal.hpp.
{
       casadi_assert_dev(B::test_cast(static_cast<Internal*>(this)));
       B ret;
       ret.own(static_cast<Internal*>(this));
       return ret;
     }
shared_from_this() [2/2]
const B casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::shared_from_this () const inline protected inherited
Definition at line 92 of file generic_shared_internal.hpp.
{
       casadi_assert_dev(B::test_cast(static_cast<const Internal*>(this)));
       B ret;
       ret.own(const_cast<Internal*>(static_cast<const Internal*>(this)));
       return ret;
     }
weak()
GenericWeakRef< SharedObject , SharedObjectInternal > * casadi::GenericSharedInternal< SharedObject , SharedObjectInternal >::weak inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1ai
Definition at line 67 of file generic_shared_internal.hpp.
{
     if (weak_ref_==nullptr) {
       weak_ref_ = new GenericWeakRef<Shared, Internal>(static_cast<Internal*>(this));
     }
     return weak_ref_;
   }
Member Data Documentation
d_
template<TypeID ID, typename T > T casadi::GenericTypeInternal< ID, T >::d_
Definition at line 53 of file generic_type_internal.hpp.
The documentation for this class was generated from the following file:
generic_type_internal.hpp