CasADi: casadi::MumpsMemory Struct Reference
casadi::MumpsMemory Struct Reference
#include <mumps_interface.hpp>
Detailed Description
Definition at line 48 of file mumps_interface.hpp.
Public Member Functions
MumpsMemory ()
~MumpsMemory ()
void add_stat (const std::string &s)
Public Attributes
DMUMPS_STRUC_C * id
std::vector< int > irn
std::vector< int > jcn
std::vector< double > nz
bool is_sfact
bool is_nfact
std::map< std::string, FStats > fstats
FStats * t_total
Constructor & Destructor Documentation
MumpsMemory()
casadi::MumpsMemory::MumpsMemory ()
Definition at line 190 of file mumps_interface.cpp.
{
     this->id = 0;
   }
~MumpsMemory()
casadi::MumpsMemory::~MumpsMemory ()
Definition at line 194 of file mumps_interface.cpp.
{
     if (this->id) {
       // Terminate the instance of the package
       this->id->job = -2;
       dmumps_c(this->id);
       // Delete the structure
       delete this->id;
     }
   }
References id.
Member Function Documentation
add_stat()
void casadi::ProtoFunctionMemory::add_stat (const std::string & s) inline inherited
Definition at line 74 of file function_internal.hpp.
{
       bool added = fstats.insert(std::make_pair(s, FStats())).second;
       casadi_assert(added, "Duplicate stat: '" + s + "'");
     }
Referenced by casadi::ProtoFunction::init_mem(), casadi::LinsolInternal::init_mem(), casadi::Nlpsol::init_mem(), casadi::OracleFunction::init_mem(), casadi::CbcInterface::init_mem(), casadi::ClpInterface::init_mem(), casadi::FatropConicInterface::init_mem(), casadi::HpipmInterface::init_mem(), casadi::Feasiblesqpmethod::init_mem(), casadi::Sqpmethod::init_mem(), and casadi::OracleFunction::local_init_mem().
Member Data Documentation
fstats
std::map<std::string, FStats> casadi::ProtoFunctionMemory::fstats inherited
Definition at line 68 of file function_internal.hpp.
Referenced by casadi::Nlpsol::callback(), casadi::IpoptUserClass::eval_h(), casadi::BonminInterface::intermediate_callback(), casadi::IpoptInterface::intermediate_callback(), casadi::OracleFunction::join_results(), casadi::DaqpInterface::solve(), casadi::HighsInterface::solve(), casadi::HpipmInterface::solve(), casadi::HpmpcInterface::solve(), casadi::ProxqpInterface::solve(), casadi::QpoasesInterface::solve(), casadi::Sqpmethod::solve_ela_QP(), casadi::Feasiblesqpmethod::solve_LP(), casadi::Feasiblesqpmethod::solve_QP(), and casadi::Sqpmethod::solve_QP().
id
DMUMPS_STRUC_C* casadi::MumpsMemory::id
Definition at line 56 of file mumps_interface.hpp.
Referenced by casadi::MumpsInterface::init_mem(), casadi::MumpsInterface::solve(), and ~MumpsMemory().
irn
std::vector<int> casadi::MumpsMemory::irn
Definition at line 59 of file mumps_interface.hpp.
is_nfact
bool casadi::LinsolMemory::is_nfact inherited
Definition at line 39 of file linsol_internal.hpp.
Referenced by casadi::Linsol::nfact().
is_sfact
bool casadi::LinsolMemory::is_sfact inherited
Definition at line 39 of file linsol_internal.hpp.
Referenced by casadi::Linsol::sfact().
jcn
std::vector<int> casadi::MumpsMemory::jcn
Definition at line 59 of file mumps_interface.hpp.
nz
std::vector<double> casadi::MumpsMemory::nz
Definition at line 62 of file mumps_interface.hpp.
t_total
FStats* casadi::ProtoFunctionMemory::t_total inherited
Definition at line 71 of file function_internal.hpp.
Referenced by casadi::LinsolCall< Tr >::eval(), and casadi::Linsol::solve().
The documentation for this struct was generated from the following files:
mumps_interface.hpp
mumps_interface.cpp