CasADi: casadi::ProtoFunctionMemory Struct Reference
casadi::ProtoFunctionMemory Struct Reference
Function memory with temporary work vectors.
#include <function_internal.hpp>
Detailed Description
Extra doc: https://github.com/casadi/casadi/wiki/L_ja
Definition at line 66 of file function_internal.hpp.
Public Member Functions
void add_stat (const std::string &s)
Public Attributes
std::map< std::string, FStats > fstats
FStats * t_total
Member Function Documentation
add_stat()
void casadi::ProtoFunctionMemory::add_stat (const std::string & s) inline
Definition at line 74 of file function_internal.hpp.
{
       bool added = fstats.insert(std::make_pair(s, FStats())).second;
       casadi_assert(added, "Duplicate stat: '" + s + "'");
     }
Referenced by casadi::ProtoFunction::init_mem(), casadi::LinsolInternal::init_mem(), casadi::Nlpsol::init_mem(), casadi::OracleFunction::init_mem(), casadi::CbcInterface::init_mem(), casadi::ClpInterface::init_mem(), casadi::FatropConicInterface::init_mem(), casadi::HpipmInterface::init_mem(), casadi::Feasiblesqpmethod::init_mem(), casadi::Sqpmethod::init_mem(), and casadi::OracleFunction::local_init_mem().
Member Data Documentation
fstats
std::map<std::string, FStats> casadi::ProtoFunctionMemory::fstats
Definition at line 68 of file function_internal.hpp.
Referenced by casadi::Nlpsol::callback(), casadi::IpoptUserClass::eval_h(), casadi::BonminInterface::intermediate_callback(), casadi::IpoptInterface::intermediate_callback(), casadi::OracleFunction::join_results(), casadi::ClarabelInterface::solve(), casadi::DaqpInterface::solve(), casadi::HighsInterface::solve(), casadi::HpipmInterface::solve(), casadi::HpmpcInterface::solve(), casadi::ProxqpInterface::solve(), casadi::QpoasesInterface::solve(), casadi::Sqpmethod::solve_ela_QP(), casadi::Feasiblesqpmethod::solve_LP(), casadi::Feasiblesqpmethod::solve_QP(), and casadi::Sqpmethod::solve_QP().
t_total
FStats* casadi::ProtoFunctionMemory::t_total
Definition at line 71 of file function_internal.hpp.
Referenced by casadi::LinsolCall< Tr >::eval(), and casadi::Linsol::solve().
The documentation for this struct was generated from the following file:
function_internal.hpp