CasADi: casadi::SXNode Class Reference
casadi::SXNode Class Reference abstract
Internal node class for SX.
#include <sx_node.hpp>
Detailed Description
Author
Joel Andersson
Date
2010
Extra doc: https://github.com/casadi/casadi/wiki/L_9t
Definition at line 49 of file sx_node.hpp.
Public Member Functions
SXNode ()
constructor
virtual ~SXNode ()
destructor
virtual const std::string & name () const
virtual std::string class_name () const =0
Get type name.
virtual casadi_int op () const =0
get the operation
virtual bool is_equal (const SXNode *node, casadi_int depth) const
Check if two nodes are equivalent up to a given depth.
virtual casadi_int n_dep () const
Number of dependencies.
virtual const SXElem & dep (casadi_int i) const
get the reference of a child
virtual SXElem & dep (casadi_int i)
get the reference of a child
virtual bool is_smooth () const
Check if smooth.
virtual void disp (std::ostream &stream, bool more) const
print
void can_inline (std::map< const SXNode *, casadi_int > &nodeind) const
Find out which nodes can be inlined.
std::string print_compact (std::map< const SXNode *, casadi_int > &nodeind, std::vector< std::string > &intermed) const
Print compact.
virtual std::string print (const std::string &arg1, const std::string &arg2) const =0
Print expression.
bool marked () const
void mark () const
void serialize (SerializingStream &s) const
Serialize an object.
virtual void serialize_node (SerializingStream &s) const
virtual bool is_constant () const
check properties of a node
virtual bool is_integer () const
check properties of a node
virtual bool is_symbolic () const
check properties of a node
virtual bool is_zero () const
check properties of a node
virtual bool is_op (casadi_int op) const
check properties of a node
virtual bool is_almost_zero (double tol) const
check properties of a node
virtual bool is_one () const
check properties of a node
virtual bool is_minus_one () const
check properties of a node
virtual bool is_nan () const
check properties of a node
virtual bool is_inf () const
check properties of a node
virtual bool is_minus_inf () const
check properties of a node
virtual double to_double () const
Get value of a constant node.
virtual casadi_int to_int () const
Get value of a constant node.
Static Public Member Functions
static void safe_delete (SXNode *n)
Non-recursive delete.
static SXNode * deserialize (DeserializingStream &s)
Public Attributes
int temp
unsigned int count
Static Public Attributes
static casadi_int eq_depth_ = 1
static std::map< casadi_int, SXNode *(*)(DeserializingStream &)> deserialize_map
Friends
class SXElem
class Matrix< SXElem >
class UniversalNodeOwner
Constructor & Destructor Documentation
SXNode()
casadi::SXNode::SXNode ()
Extra doc: https://github.com/casadi/casadi/wiki/L_9u
Definition at line 38 of file sx_node.cpp.
                  {
     count = 0;
     temp = 0;
   }
References count, and temp.
~SXNode()
casadi::SXNode::~SXNode () virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_9v
Definition at line 43 of file sx_node.cpp.
                   {
     #ifdef WITH_REFCOUNT_WARNINGS
     // Make sure that this is there are no scalar expressions pointing to it when it is destroyed
     if (count!=0) {
       // Note that casadi_assert_warning cannot be used in destructors
       std::cerr << "Reference counting failure." <<
                    "Possible cause: Circular dependency in user code." << std::endl;
     }
     #endif // WITH_REFCOUNT_WARNINGS
   }
References count.
Member Function Documentation
can_inline()
void casadi::SXNode::can_inline (std::map< const SXNode *, casadi_int > & nodeind) const
Extra doc: https://github.com/casadi/casadi/wiki/L_a6
Definition at line 103 of file sx_node.cpp.
{
     // Add or mark node in map
     std::map<const SXNode*, casadi_int>::iterator it=nodeind.find(this);
     if (it==nodeind.end()) {
       // First time encountered, mark inlined
       nodeind.insert(it, std::make_pair(this, 0));
       // Handle dependencies with recursion
       for (casadi_int i=0; i<n_dep(); ++i) {
         dep(i)->can_inline(nodeind);
       }
     } else if (it->second==0 && op()!=OP_PARAMETER) {
       // Node encountered before, do not inline (except if symbolic primitive)
       it->second = -1;
     }
   }
References can_inline(), dep(), n_dep(), op(), and casadi::OP_PARAMETER.
Referenced by can_inline(), and disp().
class_name()
virtual std::string casadi::SXNode::class_name () const pure virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_9y
Implemented in casadi::UnarySX, casadi::SymbolicSX, casadi::ConstantSX, and casadi::BinarySX.
Referenced by dep(), name(), serialize_node(), and to_int().
dep() [1/2]
SXElem & casadi::SXNode::dep (casadi_int i) virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_a3
Reimplemented in casadi::UnarySX, and casadi::BinarySX.
Definition at line 74 of file sx_node.cpp.
{
     casadi_error("'dep' not defined for " + class_name());
   }
References class_name().
dep() [2/2]
const SXElem & casadi::SXNode::dep (casadi_int i) const virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_a2
Reimplemented in casadi::UnarySX, and casadi::BinarySX.
Definition at line 70 of file sx_node.cpp.
{
     casadi_error("'dep' not defined for " + class_name());
   }
References class_name().
Referenced by casadi::SXFunction::ad_forward(), casadi::SXFunction::ad_reverse(), casadi::SXElem::binary(), can_inline(), casadi::SXElem::dep(), casadi::LinsolCall< Tr >::eval_sx(), casadi::SXFunction::init(), print_compact(), and safe_delete().
deserialize()
SXNode * casadi::SXNode::deserialize (DeserializingStream & s) static
Definition at line 209 of file sx_node.cpp.
{
     casadi_int op;
     s.unpack("SXNode::op", op);
     if (casadi_math<MX>::is_binary(op)) {
       return BinarySX::deserialize(s, op);
     } else if (casadi_math<MX>::is_unary(op)) {
       return UnarySX::deserialize(s, op);
     }
     auto it = SXNode::deserialize_map.find(op);
     if (it==SXNode::deserialize_map.end()) {
       casadi_error("Not implemented op " + str(casadi_int(op)));
     } else {
       return it->second(s);
     }
   }
References casadi::BinarySX::deserialize(), casadi::UnarySX::deserialize(), deserialize_map, op(), casadi::str(), and casadi::DeserializingStream::unpack().
Referenced by casadi::SXElem::deserialize().
disp()
void casadi::SXNode::disp (std::ostream & stream, bool more) const virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_a5
Definition at line 78 of file sx_node.cpp.
{
     // Find out which noded can be inlined
     std::map<const SXNode*, casadi_int> nodeind;
     can_inline(nodeind);
     // Print expression
     std::vector<std::string> intermed;
     std::string s = print_compact(nodeind, intermed);
     // Print intermediate expressions
     for (casadi_int i=0; i<intermed.size(); ++i)
       stream << "@" << (i+1) << "=" << intermed[i] << ", ";
     // Print this
     stream << s;
   }
References can_inline(), and print_compact().
Referenced by casadi::SXElem::disp().
is_almost_zero()
virtual bool casadi::SXNode::is_almost_zero (double tol) const inline virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::ZeroSX, and casadi::RealtypeSX.
Definition at line 74 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::is_almost_zero().
is_constant()
virtual bool casadi::SXNode::is_constant () const inline virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::ConstantSX.
Definition at line 69 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::binary(), casadi::SXFunction::init(), and casadi::SXElem::is_constant().
is_equal()
bool casadi::SXNode::is_equal (const SXNode * node, casadi_int depth) const virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_a0
Reimplemented in casadi::UnarySX, casadi::ConstantSX, and casadi::BinarySX.
Definition at line 62 of file sx_node.cpp.
{
     return false;
   }
Referenced by casadi::SXElem::is_equal().
is_inf()
virtual bool casadi::SXNode::is_inf () const inline virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::InfSX.
Definition at line 78 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::is_inf().
is_integer()
virtual bool casadi::SXNode::is_integer () const inline virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::MinusOneSX, casadi::OneSX, casadi::ZeroSX, and casadi::IntegerSX.
Definition at line 70 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::binary(), and casadi::SXElem::is_integer().
is_minus_inf()
virtual bool casadi::SXNode::is_minus_inf () const inline virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::MinusInfSX.
Definition at line 79 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::is_minus_inf().
is_minus_one()
virtual bool casadi::SXNode::is_minus_one () const inline virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::MinusOneSX.
Definition at line 76 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::binary(), and casadi::SXElem::is_minus_one().
is_nan()
virtual bool casadi::SXNode::is_nan () const inline virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::NanSX.
Definition at line 77 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::is_nan().
is_one()
virtual bool casadi::SXNode::is_one () const inline virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::OneSX.
Definition at line 75 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::binary(), and casadi::SXElem::is_one().
is_op()
virtual bool casadi::SXNode::is_op (casadi_int op) const inline virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::UnarySX, casadi::SymbolicSX, and casadi::BinarySX.
Definition at line 73 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::is_op().
is_smooth()
virtual bool casadi::SXNode::is_smooth () const inline virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_a4
Reimplemented in casadi::UnarySX, and casadi::BinarySX.
Definition at line 126 of file sx_node.hpp.
 { return true; }
is_symbolic()
virtual bool casadi::SXNode::is_symbolic () const inline virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::SymbolicSX.
Definition at line 71 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXFunction::init(), and casadi::SXElem::is_symbolic().
is_zero()
virtual bool casadi::SXNode::is_zero () const inline virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::ZeroSX.
Definition at line 72 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::binary(), and casadi::SXElem::is_zero().
mark()
void casadi::SXNode::mark () const
Definition at line 99 of file sx_node.cpp.
{
     temp = -temp-1;
   }
References temp.
marked()
bool casadi::SXNode::marked () const
Definition at line 95 of file sx_node.cpp.
{
     return temp<0;
   }
References temp.
n_dep()
virtual casadi_int casadi::SXNode::n_dep () const inline virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_a1
Reimplemented in casadi::UnarySX, and casadi::BinarySX.
Definition at line 111 of file sx_node.hpp.
 { return 0;}
Referenced by can_inline(), casadi::SXElem::n_dep(), print_compact(), and safe_delete().
name()
const std::string & casadi::SXNode::name () const virtual
Reimplemented in casadi::SymbolicSX.
Definition at line 66 of file sx_node.cpp.
{
     casadi_error("'name' not defined for " + class_name());
   }
References class_name().
Referenced by casadi::SXElem::name().
op()
virtual casadi_int casadi::SXNode::op () const pure virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_9z
Implemented in casadi::UnarySX, casadi::SymbolicSX, casadi::ConstantSX, and casadi::BinarySX.
Referenced by can_inline(), deserialize(), casadi::SXFunction::init(), casadi::SXElem::op(), and serialize().
print()
virtual std::string casadi::SXNode::print (const std::string & arg1, const std::string & arg2) const pure virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_a8
Implemented in casadi::UnarySX, casadi::SymbolicSX, casadi::ConstantSX, and casadi::BinarySX.
Referenced by print_compact().
print_compact()
std::string casadi::SXNode::print_compact (std::map< const SXNode *, casadi_int > & nodeind, std::vector< std::string > & intermed) const
Extra doc: https://github.com/casadi/casadi/wiki/L_a7
Definition at line 120 of file sx_node.cpp.
{
     // Get reference to node index
     casadi_int& ind = nodeind[this];
     // If positive, already in intermediate expressions
     if (ind>0) {
       std::stringstream ss;
       ss << "@" << ind;
       return ss.str();
     }
     // Get expressions for dependencies
     std::string arg[2];
     for (casadi_int i=0; i<n_dep(); ++i) {
       arg[i] = dep(i)->print_compact(nodeind, intermed);
     }
     // Get expression for this
     std::string s = print(arg[0], arg[1]);
     // Decide what to do with the expression
     if (ind==0) {
       // Inline expression
       return s;
     } else {
       // Add to list of intermediate expressions and return reference
       intermed.push_back(s);
       ind = intermed.size(); // For subsequent references
       std::stringstream ss;
       ss << "@" << ind;
       return ss.str();
     }
   }
References dep(), n_dep(), print(), and print_compact().
Referenced by disp(), and print_compact().
safe_delete()
void casadi::SXNode::safe_delete (SXNode * n) static
Extra doc: https://github.com/casadi/casadi/wiki/L_a9
Definition at line 155 of file sx_node.cpp.
{
     // Quick return if more owners
     if (n->count>0) return;
     // Delete straight away if it doesn't have any dependencies
     if (!n->n_dep()) {
       delete n;
       return;
     }
     // Stack of expressions to be deleted
     std::stack<SXNode*> deletion_stack;
     // Add the node to the deletion stack
     deletion_stack.push(n);
     // Process stack
     while (!deletion_stack.empty()) {
       // Top element
       SXNode *t = deletion_stack.top();
       // Check if the top element has dependencies with dependencies
       bool added_to_stack = false;
       for (casadi_int c2=0; c2<t->n_dep(); ++c2) { // for all dependencies of the dependency
         // Get the node of the dependency of the top element
         // and remove it from the smart pointer
         SXNode *n2 = t->dep(c2).assignNoDelete(casadi_limits<SXElem>::nan);
         // Check if this is the only reference to the element
         if (n2->count == 0) {
           // Check if unary or binary
           if (!n2->n_dep()) {
             // Delete straight away if not binary
             delete n2;
           } else {
             // Add to deletion stack
             deletion_stack.push(n2);
             added_to_stack = true;
           }
         }
       }
       // Delete and pop from stack if nothing added to the stack
       if (!added_to_stack) {
         delete deletion_stack.top();
         deletion_stack.pop();
       }
     }
   }
References casadi::SXElem::assignNoDelete(), count, dep(), and n_dep().
Referenced by casadi::BinarySX::~BinarySX(), and casadi::UnarySX::~UnarySX().
serialize()
void casadi::SXNode::serialize (SerializingStream & s) const
Extra doc: https://github.com/casadi/casadi/wiki/L_aa
Definition at line 204 of file sx_node.cpp.
{
     s.pack("SXNode::op", op());
     serialize_node(s);
   }
References op(), casadi::SerializingStream::pack(), and serialize_node().
serialize_node()
void casadi::SXNode::serialize_node (SerializingStream & s) const virtual
Reimplemented in casadi::UnarySX, casadi::SymbolicSX, casadi::NanSX, casadi::MinusInfSX, casadi::InfSX, casadi::MinusOneSX, casadi::OneSX, casadi::ZeroSX, casadi::IntegerSX, casadi::RealtypeSX, and casadi::BinarySX.
Definition at line 200 of file sx_node.cpp.
{
     casadi_error("'serialize_node' not defined for class " + class_name());
   }
References class_name().
Referenced by serialize().
to_double()
double casadi::SXNode::to_double () const virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_9x
Reimplemented in casadi::ConstantSX, casadi::NanSX, casadi::MinusInfSX, casadi::InfSX, casadi::MinusOneSX, casadi::OneSX, casadi::ZeroSX, casadi::IntegerSX, and casadi::RealtypeSX.
Definition at line 54 of file sx_node.cpp.
{
     return std::numeric_limits<double>::quiet_NaN();
   }
Referenced by casadi::SXElem::binary(), and casadi::SXFunction::init().
to_int()
casadi_int casadi::SXNode::to_int () const virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_9x
Reimplemented in casadi::MinusOneSX, casadi::OneSX, casadi::ZeroSX, casadi::IntegerSX, and casadi::RealtypeSX.
Definition at line 58 of file sx_node.cpp.
{
     casadi_error("to_int not defined for " + class_name());
   }
References class_name().
Referenced by casadi::SXElem::binary().
Friends And Related Function Documentation
Matrix< SXElem >
friend class Matrix< SXElem > friend
Definition at line 50 of file sx_node.hpp.
SXElem
friend class SXElem friend
Definition at line 50 of file sx_node.hpp.
UniversalNodeOwner
friend class UniversalNodeOwner friend
Definition at line 52 of file sx_node.hpp.
Member Data Documentation
count
unsigned int casadi::SXNode::count
Definition at line 170 of file sx_node.hpp.
Referenced by casadi::SXElem::assignNoDelete(), casadi::SXElem::operator=(), safe_delete(), casadi::SXElem::SXElem(), SXNode(), casadi::UniversalNodeOwner::UniversalNodeOwner(), casadi::InfSX::~InfSX(), casadi::MinusInfSX::~MinusInfSX(), casadi::MinusOneSX::~MinusOneSX(), casadi::NanSX::~NanSX(), casadi::OneSX::~OneSX(), casadi::SXElem::~SXElem(), ~SXNode(), and casadi::ZeroSX::~ZeroSX().
deserialize_map
std::map< casadi_int, SXNode *(*)(DeserializingStream &)> casadi::SXNode::deserialize_map static
Initial value:
= {
    {OP_PARAMETER, SymbolicSX::deserialize},
    {OP_CONST, ConstantSX_deserialize}}
Definition at line 181 of file sx_node.hpp.
Referenced by deserialize().
eq_depth_
casadi_int casadi::SXNode::eq_depth_ = 1 static
Definition at line 161 of file sx_node.hpp.
Referenced by casadi::SXElem::binary(), casadi::Matrix< Scalar >::get_max_depth(), casadi::SXElem::is_doubled(), and casadi::Matrix< Scalar >::set_max_depth().
temp
int casadi::SXNode::temp mutable
Temporary variables to be used in user algorithms like sorting, the user is responsible of making sure that use is thread-safe The variable is initialized to zero
Definition at line 167 of file sx_node.hpp.
Referenced by casadi::SXFunction::init(), mark(), marked(), and SXNode().
The documentation for this class was generated from the following files:
sx_node.hpp
sx_node.cpp