CasADi: casadi::CsparseCholMemory Struct Reference
casadi::CsparseCholMemory Struct Reference
#include <csparse_cholesky_interface.hpp>
Detailed Description
Definition at line 45 of file csparse_cholesky_interface.hpp.
Public Member Functions
~CsparseCholMemory ()
void add_stat (const std::string &s)
Public Attributes
cs A
css * S
csn * L
std::vector< double > temp
std::vector< int > colind
std::vector< int > row
bool is_sfact
bool is_nfact
std::map< std::string, FStats > fstats
FStats * t_total
Constructor & Destructor Documentation
~CsparseCholMemory()
casadi::CsparseCholMemory::~CsparseCholMemory ()
Member Function Documentation
add_stat()
void casadi::ProtoFunctionMemory::add_stat (const std::string & s) inline inherited
Definition at line 74 of file function_internal.hpp.
{
       bool added = fstats.insert(std::make_pair(s, FStats())).second;
       casadi_assert(added, "Duplicate stat: '" + s + "'");
     }
Referenced by casadi::ProtoFunction::init_mem(), casadi::LinsolInternal::init_mem(), casadi::Nlpsol::init_mem(), casadi::OracleFunction::init_mem(), casadi::CbcInterface::init_mem(), casadi::ClpInterface::init_mem(), casadi::FatropConicInterface::init_mem(), casadi::HpipmInterface::init_mem(), casadi::Feasiblesqpmethod::init_mem(), casadi::Sqpmethod::init_mem(), and casadi::OracleFunction::local_init_mem().
Member Data Documentation
A
cs casadi::CsparseCholMemory::A
Definition at line 50 of file csparse_cholesky_interface.hpp.
colind
std::vector<int> casadi::CsparseCholMemory::colind
Definition at line 61 of file csparse_cholesky_interface.hpp.
fstats
std::map<std::string, FStats> casadi::ProtoFunctionMemory::fstats inherited
Definition at line 68 of file function_internal.hpp.
Referenced by casadi::Nlpsol::callback(), casadi::IpoptUserClass::eval_h(), casadi::BonminInterface::intermediate_callback(), casadi::IpoptInterface::intermediate_callback(), casadi::OracleFunction::join_results(), casadi::DaqpInterface::solve(), casadi::HighsInterface::solve(), casadi::HpipmInterface::solve(), casadi::HpmpcInterface::solve(), casadi::ProxqpInterface::solve(), casadi::QpoasesInterface::solve(), casadi::Sqpmethod::solve_ela_QP(), casadi::Feasiblesqpmethod::solve_LP(), casadi::Feasiblesqpmethod::solve_QP(), and casadi::Sqpmethod::solve_QP().
is_nfact
bool casadi::LinsolMemory::is_nfact inherited
Definition at line 39 of file linsol_internal.hpp.
Referenced by casadi::Linsol::nfact().
is_sfact
bool casadi::LinsolMemory::is_sfact inherited
Definition at line 39 of file linsol_internal.hpp.
Referenced by casadi::Linsol::sfact().
L
csn* casadi::CsparseCholMemory::L
Definition at line 56 of file csparse_cholesky_interface.hpp.
row
std::vector<int> casadi::CsparseCholMemory::row
Definition at line 62 of file csparse_cholesky_interface.hpp.
S
css* casadi::CsparseCholMemory::S
Definition at line 53 of file csparse_cholesky_interface.hpp.
t_total
FStats* casadi::ProtoFunctionMemory::t_total inherited
Definition at line 71 of file function_internal.hpp.
Referenced by casadi::LinsolCall< Tr >::eval(), and casadi::Linsol::solve().
temp
std::vector<double> casadi::CsparseCholMemory::temp
Definition at line 59 of file csparse_cholesky_interface.hpp.
The documentation for this struct was generated from the following file:
csparse_cholesky_interface.hpp