CasADi: casadi::OutputSX Class Reference
casadi::OutputSX Class Reference
#include <output_sx.hpp>
Detailed Description
Definition at line 62 of file output_sx.hpp.
Public Types
using weak_ref_type = WeakRefInternalSXElem
Public Member Functions
OutputSX (const SXElem &dep, int oind)
Constructor.
OutputSX ()
Empty constructor.
std::string class_name () const override
Get type name.
std::string print (const std::string &arg1, const std::string &arg2) const override
Print expression.
~OutputSX () override
Destructor.
casadi_int op () const override
Get the operation.
casadi_int n_dep () const override
Number of dependencies.
const SXElem & dep (casadi_int i) const override
get the reference of a dependency
SXElem & dep (casadi_int i) override
get the reference of a child
bool is_output () const override
Is the node an output node?
casadi_int which_output () const override
Get the index of evaluation output.
void serialize_node (SerializingStream &s) const override
virtual const std::string & name () const
virtual Function which_function () const
Get called function.
virtual bool is_equal (const SXNode *node, casadi_int depth) const
Check if two nodes are equivalent up to a given depth.
virtual SXElem get_output (casadi_int oind) const
Get an output.
virtual bool is_smooth () const
Check if smooth.
virtual void disp (std::ostream &stream, bool more) const
print
void can_inline (std::map< const SXNode *, casadi_int > &nodeind) const
Find out which nodes can be inlined.
std::string print_compact (std::map< const SXNode *, casadi_int > &nodeind, std::vector< std::string > &intermed) const
Print compact.
bool marked () const
void mark () const
SXElem shared_from_this ()
Get a shared object from the current internal object.
const SXElem shared_from_this () const
Get a shared object from the current internal object.
void serialize (SerializingStream &s) const
Serialize an object.
casadi_int getCount () const
Get the reference count.
std::string debug_repr (const OutputSX *) const
GenericWeakRef< SharedSXElem, OutputSX > * weak ()
Get a weak reference to the object.
virtual bool is_constant () const
check properties of a node
virtual bool is_integer () const
check properties of a node
virtual bool is_symbolic () const
check properties of a node
virtual bool is_zero () const
check properties of a node
virtual bool is_op (casadi_int op) const
check properties of a node
virtual bool is_almost_zero (double tol) const
check properties of a node
virtual bool is_one () const
check properties of a node
virtual bool is_minus_one () const
check properties of a node
virtual bool is_nan () const
check properties of a node
virtual bool is_inf () const
check properties of a node
virtual bool is_minus_inf () const
check properties of a node
virtual bool is_call () const
check properties of a node
virtual bool has_output () const
check properties of a node
virtual double to_double () const
Get value of a constant node.
virtual casadi_int to_int () const
Get value of a constant node.
Static Public Member Functions
static std::vector< SXElem > split (const SXElem &e, casadi_int n)
static SXNode * deserialize (DeserializingStream &s)
static void safe_delete (SXNode *n)
Non-recursive delete.
Public Attributes
SXElem dep_
The dependencies of the node.
int oind_
Output index.
int temp
unsigned int count
Static Public Attributes
static casadi_int eq_depth_ = 1
static std::map< casadi_int, SXNode *(*)(DeserializingStream &)> deserialize_map
Protected Member Functions
void initSingleton ()
void destroySingleton ()
B shared_from_this ()
Get a shared object from the current internal object.
const B shared_from_this () const
Get a shared object from the current internal object.
Friends
class GenericShared< SharedSXElem, OutputSX >
class SharedObject
class GenericWeakRef< SharedSXElem, OutputSX >
class GenericSharedInternal< SharedSXElem, OutputSX >
class Memory
class UniversalNodeOwner
Member Typedef Documentation
weak_ref_type
using casadi::OutputSX::weak_ref_type = WeakRefInternalSXElem
Definition at line 73 of file output_sx.hpp.
Constructor & Destructor Documentation
OutputSX() [1/2]
casadi::OutputSX::OutputSX (const SXElem & dep, int oind) inline
Extra doc: https://github.com/casadi/casadi/wiki/L_294
Definition at line 78 of file output_sx.hpp.
                                           : dep_(dep), oind_(oind) {
     }
OutputSX() [2/2]
casadi::OutputSX::OutputSX () inline
Definition at line 82 of file output_sx.hpp.
                {
     }
~OutputSX()
casadi::OutputSX::~OutputSX () inline override
Extra doc: https://github.com/casadi/casadi/wiki/L_297
Definition at line 99 of file output_sx.hpp.
{
       safe_delete(dep_.assignNoDelete(casadi_limits<SXElem>::nan));
     }
Member Function Documentation
can_inline()
void casadi::SXNode::can_inline (std::map< const SXNode *, casadi_int > & nodeind) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_a6
Definition at line 113 of file sx_node.cpp.
{
     // Add or mark node in map
     std::map<const SXNode*, casadi_int>::iterator it=nodeind.find(this);
     if (it==nodeind.end()) {
       // First time encountered, mark inlined
       nodeind.insert(it, std::make_pair(this, 0));
       // Handle dependencies with recursion
       for (casadi_int i=0; i<n_dep(); ++i) {
         dep(i)->can_inline(nodeind);
       }
     } else if (it->second==0 && op()!=OP_PARAMETER) {
       // Node encountered before, do not inline (except if symbolic primitive)
       it->second = -1;
     }
   }
References casadi::SXNode::can_inline(), casadi::SXNode::dep(), casadi::SXNode::n_dep(), casadi::SXNode::op(), and casadi::OP_PARAMETER.
Referenced by casadi::SXNode::can_inline(), and casadi::SXNode::disp().
class_name()
std::string casadi::OutputSX::class_name () const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_9y
Implements casadi::SXNode.
Definition at line 87 of file output_sx.hpp.
 {return "OutputSX";}
debug_repr()
std::string casadi::GenericSharedInternal< SharedSXElem , OutputSX >::debug_repr (const OutputSX * i) const inherited
Definition at line 62 of file generic_shared_internal.hpp.
{
     // Note: i != this because of something something multiple inheritance
     return str( (casadi_int)(i)) + "/" + static_cast<const Internal*>(this)->class_name();
   }
dep() [1/2]
const SXElem& casadi::OutputSX::dep (casadi_int i) const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_29a
Reimplemented from casadi::SXNode.
Definition at line 116 of file output_sx.hpp.
 { return dep_; }
dep() [2/2]
SXElem& casadi::OutputSX::dep (casadi_int i) inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_a3
Reimplemented from casadi::SXNode.
Definition at line 117 of file output_sx.hpp.
 { return dep_; }
deserialize()
static SXNode* casadi::OutputSX::deserialize (DeserializingStream & s) inline static
Definition at line 152 of file output_sx.hpp.
{
       SXElem dep;
       int oind;
       s.unpack("OutputSX::dep", dep);
       s.unpack("OutputSX::oind", oind);
       return new OutputSX(dep, oind);
     }
References casadi::DeserializingStream::unpack().
destroySingleton()
void casadi::GenericSharedInternal< SharedSXElem , OutputSX >::destroySingleton () inline protected inherited
Called in the destructor of singletons
Definition at line 77 of file generic_shared_internal.hpp.
{
       static_cast<Internal*>(this)->count--;
     }
disp()
void casadi::SXNode::disp (std::ostream & stream, bool more) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_a5
Definition at line 88 of file sx_node.cpp.
{
     // Find out which noded can be inlined
     std::map<const SXNode*, casadi_int> nodeind;
     can_inline(nodeind);
     // Print expression
     std::vector<std::string> intermed;
     std::string s = print_compact(nodeind, intermed);
     // Print intermediate expressions
     for (casadi_int i=0; i<intermed.size(); ++i)
       stream << "@" << (i+1) << "=" << intermed[i] << ", ";
     // Print this
     stream << s;
   }
References casadi::SXNode::can_inline(), and casadi::SXNode::print_compact().
Referenced by casadi::SXElem::disp().
get_output()
SXElem casadi::SXNode::get_output (casadi_int oind) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_293
Reimplemented in casadi::CallSX.
Definition at line 227 of file sx_node.cpp.
{
     casadi_assert(oind==0, "Output index out of bounds");
     return shared_from_this();
   }
References casadi::SXNode::shared_from_this().
Referenced by casadi::SXElem::get_output().
getCount()
casadi_int casadi::GenericSharedInternal< SharedSXElem , OutputSX >::getCount inherited
Definition at line 60 of file generic_shared_internal.hpp.
{
     return static_cast<const Internal*>(this)->count;
   }
has_output()
virtual bool casadi::SXNode::has_output () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::CallSX.
Definition at line 82 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::has_output().
initSingleton()
void casadi::GenericSharedInternal< SharedSXElem , OutputSX >::initSingleton () inline protected inherited
Called in the constructor of singletons to avoid that the counter reaches zero
Definition at line 71 of file generic_shared_internal.hpp.
{
       casadi_assert_dev(static_cast<Internal*>(this)->count==0);
       static_cast<Internal*>(this)->count++;
     }
is_almost_zero()
virtual bool casadi::SXNode::is_almost_zero (double tol) const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::ZeroSX, and casadi::RealtypeSX.
Definition at line 74 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::is_almost_zero().
is_call()
virtual bool casadi::SXNode::is_call () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::CallSX.
Definition at line 80 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::is_call().
is_constant()
virtual bool casadi::SXNode::is_constant () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::ConstantSX.
Definition at line 69 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::binary(), casadi::SXFunction::init(), and casadi::SXElem::is_constant().
is_equal()
bool casadi::SXNode::is_equal (const SXNode * node, casadi_int depth) const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_a0
Reimplemented in casadi::UnarySX, casadi::ConstantSX, and casadi::BinarySX.
Definition at line 72 of file sx_node.cpp.
{
     return false;
   }
Referenced by casadi::SXElem::is_equal().
is_inf()
virtual bool casadi::SXNode::is_inf () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::InfSX.
Definition at line 78 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::is_inf().
is_integer()
virtual bool casadi::SXNode::is_integer () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::MinusOneSX, casadi::OneSX, casadi::ZeroSX, and casadi::IntegerSX.
Definition at line 70 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::binary(), and casadi::SXElem::is_integer().
is_minus_inf()
virtual bool casadi::SXNode::is_minus_inf () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::MinusInfSX.
Definition at line 79 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::is_minus_inf().
is_minus_one()
virtual bool casadi::SXNode::is_minus_one () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::MinusOneSX.
Definition at line 76 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::binary(), and casadi::SXElem::is_minus_one().
is_nan()
virtual bool casadi::SXNode::is_nan () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::NanSX.
Definition at line 77 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::is_nan().
is_one()
virtual bool casadi::SXNode::is_one () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::OneSX.
Definition at line 75 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::binary(), and casadi::SXElem::is_one().
is_op()
virtual bool casadi::SXNode::is_op (casadi_int op) const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::UnarySX, casadi::SymbolicSX, casadi::CallSX, and casadi::BinarySX.
Definition at line 73 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::is_op().
is_output()
bool casadi::OutputSX::is_output () const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_29d
Reimplemented from casadi::SXNode.
Definition at line 132 of file output_sx.hpp.
 { return true; }
is_smooth()
virtual bool casadi::SXNode::is_smooth () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_a4
Reimplemented in casadi::UnarySX, and casadi::BinarySX.
Definition at line 144 of file sx_node.hpp.
 { return true; }
is_symbolic()
virtual bool casadi::SXNode::is_symbolic () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::SymbolicSX.
Definition at line 71 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXFunction::init(), and casadi::SXElem::is_symbolic().
is_zero()
virtual bool casadi::SXNode::is_zero () const inline virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9w
Reimplemented in casadi::ZeroSX.
Definition at line 72 of file sx_node.hpp.
 { return false; }
Referenced by casadi::SXElem::binary(), and casadi::SXElem::is_zero().
mark()
void casadi::SXNode::mark () const inherited
Definition at line 109 of file sx_node.cpp.
{
     temp = -temp-1;
   }
References casadi::SXNode::temp.
marked()
bool casadi::SXNode::marked () const inherited
Definition at line 105 of file sx_node.cpp.
{
     return temp<0;
   }
References casadi::SXNode::temp.
n_dep()
casadi_int casadi::OutputSX::n_dep () const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_299
Reimplemented from casadi::SXNode.
Definition at line 111 of file output_sx.hpp.
 { return 1;}
name()
const std::string & casadi::SXNode::name () const virtual inherited
Reimplemented in casadi::SymbolicSX.
Definition at line 76 of file sx_node.cpp.
{
     casadi_error("'name' not defined for " + class_name());
   }
References casadi::SXNode::class_name().
Referenced by casadi::SXElem::name().
op()
casadi_int casadi::OutputSX::op () const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_298
Implements casadi::SXNode.
Definition at line 106 of file output_sx.hpp.
 { return -1;}
print()
std::string casadi::OutputSX::print (const std::string & arg1, const std::string & arg2) const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_296
Implements casadi::SXNode.
Definition at line 92 of file output_sx.hpp.
{
       return arg1 + "{" + str(oind_) + "}";
     }
References casadi::str().
print_compact()
std::string casadi::SXNode::print_compact (std::map< const SXNode *, casadi_int > & nodeind, std::vector< std::string > & intermed) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_a7
Definition at line 130 of file sx_node.cpp.
{
     // Get reference to node index
     casadi_int& ind = nodeind[this];
     // If positive, already in intermediate expressions
     if (ind>0) {
       std::stringstream ss;
       ss << "@" << ind;
       return ss.str();
     }
     std::string s;
     if (op()==OP_CALL) {
       const Function& f = which_function();
       // Get expressions for dependencies
       s = which_function().name() + "(";
       casadi_int k = 0;
       for (casadi_int i=0; i<f.n_in(); ++i) {
         if (f.nnz_in(i)>1) s += "[";
         for (casadi_int j=0; j<f.nnz_in(i); ++j) {
           s += dep(k++)->print_compact(nodeind, intermed);
           if (j<f.nnz_in(i)-1) s+=",";
         }
         if (f.nnz_in(i)>1) s += "]";
         if (i<f.n_in()-1) s+=",";
       }
       s += ")";
     } else {
       // Get expressions for dependencies
       std::string arg[2];
       for (casadi_int i=0; i<n_dep(); ++i) {
         arg[i] = dep(i)->print_compact(nodeind, intermed);
       }
       // Get expression for this
       s = print(arg[0], arg[1]);
     }
     // Decide what to do with the expression
     if (ind==0) {
       // Inline expression
       return s;
     } else {
       // Add to list of intermediate expressions and return reference
       intermed.push_back(s);
       ind = intermed.size(); // For subsequent references
       std::stringstream ss;
       ss << "@" << ind;
       return ss.str();
     }
   }
References casadi::SXNode::dep(), casadi::SXNode::n_dep(), casadi::Function::n_in(), casadi::Function::name(), casadi::Function::nnz_in(), casadi::SXNode::op(), casadi::OP_CALL, casadi::SXNode::print(), casadi::SXNode::print_compact(), and casadi::SXNode::which_function().
Referenced by casadi::SXNode::disp(), and casadi::SXNode::print_compact().
safe_delete()
void casadi::SXNode::safe_delete (SXNode * n) static inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_a9
Definition at line 184 of file sx_node.cpp.
{
     // Quick return if more owners
     if (n->count>0) return;
     // Delete straight away if it doesn't have any dependencies
     if (!n->n_dep()) {
       delete n;
       return;
     }
     // Stack of expressions to be deleted
     std::stack<SXNode*> deletion_stack;
     // Add the node to the deletion stack
     deletion_stack.push(n);
     // Process stack
     while (!deletion_stack.empty()) {
       // Top element
       SXNode *t = deletion_stack.top();
       // Check if the top element has dependencies with dependencies
       bool added_to_stack = false;
       for (casadi_int c2=0; c2<t->n_dep(); ++c2) { // for all dependencies of the dependency
         // Get the node of the dependency of the top element
         // and remove it from the smart pointer
         SXNode *n2 = t->dep(c2).assignNoDelete(casadi_limits<SXElem>::nan);
         // Check if this is the only reference to the element
         if (n2->count == 0) {
           // Check if unary or binary
           if (!n2->n_dep()) {
             // Delete straight away if not binary
             delete n2;
           } else {
             // Add to deletion stack
             deletion_stack.push(n2);
             added_to_stack = true;
           }
         }
       }
       // Delete and pop from stack if nothing added to the stack
       if (!added_to_stack) {
         delete deletion_stack.top();
         deletion_stack.pop();
       }
     }
   }
References casadi::SXElem::assignNoDelete(), casadi::SXNode::count, casadi::SXNode::dep(), and casadi::SXNode::n_dep().
Referenced by casadi::BinarySX::~BinarySX(), and casadi::UnarySX::~UnarySX().
serialize()
void casadi::SXNode::serialize (SerializingStream & s) const inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_aa
Definition at line 238 of file sx_node.cpp.
{
     s.pack("SXNode::op", op());
     serialize_node(s);
   }
References casadi::SXNode::op(), casadi::SerializingStream::pack(), and casadi::SXNode::serialize_node().
serialize_node()
void casadi::OutputSX::serialize_node (SerializingStream & s) const inline override virtual
Reimplemented from casadi::SXNode.
Definition at line 147 of file output_sx.hpp.
{
       s.pack("OutputSX::dep", dep_);
       s.pack("OutputSX::oind", oind_);
     }
References casadi::SerializingStream::pack().
shared_from_this() [1/4]
B casadi::GenericSharedInternal< SharedSXElem , OutputSX >::shared_from_this () inline protected inherited
Definition at line 83 of file generic_shared_internal.hpp.
{
       casadi_assert_dev(B::test_cast(static_cast<Internal*>(this)));
       B ret;
       ret.own(static_cast<Internal*>(this));
       return ret;
     }
shared_from_this() [2/4]
SXElem casadi::SXNode::shared_from_this () inherited
Definition at line 261 of file sx_node.cpp.
{
     return SXElem(this, false);
   }
References casadi::SXNode::SXElem.
Referenced by casadi::SXNode::get_output(), and casadi::CallSX::get_output().
shared_from_this() [3/4]
const B casadi::GenericSharedInternal< SharedSXElem , OutputSX >::shared_from_this () const inline protected inherited
Definition at line 92 of file generic_shared_internal.hpp.
{
       casadi_assert_dev(B::test_cast(static_cast<const Internal*>(this)));
       B ret;
       ret.own(const_cast<Internal*>(static_cast<const Internal*>(this)));
       return ret;
     }
shared_from_this() [4/4]
const SXElem casadi::SXNode::shared_from_this () const inherited
Definition at line 265 of file sx_node.cpp.
{
     return SXElem(const_cast<SXNode*>(this), false);
   }
References casadi::SXNode::SXElem.
split()
static std::vector<SXElem> casadi::OutputSX::split (const SXElem & e, casadi_int n) inline static
Definition at line 139 of file output_sx.hpp.
{
       std::vector<SXElem> ret(n);
       for (casadi_int i=0;i<n;++i) {
         ret[i] = e.get_output(i);
       }
       return ret;
     }
References casadi::SXElem::get_output().
Referenced by casadi::SXElem::call(), and casadi::SXFunction::eval_sx().
to_double()
double casadi::SXNode::to_double () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9x
Reimplemented in casadi::ConstantSX, casadi::NanSX, casadi::MinusInfSX, casadi::InfSX, casadi::MinusOneSX, casadi::OneSX, casadi::ZeroSX, casadi::IntegerSX, and casadi::RealtypeSX.
Definition at line 56 of file sx_node.cpp.
{
     return std::numeric_limits<double>::quiet_NaN();
   }
Referenced by casadi::SXElem::binary(), and casadi::SXFunction::init().
to_int()
casadi_int casadi::SXNode::to_int () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_9x
Reimplemented in casadi::MinusOneSX, casadi::OneSX, casadi::ZeroSX, casadi::IntegerSX, and casadi::RealtypeSX.
Definition at line 60 of file sx_node.cpp.
{
     casadi_error("to_int not defined for " + class_name());
   }
References casadi::SXNode::class_name().
Referenced by casadi::SXElem::binary().
weak()
GenericWeakRef< SharedSXElem , OutputSX > * casadi::GenericSharedInternal< SharedSXElem , OutputSX >::weak inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_1ai
Definition at line 67 of file generic_shared_internal.hpp.
{
     if (weak_ref_==nullptr) {
       weak_ref_ = new GenericWeakRef<Shared, Internal>(static_cast<Internal*>(this));
     }
     return weak_ref_;
   }
which_function()
Function casadi::SXNode::which_function () const virtual inherited
Extra doc: https://github.com/casadi/casadi/wiki/L_291
Reimplemented in casadi::CallSX.
Definition at line 64 of file sx_node.cpp.
{
     casadi_error("'which_function' not defined for class " + class_name());
   }
References casadi::SXNode::class_name().
Referenced by casadi::SXNode::print_compact(), and casadi::SXElem::which_function().
which_output()
casadi_int casadi::OutputSX::which_output () const inline override virtual
Extra doc: https://github.com/casadi/casadi/wiki/L_29e
Reimplemented from casadi::SXNode.
Definition at line 137 of file output_sx.hpp.
 { return oind_; }
Friends And Related Function Documentation
GenericShared< SharedSXElem, OutputSX >
friend class GenericShared< SharedSXElem, OutputSX > friend
Definition at line 56 of file output_sx.hpp.
GenericSharedInternal< SharedSXElem, OutputSX >
friend class GenericSharedInternal< SharedSXElem, OutputSX > friend
Definition at line 66 of file output_sx.hpp.
GenericWeakRef< SharedSXElem, OutputSX >
friend class GenericWeakRef< SharedSXElem, OutputSX > friend
Definition at line 66 of file output_sx.hpp.
Memory
friend class Memory friend
Definition at line 69 of file output_sx.hpp.
SharedObject
friend class SharedObject friend
Definition at line 66 of file output_sx.hpp.
UniversalNodeOwner
friend class UniversalNodeOwner friend
Definition at line 70 of file output_sx.hpp.
Member Data Documentation
count
unsigned int casadi::SXNode::count inherited
Definition at line 197 of file sx_node.hpp.
Referenced by casadi::SXElem::assignNoDelete(), casadi::SXElem::operator=(), casadi::SXNode::safe_delete(), casadi::SXElem::SXElem(), casadi::SXNode::SXNode(), casadi::UniversalNodeOwner::UniversalNodeOwner(), casadi::InfSX::~InfSX(), casadi::MinusInfSX::~MinusInfSX(), casadi::MinusOneSX::~MinusOneSX(), casadi::NanSX::~NanSX(), casadi::OneSX::~OneSX(), casadi::SXElem::~SXElem(), casadi::SXNode::~SXNode(), and casadi::ZeroSX::~ZeroSX().
dep_
SXElem casadi::OutputSX::dep_
Extra doc: https://github.com/casadi/casadi/wiki/L_29b
Definition at line 122 of file output_sx.hpp.
deserialize_map
std::map< casadi_int, SXNode *(*)(DeserializingStream &)> casadi::SXNode::deserialize_map static inherited
Initial value:
= {
    {OP_PARAMETER, SymbolicSX::deserialize},
    {OP_CONST, ConstantSX_deserialize},
    {OP_CALL, CallSX::deserialize},
    {-1, OutputSX::deserialize}}
Definition at line 209 of file sx_node.hpp.
Referenced by casadi::SXNode::deserialize().
eq_depth_
casadi_int casadi::SXNode::eq_depth_ = 1 static inherited
Definition at line 179 of file sx_node.hpp.
Referenced by casadi::SXElem::binary(), casadi::Matrix< Scalar >::get_max_depth(), casadi::SXElem::is_doubled(), and casadi::Matrix< Scalar >::set_max_depth().
oind_
int casadi::OutputSX::oind_
Extra doc: https://github.com/casadi/casadi/wiki/L_29c
Definition at line 127 of file output_sx.hpp.
temp
int casadi::SXNode::temp mutable inherited
Temporary variables to be used in user algorithms like sorting, the user is responsible of making sure that use is thread-safe The variable is initialized to zero
Definition at line 191 of file sx_node.hpp.
Referenced by casadi::SXFunction::init(), casadi::SXNode::mark(), casadi::SXNode::marked(), and casadi::SXNode::SXNode().
The documentation for this class was generated from the following file:
output_sx.hpp